VW: block.h File Reference
block.h File Reference
Functions
void vnl_block_raise_exception (char const *FILE, int LINE, char const *why)
template<class T >
T vnl_block_sum (T const x[], unsigned n)
return sum of elements.
template<class T >
T vnl_block_product (T const x[], unsigned n)
return product of elements.
template<class T >
T vnl_block_min_value (T const x[], unsigned n)
return smallest value.
template<class T >
T vnl_block_max_value (T const x[], unsigned n)
return largest value.
template<class T >
void vnl_block_copy (T const x[], T y[], unsigned n)
y[i] = x[i].
template<class T >
void vnl_block_reverse (T x[], unsigned n)
reverses sequence.
template<class T >
void vnl_block_scale (T a, T x[], unsigned n)
x[i] *= a.
template<class T >
void vnl_block_scale (T a, T const x[], T y[], unsigned n)
y[i] = a * x[i].
template<class T >
void vnl_block_add (T const x[], T y[], unsigned n)
y[i] += x[i].
template<class T >
void vnl_block_add (T const x[], T const y[], T z[], unsigned n)
z[i] = x[i] + y[i].
template<class T >
void vnl_block_sub (T const x[], T const y[], T z[], unsigned n)
z[i] = x[i] - y[i].
template<class T >
void vnl_block_mul (T const x[], T y[], unsigned n)
y[i] *= x[i].
template<class T >
void vnl_block_mul (T const x[], T const y[], T z[], unsigned n)
z[i] = x[i] * y[i].
template<class T >
void vnl_block_div (T const x[], T const y[], T z[], unsigned n)
z[i] = x[i] / y[i].
template<class T >
void vnl_block_negate (T const x[], T y[], unsigned n)
y[i] = -x[i].
template<class T >
void vnl_block_invert (T const x[], T y[], unsigned n)
y[i] = 1/x[i].
template<class T >
void vnl_block_axpy (T a, T const x[], T y[], unsigned n)
y[i] += a * x[i].
template<class T >
void vnl_block_fill (T x[], unsigned n, T value)
x[i] = v.
Detailed Description
Author:
fsm@robots.ox.ac.uk
Function Documentation
template<class T > void vnl_block_add (T const x[], T const y[], T z[], unsigned n) [inline]
z[i] = x[i] + y[i].
template<class T > void vnl_block_add (T const x[], T y[], unsigned n) [inline]
y[i] += x[i].
template<class T > void vnl_block_axpy (T a, T const x[], T y[], unsigned n) [inline]
y[i] += a * x[i].
template<class T > void vnl_block_copy (T const x[], T y[], unsigned n) [inline]
y[i] = x[i].
template<class T > void vnl_block_div (T const x[], T const y[], T z[], unsigned n) [inline]
z[i] = x[i] / y[i].
template<class T > void vnl_block_fill (T x[], unsigned n, T value) [inline]
x[i] = v.
template<class T > void vnl_block_invert (T const x[], T y[], unsigned n) [inline]
y[i] = 1/x[i].
template<class T > T vnl_block_max_value (T const x[], unsigned n) [inline]
return largest value.
References vnl_block_raise_exception().
template<class T > T vnl_block_min_value (T const x[], unsigned n) [inline]
return smallest value.
References vnl_block_raise_exception().
template<class T > void vnl_block_mul (T const x[], T const y[], T z[], unsigned n) [inline]
z[i] = x[i] * y[i].
template<class T > void vnl_block_mul (T const x[], T y[], unsigned n) [inline]
y[i] *= x[i].
template<class T > void vnl_block_negate (T const x[], T y[], unsigned n) [inline]
y[i] = -x[i].
template<class T > T vnl_block_product (T const x[], unsigned n) [inline]
return product of elements.
void vnl_block_raise_exception (char const * FILE, int LINE, char const * why)
Referenced by vnl_block_max_value(), and vnl_block_min_value().
template<class T > void vnl_block_reverse (T x[], unsigned n) [inline]
reverses sequence.
template<class T > void vnl_block_scale (T a, T const x[], T y[], unsigned n) [inline]
y[i] = a * x[i].
template<class T > void vnl_block_scale (T a, T x[], unsigned n) [inline]
x[i] *= a.
template<class T > void vnl_block_sub (T const x[], T const y[], T z[], unsigned n) [inline]
z[i] = x[i] - y[i].
template<class T > T vnl_block_sum (T const x[], unsigned n) [inline]
return sum of elements.