VW: VW::ZNPatch Class Reference
VW::ZNPatch Class Reference
#include <patchfeature.h>
Public Member Functions
ZNPatch (unsigned int size)
ZNPatch (const ZNPatch &p)
~ZNPatch ()
ZNPatch & operator= (const ZNPatch &p)
unsigned int GetSize () const
float GetValue (unsigned int x, unsigned int y) const
void SetValue (unsigned int x, unsigned int y, float val)
void SetData (unsigned int size, float *new_values)
float * operator[] (int row)
const float * operator[] (int row) const
float GetMaxValue () const
float GetMinValue () const
float GetMatchScore (const VW::ZNPatch &p2) const
void Normalise (bool weighted=false)
Use the (raw) values stored in the patch and calculate the zero-normalised values.
bool WriteASCII (std::ostream &s) const
bool WriteBinary (std::ostream &s) const
bool ReadBinary (std::istream &s)
Constructor & Destructor Documentation
VW::ZNPatch::ZNPatch (unsigned int size)
VW::ZNPatch::ZNPatch (const ZNPatch & p)
VW::ZNPatch::~ZNPatch ()
Member Function Documentation
float VW::ZNPatch::GetMatchScore (const VW::ZNPatch & p2) const [inline]
Referenced by VW::PatchFeature::GetMatchScore().
float VW::ZNPatch::GetMaxValue () const
float VW::ZNPatch::GetMinValue () const
unsigned int VW::ZNPatch::GetSize () const
Referenced by VW::PatchFeature::GetPatchSize().
float VW::ZNPatch::GetValue (unsigned int x, unsigned int y) const
void VW::ZNPatch::Normalise (bool weighted = false)
Use the (raw) values stored in the patch and calculate the zero-normalised values.
Optionally the values can be weighted using a Gaussian to emphasize the central region - this adds some computation time but can (supposedly) improve recall rates.
References std::sqrt(), and _pf_GaussianMask::weight.
VW::ZNPatch & VW::ZNPatch::operator= (const ZNPatch & p)
const float * VW::ZNPatch::operator[] (int row) const
float * VW::ZNPatch::operator[] (int row)
bool VW::ZNPatch::ReadBinary (std::istream & s)
Referenced by VW::PatchFeature::ReadBinary().
void VW::ZNPatch::SetData (unsigned int size, float * new_values)
void VW::ZNPatch::SetValue (unsigned int x, unsigned int y, float val)
bool VW::ZNPatch::WriteASCII (std::ostream & s) const
Referenced by VW::operator<<().
bool VW::ZNPatch::WriteBinary (std::ostream & s) const
Referenced by VW::PatchFeature::WriteBinary().
The documentation for this class was generated from the following files:
patchfeature.h
patchfeature.cpp