VW: VW::YorickGTK Class Reference
VW::YorickGTK Class Reference
#include <yorickgtk.h>
Public Types
enum YorickAxis { YORICK_PAN = YorickPMAC::PMAC_PAN, YORICK_TILT = YorickPMAC::PMAC_TILT, YORICK_VERGELEFT = YorickPMAC::PMAC_VERGELEFT, YORICK_VERGERIGHT = YorickPMAC::PMAC_VERGERIGHT }
Public Member Functions
YorickGTK (VW::InterfaceType t=VW::INTERFACE_AS_BUTTONWINDOW)
~YorickGTK ()
void CreateForm ()
void UpdateForm ()
virtual void i_Activate ()
Switch on/off yorick.
virtual void i_Recentre ()
Slowly move back to all axes at zero.
virtual void i_SetOrigin ()
Set the current position as zero.
virtual void i_VergeLeft ()
virtual void i_VergeRight ()
virtual void i_Elevate ()
virtual void i_Pan ()
virtual int Demand (float p, float t, float vl, float vr)
virtual int DemandPan (float p)
virtual int DemandTilt (float t)
virtual int DemandPanTilt (float p, float t)
virtual int DemandVergeLeft (float vl)
virtual int DemandVergeRight (float vr)
virtual int DemandVerge (float vl, float vr)
void LoadParameterFile (std::string paramfile=".param")
void SaveParameterFile (std::string paramfile=".param")
void Show (void)
void Hide (void)
void Quit (void)
VW::InterfaceType GetType (void)
bool SetActive (bool state)
void SetVergeLeftActive (bool state)
void SetVergeRightActive (bool state)
void SetTiltActive (bool state)
void SetPanActive (bool state)
bool GetActive (void)
bool GetVergeLeftActive (void)
bool GetVergeRightActive (void)
bool GetTiltActive (void)
bool GetPanActive (void)
int SlowRecentre (void)
int SlowDemand (float p, float t, float vl, float vr)
int WaitForCompletion (int=MAX_COUNTS, float=ODOMETRY_ACCEPT)
int Homez (void)
int HomezOneAxis (YorickAxis axis)
int GetPosition (float *p, float *t, float *vl, float *vr)
int GetPositionAndStore (float *p, float *t, float *vl, float *vr)
int GetVelocity (float *vp, float *vt, float *vvl, float *vvr)
float GetInstantVergeLeft (void)
float GetInstantVergeRight (void)
float GetInstantTilt (void)
float GetInstantPan (void)
float GetVergeLeft (void)
float GetVergeRight (void)
float GetTilt (void)
float GetPan (void)
void GetVergeLeftLimits (float *minv, float *maxv)
void GetVergeRightLimits (float *minv, float *maxv)
void GetTiltLimits (float *mint, float *maxt)
void GetPanLimits (float *minp, float *maxp)
int GetHistoricPosition (struct timeval time, float &p, float &t, float &vl, float &vr)
int GetHistoricPositionAndUncertainty (struct timeval time, float &p, float &t, float &vl, float &vr, float &delta_p, float &delta_t, float &delta_vl, float &delta_vr)
void ShowOdometryHistory (void)
void GetOdometryHistory (std::vector< timeval > &time, std::vector< double > &pan_history, std::vector< double > &tilt_history, std::vector< double > &vergeleft_history, std::vector< double > &vergeright_history)
void FlushHistory (void)
int IsPMACOpen ()
int ReadState (void)
Static Public Attributes
static const float PAN_LIMIT = 90.0
static const float TILT_LIMIT = 60.0
static const float VLEFT_LIMIT = 45.0
static const float VRIGHT_LIMIT = 45.0
Protected Member Functions
void LoadStart ()
void LoadOK ()
void SaveStart ()
void SaveOK ()
void FileCancel ()
virtual void InitButtonWindow ()
virtual void InitButtonWindow (unsigned int width, unsigned int height)
virtual void InitWidget ()
Protected Attributes
bool allow_callbacks
SigC::Signal1< void, std::string > LoadEvent
SigC::Signal1< void, std::string > SaveEvent
YorickGTKWidget * my_widget
Gtk::Window * my_window
VW::InterfaceType my_type
std::string my_name
Gtk::FileSelection * file_selector
int seq_no
float pan
float tilt
float vleft
float vright
YorickPMAC pmac
Member Enumeration Documentation
enum VW::Yorick::YorickAxis [inherited]
Enumerator:
YORICK_PAN
YORICK_TILT
YORICK_VERGELEFT
YORICK_VERGERIGHT
Constructor & Destructor Documentation
YorickGTK::YorickGTK (VW::InterfaceType t = VW::INTERFACE_AS_BUTTONWINDOW)
References allow_callbacks, VW::InterfaceGTK< YorickGTKWidget >::InitButtonWindow(), VW::YorickGTKWidget::InitForm(), VW::InterfaceGTK< YorickGTKWidget >::InitWidget(), VW::INTERFACE_AS_BUTTONWINDOW, VW::InterfaceGTK< YorickGTKWidget >::my_name, VW::InterfaceGTK< YorickGTKWidget >::my_type, and VW::InterfaceGTK< YorickGTKWidget >::my_widget.
YorickGTK::~YorickGTK ()
Member Function Documentation
void VW::YorickGTK::CreateForm ()
int YorickGTK::Demand (float p, float t, float vl, float vr) [virtual]
Reimplemented from VW::Yorick.
int YorickGTK::DemandPan (float p) [virtual]
Reimplemented from VW::Yorick.
References allow_callbacks, VW::YorickGTKWidget::drag_pad, VW::InterfaceGTK< YorickGTKWidget >::my_widget, VW::YorickGTKWidget::pan_spinner, and VW::YorickDragPad::Redraw().
Referenced by i_Pan().
int YorickGTK::DemandPanTilt (float p, float t) [virtual]
Reimplemented from VW::Yorick.
References allow_callbacks, VW::YorickGTKWidget::drag_pad, VW::YorickGTKWidget::elevation_spinner, VW::InterfaceGTK< YorickGTKWidget >::my_widget, VW::YorickGTKWidget::pan_spinner, and VW::YorickDragPad::Redraw().
int YorickGTK::DemandTilt (float t) [virtual]
Reimplemented from VW::Yorick.
References allow_callbacks, VW::YorickGTKWidget::drag_pad, VW::YorickGTKWidget::elevation_spinner, VW::InterfaceGTK< YorickGTKWidget >::my_widget, and VW::YorickDragPad::Redraw().
Referenced by i_Elevate().
int YorickGTK::DemandVerge (float vl, float vr) [virtual]
Reimplemented from VW::Yorick.
References allow_callbacks, VW::YorickGTKWidget::drag_pad, VW::InterfaceGTK< YorickGTKWidget >::my_widget, VW::YorickDragPad::Redraw(), VW::YorickGTKWidget::vergeleft_spinner, and VW::YorickGTKWidget::vergeright_spinner.
int YorickGTK::DemandVergeLeft (float vl) [virtual]
Reimplemented from VW::Yorick.
Referenced by i_VergeLeft().
int YorickGTK::DemandVergeRight (float vr) [virtual]
Reimplemented from VW::Yorick.
References allow_callbacks, VW::YorickGTKWidget::drag_pad, VW::InterfaceGTK< YorickGTKWidget >::my_widget, VW::YorickDragPad::Redraw(), and VW::YorickGTKWidget::vergeright_spinner.
Referenced by i_VergeRight().
void VW::InterfaceGTK< YorickGTKWidget >::FileCancel () [inline, protected, inherited]
void VW::Yorick::FlushHistory (void) [inherited]
References YorickPMAC::GetMode(), YorickPMAC::GetOdometry(), VW::Yorick::pmac, YorickPMAC::PMAC_ON, and VW::Yorick::seq_no.
Referenced by VW::Yorick::SetActive().
bool VW::Yorick::GetActive (void) [inline, inherited]
Referenced by i_Activate().
int VW::Yorick::GetHistoricPosition (struct timeval time, float & p, float & t, float & vl, float & vr) [inherited]
References VW::Yorick::GetHistoricPositionAndUncertainty().
int VW::Yorick::GetHistoricPositionAndUncertainty (struct timeval time, float & p, float & t, float & vl, float & vr, float & delta_p, float & delta_t, float & delta_vl, float & delta_vr) [inherited]
References YorickPMAC::GetMode(), YorickPMAC::GetOdometry(), VW::Yorick::pmac, YorickPMAC::PMAC_ON, VW::Yorick::seq_no, and YORICK_ODOMETRY_HISTORY_LENGTH.
Referenced by VW::Yorick::GetHistoricPosition().
float VW::Yorick::GetInstantPan (void) [inherited]
References VW::Yorick::GetPosition().
float VW::Yorick::GetInstantTilt (void) [inherited]
References VW::Yorick::GetPosition().
float VW::Yorick::GetInstantVergeLeft (void) [inherited]
References VW::Yorick::GetPosition().
float VW::Yorick::GetInstantVergeRight (void) [inherited]
References VW::Yorick::GetPosition().
void VW::Yorick::GetOdometryHistory (std::vector< timeval > & time, std::vector< double > & pan_history, std::vector< double > & tilt_history, std::vector< double > & vergeleft_history, std::vector< double > & vergeright_history) [inherited]
float VW::Yorick::GetPan (void) [inline, inherited]
References VW::Yorick::pan.
Referenced by VW::YorickDragPad::Redraw(), and UpdateForm().
bool VW::Yorick::GetPanActive (void) [inline, inherited]
void VW::Yorick::GetPanLimits (float * minp, float * maxp) [inline, inherited]
References VW::Yorick::PAN_LIMIT.
Referenced by VW::YorickDragPad::Redraw().
int VW::Yorick::GetPosition (float * p, float * t, float * vl, float * vr) [inherited]
References YorickPMAC::GetMode(), YorickPMAC::GetOdometry(), VW::Yorick::pmac, YorickPMAC::PMAC_ON, and VW::Yorick::seq_no.
Referenced by VW::Yorick::GetInstantPan(), VW::Yorick::GetInstantTilt(), VW::Yorick::GetInstantVergeLeft(), VW::Yorick::GetInstantVergeRight(), and VW::Yorick::WaitForCompletion().
int VW::Yorick::GetPositionAndStore (float * p, float * t, float * vl, float * vr) [inherited]
References YorickPMAC::GetMode(), YorickPMAC::GetOdometry(), VW::Yorick::pmac, YorickPMAC::PMAC_ON, and VW::Yorick::seq_no.
float VW::Yorick::GetTilt (void) [inline, inherited]
References VW::Yorick::tilt.
Referenced by VW::YorickDragPad::Redraw(), and UpdateForm().
bool VW::Yorick::GetTiltActive (void) [inline, inherited]
void VW::Yorick::GetTiltLimits (float * mint, float * maxt) [inline, inherited]
References VW::Yorick::TILT_LIMIT.
Referenced by VW::YorickDragPad::Redraw().
VW::InterfaceType VW::InterfaceGTK< YorickGTKWidget >::GetType (void) [inline, inherited]
int VW::Yorick::GetVelocity (float * vp, float * vt, float * vvl, float * vvr) [inherited]
References YorickPMAC::GetMode(), YorickPMAC::GetVelocity(), VW::Yorick::pmac, YorickPMAC::PMAC_ON, and VW::Yorick::seq_no.
Referenced by VW::Yorick::WaitForCompletion().
float VW::Yorick::GetVergeLeft (void) [inline, inherited]
References VW::Yorick::vleft.
Referenced by VW::YorickDragPad::Redraw(), and UpdateForm().
bool VW::Yorick::GetVergeLeftActive (void) [inline, inherited]
void VW::Yorick::GetVergeLeftLimits (float * minv, float * maxv) [inline, inherited]
References VW::Yorick::VLEFT_LIMIT.
Referenced by VW::YorickDragPad::Redraw().
float VW::Yorick::GetVergeRight (void) [inline, inherited]
References VW::Yorick::vright.
Referenced by VW::YorickDragPad::Redraw(), and UpdateForm().
bool VW::Yorick::GetVergeRightActive (void) [inline, inherited]
void VW::Yorick::GetVergeRightLimits (float * minv, float * maxv) [inline, inherited]
References VW::Yorick::VRIGHT_LIMIT.
Referenced by VW::YorickDragPad::Redraw().
void VW::InterfaceGTK< YorickGTKWidget >::Hide (void) [inline, inherited]
int VW::Yorick::Homez (void) [inherited]
References YorickPMAC::Demand(), YorickPMAC::GetMode(), VW::Yorick::pan, VW::Yorick::pmac, YorickPMAC::PMAC_ALL, YorickPMAC::PMAC_HOMEZ, YorickPMAC::PMAC_ON, VW::Yorick::seq_no, VW::Yorick::tilt, VW::Yorick::vleft, and VW::Yorick::vright.
Referenced by i_SetOrigin().
int VW::Yorick::HomezOneAxis (YorickAxis axis) [inherited]
References YorickPMAC::Demand(), YorickPMAC::GetMode(), VW::Yorick::pan, VW::Yorick::pmac, YorickPMAC::PMAC_HOMEZ, YorickPMAC::PMAC_ON, VW::Yorick::seq_no, VW::Yorick::tilt, VW::Yorick::vleft, VW::Yorick::vright, VW::Yorick::YORICK_PAN, VW::Yorick::YORICK_TILT, VW::Yorick::YORICK_VERGELEFT, and VW::Yorick::YORICK_VERGERIGHT.
void YorickGTK::i_Activate () [virtual]
Switch on/off yorick.
References VW::YorickGTKWidget::DisableForm(), VW::YorickGTKWidget::EnableForm(), VW::Yorick::GetActive(), VW::InterfaceGTK< YorickGTKWidget >::my_widget, and VW::Yorick::SetActive().
Referenced by VW::YorickGTKWidget::InitForm().
void YorickGTK::i_Elevate () [virtual]
References allow_callbacks, DemandTilt(), VW::YorickGTKWidget::drag_pad, VW::YorickGTKWidget::elevation_spinner, VW::InterfaceGTK< YorickGTKWidget >::my_widget, and VW::YorickDragPad::Redraw().
Referenced by VW::YorickGTKWidget::InitForm().
void YorickGTK::i_Pan () [virtual]
References allow_callbacks, DemandPan(), VW::YorickGTKWidget::drag_pad, VW::InterfaceGTK< YorickGTKWidget >::my_widget, VW::YorickGTKWidget::pan_spinner, and VW::YorickDragPad::Redraw().
Referenced by VW::YorickGTKWidget::InitForm().
void YorickGTK::i_Recentre () [virtual]
Slowly move back to all axes at zero.
References VW::Yorick::SlowRecentre(), and UpdateForm().
Referenced by VW::YorickGTKWidget::InitForm().
void YorickGTK::i_SetOrigin () [virtual]
Set the current position as zero.
References VW::Yorick::Homez(), and UpdateForm().
Referenced by VW::YorickGTKWidget::InitForm().
void YorickGTK::i_VergeLeft () [virtual]
References allow_callbacks, DemandVergeLeft(), VW::YorickGTKWidget::drag_pad, VW::InterfaceGTK< YorickGTKWidget >::my_widget, VW::YorickDragPad::Redraw(), and VW::YorickGTKWidget::vergeleft_spinner.
Referenced by VW::YorickGTKWidget::InitForm().
void YorickGTK::i_VergeRight () [virtual]
References allow_callbacks, DemandVergeRight(), VW::YorickGTKWidget::drag_pad, VW::InterfaceGTK< YorickGTKWidget >::my_widget, VW::YorickDragPad::Redraw(), and VW::YorickGTKWidget::vergeright_spinner.
Referenced by VW::YorickGTKWidget::InitForm().
virtual void VW::InterfaceGTK< YorickGTKWidget >::InitButtonWindow (unsigned int width, unsigned int height) [protected, virtual, inherited]
virtual void VW::InterfaceGTK< YorickGTKWidget >::InitButtonWindow () [protected, virtual, inherited]
Referenced by YorickGTK().
virtual void VW::InterfaceGTK< YorickGTKWidget >::InitWidget () [protected, virtual, inherited]
Referenced by YorickGTK().
int VW::Yorick::IsPMACOpen () [inherited]
References YorickPMAC::GetMode(), VW::Yorick::pmac, and YorickPMAC::PMAC_ON.
void VW::InterfaceGTK< YorickGTKWidget >::LoadOK () [inline, protected, inherited]
void VW::YorickGTK::LoadParameterFile (std::string paramfile = ".param") [inline]
void VW::InterfaceGTK< YorickGTKWidget >::LoadStart () [inline, protected, inherited]
void VW::InterfaceGTK< YorickGTKWidget >::Quit (void) [inline, inherited]
int VW::Yorick::ReadState (void) [inherited]
References YorickPMAC::GetState(), and VW::Yorick::pmac.
void VW::InterfaceGTK< YorickGTKWidget >::SaveOK () [inline, protected, inherited]
void VW::YorickGTK::SaveParameterFile (std::string paramfile = ".param") [inline]
void VW::InterfaceGTK< YorickGTKWidget >::SaveStart () [inline, protected, inherited]
bool VW::Yorick::SetActive (bool state) [inherited]
References YorickPMAC::Close(), VW::Yorick::FlushHistory(), YorickPMAC::GetMode(), YorickPMAC::Init(), VW::Yorick::pmac, YorickPMAC::PMAC_ON, and YorickPMAC::SetModePending().
Referenced by i_Activate().
void VW::Yorick::SetPanActive (bool state) [inline, inherited]
void VW::Yorick::SetTiltActive (bool state) [inline, inherited]
void VW::Yorick::SetVergeLeftActive (bool state) [inline, inherited]
void VW::Yorick::SetVergeRightActive (bool state) [inline, inherited]
void VW::InterfaceGTK< YorickGTKWidget >::Show (void) [inline, inherited]
void VW::Yorick::ShowOdometryHistory (void) [inherited]
References YORICK_ODOMETRY_HISTORY_LENGTH.
int VW::Yorick::SlowDemand (float p, float t, float vl, float vr) [inherited]
References VW::Yorick::Demand(), YorickPMAC::GetMode(), YorickPMAC::GetOdometry(), max, VW::Yorick::pan, VW::Yorick::pmac, YorickPMAC::PMAC_ON, VW::Yorick::seq_no, VW::Yorick::tilt, VW::Yorick::vleft, and VW::Yorick::vright.
Referenced by VW::Yorick::SlowRecentre().
int VW::Yorick::SlowRecentre (void) [inherited]
References VW::Yorick::SlowDemand().
Referenced by i_Recentre().
void YorickGTK::UpdateForm (void) [virtual]
Implements VW::InterfaceGTK< YorickGTKWidget >.
References allow_callbacks, VW::YorickGTKWidget::drag_pad, VW::YorickGTKWidget::elevation_spinner, VW::Yorick::GetPan(), VW::Yorick::GetTilt(), VW::Yorick::GetVergeLeft(), VW::Yorick::GetVergeRight(), VW::InterfaceGTK< YorickGTKWidget >::my_widget, VW::YorickGTKWidget::pan_spinner, VW::YorickDragPad::Redraw(), VW::YorickGTKWidget::vergeleft_spinner, and VW::YorickGTKWidget::vergeright_spinner.
Referenced by i_Recentre(), and i_SetOrigin().
int VW::Yorick::WaitForCompletion (int max_counts = MAX_COUNTS, float odometry_accept = ODOMETRY_ACCEPT) [inherited]
References VW::Yorick::GetPosition(), VW::Yorick::GetVelocity(), VW::Yorick::pan, VW::Yorick::tilt, VW::Yorick::vleft, and VW::Yorick::vright.
Member Data Documentation
bool VW::YorickGTK::allow_callbacks [protected]
Referenced by DemandPan(), DemandPanTilt(), DemandTilt(), DemandVerge(), DemandVergeRight(), i_Elevate(), i_Pan(), i_VergeLeft(), i_VergeRight(), UpdateForm(), and YorickGTK().
Gtk::FileSelection* VW::InterfaceGTK< YorickGTKWidget >::file_selector [protected, inherited]
SigC::Signal1<void,std::string> VW::InterfaceGTK< YorickGTKWidget >::LoadEvent [protected, inherited]
std::string VW::InterfaceGTK< YorickGTKWidget >::my_name [protected, inherited]
Referenced by YorickGTK().
VW::InterfaceType VW::InterfaceGTK< YorickGTKWidget >::my_type [protected, inherited]
Referenced by YorickGTK().
YorickGTKWidget * VW::InterfaceGTK< YorickGTKWidget >::my_widget [protected, inherited]
Referenced by DemandPan(), DemandPanTilt(), DemandTilt(), DemandVerge(), DemandVergeRight(), i_Activate(), i_Elevate(), i_Pan(), i_VergeLeft(), i_VergeRight(), UpdateForm(), and YorickGTK().
Gtk::Window* VW::InterfaceGTK< YorickGTKWidget >::my_window [protected, inherited]
float VW::Yorick::pan [protected, inherited]
Referenced by VW::Yorick::Demand(), VW::Yorick::DemandPan(), VW::Yorick::DemandPanTilt(), VW::Yorick::DemandTilt(), VW::Yorick::DemandVerge(), VW::Yorick::DemandVergeLeft(), VW::Yorick::DemandVergeRight(), VW::Yorick::GetPan(), VW::Yorick::Homez(), VW::Yorick::HomezOneAxis(), VW::Yorick::SlowDemand(), VW::Yorick::WaitForCompletion(), and VW::Yorick::Yorick().
const float VW::Yorick::PAN_LIMIT = 90.0 [static, inherited]
Referenced by VW::Yorick::Demand(), VW::Yorick::DemandPan(), VW::Yorick::DemandPanTilt(), VW::Yorick::GetPanLimits(), and VW::YorickGTKWidget::InitForm().
YorickPMAC VW::Yorick::pmac [protected, inherited]
Referenced by VW::Yorick::Demand(), VW::Yorick::DemandPan(), VW::Yorick::DemandPanTilt(), VW::Yorick::DemandTilt(), VW::Yorick::DemandVerge(), VW::Yorick::DemandVergeLeft(), VW::Yorick::DemandVergeRight(), VW::Yorick::FlushHistory(), VW::Yorick::GetHistoricPositionAndUncertainty(), VW::Yorick::GetPosition(), VW::Yorick::GetPositionAndStore(), VW::Yorick::GetVelocity(), VW::Yorick::Homez(), VW::Yorick::HomezOneAxis(), VW::Yorick::IsPMACOpen(), VW::Yorick::ReadState(), VW::Yorick::SetActive(), VW::Yorick::SlowDemand(), and VW::Yorick::~Yorick().
SigC::Signal1<void,std::string> VW::InterfaceGTK< YorickGTKWidget >::SaveEvent [protected, inherited]
int VW::Yorick::seq_no [protected, inherited]
Referenced by VW::Yorick::Demand(), VW::Yorick::DemandPan(), VW::Yorick::DemandPanTilt(), VW::Yorick::DemandTilt(), VW::Yorick::DemandVerge(), VW::Yorick::DemandVergeLeft(), VW::Yorick::DemandVergeRight(), VW::Yorick::FlushHistory(), VW::Yorick::GetHistoricPositionAndUncertainty(), VW::Yorick::GetPosition(), VW::Yorick::GetPositionAndStore(), VW::Yorick::GetVelocity(), VW::Yorick::Homez(), VW::Yorick::HomezOneAxis(), VW::Yorick::SlowDemand(), and VW::Yorick::Yorick().
float VW::Yorick::tilt [protected, inherited]
Referenced by VW::Yorick::Demand(), VW::Yorick::DemandPan(), VW::Yorick::DemandPanTilt(), VW::Yorick::DemandTilt(), VW::Yorick::DemandVerge(), VW::Yorick::DemandVergeLeft(), VW::Yorick::DemandVergeRight(), VW::Yorick::GetTilt(), VW::Yorick::Homez(), VW::Yorick::HomezOneAxis(), VW::Yorick::SlowDemand(), VW::Yorick::WaitForCompletion(), and VW::Yorick::Yorick().
const float VW::Yorick::TILT_LIMIT = 60.0 [static, inherited]
Referenced by VW::Yorick::Demand(), VW::Yorick::DemandPanTilt(), VW::Yorick::DemandTilt(), VW::Yorick::GetTiltLimits(), and VW::YorickGTKWidget::InitForm().
float VW::Yorick::vleft [protected, inherited]
Referenced by VW::Yorick::Demand(), VW::Yorick::DemandPan(), VW::Yorick::DemandPanTilt(), VW::Yorick::DemandTilt(), VW::Yorick::DemandVerge(), VW::Yorick::DemandVergeLeft(), VW::Yorick::DemandVergeRight(), VW::Yorick::GetVergeLeft(), VW::Yorick::Homez(), VW::Yorick::HomezOneAxis(), VW::Yorick::SlowDemand(), VW::Yorick::WaitForCompletion(), and VW::Yorick::Yorick().
const float VW::Yorick::VLEFT_LIMIT = 45.0 [static, inherited]
Referenced by VW::Yorick::Demand(), VW::Yorick::DemandVerge(), VW::Yorick::DemandVergeLeft(), VW::Yorick::GetVergeLeftLimits(), and VW::YorickGTKWidget::InitForm().
float VW::Yorick::vright [protected, inherited]
Referenced by VW::Yorick::Demand(), VW::Yorick::DemandPan(), VW::Yorick::DemandPanTilt(), VW::Yorick::DemandTilt(), VW::Yorick::DemandVerge(), VW::Yorick::DemandVergeLeft(), VW::Yorick::DemandVergeRight(), VW::Yorick::GetVergeRight(), VW::Yorick::Homez(), VW::Yorick::HomezOneAxis(), VW::Yorick::SlowDemand(), VW::Yorick::WaitForCompletion(), and VW::Yorick::Yorick().
const float VW::Yorick::VRIGHT_LIMIT = 45.0 [static, inherited]
Referenced by VW::Yorick::Demand(), VW::Yorick::DemandVerge(), VW::Yorick::DemandVergeRight(), VW::Yorick::GetVergeRightLimits(), and VW::YorickGTKWidget::InitForm().
The documentation for this class was generated from the following files:
yorickgtk.h
yorickgtk.cpp