VW: VW::RotationCentre Class Reference
VW::RotationCentre Class Reference
Little class for storing centre of rotation information.
#include <threedtoolglcommon.h>
Public Member Functions
RotationCentre (DrawingPosition &current_drawing_position)
Vector3D Centre () const
void Reset ()
void Include (const Vector3D &v0)
Change the rotation centre depending on a new point.
void IncludeCurrent ()
Include the current origin.
double XMax () const
double YMax () const
double ZMax () const
double XMin () const
double YMin () const
double ZMin () const
Protected Attributes
Vector3D centre
double xmin
double xmax
double ymin
double ymax
double zmin
double zmax
bool initialised
DrawingPosition & drawing_position
Detailed Description
Little class for storing centre of rotation information.
Store Min, Max x, y, z of all objects plotted (defining a box containing everything). Centre of rotation is the centre of this box.
Constructor & Destructor Documentation
RotationCentre::RotationCentre (DrawingPosition & current_drawing_position)
References Reset().
Member Function Documentation
Vector3D VW::RotationCentre::Centre () const [inline]
References centre.
Referenced by VW::ThreeDToolGLCommon::Dragged(), VW::ThreeDToolGLCommon::DrawAxes(), and VW::ThreeDToolGLCommon::DrawRotationCentre().
void RotationCentre::Include (const Vector3D & v0)
Change the rotation centre depending on a new point.
References centre, drawing_position, VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), initialised, VW::DrawingPosition::qWO, VW::Quaternion::RotationMatrix(), VW::DrawingPosition::rW, VW::Point3D::SetX(), VW::Point3D::SetY(), VW::Point3D::SetZ(), VERBOSE, xmax, xmin, ymax, ymin, zmax, and zmin.
Referenced by VW::ThreeDToolGLCommon::DrawCameraGraphic(), VW::ThreeDToolGLCommon::DrawCovariance(), VW::ThreeDToolGLCommon::DrawCylinder(), VW::ThreeDToolGLCommon::DrawLine(), VW::ThreeDToolGLCommon::DrawPoint(), VW::ThreeDToolGLCommon::DrawRectangle(), VW::ThreeDToolGLCommon::DrawSphere(), VW::ThreeDToolGLCommon::DrawTexturedRectangle(), VW::ThreeDToolGLCommon::DrawTriangle(), VW::ThreeDToolGLCommon::DrawWarpedTexturedRectangle(), IncludeCurrent(), and VW::ThreeDToolGLCommon::IncludeInRotationCentre().
void RotationCentre::IncludeCurrent ()
Include the current origin.
References Include().
Referenced by VW::ThreeDToolGLCommon::DrawCone(), VW::ThreeDToolGLCommon::DrawCylinder(), VW::ThreeDToolGLCommon::DrawDisc(), and VW::ThreeDToolGLCommon::DrawSphere().
void RotationCentre::Reset ()
References centre, initialised, VW::Point3D::Set(), xmax, xmin, ymax, ymin, zmax, and zmin.
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), and RotationCentre().
double VW::RotationCentre::XMax () const [inline]
References xmax.
Referenced by VW::ThreeDToolGLCommon::DrawAxes().
double VW::RotationCentre::XMin () const [inline]
References xmin.
Referenced by VW::ThreeDToolGLCommon::DrawAxes().
double VW::RotationCentre::YMax () const [inline]
References ymax.
Referenced by VW::ThreeDToolGLCommon::DrawAxes().
double VW::RotationCentre::YMin () const [inline]
References ymin.
Referenced by VW::ThreeDToolGLCommon::DrawAxes().
double VW::RotationCentre::ZMax () const [inline]
References zmax.
Referenced by VW::ThreeDToolGLCommon::DrawAxes().
double VW::RotationCentre::ZMin () const [inline]
References zmin.
Referenced by VW::ThreeDToolGLCommon::DrawAxes().
Member Data Documentation
Vector3D VW::RotationCentre::centre [protected]
Referenced by Centre(), Include(), and Reset().
DrawingPosition& VW::RotationCentre::drawing_position [protected]
Referenced by Include().
bool VW::RotationCentre::initialised [protected]
Referenced by Include(), and Reset().
double VW::RotationCentre::xmax [protected]
Referenced by Include(), Reset(), and XMax().
double VW::RotationCentre::xmin [protected]
Referenced by Include(), Reset(), and XMin().
double VW::RotationCentre::ymax [protected]
Referenced by Include(), Reset(), and YMax().
double VW::RotationCentre::ymin [protected]
Referenced by Include(), Reset(), and YMin().
double VW::RotationCentre::zmax [protected]
Referenced by Include(), Reset(), and ZMax().
double VW::RotationCentre::zmin [protected]
Referenced by Include(), Reset(), and ZMin().
The documentation for this class was generated from the following files:
threedtoolglcommon.h
threedtoolglcommon.cpp