VW: VNL::Vector< T > Class Template Reference
VNL::Vector< T > Class Template Reference
Mathematical vector class, templated by type of element.
#include <vector.h>
Public Types
typedef T element_type
Type defs for iterators.
typedef T * iterator
Type defs for iterators.
typedef T const * const_iterator
Const iterator type.
typedef CVector< T >::abs_t abs_t
Public Member Functions
Vector ()
Creates an empty vector. O(1).
Vector (unsigned len)
Creates vector containing n elements.
Vector (unsigned len, T const &v0)
Creates vector of len elements, all set to v0.
Vector (unsigned len, int n, T const values[])
Creates a vector of specified length and initialize first n elements with values. O(n).
Vector (T const &, T const &, T const &)
Creates a vector of length 3 and initializes with the arguments, x,y,z.
Vector (T const *data_block, unsigned int n)
Create n element vector and copy data from data_block.
Vector (Vector< T > const &)
Copy constructor.
Vector (Vector< T > const &, Vector< T > const &, VNL::TagAdd)
Vector (Vector< T > const &, Vector< T > const &, VNL::TagSub)
Vector (Vector< T > const &, T, VNL::TagMul)
Vector (Vector< T > const &, T, VNL::TagDiv)
Vector (Vector< T > const &, T, VNL::TagAdd)
Vector (Vector< T > const &, T, VNL::TagSub)
Vector (Matrix< T > const &, Vector< T > const &, VNL::TagMul)
Vector (Vector< T > const &, Matrix< T > const &, VNL::TagMul)
Vector (Vector< T > &that, VNL::TagGrab)
~Vector ()
Destructor.
unsigned size () const
Return the length, number of elements, dimension of this vector.
unsigned Size () const
Return the length, number of elements, dimension of this vector.
void Put (unsigned int i, T const &)
Put value at given position in vector.
T Get (unsigned int i) const
Get value at element i.
void Fill (T const &v)
Set all values to v.
void CopyIn (T const *ptr)
Sets elements to ptr[i].
void CopyOut (T *) const
Copy elements to ptr[i].
void Set (T const *ptr)
Sets elements to ptr[i].
T & operator() (unsigned int i)
Return reference to the element at specified index.
T const & operator() (unsigned int i) const
Return reference to the element at specified index. No range checking.
T & operator[] (unsigned int i)
Return reference to the element at specified index. No range checking.
T const & operator[] (unsigned int i) const
Return reference to the element at specified index. No range checking.
Vector< T > & operator= (T const &v)
Set all elements to value v.
Vector< T > & operator= (Vector< T > const &rhs)
Copy operator.
Vector< T > & operator+= (T)
Add scalar value to all elements.
Vector< T > & operator-= (T)
Subtract scalar value from all elements.
Vector< T > & operator*= (T)
Multiply all elements by scalar.
Vector< T > & operator/= (T)
Divide all elements by scalar.
Vector< T > & operator+= (Vector< T > const &rhs)
Add rhs to this and return *this.
Vector< T > & operator-= (Vector< T > const &rhs)
Subtract rhs from this and return *this.
Vector< T > & PreMultiply (Matrix< T > const &M)
*this = M*(*this) where M is a suitable matrix.
Vector< T > & PostMultiply (Matrix< T > const &M)
*this = (*this)*M where M is a suitable matrix.
Vector< T > & operator*= (Matrix< T > const &m)
*this = (*this)*M where M is a suitable matrix.
Vector< T > operator+ () const
Unary plus operator.
Vector< T > operator- () const
Unary minus operator.
Vector< T > operator+ (T v) const
Vector< T > operator- (T v) const
Vector< T > operator* (T v) const
Vector< T > operator/ (T v) const
Vector< T > operator+ (Vector< T > const &v) const
Vector< T > operator- (Vector< T > const &v) const
Vector< T > operator* (Matrix< T > const &M) const
T const * DataBlock () const
Access the contiguous block storing the elements in the vector. O(1).
T * DataBlock ()
Access the contiguous block storing the elements in the vector. O(1).
iterator begin ()
Iterator pointing to start of data.
iterator end ()
Iterator pointing to element beyond end of data.
const_iterator begin () const
Iterator pointing to start of data.
const_iterator end () const
Iterator pointing to element beyond end of data.
Vector< T > Apply (T(*f)(T)) const
Applies function to elements.
Vector< T > Apply (T(*f)(T const &)) const
Applies function to elements.
Vector< T > Extract (unsigned int len, unsigned int start=0) const
Returns a subvector specified by the start index and length. O(n).
Vector< T > & Update (Vector< T > const &, unsigned int start=0)
Replaces elements with index begining at start, by values of v. O(n).
abs_t SquaredMagnitude () const
Return sum of squares of elements.
abs_t Magnitude () const
Return magnitude (length) of vector.
abs_t OneNorm () const
Return sum of absolute values of the elements.
abs_t TwoNorm () const
Return sqrt of sum of squares of values of elements.
abs_t InfNorm () const
Return largest absolute element value.
Vector< T > & Normalize ()
Normalise by dividing through by the magnitude.
abs_t RMS () const
Root Mean Squares of values.
T MinValue () const
Smallest value.
T MaxValue () const
Largest value.
T Mean () const
Mean of values in vector.
T Sum () const
Sum of values in a vector.
void Flip ()
Reverse the order of the elements.
void Swap (Vector< T > &that)
Set this to that and that to this.
T & x () const
Return first element of vector.
T & y () const
Return second element of vector.
T & z () const
Return third element of vector.
T & t () const
Return fourth element of vector.
void assert_size (unsigned sz) const
Check that size()==sz if not, abort();.
void assert_finite () const
Check that this is finite if not, abort();.
bool IsFinite () const
Return true if its finite.
bool IsZero () const
Return true iff all the entries are zero.
bool IsEmpty () const
Return true iff the size is zero.
bool operator_eq (Vector< T > const &v) const
Return true if *this == v.
bool operator== (Vector< T > const &that) const
Equality test.
bool operator!= (Vector< T > const &that) const
Inequality test.
bool Resize (unsigned n)
Resize to n elements.
void Clear ()
Make the vector as if it had been default-constructed.
bool ReadASCII (std::istream &s)
Read from text stream.
Static Public Member Functions
static Vector< T > Read (std::istream &s)
Read from text stream.
Protected Member Functions
void assert_size_internal (unsigned sz) const
void assert_finite_internal () const
void destroy ()
Frees up the array inside vector. O(1).
Static Protected Member Functions
static void inline_function_tickler ()
Protected Attributes
unsigned num_elmts
T * data
Friends
class Matrix< T >
Detailed Description
template<class T = double>
class VNL::Vector< T >
Mathematical vector class, templated by type of element.
The Vector<T> class implements one-dimensional arithmetic vectors to be used with the Matrix<T> class. Vector<T> has size fixed by constructor time or changed by assignment operator. For faster, non-mallocing vectors with size known at compile time, use VectorFixed*.
NOTE: Vectors are indexed from zero! Thus valid elements are [0,size()-1].
Member Typedef Documentation
template<class T = double> typedef CVector<T>::abs_t VNL::Vector< T >::abs_t
template<class T = double> typedef T const* VNL::Vector< T >::const_iterator
Const iterator type.
template<class T = double> typedef T VNL::Vector< T >::element_type
Type defs for iterators.
template<class T = double> typedef T* VNL::Vector< T >::iterator
Type defs for iterators.
Constructor & Destructor Documentation
template<class T = double> VNL::Vector< T >::Vector () [inline]
Creates an empty vector. O(1).
template<class T > VNL::Vector< T >::Vector (unsigned len) [inline, explicit]
Creates vector containing n elements.
Creates a vector with specified length. O(n).
Elements are not initialized.
References vnl_vector_alloc_blah.
template<class T> VNL::Vector< T >::Vector (unsigned len, T const & v0) [inline]
Creates vector of len elements, all set to v0.
Creates a vector of specified length, and initialize all elements with value. O(n).
References VNL::Vector< T >::data, and vnl_vector_alloc_blah.
template<class T> VNL::Vector< T >::Vector (unsigned len, int n, T const values[]) [inline]
Creates a vector of specified length and initialize first n elements with values. O(n).
References VNL::Vector< T >::data, and vnl_vector_alloc_blah.
template<class T> VNL::Vector< T >::Vector (T const & px, T const & py, T const & pz) [inline]
Creates a vector of length 3 and initializes with the arguments, x,y,z.
References VNL::Vector< T >::data, and vnl_vector_alloc_blah.
template<class T = double> VNL::Vector< T >::Vector (T const * data_block, unsigned int n)
Create n element vector and copy data from data_block.
template<class T> VNL::Vector< T >::Vector (VNL::Vector< T > const & v) [inline]
Copy constructor.
Creates a new copy of vector v. O(n).
References VNL::Vector< T >::data, VNL::Vector< T >::num_elmts, and vnl_vector_alloc_blah.
template<class T> VNL::Vector< T >::Vector (VNL::Vector< T > const & u, VNL::Vector< T > const & v, VNL::TagAdd) [inline]
References VNL::Vector< T >::data, VNL::ErrorVectorDimension(), VNL::Vector< T >::num_elmts, VNL::Vector< T >::size(), and vnl_vector_alloc_blah.
template<class T> VNL::Vector< T >::Vector (VNL::Vector< T > const & u, VNL::Vector< T > const & v, VNL::TagSub) [inline]
References VNL::Vector< T >::data, VNL::ErrorVectorDimension(), VNL::Vector< T >::num_elmts, VNL::Vector< T >::size(), and vnl_vector_alloc_blah.
template<class T> VNL::Vector< T >::Vector (VNL::Vector< T > const & u, T s, VNL::TagMul) [inline]
References VNL::Vector< T >::data, VNL::Vector< T >::num_elmts, and vnl_vector_alloc_blah.
template<class T> VNL::Vector< T >::Vector (VNL::Vector< T > const & u, T s, VNL::TagDiv) [inline]
References VNL::Vector< T >::data, VNL::Vector< T >::num_elmts, and vnl_vector_alloc_blah.
template<class T> VNL::Vector< T >::Vector (VNL::Vector< T > const & u, T s, VNL::TagAdd) [inline]
References VNL::Vector< T >::data, VNL::Vector< T >::num_elmts, and vnl_vector_alloc_blah.
template<class T> VNL::Vector< T >::Vector (VNL::Vector< T > const & u, T s, VNL::TagSub) [inline]
References VNL::Vector< T >::data, VNL::Vector< T >::num_elmts, and vnl_vector_alloc_blah.
template<class T> VNL::Vector< T >::Vector (VNL::Matrix< T > const & M, VNL::Vector< T > const & v, VNL::TagMul) [inline]
References VNL::Matrix< T >::Columns(), VNL::Vector< T >::data, VNL::ErrorVectorDimension(), VNL::Vector< T >::num_elmts, VNL::Matrix< T >::Rows(), VNL::Vector< T >::size(), and vnl_vector_alloc_blah.
template<class T> VNL::Vector< T >::Vector (VNL::Vector< T > const & v, VNL::Matrix< T > const & M, VNL::TagMul) [inline]
References VNL::Matrix< T >::Columns(), VNL::Vector< T >::data, VNL::ErrorVectorDimension(), VNL::Vector< T >::num_elmts, VNL::Matrix< T >::Rows(), VNL::Vector< T >::size(), and vnl_vector_alloc_blah.
template<class T = double> VNL::Vector< T >::Vector (Vector< T > & that, VNL::TagGrab) [inline]
template<class T = double> VNL::Vector< T >::~Vector () [inline]
Destructor.
Member Function Documentation
template<class T> VNL::Vector< T > VNL::Vector< T >::Apply (T(*)(T const &) f) const [inline]
Applies function to elements.
References VNL::Vector< T >::Apply(), VNL::Vector< T >::data, VNL::Vector< T >::num_elmts, and VNL::Vector< T >::size().
template<class T> VNL::Vector< T > VNL::Vector< T >::Apply (T(*)(T) f) const [inline]
Applies function to elements.
Return the vector made by applying "f" to each element.
References VNL::Vector< T >::data, and VNL::Vector< T >::num_elmts.
Referenced by VNL::Vector< T >::Apply().
template<class T = double> void VNL::Vector< T >::assert_finite () const [inline]
Check that this is finite if not, abort();.
This function does or tests nothing if NDEBUG is defined
Referenced by VNL::RPolyRoots::RPolyRoots().
template<class T > void VNL::Vector< T >::assert_finite_internal () const [inline, protected]
References VNL::Vector< T >::IsFinite().
Referenced by VNL::Vector< std::complex< double > >::assert_finite().
template<class T = double> void VNL::Vector< T >::assert_size (unsigned sz) const [inline]
Check that size()==sz if not, abort();.
This function does or tests nothing if NDEBUG is defined
template<class T > void VNL::Vector< T >::assert_size_internal (unsigned sz) const [inline, protected]
References VNL::Vector< T >::size().
Referenced by VNL::Vector< std::complex< double > >::assert_size().
template<class T = double> const_iterator VNL::Vector< T >::begin () const [inline]
Iterator pointing to start of data.
template<class T = double> iterator VNL::Vector< T >::begin () [inline]
Iterator pointing to start of data.
Referenced by VW::RadialDistortionCompute::LeastSquaresFunction::F(), VW::PMatrixCompute::LSFuncPoints::F(), VW::Homography2DCompute::LeastSquaresFunctionPoints::F(), VW::FMPlanarCompute::LeastSquaresFunctionPoints::F(), VW::FMatrixCompute::LeastSquaresFunctionPoints::F(), VNL::GeneralizedEigensystem::GeneralizedEigensystem(), VNL::GeneralizedSchur(), VNL::Vector< std::complex< double > >::InfNorm(), VNL::MatlabPrint(), VNL::MatlabReadOrDie(), VNL::Vector< std::complex< double > >::MaxValue(), VNL::Vector< std::complex< double > >::Mean(), VNL::Vector< std::complex< double > >::MinValue(), VNL::Vector< std::complex< double > >::Normalize(), VNL::Vector< std::complex< double > >::OneNorm(), VNL::Vector< std::complex< double > >::RMS(), VNL::Vector< std::complex< double > >::SquaredMagnitude(), VNL::Vector< std::complex< double > >::Sum(), VNL::Vector< std::complex< double > >::TwoNorm(), VNL::VectorSSD(), and vnl_complexify().
template<class T > void VNL::Vector< T >::Clear () [inline]
Make the vector as if it had been default-constructed.
References VNL::Vector< T >::data, VNL::Vector< T >::destroy(), and VNL::Vector< T >::num_elmts.
Referenced by VNL::BinaryLoad(), and VNL::Vector< T >::operator=().
template<class T> void VNL::Vector< T >::CopyIn (T const * ptr) [inline]
Sets elements to ptr[i].
Sets elements of a vector to those in an array. O(n).
Note: ptr[i] must be valid for i=0..size()-1
References VNL::Vector< T >::data, and VNL::Vector< T >::num_elmts.
Referenced by VW::ComputeFuncs::ConvertTransformToParamVector(), and VNL::Vector< std::complex< double > >::Set().
template<class T> void VNL::Vector< T >::CopyOut (T * ptr) const [inline]
Copy elements to ptr[i].
Sets elements of an array to those in vector. O(n).
Note: ptr[i] must be valid for i=0..size()-1
References VNL::Vector< T >::data, and VNL::Vector< T >::num_elmts.
Referenced by VW::ComputeFuncs::ConvertParamVectorToTransform(), and VNL::SymMatrix< T >::SetHalfRow().
template<class T = double> T* VNL::Vector< T >::DataBlock () [inline]
Access the contiguous block storing the elements in the vector. O(1).
data_block()[0] is the first element of the vector
template<class T = double> T const* VNL::Vector< T >::DataBlock () const [inline]
Access the contiguous block storing the elements in the vector. O(1).
data_block()[0] is the first element of the vector
Referenced by vnl_fastops::AtB(), VNL::BinaryLoad(), VNL::BinarySave(), VNL::Cholesky< T >::Cholesky(), VNL::RPolyRoots::Compute(), VNL::ConvolveUsingFFT(), VNL::CrossProductMatrix< T >::CrossProductMatrix(), VNL::RealPolynomial::Evaluate(), VNL::RealPolynomial::EvaluateIntegral(), VW::ParametricFlowFunc< Type >::F(), vnl_fastops::inc_X_by_AtB(), VNL::LSqr::Minimize(), VNL::LBFGS::Minimize(), VNL::ConjugateGradient::Minimize(), VNL::LevenbergMarquardt::MinimizeUsingGradient(), VNL::LevenbergMarquardt::MinimizeWithoutGradient(), VNL::VectorFixed< 3, T >::operator=(), VNL::QR< T >::QR(), VNL::QR< T >::QtB(), VNL::RealEigensystem::RealEigensystem(), VW::FMPlanarCompute::ReconstructTransformHZ(), VW::FMPlanarCompute::ReconstructTransformHZJK(), VW::FMPlanarCompute::ReconstructTransformVLJK(), VNL::Matrix< T >::SetColumn(), VNL::Matrix< T >::SetRow(), VNL::QR< T >::Solve(), VNL::Cholesky< T >::Solve(), VNL::SVD< T >::SVD(), VNL::VectorFixed< 3, T >::VectorFixed(), VNL::VectorRef< double >::VectorRef(), and VNL::MatlabFilewrite::Write().
template<class T > void VNL::Vector< T >::destroy () [inline, protected]
Frees up the array inside vector. O(1).
References vnl_vector_free_blah.
Referenced by VNL::Vector< T >::Clear(), and VNL::Vector< std::complex< double > >::~Vector().
template<class T = double> const_iterator VNL::Vector< T >::end () const [inline]
Iterator pointing to element beyond end of data.
template<class T = double> iterator VNL::Vector< T >::end () [inline]
Iterator pointing to element beyond end of data.
Referenced by VNL::GeneralizedSchur().
template<class T = double> Vector<T> VNL::Vector< T >::Extract (unsigned int len, unsigned int start = 0) const
Returns a subvector specified by the start index and length. O(n).
template<class T> void VNL::Vector< T >::Fill (T const & v) [inline]
Set all values to v.
Sets all elements of a vector to a specified fill value. O(n).
References VNL::Vector< T >::data, and VNL::Vector< T >::num_elmts.
Referenced by VNL::SparseMatrix< T >::diag_AtA(), VNL::SparseMatrix< T >::mult(), VNL::operator*(), VNL::Vector< std::complex< double > >::operator=(), VNL::SparseMatrix< T >::pre_mult(), and VNL::QR< T >::QR().
template<class T > void VNL::Vector< T >::Flip () [inline]
Reverse the order of the elements.
Element i swaps with element size()-1-i
References VNL::Vector< T >::data, and VNL::Vector< T >::num_elmts.
template<class T > T VNL::Vector< T >::Get (unsigned int index) const [inline]
Get value at element i.
Gets the element at specified index and return its value. O(1).
Range check is performed.
References VNL::Vector< T >::data, and VNL::Vector< T >::num_elmts.
template<class T = double> abs_t VNL::Vector< T >::InfNorm () const [inline]
Return largest absolute element value.
Referenced by VNL::Vector< std::complex< double > >::InfNorm().
template<class T > void VNL::Vector< T >::inline_function_tickler () [inline, static, protected]
template<class T = double> bool VNL::Vector< T >::IsEmpty () const [inline]
Return true iff the size is zero.
template<class T > bool VNL::Vector< T >::IsFinite () const [inline]
Return true if its finite.
References VNL::IsFinite(), and VNL::Vector< T >::size().
Referenced by VNL::Vector< T >::assert_finite_internal().
template<class T > bool VNL::Vector< T >::IsZero () const [inline]
Return true iff all the entries are zero.
References VNL::Vector< T >::size().
template<class T = double> abs_t VNL::Vector< T >::Magnitude () const [inline]
Return magnitude (length) of vector.
Referenced by VW::FMPlanarCompute::GenerateParameterVectorHZ(), VW::FMPlanarCompute::GenerateParameterVectorHZJK(), VW::FMPlanarCompute::GenerateParameterVectorVLJK(), VNL::LevenbergMarquardt::lmder_lsqfun(), VNL::LevenbergMarquardt::lmdif_lsqfun(), and VNL::LBFGS::Minimize().
template<class T = double> T VNL::Vector< T >::MaxValue () const [inline]
Largest value.
Referenced by VNL::Vector< std::complex< double > >::MaxValue().
template<class T = double> T VNL::Vector< T >::Mean () const [inline]
Mean of values in vector.
Referenced by VNL::Vector< std::complex< double > >::Mean().
template<class T = double> T VNL::Vector< T >::MinValue () const [inline]
Smallest value.
Referenced by VNL::Vector< std::complex< double > >::MinValue().
template<class T = double> Vector<T>& VNL::Vector< T >::Normalize () [inline]
Normalise by dividing through by the magnitude.
Reimplemented in VNL::VectorFixedRef< n, T >, and VNL::VectorFixedRef< n, double >.
Referenced by VW::FMPlanarCompute::GenerateParameterVectorHZJK(), VW::FMPlanarCompute::GenerateParameterVectorVLJK(), VNL::Vector< std::complex< double > >::Normalize(), and VW::FMPlanarCompute::ReconstructTransformVLJK().
template<class T = double> abs_t VNL::Vector< T >::OneNorm () const [inline]
Return sum of absolute values of the elements.
Referenced by VNL::Vector< std::complex< double > >::OneNorm().
template<class T = double> bool VNL::Vector< T >::operator!= (Vector< T > const & that) const [inline]
Inequality test.
template<class T = double> T const& VNL::Vector< T >::operator() (unsigned int i) const [inline]
Return reference to the element at specified index. No range checking.
There are assert style boundary checks - define NDEBUG to turn them off.
template<class T = double> T& VNL::Vector< T >::operator() (unsigned int i) [inline]
Return reference to the element at specified index.
There are assert style boundary checks - define NDEBUG to turn them off.
template<class T = double> Vector<T> VNL::Vector< T >::operator* (Matrix< T > const & M) const [inline]
template<class T = double> Vector<T> VNL::Vector< T >::operator* (T v) const [inline]
Reimplemented in VNL::VectorFixed< n, T >, VNL::VectorFixed< 1, double >, VNL::VectorFixed< 2, double >, VNL::VectorFixed< 3, double >, and VNL::VectorFixed< 3, T >.
template<class T = double> Vector<T>& VNL::Vector< T >::operator*= (Matrix< T > const & m) [inline]
*this = (*this)*M where M is a suitable matrix.
this is treated as a row vector
Reimplemented in VNL::VectorFixedRef< n, T >, and VNL::VectorFixedRef< n, double >.
template<class T> VNL::Vector< T > & VNL::Vector< T >::operator*= (T value) [inline]
Multiply all elements by scalar.
Multiplies all elements of vector with value. O(n).
Reimplemented in VNL::VectorFixedRef< n, T >, and VNL::VectorFixedRef< n, double >.
References VNL::Vector< T >::data, and VNL::Vector< T >::num_elmts.
template<class T = double> Vector<T> VNL::Vector< T >::operator+ (Vector< T > const & v) const [inline]
template<class T = double> Vector<T> VNL::Vector< T >::operator+ (T v) const [inline]
Reimplemented in VNL::VectorFixed< n, T >, VNL::VectorFixed< 1, double >, VNL::VectorFixed< 2, double >, VNL::VectorFixed< 3, double >, and VNL::VectorFixed< 3, T >.
template<class T = double> Vector<T> VNL::Vector< T >::operator+ () const [inline]
Unary plus operator.
Return new vector = (*this)
template<class T> VNL::Vector< T > & VNL::Vector< T >::operator+= (VNL::Vector< T > const & rhs) [inline]
Add rhs to this and return *this.
Mutates lhs vector with its addition with rhs vector. O(n).
References VNL::Vector< T >::data, VNL::ErrorVectorDimension(), and VNL::Vector< T >::num_elmts.
template<class T> VNL::Vector< T > & VNL::Vector< T >::operator+= (T value) [inline]
Add scalar value to all elements.
Increments all elements of vector with value. O(n).
Reimplemented in VNL::VectorFixedRef< n, T >, and VNL::VectorFixedRef< n, double >.
References VNL::Vector< T >::data, and VNL::Vector< T >::num_elmts.
template<class T = double> Vector<T> VNL::Vector< T >::operator- (Vector< T > const & v) const [inline]
template<class T = double> Vector<T> VNL::Vector< T >::operator- (T v) const [inline]
Reimplemented in VNL::VectorFixed< n, T >, VNL::VectorFixed< 1, double >, VNL::VectorFixed< 2, double >, VNL::VectorFixed< 3, double >, and VNL::VectorFixed< 3, T >.
template<class T > VNL::Vector< T > VNL::Vector< T >::operator- () const [inline]
Unary minus operator.
Creates new vector containing the negation of THIS vector. O(n).
Return new vector = -1*(*this)
Reimplemented in VNL::VectorFixed< n, T >, VNL::VectorFixed< 1, double >, VNL::VectorFixed< 2, double >, VNL::VectorFixed< 3, double >, and VNL::VectorFixed< 3, T >.
References VNL::Vector< T >::data, and VNL::Vector< T >::num_elmts.
template<class T> VNL::Vector< T > & VNL::Vector< T >::operator-= (VNL::Vector< T > const & rhs) [inline]
Subtract rhs from this and return *this.
Mutates lhs vector with its substraction with rhs vector. O(n).
References VNL::Vector< T >::data, VNL::ErrorVectorDimension(), and VNL::Vector< T >::num_elmts.
template<class T> VNL::Vector< T > & VNL::Vector< T >::operator-= (T value) [inline]
Subtract scalar value from all elements.
Reimplemented in VNL::VectorFixedRef< n, T >, and VNL::VectorFixedRef< n, double >.
References VNL::Vector< T >::data, and VNL::Vector< T >::num_elmts.
template<class T = double> Vector<T> VNL::Vector< T >::operator/ (T v) const [inline]
Reimplemented in VNL::VectorFixed< n, T >, VNL::VectorFixed< 1, double >, VNL::VectorFixed< 2, double >, VNL::VectorFixed< 3, double >, and VNL::VectorFixed< 3, T >.
template<class T> VNL::Vector< T > & VNL::Vector< T >::operator/= (T value) [inline]
Divide all elements by scalar.
Divides all elements of vector by value. O(n).
Reimplemented in VNL::VectorFixedRef< n, T >, and VNL::VectorFixedRef< n, double >.
References VNL::Vector< T >::data, and VNL::Vector< T >::num_elmts.
template<class T> VNL::Vector< T > & VNL::Vector< T >::operator= (VNL::Vector< T > const & rhs) [inline]
Copy operator.
Copies rhs vector into lhs vector. O(n).
Changes the dimension of lhs vector if necessary.
Reimplemented in VNL::VectorFixed< n, T >, and VW::Line2D.
References VNL::Vector< T >::Clear(), VNL::Vector< T >::data, VNL::Vector< T >::num_elmts, VNL::Vector< T >::Resize(), and VNL::Vector< T >::size().
template<class T = double> Vector<T>& VNL::Vector< T >::operator= (T const & v) [inline]
Set all elements to value v.
Reimplemented in VNL::VectorFixedRef< n, T >, and VNL::VectorFixedRef< n, double >.
template<class T = double> bool VNL::Vector< T >::operator== (Vector< T > const & that) const [inline]
Equality test.
template<class T = double> T const& VNL::Vector< T >::operator[] (unsigned int i) const [inline]
Return reference to the element at specified index. No range checking.
template<class T = double> T& VNL::Vector< T >::operator[] (unsigned int i) [inline]
Return reference to the element at specified index. No range checking.
template<class T> bool VNL::Vector< T >::operator_eq (VNL::Vector< T > const & rhs) const [inline]
Return true if *this == v.
References VNL::Vector< T >::data, and VNL::Vector< T >::size().
Referenced by VNL::Vector< std::complex< double > >::operator!=(), and VNL::Vector< std::complex< double > >::operator==().
template<class T> VNL::Vector< T > & VNL::Vector< T >::PostMultiply (VNL::Matrix< T > const & m) [inline]
*this = (*this)*M where M is a suitable matrix.
Post-multiplies vector with matrix and stores result back in vector.
this is treated as a row vector
v = v * m. O(m*n). Vector is assumed a row matrix.
Reimplemented in VNL::VectorFixedRef< n, T >, and VNL::VectorFixedRef< n, double >.
References VNL::Matrix< T >::Columns(), VNL::Vector< T >::data, VNL::ErrorVectorDimension(), VNL::Vector< T >::num_elmts, and VNL::Matrix< T >::Rows().
Referenced by VNL::Vector< std::complex< double > >::operator*=().
template<class T> VNL::Vector< T > & VNL::Vector< T >::PreMultiply (VNL::Matrix< T > const & m) [inline]
*this = M*(*this) where M is a suitable matrix.
Pre-multiplies vector with matrix and stores result back in vector.
this is treated as a column vector
v = m * v. O(m*n). Vector is assumed a column matrix.
Reimplemented in VNL::VectorFixedRef< n, T >, and VNL::VectorFixedRef< n, double >.
References VNL::Matrix< T >::Columns(), VNL::Vector< T >::data, VNL::ErrorVectorDimension(), VNL::Vector< T >::num_elmts, and VNL::Matrix< T >::Rows().
template<class T> void VNL::Vector< T >::Put (unsigned int index, T const & value) [inline]
Put value at given position in vector.
Puts the value at specified index. O(1).
Range check is performed.
References VNL::Vector< T >::data, and VNL::Vector< T >::num_elmts.
template<class T > VNL::Vector< T > VNL::Vector< T >::Read (std::istream & s) [inline, static]
Read from text stream.
References VNL::Vector< T >::ReadASCII().
template<class T > bool VNL::Vector< T >::ReadASCII (std::istream & s) [inline]
Read from text stream.
Read a VNL::Vector from an ascii std::istream.
If the vector has nonzero size on input, read that many values. Otherwise, read to EOF.
Reimplemented in VW::Line2D.
References VNL::Vector< T >::Resize(), and VNL::Vector< T >::size().
Referenced by VNL::FileVector< T >::FileVector(), VNL::operator>>(), and VNL::Vector< T >::Read().
template<class T > bool VNL::Vector< T >::Resize (unsigned n) [inline]
Resize to n elements.
Checks early and does nothing if already size n, otherwise old data is discarded. Returns true if size change successful.
References VNL::Vector< T >::data, VNL::Vector< T >::num_elmts, vnl_vector_alloc_blah, and vnl_vector_free_blah.
Referenced by VNL::BinaryLoad(), VNL::SparseMatrix< T >::diag_AtA(), VNL::MatlabReadOrDie(), VNL::SparseMatrix< T >::mult(), VNL::Vector< T >::operator=(), VNL::SparseMatrix< T >::pre_mult(), and VNL::Vector< T >::ReadASCII().
template<class T = double> abs_t VNL::Vector< T >::RMS () const [inline]
Root Mean Squares of values.
Referenced by VW::ParametricFlowFunc< Type >::F(), VNL::LinearSystem::GetRelativeResidual(), VNL::LinearSystem::GetRMSError(), VNL::LevenbergMarquardt::lmder_lsqfun(), VNL::LevenbergMarquardt::lmdif_lsqfun(), VNL::LevenbergMarquardt::MinimizeUsingGradient(), VNL::LevenbergMarquardt::MinimizeWithoutGradient(), and VNL::LeastSquaresFunction::RMS().
template<class T = double> void VNL::Vector< T >::Set (T const * ptr) [inline]
Sets elements to ptr[i].
Note: ptr[i] must be valid for i=0..size()-1
template<class T = double> unsigned VNL::Vector< T >::Size () const [inline]
Return the length, number of elements, dimension of this vector.
Referenced by vnl_fastops::AtB(), vnl_matops::cat(), vnl_fastops::inc_X_by_AtB(), VNL::Project(), and VNL::Unproject().
template<class T = double> unsigned VNL::Vector< T >::size () const [inline]
Return the length, number of elements, dimension of this vector.
Referenced by VNL::Vector< T >::Apply(), VNL::SparseMatrixLinearSystem< T >::ApplyPreconditioner(), VNL::LinearSystem::ApplyPreconditioner(), VNL::Vector< T >::assert_size_internal(), vnl_fastops::AtB(), VNL::BinaryLoad(), VNL::BinarySave(), VNL::RPolyRoots::Compute(), VW::ComputeFuncs::ConvertParamVectorToTransform(), VNL::Convolve(), VNL::ConvolveCyclic(), VNL::ConvolveCyclicUsingFFT(), VNL::ConvolveUsingFFT(), VNL::CPolyRoots::CPolyRoots(), VNL::RealPolynomial::Degree(), VNL::RealNPolynomial::Degree(), VNL::AmoebaFit::DoAmoeba(), VNL::RealPolynomial::Evaluate(), VNL::RealPolynomial::EvaluateIntegral(), VNL::LeastSquaresFunction::FDGradF(), VNL::GeneralizedSchur(), VNL::Vector< std::complex< double > >::InfNorm(), VNL::Powell1DFun::Init(), VNL::Vector< T >::IsFinite(), VNL::Vector< T >::IsZero(), VW::Line2D::Line2D(), VNL::MatlabPrint(), VNL::MatlabReadOrDie(), VNL::Vector< std::complex< double > >::MaxValue(), VNL::Vector< std::complex< double > >::Mean(), VNL::Powell::Minimize(), VNL::LBFGS::Minimize(), VNL::LevenbergMarquardt::MinimizeUsingGradient(), VNL::LevenbergMarquardt::MinimizeWithoutGradient(), VNL::Vector< std::complex< double > >::MinValue(), VNL::SparseMatrix< T >::mult(), VNL::SparseMatrixLinearSystem< T >::Multiply(), VNL::Vector< std::complex< double > >::Normalize(), VNL::Vector< std::complex< double > >::OneNorm(), VNL::Vector< std::complex< double > >::operator()(), VNL::operator<<(), VNL::VectorFixed< 3, T >::operator=(), VNL::Vector< T >::operator=(), VNL::Vector< T >::operator_eq(), VNL::SparseMatrix< T >::pre_mult(), VNL::Vector< T >::ReadASCII(), VNL::RealNPolynomial::RealNPolynomial(), VW::FMatrixCompute::ReconstructTransform(), VW::FMPlanarCompute::ReconstructTransformHZ(), VW::FMPlanarCompute::ReconstructTransformHZJK(), VW::FMPlanarCompute::ReconstructTransformVLJK(), VNL::Vector< std::complex< double > >::RMS(), VNL::SymMatrix< T >::SetHalfRow(), VNL::AmoebaFit::SetUpSimplexAbsolute(), VNL::AmoebaFit::SetUpSimplexRelative(), VNL::SymmetricEigensystem< T >::Solve(), VNL::SVD< T >::Solve(), VNL::Cholesky< T >::Solve(), VNL::SVD< T >::SolvePreinverted(), VNL::Vector< std::complex< double > >::SquaredMagnitude(), VNL::Vector< std::complex< double > >::Sum(), VNL::SymmetricEigensystemCompute(), VNL::SparseMatrixLinearSystem< T >::TransposeMultiply(), VNL::Vector< std::complex< double > >::TwoNorm(), VNL::Vector< T >::Vector(), VNL::VectorFixed< 3, T >::VectorFixed(), VNL::VectorFixedRef< n, double >::VectorFixedRef(), VNL::VectorRef< double >::VectorRef(), VNL::VectorSSD(), vnl_complexify(), vnl_discrete_diff_fwd(), vnl_discrete_diff_sym(), vnl_discrete_diff_test_lsf(), vnl_gaussian_kernel_1d::vnl_gaussian_kernel_1d(), vnl_orthogonal_complement(), vnl_gaussian_kernel_1d::width(), and VNL::MatlabFilewrite::Write().
template<class T = double> abs_t VNL::Vector< T >::SquaredMagnitude () const [inline]
Return sum of squares of elements.
Referenced by VNL::LeastSquaresCostFunction::F().
template<class T = double> T VNL::Vector< T >::Sum () const [inline]
Sum of values in a vector.
Referenced by VNL::Vector< std::complex< double > >::Sum().
template<class T> void VNL::Vector< T >::Swap (VNL::Vector< T > & that) [inline]
Set this to that and that to this.
References VNL::Vector< T >::data, and VNL::Vector< T >::num_elmts.
template<class T = double> T& VNL::Vector< T >::t () const [inline]
Return fourth element of vector.
template<class T = double> abs_t VNL::Vector< T >::TwoNorm () const [inline]
Return sqrt of sum of squares of values of elements.
Referenced by VNL::Vector< std::complex< double > >::Magnitude(), and VNL::Vector< std::complex< double > >::TwoNorm().
template<class T = double> Vector<T>& VNL::Vector< T >::Update (Vector< T > const & , unsigned int start = 0)
Replaces elements with index begining at start, by values of v. O(n).
Referenced by VNL::SVD< T >::Solve().
template<class T = double> T& VNL::Vector< T >::x () const [inline]
Return first element of vector.
template<class T = double> T& VNL::Vector< T >::y () const [inline]
Return second element of vector.
template<class T = double> T& VNL::Vector< T >::z () const [inline]
Return third element of vector.
Friends And Related Function Documentation
template<class T = double> friend class Matrix< T > [friend]
Member Data Documentation
template<class T = double> T* VNL::Vector< T >::data [protected]
Referenced by VNL::VectorFixed< 3, T >::Apply(), VNL::Vector< T >::Apply(), VNL::Vector< std::complex< double > >::begin(), VNL::Vector< T >::Clear(), VNL::Vector< T >::CopyIn(), VNL::Vector< T >::CopyOut(), VNL::Vector< std::complex< double > >::DataBlock(), VNL::Vector< std::complex< double > >::end(), VNL::Vector< T >::Fill(), VNL::Vector< T >::Flip(), VNL::Vector< T >::Get(), VNL::Vector< std::complex< double > >::IsEmpty(), VNL::Vector< std::complex< double > >::operator()(), VNL::Vector< T >::operator*=(), VNL::Vector< T >::operator+=(), VNL::Vector< T >::operator-(), VNL::Vector< T >::operator-=(), VNL::Vector< T >::operator/=(), VNL::Vector< T >::operator=(), VNL::Vector< std::complex< double > >::operator[](), VNL::Vector< T >::operator_eq(), VNL::Vector< T >::PostMultiply(), VNL::Vector< T >::PreMultiply(), VNL::Vector< T >::Put(), VNL::Vector< T >::Resize(), VNL::Vector< T >::Swap(), VNL::Vector< std::complex< double > >::t(), VNL::Vector< T >::Vector(), VNL::Vector< std::complex< double > >::Vector(), VNL::VectorFixed< 3, T >::VectorFixed(), VNL::VectorRef< double >::VectorRef(), VNL::Vector< std::complex< double > >::x(), VNL::Vector< std::complex< double > >::y(), VNL::Vector< std::complex< double > >::z(), VNL::Vector< std::complex< double > >::~Vector(), and VNL::VectorRef< double >::~VectorRef().
template<class T = double> unsigned VNL::Vector< T >::num_elmts [protected]
Referenced by VNL::VectorFixed< 3, T >::Apply(), VNL::Vector< T >::Apply(), VNL::Vector< T >::Clear(), VNL::Vector< T >::CopyIn(), VNL::Vector< T >::CopyOut(), VNL::Vector< std::complex< double > >::end(), VNL::Vector< T >::Fill(), VNL::Vector< T >::Flip(), VNL::Vector< T >::Get(), VNL::Vector< std::complex< double > >::IsEmpty(), VNL::Vector< T >::operator*=(), VNL::Vector< T >::operator+=(), VNL::Vector< T >::operator-(), VNL::Vector< T >::operator-=(), VNL::Vector< T >::operator/=(), VNL::Vector< T >::operator=(), VNL::Vector< T >::PostMultiply(), VNL::Vector< T >::PreMultiply(), VNL::Vector< T >::Put(), VNL::Vector< T >::Resize(), VNL::Vector< std::complex< double > >::Size(), VNL::Vector< std::complex< double > >::size(), VNL::Vector< T >::Swap(), VNL::Vector< T >::Vector(), VNL::Vector< std::complex< double > >::Vector(), and VNL::VectorRef< double >::VectorRef().
The documentation for this class was generated from the following files:
vector.h
vector.tpp