VW: VW::LocalGTKGLArea Class Reference
VW::LocalGTKGLArea Class Reference
#include <threedtoolgtkglwidget.h>
Public Member Functions
LocalGTKGLArea (ThreeDToolGTKGLWidget *parent)
void draw_impl (GdkRectangle *p0)
gint expose_event_impl (GdkEventExpose *)
gint motion_notify_event_impl (GdkEventMotion *)
gint button_press_event_impl (GdkEventButton *)
gint button_release_event_impl (GdkEventButton *)
Protected Attributes
ThreeDToolGTKGLWidget * parent_ptr
int last_x
int last_y
Constructor & Destructor Documentation
LocalGTKGLArea::LocalGTKGLArea (ThreeDToolGTKGLWidget * parent)
Member Function Documentation
gint LocalGTKGLArea::button_press_event_impl (GdkEventButton * event)
References last_x, last_y, TRUE, and VERBOSE.
gint LocalGTKGLArea::button_release_event_impl (GdkEventButton * event)
References VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::Dragging(), VW::ThreeDToolGLCommon::DragRelease(), last_x, last_y, parent_ptr, TRUE, and VERBOSE.
void LocalGTKGLArea::draw_impl (GdkRectangle * p0)
References VW::ThreeDToolGLCommon::DoDrawing(), parent_ptr, and VERBOSE.
gint LocalGTKGLArea::expose_event_impl (GdkEventExpose * event)
References FALSE, TRUE, and VERBOSE.
gint LocalGTKGLArea::motion_notify_event_impl (GdkEventMotion * event)
References VW::ThreeDToolGLCommon::Dragged(), last_x, last_y, parent_ptr, TRUE, and VERBOSE.
Member Data Documentation
int VW::LocalGTKGLArea::last_x [protected]
Referenced by button_press_event_impl(), button_release_event_impl(), and motion_notify_event_impl().
int VW::LocalGTKGLArea::last_y [protected]
Referenced by button_press_event_impl(), button_release_event_impl(), and motion_notify_event_impl().
ThreeDToolGTKGLWidget* VW::LocalGTKGLArea::parent_ptr [protected]
Referenced by button_release_event_impl(), draw_impl(), and motion_notify_event_impl().
The documentation for this class was generated from the following files:
threedtoolgtkglwidget.h
threedtoolgtkglwidget.cpp