VW: VW::Covariance2D Class Reference
VW::Covariance2D Class Reference
#include <covariance2d.h>
Public Member Functions
Covariance2D ()
Construct and set to identity.
Covariance2D (double a, double b, double c)
Construct from the three parameters of a symmetric 2x2 matrix C = [ a b ] [ b c ].
Covariance2D (const Covariance2D &C)
Covariance2D (const VNL::MatrixFixed< 2, 2, double > &C)
Construct from an arbitrary 2x2 matrix.
void SetIdentity ()
void SetIsotropic (const double variance)
Set to diagonal with equal variances along each axis.
bool IsPositiveDefinite () const
The matrix must be either positive definite or semi-definite.
double Determinant () const
the determinant >= 0.
Covariance2D Inverse () const
If the matrix is positive definite then the inverse is also symmetrical and positive definite (ie a covariance).
VNL::MatrixFixed< 2, 2, double > AsMatrix () const
Get the matrix as a 2x2 VNL::MatrixFixed.
VNL::MatrixFixed< 2, 2, double > InverseMatrix () const
Get the inverse of the matrix as a 2x2 VNL::MatrixFixed.
bool CholeskyDecompose (VNL::MatrixFixed< 2, 2, double > &L) const
Perform a cholesky decomposition, returning the lower triangle L such that C = L*L'.
double GetDistance (const double ex, const double ey) const
Get the distance of this matrix d = (ex ey) C (ex ey)'.
double GetMahalanobisDistance (const double ex, const double ey) const
Get the Mahalanobis distance given errors in x and y d = (ex ey) inv(C) (ex ey)' Note that the inverse makes this a bit expensive, so if you want to use it repeatedly, calculate the inverse matrix explicitly and use the GetDistance() function of the result.
Covariance2D operator* (const double scalar) const
Scale the covariance (must be a positive scalar).
Covariance2D & operator*= (const double scalar)
Scale the covariance (must be a positive scalar).
Covariance2D operator+ (const Covariance2D &C) const
Add a covariances.
Covariance2D & operator+= (const Covariance2D &C)
Add a covariances.
Covariance2D operator/ (const double scalar) const
Scale the covariance (must be a positive scalar).
Covariance2D & operator/= (const double scalar)
Scale the covariance (must be a positive scalar).
VNL::MatrixFixed< 2, 2, double > operator* (const Covariance2D &C) const
Multiplying two covariances can result in a non-symmetric matrix.
double & operator[] (int i)
directly access the data (three doubles) - use with extreme caution
const double & operator[] (int i) const
directly access the data (three doubles) - use with extreme caution
Constructor & Destructor Documentation
VW::Covariance2D::Covariance2D () [inline]
Construct and set to identity.
Referenced by Inverse(), operator*(), operator+(), and operator/().
VW::Covariance2D::Covariance2D (double a, double b, double c) [inline]
Construct from the three parameters of a symmetric 2x2 matrix C = [ a b ] [ b c ].
VW::Covariance2D::Covariance2D (const Covariance2D & C) [inline]
VW::Covariance2D::Covariance2D (const VNL::MatrixFixed< 2, 2, double > & C) [inline, explicit]
Construct from an arbitrary 2x2 matrix.
If the matrix C is not positive semi-definite an assertion failure results.
Member Function Documentation
VNL::MatrixFixed< 2, 2, double > VW::Covariance2D::AsMatrix () const [inline]
Get the matrix as a 2x2 VNL::MatrixFixed.
bool VW::Covariance2D::CholeskyDecompose (VNL::MatrixFixed< 2, 2, double > & L) const
Perform a cholesky decomposition, returning the lower triangle L such that C = L*L'.
This will fail if the matrix is not positive semi-definite, returning false.
References VNL::Matrix< T >::Fill(), and std::sqrt().
Referenced by VW::DrawFunctions::Draw().
double VW::Covariance2D::Determinant () const [inline]
the determinant >= 0.
Cost = 3 flops
Referenced by Inverse(), and InverseMatrix().
double VW::Covariance2D::GetDistance (const double ex, const double ey) const [inline]
Get the distance of this matrix d = (ex ey) C (ex ey)'.
If [ex ey] forms a unit vector, this is the Rayleigh quotient.
double VW::Covariance2D::GetMahalanobisDistance (const double ex, const double ey) const
Get the Mahalanobis distance given errors in x and y d = (ex ey) inv(C) (ex ey)' Note that the inverse makes this a bit expensive, so if you want to use it repeatedly, calculate the inverse matrix explicitly and use the GetDistance() function of the result.
VW::Covariance2D VW::Covariance2D::Inverse () const
If the matrix is positive definite then the inverse is also symmetrical and positive definite (ie a covariance).
Cost = 6 flops
References Covariance2D(), and Determinant().
VNL::MatrixFixed< 2, 2, double > VW::Covariance2D::InverseMatrix () const
Get the inverse of the matrix as a 2x2 VNL::MatrixFixed.
Cost = 6 flops
References Determinant().
bool VW::Covariance2D::IsPositiveDefinite () const
The matrix must be either positive definite or semi-definite.
VNL::MatrixFixed< 2, 2, double > VW::Covariance2D::operator* (const Covariance2D & C) const [inline]
Multiplying two covariances can result in a non-symmetric matrix.
VW::Covariance2D VW::Covariance2D::operator* (const double scalar) const [inline]
Scale the covariance (must be a positive scalar).
References Covariance2D().
VW::Covariance2D & VW::Covariance2D::operator*= (const double scalar) [inline]
Scale the covariance (must be a positive scalar).
VW::Covariance2D VW::Covariance2D::operator+ (const Covariance2D & C) const [inline]
Add a covariances.
References Covariance2D().
VW::Covariance2D & VW::Covariance2D::operator+= (const Covariance2D & C) [inline]
Add a covariances.
VW::Covariance2D VW::Covariance2D::operator/ (const double scalar) const [inline]
Scale the covariance (must be a positive scalar).
References Covariance2D().
VW::Covariance2D & VW::Covariance2D::operator/= (const double scalar) [inline]
Scale the covariance (must be a positive scalar).
const double & VW::Covariance2D::operator[] (int i) const [inline]
directly access the data (three doubles) - use with extreme caution
double & VW::Covariance2D::operator[] (int i) [inline]
directly access the data (three doubles) - use with extreme caution
void VW::Covariance2D::SetIdentity () [inline]
void VW::Covariance2D::SetIsotropic (const double variance) [inline]
Set to diagonal with equal variances along each axis.
The documentation for this class was generated from the following files:
covariance2d.h
covariance2d.cpp