VW: VW::FMatrixComputeNonLinear Class Reference
VW::FMatrixComputeNonLinear Class Reference
#include <fmatrixcomputenonlinear.h>
Public Member Functions
FMatrixComputeNonLinear (double error_tolerance=DEFAULT_TOLERANCE, unsigned int max_iters=DEFAULT_MAXITERS)
bool Compute (VW::FMatrix &result, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1)
Compute a fundamental matrix from two lists of 2D point features.
bool Compute (VW::FMatrix &result, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const std::vector< unsigned int > &whichfeatures)
Constructor & Destructor Documentation
VW::FMatrixComputeNonLinear::FMatrixComputeNonLinear (double error_tolerance = DEFAULT_TOLERANCE, unsigned int max_iters = DEFAULT_MAXITERS) [inline]
Member Function Documentation
bool VW::FMatrixComputeNonLinear::Compute (VW::FMatrix & result, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const std::vector< unsigned int > & whichfeatures)
References VW::FMatrixCompute::GenerateParameterVector(), VNL::LeastSquaresFunction::GetNumberOfUnknowns(), VNL::LevenbergMarquardt::Minimize(), VW::FMatrixCompute::ReconstructTransform(), VNL::NonlinearMinimizer::SetFTolerance(), VNL::NonlinearMinimizer::SetMaxFunctionEvals(), and VERBOSE.
bool VW::FMatrixComputeNonLinear::Compute (VW::FMatrix & result, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1)
Compute a fundamental matrix from two lists of 2D point features.
Minimisation is performed using Levenberg-Marquadt with Sampson distance as the error measure. Note that no normalisation is performed, so its best if you normalise the data before calling this.
Returns:
true for successful minimisation, false otherwise (homography is left untouched in this case).
The documentation for this class was generated from the following files:
fmatrixcomputenonlinear.h
fmatrixcomputenonlinear.cpp