VW: VW::PlesseyOldParams Class Reference
VW::PlesseyOldParams Class Reference
#include <plesseyold.h>
Public Member Functions
PlesseyOldParams ()
PlesseyOldParams (float _strength_threshold, float _gaussian_sigma, unsigned int _patch_size, float _edge_phobia)
virtual ~PlesseyOldParams ()
float GetStrengthThreshold () const
float GetGaussianSigma () const
unsigned int GetPatchSize () const
float GetEdgePhobia () const
virtual void LoadParameterFile (string paramfile=".params")
virtual void SaveParameterFile (string paramfile=".params")
virtual void Set (const float new_strengththreshold, const float new_gaussiansigma, const unsigned int new_patchsize, const float new_edgephobia)
virtual void SetStrengthThreshold (const float new_value)
virtual void SetGaussianSigma (const float new_value)
virtual void SetPatchSize (const unsigned int new_value)
virtual void SetEdgePhobia (const float new_value)
Protected Attributes
float strength_threshold
float gaussian_sigma
unsigned int patch_size
float edge_phobia
Friends
class PlesseyOld
Constructor & Destructor Documentation
VW::PlesseyOldParams::PlesseyOldParams () [inline]
VW::PlesseyOldParams::PlesseyOldParams (float _strength_threshold, float _gaussian_sigma, unsigned int _patch_size, float _edge_phobia) [inline]
virtual VW::PlesseyOldParams::~PlesseyOldParams () [inline, virtual]
Member Function Documentation
float VW::PlesseyOldParams::GetEdgePhobia () const [inline]
References edge_phobia.
float VW::PlesseyOldParams::GetGaussianSigma () const [inline]
References gaussian_sigma.
Referenced by VW::PlesseyOld::Compute().
unsigned int VW::PlesseyOldParams::GetPatchSize () const [inline]
References patch_size.
Referenced by VW::PlesseyOld::Compute().
float VW::PlesseyOldParams::GetStrengthThreshold () const [inline]
References strength_threshold.
Referenced by VW::PlesseyOld::Compute().
void VW::PlesseyOldParams::LoadParameterFile (string paramfile = ".params") [virtual]
References VW::ParameterParser::GetValue().
Referenced by VW::PlesseyOld::PlesseyOld().
void VW::PlesseyOldParams::SaveParameterFile (string paramfile = ".params") [virtual]
References VW::ParameterWriter::AddParameter(), and VW::ParameterWriter::WriteOut().
virtual void VW::PlesseyOldParams::Set (const float new_strengththreshold, const float new_gaussiansigma, const unsigned int new_patchsize, const float new_edgephobia) [inline, virtual]
References edge_phobia, gaussian_sigma, patch_size, and strength_threshold.
virtual void VW::PlesseyOldParams::SetEdgePhobia (const float new_value) [inline, virtual]
virtual void VW::PlesseyOldParams::SetGaussianSigma (const float new_value) [inline, virtual]
References gaussian_sigma.
virtual void VW::PlesseyOldParams::SetPatchSize (const unsigned int new_value) [inline, virtual]
References patch_size.
virtual void VW::PlesseyOldParams::SetStrengthThreshold (const float new_value) [inline, virtual]
References strength_threshold.
Friends And Related Function Documentation
friend class PlesseyOld [friend]
Member Data Documentation
float VW::PlesseyOldParams::edge_phobia [protected]
Referenced by GetEdgePhobia(), and Set().
float VW::PlesseyOldParams::gaussian_sigma [protected]
Referenced by GetGaussianSigma(), Set(), and SetGaussianSigma().
unsigned int VW::PlesseyOldParams::patch_size [protected]
Referenced by GetPatchSize(), Set(), and SetPatchSize().
float VW::PlesseyOldParams::strength_threshold [protected]
Referenced by GetStrengthThreshold(), Set(), and SetStrengthThreshold().
The documentation for this class was generated from the following files:
plesseyold.h
plesseyold.cpp