VW: VW::ImagePatchYUV Class Reference
VW::ImagePatchYUV Class Reference
#include <imagepatchyuv.h>
Public Member Functions
ImagePatchYUV (const unsigned int size=5)
Data is created on construction, so height, width required.
ImagePatchYUV (const unsigned int width, const unsigned int height)
Data is created on construction, so height, width required.
ImagePatchYUV (const ImagePatchYUV &p)
virtual ~ImagePatchYUV ()
void Resize (const unsigned int width, const unsigned int height)
unsigned int GetWidth () const
Return patch width.
unsigned int GetHeight () const
Return patch height.
void SetData (const unsigned int x, const unsigned int y, const VW::PixelYUV< float > &p)
Set one element of data.
VW::PixelYUV< float > GetData (const unsigned int x, const unsigned int y) const
Get one element of data.
std::vector< VW::PixelYUV
< float > >::const_iterator GetRowStart (const unsigned int y) const
std::vector< VW::PixelYUV
< float > >::iterator GetRowStart (const unsigned int y)
VW::PixelYUV< float > GetMean () const
Return the mean of the data.
VNL::MatrixFixed< 3, 3, float > GetCovariance () const
Return the variance of the data around the mean.
float GetZNCC (const VW::ImagePatchYUV &p2) const
Get the ZNCC score with another patch.
virtual bool WriteASCII (std::ostream &stream) const
Stream as plain ASCII.
virtual bool WriteXML (std::ostream &stream, const std::string &name="") const
Stream as XML style ASCII.
virtual bool WriteBinary (std::ostream &stream) const
Stream as binary.
virtual bool ReadASCII (std::istream &stream)
Stream as plain ASCII.
virtual bool ReadXML (std::istream &stream, const std::string &name="")
Stream as XML style ASCII.
virtual bool ReadBinary (std::istream &stream)
Stream as binary.
bool WriteASCIIFile (const std::string &filename) const
Open a file and output as plain ASCII (overwriting any existing contents).
bool WriteXMLFile (const std::string &filename, const std::string &name="") const
Open a file and output as XML-style ASCII (overwriting any existing contents).
bool WriteBinaryFile (const std::string &filename) const
Open a file and output as binary (overwriting any existing contents).
virtual bool ReadASCIIFile (const std::string &filename)
Open a file and input as plain ASCII.
virtual bool ReadXMLFile (const std::string &filename, const std::string &name="")
Open a file and input as XML style ASCII.
virtual bool ReadBinaryFile (const std::string &filename)
Open a file and input as binary.
Detailed Description
Author:
BJ Tordoff
Date:
28/03/2002 @ Brief A storage class for colour (YUV) image patches.
Functions are provided for creating patches from mono images using a supplied image position. If the position is supplied as floating point then bilinear interpolation is used to get the values. This doesn't cost much processing, and Smith:Sinclair:Cipolla:Wood:BMVC1998 indicate that it has some serious effect on the matching. However, I have some reservations about the fairness of their comparisons, so the choice is yours. Note that getting and setting of data is unchecked, so be careful of sizes.
Constructor & Destructor Documentation
VW::ImagePatchYUV::ImagePatchYUV (const unsigned int size = 5) [inline]
Data is created on construction, so height, width required.
VW::ImagePatchYUV::ImagePatchYUV (const unsigned int width, const unsigned int height) [inline]
Data is created on construction, so height, width required.
VW::ImagePatchYUV::ImagePatchYUV (const ImagePatchYUV & p) [inline]
References GetData().
virtual VW::ImagePatchYUV::~ImagePatchYUV () [inline, virtual]
Member Function Documentation
VNL::MatrixFixed< 3, 3, float > VW::ImagePatchYUV::GetCovariance () const [inline]
Return the variance of the data around the mean.
Referenced by GetZNCC().
VW::PixelYUV< float > VW::ImagePatchYUV::GetData (const unsigned int x, const unsigned int y) const [inline]
Get one element of data.
Referenced by ImagePatchYUV().
unsigned int VW::ImagePatchYUV::GetHeight (void) const [inline]
Return patch height.
Referenced by VW::GetImagePatch(), VW::GetInterpolatedImagePatch(), and GetZNCC().
VW::PixelYUV< float > VW::ImagePatchYUV::GetMean () const [inline]
Return the mean of the data.
std::vector< VW::PixelYUV< float > >::iterator VW::ImagePatchYUV::GetRowStart (const unsigned int y) [inline]
std::vector< VW::PixelYUV< float > >::const_iterator VW::ImagePatchYUV::GetRowStart (const unsigned int y) const [inline]
unsigned int VW::ImagePatchYUV::GetWidth (void) const [inline]
Return patch width.
Referenced by VW::GetImagePatch(), VW::GetInterpolatedImagePatch(), and GetZNCC().
float VW::ImagePatchYUV::GetZNCC (const VW::ImagePatchYUV & p2) const
Get the ZNCC score with another patch.
References GetCovariance(), GetHeight(), GetWidth(), VW::IsNaN(), and v.
Referenced by VW::Correlate::Compute().
bool VW::ImagePatchYUV::ReadASCII (std::istream & stream) [inline, virtual]
Stream as plain ASCII.
Implements VW::IOObject.
References Resize().
Referenced by VW::PlesseyCornerYUV::ReadASCII().
bool VW::IOObject::ReadASCIIFile (const std::string & filename) [virtual, inherited]
Open a file and input as plain ASCII.
Open a file and read as plain ASCII.
Once the file is open, the child class's ReadASCII function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadASCII().
bool VW::ImagePatchYUV::ReadBinary (std::istream & stream) [inline, virtual]
Stream as binary.
Implements VW::IOObject.
References Resize(), and v.
Referenced by VW::PlesseyCornerYUV::ReadBinary().
bool VW::IOObject::ReadBinaryFile (const std::string & filename) [virtual, inherited]
Open a file and input as binary.
Open a file and read as binary.
Once the file is open, the child class's ReadBinary function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadBinary().
bool VW::ImagePatchYUV::ReadXML (std::istream & stream, const std::string & name = "") [inline, virtual]
Stream as XML style ASCII.
Implements VW::IOObject.
References VW::FindXMLBlock(), VW::GetXMLBlock(), VW::GetXMLBlockAsNumber(), Resize(), and v.
Referenced by VW::PlesseyCornerYUV::ReadXML().
bool VW::IOObject::ReadXMLFile (const std::string & filename, const std::string & name = "") [virtual, inherited]
Open a file and input as XML style ASCII.
Open a file and read as XML-style ASCII.
Once the file is open, the child class's ReadXML function is used to read the content.
Parameters:
filename the name of the file to open
name the optional name tag-attribute to match ie. data must start <MyClass name="name">
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadXML().
Referenced by VW::ClassifierUV::ClassifierUV(), and VW::FirewireCameraGTK::LoadParameterFile().
void VW::ImagePatchYUV::Resize (const unsigned int width, const unsigned int height) [inline]
Referenced by ReadASCII(), ReadBinary(), ReadXML(), VW::PlesseyCornerYUV::Set(), and VW::PlesseyCornerYUV::SetPatchSize().
void VW::ImagePatchYUV::SetData (const unsigned int x, const unsigned int y, const VW::PixelYUV< float > & p) [inline]
Set one element of data.
Referenced by VW::GetImagePatch(), and VW::GetInterpolatedImagePatch().
bool VW::ImagePatchYUV::WriteASCII (std::ostream & stream) const [inline, virtual]
Stream as plain ASCII.
Implements VW::IOObject.
Referenced by VW::PlesseyCornerYUV::WriteASCII().
bool VW::IOObject::WriteASCIIFile (const std::string & filename) const [inherited]
Open a file and output as plain ASCII (overwriting any existing contents).
Open a file and output as plain ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteASCII function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteASCII().
bool VW::ImagePatchYUV::WriteBinary (std::ostream & stream) const [inline, virtual]
Stream as binary.
Implements VW::IOObject.
References v.
Referenced by VW::PlesseyCornerYUV::WriteBinary().
bool VW::IOObject::WriteBinaryFile (const std::string & filename) const [inherited]
Open a file and output as binary (overwriting any existing contents).
Once the file is open, the child class's WriteBinary function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteBinary().
bool VW::ImagePatchYUV::WriteXML (std::ostream & stream, const std::string & name = "") const [inline, virtual]
Stream as XML style ASCII.
Implements VW::IOObject.
Referenced by VW::PlesseyCornerYUV::WriteXML().
bool VW::IOObject::WriteXMLFile (const std::string & filename, const std::string & name = "") const [inherited]
Open a file and output as XML-style ASCII (overwriting any existing contents).
Open a file and output as XML-style ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteXML function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
name the tag parameter, if required
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteXML().
Referenced by VW::FirewireCameraGTK::SaveParameterFile().
The documentation for this class was generated from the following files:
imagepatchyuv.h
imagepatchyuv.cpp