VW: VW::EssentialMatrixComputeMLESAC Class Reference
VW::EssentialMatrixComputeMLESAC Class Reference
[GeometricAlgorithms]
outlier rejection for essential matrices.
#include <essentialmatrixcomputemlesac.h>
Public Member Functions
EssentialMatrixComputeMLESAC (double image_noise, double search_area, double desired_confidence=99.0)
bool Compute (VW::EssentialMatrix &H, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, std::vector< unsigned int > &inliers)
void SetDesiredConfidence (double desired_confidence)
Set the desired confidence (%).
void SetImageNoise (double image_noise)
Set the expected image noise standard deviation (in pixels).
void SetSearchArea (double search_area)
Set the are searched for each feature.
void SetMaxIterations (unsigned int max_iters)
Set an upper bound on the number of iterations.
Detailed Description
outlier rejection for essential matrices.
Author:
BJ Tordoff
Date:
20/04/2005
Constructor & Destructor Documentation
VW::EssentialMatrixComputeMLESAC::EssentialMatrixComputeMLESAC (double image_noise, double search_area, double desired_confidence = 99.0) [inline]
Member Function Documentation
bool VW::EssentialMatrixComputeMLESAC::Compute (VW::EssentialMatrix & H, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, std::vector< unsigned int > & inliers)
References VW::Normalisation::AsMatrix(), VW::Normalisation::GetScale(), VW::Normalisation::Normalise(), VNL::Matrix< T >::Transpose(), and VERBOSE.
void VW::EssentialMatrixComputeMLESAC::SetDesiredConfidence (double desired_confidence) [inline]
Set the desired confidence (%).
Once this level of confidence is reached sampling will terminate. Note that if max_iters is also set, both will be used.
void VW::EssentialMatrixComputeMLESAC::SetImageNoise (double image_noise) [inline]
Set the expected image noise standard deviation (in pixels).
This is used to determine the Gaussian model for the inlier process.
void VW::EssentialMatrixComputeMLESAC::SetMaxIterations (unsigned int max_iters) [inline]
Set an upper bound on the number of iterations.
If not set (or set to zero), sampling will continue until the desired confidence level is reached.
void VW::EssentialMatrixComputeMLESAC::SetSearchArea (double search_area) [inline]
Set the are searched for each feature.
This determines the uniform distribution used to model the outlier process.
The documentation for this class was generated from the following files:
essentialmatrixcomputemlesac.h
essentialmatrixcomputemlesac.cpp