VW: VW::FirewireCamera Class Reference
VW::FirewireCamera Class Reference
This class is just a convenience wrapper for the various structs which hold info for the cameras.
#include <firewirecamera.h>
Public Member Functions
FirewireCamera ()
FirewireCamera (bool display_messages)
virtual bool SetUpCamera (raw1394handle_t port_handle)
void SetVerbosity (bool display_messages)
bool StartISOTransmission ()
bool StopISOTransmission ()
bool IsISOTransmitting () const
bool SetupDMACapture (dc1394_cameracapture *capture)
bool ReleaseDMACapture (dc1394_cameracapture *capture)
void SetNodeNumber (nodeid_t nn)
nodeid_t GetNodeNumber (void) const
int GetISOChannel (void) const
void SetFirewireCommandHandle (raw1394handle_t command_handle)
Set the Raw1394 handle for sending commands.
void SetFirewireReceiveHandle (raw1394handle_t receive_handle)
Set the Raw1394 handle for receiving images.
raw1394handle_t GetFirewireCommandHandle (void) const
Get the Raw1394 handle for sending commands.
raw1394handle_t GetFirewireReceiveHandle (void) const
Get the Raw1394 handle for receiving images.
std::string GetGUID () const
Get the Global Unique Identifier (GUID) that uniquely specifies this device.
std::string GetVendorString (void) const
std::string GetModelString (void) const
FirewireParams::CameraMode GetImageMode () const
void SetImageMode (FirewireParams::CameraMode new_mode)
int GetImageWidth () const
int GetImageHeight () const
FirewireParams::CameraFramerate GetFramerate (void) const
void SetFramerate (FirewireParams::CameraFramerate new_framerate)
FirewireParams::CameraImageFormat GetImageFormat (void) const
void SetImageFormat (FirewireParams::CameraImageFormat new_image_format)
void UseAutoSettings ()
void UseManualSettings ()
bool HasZoom () const
bool HasFocus () const
bool HasAutoFocus () const
bool HasIris () const
bool HasAutoIris () const
bool HasBrightness () const
bool HasAutoBrightness () const
bool HasGain () const
bool HasAutoGain () const
bool HasExposure () const
bool HasAutoExposure () const
bool HasShutter () const
bool HasAutoShutter () const
bool HasGamma () const
bool HasAutoGamma () const
bool HasSharpness () const
bool HasAutoSharpness () const
bool HasHue () const
bool HasAutoHue () const
bool HasSaturation () const
bool HasAutoSaturation () const
bool HasWhiteBalance () const
bool HasAutoWhiteBalance () const
int GetZoom () const
void GetZoomLimits (int *min_zoom, int *max_zoom) const
int GetFocus () const
void GetFocusLimits (int *min_focus, int *max_focus) const
bool GetAutoFocus () const
int GetIris () const
void GetIrisLimits (int *min_iris, int *max_iris) const
bool GetAutoIris () const
int GetBrightness () const
void GetBrightnessLimits (int *min_gain, int *max_gain) const
bool GetAutoBrightness () const
int GetGain () const
void GetGainLimits (int *min_gain, int *max_gain) const
bool GetAutoGain () const
int GetExposure () const
void GetExposureLimits (int *min_exposure, int *max_exposure) const
bool GetAutoExposure () const
int GetShutter () const
void GetShutterLimits (int *min_shutter, int *max_shutter) const
bool GetAutoShutter () const
int GetGamma () const
void GetGammaLimits (int *min_gamma, int *max_gamma) const
bool GetAutoGamma () const
int GetSharpness () const
void GetSharpnessLimits (int *min_sharpness, int *max_sharpness) const
bool GetAutoSharpness () const
int GetHue () const
void GetHueLimits (int *min_hue, int *max_hue) const
bool GetAutoHue () const
int GetSaturation () const
void GetSaturationLimits (int *min_saturation, int *max_saturation) const
bool GetAutoSaturation () const
int GetWhiteBalanceU () const
int GetWhiteBalanceV () const
void GetWhiteBalanceULimits (int *min_wbu, int *max_wbu) const
void GetWhiteBalanceVLimits (int *min_wbv, int *max_wbv) const
bool GetAutoWhiteBalance () const
virtual void SetZoom (int new_zoom)
virtual void SetFocus (int new_focus)
virtual void SetAutoFocus (bool new_state)
virtual void SetIris (int new_iris)
virtual void SetAutoIris (bool new_state)
virtual void SetGain (int new_gain)
virtual void SetAutoGain (bool new_state)
virtual void SetBrightness (int new_brightness)
virtual void SetAutoBrightness (bool new_state)
virtual void SetExposure (int new_exposure)
virtual void SetAutoExposure (bool new_state)
virtual void SetShutter (int new_shutter)
virtual void SetAutoShutter (bool new_state)
virtual void SetGamma (int new_gamma)
virtual void SetAutoGamma (bool new_state)
virtual void SetSharpness (int new_sharpness)
virtual void SetAutoSharpness (bool new_state)
virtual void SetHue (int new_hue)
virtual void SetAutoHue (bool new_state)
virtual void SetSaturation (int new_saturation)
virtual void SetAutoSaturation (bool new_state)
virtual void SetWhiteBalance (int new_U, int new_V)
virtual void SetAutoWhiteBalance (bool new_state)
bool SwitchOn (void)
bool SwitchOff (void)
void UpdateFeatureByName (const std::string &name, bool automatic, int value, int value2=0)
int GetHistoricPosition (struct timeval time, double *zoom)
void GetOdometryHistory (std::vector< timeval > &time, std::vector< double > &zoom_history)
void FlushHistory (void)
virtual bool WriteASCII (std::ostream &stream) const
Stream as plain ASCII.
virtual bool WriteXML (std::ostream &stream, const std::string &name="") const
Stream as XML style ASCII.
virtual bool WriteBinary (std::ostream &stream) const
Stream as binary.
virtual bool ReadASCII (std::istream &stream)
Stream as plain ASCII.
virtual bool ReadXML (std::istream &stream, const std::string &name="")
Stream as XML style ASCII.
virtual bool ReadBinary (std::istream &stream)
Stream as binary.
bool WriteASCIIFile (const std::string &filename) const
Open a file and output as plain ASCII (overwriting any existing contents).
bool WriteXMLFile (const std::string &filename, const std::string &name="") const
Open a file and output as XML-style ASCII (overwriting any existing contents).
bool WriteBinaryFile (const std::string &filename) const
Open a file and output as binary (overwriting any existing contents).
virtual bool ReadASCIIFile (const std::string &filename)
Open a file and input as plain ASCII.
virtual bool ReadXMLFile (const std::string &filename, const std::string &name="")
Open a file and input as XML style ASCII.
virtual bool ReadBinaryFile (const std::string &filename)
Open a file and input as binary.
Protected Member Functions
void StoreOdometryHistory (struct timeval &time, int zoom)
Protected Attributes
dc1394_camerainfo camera_info
dc1394_feature_set feature_set
dc1394_miscinfo misc_info
bool verbose
int image_width
int image_height
raw1394handle_t receive_handle
int zoom_history [CAMERA_ODOMETRY_HISTORY_LENGTH]
struct timeval time_history [CAMERA_ODOMETRY_HISTORY_LENGTH]
int history_pointer
Detailed Description
This class is just a convenience wrapper for the various structs which hold info for the cameras.
Author:
BJ Tordoff
Date:
02/08/2002
Constructor & Destructor Documentation
VW::FirewireCamera::FirewireCamera () [inline]
VW::FirewireCamera::FirewireCamera (bool display_messages)
Member Function Documentation
void VW::FirewireCamera::FlushHistory (void)
References GetZoom(), history_pointer, time_history, and zoom_history.
bool VW::FirewireCamera::GetAutoBrightness () const [inline]
References feature_set.
Referenced by WriteXML().
bool VW::FirewireCamera::GetAutoExposure () const [inline]
References feature_set.
Referenced by WriteXML().
bool VW::FirewireCamera::GetAutoFocus () const [inline]
References feature_set.
Referenced by WriteXML().
bool VW::FirewireCamera::GetAutoGain () const [inline]
References feature_set.
Referenced by WriteXML().
bool VW::FirewireCamera::GetAutoGamma () const [inline]
References feature_set.
Referenced by WriteXML().
bool VW::FirewireCamera::GetAutoHue () const [inline]
References feature_set.
Referenced by WriteXML().
bool VW::FirewireCamera::GetAutoIris () const [inline]
References feature_set.
Referenced by WriteXML().
bool VW::FirewireCamera::GetAutoSaturation () const [inline]
References feature_set.
Referenced by WriteXML().
bool VW::FirewireCamera::GetAutoSharpness () const [inline]
References feature_set.
Referenced by WriteXML().
bool VW::FirewireCamera::GetAutoShutter () const [inline]
References feature_set.
Referenced by WriteXML().
bool VW::FirewireCamera::GetAutoWhiteBalance () const [inline]
References feature_set.
Referenced by WriteXML().
int VW::FirewireCamera::GetBrightness () const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
void VW::FirewireCamera::GetBrightnessLimits (int * min_gain, int * max_gain) const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
int VW::FirewireCamera::GetExposure () const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
void VW::FirewireCamera::GetExposureLimits (int * min_exposure, int * max_exposure) const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
raw1394handle_t VW::FirewireCamera::GetFirewireCommandHandle (void) const [inline]
Get the Raw1394 handle for sending commands.
References camera_info.
raw1394handle_t VW::FirewireCamera::GetFirewireReceiveHandle (void) const [inline]
Get the Raw1394 handle for receiving images.
References receive_handle.
int VW::FirewireCamera::GetFocus () const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
void VW::FirewireCamera::GetFocusLimits (int * min_focus, int * max_focus) const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
VW::FirewireParams::CameraFramerate VW::FirewireCamera::GetFramerate (void) const [inline]
References misc_info.
Referenced by WriteASCII().
int VW::FirewireCamera::GetGain () const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
void VW::FirewireCamera::GetGainLimits (int * min_gain, int * max_gain) const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
int VW::FirewireCamera::GetGamma () const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
void VW::FirewireCamera::GetGammaLimits (int * min_gamma, int * max_gamma) const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
std::string VW::FirewireCamera::GetGUID () const [inline]
Get the Global Unique Identifier (GUID) that uniquely specifies this device.
References camera_info.
Referenced by WriteASCII().
int VW::FirewireCamera::GetHistoricPosition (struct timeval time, double * zoom)
References CAMERA_ODOMETRY_HISTORY_LENGTH, GetZoom(), history_pointer, StoreOdometryHistory(), time_history, and zoom_history.
int VW::FirewireCamera::GetHue () const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
void VW::FirewireCamera::GetHueLimits (int * min_hue, int * max_hue) const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
VW::FirewireParams::CameraImageFormat VW::FirewireCamera::GetImageFormat (void) const [inline]
References misc_info.
int VW::FirewireCamera::GetImageHeight (void) const [inline]
References image_height.
VW::FirewireParams::CameraMode VW::FirewireCamera::GetImageMode () const [inline]
References misc_info.
Referenced by WriteASCII().
int VW::FirewireCamera::GetImageWidth (void) const [inline]
References image_width.
int VW::FirewireCamera::GetIris () const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
void VW::FirewireCamera::GetIrisLimits (int * min_iris, int * max_iris) const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
int VW::FirewireCamera::GetISOChannel (void) const [inline]
References misc_info.
Referenced by WriteASCII().
std::string VW::FirewireCamera::GetModelString (void) const [inline]
References camera_info.
Referenced by WriteASCII().
nodeid_t VW::FirewireCamera::GetNodeNumber (void) const [inline]
References camera_info.
Referenced by WriteASCII().
void VW::FirewireCamera::GetOdometryHistory (std::vector< timeval > & time, std::vector< double > & zoom_history)
int VW::FirewireCamera::GetSaturation () const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
void VW::FirewireCamera::GetSaturationLimits (int * min_saturation, int * max_saturation) const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
int VW::FirewireCamera::GetSharpness () const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
void VW::FirewireCamera::GetSharpnessLimits (int * min_sharpness, int * max_sharpness) const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
int VW::FirewireCamera::GetShutter () const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
void VW::FirewireCamera::GetShutterLimits (int * min_shutter, int * max_shutter) const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
std::string VW::FirewireCamera::GetVendorString (void) const [inline]
References camera_info.
Referenced by WriteASCII().
int VW::FirewireCamera::GetWhiteBalanceU () const [inline]
References camera_info, and v.
Referenced by WriteASCII(), and WriteXML().
void VW::FirewireCamera::GetWhiteBalanceULimits (int * min_wbu, int * max_wbu) const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
int VW::FirewireCamera::GetWhiteBalanceV () const [inline]
References camera_info, and v.
Referenced by WriteASCII(), and WriteXML().
void VW::FirewireCamera::GetWhiteBalanceVLimits (int * min_wbv, int * max_wbv) const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
int VW::FirewireCamera::GetZoom () const [inline]
References camera_info.
Referenced by FlushHistory(), GetHistoricPosition(), WriteASCII(), and WriteXML().
void VW::FirewireCamera::GetZoomLimits (int * min_zoom, int * max_zoom) const [inline]
References camera_info.
Referenced by WriteASCII(), and WriteXML().
bool VW::FirewireCamera::HasAutoBrightness () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and UseAutoSettings().
bool VW::FirewireCamera::HasAutoExposure () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and UseAutoSettings().
bool VW::FirewireCamera::HasAutoFocus () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and UseAutoSettings().
bool VW::FirewireCamera::HasAutoGain () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and UseAutoSettings().
bool VW::FirewireCamera::HasAutoGamma () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and UseAutoSettings().
bool VW::FirewireCamera::HasAutoHue () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and UseAutoSettings().
bool VW::FirewireCamera::HasAutoIris () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and UseAutoSettings().
bool VW::FirewireCamera::HasAutoSaturation () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and UseAutoSettings().
bool VW::FirewireCamera::HasAutoSharpness () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and UseAutoSettings().
bool VW::FirewireCamera::HasAutoShutter () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and UseAutoSettings().
bool VW::FirewireCamera::HasAutoWhiteBalance () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and UseAutoSettings().
bool VW::FirewireCamera::HasBrightness () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), WriteASCII(), and WriteXML().
bool VW::FirewireCamera::HasExposure () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), WriteASCII(), and WriteXML().
bool VW::FirewireCamera::HasFocus () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), WriteASCII(), and WriteXML().
bool VW::FirewireCamera::HasGain () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), WriteASCII(), and WriteXML().
bool VW::FirewireCamera::HasGamma () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), WriteASCII(), and WriteXML().
bool VW::FirewireCamera::HasHue () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), WriteASCII(), and WriteXML().
bool VW::FirewireCamera::HasIris () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), WriteASCII(), and WriteXML().
bool VW::FirewireCamera::HasSaturation () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), WriteASCII(), and WriteXML().
bool VW::FirewireCamera::HasSharpness () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), WriteASCII(), and WriteXML().
bool VW::FirewireCamera::HasShutter () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), WriteASCII(), and WriteXML().
bool VW::FirewireCamera::HasWhiteBalance () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), WriteASCII(), and WriteXML().
bool VW::FirewireCamera::HasZoom () const [inline]
References feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), WriteASCII(), and WriteXML().
bool VW::FirewireCamera::IsISOTransmitting () const [inline]
References misc_info.
bool VW::FirewireCamera::ReadASCII (std::istream & stream) [virtual]
Stream as plain ASCII.
Parameters:
stream the input stream to read from
Returns:
true if successfully read, false if there are problems
Implements VW::IOObject.
bool VW::IOObject::ReadASCIIFile (const std::string & filename) [virtual, inherited]
Open a file and input as plain ASCII.
Open a file and read as plain ASCII.
Once the file is open, the child class's ReadASCII function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadASCII().
bool VW::FirewireCamera::ReadBinary (std::istream & stream) [virtual]
Stream as binary.
Parameters:
stream the input stream to read from
Returns:
true if successfully read, false if there are problems
Implements VW::IOObject.
bool VW::IOObject::ReadBinaryFile (const std::string & filename) [virtual, inherited]
Open a file and input as binary.
Open a file and read as binary.
Once the file is open, the child class's ReadBinary function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadBinary().
bool VW::FirewireCamera::ReadXML (std::istream & stream, const std::string & name = "") [virtual]
Stream as XML style ASCII.
Parameters:
stream the input stream to read from
name if specified, the found tag must have a NAME= parameter that matches
Returns:
true if successfully read, false if there are problems
Implements VW::IOObject.
References VW::FindXMLBlock(), VW::GetXMLBlock(), and UpdateFeatureByName().
bool VW::IOObject::ReadXMLFile (const std::string & filename, const std::string & name = "") [virtual, inherited]
Open a file and input as XML style ASCII.
Open a file and read as XML-style ASCII.
Once the file is open, the child class's ReadXML function is used to read the content.
Parameters:
filename the name of the file to open
name the optional name tag-attribute to match ie. data must start <MyClass name="name">
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadXML().
Referenced by VW::ClassifierUV::ClassifierUV(), and VW::FirewireCameraGTK::LoadParameterFile().
bool VW::FirewireCamera::ReleaseDMACapture (dc1394_cameracapture * capture)
References camera_info, VW::FirewireParams::FPS_1_875, misc_info, and verbose.
void VW::FirewireCamera::SetAutoBrightness (bool new_state) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info, and feature_set.
Referenced by UseAutoSettings(), and UseManualSettings().
void VW::FirewireCamera::SetAutoExposure (bool new_state) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info, and feature_set.
Referenced by UseAutoSettings(), and UseManualSettings().
void VW::FirewireCamera::SetAutoFocus (bool new_state) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info, and feature_set.
Referenced by UseAutoSettings(), and UseManualSettings().
void VW::FirewireCamera::SetAutoGain (bool new_state) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info, and feature_set.
Referenced by UseAutoSettings(), and UseManualSettings().
void VW::FirewireCamera::SetAutoGamma (bool new_state) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info, and feature_set.
Referenced by UseAutoSettings(), and UseManualSettings().
void VW::FirewireCamera::SetAutoHue (bool new_state) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info, and feature_set.
Referenced by UseAutoSettings(), and UseManualSettings().
void VW::FirewireCamera::SetAutoIris (bool new_state) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info, and feature_set.
Referenced by UseAutoSettings(), and UseManualSettings().
void VW::FirewireCamera::SetAutoSaturation (bool new_state) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info, and feature_set.
Referenced by UseAutoSettings(), and UseManualSettings().
void VW::FirewireCamera::SetAutoSharpness (bool new_state) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info, and feature_set.
Referenced by UseAutoSettings(), and UseManualSettings().
void VW::FirewireCamera::SetAutoShutter (bool new_state) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info, and feature_set.
Referenced by UseAutoSettings(), and UseManualSettings().
void VW::FirewireCamera::SetAutoWhiteBalance (bool new_state) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info, and feature_set.
Referenced by UseAutoSettings(), and UseManualSettings().
void VW::FirewireCamera::SetBrightness (int new_brightness) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info.
void VW::FirewireCamera::SetExposure (int new_exposure) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info.
void VW::FirewireCamera::SetFirewireCommandHandle (raw1394handle_t command_handle) [inline]
Set the Raw1394 handle for sending commands.
Note that receiveing images and sending commands use different handles to avoid conflicts.
References camera_info.
void VW::FirewireCamera::SetFirewireReceiveHandle (raw1394handle_t receive_handle) [inline]
Set the Raw1394 handle for receiving images.
Note that receiveing images and sending commands use different handles to avoid conflicts.
void VW::FirewireCamera::SetFocus (int new_focus) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info.
void VW::FirewireCamera::SetFramerate (FirewireParams::CameraFramerate new_framerate) [inline]
References camera_info, and misc_info.
void VW::FirewireCamera::SetGain (int new_gain) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info.
void VW::FirewireCamera::SetGamma (int new_gamma) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info.
void VW::FirewireCamera::SetHue (int new_hue) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info.
void VW::FirewireCamera::SetImageFormat (FirewireParams::CameraImageFormat new_image_format) [inline]
References camera_info, and misc_info.
Referenced by SetImageMode().
void VW::FirewireCamera::SetImageMode (FirewireParams::CameraMode new_mode)
References camera_info, VW::FirewireParams::F_VGA_NONCOMPRESSED, image_height, image_width, VW::FirewireParams::M_160x120_YUV444, VW::FirewireParams::M_320x240_YUV422, VW::FirewireParams::M_640x480_MONO, VW::FirewireParams::M_640x480_RGB, VW::FirewireParams::M_640x480_YUV411, VW::FirewireParams::M_640x480_YUV422, misc_info, and SetImageFormat().
void VW::FirewireCamera::SetIris (int new_iris) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info.
void VW::FirewireCamera::SetNodeNumber (nodeid_t nn) [inline]
References camera_info.
void VW::FirewireCamera::SetSaturation (int new_saturation) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info.
void VW::FirewireCamera::SetSharpness (int new_sharpness) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info.
void VW::FirewireCamera::SetShutter (int new_shutter) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info.
bool VW::FirewireCamera::SetUpCamera (raw1394handle_t port_handle) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info, feature_set, misc_info, verbose, and VERBOSE.
bool VW::FirewireCamera::SetupDMACapture (dc1394_cameracapture * capture)
References camera_info, FIREWIRE_VIDEO_DEVICE, VW::FirewireParams::FPS_1_875, misc_info, NUM_DMA_BUFFERS, and VERBOSE.
void VW::FirewireCamera::SetVerbosity (bool display_messages) [inline]
References verbose.
void VW::FirewireCamera::SetWhiteBalance (int new_U, int new_V) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info, and v.
void VW::FirewireCamera::SetZoom (int new_zoom) [virtual]
Reimplemented in VW::FirewireCameraGTK.
References camera_info.
bool VW::FirewireCamera::StartISOTransmission (void)
References camera_info, misc_info, receive_handle, and verbose.
bool VW::FirewireCamera::StopISOTransmission (void)
References camera_info, misc_info, and verbose.
void VW::FirewireCamera::StoreOdometryHistory (struct timeval & time, int zoom) [inline, protected]
References CAMERA_ODOMETRY_HISTORY_LENGTH, history_pointer, time_history, and zoom_history.
Referenced by GetHistoricPosition().
bool VW::FirewireCamera::SwitchOff (void) [inline]
References camera_info.
bool VW::FirewireCamera::SwitchOn (void) [inline]
References camera_info.
void VW::FirewireCamera::UpdateFeatureByName (const std::string & name, bool automatic, int value, int value2 = 0)
Referenced by ReadXML().
void VW::FirewireCamera::UseAutoSettings ()
Reimplemented in VW::FirewireCameraGTK.
References HasAutoBrightness(), HasAutoExposure(), HasAutoFocus(), HasAutoGain(), HasAutoGamma(), HasAutoHue(), HasAutoIris(), HasAutoSaturation(), HasAutoSharpness(), HasAutoShutter(), HasAutoWhiteBalance(), SetAutoBrightness(), SetAutoExposure(), SetAutoFocus(), SetAutoGain(), SetAutoGamma(), SetAutoHue(), SetAutoIris(), SetAutoSaturation(), SetAutoSharpness(), SetAutoShutter(), and SetAutoWhiteBalance().
void VW::FirewireCamera::UseManualSettings ()
Reimplemented in VW::FirewireCameraGTK.
References SetAutoBrightness(), SetAutoExposure(), SetAutoFocus(), SetAutoGain(), SetAutoGamma(), SetAutoHue(), SetAutoIris(), SetAutoSaturation(), SetAutoSharpness(), SetAutoShutter(), and SetAutoWhiteBalance().
bool VW::FirewireCamera::WriteASCII (std::ostream & stream) const [virtual]
Stream as plain ASCII.
Parameters:
stream the output stream to write to
Returns:
true if successfully written, false if there are problems
Implements VW::IOObject.
References VW::FirewireParams::FPS_15, VW::FirewireParams::FPS_1_875, VW::FirewireParams::FPS_30, VW::FirewireParams::FPS_3_75, VW::FirewireParams::FPS_60, VW::FirewireParams::FPS_7_5, GetBrightness(), GetBrightnessLimits(), GetExposure(), GetExposureLimits(), GetFocus(), GetFocusLimits(), GetFramerate(), GetGain(), GetGainLimits(), GetGamma(), GetGammaLimits(), GetGUID(), GetHue(), GetHueLimits(), GetImageMode(), GetIris(), GetIrisLimits(), GetISOChannel(), GetModelString(), GetNodeNumber(), GetSaturation(), GetSaturationLimits(), GetSharpness(), GetSharpnessLimits(), GetShutter(), GetShutterLimits(), GetVendorString(), GetWhiteBalanceU(), GetWhiteBalanceULimits(), GetWhiteBalanceV(), GetWhiteBalanceVLimits(), GetZoom(), GetZoomLimits(), HasBrightness(), HasExposure(), HasFocus(), HasGain(), HasGamma(), HasHue(), HasIris(), HasSaturation(), HasSharpness(), HasShutter(), HasWhiteBalance(), HasZoom(), VW::FirewireParams::M_160x120_YUV444, VW::FirewireParams::M_320x240_YUV422, VW::FirewireParams::M_640x480_MONO, VW::FirewireParams::M_640x480_RGB, VW::FirewireParams::M_640x480_YUV411, and VW::FirewireParams::M_640x480_YUV422.
bool VW::IOObject::WriteASCIIFile (const std::string & filename) const [inherited]
Open a file and output as plain ASCII (overwriting any existing contents).
Open a file and output as plain ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteASCII function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteASCII().
bool VW::FirewireCamera::WriteBinary (std::ostream & stream) const [virtual]
Stream as binary.
Parameters:
stream the output stream to write to
Returns:
true if successfully written, false if there are problems
Implements VW::IOObject.
bool VW::IOObject::WriteBinaryFile (const std::string & filename) const [inherited]
Open a file and output as binary (overwriting any existing contents).
Once the file is open, the child class's WriteBinary function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteBinary().
bool VW::FirewireCamera::WriteXML (std::ostream & stream, const std::string & name = "") const [virtual]
Stream as XML style ASCII.
Parameters:
stream the output stream to write to
name if specified, the class will be given a NAME= parameter
Returns:
true if successfully written, false if there are problems
Implements VW::IOObject.
References GetAutoBrightness(), GetAutoExposure(), GetAutoFocus(), GetAutoGain(), GetAutoGamma(), GetAutoHue(), GetAutoIris(), GetAutoSaturation(), GetAutoSharpness(), GetAutoShutter(), GetAutoWhiteBalance(), GetBrightness(), GetBrightnessLimits(), GetExposure(), GetExposureLimits(), GetFocus(), GetFocusLimits(), GetGain(), GetGainLimits(), GetGamma(), GetGammaLimits(), GetHue(), GetHueLimits(), GetIris(), GetIrisLimits(), GetSaturation(), GetSaturationLimits(), GetSharpness(), GetSharpnessLimits(), GetShutter(), GetShutterLimits(), GetWhiteBalanceU(), GetWhiteBalanceULimits(), GetWhiteBalanceV(), GetWhiteBalanceVLimits(), GetZoom(), GetZoomLimits(), HasBrightness(), HasExposure(), HasFocus(), HasGain(), HasGamma(), HasHue(), HasIris(), HasSaturation(), HasSharpness(), HasShutter(), HasWhiteBalance(), HasZoom(), WriteFeatureXML(), and WriteWhiteBalanceXML().
bool VW::IOObject::WriteXMLFile (const std::string & filename, const std::string & name = "") const [inherited]
Open a file and output as XML-style ASCII (overwriting any existing contents).
Open a file and output as XML-style ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteXML function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
name the tag parameter, if required
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteXML().
Referenced by VW::FirewireCameraGTK::SaveParameterFile().
Member Data Documentation
dc1394_camerainfo VW::FirewireCamera::camera_info [protected]
Referenced by GetBrightness(), GetBrightnessLimits(), GetExposure(), GetExposureLimits(), GetFirewireCommandHandle(), GetFocus(), GetFocusLimits(), GetGain(), GetGainLimits(), GetGamma(), GetGammaLimits(), GetGUID(), GetHue(), GetHueLimits(), GetIris(), GetIrisLimits(), GetModelString(), GetNodeNumber(), GetSaturation(), GetSaturationLimits(), GetSharpness(), GetSharpnessLimits(), GetShutter(), GetShutterLimits(), GetVendorString(), GetWhiteBalanceU(), GetWhiteBalanceULimits(), GetWhiteBalanceV(), GetWhiteBalanceVLimits(), GetZoom(), GetZoomLimits(), ReleaseDMACapture(), SetAutoBrightness(), SetAutoExposure(), SetAutoFocus(), SetAutoGain(), SetAutoGamma(), SetAutoHue(), SetAutoIris(), SetAutoSaturation(), SetAutoSharpness(), SetAutoShutter(), SetAutoWhiteBalance(), SetBrightness(), SetExposure(), SetFirewireCommandHandle(), SetFocus(), SetFramerate(), SetGain(), SetGamma(), SetHue(), SetImageFormat(), SetImageMode(), SetIris(), SetNodeNumber(), SetSaturation(), SetSharpness(), SetShutter(), SetUpCamera(), SetupDMACapture(), SetWhiteBalance(), SetZoom(), StartISOTransmission(), StopISOTransmission(), SwitchOff(), and SwitchOn().
dc1394_feature_set VW::FirewireCamera::feature_set [protected]
Referenced by GetAutoBrightness(), GetAutoExposure(), GetAutoFocus(), GetAutoGain(), GetAutoGamma(), GetAutoHue(), GetAutoIris(), GetAutoSaturation(), GetAutoSharpness(), GetAutoShutter(), GetAutoWhiteBalance(), HasAutoBrightness(), HasAutoExposure(), HasAutoFocus(), HasAutoGain(), HasAutoGamma(), HasAutoHue(), HasAutoIris(), HasAutoSaturation(), HasAutoSharpness(), HasAutoShutter(), HasAutoWhiteBalance(), HasBrightness(), HasExposure(), HasFocus(), HasGain(), HasGamma(), HasHue(), HasIris(), HasSaturation(), HasSharpness(), HasShutter(), HasWhiteBalance(), HasZoom(), SetAutoBrightness(), SetAutoExposure(), SetAutoFocus(), SetAutoGain(), SetAutoGamma(), SetAutoHue(), SetAutoIris(), SetAutoSaturation(), SetAutoSharpness(), SetAutoShutter(), SetAutoWhiteBalance(), and SetUpCamera().
int VW::FirewireCamera::history_pointer [protected]
Referenced by FlushHistory(), GetHistoricPosition(), and StoreOdometryHistory().
int VW::FirewireCamera::image_height [protected]
Referenced by GetImageHeight(), and SetImageMode().
int VW::FirewireCamera::image_width [protected]
Referenced by GetImageWidth(), and SetImageMode().
dc1394_miscinfo VW::FirewireCamera::misc_info [protected]
Referenced by GetFramerate(), GetImageFormat(), GetImageMode(), GetISOChannel(), IsISOTransmitting(), ReleaseDMACapture(), SetFramerate(), SetImageFormat(), SetImageMode(), SetUpCamera(), SetupDMACapture(), StartISOTransmission(), and StopISOTransmission().
raw1394handle_t VW::FirewireCamera::receive_handle [protected]
Referenced by GetFirewireReceiveHandle(), and StartISOTransmission().
struct timeval VW::FirewireCamera::time_history[CAMERA_ODOMETRY_HISTORY_LENGTH] [read, protected]
Referenced by FlushHistory(), GetHistoricPosition(), and StoreOdometryHistory().
bool VW::FirewireCamera::verbose [protected]
Referenced by ReleaseDMACapture(), SetUpCamera(), SetVerbosity(), StartISOTransmission(), and StopISOTransmission().
int VW::FirewireCamera::zoom_history[CAMERA_ODOMETRY_HISTORY_LENGTH] [protected]
Referenced by FlushHistory(), GetHistoricPosition(), and StoreOdometryHistory().
The documentation for this class was generated from the following files:
firewirecamera.h
firewirecamera.cpp