VW: VW::CalibrationMatrix Class Reference
VW::CalibrationMatrix Class Reference
[GeometricObjects]
A class to store the camera internal calibration.
#include <calibrationmatrix.h>
Public Member Functions
CalibrationMatrix ()
Construct and set to identity.
CalibrationMatrix (const CalibrationMatrix &C)
Construct from another rotation matrix.
CalibrationMatrix (const double focal_length, const double aspect_ratio, const double skew, const double principle_point_x, const double principle_point_y)
Set from list of params.
virtual ~CalibrationMatrix ()
void Set (const double focal_length, const double aspect_ratio, const double skew, const double principle_point_x, const double principle_point_y)
Set from list of params.
void Set (const VNL::MatrixFixed< 3, 3, double > &M)
Set from 3x3 matrix (must be upper triangular).
void SetIdentity ()
Set to the identity matrix.
double GetFocalLength () const
double GetAspectRatio () const
Aspect ratio is f_y/f_x.
double GetSkew () const
double GetPrincipalPointX () const
double GetPrincipalPointY () const
VW::Point2D GetPrincipalPoint () const
void SetFocalLength (const double f)
void SetAspectRatio (const double a)
Aspect ratio is f_y/f_x and must be positive.
void SetSkew (const double s)
void SetPrincipalPointX (const double px)
void SetPrincipalPointY (const double py)
void SetPrincipalPoint (const VW::Point2D &p)
VW::CalibrationMatrix Inverse () const
Return the inverse of the calibration (which is also a valid calibration!).
VNL::MatrixFixed< 3, 3, double > AsMatrix () const
Return as a 3x3 (upper triangular) matrix.
VNL::MatrixFixed< 3, 3, double > InverseMatrix () const
Return the inverse as a 3x3 (upper triangular) matrix.
VNL::MatrixFixed< 3, 3, double > TransposeMatrix () const
Return the transpose as a 3x3 matrix.
VNL::MatrixFixed< 3, 3, double > operator* (const VNL::MatrixFixed< 3, 3, double > &M) const
VW::Vector3D operator* (const VW::Vector3D &v) const
Multiply as a non-homogeneous 3-vector.
VW::Vector2D operator* (const VW::Vector2D &v) const
Multiply a 2-vector homogeneously.
VNL::MatrixFixed< 2, 2, double > Map (const VNL::MatrixFixed< 2, 2, double > &M) const
Map a 2x2 matrix homogeneously into pixel coords as K*M*K' (2x2 part only).
bool WriteASCII (std::ostream &stream) const
Stream as plain ASCII.
bool WriteXML (std::ostream &stream, const std::string &name="") const
Stream as XML style ASCII.
bool WriteBinary (std::ostream &stream) const
Stream as binary.
bool ReadASCII (std::istream &stream)
Stream as plain ASCII.
bool ReadXML (std::istream &stream, const std::string &name="")
Stream as XML style ASCII.
bool ReadBinary (std::istream &stream)
Stream as binary.
bool WriteASCIIFile (const std::string &filename) const
Open a file and output as plain ASCII (overwriting any existing contents).
bool WriteXMLFile (const std::string &filename, const std::string &name="") const
Open a file and output as XML-style ASCII (overwriting any existing contents).
bool WriteBinaryFile (const std::string &filename) const
Open a file and output as binary (overwriting any existing contents).
virtual bool ReadASCIIFile (const std::string &filename)
Open a file and input as plain ASCII.
virtual bool ReadXMLFile (const std::string &filename, const std::string &name="")
Open a file and input as XML style ASCII.
virtual bool ReadBinaryFile (const std::string &filename)
Open a file and input as binary.
Protected Attributes
double _f
double _a
double _s
double _px
double _py
Detailed Description
A class to store the camera internal calibration.
Date:
21/08/2003
Author:
BJ Tordoff Whilst this is mostly just and ordinary VW::MatrixFixed, it has some added functions for faster computation taking advantage of the known zeros.
Constructor & Destructor Documentation
VW::CalibrationMatrix::CalibrationMatrix () [inline]
Construct and set to identity.
Referenced by Inverse().
VW::CalibrationMatrix::CalibrationMatrix (const CalibrationMatrix & C) [inline]
Construct from another rotation matrix.
VW::CalibrationMatrix::CalibrationMatrix (const double focal_length, const double aspect_ratio, const double skew, const double principle_point_x, const double principle_point_y) [inline]
Set from list of params.
virtual VW::CalibrationMatrix::~CalibrationMatrix () [inline, virtual]
Member Function Documentation
VNL::MatrixFixed< 3, 3, double > VW::CalibrationMatrix::AsMatrix () const [inline]
Return as a 3x3 (upper triangular) matrix.
References _a, _f, _px, _py, and _s.
double VW::CalibrationMatrix::GetAspectRatio () const [inline]
Aspect ratio is f_y/f_x.
References _a.
Referenced by VW::CalibrationTable::AddCalibrationData(), VW::Normalisation::Normalise(), VW::ThreeDToolGLCommon::SetCameraParameters(), VW::PMatrixCompute::TransformToParamVec(), and VW::Normalisation::UnNormalise().
double VW::CalibrationMatrix::GetFocalLength () const [inline]
References _f.
Referenced by VW::CalibrationTable::AddCalibrationData(), VW::Normalisation::Normalise(), VW::ThreeDToolGLCommon::SetCameraParameters(), VW::PMatrixCompute::TransformToParamVec(), and VW::Normalisation::UnNormalise().
VW::Point2D VW::CalibrationMatrix::GetPrincipalPoint () const [inline]
References _px, and _py.
double VW::CalibrationMatrix::GetPrincipalPointX () const [inline]
References _px.
Referenced by VW::CalibrationTable::AddCalibrationData(), VW::Normalisation::Normalise(), VW::ThreeDToolGLCommon::SetCameraParameters(), VW::PMatrixCompute::TransformToParamVec(), and VW::Normalisation::UnNormalise().
double VW::CalibrationMatrix::GetPrincipalPointY () const [inline]
References _py.
Referenced by VW::CalibrationTable::AddCalibrationData(), VW::Normalisation::Normalise(), VW::ThreeDToolGLCommon::SetCameraParameters(), VW::PMatrixCompute::TransformToParamVec(), and VW::Normalisation::UnNormalise().
double VW::CalibrationMatrix::GetSkew () const [inline]
References _s.
Referenced by VW::CalibrationTable::AddCalibrationData(), VW::Normalisation::Normalise(), VW::PMatrixCompute::TransformToParamVec(), and VW::Normalisation::UnNormalise().
VW::CalibrationMatrix VW::CalibrationMatrix::Inverse () const [inline]
Return the inverse of the calibration (which is also a valid calibration!).
References _a, _f, _px, _py, _s, and CalibrationMatrix().
Referenced by VW::ThreePointPose::ComputeJacobian(), VW::ThreePointPose::ComputeJacobians(), and VW::ThreePointPose::ThreePointPose().
VNL::MatrixFixed< 3, 3, double > VW::CalibrationMatrix::InverseMatrix () const [inline]
Return the inverse as a 3x3 (upper triangular) matrix.
Note that this is much faster than getting the matrix then inverting it.
References _a, _f, _px, _py, and _s.
VNL::MatrixFixed< 2, 2, double > VW::CalibrationMatrix::Map (const VNL::MatrixFixed< 2, 2, double > & M) const [inline]
Map a 2x2 matrix homogeneously into pixel coords as K*M*K' (2x2 part only).
References _a, _f, and _s.
VW::Vector2D VW::CalibrationMatrix::operator* (const VW::Vector2D & v) const [inline]
Multiply a 2-vector homogeneously.
References _a, _f, _px, _py, _s, VW::Point2D::GetX(), VW::Point2D::GetY(), VW::Point2D::SetX(), and VW::Point2D::SetY().
VW::Vector3D VW::CalibrationMatrix::operator* (const VW::Vector3D & v) const [inline]
Multiply as a non-homogeneous 3-vector.
References _a, _f, _px, _py, _s, VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), VW::Point3D::SetX(), VW::Point3D::SetY(), and VW::Point3D::SetZ().
VNL::MatrixFixed< 3, 3, double > VW::CalibrationMatrix::operator* (const VNL::MatrixFixed< 3, 3, double > & M) const [inline]
References _a, _f, _px, _py, and _s.
bool VW::CalibrationMatrix::ReadASCII (std::istream & stream) [inline, virtual]
Stream as plain ASCII.
Parameters:
stream the input stream to read from
Returns:
true if successfully read, false if there are problems
Implements VW::IOObject.
References _a, _f, _px, _py, and _s.
bool VW::IOObject::ReadASCIIFile (const std::string & filename) [virtual, inherited]
Open a file and input as plain ASCII.
Open a file and read as plain ASCII.
Once the file is open, the child class's ReadASCII function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadASCII().
bool VW::CalibrationMatrix::ReadBinary (std::istream & stream) [inline, virtual]
Stream as binary.
Parameters:
stream the input stream to read from
Returns:
true if successfully read, false if there are problems
Implements VW::IOObject.
References _a, _f, _px, _py, and _s.
bool VW::IOObject::ReadBinaryFile (const std::string & filename) [virtual, inherited]
Open a file and input as binary.
Open a file and read as binary.
Once the file is open, the child class's ReadBinary function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadBinary().
bool VW::CalibrationMatrix::ReadXML (std::istream & stream, const std::string & name = "") [inline, virtual]
Stream as XML style ASCII.
Parameters:
stream the input stream to read from
name if specified, the found tag must have a NAME= parameter that matches
Returns:
true if successfully read, false if there are problems
Implements VW::IOObject.
References _a, _f, _px, _py, _s, VW::FindXMLBlock(), and VW::GetXMLBlock().
bool VW::IOObject::ReadXMLFile (const std::string & filename, const std::string & name = "") [virtual, inherited]
Open a file and input as XML style ASCII.
Open a file and read as XML-style ASCII.
Once the file is open, the child class's ReadXML function is used to read the content.
Parameters:
filename the name of the file to open
name the optional name tag-attribute to match ie. data must start <MyClass name="name">
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadXML().
Referenced by VW::ClassifierUV::ClassifierUV(), and VW::FirewireCameraGTK::LoadParameterFile().
void VW::CalibrationMatrix::Set (const VNL::MatrixFixed< 3, 3, double > & M) [inline]
Set from 3x3 matrix (must be upper triangular).
References _a, _f, _px, _py, and _s.
void VW::CalibrationMatrix::Set (const double focal_length, const double aspect_ratio, const double skew, const double principle_point_x, const double principle_point_y) [inline]
Set from list of params.
References _a, _f, _px, _py, and _s.
Referenced by VW::ProjectionMatrix::Decompose().
void VW::CalibrationMatrix::SetAspectRatio (const double a) [inline]
Aspect ratio is f_y/f_x and must be positive.
References _a.
Referenced by VW::CalibrationTable::GetCalibrationMatrix(), and VW::PMatrixCompute::TransformToParamVec().
void VW::CalibrationMatrix::SetFocalLength (const double f) [inline]
References _f.
Referenced by VW::CalibrationTable::GetCalibrationMatrix().
void VW::CalibrationMatrix::SetIdentity () [inline]
Set to the identity matrix.
References _a, _f, _px, _py, and _s.
Referenced by VW::ProjectionMatrix::Decompose().
void VW::CalibrationMatrix::SetPrincipalPoint (const VW::Point2D & p) [inline]
References _px, _py, VW::Point2D::GetX(), and VW::Point2D::GetY().
void VW::CalibrationMatrix::SetPrincipalPointX (const double px) [inline]
References _px.
Referenced by VW::CalibrationTable::GetCalibrationMatrix().
void VW::CalibrationMatrix::SetPrincipalPointY (const double py) [inline]
References _py.
Referenced by VW::CalibrationTable::GetCalibrationMatrix().
void VW::CalibrationMatrix::SetSkew (const double s) [inline]
References _s.
Referenced by VW::CalibrationTable::GetCalibrationMatrix(), and VW::PMatrixCompute::TransformToParamVec().
VNL::MatrixFixed< 3, 3, double > VW::CalibrationMatrix::TransposeMatrix () const [inline]
Return the transpose as a 3x3 matrix.
References _a, _f, _px, _py, and _s.
bool VW::CalibrationMatrix::WriteASCII (std::ostream & stream) const [inline, virtual]
Stream as plain ASCII.
Parameters:
stream the output stream to write to
Returns:
true if successfully written, false if there are problems
Implements VW::IOObject.
References _a, _f, _px, _py, and _s.
bool VW::IOObject::WriteASCIIFile (const std::string & filename) const [inherited]
Open a file and output as plain ASCII (overwriting any existing contents).
Open a file and output as plain ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteASCII function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteASCII().
bool VW::CalibrationMatrix::WriteBinary (std::ostream & stream) const [inline, virtual]
Stream as binary.
Parameters:
stream the output stream to write to
Returns:
true if successfully written, false if there are problems
Implements VW::IOObject.
References _a, _f, _px, _py, and _s.
bool VW::IOObject::WriteBinaryFile (const std::string & filename) const [inherited]
Open a file and output as binary (overwriting any existing contents).
Once the file is open, the child class's WriteBinary function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteBinary().
bool VW::CalibrationMatrix::WriteXML (std::ostream & stream, const std::string & name = "") const [inline, virtual]
Stream as XML style ASCII.
Parameters:
stream the output stream to write to
name if specified, the class will be given a NAME= parameter
Returns:
true if successfully written, false if there are problems
Implements VW::IOObject.
References _a, _f, _px, _py, and _s.
bool VW::IOObject::WriteXMLFile (const std::string & filename, const std::string & name = "") const [inherited]
Open a file and output as XML-style ASCII (overwriting any existing contents).
Open a file and output as XML-style ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteXML function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
name the tag parameter, if required
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteXML().
Referenced by VW::FirewireCameraGTK::SaveParameterFile().
Member Data Documentation
double VW::CalibrationMatrix::_a [protected]
Referenced by AsMatrix(), GetAspectRatio(), Inverse(), InverseMatrix(), Map(), operator*(), ReadASCII(), ReadBinary(), ReadXML(), Set(), SetAspectRatio(), SetIdentity(), TransposeMatrix(), WriteASCII(), WriteBinary(), and WriteXML().
double VW::CalibrationMatrix::_f [protected]
Referenced by AsMatrix(), GetFocalLength(), Inverse(), InverseMatrix(), Map(), operator*(), ReadASCII(), ReadBinary(), ReadXML(), Set(), SetFocalLength(), SetIdentity(), TransposeMatrix(), WriteASCII(), WriteBinary(), and WriteXML().
double VW::CalibrationMatrix::_px [protected]
Referenced by AsMatrix(), GetPrincipalPoint(), GetPrincipalPointX(), Inverse(), InverseMatrix(), operator*(), ReadASCII(), ReadBinary(), ReadXML(), Set(), SetIdentity(), SetPrincipalPoint(), SetPrincipalPointX(), TransposeMatrix(), WriteASCII(), WriteBinary(), and WriteXML().
double VW::CalibrationMatrix::_py [protected]
Referenced by AsMatrix(), GetPrincipalPoint(), GetPrincipalPointY(), Inverse(), InverseMatrix(), operator*(), ReadASCII(), ReadBinary(), ReadXML(), Set(), SetIdentity(), SetPrincipalPoint(), SetPrincipalPointY(), TransposeMatrix(), WriteASCII(), WriteBinary(), and WriteXML().
double VW::CalibrationMatrix::_s [protected]
Referenced by AsMatrix(), GetSkew(), Inverse(), InverseMatrix(), Map(), operator*(), ReadASCII(), ReadBinary(), ReadXML(), Set(), SetIdentity(), SetSkew(), TransposeMatrix(), WriteASCII(), WriteBinary(), and WriteXML().
The documentation for this class was generated from the following file:
calibrationmatrix.h