VW: VW::DisplayGTKGLWidget Class Reference
VW::DisplayGTKGLWidget Class Reference
[Displays]
A display that uses a GTK GL canvas widget for drawing.
#include <displaygtkglwidget.h>
Public Member Functions
DisplayGTKGLWidget (const std::string title="")
DisplayGTKGLWidget (const unsigned int width, const unsigned int height, const std::string title="")
~DisplayGTKGLWidget (void)
void SetSize (const unsigned int new_width, const unsigned int new_height)
Set (or reset) the size.
unsigned int GetWidth ()
unsigned int GetHeight ()
void MakeCurrent ()
void GetGLParams (float &xscale, float &yscale, float &xoffset, float &yoffset, GLuint &texid) const
void Reset (unsigned char red=0, unsigned char green=0, unsigned char blue=127)
void SetPixel (const int x, const int y, const unsigned char red, const unsigned char green, const unsigned char blue, const unsigned char alpha=0)
Set the colour of a single pixel.
void SetPixel (const int x, const int y)
Set a single pixel to the current pen colour.
void SetPenColour (const unsigned char red, const unsigned char green, const unsigned char blue, const unsigned char alpha=0)
Set the colour used for drawing lines and points.
void GetPenColour (unsigned char &red, unsigned char &green, unsigned char &blue, unsigned char &alpha) const
Recover the colour used for drawing lines and points.
void DrawPoint (const float x, const float y)
Draw a point at .
void DrawLine (const float x0, const float y0, const float x1, const float y1)
Draw a line from to .
void GetGLCoords (float pixelx, float pixely, float &glx, float &gly) const
Convert pixel coords into GL coords for drawing.
void ConvertToGLCoords (float &x, float &y) const
Convert pixel coords into GL coords for drawing.
void GetPixelCoords (float pixelx, float pixely, float &glx, float &gly) const
Convert GL coords into pixel coords.
void ConvertToPixelCoords (float &x, float &y) const
Convert GL coords into pixel coords.
virtual unsigned int GetTextureName ()
virtual unsigned int GetTextureWidth () const
virtual unsigned int GetTextureHeight () const
virtual void GenerateTexture (unsigned int desired_width, unsigned int desired_height)
float GetImageDrawingDepth () const
float GetFeatureDrawingDepth () const
void Flush ()
Force display to the screen.
bool IsInitialised ()
std::string GetTitle () const
Return the name (displayed in title bar if visible) of the display.
void DrawRectangle (const float x0, const float y0, const float x1, const float y1)
Convenience function to draw a rectangle (just calls four lots of DrawLine).
void DrawCircle (const float x0, const float y0, const float radius)
Convenience function to draw a circle (made of line segments).
void DrawRightEllipse (const float x0, const float y0, const float rx, const float ry)
Convenience function to draw a right ellipse (ie major and minor axes aligned with x, y axes).
void DrawEllipse (const float x0, const float y0, const float rx, const float ry, const float skew)
Convenience function to draw a general ellipse.
Public Attributes
SigC::Signal3< void, int, int,
int > ClickSignal
SigC::Signal5< void, int, int,
int, int, int > DragSignal
SigC::Signal5< void, int, int,
int, int, int > DragFinishedSignal
VWEvents::Event3< void, int,
int, int > ClickEvent
VWEvents::Event5< void, int,
int, int, int, int > DragEvent
VWEvents::Event5< void, int,
int, int, int, int > DragFinishedEvent
Protected Member Functions
void SwapBuffers ()
gint expose_event_impl (GdkEventExpose *)
gint motion_notify_event_impl (GdkEventMotion *)
gint button_press_event_impl (GdkEventButton *)
gint button_release_event_impl (GdkEventButton *)
void ResetCoords (double width, double height)
void InitGL ()
void SetGLView ()
Protected Attributes
unsigned int texName
unsigned int texture_width
unsigned int texture_height
float _xscale
float _xoffset
float _yscale
float _yoffset
unsigned char _red
unsigned char _green
unsigned char _blue
unsigned char _alpha
int last_x
int last_y
bool dragging
bool _initialised
bool _visible
std::string _my_title
Detailed Description
A display that uses a GTK GL canvas widget for drawing.
Author:
BJ Tordoff
Date:
29/01/2002 (NB: This class *doesn't* open a window, and is only useful when embedded in an existing GTK interface.)
***Please insert long descrition here...
Constructor & Destructor Documentation
VW::DisplayGTKGLWidget::DisplayGTKGLWidget (const std::string title = "")
VW::DisplayGTKGLWidget::DisplayGTKGLWidget (const unsigned int width, const unsigned int height, const std::string title = "")
VW::DisplayGTKGLWidget::~DisplayGTKGLWidget (void) [inline]
Member Function Documentation
gint DisplayGTKGLWidget::button_press_event_impl (GdkEventButton * event) [protected]
References VW::DisplayGLCommon::dragging, VW::DisplayGLCommon::last_x, VW::DisplayGLCommon::last_y, MakeCurrent(), TRUE, and VERBOSE.
gint DisplayGTKGLWidget::button_release_event_impl (GdkEventButton * event) [protected]
References VW::DisplayBase::ClickEvent, ClickSignal, VW::DisplayBase::DragFinishedEvent, DragFinishedSignal, VW::DisplayGLCommon::dragging, VWEvents::Event::IsAttached(), VW::DisplayGLCommon::last_x, VW::DisplayGLCommon::last_y, MakeCurrent(), TRUE, and VERBOSE.
void VW::DisplayGLCommon::ConvertToGLCoords (float & x, float & y) const [inline, inherited]
Convert pixel coords into GL coords for drawing.
References VW::DisplayGLCommon::_xoffset, VW::DisplayGLCommon::_xscale, VW::DisplayGLCommon::_yoffset, and VW::DisplayGLCommon::_yscale.
void VW::DisplayGLCommon::ConvertToPixelCoords (float & x, float & y) const [inline, inherited]
Convert GL coords into pixel coords.
References VW::DisplayGLCommon::_xoffset, VW::DisplayGLCommon::_xscale, VW::DisplayGLCommon::_yoffset, and VW::DisplayGLCommon::_yscale.
Referenced by VW::DisplayWxGLWidget::DisplayCoordsToPixelCoords().
void VW::DisplayBase::DrawCircle (const float x0, const float y0, const float radius) [inline, inherited]
Convenience function to draw a circle (made of line segments).
References VW::DisplayBase::DrawRightEllipse().
Referenced by VW::DrawFunctions::Draw().
void VW::DisplayBase::DrawEllipse (const float x0, const float y0, const float rx, const float ry, const float skew) [inherited]
Convenience function to draw a general ellipse.
The parameters are such that they are easily recovered from the matrix equation for an ellipse:
(x-x0 y-y0) C^-1 (x-x0) = sigma^2 (y-y0)
where sigma gives the "radius" (number of std devs) and C is
C = [ rx 0 ] [ rx skew ] [ skew ry ] [ 0 ry ]
Parameters:
x0 x coord of centre
y0 y coord of centre
rx radius in x-direction at y=0
ry radius in y-direction at x=0
skew effect of y on x, where skew=0 gives a right ellipse
References VW::DisplayBase::DrawLine(), and NUM_CIRC_POINTS.
Referenced by VW::DrawFunctions::Draw(), and VW::DrawFunctions::DrawCovariance().
void VW::DisplayGLCommon::DrawLine (const float x0, const float y0, const float x1, const float y1) [inline, virtual, inherited]
Draw a line from to .
Implements VW::DisplayBase.
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::GetFeatureDrawingDepth(), VW::DisplayGLCommon::GetGLCoords(), and VW::DisplayGLCommon::MakeCurrent().
Referenced by VW::DisplayGTKGL::DrawLine().
void VW::DisplayGLCommon::DrawPoint (const float x, const float y) [inline, virtual, inherited]
Draw a point at .
Implements VW::DisplayBase.
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::GetFeatureDrawingDepth(), VW::DisplayGLCommon::GetGLCoords(), and VW::DisplayGLCommon::MakeCurrent().
Referenced by VW::DisplayGTKGL::DrawPoint().
void VW::DisplayBase::DrawRectangle (const float x0, const float y0, const float x1, const float y1) [inline, inherited]
Convenience function to draw a rectangle (just calls four lots of DrawLine).
References VW::DisplayBase::DrawLine().
void VW::DisplayBase::DrawRightEllipse (const float x0, const float y0, const float rx, const float ry) [inherited]
Convenience function to draw a right ellipse (ie major and minor axes aligned with x, y axes).
Parameters:
x0 x coord of centre
y0 y coord of centre
rx max radius in x-direction
ry max radius in y direction
References VW::DisplayBase::DrawLine(), and NUM_CIRC_POINTS.
Referenced by VW::DisplayBase::DrawCircle().
gint DisplayGTKGLWidget::expose_event_impl (GdkEventExpose * event) [protected]
References FALSE, and TRUE.
void VW::DisplayGLCommon::Flush (void) [inline, virtual, inherited]
Force display to the screen.
Implements VW::DisplayBase.
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::MakeCurrent(), and VW::DisplayGLCommon::SwapBuffers().
Referenced by VW::DisplayGTKGL::Flush(), and VW::DisplayGTKGL::SwapBuffers().
void VW::DisplayGLCommon::GenerateTexture (unsigned int desired_width, unsigned int desired_height) [virtual, inherited]
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::ResetCoords(), VW::DisplayGLCommon::texName, VW::DisplayGLCommon::texture_height, VW::DisplayGLCommon::texture_width, and VERBOSE.
Referenced by VW::DrawFunctions::Draw(), and VW::DisplayGTKGL::GenerateTexture().
float VW::DisplayGLCommon::GetFeatureDrawingDepth () const [inline, inherited]
Referenced by VW::DisplayGLCommon::DrawLine(), VW::DisplayGLCommon::DrawPoint(), and VW::DisplayGLCommon::SetPixel().
void VW::DisplayGLCommon::GetGLCoords (float pixelx, float pixely, float & glx, float & gly) const [inline, inherited]
Convert pixel coords into GL coords for drawing.
References VW::DisplayGLCommon::_xoffset, VW::DisplayGLCommon::_xscale, VW::DisplayGLCommon::_yoffset, and VW::DisplayGLCommon::_yscale.
Referenced by VW::DisplayGLCommon::DrawLine(), VW::DisplayGLCommon::DrawPoint(), and VW::DisplayGLCommon::SetPixel().
void VW::DisplayGTKGLWidget::GetGLParams (float & xscale, float & yscale, float & xoffset, float & yoffset, GLuint & texid) const
Referenced by VW::DisplayGTKGL::SetSize().
unsigned int VW::DisplayGTKGLWidget::GetHeight (void) [inline, virtual]
Implements VW::DisplayBase.
Referenced by VW::DisplayGTKGL::GetHeight().
float VW::DisplayGLCommon::GetImageDrawingDepth () const [inline, inherited]
Referenced by VW::DrawFunctions::Draw().
void VW::DisplayGLCommon::GetPenColour (unsigned char & red, unsigned char & green, unsigned char & blue, unsigned char & alpha) const [inline, virtual, inherited]
Recover the colour used for drawing lines and points.
Implements VW::DisplayBase.
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::_alpha, VW::DisplayGLCommon::_blue, VW::DisplayGLCommon::_green, and VW::DisplayGLCommon::_red.
Referenced by VW::DisplayGTKGL::GetPenColour().
void VW::DisplayGLCommon::GetPixelCoords (float pixelx, float pixely, float & glx, float & gly) const [inline, inherited]
Convert GL coords into pixel coords.
References VW::DisplayGLCommon::_xoffset, VW::DisplayGLCommon::_xscale, VW::DisplayGLCommon::_yoffset, and VW::DisplayGLCommon::_yscale.
unsigned int VW::DisplayGLCommon::GetTextureHeight () const [inline, virtual, inherited]
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::texture_height.
Referenced by VW::DrawFunctions::Draw(), and VW::DisplayGTKGL::GetTextureHeight().
unsigned int VW::DisplayGLCommon::GetTextureName () [inline, virtual, inherited]
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::texName.
Referenced by VW::DrawFunctions::Draw(), and VW::DisplayGTKGL::GetTextureName().
unsigned int VW::DisplayGLCommon::GetTextureWidth () const [inline, virtual, inherited]
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::texture_width.
Referenced by VW::DrawFunctions::Draw(), and VW::DisplayGTKGL::GetTextureWidth().
std::string VW::DisplayBase::GetTitle () const [inline, inherited]
Return the name (displayed in title bar if visible) of the display.
References VW::DisplayBase::_my_title.
Referenced by VW::DisplayGLUT::SetSize().
unsigned int VW::DisplayGTKGLWidget::GetWidth (void) [inline, virtual]
Implements VW::DisplayBase.
Referenced by VW::DisplayGTKGL::GetWidth().
void VW::DisplayGLCommon::InitGL () [protected, inherited]
References VW::DisplayBase::_initialised, VW::DisplayBase::_visible, VW::DisplayGLCommon::SetGLView(), VW::DisplayGLCommon::texName, VW::DisplayGLCommon::texture_height, VW::DisplayGLCommon::texture_width, and VERBOSE.
Referenced by VW::DisplayWxGLWidget::MakeCurrent(), MakeCurrent(), and VW::DisplayGLUT::MakeCurrent().
bool VW::DisplayBase::IsInitialised () [inline, inherited]
References VW::DisplayBase::_initialised.
Referenced by VW::DrawFunctions::Draw().
void VW::DisplayGTKGLWidget::MakeCurrent () [inline, virtual]
Implements VW::DisplayGLCommon.
References VW::DisplayBase::_initialised, and VW::DisplayGLCommon::InitGL().
Referenced by button_press_event_impl(), button_release_event_impl(), VW::DisplayGTKGL::MakeCurrent(), and motion_notify_event_impl().
gint DisplayGTKGLWidget::motion_notify_event_impl (GdkEventMotion * event) [protected]
References VW::DisplayBase::DragEvent, VW::DisplayGLCommon::dragging, DragSignal, VW::DisplayGLCommon::last_x, VW::DisplayGLCommon::last_y, MakeCurrent(), TRUE, and VERBOSE.
void VW::DisplayGLCommon::Reset (unsigned char red = 0, unsigned char green = 0, unsigned char blue = 127) [inline, inherited]
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::MakeCurrent().
Referenced by VW::DrawFunctions::Draw(), and VW::DisplayGTKGL::Reset().
void VW::DisplayGLCommon::ResetCoords (double width, double height) [inline, protected, inherited]
References VW::DisplayGLCommon::_xoffset, VW::DisplayGLCommon::_xscale, VW::DisplayGLCommon::_yoffset, and VW::DisplayGLCommon::_yscale.
Referenced by VW::DisplayGLCommon::DisplayGLCommon(), VW::DisplayGLCommon::GenerateTexture(), VW::DisplayGluteWidget::SetSize(), and VW::DisplayGLUT::SetSize().
void VW::DisplayGLCommon::SetGLView () [protected, inherited]
References VERBOSE.
Referenced by VW::DisplayGLCommon::InitGL(), VW::DisplayGluteWidget::Resize(), VW::DisplayGLUT::Resize(), VW::DisplayGluteWidget::SetSize(), and VW::DisplayGLUT::SetSize().
void VW::DisplayGLCommon::SetPenColour (const unsigned char red, const unsigned char green, const unsigned char blue, const unsigned char alpha = 0) [inline, virtual, inherited]
Set the colour used for drawing lines and points.
Implements VW::DisplayBase.
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::_alpha, VW::DisplayGLCommon::_blue, VW::DisplayGLCommon::_green, VW::DisplayGLCommon::_red, and VW::DisplayGLCommon::MakeCurrent().
Referenced by VW::DisplayGTKGL::SetPenColour().
void VW::DisplayGLCommon::SetPixel (const int x, const int y) [inline, virtual, inherited]
Set a single pixel to the current pen colour.
Implements VW::DisplayBase.
References VW::DisplayGLCommon::GetFeatureDrawingDepth(), VW::DisplayGLCommon::GetGLCoords(), and VW::DisplayGLCommon::MakeCurrent().
void VW::DisplayGLCommon::SetPixel (const int x, const int y, const unsigned char red, const unsigned char green, const unsigned char blue, const unsigned char alpha = 0) [inline, virtual, inherited]
Set the colour of a single pixel.
Implements VW::DisplayBase.
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::_alpha, VW::DisplayGLCommon::_blue, VW::DisplayGLCommon::_green, VW::DisplayGLCommon::_red, VW::DisplayGLCommon::GetFeatureDrawingDepth(), VW::DisplayGLCommon::GetGLCoords(), and VW::DisplayGLCommon::MakeCurrent().
Referenced by VW::DisplayGTKGL::SetPixel().
void DisplayGTKGLWidget::SetSize (const unsigned int new_width, const unsigned int new_height) [virtual]
Set (or reset) the size.
If the display is not currently onscreen, it is shown. Otherwise it is resized (which often involves first hiding it from view, so don't expect it to be fast!).
Implements VW::DisplayBase.
References VW::DisplayBase::_visible.
void VW::DisplayGTKGLWidget::SwapBuffers () [inline, protected, virtual]
Implements VW::DisplayGLCommon.
Member Data Documentation
unsigned char VW::DisplayGLCommon::_alpha [protected, inherited]
Referenced by VW::DisplayGLCommon::GetPenColour(), VW::DisplayGLCommon::SetPenColour(), and VW::DisplayGLCommon::SetPixel().
unsigned char VW::DisplayGLCommon::_blue [protected, inherited]
Referenced by VW::DisplayGLCommon::GetPenColour(), VW::DisplayGLCommon::SetPenColour(), and VW::DisplayGLCommon::SetPixel().
unsigned char VW::DisplayGLCommon::_green [protected, inherited]
Referenced by VW::DisplayGLCommon::GetPenColour(), VW::DisplayGLCommon::SetPenColour(), and VW::DisplayGLCommon::SetPixel().
bool VW::DisplayBase::_initialised [protected, inherited]
Referenced by VW::PSCanvas::Close(), VW::PSCanvas::DrawLine(), VW::PSCanvas::Flush(), VW::DisplayGTKGL::GetHeight(), VW::DisplayGTK::GetHeight(), VW::DisplayGTKGL::GetWidth(), VW::DisplayGTK::GetWidth(), VW::DisplayGLCommon::InitGL(), VW::DisplayBase::IsInitialised(), VW::DisplayWxGLWidget::MakeCurrent(), MakeCurrent(), VW::DisplayGLUT::MakeCurrent(), VW::PSCanvas::Open(), VW::PSCanvas::SetSize(), VW::DisplayXForms::SetSize(), VW::DisplayX::SetSize(), VW::DisplayGTKGL::SetSize(), VW::DisplayGTK::SetSize(), VW::DisplayGluteWidget::SetSize(), and VW::PSCanvas::~PSCanvas().
std::string VW::DisplayBase::_my_title [protected, inherited]
Referenced by VW::DisplayBase::GetTitle(), VW::DisplayXForms::SetSize(), VW::DisplayX::SetSize(), VW::DisplayGTKGL::SetSize(), and VW::DisplayGTK::SetSize().
unsigned char VW::DisplayGLCommon::_red [protected, inherited]
Referenced by VW::DisplayGLCommon::GetPenColour(), VW::DisplayGLCommon::SetPenColour(), and VW::DisplayGLCommon::SetPixel().
bool VW::DisplayBase::_visible [protected, inherited]
Referenced by VW::DisplayGLCommon::InitGL(), VW::DisplayXForms::SetSize(), VW::DisplayX::SetSize(), SetSize(), VW::DisplayGTKGL::SetSize(), and VW::DisplayGTK::SetSize().
float VW::DisplayGLCommon::_xoffset [protected, inherited]
Referenced by VW::DisplayGLCommon::ConvertToGLCoords(), VW::DisplayGLCommon::ConvertToPixelCoords(), VW::DisplayGLCommon::GetGLCoords(), VW::DisplayGLCommon::GetPixelCoords(), VW::DisplayGLCommon::ResetCoords(), and VW::DisplayGTKGL::SetSize().
float VW::DisplayGLCommon::_xscale [protected, inherited]
Referenced by VW::DisplayGLCommon::ConvertToGLCoords(), VW::DisplayGLCommon::ConvertToPixelCoords(), VW::DisplayGLCommon::GetGLCoords(), VW::DisplayGLCommon::GetPixelCoords(), VW::DisplayGLCommon::ResetCoords(), and VW::DisplayGTKGL::SetSize().
float VW::DisplayGLCommon::_yoffset [protected, inherited]
Referenced by VW::DisplayGLCommon::ConvertToGLCoords(), VW::DisplayGLCommon::ConvertToPixelCoords(), VW::DisplayGLCommon::GetGLCoords(), VW::DisplayGLCommon::GetPixelCoords(), VW::DisplayGLCommon::ResetCoords(), and VW::DisplayGTKGL::SetSize().
float VW::DisplayGLCommon::_yscale [protected, inherited]
Referenced by VW::DisplayGLCommon::ConvertToGLCoords(), VW::DisplayGLCommon::ConvertToPixelCoords(), VW::DisplayGLCommon::GetGLCoords(), VW::DisplayGLCommon::GetPixelCoords(), VW::DisplayGLCommon::ResetCoords(), and VW::DisplayGTKGL::SetSize().
VWEvents::Event3<void,int,int,int> VW::DisplayBase::ClickEvent [inherited]
Referenced by VW::DisplayGTKGL::_HandleClick(), VW::DisplayGTK::_HandleClick(), VW::DisplayGTKWidget::button_release_event_impl(), button_release_event_impl(), DisplayXFormsCanvasHandler(), VW::DisplayGluteWidget::Mouse(), VW::DisplayGLUT::Mouse(), and VW::DisplayWxGLWidget::OnMouseUp().
SigC::Signal3<void,int,int,int> VW::DisplayGTKGLWidget::ClickSignal
Referenced by button_release_event_impl().
VWEvents::Event5<void,int,int,int,int,int> VW::DisplayBase::DragEvent [inherited]
Referenced by VW::DisplayGTKGL::_HandleDrag(), VW::DisplayGTK::_HandleDrag(), DisplayXFormsCanvasHandler(), VW::DisplayGluteWidget::Motion(), VW::DisplayGLUT::Motion(), VW::DisplayGTKWidget::motion_notify_event_impl(), motion_notify_event_impl(), and VW::DisplayWxGLWidget::OnMouseMove().
VWEvents::Event5<void,int,int,int,int,int> VW::DisplayBase::DragFinishedEvent [inherited]
Referenced by VW::DisplayGTKGL::_HandleDragFinished(), VW::DisplayGTK::_HandleDragFinished(), VW::DisplayGTKWidget::button_release_event_impl(), button_release_event_impl(), DisplayXFormsCanvasHandler(), VW::DisplayGluteWidget::Mouse(), VW::DisplayGLUT::Mouse(), and VW::DisplayWxGLWidget::OnMouseUp().
SigC::Signal5<void,int,int,int,int,int> VW::DisplayGTKGLWidget::DragFinishedSignal
Referenced by button_release_event_impl().
bool VW::DisplayGLCommon::dragging [protected, inherited]
Referenced by button_press_event_impl(), button_release_event_impl(), and motion_notify_event_impl().
SigC::Signal5<void,int,int,int,int,int> VW::DisplayGTKGLWidget::DragSignal
Referenced by motion_notify_event_impl().
int VW::DisplayGLCommon::last_x [protected, inherited]
Referenced by button_press_event_impl(), button_release_event_impl(), and motion_notify_event_impl().
int VW::DisplayGLCommon::last_y [protected, inherited]
Referenced by button_press_event_impl(), button_release_event_impl(), and motion_notify_event_impl().
unsigned int VW::DisplayGLCommon::texName [protected, inherited]
Referenced by VW::DisplayGLCommon::GenerateTexture(), VW::DisplayGLCommon::GetTextureName(), and VW::DisplayGLCommon::InitGL().
unsigned int VW::DisplayGLCommon::texture_height [protected, inherited]
Referenced by VW::DisplayGLCommon::GenerateTexture(), VW::DisplayGLCommon::GetTextureHeight(), and VW::DisplayGLCommon::InitGL().
unsigned int VW::DisplayGLCommon::texture_width [protected, inherited]
Referenced by VW::DisplayGLCommon::GenerateTexture(), VW::DisplayGLCommon::GetTextureWidth(), and VW::DisplayGLCommon::InitGL().
The documentation for this class was generated from the following files:
displaygtkglwidget.h
displaygtkglwidget.cpp