VW: VW::ROI Class Reference
VW::ROI Class Reference
[Image]
Class to hold the bounds on the Region of Interest (ROI) of a 2D array (image).
#include <roi.h>
Public Member Functions
ROI ()
Construct with zero for all coords.
ROI (int left, int top, int right, int bottom)
Construct with user defined region.
ROI (const ROI &r)
Construct from an axisting region of interest.
void Set (const VW::ROI &r)
Set to an existing region of interest (eg when copying images).
void Set (int left, int top, int right, int bottom)
Set to a user defined region.
void Get (int &left, int &top, int &right, int &bottom) const
Recover all four bounds of the region.
void Get (unsigned int &left, unsigned int &top, unsigned int &right, unsigned int &bottom) const
Recover all four bounds of the region (as unsigned).
int Left () const
Recover index of the leftmost column inside the region.
int Right () const
Recover index of the first column outside and to the right of the region.
int Top () const
Recover index of the topmost row inside the region.
int Bottom () const
Recover index of the first row outside and below the region.
unsigned int Width () const
Recover the width of the region.
unsigned int Height () const
Recover the height of the region.
void SetLeft (const int newvalue)
void SetRight (const int newvalue)
void SetTop (const int newvalue)
void SetBottom (const int newvalue)
void Shrink ()
Reduce the region by 1 in all directions.
void Shrink (unsigned int a)
Reduce the region by 'a' in all directions.
void ShrinkWidth (unsigned int a)
Reduce the region by 'a' from both left and right.
void ShrinkHeight (unsigned int a)
Reduce the region by 'a' from both top and bottom.
void Grow ()
Increase the region by 1 in all directions.
void Grow (unsigned int a)
Increase the region by 'a' in all directions.
void GrowWidth (unsigned int a)
Increase the region by 'a' from both left and right.
void GrowHeight (unsigned int a)
Increase the region by 'a' from both top and bottom.
bool IsContained (double x, double y) const
Is the specified point contained in the ROI.
Protected Attributes
int c0
int r0
int cl
int rl
Detailed Description
Class to hold the bounds on the Region of Interest (ROI) of a 2D array (image).
Author:
ID Reid, BJ Tordoff
Date:
15/01/2003
(c) Copyright University of Oxford All rights reserved
Data is stored as the first row/column of interest, and one beyond the last, so a loop that does for(x=roi.Left();x<roi.Right();x++) {} does the right thing.
Constructor & Destructor Documentation
VW::ROI::ROI () [inline]
Construct with zero for all coords.
References c0, cl, r0, and rl.
VW::ROI::ROI (int left, int top, int right, int bottom) [inline]
Construct with user defined region.
Parameters:
left the first column inside the region
right the first column beyond the right edge of the region
top the first row inside the region
bottom the first row beyond the bottom of the region
References c0, cl, r0, and rl.
VW::ROI::ROI (const ROI & r) [inline]
Construct from an axisting region of interest.
Parameters:
r an existing ROI whose position and size will be copied
References c0, cl, r0, and rl.
Member Function Documentation
int VW::ROI::Bottom () const [inline]
Recover index of the first row outside and below the region.
Returns:
the index of the first row below the region (ie. Top()<=y<Bottom())
References rl.
Referenced by VW::ShiTomasiDetector::Compute(), VW::Moments::Compute(), VW::GetPatchDescriptor::Compute(), VW::Correlate::Compute(), VW::GetPlesseyCorner::GetPlesseyCorner(), and VW::GetPlesseyCornerYUV::GetPlesseyCornerYUV().
void VW::ROI::Get (unsigned int & left, unsigned int & top, unsigned int & right, unsigned int & bottom) const [inline]
Recover all four bounds of the region (as unsigned).
Parameters:
left the first column inside the region
right the first column beyond the right edge of the region
top the first row inside the region
bottom the first row beyond the bottom of the region
References c0, cl, r0, and rl.
void VW::ROI::Get (int & left, int & top, int & right, int & bottom) const [inline]
Recover all four bounds of the region.
Parameters:
left the first column inside the region
right the first column beyond the right edge of the region
top the first row inside the region
bottom the first row beyond the bottom of the region
References c0, cl, r0, and rl.
Referenced by VW::PyramidYUV< StorageType >::_AverageAndSubsampleBy2(), VW::Pyramid< StorageType >::AverageAndSubsampleBy2(), VW::Threshold< Type >::Compute(), VW::IntegralImageSquared< DataType >::Compute(), VW::IntegralImage< DataType >::Compute(), and VW::Convolve< maskType >::Compute().
void VW::ROI::Grow (unsigned int a) [inline]
Increase the region by 'a' in all directions.
Parameters:
a the amount by which the region is increased
References c0, cl, r0, and rl.
void VW::ROI::Grow () [inline]
Increase the region by 1 in all directions.
References c0, cl, r0, and rl.
void VW::ROI::GrowHeight (unsigned int a) [inline]
Increase the region by 'a' from both top and bottom.
References r0, and rl.
void VW::ROI::GrowWidth (unsigned int a) [inline]
Increase the region by 'a' from both left and right.
References c0, and cl.
unsigned int VW::ROI::Height () const [inline]
Recover the height of the region.
Returns:
the height of (number of rows inside) the region
References r0, and rl.
Referenced by VW::ParametricFlowNonLin::Compute(), and VW::Correlate::Compute().
bool VW::ROI::IsContained (double x, double y) const [inline]
Is the specified point contained in the ROI.
References c0, cl, r0, rl, and v.
int VW::ROI::Left () const [inline]
Recover index of the leftmost column inside the region.
Returns:
the index of the first column inside the region
References c0.
Referenced by VW::ShiTomasiDetector::Compute(), VW::Moments::Compute(), VW::GetPatchDescriptor::Compute(), VW::Correlate::Compute(), VW::GetPlesseyCorner::GetPlesseyCorner(), and VW::GetPlesseyCornerYUV::GetPlesseyCornerYUV().
int VW::ROI::Right () const [inline]
Recover index of the first column outside and to the right of the region.
Returns:
the index of the first row to the right of the region (ie. Left()<=x<Right())
References cl.
Referenced by VW::ShiTomasiDetector::Compute(), VW::Moments::Compute(), VW::GetPatchDescriptor::Compute(), VW::Correlate::Compute(), VW::GetPlesseyCorner::GetPlesseyCorner(), and VW::GetPlesseyCornerYUV::GetPlesseyCornerYUV().
void VW::ROI::Set (int left, int top, int right, int bottom) [inline]
Set to a user defined region.
Parameters:
left the first column inside the region
right the first column beyond the right edge of the region
top the first row inside the region
bottom the first row beyond the bottom of the region
References c0, cl, r0, and rl.
void VW::ROI::Set (const VW::ROI & r) [inline]
Set to an existing region of interest (eg when copying images).
Parameters:
r an existing ROI whose position and size will be copied
References c0, cl, r0, and rl.
Referenced by VW::PyramidYUV< StorageType >::_AverageAndSubsampleBy2(), VW::Pyramid< StorageType >::AverageAndSubsampleBy2(), VW::Threshold< Type >::Compute(), VW::ParametricFlowWide::Compute(), VW::Convolve< maskType >::Compute(), and VW::ImageBase< PixelType, PixelPtr >::ResetROI().
void VW::ROI::SetBottom (const int newvalue) [inline]
References rl.
void VW::ROI::SetLeft (const int newvalue) [inline]
References c0.
void VW::ROI::SetRight (const int newvalue) [inline]
References cl.
void VW::ROI::SetTop (const int newvalue) [inline]
References r0.
void VW::ROI::Shrink (unsigned int a) [inline]
Reduce the region by 'a' in all directions.
Parameters:
a the amount by which the region is increased
References c0, cl, r0, and rl.
void VW::ROI::Shrink () [inline]
Reduce the region by 1 in all directions.
References c0, cl, r0, and rl.
void VW::ROI::ShrinkHeight (unsigned int a) [inline]
Reduce the region by 'a' from both top and bottom.
References r0, and rl.
Referenced by VW::Correlate::Compute().
void VW::ROI::ShrinkWidth (unsigned int a) [inline]
Reduce the region by 'a' from both left and right.
References c0, and cl.
Referenced by VW::Correlate::Compute().
int VW::ROI::Top () const [inline]
Recover index of the topmost row inside the region.
Returns:
the index of the first row inside the region
References r0.
Referenced by VW::ShiTomasiDetector::Compute(), VW::Moments::Compute(), VW::GetPatchDescriptor::Compute(), VW::Correlate::Compute(), VW::GetPlesseyCorner::GetPlesseyCorner(), and VW::GetPlesseyCornerYUV::GetPlesseyCornerYUV().
unsigned int VW::ROI::Width () const [inline]
Recover the width of the region.
Returns:
the width of (number of columns inside) the region
References c0, and cl.
Referenced by VW::ShiTomasiDetector::Compute(), VW::ParametricFlowNonLin::Compute(), and VW::Correlate::Compute().
Member Data Documentation
int VW::ROI::c0 [protected]
Referenced by Get(), Grow(), GrowWidth(), IsContained(), Left(), ROI(), Set(), SetLeft(), Shrink(), ShrinkWidth(), and Width().
int VW::ROI::cl [protected]
Referenced by Get(), Grow(), GrowWidth(), IsContained(), Right(), ROI(), Set(), SetRight(), Shrink(), ShrinkWidth(), and Width().
int VW::ROI::r0 [protected]
Referenced by Get(), Grow(), GrowHeight(), Height(), IsContained(), ROI(), Set(), SetTop(), Shrink(), ShrinkHeight(), and Top().
int VW::ROI::rl [protected]
Referenced by Bottom(), Get(), Grow(), GrowHeight(), Height(), IsContained(), ROI(), Set(), SetBottom(), Shrink(), and ShrinkHeight().
The documentation for this class was generated from the following file:
roi.h