VW: VW::SequencerMovie Class Reference
VW::SequencerMovie Class Reference
[Sequencers, CoreSequencers]
A sequencer for handling a few types of Movie file.
#include <sequencermovie.h>
Public Member Functions
SequencerMovie ()
SequencerMovie (const std::string &filename)
SequencerMovie (const std::vector< std::string > &filenames)
void AddChannel (const std::string &file_name)
void * GetBuffer (unsigned int which_channel=0)
Gain access to the sequencers buffer.
template<class ImType >
void CopyImage (ImType &image, unsigned int which_channel=0)
Take a copy of the grabbed image.
virtual void Rewind ()
Rewind the grabbing of all movies to the beginning.
std::string GetMovieName (unsigned int which_channel=0)
The name(s) of the movies.
int GetY4MPID (unsigned int which_channel=0)
The pid(s) of the y4mtoppm processes.
void _cleanup (int which_channel)
remove temporary files created for mplayer and y4mtoppm
Sequence control functions
virtual void Continuous ()
Start continuous capture from the sequence.
virtual void Stop ()
Stop continuous capture from the sequence.
virtual void Next ()
Capture the next single frame.
Initialisation functions
virtual bool Init ()
All sequencers have an Init(), even if they don't need it, so call init() before using a sequencer (especially if from an interface).
virtual void SetDelay (int d)
Set the delay between frames (only usually used for non-hardware sequencers).
Information functions
bool GetContinuous () const
Is the sequencer running in continuous mode?
int GetDelay () const
What is the delay between frames.
unsigned int GetNumberOfChannels () const
Most sequencers are able to present mutliple images per frame.
unsigned int GetCurrentFrameNumber () const
Return the current frame number.
Public Attributes
VWEvents::Event1< void, int > NewFrameEvent
The "new frame has arrived" event.
Protected Member Functions
void _InitialiseMovies ()
void _OpenFile (unsigned int which_channel)
virtual bool _Step ()
void _WaitForThread ()
Wait for the thread to exit.
virtual void _FrameArrived ()
we have been signalled that a frame has arrived and we are now "inside" the signalling object, so invoke the appropriate callback
void * Main (void *)
void _CheckInitialised ()
Protected Attributes
std::vector< ImageRGB
< unsigned char > * > im
std::vector< FILE * > fp
std::vector< std::string > movienames
std::vector< bool > file_ok
std::vector< int > y4m_pid
std::vector< int > mplayer_pid
std::vector< char * > streamname
int delay
unsigned int frame_number
bool cont
bool thread_running
bool _initialised
ThreadType parent
unsigned int number_of_channels
Mutex access_lock
bool user_finished
Detailed Description
A sequencer for handling a few types of Movie file.
Author:
ID Reid, BJ Tordoff
Date:
02/08/02 As this uses a hacked version of xanim, you'll need to get a copy. This sequencer can read images from any movie that xanim can handle.
Constructor & Destructor Documentation
SequencerMovie::SequencerMovie ()
References VW::SequencerBase::number_of_channels.
VW::SequencerMovie::SequencerMovie (const std::string & filename)
VW::SequencerMovie::SequencerMovie (const std::vector< std::string > & filenames)
Member Function Documentation
void VW::SequencerBase::_CheckInitialised () [protected, inherited]
References VW::SequencerBase::_initialised.
Referenced by VW::SequencerBase::Continuous(), VW::SequencerBase::Next(), and VW::SequencerBase::Stop().
void SequencerMovie::_cleanup (int which_channel)
remove temporary files created for mplayer and y4mtoppm
References streamname.
Referenced by _OpenFile().
void SequencerBase::_FrameArrived () [protected, virtual, inherited]
we have been signalled that a frame has arrived and we are now "inside" the signalling object, so invoke the appropriate callback
Reimplemented in VW::SequencerFileGTK, VW::SequencerFirewireGTK, VW::SequencerFileWx, VW::SequencerFirewireWx, and VW::SequencerMeteor.
References VW::SequencerBase::NewFrameEvent, VW::SequencerBase::user_finished, and VERBOSE.
Referenced by VW::SequencerBase::Main(), and VW::SequencerBase::Next().
void VW::SequencerMovie::_InitialiseMovies () [protected]
void SequencerMovie::_OpenFile (unsigned int which_channel) [protected]
References _cleanup(), file_ok, fp, movienames, mplayer_pid, streamname, and y4m_pid.
Referenced by Rewind(), and VW::SequencerMovieGTK::UpdateFromForm().
bool SequencerMovie::_Step () [protected, virtual]
Implements VW::SequencerBase.
References VW::SequencerBase::cont, file_ok, fp, VW::SequencerBase::frame_number, im, movienames, VW::SequencerBase::number_of_channels, VW::ReadImage(), and VW::SequencerBase::Stop().
void SequencerBase::_WaitForThread () [inline, protected, inherited]
Wait for the thread to exit.
References VW::SequencerBase::access_lock, VW::Mutex::Lock(), msleep(), VW::SequencerBase::thread_running, VW::Mutex::Unlock(), and VERBOSE.
Referenced by VW::SequencerBase::Stop().
void VW::SequencerMovie::AddChannel (const std::string & file_name)
void SequencerBase::Continuous () [virtual, inherited]
Start continuous capture from the sequence.
Reimplemented in VW::SequencerFileGTK, VW::SequencerFirewireGTK, VW::SequencerMovieGTK, VW::SequencerFileWx, VW::SequencerFirewireWx, and VW::SequencerMeteor.
References VW::SequencerBase::_CheckInitialised(), VW::SequencerBase::access_lock, VW::SequencerBase::cont, VW::Mutex::Lock(), VW::Thread::Start(), and VW::Mutex::Unlock().
Referenced by VW::SequencerFirewireGlute::_ContClicked(), VW::SequencerFileGlute::_ContClicked(), VW::SequencerFirewireGlow::OnMessage(), and VW::SequencerFileGlow::OnMessage().
template<class ImType > void VW::SequencerMovie::CopyImage (ImType & image, unsigned int which_channel = 0) [inline]
Take a copy of the grabbed image.
References im, and VW::ImageCopy().
void * VW::SequencerMovie::GetBuffer (unsigned int which_channel = 0) [inline, virtual]
Gain access to the sequencers buffer.
Implements VW::SequencerBase.
References im.
bool VW::SequencerBase::GetContinuous () const [inline, inherited]
Is the sequencer running in continuous mode?
References VW::SequencerBase::cont.
unsigned int VW::SequencerBase::GetCurrentFrameNumber () const [inline, inherited]
Return the current frame number.
In the case of movies or files this is the frame number with respect to the start frame (ie, 1=start frame) and won't correspond to the sequence frame numbers if started part way through a sequence.
References VW::SequencerBase::frame_number.
int VW::SequencerBase::GetDelay () const [inline, inherited]
What is the delay between frames.
References VW::SequencerBase::delay.
std::string VW::SequencerMovie::GetMovieName (unsigned int which_channel = 0) [inline]
The name(s) of the movies.
References movienames.
Referenced by VW::SequencerMovieGTKWidget::InitForm().
unsigned int VW::SequencerBase::GetNumberOfChannels () const [inline, inherited]
Most sequencers are able to present mutliple images per frame.
References VW::SequencerBase::number_of_channels.
Referenced by VW::SequencerMovieGTKWidget::InitForm(), and VW::SequencerFileGTKWidget::InitForm().
int VW::SequencerMovie::GetY4MPID (unsigned int which_channel = 0) [inline]
The pid(s) of the y4mtoppm processes.
References y4m_pid.
bool SequencerBase::Init () [virtual, inherited]
All sequencers have an Init(), even if they don't need it, so call init() before using a sequencer (especially if from an interface).
Reimplemented in VW::SequencerFile, VW::SequencerFileGTK, VW::SequencerFirewireGTK, VW::SequencerMovieGTK, VW::SequencerFileWx, VW::SequencerFirewireWx, VW::SequencerFirewire, and VW::SequencerMeteor.
References VW::SequencerBase::_initialised.
void * SequencerBase::Main (void *) [protected, virtual, inherited]
Implements VW::Thread.
References VW::SequencerBase::_FrameArrived(), VW::SequencerBase::_Step(), VW::SequencerBase::access_lock, VW::SequencerBase::cont, VW::SequencerBase::delay, VW::SequencerBase::frame_number, VW::Mutex::Lock(), msleep(), VW::SequencerBase::thread_running, VW::Mutex::Unlock(), and VERBOSE.
void SequencerBase::Next () [virtual, inherited]
Capture the next single frame.
Reimplemented in VW::SequencerFileGTK, VW::SequencerFirewireGTK, VW::SequencerMovieGTK, VW::SequencerFileWx, VW::SequencerFirewireWx, and VW::SequencerMeteor.
References VW::SequencerBase::_CheckInitialised(), VW::SequencerBase::_FrameArrived(), VW::SequencerBase::_Step(), VW::SequencerBase::access_lock, VW::SequencerBase::cont, VW::Mutex::Lock(), VW::SequencerBase::Stop(), and VW::Mutex::Unlock().
Referenced by VW::SequencerFirewireGlute::_NextClicked(), VW::SequencerFileGlute::_NextClicked(), VW::SequencerFirewireGlow::OnMessage(), and VW::SequencerFileGlow::OnMessage().
void SequencerMovie::Rewind () [virtual]
Rewind the grabbing of all movies to the beginning.
Reimplemented in VW::SequencerMovieGTK.
References _OpenFile(), file_ok, VW::SequencerBase::frame_number, and VW::SequencerBase::number_of_channels.
void VW::SequencerBase::SetDelay (int d) [inline, virtual, inherited]
Set the delay between frames (only usually used for non-hardware sequencers).
This is the time (in milliseconds) for which the sequencer sleeps between frames: the total frame period will be this plus the time taken to acquire the new frame. By default the delay is set to 1ms (zero or less is not a valid setting).
References VW::SequencerBase::delay.
void SequencerBase::Stop () [virtual, inherited]
Stop continuous capture from the sequence.
Reimplemented in VW::SequencerFileGTK, VW::SequencerFirewireGTK, VW::SequencerMovieGTK, VW::SequencerFileWx, VW::SequencerFirewireWx, VW::SequencerFirewire, and VW::SequencerMeteor.
References VW::SequencerBase::_CheckInitialised(), VW::SequencerBase::_WaitForThread(), VW::SequencerBase::access_lock, VW::SequencerBase::cont, VW::Thread::Detach(), VW::Mutex::Lock(), VW::Mutex::Unlock(), and VERBOSE.
Referenced by _Step(), VW::SequencerFile::_Step(), VW::SequencerFileGlute::_StopClicked(), VW::SequencerBase::Next(), and VW::SequencerFileGlow::OnMessage().
Member Data Documentation
bool VW::SequencerBase::_initialised [protected, inherited]
Referenced by VW::SequencerBase::_CheckInitialised(), and VW::SequencerBase::Init().
Mutex VW::SequencerBase::access_lock [protected, inherited]
Referenced by VW::SequencerFile::_Step(), VW::SequencerBase::_WaitForThread(), VW::SequencerBase::Continuous(), VW::SequencerBase::Main(), VW::SequencerBase::Next(), VW::SequencerFile::Rewind(), VW::SequencerFile::Skip(), and VW::SequencerBase::Stop().
bool VW::SequencerBase::cont [protected, inherited]
Referenced by _Step(), VW::SequencerFirewire::_Step(), VW::SequencerFile::_Step(), VW::SequencerBase::Continuous(), VW::SequencerBase::GetContinuous(), VW::SequencerBase::Main(), VW::SequencerBase::Next(), VW::SequencerBase::Stop(), VW::SequencerMovieGTK::UpdateForm(), VW::SequencerFirewireWx::UpdateForm(), VW::SequencerFileWx::UpdateForm(), and VW::SequencerFileGTK::UpdateForm().
int VW::SequencerBase::delay [protected, inherited]
Referenced by VW::SequencerBase::GetDelay(), VW::SequencerBase::Main(), and VW::SequencerBase::SetDelay().
std::vector<bool> VW::SequencerMovie::file_ok [protected]
Referenced by _OpenFile(), _Step(), Rewind(), and VW::SequencerMovieGTK::UpdateForm().
std::vector<FILE*> VW::SequencerMovie::fp [protected]
Referenced by _OpenFile(), and _Step().
unsigned int VW::SequencerBase::frame_number [protected, inherited]
Referenced by VW::SequencerFile::_InitialiseFiles(), _Step(), VW::SequencerFile::_Step(), VW::SequencerBase::GetCurrentFrameNumber(), VW::SequencerBase::Main(), Rewind(), VW::SequencerFile::Rewind(), VW::SequencerFile::SequencerFile(), VW::SequencerFile::Skip(), VW::SequencerFileWx::UpdateForm(), and VW::SequencerFileGTK::UpdateForm().
std::vector<ImageRGB<unsigned char>* > VW::SequencerMovie::im [protected]
Referenced by _Step(), CopyImage(), and GetBuffer().
std::vector<std::string> VW::SequencerMovie::movienames [protected]
Referenced by _OpenFile(), _Step(), and GetMovieName().
std::vector<int> VW::SequencerMovie::mplayer_pid [protected]
Referenced by _OpenFile().
VWEvents::Event1<void,int> VW::SequencerBase::NewFrameEvent [inherited]
The "new frame has arrived" event.
Attach a function to this callback signal if you want to perform an operation each time a new image arrives. This is typically done using my_sequencer.NewFrameEvent.connect(&MyFunction); where 'MyFunction' must take an integer argument and return void.
Referenced by VW::SequencerMeteor::_FrameArrived(), VW::SequencerFirewireWx::_FrameArrived(), VW::SequencerFirewireGTK::_FrameArrived(), VW::SequencerFileWx::_FrameArrived(), VW::SequencerFileGTK::_FrameArrived(), and VW::SequencerBase::_FrameArrived().
unsigned int VW::SequencerBase::number_of_channels [protected, inherited]
Referenced by VW::SequencerFile::_InitialiseFiles(), _Step(), VW::SequencerFirewire::_Step(), VW::SequencerFile::_Step(), VW::SequencerFile::CopyImage(), VW::SequencerFirewire::GetCamera(), VW::SequencerFirewire::GetNumberOfCameras(), VW::SequencerBase::GetNumberOfChannels(), VW::SequencerMeteor::Init(), VW::SequencerFirewire::ProbeForCameras(), Rewind(), VW::SequencerFile::Rewind(), VW::SequencerFile::SequencerFile(), VW::SequencerFirewire::SequencerFirewire(), SequencerMovie(), VW::SequencerFirewire::SetDefaultCameraSettings(), VW::SequencerFile::Skip(), VW::SequencerFirewire::StartDMA(), VW::SequencerFirewire::StartISO(), VW::SequencerFirewire::StopDMA(), VW::SequencerFirewire::StopISO(), VW::SequencerMovieGTK::UpdateForm(), VW::SequencerFileWx::UpdateForm(), VW::SequencerFileGTK::UpdateForm(), VW::SequencerMovieGTK::UpdateFromForm(), and VW::SequencerFileGTK::UpdateFromForm().
ThreadType VW::SequencerBase::parent [protected, inherited]
std::vector<char *> VW::SequencerMovie::streamname [protected]
Referenced by _cleanup(), and _OpenFile().
bool VW::SequencerBase::thread_running [protected, inherited]
Referenced by VW::SequencerFirewire::_Step(), VW::SequencerBase::_WaitForThread(), and VW::SequencerBase::Main().
bool VW::SequencerBase::user_finished [protected, inherited]
Referenced by VW::SequencerFirewireWx::_FrameArrived(), VW::SequencerFirewireGTK::_FrameArrived(), VW::SequencerFileWx::_FrameArrived(), VW::SequencerFileGTK::_FrameArrived(), and VW::SequencerBase::_FrameArrived().
std::vector<int> VW::SequencerMovie::y4m_pid [protected]
Referenced by _OpenFile(), and GetY4MPID().
The documentation for this class was generated from the following files:
sequencermovie.h
sequencermovie.cpp