VW: vnl_fastops Class Reference
vnl_fastops Class Reference
Collection of C-style matrix functions for the most time-critical applications.
#include <fastops.h>
Static Public Member Functions
static void AtA (const VNL::Matrix< double > &A, VNL::Matrix< double > *out)
Compute $A^ A$.
static void AB (const VNL::Matrix< double > &A, const VNL::Matrix< double > &B, VNL::Matrix< double > *out)
Compute AxB.
static void AtB (const VNL::Matrix< double > &A, const VNL::Matrix< double > &B, VNL::Matrix< double > *out)
Compute $A^ B$.
static void AtB (const VNL::Matrix< double > &A, const VNL::Vector< double > &B, VNL::Vector< double > *out)
Compute $A^ b$ for vector b. out_ptr may not be b.
static void ABt (const VNL::Matrix< double > &A, const VNL::Matrix< double > &B, VNL::Matrix< double > *out)
Compute $A B^$.
static void inc_X_by_AtB (VNL::Matrix< double > &X, const VNL::Matrix< double > &A, const VNL::Matrix< double > &B)
static void inc_X_by_AtB (VNL::Vector< double > &X, const VNL::Matrix< double > &A, const VNL::Vector< double > &B)
Compute $X += A^ b$.
static void inc_X_by_AtA (VNL::Matrix< double > &X, const VNL::Matrix< double > &A)
Compute $ X += A^ A$.
static void dec_X_by_AtB (VNL::Matrix< double > &X, const VNL::Matrix< double > &A, const VNL::Matrix< double > &B)
Compute $X -= A^ B$.
static void dec_X_by_AtA (VNL::Matrix< double > &X, const VNL::Matrix< double > &A)
static void dec_X_by_ABt (VNL::Matrix< double > &X, const VNL::Matrix< double > &A, const VNL::Matrix< double > &B)
Compute $X -= A B^$.
static double dot (const double *a, const double *b, int n)
Compute dot product of a and b.
Detailed Description
Collection of C-style matrix functions for the most time-critical applications.
In general, however one should consider using the vnl_transpose envelope-letter class to achieve the same results with about a 10% speed penalty.
Member Function Documentation
void vnl_fastops::AB (const VNL::Matrix< double > & A, const VNL::Matrix< double > & B, VNL::Matrix< double > * out) [static]
Compute AxB.
References VNL::Matrix< T >::Columns(), VNL::Matrix< T >::DataArray(), and VNL::Matrix< T >::Rows().
void vnl_fastops::ABt (const VNL::Matrix< double > & A, const VNL::Matrix< double > & B, VNL::Matrix< double > * out) [static]
Compute $A B^$.
References VNL::Matrix< T >::Columns(), VNL::Matrix< T >::DataArray(), and VNL::Matrix< T >::Rows().
void vnl_fastops::AtA (const VNL::Matrix< double > & A, VNL::Matrix< double > * out) [static]
Compute $A^ A$.
References VNL::Matrix< T >::Columns(), VNL::Matrix< T >::DataArray(), m, and VNL::Matrix< T >::Rows().
void vnl_fastops::AtB (const VNL::Matrix< double > & A, const VNL::Vector< double > & B, VNL::Vector< double > * out) [static]
Compute $A^ b$ for vector b. out_ptr may not be b.
References VNL::Matrix< T >::Columns(), VNL::Matrix< T >::DataArray(), VNL::Vector< T >::DataBlock(), m, VNL::Matrix< T >::Rows(), VNL::Vector< T >::size(), and VNL::Vector< T >::Size().
void vnl_fastops::AtB (const VNL::Matrix< double > & A, const VNL::Matrix< double > & B, VNL::Matrix< double > * out) [static]
Compute $A^ B$.
References VNL::Matrix< T >::Columns(), VNL::Matrix< T >::DataArray(), and VNL::Matrix< T >::Rows().
Referenced by VNL::Transpose::operator*().
void vnl_fastops::dec_X_by_ABt (VNL::Matrix< double > & X, const VNL::Matrix< double > & A, const VNL::Matrix< double > & B) [static]
Compute $X -= A B^$.
References VNL::Matrix< T >::Columns(), VNL::Matrix< T >::DataArray(), dot(), and VNL::Matrix< T >::Rows().
static void vnl_fastops::dec_X_by_AtA (VNL::Matrix< double > & X, const VNL::Matrix< double > & A) [static]
void vnl_fastops::dec_X_by_AtB (VNL::Matrix< double > & X, const VNL::Matrix< double > & A, const VNL::Matrix< double > & B) [static]
Compute $X -= A^ B$.
References VNL::Matrix< T >::Columns(), VNL::Matrix< T >::DataArray(), and VNL::Matrix< T >::Rows().
double vnl_fastops::dot (const double * a, const double * b, int n) [static]
Compute dot product of a and b.
Referenced by dec_X_by_ABt().
void vnl_fastops::inc_X_by_AtA (VNL::Matrix< double > & X, const VNL::Matrix< double > & A) [static]
Compute $ X += A^ A$.
References VNL::Matrix< T >::Columns(), VNL::Matrix< T >::DataArray(), m, and VNL::Matrix< T >::Rows().
void vnl_fastops::inc_X_by_AtB (VNL::Vector< double > & X, const VNL::Matrix< double > & A, const VNL::Vector< double > & B) [static]
Compute $X += A^ b$.
References VNL::Matrix< T >::Columns(), VNL::Matrix< T >::DataArray(), VNL::Vector< T >::DataBlock(), VNL::Matrix< T >::Rows(), and VNL::Vector< T >::Size().
void vnl_fastops::inc_X_by_AtB (VNL::Matrix< double > & X, const VNL::Matrix< double > & A, const VNL::Matrix< double > & B) [static]
References VNL::Matrix< T >::Columns(), VNL::Matrix< T >::DataArray(), and VNL::Matrix< T >::Rows().
The documentation for this class was generated from the following files:
fastops.h
fastops.cpp