VW: VW::SequencerFileGTKWidget Class Reference
VW::SequencerFileGTKWidget Class Reference
#include <sequencerfilegtk.h>
Public Member Functions
void InitForm (SequencerFileGTK *parent)
std::string GetFileName (unsigned int which_channel)
void SetLED (unsigned int which_channel, bool valid)
void AddFile (SequencerFileGTK *parent)
template<class WidgetType , class T >
void CreateButtonBar (T *parent, bool add_file_buttons=true)
Public Attributes
Gtk::VBox * files_box
Gtk::Button * go_button
Gtk::Button * next_button
Gtk::Button * stop_button
Gtk::Button * rewind_button
Gtk::Label * frame_no_label
Gtk::OptionMenu * loop_menu
Protected Attributes
std::vector
< SequencerFileChannelGTKWidget * > file_widgets
Gtk::Tooltips tooltips
Gtk::HBox * button_bar
Member Function Documentation
void VW::SequencerFileGTKWidget::AddFile (VW::SequencerFileGTK * parent)
References file_widgets, files_box, and VW::SequencerFile::GetInitialFileName().
Referenced by InitForm().
template<class WidgetType , class T > void VW::InterfaceGTKWidget::CreateButtonBar (T * parent, bool add_file_buttons = true) [inline, inherited]
References add(), VW::InterfaceGTKWidget::button_bar, hide_icon_xpm, VW::INTERFACE_AS_BUTTONWINDOW, VW::INTERFACE_AS_WIDGET, load_icon_xpm, save_icon_xpm, and VW::InterfaceGTKWidget::tooltips.
std::string VW::SequencerFileGTKWidget::GetFileName (unsigned int which_channel) [inline]
References file_widgets, and GetFileName().
Referenced by GetFileName(), and VW::SequencerFileGTK::UpdateFromForm().
void VW::SequencerFileGTKWidget::InitForm (SequencerFileGTK * parent)
References add(), AddFile(), VW::InterfaceGTKWidget::button_bar, VW::SequencerFileGTK::Continuous(), files_box, frame_no_label, VW::SequencerBase::GetNumberOfChannels(), go_button, loop_menu, VW::SequencerFileGTK::Next(), next_button, VW::SequencerFileGTK::OnLoopChanged(), VW::SequencerFileGTK::Rewind(), rewind_button, VW::SequencerFileGTK::Stop(), stop_button, and VERBOSE.
Referenced by VW::SequencerFileGTK::SequencerFileGTK().
void VW::SequencerFileGTKWidget::SetLED (unsigned int which_channel, bool valid)
References file_widgets.
Referenced by VW::SequencerFileGTK::UpdateForm().
Member Data Documentation
Gtk::HBox* VW::InterfaceGTKWidget::button_bar [protected, inherited]
Referenced by VW::InterfaceGTKWidget::CreateButtonBar(), VW::YorickGTKWidget::InitForm(), VW::SequencerMovieGTKWidget::InitForm(), VW::SequencerFirewireGTKWidget::InitForm(), InitForm(), VW::PlesseyParamsGTKWidget::InitForm(), VW::FirewireCameraGTKWidget::InitForm(), and VW::ClassifierUVGTKWidget::InitForm().
std::vector<SequencerFileChannelGTKWidget*> VW::SequencerFileGTKWidget::file_widgets [protected]
Referenced by AddFile(), GetFileName(), and SetLED().
Gtk::VBox* VW::SequencerFileGTKWidget::files_box
Referenced by AddFile(), and InitForm().
Gtk::Label* VW::SequencerFileGTKWidget::frame_no_label
Referenced by InitForm(), and VW::SequencerFileGTK::UpdateForm().
Gtk::Button* VW::SequencerFileGTKWidget::go_button
Referenced by InitForm(), and VW::SequencerFileGTK::UpdateForm().
Gtk::OptionMenu* VW::SequencerFileGTKWidget::loop_menu
Referenced by InitForm(), and VW::SequencerFileGTK::SetLooping().
Gtk::Button * VW::SequencerFileGTKWidget::next_button
Referenced by InitForm(), and VW::SequencerFileGTK::UpdateForm().
Gtk::Button * VW::SequencerFileGTKWidget::rewind_button
Referenced by InitForm(), and VW::SequencerFileGTK::UpdateForm().
Gtk::Button * VW::SequencerFileGTKWidget::stop_button
Referenced by InitForm(), and VW::SequencerFileGTK::UpdateForm().
Gtk::Tooltips VW::InterfaceGTKWidget::tooltips [protected, inherited]
Referenced by VW::InterfaceGTKWidget::CreateButtonBar(), VW::PlesseyParamsGTKWidget::InitForm(), and VW::FirewireCameraGTKWidget::InitForm().
The documentation for this class was generated from the following files:
sequencerfilegtk.h
sequencerfilegtk.cpp