VW: VNL::MatlabReadHdr Class Reference
VNL::MatlabReadHdr Class Reference
#include <matlabread.h>
Public Member Functions
MatlabReadHdr (std::istream &)
~MatlabReadHdr ()
operator bool () const
void ReadNext ()
bool IsSingle () const
bool IsRowwise () const
bool IsBigendian () const
long Rows () const
long Cols () const
bool IsComplex () const
char const * Name () const
fsm_declare_methods (float)
fsm_declare_methods (double)
fsm_declare_methods (std::complex< float >)
fsm_declare_methods (std::complex< double >)
Constructor & Destructor Documentation
VNL::MatlabReadHdr::MatlabReadHdr (std::istream & s_)
VNL::MatlabReadHdr::~MatlabReadHdr ()
Member Function Documentation
long VNL::MatlabReadHdr::Cols () const [inline]
References VNL::MatlabHeader::cols.
Referenced by VNL::MatlabReadOrDie(), and ReadNext().
VNL::MatlabReadHdr::fsm_declare_methods (std::complex< double >)
VNL::MatlabReadHdr::fsm_declare_methods (std::complex< float >)
VNL::MatlabReadHdr::fsm_declare_methods (double)
VNL::MatlabReadHdr::fsm_declare_methods (float)
bool VNL::MatlabReadHdr::IsBigendian () const
References VNL::MatlabHeader::type, and VNL::MatlabHeader::VNL_BIG_ENDIAN.
bool VNL::MatlabReadHdr::IsComplex () const [inline]
References VNL::MatlabHeader::imag.
Referenced by ReadNext().
bool VNL::MatlabReadHdr::IsRowwise () const
References VNL::MatlabHeader::type, and VNL::MatlabHeader::VNL_ROW_WISE.
bool VNL::MatlabReadHdr::IsSingle () const
References VNL::MatlabHeader::type, and VNL::MatlabHeader::VNL_SINGLE_PRECISION.
Referenced by ReadNext().
char const* VNL::MatlabReadHdr::Name () const [inline]
Referenced by VNL::MatlabReadOrDie().
VNL::MatlabReadHdr::operator bool () const
void VNL::MatlabReadHdr::ReadNext ()
References Cols(), IsComplex(), IsSingle(), and Rows().
long VNL::MatlabReadHdr::Rows () const [inline]
References VNL::MatlabHeader::rows.
Referenced by VNL::MatlabReadOrDie(), and ReadNext().
The documentation for this class was generated from the following files:
matlabread.h
matlabread.cpp