VW: VW::Delaunay2D Class Reference
VW::Delaunay2D Class Reference
[GeometricAlgorithms]
Voronoi tessellation and Delaunay triangulation.
#include <delaunay.h>
Public Member Functions
Delaunay2D ()
Delaunay2D (int tlx, int tly, int brx, int bry)
~Delaunay2D ()
void ComputeDelaunay (std::vector< Point2D > &pointlist)
void UpdateTessellation (Point2D *p)
void UpdateTessellation (Point2D p)
void UpdateTessellation (double x, double y)
void set_window_limits (int tlx, int tly, int brx, int bry)
void show_tess ()
void read_tess ()
void write_tess ()
std::vector< LineSeg2D > * GetDelaunayEdges ()
Detailed Description
Voronoi tessellation and Delaunay triangulation.
Author:
ID Reid
Date:
02/11/2002 Modified from "fcdt.c", by IDR, 04/2001 Still need to C++ify data structures and add access methdods probably should use stl for storing dlists
Constructor & Destructor Documentation
Delaunay2D::Delaunay2D ()
Delaunay2D::Delaunay2D (int tlx, int tly, int brx, int bry)
References set_window_limits().
Delaunay2D::~Delaunay2D ()
Member Function Documentation
void Delaunay2D::ComputeDelaunay (std::vector< Point2D > & pointlist)
References UpdateTessellation().
std::vector< LineSeg2D > * Delaunay2D::GetDelaunayEdges ()
References VW::Delaunay::DEdge::next, VW::Delaunay::DEdge::p, VW::Delaunay::Point::x, and VW::Delaunay::Point::y.
void Delaunay2D::read_tess ()
References VW::Delaunay::Triangle::de, VW::Delaunay::DEdge::dt, VW::Delaunay::DEdge::label, VW::Delaunay::Point::label, m, VW::Delaunay::Triangle::next, VW::Delaunay::DEdge::next, VW::Delaunay::Point::next, VW::Delaunay::DEdge::p, VW::Delaunay::Triangle::previous, VW::Delaunay::DEdge::previous, VW::Delaunay::Point::previous, VW::Delaunay::Triangle::sr, VW::Delaunay::Triangle::x, VW::Delaunay::Point::x, VW::Delaunay::Triangle::y, and VW::Delaunay::Point::y.
void Delaunay2D::set_window_limits (int tlx, int tly, int brx, int bry)
Referenced by Delaunay2D().
void Delaunay2D::show_tess (void)
References VW::Delaunay::Triangle::de, VW::Delaunay::DEdge::dt, VW::Delaunay::Point::first_neighbour, VW::Delaunay::Point::label, VW::Delaunay::Triangle::label, VW::Delaunay::DEdge::label, VW::Delaunay::Point::n_neighbour, VW::Delaunay::Point::next, VW::Delaunay::NPointer::next, VW::Delaunay::Triangle::next, VW::Delaunay::DEdge::next, VW::Delaunay::DEdge::p, VW::Delaunay::NPointer::point, VW::Delaunay::Triangle::sr, VW::Delaunay::Triangle::x, VW::Delaunay::Point::x, VW::Delaunay::Triangle::y, and VW::Delaunay::Point::y.
void Delaunay2D::UpdateTessellation (double x, double y)
void Delaunay2D::UpdateTessellation (Point2D p)
References VW::Point2D::GetX(), and VW::Point2D::GetY().
void Delaunay2D::UpdateTessellation (Point2D * p)
References VW::Point2D::GetX(), and VW::Point2D::GetY().
Referenced by ComputeDelaunay().
void Delaunay2D::write_tess (void)
References VW::Delaunay::Triangle::de, VW::Delaunay::NPointer::de, VW::Delaunay::DEdge::dt, VW::Delaunay::Point::first_neighbour, if, VW::Delaunay::Triangle::label, VW::Delaunay::DEdge::label, VW::Delaunay::Point::label, VW::Delaunay::NPointer::next, VW::Delaunay::Triangle::next, VW::Delaunay::DEdge::next, VW::Delaunay::Point::next, VW::Delaunay::DEdge::p, VW::Delaunay::NPointer::point, VW::Delaunay::Triangle::sr, VW::Delaunay::Triangle::x, VW::Delaunay::Point::x, VW::Delaunay::Triangle::y, and VW::Delaunay::Point::y.
The documentation for this class was generated from the following files:
delaunay.h
delaunay.cpp