VW: VNL::SymmetricEigensystem< T > Class Template Reference
VNL::SymmetricEigensystem< T > Class Template Reference
Computes and stores the eigensystem decomposition of a symmetric matrix.
#include <symmetriceigensystem.h>
Public Member Functions
SymmetricEigensystem (Matrix< T > const &M)
Solve real symmetric eigensystem $A x = x$.
Vector< T > GetEigenvector (int i) const
Recover specified eigenvector after computation.
T GetEigenvalue (int i) const
Recover specified eigenvalue after computation.
Vector< T > Nullvector () const
Convenience method to get least-squares nullvector.
Matrix< T > Recompose () const
Return the matrix $V D V^$.
Matrix< T > PsuedoInverse () const
return the pseudoinverse.
Matrix< T > SquareRoot () const
return the square root, if positive semi-definite.
Matrix< T > InverseSquareRoot () const
return the inverse of the square root, if positive semi-definite.
Vector< T > Solve (Vector< T > const &b)
Solve LS problem M x = b.
void Solve (Vector< T > const &b, Vector< T > *x)
Solve LS problem M x = b.
Public Attributes
Matrix< T > V
Public eigenvectors.
DiagMatrix< T > D
Public eigenvalues.
Protected Attributes
int n_
Detailed Description
template<class T>
class VNL::SymmetricEigensystem< T >
Computes and stores the eigensystem decomposition of a symmetric matrix.
Constructor & Destructor Documentation
template<class T > VNL::SymmetricEigensystem< T >::SymmetricEigensystem (VNL::Matrix< T > const & A) [inline]
Solve real symmetric eigensystem $A x = x$.
References VNL::SymmetricEigensystem< T >::D, VNL::SymmetricEigensystem< T >::n_, VNL::SymmetricEigensystemCompute(), and VNL::SymmetricEigensystem< T >::V.
Member Function Documentation
template<class T > T VNL::SymmetricEigensystem< T >::GetEigenvalue (int i) const [inline]
Recover specified eigenvalue after computation.
References VNL::SymmetricEigensystem< T >::D.
Referenced by VW::ThreePointPose::ComputeQRotn(), and VW::ThreeDToolGLCommon::Draw2DCovariance().
template<class T > VNL::Vector< T > VNL::SymmetricEigensystem< T >::GetEigenvector (int i) const [inline]
Recover specified eigenvector after computation.
References VNL::SymmetricEigensystem< T >::n_, and VNL::SymmetricEigensystem< T >::V.
Referenced by VW::ThreePointPose::ComputeQRotn(), and VNL::SymmetricEigensystem< T >::Nullvector().
template<class T > VNL::Matrix< T > VNL::SymmetricEigensystem< T >::InverseSquareRoot () const [inline]
return the inverse of the square root, if positive semi-definite.
References VNL::SymmetricEigensystem< T >::D, std::sqrt(), and VNL::SymmetricEigensystem< T >::V.
template<class T> Vector<T> VNL::SymmetricEigensystem< T >::Nullvector () const [inline]
Convenience method to get least-squares nullvector.
It is deliberate that the signature is the same as on vnl_svd<T>.
References VNL::SymmetricEigensystem< T >::GetEigenvector().
Referenced by VW::EssentialMatrixCompute::RecoverE(), VW::FMatrixCompute::RecoverF(), and VW::FMatrixAffineCompute::RecoverF().
template<class T > VNL::Matrix< T > VNL::SymmetricEigensystem< T >::PsuedoInverse () const [inline]
return the pseudoinverse.
References VNL::SymmetricEigensystem< T >::D, and VNL::SymmetricEigensystem< T >::V.
template<class T> Matrix<T> VNL::SymmetricEigensystem< T >::Recompose () const [inline]
Return the matrix $V D V^$.
This can be useful if you've modified . So an inverse is obtained using
   vnl_symmetric_eigensystem} eig(A);
   eig.D.invert_in_place}();
   VNL::Matrix<double> Ainverse = eig.recompose();
References VNL::SymmetricEigensystem< T >::D, and VNL::SymmetricEigensystem< T >::V.
template<class T> void VNL::SymmetricEigensystem< T >::Solve (Vector< T > const & b, Vector< T > * x)
Solve LS problem M x = b.
template<class T > VNL::Vector< T > VNL::SymmetricEigensystem< T >::Solve (VNL::Vector< T > const & b) [inline]
Solve LS problem M x = b.
References VNL::SymmetricEigensystem< T >::D, VNL::Vector< T >::size(), and VNL::SymmetricEigensystem< T >::V.
template<class T > VNL::Matrix< T > VNL::SymmetricEigensystem< T >::SquareRoot () const [inline]
return the square root, if positive semi-definite.
References VNL::SymmetricEigensystem< T >::D, std::sqrt(), and VNL::SymmetricEigensystem< T >::V.
Member Data Documentation
template<class T> DiagMatrix<T> VNL::SymmetricEigensystem< T >::D
Public eigenvalues.
After construction, D contains the eigenvalues, sorted as described above. Note that D is a DiagMatrix, and is therefore stored as a std::vector while behaving as a matrix.
Referenced by VNL::GeneralizedEigensystem::GeneralizedEigensystem(), VNL::SymmetricEigensystem< T >::GetEigenvalue(), VNL::SymmetricEigensystem< T >::InverseSquareRoot(), VNL::SymmetricEigensystem< T >::PsuedoInverse(), VNL::SymmetricEigensystem< T >::Recompose(), VNL::SymmetricEigensystem< T >::Solve(), VNL::SymmetricEigensystem< T >::SquareRoot(), and VNL::SymmetricEigensystem< T >::SymmetricEigensystem().
template<class T> int VNL::SymmetricEigensystem< T >::n_ [protected]
Referenced by VNL::SymmetricEigensystem< T >::GetEigenvector(), and VNL::SymmetricEigensystem< T >::SymmetricEigensystem().
template<class T> Matrix<T> VNL::SymmetricEigensystem< T >::V
Public eigenvectors.
After construction, the columns of V are the eigenvectors, sorted by increasing eigenvalue, from most negative to most positive.
Referenced by VW::ThreeDToolGLCommon::Draw2DCovariance(), VNL::GeneralizedEigensystem::GeneralizedEigensystem(), VNL::SymmetricEigensystem< T >::GetEigenvector(), VNL::SymmetricEigensystem< T >::InverseSquareRoot(), VNL::SymmetricEigensystem< T >::PsuedoInverse(), VNL::SymmetricEigensystem< T >::Recompose(), VW::EssentialMatrixCompute::RecoverE(), VW::FMatrixCompute::RecoverF(), VW::FMatrixAffineCompute::RecoverF(), VNL::SymmetricEigensystem< T >::Solve(), VNL::SymmetricEigensystem< T >::SquareRoot(), and VNL::SymmetricEigensystem< T >::SymmetricEigensystem().
The documentation for this class was generated from the following files:
symmetriceigensystem.h
symmetriceigensystem.cpp