VW: VW::LineFit Class Reference
VW::LineFit Class Reference
Fit lines to edge data.
#include <linefit.h>
Public Member Functions
LineFit (const double lim=LIM_DEFAULT, const int len=LEN_DEFAULT)
LineFit (const EdgeData &edat, std::list< LineSegFitted > &lines, const double lim=LIM_DEFAULT, const int len=LEN_DEFAULT)
LineFit (const EdgeString *s, std::list< VW::LineSegFitted > &lines, const double lim=LIM_DEFAULT, const int len=LEN_DEFAULT)
void Compute (const EdgeData &edat, std::list< LineSegFitted > &lines)
void Compute (const EdgeString *s, std::list< LineSegFitted > &lines)
operator bool ()
Detailed Description
Fit lines to edge data.
Parameters:
edat the input edge data (as output from VW::Canny)
lines the resulting set of straight line segments
lambda_lim a threshold on line straightness based on ratio of minimum eigenval of scatter matrix to number of points in the line (default 0.5)
lengththresh the minimum line length to be included in the result
Constructor & Destructor Documentation
VW::LineFit::LineFit (const double lim = LIM_DEFAULT, const int len = LEN_DEFAULT) [inline]
VW::LineFit::LineFit (const EdgeData & edat, std::list< LineSegFitted > & lines, const double lim = LIM_DEFAULT, const int len = LEN_DEFAULT) [inline]
References Compute().
VW::LineFit::LineFit (const EdgeString * s, std::list< VW::LineSegFitted > & lines, const double lim = LIM_DEFAULT, const int len = LEN_DEFAULT) [inline]
References Compute().
Member Function Documentation
void VW::LineFit::Compute (const EdgeString * s, std::list< LineSegFitted > & lines)
void VW::LineFit::Compute (const EdgeData & edat, std::list< LineSegFitted > & lines)
Referenced by LineFit().
VW::LineFit::operator bool () [inline]
The documentation for this class was generated from the following files:
linefit.h
linefit.cpp