VW: VNL::LSqr Class Reference
VNL::LSqr Class Reference
Linear least squares.
#include <lsqr.h>
Public Member Functions
LSqr (LinearSystem &ls)
~LSqr ()
void SetMaxIterations (int max_iter)
int Minimize (VNL::Vector< double > &x)
Perform the minimization starting from x=0 and putting the result into x.
int GetNumberOfIterations () const
void DiagnoseOutcome (std::ostream &os) const
Pontificate about the outcome of the last minimization.
Static Public Member Functions
static void TranslateReturnCode (std::ostream &os, int return_code)
Static Protected Member Functions
static void aprod_ (int *mode, int *m, int *n, double *x, double *y, int *leniw, int *lenrw, int *iw, double *rw)
Protected Attributes
LinearSystem * ls_
int max_iter_
int num_iter_
double resid_norm_estimate_
double result_norm_estimate_
double A_condition_estimate_
double result_norm_
int return_code_
Friends
class LSqrActivate
Detailed Description
Linear least squares.
LSqr implements an algorithm for large, sparse linear systems and sparse, linear least squares. It is a wrapper for the LSQR algorithm of Paige and Saunders (ACM TOMS 583). The sparse system is encapsulated by a VNL::LinearSystem.
Constructor & Destructor Documentation
VNL::LSqr::LSqr (LinearSystem & ls) [inline]
VNL::LSqr::~LSqr ()
Member Function Documentation
void VNL::LSqr::aprod_ (int * mode, int * m, int * n, double * x, double * y, int * leniw, int * lenrw, int * iw, double * rw) [static, protected]
References ls_, VNL::LinearSystem::Multiply(), and VNL::LinearSystem::TransposeMultiply().
Referenced by Minimize().
void VNL::LSqr::DiagnoseOutcome (std::ostream & os) const
Pontificate about the outcome of the last minimization.
References A_condition_estimate_, num_iter_, resid_norm_estimate_, result_norm_estimate_, return_code_, and TranslateReturnCode().
int VNL::LSqr::GetNumberOfIterations () const [inline]
References num_iter_.
int VNL::LSqr::Minimize (VNL::Vector< double > & x)
Perform the minimization starting from x=0 and putting the result into x.
Return code may be translated with translate_return_code().
References A_condition_estimate_, aprod_(), VNL::Vector< T >::DataBlock(), VNL::LinearSystem::GetNumberOfResiduals(), VNL::LinearSystem::GetNumberOfUnknowns(), VNL::LinearSystem::GetRHS(), ls_, lsqr_(), m, max_iter_, num_iter_, resid_norm_estimate_, result_norm_estimate_, return_code_, and v.
void VNL::LSqr::SetMaxIterations (int max_iter) [inline]
References max_iter_.
void VNL::LSqr::TranslateReturnCode (std::ostream & os, int return_code) [static]
Referenced by DiagnoseOutcome().
Friends And Related Function Documentation
friend class LSqrActivate [friend]
Member Data Documentation
double VNL::LSqr::A_condition_estimate_ [protected]
Referenced by DiagnoseOutcome(), and Minimize().
LinearSystem* VNL::LSqr::ls_ [protected]
Referenced by aprod_(), and Minimize().
int VNL::LSqr::max_iter_ [protected]
Referenced by Minimize(), and SetMaxIterations().
int VNL::LSqr::num_iter_ [protected]
Referenced by DiagnoseOutcome(), GetNumberOfIterations(), and Minimize().
double VNL::LSqr::resid_norm_estimate_ [protected]
Referenced by DiagnoseOutcome(), and Minimize().
double VNL::LSqr::result_norm_ [protected]
double VNL::LSqr::result_norm_estimate_ [protected]
Referenced by DiagnoseOutcome(), and Minimize().
int VNL::LSqr::return_code_ [protected]
Referenced by DiagnoseOutcome(), and Minimize().
The documentation for this class was generated from the following files:
lsqr.h
lsqr.cpp