VW: VW::IntegralImageSquared< DataType > Class Template Reference
VW::IntegralImageSquared< DataType > Class Template Reference
[ImageProcessing]
Implementation of integral image squared.
#include <integralimagesquared.h>
Public Member Functions
IntegralImageSquared ()
~IntegralImageSquared ()
template<class InType >
IntegralImageSquared (const ImageMono< InType > &im)
Construct and compute from source image im.
template<class InType >
IntegralImageSquared (const ImageYUV< InType > &im)
Construct and compute from Y channel of source image im.
template<class InType >
IntegralImageSquared (const ImageYUV< InType > &im, const ROI &roi)
Construct and compute from Y channel of source image im.
template<class InType >
void Compute (const ImageMono< InType > &im)
Compute the integral image squared from source image im.
template<class InType >
void Compute (const ImageYUV< InType > &im)
Compute the integral image squared from Y channel of source image im.
template<class InType >
void Compute (const ImageYUV< InType > &im, const ROI &roi)
Compute the integral image squared from Y channel of source image im.
DataType GetRegionSumSquared (int x0, int y0, int x1, int y1) const
Compute the sum-squared over a region (x0,y0)-(x1,y1) inclusive.
unsigned int GetWidth () const
unsigned int GetHeight () const
operator bool ()
Detailed Description
template<class DataType>
class VW::IntegralImageSquared< DataType >
Implementation of integral image squared.
Author:
BJ Tordoff
Date:
03/04/2004 The class is templated on the internal storage type, which should be at least as big as the data-type of the image being integrated. Usually you should maintain signed-ness, such as: Image Type Integral Image Type "unsigned char" -> "unsigned int" or "long unsigned int" "char" -> "int" or "long int" "unsigned int" -> "long unsigned int" "int" -> "long int" "float" -> "float" or "double" "double" -> "double" or "long double"
Constructor & Destructor Documentation
template<class DataType> VW::IntegralImageSquared< DataType >::IntegralImageSquared () [inline]
template<class DataType > VW::IntegralImageSquared< DataType >::~IntegralImageSquared () [inline]
template<class DataType > template<class InType > VW::IntegralImageSquared< DataType >::IntegralImageSquared (const ImageMono< InType > & im) [inline]
Construct and compute from source image im.
References VW::IntegralImageSquared< DataType >::Compute().
template<class DataType > template<class InType > VW::IntegralImageSquared< DataType >::IntegralImageSquared (const ImageYUV< InType > & im) [inline]
Construct and compute from Y channel of source image im.
References VW::IntegralImageSquared< DataType >::Compute().
template<class DataType > template<class InType > VW::IntegralImageSquared< DataType >::IntegralImageSquared (const ImageYUV< InType > & im, const ROI & roi) [inline]
Construct and compute from Y channel of source image im.
References VW::IntegralImageSquared< DataType >::Compute().
Member Function Documentation
template<class DataType > template<class InType > void IntegralImageSquared::Compute (const ImageYUV< InType > & im, const ROI & roi) [inline]
Compute the integral image squared from Y channel of source image im.
References VW::ROI::Get(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetRowStart(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), and VW::PixelYUV< Type >::y.
template<class DataType > template<class InType > void VW::IntegralImageSquared< DataType >::Compute (const ImageYUV< InType > & im) [inline]
Compute the integral image squared from Y channel of source image im.
References VW::IntegralImageSquared< DataType >::Compute(), and VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::ROI().
template<class DataType > template<class InType > void IntegralImageSquared::Compute (const ImageMono< InType > & im) [inline]
Compute the integral image squared from source image im.
References VW::ROI::Get(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetROIRowStart(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::ROI(), and VW::PixelMono< Type >::y.
Referenced by VW::IntegralImageSquared< DataType >::Compute(), and VW::IntegralImageSquared< DataType >::IntegralImageSquared().
template<class DataType> unsigned int VW::IntegralImageSquared< DataType >::GetHeight (void) const [inline]
template<class DataType > DataType VW::IntegralImageSquared< DataType >::GetRegionSumSquared (int x0, int y0, int x1, int y1) const [inline]
Compute the sum-squared over a region (x0,y0)-(x1,y1) inclusive.
Referenced by VW::Correlate::Compute().
template<class DataType> unsigned int VW::IntegralImageSquared< DataType >::GetWidth (void) const [inline]
template<class DataType> VW::IntegralImageSquared< DataType >::operator bool () [inline]
The documentation for this class was generated from the following files:
integralimagesquared.h
integralimagesquared.cpp