VW: VW::PlesseyOld Class Reference
VW::PlesseyOld Class Reference
#include <plesseyold.h>
Public Member Functions
PlesseyOld (string paramfile="")
INLINES ///.
PlesseyOld (const ImageMono< unsigned char > &im, vector< PlesseyCorner > &corners, float thresh=PlesseyOldParamsDefaults::DEF_THRESH, float sigma=PlesseyOldParamsDefaults::DEF_SIGMA, int size=PlesseyOldParamsDefaults::DEF_SIZE, float ep=PlesseyOldParamsDefaults::DEF_EDGEPHOBIA, const Normalisation &C=Normalisation())
PlesseyOld (const ImageMono< unsigned char > &im, vector< PlesseyCorner > &corners, const PlesseyOldParams &_params, const Normalisation &C=Normalisation())
PlesseyOld (const ImageMono< unsigned char > &im, vector< PlesseyCorner > &corners, string paramfile, const Normalisation &C=Normalisation())
PlesseyOld (const ImageYUV< unsigned char > &im, vector< PlesseyCorner > &corners, float thresh=PlesseyOldParamsDefaults::DEF_THRESH, float sigma=PlesseyOldParamsDefaults::DEF_SIGMA, int size=PlesseyOldParamsDefaults::DEF_SIZE, float ep=PlesseyOldParamsDefaults::DEF_EDGEPHOBIA, const Normalisation &C=Normalisation())
PlesseyOld (const ImageYUV< unsigned char > &im, vector< PlesseyCorner > &corners, const PlesseyOldParams &_params, const Normalisation &C=Normalisation())
PlesseyOld (const ImageYUV< unsigned char > &im, vector< PlesseyCorner > &corners, string paramfile, const Normalisation &C=Normalisation())
~PlesseyOld ()
operator bool () const
void Compute (const ImageMono< unsigned char > &im, vector< PlesseyCorner > &corners, const Normalisation &C=Normalisation()) const
void Compute (const ImageYUV< unsigned char > &im, vector< PlesseyCorner > &corners, const Normalisation &C=Normalisation()) const
PlesseyOldParams * GetParams ()
void SetParams (PlesseyOldParams &new_params)
Public Attributes
bool Verbose
Constructor & Destructor Documentation
VW::PlesseyOld::PlesseyOld (string paramfile = "") [inline]
INLINES ///.
References VW::PlesseyOldParams::LoadParameterFile().
VW::PlesseyOld::PlesseyOld (const ImageMono< unsigned char > & im, vector< PlesseyCorner > & corners, float thresh = PlesseyOldParamsDefaults::DEF_THRESH, float sigma = PlesseyOldParamsDefaults::DEF_SIGMA, int size = PlesseyOldParamsDefaults::DEF_SIZE, float ep = PlesseyOldParamsDefaults::DEF_EDGEPHOBIA, const Normalisation & C = Normalisation()) [inline]
References Compute().
VW::PlesseyOld::PlesseyOld (const ImageMono< unsigned char > & im, vector< PlesseyCorner > & corners, const PlesseyOldParams & _params, const Normalisation & C = Normalisation()) [inline]
References Compute().
VW::PlesseyOld::PlesseyOld (const ImageMono< unsigned char > & im, vector< PlesseyCorner > & corners, string paramfile, const Normalisation & C = Normalisation()) [inline]
References Compute(), and VW::PlesseyOldParams::LoadParameterFile().
VW::PlesseyOld::PlesseyOld (const ImageYUV< unsigned char > & im, vector< PlesseyCorner > & corners, float thresh = PlesseyOldParamsDefaults::DEF_THRESH, float sigma = PlesseyOldParamsDefaults::DEF_SIGMA, int size = PlesseyOldParamsDefaults::DEF_SIZE, float ep = PlesseyOldParamsDefaults::DEF_EDGEPHOBIA, const Normalisation & C = Normalisation()) [inline]
References Compute().
VW::PlesseyOld::PlesseyOld (const ImageYUV< unsigned char > & im, vector< PlesseyCorner > & corners, const PlesseyOldParams & _params, const Normalisation & C = Normalisation()) [inline]
References Compute().
VW::PlesseyOld::PlesseyOld (const ImageYUV< unsigned char > & im, vector< PlesseyCorner > & corners, string paramfile, const Normalisation & C = Normalisation()) [inline]
References Compute(), and VW::PlesseyOldParams::LoadParameterFile().
VW::PlesseyOld::~PlesseyOld () [inline]
Member Function Documentation
void PlesseyOld::Compute (const ImageYUV< unsigned char > & im, vector< PlesseyCorner > & corners, const Normalisation & C = Normalisation()) const
References VW::PlesseyOldParams::GetGaussianSigma(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::PlesseyOldParams::GetPatchSize(), VW::PlesseyOldParams::GetStrengthThreshold(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), VW::Normalisation::Normalise(), and VERBOSE.
void PlesseyOld::Compute (const ImageMono< unsigned char > & im, vector< PlesseyCorner > & corners, const Normalisation & C = Normalisation()) const
References VW::PlesseyOldParams::GetGaussianSigma(), VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::PlesseyOldParams::GetPatchSize(), VW::PlesseyOldParams::GetStrengthThreshold(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), VW::Normalisation::Normalise(), and VERBOSE.
Referenced by PlesseyOld().
PlesseyOldParams* VW::PlesseyOld::GetParams () [inline]
VW::PlesseyOld::operator bool () const [inline]
void VW::PlesseyOld::SetParams (PlesseyOldParams & new_params) [inline]
Member Data Documentation
bool VW::PlesseyOld::Verbose
The documentation for this class was generated from the following files:
plesseyold.h
plesseyold.cpp