VW: VW::Warp Class Reference
VW::Warp Class Reference
[ImageProcessing]
Warp a 2D image according to homography H.
#include <warp.h>
Public Member Functions
Warp ()
Warp (const VW::Homography2D &H)
Warp (const VW::Homography2D &H, const double distortion_kappa, const VW::Point2D &distortion_centre)
template<class InType , class OutType >
Warp (const InType &im, const VW::Homography2D &H, OutType &res, InterpolationMethod method=Bilinear)
Compute assuming homography is *NOT* normalised.
template<class InType , class OutType >
Warp (const InType &im, const VW::Homography2D &H, const double distortion_kappa, const VW::Point2D &distortion_centre, OutType &res, InterpolationMethod method=Bilinear)
Compute assuming homography is *NOT* normalised.
operator bool ()
template<class InType , class OutType >
void Compute (const InType &im, OutType &res, InterpolationMethod method=Bilinear)
void SetTransformation (const VW::Homography2D &H)
void SetDistortion (const double distortion_kappa, const VW::Point2D &distortion_centre)
Detailed Description
Warp a 2D image according to homography H.
Author:
ID Reid
Date:
02/08/2002 include <VW/Improc/warp.h>
Given an invertible 2D projective transformation (ie. non-singular 3x3 matrix) H, every point in the target image can be calculated from the input image.
Note that H must NOT be normalised - it must be in image coordinates, as must the distortion (if any). If you only want to correct distortion, use the DistortImage class.
Usage: VW::Warp w(H); w.Compute(input_image, output_image); or VW::Warp(input_image, H, output_image);
Constructor & Destructor Documentation
VW::Warp::Warp () [inline]
References VNL::Matrix< T >::SetIdentity().
VW::Warp::Warp (const VW::Homography2D & H) [inline]
VW::Warp::Warp (const VW::Homography2D & H, const double distortion_kappa, const VW::Point2D & distortion_centre) [inline]
template<class InType , class OutType > VW::Warp::Warp (const InType & im, const VW::Homography2D & H, OutType & res, InterpolationMethod method = Bilinear) [inline]
Compute assuming homography is *NOT* normalised.
References Compute().
template<class InType , class OutType > VW::Warp::Warp (const InType & im, const VW::Homography2D & H, const double distortion_kappa, const VW::Point2D & distortion_centre, OutType & res, InterpolationMethod method = Bilinear) [inline]
Compute assuming homography is *NOT* normalised.
References Compute().
Member Function Documentation
template<class InType , class OutType > void Warp::Compute (const InType & im, OutType & res, InterpolationMethod method = Bilinear) [inline]
References VW::Bicubic, VW::Bilinear, VW::Biquadratic, c, and VW::NearestNeighbour.
Referenced by Warp().
VW::Warp::operator bool () [inline]
void VW::Warp::SetDistortion (const double distortion_kappa, const VW::Point2D & distortion_centre) [inline]
References VW::Point2D::GetX(), and VW::Point2D::GetY().
void VW::Warp::SetTransformation (const VW::Homography2D & H) [inline]
The documentation for this class was generated from the following files:
warp.h
warp.cpp