VW: VW::Canny Class Reference
VW::Canny Class Reference
[ImageProcessing]
Class for computing image edges using the method of Canny.
#include <canny.h>
Public Member Functions
Canny (float _sigma=1.0, int _size=5, float _lo=10.0, float _hi=20.0, int _len=20)
Create the Canny object with specified parameters, but do not compute anything yet.
Canny (const ImageMono< unsigned char > &im, EdgeData &edat, float _sigma=1.0, int _size=5, float _lo=10.0, float _hi=20.0, int _len=20)
Create the Canny object with specified parameters, and compute the edge data for an image.
Canny (const ImageYUV< unsigned char > &im, EdgeData &edat, float _sigma=1.0, int _size=5, float _lo=10.0, float _hi=20.0, int _len=20)
Create the Canny object with specified parameters, and compute the edge data for an image.
void Compute (const ImageMono< unsigned char > &im, EdgeData &edat) const
Compute the edge data for an image.
void Compute (const ImageYUV< unsigned char > &im, EdgeData &edat) const
Compute the edge data for the Y channel of a YUV image.
operator bool ()
void SetGaussSigma (float val)
Set a new value for the standard deviation of the Gaussian kernel.
void SetGaussSize (int val)
Set a new value for the size of the Gaussian kernel.
void SetHiThreshold (float val)
Set a new value for the high water mark used for hysteresis.
void SetLoThreshold (float val)
Set a new value for the low water mark used for hysteresis.
void SetLenThreshold (int val)
Set a new value for the minimum edge length.
Detailed Description
Class for computing image edges using the method of Canny.
Author:
DW Murray and ID Reid
Date:
02/08/2002 Modified 16/6/2004 BJT: Add YUV support
Constructor & Destructor Documentation
VW::Canny::Canny (float _sigma = 1.0, int _size = 5, float _lo = 10.0, float _hi = 20.0, int _len = 20) [inline]
Create the Canny object with specified parameters, but do not compute anything yet.
Parameters:
sigma the standard deviation of the Gaussian smoothing kernel
size the size of the convolution kernel
hi the "high water mark" edge strength kept in the hysteresis step
lo the "low water mark" edge strength kept in the hysteresis step
len the minimum edge length that is retained
VW::Canny::Canny (const ImageMono< unsigned char > & im, EdgeData & edat, float _sigma = 1.0, int _size = 5, float _lo = 10.0, float _hi = 20.0, int _len = 20) [inline]
Create the Canny object with specified parameters, and compute the edge data for an image.
Parameters:
im the image in which edges will be found
edat the resulting edge data
sigma the standard deviation of the Gaussian smoothing kernel
size the size of the convolution kernel
hi the "high water mark" edge strength kept in the hysteresis step
lo the "low water mark" edge strength kept in the hysteresis step
len the minimum edge length that is retained
References Compute().
VW::Canny::Canny (const ImageYUV< unsigned char > & im, EdgeData & edat, float _sigma = 1.0, int _size = 5, float _lo = 10.0, float _hi = 20.0, int _len = 20) [inline]
Create the Canny object with specified parameters, and compute the edge data for an image.
Parameters:
im the image in which edges will be found
edat the resulting edge data
sigma the standard deviation of the Gaussian smoothing kernel
size the size of the convolution kernel
hi the "high water mark" edge strength kept in the hysteresis step
lo the "low water mark" edge strength kept in the hysteresis step
len the minimum edge length that is retained
References Compute().
Member Function Documentation
void Canny::Compute (const ImageYUV< unsigned char > & im, EdgeData & edata) const
Compute the edge data for the Y channel of a YUV image.
Parameters:
im the image in which edges will be found
edat the resulting edge data
References Compute(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetRowStart(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetRowStart(), and VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth().
void Canny::Compute (const ImageMono< unsigned char > & im, EdgeData & edata) const
Compute the edge data for an image.
Parameters:
im the image in which edges will be found
edat the resulting edge data
References VW::EdgeData::edgels, VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), VW::ConvolutionMask1D< maskType >::MakeGaussian(), and VW::EdgeData::strings.
Referenced by Canny(), and Compute().
VW::Canny::operator bool () [inline]
void VW::Canny::SetGaussSigma (float val) [inline]
Set a new value for the standard deviation of the Gaussian kernel.
void VW::Canny::SetGaussSize (int val) [inline]
Set a new value for the size of the Gaussian kernel.
void VW::Canny::SetHiThreshold (float val) [inline]
Set a new value for the high water mark used for hysteresis.
void VW::Canny::SetLenThreshold (int val) [inline]
Set a new value for the minimum edge length.
void VW::Canny::SetLoThreshold (float val) [inline]
Set a new value for the low water mark used for hysteresis.
The documentation for this class was generated from the following files:
canny.h
canny.cpp