VW: CompareY Class Reference
CompareY Class Reference
Public Member Functions
int operator() (const VW::CornerFeature &c1, const VW::CornerFeature &c2) const
int operator() (const VW::PlesseyCorner &c1, const VW::PlesseyCorner &c2) const
int operator() (const VW::PlesseyCornerYUV &c1, const VW::PlesseyCornerYUV &c2) const
Member Function Documentation
int CompareY::operator() (const VW::PlesseyCornerYUV & c1, const VW::PlesseyCornerYUV & c2) const [inline]
References VW::Point2D::GetY().
int CompareY::operator() (const VW::PlesseyCorner & c1, const VW::PlesseyCorner & c2) const [inline]
References VW::Point2D::GetY().
int CompareY::operator() (const VW::CornerFeature & c1, const VW::CornerFeature & c2) const [inline]
References VW::Point2D::GetY().
The documentation for this class was generated from the following files:
cornerfeature.cpp
plesseycorner.cpp
plesseycorneryuv.cpp