VW: YorickPMAC Class Reference
YorickPMAC Class Reference
#include <yorickpmac.h>
Public Types
enum PMACMode { PMAC_UNINITIALIZED = -2, PMAC_OFF, PMAC_PENDING, PMAC_ON }
enum PMACAction { PMAC_NODEMAND = 0, PMAC_DEMAND = 1, PMAC_HOMEZ = 2 }
enum PMACValidFlags {
PMAC_PAN = 1, PMAC_TILT = 2, PMAC_VERGELEFT = 4, PMAC_VERGERIGHT = 8,
PMAC_ALL = 15
}
Public Member Functions
YorickPMAC (void)
~YorickPMAC ()
void Close (void)
bool Init (void)
int Download (const int pmac, char *filename, int pflag)
void SetMode (const PMACMode mode)
PMACMode GetMode (void)
void SetModePending (void)
void SetModeOn (void)
void SetModeOff (void)
int GetState (void)
void GetOdometry (int seq_no, int *time, float *pan, float *tilt, float *vergeleft, float *vergeright)
void GetVelocity (int seq_no, int *time, float *vpan, float *vtilt, float *vvergeleft, float *vvergeright)
int ZeroOdometry (void)
void Demand (int seq_no, int time, int action, int valid_flags, float pan, float elev, float vergeleft, float vergeright)
Member Enumeration Documentation
enum YorickPMAC::PMACAction
Enumerator:
PMAC_NODEMAND
PMAC_DEMAND
PMAC_HOMEZ
enum YorickPMAC::PMACMode
Enumerator:
PMAC_UNINITIALIZED
PMAC_OFF
PMAC_PENDING
PMAC_ON
enum YorickPMAC::PMACValidFlags
Enumerator:
PMAC_PAN
PMAC_TILT
PMAC_VERGELEFT
PMAC_VERGERIGHT
PMAC_ALL
Constructor & Destructor Documentation
YorickPMAC::YorickPMAC (void)
YorickPMAC::~YorickPMAC (void)
References Close().
Member Function Documentation
void YorickPMAC::Close (void)
References SetModePending().
Referenced by VW::Yorick::SetActive(), VW::Yorick::~Yorick(), and ~YorickPMAC().
void YorickPMAC::Demand (int seq_no, int time, int action, int valid_flags, float pan, float elev, float vergeleft, float vergeright)
Referenced by VW::Yorick::Demand(), VW::Yorick::DemandPan(), VW::Yorick::DemandPanTilt(), VW::Yorick::DemandTilt(), VW::Yorick::DemandVerge(), VW::Yorick::DemandVergeLeft(), VW::Yorick::DemandVergeRight(), VW::Yorick::Homez(), and VW::Yorick::HomezOneAxis().
int YorickPMAC::Download (const int pmac, char * filename, int pflag)
References BUFLEN.
YorickPMAC::PMACMode YorickPMAC::GetMode (void)
References PMAC_UNINITIALIZED.
Referenced by VW::Yorick::Demand(), VW::Yorick::DemandPan(), VW::Yorick::DemandPanTilt(), VW::Yorick::DemandTilt(), VW::Yorick::DemandVerge(), VW::Yorick::DemandVergeLeft(), VW::Yorick::DemandVergeRight(), VW::Yorick::FlushHistory(), VW::Yorick::GetHistoricPositionAndUncertainty(), VW::Yorick::GetPosition(), VW::Yorick::GetPositionAndStore(), VW::Yorick::GetVelocity(), VW::Yorick::Homez(), VW::Yorick::HomezOneAxis(), VW::Yorick::IsPMACOpen(), VW::Yorick::SetActive(), and VW::Yorick::SlowDemand().
void YorickPMAC::GetOdometry (int seq_no, int * time, float * pan, float * tilt, float * vergeleft, float * vergeright)
Referenced by VW::Yorick::FlushHistory(), VW::Yorick::GetHistoricPositionAndUncertainty(), VW::Yorick::GetPosition(), VW::Yorick::GetPositionAndStore(), and VW::Yorick::SlowDemand().
int YorickPMAC::GetState (void)
Referenced by VW::Yorick::ReadState().
void YorickPMAC::GetVelocity (int seq_no, int * time, float * vpan, float * vtilt, float * vvergeleft, float * vvergeright)
Referenced by VW::Yorick::GetVelocity().
bool YorickPMAC::Init (void)
References SetModeOn().
Referenced by VW::Yorick::SetActive().
void YorickPMAC::SetMode (const PMACMode mode)
Referenced by SetModeOff(), SetModeOn(), and SetModePending().
void YorickPMAC::SetModeOff (void)
References PMAC_OFF, and SetMode().
void YorickPMAC::SetModeOn (void)
References PMAC_ON, and SetMode().
Referenced by Init().
void YorickPMAC::SetModePending (void)
References PMAC_PENDING, and SetMode().
Referenced by Close(), and VW::Yorick::SetActive().
int YorickPMAC::ZeroOdometry (void)
The documentation for this class was generated from the following files:
yorickpmac.h
yorickpmac.cpp