VW: VW::SequencerMovieChannelGTKWidget Class Reference
VW::SequencerMovieChannelGTKWidget Class Reference
#include <sequencermoviegtk.h>
Public Member Functions
void InitForm (SequencerMovieGTK *main_form)
std::string GetMovieName ()
void SetMovieName (const std::string s)
void SetLED (bool valid)
Protected Member Functions
void LoadStart ()
void LoadOK ()
void LoadCancel ()
Protected Attributes
Gtk::FileSelection * file_selector
SequencerMovieGTK * _main_form
Gtk::Entry * file_name
Gtk::Button * browse_button
Gtk::Pixmap * status_led
Member Function Documentation
std::string VW::SequencerMovieChannelGTKWidget::GetMovieName ()
References file_name.
void VW::SequencerMovieChannelGTKWidget::InitForm (SequencerMovieGTK * main_form)
References _main_form, add(), browse_button, file_name, led_off_xpm, load_icon_xpm, LoadStart(), status_led, and VW::SequencerMovieGTK::UpdateFromForm().
void VW::SequencerMovieChannelGTKWidget::LoadCancel () [protected]
References _main_form, file_name, file_selector, and VW::SequencerMovieGTK::UpdateFromForm().
Referenced by LoadStart().
void VW::SequencerMovieChannelGTKWidget::LoadOK () [protected]
References _main_form, file_name, file_selector, and VW::SequencerMovieGTK::UpdateFromForm().
Referenced by LoadStart().
void VW::SequencerMovieChannelGTKWidget::LoadStart () [protected]
References file_selector, LoadCancel(), and LoadOK().
Referenced by InitForm().
void VW::SequencerMovieChannelGTKWidget::SetLED (bool valid)
References led_green_xpm, led_red_xpm, and status_led.
void VW::SequencerMovieChannelGTKWidget::SetMovieName (const std::string s)
References file_name.
Member Data Documentation
SequencerMovieGTK* VW::SequencerMovieChannelGTKWidget::_main_form [protected]
Referenced by InitForm(), LoadCancel(), and LoadOK().
Gtk::Button* VW::SequencerMovieChannelGTKWidget::browse_button [protected]
Referenced by InitForm().
Gtk::Entry* VW::SequencerMovieChannelGTKWidget::file_name [protected]
Referenced by GetMovieName(), InitForm(), LoadCancel(), LoadOK(), and SetMovieName().
Gtk::FileSelection* VW::SequencerMovieChannelGTKWidget::file_selector [protected]
Referenced by LoadCancel(), LoadOK(), and LoadStart().
Gtk::Pixmap* VW::SequencerMovieChannelGTKWidget::status_led [protected]
Referenced by InitForm(), and SetLED().
The documentation for this class was generated from the following files:
sequencermoviegtk.h
sequencermoviegtk.cpp