VW: VW::ImageDiff Class Reference
VW::ImageDiff Class Reference
[ImageProcessing]
Calculate the difference between two images.
#include <imagediff.h>
Public Member Functions
ImageDiff ()
template<class ImType >
ImageDiff (const ImType &im1, const ImType &im2, ImType &diff, bool absolute=true)
template<class ImType >
void ComputeAbsolute (const ImType &im1, const ImType &im2, ImType &diff)
Compute the absolute difference abs(im1 - im2) (ie.
template<class ImType >
void ComputeSigned (const ImType &im1, const ImType &im2, ImType &diff)
Compute the signed image difference (im1 - im2) (order does matter, and bad things will happen if your images are an unsigned type).
operator bool () const
Detailed Description
Calculate the difference between two images.
Author:
ID Reid
Date:
02/08/2002 A simple class to comute either the absolute or signed difference between two images.
Constructor & Destructor Documentation
VW::ImageDiff::ImageDiff () [inline]
template<class ImType > VW::ImageDiff::ImageDiff (const ImType & im1, const ImType & im2, ImType & diff, bool absolute = true) [inline]
References ComputeAbsolute(), and ComputeSigned().
Member Function Documentation
template<class ImType > void ImageDiff::ComputeAbsolute (const ImType & im1, const ImType & im2, ImType & diff) [inline]
Compute the absolute difference abs(im1 - im2) (ie.
order doesn't matter).
References std::abs(), and c.
Referenced by ImageDiff().
template<class ImType > void ImageDiff::ComputeSigned (const ImType & im1, const ImType & im2, ImType & diff) [inline]
Compute the signed image difference (im1 - im2) (order does matter, and bad things will happen if your images are an unsigned type).
References c.
Referenced by ImageDiff().
VW::ImageDiff::operator bool () const [inline]
The documentation for this class was generated from the following files:
imagediff.h
imagediff.cpp