VW: VW::Moments Class Reference
VW::Moments Class Reference
Compute moments of a binary or monochrome image.
#include <moments.h>
Public Member Functions
template<class ImType >
Moments (const ImageMono< ImType > &im)
template<class ImType >
Moments (const ImageMono< ImType > &im, const ImageMono< float > &weight)
template<class ImType >
Moments (const ImageMono< ImType > &im, const ROI roi)
template<class ImType >
Moments (const ImageMono< ImType > &im, const ROI roi, const ImageMono< float > &weight)
template<class ImType >
void Compute (const ImageMono< ImType > &im, const ROI roi)
template<class ImType >
void Compute (const ImageMono< ImType > &im, const ROI roi, const ImageMono< float > &weights)
VW::Point2D GetCentreOfMass (void)
double GetOrientation ()
double GetCentreOfMassX ()
double GetCentreOfMassY ()
double GetMass ()
Protected Attributes
double sum
double sumx
double sumy
double sumxx
double sumxy
double sumyy
double a
double b
double c
double theta
Detailed Description
Compute moments of a binary or monochrome image.
Compute moments of a monochrome or binary image.
Author:
ID Reid
Date:
18/12/04 Determine the 0th, 1st and 2nd moments of a binary or monochrome image and provide various access methods to compute orientation, etc.
Constructor & Destructor Documentation
template<class ImType > VW::Moments::Moments (const ImageMono< ImType > & im) [inline]
References Compute(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), and VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth().
template<class ImType > VW::Moments::Moments (const ImageMono< ImType > & im, const ImageMono< float > & weight) [inline]
References Compute(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), and VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth().
template<class ImType > VW::Moments::Moments (const ImageMono< ImType > & im, const ROI roi) [inline]
References Compute().
template<class ImType > VW::Moments::Moments (const ImageMono< ImType > & im, const ROI roi, const ImageMono< float > & weight) [inline]
References Compute().
Member Function Documentation
template<class ImType > void VW::Moments::Compute (const ImageMono< ImType > & im, const ROI roi, const ImageMono< float > & weights) [inline]
References a, b, VW::ROI::Bottom(), c, VW::ROI::Left(), VW::ROI::Right(), sum, sumx, sumxx, sumxy, sumy, sumyy, theta, and VW::ROI::Top().
template<class ImType > void VW::Moments::Compute (const ImageMono< ImType > & im, const ROI roi) [inline]
References a, b, VW::ROI::Bottom(), c, VW::ROI::Left(), VW::ROI::Right(), sum, sumx, sumxx, sumxy, sumy, sumyy, theta, and VW::ROI::Top().
Referenced by Moments().
VW::Point2D VW::Moments::GetCentreOfMass (void) [inline]
References sum, sumx, and sumy.
double VW::Moments::GetCentreOfMassX () [inline]
References sum, and sumx.
double VW::Moments::GetCentreOfMassY () [inline]
References sum, and sumx.
double VW::Moments::GetMass () [inline]
References sum.
double VW::Moments::GetOrientation () [inline]
References theta.
Member Data Documentation
double VW::Moments::a [protected]
Referenced by Compute().
double VW::Moments::b [protected]
Referenced by Compute().
double VW::Moments::c [protected]
Referenced by Compute().
double VW::Moments::sum [protected]
Referenced by Compute(), GetCentreOfMass(), GetCentreOfMassX(), GetCentreOfMassY(), and GetMass().
double VW::Moments::sumx [protected]
Referenced by Compute(), GetCentreOfMass(), GetCentreOfMassX(), and GetCentreOfMassY().
double VW::Moments::sumxx [protected]
Referenced by Compute().
double VW::Moments::sumxy [protected]
Referenced by Compute().
double VW::Moments::sumy [protected]
Referenced by Compute(), and GetCentreOfMass().
double VW::Moments::sumyy [protected]
Referenced by Compute().
double VW::Moments::theta [protected]
Referenced by Compute(), and GetOrientation().
The documentation for this class was generated from the following files:
moments.h
moments.cpp