VW: CompareX Class Reference
CompareX Class Reference
Public Member Functions
int operator() (const VW::CornerFeature &c1, const VW::CornerFeature &c2) const
int operator() (const VW::PlesseyCorner &c1, const VW::PlesseyCorner &c2) const
int operator() (const VW::PlesseyCornerYUV &c1, const VW::PlesseyCornerYUV &c2) const
Member Function Documentation
int CompareX::operator() (const VW::PlesseyCornerYUV & c1, const VW::PlesseyCornerYUV & c2) const [inline]
References VW::Point2D::GetX().
int CompareX::operator() (const VW::PlesseyCorner & c1, const VW::PlesseyCorner & c2) const [inline]
References VW::Point2D::GetX().
int CompareX::operator() (const VW::CornerFeature & c1, const VW::CornerFeature & c2) const [inline]
References VW::Point2D::GetX().
The documentation for this class was generated from the following files:
cornerfeature.cpp
plesseycorner.cpp
plesseycorneryuv.cpp