VW: VW::FMatrixAffineComputePreemptive Class Reference
VW::FMatrixAffineComputePreemptive Class Reference
#include <fmaffinecomputepreemptive.h>
Public Member Functions
FMatrixAffineComputePreemptive (double image_noise, double search_area, unsigned int max_num_hypotheses)
bool Compute (VW::FMatrixAffine &F, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, std::vector< double > &posteriors)
Compute with random sampling.
bool Compute (VW::FMatrixAffine &F, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const std::vector< double > &priors, std::vector< double > &posteriors)
Compute with guided sampling according to "priors".
void SetImageNoise (double image_noise)
Set the expected image noise standard deviation (in pixels).
void SetSearchArea (double search_area)
Set the are searched for each feature.
void SetNumHypotheses (unsigned int num)
Set the number of hypotheses.
void SetMaxTime (double millisecs)
Set the maximum time in millisecs.
Constructor & Destructor Documentation
VW::FMatrixAffineComputePreemptive::FMatrixAffineComputePreemptive (double image_noise, double search_area, unsigned int max_num_hypotheses) [inline]
Member Function Documentation
bool VW::FMatrixAffineComputePreemptive::Compute (VW::FMatrixAffine & F, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const std::vector< double > & priors, std::vector< double > & posteriors)
Compute with guided sampling according to "priors".
References VW::AccumulateWeights(), VW::PDF::Gaussian1D::ApproxDensityForError2(), VW::FMatrixAffineComputeLinear::Compute(), VW::FMatrixAffineComputeLinear::ComputeWeighted(), VW::CreateRandomisedList(), VW::FAffHyp::F, VW::Timer::GetAsMilliseconds(), VW::Line2D::GetDistance2(), VW::Normalisation::GetScale(), VW::Normalisation::Normalise(), VW::Timer::Start(), VW::FMatrixAffine::Transfer(), VW::EssentialMatrixCompute::Unnormalise(), and VW::WeightedSample().
bool VW::FMatrixAffineComputePreemptive::Compute (VW::FMatrixAffine & F, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, std::vector< double > & posteriors)
Compute with random sampling.
References VW::PDF::Gaussian1D::ApproxDensityForError2(), VW::FMatrixAffineComputeLinear::Compute(), VW::FMatrixAffineComputeLinear::ComputeWeighted(), VW::CreateRandomisedList(), VW::FAffHyp::F, VW::Timer::GetAsMilliseconds(), VW::Line2D::GetDistance2(), VW::Normalisation::GetScale(), VW::Normalisation::Normalise(), VW::RandomSample(), VW::Timer::Start(), VW::FMatrixAffine::Transfer(), and VW::EssentialMatrixCompute::Unnormalise().
void VW::FMatrixAffineComputePreemptive::SetImageNoise (double image_noise) [inline]
Set the expected image noise standard deviation (in pixels).
This is used to determine the Gaussian model for the inlier process.
void VW::FMatrixAffineComputePreemptive::SetMaxTime (double millisecs) [inline]
Set the maximum time in millisecs.
If not set, not time limit is imposed.
void VW::FMatrixAffineComputePreemptive::SetNumHypotheses (unsigned int num) [inline]
Set the number of hypotheses.
void VW::FMatrixAffineComputePreemptive::SetSearchArea (double search_area) [inline]
Set the are searched for each feature.
This determines the uniform distribution used to model the outlier process.
The documentation for this class was generated from the following files:
fmaffinecomputepreemptive.h
fmaffinecomputepreemptive.cpp