VW: VW::SequencerFirewireWx Class Reference
VW::SequencerFirewireWx Class Reference
[Sequencers]
A Wx-based interface to the firewire sequencer.
#include <sequencerfirewirewx.h>
Public Member Functions
SequencerFirewireWx (wxWindow *parent, int wx_id)
~SequencerFirewireWx ()
virtual bool Init ()
Initialise the grabber.
void AddNewCamera (std::vector< VW::FirewireCamera * > &c_list, unsigned int which_element)
virtual void Continuous ()
Start continuous capture from the sequence.
virtual void Stop ()
Stop continuous capture from the sequence.
virtual void Next ()
Capture the next single frame.
void CreateForm (wxWindow *parent)
void UpdateForm ()
void UpdateFromForm ()
int GetNumberOfCameras (void) const
The total number of cameras attached to the Firewire BUS.
virtual VW::FirewireCamera * GetCamera (unsigned int which_camera)
Returns a pointer to one camera.
void * GetBuffer (unsigned int which_channel=0)
Get a pointer to the raw buffer.
template<class ImType >
void CopyImage (ImType &image, unsigned int which_channel=0)
Recover the image for one camera.
Initialisation functions
virtual void SetDelay (int d)
Set the delay between frames (only usually used for non-hardware sequencers).
Information functions
bool GetContinuous () const
Is the sequencer running in continuous mode?
int GetDelay () const
What is the delay between frames.
unsigned int GetNumberOfChannels () const
Most sequencers are able to present mutliple images per frame.
unsigned int GetCurrentFrameNumber () const
Return the current frame number.
Public Attributes
VWEvents::Event1< void, int > NewFrameEvent
The "new frame has arrived" event.
Protected Member Functions
virtual void _FrameArrived ()
we have been signalled that a frame has arrived and we are now "inside" the signalling object, so invoke the appropriate callback
void OnStopClicked (wxCommandEvent &event)
void OnNextClicked (wxCommandEvent &event)
void OnContinuousClicked (wxCommandEvent &event)
DECLARE_EVENT_TABLE ()
DECLARE_CLASS (SequencerFirewireWx)
virtual bool _Step ()
void SetDefaultCameraSettings (void)
void ProbeForCameras ()
bool StartDMA ()
Setup the DMA transfer in each camera.
bool StopDMA ()
Stop the cameras running - ie.
bool StartISO ()
Start isochronous image transfer.
bool StopISO ()
Stop isochronous image transfer.
void _WaitForThread ()
Wait for the thread to exit.
void * Main (void *)
void _CheckInitialised ()
Protected Attributes
int _wx_id
wxButton * _cont_button
wxButton * _next_button
wxButton * _stop_button
bool cameras_running
bool dma_running
int frame_num
unsigned int x_subsamp
unsigned int y_subsamp
pthread_mutex_t buffer_access_lock
int delay
unsigned int frame_number
bool cont
bool thread_running
bool _initialised
ThreadType parent
unsigned int number_of_channels
Mutex access_lock
bool user_finished
Static Protected Attributes
static raw1394handle_t raw_device_handle
static std::vector
< VW::FirewireCamera * > camera_list
static dc1394_cameracapture * camera_capture_stuff
Detailed Description
A Wx-based interface to the firewire sequencer.
Author:
BJ Tordoff and AJ Davison
Date:
26/06/2004 This sequencer is a version of SequencerFirewire which also provides a WxWidgets interface. The sequencer functionality is identical to the parent class, but with added functions to control the interface. As it is just a Wx widget it can be embedded in any WxWidgets form in the usual manner.
Constructor & Destructor Documentation
VW::SequencerFirewireWx::SequencerFirewireWx (wxWindow * parent, int wx_id)
References CreateForm().
VW::SequencerFirewireWx::~SequencerFirewireWx ()
References Stop(), VW::SequencerFirewire::StopDMA(), and VW::SequencerFirewire::StopISO().
Member Function Documentation
void VW::SequencerBase::_CheckInitialised () [protected, inherited]
References VW::SequencerBase::_initialised.
Referenced by VW::SequencerBase::Continuous(), VW::SequencerBase::Next(), and VW::SequencerBase::Stop().
void VW::SequencerFirewireWx::_FrameArrived () [protected, virtual]
we have been signalled that a frame has arrived and we are now "inside" the signalling object, so invoke the appropriate callback
Reimplemented from VW::SequencerBase.
References _wx_id, VW::SequencerBase::NewFrameEvent, and VW::SequencerBase::user_finished.
bool SequencerFirewire::_Step () [protected, virtual, inherited]
Implements VW::SequencerBase.
References VW::SequencerFirewire::buffer_access_lock, VW::SequencerFirewire::camera_capture_stuff, VW::SequencerFirewire::cameras_running, VW::SequencerBase::cont, VW::SequencerFirewire::frame_num, VW::SequencerBase::number_of_channels, VW::SequencerFirewire::StartISO(), VW::SequencerFirewire::StopISO(), VW::SequencerBase::thread_running, and VERBOSE.
void SequencerBase::_WaitForThread () [inline, protected, inherited]
Wait for the thread to exit.
References VW::SequencerBase::access_lock, VW::Mutex::Lock(), msleep(), VW::SequencerBase::thread_running, VW::Mutex::Unlock(), and VERBOSE.
Referenced by VW::SequencerBase::Stop().
void VW::SequencerFirewireWx::AddNewCamera (std::vector< VW::FirewireCamera * > & c_list, unsigned int which_element) [virtual]
Reimplemented from VW::SequencerFirewire.
void VW::SequencerFirewireWx::Continuous () [virtual]
Start continuous capture from the sequence.
Reimplemented from VW::SequencerBase.
References UpdateForm(), and VERBOSE.
Referenced by OnContinuousClicked().
template<class ImType > void VW::SequencerFirewire::CopyImage (ImType & image, unsigned int which_channel = 0) [inline, inherited]
Recover the image for one camera.
The image is copied from the raw image buffer into the VW image, employing some conversion on the way. This is not a fast thing to do. For absolute speed use the raw buffer.
References VW::SequencerFirewire::buffer_access_lock, VW::SequencerFirewire::camera_capture_stuff, VW::SequencerFirewire::camera_list, VW::FirewireParams::M_1024x768_MONO, VW::FirewireParams::M_1024x768_RGB, VW::FirewireParams::M_1024x768_YUV422, VW::FirewireParams::M_1280x960_MONO, VW::FirewireParams::M_1280x960_RGB, VW::FirewireParams::M_1280x960_YUV422, VW::FirewireParams::M_1600x1200_MONO, VW::FirewireParams::M_1600x1200_RGB, VW::FirewireParams::M_1600x1200_YUV422, VW::FirewireParams::M_160x120_YUV444, VW::FirewireParams::M_320x240_YUV422, VW::FirewireParams::M_640x480_MONO, VW::FirewireParams::M_640x480_RGB, VW::FirewireParams::M_640x480_YUV411, VW::FirewireParams::M_640x480_YUV422, VW::FirewireParams::M_800x600_MONO, VW::FirewireParams::M_800x600_RGB, VW::FirewireParams::M_800x600_YUV422, VW::ImageConversions::MonoBuffer_to_VWImage(), VW::ImageConversions::RGBBuffer_to_VWImage(), VERBOSE, VW::SequencerFirewire::x_subsamp, VW::SequencerFirewire::y_subsamp, VW::ImageConversions::YUV411Buffer_to_VWImage(), VW::ImageConversions::YUV422Buffer_to_VWImage(), and VW::ImageConversions::YUV444Buffer_to_VWImage().
void VW::SequencerFirewireWx::CreateForm (wxWindow * parent)
References _cont_button, _next_button, _stop_button, SEQUENCERFIREWIRE_CONTBUTTON, SEQUENCERFIREWIRE_NEXTBUTTON, and SEQUENCERFIREWIRE_STOPBUTTON.
Referenced by SequencerFirewireWx().
VW::SequencerFirewireWx::DECLARE_CLASS (SequencerFirewireWx) [protected]
VW::SequencerFirewireWx::DECLARE_EVENT_TABLE () [protected]
void * VW::SequencerFirewire::GetBuffer (unsigned int which_channel = 0) [inline, virtual, inherited]
Get a pointer to the raw buffer.
A raw pointer is returned, so it is up to the user to deal with it before the firewire DMA chooses to overwrite it. Wrapping an image around the bizarre format YUV images that the firewire cameras use will almost certainly be tricky. Note that the data is usually unsigned char
Implements VW::SequencerBase.
References VW::SequencerFirewire::camera_capture_stuff.
VW::FirewireCamera * VW::SequencerFirewire::GetCamera (unsigned int which_camera) [inline, virtual, inherited]
Returns a pointer to one camera.
References VW::SequencerFirewire::camera_list, and VW::SequencerBase::number_of_channels.
bool VW::SequencerBase::GetContinuous () const [inline, inherited]
Is the sequencer running in continuous mode?
References VW::SequencerBase::cont.
unsigned int VW::SequencerBase::GetCurrentFrameNumber () const [inline, inherited]
Return the current frame number.
In the case of movies or files this is the frame number with respect to the start frame (ie, 1=start frame) and won't correspond to the sequence frame numbers if started part way through a sequence.
References VW::SequencerBase::frame_number.
int VW::SequencerBase::GetDelay () const [inline, inherited]
What is the delay between frames.
References VW::SequencerBase::delay.
int VW::SequencerFirewire::GetNumberOfCameras (void) const [inline, inherited]
The total number of cameras attached to the Firewire BUS.
References VW::SequencerBase::number_of_channels.
unsigned int VW::SequencerBase::GetNumberOfChannels () const [inline, inherited]
Most sequencers are able to present mutliple images per frame.
References VW::SequencerBase::number_of_channels.
Referenced by VW::SequencerMovieGTKWidget::InitForm(), and VW::SequencerFileGTKWidget::InitForm().
bool VW::SequencerFirewireWx::Init () [virtual]
Initialise the grabber.
This tells the grabber to scan for cameras and initialise them. It must be called before trying to use the sequencer.
Reimplemented from VW::SequencerFirewire.
References UpdateForm(), and VERBOSE.
void * SequencerBase::Main (void *) [protected, virtual, inherited]
Implements VW::Thread.
References VW::SequencerBase::_FrameArrived(), VW::SequencerBase::_Step(), VW::SequencerBase::access_lock, VW::SequencerBase::cont, VW::SequencerBase::delay, VW::SequencerBase::frame_number, VW::Mutex::Lock(), msleep(), VW::SequencerBase::thread_running, VW::Mutex::Unlock(), and VERBOSE.
void VW::SequencerFirewireWx::Next () [virtual]
Capture the next single frame.
Reimplemented from VW::SequencerBase.
References UpdateForm(), and VERBOSE.
Referenced by OnNextClicked().
void VW::SequencerFirewireWx::OnContinuousClicked (wxCommandEvent & event) [protected]
References Continuous().
void VW::SequencerFirewireWx::OnNextClicked (wxCommandEvent & event) [protected]
References Next().
void VW::SequencerFirewireWx::OnStopClicked (wxCommandEvent & event) [protected]
References Stop().
void VW::SequencerFirewire::ProbeForCameras () [protected, inherited]
References VW::SequencerFirewire::AddNewCamera(), VW::SequencerFirewire::camera_capture_stuff, VW::SequencerFirewire::camera_list, VW::SequencerBase::number_of_channels, VW::SequencerFirewire::raw_device_handle, and VERBOSE.
Referenced by VW::SequencerFirewireGTK::Init(), and VW::SequencerFirewire::Init().
void VW::SequencerFirewire::SetDefaultCameraSettings (void) [protected, inherited]
References VW::SequencerFirewire::camera_list, VW::FirewireParams::FPS_15, VW::FirewireParams::M_320x240_YUV422, and VW::SequencerBase::number_of_channels.
Referenced by VW::SequencerFirewireGTK::Init(), and VW::SequencerFirewire::Init().
void VW::SequencerBase::SetDelay (int d) [inline, virtual, inherited]
Set the delay between frames (only usually used for non-hardware sequencers).
This is the time (in milliseconds) for which the sequencer sleeps between frames: the total frame period will be this plus the time taken to acquire the new frame. By default the delay is set to 1ms (zero or less is not a valid setting).
References VW::SequencerBase::delay.
bool VW::SequencerFirewire::StartDMA (void) [protected, inherited]
Setup the DMA transfer in each camera.
Note that this doesn't start transferring images, just creates the channel.
References VW::SequencerFirewire::buffer_access_lock, VW::SequencerFirewire::camera_capture_stuff, VW::SequencerFirewire::camera_list, VW::SequencerFirewire::dma_running, VW::SequencerBase::number_of_channels, and VERBOSE.
Referenced by VW::SequencerFirewire::StartISO().
bool VW::SequencerFirewire::StartISO (void) [protected, inherited]
Start isochronous image transfer.
This begins the actual transfer of images from camera to memory.
References VW::SequencerFirewire::camera_list, VW::SequencerFirewire::cameras_running, VW::SequencerFirewire::dma_running, VW::SequencerBase::number_of_channels, and VW::SequencerFirewire::StartDMA().
Referenced by VW::SequencerFirewire::_Step().
void VW::SequencerFirewireWx::Stop () [virtual]
Stop continuous capture from the sequence.
Reimplemented from VW::SequencerFirewire.
References UpdateForm(), and VERBOSE.
Referenced by OnStopClicked(), and ~SequencerFirewireWx().
bool VW::SequencerFirewire::StopDMA (void) [protected, inherited]
Stop the cameras running - ie.
stop DMA. At the moment this seems to be a fatal thing to do (ie. don't expect to be able to restart tham having called this function). However, to stop the cameras carrying on after your program has finished, call it.
References VW::SequencerFirewire::camera_capture_stuff, VW::SequencerFirewire::camera_list, VW::SequencerFirewire::dma_running, VW::SequencerBase::number_of_channels, and VERBOSE.
Referenced by VW::SequencerFirewire::StopISO(), VW::SequencerFirewire::~SequencerFirewire(), VW::SequencerFirewireGTK::~SequencerFirewireGTK(), and ~SequencerFirewireWx().
bool VW::SequencerFirewire::StopISO (void) [protected, inherited]
Stop isochronous image transfer.
This halts image transfer, and appears a safe thing to do.
References VW::SequencerFirewire::camera_list, VW::SequencerFirewire::cameras_running, VW::SequencerBase::number_of_channels, VW::SequencerFirewire::StopDMA(), and VERBOSE.
Referenced by VW::SequencerFirewire::_Step(), VW::SequencerFirewire::Stop(), VW::SequencerFirewire::~SequencerFirewire(), VW::SequencerFirewireGTK::~SequencerFirewireGTK(), and ~SequencerFirewireWx().
void VW::SequencerFirewireWx::UpdateForm (void)
References _cont_button, _next_button, _stop_button, VW::SequencerBase::cont, and VERBOSE.
Referenced by Continuous(), Init(), Next(), and Stop().
void VW::SequencerFirewireWx::UpdateFromForm ()
Member Data Documentation
wxButton* VW::SequencerFirewireWx::_cont_button [protected]
Referenced by CreateForm(), and UpdateForm().
bool VW::SequencerBase::_initialised [protected, inherited]
Referenced by VW::SequencerBase::_CheckInitialised(), and VW::SequencerBase::Init().
wxButton * VW::SequencerFirewireWx::_next_button [protected]
Referenced by CreateForm(), and UpdateForm().
wxButton * VW::SequencerFirewireWx::_stop_button [protected]
Referenced by CreateForm(), and UpdateForm().
int VW::SequencerFirewireWx::_wx_id [protected]
Referenced by _FrameArrived().
Mutex VW::SequencerBase::access_lock [protected, inherited]
Referenced by VW::SequencerFile::_Step(), VW::SequencerBase::_WaitForThread(), VW::SequencerBase::Continuous(), VW::SequencerBase::Main(), VW::SequencerBase::Next(), VW::SequencerFile::Rewind(), VW::SequencerFile::Skip(), and VW::SequencerBase::Stop().
pthread_mutex_t VW::SequencerFirewire::buffer_access_lock [protected, inherited]
Referenced by VW::SequencerFirewire::_Step(), VW::SequencerFirewire::CopyImage(), and VW::SequencerFirewire::StartDMA().
dc1394_cameracapture * VW::SequencerFirewire::camera_capture_stuff [static, protected, inherited]
Referenced by VW::SequencerFirewire::_Step(), VW::SequencerFirewire::CopyImage(), VW::SequencerFirewire::GetBuffer(), VW::SequencerFirewire::ProbeForCameras(), VW::SequencerFirewire::StartDMA(), and VW::SequencerFirewire::StopDMA().
vector< VW::FirewireCamera * > VW::SequencerFirewire::camera_list [static, protected, inherited]
Referenced by VW::SequencerFirewire::CopyImage(), VW::SequencerFirewire::GetCamera(), VW::SequencerFirewireGTK::Init(), VW::SequencerFirewire::ProbeForCameras(), VW::SequencerFirewire::SetDefaultCameraSettings(), VW::SequencerFirewire::StartDMA(), VW::SequencerFirewire::StartISO(), VW::SequencerFirewire::StopDMA(), and VW::SequencerFirewire::StopISO().
bool VW::SequencerFirewire::cameras_running [protected, inherited]
Referenced by VW::SequencerFirewire::_Step(), VW::SequencerFirewire::StartISO(), and VW::SequencerFirewire::StopISO().
bool VW::SequencerBase::cont [protected, inherited]
Referenced by VW::SequencerMovie::_Step(), VW::SequencerFirewire::_Step(), VW::SequencerFile::_Step(), VW::SequencerBase::Continuous(), VW::SequencerBase::GetContinuous(), VW::SequencerBase::Main(), VW::SequencerBase::Next(), VW::SequencerBase::Stop(), VW::SequencerMovieGTK::UpdateForm(), UpdateForm(), VW::SequencerFileWx::UpdateForm(), and VW::SequencerFileGTK::UpdateForm().
int VW::SequencerBase::delay [protected, inherited]
Referenced by VW::SequencerBase::GetDelay(), VW::SequencerBase::Main(), and VW::SequencerBase::SetDelay().
bool VW::SequencerFirewire::dma_running [protected, inherited]
Referenced by VW::SequencerFirewire::StartDMA(), VW::SequencerFirewire::StartISO(), and VW::SequencerFirewire::StopDMA().
int VW::SequencerFirewire::frame_num [protected, inherited]
Referenced by VW::SequencerFirewire::_Step().
unsigned int VW::SequencerBase::frame_number [protected, inherited]
Referenced by VW::SequencerFile::_InitialiseFiles(), VW::SequencerMovie::_Step(), VW::SequencerFile::_Step(), VW::SequencerBase::GetCurrentFrameNumber(), VW::SequencerBase::Main(), VW::SequencerMovie::Rewind(), VW::SequencerFile::Rewind(), VW::SequencerFile::SequencerFile(), VW::SequencerFile::Skip(), VW::SequencerFileWx::UpdateForm(), and VW::SequencerFileGTK::UpdateForm().
VWEvents::Event1<void,int> VW::SequencerBase::NewFrameEvent [inherited]
The "new frame has arrived" event.
Attach a function to this callback signal if you want to perform an operation each time a new image arrives. This is typically done using my_sequencer.NewFrameEvent.connect(&MyFunction); where 'MyFunction' must take an integer argument and return void.
Referenced by VW::SequencerMeteor::_FrameArrived(), _FrameArrived(), VW::SequencerFirewireGTK::_FrameArrived(), VW::SequencerFileWx::_FrameArrived(), VW::SequencerFileGTK::_FrameArrived(), and VW::SequencerBase::_FrameArrived().
unsigned int VW::SequencerBase::number_of_channels [protected, inherited]
Referenced by VW::SequencerFile::_InitialiseFiles(), VW::SequencerMovie::_Step(), VW::SequencerFirewire::_Step(), VW::SequencerFile::_Step(), VW::SequencerFile::CopyImage(), VW::SequencerFirewire::GetCamera(), VW::SequencerFirewire::GetNumberOfCameras(), VW::SequencerBase::GetNumberOfChannels(), VW::SequencerMeteor::Init(), VW::SequencerFirewire::ProbeForCameras(), VW::SequencerMovie::Rewind(), VW::SequencerFile::Rewind(), VW::SequencerFile::SequencerFile(), VW::SequencerFirewire::SequencerFirewire(), VW::SequencerMovie::SequencerMovie(), VW::SequencerFirewire::SetDefaultCameraSettings(), VW::SequencerFile::Skip(), VW::SequencerFirewire::StartDMA(), VW::SequencerFirewire::StartISO(), VW::SequencerFirewire::StopDMA(), VW::SequencerFirewire::StopISO(), VW::SequencerMovieGTK::UpdateForm(), VW::SequencerFileWx::UpdateForm(), VW::SequencerFileGTK::UpdateForm(), VW::SequencerMovieGTK::UpdateFromForm(), and VW::SequencerFileGTK::UpdateFromForm().
ThreadType VW::SequencerBase::parent [protected, inherited]
raw1394handle_t VW::SequencerFirewire::raw_device_handle [static, protected, inherited]
Referenced by VW::SequencerFirewire::ProbeForCameras().
bool VW::SequencerBase::thread_running [protected, inherited]
Referenced by VW::SequencerFirewire::_Step(), VW::SequencerBase::_WaitForThread(), and VW::SequencerBase::Main().
bool VW::SequencerBase::user_finished [protected, inherited]
Referenced by _FrameArrived(), VW::SequencerFirewireGTK::_FrameArrived(), VW::SequencerFileWx::_FrameArrived(), VW::SequencerFileGTK::_FrameArrived(), and VW::SequencerBase::_FrameArrived().
unsigned int VW::SequencerFirewire::x_subsamp [protected, inherited]
Referenced by VW::SequencerFirewire::CopyImage().
unsigned int VW::SequencerFirewire::y_subsamp [protected, inherited]
Referenced by VW::SequencerFirewire::CopyImage().
The documentation for this class was generated from the following files:
sequencerfirewirewx.h
sequencerfirewirewx.cpp