VW: VW::ChamferDistance Class Reference
VW::ChamferDistance Class Reference
[ImageProcessing]
Class for computing a linear distance transfor (aka chamfer distance) image.
#include <chamferdistance.h>
Public Member Functions
ChamferDistance ()
ChamferDistance (const VW::EdgeData &edges, VW::ImageMono< unsigned int > &result)
ChamferDistance (const VW::ImageMono< unsigned char > &inputimage, VW::ImageMono< unsigned int > &result, unsigned char threshold=127)
ChamferDistance (const VW::ImageMono< bool > &inputimage, VW::ImageMono< unsigned int > &result)
void Compute (const VW::EdgeData &edges, VW::ImageMono< unsigned int > &result)
Compute the linear distance transform from the edges specified in "edges".
void Compute (const VW::ImageMono< unsigned char > &inputimage, VW::ImageMono< unsigned int > &result, unsigned char threshold=127)
Compute the linear distance transform from a mono image where any pixel with a value above the threshold is treated as a "feature".
void Compute (const VW::ImageMono< bool > &inputimage, VW::ImageMono< unsigned int > &result)
Compute the linear distance transform from pixels of value 255.
Detailed Description
Class for computing a linear distance transfor (aka chamfer distance) image.
Author:
BJ Tordoff
Date:
26/06/2003 The distance transform uses a binary image of "features" from which the distance is measured. There are several ways in which it can be used, the easiest of which is to provide a binary image with features having a "true" value and everything else "false". Typically it is used on a thresholded silhouette or on the output of the Canny edge detector (see VW::Canny), and compute functions for these types of data are also provided.
Constructor & Destructor Documentation
VW::ChamferDistance::ChamferDistance ()
VW::ChamferDistance::ChamferDistance (const VW::EdgeData & edges, VW::ImageMono< unsigned int > & result) [inline]
References Compute().
VW::ChamferDistance::ChamferDistance (const VW::ImageMono< unsigned char > & inputimage, VW::ImageMono< unsigned int > & result, unsigned char threshold = 127) [inline]
References Compute().
VW::ChamferDistance::ChamferDistance (const VW::ImageMono< bool > & inputimage, VW::ImageMono< unsigned int > & result) [inline]
References Compute().
Member Function Documentation
void VW::ChamferDistance::Compute (const VW::ImageMono< bool > & inputimage, VW::ImageMono< unsigned int > & result)
Compute the linear distance transform from pixels of value 255.
References VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::AllocImageData(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetRowStart(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::IsAlloced(), min4(), std::sqrt(), and VW::PixelMono< Type >::y.
void VW::ChamferDistance::Compute (const VW::ImageMono< unsigned char > & inputimage, VW::ImageMono< unsigned int > & result, unsigned char threshold = 127)
Compute the linear distance transform from a mono image where any pixel with a value above the threshold is treated as a "feature".
Compute the linear distance transform (chamfer distance) from a mono image where any pixel with a value above the threshold is treated as a "feature".
References VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::AllocImageData(), Compute(), VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetRowStart(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::IsAlloced(), and VW::PixelMono< Type >::y.
void VW::ChamferDistance::Compute (const VW::EdgeData & edges, VW::ImageMono< unsigned int > & result)
Compute the linear distance transform from the edges specified in "edges".
Compute the linear distance transform (chamfer distance) from the edges specified in edgedata.
Note that as edges don't specify an image size, the result image should be resized to the desired size before use.
References VW::EdgeData::edgels, VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), and VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::IsAlloced().
Referenced by ChamferDistance(), and Compute().
The documentation for this class was generated from the following files:
chamferdistance.h
chamferdistance.cpp