VW: vnl_gaussian_kernel_1d Class Reference
vnl_gaussian_kernel_1d Class Reference
Holds one half of a discretely sampled 1D gaussian distribution.
#include <gaussiankernel1d.h>
Public Member Functions
vnl_gaussian_kernel_1d (double sigma, double cutoff=0.5/256.0)
Construct a sampled 1D gaussian of standard deviation sigma.
double G (double x) const
int width () const
double operator[] (int i) const
Protected Attributes
VNL::Vector< double > vec_
double inscale_
Detailed Description
Holds one half of a discretely sampled 1D gaussian distribution.
vnl_gaussian_kernel_1d is a class that holds one half of a discretely sampled 1D gaussian distribution.
Constructor & Destructor Documentation
vnl_gaussian_kernel_1d::vnl_gaussian_kernel_1d (double sigma, double cutoff = 0.5/256.0)
Construct a sampled 1D gaussian of standard deviation sigma.
The vector is normalized so that its sum is 0.5.
References G(), inscale_, VNL::Vector< T >::size(), v, vec_, and width().
Member Function Documentation
double vnl_gaussian_kernel_1d::G (double x) const
References inscale_.
Referenced by vnl_gaussian_kernel_1d().
double vnl_gaussian_kernel_1d::operator[] (int i) const [inline]
References vec_.
int vnl_gaussian_kernel_1d::width () const [inline]
References VNL::Vector< T >::size(), and vec_.
Referenced by vnl_gaussian_kernel_1d().
Member Data Documentation
double vnl_gaussian_kernel_1d::inscale_ [protected]
Referenced by G(), and vnl_gaussian_kernel_1d().
VNL::Vector<double> vnl_gaussian_kernel_1d::vec_ [protected]
Referenced by operator[](), vnl_gaussian_kernel_1d(), and width().
The documentation for this class was generated from the following files:
gaussiankernel1d.h
gaussiankernel1d.cpp