VW: VNL::SparseSymmetricEigensystem Class Reference
VNL::SparseSymmetricEigensystem Class Reference
Find the eigenvalues of a sparse symmetric matrix.
#include <sparsesymmetriceigensystem.h>
Public Member Functions
SparseSymmetricEigensystem ()
int CalculateNPairs (VNL::SparseMatrix< double > &M, int n, bool smallest=true, int nfigures=10)
Here is where the fortran converted code gets called.
VNL::Vector< double > GetEigenvector (int i) const
Return a calculated eigenvector.
double GetEigenvalue (int i) const
int CalculateProduct (int n, int m, const double *p, double *q)
Callback from solver to calculate the product A p.
int SaveVectors (int n, int m, const double *q, int base)
Callback to store vectors for dnlaso.
int RestoreVectors (int n, int m, double *q, int base)
Callback to restore vectors for dnlaso.
Protected Attributes
int nvalues
VNL::Vector< double > * vectors
double * values
VNL::SparseMatrix< double > * mat
std::vector< double * > temp_store
Detailed Description
Find the eigenvalues of a sparse symmetric matrix.
Solve the eigenproblem , with symmetric and sparse. The block Lanczos algorithm is used to allow the recovery of a number of eigenvale/eigenvector pairs from either end of the spectrum, to a required accuracy.
Uses the dnlaso routine from the LASO package of netlib.
Constructor & Destructor Documentation
VNL::SparseSymmetricEigensystem::SparseSymmetricEigensystem ()
Member Function Documentation
int VNL::SparseSymmetricEigensystem::CalculateNPairs (VNL::SparseMatrix< double > & M, int n, bool smallest = true, int nfigures = 10)
Here is where the fortran converted code gets called.
The sparse matrix M is assumed to be symmetric. The n smallest eigenvalues and their corresponding eigenvectors are calculated if smallest is true (the default). Otherwise the n largest eigenpairs are found. The accuracy of the eigenvalues is to nfigures decimal digits. Returns 0 if successful, non-zero otherwise.
References VNL::SparseMatrix< T >::columns(), dnlaso_(), mat, nvalues, sse_iovect_callback(), sse_op_callback(), temp_store, values, and vectors.
int VNL::SparseSymmetricEigensystem::CalculateProduct (int n, int m, const double * p, double * q)
Callback from solver to calculate the product A p.
References mat, and VNL::SparseMatrix< T >::mult().
Referenced by sse_op_callback().
double VNL::SparseSymmetricEigensystem::GetEigenvalue (int i) const
References nvalues, and values.
VNL::Vector< double > VNL::SparseSymmetricEigensystem::GetEigenvector (int i) const
Return a calculated eigenvector.
References nvalues, and vectors.
int VNL::SparseSymmetricEigensystem::RestoreVectors (int n, int m, double * q, int base)
Callback to restore vectors for dnlaso.
References temp_store.
Referenced by sse_iovect_callback().
int VNL::SparseSymmetricEigensystem::SaveVectors (int n, int m, const double * q, int base)
Callback to store vectors for dnlaso.
References temp_store.
Referenced by sse_iovect_callback().
Member Data Documentation
VNL::SparseMatrix<double>* VNL::SparseSymmetricEigensystem::mat [protected]
Referenced by CalculateNPairs(), and CalculateProduct().
int VNL::SparseSymmetricEigensystem::nvalues [protected]
Referenced by CalculateNPairs(), GetEigenvalue(), and GetEigenvector().
std::vector<double*> VNL::SparseSymmetricEigensystem::temp_store [protected]
Referenced by CalculateNPairs(), RestoreVectors(), and SaveVectors().
double* VNL::SparseSymmetricEigensystem::values [protected]
Referenced by CalculateNPairs(), and GetEigenvalue().
VNL::Vector<double>* VNL::SparseSymmetricEigensystem::vectors [protected]
Referenced by CalculateNPairs(), and GetEigenvector().
The documentation for this class was generated from the following files:
sparsesymmetriceigensystem.h
sparsesymmetriceigensystem.cpp