VW: VW::CornerMatcherBase< Feature > Class Template Reference
VW::CornerMatcherBase< Feature > Class Template Reference
[ImageProcessing]
#include <cornermatcherbase.h>
Public Member Functions
CornerMatcherBase (const MatcherType matcher_type=MatcherParams::DEF_TYPE, const float maximum_range=MatcherParams::DEF_MAX_RANGE, const float score_threshold=MatcherParams::DEF_SCORE_THRESH)
CornerMatcherBase (const std::vector< Feature > &plnew, const std::vector< Feature > &plold, std::vector< MatchData > &matchlist, const MatcherType matcher_type=MatcherParams::DEF_TYPE, const float maximum_range=MatcherParams::DEF_MAX_RANGE, const float score_threshold=MatcherParams::DEF_SCORE_THRESH)
virtual ~CornerMatcherBase ()
operator bool () const
void Compute (const std::vector< Feature > &plnew, const std::vector< Feature > &plold, std::vector< MatchData > &matchlist) const
Compute using two corner lists.
void FormLookupTable (const std::vector< MatchData > &matchlist, std::vector< int > &list1, std::vector< int > &list2) const
void SetMaximumRange (const float new_max_range)
void SetScoreThreshold (const float score_thresh)
Protected Member Functions
virtual float GetMatchScore (const Feature &f1, const Feature &f2) const =0
virtual void MatchScoresToProbs (std::vector< std::vector< MatchData > > &potentialmatches) const =0
void FindPotentialMatches (const std::vector< Feature > &old_pointlist, const std::vector< Feature > &new_pointlist, std::vector< std::vector< MatchData > > &potentialmatches) const
Use GetMatchScore to obtain a set of potential matches for each point.
bool BraindeadMatcher (const std::vector< std::vector< MatchData > > &potentialmatches, const unsigned int number_in_list1, const unsigned int number_in_list2, std::vector< MatchData > &matchlist) const
The actual matchers - 1.
bool RepeatedlyStupidMatcher (const std::vector< std::vector< MatchData > > &potentialmatches, const unsigned int number_in_list1, const unsigned int number_in_list2, std::vector< MatchData > &matchlist) const
The actual matchers - 2.
Detailed Description
template<class Feature>
class VW::CornerMatcherBase< Feature >
Author:
BJ Tordoff
Date:
14/01/2000
Abstract base class for cornermatchers, providing much of the shared functionality.
Constructor & Destructor Documentation
template<class Feature > VW::CornerMatcherBase< Feature >::CornerMatcherBase (const MatcherType matcher_type = MatcherParams::DEF_TYPE, const float maximum_range = MatcherParams::DEF_MAX_RANGE, const float score_threshold = MatcherParams::DEF_SCORE_THRESH) [inline]
template<class Feature> VW::CornerMatcherBase< Feature >::CornerMatcherBase (const std::vector< Feature > & plnew, const std::vector< Feature > & plold, std::vector< MatchData > & matchlist, const MatcherType matcher_type = MatcherParams::DEF_TYPE, const float maximum_range = MatcherParams::DEF_MAX_RANGE, const float score_threshold = MatcherParams::DEF_SCORE_THRESH)
template<class Feature> virtual VW::CornerMatcherBase< Feature >::~CornerMatcherBase () [inline, virtual]
Member Function Documentation
template<class Feature> bool VW::CornerMatcherBase< Feature >::BraindeadMatcher (const std::vector< std::vector< MatchData > > & potentialmatches, const unsigned int number_in_list1, const unsigned int number_in_list2, std::vector< MatchData > & matchlist) const [protected]
The actual matchers - 1.
a pretty daft but quick matcher. This one takes the list of potential matches for each feature and selects the best, resolving conflicts by first-come- first-served.
Referenced by VW::CornerMatcherBase< Feature >::Compute().
template<class Feature> void VW::CornerMatcherBase< Feature >::Compute (const std::vector< Feature > & plnew, const std::vector< Feature > & plold, std::vector< MatchData > & matchlist) const [inline]
Compute using two corner lists.
References VW::BRAINDEAD_MATCHER, VW::CornerMatcherBase< Feature >::BraindeadMatcher(), VW::CornerMatcherBase< Feature >::FindPotentialMatches(), VW::REPEATEDLY_STUPID_MATCHER, VW::CornerMatcherBase< Feature >::RepeatedlyStupidMatcher(), and VERBOSE.
template<class Feature> void VW::CornerMatcherBase< Feature >::FindPotentialMatches (const std::vector< Feature > & old_pointlist, const std::vector< Feature > & new_pointlist, std::vector< std::vector< MatchData > > & potentialmatches) const [protected]
Use GetMatchScore to obtain a set of potential matches for each point.
Referenced by VW::CornerMatcherBase< Feature >::Compute().
template<class Feature> void VW::CornerMatcherBase< Feature >::FormLookupTable (const std::vector< MatchData > & matchlist, std::vector< int > & list1, std::vector< int > & list2) const
template<class Feature> virtual float VW::CornerMatcherBase< Feature >::GetMatchScore (const Feature & f1, const Feature & f2) const [protected, pure virtual]
Implemented in VW::PatchFeatureMatcher, VW::PlesseyCornerMatcher, and VW::SIFTFeatureMatcher.
template<class Feature> virtual void VW::CornerMatcherBase< Feature >::MatchScoresToProbs (std::vector< std::vector< MatchData > > & potentialmatches) const [protected, pure virtual]
template<class Feature> VW::CornerMatcherBase< Feature >::operator bool () const [inline]
template<class Feature> bool VW::CornerMatcherBase< Feature >::RepeatedlyStupidMatcher (const std::vector< std::vector< MatchData > > & potentialmatches, const unsigned int number_in_list1, const unsigned int number_in_list2, std::vector< MatchData > & matchlist) const [protected]
The actual matchers - 2.
a simple iterative matcher. This one takes the list of potential matches for each feature and selects the best, resolving conflicts by iteration (usually only needs 3-4 passes).
Referenced by VW::CornerMatcherBase< Feature >::Compute().
template<class Feature > void VW::CornerMatcherBase< Feature >::SetMaximumRange (const float new_max_range) [inline]
template<class Feature > void VW::CornerMatcherBase< Feature >::SetScoreThreshold (const float score_thresh) [inline]
The documentation for this class was generated from the following files:
cornermatcherbase.h
cornermatcherbase.tpp