VW: VW::Covariance3D Class Reference
VW::Covariance3D Class Reference
#include <covariance3d.h>
Public Member Functions
Covariance3D ()
Construct and set to identity.
Covariance3D (double a, double b, double c, double d, double e, double f)
Construct from the three parameters of a symmetric 3x3 matrix C = [ a b c ] [ b d e ] [ c e f ].
Covariance3D (const Covariance3D &C)
Covariance3D (const VNL::MatrixFixed< 3, 3, double > &C)
Construct from an arbitrary 3x3 matrix.
void SetIdentity ()
void SetIsotropic (const double variance)
Set to diagonal with equal variances along each axis.
bool IsPositiveDefinite () const
The matrix must be either positive definite or semi-definite.
double Determinant () const
the determinant >= 0.
Covariance3D Inverse () const
If the matrix is positive definite then the inverse is also symmetrical and positive definite (ie a covariance).
VNL::MatrixFixed< 3, 3, double > AsMatrix () const
Get the matrix as a 3x3 VNL::MatrixFixed.
VNL::MatrixFixed< 3, 3, double > InverseMatrix () const
Get the inverse of the matrix as a 3x3 VNL::MatrixFixed.
double GetDistance (const double ex, const double ey, const double ez) const
Get the distance of this matrix d = (ex ey ez) C (ex ey ez)'.
double GetMahalanobisDistance (const double ex, const double ey, const double ez) const
Get the Mahalanobis distance given errors in x and y d = (ex ey ez) inv(C) (ex ey ez)' Note that the inverse makes this a bit expensive, so if you want to use it repeatedly, calculate the inverse matrix explicitly and use the GetDistance() function of the result.
Covariance3D operator* (const double scalar) const
Scale the covariance (must be a positive scalar).
Covariance3D & operator*= (const double scalar)
Scale the covariance (must be a positive scalar).
Covariance3D operator+ (const Covariance3D &C) const
Add a covariances.
Covariance3D & operator+= (const Covariance3D &C)
Add a covariances.
Covariance3D operator/ (const double scalar) const
Scale the covariance (must be a positive scalar).
Covariance3D & operator/= (const double scalar)
Scale the covariance (must be a positive scalar).
VNL::MatrixFixed< 3, 3, double > operator* (const Covariance3D &C) const
Multiplying two covariances can result in a non-symmetric matrix.
VW::Covariance2D LineariseAroundHomgPoint (const double x, const double y, const double w) const
Treat this 3D covariance as a 2D homogeneous one and linearise it around the point (x,y,w) to get the 2D non-homogeneous one.
const double & operator[] (int i) const
directly access the data (six doubles) - use with extreme caution
double & operator[] (int i)
directly access the data (six doubles) - use with extreme caution
Constructor & Destructor Documentation
VW::Covariance3D::Covariance3D () [inline]
Construct and set to identity.
Referenced by Inverse(), operator*(), operator+(), and operator/().
VW::Covariance3D::Covariance3D (double a, double b, double c, double d, double e, double f) [inline]
Construct from the three parameters of a symmetric 3x3 matrix C = [ a b c ] [ b d e ] [ c e f ].
VW::Covariance3D::Covariance3D (const Covariance3D & C) [inline]
VW::Covariance3D::Covariance3D (const VNL::MatrixFixed< 3, 3, double > & C) [inline, explicit]
Construct from an arbitrary 3x3 matrix.
If the matrix C is not positive semi-definite an assertion failure results.
Member Function Documentation
VNL::MatrixFixed< 3, 3, double > VW::Covariance3D::AsMatrix () const [inline]
Get the matrix as a 3x3 VNL::MatrixFixed.
double VW::Covariance3D::Determinant () const [inline]
the determinant >= 0.
Cost = 15 flops
Referenced by GetMahalanobisDistance(), Inverse(), and InverseMatrix().
double VW::Covariance3D::GetDistance (const double ex, const double ey, const double ez) const [inline]
Get the distance of this matrix d = (ex ey ez) C (ex ey ez)'.
If [ex ey] forms a unit vector, this is the Rayleigh quotient. Cost = 18 flops
double VW::Covariance3D::GetMahalanobisDistance (const double ex, const double ey, const double ez) const
Get the Mahalanobis distance given errors in x and y d = (ex ey ez) inv(C) (ex ey ez)' Note that the inverse makes this a bit expensive, so if you want to use it repeatedly, calculate the inverse matrix explicitly and use the GetDistance() function of the result.
Cost = 52 flops
References Determinant().
VW::Covariance3D VW::Covariance3D::Inverse () const
If the matrix is positive definite then the inverse is also symmetrical and positive definite (ie a covariance).
Cost = 40 flops
References Covariance3D(), and Determinant().
VNL::MatrixFixed< 3, 3, double > VW::Covariance3D::InverseMatrix () const
Get the inverse of the matrix as a 3x3 VNL::MatrixFixed.
Cost = 40 flops
References Determinant().
bool VW::Covariance3D::IsPositiveDefinite () const
The matrix must be either positive definite or semi-definite.
VW::Covariance2D VW::Covariance3D::LineariseAroundHomgPoint (const double x, const double y, const double w) const
Treat this 3D covariance as a 2D homogeneous one and linearise it around the point (x,y,w) to get the 2D non-homogeneous one.
If the point is linearised as [u,v] = [x/w, y/w] then the covariance linearises as C_2 = J C J' where J = [ w 0 -x ] / w^2 [ 0 w -y ] This is optimised to take 26 flops (standard multiply would take 45).
VNL::MatrixFixed< 3, 3, double > VW::Covariance3D::operator* (const Covariance3D & C) const [inline]
Multiplying two covariances can result in a non-symmetric matrix.
Cost is 45 flops
VW::Covariance3D VW::Covariance3D::operator* (const double scalar) const [inline]
Scale the covariance (must be a positive scalar).
References Covariance3D().
VW::Covariance3D & VW::Covariance3D::operator*= (const double scalar) [inline]
Scale the covariance (must be a positive scalar).
VW::Covariance3D VW::Covariance3D::operator+ (const Covariance3D & C) const [inline]
Add a covariances.
References Covariance3D().
VW::Covariance3D & VW::Covariance3D::operator+= (const Covariance3D & C) [inline]
Add a covariances.
VW::Covariance3D VW::Covariance3D::operator/ (const double scalar) const [inline]
Scale the covariance (must be a positive scalar).
References Covariance3D().
VW::Covariance3D & VW::Covariance3D::operator/= (const double scalar) [inline]
Scale the covariance (must be a positive scalar).
double & VW::Covariance3D::operator[] (int i) [inline]
directly access the data (six doubles) - use with extreme caution
const double & VW::Covariance3D::operator[] (int i) const [inline]
directly access the data (six doubles) - use with extreme caution
void VW::Covariance3D::SetIdentity () [inline]
void VW::Covariance3D::SetIsotropic (const double variance) [inline]
Set to diagonal with equal variances along each axis.
The documentation for this class was generated from the following files:
covariance3d.h
covariance3d.cpp