VW: VW::ParameterWriter Class Reference
VW::ParameterWriter Class Reference
#include <paramwriter.h>
Classes
class EOFErr
class WriterErr
Public Member Functions
ParameterWriter (std::string compute_obj, std::string filename=".params")
Basic constructor.
template<class T >
ParameterWriter (std::string compute_obj, const std::string parameter[], const T value[], unsigned int num_params, std::string filename=".params")
All-in-one constructor.
template<class T >
void AddParameter (const T &value)
Add a value to the base block.
template<class T >
void AddChildParameter (const std::string &parameter, const T &value)
Add a single parameter/value pair to the list.
template<class T >
void AddChildParameters (const std::string parameter[], const T value[], unsigned int num_params)
Add multiple parameter/value pairs (of the same type) to the list.
void WriteOut ()
Flush the stored parameters to disk.
operator bool () const
Protected Member Functions
void write_param_list (std::ostream &output_stream)
std::string get_next_label ()
void print_writer_error (WriterErr exception)
void copy_file_to_stream (std::string filename, std::streampos start_position, std::streampos end_position, std::ostream &output_stream)
Protected Attributes
ParameterParser _parser
std::map< std::string,
std::string > _parameters
std::string _compute_obj_name
std::string _filename
bool _Ok
Constructor & Destructor Documentation
VW::ParameterWriter::ParameterWriter (std::string compute_obj, std::string filename = ".params")
Basic constructor.
Compute_obj name determines the name of the lowest-level block to find in the file. Once found, parameters can be added to be either written directly into the block (AddParameter), or added between a ...
pair (AddChildParam).
template<class T > VW::ParameterWriter::ParameterWriter (std::string compute_obj, const std::string parameter[], const T value[], unsigned int num_params, std::string filename = ".params") [inline]
All-in-one constructor.
Compute_obj name determines the name of the lowest-level block to find in the file. Once found, the parameters listed in parameter[] are added as children (ie. between ...
pairs). In addition, the file is written to disk, allowing one-line parameter writing.
References _Ok, _parser, AddChildParameters(), and WriteOut().
Member Function Documentation
template<class T > void VW::ParameterWriter::AddChildParameter (const std::string & parameter, const T & value) [inline]
Add a single parameter/value pair to the list.
The parameter value is enclosed by a <parameter> ... </parameter> pair.
References _parameters, and VW::GenerateXMLString().
template<class T > void VW::ParameterWriter::AddChildParameters (const std::string parameter[], const T value[], unsigned int num_params) [inline]
Add multiple parameter/value pairs (of the same type) to the list.
Each parameter value is enclosed by a <parameter> ... </parameter> pair.
References _parameters, and VW::GenerateXMLString().
Referenced by ParameterWriter().
template<class T > void VW::ParameterWriter::AddParameter (const T & value) [inline]
Add a value to the base block.
The parameter value is NOT enclosed by a <parameter> ... </parameter> pair, and the GenerateXMLString(T) is called at the lowest level.
References _parameters, and VW::GenerateXMLString().
Referenced by VW::PlesseyOldParams::SaveParameterFile().
void VW::ParameterWriter::copy_file_to_stream (std::string filename, std::streampos start_position, std::streampos end_position, std::ostream & output_stream) [protected]
Referenced by WriteOut().
string VW::ParameterWriter::get_next_label () [protected]
References VW::ParameterParser::_file, _Ok, and _parser.
Referenced by WriteOut().
VW::ParameterWriter::operator bool () const [inline]
References _Ok.
void VW::ParameterWriter::print_writer_error (WriterErr exception) [protected]
References VW::ParameterParser::_file, _Ok, and _parser.
void VW::ParameterWriter::write_param_list (std::ostream & output_stream) [protected]
Referenced by WriteOut().
void VW::ParameterWriter::WriteOut ()
Flush the stored parameters to disk.
References _compute_obj_name, VW::ParameterParser::_file, _filename, _Ok, _parser, copy_file_to_stream(), get_next_label(), and write_param_list().
Referenced by ParameterWriter(), and VW::PlesseyOldParams::SaveParameterFile().
Member Data Documentation
std::string VW::ParameterWriter::_compute_obj_name [protected]
Referenced by WriteOut().
std::string VW::ParameterWriter::_filename [protected]
Referenced by WriteOut().
bool VW::ParameterWriter::_Ok [protected]
Referenced by get_next_label(), operator bool(), ParameterWriter(), print_writer_error(), and WriteOut().
std::map<std::string, std::string> VW::ParameterWriter::_parameters [protected]
Referenced by AddChildParameter(), AddChildParameters(), and AddParameter().
ParameterParser VW::ParameterWriter::_parser [protected]
Referenced by get_next_label(), ParameterWriter(), print_writer_error(), and WriteOut().
The documentation for this class was generated from the following files:
paramwriter.h
paramwriter.cpp