VW: VW::LineSegFitted Class Reference
VW::LineSegFitted Class Reference
[ImageProcessing]
A derivative of LineSeg2D that also includes goodness-of-fit data.
#include <linesegfitted.h>
Public Member Functions
LineSegFitted ()
LineSegFitted (Edgel *, Edgel *)
~LineSegFitted ()
bool CorrectEndpoints ()
Remove the end-edgels and update the line.
bool operator== (const LineSeg2D &ls)
void GetEndPoints (double &x0, double &y0, double &x1, double &y1) const
void GetEndPoints (Point2D &p0, Point2D &p1) const
Point2D GetStartPoint (void) const
double GetStartX (void) const
double GetStartY (void) const
Point2D GetEndPoint (void) const
double GetEndX (void) const
double GetEndY (void) const
Point2D GetMidPoint (void) const
void SetEndPoints (const double x0, const double y0, const double x1, const double y1)
void SetEndPoints (const Point2D p0, const Point2D p1)
void SetStartPoint (const Point2D p)
void SetEndPoint (const Point2D p)
LineSeg2D Truncate (const double x0, const double y0, const double x1, const double y1) const
Truncate to lie within a rectangle (x0,y0)->(x1,y1) (eg for displaying).
Vector2D GetDirection () const
Get the direction.
double GetLength () const
Get the length of the segment.
double GetLength2 () const
Get the sqaured length of the segment.
double Norm () const
The norm (length) of the segment.
double Norm2 () const
The squared norm (length) of the segment.
double GetAngle () const
Return the angle between the +ve X-axis and the line, measured clockwise ().
double GetDistanceToOrigin () const
Return the perpendicular distance of line from origin.
double DistanceToLeft (const VW::Point2D &testpoint) const
The distance to the left of the line to reach the testpoint (negative if to right).
bool IsToLeft (const VW::Point2D &testpoint) const
Is a point to the left of the line.
double DistanceToRight (const VW::Point2D &testpoint) const
The distance to the right of the line to reach the testpoint (negative if to left).
bool IsToRight (const VW::Point2D &testpoint) const
Is a point to the right of the line.
Line2D GetLine () const
Return the infinite line that this segment is part of.
double GetDistanceToLine (const VW::Point2D &testpoint) const
distance to infinite line.
double GetDistanceToLineSeg (const VW::Point2D &testpoint) const
distance to line segment including endpoints
double GetCosAngle (const VW::LineSeg2D &lineseg) const
Get the cosine of the angle between two line-segments.
bool GetIntersection (const VW::LineSeg2D &lineseg, VW::Point2D &result) const
Find the point of intersection of this lineseg with another.
virtual bool WriteASCII (std::ostream &stream) const
virtual bool WriteXML (std::ostream &stream, const std::string &name="") const
virtual bool WriteBinary (std::ostream &stream) const
virtual bool ReadASCII (std::istream &stream)
virtual bool ReadXML (std::istream &stream, const std::string &name="")
virtual bool ReadBinary (std::istream &stream)
Public Attributes
std::list< VW::Edgel * > edgels
double orient
double len
VW::Point2D midpoint
int status
LineInfo info
Point2D sp
Point2D ep
Friends
double operator* (const LineSeg2D &ls1, const LineSeg2D &ls2)
std::ostream & operator<< (std::ostream &s, const LineSeg2D &ls)
std::istream & operator>> (std::istream &s, LineSeg2D &ls)
Detailed Description
A derivative of LineSeg2D that also includes goodness-of-fit data.
Author:
ID Reid and BJ Tordoff
Date:
02/08/2002
Constructor & Destructor Documentation
LineSegFitted::LineSegFitted ()
References edgels, info, VW::LineInfo::n, VW::LineInfo::R, VW::LineInfo::sumx, VW::LineInfo::sumxx, VW::LineInfo::sumxy, VW::LineInfo::sumy, and VW::LineInfo::sumyy.
LineSegFitted::LineSegFitted (Edgel * e1, Edgel * e2)
References VW::Point2D::_x, VW::Point2D::_y, edgels, info, VW::LineInfo::n, VW::LineInfo::R, VW::LineInfo::sumx, VW::LineInfo::sumxx, VW::LineInfo::sumxy, VW::LineInfo::sumy, and VW::LineInfo::sumyy.
VW::LineSegFitted::~LineSegFitted () [inline]
References edgels.
Member Function Documentation
bool LineSegFitted::CorrectEndpoints ()
Remove the end-edgels and update the line.
Returns:
true if successful, false if this line segment is no longer valid.
References VW::Point2D::_x, VW::Point2D::_y, c, edgels, VW::LineSeg2D::GetAngle(), info, midpoint, VW::LineInfo::n, orient, PI, VW::LineSeg2D::SetEndPoints(), VW::LineInfo::sumx, VW::LineInfo::sumxx, VW::LineInfo::sumxy, VW::LineInfo::sumy, and VW::LineInfo::sumyy.
double VW::LineSeg2D::DistanceToLeft (const VW::Point2D & testpoint) const [inline, inherited]
The distance to the left of the line to reach the testpoint (negative if to right).
References VW::LineSeg2D::ep, VW::Point2D::GetX(), VW::Point2D::GetY(), VW::Point2D::Normalise(), and VW::LineSeg2D::sp.
Referenced by VW::LineSeg2D::IsToLeft().
double VW::LineSeg2D::DistanceToRight (const VW::Point2D & testpoint) const [inline, inherited]
The distance to the right of the line to reach the testpoint (negative if to left).
References VW::LineSeg2D::ep, VW::Point2D::GetX(), VW::Point2D::GetY(), VW::Point2D::Normalise(), and VW::LineSeg2D::sp.
Referenced by VW::LineSeg2D::IsToRight().
double LineSeg2D::GetAngle () const [inherited]
Return the angle between the +ve X-axis and the line, measured clockwise ().
References VW::LineSeg2D::ep, VW::Point2D::GetX(), VW::Point2D::GetY(), and VW::LineSeg2D::sp.
Referenced by CorrectEndpoints(), and VW::GetAngleBetween().
double VW::LineSeg2D::GetCosAngle (const VW::LineSeg2D & lineseg) const [inline, inherited]
Get the cosine of the angle between two line-segments.
References VW::LineSeg2D::ep, VW::Point2D::Normalise(), VW::ScalarProduct(), and VW::LineSeg2D::sp.
VW::Vector2D VW::LineSeg2D::GetDirection () const [inline, inherited]
Get the direction.
References VW::LineSeg2D::ep, VW::LineSeg2D::GetLength(), and VW::LineSeg2D::sp.
Referenced by VW::LineSeg2D::Truncate().
double LineSeg2D::GetDistanceToLine (const VW::Point2D & testpoint) const [inherited]
distance to infinite line.
References VW::Point2D::_x, VW::Point2D::_y, VW::LineSeg2D::ep, VW::LineSeg2D::GetLength(), and VW::LineSeg2D::sp.
Referenced by VW::LineSeg2D::GetDistanceToOrigin(), and VW::LineSeg2D::GetIntersection().
double LineSeg2D::GetDistanceToLineSeg (const VW::Point2D & testpoint) const [inherited]
distance to line segment including endpoints
References VW::Point2D::_x, VW::Point2D::_y, VW::LineSeg2D::ep, VW::Point2D::GetDistance(), VW::LineSeg2D::GetLength(), and VW::LineSeg2D::sp.
Referenced by VW::GetDistance().
double LineSeg2D::GetDistanceToOrigin () const [inherited]
Return the perpendicular distance of line from origin.
References VW::LineSeg2D::GetDistanceToLine().
VW::Point2D VW::LineSeg2D::GetEndPoint (void) const [inline, inherited]
References VW::LineSeg2D::ep.
Referenced by VW::RadialDistortion::Distort(), VW::Normalisation::Normalise(), VW::Line2D::Truncate(), VW::RadialDistortion::Undistort(), VW::RadialDistortion::UndistortInPlace(), and VW::Normalisation::UnNormalise().
void VW::LineSeg2D::GetEndPoints (VW::Point2D & p0, VW::Point2D & p1) const [inline, inherited]
References VW::LineSeg2D::ep, and VW::LineSeg2D::sp.
void VW::LineSeg2D::GetEndPoints (double & x0, double & y0, double & x1, double & y1) const [inline, inherited]
References VW::LineSeg2D::ep, VW::Point2D::Get(), and VW::LineSeg2D::sp.
double VW::LineSeg2D::GetEndX (void) const [inline, inherited]
References VW::LineSeg2D::ep, and VW::Point2D::GetX().
double VW::LineSeg2D::GetEndY (void) const [inline, inherited]
References VW::LineSeg2D::ep, and VW::Point2D::GetY().
bool LineSeg2D::GetIntersection (const VW::LineSeg2D & lineseg, VW::Point2D & result) const [inherited]
Find the point of intersection of this lineseg with another.
If there is no intersection, or it's beyond the end of the line(s) it returns false.
References VW::LineSeg2D::ep, VW::Point2D::GetDistance(), VW::LineSeg2D::GetDistanceToLine(), VW::LineSeg2D::GetLength(), VW::Point2D::GetX(), VW::Point2D::GetY(), VW::Point2D::Normalise(), VW::Point2D::Set(), and VW::LineSeg2D::sp.
double VW::LineSeg2D::GetLength () const [inline, inherited]
Get the length of the segment.
References VW::Point2D::_x, VW::Point2D::_y, VW::LineSeg2D::ep, VW::LineSeg2D::sp, and std::sqrt().
Referenced by VW::LineSeg2D::GetDirection(), VW::LineSeg2D::GetDistanceToLine(), VW::LineSeg2D::GetDistanceToLineSeg(), VW::LineSeg2D::GetIntersection(), and VW::LineSeg2D::Norm().
double VW::LineSeg2D::GetLength2 () const [inline, inherited]
Get the sqaured length of the segment.
References VW::Point2D::_x, VW::Point2D::_y, VW::LineSeg2D::ep, and VW::LineSeg2D::sp.
Referenced by VW::LineSeg2D::Norm2().
VW::Line2D VW::LineSeg2D::GetLine () const [inline, inherited]
Return the infinite line that this segment is part of.
References VW::LineSeg2D::ep, VW::Point2D::GetX(), VW::Point2D::GetY(), VW::Line2D::Set(), VW::LineSeg2D::sp, and std::sqrt().
Referenced by VW::LineThroughPoints().
VW::Point2D VW::LineSeg2D::GetMidPoint (void) const [inline, inherited]
References VW::LineSeg2D::ep, and VW::LineSeg2D::sp.
VW::Point2D VW::LineSeg2D::GetStartPoint (void) const [inline, inherited]
References VW::LineSeg2D::sp.
Referenced by VW::RadialDistortion::Distort(), VW::Normalisation::Normalise(), VW::Line2D::Truncate(), VW::RadialDistortion::Undistort(), VW::RadialDistortion::UndistortInPlace(), and VW::Normalisation::UnNormalise().
double VW::LineSeg2D::GetStartX (void) const [inline, inherited]
References VW::Point2D::GetX(), and VW::LineSeg2D::sp.
double VW::LineSeg2D::GetStartY (void) const [inline, inherited]
References VW::Point2D::GetY(), and VW::LineSeg2D::sp.
bool VW::LineSeg2D::IsToLeft (const VW::Point2D & testpoint) const [inline, inherited]
Is a point to the left of the line.
References VW::LineSeg2D::DistanceToLeft().
Referenced by VW::IsToLeft().
bool VW::LineSeg2D::IsToRight (const VW::Point2D & testpoint) const [inline, inherited]
Is a point to the right of the line.
References VW::LineSeg2D::DistanceToRight().
Referenced by VW::IsToRight().
double VW::LineSeg2D::Norm () const [inline, inherited]
The norm (length) of the segment.
References VW::LineSeg2D::GetLength().
double VW::LineSeg2D::Norm2 () const [inline, inherited]
The squared norm (length) of the segment.
References VW::LineSeg2D::GetLength2().
bool LineSeg2D::operator== (const LineSeg2D & ls) [inherited]
References VW::LineSeg2D::ep, and VW::LineSeg2D::sp.
bool VW::LineSeg2D::ReadASCII (std::istream & stream) [virtual, inherited]
References VW::LineSeg2D::ep, and VW::LineSeg2D::sp.
Referenced by VW::operator>>().
bool VW::LineSeg2D::ReadBinary (std::istream & stream) [virtual, inherited]
References VW::LineSeg2D::ep, VW::Point2D::ReadBinary(), and VW::LineSeg2D::sp.
bool VW::LineSeg2D::ReadXML (std::istream & stream, const std::string & name = "") [virtual, inherited]
References VW::LineSeg2D::ep, VW::FindXMLBlock(), VW::Point2D::ReadXML(), and VW::LineSeg2D::sp.
void VW::LineSeg2D::SetEndPoint (const Point2D p) [inline, inherited]
References VW::LineSeg2D::ep.
void VW::LineSeg2D::SetEndPoints (const Point2D p0, const Point2D p1) [inline, inherited]
References VW::LineSeg2D::ep, and VW::LineSeg2D::sp.
void VW::LineSeg2D::SetEndPoints (const double x0, const double y0, const double x1, const double y1) [inline, inherited]
References VW::LineSeg2D::ep, VW::Point2D::Set(), and VW::LineSeg2D::sp.
Referenced by CorrectEndpoints(), and VW::RadialDistortion::UndistortInPlace().
void VW::LineSeg2D::SetStartPoint (const Point2D p) [inline, inherited]
References VW::LineSeg2D::sp.
LineSeg2D LineSeg2D::Truncate (const double x0, const double y0, const double x1, const double y1) const [inherited]
Truncate to lie within a rectangle (x0,y0)->(x1,y1) (eg for displaying).
References VW::LineSeg2D::ep, VW::LineSeg2D::GetDirection(), VW::Point2D::GetX(), VW::Point2D::GetY(), VW::LineSeg2D::LineSeg2D(), and VW::LineSeg2D::sp.
bool VW::LineSeg2D::WriteASCII (std::ostream & stream) const [virtual, inherited]
References VW::LineSeg2D::ep, and VW::LineSeg2D::sp.
Referenced by VW::operator<<().
bool VW::LineSeg2D::WriteBinary (std::ostream & stream) const [virtual, inherited]
References VW::LineSeg2D::ep, VW::LineSeg2D::sp, and VW::Point2D::WriteBinary().
bool VW::LineSeg2D::WriteXML (std::ostream & stream, const std::string & name = "") const [virtual, inherited]
References VW::LineSeg2D::ep, VW::LineSeg2D::sp, and VW::Point2D::WriteXML().
Friends And Related Function Documentation
double operator* (const LineSeg2D & ls1, const LineSeg2D & ls2) [friend, inherited]
std::ostream& operator<< (std::ostream & s, const LineSeg2D & ls) [friend, inherited]
std::istream& operator>> (std::istream & s, LineSeg2D & ls) [friend, inherited]
Member Data Documentation
std::list<VW::Edgel *> VW::LineSegFitted::edgels
Referenced by CorrectEndpoints(), LineSegFitted(), and ~LineSegFitted().
Point2D VW::LineSeg2D::ep [inherited]
Referenced by VW::LineSeg2D::DistanceToLeft(), VW::LineSeg2D::DistanceToRight(), VW::DrawFunctions::Draw(), VW::LineSeg2D::GetAngle(), VW::LineSeg2D::GetCosAngle(), VW::LineSeg2D::GetDirection(), VW::LineSeg2D::GetDistanceToLine(), VW::LineSeg2D::GetDistanceToLineSeg(), VW::LineSeg2D::GetEndPoint(), VW::LineSeg2D::GetEndPoints(), VW::LineSeg2D::GetEndX(), VW::LineSeg2D::GetEndY(), VW::LineSeg2D::GetIntersection(), VW::LineSeg2D::GetLength(), VW::LineSeg2D::GetLength2(), VW::LineSeg2D::GetLine(), VW::LineSeg2D::GetMidPoint(), operator*(), VW::LineSeg2D::operator=(), VW::LineSeg2D::operator==(), VW::LineSeg2D::ReadASCII(), VW::LineSeg2D::ReadBinary(), VW::LineSeg2D::ReadXML(), VW::LineSeg2D::SetEndPoint(), VW::LineSeg2D::SetEndPoints(), VW::LineSeg2D::Truncate(), VW::LineSeg2D::WriteASCII(), VW::LineSeg2D::WriteBinary(), and VW::LineSeg2D::WriteXML().
LineInfo VW::LineSegFitted::info
Referenced by CorrectEndpoints(), LineSegFitted(), and VW::LenThresh::operator()().
double VW::LineSegFitted::len
VW::Point2D VW::LineSegFitted::midpoint
Referenced by CorrectEndpoints().
double VW::LineSegFitted::orient
Referenced by CorrectEndpoints().
Point2D VW::LineSeg2D::sp [inherited]
Referenced by VW::LineSeg2D::DistanceToLeft(), VW::LineSeg2D::DistanceToRight(), VW::DrawFunctions::Draw(), VW::LineSeg2D::GetAngle(), VW::LineSeg2D::GetCosAngle(), VW::LineSeg2D::GetDirection(), VW::LineSeg2D::GetDistanceToLine(), VW::LineSeg2D::GetDistanceToLineSeg(), VW::LineSeg2D::GetEndPoints(), VW::LineSeg2D::GetIntersection(), VW::LineSeg2D::GetLength(), VW::LineSeg2D::GetLength2(), VW::LineSeg2D::GetLine(), VW::LineSeg2D::GetMidPoint(), VW::LineSeg2D::GetStartPoint(), VW::LineSeg2D::GetStartX(), VW::LineSeg2D::GetStartY(), operator*(), VW::LineSeg2D::operator=(), VW::LineSeg2D::operator==(), VW::LineSeg2D::ReadASCII(), VW::LineSeg2D::ReadBinary(), VW::LineSeg2D::ReadXML(), VW::LineSeg2D::SetEndPoints(), VW::LineSeg2D::SetStartPoint(), VW::LineSeg2D::Truncate(), VW::LineSeg2D::WriteASCII(), VW::LineSeg2D::WriteBinary(), and VW::LineSeg2D::WriteXML().
int VW::LineSegFitted::status
The documentation for this class was generated from the following files:
linesegfitted.h
linesegfitted.cpp