VW: VW::FMatrixComputeLinear Class Reference
VW::FMatrixComputeLinear Class Reference
#include <fmatrixcomputelinear.h>
Public Member Functions
FMatrixComputeLinear (const bool normalise=true)
Create a linear computation object.
bool Compute (VW::FMatrix &result, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1)
Compute an fmatrix from two lists of 2D point features.
bool Compute (VW::FMatrix &result, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const std::vector< unsigned int > &which_features)
Compute an fmatrix from two lists of 2D point features.
bool ComputeWeighted (VW::FMatrix &result, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const std::vector< double > &weights)
Compute an fmatrix from two lists of 2D point features, weighting the contribution of the features.
bool Compute (VW::FMatrix &result, VW::FMatrixCovariance &covar, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const double noise0, const double noise1)
Compute an fmatrix and its covariance from two lists of 2D point features.
bool Compute (VW::FMatrix &result, VW::FMatrixCovariance &covar, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const double noise0, const double noise1, const std::vector< unsigned int > &which_features)
Compute an fmatrix and its covariance from selected entries of two lists of 2D point features.
bool Compute (VW::FMatrix &result, const std::vector< VW::Line2D > &l0, const std::vector< VW::Line2D > &l1)
Compute an fmatrix from 2D line features (not implemented yet).
Constructor & Destructor Documentation
VW::FMatrixComputeLinear::FMatrixComputeLinear (const bool normalise = true) [inline]
Create a linear computation object.
Note that the calculation can involve a normalisation, so it is not necessary to pre-normalise the input points/lines (although it doesn't hurt).
Member Function Documentation
bool VW::FMatrixComputeLinear::Compute (VW::FMatrix & result, const std::vector< VW::Line2D > & l0, const std::vector< VW::Line2D > & l1)
Compute an fmatrix from 2D line features (not implemented yet).
bool VW::FMatrixComputeLinear::Compute (VW::FMatrix & result, VW::FMatrixCovariance & covar, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const double noise0, const double noise1, const std::vector< unsigned int > & which_features)
Compute an fmatrix and its covariance from selected entries of two lists of 2D point features.
References VW::EssentialMatrixCompute::AddToDesignMatrix(), VW::Normalisation::GetScale(), VW::Normalisation::Init(), VW::EssentialMatrixCompute::MakeSymmetric(), VW::Normalisation::Normalise(), VW::FMatrixAffineCompute::RecoverF(), VNL::Matrix< T >::Transpose(), VW::EssentialMatrixCompute::Unnormalise(), and VERBOSE.
bool VW::FMatrixComputeLinear::Compute (VW::FMatrix & result, VW::FMatrixCovariance & covar, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const double noise0, const double noise1)
Compute an fmatrix and its covariance from two lists of 2D point features.
References VW::EssentialMatrixCompute::AddToDesignMatrix(), VW::Normalisation::GetScale(), VW::Normalisation::Init(), VW::EssentialMatrixCompute::MakeSymmetric(), VW::Normalisation::Normalise(), VW::FMatrixAffineCompute::RecoverF(), VNL::Matrix< T >::Transpose(), VW::EssentialMatrixCompute::Unnormalise(), and VERBOSE.
bool VW::FMatrixComputeLinear::Compute (VW::FMatrix & result, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const std::vector< unsigned int > & which_features)
Compute an fmatrix from two lists of 2D point features.
Note that x0, x1 are defined such that x_1 = H x_0
Parameters:
which_features a list of the indices of feature-pairs to use
References VW::EssentialMatrixCompute::AddToDesignMatrix(), VW::Normalisation::Init(), VW::EssentialMatrixCompute::MakeSymmetric(), VW::Normalisation::Normalise(), and VW::FMatrixAffineCompute::RecoverF().
bool VW::FMatrixComputeLinear::Compute (VW::FMatrix & result, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1)
Compute an fmatrix from two lists of 2D point features.
Note that x0, x1 are defined such that x_1 = H x_0
Parameters:
inlierlist a list of the indices of feature-pairs to use
References VW::EssentialMatrixCompute::AddToDesignMatrix(), VW::Normalisation::Init(), VW::EssentialMatrixCompute::MakeSymmetric(), VW::Normalisation::Normalise(), VW::FMatrixAffineCompute::RecoverF(), and VERBOSE.
Referenced by VW::FMatrixCompute::GUNSACCore(), and VW::FMatrixCompute::MLESACCore().
bool VW::FMatrixComputeLinear::ComputeWeighted (VW::FMatrix & result, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const std::vector< double > & weights)
Compute an fmatrix from two lists of 2D point features, weighting the contribution of the features.
References VW::EssentialMatrixCompute::AddToDesignMatrix(), VW::Normalisation::Init(), VW::EssentialMatrixCompute::MakeSymmetric(), VW::Normalisation::Normalise(), VW::FMatrixAffineCompute::RecoverF(), and VERBOSE.
Referenced by VW::FMatrixCompute::GUNSACCore().
The documentation for this class was generated from the following files:
fmatrixcomputelinear.h
fmatrixcomputelinear.cpp