VW: VW::PlesseyParamsGTK Class Reference
VW::PlesseyParamsGTK Class Reference
#include <plesseyparamsgtk.h>
Public Member Functions
PlesseyParamsGTK (VW::InterfaceType t=VW::INTERFACE_AS_BUTTONWINDOW)
PlesseyParamsGTK (float _strength_threshold, float _gaussian_sigma, unsigned int _convolution_patch_size, float _edge_phobia, unsigned int _stored_patch_size, VW::InterfaceType t=VW::INTERFACE_AS_BUTTONWINDOW)
void AttachPlesseyObject (VW::Plessey &plessey_object)
virtual void Set (const float new_strengththreshold, const float new_gaussiansigma, const unsigned int new_convolutionpatchsize, const float new_edgephobia, const unsigned int new_storedpatchsize)
void UpdateForm ()
virtual void SetStrengthThreshold (const float new_value)
virtual void SetGaussianSigma (const float new_value)
virtual void SetConvolutionPatchSize (const unsigned int new_value)
virtual void SetEdgePhobia (const float new_value)
virtual void SetStoredPatchSize (const unsigned int new_value)
virtual void LoadParameterFile (std::string paramfile=".params")
virtual void SaveParameterFile (std::string paramfile=".params")
void UpdateFromForm ()
void Show (void)
void Hide (void)
void Quit (void)
VW::InterfaceType GetType (void)
Protected Member Functions
void LoadStart ()
void LoadOK ()
void SaveStart ()
void SaveOK ()
void FileCancel ()
virtual void InitButtonWindow ()
virtual void InitButtonWindow (unsigned int width, unsigned int height)
virtual void InitWidget ()
Protected Attributes
SigC::Signal1< void, std::string > LoadEvent
SigC::Signal1< void, std::string > SaveEvent
PlesseyParamsGTKWidget * my_widget
Gtk::Window * my_window
VW::InterfaceType my_type
std::string my_name
Gtk::FileSelection * file_selector
Constructor & Destructor Documentation
VW::PlesseyParamsGTK::PlesseyParamsGTK (VW::InterfaceType t = VW::INTERFACE_AS_BUTTONWINDOW)
References VW::InterfaceGTK< PlesseyParamsGTKWidget >::InitButtonWindow(), VW::PlesseyParamsGTKWidget::InitForm(), VW::InterfaceGTK< PlesseyParamsGTKWidget >::InitWidget(), VW::INTERFACE_AS_BUTTONWINDOW, VW::InterfaceGTK< PlesseyParamsGTKWidget >::my_name, VW::InterfaceGTK< PlesseyParamsGTKWidget >::my_type, and VW::InterfaceGTK< PlesseyParamsGTKWidget >::my_widget.
VW::PlesseyParamsGTK::PlesseyParamsGTK (float _strength_threshold, float _gaussian_sigma, unsigned int _convolution_patch_size, float _edge_phobia, unsigned int _stored_patch_size, VW::InterfaceType t = VW::INTERFACE_AS_BUTTONWINDOW)
References VW::InterfaceGTK< PlesseyParamsGTKWidget >::InitButtonWindow(), VW::InterfaceGTK< PlesseyParamsGTKWidget >::InitWidget(), VW::INTERFACE_AS_BUTTONWINDOW, VW::InterfaceGTK< PlesseyParamsGTKWidget >::my_name, and VW::InterfaceGTK< PlesseyParamsGTKWidget >::my_type.
Member Function Documentation
void VW::PlesseyParamsGTK::AttachPlesseyObject (VW::Plessey & plessey_object)
void VW::InterfaceGTK< PlesseyParamsGTKWidget >::FileCancel () [inline, protected, inherited]
VW::InterfaceType VW::InterfaceGTK< PlesseyParamsGTKWidget >::GetType (void) [inline, inherited]
void VW::InterfaceGTK< PlesseyParamsGTKWidget >::Hide (void) [inline, inherited]
virtual void VW::InterfaceGTK< PlesseyParamsGTKWidget >::InitButtonWindow (unsigned int width, unsigned int height) [protected, virtual, inherited]
virtual void VW::InterfaceGTK< PlesseyParamsGTKWidget >::InitButtonWindow () [protected, virtual, inherited]
Referenced by PlesseyParamsGTK().
virtual void VW::InterfaceGTK< PlesseyParamsGTKWidget >::InitWidget () [protected, virtual, inherited]
Referenced by PlesseyParamsGTK().
void VW::InterfaceGTK< PlesseyParamsGTKWidget >::LoadOK () [inline, protected, inherited]
void VW::PlesseyParamsGTK::LoadParameterFile (std::string paramfile = ".params") [virtual]
References UpdateForm().
void VW::InterfaceGTK< PlesseyParamsGTKWidget >::LoadStart () [inline, protected, inherited]
void VW::InterfaceGTK< PlesseyParamsGTKWidget >::Quit (void) [inline, inherited]
void VW::InterfaceGTK< PlesseyParamsGTKWidget >::SaveOK () [inline, protected, inherited]
void VW::PlesseyParamsGTK::SaveParameterFile (std::string paramfile = ".params") [virtual]
References UpdateForm().
void VW::InterfaceGTK< PlesseyParamsGTKWidget >::SaveStart () [inline, protected, inherited]
void VW::PlesseyParamsGTK::Set (const float new_strengththreshold, const float new_gaussiansigma, const unsigned int new_convolutionpatchsize, const float new_edgephobia, const unsigned int new_storedpatchsize) [virtual]
References UpdateForm().
void VW::PlesseyParamsGTK::SetConvolutionPatchSize (const unsigned int new_value) [virtual]
References UpdateForm().
void VW::PlesseyParamsGTK::SetEdgePhobia (const float new_value) [virtual]
References UpdateForm().
void VW::PlesseyParamsGTK::SetGaussianSigma (const float new_value) [virtual]
References UpdateForm().
void VW::PlesseyParamsGTK::SetStoredPatchSize (const unsigned int new_value) [virtual]
References UpdateForm().
void VW::PlesseyParamsGTK::SetStrengthThreshold (const float new_value) [virtual]
References UpdateForm().
void VW::InterfaceGTK< PlesseyParamsGTKWidget >::Show (void) [inline, inherited]
void VW::PlesseyParamsGTK::UpdateForm (void) [virtual]
Implements VW::InterfaceGTK< PlesseyParamsGTKWidget >.
References VW::PlesseyParamsGTKWidget::convolution_size_spinner, VW::InterfaceGTK< PlesseyParamsGTKWidget >::my_widget, VW::PlesseyParamsGTKWidget::phobia_spinner, VW::PlesseyParamsGTKWidget::sigma_spinner, VW::PlesseyParamsGTKWidget::stored_size_spinner, and VW::PlesseyParamsGTKWidget::thresh_spinner.
Referenced by LoadParameterFile(), SaveParameterFile(), Set(), SetConvolutionPatchSize(), SetEdgePhobia(), SetGaussianSigma(), SetStoredPatchSize(), and SetStrengthThreshold().
void VW::PlesseyParamsGTK::UpdateFromForm ()
References VW::PlesseyParamsGTKWidget::convolution_size_spinner, VW::InterfaceGTK< PlesseyParamsGTKWidget >::my_widget, VW::PlesseyParamsGTKWidget::phobia_spinner, VW::PlesseyParamsGTKWidget::sigma_spinner, VW::PlesseyParamsGTKWidget::stored_size_spinner, and VW::PlesseyParamsGTKWidget::thresh_spinner.
Referenced by VW::PlesseyParamsGTKWidget::InitForm().
Member Data Documentation
Gtk::FileSelection* VW::InterfaceGTK< PlesseyParamsGTKWidget >::file_selector [protected, inherited]
SigC::Signal1<void,std::string> VW::InterfaceGTK< PlesseyParamsGTKWidget >::LoadEvent [protected, inherited]
std::string VW::InterfaceGTK< PlesseyParamsGTKWidget >::my_name [protected, inherited]
Referenced by PlesseyParamsGTK().
VW::InterfaceType VW::InterfaceGTK< PlesseyParamsGTKWidget >::my_type [protected, inherited]
Referenced by PlesseyParamsGTK().
PlesseyParamsGTKWidget * VW::InterfaceGTK< PlesseyParamsGTKWidget >::my_widget [protected, inherited]
Referenced by PlesseyParamsGTK(), UpdateForm(), and UpdateFromForm().
Gtk::Window* VW::InterfaceGTK< PlesseyParamsGTKWidget >::my_window [protected, inherited]
SigC::Signal1<void,std::string> VW::InterfaceGTK< PlesseyParamsGTKWidget >::SaveEvent [protected, inherited]
The documentation for this class was generated from the following files:
plesseyparamsgtk.h
plesseyparamsgtk.cpp