VW: VW::Correlate Class Reference
VW::Correlate Class Reference
#include <correlate.h>
Public Member Functions
Correlate (const VW::ImagePatch &p1, const VW::ImagePatch &p2, float &result)
Compute the zero-normalised correlation between two image patches.
Correlate (const VW::ImagePatchYUV &p1, const VW::ImagePatchYUV &p2, float &result)
Compute the zero-normalised correlation between two YUV image patches.
template<class Type >
Correlate (const VW::ImagePatch &patch, const VW::ImageMono< Type > &image, VW::ImageMono< float > &result)
Compute the zero-normalised correlation between an image patch and every pixel within the ROI of an image, storing the result in a new image.
template<class Type >
Correlate (const VW::ImagePatch &patch, const VW::ImageMono< Type > &image, VW::ImagePatch &result)
Compute the zero-normalised correlation between an image patch and every pixel within the ROI of an image, storing the result in a new patch.
template<class Type >
Correlate (const VW::ImagePatch &patch, const VW::ImageMono< Type > &image, const VW::ROI &roi, VW::ImagePatch &result)
Compute the zero-normalised correlation between an image patch and pixels in the specified ROI, storing the result in a new patch.
template<class Type >
Correlate (const VW::ImagePatch &patch, const VW::ImageYUV< Type > &image, const VW::ROI &roi, VW::ImagePatch &result)
Compute the zero-normalised correlation between an image patch and pixels in the specified ROI using only the Y channel of the YUV image, storing the result in a new patch.
void Compute (const VW::ImagePatch &p1, const VW::ImagePatch &p2, float &result) const
void Compute (const VW::ImagePatchYUV &p1, const VW::ImagePatchYUV &p2, float &result) const
template<class Type >
void Compute (const VW::ImagePatch &patch, const VW::ImageMono< Type > &image, VW::ImageMono< float > &result) const
template<class Type >
void Compute (const VW::ImagePatch &patch, const VW::ImageMono< Type > &image, VW::ImagePatch &result) const
template<class Type >
void Compute (const VW::ImagePatch &patch, const VW::ImageMono< Type > &image, const VW::ROI &roi, VW::ImagePatch &result) const
template<class Type >
void Compute (const VW::ImagePatch &patch, const VW::ImageYUV< Type > &image, const VW::ROI &roi, VW::ImagePatch &result) const
Detailed Description
Author:
BJ Tordoff
Date:
05/04/2004 @ Brief A class for computing the zero-normalised cross-correlation (ZNCC) between a patch and either another patch or an image.
Constructor & Destructor Documentation
VW::Correlate::Correlate (const VW::ImagePatch & p1, const VW::ImagePatch & p2, float & result) [inline]
Compute the zero-normalised correlation between two image patches.
References Compute().
VW::Correlate::Correlate (const VW::ImagePatchYUV & p1, const VW::ImagePatchYUV & p2, float & result) [inline]
Compute the zero-normalised correlation between two YUV image patches.
References Compute().
template<class Type > VW::Correlate::Correlate (const VW::ImagePatch & patch, const VW::ImageMono< Type > & image, VW::ImageMono< float > & result) [inline]
Compute the zero-normalised correlation between an image patch and every pixel within the ROI of an image, storing the result in a new image.
References Compute().
template<class Type > VW::Correlate::Correlate (const VW::ImagePatch & patch, const VW::ImageMono< Type > & image, VW::ImagePatch & result) [inline]
Compute the zero-normalised correlation between an image patch and every pixel within the ROI of an image, storing the result in a new patch.
References Compute().
template<class Type > VW::Correlate::Correlate (const VW::ImagePatch & patch, const VW::ImageMono< Type > & image, const VW::ROI & roi, VW::ImagePatch & result) [inline]
Compute the zero-normalised correlation between an image patch and pixels in the specified ROI, storing the result in a new patch.
References Compute().
template<class Type > VW::Correlate::Correlate (const VW::ImagePatch & patch, const VW::ImageYUV< Type > & image, const VW::ROI & roi, VW::ImagePatch & result) [inline]
Compute the zero-normalised correlation between an image patch and pixels in the specified ROI using only the Y channel of the YUV image, storing the result in a new patch.
References Compute().
Member Function Documentation
template<class Type > void VW::Correlate::Compute (const VW::ImagePatch & patch, const VW::ImageYUV< Type > & image, const VW::ROI & roi, VW::ImagePatch & result) const [inline]
References VW::ROI::Bottom(), VW::ImagePatch::GetHeight(), VW::ImagePatch::GetMean(), VW::ImagePatch::GetNormalisedSumSquared(), VW::IntegralImage< DataType >::GetRegionSum(), VW::IntegralImageSquared< DataType >::GetRegionSumSquared(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetRowStart(), VW::ImagePatch::GetRowStart(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), VW::ImagePatch::GetWidth(), VW::ROI::Height(), VW::ROI::Left(), VW::ImagePatch::Resize(), VW::ROI::Right(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::ROI(), std::sqrt(), VW::ROI::Top(), and VW::ROI::Width().
template<class Type > void VW::Correlate::Compute (const VW::ImagePatch & patch, const VW::ImageMono< Type > & image, const VW::ROI & roi, VW::ImagePatch & result) const [inline]
References VW::ROI::Bottom(), VW::ImagePatch::GetHeight(), VW::ImagePatch::GetMean(), VW::ImagePatch::GetNormalisedSumSquared(), VW::IntegralImage< DataType >::GetRegionSum(), VW::IntegralImageSquared< DataType >::GetRegionSumSquared(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetRowStart(), VW::ImagePatch::GetRowStart(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), VW::ImagePatch::GetWidth(), VW::ROI::Height(), VW::ROI::Left(), VW::ImagePatch::Resize(), VW::ROI::Right(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::ROI(), std::sqrt(), VW::ROI::Top(), and VW::ROI::Width().
template<class Type > void VW::Correlate::Compute (const VW::ImagePatch & patch, const VW::ImageMono< Type > & image, VW::ImagePatch & result) const [inline]
References Compute().
template<class Type > void VW::Correlate::Compute (const VW::ImagePatch & patch, const VW::ImageMono< Type > & image, VW::ImageMono< float > & result) const [inline]
References VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::AllocImageData(), VW::ROI::Bottom(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::FreeImageData(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), VW::ImagePatch::GetHeight(), VW::ImagePatch::GetMean(), VW::ImagePatch::GetNormalisedSumSquared(), VW::IntegralImage< DataType >::GetRegionSum(), VW::IntegralImageSquared< DataType >::GetRegionSumSquared(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetROIRowStart(), VW::ImagePatch::GetRowStart(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetRowStart(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), VW::ImagePatch::GetWidth(), VW::ROI::Height(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::IsAlloced(), VW::ROI::Left(), VW::ROI::Right(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::ROI(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::SetROI(), VW::ROI::ShrinkHeight(), VW::ROI::ShrinkWidth(), std::sqrt(), VW::ROI::Top(), and VW::ROI::Width().
void VW::Correlate::Compute (const VW::ImagePatchYUV & p1, const VW::ImagePatchYUV & p2, float & result) const [inline]
References VW::ImagePatchYUV::GetZNCC().
void VW::Correlate::Compute (const VW::ImagePatch & p1, const VW::ImagePatch & p2, float & result) const [inline]
References VW::ImagePatch::GetZNCC().
Referenced by Compute(), and Correlate().
The documentation for this class was generated from the following files:
correlate.h
correlate.cpp