VW: VNL::Cholesky< T > Class Template Reference
VNL::Cholesky< T > Class Template Reference
Decomposition of symmetric matrix.
#include <cholesky.h>
Public Types
enum Operation { quiet, verbose, estimate_condition }
Modes of computation. See constructor for details.
Public Member Functions
Cholesky (Matrix< T > const &M, Operation mode=verbose)
Make cholesky decomposition of M optionally computing the reciprocal condition number.
~Cholesky ()
Vector< T > Solve (Vector< T > const &b) const
Solve LS problem M x = b.
void Solve (Vector< T > const &b, Vector< T > *x) const
Solve LS problem M x = b.
T Determinant () const
Compute determinant.
Matrix< T > Inverse () const
Compute inverse. Not efficient.
Matrix< T > LowerTriangle () const
Return lower-triangular factor.
Matrix< T > UpperTriangle () const
Return upper-triangular factor.
Matrix< T > const & LBadlyNamedMethod ()
Return the decomposition matrix.
int RankDeficiency () const
A Success/failure flag.
T RCond () const
Return reciprocal condition number (smallest/largest singular values).
Vector< T > & Nullvector ()
Return computed nullvector.
Vector< T > const & Nullvector () const
Protected Attributes
Matrix< T > A_
T rcond_
int num_dims_rank_def_
Vector< T > nullvector_
Detailed Description
template<class T>
class VNL::Cholesky< T >
Decomposition of symmetric matrix.
A class to hold the Cholesky decomposition of a symmetric matrix and use that to solve linear systems, compute determinants and inverses. The cholesky decomposition decomposes symmetric A = L*L.transpose() where L is lower triangular, and it is therefore possible to save a little time and pass it a matrix with only the lower triangle filled in (the upper is assumed symmetric). No test for symmetry is performed.
To check that the decomposition can be used safely for solving a linear equation it is wise to construct with mode==estimate_condition and check that rcond()>sqrt(machine precision). If this is not the case it might be a good idea to use VNL::SVD instead.
Member Enumeration Documentation
template<class T > enum VNL::Cholesky::Operation
Modes of computation. See constructor for details.
Enumerator:
quiet
verbose
estimate_condition
Constructor & Destructor Documentation
template<class T > VNL::Cholesky< T >::Cholesky (VNL::Matrix< T > const & M, Operation mode = verbose) [inline]
Make cholesky decomposition of M optionally computing the reciprocal condition number.
Cholesky decomposition.
Make cholesky decomposition of M optionally computing the reciprocal condition number. If mode is estimate_condition, the condition number and an approximate nullspace are estimated, at a cost of a factor of (1 + 18/n). Here's a table of 1 + 18/n:
 n:              3      5     10     50    100    500   1000
 slowdown:     7.0    4.6    2.8    1.4   1.18   1.04   1.02
*
References VNL::Cholesky< T >::A_, VNL::Matrix< T >::Columns(), VNL::Vector< T >::DataBlock(), VNL::Cholesky< T >::estimate_condition, VNL::Cholesky< T >::num_dims_rank_def_, VNL::Cholesky< T >::rcond_, VNL::Matrix< T >::Rows(), and VNL::Cholesky< T >::verbose.
template<class T > VNL::Cholesky< T >::~Cholesky () [inline]
Member Function Documentation
template<class T > T VNL::Cholesky< T >::Determinant () const [inline]
Compute determinant.
References VNL::Cholesky< T >::A_, and VNL::Matrix< T >::DataBlock().
template<class T > VNL::Matrix< T > VNL::Cholesky< T >::Inverse () const [inline]
Compute inverse. Not efficient.
References VNL::Cholesky< T >::A_, and VNL::Matrix< T >::DataBlock().
template<class T > Matrix<T> const& VNL::Cholesky< T >::LBadlyNamedMethod () [inline]
Return the decomposition matrix.
References VNL::Cholesky< T >::A_.
template<class T > VNL::Matrix< T > VNL::Cholesky< T >::LowerTriangle () const [inline]
Return lower-triangular factor.
References VNL::Cholesky< T >::A_.
template<class T > Vector<T> const& VNL::Cholesky< T >::Nullvector () const [inline]
References VNL::Cholesky< T >::nullvector_.
template<class T > Vector<T>& VNL::Cholesky< T >::Nullvector () [inline]
Return computed nullvector.
Not calculated unless Operaton mode at construction was estimate_condition.
References VNL::Cholesky< T >::nullvector_.
template<class T > int VNL::Cholesky< T >::RankDeficiency () const [inline]
A Success/failure flag.
References VNL::Cholesky< T >::num_dims_rank_def_.
template<class T > T VNL::Cholesky< T >::RCond () const [inline]
Return reciprocal condition number (smallest/largest singular values).
As long as rcond()>sqrt(precision) the decomposition can be used for solving equations safely. Not calculated unless Operaton mode at construction was estimate_condition.
References VNL::Cholesky< T >::rcond_.
template<class T > void VNL::Cholesky< T >::Solve (VNL::Vector< T > const & b, VNL::Vector< T > * x) const [inline]
Solve LS problem M x = b.
Solve least squares problem M x = b.
The right-hand-side std::vector x may be b, which will give a fractional increase in speed.
References VNL::Cholesky< T >::A_, and VNL::Vector< T >::size().
template<class T > VNL::Vector< T > VNL::Cholesky< T >::Solve (VNL::Vector< T > const & b) const [inline]
Solve LS problem M x = b.
Solve least squares problem M x = b.
References VNL::Cholesky< T >::A_, VNL::Vector< T >::DataBlock(), and VNL::Vector< T >::size().
template<class T > VNL::Matrix< T > VNL::Cholesky< T >::UpperTriangle () const [inline]
Return upper-triangular factor.
References VNL::Cholesky< T >::A_.
Member Data Documentation
template<class T > Matrix<T> VNL::Cholesky< T >::A_ [protected]
Referenced by VNL::Cholesky< T >::Cholesky(), VNL::Cholesky< T >::Determinant(), VNL::Cholesky< T >::Inverse(), VNL::Cholesky< T >::LBadlyNamedMethod(), VNL::Cholesky< T >::LowerTriangle(), VNL::Cholesky< T >::Solve(), and VNL::Cholesky< T >::UpperTriangle().
template<class T > Vector<T> VNL::Cholesky< T >::nullvector_ [protected]
Referenced by VNL::Cholesky< T >::Nullvector().
template<class T > int VNL::Cholesky< T >::num_dims_rank_def_ [protected]
Referenced by VNL::Cholesky< T >::Cholesky(), and VNL::Cholesky< T >::RankDeficiency().
template<class T > T VNL::Cholesky< T >::rcond_ [protected]
Referenced by VNL::Cholesky< T >::Cholesky(), and VNL::Cholesky< T >::RCond().
The documentation for this class was generated from the following files:
cholesky.h
cholesky.tpp