VW: VW::Histogram2D Class Reference
VW::Histogram2D Class Reference
A simple class for storing and retrieving 2D histogram values.
#include <histogram2d.h>
Public Member Functions
Histogram2D ()
Create uninitialised.
Histogram2D (const std::vector< double > &xvals, const std::vector< double > &yvals)
Create with arrays giving the axis values.
~Histogram2D ()
void SetAxes (const std::vector< double > &xvals, const std::vector< double > &yvals)
unsigned int SizeX () const
Number of bins in X direction.
unsigned int SizeY () const
Number of bins in Y direction.
double RangeX () const
Range spanned by Y-axis.
double RangeY () const
Range spanned by Y-axis.
double XTick (unsigned int which) const
double YTick (unsigned int which) const
double GetData (unsigned int x_index, unsigned int y_index) const
double GetInterpValue (double x_val, double y_val) const
Estimate the histogram value by bilinear interpolation.
double GetClosestValue (double x_val, double y_val) const
Get the histogram value of the closest bin.
bool FindPeaks (std::vector< Histogram2DLocation > &peaks, unsigned int max_num=0) const
If any peaks are found they are stored in peaks, strongest first, otherwise return value is false.
bool FindTroughs (std::vector< Histogram2DLocation > &troughs) const
If any troughs are found they are stored in peaks, otherwise return value is false.
operator bool () const
double * operator[] (int i)
Note that direct array access (H[j][i]) is row-major, so is same as H.GetData(i,j).
const double * operator[] (int i) const
Friends
std::ostream & operator<< (std::ostream &, const Histogram2D &)
Detailed Description
A simple class for storing and retrieving 2D histogram values.
Author:
BJ Tordoff
Date:
04/06/2004
Constructor & Destructor Documentation
VW::Histogram2D::Histogram2D ()
Create uninitialised.
VW::Histogram2D::Histogram2D (const std::vector< double > & xvals, const std::vector< double > & yvals)
Create with arrays giving the axis values.
VW::Histogram2D::~Histogram2D ()
Member Function Documentation
bool VW::Histogram2D::FindPeaks (std::vector< Histogram2DLocation > & peaks, unsigned int max_num = 0) const
If any peaks are found they are stored in peaks, strongest first, otherwise return value is false.
If max_num is non zero then only the strongest max_num peaks are returned.
References VW::Histogram2DLocation::x, and VW::Histogram2DLocation::y.
bool VW::Histogram2D::FindTroughs (std::vector< Histogram2DLocation > & troughs) const
If any troughs are found they are stored in peaks, otherwise return value is false.
double VW::Histogram2D::GetClosestValue (double x_val, double y_val) const
Get the histogram value of the closest bin.
double VW::Histogram2D::GetData (unsigned int x_index, unsigned int y_index) const [inline]
double VW::Histogram2D::GetInterpValue (double x_val, double y_val) const
Estimate the histogram value by bilinear interpolation.
VW::Histogram2D::operator bool () const [inline]
const double* VW::Histogram2D::operator[] (int i) const [inline]
double* VW::Histogram2D::operator[] (int i) [inline]
Note that direct array access (H[j][i]) is row-major, so is same as H.GetData(i,j).
double VW::Histogram2D::RangeX () const [inline]
Range spanned by Y-axis.
double VW::Histogram2D::RangeY () const [inline]
Range spanned by Y-axis.
void VW::Histogram2D::SetAxes (const std::vector< double > & xvals, const std::vector< double > & yvals)
unsigned int VW::Histogram2D::SizeX () const [inline]
Number of bins in X direction.
Referenced by VW::operator<<().
unsigned int VW::Histogram2D::SizeY () const [inline]
Number of bins in Y direction.
Referenced by VW::operator<<().
double VW::Histogram2D::XTick (unsigned int which) const [inline]
Referenced by VW::operator<<().
double VW::Histogram2D::YTick (unsigned int which) const [inline]
Referenced by VW::operator<<().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & , const Histogram2D &) [friend]
The documentation for this class was generated from the following files:
histogram2d.h
histogram2d.cpp