VW: VNL::LeastSquaresFunction Class Reference
VNL::LeastSquaresFunction Class Reference
Abstract base for minimising functions.
#include <leastsquaresfunction.h>
Public Types
enum UseGradient { no_gradient, use_gradient }
Public Member Functions
LeastSquaresFunction (int number_of_unknowns, int number_of_residuals, UseGradient=use_gradient)
Construct vnl_least_squares_function.
virtual ~LeastSquaresFunction ()
void ThrowFailure ()
void ClearFailure ()
virtual void F (Vector< double > const &x, Vector< double > &fx)=0
The main function.
virtual void GradF (Vector< double > const &x, Matrix< double > &jacobian)
Calculate the Jacobian, given the parameter vector x.
void FDGradF (Vector< double > const &x, Matrix< double > &jacobian, double stepsize)
Use this to compute a finite-difference gradient other than lmdif.
virtual void Trace (int iteration, Vector< double > const &x, Vector< double > const &fx)
Called after each LM iteration to print debugging etc.
double RMS (Vector< double > const &x)
Compute the rms error at x by calling f and returning the norm of the residual vector.
int GetNumberOfUnknowns () const
Return the number of unknowns.
int GetNumberOfResiduals () const
Return the number of residuals.
bool HasGradient () const
Return true if the derived class has indicated that gradf has been implemented.
Public Attributes
bool failure
Protected Member Functions
void _init (int number_of_unknowns, int number_of_residuals)
Protected Attributes
int p_
int n_
bool use_gradient_
std::string print_x_fmt_
std::string print_f_fmt_
Detailed Description
Abstract base for minimising functions.
LeastSquaresFunction is an abstract base for functions to be minimized by an optimizer. To define your own function to be minimized, subclass from LeastSquaresFunction, and implement the pure virtual F (and optionally GradF).
Whether or not f ought to be const is a problem. Clients might well want to cache some information during the call, and if they're compute objects, will almost certainly be writing to members during the computation. For the moment it's non-const, but we'll see...
Member Enumeration Documentation
enum VNL::LeastSquaresFunction::UseGradient
Enumerator:
no_gradient
use_gradient
Constructor & Destructor Documentation
VNL::LeastSquaresFunction::LeastSquaresFunction (int number_of_unknowns, int number_of_residuals, UseGradient g = use_gradient)
Construct vnl_least_squares_function.
Passing number of parameters (unknowns, domain dimension) and number of residuals (range dimension). The optional argument should be no_gradient if the gradf function has not been implemented.
References n_, p_, use_gradient, and use_gradient_.
VNL::LeastSquaresFunction::~LeastSquaresFunction () [virtual]
Member Function Documentation
void VNL::LeastSquaresFunction::_init (int number_of_unknowns, int number_of_residuals) [protected]
References n_, and p_.
void VNL::LeastSquaresFunction::ClearFailure ()
References failure.
Referenced by VNL::LevenbergMarquardt::lmder_lsqfun(), and VNL::LevenbergMarquardt::lmdif_lsqfun().
virtual void VNL::LeastSquaresFunction::F (Vector< double > const & x, Vector< double > & fx) [pure virtual]
The main function.
Given the parameter vector x, compute the vector of residuals fx. Fx has been sized appropriately before the call.
Implemented in VW::FMatrixCompute::LeastSquaresFunctionPoints, VW::FMPlanarCompute::LeastSquaresFunctionPoints, VW::Homography2DCompute::LeastSquaresFunctionPoints, VW::PMatrixCompute::LSFuncPoints, VW::RadialDistortionCompute::LeastSquaresFunction, and VW::ParametricFlowFunc< Type >.
Referenced by VNL::LeastSquaresCostFunction::F(), FDGradF(), VNL::LeastSquaresCostFunction::GradF(), VNL::LevenbergMarquardt::lmder_lsqfun(), VNL::LevenbergMarquardt::lmdif_lsqfun(), RMS(), vnl_discrete_diff_fwd(), and vnl_discrete_diff_sym().
void VNL::LeastSquaresFunction::FDGradF (VNL::Vector< double > const & x, VNL::Matrix< double > & jacobian, double stepsize)
Use this to compute a finite-difference gradient other than lmdif.
Compute fd gradient.
References VNL::Matrix< T >::Columns(), F(), GetNumberOfResiduals(), GetNumberOfUnknowns(), VNL::Matrix< T >::Rows(), and VNL::Vector< T >::size().
int VNL::LeastSquaresFunction::GetNumberOfResiduals () const [inline]
Return the number of residuals.
References n_.
Referenced by VNL::LevenbergMarquardt::_Init(), VNL::LevenbergMarquardt::DiagnoseOutcome(), FDGradF(), VNL::LevenbergMarquardt::lmder_lsqfun(), VNL::LevenbergMarquardt::lmdif_lsqfun(), VNL::LevenbergMarquardt::MinimizeUsingGradient(), VNL::LevenbergMarquardt::MinimizeWithoutGradient(), vnl_discrete_diff_fwd(), vnl_discrete_diff_sym(), and vnl_discrete_diff_test_lsf().
int VNL::LeastSquaresFunction::GetNumberOfUnknowns () const [inline]
Return the number of unknowns.
References p_.
Referenced by VNL::LevenbergMarquardt::_Init(), VW::FMPlanarComputeNonLinear::Compute(), VW::FMatrixComputeNonLinear::Compute(), FDGradF(), VNL::LevenbergMarquardt::lmder_lsqfun(), VNL::LevenbergMarquardt::lmdif_lsqfun(), VNL::LevenbergMarquardt::MinimizeUsingGradient(), VNL::LevenbergMarquardt::MinimizeWithoutGradient(), VW::PMatrixCompute::NonLinearFromPoints(), vnl_discrete_diff_fwd(), vnl_discrete_diff_sym(), and vnl_discrete_diff_test_lsf().
void VNL::LeastSquaresFunction::GradF (VNL::Vector< double > const & x, VNL::Matrix< double > & jacobian) [virtual]
Calculate the Jacobian, given the parameter vector x.
Referenced by VNL::LeastSquaresCostFunction::GradF(), VNL::LevenbergMarquardt::lmder_lsqfun(), and vnl_discrete_diff_test_lsf().
bool VNL::LeastSquaresFunction::HasGradient () const [inline]
Return true if the derived class has indicated that gradf has been implemented.
References use_gradient_.
Referenced by VNL::LeastSquaresCostFunction::GradF(), VNL::LevenbergMarquardt::Minimize(), VNL::LevenbergMarquardt::MinimizeUsingGradient(), and VNL::LevenbergMarquardt::MinimizeWithoutGradient().
double VNL::LeastSquaresFunction::RMS (VNL::Vector< double > const & x)
Compute the rms error at x by calling f and returning the norm of the residual vector.
References F(), n_, and VNL::Vector< T >::RMS().
void VNL::LeastSquaresFunction::ThrowFailure ()
References failure.
void VNL::LeastSquaresFunction::Trace (int iteration, VNL::Vector< double > const & x, VNL::Vector< double > const & fx) [virtual]
Called after each LM iteration to print debugging etc.
Referenced by VNL::LevenbergMarquardt::lmder_lsqfun(), and VNL::LevenbergMarquardt::lmdif_lsqfun().
Member Data Documentation
bool VNL::LeastSquaresFunction::failure
Referenced by ClearFailure(), VNL::LevenbergMarquardt::lmder_lsqfun(), VNL::LevenbergMarquardt::lmdif_lsqfun(), ThrowFailure(), vnl_discrete_diff_fwd(), and vnl_discrete_diff_sym().
int VNL::LeastSquaresFunction::n_ [protected]
Referenced by _init(), GetNumberOfResiduals(), LeastSquaresFunction(), and RMS().
int VNL::LeastSquaresFunction::p_ [protected]
Referenced by _init(), GetNumberOfUnknowns(), and LeastSquaresFunction().
std::string VNL::LeastSquaresFunction::print_f_fmt_ [protected]
std::string VNL::LeastSquaresFunction::print_x_fmt_ [protected]
bool VNL::LeastSquaresFunction::use_gradient_ [protected]
Referenced by HasGradient(), and LeastSquaresFunction().
The documentation for this class was generated from the following files:
leastsquaresfunction.h
leastsquaresfunction.cpp