VW: VW::SequencerBase Class Reference
VW::SequencerBase Class Reference
[Sequencers, CoreSequencers]
The base class from which all sequencers are made.
#include <sequencerbase.h>
Public Member Functions
SequencerBase ()
virtual ~SequencerBase ()
Sequence control functions
virtual void Continuous ()
Start continuous capture from the sequence.
virtual void Stop ()
Stop continuous capture from the sequence.
virtual void Next ()
Capture the next single frame.
Initialisation functions
virtual bool Init ()
All sequencers have an Init(), even if they don't need it, so call init() before using a sequencer (especially if from an interface).
virtual void SetDelay (int d)
Set the delay between frames (only usually used for non-hardware sequencers).
Information functions
bool GetContinuous () const
Is the sequencer running in continuous mode?
int GetDelay () const
What is the delay between frames.
unsigned int GetNumberOfChannels () const
Most sequencers are able to present mutliple images per frame.
unsigned int GetCurrentFrameNumber () const
Return the current frame number.
Image access functions
virtual void * GetBuffer (unsigned int which_channel=0)=0
Take a copy of the grabbed image.
Public Attributes
VWEvents::Event1< void, int > NewFrameEvent
The "new frame has arrived" event.
Protected Member Functions
void _WaitForThread ()
Wait for the thread to exit.
virtual void _FrameArrived ()
we have been signalled that a frame has arrived and we are now "inside" the signalling object, so invoke the appropriate callback
void * Main (void *)
void _CheckInitialised ()
virtual bool _Step ()=0
Protected Attributes
int delay
unsigned int frame_number
bool cont
bool thread_running
bool _initialised
ThreadType parent
unsigned int number_of_channels
Mutex access_lock
bool user_finished
Private Member Functions
operator ThreadType * ()
int Detach ()
int Start (void *arg=0)
Static Private Member Functions
static FuncRetType _CallMain (void *obj)
Private Attributes
ThreadType _thread
void * _arg
Detailed Description
The base class from which all sequencers are made.
Author:
ID Reid, BJ Tordoff
Date:
02/08/2002 All sequencers must provide a mechanism for moving on a single frame, continuously getting frames and stopping. A frame may consist of several channels, but the frame is not presented to the user until all channels have provided an image (ie. until the slowest device responds). When a new frame is ready the NewFrameEvent signal is emitted and the user can retrieve images using the CopyImage function that all sequencers provide.
For many reasons (mainly hardware related) it is usually only possible to instantiate a single sequencer. Nothing in this base class prevents it, but bad stuff will probably happen.
NB: You *must* call the Init() function of a sequencer before use.
Constructor & Destructor Documentation
SequencerBase::SequencerBase ()
virtual VW::SequencerBase::~SequencerBase () [inline, virtual]
Member Function Documentation
void VW::SequencerBase::_CheckInitialised () [protected]
References _initialised.
Referenced by Continuous(), Next(), and Stop().
void SequencerBase::_FrameArrived () [protected, virtual]
we have been signalled that a frame has arrived and we are now "inside" the signalling object, so invoke the appropriate callback
Reimplemented in VW::SequencerFileGTK, VW::SequencerFirewireGTK, VW::SequencerFileWx, VW::SequencerFirewireWx, and VW::SequencerMeteor.
References NewFrameEvent, user_finished, and VERBOSE.
Referenced by Main(), and Next().
virtual bool VW::SequencerBase::_Step () [protected, pure virtual]
Implemented in VW::SequencerFile, VW::SequencerMovie, and VW::SequencerFirewire.
Referenced by Main(), and Next().
void SequencerBase::_WaitForThread () [inline, protected]
Wait for the thread to exit.
References access_lock, VW::Mutex::Lock(), msleep(), thread_running, VW::Mutex::Unlock(), and VERBOSE.
Referenced by Stop().
void SequencerBase::Continuous () [virtual]
Start continuous capture from the sequence.
Reimplemented in VW::SequencerFileGTK, VW::SequencerFirewireGTK, VW::SequencerMovieGTK, VW::SequencerFileWx, VW::SequencerFirewireWx, and VW::SequencerMeteor.
References _CheckInitialised(), access_lock, cont, VW::Mutex::Lock(), VW::Thread::Start(), and VW::Mutex::Unlock().
Referenced by VW::SequencerFirewireGlute::_ContClicked(), VW::SequencerFileGlute::_ContClicked(), VW::SequencerFirewireGlow::OnMessage(), and VW::SequencerFileGlow::OnMessage().
virtual void* VW::SequencerBase::GetBuffer (unsigned int which_channel = 0) [pure virtual]
Take a copy of the grabbed image.
Get a pointer to the raw buffer.
Implemented in VW::SequencerFile, VW::SequencerMovie, VW::SequencerFirewire, and VW::SequencerMeteor.
bool VW::SequencerBase::GetContinuous () const [inline]
Is the sequencer running in continuous mode?
References cont.
unsigned int VW::SequencerBase::GetCurrentFrameNumber () const [inline]
Return the current frame number.
In the case of movies or files this is the frame number with respect to the start frame (ie, 1=start frame) and won't correspond to the sequence frame numbers if started part way through a sequence.
References frame_number.
int VW::SequencerBase::GetDelay () const [inline]
What is the delay between frames.
References delay.
unsigned int VW::SequencerBase::GetNumberOfChannels () const [inline]
Most sequencers are able to present mutliple images per frame.
References number_of_channels.
Referenced by VW::SequencerMovieGTKWidget::InitForm(), and VW::SequencerFileGTKWidget::InitForm().
bool SequencerBase::Init () [virtual]
All sequencers have an Init(), even if they don't need it, so call init() before using a sequencer (especially if from an interface).
Reimplemented in VW::SequencerFile, VW::SequencerFileGTK, VW::SequencerFirewireGTK, VW::SequencerMovieGTK, VW::SequencerFileWx, VW::SequencerFirewireWx, VW::SequencerFirewire, and VW::SequencerMeteor.
References _initialised.
void * SequencerBase::Main (void *) [protected, virtual]
Implements VW::Thread.
References _FrameArrived(), _Step(), access_lock, cont, delay, frame_number, VW::Mutex::Lock(), msleep(), thread_running, VW::Mutex::Unlock(), and VERBOSE.
void SequencerBase::Next () [virtual]
Capture the next single frame.
Reimplemented in VW::SequencerFileGTK, VW::SequencerFirewireGTK, VW::SequencerMovieGTK, VW::SequencerFileWx, VW::SequencerFirewireWx, and VW::SequencerMeteor.
References _CheckInitialised(), _FrameArrived(), _Step(), access_lock, cont, VW::Mutex::Lock(), Stop(), and VW::Mutex::Unlock().
Referenced by VW::SequencerFirewireGlute::_NextClicked(), VW::SequencerFileGlute::_NextClicked(), VW::SequencerFirewireGlow::OnMessage(), and VW::SequencerFileGlow::OnMessage().
void VW::SequencerBase::SetDelay (int d) [inline, virtual]
Set the delay between frames (only usually used for non-hardware sequencers).
This is the time (in milliseconds) for which the sequencer sleeps between frames: the total frame period will be this plus the time taken to acquire the new frame. By default the delay is set to 1ms (zero or less is not a valid setting).
References delay.
void SequencerBase::Stop () [virtual]
Stop continuous capture from the sequence.
Reimplemented in VW::SequencerFileGTK, VW::SequencerFirewireGTK, VW::SequencerMovieGTK, VW::SequencerFileWx, VW::SequencerFirewireWx, VW::SequencerFirewire, and VW::SequencerMeteor.
References _CheckInitialised(), _WaitForThread(), access_lock, cont, VW::Thread::Detach(), VW::Mutex::Lock(), VW::Mutex::Unlock(), and VERBOSE.
Referenced by VW::SequencerMovie::_Step(), VW::SequencerFile::_Step(), VW::SequencerFileGlute::_StopClicked(), Next(), and VW::SequencerFileGlow::OnMessage().
Member Data Documentation
bool VW::SequencerBase::_initialised [protected]
Referenced by _CheckInitialised(), and Init().
Mutex VW::SequencerBase::access_lock [protected]
Referenced by VW::SequencerFile::_Step(), _WaitForThread(), Continuous(), Main(), Next(), VW::SequencerFile::Rewind(), VW::SequencerFile::Skip(), and Stop().
bool VW::SequencerBase::cont [protected]
Referenced by VW::SequencerMovie::_Step(), VW::SequencerFirewire::_Step(), VW::SequencerFile::_Step(), Continuous(), GetContinuous(), Main(), Next(), Stop(), VW::SequencerMovieGTK::UpdateForm(), VW::SequencerFirewireWx::UpdateForm(), VW::SequencerFileWx::UpdateForm(), and VW::SequencerFileGTK::UpdateForm().
int VW::SequencerBase::delay [protected]
Referenced by GetDelay(), Main(), and SetDelay().
unsigned int VW::SequencerBase::frame_number [protected]
Referenced by VW::SequencerFile::_InitialiseFiles(), VW::SequencerMovie::_Step(), VW::SequencerFile::_Step(), GetCurrentFrameNumber(), Main(), VW::SequencerMovie::Rewind(), VW::SequencerFile::Rewind(), VW::SequencerFile::SequencerFile(), VW::SequencerFile::Skip(), VW::SequencerFileWx::UpdateForm(), and VW::SequencerFileGTK::UpdateForm().
VWEvents::Event1<void,int> VW::SequencerBase::NewFrameEvent
The "new frame has arrived" event.
Attach a function to this callback signal if you want to perform an operation each time a new image arrives. This is typically done using my_sequencer.NewFrameEvent.connect(&MyFunction); where 'MyFunction' must take an integer argument and return void.
Referenced by VW::SequencerMeteor::_FrameArrived(), VW::SequencerFirewireWx::_FrameArrived(), VW::SequencerFirewireGTK::_FrameArrived(), VW::SequencerFileWx::_FrameArrived(), VW::SequencerFileGTK::_FrameArrived(), and _FrameArrived().
unsigned int VW::SequencerBase::number_of_channels [protected]
Referenced by VW::SequencerFile::_InitialiseFiles(), VW::SequencerMovie::_Step(), VW::SequencerFirewire::_Step(), VW::SequencerFile::_Step(), VW::SequencerFile::CopyImage(), VW::SequencerFirewire::GetCamera(), VW::SequencerFirewire::GetNumberOfCameras(), GetNumberOfChannels(), VW::SequencerMeteor::Init(), VW::SequencerFirewire::ProbeForCameras(), VW::SequencerMovie::Rewind(), VW::SequencerFile::Rewind(), VW::SequencerFile::SequencerFile(), VW::SequencerFirewire::SequencerFirewire(), VW::SequencerMovie::SequencerMovie(), VW::SequencerFirewire::SetDefaultCameraSettings(), VW::SequencerFile::Skip(), VW::SequencerFirewire::StartDMA(), VW::SequencerFirewire::StartISO(), VW::SequencerFirewire::StopDMA(), VW::SequencerFirewire::StopISO(), VW::SequencerMovieGTK::UpdateForm(), VW::SequencerFileWx::UpdateForm(), VW::SequencerFileGTK::UpdateForm(), VW::SequencerMovieGTK::UpdateFromForm(), and VW::SequencerFileGTK::UpdateFromForm().
ThreadType VW::SequencerBase::parent [protected]
bool VW::SequencerBase::thread_running [protected]
Referenced by VW::SequencerFirewire::_Step(), _WaitForThread(), and Main().
bool VW::SequencerBase::user_finished [protected]
Referenced by VW::SequencerFirewireWx::_FrameArrived(), VW::SequencerFirewireGTK::_FrameArrived(), VW::SequencerFileWx::_FrameArrived(), VW::SequencerFileGTK::_FrameArrived(), and _FrameArrived().
The documentation for this class was generated from the following files:
sequencerbase.h
sequencerbase.cpp