VW: VW::Subsample Class Reference
VW::Subsample Class Reference
[ImageProcessing]
Subsample an image by an integer factor.
#include <subsample.h>
Public Member Functions
Subsample (int f=2)
template<class ImType >
Subsample (ImType &im, int f=2)
Subsample an image by the factor $f$ in-place.
template<class ImType >
Subsample (const ImType &im, ImType &result, int f=2)
Subsample an image by the factor $f$ storing the result.
template<class ImType >
void Compute (ImType &im)
template<class ImType >
void Compute (const ImType &im, ImType &result)
operator bool ()
void SetFactor (int f)
Detailed Description
Subsample an image by an integer factor.
Author:
ID Reid and BJ Tordoff
Date:
02/08/2002
Constructor & Destructor Documentation
VW::Subsample::Subsample (int f = 2) [inline]
template<class ImType > VW::Subsample::Subsample (ImType & im, int f = 2) [inline]
Subsample an image by the factor $f$ in-place.
References Compute().
template<class ImType > VW::Subsample::Subsample (const ImType & im, ImType & result, int f = 2) [inline]
Subsample an image by the factor $f$ storing the result.
References Compute().
Member Function Documentation
template<class ImType > void VW::Subsample::Compute (const ImType & im, ImType & result) [inline]
References c.
template<class ImType > void VW::Subsample::Compute (ImType & im) [inline]
Referenced by Subsample().
VW::Subsample::operator bool () [inline]
void VW::Subsample::SetFactor (int f) [inline]
The documentation for this class was generated from the following files:
subsample.h
subsample.cpp