VW: VW::FMatrixAffineComputeLinear Class Reference
VW::FMatrixAffineComputeLinear Class Reference
[GeometricAlgorithms]
FMatrixAffineComputeLinear.
#include <fmaffinecomputelinear.h>
Public Member Functions
FMatrixAffineComputeLinear (const bool normalise=true)
Create a linear computation object.
bool Compute (VW::FMatrixAffine &result, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1)
Compute an affine fundamental matrix from two lists of 2D point features.
bool Compute (VW::FMatrixAffine &result, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const std::vector< unsigned int > &which_features)
Compute an affine fundamental matrix from two lists of 2D point features.
bool ComputeWeighted (VW::FMatrixAffine &result, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const std::vector< double > &weights)
Compute an affine fundamental matrix from two lists of 2D point features, weighting the contribution of the features.
bool Compute (VW::FMatrixAffine &result, VW::FMatrixAffineCovariance &covar, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const double noise0, const double noise1)
Compute a homography and its covariance from two lists of 2D point features.
bool Compute (VW::FMatrixAffine &result, VW::FMatrixAffineCovariance &covar, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const double noise0, const double noise1, const std::vector< unsigned int > &which_features)
Compute a homography and its covariance from selected entries of two lists of 2D point features.
Detailed Description
FMatrixAffineComputeLinear.
Author:
BJ Tordoff
Date:
08/04/2005 linear algorithm for affine FMatrices.
Constructor & Destructor Documentation
VW::FMatrixAffineComputeLinear::FMatrixAffineComputeLinear (const bool normalise = true) [inline]
Create a linear computation object.
Note that the calculation can involve a normalisation, so it is not necessary to pre-normalise the input points/lines (although it doesn't hurt).
Member Function Documentation
bool VW::FMatrixAffineComputeLinear::Compute (VW::FMatrixAffine & result, VW::FMatrixAffineCovariance & covar, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const double noise0, const double noise1, const std::vector< unsigned int > & which_features)
Compute a homography and its covariance from selected entries of two lists of 2D point features.
References VW::EssentialMatrixCompute::AddToDesignMatrix(), VW::Normalisation::GetScale(), VW::Normalisation::Init(), VW::EssentialMatrixCompute::MakeSymmetric(), VW::Normalisation::Normalise(), VW::FMatrixAffineCompute::RecoverF(), VNL::Matrix< T >::Transpose(), VW::EssentialMatrixCompute::Unnormalise(), and VERBOSE.
bool VW::FMatrixAffineComputeLinear::Compute (VW::FMatrixAffine & result, VW::FMatrixAffineCovariance & covar, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const double noise0, const double noise1)
Compute a homography and its covariance from two lists of 2D point features.
References VW::EssentialMatrixCompute::AddToDesignMatrix(), VW::Normalisation::GetScale(), VW::Normalisation::Init(), VW::EssentialMatrixCompute::MakeSymmetric(), VW::Normalisation::Normalise(), VW::FMatrixAffineCompute::RecoverF(), VNL::Matrix< T >::Transpose(), VW::EssentialMatrixCompute::Unnormalise(), and VERBOSE.
bool VW::FMatrixAffineComputeLinear::Compute (VW::FMatrixAffine & result, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const std::vector< unsigned int > & which_features)
Compute an affine fundamental matrix from two lists of 2D point features.
Note that x0, x1 are defined such that x_1' F x_0 = 0
Parameters:
which_features a list of the indices of feature-pairs to use
References VW::EssentialMatrixCompute::AddToDesignMatrix(), VW::Normalisation::Init(), VW::EssentialMatrixCompute::MakeSymmetric(), VW::Normalisation::Normalise(), and VW::FMatrixAffineCompute::RecoverF().
bool VW::FMatrixAffineComputeLinear::Compute (VW::FMatrixAffine & result, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1)
Compute an affine fundamental matrix from two lists of 2D point features.
Note that x0, x1 are defined such that x_1' F x_0 = 0
References VW::EssentialMatrixCompute::AddToDesignMatrix(), VW::Normalisation::Init(), VW::EssentialMatrixCompute::MakeSymmetric(), VW::Normalisation::Normalise(), VW::FMatrixAffineCompute::RecoverF(), and VERBOSE.
Referenced by VW::FMatrixAffineComputePreemptive::Compute(), VW::FMatrixAffineCompute::GUISACCore(), and VW::FMatrixAffineCompute::MLESACCore().
bool VW::FMatrixAffineComputeLinear::ComputeWeighted (VW::FMatrixAffine & result, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const std::vector< double > & weights)
Compute an affine fundamental matrix from two lists of 2D point features, weighting the contribution of the features.
References VW::EssentialMatrixCompute::AddToDesignMatrix(), VW::Normalisation::Init(), VW::EssentialMatrixCompute::MakeSymmetric(), VW::Normalisation::Normalise(), VW::FMatrixAffineCompute::RecoverF(), and VERBOSE.
Referenced by VW::FMatrixAffineComputePreemptive::Compute(), and VW::FMatrixAffineCompute::GUISACCore().
The documentation for this class was generated from the following files:
fmaffinecomputelinear.h
fmaffinecomputelinear.cpp