VW: VNL::SparseMatrix< T > Class Template Reference
VNL::SparseMatrix< T > Class Template Reference
Simple sparse matrix.
#include <sparsematrix.h>
Public Types
typedef SparseMatrixPair< T > pair_t
typedef std::vector< pair_t > row
typedef std::vector< row > SparseMatrixElements
Public Member Functions
SparseMatrix ()
Construct an empty matrix.
SparseMatrix (unsigned int m, unsigned int n)
Construct an empty m*n matrix.
SparseMatrix (const SparseMatrix< T > &rhs)
Construct an m*n Matrix and copy rhs into it.
SparseMatrix< T > & operator= (const SparseMatrix< T > &rhs)
Copy another SparseMatrix<T> into this.
void mult (SparseMatrix< T > const &rhs, SparseMatrix< T > &result) const
Multiply this*rhs, another sparse matrix.
void mult (Vector< T > const &rhs, Vector< T > &result) const
Multiply this*rhs, where rhs is a vector.
void mult (unsigned int n, unsigned int m, T const *p, T *q) const
Multiply this*p, a fortran order matrix.
void pre_mult (const Vector< T > &lhs, Vector< T > &result) const
Multiplies lhs*this, where lhs is a vector.
void add (const SparseMatrix< T > &rhs, SparseMatrix< T > &result) const
Add rhs to this.
void subtract (const SparseMatrix< T > &rhs, SparseMatrix< T > &result) const
Subtract rhs from this.
T & operator() (unsigned int row, unsigned int column)
Get a reference to an entry in the matrix.
void diag_AtA (Vector< T > &result) const
Get diag(A_tranpose * A).
void set_row (unsigned int r, std::vector< int > const &cols, std::vector< T > const &vals)
Set a whole row at once. Much faster.
row & get_row (unsigned int r)
Return row as vector of pairs.
SparseMatrix< T > & vcat (SparseMatrix< T > const &A)
Laminate matrix A onto the bottom of this one.
unsigned int rows () const
Get the number of rows in the matrix.
unsigned int columns () const
Get the number of columns in the matrix.
unsigned int cols () const
Get the number of columns in the matrix.
bool empty_row (unsigned int r) const
Return whether a given row is empty.
T sum_row (unsigned int r)
This is occasionally useful.
void scale_row (unsigned int r, T scale)
Useful for normalizing row sums in convolution operators.
void resize (int r, int c)
Resizes the array to have r rows and c cols.
void reset ()
Resets the internal iterator.
bool next ()
Moves the internal iterator to next non-zero entry in matrix.
int getrow ()
Returns the row of the entry pointed to by internal iterator.
int getcolumn ()
Returns the column of the entry pointed to by internal iterator.
T value ()
Returns the value pointed to by the internal iterator.
Protected Attributes
SparseMatrixElements elements
unsigned int rs_
unsigned int cs_
unsigned int itr_row
row::iterator itr_cur
bool itr_isreset
Detailed Description
template<class T>
class VNL::SparseMatrix< T >
Simple sparse matrix.
Stores non-zero elements as a sparse_matrix_pair
Member Typedef Documentation
template<class T> typedef SparseMatrixPair<T> VNL::SparseMatrix< T >::pair_t
template<class T> typedef std::vector< pair_t > VNL::SparseMatrix< T >::row
template<class T> typedef std::vector< row > VNL::SparseMatrix< T >::SparseMatrixElements
Constructor & Destructor Documentation
template<class T > VNL::SparseMatrix< T >::SparseMatrix () [inline]
Construct an empty matrix.
template<class T > VNL::SparseMatrix< T >::SparseMatrix (unsigned int m, unsigned int n) [inline]
Construct an empty m*n matrix.
Construct an empty m*n matrix. There are m rows and n columns.
template<class T> VNL::SparseMatrix< T >::SparseMatrix (const SparseMatrix< T > & rhs) [inline]
Construct an m*n Matrix and copy rhs into it.
Member Function Documentation
template<class T> void VNL::SparseMatrix< T >::add (const SparseMatrix< T > & rhs, VNL::SparseMatrix< T > & result) const [inline]
Add rhs to this.
References VNL::SparseMatrix< T >::columns(), VNL::SparseMatrix< T >::cs_, VNL::SparseMatrix< T >::elements, VNL::SparseMatrix< T >::empty_row(), VNL::SparseMatrixPair< T >::first, VNL::SparseMatrix< T >::rows(), VNL::SparseMatrix< T >::rs_, and VNL::SparseMatrixPair< T >::second.
template<class T> unsigned int VNL::SparseMatrix< T >::cols () const [inline]
Get the number of columns in the matrix.
template<class T> unsigned int VNL::SparseMatrix< T >::columns () const [inline]
Get the number of columns in the matrix.
Referenced by VNL::SparseMatrix< T >::add(), VNL::SparseSymmetricEigensystem::CalculateNPairs(), VNL::SparseMatrix< T >::diag_AtA(), VNL::SparseMatrix< T >::mult(), VNL::SparseMatrix< T >::operator()(), VNL::SparseMatrix< T >::pre_mult(), and VNL::SparseMatrix< T >::subtract().
template<class T> void VNL::SparseMatrix< T >::diag_AtA (VNL::Vector< T > & result) const [inline]
Get diag(A_tranpose * A).
Useful for forming Jacobi preconditioners for linear solvers.
References VNL::SparseMatrix< T >::columns(), VNL::SparseMatrix< T >::elements, VNL::Vector< T >::Fill(), VNL::SparseMatrixPair< T >::first, VNL::Vector< T >::Resize(), and VNL::SparseMatrixPair< T >::second.
template<class T> bool VNL::SparseMatrix< T >::empty_row (unsigned int r) const [inline]
Return whether a given row is empty.
Referenced by VNL::SparseMatrix< T >::add(), and VNL::SparseMatrix< T >::subtract().
template<class T> row& VNL::SparseMatrix< T >::get_row (unsigned int r) [inline]
Return row as vector of pairs.
Added to aid binary I/O
template<class T > int VNL::SparseMatrix< T >::getcolumn () [inline]
Returns the column of the entry pointed to by internal iterator.
template<class T > int VNL::SparseMatrix< T >::getrow () [inline]
Returns the row of the entry pointed to by internal iterator.
References VNL::SparseMatrix< T >::itr_row.
template<class T> void VNL::SparseMatrix< T >::mult (unsigned int prows, unsigned int pcols, T const * p, T * q) const [inline]
Multiply this*p, a fortran order matrix.
The matrix p has n rows and m columns, and is in fortran order, ie. columns first.
References VNL::SparseMatrix< T >::columns(), VNL::SparseMatrix< T >::elements, VNL::SparseMatrixPair< T >::first, VNL::SparseMatrix< T >::rows(), and VNL::SparseMatrixPair< T >::second.
template<class T> void VNL::SparseMatrix< T >::mult (VNL::Vector< T > const & rhs, VNL::Vector< T > & result) const [inline]
Multiply this*rhs, where rhs is a vector.
Multiply this*rhs, a vector.
References VNL::SparseMatrix< T >::columns(), VNL::SparseMatrix< T >::elements, VNL::Vector< T >::Fill(), VNL::SparseMatrixPair< T >::first, VNL::Vector< T >::Resize(), VNL::SparseMatrix< T >::rows(), VNL::SparseMatrixPair< T >::second, and VNL::Vector< T >::size().
template<class T> void VNL::SparseMatrix< T >::mult (VNL::SparseMatrix< T > const & rhs, VNL::SparseMatrix< T > & result) const [inline]
Multiply this*rhs, another sparse matrix.
References VNL::SparseMatrix< T >::columns(), VNL::SparseMatrix< T >::cs_, VNL::SparseMatrix< T >::elements, VNL::SparseMatrixPair< T >::first, VNL::SparseMatrix< T >::rows(), VNL::SparseMatrix< T >::rs_, and VNL::SparseMatrixPair< T >::second.
Referenced by VNL::SparseSymmetricEigensystem::CalculateProduct().
template<class T > bool VNL::SparseMatrix< T >::next () [inline]
Moves the internal iterator to next non-zero entry in matrix.
Returns true if there is another value, false otherwise. Use in combination with methods reset, getrow, getcolumn, and value.
References VNL::SparseMatrix< T >::elements, VNL::SparseMatrix< T >::itr_cur, VNL::SparseMatrix< T >::itr_isreset, VNL::SparseMatrix< T >::itr_row, and VNL::SparseMatrix< T >::rows().
template<class T > T & VNL::SparseMatrix< T >::operator() (unsigned int row, unsigned int column) [inline]
Get a reference to an entry in the matrix.
References VNL::SparseMatrix< T >::columns(), VNL::SparseMatrix< T >::elements, and VNL::SparseMatrix< T >::rows().
template<class T> VNL::SparseMatrix< T > & VNL::SparseMatrix< T >::operator= (const SparseMatrix< T > & rhs) [inline]
Copy another SparseMatrix<T> into this.
Copy another VNL::SparseMatrix<T> into this.
References VNL::SparseMatrix< T >::cs_, VNL::SparseMatrix< T >::elements, and VNL::SparseMatrix< T >::rs_.
template<class T> void VNL::SparseMatrix< T >::pre_mult (const Vector< T > & lhs, VNL::Vector< T > & result) const [inline]
Multiplies lhs*this, where lhs is a vector.
Multiply lhs*this, where lhs is a vector.
References VNL::SparseMatrix< T >::columns(), VNL::SparseMatrix< T >::elements, VNL::Vector< T >::Fill(), VNL::SparseMatrixPair< T >::first, VNL::Vector< T >::Resize(), VNL::SparseMatrix< T >::rows(), VNL::SparseMatrixPair< T >::second, and VNL::Vector< T >::size().
template<class T > void VNL::SparseMatrix< T >::reset () [inline]
Resets the internal iterator.
References VNL::SparseMatrix< T >::itr_isreset, and VNL::SparseMatrix< T >::itr_row.
template<class T > void VNL::SparseMatrix< T >::resize (int r, int c) [inline]
Resizes the array to have r rows and c cols.
Resizes the matrix so that it has r rows and c columns.
Currently not implemented.
template<class T> unsigned int VNL::SparseMatrix< T >::rows () const [inline]
Get the number of rows in the matrix.
Referenced by VNL::SparseMatrix< T >::add(), VNL::SparseMatrix< T >::mult(), VNL::SparseMatrix< T >::next(), VNL::SparseMatrix< T >::operator()(), VNL::SparseMatrix< T >::pre_mult(), VNL::SparseMatrix< T >::scale_row(), VNL::SparseMatrix< T >::set_row(), VNL::SparseMatrix< T >::subtract(), and VNL::SparseMatrix< T >::sum_row().
template<class T> void VNL::SparseMatrix< T >::scale_row (unsigned int r, T scale) [inline]
Useful for normalizing row sums in convolution operators.
References VNL::SparseMatrix< T >::elements, and VNL::SparseMatrix< T >::rows().
template<class T> void VNL::SparseMatrix< T >::set_row (unsigned int r, std::vector< int > const & cols, std::vector< T > const & vals) [inline]
Set a whole row at once. Much faster.
Set row in the matrix.
References VNL::SparseMatrix< T >::elements, and VNL::SparseMatrix< T >::rows().
template<class T> void VNL::SparseMatrix< T >::subtract (const SparseMatrix< T > & rhs, VNL::SparseMatrix< T > & result) const [inline]
Subtract rhs from this.
References VNL::SparseMatrix< T >::columns(), VNL::SparseMatrix< T >::cs_, VNL::SparseMatrix< T >::elements, VNL::SparseMatrix< T >::empty_row(), VNL::SparseMatrixPair< T >::first, VNL::SparseMatrix< T >::rows(), VNL::SparseMatrix< T >::rs_, and VNL::SparseMatrixPair< T >::second.
template<class T > T VNL::SparseMatrix< T >::sum_row (unsigned int r) [inline]
This is occasionally useful.
This is occasionally useful. Sums a row of the matrix efficiently.
References VNL::SparseMatrix< T >::elements, and VNL::SparseMatrix< T >::rows().
template<class T > T VNL::SparseMatrix< T >::value () [inline]
Returns the value pointed to by the internal iterator.
template<class T> VNL::SparseMatrix< T > & VNL::SparseMatrix< T >::vcat (VNL::SparseMatrix< T > const & A) [inline]
Laminate matrix A onto the bottom of this one.
References VNL::SparseMatrix< T >::cs_, VNL::SparseMatrix< T >::elements, and VNL::SparseMatrix< T >::rs_.
Member Data Documentation
template<class T> unsigned int VNL::SparseMatrix< T >::cs_ [protected]
Referenced by VNL::SparseMatrix< T >::add(), VNL::SparseMatrix< double >::cols(), VNL::SparseMatrix< double >::columns(), VNL::SparseMatrix< T >::mult(), VNL::SparseMatrix< T >::operator=(), VNL::SparseMatrix< T >::subtract(), and VNL::SparseMatrix< T >::vcat().
template<class T> SparseMatrixElements VNL::SparseMatrix< T >::elements [protected]
Referenced by VNL::SparseMatrix< T >::add(), VNL::SparseMatrix< T >::diag_AtA(), VNL::SparseMatrix< double >::empty_row(), VNL::SparseMatrix< double >::get_row(), VNL::SparseMatrix< T >::mult(), VNL::SparseMatrix< T >::next(), VNL::SparseMatrix< T >::operator()(), VNL::SparseMatrix< T >::operator=(), VNL::SparseMatrix< T >::pre_mult(), VNL::SparseMatrix< T >::scale_row(), VNL::SparseMatrix< T >::set_row(), VNL::SparseMatrix< T >::subtract(), VNL::SparseMatrix< T >::sum_row(), and VNL::SparseMatrix< T >::vcat().
template<class T> row::iterator VNL::SparseMatrix< T >::itr_cur [protected]
Referenced by VNL::SparseMatrix< T >::next().
template<class T> bool VNL::SparseMatrix< T >::itr_isreset [protected]
Referenced by VNL::SparseMatrix< T >::next(), and VNL::SparseMatrix< T >::reset().
template<class T> unsigned int VNL::SparseMatrix< T >::itr_row [protected]
Referenced by VNL::SparseMatrix< T >::getrow(), VNL::SparseMatrix< T >::next(), and VNL::SparseMatrix< T >::reset().
template<class T> unsigned int VNL::SparseMatrix< T >::rs_ [protected]
Referenced by VNL::SparseMatrix< T >::add(), VNL::SparseMatrix< T >::mult(), VNL::SparseMatrix< T >::operator=(), VNL::SparseMatrix< double >::rows(), VNL::SparseMatrix< T >::subtract(), and VNL::SparseMatrix< T >::vcat().
The documentation for this class was generated from the following files:
sparsematrix.h
sparsematrix.tpp