VW: VNL::RealPolynomial Class Reference
VNL::RealPolynomial Class Reference
Evaluation of real polynomials at real and complex points.
#include <realpolynomial.h>
Public Member Functions
RealPolynomial (VNL::Vector< double > const &a)
Initialize polynomial.
RealPolynomial (double const *a, int len)
Initialize polynomial from C vector.
RealPolynomial (double a)
Initialize polynomial from double.
RealPolynomial (int d)
Initialize polynomial of a given degree.
bool operator== (RealPolynomial const &p)
double Evaluate (double x) const
Evaluate polynomial at value x.
double EvaluateIntegral (double x) const
Evaluate integral at x (assuming constant of integration is zero).
double EvaluateIntegral (double x1, double x2) const
Evaluate integral between x1 and x2.
double Devaluate (double x) const
Evaluate derivative at value x.
std::complex< double > Evaluate (std::complex< double > const &x) const
Evaluate polynomial at complex value x.
std::complex< double > Devaluate (std::complex< double > const &x) const
Evaluate derivative at complex value x.
RealPolynomial Derivative () const
Return derivative of this polynomial.
RealPolynomial Primitive () const
Return primitive function (inverse derivative) of this polynomial.
int Degree () const
Return the degree (highest power of x) of the polynomial.
double & operator[] (int i)
Access to the polynomial coefficients.
double operator[] (int i) const
Access to the polynomial coefficients.
const VNL::Vector< double > & Coefficients () const
Return the vector of coefficients.
VNL::Vector< double > & Coefficients ()
Return the vector of coefficients.
void SetCoefficients (VNL::Vector< double > const &coeffs)
void Print (std::ostream &os) const
Print this polynomial to stream.
Protected Attributes
VNL::Vector< double > coeffs_
The coefficients of the polynomial.
Detailed Description
Evaluation of real polynomials at real and complex points.
vnl_real_polynomial represents a univariate polynomial with real coefficients, stored as a vector of doubles. This allows evaluation of the polynomial at given values of , or of its derivative .
Roots may be extracted using the roots() method.
Constructor & Destructor Documentation
VNL::RealPolynomial::RealPolynomial (VNL::Vector< double > const & a) [inline]
Initialize polynomial.
The polynomial is .
Referenced by Derivative(), and Primitive().
VNL::RealPolynomial::RealPolynomial (double const * a, int len) [inline]
Initialize polynomial from C vector.
The parameter len is the number of coefficients, one greater than the degree.
VNL::RealPolynomial::RealPolynomial (double a) [inline]
Initialize polynomial from double.
Useful when adding or multiplying a polynomial and a number.
References coeffs_.
VNL::RealPolynomial::RealPolynomial (int d) [inline]
Initialize polynomial of a given degree.
Member Function Documentation
VNL::Vector<double>& VNL::RealPolynomial::Coefficients () [inline]
Return the vector of coefficients.
References coeffs_.
const VNL::Vector<double>& VNL::RealPolynomial::Coefficients () const [inline]
Return the vector of coefficients.
References coeffs_.
Referenced by Derivative(), VNL::operator*(), operator==(), Primitive(), and VNL::RPolyRoots::RPolyRoots().
int VNL::RealPolynomial::Degree () const [inline]
Return the degree (highest power of x) of the polynomial.
References coeffs_, and VNL::Vector< T >::size().
Referenced by Derivative(), VNL::operator*(), VNL::operator+(), VNL::operator-(), Primitive(), and Print().
VNL::RealPolynomial VNL::RealPolynomial::Derivative () const
Return derivative of this polynomial.
References c, Coefficients(), Degree(), and RealPolynomial().
Referenced by Devaluate().
std::complex< double > VNL::RealPolynomial::Devaluate (std::complex< double > const & x) const
Evaluate derivative at complex value x.
Evaluate derivative at complex value x. Not implemented.
References Derivative(), and Evaluate().
double VNL::RealPolynomial::Devaluate (double x) const
Evaluate derivative at value x.
References Derivative(), and Evaluate().
std::complex< double > VNL::RealPolynomial::Evaluate (std::complex< double > const & x) const
Evaluate polynomial at complex value x.
References coeffs_, VNL::Vector< T >::DataBlock(), and VNL::Vector< T >::size().
double VNL::RealPolynomial::Evaluate (double x) const
Evaluate polynomial at value x.
References coeffs_, VNL::Vector< T >::DataBlock(), and VNL::Vector< T >::size().
Referenced by Devaluate().
double VNL::RealPolynomial::EvaluateIntegral (double x1, double x2) const
Evaluate integral between x1 and x2.
References EvaluateIntegral().
double VNL::RealPolynomial::EvaluateIntegral (double x) const
Evaluate integral at x (assuming constant of integration is zero).
References coeffs_, VNL::Vector< T >::DataBlock(), and VNL::Vector< T >::size().
Referenced by EvaluateIntegral(), and VNL::RMSDifference().
bool VNL::RealPolynomial::operator== (RealPolynomial const & p) [inline]
References Coefficients(), and coeffs_.
double VNL::RealPolynomial::operator[] (int i) const [inline]
Access to the polynomial coefficients.
References coeffs_.
double& VNL::RealPolynomial::operator[] (int i) [inline]
Access to the polynomial coefficients.
References coeffs_.
VNL::RealPolynomial VNL::RealPolynomial::Primitive () const
Return primitive function (inverse derivative) of this polynomial.
Since a primitive function is not unique, the one with constant = 0 is returned
References c, Coefficients(), Degree(), and RealPolynomial().
void VNL::RealPolynomial::Print (std::ostream & os) const
Print this polynomial to stream.
References coeffs_, and Degree().
void VNL::RealPolynomial::SetCoefficients (VNL::Vector< double > const & coeffs) [inline]
References coeffs_.
Member Data Documentation
VNL::Vector<double> VNL::RealPolynomial::coeffs_ [protected]
The coefficients of the polynomial.
coeffs_[0] is the const term. coeffs_[n] is the coefficient of the x^n term.
Referenced by Coefficients(), Degree(), Evaluate(), EvaluateIntegral(), operator==(), operator[](), Print(), RealPolynomial(), and SetCoefficients().
The documentation for this class was generated from the following files:
realpolynomial.h
realpolynomial.cpp