VW: VW::FirewireCameraGTK Class Reference
VW::FirewireCameraGTK Class Reference
[UserInterface]
The main firewire-camera interface class.
#include <firewirecameragtk.h>
Public Member Functions
FirewireCameraGTK (VW::InterfaceType t=VW::INTERFACE_AS_BUTTONWINDOW, bool verbosity=false)
~FirewireCameraGTK (void)
virtual bool SetUpCamera (raw1394handle_t port_handle)
void UseAutoSettings ()
void UseManualSettings ()
virtual void SetZoom (int new_zoom)
virtual void SetFocus (int new_focus)
virtual void SetAutoFocus (bool new_state)
virtual void SetIris (int new_iris)
virtual void SetAutoIris (bool new_state)
virtual void SetBrightness (int new_brightness)
virtual void SetAutoBrightness (bool new_state)
virtual void SetGain (int new_gain)
virtual void SetAutoGain (bool new_state)
virtual void SetExposure (int new_exposure)
virtual void SetAutoExposure (bool new_state)
virtual void SetShutter (int new_shutter)
virtual void SetAutoShutter (bool new_state)
virtual void SetGamma (int new_gamma)
virtual void SetAutoGamma (bool new_state)
virtual void SetSharpness (int new_sharpness)
virtual void SetAutoSharpness (bool new_state)
virtual void SetHue (int new_hue)
virtual void SetAutoHue (bool new_state)
virtual void SetSaturation (int new_saturation)
virtual void SetAutoSaturation (bool new_state)
virtual void SetWhiteBalance (int new_U, int new_V)
virtual void SetAutoWhiteBalance (bool new_state)
void LoadParameterFile (std::string paramfile=".param")
void SaveParameterFile (std::string paramfile=".param")
void Show (void)
void Hide (void)
void Quit (void)
VW::InterfaceType GetType (void)
void SetVerbosity (bool display_messages)
bool StartISOTransmission ()
bool StopISOTransmission ()
bool IsISOTransmitting () const
bool SetupDMACapture (dc1394_cameracapture *capture)
bool ReleaseDMACapture (dc1394_cameracapture *capture)
void SetNodeNumber (nodeid_t nn)
nodeid_t GetNodeNumber (void) const
int GetISOChannel (void) const
void SetFirewireCommandHandle (raw1394handle_t command_handle)
Set the Raw1394 handle for sending commands.
void SetFirewireReceiveHandle (raw1394handle_t receive_handle)
Set the Raw1394 handle for receiving images.
raw1394handle_t GetFirewireCommandHandle (void) const
Get the Raw1394 handle for sending commands.
raw1394handle_t GetFirewireReceiveHandle (void) const
Get the Raw1394 handle for receiving images.
std::string GetGUID () const
Get the Global Unique Identifier (GUID) that uniquely specifies this device.
std::string GetVendorString (void) const
std::string GetModelString (void) const
FirewireParams::CameraMode GetImageMode () const
void SetImageMode (FirewireParams::CameraMode new_mode)
int GetImageWidth () const
int GetImageHeight () const
FirewireParams::CameraFramerate GetFramerate (void) const
void SetFramerate (FirewireParams::CameraFramerate new_framerate)
FirewireParams::CameraImageFormat GetImageFormat (void) const
void SetImageFormat (FirewireParams::CameraImageFormat new_image_format)
bool HasZoom () const
bool HasFocus () const
bool HasAutoFocus () const
bool HasIris () const
bool HasAutoIris () const
bool HasBrightness () const
bool HasAutoBrightness () const
bool HasGain () const
bool HasAutoGain () const
bool HasExposure () const
bool HasAutoExposure () const
bool HasShutter () const
bool HasAutoShutter () const
bool HasGamma () const
bool HasAutoGamma () const
bool HasSharpness () const
bool HasAutoSharpness () const
bool HasHue () const
bool HasAutoHue () const
bool HasSaturation () const
bool HasAutoSaturation () const
bool HasWhiteBalance () const
bool HasAutoWhiteBalance () const
int GetZoom () const
void GetZoomLimits (int *min_zoom, int *max_zoom) const
int GetFocus () const
void GetFocusLimits (int *min_focus, int *max_focus) const
bool GetAutoFocus () const
int GetIris () const
void GetIrisLimits (int *min_iris, int *max_iris) const
bool GetAutoIris () const
int GetBrightness () const
void GetBrightnessLimits (int *min_gain, int *max_gain) const
bool GetAutoBrightness () const
int GetGain () const
void GetGainLimits (int *min_gain, int *max_gain) const
bool GetAutoGain () const
int GetExposure () const
void GetExposureLimits (int *min_exposure, int *max_exposure) const
bool GetAutoExposure () const
int GetShutter () const
void GetShutterLimits (int *min_shutter, int *max_shutter) const
bool GetAutoShutter () const
int GetGamma () const
void GetGammaLimits (int *min_gamma, int *max_gamma) const
bool GetAutoGamma () const
int GetSharpness () const
void GetSharpnessLimits (int *min_sharpness, int *max_sharpness) const
bool GetAutoSharpness () const
int GetHue () const
void GetHueLimits (int *min_hue, int *max_hue) const
bool GetAutoHue () const
int GetSaturation () const
void GetSaturationLimits (int *min_saturation, int *max_saturation) const
bool GetAutoSaturation () const
int GetWhiteBalanceU () const
int GetWhiteBalanceV () const
void GetWhiteBalanceULimits (int *min_wbu, int *max_wbu) const
void GetWhiteBalanceVLimits (int *min_wbv, int *max_wbv) const
bool GetAutoWhiteBalance () const
bool SwitchOn (void)
bool SwitchOff (void)
void UpdateFeatureByName (const std::string &name, bool automatic, int value, int value2=0)
int GetHistoricPosition (struct timeval time, double *zoom)
void GetOdometryHistory (std::vector< timeval > &time, std::vector< double > &zoom_history)
void FlushHistory (void)
virtual bool WriteASCII (std::ostream &stream) const
Stream as plain ASCII.
virtual bool WriteXML (std::ostream &stream, const std::string &name="") const
Stream as XML style ASCII.
virtual bool WriteBinary (std::ostream &stream) const
Stream as binary.
virtual bool ReadASCII (std::istream &stream)
Stream as plain ASCII.
virtual bool ReadXML (std::istream &stream, const std::string &name="")
Stream as XML style ASCII.
virtual bool ReadBinary (std::istream &stream)
Stream as binary.
bool WriteASCIIFile (const std::string &filename) const
Open a file and output as plain ASCII (overwriting any existing contents).
bool WriteXMLFile (const std::string &filename, const std::string &name="") const
Open a file and output as XML-style ASCII (overwriting any existing contents).
bool WriteBinaryFile (const std::string &filename) const
Open a file and output as binary (overwriting any existing contents).
virtual bool ReadASCIIFile (const std::string &filename)
Open a file and input as plain ASCII.
virtual bool ReadXMLFile (const std::string &filename, const std::string &name="")
Open a file and input as XML style ASCII.
virtual bool ReadBinaryFile (const std::string &filename)
Open a file and input as binary.
Protected Member Functions
void CreateForm ()
void PageChange (Gtk::Notebook_Helpers::Page *p0, guint p1)
void ChangeZoom ()
void ChangeFocus ()
void ChangeAutoFocus ()
void ChangeIris ()
void ChangeAutoIris ()
void ChangeBrightness ()
void ChangeAutoBrightness ()
void ChangeGain ()
void ChangeAutoGain ()
void ChangeExposure ()
void ChangeAutoExposure ()
void ChangeShutter ()
void ChangeAutoShutter ()
void ChangeGamma ()
void ChangeAutoGamma ()
void ChangeSharpness ()
void ChangeAutoSharpness ()
void ChangeHue ()
void ChangeAutoHue ()
void ChangeSaturation ()
void ChangeAutoSaturation ()
void ChangeWhiteBalance ()
void ChangeAutoWhiteBalance ()
void LoadStart ()
void LoadOK ()
void SaveStart ()
void SaveOK ()
void FileCancel ()
virtual void InitButtonWindow ()
virtual void InitButtonWindow (unsigned int width, unsigned int height)
virtual void InitWidget ()
void StoreOdometryHistory (struct timeval &time, int zoom)
Protected Attributes
SigC::Signal1< void, std::string > LoadEvent
SigC::Signal1< void, std::string > SaveEvent
FirewireCameraGTKWidget * my_widget
Gtk::Window * my_window
VW::InterfaceType my_type
std::string my_name
Gtk::FileSelection * file_selector
dc1394_camerainfo camera_info
dc1394_feature_set feature_set
dc1394_miscinfo misc_info
bool verbose
int image_width
int image_height
raw1394handle_t receive_handle
int zoom_history [CAMERA_ODOMETRY_HISTORY_LENGTH]
struct timeval time_history [CAMERA_ODOMETRY_HISTORY_LENGTH]
int history_pointer
Friends
class FirewireCameraGTKWidget
Detailed Description
The main firewire-camera interface class.
An interface to a firewire camera, allowing GUI control of any/all available camera parameters (zoom, iris, focus etc).
This interface contains a widget which can either be attached directly to the user window, or attaches a button which pops up the widget.
Author:
BJ Tordoff
Date:
02/08/2002 *** Insert Long Description Here ***
Constructor & Destructor Documentation
VW::FirewireCameraGTK::FirewireCameraGTK (VW::InterfaceType t = VW::INTERFACE_AS_BUTTONWINDOW, bool verbosity = false)
References VW::InterfaceGTK< FirewireCameraGTKWidget >::InitButtonWindow(), VW::InterfaceGTK< FirewireCameraGTKWidget >::InitWidget(), VW::INTERFACE_AS_BUTTONWINDOW, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_name, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_type.
VW::FirewireCameraGTK::~FirewireCameraGTK (void) [inline]
Member Function Documentation
void VW::FirewireCameraGTK::ChangeAutoBrightness () [inline, protected]
References VW::FirewireCameraGTKWidget::autobrightness_button, VW::FirewireCameraGTKWidget::brightness_label, VW::FirewireCameraGTKWidget::brightness_spinner, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetAutoBrightness(), and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeAutoExposure () [inline, protected]
References VW::FirewireCameraGTKWidget::autoexposure_button, VW::FirewireCameraGTKWidget::exposure_label, VW::FirewireCameraGTKWidget::exposure_spinner, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetAutoExposure(), and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeAutoFocus () [inline, protected]
References VW::FirewireCameraGTKWidget::autofocus_button, VW::FirewireCameraGTKWidget::focus_label, VW::FirewireCameraGTKWidget::focus_spinner, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetAutoFocus(), and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeAutoGain () [inline, protected]
References VW::FirewireCameraGTKWidget::autogain_button, VW::FirewireCameraGTKWidget::gain_label, VW::FirewireCameraGTKWidget::gain_spinner, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetAutoGain(), and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeAutoGamma () [inline, protected]
References VW::FirewireCameraGTKWidget::autogamma_button, VW::FirewireCameraGTKWidget::gamma_label, VW::FirewireCameraGTKWidget::gamma_spinner, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetAutoGamma(), and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeAutoHue () [inline, protected]
References VW::FirewireCameraGTKWidget::autohue_button, VW::FirewireCameraGTKWidget::hue_label, VW::FirewireCameraGTKWidget::hue_spinner, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetAutoHue(), and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeAutoIris () [inline, protected]
References VW::FirewireCameraGTKWidget::autoiris_button, VW::FirewireCameraGTKWidget::iris_label, VW::FirewireCameraGTKWidget::iris_spinner, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetAutoIris(), and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeAutoSaturation () [inline, protected]
References VW::FirewireCameraGTKWidget::autosaturation_button, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, VW::FirewireCameraGTKWidget::saturation_label, VW::FirewireCameraGTKWidget::saturation_spinner, SetAutoSaturation(), and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeAutoSharpness () [inline, protected]
References VW::FirewireCameraGTKWidget::autosharpness_button, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetAutoSharpness(), VW::FirewireCameraGTKWidget::sharpness_label, VW::FirewireCameraGTKWidget::sharpness_spinner, and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeAutoShutter () [inline, protected]
References VW::FirewireCameraGTKWidget::autoshutter_button, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetAutoShutter(), VW::FirewireCameraGTKWidget::shutter_label, VW::FirewireCameraGTKWidget::shutter_spinner, and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeAutoWhiteBalance () [inline, protected]
References VW::FirewireCameraGTKWidget::autowhitebalance_button, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetAutoWhiteBalance(), v, VW::FirewireCameraGTKWidget::whitebalance_label, VW::FirewireCameraGTKWidget::whitebalanceU_label, VW::FirewireCameraGTKWidget::whitebalanceU_spinner, VW::FirewireCameraGTKWidget::whitebalanceV_label, and VW::FirewireCameraGTKWidget::whitebalanceV_spinner.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeBrightness () [inline, protected]
References VW::FirewireCameraGTKWidget::brightness_spinner, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetBrightness(), and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeExposure () [inline, protected]
References VW::FirewireCameraGTKWidget::exposure_spinner, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetExposure(), and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeFocus () [inline, protected]
References VW::FirewireCameraGTKWidget::focus_spinner, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetFocus(), and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeGain () [inline, protected]
References VW::FirewireCameraGTKWidget::gain_spinner, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetGain(), and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeGamma () [inline, protected]
References VW::FirewireCameraGTKWidget::gamma_spinner, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetGamma(), and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeHue () [inline, protected]
References VW::FirewireCameraGTKWidget::hue_spinner, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetHue(), and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeIris () [inline, protected]
References VW::FirewireCameraGTKWidget::iris_spinner, VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetIris(), and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeSaturation () [inline, protected]
References VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, VW::FirewireCameraGTKWidget::saturation_spinner, SetSaturation(), and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeSharpness () [inline, protected]
References VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetSharpness(), VW::FirewireCameraGTKWidget::sharpness_spinner, and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeShutter () [inline, protected]
References VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetShutter(), VW::FirewireCameraGTKWidget::shutter_spinner, and v.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeWhiteBalance () [inline, protected]
References VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetWhiteBalance(), v, VW::FirewireCameraGTKWidget::whitebalanceU_spinner, and VW::FirewireCameraGTKWidget::whitebalanceV_spinner.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::ChangeZoom () [inline, protected]
References VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, SetZoom(), v, and VW::FirewireCameraGTKWidget::zoom_spinner.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::CreateForm () [protected]
void VW::InterfaceGTK< FirewireCameraGTKWidget >::FileCancel () [inline, protected, inherited]
void VW::FirewireCamera::FlushHistory (void) [inherited]
References VW::FirewireCamera::GetZoom(), VW::FirewireCamera::history_pointer, VW::FirewireCamera::time_history, and VW::FirewireCamera::zoom_history.
bool VW::FirewireCamera::GetAutoBrightness () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::GetAutoExposure () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::GetAutoFocus () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::GetAutoGain () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::GetAutoGamma () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::GetAutoHue () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::GetAutoIris () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::GetAutoSaturation () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::GetAutoSharpness () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::GetAutoShutter () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::GetAutoWhiteBalance () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCamera::WriteXML().
int VW::FirewireCamera::GetBrightness () const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
void VW::FirewireCamera::GetBrightnessLimits (int * min_gain, int * max_gain) const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
int VW::FirewireCamera::GetExposure () const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
void VW::FirewireCamera::GetExposureLimits (int * min_exposure, int * max_exposure) const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
raw1394handle_t VW::FirewireCamera::GetFirewireCommandHandle (void) const [inline, inherited]
Get the Raw1394 handle for sending commands.
References VW::FirewireCamera::camera_info.
raw1394handle_t VW::FirewireCamera::GetFirewireReceiveHandle (void) const [inline, inherited]
Get the Raw1394 handle for receiving images.
References VW::FirewireCamera::receive_handle.
int VW::FirewireCamera::GetFocus () const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
void VW::FirewireCamera::GetFocusLimits (int * min_focus, int * max_focus) const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
VW::FirewireParams::CameraFramerate VW::FirewireCamera::GetFramerate (void) const [inline, inherited]
References VW::FirewireCamera::misc_info.
Referenced by VW::FirewireCamera::WriteASCII().
int VW::FirewireCamera::GetGain () const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
void VW::FirewireCamera::GetGainLimits (int * min_gain, int * max_gain) const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
int VW::FirewireCamera::GetGamma () const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
void VW::FirewireCamera::GetGammaLimits (int * min_gamma, int * max_gamma) const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
std::string VW::FirewireCamera::GetGUID () const [inline, inherited]
Get the Global Unique Identifier (GUID) that uniquely specifies this device.
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII().
int VW::FirewireCamera::GetHistoricPosition (struct timeval time, double * zoom) [inherited]
References CAMERA_ODOMETRY_HISTORY_LENGTH, VW::FirewireCamera::GetZoom(), VW::FirewireCamera::history_pointer, VW::FirewireCamera::StoreOdometryHistory(), VW::FirewireCamera::time_history, and VW::FirewireCamera::zoom_history.
int VW::FirewireCamera::GetHue () const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
void VW::FirewireCamera::GetHueLimits (int * min_hue, int * max_hue) const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
VW::FirewireParams::CameraImageFormat VW::FirewireCamera::GetImageFormat (void) const [inline, inherited]
References VW::FirewireCamera::misc_info.
int VW::FirewireCamera::GetImageHeight (void) const [inline, inherited]
References VW::FirewireCamera::image_height.
VW::FirewireParams::CameraMode VW::FirewireCamera::GetImageMode () const [inline, inherited]
References VW::FirewireCamera::misc_info.
Referenced by VW::FirewireCamera::WriteASCII().
int VW::FirewireCamera::GetImageWidth (void) const [inline, inherited]
References VW::FirewireCamera::image_width.
int VW::FirewireCamera::GetIris () const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
void VW::FirewireCamera::GetIrisLimits (int * min_iris, int * max_iris) const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
int VW::FirewireCamera::GetISOChannel (void) const [inline, inherited]
References VW::FirewireCamera::misc_info.
Referenced by VW::FirewireCamera::WriteASCII().
std::string VW::FirewireCamera::GetModelString (void) const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII().
nodeid_t VW::FirewireCamera::GetNodeNumber (void) const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII().
void VW::FirewireCamera::GetOdometryHistory (std::vector< timeval > & time, std::vector< double > & zoom_history) [inherited]
int VW::FirewireCamera::GetSaturation () const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
void VW::FirewireCamera::GetSaturationLimits (int * min_saturation, int * max_saturation) const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
int VW::FirewireCamera::GetSharpness () const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
void VW::FirewireCamera::GetSharpnessLimits (int * min_sharpness, int * max_sharpness) const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
int VW::FirewireCamera::GetShutter () const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
void VW::FirewireCamera::GetShutterLimits (int * min_shutter, int * max_shutter) const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
VW::InterfaceType VW::InterfaceGTK< FirewireCameraGTKWidget >::GetType (void) [inline, inherited]
std::string VW::FirewireCamera::GetVendorString (void) const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII().
int VW::FirewireCamera::GetWhiteBalanceU () const [inline, inherited]
References VW::FirewireCamera::camera_info, and v.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
void VW::FirewireCamera::GetWhiteBalanceULimits (int * min_wbu, int * max_wbu) const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
int VW::FirewireCamera::GetWhiteBalanceV () const [inline, inherited]
References VW::FirewireCamera::camera_info, and v.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
void VW::FirewireCamera::GetWhiteBalanceVLimits (int * min_wbv, int * max_wbv) const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
int VW::FirewireCamera::GetZoom () const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::FlushHistory(), VW::FirewireCamera::GetHistoricPosition(), VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
void VW::FirewireCamera::GetZoomLimits (int * min_zoom, int * max_zoom) const [inline, inherited]
References VW::FirewireCamera::camera_info.
Referenced by VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::HasAutoBrightness () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and VW::FirewireCamera::UseAutoSettings().
bool VW::FirewireCamera::HasAutoExposure () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and VW::FirewireCamera::UseAutoSettings().
bool VW::FirewireCamera::HasAutoFocus () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and VW::FirewireCamera::UseAutoSettings().
bool VW::FirewireCamera::HasAutoGain () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and VW::FirewireCamera::UseAutoSettings().
bool VW::FirewireCamera::HasAutoGamma () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and VW::FirewireCamera::UseAutoSettings().
bool VW::FirewireCamera::HasAutoHue () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and VW::FirewireCamera::UseAutoSettings().
bool VW::FirewireCamera::HasAutoIris () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and VW::FirewireCamera::UseAutoSettings().
bool VW::FirewireCamera::HasAutoSaturation () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and VW::FirewireCamera::UseAutoSettings().
bool VW::FirewireCamera::HasAutoSharpness () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and VW::FirewireCamera::UseAutoSettings().
bool VW::FirewireCamera::HasAutoShutter () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and VW::FirewireCamera::UseAutoSettings().
bool VW::FirewireCamera::HasAutoWhiteBalance () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), and VW::FirewireCamera::UseAutoSettings().
bool VW::FirewireCamera::HasBrightness () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::HasExposure () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::HasFocus () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::HasGain () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::HasGamma () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::HasHue () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::HasIris () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::HasSaturation () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::HasSharpness () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::HasShutter () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::HasWhiteBalance () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
bool VW::FirewireCamera::HasZoom () const [inline, inherited]
References VW::FirewireCamera::feature_set.
Referenced by VW::FirewireCameraGTKWidget::InitForm(), VW::FirewireCamera::WriteASCII(), and VW::FirewireCamera::WriteXML().
void VW::InterfaceGTK< FirewireCameraGTKWidget >::Hide (void) [inline, inherited]
virtual void VW::InterfaceGTK< FirewireCameraGTKWidget >::InitButtonWindow (unsigned int width, unsigned int height) [protected, virtual, inherited]
virtual void VW::InterfaceGTK< FirewireCameraGTKWidget >::InitButtonWindow () [protected, virtual, inherited]
Referenced by FirewireCameraGTK().
virtual void VW::InterfaceGTK< FirewireCameraGTKWidget >::InitWidget () [protected, virtual, inherited]
Referenced by FirewireCameraGTK().
bool VW::FirewireCamera::IsISOTransmitting () const [inline, inherited]
References VW::FirewireCamera::misc_info.
void VW::InterfaceGTK< FirewireCameraGTKWidget >::LoadOK () [inline, protected, inherited]
void VW::FirewireCameraGTK::LoadParameterFile (std::string paramfile = ".param") [inline]
References VW::IOObject::ReadXMLFile().
void VW::InterfaceGTK< FirewireCameraGTKWidget >::LoadStart () [inline, protected, inherited]
void VW::FirewireCameraGTK::PageChange (Gtk::Notebook_Helpers::Page * p0, guint p1) [inline, protected]
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::InterfaceGTK< FirewireCameraGTKWidget >::Quit (void) [inline, inherited]
bool VW::FirewireCamera::ReadASCII (std::istream & stream) [virtual, inherited]
Stream as plain ASCII.
Parameters:
stream the input stream to read from
Returns:
true if successfully read, false if there are problems
Implements VW::IOObject.
bool VW::IOObject::ReadASCIIFile (const std::string & filename) [virtual, inherited]
Open a file and input as plain ASCII.
Open a file and read as plain ASCII.
Once the file is open, the child class's ReadASCII function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadASCII().
bool VW::FirewireCamera::ReadBinary (std::istream & stream) [virtual, inherited]
Stream as binary.
Parameters:
stream the input stream to read from
Returns:
true if successfully read, false if there are problems
Implements VW::IOObject.
bool VW::IOObject::ReadBinaryFile (const std::string & filename) [virtual, inherited]
Open a file and input as binary.
Open a file and read as binary.
Once the file is open, the child class's ReadBinary function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadBinary().
bool VW::FirewireCamera::ReadXML (std::istream & stream, const std::string & name = "") [virtual, inherited]
Stream as XML style ASCII.
Parameters:
stream the input stream to read from
name if specified, the found tag must have a NAME= parameter that matches
Returns:
true if successfully read, false if there are problems
Implements VW::IOObject.
References VW::FindXMLBlock(), VW::GetXMLBlock(), and VW::FirewireCamera::UpdateFeatureByName().
bool VW::IOObject::ReadXMLFile (const std::string & filename, const std::string & name = "") [virtual, inherited]
Open a file and input as XML style ASCII.
Open a file and read as XML-style ASCII.
Once the file is open, the child class's ReadXML function is used to read the content.
Parameters:
filename the name of the file to open
name the optional name tag-attribute to match ie. data must start <MyClass name="name">
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadXML().
Referenced by VW::ClassifierUV::ClassifierUV(), and LoadParameterFile().
bool VW::FirewireCamera::ReleaseDMACapture (dc1394_cameracapture * capture) [inherited]
References VW::FirewireCamera::camera_info, VW::FirewireParams::FPS_1_875, VW::FirewireCamera::misc_info, and VW::FirewireCamera::verbose.
void VW::InterfaceGTK< FirewireCameraGTKWidget >::SaveOK () [inline, protected, inherited]
void VW::FirewireCameraGTK::SaveParameterFile (std::string paramfile = ".param") [inline]
References VW::IOObject::WriteXMLFile().
void VW::InterfaceGTK< FirewireCameraGTKWidget >::SaveStart () [inline, protected, inherited]
void VW::FirewireCameraGTK::SetAutoBrightness (bool new_state) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::autobrightness_button, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
Referenced by ChangeAutoBrightness().
void VW::FirewireCameraGTK::SetAutoExposure (bool new_state) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::autoexposure_button, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
Referenced by ChangeAutoExposure().
void VW::FirewireCameraGTK::SetAutoFocus (bool new_state) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::autofocus_button, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
Referenced by ChangeAutoFocus().
void VW::FirewireCameraGTK::SetAutoGain (bool new_state) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::autogain_button, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
Referenced by ChangeAutoGain().
void VW::FirewireCameraGTK::SetAutoGamma (bool new_state) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::autogamma_button, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
Referenced by ChangeAutoGamma().
void VW::FirewireCameraGTK::SetAutoHue (bool new_state) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::autohue_button, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
Referenced by ChangeAutoHue().
void VW::FirewireCameraGTK::SetAutoIris (bool new_state) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::autoiris_button, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
Referenced by ChangeAutoIris().
void VW::FirewireCameraGTK::SetAutoSaturation (bool new_state) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::autosaturation_button, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
Referenced by ChangeAutoSaturation().
void VW::FirewireCameraGTK::SetAutoSharpness (bool new_state) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::autosharpness_button, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
Referenced by ChangeAutoSharpness().
void VW::FirewireCameraGTK::SetAutoShutter (bool new_state) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::autoshutter_button, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
Referenced by ChangeAutoShutter().
void VW::FirewireCameraGTK::SetAutoWhiteBalance (bool new_state) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::autowhitebalance_button, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
Referenced by ChangeAutoWhiteBalance().
void VW::FirewireCameraGTK::SetBrightness (int new_brightness) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::brightness_spinner, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
Referenced by ChangeBrightness().
void VW::FirewireCameraGTK::SetExposure (int new_exposure) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::exposure_spinner, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
Referenced by ChangeExposure().
void VW::FirewireCamera::SetFirewireCommandHandle (raw1394handle_t command_handle) [inline, inherited]
Set the Raw1394 handle for sending commands.
Note that receiveing images and sending commands use different handles to avoid conflicts.
References VW::FirewireCamera::camera_info.
void VW::FirewireCamera::SetFirewireReceiveHandle (raw1394handle_t receive_handle) [inline, inherited]
Set the Raw1394 handle for receiving images.
Note that receiveing images and sending commands use different handles to avoid conflicts.
void VW::FirewireCameraGTK::SetFocus (int new_focus) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::focus_spinner, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
Referenced by ChangeFocus().
void VW::FirewireCamera::SetFramerate (FirewireParams::CameraFramerate new_framerate) [inline, inherited]
References VW::FirewireCamera::camera_info, and VW::FirewireCamera::misc_info.
void VW::FirewireCameraGTK::SetGain (int new_gain) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::gain_spinner, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
Referenced by ChangeGain().
void VW::FirewireCameraGTK::SetGamma (int new_gamma) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::gamma_spinner, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
Referenced by ChangeGamma().
void VW::FirewireCameraGTK::SetHue (int new_hue) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::hue_spinner, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
Referenced by ChangeHue().
void VW::FirewireCamera::SetImageFormat (FirewireParams::CameraImageFormat new_image_format) [inline, inherited]
References VW::FirewireCamera::camera_info, and VW::FirewireCamera::misc_info.
Referenced by VW::FirewireCamera::SetImageMode().
void VW::FirewireCamera::SetImageMode (FirewireParams::CameraMode new_mode) [inherited]
References VW::FirewireCamera::camera_info, VW::FirewireParams::F_VGA_NONCOMPRESSED, VW::FirewireCamera::image_height, VW::FirewireCamera::image_width, VW::FirewireParams::M_160x120_YUV444, VW::FirewireParams::M_320x240_YUV422, VW::FirewireParams::M_640x480_MONO, VW::FirewireParams::M_640x480_RGB, VW::FirewireParams::M_640x480_YUV411, VW::FirewireParams::M_640x480_YUV422, VW::FirewireCamera::misc_info, and VW::FirewireCamera::SetImageFormat().
void VW::FirewireCameraGTK::SetIris (int new_iris) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::iris_spinner, and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
Referenced by ChangeIris().
void VW::FirewireCamera::SetNodeNumber (nodeid_t nn) [inline, inherited]
References VW::FirewireCamera::camera_info.
void VW::FirewireCameraGTK::SetSaturation (int new_saturation) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, and VW::FirewireCameraGTKWidget::saturation_spinner.
Referenced by ChangeSaturation().
void VW::FirewireCameraGTK::SetSharpness (int new_sharpness) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, and VW::FirewireCameraGTKWidget::sharpness_spinner.
Referenced by ChangeSharpness().
void VW::FirewireCameraGTK::SetShutter (int new_shutter) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, and VW::FirewireCameraGTKWidget::shutter_spinner.
Referenced by ChangeShutter().
bool VW::FirewireCameraGTK::SetUpCamera (raw1394handle_t port_handle) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::FirewireCameraGTKWidget::InitForm(), and VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget.
bool VW::FirewireCamera::SetupDMACapture (dc1394_cameracapture * capture) [inherited]
References VW::FirewireCamera::camera_info, FIREWIRE_VIDEO_DEVICE, VW::FirewireParams::FPS_1_875, VW::FirewireCamera::misc_info, NUM_DMA_BUFFERS, and VERBOSE.
void VW::FirewireCamera::SetVerbosity (bool display_messages) [inline, inherited]
References VW::FirewireCamera::verbose.
void VW::FirewireCameraGTK::SetWhiteBalance (int new_U, int new_V) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, VW::FirewireCameraGTKWidget::whitebalanceU_spinner, and VW::FirewireCameraGTKWidget::whitebalanceV_spinner.
Referenced by ChangeWhiteBalance().
void VW::FirewireCameraGTK::SetZoom (int new_zoom) [virtual]
Reimplemented from VW::FirewireCamera.
References VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget, and VW::FirewireCameraGTKWidget::zoom_spinner.
Referenced by ChangeZoom().
void VW::InterfaceGTK< FirewireCameraGTKWidget >::Show (void) [inline, inherited]
bool VW::FirewireCamera::StartISOTransmission (void) [inherited]
References VW::FirewireCamera::camera_info, VW::FirewireCamera::misc_info, VW::FirewireCamera::receive_handle, and VW::FirewireCamera::verbose.
bool VW::FirewireCamera::StopISOTransmission (void) [inherited]
References VW::FirewireCamera::camera_info, VW::FirewireCamera::misc_info, and VW::FirewireCamera::verbose.
void VW::FirewireCamera::StoreOdometryHistory (struct timeval & time, int zoom) [inline, protected, inherited]
References CAMERA_ODOMETRY_HISTORY_LENGTH, VW::FirewireCamera::history_pointer, VW::FirewireCamera::time_history, and VW::FirewireCamera::zoom_history.
Referenced by VW::FirewireCamera::GetHistoricPosition().
bool VW::FirewireCamera::SwitchOff (void) [inline, inherited]
References VW::FirewireCamera::camera_info.
bool VW::FirewireCamera::SwitchOn (void) [inline, inherited]
References VW::FirewireCamera::camera_info.
void VW::FirewireCamera::UpdateFeatureByName (const std::string & name, bool automatic, int value, int value2 = 0) [inherited]
Referenced by VW::FirewireCamera::ReadXML().
void VW::FirewireCameraGTK::UseAutoSettings () [inline]
Reimplemented from VW::FirewireCamera.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
void VW::FirewireCameraGTK::UseManualSettings () [inline]
Reimplemented from VW::FirewireCamera.
Referenced by VW::FirewireCameraGTKWidget::InitForm().
bool VW::FirewireCamera::WriteASCII (std::ostream & stream) const [virtual, inherited]
Stream as plain ASCII.
Parameters:
stream the output stream to write to
Returns:
true if successfully written, false if there are problems
Implements VW::IOObject.
References VW::FirewireParams::FPS_15, VW::FirewireParams::FPS_1_875, VW::FirewireParams::FPS_30, VW::FirewireParams::FPS_3_75, VW::FirewireParams::FPS_60, VW::FirewireParams::FPS_7_5, VW::FirewireCamera::GetBrightness(), VW::FirewireCamera::GetBrightnessLimits(), VW::FirewireCamera::GetExposure(), VW::FirewireCamera::GetExposureLimits(), VW::FirewireCamera::GetFocus(), VW::FirewireCamera::GetFocusLimits(), VW::FirewireCamera::GetFramerate(), VW::FirewireCamera::GetGain(), VW::FirewireCamera::GetGainLimits(), VW::FirewireCamera::GetGamma(), VW::FirewireCamera::GetGammaLimits(), VW::FirewireCamera::GetGUID(), VW::FirewireCamera::GetHue(), VW::FirewireCamera::GetHueLimits(), VW::FirewireCamera::GetImageMode(), VW::FirewireCamera::GetIris(), VW::FirewireCamera::GetIrisLimits(), VW::FirewireCamera::GetISOChannel(), VW::FirewireCamera::GetModelString(), VW::FirewireCamera::GetNodeNumber(), VW::FirewireCamera::GetSaturation(), VW::FirewireCamera::GetSaturationLimits(), VW::FirewireCamera::GetSharpness(), VW::FirewireCamera::GetSharpnessLimits(), VW::FirewireCamera::GetShutter(), VW::FirewireCamera::GetShutterLimits(), VW::FirewireCamera::GetVendorString(), VW::FirewireCamera::GetWhiteBalanceU(), VW::FirewireCamera::GetWhiteBalanceULimits(), VW::FirewireCamera::GetWhiteBalanceV(), VW::FirewireCamera::GetWhiteBalanceVLimits(), VW::FirewireCamera::GetZoom(), VW::FirewireCamera::GetZoomLimits(), VW::FirewireCamera::HasBrightness(), VW::FirewireCamera::HasExposure(), VW::FirewireCamera::HasFocus(), VW::FirewireCamera::HasGain(), VW::FirewireCamera::HasGamma(), VW::FirewireCamera::HasHue(), VW::FirewireCamera::HasIris(), VW::FirewireCamera::HasSaturation(), VW::FirewireCamera::HasSharpness(), VW::FirewireCamera::HasShutter(), VW::FirewireCamera::HasWhiteBalance(), VW::FirewireCamera::HasZoom(), VW::FirewireParams::M_160x120_YUV444, VW::FirewireParams::M_320x240_YUV422, VW::FirewireParams::M_640x480_MONO, VW::FirewireParams::M_640x480_RGB, VW::FirewireParams::M_640x480_YUV411, and VW::FirewireParams::M_640x480_YUV422.
bool VW::IOObject::WriteASCIIFile (const std::string & filename) const [inherited]
Open a file and output as plain ASCII (overwriting any existing contents).
Open a file and output as plain ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteASCII function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteASCII().
bool VW::FirewireCamera::WriteBinary (std::ostream & stream) const [virtual, inherited]
Stream as binary.
Parameters:
stream the output stream to write to
Returns:
true if successfully written, false if there are problems
Implements VW::IOObject.
bool VW::IOObject::WriteBinaryFile (const std::string & filename) const [inherited]
Open a file and output as binary (overwriting any existing contents).
Once the file is open, the child class's WriteBinary function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteBinary().
bool VW::FirewireCamera::WriteXML (std::ostream & stream, const std::string & name = "") const [virtual, inherited]
Stream as XML style ASCII.
Parameters:
stream the output stream to write to
name if specified, the class will be given a NAME= parameter
Returns:
true if successfully written, false if there are problems
Implements VW::IOObject.
References VW::FirewireCamera::GetAutoBrightness(), VW::FirewireCamera::GetAutoExposure(), VW::FirewireCamera::GetAutoFocus(), VW::FirewireCamera::GetAutoGain(), VW::FirewireCamera::GetAutoGamma(), VW::FirewireCamera::GetAutoHue(), VW::FirewireCamera::GetAutoIris(), VW::FirewireCamera::GetAutoSaturation(), VW::FirewireCamera::GetAutoSharpness(), VW::FirewireCamera::GetAutoShutter(), VW::FirewireCamera::GetAutoWhiteBalance(), VW::FirewireCamera::GetBrightness(), VW::FirewireCamera::GetBrightnessLimits(), VW::FirewireCamera::GetExposure(), VW::FirewireCamera::GetExposureLimits(), VW::FirewireCamera::GetFocus(), VW::FirewireCamera::GetFocusLimits(), VW::FirewireCamera::GetGain(), VW::FirewireCamera::GetGainLimits(), VW::FirewireCamera::GetGamma(), VW::FirewireCamera::GetGammaLimits(), VW::FirewireCamera::GetHue(), VW::FirewireCamera::GetHueLimits(), VW::FirewireCamera::GetIris(), VW::FirewireCamera::GetIrisLimits(), VW::FirewireCamera::GetSaturation(), VW::FirewireCamera::GetSaturationLimits(), VW::FirewireCamera::GetSharpness(), VW::FirewireCamera::GetSharpnessLimits(), VW::FirewireCamera::GetShutter(), VW::FirewireCamera::GetShutterLimits(), VW::FirewireCamera::GetWhiteBalanceU(), VW::FirewireCamera::GetWhiteBalanceULimits(), VW::FirewireCamera::GetWhiteBalanceV(), VW::FirewireCamera::GetWhiteBalanceVLimits(), VW::FirewireCamera::GetZoom(), VW::FirewireCamera::GetZoomLimits(), VW::FirewireCamera::HasBrightness(), VW::FirewireCamera::HasExposure(), VW::FirewireCamera::HasFocus(), VW::FirewireCamera::HasGain(), VW::FirewireCamera::HasGamma(), VW::FirewireCamera::HasHue(), VW::FirewireCamera::HasIris(), VW::FirewireCamera::HasSaturation(), VW::FirewireCamera::HasSharpness(), VW::FirewireCamera::HasShutter(), VW::FirewireCamera::HasWhiteBalance(), VW::FirewireCamera::HasZoom(), WriteFeatureXML(), and WriteWhiteBalanceXML().
bool VW::IOObject::WriteXMLFile (const std::string & filename, const std::string & name = "") const [inherited]
Open a file and output as XML-style ASCII (overwriting any existing contents).
Open a file and output as XML-style ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteXML function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
name the tag parameter, if required
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteXML().
Referenced by SaveParameterFile().
Friends And Related Function Documentation
friend class FirewireCameraGTKWidget [friend]
Member Data Documentation
dc1394_camerainfo VW::FirewireCamera::camera_info [protected, inherited]
Referenced by VW::FirewireCamera::GetBrightness(), VW::FirewireCamera::GetBrightnessLimits(), VW::FirewireCamera::GetExposure(), VW::FirewireCamera::GetExposureLimits(), VW::FirewireCamera::GetFirewireCommandHandle(), VW::FirewireCamera::GetFocus(), VW::FirewireCamera::GetFocusLimits(), VW::FirewireCamera::GetGain(), VW::FirewireCamera::GetGainLimits(), VW::FirewireCamera::GetGamma(), VW::FirewireCamera::GetGammaLimits(), VW::FirewireCamera::GetGUID(), VW::FirewireCamera::GetHue(), VW::FirewireCamera::GetHueLimits(), VW::FirewireCamera::GetIris(), VW::FirewireCamera::GetIrisLimits(), VW::FirewireCamera::GetModelString(), VW::FirewireCamera::GetNodeNumber(), VW::FirewireCamera::GetSaturation(), VW::FirewireCamera::GetSaturationLimits(), VW::FirewireCamera::GetSharpness(), VW::FirewireCamera::GetSharpnessLimits(), VW::FirewireCamera::GetShutter(), VW::FirewireCamera::GetShutterLimits(), VW::FirewireCamera::GetVendorString(), VW::FirewireCamera::GetWhiteBalanceU(), VW::FirewireCamera::GetWhiteBalanceULimits(), VW::FirewireCamera::GetWhiteBalanceV(), VW::FirewireCamera::GetWhiteBalanceVLimits(), VW::FirewireCamera::GetZoom(), VW::FirewireCamera::GetZoomLimits(), VW::FirewireCamera::ReleaseDMACapture(), VW::FirewireCamera::SetAutoBrightness(), VW::FirewireCamera::SetAutoExposure(), VW::FirewireCamera::SetAutoFocus(), VW::FirewireCamera::SetAutoGain(), VW::FirewireCamera::SetAutoGamma(), VW::FirewireCamera::SetAutoHue(), VW::FirewireCamera::SetAutoIris(), VW::FirewireCamera::SetAutoSaturation(), VW::FirewireCamera::SetAutoSharpness(), VW::FirewireCamera::SetAutoShutter(), VW::FirewireCamera::SetAutoWhiteBalance(), VW::FirewireCamera::SetBrightness(), VW::FirewireCamera::SetExposure(), VW::FirewireCamera::SetFirewireCommandHandle(), VW::FirewireCamera::SetFocus(), VW::FirewireCamera::SetFramerate(), VW::FirewireCamera::SetGain(), VW::FirewireCamera::SetGamma(), VW::FirewireCamera::SetHue(), VW::FirewireCamera::SetImageFormat(), VW::FirewireCamera::SetImageMode(), VW::FirewireCamera::SetIris(), VW::FirewireCamera::SetNodeNumber(), VW::FirewireCamera::SetSaturation(), VW::FirewireCamera::SetSharpness(), VW::FirewireCamera::SetShutter(), VW::FirewireCamera::SetUpCamera(), VW::FirewireCamera::SetupDMACapture(), VW::FirewireCamera::SetWhiteBalance(), VW::FirewireCamera::SetZoom(), VW::FirewireCamera::StartISOTransmission(), VW::FirewireCamera::StopISOTransmission(), VW::FirewireCamera::SwitchOff(), and VW::FirewireCamera::SwitchOn().
dc1394_feature_set VW::FirewireCamera::feature_set [protected, inherited]
Referenced by VW::FirewireCamera::GetAutoBrightness(), VW::FirewireCamera::GetAutoExposure(), VW::FirewireCamera::GetAutoFocus(), VW::FirewireCamera::GetAutoGain(), VW::FirewireCamera::GetAutoGamma(), VW::FirewireCamera::GetAutoHue(), VW::FirewireCamera::GetAutoIris(), VW::FirewireCamera::GetAutoSaturation(), VW::FirewireCamera::GetAutoSharpness(), VW::FirewireCamera::GetAutoShutter(), VW::FirewireCamera::GetAutoWhiteBalance(), VW::FirewireCamera::HasAutoBrightness(), VW::FirewireCamera::HasAutoExposure(), VW::FirewireCamera::HasAutoFocus(), VW::FirewireCamera::HasAutoGain(), VW::FirewireCamera::HasAutoGamma(), VW::FirewireCamera::HasAutoHue(), VW::FirewireCamera::HasAutoIris(), VW::FirewireCamera::HasAutoSaturation(), VW::FirewireCamera::HasAutoSharpness(), VW::FirewireCamera::HasAutoShutter(), VW::FirewireCamera::HasAutoWhiteBalance(), VW::FirewireCamera::HasBrightness(), VW::FirewireCamera::HasExposure(), VW::FirewireCamera::HasFocus(), VW::FirewireCamera::HasGain(), VW::FirewireCamera::HasGamma(), VW::FirewireCamera::HasHue(), VW::FirewireCamera::HasIris(), VW::FirewireCamera::HasSaturation(), VW::FirewireCamera::HasSharpness(), VW::FirewireCamera::HasShutter(), VW::FirewireCamera::HasWhiteBalance(), VW::FirewireCamera::HasZoom(), VW::FirewireCamera::SetAutoBrightness(), VW::FirewireCamera::SetAutoExposure(), VW::FirewireCamera::SetAutoFocus(), VW::FirewireCamera::SetAutoGain(), VW::FirewireCamera::SetAutoGamma(), VW::FirewireCamera::SetAutoHue(), VW::FirewireCamera::SetAutoIris(), VW::FirewireCamera::SetAutoSaturation(), VW::FirewireCamera::SetAutoSharpness(), VW::FirewireCamera::SetAutoShutter(), VW::FirewireCamera::SetAutoWhiteBalance(), and VW::FirewireCamera::SetUpCamera().
Gtk::FileSelection* VW::InterfaceGTK< FirewireCameraGTKWidget >::file_selector [protected, inherited]
int VW::FirewireCamera::history_pointer [protected, inherited]
Referenced by VW::FirewireCamera::FlushHistory(), VW::FirewireCamera::GetHistoricPosition(), and VW::FirewireCamera::StoreOdometryHistory().
int VW::FirewireCamera::image_height [protected, inherited]
Referenced by VW::FirewireCamera::GetImageHeight(), and VW::FirewireCamera::SetImageMode().
int VW::FirewireCamera::image_width [protected, inherited]
Referenced by VW::FirewireCamera::GetImageWidth(), and VW::FirewireCamera::SetImageMode().
SigC::Signal1<void,std::string> VW::InterfaceGTK< FirewireCameraGTKWidget >::LoadEvent [protected, inherited]
dc1394_miscinfo VW::FirewireCamera::misc_info [protected, inherited]
Referenced by VW::FirewireCamera::GetFramerate(), VW::FirewireCamera::GetImageFormat(), VW::FirewireCamera::GetImageMode(), VW::FirewireCamera::GetISOChannel(), VW::FirewireCamera::IsISOTransmitting(), VW::FirewireCamera::ReleaseDMACapture(), VW::FirewireCamera::SetFramerate(), VW::FirewireCamera::SetImageFormat(), VW::FirewireCamera::SetImageMode(), VW::FirewireCamera::SetUpCamera(), VW::FirewireCamera::SetupDMACapture(), VW::FirewireCamera::StartISOTransmission(), and VW::FirewireCamera::StopISOTransmission().
std::string VW::InterfaceGTK< FirewireCameraGTKWidget >::my_name [protected, inherited]
Referenced by FirewireCameraGTK().
VW::InterfaceType VW::InterfaceGTK< FirewireCameraGTKWidget >::my_type [protected, inherited]
Referenced by FirewireCameraGTK().
FirewireCameraGTKWidget * VW::InterfaceGTK< FirewireCameraGTKWidget >::my_widget [protected, inherited]
Referenced by ChangeAutoBrightness(), ChangeAutoExposure(), ChangeAutoFocus(), ChangeAutoGain(), ChangeAutoGamma(), ChangeAutoHue(), ChangeAutoIris(), ChangeAutoSaturation(), ChangeAutoSharpness(), ChangeAutoShutter(), ChangeAutoWhiteBalance(), ChangeBrightness(), ChangeExposure(), ChangeFocus(), ChangeGain(), ChangeGamma(), ChangeHue(), ChangeIris(), ChangeSaturation(), ChangeSharpness(), ChangeShutter(), ChangeWhiteBalance(), ChangeZoom(), SetAutoBrightness(), SetAutoExposure(), SetAutoFocus(), SetAutoGain(), SetAutoGamma(), SetAutoHue(), SetAutoIris(), SetAutoSaturation(), SetAutoSharpness(), SetAutoShutter(), SetAutoWhiteBalance(), SetBrightness(), SetExposure(), SetFocus(), SetGain(), SetGamma(), SetHue(), SetIris(), SetSaturation(), SetSharpness(), SetShutter(), SetUpCamera(), SetWhiteBalance(), and SetZoom().
Gtk::Window* VW::InterfaceGTK< FirewireCameraGTKWidget >::my_window [protected, inherited]
raw1394handle_t VW::FirewireCamera::receive_handle [protected, inherited]
Referenced by VW::FirewireCamera::GetFirewireReceiveHandle(), and VW::FirewireCamera::StartISOTransmission().
SigC::Signal1<void,std::string> VW::InterfaceGTK< FirewireCameraGTKWidget >::SaveEvent [protected, inherited]
struct timeval VW::FirewireCamera::time_history[CAMERA_ODOMETRY_HISTORY_LENGTH] [read, protected, inherited]
Referenced by VW::FirewireCamera::FlushHistory(), VW::FirewireCamera::GetHistoricPosition(), and VW::FirewireCamera::StoreOdometryHistory().
bool VW::FirewireCamera::verbose [protected, inherited]
Referenced by VW::FirewireCamera::ReleaseDMACapture(), VW::FirewireCamera::SetUpCamera(), VW::FirewireCamera::SetVerbosity(), VW::FirewireCamera::StartISOTransmission(), and VW::FirewireCamera::StopISOTransmission().
int VW::FirewireCamera::zoom_history[CAMERA_ODOMETRY_HISTORY_LENGTH] [protected, inherited]
Referenced by VW::FirewireCamera::FlushHistory(), VW::FirewireCamera::GetHistoricPosition(), and VW::FirewireCamera::StoreOdometryHistory().
The documentation for this class was generated from the following files:
firewirecameragtk.h
firewirecameragtk.cpp