VW: VNL::LeastSquaresCostFunction Class Reference
VNL::LeastSquaresCostFunction Class Reference
An adaptor that converts a vnl_least_squares_function to a vnl_cost_function.
#include <leastsquarescostfunction.h>
Public Types
typedef NumericLimits< double > limits
Public Member Functions
LeastSquaresCostFunction (LeastSquaresFunction *f)
double F (const Vector< double > &x)
The main function. Given the parameter vector x, compute the value of f(x).
virtual void GradF (const Vector< double > &x, Vector< double > &gradient)
Calculate the gradient of f at parameter vector x.
Vector< double > GradF (Vector< double > const &x)
Conveniences for printing grad, fdgrad.
virtual void Compute (Vector< double > const &x, double *f, Vector< double > *g)
Compute one or both of f and g.
int GetNumberOfUnknowns () const
Return the number of unknowns.
void FDGradF (Vector< double > const &x, Vector< double > &gradient, double stepsize=1e-5)
Compute finite-difference gradient.
Vector< double > FDGradF (Vector< double > const &x)
virtual double ReportedError (double f_value)
Called when error is printed for user.
virtual double GetRangeMin () const
Return bounding cube of range (outputs).
virtual double GetRangeMax () const
virtual UnaryFunction< double,
Vector< double > > * Copy () const
Copy should allocate a copy of this on the heap and return it.
Public Attributes
int dim
Protected Attributes
Vector< double > storage_
Matrix< double > jacobian_
LeastSquaresFunction * f_
Detailed Description
An adaptor that converts a vnl_least_squares_function to a vnl_cost_function.
Member Typedef Documentation
typedef NumericLimits<double > VNL::UnaryFunction< double , Vector< double > >::limits [inherited]
Constructor & Destructor Documentation
VNL::LeastSquaresCostFunction::LeastSquaresCostFunction (LeastSquaresFunction * f)
Member Function Documentation
void VNL::CostFunction::Compute (VNL::Vector< double > const & x, double * f, VNL::Vector< double > * g) [virtual, inherited]
Compute one or both of f and g.
Normally implemented in terms of the above two, but may be faster if specialized. f != 0 => compute f
References VNL::CostFunction::F(), and VNL::CostFunction::GradF().
Referenced by VNL::CostFunction::F(), VNL::CostFunction::GradF(), VNL::LBFGS::Minimize(), and VNL::ConjugateGradient::ValueAndGradientComputer_().
virtual UnaryFunction<double ,Vector< double > >* VNL::UnaryFunction< double , Vector< double > >::Copy () const [inline, virtual, inherited]
Copy should allocate a copy of this on the heap and return it.
If Subclasses do not implement this function, it will return null, but many applications will never call it, so this may not be a problem for you.
double VNL::LeastSquaresCostFunction::F (const Vector< double > & x) [virtual]
The main function. Given the parameter vector x, compute the value of f(x).
Default implementation of f is compute.
..
Reimplemented from VNL::CostFunction.
References VNL::LeastSquaresFunction::F(), f_, VNL::Vector< T >::SquaredMagnitude(), and storage_.
VNL::Vector< double > VNL::CostFunction::FDGradF (VNL::Vector< double > const & x) [inherited]
References VNL::CostFunction::dim, and VNL::CostFunction::FDGradF().
void VNL::CostFunction::FDGradF (VNL::Vector< double > const & x, VNL::Vector< double > & gradient, double stepsize = 1e-5) [inherited]
Compute finite-difference gradient.
Compute fd gradient.
References VNL::CostFunction::dim, and VNL::CostFunction::F().
Referenced by VNL::CostFunction::FDGradF(), and VNL::LBFGS::Minimize().
int VNL::CostFunction::GetNumberOfUnknowns () const [inline, inherited]
Return the number of unknowns.
References VNL::CostFunction::dim.
Referenced by VNL::Amoeba::Amoeba(), VNL::ConjugateGradient::GradientComputer_(), VNL::LBFGS::Minimize(), VNL::ConjugateGradient::Minimize(), VNL::ConjugateGradient::Preconditioner_(), VNL::ConjugateGradient::ValueAndGradientComputer_(), and VNL::ConjugateGradient::ValueComputer_().
virtual double VNL::UnaryFunction< double , Vector< double > >::GetRangeMax () const [inline, virtual, inherited]
virtual double VNL::UnaryFunction< double , Vector< double > >::GetRangeMin () const [inline, virtual, inherited]
Return bounding cube of range (outputs).
VNL::Vector< double > VNL::CostFunction::GradF (VNL::Vector< double > const & x) [inherited]
Conveniences for printing grad, fdgrad.
References VNL::CostFunction::dim, and VNL::CostFunction::GradF().
void VNL::LeastSquaresCostFunction::GradF (const Vector< double > & x, Vector< double > & g) [virtual]
Calculate the gradient of f at parameter vector x.
Default implementation of gradf is to call compute.
Reimplemented from VNL::CostFunction.
References c, VNL::Matrix< T >::Columns(), VNL::LeastSquaresFunction::F(), f_, VNL::LeastSquaresFunction::GradF(), VNL::LeastSquaresFunction::HasGradient(), jacobian_, VNL::Matrix< T >::Rows(), and storage_.
virtual double VNL::CostFunction::ReportedError (double f_value) [inline, virtual, inherited]
Called when error is printed for user.
Referenced by VNL::ConjugateGradient::DiagnoseOutcome(), and VNL::LBFGS::Minimize().
Member Data Documentation
int VNL::CostFunction::dim [inherited]
Referenced by VNL::CostFunction::FDGradF(), VNL::CostFunction::GetNumberOfUnknowns(), and VNL::CostFunction::GradF().
LeastSquaresFunction* VNL::LeastSquaresCostFunction::f_ [protected]
Referenced by F(), and GradF().
Matrix<double> VNL::LeastSquaresCostFunction::jacobian_ [protected]
Referenced by GradF().
Vector<double> VNL::LeastSquaresCostFunction::storage_ [protected]
Referenced by F(), and GradF().
The documentation for this class was generated from the following files:
leastsquarescostfunction.h
leastsquarescostfunction.cpp