VW: VW::Threshold< Type > Class Template Reference
VW::Threshold< Type > Class Template Reference
[ImageProcessing]
#include <threshold.h>
Public Member Functions
Threshold (const Type thresh=1, const Type l=0, const Type u=1)
Threshold (const ImageMono< Type > &im, ImageMono< Type > &result, const Type val)
Threshold (const ImageMono< Type > &im, ImageMono< Type > &result, const Type val, const Type l, const Type u)
Threshold (ImageMono< Type > &im, const Type val, const Type l, const Type u)
Threshold (ImageMono< Type > &im, const Type val)
void Compute (const ImageMono< Type > &im, ImageMono< Type > &result)
void Compute (ImageMono< Type > &im)
operator bool ()
void SetThreshold (Type val)
void SetLower (Type val)
void SetUpper (Type val)
Detailed Description
template<class Type>
class VW::Threshold< Type >
Author:
ID Reid
Date:
02/08/2002
Constructor & Destructor Documentation
template<class Type > VW::Threshold< Type >::Threshold (const Type thresh = 1, const Type l = 0, const Type u = 1) [inline]
template<class Type > VW::Threshold< Type >::Threshold (const ImageMono< Type > & im, ImageMono< Type > & result, const Type val) [inline]
References VW::Threshold< Type >::Compute().
template<class Type > VW::Threshold< Type >::Threshold (const ImageMono< Type > & im, ImageMono< Type > & result, const Type val, const Type l, const Type u) [inline]
References VW::Threshold< Type >::Compute().
template<class Type > VW::Threshold< Type >::Threshold (ImageMono< Type > & im, const Type val, const Type l, const Type u) [inline]
References VW::Threshold< Type >::Compute().
template<class Type > VW::Threshold< Type >::Threshold (ImageMono< Type > & im, const Type val) [inline]
References VW::Threshold< Type >::Compute().
Member Function Documentation
template<class Type > void Threshold::Compute (ImageMono< Type > & im) [inline]
References c, VW::ROI::Get(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetROIRowStart(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::IsAlloced(), VW::PixelMono< Type >::Luminance(), and VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::ROI().
template<class Type > void Threshold::Compute (const ImageMono< Type > & im, ImageMono< Type > & result) [inline]
References VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::AllocImageData(), c, VW::ROI::Get(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetROIRowStart(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::IsAlloced(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::ROI(), and VW::ROI::Set().
Referenced by VW::Threshold< Type >::Threshold().
template<class Type > VW::Threshold< Type >::operator bool () [inline]
template<class Type > void VW::Threshold< Type >::SetLower (Type val) [inline]
template<class Type > void VW::Threshold< Type >::SetThreshold (Type val) [inline]
template<class Type > void VW::Threshold< Type >::SetUpper (Type val) [inline]
The documentation for this class was generated from the following files:
threshold.h
threshold.cpp