VW: vnl_matops Class Reference
vnl_matops Class Reference
A collection of Matrix operations.
#include <matops.h>
Static Public Member Functions
static double homg_diff (VNL::Matrix< double > const &A, VNL::Matrix< double > const &B)
Return fro_norm((A .
static VNL::Matrix< double > cat (VNL::Matrix< double > const &A, VNL::Matrix< double > const &B)
Laminating.
static VNL::Matrix< double > cat (VNL::Matrix< double > const &A, VNL::Vector< double > const &B)
static VNL::Matrix< double > cat (VNL::Vector< double > const &A, VNL::Matrix< double > const &B)
static VNL::Matrix< double > vcat (VNL::Matrix< double > const &A, VNL::Matrix< double > const &B)
static VNL::Matrix< double > f2d (VNL::Matrix< float > const &)
Conversions.
static VNL::Vector< double > f2d (VNL::Vector< float > const &)
static VNL::Matrix< float > d2f (VNL::Matrix< double > const &)
static VNL::Vector< float > d2f (VNL::Vector< double > const &)
Detailed Description
A collection of Matrix operations.
mostly declared as static methods. Highlights include the in-place transpose, and type conversions. matlab_print has been moved to vnl_matlab_print.h.
Member Function Documentation
VNL::Matrix< double > vnl_matops::cat (VNL::Vector< double > const & A, VNL::Matrix< double > const & B) [static]
References VNL::Matrix< T >::Columns(), VNL::Matrix< T >::Rows(), VNL::Matrix< T >::SetColumn(), VNL::Vector< T >::Size(), and VNL::Matrix< T >::Update().
VNL::Matrix< double > vnl_matops::cat (VNL::Matrix< double > const & A, VNL::Vector< double > const & B) [static]
References VNL::Matrix< T >::Columns(), VNL::Matrix< T >::Rows(), VNL::Matrix< T >::SetColumn(), VNL::Vector< T >::Size(), and VNL::Matrix< T >::Update().
VNL::Matrix< double > vnl_matops::cat (VNL::Matrix< double > const & A, VNL::Matrix< double > const & B) [static]
Laminating.
References VNL::Matrix< T >::Columns(), VNL::Matrix< T >::Rows(), and VNL::Matrix< T >::Update().
VNL::Vector< float > vnl_matops::d2f (VNL::Vector< double > const & M) [static]
VNL::Matrix< float > vnl_matops::d2f (VNL::Matrix< double > const & M) [static]
VNL::Vector< double > vnl_matops::f2d (VNL::Vector< float > const & M) [static]
double VNL::Matrix< double > vnl_matops::f2d (VNL::Matrix< float > const & M) [static]
Conversions.
double vnl_matops::homg_diff (VNL::Matrix< double > const & A, VNL::Matrix< double > const & B) [static]
Return fro_norm((A .
/ B) - mean(A ./ B)).
References VNL::ElementQuotient(), and VNL::Matrix< T >::Mean().
VNL::Matrix< double > vnl_matops::vcat (VNL::Matrix< double > const & A, VNL::Matrix< double > const & B) [static]
References VNL::Matrix< T >::Columns(), VNL::Matrix< T >::Rows(), and VNL::Matrix< T >::Update().
The documentation for this class was generated from the following files:
matops.h
matops.cpp