VW: VNL::Powell1DFun Class Reference
VNL::Powell1DFun Class Reference
Public Types
typedef NumericLimits< double > limits
Public Member Functions
Powell1DFun (int n, CostFunction *f, Powell *powell)
void Init (VNL::Vector< double > const &x0, VNL::Vector< double > const &dx)
double F (const VNL::Vector< double > &x)
The main function. Given the parameter vector x, compute the value of f(x).
void Uninit (double lambda, VNL::Vector< double > &out)
virtual void GradF (Vector< double > const &x, Vector< double > &gradient)
Calculate the gradient of f at parameter vector x.
Vector< double > GradF (Vector< double > const &x)
Conveniences for printing grad, fdgrad.
virtual void Compute (Vector< double > const &x, double *f, Vector< double > *g)
Compute one or both of f and g.
int GetNumberOfUnknowns () const
Return the number of unknowns.
void FDGradF (Vector< double > const &x, Vector< double > &gradient, double stepsize=1e-5)
Compute finite-difference gradient.
Vector< double > FDGradF (Vector< double > const &x)
virtual double ReportedError (double f_value)
Called when error is printed for user.
virtual double GetRangeMin () const
Return bounding cube of range (outputs).
virtual double GetRangeMax () const
virtual UnaryFunction< double,
Vector< double > > * Copy () const
Copy should allocate a copy of this on the heap and return it.
Public Attributes
Powell * powell_
CostFunction * f_
unsigned int n_
Vector< double > x0_
Vector< double > dx_
Vector< double > tmpx_
int dim
Member Typedef Documentation
typedef NumericLimits<double > VNL::UnaryFunction< double , Vector< double > >::limits [inherited]
Constructor & Destructor Documentation
VNL::Powell1DFun::Powell1DFun (int n, CostFunction * f, Powell * powell) [inline]
Member Function Documentation
void VNL::CostFunction::Compute (VNL::Vector< double > const & x, double * f, VNL::Vector< double > * g) [virtual, inherited]
Compute one or both of f and g.
Normally implemented in terms of the above two, but may be faster if specialized. f != 0 => compute f
References VNL::CostFunction::F(), and VNL::CostFunction::GradF().
Referenced by VNL::CostFunction::F(), VNL::CostFunction::GradF(), VNL::LBFGS::Minimize(), and VNL::ConjugateGradient::ValueAndGradientComputer_().
virtual UnaryFunction<double ,Vector< double > >* VNL::UnaryFunction< double , Vector< double > >::Copy () const [inline, virtual, inherited]
Copy should allocate a copy of this on the heap and return it.
If Subclasses do not implement this function, it will return null, but many applications will never call it, so this may not be a problem for you.
double VNL::Powell1DFun::F (const VNL::Vector< double > & x) [inline, virtual]
The main function. Given the parameter vector x, compute the value of f(x).
Default implementation of f is compute.
..
Reimplemented from VNL::CostFunction.
References VNL::Powell::_PubReportEval(), VNL::CostFunction::F(), f_, powell_, tmpx_, and Uninit().
VNL::Vector< double > VNL::CostFunction::FDGradF (VNL::Vector< double > const & x) [inherited]
References VNL::CostFunction::dim, and VNL::CostFunction::FDGradF().
void VNL::CostFunction::FDGradF (VNL::Vector< double > const & x, VNL::Vector< double > & gradient, double stepsize = 1e-5) [inherited]
Compute finite-difference gradient.
Compute fd gradient.
References VNL::CostFunction::dim, and VNL::CostFunction::F().
Referenced by VNL::CostFunction::FDGradF(), and VNL::LBFGS::Minimize().
int VNL::CostFunction::GetNumberOfUnknowns () const [inline, inherited]
Return the number of unknowns.
References VNL::CostFunction::dim.
Referenced by VNL::Amoeba::Amoeba(), VNL::ConjugateGradient::GradientComputer_(), VNL::LBFGS::Minimize(), VNL::ConjugateGradient::Minimize(), VNL::ConjugateGradient::Preconditioner_(), VNL::ConjugateGradient::ValueAndGradientComputer_(), and VNL::ConjugateGradient::ValueComputer_().
virtual double VNL::UnaryFunction< double , Vector< double > >::GetRangeMax () const [inline, virtual, inherited]
virtual double VNL::UnaryFunction< double , Vector< double > >::GetRangeMin () const [inline, virtual, inherited]
Return bounding cube of range (outputs).
VNL::Vector< double > VNL::CostFunction::GradF (VNL::Vector< double > const & x) [inherited]
Conveniences for printing grad, fdgrad.
References VNL::CostFunction::dim, and VNL::CostFunction::GradF().
void VNL::CostFunction::GradF (VNL::Vector< double > const & x, VNL::Vector< double > & g) [virtual, inherited]
Calculate the gradient of f at parameter vector x.
Default implementation of gradf is to call compute.
Reimplemented in VNL::LeastSquaresCostFunction.
References VNL::CostFunction::Compute().
Referenced by VNL::CostFunction::Compute(), VNL::CostFunction::GradF(), and VNL::ConjugateGradient::GradientComputer_().
void VNL::Powell1DFun::Init (VNL::Vector< double > const & x0, VNL::Vector< double > const & dx) [inline]
References dx_, n_, VNL::Vector< T >::size(), and x0_.
Referenced by VNL::Powell::Minimize().
virtual double VNL::CostFunction::ReportedError (double f_value) [inline, virtual, inherited]
Called when error is printed for user.
Referenced by VNL::ConjugateGradient::DiagnoseOutcome(), and VNL::LBFGS::Minimize().
void VNL::Powell1DFun::Uninit (double lambda, VNL::Vector< double > & out) [inline]
References dx_, n_, and x0_.
Referenced by F(), and VNL::Powell::Minimize().
Member Data Documentation
int VNL::CostFunction::dim [inherited]
Referenced by VNL::CostFunction::FDGradF(), VNL::CostFunction::GetNumberOfUnknowns(), and VNL::CostFunction::GradF().
Vector<double> VNL::Powell1DFun::dx_
Referenced by Init(), and Uninit().
CostFunction* VNL::Powell1DFun::f_
Referenced by F().
unsigned int VNL::Powell1DFun::n_
Referenced by Init(), and Uninit().
Powell* VNL::Powell1DFun::powell_
Referenced by F().
Vector<double> VNL::Powell1DFun::tmpx_
Referenced by F().
Vector<double> VNL::Powell1DFun::x0_
Referenced by Init(), and Uninit().
The documentation for this class was generated from the following file:
powell.cpp