VW: VW::PlesseyCornerMatcher Class Reference
VW::PlesseyCornerMatcher Class Reference
#include <plesseycornermatcher.h>
Public Member Functions
PlesseyCornerMatcher (const MatcherType matcher_type=MatcherParams::DEF_TYPE, const float maximum_range=MatcherParams::DEF_MAX_RANGE, const float score_threshold=MatcherParams::DEF_SCORE_THRESH)
Construct and compute specifying all params.
PlesseyCornerMatcher (const std::vector< VW::PlesseyCorner > &plnew, const std::vector< VW::PlesseyCorner > &plold, std::vector< VW::MatchData > &matchlist, const MatcherType matcher_type=MatcherParams::DEF_TYPE, const float maximum_range=MatcherParams::DEF_MAX_RANGE, const float score_threshold=MatcherParams::DEF_SCORE_THRESH)
Construct and compute specifying all params.
operator bool () const
void Compute (const std::vector< VW::PlesseyCorner > &plnew, const std::vector< VW::PlesseyCorner > &plold, std::vector< MatchData > &matchlist) const
Compute using two corner lists.
void FormLookupTable (const std::vector< MatchData > &matchlist, std::vector< int > &list1, std::vector< int > &list2) const
void SetMaximumRange (const float new_max_range)
void SetScoreThreshold (const float score_thresh)
Protected Member Functions
float GetMatchScore (const VW::PlesseyCorner &f1, const VW::PlesseyCorner &f2) const
void MatchScoresToProbs (std::vector< std::vector< VW::MatchData > > &potentialmatches) const
virtual void MatchScoresToProbs (std::vector< std::vector< MatchData > > &potentialmatches) const =0
void FindPotentialMatches (const std::vector< VW::PlesseyCorner > &old_pointlist, const std::vector< VW::PlesseyCorner > &new_pointlist, std::vector< std::vector< MatchData > > &potentialmatches) const
Use GetMatchScore to obtain a set of potential matches for each point.
bool BraindeadMatcher (const std::vector< std::vector< MatchData > > &potentialmatches, const unsigned int number_in_list1, const unsigned int number_in_list2, std::vector< MatchData > &matchlist) const
The actual matchers - 1.
bool RepeatedlyStupidMatcher (const std::vector< std::vector< MatchData > > &potentialmatches, const unsigned int number_in_list1, const unsigned int number_in_list2, std::vector< MatchData > &matchlist) const
The actual matchers - 2.
Constructor & Destructor Documentation
VW::PlesseyCornerMatcher::PlesseyCornerMatcher (const MatcherType matcher_type = MatcherParams::DEF_TYPE, const float maximum_range = MatcherParams::DEF_MAX_RANGE, const float score_threshold = MatcherParams::DEF_SCORE_THRESH)
Construct and compute specifying all params.
VW::PlesseyCornerMatcher::PlesseyCornerMatcher (const std::vector< VW::PlesseyCorner > & plnew, const std::vector< VW::PlesseyCorner > & plold, std::vector< VW::MatchData > & matchlist, const MatcherType matcher_type = MatcherParams::DEF_TYPE, const float maximum_range = MatcherParams::DEF_MAX_RANGE, const float score_threshold = MatcherParams::DEF_SCORE_THRESH)
Construct and compute specifying all params.
References VW::CornerMatcherBase< VW::PlesseyCorner >::Compute().
Member Function Documentation
bool VW::CornerMatcherBase< VW::PlesseyCorner >::BraindeadMatcher (const std::vector< std::vector< MatchData > > & potentialmatches, const unsigned int number_in_list1, const unsigned int number_in_list2, std::vector< MatchData > & matchlist) const [protected, inherited]
The actual matchers - 1.
a pretty daft but quick matcher. This one takes the list of potential matches for each feature and selects the best, resolving conflicts by first-come- first-served.
void VW::CornerMatcherBase< VW::PlesseyCorner >::Compute (const std::vector< VW::PlesseyCorner > & plnew, const std::vector< VW::PlesseyCorner > & plold, std::vector< MatchData > & matchlist) const [inherited]
Compute using two corner lists.
Referenced by PlesseyCornerMatcher().
void VW::CornerMatcherBase< VW::PlesseyCorner >::FindPotentialMatches (const std::vector< VW::PlesseyCorner > & old_pointlist, const std::vector< VW::PlesseyCorner > & new_pointlist, std::vector< std::vector< MatchData > > & potentialmatches) const [protected, inherited]
Use GetMatchScore to obtain a set of potential matches for each point.
void VW::CornerMatcherBase< VW::PlesseyCorner >::FormLookupTable (const std::vector< MatchData > & matchlist, std::vector< int > & list1, std::vector< int > & list2) const [inherited]
float VW::PlesseyCornerMatcher::GetMatchScore (const VW::PlesseyCorner & f1, const VW::PlesseyCorner & f2) const [inline, protected, virtual]
Implements VW::CornerMatcherBase< VW::PlesseyCorner >.
References VW::PlesseyCorner::GetImagePatch(), and VW::ImagePatch::GetZNCC().
virtual void VW::CornerMatcherBase< VW::PlesseyCorner >::MatchScoresToProbs (std::vector< std::vector< MatchData > > & potentialmatches) const [protected, pure virtual, inherited]
void VW::PlesseyCornerMatcher::MatchScoresToProbs (std::vector< std::vector< VW::MatchData > > & potentialmatches) const [protected]
VW::CornerMatcherBase< VW::PlesseyCorner >::operator bool () const [inline, inherited]
bool VW::CornerMatcherBase< VW::PlesseyCorner >::RepeatedlyStupidMatcher (const std::vector< std::vector< MatchData > > & potentialmatches, const unsigned int number_in_list1, const unsigned int number_in_list2, std::vector< MatchData > & matchlist) const [protected, inherited]
The actual matchers - 2.
a simple iterative matcher. This one takes the list of potential matches for each feature and selects the best, resolving conflicts by iteration (usually only needs 3-4 passes).
void VW::CornerMatcherBase< VW::PlesseyCorner >::SetMaximumRange (const float new_max_range) [inherited]
void VW::CornerMatcherBase< VW::PlesseyCorner >::SetScoreThreshold (const float score_thresh) [inherited]
The documentation for this class was generated from the following files:
plesseycornermatcher.h
plesseycornermatcher.cpp