VW: VW::AWFObject Class Reference
VW::AWFObject Class Reference
Class to read and store an Alias WaveFront (AWF) objects.
#include <awfobject.h>
Public Member Functions
AWFObject ()
AWFObject (const std::string &filename, bool generate_edges=false)
void LoadFile (const std::string &filename, bool generate_edges=false)
Load a new object from a file.
void SaveObject (const std::string &filename) const
Write out the geometry data to a ".obj" file (filename should include the full path and extension - none will be added).
void SaveMaterials (const std::string &filename) const
Write out the materials data to a ".mtl" file (filename should include the full path and extension - none will be added).
void SaveAll (const std::string &filename) const
Write out all data.
void SaveAsVRML (const std::string &filename) const
void Draw () const
Draw the object - note that you must have the right GL context set and the position and orientation how you want them - this functions just draws on the current view at the current position!
void Draw (VW::ThreeDToolGLCommon &display, const int name=0) const
VW version of the draw command that also takes into account sizing etc, and with optional selection (0 indicates no selection).
void GetBoundingBox (float &x0, float &y0, float &z0, float &x1, float &y1, float &z1) const
void Translate (const VW::Vector3D &delta)
Move the object with respect to its origin.
void Rotate (const VW::Quaternion &q)
Rotate the object with respect to its origin.
void RotateY (const double theta)
Rotate the object around the Y-axis with respect to its origin.
void Rescale (float scale_factor)
Scale the object uniformly around its origin.
void Recentre ()
Make the object origin the centroid.
void Unitise ()
Rescale so that the largest dimension is 1.
unsigned int GetNumVertices () const
unsigned int GetNumEdges () const
unsigned int GetNumFaces () const
VW::Point3D GetVertex (unsigned int index) const
Get a vertex in object coords.
void GetEdge (unsigned int index, VW::LineSeg3D &line, VW::Vector3D &normal1, VW::Vector3D &normal2) const
Get an edge, along with the normals for the bordering faces.
void GetFace (unsigned int index, std::vector< VW::Point3D > &vertices, VW::Vector3D &normal) const
Protected Member Functions
void _CalcBoundingBox ()
void _ReadVertex (const std::string &data)
void _GenerateEdges ()
void _GenList ()
Protected Attributes
bool _initialised
std::vector< Vector3D > _vertex
std::vector< Vector3D > _normal
std::vector< Vector2D > _texcoord
std::vector< AWFFace > _face
std::vector< AWFEdge > _edge
std::vector< AWFMaterial > _material
int _list_id
float _minx
float _maxx
float _miny
float _maxy
float _minz
float _maxz
Detailed Description
Class to read and store an Alias WaveFront (AWF) objects.
Author:
BJ Tordoff
Date:
13/01/2004
Constructor & Destructor Documentation
VW::AWFObject::AWFObject ()
VW::AWFObject::AWFObject (const std::string & filename, bool generate_edges = false)
References LoadFile().
Member Function Documentation
void VW::AWFObject::_CalcBoundingBox () [protected]
References _maxx, _maxy, _maxz, _minx, _miny, _minz, _vertex, and v.
Referenced by LoadFile(), Rotate(), and RotateY().
void VW::AWFObject::_GenerateEdges () [protected]
References _edge, _face, VW::AWFFace::_vindex, and VW::AWFEdge::AddFace().
Referenced by LoadFile().
void VW::AWFObject::_GenList () [protected]
References _edge, _face, _initialised, _list_id, _material, _normal, _texcoord, _vertex, VW::Point3D::_x, VW::Point3D::_y, VW::Point3D::_z, VW::Point2D::GetX(), VW::Point3D::GetX(), VW::Point2D::GetY(), VW::Point3D::GetY(), VW::Point3D::GetZ(), v, VERBOSE, VW::VertexOnly, VW::WithNormal, VW::WithTexture, and VW::WithTextureAndNormal.
Referenced by LoadFile(), Rescale(), Rotate(), RotateY(), and Translate().
void VW::AWFObject::_ReadVertex (const std::string & data) [protected]
References _normal, _texcoord, _vertex, and VERBOSE.
Referenced by LoadFile().
void VW::AWFObject::Draw (VW::ThreeDToolGLCommon & display, const int name = 0) const
VW version of the draw command that also takes into account sizing etc, and with optional selection (0 indicates no selection).
References _maxx, _maxy, _maxz, _minx, _miny, _minz, Draw(), and VW::ThreeDToolGLCommon::IncludeInRotationCentre().
void VW::AWFObject::Draw () const
Draw the object - note that you must have the right GL context set and the position and orientation how you want them - this functions just draws on the current view at the current position!
References _initialised, and _list_id.
Referenced by Draw().
void VW::AWFObject::GetBoundingBox (float & x0, float & y0, float & z0, float & x1, float & y1, float & z1) const
References _maxx, _maxy, _maxz, _minx, _miny, and _minz.
void VW::AWFObject::GetEdge (unsigned int index, VW::LineSeg3D & line, VW::Vector3D & normal1, VW::Vector3D & normal2) const [inline]
Get an edge, along with the normals for the bordering faces.
References _edge, _face, and _vertex.
void VW::AWFObject::GetFace (unsigned int index, std::vector< VW::Point3D > & vertices, VW::Vector3D & normal) const [inline]
References _face, _vertex, and v.
unsigned int VW::AWFObject::GetNumEdges () const [inline]
References _edge.
unsigned int VW::AWFObject::GetNumFaces () const [inline]
References _face.
unsigned int VW::AWFObject::GetNumVertices () const [inline]
References _vertex.
VW::Point3D VW::AWFObject::GetVertex (unsigned int index) const [inline]
Get a vertex in object coords.
References _vertex.
void VW::AWFObject::LoadFile (const std::string & filename, bool generate_edges = false)
Load a new object from a file.
Any existing data will be discarded.
References _CalcBoundingBox(), _edge, _face, _GenerateEdges(), _GenList(), _initialised, _material, _normal, _ReadVertex(), _texcoord, _vertex, VW::AddDefaultAWFMaterials(), VW::AWFFace::Check(), VW::GetFilePath(), m, VW::ReadAWFMaterialsFile(), VW::AWFFace::ReadLine(), and VERBOSE.
Referenced by AWFObject().
void VW::AWFObject::Recentre ()
Make the object origin the centroid.
References _maxx, _maxy, _maxz, _minx, _miny, _minz, and Translate().
void VW::AWFObject::Rescale (float scale_factor)
Scale the object uniformly around its origin.
References _GenList(), _maxx, _maxy, _maxz, _minx, _miny, _minz, _vertex, and v.
Referenced by Unitise().
void VW::AWFObject::Rotate (const VW::Quaternion & q)
Rotate the object with respect to its origin.
References _CalcBoundingBox(), _face, _GenList(), _normal, _vertex, VW::Quaternion::Rotate(), and v.
void VW::AWFObject::RotateY (const double theta)
Rotate the object around the Y-axis with respect to its origin.
References _CalcBoundingBox(), _GenList(), _normal, _vertex, c, and v.
void VW::AWFObject::SaveAll (const std::string & filename) const
Write out all data.
The geometry is saved to filename.obj, the materials to filename.mtl and any texture images are copied to the same location (if different from the source location).
References _material, VW::CopyFile(), m, VW::ReformFilename(), SaveMaterials(), SaveObject(), and VW::SplitFilename().
void VW::AWFObject::SaveAsVRML (const std::string & filename) const
References _face, _material, _normal, _texcoord, _vertex, VW::CopyFile(), m, VW::ReformFilename(), and VW::SplitFilename().
void VW::AWFObject::SaveMaterials (const std::string & filename) const
Write out the materials data to a ".mtl" file (filename should include the full path and extension - none will be added).
References _material, and m.
Referenced by SaveAll().
void VW::AWFObject::SaveObject (const std::string & filename) const
Write out the geometry data to a ".obj" file (filename should include the full path and extension - none will be added).
References _face, _material, _normal, _texcoord, _vertex, VW::SplitFilename(), and v.
Referenced by SaveAll().
void VW::AWFObject::Translate (const VW::Vector3D & delta)
Move the object with respect to its origin.
References _GenList(), _maxx, _maxy, _maxz, _minx, _miny, _minz, _vertex, VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), and v.
Referenced by Recentre().
void VW::AWFObject::Unitise ()
Rescale so that the largest dimension is 1.
References _maxx, _maxy, _maxz, _minx, _miny, _minz, and Rescale().
Member Data Documentation
std::vector<AWFEdge> VW::AWFObject::_edge [protected]
Referenced by _GenerateEdges(), _GenList(), GetEdge(), GetNumEdges(), and LoadFile().
std::vector<AWFFace> VW::AWFObject::_face [protected]
Referenced by _GenerateEdges(), _GenList(), GetEdge(), GetFace(), GetNumFaces(), LoadFile(), Rotate(), SaveAsVRML(), and SaveObject().
bool VW::AWFObject::_initialised [protected]
Referenced by _GenList(), Draw(), and LoadFile().
int VW::AWFObject::_list_id [protected]
Referenced by _GenList(), and Draw().
std::vector<AWFMaterial> VW::AWFObject::_material [protected]
Referenced by _GenList(), LoadFile(), SaveAll(), SaveAsVRML(), SaveMaterials(), and SaveObject().
float VW::AWFObject::_maxx [protected]
Referenced by _CalcBoundingBox(), Draw(), GetBoundingBox(), Recentre(), Rescale(), Translate(), and Unitise().
float VW::AWFObject::_maxy [protected]
Referenced by _CalcBoundingBox(), Draw(), GetBoundingBox(), Recentre(), Rescale(), Translate(), and Unitise().
float VW::AWFObject::_maxz [protected]
Referenced by _CalcBoundingBox(), Draw(), GetBoundingBox(), Recentre(), Rescale(), Translate(), and Unitise().
float VW::AWFObject::_minx [protected]
Referenced by _CalcBoundingBox(), Draw(), GetBoundingBox(), Recentre(), Rescale(), Translate(), and Unitise().
float VW::AWFObject::_miny [protected]
Referenced by _CalcBoundingBox(), Draw(), GetBoundingBox(), Recentre(), Rescale(), Translate(), and Unitise().
float VW::AWFObject::_minz [protected]
Referenced by _CalcBoundingBox(), Draw(), GetBoundingBox(), Recentre(), Rescale(), Translate(), and Unitise().
std::vector<Vector3D> VW::AWFObject::_normal [protected]
Referenced by _GenList(), _ReadVertex(), LoadFile(), Rotate(), RotateY(), SaveAsVRML(), and SaveObject().
std::vector<Vector2D> VW::AWFObject::_texcoord [protected]
Referenced by _GenList(), _ReadVertex(), LoadFile(), SaveAsVRML(), and SaveObject().
std::vector<Vector3D> VW::AWFObject::_vertex [protected]
Referenced by _CalcBoundingBox(), _GenList(), _ReadVertex(), GetEdge(), GetFace(), GetNumVertices(), GetVertex(), LoadFile(), Rescale(), Rotate(), RotateY(), SaveAsVRML(), SaveObject(), and Translate().
The documentation for this class was generated from the following files:
awfobject.h
awfobject.cpp