VW: Glute2::Window Class Reference
Glute2::Window Class Reference
#include <window.h>
Public Member Functions
Window (int w, int h, const std::string &title)
virtual ~Window ()
void Add (Widget *child)
void Position (int x, int y)
void FullScreen ()
void Show ()
void Hide ()
void Iconify ()
void Push ()
void Pop ()
void SetClearColour (float r, float g, float b, float a)
void SetCursor (int cursor)
void Redisplay ()
void MakeCurrent ()
void SwapBuffers ()
void Flush ()
int GetWindowID () const
unsigned int GetWidth () const
unsigned int GetHeight () const
Protected Member Functions
void Resize (int w, int h)
void Draw ()
void Mouse (int button, int state, int x, int y)
void Motion (int x, int y)
void PassiveMotion (int x, int y)
void Keyboard (unsigned char key, int x, int y)
virtual void Entry (int state)
virtual void Special (int key, int x, int y)
bool IsMe (int i) const
void SetID (int id)
int GetID () const
int _CreateWindow (unsigned int width, unsigned int height, const std::string &title)
int _CreateSubwindow (int parent_window_id, unsigned int x, unsigned int y, unsigned int width, unsigned int height)
void _MakeCurrent () const
Protected Attributes
int _x
int _y
int _width
int _height
int _window_id
bool _focused
Widget * _childwidget
bool _havechild
bool _dragging
int _last_x
int _last_y
int _current_button
Colour _clear_colour
Constructor & Destructor Documentation
Glute2::Window::Window (int w, int h, const std::string & title)
References VW::GLUTWindow::_CreateWindow(), and _window_id.
Glute2::Window::~Window () [virtual]
Member Function Documentation
int VW::GLUTWindow::_CreateSubwindow (int parent_window_id, unsigned int x, unsigned int y, unsigned int width, unsigned int height) [protected, inherited]
References GLUTAddWindow(), and GLUTRegisterCallbacks().
Referenced by VW::ThreeDToolGluteWidget::SetSize(), and VW::DisplayGluteWidget::SetSize().
int VW::GLUTWindow::_CreateWindow (unsigned int width, unsigned int height, const std::string & title) [protected, inherited]
References GLUTAddWindow(), GLUTRegisterCallbacks(), and VERBOSE.
Referenced by VW::DisplayGLUT::SetSize(), VW::ThreeDToolGLUT::ThreeDToolGLUT(), and Window().
void VW::GLUTWindow::_MakeCurrent () const [inline, protected, inherited]
Referenced by MakeCurrent(), VW::DisplayGluteWidget::MakeCurrent(), VW::DisplayGluteWidget::Resize(), VW::DisplayGluteWidget::SetSize(), and VW::DisplayGluteWidget::SwapBuffers().
void Glute2::Window::Add (Widget * child)
References _childwidget, _havechild, _height, _width, Glute2::Widget::GetMinimumHeight(), Glute2::Widget::GetMinimumWidth(), PADDING, Resize(), Glute2::Widget::SetParentWindow(), Glute2::Widget::SetPosition(), and Glute2::Widget::SetSize().
void Glute2::Window::Draw () [protected, virtual]
Implements VW::GLUTWindow.
References _childwidget, _clear_colour, _havechild, _height, _width, Glute2::Widget::Draw(), MakeCurrent(), Glute2::Colour::MakeCurrentClear(), and SwapBuffers().
Referenced by Resize(), and Show().
void Glute2::Window::Entry (int state) [protected, virtual]
void Glute2::Window::Flush (void)
void Glute2::Window::FullScreen ()
References _window_id.
unsigned int Glute2::Window::GetHeight (void) const [inline]
References _height.
Referenced by VW::ThreeDToolGluteWidget::Resize(), VW::DisplayGluteWidget::Resize(), VW::ThreeDToolGluteWidget::SetSize(), and VW::DisplayGluteWidget::SetSize().
int VW::GLUTWindow::GetID () const [inline, inherited]
Referenced by GLUTAddWindow(), VW::ThreeDToolGluteWidget::MakeCurrent(), VW::ThreeDToolGluteWidget::RequestDraw(), VW::ThreeDToolGluteWidget::Resize(), and VW::ThreeDToolGluteWidget::SwapBuffers().
unsigned int Glute2::Window::GetWidth (void) const [inline]
References _width.
int Glute2::Window::GetWindowID () const
References _window_id.
Referenced by VW::ThreeDToolGluteWidget::RequestDraw(), VW::ThreeDToolGluteWidget::Resize(), VW::DisplayGluteWidget::Resize(), VW::ThreeDToolGluteWidget::SetSize(), VW::DisplayGluteWidget::SetSize(), and VW::ThreeDToolGluteWidget::SwapBuffers().
void Glute2::Window::Hide ()
References _window_id.
void Glute2::Window::Iconify ()
References _window_id.
bool VW::GLUTWindow::IsMe (int i) const [inline, inherited]
Reimplemented in VW::DisplayGLUT, VW::ThreeDToolGLUT, VW::DisplayGluteWidget, and VW::ThreeDToolGluteWidget.
void Glute2::Window::Keyboard (unsigned char key, int x, int y) [protected, virtual]
Implements VW::GLUTWindow.
References _childwidget, _focused, _havechild, and Glute2::Widget::_KeyPress().
void Glute2::Window::MakeCurrent ()
References VW::GLUTWindow::_MakeCurrent().
Referenced by Draw(), Motion(), Mouse(), and PassiveMotion().
void Glute2::Window::Motion (int x, int y) [protected, virtual]
Implements VW::GLUTWindow.
References _childwidget, _current_button, Glute2::Widget::_Drag(), _dragging, _focused, _last_x, _last_y, Glute2::Widget::_NeedsRedraw(), Glute2::Widget::Draw(), MakeCurrent(), and SwapBuffers().
void Glute2::Window::Mouse (int button, int state, int x, int y) [protected, virtual]
Implements VW::GLUTWindow.
References _childwidget, _current_button, _dragging, _focused, _havechild, _last_x, _last_y, Glute2::Widget::_MousePressed(), Glute2::Widget::_MouseReleased(), Glute2::Widget::_NeedsRedraw(), Glute2::Widget::Draw(), MakeCurrent(), and SwapBuffers().
void Glute2::Window::PassiveMotion (int x, int y) [protected, virtual]
Implements VW::GLUTWindow.
References _childwidget, _focused, _havechild, _height, Glute2::Widget::_IsIn(), Glute2::Widget::_NeedsRedraw(), Glute2::Widget::_PassiveMotion(), Glute2::Widget::_SetFocus(), Glute2::Widget::Draw(), MakeCurrent(), and SwapBuffers().
void Glute2::Window::Pop ()
References _window_id.
void Glute2::Window::Position (int x, int y)
References _window_id, _x, and _y.
void Glute2::Window::Push ()
References _window_id.
void Glute2::Window::Redisplay ()
References _window_id.
void Glute2::Window::Resize (int w, int h) [protected, virtual]
Implements VW::GLUTWindow.
References _childwidget, _havechild, _height, _width, _window_id, Draw(), Glute2::Widget::GetMinimumHeight(), Glute2::Widget::GetMinimumWidth(), PADDING, and Glute2::Widget::SetSize().
Referenced by Add().
void Glute2::Window::SetClearColour (float r, float g, float b, float a)
References _clear_colour, and Glute2::Colour::Set().
void Glute2::Window::SetCursor (int cursor)
void VW::GLUTWindow::SetID (int id) [inline, inherited]
void Glute2::Window::Show ()
References _window_id, and Draw().
void Glute2::Window::Special (int key, int x, int y) [protected, virtual]
void Glute2::Window::SwapBuffers ()
Referenced by Draw(), Motion(), Mouse(), and PassiveMotion().
Member Data Documentation
Widget* Glute2::Window::_childwidget [protected]
Referenced by Add(), Draw(), Keyboard(), Motion(), Mouse(), PassiveMotion(), and Resize().
Colour Glute2::Window::_clear_colour [protected]
Referenced by Draw(), and SetClearColour().
int Glute2::Window::_current_button [protected]
Referenced by Motion(), and Mouse().
bool Glute2::Window::_dragging [protected]
Referenced by Motion(), and Mouse().
bool Glute2::Window::_focused [protected]
Referenced by Keyboard(), Motion(), Mouse(), and PassiveMotion().
bool Glute2::Window::_havechild [protected]
Referenced by Add(), Draw(), Keyboard(), Mouse(), PassiveMotion(), and Resize().
int Glute2::Window::_height [protected]
Referenced by Add(), Draw(), GetHeight(), PassiveMotion(), and Resize().
int Glute2::Window::_last_x [protected]
Referenced by Motion(), and Mouse().
int Glute2::Window::_last_y [protected]
Referenced by Motion(), and Mouse().
int Glute2::Window::_width [protected]
Referenced by Add(), Draw(), GetWidth(), and Resize().
int Glute2::Window::_window_id [protected]
Referenced by FullScreen(), GetWindowID(), Hide(), Iconify(), Pop(), Position(), Push(), Redisplay(), Resize(), Show(), and Window().
int Glute2::Window::_x [protected]
Referenced by Position().
int Glute2::Window::_y [protected]
Referenced by Position().
The documentation for this class was generated from the following files:
window.h
window.cpp