VW: VNL::BigNum Class Reference
VNL::BigNum Class Reference
Infinite precision integers.
#include <bignum.h>
Public Member Functions
BigNum ()
Creates a zero VNL::BigNum.
BigNum (long)
Creates a VNL::BigNum from a long integer.
BigNum (unsigned long)
Creates a VNL::BigNum from an unsigned long integer.
BigNum (int)
Creates a VNL::BigNum from an integer.
BigNum (unsigned int)
Creates a VNL::BigNum from an unsigned integer.
BigNum (double)
Creates a VNL::BigNum from a double floating point number.
BigNum (long double)
Creates a VNL::BigNum from a "long double" floating point number.
BigNum (BigNum const &)
Copies the contents of VNL::BigNum b.
BigNum (const char *)
Creates a VNL::BigNum from the character string representation.
~BigNum ()
Frees space for VNL::BigNum.
operator short () const
Implicit conversion from a VNL::BigNum to a short.
operator int () const
Implicit conversion from a VNL::BigNum to an int.
operator long () const
Implicit conversion from a VNL::BigNum to a long.
operator float () const
Implicit conversion from a VNL::BigNum to a float.
operator double () const
Implicit conversion from a VNL::BigNum to a double.
operator long double () const
Implicit conversion from a VNL::BigNum to a long double.
operator short ()
operator int ()
operator long ()
operator float ()
operator double ()
operator long double ()
BigNum operator- () const
Returns the negation of a VNL::BigNum.
BigNum operator+ ()
BigNum operator+ () const
BigNum & operator= (const BigNum &)
Copies rhs VNL::BigNum to lhs VNL::BigNum.
BigNum operator<< (int l) const
BigNum operator>> (int l) const
Shifts bignum to the left/right l digits.
BigNum operator+ (BigNum const &r) const
Adds two VNL::BigNums, and returns new sum.
BigNum & operator+= (BigNum const &r)
BigNum & operator-= (BigNum const &r)
BigNum & operator*= (BigNum const &r)
Multiplies this with a VNL::BigNum.
BigNum & operator/= (BigNum const &r)
Divides this by a VNL::BigNum.
BigNum & operator%= (BigNum const &r)
BigNum & operator<<= (int l)
BigNum & operator>>= (int l)
BigNum & operator++ ()
prefix increment (++b).
BigNum & operator-- ()
decrement.
BigNum operator++ (int)
postfix increment (b++).
BigNum operator-- (int)
decrement.
bool operator== (BigNum const &) const
Two VNL::BigNums are equal if and only if they have the same integer representation.
bool operator< (BigNum const &) const
Compares two VNL::BigNums.
bool operator!= (BigNum const &r) const
bool operator> (BigNum const &r) const
bool operator<= (BigNum const &r) const
bool operator>= (BigNum const &r) const
bool operator== (long r) const
bool operator!= (long r) const
bool operator< (long r) const
bool operator> (long r) const
bool operator<= (long r) const
bool operator>= (long r) const
bool operator== (int r) const
bool operator!= (int r) const
bool operator< (int r) const
bool operator> (int r) const
bool operator<= (int r) const
bool operator>= (int r) const
bool operator== (double r) const
bool operator!= (double r) const
bool operator< (double r) const
bool operator> (double r) const
bool operator<= (double r) const
bool operator>= (double r) const
bool operator== (long double r) const
bool operator!= (long double r) const
bool operator< (long double r) const
bool operator> (long double r) const
bool operator<= (long double r) const
bool operator>= (long double r) const
BigNum Abs () const
void Dump (std::ostream &=std::cout) const
dump the contents of a VNL::BigNum to a stream, default cout.
Friends
int MagnitudeCmp (const BigNum &, const BigNum &)
void Add (const BigNum &, const BigNum &, BigNum &)
void Subtract (const BigNum &, const BigNum &, BigNum &)
void MultiplyAux (const BigNum &, unsigned short, BigNum &, unsigned short)
unsigned short Normalize (const BigNum &, const BigNum &, BigNum &, BigNum &)
void DivideAux (const BigNum &, unsigned short, BigNum &, unsigned short &)
unsigned short EstimateQHat (const BigNum &, const BigNum &, unsigned short)
unsigned short MultiplySubtract (BigNum &, const BigNum &, unsigned short, unsigned short)
void Divide (const BigNum &, const BigNum &, BigNum &, BigNum &)
BigNum LeftShift (const BigNum &b1, int l)
BigNum RightShift (const BigNum &b1, int l)
std::ostream & operator<< (std::ostream &, const BigNum &)
std::istream & operator>> (std::istream &, BigNum &)
std::string & BigNumToString (std::string &s, const BigNum &b)
BigNum & BigNumFromString (BigNum &b, const std::string &s)
Detailed Description
Infinite precision integers.
The BigNum class implements near-infinite precision integers and arithmetic by using a dynamic bit vector. A BigNum object will grow in size as necessary to hold its integer value. Implicit conversion to the system defined types: short, int, long, float, double and long double is supported by overloaded operator member functions. Addition and subtraction operators are performed by simple bitwise addition and subtraction on unsigned short boundaries with checks for carry flag propagation. The multiplication, division, and remainder operations utilize the algorithms from Knuth's Volume 2 of "The Art of Computer Programming". However, despite the use of these algorithms and inline member functions, arithmetic operations on BigNum objects are considerably slower than the built-in integer types that use hardware integer arithmetic capabilities.
The BigNum class supports the parsing of character string representations of all the literal number formats. The following table shows an example of a character string representation on the left and a brief description of the interpreted meaning on the right:
Character String Interpreted Meaning 1234 1234 1234l 1234 1234L 1234 1234u 1234 1234U 1234 1234ul 1234 1234UL 1234 01234 1234 in octal (leading 0) 0x1234 1234 in hexadecimal (leading 0x) 0X1234 1234 in hexadecimal (leading 0X) 123.4 123 (value truncated) 1.234e2 123 (exponent expanded/truncated) 1.234e-5 0 (truncated value less than 1)
Constructor & Destructor Documentation
VNL::BigNum::BigNum ()
Creates a zero VNL::BigNum.
Referenced by operator!=(), operator<(), operator<<(), operator<=(), operator==(), operator>(), operator>=(), and operator>>().
VNL::BigNum::BigNum (long l)
Creates a VNL::BigNum from a long integer.
VNL::BigNum::BigNum (unsigned long l)
Creates a VNL::BigNum from an unsigned long integer.
VNL::BigNum::BigNum (int l)
Creates a VNL::BigNum from an integer.
VNL::BigNum::BigNum (unsigned int l)
Creates a VNL::BigNum from an unsigned integer.
VNL::BigNum::BigNum (double d)
Creates a VNL::BigNum from a double floating point number.
VNL::BigNum::BigNum (long double d)
Creates a VNL::BigNum from a "long double" floating point number.
VNL::BigNum::BigNum (BigNum const & b)
Copies the contents of VNL::BigNum b.
VNL::BigNum::BigNum (const char * s)
Creates a VNL::BigNum from the character string representation.
VNL::BigNum::~BigNum ()
Frees space for VNL::BigNum.
Member Function Documentation
BigNum VNL::BigNum::Abs () const [inline]
References operator-(), and operator<().
Referenced by VNL::Abs(), and std::abs().
void VNL::BigNum::Dump (std::ostream & os = std::cout) const
dump the contents of a VNL::BigNum to a stream, default cout.
VNL::BigNum::operator double () [inline]
VNL::BigNum::operator double () const
Implicit conversion from a VNL::BigNum to a double.
Referenced by operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
VNL::BigNum::operator float () [inline]
VNL::BigNum::operator float () const
Implicit conversion from a VNL::BigNum to a float.
VNL::BigNum::operator int () [inline]
VNL::BigNum::operator int () const
Implicit conversion from a VNL::BigNum to an int.
VNL::BigNum::operator long () [inline]
VNL::BigNum::operator long () const
Implicit conversion from a VNL::BigNum to a long.
VNL::BigNum::operator long double () [inline]
VNL::BigNum::operator long double () const
Implicit conversion from a VNL::BigNum to a long double.
Referenced by operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
VNL::BigNum::operator short () [inline]
VNL::BigNum::operator short () const
Implicit conversion from a VNL::BigNum to a short.
bool VNL::BigNum::operator!= (long double r) const [inline]
References operator long double().
bool VNL::BigNum::operator!= (double r) const [inline]
References operator double().
bool VNL::BigNum::operator!= (int r) const [inline]
References operator==().
bool VNL::BigNum::operator!= (long r) const [inline]
References BigNum(), and operator==().
bool VNL::BigNum::operator!= (BigNum const & r) const [inline]
References operator==().
VNL::BigNum & VNL::BigNum::operator%= (BigNum const & r)
References Divide.
VNL::BigNum & VNL::BigNum::operator*= (BigNum const & r)
Multiplies this with a VNL::BigNum.
References MultiplyAux.
VNL::BigNum VNL::BigNum::operator+ (BigNum const & r) const
Adds two VNL::BigNums, and returns new sum.
References Add, MagnitudeCmp, and Subtract.
BigNum VNL::BigNum::operator+ () const [inline]
BigNum VNL::BigNum::operator+ () [inline]
Referenced by operator+=(), and operator-=().
BigNum VNL::BigNum::operator++ (int) [inline]
postfix increment (b++).
References operator++().
Referenced by operator++().
VNL::BigNum & VNL::BigNum::operator++ ()
prefix increment (++b).
Prefix increment. Increments a VNL::BigNum by 1, and returns it.
BigNum& VNL::BigNum::operator+= (BigNum const & r) [inline]
References operator+().
VNL::BigNum VNL::BigNum::operator- () const
Returns the negation of a VNL::BigNum.
Referenced by Abs().
BigNum VNL::BigNum::operator-- (int) [inline]
decrement.
References operator--().
Referenced by operator--().
VNL::BigNum & VNL::BigNum::operator-- ()
decrement.
Prefix decrement. Decrements a VNL::BigNum by 1, and returns it.
BigNum& VNL::BigNum::operator-= (BigNum const & r) [inline]
References operator+().
VNL::BigNum & VNL::BigNum::operator/= (BigNum const & r)
Divides this by a VNL::BigNum.
References Divide.
bool VNL::BigNum::operator< (long double r) const [inline]
References operator long double().
bool VNL::BigNum::operator< (double r) const [inline]
References operator double().
bool VNL::BigNum::operator< (int r) const [inline]
References operator<().
Referenced by operator<().
bool VNL::BigNum::operator< (long r) const [inline]
References BigNum(), and operator<().
Referenced by operator<().
bool VNL::BigNum::operator< (BigNum const & rhs) const
Compares two VNL::BigNums.
References MagnitudeCmp.
Referenced by Abs(), and operator>=().
VNL::BigNum VNL::BigNum::operator<< (int l) const
References BigNum(), LeftShift, and RightShift.
BigNum& VNL::BigNum::operator<<= (int l) [inline]
bool VNL::BigNum::operator<= (long double r) const [inline]
References operator long double().
bool VNL::BigNum::operator<= (double r) const [inline]
References operator double().
bool VNL::BigNum::operator<= (int r) const [inline]
References operator>().
bool VNL::BigNum::operator<= (long r) const [inline]
References BigNum(), and operator>().
bool VNL::BigNum::operator<= (BigNum const & r) const [inline]
References operator>().
VNL::BigNum & VNL::BigNum::operator= (const BigNum & rhs)
Copies rhs VNL::BigNum to lhs VNL::BigNum.
bool VNL::BigNum::operator== (long double r) const [inline]
References operator long double().
bool VNL::BigNum::operator== (double r) const [inline]
References operator double().
bool VNL::BigNum::operator== (int r) const [inline]
References operator==().
Referenced by operator==().
bool VNL::BigNum::operator== (long r) const [inline]
References BigNum(), and operator==().
Referenced by operator==().
bool VNL::BigNum::operator== (BigNum const & rhs) const
Two VNL::BigNums are equal if and only if they have the same integer representation.
Referenced by operator!=().
bool VNL::BigNum::operator> (long double r) const [inline]
References operator long double().
bool VNL::BigNum::operator> (double r) const [inline]
References operator double().
bool VNL::BigNum::operator> (int r) const [inline]
References BigNum().
bool VNL::BigNum::operator> (long r) const [inline]
References BigNum().
bool VNL::BigNum::operator> (BigNum const & r) const [inline]
Referenced by operator<=().
bool VNL::BigNum::operator>= (long double r) const [inline]
References operator long double().
bool VNL::BigNum::operator>= (double r) const [inline]
References operator double().
bool VNL::BigNum::operator>= (int r) const [inline]
References operator<().
bool VNL::BigNum::operator>= (long r) const [inline]
References BigNum(), and operator<().
bool VNL::BigNum::operator>= (BigNum const & r) const [inline]
References operator<().
VNL::BigNum VNL::BigNum::operator>> (int l) const
Shifts bignum to the left/right l digits.
References BigNum(), LeftShift, and RightShift.
BigNum& VNL::BigNum::operator>>= (int l) [inline]
Friends And Related Function Documentation
void Add (const BigNum & , const BigNum & , BigNum &) [friend]
Referenced by operator+().
BigNum& BigNumFromString (BigNum & b, const std::string & s) [friend]
std::string& BigNumToString (std::string & s, const BigNum & b) [friend]
void Divide (const BigNum & , const BigNum & , BigNum & , BigNum &) [friend]
Referenced by operator%=(), and operator/=().
void DivideAux (const BigNum & , unsigned short, BigNum & , unsigned short &) [friend]
unsigned short EstimateQHat (const BigNum & , const BigNum & , unsigned short) [friend]
BigNum LeftShift (const BigNum & b1, int l) [friend]
Referenced by operator<<(), and operator>>().
int MagnitudeCmp (const BigNum & , const BigNum &) [friend]
Referenced by operator+(), and operator<().
void MultiplyAux (const BigNum & , unsigned short, BigNum & , unsigned short) [friend]
Referenced by operator*=().
unsigned short MultiplySubtract (BigNum & , const BigNum & , unsigned short, unsigned short) [friend]
unsigned short Normalize (const BigNum & , const BigNum & , BigNum & , BigNum &) [friend]
std::ostream& operator<< (std::ostream & , const BigNum &) [friend]
std::istream& operator>> (std::istream & , BigNum &) [friend]
BigNum RightShift (const BigNum & b1, int l) [friend]
Referenced by operator<<(), and operator>>().
void Subtract (const BigNum & , const BigNum & , BigNum &) [friend]
Referenced by operator+().
The documentation for this class was generated from the following files:
bignum.h
bignum.cpp