VW: VW::Homography2DComputeNonLinear Class Reference
VW::Homography2DComputeNonLinear Class Reference
#include <homography2dcomputenonlinear.h>
Public Member Functions
Homography2DComputeNonLinear (double error_tolerance=DEFAULT_TOLERANCE, unsigned int max_iters=DEFAULT_MAXITERS)
bool Compute (Homography2D &result, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1)
Compute from two lists of corresponding points.
bool Compute (Homography2D &result, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const std::vector< unsigned int > &whichfeatures)
Compute from selected entries of two lists of corresponding points.
bool Compute (Homography2D &result, const std::vector< VW::Line2D > &l0, const std::vector< VW::Line2D > &l1)
Compute from two lists of corresponding lines.
bool Compute (Homography2D &result, const std::vector< VW::Line2D > &l0, const std::vector< VW::Line2D > &l1, const std::vector< unsigned int > &whichfeatures)
Compute from selected entries of two lists of corresponding lines.
Constructor & Destructor Documentation
VW::Homography2DComputeNonLinear::Homography2DComputeNonLinear (double error_tolerance = DEFAULT_TOLERANCE, unsigned int max_iters = DEFAULT_MAXITERS) [inline]
Member Function Documentation
bool VW::Homography2DComputeNonLinear::Compute (VW::Homography2D & result, const std::vector< VW::Line2D > & l0, const std::vector< VW::Line2D > & l1, const std::vector< unsigned int > & whichfeatures)
Compute from selected entries of two lists of corresponding lines.
bool VW::Homography2DComputeNonLinear::Compute (VW::Homography2D & result, const std::vector< VW::Line2D > & l0, const std::vector< VW::Line2D > & l1)
Compute from two lists of corresponding lines.
References Compute().
bool VW::Homography2DComputeNonLinear::Compute (VW::Homography2D & result, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const std::vector< unsigned int > & whichfeatures)
Compute from selected entries of two lists of corresponding points.
References VW::ComputeFuncs::ConvertParamVectorToTransform(), VW::ComputeFuncs::ConvertTransformToParamVector(), VNL::LevenbergMarquardt::Minimize(), VNL::NonlinearMinimizer::SetFTolerance(), and VNL::NonlinearMinimizer::SetMaxFunctionEvals().
bool VW::Homography2DComputeNonLinear::Compute (VW::Homography2D & result, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1)
Compute from two lists of corresponding points.
Referenced by Compute().
The documentation for this class was generated from the following files:
homography2dcomputenonlinear.h
homography2dcomputenonlinear.cpp