VW: VW::EssentialMatrixCompute5Point Class Reference
VW::EssentialMatrixCompute5Point Class Reference
[GeometricAlgorithms]
EssentialMatrixCompute5Point.
#include <essentialmatrixcompute5point.h>
Public Member Functions
EssentialMatrixCompute5Point (const bool normalise=true)
Create a linear computation object.
bool Compute (std::vector< EssentialMatrix > &ematrices, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1)
Compute essential matrices from two lists of 2D point features.
bool Compute (std::vector< EssentialMatrix > &ematrices, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const std::vector< unsigned int > &which_features)
Compute an fmatrix from two lists of 2D point features.
Detailed Description
EssentialMatrixCompute5Point.
Author:
G Vogiatzis, BJ Tordoff
Date:
19/04/2005 Five point minimal-set algorithm for computing essential matrices. Using only five correspondences results in a 4D nullspace and requires solution of a 10th degree polynomial (and hence produces between 0 and 10 essential matrices). Despite this, it's actually very fast!
Ref: Nister, D. ICCV2003 "An efficient solution to the five-point relative pose problem" (see also his thesis)
Constructor & Destructor Documentation
VW::EssentialMatrixCompute5Point::EssentialMatrixCompute5Point (const bool normalise = true) [inline]
Create a linear computation object.
Note that the calculation can involve a normalisation, so it is not necessary to pre-normalise the input points/lines (although it doesn't hurt).
Member Function Documentation
bool VW::EssentialMatrixCompute5Point::Compute (std::vector< EssentialMatrix > & ematrices, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const std::vector< unsigned int > & which_features)
Compute an fmatrix from two lists of 2D point features.
Note that x0, x1 are defined such that x_1 E x_0 = 0.
Parameters:
which_features a list of the indices of feature-pairs to use
Returns:
false if no solutions are found
References VW::EssentialMatrixCompute::AddToDesignMatrix(), VW::Normalisation::Init(), VW::Normalisation::Normalise(), and VERBOSE.
bool VW::EssentialMatrixCompute5Point::Compute (std::vector< EssentialMatrix > & ematrices, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1)
Compute essential matrices from two lists of 2D point features.
Note that x0, x1 are defined such that x_1 E x_0 = 0. Returns false if no solutions could be found.
References VW::EssentialMatrixCompute::AddToDesignMatrix(), VW::Normalisation::Init(), VW::Normalisation::Normalise(), and VERBOSE.
Referenced by VW::EssentialMatrixComputePreemptive::Compute().
The documentation for this class was generated from the following files:
essentialmatrixcompute5point.h
essentialmatrixcompute5point.cpp