VW: VW::ConvolutionMask1D< maskType > Class Template Reference
VW::ConvolutionMask1D< maskType > Class Template Reference
#include <convolve.h>
Public Member Functions
ConvolutionMask1D (int n=1)
ConvolutionMask1D (maskType x1, maskType x2, maskType x3)
ConvolutionMask1D (maskType x1, maskType x2, maskType x3, maskType x4, maskType x5)
ConvolutionMask1D (maskType *x, int n)
ConvolutionMask1D (ConvolutionMask1D &c)
~ConvolutionMask1D ()
int GetHalfWidth () const
maskType GetWeight () const
int Symmetry () const
void MakeGaussian (double sigma)
Set this mask to be a Gaussian kernel of standard deviation sigma.
void MakeUniform ()
Set this mask to be a uniform kernel (all values=1/n).
Public Attributes
maskType * mask
Detailed Description
template<class maskType>
class VW::ConvolutionMask1D< maskType >
Author:
ID Reid, DW Murray
Date:
02/08/2002 @ Brief A class to store the mask for use in a convolution (note that the mask is the reverse of the signal --- it's backwards!).
Constructor & Destructor Documentation
template<class maskType > VW::ConvolutionMask1D< maskType >::ConvolutionMask1D (int n = 1) [inline]
References VW::ConvolutionMask1D< maskType >::mask, and NO_SYMMETRY.
template<class maskType> VW::ConvolutionMask1D< maskType >::ConvolutionMask1D (maskType x1, maskType x2, maskType x3) [inline]
References EVEN_SYMMETRY, VW::ConvolutionMask1D< maskType >::mask, NO_SYMMETRY, and ODD_SYMMETRY.
template<class maskType> VW::ConvolutionMask1D< maskType >::ConvolutionMask1D (maskType x1, maskType x2, maskType x3, maskType x4, maskType x5) [inline]
References EVEN_SYMMETRY, VW::ConvolutionMask1D< maskType >::mask, NO_SYMMETRY, and ODD_SYMMETRY.
template<class maskType> VW::ConvolutionMask1D< maskType >::ConvolutionMask1D (maskType * x, int n) [inline]
References EVEN_SYMMETRY, VW::ConvolutionMask1D< maskType >::mask, NO_SYMMETRY, and ODD_SYMMETRY.
template<class maskType> VW::ConvolutionMask1D< maskType >::ConvolutionMask1D (ConvolutionMask1D< maskType > & c) [inline]
References VW::ConvolutionMask1D< maskType >::mask.
template<class maskType > VW::ConvolutionMask1D< maskType >::~ConvolutionMask1D () [inline]
References VW::ConvolutionMask1D< maskType >::mask.
Member Function Documentation
template<class maskType> int VW::ConvolutionMask1D< maskType >::GetHalfWidth () const [inline]
Referenced by VW::PlesseyDetector::Compute().
template<class maskType> maskType VW::ConvolutionMask1D< maskType >::GetWeight () const [inline]
template<class maskType > void VW::ConvolutionMask1D< maskType >::MakeGaussian (double sigma) [inline]
Set this mask to be a Gaussian kernel of standard deviation sigma.
References EVEN_SYMMETRY, VW::ConvolutionMask1D< maskType >::mask, and ZERO_SIGMA_THRES.
Referenced by VW::PyramidYUV< StorageType >::Compute(), VW::Pyramid< StorageType >::Compute(), VW::PlesseyDetector::Compute(), VW::Canny::Compute(), GenerallySmooth(), and VW::SmoothGaussian::SmoothGaussian().
template<class maskType > void VW::ConvolutionMask1D< maskType >::MakeUniform () [inline]
Set this mask to be a uniform kernel (all values=1/n).
References EVEN_SYMMETRY, and VW::ConvolutionMask1D< maskType >::mask.
template<class maskType> int VW::ConvolutionMask1D< maskType >::Symmetry () const [inline]
Member Data Documentation
template<class maskType> maskType* VW::ConvolutionMask1D< maskType >::mask
Referenced by VW::PlesseyDetector::Compute(), VW::ConvolutionMask1D< maskType >::ConvolutionMask1D(), GenerallySmooth(), VW::ConvolutionMask1D< maskType >::MakeGaussian(), VW::ConvolutionMask1D< maskType >::MakeUniform(), and VW::ConvolutionMask1D< maskType >::~ConvolutionMask1D().
The documentation for this class was generated from the following files:
VW/Improc/convolve.h
convolve.cpp