VW: VW::ConvexHull2D Class Reference
VW::ConvexHull2D Class Reference
[GeometricAlgorithms]
Computation of the convex hull of a set of 2D points.
#include <convexhull2d.h>
Public Member Functions
ConvexHull2D ()
Construct only.
ConvexHull2D (const std::vector< VW::Point2D > &input_points)
Construct and compute, storing the data internally.
ConvexHull2D (const std::vector< VW::Point2D > &input_points, std::vector< VW::Point2D > &output_points)
Construct and compute, returning a list of points on the hull ordered clockwise.
ConvexHull2D (const std::vector< VW::Point2D > &input_points, std::vector< unsigned int > &hull_indices)
Construct and compute, returning the indices of points on the hull ordered clockwise.
bool Compute (const std::vector< VW::Point2D > &input_points, std::vector< VW::Point2D > &output_points)
Compute, returning a list of points on the hull ordered clockwise.
bool Compute (const std::vector< VW::Point2D > &input_points, std::vector< unsigned int > &hull_indices)
Compute, returning the indices of points on the hull ordered clockwise.
Protected Member Functions
double _IsClockwise (const VW::Point2D &p, const VW::Point2D &q, const VW::Point2D &r) const
Return positive if p-q-r are clockwise, neg if ccw, zero if colinear.
Protected Attributes
bool _have_hull
std::vector< VW::Point2D > _hull
Detailed Description
Computation of the convex hull of a set of 2D points.
Author:
BJ Tordoff
Date:
03/02/2004 The input is always a set of VW::Point2D's, but the output can either be a list of indices into this array, or a new array containing the points on the hull.
Computation time is approximately n^2 + n*log(n) for best case, and 2*n^2 at worst. The convex hull computation itself is just n*log(n) (if I coded it right), but requires pre-sorted corner lists, which can take up to n^2 operations. If the points happen to be in y-index order (such as output from corner detection), the sort will be pretty quick.
Constructor & Destructor Documentation
VW::ConvexHull2D::ConvexHull2D ()
Construct only.
VW::ConvexHull2D::ConvexHull2D (const std::vector< VW::Point2D > & input_points)
Construct and compute, storing the data internally.
### What use is this? - at present you can't access the stored data!
References _hull, and Compute().
VW::ConvexHull2D::ConvexHull2D (const std::vector< VW::Point2D > & input_points, std::vector< VW::Point2D > & output_points)
Construct and compute, returning a list of points on the hull ordered clockwise.
References Compute().
VW::ConvexHull2D::ConvexHull2D (const std::vector< VW::Point2D > & input_points, std::vector< unsigned int > & hull_indices)
Construct and compute, returning the indices of points on the hull ordered clockwise.
References Compute().
Member Function Documentation
double VW::ConvexHull2D::_IsClockwise (const VW::Point2D & p, const VW::Point2D & q, const VW::Point2D & r) const [protected]
Return positive if p-q-r are clockwise, neg if ccw, zero if colinear.
References VW::Point2D::GetX(), and VW::Point2D::GetY().
Referenced by Compute().
bool VW::ConvexHull2D::Compute (const std::vector< VW::Point2D > & input_points, std::vector< unsigned int > & hull_indices)
Compute, returning the indices of points on the hull ordered clockwise.
References _have_hull, _IsClockwise(), and VERBOSE.
bool VW::ConvexHull2D::Compute (const std::vector< VW::Point2D > & input_points, std::vector< VW::Point2D > & output_points)
Compute, returning a list of points on the hull ordered clockwise.
Referenced by ConvexHull2D().
Member Data Documentation
bool VW::ConvexHull2D::_have_hull [protected]
Referenced by Compute().
std::vector<VW::Point2D> VW::ConvexHull2D::_hull [protected]
Referenced by ConvexHull2D().
The documentation for this class was generated from the following files:
convexhull2d.h
convexhull2d.cpp