VW: VNL::RealEigensystem Class Reference
VNL::RealEigensystem Class Reference
Extract eigensystem of unsymmetric matrix M, using the EISPACK routine.
#include <realeigensystem.h>
Public Member Functions
RealEigensystem (Matrix< double > const &M)
Extract eigensystem of unsymmetric matrix M, using the EISPACK routine rg.
Public Attributes
Matrix< double > Vreal
Matrix< std::complex< double > > V
Output matrix of eigenvectors, which will in general be complex.
DiagMatrix< std::complex
< double > > D
Output diagonal matrix of eigenvalues.
Detailed Description
Extract eigensystem of unsymmetric matrix M, using the EISPACK routine.
vnl_eigensystem is a full-bore real eigensystem. If your matrix is symmetric, it is *much* better to use vnl_symmetric_eigensystem.
Constructor & Destructor Documentation
VNL::RealEigensystem::RealEigensystem (VNL::Matrix< double > const & M)
Extract eigensystem of unsymmetric matrix M, using the EISPACK routine rg.
Should probably switch to using LAPACK's dgeev to avoid transposing.
References c, VNL::Matrix< T >::Columns(), D, VNL::Matrix< T >::DataBlock(), VNL::Vector< T >::DataBlock(), rg_(), VNL::Matrix< T >::Rows(), V, and Vreal.
Member Data Documentation
DiagMatrix<std::complex<double> > VNL::RealEigensystem::D
Output diagonal matrix of eigenvalues.
Referenced by RealEigensystem().
Matrix<std::complex<double> > VNL::RealEigensystem::V
Output matrix of eigenvectors, which will in general be complex.
Referenced by RealEigensystem().
Matrix<double> VNL::RealEigensystem::Vreal
Referenced by RealEigensystem().
The documentation for this class was generated from the following files:
realeigensystem.h
realeigensystem.cpp