VW: VW::DOGDetector Class Reference
VW::DOGDetector Class Reference
#include <dogdetector.h>
Public Member Functions
DOGDetector (DOGDetectorParams parameters=DOGDetectorParams())
Construct and set parameters only.
DOGDetector (const VW::Pyramid< float > &pyramid, std::vector< CornerFeature > &features, DOGDetectorParams parameters=DOGDetectorParams())
Construct and detect corners.
DOGDetector (const VW::Pyramid< float > &pyramid, CornerFeature &best_feature, DOGDetectorParams parameters=DOGDetectorParams())
Construct and detect the single strongest feature.
DOGDetector (const VW::ImageMono< unsigned char > &image, CornerFeature &best_feature, DOGDetectorParams parameters=DOGDetectorParams())
Construct and detect the single strongest feature.
~DOGDetector ()
void Compute (const VW::Pyramid< float > &pyramid, std::vector< CornerFeature > &features)
Compute features from a pyramid using pre-set params.
void Compute (const VW::Pyramid< float > &pyramid, CornerFeature &best_feature)
Compute single best feature from a pyramid using pre-set params.
void Compute (const VW::ImageMono< unsigned char > &image, CornerFeature &best_feature)
Compute single best feature from a single image using pre-set params.
void SetParams (const DOGDetectorParams &new_params)
void SetMaxNumFeatures (unsigned int new_maximum)
Set the maximum number of features (note that a high curvature threshold may cause many fewer than this to be detected).
void SetCurvatureThreshold (float max_curvature_ratio)
Curvature threshold controls the maximum ratio between the maximum and minimum curvatures for a location (a corner has high curvature in all directions).
Constructor & Destructor Documentation
VW::DOGDetector::DOGDetector (VW::DOGDetectorParams parameters = DOGDetectorParams()) [inline]
Construct and set parameters only.
VW::DOGDetector::DOGDetector (const VW::Pyramid< float > & pyramid, std::vector< CornerFeature > & features, VW::DOGDetectorParams parameters = DOGDetectorParams()) [inline]
Construct and detect corners.
References Compute().
VW::DOGDetector::DOGDetector (const VW::Pyramid< float > & pyramid, CornerFeature & best_feature, DOGDetectorParams parameters = DOGDetectorParams()) [inline]
Construct and detect the single strongest feature.
References Compute().
VW::DOGDetector::DOGDetector (const VW::ImageMono< unsigned char > & image, CornerFeature & best_feature, DOGDetectorParams parameters = DOGDetectorParams()) [inline]
Construct and detect the single strongest feature.
References Compute().
VW::DOGDetector::~DOGDetector () [inline]
Member Function Documentation
void VW::DOGDetector::Compute (const VW::ImageMono< unsigned char > & image, CornerFeature & best_feature)
Compute single best feature from a single image using pre-set params.
References VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), and VERBOSE.
void VW::DOGDetector::Compute (const VW::Pyramid< float > & pyramid, CornerFeature & best_feature)
Compute single best feature from a pyramid using pre-set params.
References VW::Pyramid< StorageType >::GetHeight(), VW::Pyramid< StorageType >::GetMinSize(), VW::Pyramid< StorageType >::GetNumLevelsPerOctave(), VW::Pyramid< StorageType >::GetWidth(), and VERBOSE.
void VW::DOGDetector::Compute (const VW::Pyramid< float > & pyramid, std::vector< CornerFeature > & features)
Compute features from a pyramid using pre-set params.
References VW::Pyramid< StorageType >::GetHeight(), VW::Pyramid< StorageType >::GetMinSize(), VW::Pyramid< StorageType >::GetNumLevelsPerOctave(), VW::Pyramid< StorageType >::GetWidth(), VW::DOGDetectorParams::max_curvature_ratio, VW::DOGDetectorParams::max_features, and VERBOSE.
Referenced by DOGDetector().
void VW::DOGDetector::SetCurvatureThreshold (float max_curvature_ratio) [inline]
Curvature threshold controls the maximum ratio between the maximum and minimum curvatures for a location (a corner has high curvature in all directions).
References VW::DOGDetectorParams::max_curvature_ratio.
void VW::DOGDetector::SetMaxNumFeatures (unsigned int new_maximum) [inline]
Set the maximum number of features (note that a high curvature threshold may cause many fewer than this to be detected).
References VW::DOGDetectorParams::max_features.
void VW::DOGDetector::SetParams (const DOGDetectorParams & new_params) [inline]
The documentation for this class was generated from the following files:
dogdetector.h
dogdetector.cpp