VW: vnl_scalar_join_iterator< T > Class Template Reference
vnl_scalar_join_iterator< T > Class Template Reference
Database join on matrix columns.
#include <scalarjoiniterator.h>
Public Member Functions
vnl_scalar_join_iterator (const vnl_matrix< T > &relation1, unsigned column1, const vnl_matrix< T > &relation2, unsigned column2)
Initialize this iterator to the join of relation1(:,column1) and relation2(:,column2).
~vnl_scalar_join_iterator ()
Destructor.
operator bool ()
Return true if all pairs have been seen.
vnl_scalar_join_iterator< T > & operator++ ()
Advance to the next pair. This is prefix ++.
bool done ()
void next ()
Increment the iterator to point to the next pair of rows.
unsigned row1 ()
Return the indices of the current rows in the first and second relations.
unsigned row2 ()
Return the indices of the current rows in the first and second relations.
Protected Attributes
unsigned n1
unsigned n2
vcl_list
< vnl_scalar_join_iterator_indexed_pair
< T > > * pI1
vcl_list
< vnl_scalar_join_iterator_indexed_pair
< T > > * pI2
vcl_list
< vnl_scalar_join_iterator_indexed_pair
< T > > & I1
vcl_list
< vnl_scalar_join_iterator_indexed_pair
< T > > & I2
vcl_list
< vnl_scalar_join_iterator_indexed_pair
< T > >::iterator index1
vcl_list
< vnl_scalar_join_iterator_indexed_pair
< T > >::iterator index2
Detailed Description
template<class T>
class vnl_scalar_join_iterator< T >
Database join on matrix columns.
vnl_scalar_join_iterator implements a fast database join on columns of matrices of scalars. "Scalar" here really means that the objects have comparison operators. The cost is O(n log n) where n is the number of rows, all for the two sorts in the ctor.
CAVEAT: The current implementation fudges multiple occurrences of the same key in the source column. For example,
    join  1 3 and  3 5 on columns 2 and 1 respectively
          2 3      3 6
should give
          1 3 3 5
          1 3 3 6
          2 3 3 5
          2 3 3 6
and it doesn't. Contact awf if you need this to work.
Constructor & Destructor Documentation
template<class T > vnl_scalar_join_iterator< T >::vnl_scalar_join_iterator (const vnl_matrix< T > & relation1, unsigned column1, const vnl_matrix< T > & relation2, unsigned column2) [inline]
Initialize this iterator to the join of relation1(:,column1) and relation2(:,column2).
The algorithm sorts an array of pointers to each row and traversal of the iterator runs through these to produce the join. After construction the row1() and row2() methods indicate the first pair.
template<class T > vnl_scalar_join_iterator< T >::~vnl_scalar_join_iterator () [inline]
Destructor.
References vnl_scalar_join_iterator< T >::pI1, and vnl_scalar_join_iterator< T >::pI2.
Member Function Documentation
template<class T > bool vnl_scalar_join_iterator< T >::done () [inline]
References vnl_scalar_join_iterator< T >::I1, vnl_scalar_join_iterator< T >::I2, vnl_scalar_join_iterator< T >::index1, and vnl_scalar_join_iterator< T >::index2.
Referenced by vnl_scalar_join_iterator< T >::next(), and vnl_scalar_join_iterator< T >::operator bool().
template<class T > void vnl_scalar_join_iterator< T >::next () [inline]
Increment the iterator to point to the next pair of rows.
References vnl_scalar_join_iterator< T >::done(), vnl_scalar_join_iterator< T >::I2, vnl_scalar_join_iterator< T >::index1, and vnl_scalar_join_iterator< T >::index2.
Referenced by vnl_scalar_join_iterator< T >::operator++().
template<class T> vnl_scalar_join_iterator< T >::operator bool () [inline]
Return true if all pairs have been seen.
References vnl_scalar_join_iterator< T >::done().
template<class T> vnl_scalar_join_iterator<T>& vnl_scalar_join_iterator< T >::operator++ () [inline]
Advance to the next pair. This is prefix ++.
References vnl_scalar_join_iterator< T >::next().
template<class T > unsigned vnl_scalar_join_iterator< T >::row1 () [inline]
Return the indices of the current rows in the first and second relations.
template<class T > unsigned vnl_scalar_join_iterator< T >::row2 () [inline]
Return the indices of the current rows in the first and second relations.
Member Data Documentation
template<class T> vcl_list<vnl_scalar_join_iterator_indexed_pair<T> >& vnl_scalar_join_iterator< T >::I1 [protected]
Referenced by vnl_scalar_join_iterator< T >::done().
template<class T> vcl_list<vnl_scalar_join_iterator_indexed_pair<T> >& vnl_scalar_join_iterator< T >::I2 [protected]
Referenced by vnl_scalar_join_iterator< T >::done(), and vnl_scalar_join_iterator< T >::next().
template<class T> vcl_list<vnl_scalar_join_iterator_indexed_pair<T> >::iterator vnl_scalar_join_iterator< T >::index1 [protected]
Referenced by vnl_scalar_join_iterator< T >::done(), and vnl_scalar_join_iterator< T >::next().
template<class T> vcl_list<vnl_scalar_join_iterator_indexed_pair<T> >::iterator vnl_scalar_join_iterator< T >::index2 [protected]
Referenced by vnl_scalar_join_iterator< T >::done(), and vnl_scalar_join_iterator< T >::next().
template<class T> unsigned vnl_scalar_join_iterator< T >::n1 [protected]
template<class T> unsigned vnl_scalar_join_iterator< T >::n2 [protected]
template<class T> vcl_list<vnl_scalar_join_iterator_indexed_pair<T> >* vnl_scalar_join_iterator< T >::pI1 [protected]
Referenced by vnl_scalar_join_iterator< T >::~vnl_scalar_join_iterator().
template<class T> vcl_list<vnl_scalar_join_iterator_indexed_pair<T> >* vnl_scalar_join_iterator< T >::pI2 [protected]
Referenced by vnl_scalar_join_iterator< T >::~vnl_scalar_join_iterator().
The documentation for this class was generated from the following files:
scalarjoiniterator.h
scalarjoiniterator.tpp