VW: VW::PyramidYUV< StorageType > Class Template Reference
VW::PyramidYUV< StorageType > Class Template Reference
[ImageProcessing]
Construct an image pyramid from a YUV image.
#include <pyramidyuv.h>
Public Member Functions
PyramidYUV ()
Default constructor.
template<class ImageType >
PyramidYUV (const ImageType &im, unsigned int minsize=32, unsigned int num_levels_per_octave=1, bool quick_and_dirty=false)
Construct and compute (note that the pyramid is monochrome regardless of the input image type).
~PyramidYUV ()
template<class ImageType >
void Compute (const ImageType &im, unsigned int minsize=32, unsigned int num_levels_per_octave=1, bool quick_and_dirty=false)
Compute the pyramid based on the supplied image (note that the pyramid is YUV regardless of the input image type).
unsigned int NumLevels () const
The number of levels (images) contained in this pyramid.
unsigned int GetWidth (unsigned int which_level=0) const
The width of the specified level (or the largest width if not specified).
unsigned int GetHeight (unsigned int which_level=0) const
The height of the specified level (or the largest height if not specified).
const std::vector< ImageYUV
< StorageType > * > & Level () const
Get access to the array of images.
const ImageYUV< StorageType > & operator[] (int i) const
Access a particular level (read only).
ImageYUV< StorageType > & operator[] (int i)
Access a particular level (read/write).
float ScalingFactor () const
The scale factor between successive levels (0.5 for sumbsample by 2).
float GetScale (unsigned int which_level) const
Get the sclae factor associated with a level of the pyramid (this is the ratio of the image size compared to the base image size, and is always less than 1).
Protected Member Functions
void _AverageAndSubsampleBy2 (const VW::ImageYUV< StorageType > &source_image, VW::ImageYUV< StorageType > &dest_image)
A function to combine smoothing and subsampling in a quick and dirty fashion.
Protected Attributes
unsigned int num_levels
float scaling_factor
std::vector< ImageYUV
< StorageType > * > level
Detailed Description
template<class StorageType>
class VW::PyramidYUV< StorageType >
Construct an image pyramid from a YUV image.
Author:
BJ Tordoff
Date:
10/08/2004 The YUV image pyramid consists of subsampled octaves of the base image. Subsampling can be performed either using the correct method of Gaussian smoothing at the nyquist frequency followed by decimation, or using the faster method of averaging 2x2 blocks of pixels before decimation.
Constructor & Destructor Documentation
template<class StorageType > VW::PyramidYUV< StorageType >::PyramidYUV () [inline]
Default constructor.
If you do not supply an image at object creation, you will have to subsequently call one of the compute methods below.
template<class StorageType > template<class ImageType > VW::PyramidYUV< StorageType >::PyramidYUV (const ImageType & im, unsigned int minsize = 32, unsigned int num_levels_per_octave = 1, bool quick_and_dirty = false) [inline]
Construct and compute (note that the pyramid is monochrome regardless of the input image type).
This constructs the object and calls the compute function with (optional) parameters for size, number of levels etc.
References VW::PyramidYUV< StorageType >::Compute().
template<class StorageType > VW::PyramidYUV< StorageType >::~PyramidYUV () [inline]
References VW::PyramidYUV< StorageType >::level, and VW::PyramidYUV< StorageType >::num_levels.
Member Function Documentation
template<class StorageType > void PyramidYUV::_AverageAndSubsampleBy2 (const VW::ImageYUV< StorageType > & source_image, VW::ImageYUV< StorageType > & dest_image) [inline, protected]
A function to combine smoothing and subsampling in a quick and dirty fashion.
References VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::AllocImageData(), alpha, VW::PixelYUV< Type >::alpha, c, VW::ROI::Get(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetROIRowStart(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::IsAlloced(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::ROI(), VW::ROI::Set(), VW::PixelYUV< Type >::u, v, VW::PixelYUV< Type >::v, and VW::PixelYUV< Type >::y.
Referenced by VW::PyramidYUV< StorageType >::Compute().
template<class StorageType > template<class ImageType > void PyramidYUV::Compute (const ImageType & im, unsigned int minsize = 32, unsigned int num_levels_per_octave = 1, bool quick_and_dirty = false) [inline]
Compute the pyramid based on the supplied image (note that the pyramid is YUV regardless of the input image type).
Only call the compute function if you didn't construct the object with an image. If quick and dirty is false (default) then Ian's method is used, where convolution is with an approximately Gaussian kernel. The alternative method just averages 2x2 blocks of pixels, which may give some marginal speed improvements.
References VW::PyramidYUV< StorageType >::_AverageAndSubsampleBy2(), VW::Bilinear, VW::ScaleImage::Compute(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), VW::ImageCopy(), VW::PyramidYUV< StorageType >::level, VW::ConvolutionMask1D< maskType >::MakeGaussian(), VW::PyramidYUV< StorageType >::num_levels, and VW::PyramidYUV< StorageType >::scaling_factor.
Referenced by VW::PyramidYUV< StorageType >::PyramidYUV().
template<class StorageType > unsigned int VW::PyramidYUV< StorageType >::GetHeight (unsigned int which_level = 0) const [inline]
The height of the specified level (or the largest height if not specified).
References VW::PyramidYUV< StorageType >::level.
template<class StorageType > float VW::PyramidYUV< StorageType >::GetScale (unsigned int which_level) const [inline]
Get the sclae factor associated with a level of the pyramid (this is the ratio of the image size compared to the base image size, and is always less than 1).
References VW::PyramidYUV< StorageType >::scaling_factor.
template<class StorageType > unsigned int VW::PyramidYUV< StorageType >::GetWidth (unsigned int which_level = 0) const [inline]
The width of the specified level (or the largest width if not specified).
References VW::PyramidYUV< StorageType >::level.
template<class StorageType > const std::vector< VW::ImageYUV< StorageType > * > & VW::PyramidYUV< StorageType >::Level () const [inline]
Get access to the array of images.
References VW::PyramidYUV< StorageType >::level.
template<class StorageType > unsigned int VW::PyramidYUV< StorageType >::NumLevels () const [inline]
The number of levels (images) contained in this pyramid.
References VW::PyramidYUV< StorageType >::num_levels.
template<class StorageType > VW::ImageYUV< StorageType > & VW::PyramidYUV< StorageType >::operator[] (int i) [inline]
Access a particular level (read/write).
References VW::PyramidYUV< StorageType >::level.
template<class StorageType > const VW::ImageYUV< StorageType > & VW::PyramidYUV< StorageType >::operator[] (int i) const [inline]
Access a particular level (read only).
References VW::PyramidYUV< StorageType >::level.
template<class StorageType > float VW::PyramidYUV< StorageType >::ScalingFactor () const [inline]
The scale factor between successive levels (0.5 for sumbsample by 2).
References VW::PyramidYUV< StorageType >::scaling_factor.
Member Data Documentation
template<class StorageType > std::vector<ImageYUV<StorageType> *> VW::PyramidYUV< StorageType >::level [protected]
Referenced by VW::PyramidYUV< StorageType >::Compute(), VW::PyramidYUV< StorageType >::GetHeight(), VW::PyramidYUV< StorageType >::GetWidth(), VW::PyramidYUV< StorageType >::Level(), VW::PyramidYUV< StorageType >::operator[](), and VW::PyramidYUV< StorageType >::~PyramidYUV().
template<class StorageType > unsigned int VW::PyramidYUV< StorageType >::num_levels [protected]
Referenced by VW::PyramidYUV< StorageType >::Compute(), VW::PyramidYUV< StorageType >::NumLevels(), and VW::PyramidYUV< StorageType >::~PyramidYUV().
template<class StorageType > float VW::PyramidYUV< StorageType >::scaling_factor [protected]
Referenced by VW::PyramidYUV< StorageType >::Compute(), VW::PyramidYUV< StorageType >::GetScale(), and VW::PyramidYUV< StorageType >::ScalingFactor().
The documentation for this class was generated from the following files:
pyramidyuv.h
pyramidyuv.cpp