VW: VW::ParametricFlow Class Reference
VW::ParametricFlow Class Reference
#include <parametricflow.h>
Public Member Functions
ParametricFlow (int p=8)
template<class Type >
ParametricFlow (const ImageMono< Type > &imold, const ImageMono< Type > &imnew, const int p, VW::Homography2D &H)
template<class Type >
void Compute (const ImageMono< Type > &imold, const ImageMono< Type > &imnew, VW::Homography2D &H)
operator bool ()
void SetParamSpace (const int p)
int GetParamSpace ()
Constructor & Destructor Documentation
VW::ParametricFlow::ParametricFlow (int p = 8) [inline]
template<class Type > VW::ParametricFlow::ParametricFlow (const ImageMono< Type > & imold, const ImageMono< Type > & imnew, const int p, VW::Homography2D & H) [inline]
References Compute().
Member Function Documentation
template<class Type > void ParametricFlow::Compute (const ImageMono< Type > & imold, const ImageMono< Type > & imnew, VW::Homography2D & H) [inline]
References c, DET_THRESH, VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), and VW::PixelMono< Type >::y.
Referenced by ParametricFlow().
int VW::ParametricFlow::GetParamSpace () [inline]
VW::ParametricFlow::operator bool () [inline]
void VW::ParametricFlow::SetParamSpace (const int p) [inline]
The documentation for this class was generated from the following files:
parametricflow.h
parametricflow.cpp