VW: VW::Randint Class Reference
VW::Randint Class Reference
#include <random.h>
Public Member Functions
Randint (long s=0)
void Seed (long s)
int Abs (int x)
int Draw ()
double FDraw ()
int operator() ()
Static Public Member Functions
static double RandMax ()
Constructor & Destructor Documentation
VW::Randint::Randint (long s = 0) [inline]
Member Function Documentation
int VW::Randint::Abs (int x) [inline]
Referenced by FDraw(), and operator()().
int VW::Randint::Draw () [inline]
Referenced by FDraw(), and operator()().
double VW::Randint::FDraw () [inline]
References Abs(), Draw(), and RandMax().
Referenced by VW::Urand::operator()().
int VW::Randint::operator() () [inline]
Reimplemented in VW::Urand.
References Abs(), and Draw().
double VW::Randint::RandMax () [inline, static]
Referenced by FDraw().
void VW::Randint::Seed (long s) [inline]
The documentation for this class was generated from the following file:
random.h