VW: VW::GTI Class Reference
VW::GTI Class Reference
Simple interface class for controlling "Gonad the Invincible".
#include <gti_main.h>
Public Member Functions
int InitLink (std::string boot_file)
GTI (void)
~GTI (void)
int Rotate (float angle)
int Drive (float dist)
int SetVelocity (float velocity)
int SetSteeringAngle (float angle)
int GetDriveOdometry (int *count)
Detailed Description
Simple interface class for controlling "Gonad the Invincible".
Author:
ID Reid, BJ Tordoff
Date:
09/09/2002 This is just a class implementation of some stuff that used to be in module.h, but has now been split into VW::Yorick, VW::SequencerMeteor and VW::GTI.
Constructor & Destructor Documentation
VW::GTI::GTI (void) [inline]
VW::GTI::~GTI (void) [inline]
Member Function Documentation
int GTI::Drive (float dist)
References ChanInChar(), ChanOut(), ChanOutChar(), TheLink, and VDRV_CHAR.
int GTI::GetDriveOdometry (int * count)
References ChanInMsg(), ChanOutChar(), GETD_CHAR, OK, and TheLink.
int VW::GTI::InitLink (std::string boot_file)
int GTI::Rotate (float angle)
References ChanInChar(), ChanOut(), ChanOutChar(), TheLink, and VROT_CHAR.
int GTI::SetSteeringAngle (float angle)
References ChanInMsg(), ChanOut(), ChanOutChar(), OK, SABS_CHAR, and TheLink.
int GTI::SetVelocity (float velocity)
References ChanInMsg(), ChanOut(), ChanOutChar(), OK, TheLink, and VABS_CHAR.
The documentation for this class was generated from the following files:
gti_main.h
gti_main.cpp