VW: VNL::CVector< T > Class Template Reference
VNL::CVector< T > Class Template Reference
vnl_c_vector interfaces to lowlevel memory-block operations.
#include <cvector.h>
Public Types
typedef NumericTraits< T >::abs_t abs_t
Static Public Member Functions
static T Sum (T const *v, unsigned n)
static abs_t SquaredMagnitude (T const *p, unsigned n)
static void Normalize (T *, unsigned n)
static void Apply (T const *, unsigned, T(*f)(T), T *v_out)
static void Apply (T const *, unsigned, T(*f)(T const &), T *v_out)
static void Copy (T const *x, T *y, unsigned)
y[i] = x[i].
static void Scale (T const *x, T *y, unsigned, T const &)
y[i] = a*x[i].
static void Add (T const *x, T const *y, T *z, unsigned)
z[i] = x[i] + y[i];.
static void Add (T const *x, T const &y, T *z, unsigned)
z[i] = x[i] + y;.
static void Subtract (T const *x, T const *y, T *z, unsigned)
z[i] = x[i] - y[i].
static void Subtract (T const *x, T const &y, T *z, unsigned)
z[i] = x[i] - y[i].
static void Multiply (T const *x, T const *y, T *z, unsigned)
z[i] = x[i] * y[i].
static void Multiply (T const *x, T const &y, T *z, unsigned)
z[i] = x[i] * y[i].
static void Divide (T const *x, T const *y, T *z, unsigned)
z[i] = x[i] / y[i].
static void Divide (T const *x, T const &y, T *z, unsigned)
z[i] = x[i] / y[i].
static void Negate (T const *x, T *y, unsigned)
y[i] = -x[i].
static void Invert (T const *x, T *y, unsigned)
y[i] = 1/x[i].
static void SelfPlusAx (T const &a, T const *x, T *y, unsigned)
y[i] += a*x[i].
static void Fill (T *x, unsigned, T const &v)
x[i] = v.
static void Reverse (T *x, unsigned)
static T DotProduct (T const *, T const *, unsigned)
static T InnerProduct (T const *, T const *, unsigned)
conjugate second.
static void Conjugate (T const *, T *, unsigned)
static T MaxValue (T const *, unsigned)
Returns max value of the vector.
static T MinValue (T const *, unsigned)
Returns min value of the vector.
static T Mean (T const *p, unsigned n)
static abs_t OneNorm (T const *p, unsigned n)
one_norm : sum of abs values.
static abs_t TwoNorm (T const *p, unsigned n)
two_norm : sqrt of sum of squared abs values.
static abs_t InfNorm (T const *p, unsigned n)
inf_norm : max of abs values.
static abs_t TwoNorm2 (T const *p, unsigned n)
two_nrm2 : sum of squared abs values.
static abs_t RMSNorm (T const *p, unsigned n)
rms_norm : sqrt of mean sum of squared abs values.
static T EuclidDist2 (T const *, T const *, unsigned)
Euclidean Distance between two vectors.
static T ** AllocateTptr (int n)
Memory allocation.
static T * AllocateT (int n)
static void Deallocate (T **, int n_when_allocated)
static void Deallocate (T *, int n_when_allocated)
static std::ostream & PrintVector (std::ostream &, T const *, unsigned)
Input & output.
Detailed Description
template<class T>
class VNL::CVector< T >
vnl_c_vector interfaces to lowlevel memory-block operations.
Member Typedef Documentation
template<class T> typedef NumericTraits<T>::abs_t VNL::CVector< T >::abs_t
Member Function Documentation
template<class T> void VNL::CVector< T >::Add (T const * x, T const & y, T * z, unsigned n) [inline, static]
z[i] = x[i] + y;.
References impl_elmt_wise_commutative_a.
template<class T> void VNL::CVector< T >::Add (T const * x, T const * y, T * z, unsigned n) [inline, static]
z[i] = x[i] + y[i];.
References impl_elmt_wise_commutative.
template<class T > T * VNL::CVector< T >::AllocateT (int n) [inline, static]
References vnl_c_vector_alloc(), and vnl_c_vector_construct().
template<class T > T ** VNL::CVector< T >::AllocateTptr (int n) [inline, static]
Memory allocation.
References vnl_c_vector_alloc().
template<class T> void VNL::CVector< T >::Apply (T const * v, unsigned n, T(*)(T const &) f, T * v_out) [inline, static]
template<class T> void VNL::CVector< T >::Apply (T const * v, unsigned n, T(*)(T) f, T * v_out) [inline, static]
template<class T> void VNL::CVector< T >::Conjugate (T const * src, T * dst, unsigned n) [inline, static]
template<class T> void VNL::CVector< T >::Copy (T const * x, T * y, unsigned n) [inline, static]
y[i] = x[i].
template<class T> void VNL::CVector< T >::Deallocate (T * p, int n_when_allocated) [inline, static]
References vnl_c_vector_dealloc(), and vnl_c_vector_destruct().
template<class T> void VNL::CVector< T >::Deallocate (T ** v, int n_when_allocated) [inline, static]
References vnl_c_vector_dealloc().
template<class T> void VNL::CVector< T >::Divide (T const * x, T const & y, T * z, unsigned n) [inline, static]
z[i] = x[i] / y[i].
References impl_elmt_wise_commutative_a.
template<class T> void VNL::CVector< T >::Divide (T const * x, T const * y, T * z, unsigned n) [inline, static]
z[i] = x[i] / y[i].
References impl_elmt_wise_non_commutative.
template<class T> T VNL::CVector< T >::DotProduct (T const * a, T const * b, unsigned n) [inline, static]
template<class T> T VNL::CVector< T >::EuclidDist2 (T const * a, T const * b, unsigned n) [inline, static]
Euclidean Distance between two vectors.
Sum of Differences squared.
template<class T> void VNL::CVector< T >::Fill (T * x, unsigned n, T const & v) [inline, static]
x[i] = v.
template<class T> static abs_t VNL::CVector< T >::InfNorm (T const * p, unsigned n) [inline, static]
inf_norm : max of abs values.
References VNL::CVectorInfNorm().
template<class T> T VNL::CVector< T >::InnerProduct (T const * a, T const * b, unsigned n) [inline, static]
conjugate second.
template<class T> void VNL::CVector< T >::Invert (T const * x, T * y, unsigned n) [inline, static]
y[i] = 1/x[i].
template<class T> T VNL::CVector< T >::MaxValue (T const * src, unsigned n) [inline, static]
Returns max value of the vector.
template<class T> static T VNL::CVector< T >::Mean (T const * p, unsigned n) [inline, static]
References VNL::CVector< T >::Sum().
template<class T> T VNL::CVector< T >::MinValue (T const * src, unsigned n) [inline, static]
Returns min value of the vector.
template<class T> void VNL::CVector< T >::Multiply (T const * x, T const & y, T * z, unsigned n) [inline, static]
z[i] = x[i] * y[i].
References impl_elmt_wise_commutative_a.
template<class T> void VNL::CVector< T >::Multiply (T const * x, T const * y, T * z, unsigned n) [inline, static]
z[i] = x[i] * y[i].
References impl_elmt_wise_commutative.
template<class T> void VNL::CVector< T >::Negate (T const * x, T * y, unsigned n) [inline, static]
y[i] = -x[i].
Note that this is a no-op when T is an unsigned type.
template<class T> void VNL::CVector< T >::Normalize (T * v, unsigned n) [inline, static]
References std::sqrt(), and VNL::SquaredMagnitude().
template<class T> static abs_t VNL::CVector< T >::OneNorm (T const * p, unsigned n) [inline, static]
one_norm : sum of abs values.
References VNL::CVectorOneNorm().
template<class T> std::ostream & VNL::CVector< T >::PrintVector (std::ostream & s, T const * v, unsigned size) [inline, static]
Input & output.
template<class T> void VNL::CVector< T >::Reverse (T * x, unsigned n) [inline, static]
template<class T> static abs_t VNL::CVector< T >::RMSNorm (T const * p, unsigned n) [inline, static]
rms_norm : sqrt of mean sum of squared abs values.
References VNL::CVectorRMSNorm().
template<class T> void VNL::CVector< T >::Scale (T const * x, T * y, unsigned n, T const & a_) [inline, static]
y[i] = a*x[i].
template<class T> void VNL::CVector< T >::SelfPlusAx (T const & a, T const * x, T * y, unsigned n) [inline, static]
y[i] += a*x[i].
template<class T> static abs_t VNL::CVector< T >::SquaredMagnitude (T const * p, unsigned n) [inline, static]
References VNL::CVectorTwoNormSquared().
template<class T> void VNL::CVector< T >::Subtract (T const * x, T const & y, T * z, unsigned n) [inline, static]
z[i] = x[i] - y[i].
References impl_elmt_wise_commutative_a.
template<class T> void VNL::CVector< T >::Subtract (T const * x, T const * y, T * z, unsigned n) [inline, static]
z[i] = x[i] - y[i].
References impl_elmt_wise_non_commutative.
template<class T> T VNL::CVector< T >::Sum (T const * v, unsigned n) [inline, static]
Referenced by VNL::CVector< T >::Mean().
template<class T> static abs_t VNL::CVector< T >::TwoNorm (T const * p, unsigned n) [inline, static]
two_norm : sqrt of sum of squared abs values.
References VNL::CVectorTwoNorm().
template<class T> static abs_t VNL::CVector< T >::TwoNorm2 (T const * p, unsigned n) [inline, static]
two_nrm2 : sum of squared abs values.
References VNL::CVectorTwoNormSquared().
The documentation for this class was generated from the following files:
cvector.h
cvector.tpp