VW: VW::Normalisation3D Class Reference
VW::Normalisation3D Class Reference
[GeometricObjects]
A 3D normalisation object.
#include <normalisation3d.h>
Public Member Functions
Normalisation3D ()
Construct and set to identity.
Normalisation3D (double width, double height=0, double depth=0)
Construct using a single dimension or also specify height and depth when they are different.
Normalisation3D (double scale, const VW::Point3D &centre)
Construct and set to isotropic scaling around given location.
Normalisation3D (const VNL::MatrixFixed< 4, 4, double > &C)
Construct from an existing 4x4 matrix.
Normalisation3D (const VNL::MatrixFixed< 4, 4, float > &C)
Constaruct from an existing floating point matrix.
Normalisation3D (const std::vector< VW::Point3D > &feature_list)
Construct based on mean and standard deviation of point feature list.
Normalisation3D (const std::vector< VW::Point3D > &feature_list, const std::vector< unsigned int > &which_features)
Construct based on mean and standard deviation of selected elements from a point feature list.
Normalisation3D (const Normalisation3D &C)
Construct (copy) from an existing normalisation.
void Init ()
void Init (double width, double height=0, double depth=0)
void Init (double scale, const VW::Point3D &centre)
void Init (const VNL::MatrixFixed< 4, 4, double > &C)
void Init (const VNL::MatrixFixed< 4, 4, float > &C)
template<class PointFeature >
void Init (const std::vector< PointFeature > &feature_list)
Initialise based on mean and standard deviation of selected elements from a point feature list.
template<class PointFeature >
void Init (const std::vector< PointFeature > &feature_list, const std::vector< unsigned int > &which_features)
Initialise based on mean and standard deviation of selected elements from a point feature list.
template<class PointFeature >
void Normalise (std::vector< PointFeature > &feature_list, VW::Point3D point=VW::Point3D()) const
template<class PointFeature >
PointFeature Normalise (const PointFeature &feature, VW::Point3D point=VW::Point3D()) const
VNL::MatrixFixed< 4, 4, double > Normalise (const VNL::MatrixFixed< 4, 4, double > &M) const
Normalise a 3x3 double precision matrix.
VNL::MatrixFixed< 4, 4, float > Normalise (const VNL::MatrixFixed< 4, 4, float > &M) const
Normalise a 3x3 floating point matrix.
template<class PointFeature >
void UnNormalise (std::vector< PointFeature > &feature_list, VW::Point3D point=VW::Point3D()) const
template<class PointFeature >
PointFeature UnNormalise (const PointFeature &feature, VW::Point3D point=VW::Point3D()) const
VNL::MatrixFixed< 4, 4, double > UnNormalise (const VNL::MatrixFixed< 4, 4, double > &M) const
VNL::MatrixFixed< 4, 4, float > UnNormalise (const VNL::MatrixFixed< 4, 4, float > &M) const
VNL::MatrixFixed< 4, 4, double > operator() () const
VNL::MatrixFixed< 4, 4, double > AsMatrix () const
VNL::MatrixFixed< 4, 4, double > InverseMatrix () const
double GetScale () const
double GetCentreX () const
double GetCentreY () const
double GetCentreZ () const
void GetCentre (double &x, double &y, double &z) const
bool IsIdentity () const
Protected Attributes
double _scale
double _centre_x
double _centre_y
double _centre_z
Detailed Description
A 3D normalisation object.
Author:
BJ Tordoff
Date:
15/8/2003 This class is designed for normalising points and lines (segments) in 3D euclidean space, such as must be done before calculating the various 3D transforms and 3D to 2D projections. A variety of normalisations are possible, but the most common and simplest is to simply provide a single distance which is assumed to be the dimension of a cube containing all points.
X, Y and Z are scaled equally. Doing otherwise complicates things and is rarely needed.
Constructor & Destructor Documentation
VW::Normalisation3D::Normalisation3D () [inline]
Construct and set to identity.
VW::Normalisation3D::Normalisation3D (double width, double height = 0, double depth = 0) [inline]
Construct using a single dimension or also specify height and depth when they are different.
The scaling is then isotropic around the cuboid centre.
References Init().
VW::Normalisation3D::Normalisation3D (double scale, const VW::Point3D & centre) [inline]
Construct and set to isotropic scaling around given location.
VW::Normalisation3D::Normalisation3D (const VNL::MatrixFixed< 4, 4, double > & C) [inline]
Construct from an existing 4x4 matrix.
VW::Normalisation3D::Normalisation3D (const VNL::MatrixFixed< 4, 4, float > & C) [inline]
Constaruct from an existing floating point matrix.
VW::Normalisation3D::Normalisation3D (const std::vector< VW::Point3D > & feature_list) [inline]
Construct based on mean and standard deviation of point feature list.
References Init().
VW::Normalisation3D::Normalisation3D (const std::vector< VW::Point3D > & feature_list, const std::vector< unsigned int > & which_features) [inline]
Construct based on mean and standard deviation of selected elements from a point feature list.
References Init().
VW::Normalisation3D::Normalisation3D (const Normalisation3D & C) [inline]
Construct (copy) from an existing normalisation.
Member Function Documentation
VNL::MatrixFixed< 4, 4, double > VW::Normalisation3D::AsMatrix () const
References _centre_x, _centre_y, _centre_z, and _scale.
Referenced by VW::PMatrixCompute::LinearFromPoints(), VW::PMatrixCompute::NonLinearFromPoints(), Normalise(), and operator()().
void VW::Normalisation3D::GetCentre (double & x, double & y, double & z) const [inline]
References _centre_x, _centre_y, and _centre_z.
double VW::Normalisation3D::GetCentreX () const [inline]
References _centre_x.
double VW::Normalisation3D::GetCentreY () const [inline]
References _centre_y.
double VW::Normalisation3D::GetCentreZ () const [inline]
References _centre_z.
double VW::Normalisation3D::GetScale () const [inline]
References _scale.
template<class PointFeature > void VW::Normalisation3D::Init (const std::vector< PointFeature > & feature_list, const std::vector< unsigned int > & which_features) [inline]
Initialise based on mean and standard deviation of selected elements from a point feature list.
References _centre_x, _centre_y, _centre_z, _scale, and VW::GetPointDistribution().
template<class PointFeature > void VW::Normalisation3D::Init (const std::vector< PointFeature > & feature_list) [inline]
Initialise based on mean and standard deviation of selected elements from a point feature list.
References _centre_x, _centre_y, _centre_z, _scale, and VW::GetPointDistribution().
void VW::Normalisation3D::Init (const VNL::MatrixFixed< 4, 4, float > & C) [inline]
References _centre_x, _centre_y, _centre_z, and _scale.
void VW::Normalisation3D::Init (const VNL::MatrixFixed< 4, 4, double > & C) [inline]
References _centre_x, _centre_y, _centre_z, and _scale.
void VW::Normalisation3D::Init (double scale, const VW::Point3D & centre) [inline]
References _centre_x, _centre_y, _centre_z, _scale, VW::Point3D::GetX(), VW::Point3D::GetY(), and VW::Point3D::GetZ().
void VW::Normalisation3D::Init (double width, double height = 0, double depth = 0) [inline]
References _centre_x, _centre_y, _centre_z, and _scale.
void VW::Normalisation3D::Init () [inline]
References _centre_x, _centre_y, _centre_z, and _scale.
Referenced by VW::PMatrixCompute::LinearFromPoints(), and Normalisation3D().
VNL::MatrixFixed< 4, 4, double > VW::Normalisation3D::InverseMatrix () const
References _centre_x, _centre_y, _centre_z, and _scale.
Referenced by VW::PMatrixCompute::NonLinearFromPoints(), and UnNormalise().
bool VW::Normalisation3D::IsIdentity () const [inline]
References _centre_x, _centre_y, _centre_z, and _scale.
Referenced by Normalise(), and UnNormalise().
VNL::MatrixFixed< 4, 4, float > VW::Normalisation3D::Normalise (const VNL::MatrixFixed< 4, 4, float > & M) const
Normalise a 3x3 floating point matrix.
References AsMatrix(), and VNL::Copy().
VNL::MatrixFixed< 4, 4, double > VW::Normalisation3D::Normalise (const VNL::MatrixFixed< 4, 4, double > & M) const [inline]
Normalise a 3x3 double precision matrix.
References AsMatrix().
template<class PointFeature > PointFeature VW::Normalisation3D::Normalise (const PointFeature & feature, VW::Point3D point = VW::Point3D()) const [inline]
References _centre_x, _centre_y, _centre_z, and _scale.
template<class PointFeature > void VW::Normalisation3D::Normalise (std::vector< PointFeature > & feature_list, VW::Point3D point = VW::Point3D()) const [inline]
References IsIdentity().
Referenced by VW::PMatrixCompute::LinearFromPoints(), and VW::PMatrixCompute::NonLinearFromPoints().
VNL::MatrixFixed<4,4,double> VW::Normalisation3D::operator() () const [inline]
References AsMatrix().
VNL::MatrixFixed< 4, 4, float > VW::Normalisation3D::UnNormalise (const VNL::MatrixFixed< 4, 4, float > & M) const
References VNL::Copy(), and InverseMatrix().
VNL::MatrixFixed< 4, 4, double > VW::Normalisation3D::UnNormalise (const VNL::MatrixFixed< 4, 4, double > & M) const [inline]
Parameters:
M the matrix to be unnormalised (will not be changed)
Returns:
a new matrix which is un-normalised
References InverseMatrix().
template<class PointFeature > PointFeature VW::Normalisation3D::UnNormalise (const PointFeature & feature, VW::Point3D point = VW::Point3D()) const [inline]
References _centre_x, _centre_y, _centre_z, and _scale.
template<class PointFeature > void VW::Normalisation3D::UnNormalise (std::vector< PointFeature > & feature_list, VW::Point3D point = VW::Point3D()) const [inline]
References IsIdentity().
Member Data Documentation
double VW::Normalisation3D::_centre_x [protected]
Referenced by AsMatrix(), GetCentre(), GetCentreX(), Init(), InverseMatrix(), IsIdentity(), Normalise(), and UnNormalise().
double VW::Normalisation3D::_centre_y [protected]
Referenced by AsMatrix(), GetCentre(), GetCentreY(), Init(), InverseMatrix(), IsIdentity(), Normalise(), and UnNormalise().
double VW::Normalisation3D::_centre_z [protected]
Referenced by AsMatrix(), GetCentre(), GetCentreZ(), Init(), InverseMatrix(), IsIdentity(), Normalise(), and UnNormalise().
double VW::Normalisation3D::_scale [protected]
Referenced by AsMatrix(), GetScale(), Init(), InverseMatrix(), IsIdentity(), Normalise(), and UnNormalise().
The documentation for this class was generated from the following files:
normalisation3d.h
normalisation3d.cpp