VW: VNL::QR< T > Class Template Reference
VNL::QR< T > Class Template Reference
Extract the Q*R decomposition of matrix M.
#include <qr.h>
Public Member Functions
QR (Matrix< T > const &M)
~QR ()
Vector< T > Solve (const Vector< T > &rhs) const
Solve equation M x = b for x using the computed decomposition.
T Determinant () const
Return the determinant of M. This is computed from M = Q R as follows:.
Matrix< T > & Q ()
Unpack and return unitary part Q.
Matrix< T > & R ()
Unpack and return R.
Vector< T > QtB (const Vector< T > &b) const
Return residual vector d of M x = b -> d = Q'b.
Detailed Description
template<class T>
class VNL::QR< T >
Extract the Q*R decomposition of matrix M.
The decomposition is stored in a compact and time-efficient packed form, which is most easily used via the "solve" and "determinant" methods.
Constructor & Destructor Documentation
template<class T > VNL::QR< T >::QR (VNL::Matrix< T > const & M) [inline]
References c, VNL::Matrix< T >::Columns(), VNL::Vector< T >::DataBlock(), VNL::Vector< T >::Fill(), and VNL::Matrix< T >::Rows().
template<class T > VNL::QR< T >::~QR () [inline]
Member Function Documentation
template<class T > T VNL::QR< T >::Determinant () const [inline]
Return the determinant of M. This is computed from M = Q R as follows:.
|M| = |Q| |R| |R| is the product of the diagonal elements. |Q| is (-1)^n as it is a product of Householder reflections. So det = -prod(-r_ii).
References m, and VNL::Min().
template<class T > VNL::Matrix< T > & VNL::QR< T >::Q () [inline]
Unpack and return unitary part Q.
References c, m, VNL::MatlabPrint(), VNL::SquaredMagnitude(), and v.
template<class T > VNL::Vector< T > VNL::QR< T >::QtB (const Vector< T > & b) const [inline]
Return residual vector d of M x = b -> d = Q'b.
References VNL::Vector< T >::DataBlock().
Referenced by VNL::QR< T >::Solve().
template<class T > VNL::Matrix< T > & VNL::QR< T >::R () [inline]
Unpack and return R.
References m.
template<class T > VNL::Vector< T > VNL::QR< T >::Solve (const Vector< T > & rhs) const [inline]
Solve equation M x = b for x using the computed decomposition.
References VNL::Vector< T >::DataBlock(), and VNL::QR< T >::QtB().
The documentation for this class was generated from the following files:
qr.h
qr.tpp