VW: drawvl500.cpp File Reference
drawvl500.cpp File Reference
#include "drawvl500.h"
Functions
void DrawVL500Face (float width, float depth, float bevel)
void DrawVL500Curve (float width, float curveheight, float bevel, int m, int n)
void DrawVL500FrontQuadrant (int mx, int my, float width, float height, float frontcurve)
Function Documentation
void DrawVL500Curve (float width, float curveheight, float bevel, int m, int n)
Referenced by VW::DrawVL500().
void DrawVL500Face (float width, float depth, float bevel)
Referenced by VW::DrawVL500().
void DrawVL500FrontQuadrant (int mx, int my, float width, float height, float frontcurve)
Referenced by VW::DrawVL500().