VW: drawthreequarterdesk.cpp File Reference
drawthreequarterdesk.cpp File Reference
#include "drawthreequarterdesk.h"
Functions
void DrawThreeQuarterDeskTop (double height, int norm)
void DrawThreeQuarterDeskBorder ()
void DrawThreeQuarterDeskLeg (double x, double y, int dx, int dy)
Function Documentation
void DrawThreeQuarterDeskBorder ()
Referenced by VW::DrawThreeQuarterDesk().
void DrawThreeQuarterDeskLeg (double x, double y, int dx, int dy)
Referenced by VW::DrawThreeQuarterDesk().
void DrawThreeQuarterDeskTop (double height, int norm)
Referenced by VW::DrawThreeQuarterDesk().