VW: drawgti.cpp File Reference
drawgti.cpp File Reference
#include "drawgti.h"
#include "threedtoolglcommon.h"
#include "drawyorick811.h"
Functions
void DrawGTIBlock (VW::ThreeDToolGLCommon &display, const VW::Vector3D &position, const VW::Quaternion &orientation, bool battery=false)
void DrawGTIWheel (VW::ThreeDToolGLCommon &display, const VW::Vector3D &position, const VW::Quaternion &orientation)
Variables
const float block_width = float(0.190)
const float block_depth = float(0.190)
const float block_height = float(0.190)
const float bar_size = float(0.025)
const float wheel_height = float(0.220)
const float wheel_radius = float(0.080)
const float wheel_thickness = float(0.030)
const float wheel_spacing = float(0.005)
Function Documentation
void DrawGTIBlock (VW::ThreeDToolGLCommon & display, const VW::Vector3D & position, const VW::Quaternion & orientation, bool battery = false)
References bar_size, block_depth, block_height, block_width, VW::ThreeDToolGLCommon::PopDrawingPosition(), VW::ThreeDToolGLCommon::PushDrawingPosition(), VW::ThreeDToolGLCommon::RotateDrawingPosition(), VW::ThreeDToolGLCommon::SetPenColour(), and VW::ThreeDToolGLCommon::TranslateDrawingPosition().
Referenced by VW::DrawGTI().
void DrawGTIWheel (VW::ThreeDToolGLCommon & display, const VW::Vector3D & position, const VW::Quaternion & orientation)
References block_depth, block_width, VW::ThreeDToolGLCommon::DrawCylinder(), VW::ThreeDToolGLCommon::DrawDisc(), VW::ThreeDToolGLCommon::PopDrawingPosition(), VW::ThreeDToolGLCommon::PushDrawingPosition(), VW::ThreeDToolGLCommon::RotateDrawingPosition(), VW::ThreeDToolGLCommon::SetPenColour(), VW::ThreeDToolGLCommon::TranslateDrawingPosition(), wheel_height, wheel_radius, wheel_spacing, and wheel_thickness.
Referenced by VW::DrawGTI().
Variable Documentation
const float bar_size = float(0.025)
Referenced by DrawGTIBlock().
const float block_depth = float(0.190)
Referenced by VW::DrawGTI(), DrawGTIBlock(), and DrawGTIWheel().
const float block_height = float(0.190)
Referenced by DrawGTIBlock(), and VW::DrawGTIWithYorick().
const float block_width = float(0.190)
Referenced by VW::DrawGTI(), DrawGTIBlock(), and DrawGTIWheel().
const float wheel_height = float(0.220)
Referenced by VW::DrawGTI(), DrawGTIWheel(), and VW::DrawGTIWithYorick().
const float wheel_radius = float(0.080)
Referenced by DrawGTIWheel().
const float wheel_spacing = float(0.005)
Referenced by DrawGTIWheel().
const float wheel_thickness = float(0.030)
Referenced by DrawGTIWheel().