VW: essentialmatrixcompute5point.cpp File Reference
essentialmatrixcompute5point.cpp File Reference
#include <iostream>
#include <VNL/realpolynomial.h>
#include <VNL/Algo/qr.h>
#include <VNL/Algo/determinant.h>
#include <VNL/Algo/rpolyroots.h>
#include <VW/Utils/timer.h>
#include <VW/GeomObjects/fmatrix.h>
#include <VW/GeomObjects/normalisation.h>
#include <VW/GeomObjects/point2d.h>
#include <VW/MathBits/random.h>
#include "essentialmatrixcompute5point.h"
#include "essentialmatrixcompute.h"
Defines
#define VERBOSE false
Typedefs
typedef VNL::VectorFixed
< 4, double > Double4
typedef VNL::VectorFixed
< 5, double > Double5
typedef VNL::VectorFixed
< 7, double > Double7
typedef VNL::VectorFixed
< 8, double > Double8
typedef VNL::VectorFixed
< 10, double > Double10
typedef VNL::VectorFixed
< 11, double > Double11
typedef VNL::VectorFixed
< 20, double > Double20
Functions
void GetRowEchelonForm (VNL::MatrixFixed< 10, 20, double > &M)
Reduce a matrix to its row-echelon form (unit on pivots).
Detailed Description
Author:
G Vogiatzis, BJ Tordoff
Date:
19/04/2005
(c) Copyright University of Cambridge
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
Define Documentation
#define VERBOSE false
Typedef Documentation
typedef VNL::VectorFixed<10,double> Double10
typedef VNL::VectorFixed<11,double> Double11
typedef VNL::VectorFixed<20,double> Double20
typedef VNL::VectorFixed< 4,double> Double4
typedef VNL::VectorFixed< 5,double> Double5
typedef VNL::VectorFixed< 7,double> Double7
typedef VNL::VectorFixed< 8,double> Double8
Function Documentation
void GetRowEchelonForm (VNL::MatrixFixed< 10, 20, double > & M)
Reduce a matrix to its row-echelon form (unit on pivots).
References abs, VNL::Matrix< T >::Columns(), VNL::Matrix< T >::GetRow(), VNL::Matrix< T >::Rows(), and VNL::Matrix< T >::SetRow().