VW: glutloop.cpp File Reference
glutloop.cpp File Reference
#include <GL/glut.h>
#include <iostream>
#include <vector>
#include <stdlib.h>
#include <cstdlib>
#include <VW/Utils/timer.h>
#include "glutwindow.h"
#include "glutloop.h"
Defines
#define VERBOSE false
#define SAFE false
Functions
void GLUTAddWindow (VW::GLUTWindow *w)
int GetWindowID ()
void GLUTDrawFunc ()
void GLUTResizeFunc (int newwidth, int newheight)
void GLUTMotionFunc (int newx, int newy)
void GLUTPassiveMotionFunc (int newx, int newy)
void GLUTMouseFunc (int button, int state, int x, int y)
void GLUTIdleEvent ()
void GLUTRegisterCallbacks ()
Variables
std::vector< VW::GLUTWindow * > windows
bool GLUT_INITIALISED = false
bool USE_IDLER = false
Detailed Description
Author:
BJ Tordoff & KR Connor
Date:
03/12/2003
(c) Copyright University of Oxford
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
Define Documentation
#define SAFE false
Referenced by GetWindowID().
#define VERBOSE false
Function Documentation
int GetWindowID ()
References SAFE, VERBOSE, and windows.
Referenced by GLUTMotionFunc(), GLUTMouseFunc(), GLUTPassiveMotionFunc(), and GLUTResizeFunc().
void GLUTAddWindow (VW::GLUTWindow * w)
References VW::GLUTWindow::GetID(), VERBOSE, and windows.
Referenced by VW::GLUTWindow::_CreateSubwindow(), and VW::GLUTWindow::_CreateWindow().
void GLUTDrawFunc ()
References VERBOSE, and windows.
Referenced by GLUTRegisterCallbacks().
void GLUTIdleEvent ()
References VERBOSE.
Referenced by GLUTRegisterCallbacks().
void GLUTMotionFunc (int newx, int newy)
References VW::Timer::GetAsMilliseconds(), GetWindowID(), VW::Timer::Start(), VERBOSE, and windows.
Referenced by GLUTRegisterCallbacks().
void GLUTMouseFunc (int button, int state, int x, int y)
References GetWindowID(), VERBOSE, and windows.
Referenced by GLUTRegisterCallbacks().
void GLUTPassiveMotionFunc (int newx, int newy)
References VW::Timer::GetAsMilliseconds(), GetWindowID(), VW::Timer::Start(), VERBOSE, and windows.
Referenced by GLUTRegisterCallbacks().
void GLUTRegisterCallbacks ()
References GLUTDrawFunc(), GLUTIdleEvent(), GLUTMotionFunc(), GLUTMouseFunc(), GLUTPassiveMotionFunc(), GLUTResizeFunc(), USE_IDLER, and VERBOSE.
Referenced by VW::GLUTWindow::_CreateSubwindow(), and VW::GLUTWindow::_CreateWindow().
void GLUTResizeFunc (int newwidth, int newheight)
References GetWindowID(), VERBOSE, and windows.
Referenced by GLUTRegisterCallbacks().
Variable Documentation
bool GLUT_INITIALISED = false
Referenced by VW::GLUTInit().
bool USE_IDLER = false
Referenced by VW::GLUTInit(), and GLUTRegisterCallbacks().
std::vector<VW::GLUTWindow*> windows
Referenced by GetWindowID(), GLUTAddWindow(), GLUTDrawFunc(), GLUTMotionFunc(), GLUTMouseFunc(), GLUTPassiveMotionFunc(), and GLUTResizeFunc().