VW: VW Namespace Reference
VW Namespace Reference
[ImageProcessing]
Compute instantiations for Improc.
Namespaces
namespace ComputeFuncs
Functions that are common to the computation routines.
namespace Delaunay
namespace for Delaunay data (keeps it from cluttering the VW namespace).
namespace DrawFunctions
Draw things on displays.
namespace DrawImage
namespace EssentialMatrixCompute
Assorted helper functions for computing Essential Matrices.
namespace FirewireParams
These are proper C++ enums of things that are enumerated in dc1394_control.h.
namespace FMatrixAffineCompute
Assorted helper functions for computing affine Fundamental Matrices.
namespace FMatrixCompute
Assorted helper functions for computing Fundamental Matrices.
namespace FMPlanarCompute
namespace Homography2DCompute
ComputeLinear functions for Homography2Ds.
namespace ImageConversions
Whole buffer (or image) conversions.
namespace Line2DCompute
ComputeLinear functions for Line2D's.
namespace MatcherParams
namespace MeteorParams
Grouping of the meteor-related enumerations.
namespace Misc
Part of the VW::Misc namespace.
namespace MLESACFuncs
Functions that are common to the MLESAC based computation routines.
namespace PDF
namespace PlesseyOldParamsDefaults
namespace PMatrix2DCompute
ComputeLinear functions for projection-matrices.
namespace PMatrixCompute
namespace RadialDistortion
Methods for distorting and correcting images, points and lines for the effects of radial distortion.
namespace RadialDistortionCompute
Classes
class ConvexHull2D
Computation of the convex hull of a set of 2D points.
class Delaunay2D
Voronoi tessellation and Delaunay triangulation.
class EssentialMatrixCompute5Point
EssentialMatrixCompute5Point.
class EssentialMatrixComputeLinear
EssentialMatrixComputeLinear.
class EssentialMatrixComputeMLESAC
outlier rejection for essential matrices.
class EssHyp
class EssentialMatrixComputePreemptive
class FMatrixAffineComputeGUISAC
Compute an affine fundamental matrix from two lists of 2D point features using BJT's guided sampling and consensus method.
class FMatrixAffineComputeLinear
FMatrixAffineComputeLinear.
class FMatrixAffineComputeMLESAC
Compute a homography from two lists of 2D point features using Torr and Zisserman's maximum likelihood sampling and consensus method.
class FAffHyp
A simple class for storing a hypothesis and its rank (used for sorting).
class FMatrixAffineComputePreemptive
class FMatrixComputeGUNSAC
Compute a fundamental matrix from two lists of 2D point features using BJT's guided uncertain sampling and consensus method.
class FMatrixComputeLinear
class FMatrixComputeMLESAC
outlier rejection for fundamental matrices.
class FMatrixComputeNonLinear
class FMPlanarComputeNonLinear
class Homography2DComputeGUISAC
Compute a homography from two lists of 2D point features using BJT's guided sampling and consensus method.
class Homography2DComputeGUNSAC
Compute a homography from two lists of 2D point features using BJT's guided uncertain sampling and consensus method.
class Homography2DComputeLinear
class Homography2DComputeMLESAC
Compute a homography from two lists of 2D point features using Torr and Zisserman's maximum likelihood sampling and consensus method.
class Homography2DComputeNonLinear
class RandItem
class ThreePointPose
Compute 3D pose of 3 points given their image projections.
class AngleAxis
Representation of a 3D rotation as an angle-axis or axial vector.
class CalibrationMatrix
A class to store the camera internal calibration.
class CalibrationTable
A camera calibration look-up table.
class EssentialMatrix
A class to represent an essential matrix.
class FMatrix
A class to represent a fundamental matrix.
class FMatrixCovariance
class FMatrixAffine
A class to represent an affine fundamental matrix.
class FMatrixAffineCovariance
class FMatrixPlanar
A class to represent the specialisation of the fundamental matrix due to camera motion in a plane.
class Homography2D
A class to represent a planar homography.
class Homography2DCovariance
class Line2D
Representation of a 2D (infinite) line.
class LineSeg2D
Representation of a 2D line segment.
class LineSeg3D
Representation of a 3D line segment (ie a line with endpoints).
class Normalisation
A 2D normalisation object.
class Normalisation3D
A 3D normalisation object.
class Point2D
Representation of a 2D position or vector.
class Point3D
Representation of a 3D position or vector.
class ProjectionMatrix
A class to represent a projection matrix.
class Quaternion
Representation of a 3D quaternion.
class RotationMatrix
A class to store (3D) rotation matrices.
class Trajectory
class TrajectoryMap
List structure designed to hold trajectories of poitns, lines etc.
class Transform
The base class from which all transforms are made.
class DisplayBase
Base class for displays.
class PSCanvas
A canvas for drawing raw postscript.
class ImageBase
The base class from which all images are made.
class ImageHSV
A class for storing HSV (Hue, Saturation, Value) images.
class ImageInterleave
A class for storing interleaved (pixel-interlaced) images.
class ImageMono
A class for storing monochrome images.
class ImageRGB
A class for storing RGB images.
class ImageRGBPlanes
A class for storing an RGB image as seperate R, G and B images.
class ImageYUV
A class for storing YUV (YCrCb?) images.
class PixelHSV
class PixelMono
A class for storing Mono pixels.
class PixelRGB
A class for storing RGB pixels.
class PixelYUV
A class for storing YUV (YCrCb?) pixels.
class PixPtr
A pixel pointer implementation.
class ROI
Class to hold the bounds on the Region of Interest (ROI) of a 2D array (image).
class Canny
Class for computing image edges using the method of Canny.
class ChamferDistance
Class for computing a linear distance transfor (aka chamfer distance) image.
class ClassifierUV
A class to store a classification histogram, and providing classification of pixels or whole images.
class ConvolutionMask1D
class Convolve
class CornerFeature
A simple image location with a detection strength and scale.
class CornerMatcherBase
class Correlate
struct DOGDetectorParams
class DOGDetector
class Edgel
class EdgeData
class GetPatchDescriptor
Describe image features by the surrounding patch (with normalisation).
class GetPlesseyCorner
Old PlesseyCorner code.
class GetPlesseyCornerYUV
Old PlesseyCorner code.
class GetSIFTDescriptor
Interest point description using the method of Lowe.
class HistogramEqualisation
Standard histogram equalisation of image intensities.
class ImageDiff
Calculate the difference between two images.
class ImagePatch
class ImagePatchYUV
class IntegralImage
Implementation of integral image as described in Viola's CVPR2001 paper on face detection via boosting.
class IntegralImageSquared
Implementation of integral image squared.
class LenThresh
class LineFit
Fit lines to edge data.
struct LineInfo
Statistical information about a fitted line segment.
class LineSegFitted
A derivative of LineSeg2D that also includes goodness-of-fit data.
class MatchData
A storage class for match data.
class Moments
Compute moments of a binary or monochrome image.
class ParametricFlow
class ParametricFlowFunc
class ParametricFlowNonLin
class ParametricFlowWide
class ZNPatch
class PatchFeature
A class to store a feature location along with the zero-normalised patch of the surrounding image.
class PatchFeatureMatcher
class PlesseyCorner
class PlesseyCornerMatcher
class PlesseyCornerYUV
class PlesseyDetector
Interest point detection using the method of Harris/Plessey.
class PlesseyOldParams
class PlesseyOld
class Pyramid
Construct an image pyramid from an image.
class PyramidCorrelate
class PyramidYUV
Construct an image pyramid from a YUV image.
class ScaleImage
Scaling of an image (isotropic or XY aligned).
class ShiTomasiDetector
Interest point detection using the method of Shi & Tomasi.
struct SiftFeature
struct SiftParameters
class Sift
Interest point detection using David Lowe's SIFT (Scale invariant feature transform) descriptor.
class SIFTFeature
A class to store a feature location along with the descriptor as proposed by David Lowe.
class SIFTFeatureMatcher
class SmoothGaussian
Smooth an image using a Gaussian kernels.
class SmoothUniform
Smooth an image using a uniform kernel --- this is an optimised version, and is usually at least twice as fast as the gaussian smoothing.
class Subsample
Subsample an image by an integer factor.
class Threshold
class Warp
Warp a 2D image according to homography H.
class IOObject
Abstract base class for objects that can be input/output in a standard (streaming) way.
class ParameterParser
class ParameterWriter
class ChebyshevPolynomial
Some functions for fitting and evaluating Chebyshev polynomials.
class Covariance2D
class Covariance3D
class HistogramLocation
A simple class for storing a location.
class Histogram
A simple class for storing and retrieving 1D histogram values.
class Histogram2DLocation
A simple class for storing a location.
class Histogram2D
A simple class for storing and retrieving 2D histogram values.
class KalmanFilter
Fixed dimension Kalman filter without inputs.
class KalmanFilterWithInput
Fixed dimension Kalman filter including inputs.
class Randint
class Urand
class SequencerBase
The base class from which all sequencers are made.
class SequencerFile
A sequencer for handling sequentailly ordered files.
class SequencerMovie
A sequencer for handling a few types of Movie file.
class Thread
Base class from which a multi-threaded app can derrive.
class Mutex
Simple class to represent a mutex (mutual exclusion).
class Timer
Simple timer class for measuring elapsed time, with precision down to microseconds.
class DisplayX
A display which uses only Raw X library calls.
class DisplayXForms
class AWFEdge
class AWFFace
A class to represent faces for Alias WaveFront (AWF) objects.
class AWFMaterial
Class to store material properties for Alias WaveFront (AWF) objects.
class AWFObject
Class to read and store an Alias WaveFront (AWF) objects.
class DisplayGLCommon
Base class for OpenGL displays.
class DisplayGLUT
A display which uses only OpenGL/GLUT library calls.
class GLUTWindow
class DrawingPosition
A class to store a translation, rotation drawing position.
class RotationCentre
Little class for storing centre of rotation information.
class ThreeDToolGLCommon
A base class for doing 3D drawing in VW.
class ThreeDToolGLUT
A version of the ThreeDToolGLWidget which uses GLUT to open a window and handle events.
class DisplayGluteWidget
A display which uses only OpenGL/GLUT library calls.
class SequencerFileGlute
class SequencerFirewireGlute
class ThreeDToolGluteWidget
A version of the ThreeDTool which can be embedded in a glute GUI.
class DisplayGTK
A display that makes use of a GTK window.
class DisplayGTKCommon
class DisplayGTKGL
A display that makes use of a GTK window.
class DisplayGTKGLWidget
A display that uses a GTK GL canvas widget for drawing.
class DisplayGTKWidget
An embeddable GTK widget for displaying images.
class LocalGTKGLArea
class ThreeDToolGTKGLWidget
A version of the ThreeDToolGLWidget which is also a GTK widget, and can be embedded in a GTK interface.
class ClassifierUVGTKWidget
The widget which forms the heart of the interface.
class ClassifierUVGTK
class FirewireCameraGTKWidget
The firewire-camera interface widget.
class FirewireCameraGTK
The main firewire-camera interface class.
class InterfaceGTKWidget
The abstract interface widget.
class InterfaceGTK
The abstract interface class.
class PlesseyParamsGTKWidget
The widget which forms the heart of the interface.
class PlesseyParamsGTK
class SequencerFileGTK
A GTK1-based interface to the file sequencer.
class SequencerFileChannelGTKWidget
class SequencerFileGTKWidget
class SequencerFirewireGTKWidget
class SequencerFirewireGTK
A GTK1-based interface to the firewire sequencer.
class SequencerMovieGTK
class SequencerMovieChannelGTKWidget
class SequencerMovieGTKWidget
class YorickDragPad
The Yorick drag-pad.
class YorickGTKWidget
The Yorick widget.
class YorickGTK
class DisplayWxGLWidget
A display widget for WxWidgets guis.
class ThreeDToolWxGLWidget
A version of the ThreeDToolGLWidget for embedding in WxWidgets apps.
class SequencerFileWx
A Wx-based interface to the file sequencer.
class SequencerFirewireWx
A Wx-based interface to the firewire sequencer.
class FirewireCamera
This class is just a convenience wrapper for the various structs which hold info for the cameras.
class SequencerFirewire
Retrieve a sequence of image from one or more firewire cameras.
class SequencerMeteor
A sequencer for handling the Matrox Meteor frame-grabber.
class Yorick
class GTI
Simple interface class for controlling "Gonad the Invincible".
class ThreeDToolGlowWidget
class SequencerFileGlow
class SequencerFirewireGlow
class ThreeDToolQGLWidget
A version of ThreeDToolGLCommon which is also a Qt widget.
class DogDetector
Interest point detection using David Lowe's extrema of Difference-of-Gaussian (DOG) operator.
class Plesseycorner
A simple image feature which describes a location in terms of a normalised patch of the surrounding image.
class PlesseycornerYUV
A simple image feature suitable for representing Plessey corners.
class wxNewFrameEvent
A Wx-based interface to the file sequencer.
Typedefs
typedef Point3D Vector3D
typedef Point2D Vector2D
typedef ImageInterleave
< unsigned char, 4 > ImageInterleave32
typedef ImageInterleave
< unsigned char, 2 > ImageInterleave16
typedef std::deque< Edgel * > EdgeString
typedef pthread_t ThreadType
typedef pthread_mutex_t MutexType
typedef void * FuncRetType
Enumerations
enum MatcherType { BRAINDEAD_MATCHER = 0, REPEATEDLY_STUPID_MATCHER }
enum InterpolationMethod { NearestNeighbour, Bilinear, Biquadratic, Bicubic }
enum SequencerLoopMode { NO_LOOPING, LOOP, BOUNCE, REPEATLAST }
What should the sequencer do when it gets to the end of the sequence?
enum AWFFaceType { VertexOnly = 0, WithTexture, WithNormal, WithTextureAndNormal }
enum AWFMaterialType { DiffuseMaterial = 0, AmbientMaterial, SpecularMaterial }
enum GLMaterialType { GLMATERIAL_BRASS, GLMATERIAL_REDPLASTIC, GLMATERIAL_EMERALD, GLMATERIAL_SLATE }
Some predefined material types for GL use.
enum InterfaceType { INTERFACE_AS_WIDGET, INTERFACE_AS_BUTTONWINDOW }
The interface type.
Functions
void RandomSample (unsigned int number_to_pick, unsigned int total_num_features, std::vector< unsigned int > &sample_indices)
Select 'number_to_pick' samples from a list using even random samples.
void WeightedSample (unsigned int number_to_pick, const std::vector< double > &cumulative_weights, std::vector< unsigned int > &sample_indices)
Select 'number_to_pick' samples from a list using weighted samples.
void AccumulateWeights (const std::vector< double > &weights, std::vector< double > &cumulative_weights, std::vector< unsigned int > *include_only=0)
Create a cumulative probability list from a probability list.
void CreateRandomisedList (std::vector< unsigned int > &indices, unsigned int max_index)
Create a random list of the numbers from 0 to (max_index-1) where each number is gauranteed to be listed exactly once.
void TransferPoint (const VW::Point2D &source_point, const VW::FMatrix &F, const VW::FMatrixCovariance &FCovar, const float image_noise_variance, VW::Line2D &dest_line, VW::Covariance3D &dest_line_covar)
Transfer a point and its covariance using an uncertain estimate of an FMatrix.
double GetDistanceVariance (const VW::Point2D &dest_point, const VW::Line2D &epipolar_line, const VW::Covariance3D &epipolar_line_covar, const float image_noise_variance)
Find the variance of the distance between point and line given the line uncertainty and image noise (in image 2).
void TransferPoint (const VW::Point2D &source_point, const VW::FMatrixAffine &F, const VW::FMatrixAffineCovariance &FCovar, const float image_noise_variance, VW::Line2D &dest_line, VW::Covariance3D &dest_line_covar)
Transfer a point and its covariance using an uncertain estimate of an FMatrix.
void GeneratePointsInCuboid (const double width, const double height, const double depth, const unsigned int num_points, std::vector< VW::Point3D > &worldpoints)
Cuboid centered around origin.
void GeneratePointsOnSphereSurface (const double radius, const unsigned int num_points, std::vector< VW::Point3D > &worldpoints)
Generate a cloud of points on a spherical surface centered at origin.
void GeneratePointsInSphere (const double radius, const unsigned int num_points, std::vector< VW::Point3D > &worldpoints)
Generate a cloud of points filling a sphere centered at origin.
void GeneratePointsInShell (const double inner_radius, const double outer_radius, const unsigned int num_points, std::vector< VW::Point3D > &worldpoints)
Generate a cloud of points in a spherical shell centered at origin.
void GeneratePointsInShellPatch (const double inner_radius, const double outer_radius, const double max_angle, const unsigned int num_points, std::vector< VW::Point3D > &worldpoints)
Generate a cloud of points in a square patch on a spherical shell centered at the origin and pointing along 'z' (max_angle gives conic half-angle, and is in radians.
void TransferPoint (const VW::Point2D &source_point, const VW::Homography2D &H, const VW::Homography2DCovariance &HCovar, const float image_noise_variance, VW::Point2D &dest_point, VW::Covariance2D &dest_covar)
Transfer a point and both its uncertainty and that of the tranform (note that the total uncertainty requires you to add any noise in image 2).
template<>
unsigned int Homography2D::GetMinFeatures< VW::Point2D > (const VW::Point2D &)
template<>
unsigned int Homography2D::GetMinFeatures< VW::LineSeg2D > (const VW::LineSeg2D &)
void NormaliseLine (VW::Line2D &line, VW::Covariance3D &line_covariance)
Normalise the line and its covariance so that distances can be measured using the dot product.
ostream & operator<< (ostream &s, const LineSeg2D &ls)
istream & operator>> (istream &s, LineSeg2D &ls)
double operator* (const LineSeg3D &ls1, const LineSeg3D &ls2)
double Norm2 (const LineSeg3D &ls)
double Norm (const LineSeg3D &ls)
ostream & operator<< (ostream &s, const LineSeg3D &ls)
istream & operator>> (istream &s, LineSeg3D &ls)
VW::LineSeg3D operator+ (const VW::LineSeg3D &line, const VW::Point3D &point)
VW::LineSeg3D operator- (const VW::LineSeg3D &line, const VW::Point3D &point)
VW::Point2D Round (const VW::Point2D &p)
Round coordinates to integer values.
VW::Point3D Round (const VW::Point3D &p)
Round coordinates to integer values.
double GetDistance (const VW::Point2D &p1, const VW::Point2D &p2)
Distance between 2 points.
double GetDistance (const VW::Point2D &p, const VW::Line2D &l)
Distance between a point and a line.
double GetDistance (const VW::Point2D &p, const VW::LineSeg2D &l)
Distance between a point and a line segment.
VW::Line2D LineThroughPoints (const VW::Point2D &p1, const VW::Point2D &p2)
Find the line that passes through two points.
VW::Point2D Intersect (const VW::Line2D &l1, const VW::Line2D &l2)
Find the point of intersection of two lines.
double GetAngleBetween (const VW::LineSeg2D &l1, const VW::LineSeg2D &l2)
Get the angle (in radians) between two line segments.
VNL::MatrixFixed< 3, 3, double > GetDerivativeRotationMatrix (const VW::Vector3D &axis, const double angle)
Recover the derivative matrix of a rotation with respect to the angle of rotation.
bool IsToLeft (const VW::Point2D &point, const VW::LineSeg2D &line)
Is the point to the left of the line-segment (only meaningful for lines with a sense of direction).
bool IsToRight (const VW::Point2D &point, const VW::LineSeg2D &line)
Is the point to the right of the line-segment (only meaningful for lines with a sense of direction).
VW::Point2D Project (const VW::Point3D &worldpoint, const VNL::MatrixFixed< 3, 4, double >projectionmatrix)
Project a 3D point onto a 2D point.
VW::LineSeg2D Project (const VW::LineSeg3D &worldline, const VNL::MatrixFixed< 3, 4, double >projectionmatrix)
Project a 3D line-segment onto a 2D line-segment.
template<class Feature >
unsigned int FindNearestPoint (const VW::Point2D &testpoint, const std::vector< Feature > &points)
Find the point that is closest to a 2D location.
template<class Feature >
void FindNNearestPoints (const VW::Point2D &testpoint, const std::vector< Feature > &points, unsigned int n, std::vector< unsigned int > &indices, double max_ratio=0.0)
Find the N nearest points to a 2D location.
template<class Feature >
std::list< Feature >::iterator FindNearestLineSeg (const VW::Point2D &testpoint, std::list< Feature > &lines)
Find the line segment that is closest to a 2D location.
template<class PointFeature >
void GetPointDistribution (const std::vector< PointFeature > &feature_list, double &mean_x, double &mean_y, double &sd)
Calculate the mean position and standard deviation distance of a 2D point set.
template<class PointFeature >
void GetPointDistribution (const std::vector< PointFeature > &feature_list, double &mean_x, double &mean_y, double &mean_z, double &sd)
Calculate the mean position and standard deviation distance of a 3D point set.
template<class PointFeature >
void GetPointDistribution (const std::vector< PointFeature > &feature_list, const std::vector< unsigned int > &which_features, double &mean_x, double &mean_y, double &sd)
Calculate the mean position and standard deviation distance of particular members of a 2D point set.
template<class PointFeature >
void GetPointDistribution (const std::vector< PointFeature > &feature_list, const std::vector< unsigned int > &which_features, double &mean_x, double &mean_y, double &mean_z, double &sd)
Calculate the mean position and standard deviation distance of particular members of a 3D point set.
Point2D operator+ (const Point2D &p1, const Point2D &p2)
Point2D operator- (const Point2D &p)
Point2D operator- (const Point2D &p1, const Point2D &p2)
double operator* (const Point2D &p1, const Point2D &p2)
Point2D operator* (const Point2D &p1, const double a)
Point2D operator* (const double a, const Point2D &p1)
Point2D operator/ (const Point2D &p1, const double a)
double ScalarProduct (const VW::Point2D &p1, const VW::Point2D &p2)
Point3D operator- (const Point3D &p1, const Point3D &p2)
Point3D operator+ (const Point3D &p1, const Point3D &p2)
Point3D operator- (const Point3D &p)
double operator* (const Point3D &p1, const Point3D &p2)
Point3D operator* (const Point3D &p1, const double a)
Point3D operator* (const double a, const Point3D &p1)
Point3D operator* (const VNL::MatrixFixed< 3, 3, double > &M, const Point3D &p1)
Point3D operator/ (const Point3D &p1, const double a)
VW::Point3D VectorProduct (const VW::Point3D &p1, const VW::Point3D &p2)
double ScalarProduct (const VW::Point3D &p1, const VW::Point3D &p2)
double ScalarTripleProduct (const VW::Point3D &p1, const VW::Point3D &p2, const VW::Point3D &p3)
template<>
void ImageCopy (const ImageMono< float > &im, ImageMono< unsigned char > &res)
template<>
void ImageCopy (const ImageYUV< unsigned char > &im, ImageMono< float > &res)
template<>
void ImageCopy (const ImageRGB< unsigned char > &im, ImageMono< float > &res)
template<>
void ImageCopy (const ImageMono< float > &im, ImageRGB< unsigned char > &res)
template<>
void ImageCopy (const ImageMono< int > &im, ImageMono< unsigned char > &res)
template<>
void ImageCopy (const ImageRGB< float > &im, ImageRGB< unsigned char > &res)
INSTANTIATE (ImageMono< unsigned char >, ImageMono< unsigned char >)
INSTANTIATE (ImageMono< float >, ImageMono< float >)
INSTANTIATE (ImageRGB< unsigned char >, ImageRGB< unsigned char >)
INSTANTIATE (ImageRGB< float >, ImageRGB< float >)
INSTANTIATE (ImageYUV< unsigned char >, ImageYUV< unsigned char >)
INSTANTIATE (ImageYUV< float >, ImageYUV< float >)
INSTANTIATE (ImageMono< unsigned char >, ImageMono< float >)
INSTANTIATE (ImageMono< unsigned int >, ImageMono< unsigned char >)
INSTANTIATE (ImageMono< double >, ImageMono< unsigned char >)
INSTANTIATE (ImageMono< unsigned char >, ImageMono< double >)
INSTANTIATE (ImageYUV< unsigned char >, ImageYUV< float >)
INSTANTIATE (ImageYUV< unsigned int >, ImageYUV< unsigned char >)
INSTANTIATE (ImageRGB< unsigned char >, ImageMono< unsigned char >)
INSTANTIATE (ImageYUV< unsigned char >, ImageMono< unsigned char >)
INSTANTIATE (ImageRGB< float >, ImageMono< float >)
INSTANTIATE (ImageYUV< float >, ImageMono< float >)
INSTANTIATE (ImageMono< unsigned char >, ImageRGB< unsigned char >)
INSTANTIATE (ImageYUV< unsigned char >, ImageRGB< unsigned char >)
INSTANTIATE (ImageHSV< unsigned char >, ImageRGB< unsigned char >)
INSTANTIATE (ImageMono< float >, ImageRGB< float >)
INSTANTIATE (ImageYUV< float >, ImageRGB< float >)
INSTANTIATE (ImageHSV< float >, ImageRGB< float >)
INSTANTIATE (ImageMono< unsigned char >, ImageYUV< unsigned char >)
INSTANTIATE (ImageRGB< unsigned char >, ImageYUV< unsigned char >)
INSTANTIATE (ImageMono< float >, ImageYUV< float >)
INSTANTIATE (ImageRGB< float >, ImageYUV< float >)
template<class inType , class outType >
void ImageCopy (const inType &im, outType &res)
Functions for copying one image into another.
template<class inType , class outType >
void ImageFlipCopy (const inType &im, outType &res)
INSTANTIATE (ImageMono< unsigned char >)
INSTANTIATE (ImageMono< unsigned int >)
INSTANTIATE (ImageMono< int >)
INSTANTIATE (ImageMono< float >)
INSTANTIATE (ImageMono< double >)
INSTANTIATE (ImageRGB< unsigned char >)
INSTANTIATE (ImageRGB< unsigned int >)
INSTANTIATE (ImageRGB< int >)
INSTANTIATE (ImageRGB< float >)
INSTANTIATE (ImageRGB< double >)
INSTANTIATE (ImageYUV< unsigned char >)
INSTANTIATE (ImageYUV< unsigned int >)
INSTANTIATE (ImageYUV< int >)
INSTANTIATE (ImageYUV< float >)
INSTANTIATE (ImageYUV< double >)
INSTANTIATE (ImageHSV< unsigned char >)
INSTANTIATE (ImageHSV< unsigned int >)
INSTANTIATE (ImageHSV< int >)
INSTANTIATE (ImageHSV< float >)
INSTANTIATE (ImageHSV< double >)
template<class ImType >
bool ReadImage (FILE *file, ImType &image)
template<class ImType >
bool ReadImage (const std::string &filename, ImType &image)
template<class ImType >
bool WriteImage (FILE *file, const ImType &image)
template<class ImType >
bool WriteImage (const std::string &filename, const ImType &image)
template<class valType >
bool ReadGDIImage (const std::string &filename, VW::ImageMono< valType > &image)
template<class valType >
bool ReadGDIImage (const std::string &filename, VW::ImageYUV< valType > &image)
template<class valType >
bool ReadGDIImage (const std::string &filename, VW::ImageHSV< valType > &image)
template<class valType >
bool ReadGDIImage (const std::string &filename, VW::ImageRGB< valType > &image)
template<class valType >
bool ReadGDIImage (const std::string &filename, VW::ImageRGBPlanes< valType > &image)
template<class valType >
bool WriteGDIImage (const std::string &filename, const VW::ImageMono< valType > &image)
template<class valType >
bool WriteGDIImage (const std::string &filename, const VW::ImageYUV< valType > &image)
template<class valType >
bool WriteGDIImage (const std::string &filename, const VW::ImageHSV< valType > &image)
template<class valType >
bool WriteGDIImage (const std::string &filename, const VW::ImageRGB< valType > &image)
template<class valType >
bool WriteGDIImage (const std::string &filename, const VW::ImageRGBPlanes< valType > &image)
template<>
bool ReadGDIImage< unsigned char > (const std::string &filename, VW::ImageMono< unsigned char > &image)
template<>
bool ReadGDIImage< unsigned char > (const std::string &filename, VW::ImageYUV< unsigned char > &image)
template<>
bool ReadGDIImage< unsigned char > (const std::string &filename, VW::ImageHSV< unsigned char > &image)
template<>
bool ReadGDIImage< unsigned char > (const std::string &filename, VW::ImageRGB< unsigned char > &image)
template<>
bool ReadGDIImage< unsigned char > (const std::string &filename, VW::ImageRGBPlanes< unsigned char > &image)
template<>
bool WriteGDIImage< unsigned char > (const std::string &filename, const VW::ImageMono< unsigned char > &image)
template<>
bool WriteGDIImage< unsigned char > (const std::string &filename, const VW::ImageYUV< unsigned char > &image)
template<>
bool WriteGDIImage< unsigned char > (const std::string &filename, const VW::ImageHSV< unsigned char > &image)
template<>
bool WriteGDIImage< unsigned char > (const std::string &filename, const VW::ImageRGB< unsigned char > &image)
template<>
bool WriteGDIImage< unsigned char > (const std::string &filename, const VW::ImageRGBPlanes< unsigned char > &image)
bool ReadJPEGImage (FILE *filepointer, VW::ImageMono< unsigned char > &image)
bool ReadJPEGImage (FILE *filepointer, VW::ImageMono< float > &image)
bool ReadJPEGImage (FILE *filepointer, VW::ImageYUV< unsigned char > &image)
bool ReadJPEGImage (FILE *filepointer, VW::ImageRGB< unsigned char > &image)
bool WriteJPEGImage (FILE *filepointer, const VW::ImageMono< unsigned char > &image)
bool WriteJPEGImage (FILE *filepointer, const VW::ImageMono< float > &image)
bool WriteJPEGImage (FILE *filepointer, const VW::ImageYUV< unsigned char > &image)
bool WriteJPEGImage (FILE *filepointer, const VW::ImageRGB< unsigned char > &image)
INSTANTIATE (unsigned char)
template<class valType >
bool ReadPPMImage (const std::string &filename, VW::ImageMono< valType > &image)
template<class valType >
bool ReadPPMImage (const std::string &filename, VW::ImageYUV< valType > &image)
template<class valType >
bool ReadPPMImage (const std::string &filename, VW::ImageHSV< valType > &image)
template<class valType >
bool ReadPPMImage (const std::string &filename, VW::ImageRGB< valType > &image)
template<class valType >
bool ReadPPMImage (const std::string &filename, VW::ImageRGBPlanes< valType > &image)
template<class valType >
bool ReadPPMImage (FILE *filepointer, VW::ImageMono< valType > &image)
template<class valType >
bool ReadPPMImage (FILE *filepointer, VW::ImageYUV< valType > &image)
template<class valType >
bool ReadPPMImage (FILE *filepointer, VW::ImageHSV< valType > &image)
template<class valType >
bool ReadPPMImage (FILE *filepointer, VW::ImageRGB< valType > &image)
template<class valType >
bool ReadPPMImage (FILE *filepointer, VW::ImageRGBPlanes< valType > &image)
template<class valType >
bool WritePPMImage (const std::string &filename, const VW::ImageMono< valType > &image)
template<class valType >
bool WritePPMImage (const std::string &filename, const VW::ImageYUV< valType > &image)
template<class valType >
bool WritePPMImage (const std::string &filename, const VW::ImageHSV< valType > &image)
template<class valType >
bool WritePPMImage (const std::string &filename, const VW::ImageRGB< valType > &image)
template<class valType >
bool WritePPMImage (const std::string &filename, const VW::ImageRGBPlanes< valType > &image)
template<class valType >
bool WritePPMImage (FILE *filepointer, const VW::ImageMono< valType > &image)
template<class valType >
bool WritePPMImage (FILE *filepointer, const VW::ImageYUV< valType > &image)
template<class valType >
bool WritePPMImage (FILE *filepointer, const VW::ImageHSV< valType > &image)
template<class valType >
bool WritePPMImage (FILE *filepointer, const VW::ImageRGB< valType > &image)
template<class valType >
bool WritePPMImage (FILE *filepointer, const VW::ImageRGBPlanes< valType > &image)
template<>
bool ReadPPMImage< unsigned char > (FILE *filepointer, VW::ImageMono< unsigned char > &image)
template<>
bool ReadPPMImage< unsigned char > (FILE *filepointer, VW::ImageYUV< unsigned char > &image)
template<>
bool ReadPPMImage< unsigned char > (FILE *filepointer, VW::ImageHSV< unsigned char > &image)
template<>
bool ReadPPMImage< unsigned char > (FILE *filepointer, VW::ImageRGB< unsigned char > &image)
template<>
bool ReadPPMImage< unsigned char > (FILE *filepointer, VW::ImageRGBPlanes< unsigned char > &image)
template<>
bool WritePPMImage< unsigned char > (FILE *filepointer, const VW::ImageMono< unsigned char > &image)
template<>
bool WritePPMImage< unsigned char > (FILE *filepointer, const VW::ImageYUV< unsigned char > &image)
template<>
bool WritePPMImage< unsigned char > (FILE *filepointer, const VW::ImageHSV< unsigned char > &image)
template<>
bool WritePPMImage< unsigned char > (FILE *filepointer, const VW::ImageRGB< unsigned char > &image)
template<>
bool WritePPMImage< unsigned char > (FILE *filepointer, const VW::ImageRGBPlanes< unsigned char > &image)
template<class Type >
VW::PixelMono< double > operator* (const VW::PixelMono< Type > &p, const double a)
template<class Type >
VW::PixelMono< double > operator* (const double a, const VW::PixelMono< Type > &p)
template<class Type >
VW::PixelMono< float > operator* (const VW::PixelMono< Type > &p, const float a)
template<class Type >
VW::PixelMono< float > operator* (const float a, const VW::PixelMono< Type > &p)
template<class Type >
VW::PixelMono< Type > operator+ (const VW::PixelMono< Type > &p1, const VW::PixelMono< Type > &p2)
template<class Type >
VW::PixelMono< Type > operator- (const VW::PixelMono< Type > &p1, const VW::PixelMono< Type > &p2)
template<class Type >
VW::PixelRGB< double > operator* (const VW::PixelRGB< Type > &p, const double a)
template<class Type >
VW::PixelRGB< double > operator* (const double a, const VW::PixelRGB< Type > &p)
template<class Type >
VW::PixelRGB< float > operator* (const VW::PixelRGB< Type > &p, const float a)
template<class Type >
VW::PixelRGB< float > operator* (const float a, const VW::PixelRGB< Type > &p)
template<class Type >
VW::PixelRGB< Type > operator+ (const VW::PixelRGB< Type > &p1, const VW::PixelRGB< Type > &p2)
template<class Type >
VW::PixelRGB< Type > operator- (const VW::PixelRGB< Type > &p1, const VW::PixelRGB< Type > &p2)
template<class Type >
VW::PixelYUV< double > operator* (const VW::PixelYUV< Type > &p, const double a)
template<class Type >
VW::PixelYUV< double > operator* (const double a, const VW::PixelYUV< Type > &p)
template<class Type >
VW::PixelYUV< float > operator* (const VW::PixelYUV< Type > &p, const float a)
template<class Type >
VW::PixelYUV< float > operator* (const float a, const VW::PixelYUV< Type > &p)
template<class Type >
VW::PixelYUV< Type > operator+ (const VW::PixelYUV< Type > &p1, const VW::PixelYUV< Type > &p2)
template<class Type >
VW::PixelYUV< Type > operator- (const VW::PixelYUV< Type > &p1, const VW::PixelYUV< Type > &p2)
void PixelList2ClassifierUVMatrix (const std::string &pixellist_filename, const std::string &matrix_filename, unsigned int binsize=2)
A function to load a list of pixel data and output a classification matrix.
INSTANTIATE (float, float, float)
INSTANTIATE (float, unsigned char, float)
INSTANTIATE (int, unsigned char, unsigned char)
INSTANTIATE (float, unsigned char, unsigned char)
void SortStrongestFirst (std::vector< CornerFeature > &list)
Sort into order of decreasing strength.
void SortByStrength (std::vector< CornerFeature > &list)
Sort into order of increasing strength.
void SortByXValue (std::vector< CornerFeature > &list)
Sort into order of increasing X-value.
void SortByYValue (std::vector< CornerFeature > &list)
Sort into order of increasing Y-value.
std::ostream & operator<< (std::ostream &os, const DOGDetectorParams &p)
void GetInterpolatedImagePatch (const ImageMono< unsigned char > &im, const double x, const double y, VW::ImagePatch &patch)
Create a re-sampled image patch using bilinear interpolation.
void GetInterpolatedImagePatch (const ImageMono< float > &im, const double x, const double y, VW::ImagePatch &patch)
Create a re-sampled image patch using bilinear interpolation.
void GetInterpolatedImagePatch (const ImageYUV< unsigned char > &im, const double x, const double y, VW::ImagePatch &patch)
Create a re-sampled image patch from the Y channel of a YUV image using bilinear interpolation.
void GetImagePatch (const ImageMono< unsigned char > &im, const double x, const double y, VW::ImagePatch &patch)
Create an image patch without interpolation.
void GetImagePatch (const ImageMono< float > &im, const double x, const double y, VW::ImagePatch &patch)
Create an image patch without interpolation.
void GetImagePatch (const ImageYUV< unsigned char > &im, const double x, const double y, VW::ImagePatch &patch)
Create an image patch from the Y channel of a YUV image without interpolation.
void GetInterpolatedImagePatch (const ImageYUV< unsigned char > &im, const double x, const double y, VW::ImagePatchYUV &patch)
Create a re-sampled image patch from the Y channel of a YUV image using bilinear interpolation.
void GetImagePatch (const ImageYUV< unsigned char > &im, const double x, const double y, VW::ImagePatchYUV &patch)
Create an image patch from the Y channel of a YUV image without interpolation.
void SortAscending (std::vector< MatchData > &list)
Sort into order of increasing match score.
void SortDescending (std::vector< MatchData > &list)
Sort into order of decreasing match score.
template<class FeatureType >
void MatchesToPointLists (const std::vector< FeatureType > &old_features, const std::vector< FeatureType > &new_features, const std::vector< VW::MatchData > &matches, std::vector< VW::Point2D > &old_points, std::vector< VW::Point2D > &new_points)
A utility function to make lists of matched point2d's from lists of features and correspondence data.
template<class FeatureType >
void MatchesToPointLists (const std::vector< FeatureType > &old_features, const std::vector< FeatureType > &new_features, const std::vector< VW::MatchData > &matches, std::vector< VW::Point2D > &old_points, std::vector< VW::Point2D > &new_points, std::vector< double > &scores)
A utility function to make lists of matched point2d's from lists of features and correspondence data, including a list of the scores (priors).
std::ostream & operator<< (std::ostream &s, const VW::MatchData &m)
std::istream & operator>> (std::istream &s, VW::MatchData &m)
template<class Type >
void NormaliseIntensity (VW::ImageMono< Type > &image, double desired_stddev)
template<class Type >
void NormaliseIntensity (VW::ImageYUV< Type > &image, double desired_stddev)
template void NormaliseIntensity (VW::ImageMono< unsigned char > &, double)
template void NormaliseIntensity (VW::ImageYUV< unsigned char > &, double)
std::ostream & operator<< (std::ostream &s, const ZNPatch &p)
std::ostream & operator<< (std::ostream &s, const PatchFeature &f)
void SortByStrength (std::vector< PlesseyCorner > &list)
Sort into order of increasing strength.
void SortByXValue (std::vector< PlesseyCorner > &list)
Sort into order of increasing X-value.
void SortByYValue (std::vector< PlesseyCorner > &list)
Sort into order of increasing Y-value.
void SortByStrength (std::vector< PlesseyCornerYUV > &list, bool strongest_first=true)
Sort into order of in/decreasing strength.
void SortByXValue (std::vector< PlesseyCornerYUV > &list)
Sort into order of increasing X-value.
void SortByYValue (std::vector< PlesseyCornerYUV > &list)
Sort into order of increasing Y-value.
INSTANTIATE (float)
bool SaveSiftFeature (const SiftFeature &feature, const char *filename)
bool LoadSiftFeature (SiftFeature &feature, const char *filename)
std::ostream & operator<< (std::ostream &os, const SiftParameters &p)
int SiftMatchNN (const SiftFeature &key, const std::vector< SiftFeature > &database, double distance_ratio_max=0.8, double min_strength=1.0)
std::ostream & operator<< (std::ostream &s, const SIFTFeature &f)
bool FileExists (const std::string &filename)
Determine whether the specified file exists.
int FindFileSize (const std::string &filename)
Find the size of a file.
bool IsADirectory (const std::string &name)
Is this a directory (true) or a file (false).
bool GetFileList (const std::string &directoryname, std::vector< std::string > &filenames, bool fullpaths=true)
Get the list of files in a directory.
bool GetSubdirectoryList (const std::string &directoryname, std::vector< std::string > &subdirectories, bool fullpaths=true)
Get the list of subdirectories of a directory.
std::string GetFilePath (const std::string &filename)
Split out the path from a fully qualified filename (not including the final '/').
std::string GetFileBasename (const std::string &filename)
Recover the base of a filename (ie everything between the last '/' and the last dot).
std::string GetFileExtension (const std::string &filename)
Recover the suffix of a filename (ie everything up to the last dot).
std::string StripPath (const std::string &filename)
Remove the path component of the filename.
void SplitFilename (const std::string &filename, std::string &path, std::string &base, std::string &extension)
Split a filename into path+'/'+base+'.
std::string ReformFilename (const std::string &path, const std::string &base, const std::string &extension)
Refrom a filename from its path, base and extension.
bool CopyFile (const std::string &sourcefile, const std::string &destfile)
Copy a file from one location to another (binary).
std::ostream & WriteBinary (std::ostream &stream, const char &value)
Convert a standard type to a binary string.
std::ostream & WriteBinary (std::ostream &stream, const unsigned char &value)
std::ostream & WriteBinary (std::ostream &stream, const int &value)
std::ostream & WriteBinary (std::ostream &stream, const unsigned int &value)
std::ostream & WriteBinary (std::ostream &stream, const float &value)
std::ostream & WriteBinary (std::ostream &stream, const double &value)
std::ostream & WriteBinary (std::ostream &stream, const double *values, unsigned int n)
Write an array of n entries.
std::ostream & WriteBinary (std::ostream &stream, const float *values, unsigned int n)
std::istream & ReadBinary (std::istream &stream, char &value)
Read a binary string and convert to a standard type.
std::istream & ReadBinary (std::istream &stream, unsigned char &value)
std::istream & ReadBinary (std::istream &stream, int &value)
std::istream & ReadBinary (std::istream &stream, unsigned int &value)
std::istream & ReadBinary (std::istream &stream, float &value)
std::istream & ReadBinary (std::istream &stream, double &value)
std::istream & ReadBinary (std::istream &stream, double *values, unsigned int n)
std::istream & ReadBinary (std::istream &stream, float *values, unsigned int n)
bool FindXMLBlock (const std::string &block_name, std::istream &input_stream, std::string &name)
Find an XML block and leave the stream pointing to its contents.
bool GetXMLBlock (const std::string &block_name, std::istream &input_stream, std::istringstream &contents, std::string &name)
Find an XML block and read its contents into a string.
bool GetXMLBlock (const std::string &block_name, const std::string &input_string, std::string &contents, std::string &name)
Find an XML block and return its contents.
bool GetXMLBlockAsNumber (const std::string &block_name, std::istream &input_string, double &contents, std::string &name)
Find an XML block and return its contents as a double precision number.
bool GetXMLBlockAsNumber (const std::string &block_name, std::istream &input_string, float &contents, std::string &name)
Find an XML block and return its contents as a floating point number.
bool GetXMLBlockAsNumber (const std::string &block_name, std::istream &input_string, int &contents, std::string &name)
Find an XML block and return its contents as an unsigned integer number.
bool GetXMLBlockAsNumber (const std::string &block_name, std::istream &input_string, unsigned int &contents, std::string &name)
Find an XML block and return its contents as an unsigned integer number.
bool GetMultipleXMLBlocks (const std::string &block_name, std::istream &input_string, std::vector< std::string > &contents, std::vector< std::string > &names)
Find all XML blocks matching the given tag and return their contents.
bool FindNextXMLTag (std::istream &input_file, std::string &tagname, std::string &arguments)
Skip forwards to the next XML-style tag.
template<class T >
bool ReadXMLString (const std::string &str, T &data)
Read a string into a value.
template<class T >
std::string GenerateXMLString (const T &data, unsigned int indentation=0)
Generate an XML string for a type.
double LinearAtan2 (double y, double x)
Fast approximation to arc-tangent over full range.
VNL::MatrixFixed< 2, 2, double > operator* (const VNL::MatrixFixed< 2, 2, double > &M, const Covariance2D &C)
Pre-multiply by an arbitrary quare matrix Cost is 12 flops.
VNL::MatrixFixed< 2, 2, double > operator* (const Covariance2D &C, const VNL::MatrixFixed< 2, 2, double > &M)
Post-multiply by an arbitrary quare matrix Cost is 12 flops.
VW::Covariance2D MapCovariance (const VNL::MatrixFixed< 2, 2, double > &M, const Covariance2D &C)
Map the Covariance using another matrix C2 = M*C*M' Cost is 21 flops.
VNL::MatrixFixed< 3, 3, double > operator* (const VNL::MatrixFixed< 3, 3, double > &M, const Covariance3D &C)
Pre-multiply by an arbitrary quare matrix Cost is 45 flops.
VNL::MatrixFixed< 3, 3, double > operator* (const Covariance3D &C, const VNL::MatrixFixed< 3, 3, double > &M)
Post-multiply by an arbitrary quare matrix Cost is 45 flops.
VW::Covariance3D MapCovariance (const VNL::MatrixFixed< 3, 3, double > &M, const Covariance3D &C)
Map the Covariance using another matrix C2 = M*C*M' Cost is 75 flops.
double PadeExp11 (const double x)
An approximation to exp using the 1,1 Pade approximation, valid to within 10% up to x=1.0 (3 flops).
double PadeExp22 (const double x)
An approximation to exp using the 1,1 Pade approximation, valid to within 10% up to x=2.3 (7 flops).
double PadeExp33 (const double x)
An approximation to exp using the 3,3 Pade approximation, valid to within 10% up to x=3.45 (11 flops).
double PadeExp44 (const double x)
An approximation to exp using the 4,4 Pade approximation, valid to within 10% up to x=4.85 (15 flops).
std::ostream & operator<< (std::ostream &stream, const VW::Histogram &H)
std::ostream & operator<< (std::ostream &stream, const Histogram2D &H)
bool IsNaN (double x)
Return true iff x is "Not a Number".
bool IsFinite (double x)
Return true if x is neither NaN nor Inf.
void SeedRand ()
Seed the random number generator with a time-dependent seed (comes from clock).
double Rand (double upper)
Get a random number in the range 0 <= x < upper.
int RandInt (int upper)
Get a random integer number in the range 0 <= x < upper.
std::ostream & operator<< (std::ostream &stream, const Timer &timer)
void XInit (int argc, char **argv)
void XLoop ()
void GetAndDispatchXEvent ()
std::ostream & operator<< (std::ostream &s, const AWFFace &f)
void ReadAWFMaterialsFile (const std::string &filename, std::vector< AWFMaterial > &materials)
Read a materials (.mtl) file and add the materials contained to the result vector.
std::ostream & operator<< (std::ostream &s, const AWFMaterial &m)
void AddDefaultAWFMaterials (std::vector< AWFMaterial > &materials)
void DrawFireI (VW::ThreeDToolGLCommon &display, const VW::Vector3D &position, const VW::Quaternion &orientation)
Draw a model of the Unibrain Fire-I camera.
void DrawGTI (VW::ThreeDToolGLCommon &display, const VW::Vector3D &position, const VW::Quaternion &orientation)
Draw a model of the GTI mobile robot.
void DrawGTIWithYorick (VW::ThreeDToolGLCommon &display, const VW::Vector3D &position, const VW::Quaternion &orientation, const double yorickpan=0, const double yoricktilt=0, const double yorickvergeleft=0, const double yorickvergeright=0, const std::string &yorickcameratype="VL500")
Draw a model of the GTI mobile robot.
void DrawThreeQuarterDesk (VW::ThreeDToolGLCommon &display, const VW::Vector3D &position, const VW::Quaternion &orientation, bool origin_on_desk=true)
Draw a model of a three-quarter corner desk.
void DrawVL500 (VW::ThreeDToolGLCommon &display, const VW::Vector3D &position, const VW::Quaternion &orientation, bool origin_is_optic_centre=true)
Draw a model of the Sony VL500 camera.
void DrawWeRo (VW::ThreeDToolGLCommon &display, const VW::Vector3D &position, const VW::Quaternion &orientation, const double tilt=0, const double pan=0, const double cyclo=0, const bool origin_at_camera_centre=false)
Draw a model of the WeRo active head.
void DrawYorick811 (VW::ThreeDToolGLCommon &display, const VW::Vector3D &position, const VW::Quaternion &orientation, const double pan=0, const double tilt=0, const double vergeleft=0, const double vergeright=0, const std::string &cameratype="VL500")
Draw a model of the Yorick811 active head.
void GLUTInit (int argc, char **argv, bool use_idler=false)
void GLUTLoop ()
IMPLEMENT_DYNAMIC_CLASS (DisplayWxGLWidget, wxGLCanvas)
IMPLEMENT_CLASS (SequencerFileWx, wxPanel)
IMPLEMENT_CLASS (SequencerFirewireWx, wxPanel)
Variables
const double NaN = 0.0/0.0
Detailed Description
Compute instantiations for Improc.
ParameterWriter.
method type for scaling, warping etc.
Here we have instantiations of varioius compute functions for PlesseyCorners. For dependency reasons, it has to be done here rather than in the Geom directory.
Author:
BJ Tordoff
Date:
05/07/2004
Write out a parameter list definition to a parameter file, as defined in paramfiles.README
Typedef Documentation
typedef std::deque<Edgel *> VW::EdgeString
typedef void* VW::FuncRetType
typedef ImageInterleave<unsigned char, 2> VW::ImageInterleave16
typedef ImageInterleave<unsigned char, 4> VW::ImageInterleave32
typedef pthread_mutex_t VW::MutexType
typedef pthread_t VW::ThreadType
typedef Point2D VW::Vector2D
typedef Point3D VW::Vector3D
Enumeration Type Documentation
enum VW::AWFFaceType
Enumerator:
VertexOnly
WithTexture
WithNormal
WithTextureAndNormal
enum VW::AWFMaterialType
Enumerator:
DiffuseMaterial
AmbientMaterial
SpecularMaterial
enum VW::GLMaterialType
Some predefined material types for GL use.
Enumerator:
GLMATERIAL_BRASS
GLMATERIAL_REDPLASTIC
GLMATERIAL_EMERALD
GLMATERIAL_SLATE
enum VW::InterfaceType
The interface type.
GTK Interfaces can be attached to a form as either a complete encapsulated widget or as a button that pops up a window.
Enumerator:
INTERFACE_AS_WIDGET
INTERFACE_AS_BUTTONWINDOW
enum VW::InterpolationMethod
Enumerator:
NearestNeighbour
Bilinear
Biquadratic
Bicubic
enum VW::MatcherType
Enumerator:
BRAINDEAD_MATCHER
REPEATEDLY_STUPID_MATCHER
enum VW::SequencerLoopMode
What should the sequencer do when it gets to the end of the sequence?
Enumerator:
NO_LOOPING
Stop (and print an error to cerr if _Step() is called again).
LOOP
Continue from the start of the sequence.
BOUNCE
Start playing the sequence backwards.
REPEATLAST
Continue to repeat the last frame.
Function Documentation
void VW::AccumulateWeights (const std::vector< double > & weights, std::vector< double > & cumulative_weights, std::vector< unsigned int > * include_only = 0) [inline]
Create a cumulative probability list from a probability list.
References c.
Referenced by VW::FMatrixAffineComputePreemptive::Compute(), VW::EssentialMatrixComputePreemptive::Compute(), VW::Homography2DCompute::GUISACCore(), VW::FMatrixAffineCompute::GUISACCore(), VW::Line2DCompute::GUISACFromPoints(), VW::Homography2DCompute::GUNSACCore(), and VW::FMatrixCompute::GUNSACCore().
void VW::AddDefaultAWFMaterials (std::vector< AWFMaterial > & materials)
References DiffuseMaterial, m, VW::AWFMaterial::SetAmbientColour(), VW::AWFMaterial::SetDiffuseColour(), VW::AWFMaterial::SetShininess(), VW::AWFMaterial::SetSpecularColour(), VW::AWFMaterial::SetType(), and SpecularMaterial.
Referenced by VW::AWFObject::LoadFile().
bool VW::CopyFile (const std::string & sourcefile, const std::string & destfile)
Copy a file from one location to another (binary).
Referenced by VW::AWFObject::SaveAll(), and VW::AWFObject::SaveAsVRML().
void VW::CreateRandomisedList (std::vector< unsigned int > & indices, unsigned int max_index)
Create a random list of the numbers from 0 to (max_index-1) where each number is gauranteed to be listed exactly once.
Referenced by VW::FMatrixAffineComputePreemptive::Compute(), and VW::EssentialMatrixComputePreemptive::Compute().
bool VW::FileExists (const std::string & filename)
Determine whether the specified file exists.
int VW::FindFileSize (const std::string & filename)
Find the size of a file.
Returns size in bytes, or zero if no file found.
template<class Feature > std::list< Feature >::iterator VW::FindNearestLineSeg (const VW::Point2D & testpoint, std::list< Feature > & lines) [inline]
Find the line segment that is closest to a 2D location.
template<class Feature > unsigned int VW::FindNearestPoint (const VW::Point2D & testpoint, const std::vector< Feature > & points) [inline]
Find the point that is closest to a 2D location.
bool VW::FindNextXMLTag (std::istream & input_file, std::string & tagname, std::string & arguments)
Skip forwards to the next XML-style tag.
Intermediate material is discarded, and if no tag is found before the end of the input the result is false. When a tag is found, the result is true, the tag name is returned in 'tagname' and any arguments found are returned in 'arguments'.
Referenced by FindXMLBlock(), and GetXMLBlock().
template<class Feature > void VW::FindNNearestPoints (const VW::Point2D & testpoint, const std::vector< Feature > & points, unsigned int n, std::vector< unsigned int > & indices, double max_ratio = 0.0) [inline]
Find the N nearest points to a 2D location.
Parameters:
testpoint the location that is searched around
points the list of points to be scanned
n the maximum number of points to find
indices the indices of the nearest points
max_ratio points are only included if their distance is less than max_ratio times the best distance. If zero, all points are considered.
bool VW::FindXMLBlock (const std::string & block_name, std::istream & input_stream, std::string & name)
Find an XML block and leave the stream pointing to its contents.
The input stream is scanned for the <name> block but the contents are not read. Use this where the block contents may be large, otherwise just read the block into a string using the functions which follow, as this gives better error protection.
References FindNextXMLTag(), GetNameFromArgs(), and VERBOSE.
Referenced by PixelList2ClassifierUVMatrix(), VW::Quaternion::ReadXML(), VW::Point3D::ReadXML(), VW::Point2D::ReadXML(), VW::LineSeg2D::ReadXML(), VW::Line2D::ReadXML(), VW::ImagePatchYUV::ReadXML(), VW::ImagePatch::ReadXML(), VW::FirewireCamera::ReadXML(), VW::ClassifierUV::ReadXML(), VW::CalibrationTable::ReadXML(), VW::CalibrationMatrix::ReadXML(), and VW::AngleAxis::ReadXML().
void VW::GeneratePointsInCuboid (const double width, const double height, const double depth, const unsigned int num_points, std::vector< VW::Point3D > & worldpoints)
Cuboid centered around origin.
References Rand().
void VW::GeneratePointsInShell (const double inner_radius, const double outer_radius, const unsigned int num_points, std::vector< VW::Point3D > & worldpoints)
Generate a cloud of points in a spherical shell centered at origin.
References PI, Rand(), std::sqrt(), and TWOPI.
void VW::GeneratePointsInShellPatch (const double inner_radius, const double outer_radius, const double max_angle, const unsigned int num_points, std::vector< VW::Point3D > & worldpoints)
Generate a cloud of points in a square patch on a spherical shell centered at the origin and pointing along 'z' (max_angle gives conic half-angle, and is in radians.
Do not give an angle greater than PI/2, as this will spoil the distribution of points)
References Rand(), and std::sqrt().
void VW::GeneratePointsInSphere (const double radius, const unsigned int num_points, std::vector< VW::Point3D > & worldpoints)
Generate a cloud of points filling a sphere centered at origin.
References PI, Rand(), std::sqrt(), and TWOPI.
void VW::GeneratePointsOnSphereSurface (const double radius, const unsigned int num_points, std::vector< VW::Point3D > & worldpoints)
Generate a cloud of points on a spherical surface centered at origin.
References PI, Rand(), and TWOPI.
template<class T > std::string VW::GenerateXMLString (const T & data, unsigned int indentation = 0) [inline]
Generate an XML string for a type.
For simple values this is just a >> operation, but can be overloaded for complex data-types to include creation of XML marked member-types.
Referenced by VW::ParameterWriter::AddChildParameter(), VW::ParameterWriter::AddChildParameters(), and VW::ParameterWriter::AddParameter().
void VW::GetAndDispatchXEvent ()
References globalXdisplay, and xdisplaylist.
Referenced by XLoop().
double VW::GetAngleBetween (const VW::LineSeg2D & l1, const VW::LineSeg2D & l2) [inline]
Get the angle (in radians) between two line segments.
References VW::LineSeg2D::GetAngle().
VNL::MatrixFixed< 3, 3, double > VW::GetDerivativeRotationMatrix (const VW::Vector3D & axis, const double angle)
Recover the derivative matrix of a rotation with respect to the angle of rotation.
References VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), and VW::Point3D::Norm().
double VW::GetDistance (const VW::Point2D & p, const VW::LineSeg2D & l) [inline]
Distance between a point and a line segment.
Note that this is the distance to the closest end if the point does not project onto the segment.
References VW::LineSeg2D::GetDistanceToLineSeg().
double VW::GetDistance (const VW::Point2D & p, const VW::Line2D & l) [inline]
Distance between a point and a line.
References VW::Line2D::GetDistance().
double VW::GetDistance (const VW::Point2D & p1, const VW::Point2D & p2) [inline]
Distance between 2 points.
Referenced by VW::RadialDistortionCompute::LeastSquaresFunction::F().
double VW::GetDistanceVariance (const VW::Point2D & dest_point, const VW::Line2D & epipolar_line, const VW::Covariance3D & epipolar_line_covar, const float image_noise_variance)
Find the variance of the distance between point and line given the line uncertainty and image noise (in image 2).
Note that the line and its covariance must be normalised (using VW::NormaliseLine).
References VW::Point2D::GetX(), VW::Point2D::GetY(), and v.
std::string VW::GetFileBasename (const std::string & filename)
Recover the base of a filename (ie everything between the last '/' and the last dot).
std::string VW::GetFileExtension (const std::string & filename)
Recover the suffix of a filename (ie everything up to the last dot).
If the dot is the last character, or doesn't exist, an empty string is returned.
bool VW::GetFileList (const std::string & directoryname, std::vector< std::string > & filenames, bool fullpaths = true)
Get the list of files in a directory.
References IsADirectory().
std::string VW::GetFilePath (const std::string & filename)
Split out the path from a fully qualified filename (not including the final '/').
Referenced by VW::AWFObject::LoadFile().
void VW::GetImagePatch (const ImageYUV< unsigned char > & im, const double x, const double y, VW::ImagePatchYUV & patch)
Create an image patch from the Y channel of a YUV image without interpolation.
References VW::ImagePatchYUV::GetHeight(), VW::ImagePatchYUV::GetWidth(), VW::ImagePatchYUV::SetData(), and v.
void VW::GetImagePatch (const ImageYUV< unsigned char > & im, const double x, const double y, VW::ImagePatch & patch)
Create an image patch from the Y channel of a YUV image without interpolation.
References VW::ImagePatch::GetHeight(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetPixel(), VW::ImagePatch::GetWidth(), and VW::ImagePatch::SetData().
void VW::GetImagePatch (const ImageMono< float > & im, const double x, const double y, VW::ImagePatch & patch)
Create an image patch without interpolation.
References VW::ImagePatch::GetHeight(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetPixel(), VW::ImagePatch::GetWidth(), and VW::ImagePatch::SetData().
void VW::GetImagePatch (const ImageMono< unsigned char > & im, const double x, const double y, VW::ImagePatch & patch)
Create an image patch without interpolation.
References VW::ImagePatch::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetPixel(), VW::ImagePatch::GetWidth(), VW::ImagePatch::SetData(), and VW::PixelMono< Type >::y.
Referenced by VW::GetPlesseyCorner::GetPlesseyCorner(), and VW::GetPlesseyCornerYUV::GetPlesseyCornerYUV().
void VW::GetInterpolatedImagePatch (const ImageYUV< unsigned char > & im, const double x, const double y, VW::ImagePatchYUV & patch)
Create a re-sampled image patch from the Y channel of a YUV image using bilinear interpolation.
References VW::ImagePatchYUV::GetHeight(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetPixel(), VW::ImagePatchYUV::GetWidth(), and VW::ImagePatchYUV::SetData().
void VW::GetInterpolatedImagePatch (const ImageYUV< unsigned char > & im, const double x, const double y, VW::ImagePatch & patch)
Create a re-sampled image patch from the Y channel of a YUV image using bilinear interpolation.
References VW::ImagePatch::GetHeight(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetPixel(), VW::ImagePatch::GetWidth(), and VW::ImagePatch::SetData().
void VW::GetInterpolatedImagePatch (const ImageMono< float > & im, const double x, const double y, VW::ImagePatch & patch)
Create a re-sampled image patch using bilinear interpolation.
References VW::ImagePatch::GetHeight(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetPixel(), VW::ImagePatch::GetWidth(), and VW::ImagePatch::SetData().
void VW::GetInterpolatedImagePatch (const ImageMono< unsigned char > & im, const double x, const double y, VW::ImagePatch & patch)
Create a re-sampled image patch using bilinear interpolation.
References VW::ImagePatch::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetPixel(), VW::ImagePatch::GetWidth(), VW::ImagePatch::SetData(), and VW::PixelMono< Type >::y.
Referenced by VW::GetPlesseyCorner::GetPlesseyCorner(), and VW::GetPlesseyCornerYUV::GetPlesseyCornerYUV().
bool VW::GetMultipleXMLBlocks (const std::string & block_name, std::istream & input_string, std::vector< std::string > & contents, std::vector< std::string > & names)
Find all XML blocks matching the given tag and return their contents.
The input string is scanned for any <name>...</name> blocks and the contents returned for each along with the name (if any).
template<class PointFeature > void VW::GetPointDistribution (const std::vector< PointFeature > & feature_list, const std::vector< unsigned int > & which_features, double & mean_x, double & mean_y, double & mean_z, double & sd) [inline]
Calculate the mean position and standard deviation distance of particular members of a 3D point set.
This is used for optimal normalisation of inlier point data, amoungst others.
References std::sqrt().
template<class PointFeature > void VW::GetPointDistribution (const std::vector< PointFeature > & feature_list, const std::vector< unsigned int > & which_features, double & mean_x, double & mean_y, double & sd) [inline]
Calculate the mean position and standard deviation distance of particular members of a 2D point set.
This is used for optimal normalisation of inlier point data, amoungst others.
References std::sqrt().
template<class PointFeature > void VW::GetPointDistribution (const std::vector< PointFeature > & feature_list, double & mean_x, double & mean_y, double & mean_z, double & sd) [inline]
Calculate the mean position and standard deviation distance of a 3D point set.
This is used for optimal normalisation of point data, amoungst others.
References std::sqrt().
template<class PointFeature > void VW::GetPointDistribution (const std::vector< PointFeature > & feature_list, double & mean_x, double & mean_y, double & sd) [inline]
Calculate the mean position and standard deviation distance of a 2D point set.
This is used for optimal normalisation of point data, amoungst others.
References std::sqrt().
Referenced by VW::Normalisation3D::Init(), and VW::Normalisation::Init().
bool VW::GetSubdirectoryList (const std::string & directoryname, std::vector< std::string > & subdirectories, bool fullpaths = true)
Get the list of subdirectories of a directory.
bool VW::GetXMLBlock (const std::string & block_name, const std::string & input_string, std::string & contents, std::string & name)
Find an XML block and return its contents.
The input string is scanned for a <name>...</name> block and the contents returned. This version takes a string as input, but otherwise behaves exactly as the stream version. Note that if the block contents are likely to be large, the VW::FindXMLBlock function should be used.
References GetXMLBlock(), and VERBOSE.
bool VW::GetXMLBlock (const std::string & block_name, std::istream & input_stream, std::istringstream & contents, std::string & name)
Find an XML block and read its contents into a string.
The input stream is scanned for a <name>...</name> block and the contents returned. Note that if the block contents are likely to be large, the VW::FindXMLBlock function should be used.
References c, FindNextXMLTag(), GetNameFromArgs(), and VERBOSE.
Referenced by GetXMLBlock(), GetXMLBlockAsNumber(), PixelList2ClassifierUVMatrix(), VW::Quaternion::ReadXML(), VW::Point2D::ReadXML(), VW::Line2D::ReadXML(), VW::ImagePatchYUV::ReadXML(), VW::ImagePatch::ReadXML(), VW::FirewireCamera::ReadXML(), VW::CalibrationTable::ReadXML(), VW::CalibrationMatrix::ReadXML(), and VW::AngleAxis::ReadXML().
bool VW::GetXMLBlockAsNumber (const std::string & block_name, std::istream & input_string, unsigned int & contents, std::string & name)
Find an XML block and return its contents as an unsigned integer number.
References GetXMLBlock(), and VERBOSE.
bool VW::GetXMLBlockAsNumber (const std::string & block_name, std::istream & input_string, int & contents, std::string & name)
Find an XML block and return its contents as an unsigned integer number.
References GetXMLBlock(), and VERBOSE.
bool VW::GetXMLBlockAsNumber (const std::string & block_name, std::istream & input_string, float & contents, std::string & name)
Find an XML block and return its contents as a floating point number.
References GetXMLBlock(), and VERBOSE.
bool VW::GetXMLBlockAsNumber (const std::string & block_name, std::istream & input_string, double & contents, std::string & name)
Find an XML block and return its contents as a double precision number.
References GetXMLBlock(), and VERBOSE.
Referenced by VW::Point3D::ReadXML(), VW::ImagePatchYUV::ReadXML(), VW::ImagePatch::ReadXML(), VW::ClassifierUV::ReadXML(), and VW::CalibrationTable::ReadXML().
void VW::GLUTInit (int argc, char ** argv, bool use_idler = false)
References GLUT_INITIALISED, USE_IDLER, and VERBOSE.
void VW::GLUTLoop ()
References VERBOSE.
template<> unsigned int VW::Homography2D::GetMinFeatures< VW::LineSeg2D > (const VW::LineSeg2D &) [inline]
template<> unsigned int VW::Homography2D::GetMinFeatures< VW::Point2D > (const VW::Point2D &) [inline]
template<> void VW::ImageCopy (const ImageRGB< float > & im, ImageRGB< unsigned char > & res) [inline]
template<> void VW::ImageCopy (const ImageMono< int > & im, ImageMono< unsigned char > & res) [inline]
template<> void VW::ImageCopy (const ImageMono< float > & im, ImageRGB< unsigned char > & res) [inline]
template<> void VW::ImageCopy (const ImageRGB< unsigned char > & im, ImageMono< float > & res) [inline]
template<> void VW::ImageCopy (const ImageYUV< unsigned char > & im, ImageMono< float > & res) [inline]
template<> void VW::ImageCopy (const ImageMono< float > & im, ImageMono< unsigned char > & res) [inline]
Referenced by VW::PyramidYUV< StorageType >::Compute(), VW::Pyramid< StorageType >::Compute(), VW::SequencerMovie::CopyImage(), VW::SequencerFile::CopyImage(), VW::DrawFunctions::Draw(), VW::ThreeDToolGLCommon::GetImage(), VW::Sift::MakeResultImage(), ReadGDIImage(), ReadPPMImage(), WriteGDIImage(), and WritePPMImage().
template<class inType , class outType > void VW::ImageFlipCopy (const inType & im, outType & res) [inline]
References c.
VW::IMPLEMENT_CLASS (SequencerFirewireWx , wxPanel)
VW::IMPLEMENT_CLASS (SequencerFileWx , wxPanel)
VW::IMPLEMENT_DYNAMIC_CLASS (DisplayWxGLWidget , wxGLCanvas)
VW::INSTANTIATE (float)
VW::INSTANTIATE (float , unsigned char, unsigned char)
VW::INSTANTIATE (int , unsigned char, unsigned char)
VW::INSTANTIATE (float , unsigned char, float)
VW::INSTANTIATE (float , float , float)
VW::INSTANTIATE (unsigned char)
VW::INSTANTIATE (ImageHSV< double >)
VW::INSTANTIATE (ImageHSV< float >)
VW::INSTANTIATE (ImageHSV< int >)
VW::INSTANTIATE (ImageHSV< unsigned int >)
VW::INSTANTIATE (ImageHSV< unsigned char >)
VW::INSTANTIATE (ImageYUV< double >)
VW::INSTANTIATE (ImageYUV< float >)
VW::INSTANTIATE (ImageYUV< int >)
VW::INSTANTIATE (ImageYUV< unsigned int >)
VW::INSTANTIATE (ImageYUV< unsigned char >)
VW::INSTANTIATE (ImageRGB< double >)
VW::INSTANTIATE (ImageRGB< float >)
VW::INSTANTIATE (ImageRGB< int >)
VW::INSTANTIATE (ImageRGB< unsigned int >)
VW::INSTANTIATE (ImageRGB< unsigned char >)
VW::INSTANTIATE (ImageMono< double >)
VW::INSTANTIATE (ImageMono< float >)
VW::INSTANTIATE (ImageMono< int >)
VW::INSTANTIATE (ImageMono< unsigned int >)
VW::INSTANTIATE (ImageMono< unsigned char >)
VW::INSTANTIATE (ImageRGB< float > , ImageYUV< float >)
VW::INSTANTIATE (ImageMono< float > , ImageYUV< float >)
VW::INSTANTIATE (ImageRGB< unsigned char > , ImageYUV< unsigned char >)
VW::INSTANTIATE (ImageMono< unsigned char > , ImageYUV< unsigned char >)
VW::INSTANTIATE (ImageHSV< float > , ImageRGB< float >)
VW::INSTANTIATE (ImageYUV< float > , ImageRGB< float >)
VW::INSTANTIATE (ImageMono< float > , ImageRGB< float >)
VW::INSTANTIATE (ImageHSV< unsigned char > , ImageRGB< unsigned char >)
VW::INSTANTIATE (ImageYUV< unsigned char > , ImageRGB< unsigned char >)
VW::INSTANTIATE (ImageMono< unsigned char > , ImageRGB< unsigned char >)
VW::INSTANTIATE (ImageYUV< float > , ImageMono< float >)
VW::INSTANTIATE (ImageRGB< float > , ImageMono< float >)
VW::INSTANTIATE (ImageYUV< unsigned char > , ImageMono< unsigned char >)
VW::INSTANTIATE (ImageRGB< unsigned char > , ImageMono< unsigned char >)
VW::INSTANTIATE (ImageYUV< unsigned int > , ImageYUV< unsigned char >)
VW::INSTANTIATE (ImageYUV< unsigned char > , ImageYUV< float >)
VW::INSTANTIATE (ImageMono< unsigned char > , ImageMono< double >)
VW::INSTANTIATE (ImageMono< double > , ImageMono< unsigned char >)
VW::INSTANTIATE (ImageMono< unsigned int > , ImageMono< unsigned char >)
VW::INSTANTIATE (ImageMono< unsigned char > , ImageMono< float >)
VW::INSTANTIATE (ImageYUV< float > , ImageYUV< float >)
VW::INSTANTIATE (ImageYUV< unsigned char > , ImageYUV< unsigned char >)
VW::INSTANTIATE (ImageRGB< float > , ImageRGB< float >)
VW::INSTANTIATE (ImageRGB< unsigned char > , ImageRGB< unsigned char >)
VW::INSTANTIATE (ImageMono< float > , ImageMono< float >)
VW::INSTANTIATE (ImageMono< unsigned char > , ImageMono< unsigned char >)
VW::Point2D VW::Intersect (const VW::Line2D & l1, const VW::Line2D & l2) [inline]
Find the point of intersection of two lines.
References VW::Line2D::GetA(), VW::Line2D::GetB(), and VW::Line2D::GetC().
bool VW::IsADirectory (const std::string & name)
Is this a directory (true) or a file (false).
Referenced by GetFileList().
bool VW::IsFinite (double x) [inline]
Return true if x is neither NaN nor Inf.
bool VW::IsNaN (double x) [inline]
Return true iff x is "Not a Number".
Referenced by VW::Misc::CorrelationScoreAJD(), VW::Misc::CorrelationScoreNMSD(), and VW::ImagePatchYUV::GetZNCC().
bool VW::IsToLeft (const VW::Point2D & point, const VW::LineSeg2D & line) [inline]
Is the point to the left of the line-segment (only meaningful for lines with a sense of direction).
References VW::LineSeg2D::IsToLeft().
bool VW::IsToRight (const VW::Point2D & point, const VW::LineSeg2D & line) [inline]
Is the point to the right of the line-segment (only meaningful for lines with a sense of direction).
References VW::LineSeg2D::IsToRight().
VW::Line2D VW::LineThroughPoints (const VW::Point2D & p1, const VW::Point2D & p2) [inline]
Find the line that passes through two points.
References VW::LineSeg2D::GetLine().
bool VW::LoadSiftFeature (SiftFeature & feature, const char * filename)
References VW::SiftFeature::descriptor, VW::SiftFeature::orientation, VW::SiftFeature::scale, VW::SiftFeature::x, and VW::SiftFeature::y.
VW::Covariance3D VW::MapCovariance (const VNL::MatrixFixed< 3, 3, double > & M, const Covariance3D & C) [inline]
Map the Covariance using another matrix C2 = M*C*M' Cost is 75 flops.
References c.
VW::Covariance2D VW::MapCovariance (const VNL::MatrixFixed< 2, 2, double > & M, const Covariance2D & C) [inline]
Map the Covariance using another matrix C2 = M*C*M' Cost is 21 flops.
References c.
Referenced by TransferPoint().
template<class FeatureType > void VW::MatchesToPointLists (const std::vector< FeatureType > & old_features, const std::vector< FeatureType > & new_features, const std::vector< VW::MatchData > & matches, std::vector< VW::Point2D > & old_points, std::vector< VW::Point2D > & new_points, std::vector< double > & scores) [inline]
A utility function to make lists of matched point2d's from lists of features and correspondence data, including a list of the scores (priors).
References VW::MatchData::GetNewIndex(), VW::MatchData::GetOldIndex(), VW::MatchData::GetScore(), and m.
template<class FeatureType > void VW::MatchesToPointLists (const std::vector< FeatureType > & old_features, const std::vector< FeatureType > & new_features, const std::vector< VW::MatchData > & matches, std::vector< VW::Point2D > & old_points, std::vector< VW::Point2D > & new_points) [inline]
A utility function to make lists of matched point2d's from lists of features and correspondence data.
References VW::MatchData::GetNewIndex(), VW::MatchData::GetOldIndex(), and m.
double VW::Norm (const LineSeg3D & ls)
References VW::LineSeg3D::_ep, VW::LineSeg3D::_sp, VW::Point3D::_x, VW::Point3D::_y, VW::Point3D::_z, and std::sqrt().
double VW::Norm2 (const LineSeg3D & ls)
References VW::LineSeg3D::_ep, VW::LineSeg3D::_sp, VW::Point3D::_x, VW::Point3D::_y, and VW::Point3D::_z.
template void VW::NormaliseIntensity (VW::ImageYUV< unsigned char > & , double)
template void VW::NormaliseIntensity (VW::ImageMono< unsigned char > & , double)
template<class Type > void VW::NormaliseIntensity (VW::ImageYUV< Type > & image, double desired_stddev) [inline]
template<class Type > void VW::NormaliseIntensity (VW::ImageMono< Type > & image, double desired_stddev) [inline]
void VW::NormaliseLine (VW::Line2D & line, VW::Covariance3D & line_covariance)
Normalise the line and its covariance so that distances can be measured using the dot product.
Normalise the line so that distances are correct
References std::sqrt().
Referenced by TransferPoint().
VNL::MatrixFixed< 3, 3, double > VW::operator* (const Covariance3D & C, const VNL::MatrixFixed< 3, 3, double > & M) [inline]
Post-multiply by an arbitrary quare matrix Cost is 45 flops.
VNL::MatrixFixed< 3, 3, double > VW::operator* (const VNL::MatrixFixed< 3, 3, double > & M, const Covariance3D & C) [inline]
Pre-multiply by an arbitrary quare matrix Cost is 45 flops.
VNL::MatrixFixed< 2, 2, double > VW::operator* (const Covariance2D & C, const VNL::MatrixFixed< 2, 2, double > & M) [inline]
Post-multiply by an arbitrary quare matrix Cost is 12 flops.
VNL::MatrixFixed< 2, 2, double > VW::operator* (const VNL::MatrixFixed< 2, 2, double > & M, const Covariance2D & C) [inline]
Pre-multiply by an arbitrary quare matrix Cost is 12 flops.
template<class Type > VW::PixelYUV<float> VW::operator* (const float a, const VW::PixelYUV< Type > & p) [inline]
References VW::PixelYUV< Type >::u, VW::PixelYUV< Type >::v, and VW::PixelYUV< Type >::y.
template<class Type > VW::PixelYUV<float> VW::operator* (const VW::PixelYUV< Type > & p, const float a) [inline]
References VW::PixelYUV< Type >::u, VW::PixelYUV< Type >::v, and VW::PixelYUV< Type >::y.
template<class Type > VW::PixelYUV<double> VW::operator* (const double a, const VW::PixelYUV< Type > & p) [inline]
References VW::PixelYUV< Type >::u, VW::PixelYUV< Type >::v, and VW::PixelYUV< Type >::y.
template<class Type > VW::PixelYUV<double> VW::operator* (const VW::PixelYUV< Type > & p, const double a) [inline]
References VW::PixelYUV< Type >::u, VW::PixelYUV< Type >::v, and VW::PixelYUV< Type >::y.
template<class Type > VW::PixelRGB<float> VW::operator* (const float a, const VW::PixelRGB< Type > & p) [inline]
References VW::PixelRGB< Type >::alpha, VW::PixelRGB< Type >::b, VW::PixelRGB< Type >::g, and VW::PixelRGB< Type >::r.
template<class Type > VW::PixelRGB<float> VW::operator* (const VW::PixelRGB< Type > & p, const float a) [inline]
References VW::PixelRGB< Type >::alpha, VW::PixelRGB< Type >::b, VW::PixelRGB< Type >::g, and VW::PixelRGB< Type >::r.
template<class Type > VW::PixelRGB<double> VW::operator* (const double a, const VW::PixelRGB< Type > & p) [inline]
References VW::PixelRGB< Type >::alpha, VW::PixelRGB< Type >::b, VW::PixelRGB< Type >::g, and VW::PixelRGB< Type >::r.
template<class Type > VW::PixelRGB<double> VW::operator* (const VW::PixelRGB< Type > & p, const double a) [inline]
References VW::PixelRGB< Type >::alpha, VW::PixelRGB< Type >::b, VW::PixelRGB< Type >::g, and VW::PixelRGB< Type >::r.
template<class Type > VW::PixelMono<float> VW::operator* (const float a, const VW::PixelMono< Type > & p) [inline]
References VW::PixelMono< Type >::y.
template<class Type > VW::PixelMono<float> VW::operator* (const VW::PixelMono< Type > & p, const float a) [inline]
References VW::PixelMono< Type >::y.
template<class Type > VW::PixelMono<double> VW::operator* (const double a, const VW::PixelMono< Type > & p) [inline]
References VW::PixelMono< Type >::y.
template<class Type > VW::PixelMono<double> VW::operator* (const VW::PixelMono< Type > & p, const double a) [inline]
References VW::PixelMono< Type >::y.
Point3D VW::operator* (const VNL::MatrixFixed< 3, 3, double > & M, const Point3D & p1)
References VW::Point3D::_x, VW::Point3D::_y, and VW::Point3D::_z.
Point3D VW::operator* (const double a, const Point3D & p1)
References VW::Point3D::_x, VW::Point3D::_y, and VW::Point3D::_z.
Point3D VW::operator* (const Point3D & p1, const double a)
References VW::Point3D::_x, VW::Point3D::_y, and VW::Point3D::_z.
double VW::operator* (const Point3D & p1, const Point3D & p2)
References VW::Point3D::_x, VW::Point3D::_y, and VW::Point3D::_z.
Point2D VW::operator* (const double a, const Point2D & p1)
References VW::Point2D::_x, and VW::Point2D::_y.
Point2D VW::operator* (const Point2D & p1, const double a)
References VW::Point2D::_x, and VW::Point2D::_y.
double VW::operator* (const Point2D & p1, const Point2D & p2)
References VW::Point2D::_x, and VW::Point2D::_y.
double VW::operator* (const LineSeg3D & ls1, const LineSeg3D & ls2)
References VW::LineSeg3D::_ep, VW::LineSeg3D::_sp, VW::Point3D::GetX(), VW::Point3D::GetY(), and VW::Point3D::GetZ().
template<class Type > VW::PixelYUV<Type> VW::operator+ (const VW::PixelYUV< Type > & p1, const VW::PixelYUV< Type > & p2) [inline]
template<class Type > VW::PixelRGB<Type> VW::operator+ (const VW::PixelRGB< Type > & p1, const VW::PixelRGB< Type > & p2) [inline]
References VW::PixelRGB< Type >::alpha, VW::PixelRGB< Type >::b, VW::PixelRGB< Type >::g, and VW::PixelRGB< Type >::r.
template<class Type > VW::PixelMono<Type> VW::operator+ (const VW::PixelMono< Type > & p1, const VW::PixelMono< Type > & p2) [inline]
Point3D VW::operator+ (const Point3D & p1, const Point3D & p2)
References VW::Point3D::_x, VW::Point3D::_y, and VW::Point3D::_z.
Point2D VW::operator+ (const Point2D & p1, const Point2D & p2)
References VW::Point2D::_x, and VW::Point2D::_y.
VW::LineSeg3D VW::operator+ (const VW::LineSeg3D & line, const VW::Point3D & point) [inline]
template<class Type > VW::PixelYUV<Type> VW::operator- (const VW::PixelYUV< Type > & p1, const VW::PixelYUV< Type > & p2) [inline]
template<class Type > VW::PixelRGB<Type> VW::operator- (const VW::PixelRGB< Type > & p1, const VW::PixelRGB< Type > & p2) [inline]
References VW::PixelRGB< Type >::alpha, VW::PixelRGB< Type >::b, VW::PixelRGB< Type >::g, and VW::PixelRGB< Type >::r.
template<class Type > VW::PixelMono<Type> VW::operator- (const VW::PixelMono< Type > & p1, const VW::PixelMono< Type > & p2) [inline]
Point3D VW::operator- (const Point3D & p)
References VW::Point3D::_x, VW::Point3D::_y, and VW::Point3D::_z.
Point3D VW::operator- (const Point3D & p1, const Point3D & p2)
References VW::Point3D::_x, VW::Point3D::_y, and VW::Point3D::_z.
Point2D VW::operator- (const Point2D & p1, const Point2D & p2)
References VW::Point2D::_x, and VW::Point2D::_y.
Point2D VW::operator- (const Point2D & p)
References VW::Point2D::_x, and VW::Point2D::_y.
VW::LineSeg3D VW::operator- (const VW::LineSeg3D & line, const VW::Point3D & point) [inline]
Point3D VW::operator/ (const Point3D & p1, const double a)
References VW::Point3D::_x, VW::Point3D::_y, and VW::Point3D::_z.
Point2D VW::operator/ (const Point2D & p1, const double a)
References VW::Point2D::_x, and VW::Point2D::_y.
std::ostream & VW::operator<< (std::ostream & s, const AWFMaterial & m)
References VW::AWFMaterial::_alpha, VW::AWFMaterial::_got_ka, VW::AWFMaterial::_got_kd, VW::AWFMaterial::_got_ke, VW::AWFMaterial::_got_ks, VW::AWFMaterial::_has_texture, VW::AWFMaterial::_illum, VW::AWFMaterial::_Ka, VW::AWFMaterial::_Kd, VW::AWFMaterial::_Ke, VW::AWFMaterial::_Ks, VW::AWFMaterial::_my_name, VW::AWFMaterial::_shininess, VW::AWFMaterial::_texturename, and StripPath().
std::ostream & VW::operator<< (std::ostream & s, const AWFFace & f)
References VW::AWFFace::_nindex, VW::AWFFace::_tindex, VW::AWFFace::_type, VW::AWFFace::_vindex, VertexOnly, WithNormal, WithTexture, and WithTextureAndNormal.
std::ostream & VW::operator<< (std::ostream & stream, const Timer & timer)
References VW::Timer::GetAsSeconds().
std::ostream & VW::operator<< (std::ostream & stream, const Histogram2D & H)
References VW::Histogram2D::SizeX(), VW::Histogram2D::SizeY(), VW::Histogram2D::XTick(), and VW::Histogram2D::YTick().
std::ostream & VW::operator<< (std::ostream & stream, const VW::Histogram & H)
References VW::Histogram::Size(), and VW::Histogram::Tick().
std::ostream& VW::operator<< (std::ostream & s, const SIFTFeature & f) [inline]
References VW::SIFTFeature::WriteASCII().
std::ostream& VW::operator<< (std::ostream & os, const SiftParameters & p)
std::ostream& VW::operator<< (std::ostream & s, const PatchFeature & f) [inline]
References VW::PatchFeature::WriteASCII().
std::ostream & VW::operator<< (std::ostream & s, const ZNPatch & p)
References VW::ZNPatch::WriteASCII().
std::ostream& VW::operator<< (std::ostream & s, const VW::MatchData & m) [inline]
References VW::MatchData::new_index, and VW::MatchData::old_index.
std::ostream& VW::operator<< (std::ostream & os, const DOGDetectorParams & p)
ostream& VW::operator<< (ostream & s, const LineSeg3D & ls)
References VW::LineSeg3D::_ep, and VW::LineSeg3D::_sp.
ostream& VW::operator<< (ostream & s, const LineSeg2D & ls)
References VW::LineSeg2D::WriteASCII().
std::istream& VW::operator>> (std::istream & s, VW::MatchData & m) [inline]
References VW::MatchData::new_index, and VW::MatchData::old_index.
istream& VW::operator>> (istream & s, LineSeg3D & ls)
References VW::LineSeg3D::_ep, and VW::LineSeg3D::_sp.
istream& VW::operator>> (istream & s, LineSeg2D & ls)
References VW::LineSeg2D::ReadASCII().
double VW::PadeExp11 (const double x) [inline]
An approximation to exp using the 1,1 Pade approximation, valid to within 10% up to x=1.0 (3 flops).
double VW::PadeExp22 (const double x) [inline]
An approximation to exp using the 1,1 Pade approximation, valid to within 10% up to x=2.3 (7 flops).
double VW::PadeExp33 (const double x) [inline]
An approximation to exp using the 3,3 Pade approximation, valid to within 10% up to x=3.45 (11 flops).
double VW::PadeExp44 (const double x) [inline]
An approximation to exp using the 4,4 Pade approximation, valid to within 10% up to x=4.85 (15 flops).
Referenced by VW::PDF::Gaussian2DIso::ApproxDensityForError2(), and VW::PDF::Gaussian1D::ApproxDensityForError2().
void VW::PixelList2ClassifierUVMatrix (const std::string & pixellist_filename, const std::string & matrix_filename, unsigned int binsize = 2)
A function to load a list of pixel data and output a classification matrix.
References c, FindXMLBlock(), GetXMLBlock(), m, prob(), v, and VERBOSE.
VW::LineSeg2D VW::Project (const VW::LineSeg3D & worldline, const VNL::MatrixFixed< 3, 4, double > projectionmatrix) [inline]
Project a 3D line-segment onto a 2D line-segment.
References VW::LineSeg3D::GetEndPoint(), VW::LineSeg3D::GetStartPoint(), and Project().
VW::Point2D VW::Project (const VW::Point3D & worldpoint, const VNL::MatrixFixed< 3, 4, double > projectionmatrix) [inline]
Project a 3D point onto a 2D point.
References VW::Point3D::GetX(), VW::Point3D::GetY(), and VW::Point3D::GetZ().
Referenced by Project().
double VW::Rand (double upper) [inline]
Get a random number in the range 0 <= x < upper.
Referenced by GeneratePointsInCuboid(), GeneratePointsInShell(), GeneratePointsInShellPatch(), GeneratePointsInSphere(), GeneratePointsOnSphereSurface(), RandInt(), VW::PDF::Uniform1D::Sample(), VW::PDF::Rayleigh::Sample(), VW::PDF::Gaussian2DIso::Sample(), VW::PDF::Gaussian1D::Sample(), and VW::PDF::Exponential::Sample().
int VW::RandInt (int upper) [inline]
Get a random integer number in the range 0 <= x < upper.
References Rand().
void VW::RandomSample (unsigned int number_to_pick, unsigned int total_num_features, std::vector< unsigned int > & sample_indices) [inline]
Select 'number_to_pick' samples from a list using even random samples.
The list is assumed to be 'total_num_features' long, and the resulting indices are placed in 'sample_indices'.
References VERBOSE.
Referenced by VW::FMatrixAffineComputePreemptive::Compute(), VW::EssentialMatrixComputePreemptive::Compute(), VW::Homography2DCompute::MLESACCore(), VW::FMatrixCompute::MLESACCore(), VW::FMatrixAffineCompute::MLESACCore(), and VW::Line2DCompute::MLESACFromPoints().
void VW::ReadAWFMaterialsFile (const std::string & filename, std::vector< AWFMaterial > & materials)
Read a materials (.mtl) file and add the materials contained to the result vector.
Referenced by VW::AWFObject::LoadFile().
std::istream& VW::ReadBinary (std::istream & stream, float * values, unsigned int n)
std::istream& VW::ReadBinary (std::istream & stream, double * values, unsigned int n)
std::istream& VW::ReadBinary (std::istream & stream, double & value)
std::istream& VW::ReadBinary (std::istream & stream, float & value)
std::istream& VW::ReadBinary (std::istream & stream, unsigned int & value)
std::istream& VW::ReadBinary (std::istream & stream, int & value)
std::istream& VW::ReadBinary (std::istream & stream, unsigned char & value)
std::istream& VW::ReadBinary (std::istream & stream, char & value)
Read a binary string and convert to a standard type.
Referenced by VW::ImagePatch::ReadBinary().
template<class valType > bool VW::ReadGDIImage (const std::string & filename, VW::ImageRGBPlanes< valType > & image) [inline]
template<class valType > bool VW::ReadGDIImage (const std::string & filename, VW::ImageRGB< valType > & image) [inline]
References ImageCopy(), and ReadGDIImage().
template<class valType > bool VW::ReadGDIImage (const std::string & filename, VW::ImageHSV< valType > & image) [inline]
References ImageCopy(), and ReadGDIImage().
template<class valType > bool VW::ReadGDIImage (const std::string & filename, VW::ImageYUV< valType > & image) [inline]
References ImageCopy(), and ReadGDIImage().
template<class valType > bool VW::ReadGDIImage (const std::string & filename, VW::ImageMono< valType > & image) [inline]
References ImageCopy().
Referenced by ReadGDIImage().
template<> bool VW::ReadGDIImage< unsigned char > (const std::string & filename, VW::ImageRGBPlanes< unsigned char > & image) [inline]
template<> bool VW::ReadGDIImage< unsigned char > (const std::string & filename, VW::ImageRGB< unsigned char > & image) [inline]
template<> bool VW::ReadGDIImage< unsigned char > (const std::string & filename, VW::ImageHSV< unsigned char > & image) [inline]
template<> bool VW::ReadGDIImage< unsigned char > (const std::string & filename, VW::ImageYUV< unsigned char > & image) [inline]
template<> bool VW::ReadGDIImage< unsigned char > (const std::string & filename, VW::ImageMono< unsigned char > & image) [inline]
template<class ImType > bool VW::ReadImage (const std::string & filename, ImType & image) [inline]
References _FindSuffix().
template<class ImType > bool VW::ReadImage (FILE * file, ImType & image) [inline]
References ReadPPMImage().
Referenced by VW::SequencerMovie::_Step(), and VW::SequencerFile::_Step().
bool VW::ReadJPEGImage (FILE * filepointer, VW::ImageRGB< unsigned char > & image)
References VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::AllocImageData(), VW::PixelRGB< Type >::alpha, VW::PixelRGB< Type >::b, beginJpegInput(), c, VW::PixelRGB< Type >::g, VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetHeight(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetRowStart(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetWidth(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::IsAlloced(), m, VW::PixelRGB< Type >::r, v, VERBOSE, and VW::ImageConversions::YUV2RGB().
bool VW::ReadJPEGImage (FILE * filepointer, VW::ImageYUV< unsigned char > & image)
References VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::AllocImageData(), VW::PixelYUV< Type >::alpha, beginJpegInput(), c, VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetRowStart(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::IsAlloced(), m, VW::ImageConversions::RGB2YUV(), VW::PixelYUV< Type >::u, VW::PixelYUV< Type >::v, VERBOSE, and VW::PixelYUV< Type >::y.
bool VW::ReadJPEGImage (FILE * filepointer, VW::ImageMono< float > & image)
References VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::AllocImageData(), beginJpegInput(), c, VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetRowStart(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::IsAlloced(), m, VW::ImageConversions::RGB2Y(), VERBOSE, and VW::PixelMono< Type >::y.
bool VW::ReadJPEGImage (FILE * filepointer, VW::ImageMono< unsigned char > & image)
References VW::ImageBase< PixelType, PixelPtr >::AllocImageData(), beginJpegInput(), c, VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetRowStart(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), VW::ImageBase< PixelType, PixelPtr >::IsAlloced(), m, VW::ImageConversions::RGB2Y(), VERBOSE, and VW::PixelMono< Type >::y.
template<class valType > bool VW::ReadPPMImage (FILE * filepointer, VW::ImageRGBPlanes< valType > & image) [inline]
template<class valType > bool VW::ReadPPMImage (FILE * filepointer, VW::ImageRGB< valType > & image) [inline]
References ImageCopy(), and ReadPPMImage().
template<class valType > bool VW::ReadPPMImage (FILE * filepointer, VW::ImageHSV< valType > & image) [inline]
References ImageCopy(), and ReadPPMImage().
template<class valType > bool VW::ReadPPMImage (FILE * filepointer, VW::ImageYUV< valType > & image) [inline]
References ImageCopy(), and ReadPPMImage().
template<class valType > bool VW::ReadPPMImage (FILE * filepointer, VW::ImageMono< valType > & image) [inline]
References ImageCopy(), and ReadPPMImage().
template<class valType > bool VW::ReadPPMImage (const std::string & filename, VW::ImageRGBPlanes< valType > & image) [inline]
References ReadPPMImage().
template<class valType > bool VW::ReadPPMImage (const std::string & filename, VW::ImageRGB< valType > & image) [inline]
References ReadPPMImage().
template<class valType > bool VW::ReadPPMImage (const std::string & filename, VW::ImageHSV< valType > & image) [inline]
References ReadPPMImage().
template<class valType > bool VW::ReadPPMImage (const std::string & filename, VW::ImageYUV< valType > & image) [inline]
References ReadPPMImage().
template<class valType > bool VW::ReadPPMImage (const std::string & filename, VW::ImageMono< valType > & image) [inline]
Referenced by ReadImage(), and ReadPPMImage().
template<> bool VW::ReadPPMImage< unsigned char > (FILE * filepointer, VW::ImageRGBPlanes< unsigned char > & image) [inline]
template<> bool VW::ReadPPMImage< unsigned char > (FILE * filepointer, VW::ImageRGB< unsigned char > & image) [inline]
template<> bool VW::ReadPPMImage< unsigned char > (FILE * filepointer, VW::ImageHSV< unsigned char > & image) [inline]
template<> bool VW::ReadPPMImage< unsigned char > (FILE * filepointer, VW::ImageYUV< unsigned char > & image) [inline]
template<> bool VW::ReadPPMImage< unsigned char > (FILE * filepointer, VW::ImageMono< unsigned char > & image) [inline]
template<class T > bool VW::ReadXMLString (const std::string & str, T & data) [inline]
Read a string into a value.
For simple values this is just a << operation, but can be overloaded for complex data-types to include parsing of XML marked members.
std::string VW::ReformFilename (const std::string & path, const std::string & base, const std::string & extension)
Refrom a filename from its path, base and extension.
Referenced by VW::AWFObject::SaveAll(), and VW::AWFObject::SaveAsVRML().
VW::Point3D VW::Round (const VW::Point3D & p) [inline]
Round coordinates to integer values.
References VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), and ROUND.
VW::Point2D VW::Round (const VW::Point2D & p) [inline]
Round coordinates to integer values.
References VW::Point2D::GetX(), VW::Point2D::GetY(), and ROUND.
bool VW::SaveSiftFeature (const SiftFeature & feature, const char * filename)
References VW::SiftFeature::descriptor, VW::SiftFeature::orientation, VW::SiftFeature::scale, VW::SiftFeature::x, and VW::SiftFeature::y.
double VW::ScalarProduct (const VW::Point3D & p1, const VW::Point3D & p2) [inline]
References VW::Point3D::_x, VW::Point3D::_y, and VW::Point3D::_z.
double VW::ScalarProduct (const VW::Point2D & p1, const VW::Point2D & p2) [inline]
References VW::Point2D::_x, and VW::Point2D::_y.
Referenced by VW::LineSeg2D::GetCosAngle().
double VW::ScalarTripleProduct (const VW::Point3D & p1, const VW::Point3D & p2, const VW::Point3D & p3) [inline]
References VW::Point3D::_x, VW::Point3D::_y, and VW::Point3D::_z.
void VW::SeedRand () [inline]
Seed the random number generator with a time-dependent seed (comes from clock).
Referenced by VW::Homography2DCompute::GUISACCore(), VW::FMatrixAffineCompute::GUISACCore(), VW::Line2DCompute::GUISACFromPoints(), VW::Homography2DCompute::GUNSACCore(), VW::Homography2DCompute::MLESACCore(), VW::FMatrixCompute::MLESACCore(), VW::FMatrixAffineCompute::MLESACCore(), and VW::Line2DCompute::MLESACFromPoints().
int VW::SiftMatchNN (const SiftFeature & key, const std::vector< SiftFeature > & database, double distance_ratio_max = 0.8, double min_strength = 1.0)
References VW::SiftFeature::descriptor, std::sqrt(), and v.
void VW::SortAscending (std::vector< MatchData > & list)
Sort into order of increasing match score.
void VW::SortByStrength (std::vector< PlesseyCornerYUV > & list, bool strongest_first = true)
Sort into order of in/decreasing strength.
void VW::SortByStrength (std::vector< PlesseyCorner > & list)
Sort into order of increasing strength.
void VW::SortByStrength (std::vector< CornerFeature > & list)
Sort into order of increasing strength.
void VW::SortByXValue (std::vector< PlesseyCornerYUV > & list)
Sort into order of increasing X-value.
void VW::SortByXValue (std::vector< PlesseyCorner > & list)
Sort into order of increasing X-value.
void VW::SortByXValue (std::vector< CornerFeature > & list)
Sort into order of increasing X-value.
void VW::SortByYValue (std::vector< PlesseyCornerYUV > & list)
Sort into order of increasing Y-value.
void VW::SortByYValue (std::vector< PlesseyCorner > & list)
Sort into order of increasing Y-value.
void VW::SortByYValue (std::vector< CornerFeature > & list)
Sort into order of increasing Y-value.
void VW::SortDescending (std::vector< MatchData > & list)
Sort into order of decreasing match score.
void VW::SortStrongestFirst (std::vector< CornerFeature > & list)
Sort into order of decreasing strength.
void VW::SplitFilename (const std::string & filename, std::string & path, std::string & base, std::string & extension)
Split a filename into path+'/'+base+'.
'+extension.
Referenced by VW::AWFObject::SaveAll(), VW::AWFObject::SaveAsVRML(), and VW::AWFObject::SaveObject().
std::string VW::StripPath (const std::string & filename)
Remove the path component of the filename.
Referenced by VW::AWFMaterial::GetVRMLString(), and operator<<().
void VW::TransferPoint (const VW::Point2D & source_point, const VW::Homography2D & H, const VW::Homography2DCovariance & HCovar, const float image_noise_variance, VW::Point2D & dest_point, VW::Covariance2D & dest_covar)
Transfer a point and both its uncertainty and that of the tranform (note that the total uncertainty requires you to add any noise in image 2).
References VW::Point2D::GetX(), VW::Point2D::GetY(), MapCovariance(), VW::Point2D::Set(), and VW::Homography2DCovariance::TransferUncertainty().
void VW::TransferPoint (const VW::Point2D & source_point, const VW::FMatrixAffine & F, const VW::FMatrixAffineCovariance & FCovar, const float image_noise_variance, VW::Line2D & dest_line, VW::Covariance3D & dest_line_covar)
Transfer a point and its covariance using an uncertain estimate of an FMatrix.
The result is a (normalised) line and its covariance.
void VW::TransferPoint (const VW::Point2D & source_point, const VW::FMatrix & F, const VW::FMatrixCovariance & FCovar, const float image_noise_variance, VW::Line2D & dest_line, VW::Covariance3D & dest_line_covar)
Transfer a point and its covariance using an uncertain estimate of an FMatrix.
The result is a (normalised) line and its covariance.
Normalise the line so that distances are correct
References VW::Point2D::GetX(), VW::Point2D::GetY(), MapCovariance(), NormaliseLine(), and VW::FMatrixCovariance::TransferUncertainty().
VW::Point3D VW::VectorProduct (const VW::Point3D & p1, const VW::Point3D & p2) [inline]
References VW::Point3D::_x, VW::Point3D::_y, and VW::Point3D::_z.
Referenced by VW::ThreeDToolGLCommon::LookAt(), VW::Quaternion::operator*(), VW::Quaternion::Rotate(), VW::AngleAxis::Rotate(), and VW::ThreeDToolGLCommon::TrackBall().
void VW::WeightedSample (unsigned int number_to_pick, const std::vector< double > & cumulative_weights, std::vector< unsigned int > & sample_indices) [inline]
Select 'number_to_pick' samples from a list using weighted samples.
The resulting indices are placed in 'sample_indices'.
Referenced by VW::FMatrixAffineComputePreemptive::Compute(), VW::EssentialMatrixComputePreemptive::Compute(), VW::Homography2DCompute::GUISACCore(), VW::FMatrixAffineCompute::GUISACCore(), VW::Line2DCompute::GUISACFromPoints(), VW::Homography2DCompute::GUNSACCore(), and VW::FMatrixCompute::GUNSACCore().
std::ostream& VW::WriteBinary (std::ostream & stream, const float * values, unsigned int n)
std::ostream& VW::WriteBinary (std::ostream & stream, const double * values, unsigned int n)
Write an array of n entries.
std::ostream& VW::WriteBinary (std::ostream & stream, const double & value)
std::ostream& VW::WriteBinary (std::ostream & stream, const float & value)
std::ostream& VW::WriteBinary (std::ostream & stream, const unsigned int & value)
std::ostream& VW::WriteBinary (std::ostream & stream, const int & value)
std::ostream& VW::WriteBinary (std::ostream & stream, const unsigned char & value)
std::ostream& VW::WriteBinary (std::ostream & stream, const char & value)
Convert a standard type to a binary string.
Referenced by VW::ImagePatch::WriteBinary().
template<class valType > bool VW::WriteGDIImage (const std::string & filename, const VW::ImageRGBPlanes< valType > & image) [inline]
template<class valType > bool VW::WriteGDIImage (const std::string & filename, const VW::ImageRGB< valType > & image) [inline]
References ImageCopy(), and WriteGDIImage().
template<class valType > bool VW::WriteGDIImage (const std::string & filename, const VW::ImageHSV< valType > & image) [inline]
References ImageCopy(), and WriteGDIImage().
template<class valType > bool VW::WriteGDIImage (const std::string & filename, const VW::ImageYUV< valType > & image) [inline]
References ImageCopy(), and WriteGDIImage().
template<class valType > bool VW::WriteGDIImage (const std::string & filename, const VW::ImageMono< valType > & image) [inline]
References ImageCopy().
Referenced by WriteGDIImage().
template<> bool VW::WriteGDIImage< unsigned char > (const std::string & filename, const VW::ImageRGBPlanes< unsigned char > & image) [inline]
template<> bool VW::WriteGDIImage< unsigned char > (const std::string & filename, const VW::ImageRGB< unsigned char > & image) [inline]
template<> bool VW::WriteGDIImage< unsigned char > (const std::string & filename, const VW::ImageHSV< unsigned char > & image) [inline]
template<> bool VW::WriteGDIImage< unsigned char > (const std::string & filename, const VW::ImageYUV< unsigned char > & image) [inline]
template<> bool VW::WriteGDIImage< unsigned char > (const std::string & filename, const VW::ImageMono< unsigned char > & image) [inline]
template<class ImType > bool VW::WriteImage (const std::string & filename, const ImType & image) [inline]
References _FindSuffix().
template<class ImType > bool VW::WriteImage (FILE * file, const ImType & image) [inline]
References WritePPMImage().
bool VW::WriteJPEGImage (FILE * filepointer, const VW::ImageRGB< unsigned char > & image)
References VW::PixelRGB< Type >::b, VW::PixelRGB< Type >::g, VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetHeight(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetRowStart(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetWidth(), VW::PixelRGB< Type >::r, and VERBOSE.
bool VW::WriteJPEGImage (FILE * filepointer, const VW::ImageYUV< unsigned char > & image)
References VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetRowStart(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), VW::PixelYUV< Type >::u, VW::PixelYUV< Type >::v, VERBOSE, and VW::PixelYUV< Type >::y.
bool VW::WriteJPEGImage (FILE * filepointer, const VW::ImageMono< float > & image)
References VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetRowStart(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), and VERBOSE.
bool VW::WriteJPEGImage (FILE * filepointer, const VW::ImageMono< unsigned char > & image)
References VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetRowStart(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), and VERBOSE.
template<class valType > bool VW::WritePPMImage (FILE * filepointer, const VW::ImageRGBPlanes< valType > & image) [inline]
template<class valType > bool VW::WritePPMImage (FILE * filepointer, const VW::ImageRGB< valType > & image) [inline]
References ImageCopy(), and WritePPMImage().
template<class valType > bool VW::WritePPMImage (FILE * filepointer, const VW::ImageHSV< valType > & image) [inline]
References ImageCopy(), and WritePPMImage().
template<class valType > bool VW::WritePPMImage (FILE * filepointer, const VW::ImageYUV< valType > & image) [inline]
References ImageCopy(), and WritePPMImage().
template<class valType > bool VW::WritePPMImage (FILE * filepointer, const VW::ImageMono< valType > & image) [inline]
References ImageCopy(), and WritePPMImage().
template<class valType > bool VW::WritePPMImage (const std::string & filename, const VW::ImageRGBPlanes< valType > & image) [inline]
References WritePPMImage().
template<class valType > bool VW::WritePPMImage (const std::string & filename, const VW::ImageRGB< valType > & image) [inline]
References WritePPMImage().
template<class valType > bool VW::WritePPMImage (const std::string & filename, const VW::ImageHSV< valType > & image) [inline]
References WritePPMImage().
template<class valType > bool VW::WritePPMImage (const std::string & filename, const VW::ImageYUV< valType > & image) [inline]
References WritePPMImage().
template<class valType > bool VW::WritePPMImage (const std::string & filename, const VW::ImageMono< valType > & image) [inline]
Referenced by WriteImage(), and WritePPMImage().
template<> bool VW::WritePPMImage< unsigned char > (FILE * filepointer, const VW::ImageRGBPlanes< unsigned char > & image) [inline]
template<> bool VW::WritePPMImage< unsigned char > (FILE * filepointer, const VW::ImageRGB< unsigned char > & image) [inline]
template<> bool VW::WritePPMImage< unsigned char > (FILE * filepointer, const VW::ImageHSV< unsigned char > & image) [inline]
template<> bool VW::WritePPMImage< unsigned char > (FILE * filepointer, const VW::ImageYUV< unsigned char > & image) [inline]
template<> bool VW::WritePPMImage< unsigned char > (FILE * filepointer, const VW::ImageMono< unsigned char > & image) [inline]
void VW::XInit (int argc, char ** argv)
References globalXdisplay.
void VW::XLoop ()
References GetAndDispatchXEvent(), and VERBOSE.
Variable Documentation
const double VW::NaN = 0.0/0.0