VW: VNL Namespace Reference
VNL Namespace Reference
call this to initialize the format stack.
Classes
struct AmoebaFit
class AmoebaLSCF
class Amoeba
Nelder-Meade downhill simplex.
struct AmoebaSimplexCorner
struct BrentData
class Brent
Brent 1D minimizer.
class Cholesky
Decomposition of symmetric matrix.
class ComplexEigensystem
Calculates eigenvalues and eigenvectors of a square complex matrix.
class ConjugateGradientActivate
class ConjugateGradient
real function minimization.
class CPolyRoots
Find all the roots of a univariate polynomial with complex coefficients.
struct FFT1D
In-place 1D fast fourier transform.
struct FFT2D
In-place 2D fast fourier transform.
struct FFTBase
Base class for in-place ND fast fourier transform.
struct FFTPrimeFactors
Holds prime factor information.
class GeneralizedEigensystem
Solves the generalized eigenproblem Ax=Bx.
class LBFGS
Limited memory Broyden Fletcher Goldfarb Shannon minimization.
class LevenbergMarquardtActivate
class LevenbergMarquardt
Levenberg Marquardt nonlinear least squares.
class LSqrActivate
class LSqr
Linear least squares.
struct MatrixInverse
Calculates inverse of a matrix (wrapper around vnl_svd<double>).
class Powell1DFun
class Powell
The ever-popular Powell minimizer.
class QR
Extract the Q*R decomposition of matrix M.
class RealEigensystem
Extract eigensystem of unsymmetric matrix M, using the EISPACK routine.
class RNPolySolveCmplx
This is a local implementation of a "complex number" class, for internal use only.
class RNPolySolve
Solves for roots of system of real polynomials.
class RPolyRoots
Find the roots of a real polynomial.
class Scatter3x3
class SparseSymmetricEigensystem
Find the eigenvalues of a sparse symmetric matrix.
class SVD
Holds the singular value decomposition of a VNL::Matrix.
class SymmetricEigensystem
Computes and stores the eigensystem decomposition of a symmetric matrix.
class BigNum
Infinite precision integers.
class NumericTraits< BigNum >
struct ComplexTraits< BigNum >
struct ComplexTraits< std::complex< BigNum > >
class NumericTraits< std::complex< BigNum > >
struct ComplexTraits< float >
struct ComplexTraits< double >
struct ComplexTraits< long double >
struct ComplexTraits< ::std::complex< float > >
struct ComplexTraits< ::std::complex< double > >
struct ComplexTraits< ::std::complex< long double > >
class CostFunction
An object that represents a function from R^n -> R.
class CrossProductMatrix
3x3 cross-product matrix of vector
class CVector
vnl_c_vector interfaces to lowlevel memory-block operations.
class DiagMatrix
stores a diagonal matrix as a single vector.
class FileMatrix
Class to load a matrix from a file.
class FileVector
Templated class to load a vector from a file.
class Identity
class LeastSquaresCostFunction
An adaptor that converts a vnl_least_squares_function to a vnl_cost_function.
class LeastSquaresFunction
Abstract base for minimising functions.
class LinearSystem
Abstraction for a linear system of equations.
class MatlabFilewrite
Code to perform MATLAB binary file operations.
struct MatlabHeader
struct MatlabPrintProxy
class MatlabReadHdr
class Matrix
An ordinary mathematical matrix.
class MatrixFixed
Fixed size matrix.
class MatrixFixedRef
Fixed size stack-stored vnl_matrix.
class MatrixRef
vnl_matrix reference to user-supplied storage.
class NonlinearMinimizer
vnl_nonlinear_minimizer is a base class for nonlinear optimization.
class NumericLimits
Standard limits for numeric datatypes.
class NumericLimits< vnl_tmp_signed32 >
class NumericLimits< long >
class NumericLimits< unsigned long >
class NumericLimits< unsigned short >
class NumericLimits< short >
class NumericLimits< float >
class NumericLimits< double >
class NumericTraits< bool >
class NumericTraits< char >
class NumericTraits< char const >
class NumericTraits< unsigned char >
class NumericTraits< unsigned char const >
class NumericTraits< signed char >
class NumericTraits< signed char const >
class NumericTraits< unsigned short >
class NumericTraits< unsigned short const >
class NumericTraits< signed short >
class NumericTraits< signed short const >
class NumericTraits< unsigned int >
class NumericTraits< unsigned int const >
class NumericTraits< signed int >
class NumericTraits< signed int const >
class NumericTraits< signed long >
class NumericTraits< signed long const >
class NumericTraits< unsigned long >
class NumericTraits< unsigned long const >
class NumericTraits< float >
class NumericTraits< float const >
class NumericTraits< double >
class NumericTraits< double const >
class NumericTraits< long double >
class NumericTraits< long double const >
class NumericTraits< std::complex< float > >
class NumericTraits< std::complex< float > const >
class NumericTraits< std::complex< double > >
class NumericTraits< std::complex< double > const >
class NumericTraits< std::complex< long double > >
class NumericTraits< std::complex< long double > const >
class Rational
Infinite precision rational numbers.
struct ComplexTraits< Rational >
class NumericTraits< Rational >
class NumericTraits< Rational const >
struct ComplexTraits< std::complex< Rational > >
class NumericTraits< std::complex< Rational > >
class NumericTraits< std::complex< Rational > const >
class RealNPolynomial
real polynomial in N variables.
class RealPolynomial
Evaluation of real polynomials at real and complex points.
class SparseMatrixPair
Stores elements of sparse matrix.
class SparseMatrix
Simple sparse matrix.
class SparseMatrixLinearSystem
SparseMatrix -> LinearSystem adaptor.
class SymMatrix
stores a symmetric matrix as just the diagonal and lower triangular part.
struct TagAdd
struct TagSub
struct TagMul
struct TagDiv
struct TagGrab
class Transpose
Efficient matrix transpose.
class UnaryFunction
Abstract 1D map between two types (read spaces).
class Vector
Mathematical vector class, templated by type of element.
class VectorFixed
fixed length stack-stored vnl_vector.
class VectorFixedRef
class VectorRef
vnl_vector using user-supplied storage.
class Math
real numerical constants.
Typedefs
typedef Vector< double > VecD
typedef Vector< float > VecF
Enumerations
enum MatlabPrintFormat {
matlab_print_format_default, matlab_print_format_short, matlab_print_format_long, matlab_print_format_short_e,
matlab_print_format_long_e
}
pretty-printing matlab formats.
enum MatrixType { MatrixNull, MatrixIdentity }
enum FloatRoundStyle {
vnl_round_indeterminate = -1, vnl_round_toward_zero = 0, vnl_round_to_nearest = 1, vnl_round_toward_infinity = 2,
vnl_round_toward_neg_infinity = 3
}
18.2.1.3 Type float_round_style [lib.round.style].
Functions
template<class T >
void Adjugate (Matrix< T > const &A, Matrix< T > *out)
template<class T >
Matrix< T > Adjugate (Matrix< T > const &A)
std::ostream & operator<< (std::ostream &s, const AmoebaSimplexCorner &simplex)
std::ostream & operator<< (std::ostream &s, const std::vector< AmoebaSimplexCorner > &simplex)
bool operator== (const AmoebaSimplexCorner &a, const AmoebaSimplexCorner &b)
double ChiSquaredCumulative (double chisq, int dof)
Compute cumulative distribution function value for chi-squared distribution.
template<class T >
double ChiSquaredStatistic1 (T const *A, T const *B, int n, bool normalize)
Name space for various chi-squared distribution functions.
template<class T >
double ChiSquaredStatistic2 (T const *A, T const *B, int n, bool normalize)
template<class T >
double ChiSquaredStatistic12 (T const *A, T const *B, int n, bool normalize)
template<class T1 , class T2 , class U >
VNL::Vector< U > Convolve (VNL::Vector< T1 > const &v1, VNL::Vector< T2 > const &v2, U *, int use_fft=0)
Convolve two VNL::Vector<T>'s, possibly with different base types T.
template<class T >
VNL::Vector< T > Convolve (VNL::Vector< T > const &v1, VNL::Vector< T > const &v2, int use_fft=0)
Convolve two VNL::Vector<T>'s, with the same base type T.
template<class T1 , class T2 , class U >
VNL::Vector< U > ConvolveCyclic (VNL::Vector< T1 > const &v1, VNL::Vector< T2 > const &v2, U *, bool use_fft=false)
Cyclically convolve two VNL::Vector<T>'s of the same length.
template<class T1 , class T2 , class U >
VNL::Matrix< U > Convolve (VNL::Matrix< T1 > const &v1, VNL::Matrix< T2 > const &v2, U *, int use_fft=0)
template<class T >
VNL::Matrix< T > Convolve (VNL::Matrix< T > const &v1, VNL::Matrix< T > const &v2, int use_fft=0)
template<class T1 , class T2 , class U >
VNL::Matrix< U > ConvolveCyclic (VNL::Matrix< T1 > const &v1, VNL::Matrix< T2 > const &v2, U *, bool use_fft=false)
template<class T1 , class T2 , class U >
VNL::Matrix< U > Convolve (VNL::Matrix< T1 > const &v1, VNL::Vector< T2 > const &v2, U *, int use_fft=0)
template<class T >
VNL::Matrix< T > Convolve (VNL::Matrix< T > const &v1, VNL::Vector< T > const &v2, int use_fft=0)
template<class T1 , class T2 , class U >
VNL::Vector< U > ConvolveCyclicUsingFFT (VNL::Vector< T1 > const &v1, VNL::Vector< T2 > const &v2, U *)
template<class T1 , class T2 , class U >
VNL::Vector< U > ConvolveUsingFFT (VNL::Vector< T1 > const &v1, VNL::Vector< T2 > const &v2, U *, int n)
template<class T >
T Determinant (T const *row0, T const *row1)
direct evaluation for 2x2 matrix.
template<class T >
T Determinant (T const *row0, T const *row1, T const *row2)
direct evaluation for 3x3 matrix.
template<class T >
T Determinant (T const *row0, T const *row1, T const *row2, T const *row3)
direct evaluation for 4x4 matrix.
template<class T >
T Determinant (VNL::Matrix< T > const &M, bool balance=false)
evaluation using direct methods for sizes of 2x2, 3x3, and 4x4 or qr decompostion for other matrices.
void FFTSetgpfa (float *triggs, int size, int pqr[3], int *info)
use C++ overloading to find the correct FORTRAN routine from templated FFT code.
void FFTSetgpfa (double *triggs, int size, int pqr[3], int *info)
use C++ overloading to find the correct FORTRAN routine from templated FFT code.
void FFTgpfa (float *a, float *b, float const *triggs, int inc, int jump, int n, int lot, int isign, int const pqr[3], int *info)
void FFTgpfa (double *a, double *b, double const *triggs, int inc, int jump, int n, int lot, int isign, int const pqr[3], int *info)
template<>
bool GeneralizedSchur (VNL::Matrix< double > *A, VNL::Matrix< double > *B, VNL::Vector< double > *alphar, VNL::Vector< double > *alphai, VNL::Vector< double > *beta, VNL::Matrix< double > *L, VNL::Matrix< double > *R)
template<class T >
bool GeneralizedSchur (VNL::Matrix< T > *A, VNL::Matrix< T > *B, VNL::Vector< T > *alphar, VNL::Vector< T > *alphai, VNL::Vector< T > *beta, VNL::Matrix< T > *L, VNL::Matrix< T > *R)
Vector< double > LevenbergMarquardtMinimize (LeastSquaresFunction &f, Vector< double > const &initial_estimate)
Find minimum of "f", starting at "initial_estimate", and return.
template<class T >
T QRDeterminant (Matrix< T > const &m)
Compute determinant of matrix "M" using QR.
template<class T >
std::ostream & operator<< (std::ostream &, QR< T > const &qr)
template<class T >
VNL::Matrix< T > SVDInverse (VNL::Matrix< T > const &m)
bool SymmetricEigensystemCompute (Matrix< float > const &A, Matrix< float > &V, Vector< float > &D)
Find eigenvalues of a symmetric matrix.
bool SymmetricEigensystemCompute (Matrix< double > const &A, Matrix< double > &V, Vector< double > &D)
Find eigenvalues of a symmetric matrix.
int MagnitudeCmp (const BigNum &, const BigNum &)
void Add (const BigNum &, const BigNum &, BigNum &)
void Subtract (const BigNum &, const BigNum &, BigNum &)
void MultiplyAux (const BigNum &, unsigned short d, BigNum &, unsigned short i)
unsigned short Normalize (const BigNum &, const BigNum &, BigNum &, BigNum &)
Normalize for division.
void DivideAux (const BigNum &, unsigned short, BigNum &, unsigned short &)
Divide digit.
unsigned short EstimateQHat (const BigNum &, const BigNum &, unsigned short)
unsigned short MultiplySubtract (BigNum &, const BigNum &, unsigned short, unsigned short)
Multiply quotient and subtract.
void Divide (const BigNum &, const BigNum &, BigNum &, BigNum &)
BigNum LeftShift (const BigNum &b1, int l)
BigNum RightShift (const BigNum &b1, int l)
std::ostream & operator<< (std::ostream &s, BigNum const &r)
formatted output.
std::istream & operator>> (std::istream &s, BigNum &r)
simple input.
std::string & BigNumToString (std::string &s, const BigNum &b)
Convert the number to a decimal representation in a string.
BigNum & BigNumFromString (BigNum &b, const std::string &s)
Convert the number from a decimal representation in a string.
BigNum operator+ (BigNum const &r1, long r2)
Returns the addition of two bignum numbers.
BigNum operator+ (BigNum const &r1, int r2)
BigNum operator+ (BigNum const &r1, double r2)
BigNum operator+ (BigNum const &r1, long double r2)
BigNum operator+ (long r2, BigNum const &r1)
BigNum operator+ (int r2, BigNum const &r1)
BigNum operator+ (double r2, BigNum const &r1)
BigNum operator+ (long double r2, BigNum const &r1)
BigNum operator- (BigNum const &r1, BigNum const &r2)
Returns the difference of two bignum numbers.
BigNum operator- (BigNum const &r1, long r2)
BigNum operator- (BigNum const &r1, int r2)
BigNum operator- (BigNum const &r1, double r2)
BigNum operator- (BigNum const &r1, long double r2)
BigNum operator- (long r2, BigNum const &r1)
BigNum operator- (int r2, BigNum const &r1)
BigNum operator- (double r2, BigNum const &r1)
BigNum operator- (long double r2, BigNum const &r1)
BigNum operator* (BigNum const &r1, BigNum const &r2)
Returns the multiplication of two bignum numbers.
BigNum operator* (BigNum const &r1, long r2)
BigNum operator* (BigNum const &r1, int r2)
BigNum operator* (BigNum const &r1, double r2)
BigNum operator* (BigNum const &r1, long double r2)
BigNum operator* (long r2, BigNum const &r1)
BigNum operator* (int r2, BigNum const &r1)
BigNum operator* (double r2, BigNum const &r1)
BigNum operator* (long double r2, BigNum const &r1)
BigNum operator/ (BigNum const &r1, BigNum const &r2)
Returns the division of two bignum numbers.
BigNum operator/ (BigNum const &r1, long r2)
BigNum operator/ (BigNum const &r1, int r2)
BigNum operator/ (BigNum const &r1, double r2)
BigNum operator/ (BigNum const &r1, long double r2)
BigNum operator/ (long r1, BigNum const &r2)
BigNum operator/ (int r1, BigNum const &r2)
BigNum operator/ (double r1, BigNum const &r2)
BigNum operator/ (long double r1, BigNum const &r2)
BigNum operator% (BigNum const &r1, BigNum const &r2)
Returns the remainder of r1 divided by r2.
BigNum operator% (BigNum const &r1, long r2)
BigNum operator% (BigNum const &r1, int r2)
BigNum operator% (long r1, BigNum const &r2)
BigNum operator% (int r1, BigNum const &r2)
bool operator== (long r1, BigNum const &r2)
bool operator!= (long r1, BigNum const &r2)
bool operator< (long r1, BigNum const &r2)
bool operator> (long r1, BigNum const &r2)
bool operator<= (long r1, BigNum const &r2)
bool operator>= (long r1, BigNum const &r2)
BigNum Abs (BigNum const &x)
BigNum SquaredMagnitude (BigNum const &x)
BigNum Sqr (BigNum const &x)
bool IsNaN (BigNum const &)
bool IsFinite (BigNum const &)
bool IsNaN (std::complex< BigNum > const &)
bool IsFinite (std::complex< BigNum > const &)
BigNum SquaredMagnitude (std::complex< BigNum > const &z)
BigNum Abs (std::complex< BigNum > const &z)
std::complex< BigNum > Sqr (std::complex< BigNum > const &z)
std::ostream & operator<< (std::ostream &s, std::complex< BigNum > const &z)
std::istream & operator>> (std::istream &s, std::complex< BigNum > &z)
template<class T >
bool BinarySave (std::ostream &f, VNL::Vector< T > const &v)
template<class T >
bool BinaryLoad (std::istream &f, VNL::Vector< T > &v)
template<class T >
bool BinarySave (std::ostream &f, VNL::Matrix< T > const &A)
vnl_matrix.
template<class T >
bool BinaryLoad (std::istream &f, VNL::Matrix< T > &A)
template<class T >
bool BinarySave (std::ostream &f, VNL::DiagMatrix< T > const &D)
vnl_diag_matrix.
template<class T >
bool BinaryLoad (std::istream &f, VNL::DiagMatrix< T > &D)
inst (int)
inst (float)
inst (double)
template<class T >
void Complexify (T const *R, T const *I, std::complex< T > *C, unsigned n)
Overwrite complex array C (of length n) with pairs from real arrays R and I.
template<class T >
void Complexify (T const *R, std::complex< T > *C, unsigned n)
Overwrite complex array C (sz n) with complexified version of real array R.
template<class T >
VNL::Vector< std::complex< T > > Complexify (VNL::Vector< T > const &R)
Return complexified version of real vector R.
template<class T >
VNL::Vector< std::complex< T > > Complexify (VNL::Vector< T > const &R, VNL::Vector< T > const &I)
Return complex vector R+j*I from two real vectors R and I.
template<class T >
VNL::Matrix< std::complex< T > > Complexify (VNL::Matrix< T > const &R)
Return complexified version of real matrix R.
template<class T >
VNL::Matrix< std::complex< T > > Complexify (VNL::Matrix< T > const &R, VNL::Matrix< T > const &I)
Return complex matrix R+j*I from two real matrices R and I.
makro (char)
makro (int)
makro (long)
template<class S , class T >
void Copy (S const *src, T *dst, unsigned n)
Easy conversion between vectors and matrices templated over different types.
template<class S , class T >
void Copy (S const &, T &)
Easy conversion between vectors and matrices templated over different types.
template<class T , class S >
void CVectorOneNorm (T const *p, unsigned n, S *out)
template<class T , class S >
void CVectorTwoNorm (T const *p, unsigned n, S *out)
template<class T , class S >
void CVectorInfNorm (T const *p, unsigned n, S *out)
template<class T , class S >
void CVectorTwoNormSquared (T const *p, unsigned n, S *out)
template<class T , class S >
void CVectorRMSNorm (T const *p, unsigned n, S *out)
template<class T >
T Det (T const *row0, T const *row1)
2x2 matrix.
template<class T >
T Det (T const *row0, T const *row1, T const *row2)
3x3 matrix.
template<class T >
T Det (T const *row0, T const *row1, T const *row2, T const *row3)
4x4 matrix.
template<class T >
T Det (MatrixFixed< 1, 1, T > const &m)
template<class T >
T Det (MatrixFixed< 2, 2, T > const &m)
template<class T >
T Det (MatrixFixed< 3, 3, T > const &m)
template<class T >
T Det (MatrixFixed< 4, 4, T > const &m)
template<class T >
std::ostream & operator<< (std::ostream &, VNL::DiagMatrix< T > const &)
Print in MATLAB diag([1 2 3]) form.
template<class T >
VNL::Matrix< T > operator* (VNL::Matrix< T > const &A, VNL::DiagMatrix< T > const &D)
Multiply a Matrix by a DiagMatrix. Just scales the columns - mn flops.
template<class T >
VNL::Matrix< T > operator* (VNL::DiagMatrix< T > const &D, VNL::Matrix< T > const &A)
Multiply a DiagMatrix by a Matrix. Just scales the rows - mn flops.
template<class T >
VNL::Matrix< T > operator+ (VNL::Matrix< T > const &A, VNL::DiagMatrix< T > const &D)
Add a DiagMatrix to a Matrix. n adds, mn copies.
template<class T >
VNL::Matrix< T > operator+ (VNL::DiagMatrix< T > const &D, VNL::Matrix< T > const &A)
Add a Matrix to a DiagMatrix. n adds, mn copies.
template<class T >
VNL::Matrix< T > operator- (VNL::Matrix< T > const &A, VNL::DiagMatrix< T > const &D)
Subtract a DiagMatrix from a Matrix. n adds, mn copies.
template<class T >
VNL::Matrix< T > operator- (VNL::DiagMatrix< T > const &D, VNL::Matrix< T > const &A)
Subtract a Matrix from a DiagMatrix. n adds, mn copies.
template<class T >
VNL::Vector< T > operator* (VNL::DiagMatrix< T > const &D, VNL::Vector< T > const &A)
Multiply a DiagMatrix by a Vector. n flops.
template<class T >
VNL::Vector< T > operator* (VNL::Vector< T > const &A, VNL::DiagMatrix< T > const &D)
Multiply a Vector by a DiagMatrix. n flops.
void ErrorVectorIndex (const char *fcn, int index)
Raise exception for invalid index.
void ErrorVectorDimension (const char *fcn, int l1, int l2)
Raise exception for invalid dimensions.
void ErrorVectorVaArg (int n)
Raise exception for using class objects, or chars in (.
void ErrorMatrixRowIndex (char const *fcn, int r)
void ErrorMatrixColIndex (char const *fcn, int c)
Raise exception for invalid col index.
void ErrorMatrixDimension (char const *fcn, int r1, int c1, int r2, int c2)
Raise exception for invalid dimensions.
void ErrorMatrixNonSquare (char const *fcn)
Raise exception for invalid dimensions.
void ErrorMatrixVaArg (int n)
Raise exception for using class objects, or chars in (.
template<class T >
std::ostream & MatlabPrint (std::ostream &, T const *array, unsigned length, VNL::MatlabPrintFormat=VNL::matlab_print_format_default)
print a 1D array.
template<class T >
std::ostream & MatlabPrint (std::ostream &, T const *const *array, unsigned rows, unsigned cols, VNL::MatlabPrintFormat=VNL::matlab_print_format_default)
print a 2D array.
template<class T >
std::ostream & MatlabPrint (std::ostream &, VNL::DiagMatrix< T > const &, char const *variable_name=0, VNL::MatlabPrintFormat=VNL::matlab_print_format_default)
print a vnl_diagonal_matrix<>.
template<class T >
std::ostream & MatlabPrint (std::ostream &, VNL::Matrix< T > const &, char const *variable_name=0, VNL::MatlabPrintFormat=VNL::matlab_print_format_default)
print a vnl_matrix<>.
template<class T >
std::ostream & MatlabPrint (std::ostream &, VNL::Vector< T > const &, char const *variable_name=0, VNL::MatlabPrintFormat=VNL::matlab_print_format_default)
print a vnl_vector<>.
template<class T >
MatlabPrintProxy< T > MatlabPrint (T const &obj, char const *name=0, VNL::MatlabPrintFormat format=VNL::matlab_print_format_default)
MatlabPrintFormat MatlabPrintFormatTop ()
get top of stack :.
MatlabPrintFormat MatlabPrintFormatSet (MatlabPrintFormat)
set new, get old format at top of stack :.
void MatlabPrintFormatPush (MatlabPrintFormat)
push/pop the top of the stack :.
void MatlabPrintFormatPop ()
MATLAB_PRINT_SCALAR_DECLARE (int)
MATLAB_PRINT_SCALAR_DECLARE (unsigned int)
MATLAB_PRINT_SCALAR_DECLARE (float)
MATLAB_PRINT_SCALAR_DECLARE (double)
MATLAB_PRINT_SCALAR_DECLARE (long double)
MATLAB_PRINT_SCALAR_DECLARE (std::complex< float >)
MATLAB_PRINT_SCALAR_DECLARE (std::complex< double >)
MATLAB_PRINT_SCALAR_DECLARE (std::complex< long double >)
template<class T >
std::ostream & MatlabPrintScalar (std::ostream &, T value, VNL::MatlabPrintFormat=VNL::matlab_print_format_default)
print scalar to std::ostream.
void ReadBytes (std::istream &s, void *p, unsigned bytes)
template<>
void MatlabReadData (std::istream &s, float *p, unsigned n)
template<>
void MatlabReadData (std::istream &s, double *p, unsigned n)
template<class T >
bool MatlabReadOrDie (std::istream &, Vector< T > &, char const *name=0)
Attempt to read vector or matrix.
template<class T >
bool MatlabReadOrDie (std::istream &, Matrix< T > &, char const *name=0)
template<class T >
void MatlabReadData (std::istream &s, T *ptr, unsigned n)
MATLAB stores its data as a real block followed by an imaginary block.
void WriteBytes (std::ostream &s, void const *p, unsigned bytes)
long ScalarPrecision (float const &)
long ScalarPrecision (double const &)
long ScalarPrecision (std::complex< float > const &)
long ScalarPrecision (std::complex< double > const &)
long IsComplex (float const &)
long IsComplex (double const &)
long IsComplex (std::complex< float > const &)
long IsComplex (std::complex< double > const &)
void WriteReal (std::ostream &s, float const *data, unsigned n)
void WriteReal (std::ostream &s, double const *data, unsigned n)
void WriteReal (std::ostream &s, std::complex< float > const *data, unsigned n)
void WriteReal (std::ostream &s, std::complex< double > const *data, unsigned n)
void WriteImag (std::ostream &, float const *, unsigned)
void WriteImag (std::ostream &, double const *, unsigned)
void WriteImag (std::ostream &s, std::complex< float > const *data, unsigned n)
void WriteImag (std::ostream &s, std::complex< double > const *data, unsigned n)
template<class T >
bool MatlabWrite (std::ostream &, T const &, char const *variable_name)
scalars.
template<class T >
bool MatlabWrite (std::ostream &, T const *, unsigned size, char const *variable_name)
1D array.
template<class T >
bool MatlabWrite (std::ostream &, T const *const *, unsigned rows, unsigned cols, char const *variable_name)
2D array.
template<class T >
m operator+ (T const &, m const &)
template<class T >
m operator- (T const &, m const &)
template<class T >
m operator* (T const &, m const &)
template<class T >
m ElementProduct (m const &, m const &)
template<class T >
m ElementQuotient (m const &, m const &)
template<class T >
T DotProduct (m const &, m const &)
template<class T >
T InnerProduct (m const &, m const &)
template<class T >
T CosAngle (m const &, m const &)
template<class T >
std::ostream & operator<< (std::ostream &, m const &)
template<class T >
std::istream & operator>> (std::istream &, m &)
template<class T >
Matrix< T > operator* (T const &value, Matrix< T > const &m)
template<class T >
Matrix< T > operator+ (T const &value, Matrix< T > const &m)
template<class T >
void Swap (Matrix< T > &A, Matrix< T > &B)
template<class doublereal >
int InplaceTranspose (doublereal *a, unsigned m, unsigned n, char *move, unsigned iwrk)
template<class T >
bool MatrixExp (Matrix< T > const &X, Matrix< T > &expX, double max_err)
Compute the exponential of a square matrix - fiddly form.
template<class T >
Matrix< T > MatrixExp (Matrix< T > const &X)
Compute the exponential of a square matrix - easy form.
std::ostream & operator<< (std::ostream &s, Rational const &r)
formatted output.
std::istream & operator>> (std::istream &s, Rational &r)
simple input.
Rational operator+ (Rational const &r1, Rational const &r2)
Returns the addition of two rational numbers.
Rational operator+ (Rational const &r1, long r2)
Rational operator+ (Rational const &r1, int r2)
Rational operator+ (long r2, Rational const &r1)
Rational operator+ (int r2, Rational const &r1)
Rational operator- (Rational const &r1, Rational const &r2)
Returns the difference of two rational numbers.
Rational operator- (Rational const &r1, long r2)
Rational operator- (Rational const &r1, int r2)
Rational operator- (long r2, Rational const &r1)
Rational operator- (int r2, Rational const &r1)
Rational operator* (Rational const &r1, Rational const &r2)
Returns the multiplication of two rational numbers.
Rational operator* (Rational const &r1, long r2)
Rational operator* (Rational const &r1, int r2)
Rational operator* (long r2, Rational const &r1)
Rational operator* (int r2, Rational const &r1)
Rational operator/ (Rational const &r1, Rational const &r2)
Returns the division of two rational numbers.
Rational operator/ (Rational const &r1, long r2)
Rational operator/ (Rational const &r1, int r2)
Rational operator/ (long r1, Rational const &r2)
Rational operator/ (int r1, Rational const &r2)
Rational operator% (Rational const &r1, Rational const &r2)
Returns the remainder of r1 divided by r2.
Rational operator% (Rational const &r1, long r2)
Rational operator% (Rational const &r1, int r2)
Rational operator% (long r1, Rational const &r2)
Rational operator% (int r1, Rational const &r2)
bool operator== (int r1, Rational const &r2)
bool operator== (long r1, Rational const &r2)
bool operator!= (int r1, Rational const &r2)
bool operator!= (long r1, Rational const &r2)
bool operator< (int r1, Rational const &r2)
bool operator< (long r1, Rational const &r2)
bool operator> (int r1, Rational const &r2)
bool operator> (long r1, Rational const &r2)
bool operator<= (int r1, Rational const &r2)
bool operator<= (long r1, Rational const &r2)
bool operator>= (int r1, Rational const &r2)
bool operator>= (long r1, Rational const &r2)
long Truncate (Rational const &r)
long Floor (Rational const &r)
long Ceil (Rational const &r)
long Round (Rational const &r)
Rational Abs (Rational const &x)
Rational SquaredMagnitude (Rational const &x)
Rational Sqr (Rational const &x)
bool IsNaN (Rational const &)
bool IsFinite (Rational const &x)
bool vnl_math_isnan (std::complex< Rational > const &z)
bool vnl_math_isfinite (std::complex< Rational > const &z)
Rational vnl_math_squared_magnitude (std::complex< Rational > const &z)
Rational vnl_math_abs (std::complex< Rational > const &z)
std::complex< Rational > vnl_math_sqr (std::complex< Rational > const &z)
std::ostream & operator<< (std::ostream &s, std::complex< Rational > const &z)
std::istream & operator>> (std::istream &s, std::complex< Rational > &z)
template<class T >
T RealPolynomialEvaluate (double const *a, int n, T const &x)
RealPolynomial operator+ (const RealPolynomial &f1, const RealPolynomial &f2)
Returns polynomial which is sum of two polynomials f1(x)+f2(x).
RealPolynomial operator- (const RealPolynomial &f1, const RealPolynomial &f2)
Returns polynomial which is different of two polynomials f1(x)-f2(x).
RealPolynomial operator* (const RealPolynomial &f1, const RealPolynomial &f2)
Returns polynomial which is product of two polynomials f1(x)*f2(x).
double RMSDifference (const RealPolynomial &f1, const RealPolynomial &f2, double x1, double x2)
Returns RMS difference between f1 and f2 over range [x1,x2].
void SampleReseed ()
re-seed the random number generator.
void SampleReseed (int seed)
re-seed the random number generator given a seed.
double SampleUniform (double a, double b)
uniform on [a, b).
void SampleNormal2 (double *x, double *y)
two independent samples from a standard normal distribution.
double SampleNormal (double mean, double sigma)
Normal distribution with given mean and standard deviation.
template<class I >
void SampleUniform (I begin, I end, double a, double b)
handy function to fill a range of values.
template<class I >
void SampleNormal (I begin, I end, double mean, double sigma)
handy function to fill a range of values.
VNL_TRACE_INSTANTIATE (float)
VNL_TRACE_INSTANTIATE (double)
template<class T >
T Trace (VNL::Matrix< T > const &)
Calculate trace of a matrix.
template<class T >
T DotProduct (v const &, v const &)
template<class T >
T InnerProduct (v const &, v const &)
template<class T >
T Bracket (v const &, m const &, v const &)
template<class T >
T CosAngle (v const &, v const &)
template<class T >
double Angle (v const &, v const &)
template<class T >
m OuterProduct (v const &, v const &)
template<class T >
v operator+ (T, v const &)
template<class T >
v operator- (T, v const &)
template<class T >
v operator* (T, v const &)
template<class T >
v operator* (v const &, m const &)
template<class T >
v ElementProduct (v const &, v const &)
template<class T >
v ElementQuotient (v const &, v const &)
template<class T >
T Cross2D (v const &, v const &)
template<class T >
v Cross3D (v const &, v const &)
template<class T >
T VectorSSD (v const &, v const &)
template<class T >
void Swap (v &, v &)
template<class T >
Vector< T > operator* (Matrix< T > const &m, Vector< T > const &v)
multiply matrix and (column) vector. O(m*n).
template<class T >
Vector< T > operator+ (T s, Vector< T > const &v)
add scalar and vector. O(n).
template<class T >
Vector< T > operator- (T s, Vector< T > const &v)
subtract vector from scalar. O(n).
template<class T >
Vector< T > operator* (T s, Vector< T > const &v)
multiply scalar and vector. O(n).
template<class T >
void Swap (Vector< T > &a, Vector< T > &b)
template<class T >
T VectorSSD (Vector< T > const &v1, Vector< T > const &v2)
Euclidean Distance between two vectors.
template<class T >
Vector< T > Project (const Vector< T > &v)
Project a homogeneous vector down to a non-homogeneous one.
template<class T >
Vector< T > Unproject (const Vector< T > &v)
Convert a non-homogeneous vector into a homogeneous vector.
template<class T >
std::ostream & operator<< (std::ostream &, Vector< T > const &)
Read/write vector from/to a std::istream.
template<class T >
std::istream & operator>> (std::istream &, Vector< T > &)
Read a VNL::Vector from an ascii std::istream.
template<int n, class T >
VectorFixed< n, T > ElementProduct (VectorFixedRef< n, T > const &, VectorFixedRef< n, T > const &)
template<int n, class T >
VectorFixed< n, T > ElementQuotient (VectorFixedRef< n, T >const &, VectorFixedRef< n, T > const &)
template<int n, class T >
VectorFixed< n, T > operator+ (T const t, VectorFixedRef< n, T > const &rhs)
template<int n, class T >
VectorFixed< n, T > operator- (T const t, VectorFixedRef< n, T > const &rhs)
template<int n, class T >
VectorFixed< n, T > operator* (T const t, VectorFixedRef< n, T > const &rhs)
template<int n, class T >
VectorFixed< n-1, T > Project (const VectorFixed< n, T > &v)
Project a homogeneous vector down to a non-homogeneous one.
template<int n, class T >
VectorFixed< n+1, T > Unproject (const VectorFixed< n, T > &v)
Convert a non-homogeneous vector into a homogeneous vector.
template<int n, class T >
VectorFixed< n, T > Diagmult (const VectorFixed< n, T > &v1, const VectorFixed< n, T > &v2)
Multiply two vectors, treating one vector as representing a diagonal matrix.
template<class T >
T HugeVal (T)
Type-accessible infinities for use in templates.
double HugeVal (double)
float HugeVal (float)
long int HugeVal (long int)
int HugeVal (int)
short HugeVal (short)
char HugeVal (char)
template<class T >
bool IsNaN (T)
bool IsNaN (float)
Return true iff x is "Not a Number".
bool IsNaN (double)
Return true iff x is "Not a Number".
bool IsNaN (long double)
Return true iff x is "Not a Number".
template<class T >
bool IsInf (T)
bool IsInf (float)
Return true if x is inf.
bool IsInf (double)
Return true if x is inf.
bool IsInf (long double)
Return true if x is inf.
template<class T >
bool IsFinite (T)
bool IsFinite (float)
Return true if x is neither NaN nor Inf.
bool IsFinite (double)
Return true if x is neither NaN nor Inf.
bool IsFinite (long double)
Return true if x is neither NaN nor Inf.
long Rnd (float x)
int Rnd (double x)
bool Abs (bool x)
unsigned char Abs (unsigned char x)
unsigned char Abs (signed char x)
unsigned char Abs (char x)
unsigned short Abs (short x)
unsigned short Abs (unsigned short x)
int Abs (int x)
unsigned int Abs (unsigned int x)
long Abs (long x)
unsigned long Abs (unsigned long x)
float Abs (float x)
double Abs (double x)
long double Abs (long double x)
int Max (int x, int y)
unsigned int Max (unsigned int x, unsigned int y)
long Max (long x, long y)
unsigned long Max (unsigned long x, unsigned long y)
float Max (float x, float y)
double Max (double x, double y)
int Min (int x, int y)
unsigned int Min (unsigned int x, unsigned int y)
long Min (long x, long y)
unsigned long Min (unsigned long x, unsigned long y)
float Min (float x, float y)
double Min (double x, double y)
bool Sqr (bool x)
int Sqr (int x)
unsigned int Sqr (unsigned int x)
long Sqr (long x)
float Sqr (float x)
double Sqr (double x)
int Sgn (int x)
int Sgn (long x)
int Sgn (float x)
int Sgn (double x)
int Sgn0 (int x)
int Sgn0 (long x)
int Sgn0 (float x)
int Sgn0 (double x)
unsigned int SquaredMagnitude (char x)
unsigned int SquaredMagnitude (unsigned char x)
unsigned int SquaredMagnitude (int x)
unsigned int SquaredMagnitude (unsigned int x)
long SquaredMagnitude (long x)
unsigned long SquaredMagnitude (unsigned long x)
float SquaredMagnitude (float x)
double SquaredMagnitude (double x)
long double SquaredMagnitude (long double x)
float Cuberoot (float a)
double Cuberoot (double a)
double Hypot (int x, int y)
float Hypot (float x, float y)
double Hypot (double x, double y)
Detailed Description
call this to initialize the format stack.
Typedef Documentation
typedef Vector<double> VNL::VecD
typedef Vector<float> VNL::VecF
Enumeration Type Documentation
enum VNL::FloatRoundStyle
18.2.1.3 Type float_round_style [lib.round.style].
Enumerator:
vnl_round_indeterminate
vnl_round_toward_zero
vnl_round_to_nearest
vnl_round_toward_infinity
vnl_round_toward_neg_infinity
enum VNL::MatlabPrintFormat
pretty-printing matlab formats.
Enumerator:
matlab_print_format_default
matlab_print_format_short
matlab_print_format_long
matlab_print_format_short_e
matlab_print_format_long_e
enum VNL::MatrixType
Enumerator:
MatrixNull
MatrixIdentity
Function Documentation
long double VNL::Abs (long double x) [inline]
double VNL::Abs (double x) [inline]
float VNL::Abs (float x) [inline]
unsigned long VNL::Abs (unsigned long x) [inline]
long VNL::Abs (long x) [inline]
unsigned int VNL::Abs (unsigned int x) [inline]
int VNL::Abs (int x) [inline]
unsigned short VNL::Abs (unsigned short x) [inline]
unsigned short VNL::Abs (short x) [inline]
unsigned char VNL::Abs (char x) [inline]
unsigned char VNL::Abs (signed char x) [inline]
unsigned char VNL::Abs (unsigned char x) [inline]
bool VNL::Abs (bool x) [inline]
Rational VNL::Abs (Rational const & x) [inline]
BigNum VNL::Abs (std::complex< BigNum > const & z) [inline]
References std::sqrt().
BigNum VNL::Abs (BigNum const & x) [inline]
References VNL::BigNum::Abs().
Referenced by CVectorInfNorm(), CVectorOneNorm(), VNL::Matrix< T >::IsIdentity(), VNL::Matrix< T >::IsZero(), VNL::Matrix< T >::operatorInfNorm(), VNL::Matrix< T >::operatorOneNorm(), and VNL::AmoebaFit::SetUpSimplexRelative().
void VNL::Add (const BigNum & b1, const BigNum & b2, VNL::BigNum & sum)
template<class T > VNL::Matrix< T > VNL::Adjugate (VNL::Matrix< T > const & A) [inline]
References Adjugate(), VNL::Matrix< T >::Columns(), and VNL::Matrix< T >::Rows().
template<class T > void VNL::Adjugate (VNL::Matrix< T > const & A, VNL::Matrix< T > * out) [inline]
References VNL::Matrix< T >::assert_size(), Determinant(), VNL::Matrix< T >::Rows(), sub(), and v.
Referenced by Adjugate().
template<class T > double VNL::Angle (v const & , v const &) [inline]
VNL::BigNum & VNL::BigNumFromString (VNL::BigNum & b, const std::string & s)
Convert the number from a decimal representation in a string.
std::string & VNL::BigNumToString (std::string & s, const BigNum & b)
Convert the number to a decimal representation in a string.
References Divide().
template<class T > bool VNL::BinaryLoad (std::istream & f, VNL::DiagMatrix< T > & D) [inline]
References VNL::DiagMatrix< T >::Clear(), VNL::DiagMatrix< T >::DataBlock(), VNL::DiagMatrix< T >::Resize(), VNL::DiagMatrix< T >::size(), and stream_cast.
template<class T > bool VNL::BinaryLoad (std::istream & f, VNL::Matrix< T > & A) [inline]
References c, VNL::Matrix< T >::Clear(), VNL::Matrix< T >::DataBlock(), VNL::Matrix< T >::Resize(), VNL::Matrix< T >::size(), and stream_cast.
template<class T > bool VNL::BinaryLoad (std::istream & f, VNL::Vector< T > & v) [inline]
References VNL::Vector< T >::Clear(), VNL::Vector< T >::DataBlock(), VNL::Vector< T >::Resize(), VNL::Vector< T >::size(), and stream_cast.
template<class T > bool VNL::BinarySave (std::ostream & f, VNL::DiagMatrix< T > const & D) [inline]
vnl_diag_matrix.
References VNL::DiagMatrix< T >::DataBlock(), VNL::DiagMatrix< T >::size(), and stream_cast.
template<class T > bool VNL::BinarySave (std::ostream & f, VNL::Matrix< T > const & A) [inline]
vnl_matrix.
References VNL::Matrix< T >::Cols(), VNL::Matrix< T >::DataArray(), VNL::Matrix< T >::DataBlock(), VNL::Matrix< T >::Rows(), VNL::Matrix< T >::size(), and stream_cast.
template<class T > bool VNL::BinarySave (std::ostream & f, VNL::Vector< T > const & v) [inline]
References VNL::Vector< T >::DataBlock(), VNL::Vector< T >::size(), and stream_cast.
template<class T > T VNL::Bracket (v const & , m const & , v const &) [inline]
long VNL::Ceil (Rational const & r) [inline]
References VNL::Rational::Ceil().
double VNL::ChiSquaredCumulative (double chisq, int dof)
Compute cumulative distribution function value for chi-squared distribution.
Compute cumulative distribution function for chi-squared distribution.
This subroutine computes the cumulative distribution function value for the chi-squared distribution with integer degrees of freedom parameter = dof. This distribution is defined for all non-negative chisq. Thus if a random variable x is drawn from a chi-squared distribution with d degrees of freedom, then P(x < X) = VNL::ChiSquaredCumulative(X,d).
References dchscdf_().
template<class T > double VNL::ChiSquaredStatistic1 (T const * A, T const * B, int n, bool normalize) [inline]
Name space for various chi-squared distribution functions.
A[] and B[] are (pointers to) arrays containing histograms. If the 'normalize' parameter is true, each histogram will be implicitly normalized (so as to sum to 1) before the statistic is calculated :
*DO NOT* add scale factors to these functions or you will break the code written by those who read the documentation. fsm.
Referenced by ChiSquaredStatistic2().
template<class T > double VNL::ChiSquaredStatistic12 (T const * A, T const * B, int n, bool normalize) [inline]
template<class T > double VNL::ChiSquaredStatistic2 (T const * A, T const * B, int n, bool normalize) [inline]
References ChiSquaredStatistic1().
template<class T > VNL::Matrix<std::complex<T> > VNL::Complexify (VNL::Matrix< T > const & R, VNL::Matrix< T > const & I) [inline]
Return complex matrix R+j*I from two real matrices R and I.
template<class T > VNL::Matrix<std::complex<T> > VNL::Complexify (VNL::Matrix< T > const & R) [inline]
Return complexified version of real matrix R.
template<class T > VNL::Vector<std::complex<T> > VNL::Complexify (VNL::Vector< T > const & R, VNL::Vector< T > const & I) [inline]
Return complex vector R+j*I from two real vectors R and I.
template<class T > VNL::Vector<std::complex<T> > VNL::Complexify (VNL::Vector< T > const & R) [inline]
Return complexified version of real vector R.
template<class T > void VNL::Complexify (T const * R, std::complex< T > * C, unsigned n) [inline]
Overwrite complex array C (sz n) with complexified version of real array R.
template<class T > void VNL::Complexify (T const * R, T const * I, std::complex< T > * C, unsigned n) [inline]
Overwrite complex array C (of length n) with pairs from real arrays R and I.
Referenced by VNL::ComplexEigensystem::ComplexEigensystem().
template<class T > VNL::Matrix<T> VNL::Convolve (VNL::Matrix< T > const & v1, VNL::Vector< T > const & v2, int use_fft = 0) [inline]
template<class T1 , class T2 , class U > VNL::Matrix<U> VNL::Convolve (VNL::Matrix< T1 > const & v1, VNL::Vector< T2 > const & v2, U * , int use_fft = 0) [inline]
template<class T > VNL::Matrix<T> VNL::Convolve (VNL::Matrix< T > const & v1, VNL::Matrix< T > const & v2, int use_fft = 0) [inline]
template<class T1 , class T2 , class U > VNL::Matrix<U> VNL::Convolve (VNL::Matrix< T1 > const & v1, VNL::Matrix< T2 > const & v2, U * , int use_fft = 0) [inline]
template<class T > VNL::Vector< T > VNL::Convolve (VNL::Vector< T > const & v1, VNL::Vector< T > const & v2, int use_fft = 0) [inline]
Convolve two VNL::Vector<T>'s, with the same base type T.
The returned VNL::Vector has the same base type T, and is identical to the return value of the previous function when T1 = T2 = U.
References ConvolveUsingFFT(), and VNL::Vector< T >::size().
template<class T1 , class T2 , class U > VNL::Vector< U > VNL::Convolve (VNL::Vector< T1 > const & v1, VNL::Vector< T2 > const & v2, U * , int use_fft = 0) [inline]
Convolve two VNL::Vector<T>'s, possibly with different base types T.
.
The returned VNL::Vector has base type U (the third argument). All calculations are done with type U, so take care! To specify the third argument, pass e.g. a null pointer, casted to U*. Thus: vnl_convolve(v1, v2, (double*)0) would convolve v1 and v2, and return a VNL::Vector<double>.
This convolution is non-cyclic, and the length of the result is one less than the sum of the lengths of the two input vectors. But if one of the arguments has length 0, the result has length 0.
When specifying a non-zero 4th argument, FFTs are used to compute the result (see below), which should be identical. The speed of execution may of course differ. In this case both vectors are padded with a sufficient number of zeros, making the length at least that 4th argument, then vnl_convolve_cyclic() is applied.
References ConvolveUsingFFT(), and VNL::Vector< T >::size().
template<class T1 , class T2 , class U > VNL::Matrix<U> VNL::ConvolveCyclic (VNL::Matrix< T1 > const & v1, VNL::Matrix< T2 > const & v2, U * , bool use_fft = false) [inline]
template<class T1 , class T2 , class U > VNL::Vector< U > VNL::ConvolveCyclic (VNL::Vector< T1 > const & v1, VNL::Vector< T2 > const & v2, U * , bool use_fft = false) [inline]
Cyclically convolve two VNL::Vector<T>'s of the same length.
.
A cyclic convolution requires that the lengths of the input vectors are identical. If this is not the case, an assert failure occurs. The length of the returned vector equals the length of the inputs.
Since the convolution theorem states that a cyclic convolution followed by an FFT is the same as an FFT followed by a multiplication, a cyclic convolution can also be implemented using 3 FFTs on n points and n complex multiplications. By default, vnl_convolve_cyclic does not use FFTs. By specifying "true" as the fourth argument, calculation of the convolution is done using FFTs. This will generally be faster for large n, especially if the vectors are not sparse, and/or if n is a power of 2.
References ConvolveCyclicUsingFFT(), and VNL::Vector< T >::size().
template<class T1 , class T2 , class U > VNL::Vector<U> VNL::ConvolveCyclicUsingFFT (VNL::Vector< T1 > const & v1, VNL::Vector< T2 > const & v2, U *) [inline]
References VNL::FFT1D< T >::BwdTransform(), VNL::FFT1D< T >::FwdTransform(), and VNL::Vector< T >::size().
Referenced by ConvolveCyclic(), and ConvolveUsingFFT().
template<class T1 , class T2 , class U > VNL::Vector<U> VNL::ConvolveUsingFFT (VNL::Vector< T1 > const & v1, VNL::Vector< T2 > const & v2, U * , int n) [inline]
References ConvolveCyclicUsingFFT(), VNL::Vector< T >::DataBlock(), and VNL::Vector< T >::size().
Referenced by Convolve().
template<class S , class T > void VNL::Copy (S const & src, T & dst) [inline]
Easy conversion between vectors and matrices templated over different types.
References Copy().
template<class S , class T > void VNL::Copy (S const * src, T * dst, unsigned n) [inline]
Easy conversion between vectors and matrices templated over different types.
Referenced by Copy(), VNL::SparseMatrixLinearSystem< T >::GetRHS(), VNL::SparseMatrixLinearSystem< T >::Multiply(), VW::Normalisation3D::Normalise(), VW::Normalisation::Normalise(), VNL::SVD< T >::SVD(), SymmetricEigensystemCompute(), VNL::SparseMatrixLinearSystem< T >::TransposeMultiply(), VW::Normalisation3D::UnNormalise(), and VW::Normalisation::UnNormalise().
template<class T > T VNL::CosAngle (v const & , v const &) [inline]
template<class T > T VNL::CosAngle (m const & , m const &) [inline]
Referenced by vnl_discrete_diff_test_lsf().
template<class T > T VNL::Cross2D (v const & , v const &) [inline]
template<class T > v VNL::Cross3D (v const & , v const &) [inline]
Referenced by VW::FMPlanarCompute::GenerateParameterVectorHZ(), VW::FMPlanarCompute::GenerateParameterVectorHZJK(), VW::FMPlanarCompute::GenerateParameterVectorVLJK(), and VW::FMPlanarCompute::ReconstructTransformHZJK().
double VNL::Cuberoot (double a) [inline]
float VNL::Cuberoot (float a) [inline]
template<class T , class S > void VNL::CVectorInfNorm (T const * p, unsigned n, S * out) [inline]
References Abs().
Referenced by VNL::CVector< T >::InfNorm().
template<class T , class S > void VNL::CVectorOneNorm (T const * p, unsigned n, S * out) [inline]
References Abs().
Referenced by VNL::CVector< T >::OneNorm().
template<class T , class S > void VNL::CVectorRMSNorm (T const * p, unsigned n, S * out) [inline]
References CVectorTwoNormSquared(), and std::sqrt().
Referenced by VNL::CVector< T >::RMSNorm().
template<class T , class S > void VNL::CVectorTwoNorm (T const * p, unsigned n, S * out) [inline]
References CVectorTwoNormSquared(), and std::sqrt().
Referenced by VNL::CVector< T >::TwoNorm().
template<class T , class S > void VNL::CVectorTwoNormSquared (T const * p, unsigned n, S * out) [inline]
References SquaredMagnitude().
Referenced by CVectorRMSNorm(), CVectorTwoNorm(), VNL::CVector< T >::SquaredMagnitude(), and VNL::CVector< T >::TwoNorm2().
template<class T > T VNL::Det (MatrixFixed< 4, 4, T > const & m) [inline]
References Det().
template<class T > T VNL::Det (MatrixFixed< 3, 3, T > const & m) [inline]
References Det().
template<class T > T VNL::Det (MatrixFixed< 2, 2, T > const & m) [inline]
References Det().
template<class T > T VNL::Det (MatrixFixed< 1, 1, T > const & m) [inline]
template<class T > T VNL::Det (T const * row0, T const * row1, T const * row2, T const * row3) [inline]
4x4 matrix.
template<class T > T VNL::Det (T const * row0, T const * row1, T const * row2) [inline]
3x3 matrix.
template<class T > T VNL::Det (T const * row0, T const * row1) [inline]
2x2 matrix.
Referenced by Det().
template<class T > T VNL::Determinant (VNL::Matrix< T > const & M, bool balance = false) [inline]
evaluation using direct methods for sizes of 2x2, 3x3, and 4x4 or qr decompostion for other matrices.
References abs, VNL::Matrix< T >::Columns(), Determinant(), VNL::Matrix< T >::GetColumn(), VNL::Matrix< T >::GetRow(), VNL::Matrix< T >::Rows(), VNL::Matrix< T >::ScaleColumn(), VNL::Matrix< T >::ScaleRow(), and v.
template<class T > T VNL::Determinant (T const * row0, T const * row1, T const * row2, T const * row3) [inline]
direct evaluation for 4x4 matrix.
template<class T > T VNL::Determinant (T const * row0, T const * row1, T const * row2) [inline]
direct evaluation for 3x3 matrix.
template<class T > T VNL::Determinant (T const * row0, T const * row1) [inline]
direct evaluation for 2x2 matrix.
Referenced by Adjugate(), VW::EssentialMatrix::Decompose(), Determinant(), QRDeterminant(), and VW::RotationMatrix::Set().
template<int n, class T > VectorFixed<n,T> VNL::Diagmult (const VectorFixed< n, T > & v1, const VectorFixed< n, T > & v2) [inline]
Multiply two vectors, treating one vector as representing a diagonal matrix.
This has the effect of an element-by-element multiplication of the two vectors.
void VNL::Divide (const BigNum & b1, const BigNum & b2, VNL::BigNum & q, VNL::BigNum & r)
References DivideAux(), EstimateQHat(), MagnitudeCmp(), MultiplySubtract(), and Normalize().
Referenced by BigNumToString(), and operator<<().
void VNL::DivideAux (const BigNum & , unsigned short, BigNum & , unsigned short &)
Divide digit.
Referenced by Divide().
template<class T > T VNL::DotProduct (v const & , v const &) [inline]
template<class T > T VNL::DotProduct (m const & , m const &) [inline]
Referenced by VNL::SparseMatrixLinearSystem< T >::ApplyPreconditioner(), VW::PDF::Gaussian2DIso::EvaluateDensityForError(), VW::PDF::Gaussian2D::EvaluateDensityForError(), VW::Homography2DCompute::LeastSquaresFunctionPoints::F(), and VW::FMPlanarCompute::GenerateParameterVectorHZJK().
template<int n, class T > VectorFixed< n, T > VNL::ElementProduct (VectorFixedRef< n, T > const & a, VectorFixedRef< n, T > const & b) [inline]
template<class T > v VNL::ElementProduct (v const & , v const &) [inline]
template<class T > m VNL::ElementProduct (m const & , m const &) [inline]
Referenced by operator*().
template<int n, class T > VectorFixed< n, T > VNL::ElementQuotient (VectorFixedRef< n, T >const & a, VectorFixedRef< n, T > const & b) [inline]
template<class T > v VNL::ElementQuotient (v const & , v const &) [inline]
template<class T > m VNL::ElementQuotient (m const & , m const &) [inline]
Referenced by vnl_matops::homg_diff().
void VNL::ErrorMatrixColIndex (char const * fcn, int c)
Raise exception for invalid col index.
Referenced by VNL::Matrix< T >::GetColumn(), VNL::Matrix< T >::GetNColumns(), and VNL::Matrix< T >::ScaleColumn().
void VNL::ErrorMatrixDimension (char const * fcn, int r1, int c1, int r2, int c2)
Raise exception for invalid dimensions.
Referenced by VNL::Matrix< T >::Extract(), VNL::Matrix< T >::Matrix(), VNL::Matrix< T >::operator+=(), VNL::Matrix< T >::operator-=(), VNL::Matrix< T >::SetColumns(), VNL::SymMatrix< T >::Update(), and VNL::Matrix< T >::Update().
void VNL::ErrorMatrixNonSquare (char const * fcn)
Raise exception for invalid dimensions.
Referenced by VNL::Matrix< T >::SetIdentity().
void VNL::ErrorMatrixRowIndex (char const * fcn, int r)
Referenced by VNL::Matrix< T >::GetNRows(), VNL::Matrix< T >::GetRow(), and VNL::Matrix< T >::ScaleRow().
void VNL::ErrorMatrixVaArg (int n)
Raise exception for using class objects, or chars in (.
..).
void VNL::ErrorVectorDimension (const char * fcn, int l1, int l2)
Raise exception for invalid dimensions.
Referenced by VNL::Vector< T >::operator+=(), VNL::Vector< T >::operator-=(), VNL::VectorFixed< 3, T >::operator=(), VNL::Vector< T >::PostMultiply(), VNL::Vector< T >::PreMultiply(), VNL::SymMatrix< T >::SetHalfRow(), VNL::Vector< T >::Vector(), and VNL::VectorFixed< 3, T >::VectorFixed().
void VNL::ErrorVectorIndex (const char * fcn, int index)
Raise exception for invalid index.
void VNL::ErrorVectorVaArg (int n)
Raise exception for using class objects, or chars in (.
..).
unsigned short VNL::EstimateQHat (const BigNum & , const BigNum & , unsigned short)
Referenced by Divide().
void VNL::FFTgpfa (double * a, double * b, double const * triggs, int inc, int jump, int n, int lot, int isign, int const pqr[3], int * info)
References dgpfa_().
void VNL::FFTgpfa (float * a, float * b, float const * triggs, int inc, int jump, int n, int lot, int isign, int const pqr[3], int * info)
References gpfa_().
Referenced by VNL::FFTBase< D, T >::Transform().
void VNL::FFTSetgpfa (double * triggs, int size, int pqr[3], int * info)
use C++ overloading to find the correct FORTRAN routine from templated FFT code.
References dsetgpfa_().
void VNL::FFTSetgpfa (float * triggs, int size, int pqr[3], int * info)
use C++ overloading to find the correct FORTRAN routine from templated FFT code.
References setgpfa_().
long VNL::Floor (Rational const & r) [inline]
References VNL::Rational::Floor().
template<class T > bool VNL::GeneralizedSchur (VNL::Matrix< T > * A, VNL::Matrix< T > * B, VNL::Vector< T > * alphar, VNL::Vector< T > * alphai, VNL::Vector< T > * beta, VNL::Matrix< T > * L, VNL::Matrix< T > * R) [inline]
References VNL::Vector< T >::begin(), VNL::Matrix< T >::begin(), VNL::Matrix< T >::Cols(), VNL::Vector< T >::end(), VNL::Matrix< T >::end(), GeneralizedSchur(), VNL::Matrix< T >::Rows(), VNL::Vector< T >::size(), and VNL::Matrix< T >::size().
template<> bool VNL::GeneralizedSchur (VNL::Matrix< double > * A, VNL::Matrix< double > * B, VNL::Vector< double > * alphar, VNL::Vector< double > * alphai, VNL::Vector< double > * beta, VNL::Matrix< double > * L, VNL::Matrix< double > * R) [inline]
Referenced by GeneralizedSchur().
char VNL::HugeVal (char)
short VNL::HugeVal (short)
int VNL::HugeVal (int)
long int VNL::HugeVal (long int)
float VNL::HugeVal (float)
double VNL::HugeVal (double)
template<class T > T VNL::HugeVal (T) [inline]
Type-accessible infinities for use in templates.
double VNL::Hypot (double x, double y) [inline]
References std::sqrt().
float VNL::Hypot (float x, float y) [inline]
References std::sqrt().
double VNL::Hypot (int x, int y) [inline]
References std::sqrt().
template<class T > T VNL::InnerProduct (v const & , v const &) [inline]
template<class T > T VNL::InnerProduct (m const & , m const &) [inline]
template<class doublereal > int VNL::InplaceTranspose (doublereal * a, unsigned m, unsigned n, char * move, unsigned iwrk) [inline]
References c.
VNL::inst (double)
VNL::inst (float)
VNL::inst (int)
long VNL::IsComplex (std::complex< double > const &)
long VNL::IsComplex (std::complex< float > const &)
long VNL::IsComplex (double const &)
long VNL::IsComplex (float const &)
Referenced by MatlabWrite().
bool VNL::IsFinite (long double x)
Return true if x is neither NaN nor Inf.
bool VNL::IsFinite (double x) [inline]
Return true if x is neither NaN nor Inf.
bool VNL::IsFinite (float x)
Return true if x is neither NaN nor Inf.
References finitef.
template<class T > bool VNL::IsFinite (T) [inline]
bool VNL::IsFinite (Rational const & x) [inline]
References VNL::Rational::Denominator().
bool VNL::IsFinite (std::complex< BigNum > const &) [inline]
bool VNL::IsFinite (BigNum const &) [inline]
Referenced by VNL::Matrix< T >::assert_finite_internal(), VNL::Vector< T >::IsFinite(), and VNL::Matrix< T >::IsFinite().
bool VNL::IsInf (long double x)
Return true if x is inf.
bool VNL::IsInf (double x)
Return true if x is inf.
bool VNL::IsInf (float x)
Return true if x is inf.
References finitef.
template<class T > bool VNL::IsInf (T) [inline]
bool VNL::IsNaN (long double x)
Return true iff x is "Not a Number".
bool VNL::IsNaN (double x) [inline]
Return true iff x is "Not a Number".
Referenced by VW::Misc::CorrelationScoreAJD(), VW::Misc::CorrelationScoreNMSD(), and VW::ImagePatchYUV::GetZNCC().
bool VNL::IsNaN (float x)
Return true iff x is "Not a Number".
template<class T > bool VNL::IsNaN (T) [inline]
bool VNL::IsNaN (Rational const &) [inline]
bool VNL::IsNaN (std::complex< BigNum > const &) [inline]
bool VNL::IsNaN (BigNum const &) [inline]
Referenced by VNL::Matrix< T >::HasNaNs().
VNL::BigNum VNL::LeftShift (const BigNum & b1, int l)
VNL::Vector< double > VNL::LevenbergMarquardtMinimize (VNL::LeastSquaresFunction & f, VNL::Vector< double > const & initial_estimate)
Find minimum of "f", starting at "initial_estimate", and return.
References VNL::LevenbergMarquardt::Minimize().
int VNL::MagnitudeCmp (const BigNum & b1, const BigNum & b2)
Referenced by Divide().
VNL::makro (long)
VNL::makro (int)
VNL::makro (char)
VNL::MATLAB_PRINT_SCALAR_DECLARE (std::complex< long double >)
VNL::MATLAB_PRINT_SCALAR_DECLARE (std::complex< double >)
VNL::MATLAB_PRINT_SCALAR_DECLARE (std::complex< float >)
VNL::MATLAB_PRINT_SCALAR_DECLARE (long double)
VNL::MATLAB_PRINT_SCALAR_DECLARE (double)
VNL::MATLAB_PRINT_SCALAR_DECLARE (float)
VNL::MATLAB_PRINT_SCALAR_DECLARE (unsigned int)
VNL::MATLAB_PRINT_SCALAR_DECLARE (int)
template<class T > MatlabPrintProxy<T> VNL::MatlabPrint (T const & obj, char const * name = 0, VNL::MatlabPrintFormat format = VNL::matlab_print_format_default) [inline]
template<class T > std::ostream & VNL::MatlabPrint (std::ostream & s, VNL::Vector< T > const & v, char const * variable_name = 0, VNL::MatlabPrintFormat format = VNL::matlab_print_format_default) [inline]
print a vnl_vector<>.
References VNL::Vector< T >::begin(), MatlabPrint(), and VNL::Vector< T >::size().
template<class T > std::ostream & VNL::MatlabPrint (std::ostream & s, VNL::Matrix< T > const & M, char const * variable_name = 0, VNL::MatlabPrintFormat format = VNL::matlab_print_format_default) [inline]
print a vnl_matrix<>.
References VNL::Matrix< T >::Columns(), MatlabPrint(), and VNL::Matrix< T >::Rows().
template<class T > std::ostream & VNL::MatlabPrint (std::ostream & s, VNL::DiagMatrix< T > const & D, char const * variable_name = 0, VNL::MatlabPrintFormat format = VNL::matlab_print_format_default) [inline]
print a vnl_diagonal_matrix<>.
References VNL::DiagMatrix< T >::begin(), MatlabPrint(), and VNL::DiagMatrix< T >::size().
template<class T > std::ostream & VNL::MatlabPrint (std::ostream & s, T const *const * array, unsigned rows, unsigned cols, VNL::MatlabPrintFormat format = VNL::matlab_print_format_default) [inline]
print a 2D array.
References MatlabPrint().
template<class T > std::ostream & VNL::MatlabPrint (std::ostream & s, T const * array, unsigned length, VNL::MatlabPrintFormat format = VNL::matlab_print_format_default) [inline]
print a 1D array.
References MatlabPrintScalar().
Referenced by VNL::GeneralizedEigensystem::GeneralizedEigensystem(), MatlabPrint(), VNL::Powell::Minimize(), operator<<(), VNL::QR< T >::Q(), VNL::SVD< T >::SVD(), and vnl_dbprintmx().
void VNL::MatlabPrintFormatPop ()
void VNL::MatlabPrintFormatPush (VNL::MatlabPrintFormat f)
push/pop the top of the stack :.
VNL::MatlabPrintFormat VNL::MatlabPrintFormatSet (VNL::MatlabPrintFormat f)
set new, get old format at top of stack :.
VNL::MatlabPrintFormat VNL::MatlabPrintFormatTop ()
get top of stack :.
template<class T > std::ostream & VNL::MatlabPrintScalar (std::ostream & s, T value, VNL::MatlabPrintFormat format = VNL::matlab_print_format_default) [inline]
print scalar to std::ostream.
Referenced by MatlabPrint().
template<class T > void VNL::MatlabReadData (std::istream & s, T * ptr, unsigned n) [inline]
MATLAB stores its data as a real block followed by an imaginary block.
This function will read both blocks and interleave them into the area pointed to by ptr. For real T, it is equivalent to s.read(ptr, sizeof(T)*n);
template<> void VNL::MatlabReadData (std::istream & s, double * p, unsigned n) [inline]
References ReadBytes().
template<> void VNL::MatlabReadData (std::istream & s, float * p, unsigned n) [inline]
References ReadBytes().
template<class T > bool VNL::MatlabReadOrDie (std::istream & s, VNL::Matrix< T > & M, char const * name = 0) [inline]
References VNL::MatlabReadHdr::Cols(), VNL::Matrix< T >::Cols(), VNL::Matrix< T >::DataArray(), VNL::MatlabReadHdr::Name(), VNL::MatlabReadHdr::Rows(), and VNL::Matrix< T >::Rows().
template<class T > bool VNL::MatlabReadOrDie (std::istream & s, VNL::Vector< T > & v, char const * name = 0) [inline]
Attempt to read vector or matrix.
If the MATLAB header cannot be read, return false. Else, if a name is given, and it doesn't match what's in the file, abort(). If the data in the file cannot reasonably be read into the destination, abort().
The vector/matrix will be resized if necessary.
References VNL::Vector< T >::begin(), VNL::MatlabReadHdr::Cols(), VNL::MatlabReadHdr::Name(), VNL::Vector< T >::Resize(), VNL::MatlabReadHdr::Rows(), and VNL::Vector< T >::size().
template<class T > bool VNL::MatlabWrite (std::ostream & s, T const *const * data, unsigned rows, unsigned cols, char const * variable_name) [inline]
2D array.
References VNL::MatlabHeader::cols, VNL::MatlabHeader::imag, IsComplex(), VNL::MatlabHeader::namlen, native_BYTE_ORDER, VNL::MatlabHeader::rows, ScalarPrecision(), VNL::MatlabHeader::type, VNL::MatlabHeader::VNL_ROW_WISE, WriteBytes(), WriteImag(), and WriteReal().
template<class T > bool VNL::MatlabWrite (std::ostream & s, T const * v, unsigned size, char const * variable_name) [inline]
1D array.
References VNL::MatlabHeader::cols, VNL::MatlabHeader::imag, IsComplex(), VNL::MatlabHeader::namlen, native_BYTE_ORDER, VNL::MatlabHeader::rows, ScalarPrecision(), VNL::MatlabHeader::type, VNL::MatlabHeader::VNL_COLUMN_WISE, WriteBytes(), WriteImag(), and WriteReal().
template<class T > bool VNL::MatlabWrite (std::ostream & s, T const & x, char const * variable_name) [inline]
scalars.
References VNL::MatlabHeader::cols, VNL::MatlabHeader::imag, IsComplex(), VNL::MatlabHeader::namlen, native_BYTE_ORDER, VNL::MatlabHeader::rows, ScalarPrecision(), VNL::MatlabHeader::type, VNL::MatlabHeader::VNL_COLUMN_WISE, WriteBytes(), WriteImag(), and WriteReal().
Referenced by VNL::MatlabFilewrite::Write().
template<class T > VNL::Matrix< T > VNL::MatrixExp (VNL::Matrix< T > const & X) [inline]
Compute the exponential of a square matrix - easy form.
References VNL::Matrix< T >::Cols(), MatrixExp(), and VNL::Matrix< T >::Rows().
template<class T > bool VNL::MatrixExp (VNL::Matrix< T > const & X, VNL::Matrix< T > & expX, double max_err) [inline]
Compute the exponential of a square matrix - fiddly form.
References VNL::Matrix< T >::assert_size(), VNL::Matrix< T >::operatorInfNorm(), VNL::Matrix< T >::Rows(), and VNL::Matrix< T >::SetIdentity().
Referenced by MatrixExp().
double VNL::Max (double x, double y) [inline]
float VNL::Max (float x, float y) [inline]
unsigned long VNL::Max (unsigned long x, unsigned long y) [inline]
long VNL::Max (long x, long y) [inline]
unsigned int VNL::Max (unsigned int x, unsigned int y) [inline]
int VNL::Max (int x, int y) [inline]
double VNL::Min (double x, double y) [inline]
float VNL::Min (float x, float y) [inline]
unsigned long VNL::Min (unsigned long x, unsigned long y) [inline]
long VNL::Min (long x, long y) [inline]
unsigned int VNL::Min (unsigned int x, unsigned int y) [inline]
int VNL::Min (int x, int y) [inline]
Referenced by VNL::QR< T >::Determinant().
void VNL::MultiplyAux (const BigNum & b, unsigned short d, VNL::BigNum & prod, unsigned short i)
Referenced by Normalize().
unsigned short VNL::MultiplySubtract (BigNum & , const BigNum & , unsigned short, unsigned short)
Multiply quotient and subtract.
Referenced by Divide().
Data VNL::Normalize (const BigNum & b1, const BigNum & b2, VNL::BigNum & u, VNL::BigNum & v)
Normalize for division.
References MultiplyAux().
Referenced by Divide(), VNL::Rational::operator%=(), VNL::Rational::operator*=(), and VNL::Rational::operator/=().
bool VNL::operator!= (long r1, Rational const & r2) [inline]
bool VNL::operator!= (int r1, Rational const & r2) [inline]
bool VNL::operator!= (long r1, BigNum const & r2) [inline]
Rational VNL::operator% (int r1, Rational const & r2) [inline]
Rational VNL::operator% (long r1, Rational const & r2) [inline]
Rational VNL::operator% (Rational const & r1, int r2) [inline]
Rational VNL::operator% (Rational const & r1, long r2) [inline]
Rational VNL::operator% (Rational const & r1, Rational const & r2) [inline]
Returns the remainder of r1 divided by r2.
BigNum VNL::operator% (int r1, BigNum const & r2) [inline]
BigNum VNL::operator% (long r1, BigNum const & r2) [inline]
BigNum VNL::operator% (BigNum const & r1, int r2) [inline]
BigNum VNL::operator% (BigNum const & r1, long r2) [inline]
BigNum VNL::operator% (BigNum const & r1, BigNum const & r2) [inline]
Returns the remainder of r1 divided by r2.
template<int n, class T > VectorFixed<n,T> VNL::operator* (T const t, VectorFixedRef< n, T > const & rhs) [inline]
template<class T > Vector<T> VNL::operator* (T s, Vector< T > const & v) [inline]
multiply scalar and vector. O(n).
template<class T > Vector<T> VNL::operator* (Matrix< T > const & m, Vector< T > const & v) [inline]
multiply matrix and (column) vector. O(m*n).
template<class T > v VNL::operator* (v const & , m const &) [inline]
template<class T > v VNL::operator* (T , v const &) [inline]
VNL::RealPolynomial VNL::operator* (const RealPolynomial & f1, const RealPolynomial & f2)
Returns polynomial which is product of two polynomials f1(x)*f2(x).
References VNL::RealPolynomial::Coefficients(), VNL::RealPolynomial::Degree(), and VNL::Vector< T >::Fill().
Rational VNL::operator* (int r2, Rational const & r1) [inline]
Rational VNL::operator* (long r2, Rational const & r1) [inline]
Rational VNL::operator* (Rational const & r1, int r2) [inline]
Rational VNL::operator* (Rational const & r1, long r2) [inline]
Rational VNL::operator* (Rational const & r1, Rational const & r2) [inline]
Returns the multiplication of two rational numbers.
template<class T > Matrix<T> VNL::operator* (T const & value, Matrix< T > const & m) [inline]
template<class T > m VNL::operator* (T const & , m const &) [inline]
template<class T > VNL::Vector<T> VNL::operator* (VNL::Vector< T > const & A, VNL::DiagMatrix< T > const & D) [inline]
Multiply a Vector by a DiagMatrix. n flops.
References VNL::DiagMatrix< T >::Diagonal(), and ElementProduct().
template<class T > VNL::Vector<T> VNL::operator* (VNL::DiagMatrix< T > const & D, VNL::Vector< T > const & A) [inline]
Multiply a DiagMatrix by a Vector. n flops.
References VNL::DiagMatrix< T >::Diagonal(), and ElementProduct().
template<class T > VNL::Matrix<T> VNL::operator* (VNL::DiagMatrix< T > const & D, VNL::Matrix< T > const & A) [inline]
Multiply a DiagMatrix by a Matrix. Just scales the rows - mn flops.
References VNL::Matrix< T >::Columns(), VNL::DiagMatrix< T >::DataBlock(), and VNL::Matrix< T >::Rows().
template<class T > VNL::Matrix<T> VNL::operator* (VNL::Matrix< T > const & A, VNL::DiagMatrix< T > const & D) [inline]
Multiply a Matrix by a DiagMatrix. Just scales the columns - mn flops.
References VNL::Matrix< T >::Columns(), and VNL::Matrix< T >::Rows().
BigNum VNL::operator* (long double r2, BigNum const & r1) [inline]
BigNum VNL::operator* (double r2, BigNum const & r1) [inline]
BigNum VNL::operator* (int r2, BigNum const & r1) [inline]
BigNum VNL::operator* (long r2, BigNum const & r1) [inline]
BigNum VNL::operator* (BigNum const & r1, long double r2) [inline]
BigNum VNL::operator* (BigNum const & r1, double r2) [inline]
BigNum VNL::operator* (BigNum const & r1, int r2) [inline]
BigNum VNL::operator* (BigNum const & r1, long r2) [inline]
BigNum VNL::operator* (BigNum const & r1, BigNum const & r2) [inline]
Returns the multiplication of two bignum numbers.
template<int n, class T > VectorFixed<n,T> VNL::operator+ (T const t, VectorFixedRef< n, T > const & rhs) [inline]
template<class T > Vector<T> VNL::operator+ (T s, Vector< T > const & v) [inline]
add scalar and vector. O(n).
template<class T > v VNL::operator+ (T , v const &) [inline]
VNL::RealPolynomial VNL::operator+ (const RealPolynomial & f1, const RealPolynomial & f2)
Returns polynomial which is sum of two polynomials f1(x)+f2(x).
Returns sum of two polynomials f1(x)+f2(x).
References VNL::RealPolynomial::Degree().
Rational VNL::operator+ (int r2, Rational const & r1) [inline]
Rational VNL::operator+ (long r2, Rational const & r1) [inline]
Rational VNL::operator+ (Rational const & r1, int r2) [inline]
Rational VNL::operator+ (Rational const & r1, long r2) [inline]
Rational VNL::operator+ (Rational const & r1, Rational const & r2) [inline]
Returns the addition of two rational numbers.
template<class T > Matrix<T> VNL::operator+ (T const & value, Matrix< T > const & m) [inline]
template<class T > m VNL::operator+ (T const & , m const &) [inline]
template<class T > VNL::Matrix<T> VNL::operator+ (VNL::DiagMatrix< T > const & D, VNL::Matrix< T > const & A) [inline]
Add a Matrix to a DiagMatrix. n adds, mn copies.
template<class T > VNL::Matrix<T> VNL::operator+ (VNL::Matrix< T > const & A, VNL::DiagMatrix< T > const & D) [inline]
Add a DiagMatrix to a Matrix. n adds, mn copies.
References VNL::DiagMatrix< T >::DataBlock(), and VNL::DiagMatrix< T >::size().
BigNum VNL::operator+ (long double r2, BigNum const & r1) [inline]
BigNum VNL::operator+ (double r2, BigNum const & r1) [inline]
BigNum VNL::operator+ (int r2, BigNum const & r1) [inline]
BigNum VNL::operator+ (long r2, BigNum const & r1) [inline]
BigNum VNL::operator+ (BigNum const & r1, long double r2) [inline]
BigNum VNL::operator+ (BigNum const & r1, double r2) [inline]
BigNum VNL::operator+ (BigNum const & r1, int r2) [inline]
BigNum VNL::operator+ (BigNum const & r1, long r2) [inline]
Returns the addition of two bignum numbers.
template<int n, class T > VectorFixed<n,T> VNL::operator- (T const t, VectorFixedRef< n, T > const & rhs) [inline]
template<class T > Vector<T> VNL::operator- (T s, Vector< T > const & v) [inline]
subtract vector from scalar. O(n).
template<class T > v VNL::operator- (T , v const &) [inline]
VNL::RealPolynomial VNL::operator- (const RealPolynomial & f1, const RealPolynomial & f2)
Returns polynomial which is different of two polynomials f1(x)-f2(x).
Returns sum of two polynomials f1(x)-f2(x).
References VNL::RealPolynomial::Degree().
Rational VNL::operator- (int r2, Rational const & r1) [inline]
Rational VNL::operator- (long r2, Rational const & r1) [inline]
Rational VNL::operator- (Rational const & r1, int r2) [inline]
Rational VNL::operator- (Rational const & r1, long r2) [inline]
Rational VNL::operator- (Rational const & r1, Rational const & r2) [inline]
Returns the difference of two rational numbers.
template<class T > m VNL::operator- (T const & , m const &) [inline]
template<class T > VNL::Matrix<T> VNL::operator- (VNL::DiagMatrix< T > const & D, VNL::Matrix< T > const & A) [inline]
Subtract a Matrix from a DiagMatrix. n adds, mn copies.
References VNL::DiagMatrix< T >::DataBlock(), and VNL::DiagMatrix< T >::size().
template<class T > VNL::Matrix<T> VNL::operator- (VNL::Matrix< T > const & A, VNL::DiagMatrix< T > const & D) [inline]
Subtract a DiagMatrix from a Matrix. n adds, mn copies.
References VNL::DiagMatrix< T >::DataBlock(), and VNL::DiagMatrix< T >::size().
BigNum VNL::operator- (long double r2, BigNum const & r1) [inline]
BigNum VNL::operator- (double r2, BigNum const & r1) [inline]
BigNum VNL::operator- (int r2, BigNum const & r1) [inline]
BigNum VNL::operator- (long r2, BigNum const & r1) [inline]
BigNum VNL::operator- (BigNum const & r1, long double r2) [inline]
BigNum VNL::operator- (BigNum const & r1, double r2) [inline]
BigNum VNL::operator- (BigNum const & r1, int r2) [inline]
BigNum VNL::operator- (BigNum const & r1, long r2) [inline]
BigNum VNL::operator- (BigNum const & r1, BigNum const & r2) [inline]
Returns the difference of two bignum numbers.
Rational VNL::operator/ (int r1, Rational const & r2) [inline]
Rational VNL::operator/ (long r1, Rational const & r2) [inline]
Rational VNL::operator/ (Rational const & r1, int r2) [inline]
Rational VNL::operator/ (Rational const & r1, long r2) [inline]
Rational VNL::operator/ (Rational const & r1, Rational const & r2) [inline]
Returns the division of two rational numbers.
BigNum VNL::operator/ (long double r1, BigNum const & r2) [inline]
BigNum VNL::operator/ (double r1, BigNum const & r2) [inline]
BigNum VNL::operator/ (int r1, BigNum const & r2) [inline]
BigNum VNL::operator/ (long r1, BigNum const & r2) [inline]
BigNum VNL::operator/ (BigNum const & r1, long double r2) [inline]
BigNum VNL::operator/ (BigNum const & r1, double r2) [inline]
BigNum VNL::operator/ (BigNum const & r1, int r2) [inline]
BigNum VNL::operator/ (BigNum const & r1, long r2) [inline]
BigNum VNL::operator/ (BigNum const & r1, BigNum const & r2) [inline]
Returns the division of two bignum numbers.
bool VNL::operator< (long r1, Rational const & r2) [inline]
bool VNL::operator< (int r1, Rational const & r2) [inline]
bool VNL::operator< (long r1, BigNum const & r2) [inline]
Referenced by VNL::Rational::operator>=().
template<class T > std::ostream & VNL::operator<< (std::ostream & s, VNL::Vector< T > const & v) [inline]
Read/write vector from/to a std::istream.
Overloads the output operator to print a vector. O(n).
References VNL::Vector< T >::size().
std::ostream& VNL::operator<< (std::ostream & s, std::complex< Rational > const & z) [inline]
std::ostream& VNL::operator<< (std::ostream & s, Rational const & r) [inline]
formatted output.
References VNL::Rational::Denominator(), and VNL::Rational::Numerator().
template<class T > std::ostream& VNL::operator<< (std::ostream & , m const &) [inline]
template<class T > std::ostream & VNL::operator<< (std::ostream & s, VNL::DiagMatrix< T > const & D) [inline]
Print in MATLAB diag([1 2 3]) form.
std::ostream& VNL::operator<< (std::ostream & s, std::complex< BigNum > const & z) [inline]
std::ostream & VNL::operator<< (std::ostream & s, BigNum const & r)
formatted output.
Formatted output for bignum.
References Divide().
template<class T > std::ostream& VNL::operator<< (std::ostream & , QR< T > const & qr) [inline]
std::ostream& VNL::operator<< (std::ostream & s, const std::vector< AmoebaSimplexCorner > & simplex)
std::ostream& VNL::operator<< (std::ostream & s, const AmoebaSimplexCorner & simplex)
References VNL::AmoebaSimplexCorner::fv.
bool VNL::operator<= (long r1, Rational const & r2) [inline]
bool VNL::operator<= (int r1, Rational const & r2) [inline]
bool VNL::operator<= (long r1, BigNum const & r2) [inline]
bool VNL::operator== (long r1, Rational const & r2) [inline]
bool VNL::operator== (int r1, Rational const & r2) [inline]
bool VNL::operator== (long r1, BigNum const & r2) [inline]
bool VNL::operator== (const AmoebaSimplexCorner & a, const AmoebaSimplexCorner & b)
Referenced by operator==().
bool VNL::operator> (long r1, Rational const & r2) [inline]
bool VNL::operator> (int r1, Rational const & r2) [inline]
bool VNL::operator> (long r1, BigNum const & r2) [inline]
Referenced by VNL::Rational::operator<=().
bool VNL::operator>= (long r1, Rational const & r2) [inline]
bool VNL::operator>= (int r1, Rational const & r2) [inline]
bool VNL::operator>= (long r1, BigNum const & r2) [inline]
template<class T > std::istream & VNL::operator>> (std::istream & s, VNL::Vector< T > & M) [inline]
Read a VNL::Vector from an ascii std::istream.
If the vector has nonzero size on input, read that many values. Otherwise, read to EOF.
References VNL::Vector< T >::ReadASCII().
std::istream& VNL::operator>> (std::istream & s, std::complex< Rational > & z) [inline]
std::istream& VNL::operator>> (std::istream & s, Rational & r) [inline]
simple input.
References VNL::Rational::Set().
template<class T > std::istream& VNL::operator>> (std::istream & , m &) [inline]
std::istream& VNL::operator>> (std::istream & s, std::complex< BigNum > & z) [inline]
std::istream & VNL::operator>> (std::istream & s, VNL::BigNum & x)
simple input.
Reads a VNL::BigNum from a stream.
template<class T > m VNL::OuterProduct (v const & , v const &) [inline]
Referenced by VW::FMPlanarCompute::ReconstructTransformVLJK().
template<int n, class T > VectorFixed<n-1,T> VNL::Project (const VectorFixed< n, T > & v) [inline]
Project a homogeneous vector down to a non-homogeneous one.
Returns a new vector containing all the elements of the input vector, apart from the last one, divided by the last one.
template<class T > Vector<T> VNL::Project (const Vector< T > & v) [inline]
Project a homogeneous vector down to a non-homogeneous one.
Returns a new vector containing all the elements of the input vector, apart from the last one, divided by the last one.
References VNL::Vector< T >::Size().
template<class T > T VNL::QRDeterminant (Matrix< T > const & m) [inline]
Compute determinant of matrix "M" using QR.
References Determinant().
void VNL::ReadBytes (std::istream & s, void * p, unsigned bytes)
Referenced by MatlabReadData().
template<class T > T VNL::RealPolynomialEvaluate (double const * a, int n, T const & x) [inline]
VNL::BigNum VNL::RightShift (const BigNum & b1, int l)
double VNL::RMSDifference (const RealPolynomial & f1, const RealPolynomial & f2, double x1, double x2)
Returns RMS difference between f1 and f2 over range [x1,x2].
References VNL::RealPolynomial::EvaluateIntegral(), and std::sqrt().
int VNL::Rnd (double x) [inline]
long VNL::Rnd (float x) [inline]
long VNL::Round (Rational const & r) [inline]
References VNL::Rational::Round().
template<class I > void VNL::SampleNormal (I begin, I end, double mean, double sigma) [inline]
handy function to fill a range of values.
References SampleNormal().
double VNL::SampleNormal (double mean, double sigma)
Normal distribution with given mean and standard deviation.
References SampleNormal2().
Referenced by SampleNormal().
void VNL::SampleNormal2 (double * x, double * y)
two independent samples from a standard normal distribution.
References VNL::Math::pi, SampleUniform(), and std::sqrt().
Referenced by SampleNormal().
void VNL::SampleReseed (int seed)
re-seed the random number generator given a seed.
void VNL::SampleReseed ()
re-seed the random number generator.
template<class I > void VNL::SampleUniform (I begin, I end, double a, double b) [inline]
handy function to fill a range of values.
References SampleUniform().
double VNL::SampleUniform (double a, double b)
uniform on [a, b).
return a random number uniformly drawn on [a, b).
Referenced by SampleNormal2(), and SampleUniform().
long VNL::ScalarPrecision (std::complex< double > const &)
References VNL::MatlabHeader::VNL_DOUBLE_PRECISION.
long VNL::ScalarPrecision (std::complex< float > const &)
References VNL::MatlabHeader::VNL_SINGLE_PRECISION.
long VNL::ScalarPrecision (double const &)
References VNL::MatlabHeader::VNL_DOUBLE_PRECISION.
long VNL::ScalarPrecision (float const &)
References VNL::MatlabHeader::VNL_SINGLE_PRECISION.
Referenced by MatlabWrite().
int VNL::Sgn (double x) [inline]
int VNL::Sgn (float x) [inline]
int VNL::Sgn (long x) [inline]
int VNL::Sgn (int x) [inline]
Referenced by VNL::Brent::BracketMinimum(), VNL::AmoebaSimplexCorner::Compare(), VW::FMPlanarCompute::GenerateParameterVectorHZ(), VW::FMPlanarCompute::GenerateParameterVectorHZJK(), VW::FMPlanarCompute::GenerateParameterVectorVLJK(), VNL::Brent::MinimizeGivenBounds(), and VNL::Brent::MinimizeGivenBoundsAnd1stF().
int VNL::Sgn0 (double x) [inline]
int VNL::Sgn0 (float x) [inline]
int VNL::Sgn0 (long x) [inline]
int VNL::Sgn0 (int x) [inline]
double VNL::Sqr (double x) [inline]
float VNL::Sqr (float x) [inline]
long VNL::Sqr (long x) [inline]
unsigned int VNL::Sqr (unsigned int x) [inline]
int VNL::Sqr (int x) [inline]
bool VNL::Sqr (bool x) [inline]
Rational VNL::Sqr (Rational const & x) [inline]
std::complex<BigNum> VNL::Sqr (std::complex< BigNum > const & z) [inline]
BigNum VNL::Sqr (BigNum const & x) [inline]
Referenced by VNL::Powell::Minimize().
long double VNL::SquaredMagnitude (long double x) [inline]
double VNL::SquaredMagnitude (double x) [inline]
float VNL::SquaredMagnitude (float x) [inline]
unsigned long VNL::SquaredMagnitude (unsigned long x) [inline]
long VNL::SquaredMagnitude (long x) [inline]
unsigned int VNL::SquaredMagnitude (unsigned int x) [inline]
unsigned int VNL::SquaredMagnitude (int x) [inline]
unsigned int VNL::SquaredMagnitude (unsigned char x) [inline]
unsigned int VNL::SquaredMagnitude (char x) [inline]
Rational VNL::SquaredMagnitude (Rational const & x) [inline]
BigNum VNL::SquaredMagnitude (std::complex< BigNum > const & z) [inline]
BigNum VNL::SquaredMagnitude (BigNum const & x) [inline]
Referenced by CVectorTwoNormSquared(), VNL::LBFGS::Minimize(), VNL::CVector< T >::Normalize(), VNL::Matrix< T >::NormalizeColumns(), VNL::Matrix< T >::NormalizeRows(), and VNL::QR< T >::Q().
void VNL::Subtract (const BigNum & bmax, const BigNum & bmin, VNL::BigNum & diff)
template<class T > VNL::Matrix<T> VNL::SVDInverse (VNL::Matrix< T > const & m) [inline]
template<class T > void VNL::Swap (Vector< T > & a, Vector< T > & b) [inline]
template<class T > void VNL::Swap (v & , v &) [inline]
template<class T > void VNL::Swap (Matrix< T > & A, Matrix< T > & B) [inline]
References VNL::Matrix< T >::Swap().
bool VNL::SymmetricEigensystemCompute (VNL::Matrix< double > const & A, VNL::Matrix< double > & V, VNL::Vector< double > & D)
Find eigenvalues of a symmetric matrix.
References VNL::Matrix< T >::assert_finite(), c, VNL::Matrix< T >::Columns(), VNL::Matrix< T >::DataBlock(), VNL::Matrix< T >::Rows(), rs_(), and VNL::Vector< T >::size().
bool VNL::SymmetricEigensystemCompute (VNL::Matrix< float > const & A, VNL::Matrix< float > & V, VNL::Vector< float > & D)
Find eigenvalues of a symmetric matrix.
References VNL::Matrix< T >::Columns(), Copy(), VNL::Matrix< T >::Rows(), and VNL::Vector< T >::size().
Referenced by VNL::Scatter3x3< T >::compute_eigensystem(), and VNL::SymmetricEigensystem< T >::SymmetricEigensystem().
template<class T > T VNL::Trace (VNL::Matrix< T > const & M) [inline]
Calculate trace of a matrix.
References VNL::Matrix< T >::Cols(), and VNL::Matrix< T >::Rows().
long VNL::Truncate (Rational const & r) [inline]
References VNL::Rational::Truncate().
Referenced by VNL::Rational::Ceil(), VNL::Rational::Floor(), VNL::Rational::operator int(), VNL::Rational::operator long(), VNL::Rational::operator short(), and VNL::Rational::Round().
template<int n, class T > VectorFixed<n+1,T> VNL::Unproject (const VectorFixed< n, T > & v) [inline]
Convert a non-homogeneous vector into a homogeneous vector.
Returns a new vector which is the input vector augmented by one more element of value 1.0.
template<class T > Vector<T> VNL::Unproject (const Vector< T > & v) [inline]
Convert a non-homogeneous vector into a homogeneous vector.
Returns a new vector which is the input vector augmented by one more element of value 1.0.
References VNL::Vector< T >::Size().
template<class T > T VNL::VectorSSD (Vector< T > const & v1, Vector< T > const & v2) [inline]
Euclidean Distance between two vectors.
Sum of Differences squared.
References VNL::Vector< T >::begin(), and VNL::Vector< T >::size().
template<class T > T VNL::VectorSSD (v const & , v const &) [inline]
Rational VNL::vnl_math_abs (std::complex< Rational > const & z) [inline]
References std::sqrt().
bool VNL::vnl_math_isfinite (std::complex< Rational > const & z) [inline]
bool VNL::vnl_math_isnan (std::complex< Rational > const & z) [inline]
std::complex<Rational> VNL::vnl_math_sqr (std::complex< Rational > const & z) [inline]
Rational VNL::vnl_math_squared_magnitude (std::complex< Rational > const & z) [inline]
VNL::VNL_TRACE_INSTANTIATE (double)
VNL::VNL_TRACE_INSTANTIATE (float)
void VNL::WriteBytes (std::ostream & s, void const * p, unsigned bytes)
Referenced by MatlabWrite(), WriteImag(), and WriteReal().
void VNL::WriteImag (std::ostream & s, std::complex< double > const * data, unsigned n)
References WriteBytes().
void VNL::WriteImag (std::ostream & s, std::complex< float > const * data, unsigned n)
References WriteBytes().
void VNL::WriteImag (std::ostream & , double const * , unsigned)
void VNL::WriteImag (std::ostream & , float const * , unsigned)
Referenced by MatlabWrite().
void VNL::WriteReal (std::ostream & s, std::complex< double > const * data, unsigned n)
References WriteBytes().
void VNL::WriteReal (std::ostream & s, std::complex< float > const * data, unsigned n)
References WriteBytes().
void VNL::WriteReal (std::ostream & s, double const * data, unsigned n)
References WriteBytes().
void VNL::WriteReal (std::ostream & s, float const * data, unsigned n)
References WriteBytes().
Referenced by MatlabWrite().