VW: VW::DrawFunctions Namespace Reference
VW::DrawFunctions Namespace Reference
Draw things on displays.
Classes
struct Colour
Small struct that stores the colour to be used for drawing.
Enumerations
enum CornerShape { CROSS, PLUS, SQUARE, BAD_SHAPE }
Enum of shapes for drawing point features.
Functions
void Draw (DisplayBase &display, const ImageMono< unsigned char > &image)
void Draw (DisplayBase &display, const ImageRGB< unsigned char > &image)
void Draw (DisplayBase &display, const ImageHSV< unsigned char > &image)
void Draw (DisplayBase &display, const Point2D &p, Normalisation C=Normalisation(), float size=2, CornerShape shape=PLUS)
void Draw (DisplayBase &display, const std::vector< Point2D > &pl, Normalisation C=Normalisation(), float size=2, CornerShape shape=PLUS)
void Draw (DisplayBase &display, const Point2D &p, float size=2, CornerShape shape=PLUS)
void Draw (DisplayBase &display, const VW::CornerFeature &p, Normalisation C=Normalisation(), float size=2, CornerShape shape=PLUS)
void Draw (DisplayBase &display, const VW::CornerFeature &p, float size=2, CornerShape shape=PLUS)
void Draw (DisplayBase &display, const VW::SIFTFeature &p, Normalisation C=Normalisation())
void Draw (DisplayBase &display, const std::vector< VW::SIFTFeature > &p, Normalisation C=Normalisation())
void Draw (DisplayBase &display, const VW::PatchFeature &p, Normalisation C=Normalisation())
void Draw (DisplayBase &display, const std::vector< VW::PatchFeature > &p, Normalisation C=Normalisation())
void Draw (DisplayBase &display, const LineSeg2D &ls, Normalisation C=Normalisation())
void Draw (DisplayBase &display, const std::list< LineSeg2D > &ls)
void Draw (DisplayBase &display, const std::list< LineSegFitted > &ls)
void Draw (DisplayBase &display, const Line2D &l, Normalisation C=Normalisation())
void Draw (DisplayBase &display, const Trajectory< Point2D > &t, Normalisation C=Normalisation(), bool=true)
void Draw (DisplayBase &display, const Trajectory< Point2D > &t, bool b)
void Draw (DisplayBase &display, const Trajectory< VW::PlesseyCorner > &t, Normalisation C=Normalisation(), bool=true)
void Draw (DisplayBase &display, const Trajectory< VW::PlesseyCorner > &t, bool b)
template<class Type >
void Draw (DisplayBase &display, const TrajectoryMap< Type > &tm, Normalisation C=Normalisation())
void Draw (DisplayBase &display, const EdgeData &edat)
void Draw (DisplayBase &display, const EdgeString &estring)
void Draw (DisplayBase &display, const std::vector< VW::CornerFeature > &corners, Normalisation C=Normalisation(), float size=2, CornerShape shape=PLUS, const std::vector< Colour > *colours=0)
void Draw (DisplayBase &display, const Point2D &location, const VW::Covariance2D &covar)
void DrawCovariance (DisplayBase &display, const Point2D &location, const VNL::MatrixFixed< 2, 2, double > &covar)
void DrawRectangleOutline (DisplayBase &display, unsigned int x0, unsigned int y0, unsigned int x1, unsigned int y1, unsigned int linewidth=1)
void Draw (PSCanvas &psc, const ImageMono< unsigned char > &image)
void Draw (PSCanvas &psc, const ImageRGB< unsigned char > &image)
void Draw (PSCanvas &psc, const ImageYUV< unsigned char > &image)
void Draw (PSCanvas &psc, const EdgeData &edges)
void Draw (DisplayX &display, const ImageMono< unsigned char > &image)
void Draw (DisplayX &display, const ImageRGB< unsigned char > &image)
void Draw (DisplayX &display, const ImageYUV< unsigned char > &image)
void Draw (DisplayX &display, const ImageHSV< unsigned char > &image)
void Draw (DisplayX &display, const ImageInterleave< unsigned char, 4 > &image)
void Draw (DisplayX &display, const ImageInterleave< unsigned char, 2 > &image)
void Draw (DisplayXForms &display, const ImageMono< unsigned char > &image)
void Draw (DisplayXForms &display, const ImageRGB< unsigned char > &image)
void Draw (DisplayXForms &display, const ImageYUV< unsigned char > &image)
void Draw (DisplayXForms &display, const ImageHSV< unsigned char > &image)
void Draw (DisplayXForms &display, const ImageInterleave< unsigned char, 4 > &image)
void Draw (DisplayXForms &display, const ImageInterleave< unsigned char, 2 > &image)
void Draw (DisplayGLCommon &display, const ImageMono< unsigned char > &image)
void Draw (DisplayGLCommon &display, const ImageRGB< unsigned char > &image)
void Draw (DisplayGLCommon &display, const ImageYUV< unsigned char > &image)
void Draw (DisplayGLCommon &display, const ImageHSV< unsigned char > &image)
void Draw (DisplayGLCommon &display, const std::vector< VW::PlesseyCorner > &corners, VW::Normalisation C=Normalisation(), float size=2, CornerShape shape=PLUS, const std::vector< Colour > *colours=0)
void Draw (DisplayGTKGLCommon &display, const ImageMono< unsigned char > &image, const vnl_vector_fixed< float, 3 > position, const vnl_quaternion< float > orientation)
void Draw (DisplayGTKGLCommon &display, const Point3D &p)
void Draw (DisplayGTKCommon &display, const ImageMono< unsigned char > &image)
void Draw (DisplayGTKCommon &display, const ImageRGB< unsigned char > &image)
void Draw (DisplayGTKCommon &display, const ImageYUV< unsigned char > &image)
void Draw (DisplayGTKCommon &display, const ImageHSV< unsigned char > &image)
void Draw (DisplayGTKCommon &display, const EdgeData &edat)
Detailed Description
Draw things on displays.
Author:
BJ Tordoff, JGH Knight
Date:
02/08/2002 This file can draw things on general displays using primitives only. The functions are therefore slow and an optimised version should be used where available (these are normally provided with the implementations of the display).
Function Documentation
void VW::DrawFunctions::Draw (DisplayGTKCommon & display, const EdgeData & edat)
void VW::DrawFunctions::Draw (DisplayGTKCommon & display, const ImageHSV< unsigned char > & image)
void VW::DrawFunctions::Draw (DisplayGTKCommon & display, const ImageYUV< unsigned char > & image)
References Draw(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), and VW::ImageCopy().
void VW::DrawFunctions::Draw (DisplayGTKCommon & display, const ImageRGB< unsigned char > & image)
References VW::DisplayGTKCommon::GetDrawingArea(), VW::DisplayGTKWidget::GetHeight(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetHeight(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetRawBuffer(), VW::DisplayGTKWidget::GetWidth(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetWidth(), and VW::ImageConversions::VWImage_to_RGBBuffer().
void VW::DrawFunctions::Draw (DisplayGTKCommon & display, const ImageMono< unsigned char > & image)
References VW::DisplayGTKCommon::GetDrawingArea(), VW::DisplayGTKWidget::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetRawBuffer(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), and VW::DisplayGTKWidget::GetWidth().
void VW::DrawFunctions::Draw (DisplayGTKGLCommon & display, const Point3D & p)
References VW::Point3D::GetX(), VW::Point3D::GetY(), and VW::Point3D::GetZ().
void VW::DrawFunctions::Draw (DisplayGTKGLCommon & display, const ImageMono< unsigned char > & image, const vnl_vector_fixed< float, 3 > position, const vnl_quaternion< float > orientation)
AJD
References DEF_IMAGE_HALF_HEIGHT, VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetRawBuffer(), and VW::ImageBase< PixelType, PixelPtr >::GetWidth().
void VW::DrawFunctions::Draw (DisplayGLCommon & display, const std::vector< VW::PlesseyCorner > & corners, VW::Normalisation C = Normalisation(), float size = 2, CornerShape shape = PLUS, const std::vector< Colour > * colours = 0)
void VW::DrawFunctions::Draw (DisplayGLCommon & display, const ImageHSV< unsigned char > & image)
References Draw(), VW::ImageBase< PixelHSV< Type >, PixelHSV< Type > * >::GetHeight(), VW::ImageBase< PixelHSV< Type >, PixelHSV< Type > * >::GetWidth(), and VW::ImageCopy().
void VW::DrawFunctions::Draw (DisplayGLCommon & display, const ImageYUV< unsigned char > & image)
References Draw(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), and VW::ImageCopy().
void VW::DrawFunctions::Draw (DisplayGLCommon & display, const ImageRGB< unsigned char > & image)
References VW::DisplayGLCommon::GenerateTexture(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetHeight(), VW::DisplayGLCommon::GetImageDrawingDepth(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetRawBuffer(), VW::DisplayGLCommon::GetTextureHeight(), VW::DisplayGLCommon::GetTextureName(), VW::DisplayGLCommon::GetTextureWidth(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetWidth(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::IsAlloced(), VW::DisplayGLCommon::MakeCurrent(), VW::DisplayGLCommon::Reset(), VERBOSE, and VW::ImageConversions::VWImage_to_RGBABuffer().
void VW::DrawFunctions::Draw (DisplayGLCommon & display, const ImageMono< unsigned char > & image)
References VW::DisplayGLCommon::GenerateTexture(), VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::DisplayGLCommon::GetImageDrawingDepth(), VW::ImageBase< PixelType, PixelPtr >::GetRawBuffer(), VW::DisplayGLCommon::GetTextureHeight(), VW::DisplayGLCommon::GetTextureName(), VW::DisplayGLCommon::GetTextureWidth(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), VW::ImageBase< PixelType, PixelPtr >::IsAlloced(), VW::DisplayGLCommon::MakeCurrent(), VW::DisplayGLCommon::Reset(), and VERBOSE.
void VW::DrawFunctions::Draw (DisplayXForms & display, const ImageInterleave< unsigned char, 2 > & image)
void VW::DrawFunctions::Draw (DisplayXForms & display, const ImageInterleave< unsigned char, 4 > & image)
void VW::DrawFunctions::Draw (DisplayXForms & display, const ImageHSV< unsigned char > & image)
References VW::DisplayXForms::ColourLookUp(), VW::DisplayXForms::DisplayXImage(), VW::DisplayXForms::GetDepth(), VW::DisplayXForms::GetHeight(), VW::ImageBase< PixelHSV< Type >, PixelHSV< Type > * >::GetHeight(), VW::DisplayXForms::GetImagePointer(), VW::ImageBase< PixelHSV< Type >, PixelHSV< Type > * >::GetRowStart(), VW::DisplayXForms::GetWidth(), VW::ImageBase< PixelHSV< Type >, PixelHSV< Type > * >::GetWidth(), VW::PixelHSV< Type >::h, VW::ImageConversions::HSV2RGB(), VW::PixelHSV< Type >::s, VW::PixelHSV< Type >::v, and v.
void VW::DrawFunctions::Draw (DisplayXForms & display, const ImageYUV< unsigned char > & image)
References VW::DisplayXForms::ColourLookUp(), VW::DisplayXForms::DisplayXImage(), VW::DisplayXForms::GetDepth(), VW::DisplayXForms::GetHeight(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::DisplayXForms::GetImagePointer(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetRowStart(), VW::DisplayXForms::GetWidth(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), VW::PixelYUV< Type >::u, VW::PixelYUV< Type >::v, v, VW::PixelYUV< Type >::y, and VW::ImageConversions::YUV2RGB().
void VW::DrawFunctions::Draw (DisplayXForms & display, const ImageRGB< unsigned char > & image)
References VW::PixelRGB< Type >::b, VW::DisplayXForms::ColourLookUp(), VW::DisplayXForms::DisplayXImage(), VW::PixelRGB< Type >::g, VW::DisplayXForms::GetDepth(), VW::DisplayXForms::GetHeight(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetHeight(), VW::DisplayXForms::GetImagePointer(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetRawBuffer(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetRowStart(), VW::DisplayXForms::GetWidth(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetWidth(), and VW::PixelRGB< Type >::r.
void VW::DrawFunctions::Draw (DisplayXForms & display, const ImageMono< unsigned char > & image)
References VW::DisplayXForms::DisplayXImage(), VW::DisplayXForms::GetDepth(), VW::DisplayXForms::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::DisplayXForms::GetImagePointer(), VW::ImageBase< PixelType, PixelPtr >::GetRowStart(), VW::DisplayXForms::GetWidth(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), and VW::DisplayXForms::GreyLookUp().
void VW::DrawFunctions::Draw (DisplayX & display, const ImageInterleave< unsigned char, 2 > & image)
void VW::DrawFunctions::Draw (DisplayX & display, const ImageInterleave< unsigned char, 4 > & image)
void VW::DrawFunctions::Draw (DisplayX & display, const ImageHSV< unsigned char > & image)
References VW::DisplayX::ColourLookUp(), VW::DisplayX::DisplayXImage(), VW::DisplayX::GetDepth(), VW::DisplayX::GetHeight(), VW::ImageBase< PixelHSV< Type >, PixelHSV< Type > * >::GetHeight(), VW::DisplayX::GetImagePointer(), VW::ImageBase< PixelHSV< Type >, PixelHSV< Type > * >::GetRowStart(), VW::DisplayX::GetWidth(), VW::ImageBase< PixelHSV< Type >, PixelHSV< Type > * >::GetWidth(), VW::PixelHSV< Type >::h, VW::ImageConversions::HSV2RGB(), VW::PixelHSV< Type >::s, VW::PixelHSV< Type >::v, and v.
void VW::DrawFunctions::Draw (DisplayX & display, const ImageYUV< unsigned char > & image)
References VW::DisplayX::ColourLookUp(), VW::DisplayX::DisplayXImage(), VW::DisplayX::GetDepth(), VW::DisplayX::GetHeight(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::DisplayX::GetImagePointer(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetRowStart(), VW::DisplayX::GetWidth(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), VW::PixelYUV< Type >::u, VW::PixelYUV< Type >::v, v, VW::PixelYUV< Type >::y, and VW::ImageConversions::YUV2RGB().
void VW::DrawFunctions::Draw (DisplayX & display, const ImageRGB< unsigned char > & image)
References VW::PixelRGB< Type >::b, VW::DisplayX::ColourLookUp(), VW::DisplayX::DisplayXImage(), VW::PixelRGB< Type >::g, VW::DisplayX::GetDepth(), VW::DisplayX::GetHeight(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetHeight(), VW::DisplayX::GetImagePointer(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetRawBuffer(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetRowStart(), VW::DisplayX::GetWidth(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetWidth(), and VW::PixelRGB< Type >::r.
void VW::DrawFunctions::Draw (DisplayX & display, const ImageMono< unsigned char > & image)
References VW::DisplayX::DisplayXImage(), VW::DisplayX::GetDepth(), VW::DisplayX::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::DisplayX::GetImagePointer(), VW::ImageBase< PixelType, PixelPtr >::GetRowStart(), VW::DisplayX::GetWidth(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), and VW::DisplayX::GreyLookUp().
void VW::DrawFunctions::Draw (PSCanvas & psc, const EdgeData & edges)
References ca(), VW::PSCanvas::DrawLine(), VW::EdgeData::edgels, and VW::PSCanvas::SetPenColour().
void VW::DrawFunctions::Draw (PSCanvas & psc, const ImageYUV< unsigned char > & image)
References VW::PixelRGB< Type >::b, VW::PixelRGB< Type >::g, VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), VW::DisplayBase::IsInitialised(), VW::PixelRGB< Type >::r, and VW::PSCanvas::Stream().
void VW::DrawFunctions::Draw (PSCanvas & psc, const ImageRGB< unsigned char > & image)
References VW::PixelRGB< Type >::b, VW::PixelRGB< Type >::g, VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetHeight(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetWidth(), VW::DisplayBase::IsInitialised(), VW::PixelRGB< Type >::r, and VW::PSCanvas::Stream().
void VW::DrawFunctions::Draw (PSCanvas & psc, const ImageMono< unsigned char > & image)
References VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), VW::DisplayBase::IsInitialised(), VW::PSCanvas::Stream(), and VW::PixelMono< Type >::y.
void VW::DrawFunctions::Draw (VW::DisplayBase & display, const Point2D & location, const VW::Covariance2D & covar)
References VW::Covariance2D::CholeskyDecompose(), VW::DisplayBase::DrawEllipse(), VW::Point2D::GetX(), and VW::Point2D::GetY().
void VW::DrawFunctions::Draw (DisplayBase & display, const std::vector< VW::CornerFeature > & corners, Normalisation C = Normalisation(), float size = 2, CornerShape shape = PLUS, const std::vector< Colour > * colours = 0)
void VW::DrawFunctions::Draw (DisplayBase & display, const EdgeString & estring)
References VW::DisplayBase::SetPixel().
void VW::DrawFunctions::Draw (DisplayBase & display, const EdgeData & edat)
References VW::EdgeData::edgels, and VW::DisplayBase::SetPixel().
template<class Type > void VW::DrawFunctions::Draw (DisplayBase & display, const TrajectoryMap< Type > & tm, Normalisation C = Normalisation()) [inline]
References Draw().
void VW::DrawFunctions::Draw (DisplayBase & display, const Trajectory< VW::PlesseyCorner > & t, bool b)
References Draw().
void VW::DrawFunctions::Draw (DisplayBase & display, const Trajectory< VW::PlesseyCorner > & t, Normalisation C = Normalisation(), bool draw_backwards = true)
References VW::DisplayBase::DrawLine(), VW::Trajectory< Feature >::GetNewestFeature(), VW::Trajectory< Feature >::GetOldestFeature(), VW::Trajectory< Feature >::GetOldFeature(), VW::DisplayBase::GetPenColour(), VW::Point2D::GetX(), VW::Point2D::GetY(), VW::DisplayBase::SetPenColour(), VW::Trajectory< Feature >::size(), and VW::Normalisation::UnNormalise().
void VW::DrawFunctions::Draw (DisplayBase & display, const Trajectory< Point2D > & t, bool b)
References Draw().
void VW::DrawFunctions::Draw (DisplayBase & display, const Trajectory< Point2D > & t, Normalisation C = Normalisation(), bool draw_backwards = true)
References VW::DisplayBase::DrawLine(), VW::Trajectory< Feature >::GetNewestFeature(), VW::Trajectory< Feature >::GetOldestFeature(), VW::Trajectory< Feature >::GetOldFeature(), VW::DisplayBase::GetPenColour(), VW::Point2D::GetX(), VW::Point2D::GetY(), VW::DisplayBase::SetPenColour(), VW::Trajectory< Feature >::size(), and VW::Normalisation::UnNormalise().
void VW::DrawFunctions::Draw (DisplayBase & display, const Line2D & l, Normalisation C = Normalisation())
References Draw(), VW::DisplayBase::GetHeight(), VW::DisplayBase::GetWidth(), VW::Line2D::Truncate(), and VW::Normalisation::UnNormalise().
void VW::DrawFunctions::Draw (DisplayBase & display, const std::list< LineSegFitted > & ls)
References Draw().
void VW::DrawFunctions::Draw (DisplayBase & display, const std::list< LineSeg2D > & ls)
References Draw().
void VW::DrawFunctions::Draw (DisplayBase & display, const LineSeg2D & ls, Normalisation C = Normalisation())
References VW::DisplayBase::DrawLine(), VW::LineSeg2D::ep, VW::Point2D::GetX(), VW::Point2D::GetY(), VW::LineSeg2D::sp, and VW::Normalisation::UnNormalise().
void VW::DrawFunctions::Draw (DisplayBase & display, const std::vector< VW::PatchFeature > & p, Normalisation C = Normalisation())
References Draw().
void VW::DrawFunctions::Draw (DisplayBase & display, const VW::PatchFeature & p, Normalisation C = Normalisation())
References c, VW::DisplayBase::DrawLine(), VW::CornerFeature::GetFeatureScale(), VW::PatchFeature::GetOrientation(), VW::PatchFeature::GetPatchSize(), VW::Point2D::GetX(), VW::Point2D::GetY(), and VW::Normalisation::UnNormalise().
void VW::DrawFunctions::Draw (DisplayBase & display, const std::vector< VW::SIFTFeature > & p, Normalisation C = Normalisation())
References Draw().
void VW::DrawFunctions::Draw (DisplayBase & display, const VW::SIFTFeature & p, Normalisation C = Normalisation())
References VW::DisplayBase::DrawCircle(), VW::DisplayBase::DrawLine(), VW::CornerFeature::GetFeatureScale(), VW::SIFTFeature::GetOrientation(), VW::Point2D::GetX(), VW::Point2D::GetY(), and VW::Normalisation::UnNormalise().
void VW::DrawFunctions::Draw (DisplayBase & display, const VW::CornerFeature & p, float size = 2, CornerShape shape = PLUS)
References Draw().
void VW::DrawFunctions::Draw (DisplayBase & display, const VW::CornerFeature & p, Normalisation C = Normalisation(), float size = 2, CornerShape shape = PLUS)
References CROSS, VW::DisplayBase::DrawLine(), VW::CornerFeature::GetFeatureScale(), VW::Point2D::GetX(), VW::Point2D::GetY(), PLUS, SQUARE, and VW::Normalisation::UnNormalise().
void VW::DrawFunctions::Draw (DisplayBase & display, const Point2D & p, float size = 2, CornerShape shape = PLUS)
References Draw().
void VW::DrawFunctions::Draw (DisplayBase & display, const std::vector< Point2D > & pl, Normalisation C = Normalisation(), float size = 2, CornerShape shape = PLUS)
References Draw().
void VW::DrawFunctions::Draw (DisplayBase & display, const Point2D & p, Normalisation C = Normalisation(), float size = 2, CornerShape shape = PLUS)
References CROSS, VW::DisplayBase::DrawLine(), VW::Point2D::GetX(), VW::Point2D::GetY(), PLUS, SQUARE, and VW::Normalisation::UnNormalise().
void VW::DrawFunctions::Draw (DisplayBase & display, const ImageHSV< unsigned char > & image)
void VW::DrawFunctions::Draw (DisplayBase & display, const ImageRGB< unsigned char > & image)
References VW::PixelRGB< Type >::b, VW::PixelRGB< Type >::g, VW::DisplayBase::GetHeight(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetHeight(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetPixel(), VW::DisplayBase::GetWidth(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetWidth(), VW::PixelRGB< Type >::r, and VW::DisplayBase::SetPixel().
void VW::DrawFunctions::Draw (DisplayBase & display, const ImageMono< unsigned char > & image)
References VW::DisplayBase::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetPixel(), VW::DisplayBase::GetWidth(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), VW::DisplayBase::SetPixel(), and VW::PixelMono< Type >::y.
Referenced by Draw().
void VW::DrawFunctions::DrawCovariance (DisplayBase & display, const Point2D & location, const VNL::MatrixFixed< 2, 2, double > & covar)
References VW::DisplayBase::DrawEllipse(), VW::Point2D::GetX(), VW::Point2D::GetY(), and std::sqrt().
void VW::DrawFunctions::DrawRectangleOutline (DisplayBase & display, unsigned int x0, unsigned int y0, unsigned int x1, unsigned int y1, unsigned int linewidth = 1)
References VW::DisplayBase::DrawLine().