VW: VW::FMPlanarCompute Namespace Reference
VW::FMPlanarCompute Namespace Reference
Classes
class LeastSquaresFunctionPoints
A small class that knows how to be minimised.
Functions
VNL::Vector< double > GenerateParameterVectorHZ (const VW::FMatrixPlanar &fmatrix)
Parameterises F as [e2]x [ls]x [e1]x (see HZ 8.4 p233).
VW::FMatrixPlanar ReconstructTransformHZ (const VNL::Vector< double > &x)
VNL::Vector< double > GenerateParameterVectorVLJK (const VW::FMatrixPlanar &fmatrix)
Parameterises F as antisymmetric part and symmetric part, but symmetric part is parameterised as fixed lines lh and ls as per Vieville and Lingrand (ECCV96).
VW::FMatrixPlanar ReconstructTransformVLJK (const VNL::Vector< double > &x)
VNL::Vector< double > GenerateParameterVectorHZJK (const VW::FMatrixPlanar &fmatrix)
Parameterises F as fixed lines lh and ls, from the symmetric part of F, and two two-vector [a1 b1]' and [a2 b2]' which define the position of the epipoles e1 and e2 on lh (the horizon line).
VW::FMatrixPlanar ReconstructTransformHZJK (const VNL::Vector< double > &x)
Function Documentation
VNL::Vector<double> VW::FMPlanarCompute::GenerateParameterVectorHZ (const VW::FMatrixPlanar & fmatrix)
Parameterises F as [e2]x [ls]x [e1]x (see HZ 8.4 p233).
Basically copied from oxl/mvl/FMPlanarNonLinFun.cxx
References VW::FMatrix::AsMatrix(), VNL::Cross3D(), VNL::Matrix< T >::FrobeniusNorm(), VW::FMatrix::GetEpipoles(), VW::Point2D::GetX(), VW::Point2D::GetY(), VNL::Vector< T >::Magnitude(), VNL::VectorFixedRef< n, T >::Normalize(), VNL::Sgn(), std::sqrt(), and VNL::Matrix< T >::Transpose().
Referenced by VW::FMPlanarComputeNonLinear::Compute().
VNL::Vector<double> VW::FMPlanarCompute::GenerateParameterVectorHZJK (const VW::FMatrixPlanar & fmatrix)
Parameterises F as fixed lines lh and ls, from the symmetric part of F, and two two-vector [a1 b1]' and [a2 b2]' which define the position of the epipoles e1 and e2 on lh (the horizon line).
So F = [e2]x [ls]x [e1]x as per HZ, but e1 = a1 xs + b1 xp, and e2 = a2 xs + b2 xp, where xs = lh x ls, and xp = xs x lh (ie xp is a point on lh perpendicular to xs, the intersection of lh and ls) We have from this that a1|2 = xs' e1|2, b1|2 = xp' e1|2.
References VW::FMatrix::AsMatrix(), VNL::Cross3D(), VNL::DotProduct(), VNL::Matrix< T >::FrobeniusNorm(), VNL::Vector< T >::Magnitude(), VNL::VectorFixedRef< n, T >::Normalize(), VNL::Vector< T >::Normalize(), VNL::SVD< T >::Nullvector(), VNL::Sgn(), std::sqrt(), and VNL::Matrix< T >::Transpose().
Referenced by VW::FMPlanarComputeNonLinear::Compute().
VNL::Vector<double> VW::FMPlanarCompute::GenerateParameterVectorVLJK (const VW::FMatrixPlanar & fmatrix)
Parameterises F as antisymmetric part and symmetric part, but symmetric part is parameterised as fixed lines lh and ls as per Vieville and Lingrand (ECCV96).
So F = [fa]x + (lh.ls' + ls.lh')
ERROR: It turns out this is an under-parameterisation, as fa is a point on lh and therefore only constitues one parameter, not two.
References VW::FMatrix::AsMatrix(), VNL::Cross3D(), VNL::Matrix< T >::FrobeniusNorm(), VW::FMatrix::GetEpipoles(), VNL::Vector< T >::Magnitude(), VNL::Vector< T >::Normalize(), VNL::VectorFixedRef< n, T >::Normalize(), VNL::SVD< T >::Nullvector(), VNL::Sgn(), std::sqrt(), and VNL::Matrix< T >::Transpose().
Referenced by VW::FMPlanarComputeNonLinear::Compute().
VW::FMatrixPlanar VW::FMPlanarCompute::ReconstructTransformHZ (const VNL::Vector< double > & x)
References VNL::Vector< T >::DataBlock(), VNL::Matrix< T >::FrobeniusNorm(), VNL::Vector< T >::size(), and v.
Referenced by VW::FMPlanarComputeNonLinear::Compute(), and VW::FMPlanarCompute::LeastSquaresFunctionPoints::F().
VW::FMatrixPlanar VW::FMPlanarCompute::ReconstructTransformHZJK (const VNL::Vector< double > & x)
References VNL::Cross3D(), VNL::Vector< T >::DataBlock(), VNL::Matrix< T >::FrobeniusNorm(), VNL::VectorFixedRef< n, T >::Normalize(), VNL::Vector< T >::size(), and v.
Referenced by VW::FMPlanarComputeNonLinear::Compute(), and VW::FMPlanarCompute::LeastSquaresFunctionPoints::F().
VW::FMatrixPlanar VW::FMPlanarCompute::ReconstructTransformVLJK (const VNL::Vector< double > & x)
References VNL::Vector< T >::DataBlock(), VNL::Matrix< T >::FrobeniusNorm(), VNL::Vector< T >::Normalize(), VNL::OuterProduct(), VNL::Vector< T >::size(), and v.
Referenced by VW::FMPlanarComputeNonLinear::Compute(), and VW::FMPlanarCompute::LeastSquaresFunctionPoints::F().