VW: utils.h File Reference
TI/TransputerCode/utils.h File Reference
Functions
df_type atan2_c (df_type y, df_type x)
df_type div_c (df_type denom, df_type num)
void ca (int num,...)
void prob (void)
double sqr (double t)
df_type sqrf (df_type t)
df_type csqrtf (df_type t)
int tround (df_type a)
df_type hyppot (df_type a, df_type b)
void print_var (void)
df_type add (df_type a1, df_type a2)
df_type sub (df_type a1, df_type a2)
df_type fix (df_type tmp_f, df_type tmp_s)
df_type fix_gam (df_type tmp_ff, df_type tmp_ss)
Function Documentation
df_type add (df_type a1, df_type a2)
Referenced by VW::InterfaceGTKWidget::CreateButtonBar(), VW::YorickGTKWidget::InitForm(), VW::SequencerMovieChannelGTKWidget::InitForm(), VW::SequencerMovieGTKWidget::InitForm(), VW::SequencerFirewireGTKWidget::InitForm(), VW::SequencerFileChannelGTKWidget::InitForm(), VW::SequencerFileGTKWidget::InitForm(), VW::PlesseyParamsGTKWidget::InitForm(), VW::FirewireCameraGTKWidget::InitForm(), VW::ClassifierUVGTKWidget::InitForm(), and VW::ThreeDToolGTKGLWidget::ThreeDToolGTKGLWidget().
df_type atan2_c (df_type y, df_type x)
void ca (int num, ...)
Referenced by VW::DrawFunctions::Draw().
df_type csqrtf (df_type t)
df_type div_c (df_type denom, df_type num)
df_type fix (df_type tmp_f, df_type tmp_s)
df_type fix_gam (df_type tmp_ff, df_type tmp_ss)
df_type hyppot (df_type a, df_type b)
void print_var (void)
void prob (void)
Referenced by VW::Line2DCompute::CalcErrorProbabilityPoint(), and VW::PixelList2ClassifierUVMatrix().
double sqr (double t)
df_type sqrf (df_type t)
df_type sub (df_type a1, df_type a2)
Referenced by VNL::Adjugate().
int tround (df_type a)