VW: VNL::Rational Class Reference
VNL::Rational Class Reference
Infinite precision rational numbers.
#include <rational.h>
Public Member Functions
Rational (long num=0L, long den=1L)
Creates a rational with given numerator and denominator.
Rational (int num, int den=1)
Rational (unsigned int num, unsigned int den=1)
Rational (double d)
Creates a rational from a double.
Rational (Rational const &from)
~Rational ()
void Set (long num, long den)
long Numerator () const
Return the numerator of the (simplified) rational number representation.
long Denominator () const
Return the denominator of the (simplified) rational number representation.
Rational & operator= (Rational const &rhs)
Copies the contents and state of rhs rational over to the lhs.
bool operator== (Rational const &rhs) const
Returns true if the two rationals have the same representation.
bool operator!= (Rational const &rhs) const
bool operator== (long rhs) const
bool operator!= (long rhs) const
bool operator== (int rhs) const
bool operator!= (int rhs) const
Rational operator- () const
Unary minus - returns the negation of the current rational.
Rational operator+ () const
Unary plus - returns the current rational.
bool operator! () const
Unary not - returns true if rational is equal to zero.
Rational Abs () const
Returns the absolute value of the current rational.
Rational & Invert ()
Replaces rational with 1/rational and returns it.
Rational & operator+= (Rational const &r)
Plus/assign: replace lhs by lhs + rhs.
Rational & operator+= (long r)
Rational & operator-= (Rational const &r)
Minus/assign: replace lhs by lhs - rhs.
Rational & operator-= (long r)
Rational & operator*= (Rational const &r)
Multiply/assign: replace lhs by lhs * rhs.
Rational & operator*= (long r)
Rational & operator/= (Rational const &r)
Divide/assign: replace lhs by lhs / rhs.
Rational & operator/= (long r)
Rational & operator%= (Rational const &r)
Modulus/assign: replace lhs by lhs % rhs.
Rational & operator%= (long r)
Rational & operator++ ()
Pre-increment (++r). No-op when +-Inf.
Rational & operator-- ()
Pre-decrement (--r). No-op when +-Inf.
Rational operator++ (int)
Post-increment (r++). No-op when +-Inf.
Rational operator-- (int)
Post-decrement (r--). No-op when +-Inf.
bool operator< (Rational const &rhs) const
bool operator> (Rational const &r) const
bool operator<= (Rational const &r) const
bool operator>= (Rational const &r) const
bool operator< (long r) const
bool operator> (long r) const
bool operator<= (long r) const
bool operator>= (long r) const
bool operator< (int r) const
bool operator> (int r) const
bool operator<= (int r) const
bool operator>= (int r) const
bool operator< (double r) const
bool operator> (double r) const
bool operator<= (double r) const
bool operator>= (double r) const
long Truncate () const
Converts rational value to integer by truncating towards zero.
long Floor () const
Converts rational value to integer by truncating towards negative infinity.
long Ceil () const
Converts rational value to integer by truncating towards positive infinity.
long Round () const
Rounds rational to nearest integer.
operator short ()
operator int ()
operator long () const
operator long ()
operator float () const
operator float ()
operator double () const
operator double ()
Static Public Member Functions
static long GCD (long l1, long l2)
Calculate greatest common divisor of two integers.
Detailed Description
Infinite precision rational numbers.
The vnl_rational class provides infinite precision rational numbers and arithmetic, using the built-in type long, for the numerator and denominator. Implicit conversion to the system defined types short, int, long, float, and double is supported by overloaded operator member functions. Although the rational class makes judicous use of inline functions and deals only with integral values, the user is warned that the rational integer arithmetic class is still considerably slower than the built-in integer data types. If the range of values anticipated will fit into a built-in type, use that instead.
In addition to the original COOL Rational class, vnl_rational is able to represent plus and minus infinity. An other interesting addition is the possibility to construct a rational from a double. This allows for lossless conversion from e.g. double 1.0/3.0 to the rational number 1/3, hence no more rounding errors. This is implemented with continued fraction approximations.
Constructor & Destructor Documentation
VNL::Rational::Rational (long num = 0L, long den = 1L) [inline]
Creates a rational with given numerator and denominator.
Default constructor gives 0. Also serves as automatic cast from long to Rational. The only input which is not allowed is (0,0); the denominator is allowed to be 0, to represent +Inf or -Inf.
Referenced by Abs(), and operator-().
VNL::Rational::Rational (int num, int den = 1) [inline]
VNL::Rational::Rational (unsigned int num, unsigned int den = 1) [inline]
VNL::Rational::Rational (double d) [explicit]
Creates a rational from a double.
This is done by computing the continued fraction approximation for d. Note that this is explicitly *not* an automatic type conversion.
VNL::Rational::Rational (Rational const & from) [inline]
VNL::Rational::~Rational () [inline]
Member Function Documentation
Rational VNL::Rational::Abs () const [inline]
Returns the absolute value of the current rational.
References Rational().
Referenced by std::abs().
long VNL::Rational::Ceil () const [inline]
Converts rational value to integer by truncating towards positive infinity.
References VNL::Truncate().
Referenced by VNL::Ceil().
long VNL::Rational::Denominator () const [inline]
Return the denominator of the (simplified) rational number representation.
Referenced by VNL::IsFinite(), operator%=(), operator*=(), operator+=(), operator-=(), operator/=(), operator<(), VNL::operator<<(), operator=(), and operator==().
long VNL::Rational::Floor () const [inline]
Converts rational value to integer by truncating towards negative infinity.
References VNL::Truncate().
Referenced by VNL::Floor().
static long VNL::Rational::GCD (long l1, long l2) [inline, static]
Calculate greatest common divisor of two integers.
Used to simplify rational number.
Referenced by operator%=(), operator+=(), and operator-=().
Rational& VNL::Rational::Invert () [inline]
Replaces rational with 1/rational and returns it.
Inverting 0 gives +Inf, inverting +-Inf gives 0.
long VNL::Rational::Numerator () const [inline]
Return the numerator of the (simplified) rational number representation.
Referenced by operator%=(), operator*=(), operator+=(), operator-=(), operator/=(), operator<(), VNL::operator<<(), operator=(), and operator==().
VNL::Rational::operator double () [inline]
VNL::Rational::operator double () const [inline]
VNL::Rational::operator float () [inline]
VNL::Rational::operator float () const [inline]
VNL::Rational::operator int () [inline]
References VNL::Truncate().
VNL::Rational::operator long () [inline]
References VNL::Truncate().
VNL::Rational::operator long () const [inline]
References VNL::Truncate().
VNL::Rational::operator short () [inline]
References VNL::Truncate().
bool VNL::Rational::operator! () const [inline]
Unary not - returns true if rational is equal to zero.
bool VNL::Rational::operator!= (int rhs) const [inline]
References operator==().
bool VNL::Rational::operator!= (long rhs) const [inline]
References operator==().
bool VNL::Rational::operator!= (Rational const & rhs) const [inline]
References operator==().
Rational& VNL::Rational::operator%= (long r) [inline]
References VNL::Normalize().
Rational& VNL::Rational::operator%= (Rational const & r) [inline]
Modulus/assign: replace lhs by lhs % rhs.
Note that r % Inf is r, and that r % 0 and Inf % r are undefined.
References c, Denominator(), GCD(), VNL::Normalize(), and Numerator().
Rational& VNL::Rational::operator*= (long r) [inline]
References VNL::Normalize().
Rational& VNL::Rational::operator*= (Rational const & r) [inline]
Multiply/assign: replace lhs by lhs * rhs.
Note that 0 * Inf and Inf * 0 are undefined.
References Denominator(), VNL::Normalize(), and Numerator().
Rational VNL::Rational::operator+ () const [inline]
Unary plus - returns the current rational.
Rational VNL::Rational::operator++ (int) [inline]
Post-increment (r++). No-op when +-Inf.
Rational& VNL::Rational::operator++ () [inline]
Pre-increment (++r). No-op when +-Inf.
Rational& VNL::Rational::operator+= (long r) [inline]
Rational& VNL::Rational::operator+= (Rational const & r) [inline]
Plus/assign: replace lhs by lhs + rhs.
Note that +Inf + -Inf and -Inf + +Inf are undefined.
References c, Denominator(), GCD(), and Numerator().
Rational VNL::Rational::operator- () const [inline]
Unary minus - returns the negation of the current rational.
References Rational().
Rational VNL::Rational::operator-- (int) [inline]
Post-decrement (r--). No-op when +-Inf.
Rational& VNL::Rational::operator-- () [inline]
Pre-decrement (--r). No-op when +-Inf.
Rational& VNL::Rational::operator-= (long r) [inline]
Rational& VNL::Rational::operator-= (Rational const & r) [inline]
Minus/assign: replace lhs by lhs - rhs.
Note that +Inf - +Inf and -Inf - -Inf are undefined.
References c, Denominator(), GCD(), and Numerator().
Rational& VNL::Rational::operator/= (long r) [inline]
References VNL::Normalize().
Rational& VNL::Rational::operator/= (Rational const & r) [inline]
Divide/assign: replace lhs by lhs / rhs.
Note that 0 / 0 and Inf / Inf are undefined.
References Denominator(), VNL::Normalize(), and Numerator().
bool VNL::Rational::operator< (double r) const [inline]
bool VNL::Rational::operator< (int r) const [inline]
bool VNL::Rational::operator< (long r) const [inline]
bool VNL::Rational::operator< (Rational const & rhs) const [inline]
References Denominator(), and Numerator().
bool VNL::Rational::operator<= (double r) const [inline]
References VNL::operator>().
bool VNL::Rational::operator<= (int r) const [inline]
References VNL::operator>().
bool VNL::Rational::operator<= (long r) const [inline]
References VNL::operator>().
bool VNL::Rational::operator<= (Rational const & r) const [inline]
References VNL::operator>().
Rational& VNL::Rational::operator= (Rational const & rhs) [inline]
Copies the contents and state of rhs rational over to the lhs.
References Denominator(), and Numerator().
bool VNL::Rational::operator== (int rhs) const [inline]
bool VNL::Rational::operator== (long rhs) const [inline]
bool VNL::Rational::operator== (Rational const & rhs) const [inline]
Returns true if the two rationals have the same representation.
References Denominator(), and Numerator().
Referenced by operator!=().
bool VNL::Rational::operator> (double r) const [inline]
bool VNL::Rational::operator> (int r) const [inline]
bool VNL::Rational::operator> (long r) const [inline]
bool VNL::Rational::operator> (Rational const & r) const [inline]
bool VNL::Rational::operator>= (double r) const [inline]
References VNL::operator<().
bool VNL::Rational::operator>= (int r) const [inline]
References VNL::operator<().
bool VNL::Rational::operator>= (long r) const [inline]
References VNL::operator<().
bool VNL::Rational::operator>= (Rational const & r) const [inline]
References VNL::operator<().
long VNL::Rational::Round () const [inline]
Rounds rational to nearest integer.
References VNL::Truncate().
Referenced by VNL::Round().
void VNL::Rational::Set (long num, long den) [inline]
Referenced by VNL::operator>>().
long VNL::Rational::Truncate () const [inline]
Converts rational value to integer by truncating towards zero.
Referenced by VNL::Truncate().
The documentation for this class was generated from the following files:
rational.h
rational.cpp