VW: vnl_alloc Class Reference
vnl_alloc Class Reference
#include <alloc.h>
Classes
class lock
union obj
Public Types
typedef char value_type
Static Public Member Functions
static void * allocate (size_t n)
static void deallocate (void *p, size_t n)
static void * reallocate (void *p, size_t old_sz, size_t new_sz)
Friends
union obj
class lock
Member Typedef Documentation
typedef char vnl_alloc::value_type
Member Function Documentation
static void* vnl_alloc::allocate (size_t n) [inline, static]
References obj, and VNL_ALLOC_MAX_BYTES.
Referenced by reallocate(), and vnl_c_vector_alloc().
static void vnl_alloc::deallocate (void * p, size_t n) [inline, static]
References obj, and VNL_ALLOC_MAX_BYTES.
Referenced by reallocate(), and vnl_c_vector_dealloc().
void * vnl_alloc::reallocate (void * p, size_t old_sz, size_t new_sz) [static]
References allocate(), deallocate(), and VNL_ALLOC_MAX_BYTES.
Friends And Related Function Documentation
friend class lock [friend]
friend union obj [friend]
Referenced by allocate(), and deallocate().
The documentation for this class was generated from the following files:
alloc.h
alloc.cpp