VW: VW::Trajectory< Feature > Class Template Reference
VW::Trajectory< Feature > Class Template Reference
#include <trajectorymap.h>
Public Member Functions
Trajectory (unsigned int max_size=5, unsigned int num_priors=0)
Trajectory (const Feature &start_element, const double propagation_score=0, const std::vector< double > &priors=std::vector< double >(), unsigned int max_size=5)
Trajectory (const Trajectory< Feature > &t)
~Trajectory ()
Trajectory< Feature > & operator= (const Trajectory< Feature > &t)
void Add (const Feature &new_feature, const double propagation_score=0, const std::vector< double > &priors=std::vector< double >())
const Feature & GetOldestFeature (void) const
const Feature & GetNewestFeature (void) const
const Feature & GetOldFeature (const unsigned int age) const
double GetPropagationScore (const unsigned int age=0) const
void SetNumberOfPriors (const unsigned int num_priors)
double GetPrior (const unsigned int age=0, const unsigned int which_prior=0) const
void SetPrior (const unsigned int age, const unsigned int which_prior, const double new_score)
unsigned int Age () const
The total number of frames for which this trajectory has existed.
unsigned int size () const
The total number of frames stored.
void clear ()
Clear this trajectory.
std::string print () const
template<class Feature>
class VW::Trajectory< Feature >
Constructor & Destructor Documentation
template<class Feature > VW::Trajectory< Feature >::Trajectory (unsigned int max_size = 5, unsigned int num_priors = 0) [inline]
template<class Feature > VW::Trajectory< Feature >::Trajectory (const Feature & start_element, const double propagation_score = 0, const std::vector< double > & priors = std::vector<double>(), unsigned int max_size = 5) [inline]
template<class Feature > VW::Trajectory< Feature >::Trajectory (const Trajectory< Feature > & t) [inline]
template<class Feature > VW::Trajectory< Feature >::~Trajectory () [inline]
Member Function Documentation
template<class Feature > void VW::Trajectory< Feature >::Add (const Feature & new_feature, const double propagation_score = 0, const std::vector< double > & priors = std::vector<double>()) [inline]
template<class Feature > unsigned int VW::Trajectory< Feature >::Age () const [inline]
The total number of frames for which this trajectory has existed.
Note that this may be longer than the trajectory length if (age>MaxSize).
template<class Feature > void VW::Trajectory< Feature >::clear () [inline]
Clear this trajectory.
The buffer is emptied and age reset to zero.
template<class Feature > const Feature & VW::Trajectory< Feature >::GetNewestFeature (void) const [inline]
Referenced by VW::DrawFunctions::Draw().
template<class Feature > const Feature & VW::Trajectory< Feature >::GetOldestFeature (void) const [inline]
Referenced by VW::DrawFunctions::Draw().
template<class Feature > const Feature & VW::Trajectory< Feature >::GetOldFeature (const unsigned int age) const [inline]
Referenced by VW::DrawFunctions::Draw().
template<class Feature > double VW::Trajectory< Feature >::GetPrior (const unsigned int age = 0, const unsigned int which_prior = 0) const [inline]
template<class Feature > double VW::Trajectory< Feature >::GetPropagationScore (const unsigned int age = 0) const [inline]
template<class Feature > Trajectory< Feature > & VW::Trajectory< Feature >::operator= (const Trajectory< Feature > & t) [inline]
template<class Feature > std::string VW::Trajectory< Feature >::print () const [inline]
template<class Feature > void VW::Trajectory< Feature >::SetNumberOfPriors (const unsigned int num_priors) [inline]
template<class Feature > void VW::Trajectory< Feature >::SetPrior (const unsigned int age, const unsigned int which_prior, const double new_score) [inline]
template<class Feature > unsigned int VW::Trajectory< Feature >::size () const [inline]
The total number of frames stored.
Note that this may be less than the age if (age>MaxSize).
Referenced by VW::DrawFunctions::Draw().
The documentation for this class was generated from the following file:
trajectorymap.h