VW: VW::Line2D Class Reference
VW::Line2D Class Reference
[GeometricObjects]
Representation of a 2D (infinite) line.
#include <line2d.h>
Public Types
typedef double element_type
Type defs for iterators.
typedef double * iterator
Type defs for iterators.
typedef doubleconst * const_iterator
Const iterator type.
typedef CVector< double >::abs_t abs_t
Public Member Functions
Line2D ()
Line2D (double a, double b, double c)
Line2D (const VNL::VectorFixed< 3, double > &line)
Line2D (const VNL::VectorFixed< 3, float > &line)
Line2D (const VNL::Vector< double > &line)
Line2D (const VNL::Vector< float > &line)
virtual ~Line2D ()
Line2D & operator= (const Line2D &p)
Copy operator.
void Set (double a, double b, double c)
void Set (const VNL::Vector< double > &line)
double GetA () const
double GetB () const
double GetC () const
double LookupY (const double x) const
Find the Y value corresponding to the given X value.
double LookupX (const double y) const
Find the X value corresponding to the given Y value.
VW::Vector2D GetDirection () const
The direction of the line (unit vector).
VW::Vector2D GetPerpendicular () const
The direction perpendicular to the line (unit vector).
double GetDistance (const double x, const double y) const
Get the distance of a point from this line.
double GetDistance (const Point2D &p) const
Get the distance of a point from this line.
double GetDistance2 (const double x, const double y) const
Get the squared distance of a point from this line.
double GetDistance2 (const Point2D &p) const
Get the squared distance of a point from this line.
LineSeg2D TruncateX (const double x0, const double x1) const
Truncate using bounds on X (result is a line-segment).
LineSeg2D TruncateY (const double y0, const double y1) const
Truncate using bounds on Y (result is a line-segment).
LineSeg2D Truncate (const double x0, const double y0, const double x1, const double y1) const
Truncate to lie within a rectangle (x0,y0)->(x1,y1) (eg for displaying).
virtual bool WriteASCII (std::ostream &stream) const
virtual bool WriteXML (std::ostream &stream, const std::string &name="") const
virtual bool WriteBinary (std::ostream &stream) const
virtual bool ReadASCII (std::istream &stream)
Read from text stream.
virtual bool ReadXML (std::istream &stream, const std::string &name="")
virtual bool ReadBinary (std::istream &stream)
VectorFixed< n, double > Apply (double(*f)(double))
VectorFixed< n, double > Apply (double(*f)(doubleconst &))
Vector< double > Apply (double(*f)(double)) const
Applies function to elements.
Vector< double > Apply (double(*f)(doubleconst &)) const
Applies function to elements.
VectorFixed< n, double > operator- () const
Unary minus operator.
VectorFixed< n, double > operator- (doubleconst t) const
VectorFixed< n, double > operator- (Vector< double > const &rhs) const
Vector< double > operator- (Vector< double > const &v) const
VectorFixed< n, double > operator+ (doubleconst t) const
VectorFixed< n, double > operator+ (Vector< double > const &rhs) const
Vector< double > operator+ () const
Unary plus operator.
Vector< double > operator+ (Vector< double > const &v) const
VectorFixed< n, double > operator* (doubleconst t) const
Vector< double > operator* (Matrix< double > const &M) const
VectorFixed< n, double > operator/ (doubleconst t) const
MatrixFixed< 1, n, double > AsRow ()
Convert a vector into a 1-by-size matrix (i.e.
MatrixFixed< n, 1, double > AsColumn ()
Convert a vector into a 1-by-size matrix (i.e.
VectorFixedRef< n, double > & operator+= (doubleconst t)
Add scalar value to all elements.
VectorFixedRef< n, double > & operator+= (Vector< double > const &rhs)
Vector< double > & operator+= (Vector< double > const &rhs)
Add rhs to this and return *this.
VectorFixedRef< n, double > & operator-= (doubleconst t)
Subtract scalar value from all elements.
VectorFixedRef< n, double > & operator-= (Vector< double > const &rhs)
Vector< double > & operator-= (Vector< double > const &rhs)
Subtract rhs from this and return *this.
VectorFixedRef< n, double > & operator*= (doubleconst t)
Multiply all elements by scalar.
Vector< double > & operator*= (Matrix< double > const &)
*this = (*this)*M where M is a suitable matrix.
VectorFixedRef< n, double > & operator/= (doubleconst t)
Divide all elements by scalar.
VectorFixedRef< n, double > & Update (Vector< double > const &v, unsigned int start=0)
Vector< double > & Update (Vector< double > const &, unsigned int start=0)
Replaces elements with index begining at start, by values of v. O(n).
VectorFixedRef< n, double > & Normalize ()
Normalise by dividing through by the magnitude.
Vector< double > & PreMultiply (Matrix< double > const &)
*this = M*(*this) where M is a suitable matrix.
Vector< double > & PostMultiply (Matrix< double > const &)
*this = (*this)*M where M is a suitable matrix.
unsigned size () const
Return the length, number of elements, dimension of this vector.
unsigned Size () const
Return the length, number of elements, dimension of this vector.
void Put (unsigned int i, doubleconst &)
Put value at given position in vector.
double Get (unsigned int i) const
Get value at element i.
void Fill (doubleconst &v)
Set all values to v.
void CopyIn (doubleconst *ptr)
Sets elements to ptr[i].
void CopyOut (double *) const
Copy elements to ptr[i].
void Set (doubleconst *ptr)
Sets elements to ptr[i].
double & operator() (unsigned int i)
Return reference to the element at specified index.
doubleconst & operator() (unsigned int i) const
Return reference to the element at specified index. No range checking.
double & operator[] (unsigned int i)
Return reference to the element at specified index. No range checking.
doubleconst & operator[] (unsigned int i) const
Return reference to the element at specified index. No range checking.
doubleconst * DataBlock () const
Access the contiguous block storing the elements in the vector. O(1).
double * DataBlock ()
Access the contiguous block storing the elements in the vector. O(1).
iterator begin ()
Iterator pointing to start of data.
const_iterator begin () const
Iterator pointing to start of data.
iterator end ()
Iterator pointing to element beyond end of data.
const_iterator end () const
Iterator pointing to element beyond end of data.
Vector< double > Extract (unsigned int len, unsigned int start=0) const
Returns a subvector specified by the start index and length. O(n).
abs_t SquaredMagnitude () const
Return sum of squares of elements.
abs_t Magnitude () const
Return magnitude (length) of vector.
abs_t OneNorm () const
Return sum of absolute values of the elements.
abs_t TwoNorm () const
Return sqrt of sum of squares of values of elements.
abs_t InfNorm () const
Return largest absolute element value.
abs_t RMS () const
Root Mean Squares of values.
double MinValue () const
Smallest value.
double MaxValue () const
Largest value.
double Mean () const
Mean of values in vector.
double Sum () const
Sum of values in a vector.
void Flip ()
Reverse the order of the elements.
void Swap (Vector< double > &that)
Set this to that and that to this.
double & x () const
Return first element of vector.
double & y () const
Return second element of vector.
double & z () const
Return third element of vector.
double & t () const
Return fourth element of vector.
void assert_size (unsigned sz) const
Check that size()==sz if not, abort();.
void assert_finite () const
Check that this is finite if not, abort();.
bool IsFinite () const
Return true if its finite.
bool IsZero () const
Return true iff all the entries are zero.
bool IsEmpty () const
Return true iff the size is zero.
bool operator_eq (Vector< double > const &v) const
Return true if *this == v.
bool operator== (Vector< double > const &that) const
Equality test.
bool operator!= (Vector< double > const &that) const
Inequality test.
bool Resize (unsigned n)
Resize to n elements.
void Clear ()
Make the vector as if it had been default-constructed.
Static Public Member Functions
static Vector< double > Read (std::istream &s)
Read from text stream.
Protected Member Functions
void assert_size_internal (unsigned sz) const
void assert_finite_internal () const
void destroy ()
Static Protected Member Functions
static void inline_function_tickler ()
Protected Attributes
unsigned num_elmts
double * data
Friends
VectorFixed< n, double > ElementProduct (VectorFixedRef< n, double > const &, VectorFixedRef< n, double > const &)
VectorFixed< n, double > ElementQuotient (VectorFixedRef< n, double > const &, VectorFixedRef< n, double > const &)
class Matrix< T >
Detailed Description
Representation of a 2D (infinite) line.
Author:
ID Reid
Date:
02/08/02 Note that this definition of a line is infinite - that is, no end-points are stored. For a finite line, see VW::LineSeg2D. The data is stored as a 3D vector [a b c] defining the line ax + by + c = 0.
Computation routines are conatined in VW::Line2DCompute and some other operations in operations.h
Member Typedef Documentation
typedef CVector<double >::abs_t VNL::Vector< double >::abs_t [inherited]
typedef double const* VNL::Vector< double >::const_iterator [inherited]
Const iterator type.
typedef double VNL::Vector< double >::element_type [inherited]
Type defs for iterators.
typedef double * VNL::Vector< double >::iterator [inherited]
Type defs for iterators.
Constructor & Destructor Documentation
VW::Line2D::Line2D () [inline]
VW::Line2D::Line2D (double a, double b, double c) [inline]
VW::Line2D::Line2D (const VNL::VectorFixed< 3, double > & line) [inline]
VW::Line2D::Line2D (const VNL::VectorFixed< 3, float > & line) [inline]
References VNL::Vector< double >::data.
VW::Line2D::Line2D (const VNL::Vector< double > & line) [inline]
VW::Line2D::Line2D (const VNL::Vector< float > & line) [inline]
References VNL::Vector< double >::data, and VNL::Vector< T >::size().
virtual VW::Line2D::~Line2D () [inline, virtual]
Member Function Documentation
Vector<double > VNL::Vector< double >::Apply (double (*)(double const &) f) const [inherited]
Applies function to elements.
Vector<double > VNL::Vector< double >::Apply (double (*)(double) f) const [inherited]
Applies function to elements.
Return the vector made by applying "f" to each element.
VectorFixed<n,double > VNL::VectorFixed< n, double >::Apply (double (*)(double const &) f) [inline, inherited]
VectorFixed<n,double > VNL::VectorFixed< n, double >::Apply (double (*)(double) f) [inline, inherited]
MatrixFixed<n,1,double > VNL::VectorFixed< n, double >::AsColumn () [inline, inherited]
Convert a vector into a 1-by-size matrix (i.e.
a column vector).
MatrixFixed<1,n,double > VNL::VectorFixed< n, double >::AsRow () [inline, inherited]
Convert a vector into a 1-by-size matrix (i.e.
a row vector).
void VNL::Vector< double >::assert_finite () const [inline, inherited]
Check that this is finite if not, abort();.
This function does or tests nothing if NDEBUG is defined
void VNL::Vector< double >::assert_finite_internal () const [protected, inherited]
void VNL::Vector< double >::assert_size (unsigned sz) const [inline, inherited]
Check that size()==sz if not, abort();.
This function does or tests nothing if NDEBUG is defined
void VNL::Vector< double >::assert_size_internal (unsigned sz) const [protected, inherited]
const_iterator VNL::Vector< double >::begin () const [inline, inherited]
Iterator pointing to start of data.
iterator VNL::Vector< double >::begin () [inline, inherited]
Iterator pointing to start of data.
void VNL::Vector< double >::Clear () [inherited]
Make the vector as if it had been default-constructed.
void VNL::Vector< double >::CopyIn (double const * ptr) [inherited]
Sets elements to ptr[i].
Sets elements of a vector to those in an array. O(n).
Note: ptr[i] must be valid for i=0..size()-1
void VNL::Vector< double >::CopyOut (double *) const [inherited]
Copy elements to ptr[i].
Sets elements of an array to those in vector. O(n).
Note: ptr[i] must be valid for i=0..size()-1
double * VNL::Vector< double >::DataBlock () [inline, inherited]
Access the contiguous block storing the elements in the vector. O(1).
data_block()[0] is the first element of the vector
double const* VNL::Vector< double >::DataBlock () const [inline, inherited]
Access the contiguous block storing the elements in the vector. O(1).
data_block()[0] is the first element of the vector
void VNL::Vector< double >::destroy () [protected, inherited]
Frees up the array inside vector. O(1).
const_iterator VNL::Vector< double >::end () const [inline, inherited]
Iterator pointing to element beyond end of data.
iterator VNL::Vector< double >::end () [inline, inherited]
Iterator pointing to element beyond end of data.
Vector<double > VNL::Vector< double >::Extract (unsigned int len, unsigned int start = 0) const [inherited]
Returns a subvector specified by the start index and length. O(n).
void VNL::Vector< double >::Fill (double const & v) [inherited]
Set all values to v.
Sets all elements of a vector to a specified fill value. O(n).
void VNL::Vector< double >::Flip () [inherited]
Reverse the order of the elements.
Element i swaps with element size()-1-i
double VNL::Vector< double >::Get (unsigned int i) const [inline, inherited]
Get value at element i.
Gets the element at specified index and return its value. O(1).
Range check is performed.
double VW::Line2D::GetA () const [inline]
References VNL::Vector< double >::data.
Referenced by VW::Intersect().
double VW::Line2D::GetB () const [inline]
References VNL::Vector< double >::data.
Referenced by VW::Intersect().
double VW::Line2D::GetC () const [inline]
References VNL::Vector< double >::data.
Referenced by VW::Intersect().
VW::Vector2D VW::Line2D::GetDirection () const
The direction of the line (unit vector).
References VNL::Vector< double >::data, and std::sqrt().
double VW::Line2D::GetDistance (const Point2D & p) const
Get the distance of a point from this line.
References GetDistance(), VW::Point2D::GetX(), and VW::Point2D::GetY().
double VW::Line2D::GetDistance (const double x, const double y) const
Get the distance of a point from this line.
References VNL::Vector< double >::data, and std::sqrt().
Referenced by VW::Line2DCompute::CalcErrorProbabilityPoint(), VW::GetDistance(), and GetDistance().
double VW::Line2D::GetDistance2 (const Point2D & p) const
Get the squared distance of a point from this line.
References GetDistance2(), VW::Point2D::GetX(), and VW::Point2D::GetY().
double VW::Line2D::GetDistance2 (const double x, const double y) const
Get the squared distance of a point from this line.
References VNL::Vector< double >::data.
Referenced by VW::FMatrixAffineComputePreemptive::Compute(), VW::EssentialMatrixComputePreemptive::Compute(), and GetDistance2().
VW::Vector2D VW::Line2D::GetPerpendicular () const
The direction perpendicular to the line (unit vector).
References VNL::Vector< double >::data, and std::sqrt().
abs_t VNL::Vector< double >::InfNorm () const [inline, inherited]
Return largest absolute element value.
static void VNL::Vector< double >::inline_function_tickler () [static, protected, inherited]
bool VNL::Vector< double >::IsEmpty () const [inline, inherited]
Return true iff the size is zero.
bool VNL::Vector< double >::IsFinite () const [inherited]
Return true if its finite.
bool VNL::Vector< double >::IsZero () const [inherited]
Return true iff all the entries are zero.
double VW::Line2D::LookupX (const double y) const [inline]
Find the X value corresponding to the given Y value.
References VNL::Vector< double >::data.
Referenced by TruncateY().
double VW::Line2D::LookupY (const double x) const [inline]
Find the Y value corresponding to the given X value.
References VNL::Vector< double >::data.
Referenced by TruncateX().
abs_t VNL::Vector< double >::Magnitude () const [inline, inherited]
Return magnitude (length) of vector.
double VNL::Vector< double >::MaxValue () const [inline, inherited]
Largest value.
double VNL::Vector< double >::Mean () const [inline, inherited]
Mean of values in vector.
double VNL::Vector< double >::MinValue () const [inline, inherited]
Smallest value.
VectorFixedRef<n,double >& VNL::VectorFixedRef< n, double >::Normalize () [inline, inherited]
Normalise by dividing through by the magnitude.
Reimplemented from VNL::Vector< double >.
References VNL::VectorFixedRef< n, T >::Normalize().
abs_t VNL::Vector< double >::OneNorm () const [inline, inherited]
Return sum of absolute values of the elements.
bool VNL::Vector< double >::operator!= (Vector< double > const & that) const [inline, inherited]
Inequality test.
double const& VNL::Vector< double >::operator() (unsigned int i) const [inline, inherited]
Return reference to the element at specified index. No range checking.
There are assert style boundary checks - define NDEBUG to turn them off.
double & VNL::Vector< double >::operator() (unsigned int i) [inline, inherited]
Return reference to the element at specified index.
There are assert style boundary checks - define NDEBUG to turn them off.
Vector<double > VNL::Vector< double >::operator* (Matrix< double > const & M) const [inline, inherited]
VectorFixed<n,double > VNL::VectorFixed< n, double >::operator* (double const t) const [inline, inherited]
Reimplemented from VNL::Vector< double >.
Vector<double >& VNL::VectorFixedRef< n, double >::operator*= (Matrix< double > const & m) [inherited]
*this = (*this)*M where M is a suitable matrix.
this is treated as a row vector
Reimplemented from VNL::Vector< double >.
VectorFixedRef<n,double >& VNL::VectorFixedRef< n, double >::operator*= (double const) [inline, inherited]
Multiply all elements by scalar.
Multiplies all elements of vector with value. O(n).
Reimplemented from VNL::Vector< double >.
References VNL::VectorFixedRef< n, T >::operator*=().
Vector<double > VNL::Vector< double >::operator+ (Vector< double > const & v) const [inline, inherited]
Vector<double > VNL::Vector< double >::operator+ () const [inline, inherited]
Unary plus operator.
Return new vector = (*this)
VectorFixed<n,double > VNL::VectorFixed< n, double >::operator+ (Vector< double > const & rhs) const [inline, inherited]
VectorFixed<n,double > VNL::VectorFixed< n, double >::operator+ (double const t) const [inline, inherited]
Reimplemented from VNL::Vector< double >.
Vector<double >& VNL::Vector< double >::operator+= (Vector< double > const & rhs) [inherited]
Add rhs to this and return *this.
Mutates lhs vector with its addition with rhs vector. O(n).
VectorFixedRef<n,double >& VNL::VectorFixedRef< n, double >::operator+= (Vector< double > const & rhs) [inline, inherited]
References VNL::VectorFixedRef< n, T >::operator+=().
VectorFixedRef<n,double >& VNL::VectorFixedRef< n, double >::operator+= (double const) [inline, inherited]
Add scalar value to all elements.
Increments all elements of vector with value. O(n).
Reimplemented from VNL::Vector< double >.
References VNL::VectorFixedRef< n, T >::operator+=().
Vector<double > VNL::Vector< double >::operator- (Vector< double > const & v) const [inline, inherited]
VectorFixed<n,double > VNL::VectorFixed< n, double >::operator- (Vector< double > const & rhs) const [inline, inherited]
VectorFixed<n,double > VNL::VectorFixed< n, double >::operator- (double const t) const [inline, inherited]
Reimplemented from VNL::Vector< double >.
VectorFixed<n,double > VNL::VectorFixed< n, double >::operator- () const [inline, inherited]
Unary minus operator.
Creates new vector containing the negation of THIS vector. O(n).
Return new vector = -1*(*this)
Reimplemented from VNL::Vector< double >.
Vector<double >& VNL::Vector< double >::operator-= (Vector< double > const & rhs) [inherited]
Subtract rhs from this and return *this.
Mutates lhs vector with its substraction with rhs vector. O(n).
VectorFixedRef<n,double >& VNL::VectorFixedRef< n, double >::operator-= (Vector< double > const & rhs) [inline, inherited]
References VNL::VectorFixedRef< n, T >::operator-=().
VectorFixedRef<n,double >& VNL::VectorFixedRef< n, double >::operator-= (double const) [inline, inherited]
Subtract scalar value from all elements.
Reimplemented from VNL::Vector< double >.
References VNL::VectorFixedRef< n, T >::operator-=().
VectorFixed<n,double > VNL::VectorFixed< n, double >::operator/ (double const t) const [inline, inherited]
Reimplemented from VNL::Vector< double >.
VectorFixedRef<n,double >& VNL::VectorFixedRef< n, double >::operator/= (double const) [inline, inherited]
Divide all elements by scalar.
Divides all elements of vector by value. O(n).
Reimplemented from VNL::Vector< double >.
References VNL::VectorFixedRef< n, T >::operator/=().
VW::Line2D & VW::Line2D::operator= (const Line2D & rhs) [inline]
Copy operator.
Reimplemented from VNL::Vector< double >.
References VNL::Vector< double >::data.
bool VNL::Vector< double >::operator== (Vector< double > const & that) const [inline, inherited]
Equality test.
double const& VNL::Vector< double >::operator[] (unsigned int i) const [inline, inherited]
Return reference to the element at specified index. No range checking.
double & VNL::Vector< double >::operator[] (unsigned int i) [inline, inherited]
Return reference to the element at specified index. No range checking.
bool VNL::Vector< double >::operator_eq (Vector< double > const & v) const [inherited]
Return true if *this == v.
Vector<double >& VNL::VectorFixedRef< n, double >::PostMultiply (Matrix< double > const & M) [inherited]
*this = (*this)*M where M is a suitable matrix.
Post-multiplies vector with matrix and stores result back in vector.
this is treated as a row vector
v = v * m. O(m*n). Vector is assumed a row matrix.
Reimplemented from VNL::Vector< double >.
Vector<double >& VNL::VectorFixedRef< n, double >::PreMultiply (Matrix< double > const & M) [inherited]
*this = M*(*this) where M is a suitable matrix.
Pre-multiplies vector with matrix and stores result back in vector.
this is treated as a column vector
v = m * v. O(m*n). Vector is assumed a column matrix.
Reimplemented from VNL::Vector< double >.
void VNL::Vector< double >::Put (unsigned int i, double const &) [inline, inherited]
Put value at given position in vector.
Puts the value at specified index. O(1).
Range check is performed.
static Vector<double > VNL::Vector< double >::Read (std::istream & s) [static, inherited]
Read from text stream.
bool VW::Line2D::ReadASCII (std::istream & s) [inline, virtual]
Read from text stream.
Reimplemented from VNL::Vector< double >.
References VNL::Vector< double >::data.
bool VW::Line2D::ReadBinary (std::istream & stream) [inline, virtual]
References VNL::Vector< double >::data.
bool VW::Line2D::ReadXML (std::istream & stream, const std::string & name = "") [inline, virtual]
References VNL::Vector< double >::data, VW::FindXMLBlock(), and VW::GetXMLBlock().
bool VNL::Vector< double >::Resize (unsigned n) [inherited]
Resize to n elements.
Checks early and does nothing if already size n, otherwise old data is discarded. Returns true if size change successful.
abs_t VNL::Vector< double >::RMS () const [inline, inherited]
Root Mean Squares of values.
void VNL::Vector< double >::Set (double const * ptr) [inline, inherited]
Sets elements to ptr[i].
Note: ptr[i] must be valid for i=0..size()-1
void VW::Line2D::Set (const VNL::Vector< double > & line) [inline]
References VNL::Vector< double >::data.
void VW::Line2D::Set (double a, double b, double c) [inline]
References VNL::Vector< double >::data.
Referenced by VW::LineSeg2D::GetLine().
unsigned VNL::Vector< double >::Size () const [inline, inherited]
Return the length, number of elements, dimension of this vector.
unsigned VNL::Vector< double >::size () const [inline, inherited]
Return the length, number of elements, dimension of this vector.
abs_t VNL::Vector< double >::SquaredMagnitude () const [inline, inherited]
Return sum of squares of elements.
double VNL::Vector< double >::Sum () const [inline, inherited]
Sum of values in a vector.
void VNL::Vector< double >::Swap (Vector< double > & that) [inherited]
Set this to that and that to this.
double & VNL::Vector< double >::t () const [inline, inherited]
Return fourth element of vector.
VW::LineSeg2D VW::Line2D::Truncate (const double x0, const double y0, const double x1, const double y1) const
Truncate to lie within a rectangle (x0,y0)->(x1,y1) (eg for displaying).
References VNL::Vector< double >::data, VW::LineSeg2D::GetEndPoint(), VW::LineSeg2D::GetStartPoint(), VW::Point2D::GetX(), VW::Point2D::GetY(), TruncateX(), TruncateY(), VNL::Vector< double >::x(), and VNL::Vector< double >::y().
Referenced by VW::DrawFunctions::Draw().
VW::LineSeg2D VW::Line2D::TruncateX (const double x0, const double x1) const
Truncate using bounds on X (result is a line-segment).
References LookupY().
Referenced by Truncate().
VW::LineSeg2D VW::Line2D::TruncateY (const double y0, const double y1) const
Truncate using bounds on Y (result is a line-segment).
References LookupX().
Referenced by Truncate().
abs_t VNL::Vector< double >::TwoNorm () const [inline, inherited]
Return sqrt of sum of squares of values of elements.
Vector<double >& VNL::Vector< double >::Update (Vector< double > const & , unsigned int start = 0) [inherited]
Replaces elements with index begining at start, by values of v. O(n).
VectorFixedRef<n,double >& VNL::VectorFixedRef< n, double >::Update (Vector< double > const & v, unsigned int start = 0) [inline, inherited]
References VNL::VectorFixedRef< n, T >::Update().
bool VW::Line2D::WriteASCII (std::ostream & stream) const [inline, virtual]
References VNL::Vector< double >::data.
bool VW::Line2D::WriteBinary (std::ostream & stream) const [inline, virtual]
References VNL::Vector< double >::data.
bool VW::Line2D::WriteXML (std::ostream & stream, const std::string & name = "") const [inline, virtual]
References VNL::Vector< double >::data.
double & VNL::Vector< double >::x () const [inline, inherited]
Return first element of vector.
Referenced by Truncate().
double & VNL::Vector< double >::y () const [inline, inherited]
Return second element of vector.
Referenced by Truncate().
double & VNL::Vector< double >::z () const [inline, inherited]
Return third element of vector.
Friends And Related Function Documentation
VectorFixed<n,double > ElementProduct (VectorFixedRef< n, double > const & a, VectorFixedRef< n, double > const & b) [friend, inherited]
VectorFixed<n,double > ElementQuotient (VectorFixedRef< n, double > const & a, VectorFixedRef< n, double > const & b) [friend, inherited]
friend class Matrix< double > [friend, inherited]
Member Data Documentation
double * VNL::Vector< double >::data [protected, inherited]
Referenced by GetA(), GetB(), GetC(), GetDirection(), GetDistance(), GetDistance2(), GetPerpendicular(), Line2D(), LookupX(), LookupY(), operator=(), ReadASCII(), ReadBinary(), ReadXML(), Set(), Truncate(), WriteASCII(), WriteBinary(), and WriteXML().
unsigned VNL::Vector< double >::num_elmts [protected, inherited]
The documentation for this class was generated from the following files:
line2d.h
line2d.cpp