VW: VW::ChebyshevPolynomial Class Reference
VW::ChebyshevPolynomial Class Reference
[MathsStuff]
Some functions for fitting and evaluating Chebyshev polynomials.
#include <chebyshevpolynomial.h>
Public Member Functions
ChebyshevPolynomial (unsigned int poly_order=5)
Construct with no data.
ChebyshevPolynomial (const std::vector< double > &x, const std::vector< double > &y, unsigned int poly_order=5)
Construct with data.
~ChebyshevPolynomial ()
void Clear ()
Remove all existing data from the internal store.
void SetPolynomialOrder (unsigned int poly_order)
Change the order of the polynomial to be fitted.
void AddData (double x, double y)
Append new data to the internal store.
void AddData (const std::vector< double > &x, const std::vector< double > &y)
double GetYValue (double x) const
Get the y-value corresponding to a particular X-position.
void GetLimits (double &minx, double &maxx, double &miny, double &maxy) const
unsigned int GetNumberOfDataPoints () const
double GetDataX (unsigned int index) const
double GetDataY (unsigned int index) const
void GetCoeffs (std::vector< double > &coeffs) const
Detailed Description
Some functions for fitting and evaluating Chebyshev polynomials.
Author:
BJ Tordoff
Date:
02/08/02
Constructor & Destructor Documentation
VW::ChebyshevPolynomial::ChebyshevPolynomial (unsigned int poly_order = 5)
Construct with no data.
Data must be added before use.
VW::ChebyshevPolynomial::ChebyshevPolynomial (const std::vector< double > & x, const std::vector< double > & y, unsigned int poly_order = 5)
Construct with data.
Data is added and the polynomial fitted, ready for use.
VW::ChebyshevPolynomial::~ChebyshevPolynomial () [inline]
Member Function Documentation
void VW::ChebyshevPolynomial::AddData (const std::vector< double > & x, const std::vector< double > & y)
void VW::ChebyshevPolynomial::AddData (double x, double y)
Append new data to the internal store.
Referenced by VW::CalibrationTable::AddCalibrationData(), and VW::CalibrationTable::AddDistortionData().
void VW::ChebyshevPolynomial::Clear () [inline]
Remove all existing data from the internal store.
Referenced by VW::CalibrationTable::Clear().
void VW::ChebyshevPolynomial::GetCoeffs (std::vector< double > & coeffs) const [inline]
Referenced by VW::CalibrationTable::PrintPolyCoeffs().
double VW::ChebyshevPolynomial::GetDataX (unsigned int index) const [inline]
double VW::ChebyshevPolynomial::GetDataY (unsigned int index) const [inline]
void VW::ChebyshevPolynomial::GetLimits (double & minx, double & maxx, double & miny, double & maxy) const [inline]
unsigned int VW::ChebyshevPolynomial::GetNumberOfDataPoints (void) const [inline]
double VW::ChebyshevPolynomial::GetYValue (double x) const
Get the y-value corresponding to a particular X-position.
Referenced by VW::CalibrationTable::GetCalibrationMatrix(), VW::CalibrationTable::GetDistortion(), and VW::CalibrationTable::GetMotorPosition().
void VW::ChebyshevPolynomial::SetPolynomialOrder (unsigned int poly_order)
Change the order of the polynomial to be fitted.
Referenced by VW::CalibrationTable::SetFixedAspect(), VW::CalibrationTable::SetFixedPrincipalPoint(), VW::CalibrationTable::SetFixedSkew(), VW::CalibrationTable::SetVaryingAspect(), VW::CalibrationTable::SetVaryingPrincipalPoint(), and VW::CalibrationTable::SetVaryingSkew().
The documentation for this class was generated from the following files:
chebyshevpolynomial.h
chebyshevpolynomial.cpp