VW: VW::PlesseyDetector Class Reference
VW::PlesseyDetector Class Reference
[ImageProcessing]
Interest point detection using the method of Harris/Plessey.
#include <plesseydetector.h>
Public Member Functions
PlesseyDetector ()
Construct with default params.
PlesseyDetector (const float thresh, const float sigma, const int convolution_size, const float ep, const unsigned int max_number=0)
Construct with parameters only.
PlesseyDetector (const VW::ImageMono< unsigned char > &im, std::vector< CornerFeature > &corners, const float thresh=DEF_THRESH, const float sigma=DEF_SIGMA, const int convolution_size=DEF_SIZE, const float ep=DEF_EDGEPHOBIA, const unsigned int max_number=0, const VW::Normalisation &C=Normalisation())
Construct and compute from a mono image, specifying all parameters.
PlesseyDetector (const VW::ImageMono< unsigned char > &im, CornerFeature &best_corner, const float thresh=DEF_THRESH, const float sigma=DEF_SIGMA, const int convolution_size=DEF_SIZE, const float ep=DEF_EDGEPHOBIA, const unsigned int max_number=0, const VW::Normalisation &C=Normalisation())
Construct and compute th single best feature from a mono image, specifying all parameters.
PlesseyDetector (const ImageYUV< unsigned char > &im, std::vector< CornerFeature > &corners, const float thresh=DEF_THRESH, const float sigma=DEF_SIGMA, const int size=DEF_SIZE, const float ep=DEF_EDGEPHOBIA, const unsigned int max_number=0, const Normalisation &C=Normalisation())
Construct and compute from a YUV image, specifying all parameters.
PlesseyDetector (const Pyramid< unsigned char > &im, std::vector< CornerFeature > &corners, const float thresh=DEF_THRESH, const float sigma=DEF_SIGMA, const int size=DEF_SIZE, const float ep=DEF_EDGEPHOBIA, const unsigned int max_number=0, const Normalisation &C=Normalisation())
Construct and compute from a pyramid of mono images.
PlesseyDetector (const Pyramid< float > &im, std::vector< CornerFeature > &corners, const float thresh=DEF_THRESH, const float sigma=DEF_SIGMA, const int size=DEF_SIZE, const float ep=DEF_EDGEPHOBIA, const unsigned int max_number=0, const Normalisation &C=Normalisation())
PlesseyDetector (const Pyramid< float > &im, CornerFeature &best_corner, const float thresh=DEF_THRESH, const float sigma=DEF_SIGMA, const int size=DEF_SIZE, const float ep=DEF_EDGEPHOBIA, const unsigned int max_number=0, const Normalisation &C=Normalisation())
~PlesseyDetector ()
operator bool () const
void Compute (const ImageMono< unsigned char > &image, std::vector< CornerFeature > &features, const Normalisation &C=Normalisation()) const
void Compute (const ImageMono< unsigned char > &image, CornerFeature &best_corner, const Normalisation &C=Normalisation()) const
void Compute (const Pyramid< unsigned char > &image, std::vector< CornerFeature > &features, const Normalisation &C=Normalisation()) const
void Compute (const Pyramid< float > &image, std::vector< CornerFeature > &features, const Normalisation &C=Normalisation()) const
void Compute (const Pyramid< float > &image, CornerFeature &best_corner, const Normalisation &C=Normalisation()) const
void Compute (const ImageYUV< unsigned char > &image, std::vector< CornerFeature > &features, const Normalisation &C=Normalisation()) const
void SetMinStrengthThreshold (float new_threshold)
void SetPatchSize (unsigned int new_size)
void SetSmoothingSigma (float new_sigma)
void SetEdgePhobia (float new_phobia)
void SetMaxNumFeatures (unsigned int new_maximum)
Public Attributes
bool Verbose
Detailed Description
Interest point detection using the method of Harris/Plessey.
Author:
ID Reid and BJ Tordoff
Date:
02/08/2002 The Plessey Corner Detector (with Harris-Stephens scoring system)
the Plessey (or Harris) corner detection system. The main detector is a function object 'Plessey' which takes an image or image-pyramid as input and produces a list of interest point locations (ie. vector<CornerFeature>).
To convert these locations into useful features, this list must then be passed to a descriptor finder, eg:
vector<CornerFeature> corners; vector<SIFTFeature> siftcorners;
VW::PlesseyDetector(image, corners); VW::GetSIFTDescriptor(corners, image, siftcorners);
Although this seems wasteful, the memory overhead in calculating two lists is not significant, and some descriptors (such as SIFT) can produce more than one feature per location.
Constructor & Destructor Documentation
VW::PlesseyDetector::PlesseyDetector () [inline]
Construct with default params.
INLINES ///.
VW::PlesseyDetector::PlesseyDetector (const float thresh, const float sigma, const int convolution_size, const float ep, const unsigned int max_number = 0) [inline]
Construct with parameters only.
VW::PlesseyDetector::PlesseyDetector (const VW::ImageMono< unsigned char > & im, std::vector< CornerFeature > & corners, const float thresh = DEF_THRESH, const float sigma = DEF_SIGMA, const int convolution_size = DEF_SIZE, const float ep = DEF_EDGEPHOBIA, const unsigned int max_number = 0, const VW::Normalisation & C = Normalisation()) [inline]
Construct and compute from a mono image, specifying all parameters.
References Compute().
VW::PlesseyDetector::PlesseyDetector (const VW::ImageMono< unsigned char > & im, CornerFeature & best_corner, const float thresh = DEF_THRESH, const float sigma = DEF_SIGMA, const int convolution_size = DEF_SIZE, const float ep = DEF_EDGEPHOBIA, const unsigned int max_number = 0, const VW::Normalisation & C = Normalisation()) [inline]
Construct and compute th single best feature from a mono image, specifying all parameters.
References Compute().
VW::PlesseyDetector::PlesseyDetector (const ImageYUV< unsigned char > & im, std::vector< CornerFeature > & corners, const float thresh = DEF_THRESH, const float sigma = DEF_SIGMA, const int size = DEF_SIZE, const float ep = DEF_EDGEPHOBIA, const unsigned int max_number = 0, const Normalisation & C = Normalisation()) [inline]
Construct and compute from a YUV image, specifying all parameters.
References Compute().
VW::PlesseyDetector::PlesseyDetector (const Pyramid< unsigned char > & im, std::vector< CornerFeature > & corners, const float thresh = DEF_THRESH, const float sigma = DEF_SIGMA, const int size = DEF_SIZE, const float ep = DEF_EDGEPHOBIA, const unsigned int max_number = 0, const Normalisation & C = Normalisation()) [inline]
Construct and compute from a pyramid of mono images.
References Compute().
VW::PlesseyDetector::PlesseyDetector (const Pyramid< float > & im, std::vector< CornerFeature > & corners, const float thresh = DEF_THRESH, const float sigma = DEF_SIGMA, const int size = DEF_SIZE, const float ep = DEF_EDGEPHOBIA, const unsigned int max_number = 0, const Normalisation & C = Normalisation()) [inline]
References Compute().
VW::PlesseyDetector::PlesseyDetector (const Pyramid< float > & im, CornerFeature & best_corner, const float thresh = DEF_THRESH, const float sigma = DEF_SIGMA, const int size = DEF_SIZE, const float ep = DEF_EDGEPHOBIA, const unsigned int max_number = 0, const Normalisation & C = Normalisation()) [inline]
References Compute().
VW::PlesseyDetector::~PlesseyDetector () [inline]
Member Function Documentation
void VW::PlesseyDetector::Compute (const ImageYUV< unsigned char > & image, std::vector< CornerFeature > & features, const Normalisation & C = Normalisation()) const
void PlesseyDetector::Compute (const Pyramid< float > & image, CornerFeature & best_corner, const Normalisation & C = Normalisation()) const
References VW::CornerFeature::GetCornerStrength(), VW::ConvolutionMask1D< maskType >::GetHalfWidth(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), VW::Pyramid< StorageType >::GetScale(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), VW::Point2D::GetX(), VW::Point2D::GetY(), VW::ConvolutionMask1D< maskType >::MakeGaussian(), VW::ConvolutionMask1D< maskType >::mask, VW::Normalisation::Normalise(), VW::Pyramid< StorageType >::NumLevels(), VW::CornerFeature::Set(), and VERBOSE.
void VW::PlesseyDetector::Compute (const Pyramid< float > & image, std::vector< CornerFeature > & features, const Normalisation & C = Normalisation()) const
void VW::PlesseyDetector::Compute (const Pyramid< unsigned char > & image, std::vector< CornerFeature > & features, const Normalisation & C = Normalisation()) const
void PlesseyDetector::Compute (const ImageMono< unsigned char > & image, CornerFeature & best_corner, const Normalisation & C = Normalisation()) const
References VW::CornerFeature::GetCornerStrength(), VW::ConvolutionMask1D< maskType >::GetHalfWidth(), VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), VW::ImageBase< PixelType, PixelPtr >::IsAlloced(), VW::ConvolutionMask1D< maskType >::MakeGaussian(), VW::ConvolutionMask1D< maskType >::mask, VW::Normalisation::Normalise(), VW::CornerFeature::SetCornerStrength(), and VERBOSE.
void VW::PlesseyDetector::Compute (const ImageMono< unsigned char > & image, std::vector< CornerFeature > & features, const Normalisation & C = Normalisation()) const
Referenced by PlesseyDetector().
VW::PlesseyDetector::operator bool () const [inline]
void VW::PlesseyDetector::SetEdgePhobia (float new_phobia) [inline]
void VW::PlesseyDetector::SetMaxNumFeatures (unsigned int new_maximum) [inline]
void VW::PlesseyDetector::SetMinStrengthThreshold (float new_threshold) [inline]
void VW::PlesseyDetector::SetPatchSize (unsigned int new_size) [inline]
void VW::PlesseyDetector::SetSmoothingSigma (float new_sigma) [inline]
Member Data Documentation
bool VW::PlesseyDetector::Verbose
The documentation for this class was generated from the following files:
plesseydetector.h
plesseydetector.cpp