VW: VW::Homography2DComputeLinear Class Reference
VW::Homography2DComputeLinear Class Reference
#include <homography2dcomputelinear.h>
Public Member Functions
Homography2DComputeLinear (const bool normalise=true)
Create a linear computation object.
bool Compute (VW::Homography2D &result, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1)
Compute a homography from two lists of 2D point features.
bool Compute (VW::Homography2D &result, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const std::vector< unsigned int > &which_features)
Compute a homography from two lists of 2D point features.
bool ComputeWeighted (VW::Homography2D &result, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const std::vector< double > &weights)
Compute a homography from two lists of 2D point features, weighting the contribution of the features.
bool Compute (VW::Homography2D &result, VW::Homography2DCovariance &covar, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const double noise0, const double noise1)
Compute a homography and its covariance from two lists of 2D point features.
bool Compute (VW::Homography2D &result, VW::Homography2DCovariance &covar, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const double noise0, const double noise1, const std::vector< unsigned int > &which_features)
Compute a homography and its covariance from selected entries of two lists of 2D point features.
bool Compute (VW::Homography2D &result, const std::vector< VW::Line2D > &l0, const std::vector< VW::Line2D > &l1)
Compute a homography from 2D line features (not implemented yet).
Constructor & Destructor Documentation
VW::Homography2DComputeLinear::Homography2DComputeLinear (const bool normalise = true) [inline]
Create a linear computation object.
Note that the calculation can involve a normalisation, so it is not necessary to pre-normalise the input points/lines (although it doesn't hurt).
Member Function Documentation
bool VW::Homography2DComputeLinear::Compute (VW::Homography2D & result, const std::vector< VW::Line2D > & l0, const std::vector< VW::Line2D > & l1)
Compute a homography from 2D line features (not implemented yet).
bool VW::Homography2DComputeLinear::Compute (VW::Homography2D & result, VW::Homography2DCovariance & covar, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const double noise0, const double noise1, const std::vector< unsigned int > & which_features)
Compute a homography and its covariance from selected entries of two lists of 2D point features.
References VW::Normalisation::GetScale(), VW::Normalisation::Init(), VW::EssentialMatrixCompute::MakeSymmetric(), VW::Normalisation::Normalise(), VNL::Matrix< T >::Transpose(), VW::EssentialMatrixCompute::Unnormalise(), and VERBOSE.
bool VW::Homography2DComputeLinear::Compute (VW::Homography2D & result, VW::Homography2DCovariance & covar, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const double noise0, const double noise1)
Compute a homography and its covariance from two lists of 2D point features.
References VW::Normalisation::GetScale(), VW::Normalisation::Init(), VW::EssentialMatrixCompute::MakeSymmetric(), VW::Normalisation::Normalise(), VNL::Matrix< T >::Transpose(), VW::EssentialMatrixCompute::Unnormalise(), and VERBOSE.
bool VW::Homography2DComputeLinear::Compute (VW::Homography2D & result, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const std::vector< unsigned int > & which_features)
Compute a homography from two lists of 2D point features.
Note that x0, x1 are defined such that x_1 = H x_0
Parameters:
which_features a list of the indices of feature-pairs to use
References VW::Normalisation::Init(), VW::EssentialMatrixCompute::MakeSymmetric(), and VW::Normalisation::Normalise().
bool VW::Homography2DComputeLinear::Compute (VW::Homography2D & result, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1)
Compute a homography from two lists of 2D point features.
Note that x0, x1 are defined such that x_1 = H x_0
Parameters:
inlierlist a list of the indices of feature-pairs to use
References VW::Normalisation::Init(), VW::EssentialMatrixCompute::MakeSymmetric(), VW::Normalisation::Normalise(), and VERBOSE.
Referenced by VW::Homography2DCompute::GUISACCore(), VW::Homography2DCompute::GUNSACCore(), and VW::Homography2DCompute::MLESACCore().
bool VW::Homography2DComputeLinear::ComputeWeighted (VW::Homography2D & result, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const std::vector< double > & weights)
Compute a homography from two lists of 2D point features, weighting the contribution of the features.
References VW::Normalisation::Init(), VW::EssentialMatrixCompute::MakeSymmetric(), VW::Normalisation::Normalise(), and VERBOSE.
Referenced by VW::Homography2DCompute::GUISACCore(), and VW::Homography2DCompute::GUNSACCore().
The documentation for this class was generated from the following files:
homography2dcomputelinear.h
homography2dcomputelinear.cpp