VW: VNL::NumericLimits< T > Class Template Reference
VNL::NumericLimits< T > Class Template Reference
Standard limits for numeric datatypes.
#include <numericlimits.h>
Static Public Member Functions
static T min ()
Minimum finite value.
static T max ()
Maximum finite value.
static T epsilon ()
Machine epsilon.
static T round_error ()
Measure of the maximum rounding error.
static T infinity ()
Representation of positive infinity, if available.
static T quiet_NaN ()
Representation of a quiet ``Not a Number,'' if available.
static T signaling_NaN ()
Representation of a signaling ``Not a Number,'' if available.
static T denorm_min ()
Minimum positive denormalized value.
Static Public Attributes
static const bool is_specialized
Distingishes between scalar types, which have specialisations, and non-scalar types, which don't.
static const int digits
Number of radix digits which can be represented without change.
static const int digits10
Number of base 10 digits which can be represented without change.
static const bool is_signed
True if the type is signed.
static const bool is_integer
True if the type is integer.
static const bool is_exact
True if the type uses an exact representation.
static const int radix
For floating types, specifies the base or radix of the exponent representation (often 2).
static const int min_exponent
Minimum negative integer such that radix raised to that power is in range.
static const int min_exponent10
Minimum negative integer such that 10 raised to that power is in range.
static const int max_exponent
Maximum positive integer such that radix raised to that power is in range.
static const int max_exponent10
Maximum positive integer such that 10 raised to that power is in range.
static const bool has_infinity
True if the type has a representation for positive infinity.
static const bool has_quiet_NaN
True if the type has a representation for a quiet (non-signaling).
static const bool has_signaling_NaN
True if the type has a representation for a signaling.
static const bool has_denorm
True if the type allows denormalized values (variable number of exponent bits).
static const bool is_iec559
True if and only if the type adheres to IEC 559 standard.
static const bool is_bounded
True if the set of values representable by the type is finite.
static const bool is_modulo
True if the type is modulo.
static const bool traps
True if trapping is implemented for the type.
static const bool tinyness_before
True if tinyness is detected before rounding. Refer to IEC 559.
static const FloatRoundStyle round_style
The rounding style for the type. Equivalent to FLT_ROUNDS.
Detailed Description
template<class T>
class VNL::NumericLimits< T >
Standard limits for numeric datatypes.
Implementation of the May 96 ANSI Draft Working Paper (DWP) numeric_limits class. Numbering in the documentation below refers to section 18.2 of the DWP.
Member Function Documentation
template<class T > static T VNL::NumericLimits< T >::denorm_min () [static]
Minimum positive denormalized value.
Meaningful for all floating point types. In specializations for which has_denorm == false, returns the minimum positive normalized value. For types with has_denorm == false, the member denorm_min() shall return the same value as the member min().
template<class T > static T VNL::NumericLimits< T >::epsilon () [static]
Machine epsilon.
The difference between 1 and the least value greater than 1 that is representable. Equivalent to FLT_EPSILON, DBL_EPSILON, LDBL_EPSILON. Meaningful only for floating point types.
template<class T > static T VNL::NumericLimits< T >::infinity () [static]
Representation of positive infinity, if available.
template<class T > static T VNL::NumericLimits< T >::max () [static]
Maximum finite value.
Equivalent to CHAR_MAX, SHRT_MAX, FLT_MAX, DBL_MAX, etc. Meaningful for all specializations in which is_bounded == true.
Referenced by VNL::UnaryFunction< T, T >::GetRangeMax(), VNL::NumericLimits< short >::infinity(), VNL::NumericLimits< unsigned short >::infinity(), VNL::NumericLimits< unsigned long >::infinity(), VNL::NumericLimits< long >::infinity(), and VNL::NumericLimits< vnl_tmp_signed32 >::infinity().
template<class T > static T VNL::NumericLimits< T >::min () [static]
Minimum finite value.
Equivalent to CHAR_MIN, SHRT_MIN, FLT_MIN, DBL_MIN, etc.
For floating types with denormalization, returns the minimum positive normalized value, denorm_min().
Meaningful for all specializations in which is_bounded == true, or is_bounded == false && is_signed == false.
Referenced by VNL::NumericLimits< double >::denorm_min(), VNL::NumericLimits< float >::denorm_min(), VNL::NumericLimits< short >::denorm_min(), VNL::NumericLimits< unsigned short >::denorm_min(), VNL::NumericLimits< unsigned long >::denorm_min(), VNL::NumericLimits< long >::denorm_min(), and VNL::NumericLimits< vnl_tmp_signed32 >::denorm_min().
template<class T > static T VNL::NumericLimits< T >::quiet_NaN () [static]
Representation of a quiet ``Not a Number,'' if available.
Referenced by VNL::NumericLimits< float >::signaling_NaN(), and VNL::NumericLimits< double >::signaling_NaN().
template<class T > static T VNL::NumericLimits< T >::round_error () [static]
Measure of the maximum rounding error.
This has a precise definition in the Language Independent Arithmetic (LIA-1) standard. Required by LIA-1.
template<class T > static T VNL::NumericLimits< T >::signaling_NaN () [static]
Representation of a signaling ``Not a Number,'' if available.
Member Data Documentation
template<class T > const int VNL::NumericLimits< T >::digits [static]
Number of radix digits which can be represented without change.
For built-in integer types, the number of non-sign bits in the representation. For floating point types, the number of radix digits in the mantissa. Equivalent to FLT_MANT_DIG, DBL_MANT_DIG, LDBL_MANT_DIG.
template<class T > const int VNL::NumericLimits< T >::digits10 [static]
Number of base 10 digits which can be represented without change.
Equivalent to FLT_DIG, DBL_DIG, LDBL_DIG. Meaningful for all specializations in which is_bounded == true.
template<class T > const bool VNL::NumericLimits< T >::has_denorm [static]
True if the type allows denormalized values (variable number of exponent bits).
Meaningful only for flotaing point types.
template<class T > const bool VNL::NumericLimits< T >::has_infinity [static]
True if the type has a representation for positive infinity.
Meaningful only for floating point types. Shall be true for all specializations in which is_iec559 == true.
template<class T > const bool VNL::NumericLimits< T >::has_quiet_NaN [static]
True if the type has a representation for a quiet (non-signaling).
``Not a Number.''. RLIA Meaningful only for floating point types. Shall be true for all specializations in which is_iec559 == true.
template<class T > const bool VNL::NumericLimits< T >::has_signaling_NaN [static]
True if the type has a representation for a signaling.
``Not a Number.''. Meaningful only for floating point types. Shall be true for all specializations in which is_iec559 == true.
template<class T > const bool VNL::NumericLimits< T >::is_bounded [static]
True if the set of values representable by the type is finite.
All built-in types are bounded, this member would be false for arbitrary precision types.
template<class T > const bool VNL::NumericLimits< T >::is_exact [static]
True if the type uses an exact representation.
All integer types are exact, but not vice versa. For example, rational and fixed-exponent representations are exact but not integer.
template<class T > const bool VNL::NumericLimits< T >::is_iec559 [static]
True if and only if the type adheres to IEC 559 standard.
International Electrotechnical Commission standard 559 is the same as IEEE 754.
template<class T > const bool VNL::NumericLimits< T >::is_integer [static]
True if the type is integer.
template<class T > const bool VNL::NumericLimits< T >::is_modulo [static]
True if the type is modulo.
A type is modulo if it is possible to add two positive numbers and have a result which wraps around to a third number which is less. Generally, this is false for floating types, true for unsigned integers, and true for signed integers on most machines.
template<class T > const bool VNL::NumericLimits< T >::is_signed [static]
True if the type is signed.
template<class T > const bool VNL::NumericLimits< T >::is_specialized [static]
Distingishes between scalar types, which have specialisations, and non-scalar types, which don't.
template<class T > const int VNL::NumericLimits< T >::max_exponent [static]
Maximum positive integer such that radix raised to that power is in range.
Equivalent to FLT_MAX_EXP, DBL_MAX_EXP, LDBL_MAX_EXP. Meaningful only for floating point types.
template<class T > const int VNL::NumericLimits< T >::max_exponent10 [static]
Maximum positive integer such that 10 raised to that power is in range.
Equivalent to FLT_MAX_10_EXP, DBL_MAX_10_EXP, LDBL_MAX_10_EXP. Meaningful only for floating point types.
template<class T > const int VNL::NumericLimits< T >::min_exponent [static]
Minimum negative integer such that radix raised to that power is in range.
Equivalent to FLT_MIN_EXP, DBL_MIN_EXP, LDBL_MIN_EXP. Meaningful only for floating point types.
template<class T > const int VNL::NumericLimits< T >::min_exponent10 [static]
Minimum negative integer such that 10 raised to that power is in range.
Equivalent to FLT_MIN_10_EXP, DBL_MIN_10_EXP, LDBL_MIN_10_EXP. Meaningful only for floating point types.
template<class T > const int VNL::NumericLimits< T >::radix [static]
For floating types, specifies the base or radix of the exponent representation (often 2).
Equivalent to FLT_RADIX. For integer types, specifies the base of the representation - distinguishes types with bases other than 2 (e.g. BCD).
template<class T > const FloatRoundStyle VNL::NumericLimits< T >::round_style [static]
The rounding style for the type. Equivalent to FLT_ROUNDS.
Specializations for integer types shall return round_toward_zero.
template<class T > const bool VNL::NumericLimits< T >::tinyness_before [static]
True if tinyness is detected before rounding. Refer to IEC 559.
template<class T > const bool VNL::NumericLimits< T >::traps [static]
True if trapping is implemented for the type.
The documentation for this class was generated from the following file:
numericlimits.h