VW: VW::ClassifierUVGTK Class Reference
VW::ClassifierUVGTK Class Reference
#include <classifieruvgtk.h>
Public Member Functions
ClassifierUVGTK (VW::InterfaceType t=VW::INTERFACE_AS_BUTTONWINDOW)
virtual void LoadParameterFile (std::string paramfile=".params")
Load an existing data-file (same as ReadXMLFile()).
virtual void SaveParameterFile (std::string paramfile=".params")
Save into data-file (same as WriteXMLFile()).
void UpdateForm ()
void UpdateFromForm ()
void Show (void)
void Hide (void)
void Quit (void)
VW::InterfaceType GetType (void)
void Reset (unsigned int new_bin_size=1, unsigned int new_num_classes=0)
Set to a new size (and fill with CLASSIFIER_OTHER).
unsigned int Classify (unsigned char u, unsigned char v) const
Classify a given UV pair.
void Classify (const VW::ImageYUV< unsigned char > &input_image, VW::ImageMono< unsigned char > &classification) const
float GetProb (unsigned char u, unsigned char v, unsigned int which_class) const
Get the probability that a given UV pair belongs to .
void GetProbImage (const VW::ImageYUV< unsigned char > &input_image, unsigned int which_class, VW::ImageMono< float > &prob) const
Get the probability that each pixel belongs to .
void GetProbImage (const VW::ImageYUV< unsigned char > &input_image, unsigned int which_class, VW::ImageMono< unsigned char > &prob) const
Get the probability that each pixel belongs to .
void ClassifyAndColour (const VW::ImageYUV< unsigned char > &input_image, VW::ImageRGB< unsigned char > &classification) const
void GetHistogramAsImage (VW::ImageRGB< unsigned char > &histogram) const
unsigned int ** GetClassifierMatrix ()
virtual bool WriteASCII (std::ostream &stream) const
Stream out as plain ASCII.
virtual bool WriteXML (std::ostream &stream, const std::string &name="") const
Stream out as XML style ASCII.
virtual bool WriteBinary (std::ostream &stream) const
Stream out as binary.
virtual bool ReadASCII (std::istream &stream)
Stream in as plain ASCII.
virtual bool ReadXML (std::istream &stream, const std::string &name="")
Stream in as XML style ASCII.
virtual bool ReadBinary (std::istream &stream)
Stream in as binary.
bool WriteASCIIFile (const std::string &filename) const
Open a file and output as plain ASCII (overwriting any existing contents).
bool WriteXMLFile (const std::string &filename, const std::string &name="") const
Open a file and output as XML-style ASCII (overwriting any existing contents).
bool WriteBinaryFile (const std::string &filename) const
Open a file and output as binary (overwriting any existing contents).
virtual bool ReadASCIIFile (const std::string &filename)
Open a file and input as plain ASCII.
virtual bool ReadXMLFile (const std::string &filename, const std::string &name="")
Open a file and input as XML style ASCII.
virtual bool ReadBinaryFile (const std::string &filename)
Open a file and input as binary.
Protected Member Functions
void LoadStart ()
void LoadOK ()
void SaveStart ()
void SaveOK ()
void FileCancel ()
virtual void InitButtonWindow ()
virtual void InitButtonWindow (unsigned int width, unsigned int height)
virtual void InitWidget ()
void Colourify (unsigned int class_index, unsigned char &r, unsigned char &g, unsigned char &b) const
Protected Attributes
std::string _param_file
SigC::Signal1< void, std::string > LoadEvent
SigC::Signal1< void, std::string > SaveEvent
ClassifierUVGTKWidget * my_widget
Gtk::Window * my_window
VW::InterfaceType my_type
std::string my_name
Gtk::FileSelection * file_selector
unsigned int ** classifier_matrix
std::vector< float ** > prob_matrix
unsigned int num_classes
unsigned int rows
unsigned int columns
unsigned int my_bin_size
float u_scale
float v_scale
Constructor & Destructor Documentation
VW::ClassifierUVGTK::ClassifierUVGTK (VW::InterfaceType t = VW::INTERFACE_AS_BUTTONWINDOW)
References VW::InterfaceGTK< ClassifierUVGTKWidget >::InitButtonWindow(), VW::ClassifierUVGTKWidget::InitForm(), VW::InterfaceGTK< ClassifierUVGTKWidget >::InitWidget(), VW::INTERFACE_AS_BUTTONWINDOW, VW::InterfaceGTK< ClassifierUVGTKWidget >::my_name, VW::InterfaceGTK< ClassifierUVGTKWidget >::my_type, and VW::InterfaceGTK< ClassifierUVGTKWidget >::my_widget.
Member Function Documentation
void VW::ClassifierUV::Classify (const VW::ImageYUV< unsigned char > & input_image, VW::ImageMono< unsigned char > & classification) const [inherited]
References VW::ImageBase< PixelType, PixelPtr >::AllocImageData(), VW::ClassifierUV::Classify(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetRawBuffer(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetRawBuffer(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), VW::ImageBase< PixelType, PixelPtr >::IsAlloced(), and v.
unsigned int VW::ClassifierUV::Classify (unsigned char u, unsigned char v) const [inline, inherited]
Classify a given UV pair.
References VW::ClassifierUV::classifier_matrix, VW::ClassifierUV::u_scale, and VW::ClassifierUV::v_scale.
Referenced by VW::ClassifierUV::Classify(), and VW::ClassifierUV::ClassifyAndColour().
void VW::ClassifierUV::ClassifyAndColour (const VW::ImageYUV< unsigned char > & input_image, VW::ImageRGB< unsigned char > & classification) const [inherited]
References VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::AllocImageData(), c, VW::ClassifierUV::Classify(), VW::ClassifierUV::Colourify(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetHeight(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetRawBuffer(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetRawBuffer(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetWidth(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::IsAlloced(), and v.
void VW::ClassifierUV::Colourify (unsigned int class_index, unsigned char & r, unsigned char & g, unsigned char & b) const [inline, protected, inherited]
Referenced by VW::ClassifierUV::ClassifyAndColour(), and VW::ClassifierUV::GetHistogramAsImage().
void VW::InterfaceGTK< ClassifierUVGTKWidget >::FileCancel () [inline, protected, inherited]
unsigned int ** VW::ClassifierUV::GetClassifierMatrix () [inline, inherited]
References VW::ClassifierUV::classifier_matrix.
void VW::ClassifierUV::GetHistogramAsImage (VW::ImageRGB< unsigned char > & histogram) const [inherited]
References VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::AllocImageData(), c, VW::ClassifierUV::classifier_matrix, VW::ClassifierUV::Colourify(), VW::ClassifierUV::columns, VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetHeight(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetWidth(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::IsAlloced(), VW::ClassifierUV::rows, and VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::SetPixel().
float VW::ClassifierUV::GetProb (unsigned char u, unsigned char v, unsigned int which_class) const [inline, inherited]
Get the probability that a given UV pair belongs to .
References VW::ClassifierUV::prob_matrix, VW::ClassifierUV::u_scale, and VW::ClassifierUV::v_scale.
Referenced by VW::ClassifierUV::GetProbImage().
void VW::ClassifierUV::GetProbImage (const VW::ImageYUV< unsigned char > & input_image, unsigned int which_class, VW::ImageMono< unsigned char > & prob) const [inherited]
Get the probability that each pixel belongs to .
resulting pixels have values between 0 and 255 inclusive.
References VW::ImageBase< PixelType, PixelPtr >::AllocImageData(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ClassifierUV::GetProb(), VW::ImageBase< PixelType, PixelPtr >::GetRawBuffer(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetRawBuffer(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), VW::ImageBase< PixelType, PixelPtr >::IsAlloced(), and v.
void VW::ClassifierUV::GetProbImage (const VW::ImageYUV< unsigned char > & input_image, unsigned int which_class, VW::ImageMono< float > & prob) const [inherited]
Get the probability that each pixel belongs to .
resulting pixels have values between 0 and 1 inclusive.
References VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::AllocImageData(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), VW::ClassifierUV::GetProb(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetRawBuffer(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetRawBuffer(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::IsAlloced(), and v.
VW::InterfaceType VW::InterfaceGTK< ClassifierUVGTKWidget >::GetType (void) [inline, inherited]
void VW::InterfaceGTK< ClassifierUVGTKWidget >::Hide (void) [inline, inherited]
virtual void VW::InterfaceGTK< ClassifierUVGTKWidget >::InitButtonWindow (unsigned int width, unsigned int height) [protected, virtual, inherited]
virtual void VW::InterfaceGTK< ClassifierUVGTKWidget >::InitButtonWindow () [protected, virtual, inherited]
Referenced by ClassifierUVGTK().
virtual void VW::InterfaceGTK< ClassifierUVGTKWidget >::InitWidget () [protected, virtual, inherited]
Referenced by ClassifierUVGTK().
void VW::InterfaceGTK< ClassifierUVGTKWidget >::LoadOK () [inline, protected, inherited]
void VW::ClassifierUVGTK::LoadParameterFile (std::string filename = ".params") [virtual]
Load an existing data-file (same as ReadXMLFile()).
Reimplemented from VW::ClassifierUV.
References _param_file, and UpdateForm().
void VW::InterfaceGTK< ClassifierUVGTKWidget >::LoadStart () [inline, protected, inherited]
void VW::InterfaceGTK< ClassifierUVGTKWidget >::Quit (void) [inline, inherited]
bool VW::ClassifierUV::ReadASCII (std::istream & stream) [inline, virtual, inherited]
Stream in as plain ASCII.
Implements VW::IOObject.
bool VW::IOObject::ReadASCIIFile (const std::string & filename) [virtual, inherited]
Open a file and input as plain ASCII.
Open a file and read as plain ASCII.
Once the file is open, the child class's ReadASCII function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadASCII().
bool VW::ClassifierUV::ReadBinary (std::istream & stream) [inline, virtual, inherited]
Stream in as binary.
Implements VW::IOObject.
bool VW::IOObject::ReadBinaryFile (const std::string & filename) [virtual, inherited]
Open a file and input as binary.
Open a file and read as binary.
Once the file is open, the child class's ReadBinary function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadBinary().
bool VW::ClassifierUV::ReadXML (std::istream & stream, const std::string & name = "") [inline, virtual, inherited]
Stream in as XML style ASCII.
Implements VW::IOObject.
References c, VW::ClassifierUV::classifier_matrix, VW::ClassifierUV::columns, VW::FindXMLBlock(), VW::GetXMLBlockAsNumber(), VW::ClassifierUV::prob_matrix, VW::ClassifierUV::Reset(), and VW::ClassifierUV::rows.
bool VW::IOObject::ReadXMLFile (const std::string & filename, const std::string & name = "") [virtual, inherited]
Open a file and input as XML style ASCII.
Open a file and read as XML-style ASCII.
Once the file is open, the child class's ReadXML function is used to read the content.
Parameters:
filename the name of the file to open
name the optional name tag-attribute to match ie. data must start <MyClass name="name">
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadXML().
Referenced by VW::ClassifierUV::ClassifierUV(), and VW::FirewireCameraGTK::LoadParameterFile().
void VW::ClassifierUV::Reset (unsigned int new_bin_size = 1, unsigned int new_num_classes = 0) [inherited]
Set to a new size (and fill with CLASSIFIER_OTHER).
References c, VW::ClassifierUV::classifier_matrix, VW::ClassifierUV::columns, VW::ClassifierUV::my_bin_size, VW::ClassifierUV::num_classes, VW::ClassifierUV::prob_matrix, VW::ClassifierUV::rows, VW::ClassifierUV::u_scale, and VW::ClassifierUV::v_scale.
Referenced by VW::ClassifierUV::ReadXML().
void VW::InterfaceGTK< ClassifierUVGTKWidget >::SaveOK () [inline, protected, inherited]
void VW::ClassifierUVGTK::SaveParameterFile (std::string filename = ".params") [virtual]
Save into data-file (same as WriteXMLFile()).
Reimplemented from VW::ClassifierUV.
References UpdateForm().
void VW::InterfaceGTK< ClassifierUVGTKWidget >::SaveStart () [inline, protected, inherited]
void VW::InterfaceGTK< ClassifierUVGTKWidget >::Show (void) [inline, inherited]
void VW::ClassifierUVGTK::UpdateForm () [virtual]
Implements VW::InterfaceGTK< ClassifierUVGTKWidget >.
References _param_file, VW::ClassifierUVGTKWidget::filename, and VW::InterfaceGTK< ClassifierUVGTKWidget >::my_widget.
Referenced by LoadParameterFile(), and SaveParameterFile().
void VW::ClassifierUVGTK::UpdateFromForm ()
bool VW::ClassifierUV::WriteASCII (std::ostream & stream) const [inline, virtual, inherited]
Stream out as plain ASCII.
Implements VW::IOObject.
bool VW::IOObject::WriteASCIIFile (const std::string & filename) const [inherited]
Open a file and output as plain ASCII (overwriting any existing contents).
Open a file and output as plain ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteASCII function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteASCII().
bool VW::ClassifierUV::WriteBinary (std::ostream & stream) const [inline, virtual, inherited]
Stream out as binary.
Implements VW::IOObject.
bool VW::IOObject::WriteBinaryFile (const std::string & filename) const [inherited]
Open a file and output as binary (overwriting any existing contents).
Once the file is open, the child class's WriteBinary function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteBinary().
bool VW::ClassifierUV::WriteXML (std::ostream & stream, const std::string & name = "") const [inline, virtual, inherited]
Stream out as XML style ASCII.
Implements VW::IOObject.
bool VW::IOObject::WriteXMLFile (const std::string & filename, const std::string & name = "") const [inherited]
Open a file and output as XML-style ASCII (overwriting any existing contents).
Open a file and output as XML-style ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteXML function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
name the tag parameter, if required
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteXML().
Referenced by VW::FirewireCameraGTK::SaveParameterFile().
Member Data Documentation
std::string VW::ClassifierUVGTK::_param_file [protected]
Referenced by LoadParameterFile(), and UpdateForm().
unsigned int** VW::ClassifierUV::classifier_matrix [protected, inherited]
Referenced by VW::ClassifierUV::Classify(), VW::ClassifierUV::GetClassifierMatrix(), VW::ClassifierUV::GetHistogramAsImage(), VW::ClassifierUV::ReadXML(), VW::ClassifierUV::Reset(), and VW::ClassifierUV::~ClassifierUV().
unsigned int VW::ClassifierUV::columns [protected, inherited]
Referenced by VW::ClassifierUV::GetHistogramAsImage(), VW::ClassifierUV::ReadXML(), and VW::ClassifierUV::Reset().
Gtk::FileSelection* VW::InterfaceGTK< ClassifierUVGTKWidget >::file_selector [protected, inherited]
SigC::Signal1<void,std::string> VW::InterfaceGTK< ClassifierUVGTKWidget >::LoadEvent [protected, inherited]
unsigned int VW::ClassifierUV::my_bin_size [protected, inherited]
Referenced by VW::ClassifierUV::Reset().
std::string VW::InterfaceGTK< ClassifierUVGTKWidget >::my_name [protected, inherited]
Referenced by ClassifierUVGTK().
VW::InterfaceType VW::InterfaceGTK< ClassifierUVGTKWidget >::my_type [protected, inherited]
Referenced by ClassifierUVGTK().
ClassifierUVGTKWidget * VW::InterfaceGTK< ClassifierUVGTKWidget >::my_widget [protected, inherited]
Referenced by ClassifierUVGTK(), and UpdateForm().
Gtk::Window* VW::InterfaceGTK< ClassifierUVGTKWidget >::my_window [protected, inherited]
unsigned int VW::ClassifierUV::num_classes [protected, inherited]
Referenced by VW::ClassifierUV::Reset(), and VW::ClassifierUV::~ClassifierUV().
std::vector<float**> VW::ClassifierUV::prob_matrix [protected, inherited]
Referenced by VW::ClassifierUV::GetProb(), VW::ClassifierUV::ReadXML(), VW::ClassifierUV::Reset(), and VW::ClassifierUV::~ClassifierUV().
unsigned int VW::ClassifierUV::rows [protected, inherited]
Referenced by VW::ClassifierUV::GetHistogramAsImage(), VW::ClassifierUV::ReadXML(), VW::ClassifierUV::Reset(), and VW::ClassifierUV::~ClassifierUV().
SigC::Signal1<void,std::string> VW::InterfaceGTK< ClassifierUVGTKWidget >::SaveEvent [protected, inherited]
float VW::ClassifierUV::u_scale [protected, inherited]
Referenced by VW::ClassifierUV::Classify(), VW::ClassifierUV::GetProb(), and VW::ClassifierUV::Reset().
float VW::ClassifierUV::v_scale [protected, inherited]
Referenced by VW::ClassifierUV::Classify(), VW::ClassifierUV::GetProb(), and VW::ClassifierUV::Reset().
The documentation for this class was generated from the following files:
classifieruvgtk.h
classifieruvgtk.cpp