VW: VNL::MatrixFixed< m, n, T > Class Template Reference
VNL::MatrixFixed< m, n, T > Class Template Reference
Fixed size matrix.
#include <matrixfixed.h>
Public Types
typedef CVector< T >::abs_t abs_t
Type def for norms.
typedef T element_type
typedef T * iterator
Iterators.
typedef T const * const_iterator
Const iterators.
Public Member Functions
MatrixFixed ()
Construct an empty m*n matrix.
MatrixFixed (const T &value)
Construct an m*n matrix and fill with value.
MatrixFixed (const T *datablck)
Construct an m*n Matrix and copy data into it row-wise.
MatrixFixed (const Matrix< T > &rhs)
Construct an m*n Matrix and copy rhs into it.
~MatrixFixed ()
MatrixFixed< m, n, T > & operator= (const Matrix< T > &rhs)
Copy a vnl_matrix into this.
MatrixFixed< m, n, T > & operator= (const MatrixFixed< m, n, T > &rhs)
Copy another MatrixFixed<m,n,T> into this.
MatrixFixed (const MatrixFixed< m, n, T > &rhs)
bool resize (unsigned int, unsigned int)
Resizing a vnl_matrix_ref fails.
unsigned Rows () const
Return number of rows.
unsigned Columns () const
Return number of columns.
unsigned Cols () const
Return number of columns.
unsigned Size () const
Return number of elements.
unsigned size () const
Return number of elements.
void Put (unsigned r, unsigned c, T const &)
set element with boundary checks if error checking is on.
T Get (unsigned r, unsigned c) const
get element with boundary checks if error checking is on.
T * operator[] (unsigned r)
return pointer to given row.
T const * operator[] (unsigned r) const
return pointer to given row.
T & operator() (unsigned r, unsigned c)
Access an element for reading or writing.
T const & operator() (unsigned r, unsigned c) const
Access an element for reading.
void Fill (T const &)
Set all elements of matrix to specified value.
void FillDiagonal (T const &)
Set all diagonal elements of matrix to specified value.
void CopyIn (T const *)
Fill (laminate) this matrix with the given data.
void Set (T const *d)
Fill (laminate) this matrix with the given data.
void CopyOut (T *) const
Fill the given array with this matrix.
Matrix< T > & operator+= (T value)
Add rhs to each element of lhs matrix in situ.
Matrix< T > & operator+= (Matrix< T > const &)
Add rhs to lhs matrix in situ.
Matrix< T > & operator-= (T value)
Subtract rhs from each element of lhs matrix in situ.
Matrix< T > & operator-= (Matrix< T > const &)
Subtract rhs from lhs matrix in situ.
Matrix< T > & operator*= (T value)
Scalar multiplication in situ of lhs matrix by rhs.
Matrix< T > & operator*= (Matrix< T > const &rhs)
Multiply lhs matrix in situ by rhs.
Matrix< T > & operator/= (T value)
Scalar division of lhs matrix in situ by rhs.
Matrix< T > operator- () const
Negate all elements of matrix.
Matrix< T > operator- (T const &v) const
Subtract rhs from each element of lhs matrix and return result in new matrix.
Matrix< T > operator- (Matrix< T > const &rhs) const
Matrix subtract rhs from lhs and return result in new matrix.
Matrix< T > operator+ (T const &v) const
Add rhs to each element of lhs matrix and return result in new matrix.
Matrix< T > operator+ (Matrix< T > const &rhs) const
Matrix add rhs to lhs matrix and return result in new matrix.
Matrix< T > operator* (T const &v) const
Scalar multiplication of lhs matrix by rhs and return result in new matrix.
Matrix< T > operator* (Matrix< T > const &rhs) const
Matrix multiply lhs by rhs matrix and return result in new matrix.
Matrix< T > operator/ (T const &v) const
Scalar division of lhs matrix by rhs and return result in new matrix.
Matrix< T > Apply (T(*f)(T)) const
Make a new matrix by applying function to each element.
Matrix< T > Apply (T(*f)(T const &)) const
Make a new matrix by applying function to each element.
Matrix< T > Transpose () const
Return transpose.
Matrix< T > ConjugateTranspose () const
Return conjugate transpose.
Matrix< T > & Update (Matrix< T > const &, unsigned top=0, unsigned left=0)
Set values of this matrix to those of M, starting at [top,left].
void SetColumn (unsigned i, T const *v)
Set the elements of the i'th column to v[j] (No bounds checking).
void SetColumn (unsigned i, T value)
Set the elements of the i'th column to value.
void SetColumn (unsigned j, Vector< T > const &v)
Set j-th colum to v.
void SetColumns (unsigned starting_column, Matrix< T > const &M)
Set columns to those in M, starting at starting_column.
void SetRow (unsigned i, T const *v)
Set the elements of the i'th row to v[j] (No bounds checking).
void SetRow (unsigned i, T value)
Set the elements of the i'th row to value.
void SetRow (unsigned i, Vector< T > const &)
Set the i-th row.
Matrix< T > Extract (unsigned rows, unsigned cols, unsigned top=0, unsigned left=0) const
Extract a sub-matrix of size rows x cols, starting at (top,left).
Vector< T > GetRow (unsigned row) const
Get a vector equal to the given row.
Vector< T > GetColumn (unsigned col) const
Get a vector equal to the given column.
Matrix< T > GetNRows (unsigned rowstart, unsigned n) const
Get n rows beginning at rowstart.
Matrix< T > GetNColumns (unsigned colstart, unsigned n) const
Get n columns beginning at colstart.
void SetIdentity (T val=T(1))
Set this matrix to an identity (or diagonal) matrix.
void InplaceTranspose ()
Transpose this matrix efficiently.
void FlipUD ()
Reverse order of rows.
void FlipLR ()
Reverse order of columns.
void NormalizeRows ()
Normalize each row so it is a unit vector.
void NormalizeColumns ()
Normalize each column so it is a unit vector.
void ScaleRow (unsigned row, T value)
Scale elements in given row by a factor of T.
void ScaleColumn (unsigned col, T value)
Scale elements in given column by a factor of T.
void Swap (Matrix< T > &that)
Swap this matrix with that matrix.
abs_t ArrayOneNorm () const
Return sum of absolute values of elements.
abs_t ArrayTwoNorm () const
Return square root of sum of squared absolute element values.
abs_t ArrayInfNorm () const
Return largest absolute element value.
abs_t AbsoluteValueSum () const
Return sum of absolute values of elements.
abs_t AbsoluteValueMax () const
Return largest absolute value.
abs_t operatorOneNorm () const
abs_t operatorInfNorm () const
abs_t FrobeniusNorm () const
Return frobenius norm of matrix (sqrt of sum of squares of its elements).
abs_t FroNorm () const
Return frobenius norm of matrix (sqrt of sum of squares of its elements).
abs_t RMS () const
Return RMS of all elements.
T MinValue () const
Return minimum value of elements.
T MaxValue () const
Return maximum value of elements.
T Mean () const
Return mean of all matrix elements.
bool IsEmpty () const
Return true iff the size is zero.
bool IsIdentity () const
Return true if all elements equal to identity.
bool IsIdentity (double tol) const
Return true if all elements equal to identity, within given tolerance.
bool IsZero () const
Return true if all elements equal to zero.
bool IsZero (double tol) const
Return true if all elements equal to zero, within given tolerance.
bool IsFinite () const
Return true if finite.
bool HasNaNs () const
Return true if matrix contains NaNs.
void assert_size (unsigned rows, unsigned cols) const
abort if size is not as expected.
void assert_finite () const
abort if matrix containins any INFs or NANs.
bool ReadASCII (std::istream &s)
Read a Matrix from an ascii std::istream.
T const * DataBlock () const
Access the contiguous block storing the elements in the matrix row-wise. O(1).
T * DataBlock ()
Access the contiguous block storing the elements in the matrix row-wise. O(1).
T const *const * DataArray () const
Access the 2D array, so that elements can be accessed with array[row][col] directly.
T ** DataArray ()
Access the 2D array, so that elements can be accessed with array[row][col] directly.
iterator begin ()
Iterator pointing to start of data.
const_iterator begin () const
Iterator pointing to start of data.
iterator end ()
Iterator pointing to element beyond end of data.
const_iterator end () const
Iterator pointing to element beyond end of data.
bool operator_eq (Matrix< T > const &rhs) const
Return true if *this == rhs.
bool operator== (Matrix< T > const &that) const
Equality operator.
bool operator!= (Matrix< T > const &that) const
Inequality operator.
void print (std::ostream &os) const
Print matrix to os in some hopefully sensible format.
void Clear ()
Make the matrix as if it had been default-constructed.
bool Resize (unsigned r, unsigned c)
Resize to r rows by c columns. Old data lost.
Static Public Member Functions
static Matrix< T > Read (std::istream &s)
Read a Matrix from an ascii std::istream.
Protected Member Functions
void assert_size_internal (unsigned rows, unsigned cols) const
Abort unless M has the given size.
void assert_finite_internal () const
Abort if any element of M is inf or nan.
void destroy ()
Delete data.
Static Protected Member Functions
static void inline_function_tickler ()
Protected Attributes
unsigned num_rows
unsigned num_cols
T ** data
Detailed Description
template<int m, int n, class T = double>
class VNL::MatrixFixed< m, n, T >
Fixed size matrix.
A subclass of vnl_matrix_fixed_ref, all storage is local and all vnl_matrix operations are valid.
Member Typedef Documentation
template<class T = double> typedef CVector<T>::abs_t VNL::Matrix< T >::abs_t [inherited]
Type def for norms.
template<class T = double> typedef T const* VNL::Matrix< T >::const_iterator [inherited]
Const iterators.
template<class T = double> typedef T VNL::Matrix< T >::element_type [inherited]
template<class T = double> typedef T* VNL::Matrix< T >::iterator [inherited]
Iterators.
Constructor & Destructor Documentation
template<int m, int n, class T = double> VNL::MatrixFixed< m, n, T >::MatrixFixed () [inline]
Construct an empty m*n matrix.
template<int m, int n, class T = double> VNL::MatrixFixed< m, n, T >::MatrixFixed (const T & value) [inline]
Construct an m*n matrix and fill with value.
template<int m, int n, class T = double> VNL::MatrixFixed< m, n, T >::MatrixFixed (const T * datablck) [inline]
Construct an m*n Matrix and copy data into it row-wise.
template<int m, int n, class T = double> VNL::MatrixFixed< m, n, T >::MatrixFixed (const Matrix< T > & rhs) [inline]
Construct an m*n Matrix and copy rhs into it.
Abort if rhs is not the same size.
template<int m, int n, class T = double> VNL::MatrixFixed< m, n, T >::~MatrixFixed () [inline]
template<int m, int n, class T = double> VNL::MatrixFixed< m, n, T >::MatrixFixed (const MatrixFixed< m, n, T > & rhs) [inline]
Member Function Documentation
template<class T = double> abs_t VNL::Matrix< T >::AbsoluteValueMax () const [inline, inherited]
Return largest absolute value.
template<class T = double> abs_t VNL::Matrix< T >::AbsoluteValueSum () const [inline, inherited]
Return sum of absolute values of elements.
template<class T> VNL::Matrix< T > VNL::Matrix< T >::Apply (T(*)(T const &) f) const [inline, inherited]
Make a new matrix by applying function to each element.
Return the matrix made by applying "f" to each element.
References VNL::Matrix< T >::Apply(), VNL::Matrix< T >::data, VNL::Matrix< T >::DataBlock(), and VNL::Matrix< T >::num_cols.
template<class T> VNL::Matrix< T > VNL::Matrix< T >::Apply (T(*)(T) f) const [inline, inherited]
Make a new matrix by applying function to each element.
Return the matrix made by applying "f" to each element.
References VNL::Matrix< T >::data, VNL::Matrix< T >::DataBlock(), and VNL::Matrix< T >::num_cols.
Referenced by VNL::Matrix< T >::Apply().
template<class T = double> abs_t VNL::Matrix< T >::ArrayInfNorm () const [inline, inherited]
Return largest absolute element value.
Referenced by VNL::Matrix< std::complex< double > >::AbsoluteValueMax().
template<class T = double> abs_t VNL::Matrix< T >::ArrayOneNorm () const [inline, inherited]
Return sum of absolute values of elements.
Referenced by VNL::Matrix< std::complex< double > >::AbsoluteValueSum().
template<class T = double> abs_t VNL::Matrix< T >::ArrayTwoNorm () const [inline, inherited]
Return square root of sum of squared absolute element values.
template<class T = double> void VNL::Matrix< T >::assert_finite () const [inline, inherited]
abort if matrix containins any INFs or NANs.
This function does or tests nothing if NDEBUG is defined
Referenced by VNL::SVD< T >::SVD(), and VNL::SymmetricEigensystemCompute().
template<class T > void VNL::Matrix< T >::assert_finite_internal () const [inline, protected, inherited]
Abort if any element of M is inf or nan.
References VNL::Matrix< T >::Columns(), VNL::IsFinite(), VNL::Matrix< T >::IsFinite(), and VNL::Matrix< T >::Rows().
Referenced by VNL::Matrix< std::complex< double > >::assert_finite().
template<class T = double> void VNL::Matrix< T >::assert_size (unsigned rows, unsigned cols) const [inline, inherited]
abort if size is not as expected.
This function does or tests nothing if NDEBUG is defined
Referenced by VNL::Adjugate(), VNL::ComplexEigensystem::ComplexEigensystem(), and VNL::MatrixExp().
template<class T > void VNL::Matrix< T >::assert_size_internal (unsigned rows, unsigned cols) const [inline, protected, inherited]
Abort unless M has the given size.
References VNL::Matrix< T >::Columns(), and VNL::Matrix< T >::Rows().
Referenced by VNL::Matrix< std::complex< double > >::assert_size().
template<class T = double> const_iterator VNL::Matrix< T >::begin () const [inline, inherited]
Iterator pointing to start of data.
template<class T = double> iterator VNL::Matrix< T >::begin () [inline, inherited]
Iterator pointing to start of data.
Referenced by VNL::Matrix< std::complex< double > >::ArrayInfNorm(), VNL::Matrix< std::complex< double > >::ArrayOneNorm(), VNL::Matrix< std::complex< double > >::ArrayTwoNorm(), VNL::ComplexEigensystem::ComplexEigensystem(), VNL::Matrix< T >::ConjugateTranspose(), VNL::Matrix< std::complex< double > >::FrobeniusNorm(), VNL::GeneralizedSchur(), VNL::Matrix< std::complex< double > >::MaxValue(), VNL::Matrix< std::complex< double > >::Mean(), VNL::Matrix< std::complex< double > >::MinValue(), VNL::Matrix< std::complex< double > >::RMS(), and vnl_complexify().
template<class T > void VNL::Matrix< T >::Clear () [inline, inherited]
Make the matrix as if it had been default-constructed.
References VNL::Matrix< T >::data, VNL::Matrix< T >::destroy(), VNL::Matrix< T >::num_cols, and VNL::Matrix< T >::num_rows.
Referenced by VNL::BinaryLoad(), and VNL::Matrix< T >::operator=().
template<class T = double> unsigned VNL::Matrix< T >::Cols () const [inline, inherited]
Return number of columns.
A synonym for columns()
Referenced by VNL::BinarySave(), VNL::GeneralizedSchur(), VNL::MatlabReadOrDie(), VNL::MatrixExp(), VNL::Matrix< std::complex< double > >::operator()(), VW::Homography2DCovariance::operator=(), VW::FMatrixAffineCovariance::operator=(), VW::FMatrixAffine::operator=(), VW::FMatrixCovariance::operator=(), operator==(), VNL::RealNPolynomial::Set(), VNL::Matrix< std::complex< double > >::size(), VNL::Matrix< std::complex< double > >::Size(), VNL::SymMatrix< T >::SymMatrix(), VNL::Trace(), and VNL::MatlabFilewrite::Write().
template<class T = double> unsigned VNL::Matrix< T >::Columns () const [inline, inherited]
Return number of columns.
A synonym for cols()
Referenced by vnl_fastops::AB(), vnl_fastops::ABt(), VNL::Adjugate(), VNL::Matrix< T >::assert_finite_internal(), VNL::Matrix< T >::assert_size_internal(), vnl_fastops::AtA(), vnl_fastops::AtB(), vnl_matops::cat(), VNL::Cholesky< T >::Cholesky(), vnl_fastops::dec_X_by_ABt(), vnl_fastops::dec_X_by_AtB(), VNL::Determinant(), VNL::LeastSquaresFunction::FDGradF(), VNL::Matrix< T >::FlipLR(), VNL::Matrix< T >::FlipUD(), GetRowEchelonForm(), VNL::LeastSquaresCostFunction::GradF(), VNL::Matrix< T >::HasNaNs(), vnl_fastops::inc_X_by_AtA(), vnl_fastops::inc_X_by_AtB(), VNL::Matrix< T >::InplaceTranspose(), VNL::Matrix< T >::IsFinite(), VNL::Matrix< T >::IsIdentity(), VNL::Matrix< T >::IsZero(), VNL::MatlabPrint(), VNL::MatrixFixed< 9, 9, double >::MatrixFixed(), VNL::Transpose::operator*(), VNL::operator*(), VW::ProjectionMatrix::operator=(), VNL::MatrixFixedRef< m, n, float >::operator=(), VNL::MatrixFixed< 9, 9, double >::operator=(), VW::Homography2D::operator=(), VW::FMatrix::operator=(), VW::EssentialMatrix::operator=(), VNL::Vector< T >::PostMultiply(), VNL::Vector< T >::PreMultiply(), VNL::Matrix< T >::print(), VW::ProjectionMatrix::ProjectionMatrix(), VNL::QR< T >::QR(), VNL::Matrix< T >::ReadASCII(), VNL::RealEigensystem::RealEigensystem(), VNL::SVD< T >::Solve(), VNL::SVD< T >::SVD(), VNL::SymmetricEigensystemCompute(), vnl_matops::vcat(), VNL::Vector< T >::Vector(), vnl_complexify(), vnl_discrete_diff_fwd(), vnl_discrete_diff_sym(), and vnl_fortran_copy< T >::vnl_fortran_copy().
template<class T > VNL::Matrix< T > VNL::Matrix< T >::ConjugateTranspose () const [inline, inherited]
Return conjugate transpose.
References VNL::Matrix< T >::begin(), VNL::Matrix< T >::size(), and VNL::Matrix< T >::Transpose().
template<class T> void VNL::Matrix< T >::CopyIn (T const * p) [inline, inherited]
Fill (laminate) this matrix with the given data.
Fill this matrix with the given data.
We assume that p points to a contiguous rows*cols array, stored rowwise.
References VNL::Matrix< T >::data, and VNL::Matrix< T >::num_cols.
Referenced by VW::ComputeFuncs::ConvertParamVectorToTransform(), and VNL::Matrix< std::complex< double > >::Set().
template<class T> void VNL::Matrix< T >::CopyOut (T * p) const [inline, inherited]
Fill the given array with this matrix.
We assume that p points to a contiguous rows*cols array, stored rowwise. No bounds checking on the array
We assume that p points to a contiguous rows*cols array, stored rowwise.
References VNL::Matrix< T >::data, and VNL::Matrix< T >::num_cols.
Referenced by VW::ComputeFuncs::ConvertTransformToParamVector().
template<class T = double> T* * VNL::Matrix< T >::DataArray () [inline, inherited]
Access the 2D array, so that elements can be accessed with array[row][col] directly.
2d array, [row][column].
template<class T = double> T const* const* VNL::Matrix< T >::DataArray () const [inline, inherited]
Access the 2D array, so that elements can be accessed with array[row][col] directly.
2d array, [row][column].
Referenced by vnl_fastops::AB(), vnl_fastops::ABt(), vnl_fastops::AtA(), vnl_fastops::AtB(), VNL::BinarySave(), vnl_fastops::dec_X_by_ABt(), vnl_fastops::dec_X_by_AtB(), vnl_fastops::inc_X_by_AtA(), vnl_fastops::inc_X_by_AtB(), VNL::MatlabReadOrDie(), and VNL::MatlabFilewrite::Write().
template<class T = double> T* VNL::Matrix< T >::DataBlock () [inline, inherited]
Access the contiguous block storing the elements in the matrix row-wise. O(1).
1d array, row-major order.
template<class T = double> T const* VNL::Matrix< T >::DataBlock () const [inline, inherited]
Access the contiguous block storing the elements in the matrix row-wise. O(1).
1d array, row-major order.
Referenced by VNL::Matrix< T >::Apply(), VNL::BinaryLoad(), VNL::BinarySave(), VW::ParametricFlowNonLin::Compute(), VNL::Cholesky< T >::Determinant(), VNL::Matrix< T >::InplaceTranspose(), VNL::Cholesky< T >::Inverse(), VNL::MatrixFixed< 9, 9, double >::MatrixFixed(), VNL::LevenbergMarquardt::MinimizeUsingGradient(), VNL::LevenbergMarquardt::MinimizeWithoutGradient(), VNL::MatrixFixedRef< m, n, float >::operator=(), VNL::MatrixFixed< 9, 9, double >::operator=(), VW::Homography2DCovariance::operator=(), VW::FMatrixAffineCovariance::operator=(), VW::FMatrixCovariance::operator=(), VNL::RealEigensystem::RealEigensystem(), and VNL::SymmetricEigensystemCompute().
template<class T > void VNL::Matrix< T >::destroy () [inline, protected, inherited]
Delete data.
Frees up the dynamic storage used by matrix.
O(m*n).
References vnl_matrix_free_blah.
Referenced by VNL::Matrix< T >::Clear(), and VNL::Matrix< std::complex< double > >::~Matrix().
template<class T = double> const_iterator VNL::Matrix< T >::end () const [inline, inherited]
Iterator pointing to element beyond end of data.
template<class T = double> iterator VNL::Matrix< T >::end () [inline, inherited]
Iterator pointing to element beyond end of data.
Referenced by VNL::GeneralizedSchur().
template<class T > VNL::Matrix< T > VNL::Matrix< T >::Extract (unsigned rowz, unsigned colz, unsigned top = 0, unsigned left = 0) const [inline, inherited]
Extract a sub-matrix of size rows x cols, starting at (top,left).
Returns a copy of submatrix of THIS matrix, specified by the top-left corner and size in rows, cols. O(m*n).
Thus it contains elements [top,top+rows-1][left,left+cols-1]
Use update() to copy new values of this submatrix back into THIS matrix.
References VNL::Matrix< T >::data, VNL::ErrorMatrixDimension(), and VNL::Matrix< T >::num_cols.
template<class T> void VNL::Matrix< T >::Fill (T const & value) [inline, inherited]
Set all elements of matrix to specified value.
Sets all elements of matrix to specified value. O(m*n).
Complexity
References VNL::Matrix< T >::data, VNL::Matrix< T >::num_cols, and VNL::Matrix< T >::num_rows.
Referenced by VW::Covariance2D::CholeskyDecompose(), and VNL::Matrix< std::complex< double > >::operator=().
template<class T> void VNL::Matrix< T >::FillDiagonal (T const & value) [inline, inherited]
Set all diagonal elements of matrix to specified value.
Sets all diagonal elements of matrix to specified value. O(n).
Complexity
References VNL::Matrix< T >::data, VNL::Matrix< T >::num_cols, and VNL::Matrix< T >::num_rows.
template<class T > void VNL::Matrix< T >::FlipLR () [inline, inherited]
Reverse order of columns.
References c, VNL::Matrix< T >::Columns(), and VNL::Matrix< T >::Rows().
template<class T > void VNL::Matrix< T >::FlipUD () [inline, inherited]
Reverse order of rows.
Reverse order of rows. Name is from Matlab, meaning "flip upside down".
References c, VNL::Matrix< T >::Columns(), and VNL::Matrix< T >::Rows().
template<class T = double> abs_t VNL::Matrix< T >::FrobeniusNorm () const [inline, inherited]
Return frobenius norm of matrix (sqrt of sum of squares of its elements).
Referenced by VW::ComputeFuncs::ConvertParamVectorToTransform(), VW::ComputeFuncs::ConvertTransformToParamVector(), VNL::Matrix< std::complex< double > >::FroNorm(), VW::FMatrixCompute::GenerateParameterVector(), VW::FMPlanarCompute::GenerateParameterVectorHZ(), VW::FMPlanarCompute::GenerateParameterVectorHZJK(), VW::FMPlanarCompute::GenerateParameterVectorVLJK(), VW::FMPlanarCompute::ReconstructTransformHZ(), VW::FMPlanarCompute::ReconstructTransformHZJK(), VW::FMPlanarCompute::ReconstructTransformVLJK(), and VNL::SVD< T >::SVD().
template<class T = double> abs_t VNL::Matrix< T >::FroNorm () const [inline, inherited]
Return frobenius norm of matrix (sqrt of sum of squares of its elements).
template<class T > T VNL::Matrix< T >::Get (unsigned row, unsigned column) const [inline, inherited]
get element with boundary checks if error checking is on.
get -- Returns the value of the element at specified row and column. O(1).
Checks for valid range of indices.
References VNL::Matrix< T >::data, VNL::Matrix< T >::num_cols, and VNL::Matrix< T >::num_rows.
template<class T > VNL::Vector< T > VNL::Matrix< T >::GetColumn (unsigned col) const [inline, inherited]
Get a vector equal to the given column.
Create a vector out of column[column_index].
References VNL::Matrix< T >::data, VNL::ErrorMatrixColIndex(), VNL::Matrix< T >::num_cols, and v.
Referenced by VNL::Determinant().
template<class T > VNL::Matrix< T > VNL::Matrix< T >::GetNColumns (unsigned colstart, unsigned n) const [inline, inherited]
Get n columns beginning at colstart.
Returns a copy of n columns, starting from "column".
References c, VNL::Matrix< T >::data, VNL::ErrorMatrixColIndex(), and VNL::Matrix< T >::num_cols.
Referenced by VNL::GeneralizedEigensystem::GeneralizedEigensystem().
template<class T > VNL::Matrix< T > VNL::Matrix< T >::GetNRows (unsigned rowstart, unsigned n) const [inline, inherited]
Get n rows beginning at rowstart.
Returns a copy of n rows, starting from "row".
References VNL::Matrix< T >::data, VNL::ErrorMatrixRowIndex(), and VNL::Matrix< T >::num_cols.
template<class T > VNL::Vector< T > VNL::Matrix< T >::GetRow (unsigned row) const [inline, inherited]
Get a vector equal to the given row.
Create a vector out of row[row_index].
References VNL::Matrix< T >::data, VNL::ErrorMatrixRowIndex(), VNL::Matrix< T >::num_cols, and v.
Referenced by VNL::Determinant(), GetRowEchelonForm(), VNL::ComplexEigensystem::LeftEigenVector(), and VNL::ComplexEigensystem::RightEigenVector().
template<class T > bool VNL::Matrix< T >::HasNaNs () const [inline, inherited]
Return true if matrix contains NaNs.
Return true if any element of (*this) is nan.
References VNL::Matrix< T >::Columns(), VNL::IsNaN(), and VNL::Matrix< T >::Rows().
template<class T > void VNL::Matrix< T >::inline_function_tickler () [inline, static, protected, inherited]
template<class T > void VNL::Matrix< T >::InplaceTranspose () [inline, inherited]
Transpose this matrix efficiently.
Transpose matrix M in place.
Works for rectangular matrices using an enormously clever algorithm from ACM TOMS.
References VNL::Matrix< T >::Columns(), VNL::Matrix< T >::data, VNL::Matrix< T >::DataBlock(), VNL::Matrix< T >::num_cols, and VNL::Matrix< T >::Rows().
Referenced by VNL::LevenbergMarquardt::lmder_lsqfun().
template<class T = double> bool VNL::Matrix< T >::IsEmpty () const [inline, inherited]
Return true iff the size is zero.
template<class T > bool VNL::Matrix< T >::IsFinite () const [inline, inherited]
Return true if finite.
Return false if any element of (*this) is inf or nan.
References VNL::Matrix< T >::Columns(), VNL::IsFinite(), and VNL::Matrix< T >::Rows().
Referenced by VNL::Matrix< T >::assert_finite_internal().
template<class T > bool VNL::Matrix< T >::IsIdentity (double tol) const [inline, inherited]
Return true if all elements equal to identity, within given tolerance.
Return true if maximum absolute deviation of M from identity is <= tol.
References VNL::Abs(), VNL::Matrix< T >::Columns(), and VNL::Matrix< T >::Rows().
template<class T > bool VNL::Matrix< T >::IsIdentity () const [inline, inherited]
Return true if all elements equal to identity.
References VNL::Matrix< T >::Columns(), and VNL::Matrix< T >::Rows().
template<class T > bool VNL::Matrix< T >::IsZero (double tol) const [inline, inherited]
Return true if all elements equal to zero, within given tolerance.
Return true if max(abs((*this))) <= tol.
References VNL::Abs(), VNL::Matrix< T >::Columns(), and VNL::Matrix< T >::Rows().
template<class T > bool VNL::Matrix< T >::IsZero () const [inline, inherited]
Return true if all elements equal to zero.
References VNL::Matrix< T >::Columns(), and VNL::Matrix< T >::Rows().
template<class T = double> T VNL::Matrix< T >::MaxValue () const [inline, inherited]
Return maximum value of elements.
Referenced by VNL::Matrix< std::complex< double > >::MaxValue(), and VNL::RealNPolynomial::Set().
template<class T = double> T VNL::Matrix< T >::Mean () const [inline, inherited]
Return mean of all matrix elements.
Referenced by vnl_matops::homg_diff(), and VNL::Matrix< std::complex< double > >::Mean().
template<class T = double> T VNL::Matrix< T >::MinValue () const [inline, inherited]
Return minimum value of elements.
Referenced by VNL::Matrix< std::complex< double > >::MinValue().
template<class T > void VNL::Matrix< T >::NormalizeColumns () [inline, inherited]
Normalize each column so it is a unit vector.
Make each column of the matrix have unit norm.
Zero columns are ignored
All-zero columns are ignored.
References VNL::Matrix< T >::data, VNL::Matrix< T >::num_cols, std::sqrt(), and VNL::SquaredMagnitude().
template<class T > void VNL::Matrix< T >::NormalizeRows () [inline, inherited]
Normalize each row so it is a unit vector.
Make each row of the matrix have unit norm.
Zero rows are ignored
All-zero rows are ignored.
References VNL::Matrix< T >::data, VNL::Matrix< T >::num_cols, std::sqrt(), and VNL::SquaredMagnitude().
template<class T = double> bool VNL::Matrix< T >::operator!= (Matrix< T > const & that) const [inline, inherited]
Inequality operator.
template<class T = double> T const& VNL::Matrix< T >::operator() (unsigned r, unsigned c) const [inline, inherited]
Access an element for reading.
There are assert style boundary checks - define NDEBUG to turn them off.
template<class T = double> T& VNL::Matrix< T >::operator() (unsigned r, unsigned c) [inline, inherited]
Access an element for reading or writing.
There are assert style boundary checks - define NDEBUG to turn them off.
template<class T = double> Matrix<T> VNL::Matrix< T >::operator* (Matrix< T > const & rhs) const [inline, inherited]
Matrix multiply lhs by rhs matrix and return result in new matrix.
template<class T = double> Matrix<T> VNL::Matrix< T >::operator* (T const & v) const [inline, inherited]
Scalar multiplication of lhs matrix by rhs and return result in new matrix.
template<class T = double> Matrix<T>& VNL::Matrix< T >::operator*= (Matrix< T > const & rhs) [inline, inherited]
Multiply lhs matrix in situ by rhs.
template<class T> VNL::Matrix< T > & VNL::Matrix< T >::operator*= (T value) [inline, inherited]
Scalar multiplication in situ of lhs matrix by rhs.
References VNL::Matrix< T >::data, VNL::Matrix< T >::num_cols, and VNL::Matrix< T >::num_rows.
template<class T = double> Matrix<T> VNL::Matrix< T >::operator+ (Matrix< T > const & rhs) const [inline, inherited]
Matrix add rhs to lhs matrix and return result in new matrix.
template<class T = double> Matrix<T> VNL::Matrix< T >::operator+ (T const & v) const [inline, inherited]
Add rhs to each element of lhs matrix and return result in new matrix.
template<class T> VNL::Matrix< T > & VNL::Matrix< T >::operator+= (Matrix< T > const & rhs) [inline, inherited]
Add rhs to lhs matrix in situ.
Adds lhs matrix with rhs matrix, and stores in place in lhs matrix.
O(m*n). The dimensions of the two matrices must be identical.
References VNL::Matrix< T >::data, VNL::ErrorMatrixDimension(), VNL::Matrix< T >::num_cols, and VNL::Matrix< T >::num_rows.
template<class T> VNL::Matrix< T > & VNL::Matrix< T >::operator+= (T value) [inline, inherited]
Add rhs to each element of lhs matrix in situ.
References VNL::Matrix< T >::data, VNL::Matrix< T >::num_cols, and VNL::Matrix< T >::num_rows.
template<class T = double> Matrix<T> VNL::Matrix< T >::operator- (Matrix< T > const & rhs) const [inline, inherited]
Matrix subtract rhs from lhs and return result in new matrix.
template<class T = double> Matrix<T> VNL::Matrix< T >::operator- (T const & v) const [inline, inherited]
Subtract rhs from each element of lhs matrix and return result in new matrix.
template<class T > VNL::Matrix< T > VNL::Matrix< T >::operator- () const [inline, inherited]
Negate all elements of matrix.
Returns new matrix which is the negation of THIS matrix.
O(m*n).
References VNL::Matrix< T >::data, and VNL::Matrix< T >::num_cols.
template<class T> VNL::Matrix< T > & VNL::Matrix< T >::operator-= (Matrix< T > const & rhs) [inline, inherited]
Subtract rhs from lhs matrix in situ.
Substract lhs matrix with rhs matrix and store in place in lhs matrix.
O(m*n). The dimensions of the two matrices must be identical.
References VNL::Matrix< T >::data, VNL::ErrorMatrixDimension(), VNL::Matrix< T >::num_cols, and VNL::Matrix< T >::num_rows.
template<class T> VNL::Matrix< T > & VNL::Matrix< T >::operator-= (T value) [inline, inherited]
Subtract rhs from each element of lhs matrix in situ.
References VNL::Matrix< T >::data, VNL::Matrix< T >::num_cols, and VNL::Matrix< T >::num_rows.
template<class T = double> Matrix<T> VNL::Matrix< T >::operator/ (T const & v) const [inline, inherited]
Scalar division of lhs matrix by rhs and return result in new matrix.
template<class T> VNL::Matrix< T > & VNL::Matrix< T >::operator/= (T value) [inline, inherited]
Scalar division of lhs matrix in situ by rhs.
References VNL::Matrix< T >::data, VNL::Matrix< T >::num_cols, and VNL::Matrix< T >::num_rows.
template<int m, int n, class T = double> MatrixFixed<m,n,T>& VNL::MatrixFixed< m, n, T >::operator= (const MatrixFixed< m, n, T > & rhs) [inline]
Copy another MatrixFixed<m,n,T> into this.
Reimplemented from VNL::Matrix< T >.
template<int m, int n, class T = double> MatrixFixed<m,n,T>& VNL::MatrixFixed< m, n, T >::operator= (const Matrix< T > & rhs) [inline]
Copy a vnl_matrix into this.
Abort if rhs is not the same size.
Reimplemented from VNL::MatrixFixedRef< m, n, T >.
Reimplemented in VW::EssentialMatrix, VW::FMatrix, VW::FMatrixCovariance, VW::FMatrixAffineCovariance, VW::Homography2DCovariance, and VW::ProjectionMatrix.
template<class T = double> bool VNL::Matrix< T >::operator== (Matrix< T > const & that) const [inline, inherited]
Equality operator.
template<class T = double> T const* VNL::Matrix< T >::operator[] (unsigned r) const [inline, inherited]
return pointer to given row.
No boundary checking here.
template<class T = double> T* VNL::Matrix< T >::operator[] (unsigned r) [inline, inherited]
return pointer to given row.
No boundary checking here.
template<class T> bool VNL::Matrix< T >::operator_eq (VNL::Matrix< T > const & rhs) const [inline, inherited]
Return true if *this == rhs.
Two matrices are equal if and only if they have the same dimensions and the same values.
O(m*n). Elements are compared with operator== as default. Change this default with set_compare() at run time or by specializing Matrix_compare at compile time.
References VNL::Matrix< T >::data, VNL::Matrix< T >::num_cols, and VNL::Matrix< T >::num_rows.
Referenced by VNL::Matrix< std::complex< double > >::operator!=(), and VNL::Matrix< std::complex< double > >::operator==().
template<class T > VNL::Matrix< T >::abs_t VNL::Matrix< T >::operatorInfNorm () const [inline, inherited]
References VNL::Abs(), VNL::Matrix< T >::data, max, and VNL::Matrix< T >::num_cols.
Referenced by VNL::MatrixExp().
template<class T > VNL::Matrix< T >::abs_t VNL::Matrix< T >::operatorOneNorm () const [inline, inherited]
References VNL::Abs(), VNL::Matrix< T >::data, max, and VNL::Matrix< T >::num_cols.
template<class T > void VNL::Matrix< T >::print (std::ostream & os) const [inline, inherited]
Print matrix to os in some hopefully sensible format.
References VNL::Matrix< T >::Columns(), VNL::Matrix< T >::data, and VNL::Matrix< T >::Rows().
template<class T> void VNL::Matrix< T >::Put (unsigned row, unsigned column, T const & value) [inline, inherited]
set element with boundary checks if error checking is on.
put -- Puts value into element at specified row and column. O(1).
Checks for valid range of indices.
References VNL::Matrix< T >::data, VNL::Matrix< T >::num_cols, and VNL::Matrix< T >::num_rows.
template<class T > VNL::Matrix< T > VNL::Matrix< T >::Read (std::istream & s) [inline, static, inherited]
Read a Matrix from an ascii std::istream.
Automatically determines file size if the input matrix has zero size. This is a static method so you can type <verb> Matrix<float> M = Matrix<float>::read(cin); </verb> which many people prefer to the ">>" alternative.
template<class T > bool VNL::Matrix< T >::ReadASCII (std::istream & s) [inline, inherited]
Read a Matrix from an ascii std::istream.
Automatically determines file size if the input matrix has zero size.
References c, VNL::Matrix< T >::Columns(), VNL::Matrix< T >::data, VNL::Matrix< T >::Resize(), and VNL::Matrix< T >::Rows().
Referenced by VNL::FileMatrix< T >::FileMatrix().
template<class T > bool VNL::Matrix< T >::Resize (unsigned r, unsigned c) [inline, inherited]
Resize to r rows by c columns. Old data lost.
returns true if size changed.
References VNL::Matrix< T >::data, VNL::Matrix< T >::num_cols, VNL::Matrix< T >::num_rows, vnl_matrix_alloc_blah, and vnl_matrix_free_blah.
Referenced by VNL::BinaryLoad(), VNL::Matrix< T >::operator=(), and VNL::Matrix< T >::ReadASCII().
template<int m, int n, class T> bool VNL::MatrixFixedRef< m, n, T >::resize (unsigned int, unsigned int) [inline, inherited]
Resizing a vnl_matrix_ref fails.
Referenced by VW::EssentialMatrixComputePreemptive::Compute().
template<class T = double> abs_t VNL::Matrix< T >::RMS () const [inline, inherited]
Return RMS of all elements.
template<class T = double> unsigned VNL::Matrix< T >::Rows () const [inline, inherited]
Return number of rows.
Referenced by vnl_fastops::AB(), vnl_fastops::ABt(), VNL::Adjugate(), VNL::Matrix< T >::assert_finite_internal(), VNL::Matrix< T >::assert_size_internal(), vnl_fastops::AtA(), vnl_fastops::AtB(), VNL::BinarySave(), vnl_matops::cat(), VNL::Cholesky< T >::Cholesky(), vnl_fastops::dec_X_by_ABt(), vnl_fastops::dec_X_by_AtB(), VNL::Determinant(), VNL::LeastSquaresFunction::FDGradF(), VNL::Matrix< T >::FlipLR(), VNL::Matrix< T >::FlipUD(), VNL::GeneralizedSchur(), GetRowEchelonForm(), VNL::LeastSquaresCostFunction::GradF(), VNL::Matrix< T >::HasNaNs(), vnl_fastops::inc_X_by_AtA(), vnl_fastops::inc_X_by_AtB(), VNL::Matrix< T >::InplaceTranspose(), VNL::Matrix< T >::IsFinite(), VNL::Matrix< T >::IsIdentity(), VNL::Matrix< T >::IsZero(), VNL::MatlabPrint(), VNL::MatlabReadOrDie(), VNL::MatrixExp(), VNL::MatrixFixed< 9, 9, double >::MatrixFixed(), VNL::Matrix< std::complex< double > >::operator()(), VNL::operator*(), VW::ProjectionMatrix::operator=(), VNL::MatrixFixedRef< m, n, float >::operator=(), VNL::MatrixFixed< 9, 9, double >::operator=(), VW::Homography2DCovariance::operator=(), VW::Homography2D::operator=(), VW::FMatrixAffineCovariance::operator=(), VW::FMatrixAffine::operator=(), VW::FMatrixCovariance::operator=(), VW::FMatrix::operator=(), VW::EssentialMatrix::operator=(), operator==(), VNL::Vector< T >::PostMultiply(), VNL::Vector< T >::PreMultiply(), VNL::Matrix< T >::print(), VW::ProjectionMatrix::ProjectionMatrix(), VNL::QR< T >::QR(), VNL::Matrix< T >::ReadASCII(), VNL::RealEigensystem::RealEigensystem(), VNL::RealNPolynomial::RealNPolynomial(), VNL::RealNPolynomial::Set(), VNL::Matrix< std::complex< double > >::size(), VNL::Matrix< std::complex< double > >::Size(), VNL::SVD< T >::Solve(), VNL::SVD< T >::SVD(), VNL::SymmetricEigensystemCompute(), VNL::Trace(), vnl_matops::vcat(), VNL::Vector< T >::Vector(), vnl_complexify(), vnl_discrete_diff_fwd(), vnl_discrete_diff_sym(), vnl_fortran_copy< T >::vnl_fortran_copy(), and VNL::MatlabFilewrite::Write().
template<class T> void VNL::Matrix< T >::ScaleColumn (unsigned col, T value) [inline, inherited]
Scale elements in given column by a factor of T.
Multiply column[column_index] by value.
References VNL::Matrix< T >::data, VNL::ErrorMatrixColIndex(), and VNL::Matrix< T >::num_cols.
Referenced by VNL::Determinant().
template<class T> void VNL::Matrix< T >::ScaleRow (unsigned row, T value) [inline, inherited]
Scale elements in given row by a factor of T.
Multiply row[row_index] by value.
References VNL::Matrix< T >::data, VNL::ErrorMatrixRowIndex(), and VNL::Matrix< T >::num_cols.
Referenced by VNL::Determinant().
template<class T = double> void VNL::Matrix< T >::Set (T const * d) [inline, inherited]
Fill (laminate) this matrix with the given data.
A synonym for copy_in()
Reimplemented in VNL::CrossProductMatrix< T >.
template<class T> void VNL::Matrix< T >::SetColumn (unsigned j, VNL::Vector< T > const & v) [inline, inherited]
Set j-th colum to v.
Set column[column_index] to given vector. No bounds check.
References VNL::Vector< T >::DataBlock(), and VNL::Matrix< T >::SetColumn().
template<class T> void VNL::Matrix< T >::SetColumn (unsigned i, T value) [inline, inherited]
Set the elements of the i'th column to value.
Set column[column_index] to given value.
References VNL::Matrix< T >::data.
template<class T> void VNL::Matrix< T >::SetColumn (unsigned i, T const * v) [inline, inherited]
Set the elements of the i'th column to v[j] (No bounds checking).
Set column[column_index] to data at given address.
References VNL::Matrix< T >::data.
Referenced by VNL::VectorFixed< 3, T >::AsColumn(), vnl_matops::cat(), and VNL::Matrix< T >::SetColumn().
template<class T> void VNL::Matrix< T >::SetColumns (unsigned starting_column, Matrix< T > const & M) [inline, inherited]
Set columns to those in M, starting at starting_column.
Set columns starting at starting_column to given matrix.
References VNL::Matrix< T >::data, VNL::ErrorMatrixDimension(), VNL::Matrix< T >::num_cols, and VNL::Matrix< T >::num_rows.
template<class T> void VNL::Matrix< T >::SetIdentity (T val = T(1)) [inline, inherited]
Set this matrix to an identity (or diagonal) matrix.
Fill this matrix with a row*row identity matrix.
Abort if the matrix is not square
References VNL::Matrix< T >::data, VNL::ErrorMatrixNonSquare(), and VNL::Matrix< T >::num_cols.
Referenced by VNL::MatrixExp(), and VW::Warp::Warp().
template<class T> void VNL::Matrix< T >::SetRow (unsigned i, VNL::Vector< T > const & v) [inline, inherited]
Set the i-th row.
Set row[row_index] to given vector. No bounds check.
References VNL::Vector< T >::DataBlock(), and VNL::Matrix< T >::SetRow().
template<class T> void VNL::Matrix< T >::SetRow (unsigned i, T value) [inline, inherited]
Set the elements of the i'th row to value.
Set row[row_index] to given value.
References VNL::Matrix< T >::data, and VNL::Matrix< T >::num_cols.
template<class T> void VNL::Matrix< T >::SetRow (unsigned i, T const * v) [inline, inherited]
Set the elements of the i'th row to v[j] (No bounds checking).
Set row[row_index] to data at given address. No bounds check.
References VNL::Matrix< T >::data, and VNL::Matrix< T >::num_cols.
Referenced by VNL::VectorFixed< 3, T >::AsRow(), GetRowEchelonForm(), VNL::Matrix< T >::SetRow(), and vnl_orthogonal_complement().
template<class T = double> unsigned VNL::Matrix< T >::size () const [inline, inherited]
Return number of elements.
This equals rows() * cols()
Referenced by VNL::Matrix< std::complex< double > >::ArrayInfNorm(), VNL::Matrix< std::complex< double > >::ArrayOneNorm(), VNL::Matrix< std::complex< double > >::ArrayTwoNorm(), VNL::BinaryLoad(), VNL::BinarySave(), VNL::ComplexEigensystem::ComplexEigensystem(), VNL::Matrix< T >::ConjugateTranspose(), VW::ComputeFuncs::ConvertParamVectorToTransform(), VW::ComputeFuncs::ConvertTransformToParamVector(), VNL::Matrix< std::complex< double > >::FrobeniusNorm(), VNL::GeneralizedSchur(), VNL::Matrix< std::complex< double > >::MaxValue(), VNL::Matrix< std::complex< double > >::Mean(), VNL::Matrix< std::complex< double > >::MinValue(), VNL::Matrix< std::complex< double > >::RMS(), and vnl_complexify().
template<class T = double> unsigned VNL::Matrix< T >::Size () const [inline, inherited]
Return number of elements.
This equals rows() * cols()
template<class T> void VNL::Matrix< T >::Swap (Matrix< T > & that) [inline, inherited]
Swap this matrix with that matrix.
References VNL::Matrix< T >::data, VNL::Matrix< T >::num_cols, and VNL::Matrix< T >::num_rows.
Referenced by VNL::Swap().
template<class T > VNL::Matrix< T > VNL::Matrix< T >::Transpose () const [inline, inherited]
Return transpose.
Returns new matrix with rows and columns transposed.
O(m*n).
Reimplemented in VW::RotationMatrix.
References VNL::Matrix< T >::data, and VNL::Matrix< T >::num_cols.
Referenced by VNL::Transpose::AsMatrix(), VW::Homography2DComputeLinear::Compute(), VW::FMatrixComputeMLESAC::Compute(), VW::FMatrixComputeLinear::Compute(), VW::FMatrixAffineComputeLinear::Compute(), VW::EssentialMatrixComputeMLESAC::Compute(), VNL::Matrix< T >::ConjugateTranspose(), VNL::GeneralizedEigensystem::GeneralizedEigensystem(), VW::FMatrixCompute::GenerateParameterVector(), VW::FMPlanarCompute::GenerateParameterVectorHZ(), VW::FMPlanarCompute::GenerateParameterVectorHZJK(), VW::FMPlanarCompute::GenerateParameterVectorVLJK(), VNL::Transpose::operator Matrix< double >(), and VW::FMatrixAffineCompute::Unnormalise().
template<class T> VNL::Matrix< T > & VNL::Matrix< T >::Update (Matrix< T > const & m, unsigned top = 0, unsigned left = 0) [inline, inherited]
Set values of this matrix to those of M, starting at [top,left].
Replaces the submatrix of THIS matrix, starting at top left corner, by the elements of matrix m. O(m*n).
This is the reverse of extract().
References VNL::Matrix< T >::data, VNL::ErrorMatrixDimension(), VNL::Matrix< T >::num_cols, and VNL::Matrix< T >::num_rows.
Referenced by vnl_matops::cat(), VNL::GeneralizedEigensystem::GeneralizedEigensystem(), and vnl_matops::vcat().
Member Data Documentation
template<class T = double> T** VNL::Matrix< T >::data [protected, inherited]
Referenced by VNL::Matrix< T >::Apply(), VNL::Matrix< std::complex< double > >::begin(), VNL::Matrix< T >::Clear(), VNL::Matrix< T >::CopyIn(), VNL::Matrix< T >::CopyOut(), VNL::Matrix< std::complex< double > >::DataArray(), VNL::Matrix< std::complex< double > >::DataBlock(), VNL::Matrix< std::complex< double > >::end(), VNL::Matrix< T >::Extract(), VNL::Matrix< T >::Fill(), VNL::Matrix< T >::FillDiagonal(), VNL::Matrix< T >::Get(), VNL::Matrix< T >::GetColumn(), VNL::Matrix< T >::GetNColumns(), VNL::Matrix< T >::GetNRows(), VNL::Matrix< T >::GetRow(), VNL::Matrix< T >::InplaceTranspose(), VNL::Matrix< std::complex< double > >::IsEmpty(), VNL::Matrix< T >::Matrix(), VNL::Matrix< std::complex< double > >::Matrix(), VNL::MatrixFixedRef< m, n, float >::MatrixFixedRef(), VNL::MatrixRef< T >::MatrixRef(), VNL::Matrix< T >::NormalizeColumns(), VNL::Matrix< T >::NormalizeRows(), VNL::Matrix< std::complex< double > >::operator()(), VNL::Matrix< T >::operator*=(), VNL::Matrix< T >::operator+=(), VNL::Matrix< T >::operator-(), VNL::Matrix< T >::operator-=(), VNL::Matrix< T >::operator/=(), VNL::MatrixFixedRef< m, n, float >::operator=(), VNL::Matrix< T >::operator=(), VNL::Matrix< std::complex< double > >::operator[](), VNL::Matrix< T >::operator_eq(), VNL::Matrix< T >::operatorInfNorm(), VNL::Matrix< T >::operatorOneNorm(), VNL::Matrix< T >::print(), VNL::Matrix< T >::Put(), VNL::Matrix< T >::ReadASCII(), VNL::Matrix< T >::Resize(), VNL::Matrix< T >::ScaleColumn(), VNL::Matrix< T >::ScaleRow(), VNL::Matrix< T >::SetColumn(), VNL::Matrix< T >::SetColumns(), VNL::Matrix< T >::SetIdentity(), VNL::Matrix< T >::SetRow(), VNL::Matrix< T >::Swap(), VNL::Matrix< T >::Transpose(), VNL::Matrix< T >::Update(), VNL::Matrix< std::complex< double > >::~Matrix(), VNL::MatrixFixedRef< m, n, float >::~MatrixFixedRef(), and VNL::MatrixRef< T >::~MatrixRef().
template<class T = double> unsigned VNL::Matrix< T >::num_cols [protected, inherited]
Referenced by VNL::Matrix< T >::Apply(), VNL::Matrix< T >::Clear(), VNL::Matrix< std::complex< double > >::Cols(), VNL::Matrix< std::complex< double > >::Columns(), VNL::Matrix< T >::CopyIn(), VNL::Matrix< T >::CopyOut(), VNL::Matrix< std::complex< double > >::end(), VNL::Matrix< T >::Extract(), VNL::Matrix< T >::Fill(), VNL::Matrix< T >::FillDiagonal(), VNL::Matrix< T >::Get(), VNL::Matrix< T >::GetColumn(), VNL::Matrix< T >::GetNColumns(), VNL::Matrix< T >::GetNRows(), VNL::Matrix< T >::GetRow(), VNL::Matrix< T >::InplaceTranspose(), VNL::Matrix< std::complex< double > >::IsEmpty(), VNL::Matrix< T >::Matrix(), VNL::Matrix< std::complex< double > >::Matrix(), VNL::MatrixFixedRef< m, n, float >::MatrixFixedRef(), VNL::MatrixRef< T >::MatrixRef(), VNL::Matrix< T >::NormalizeColumns(), VNL::Matrix< T >::NormalizeRows(), VNL::Matrix< T >::operator*=(), VNL::Matrix< T >::operator+=(), VNL::Matrix< T >::operator-(), VNL::Matrix< T >::operator-=(), VNL::Matrix< T >::operator/=(), VNL::Matrix< T >::operator=(), VNL::Matrix< T >::operator_eq(), VNL::Matrix< T >::operatorInfNorm(), VNL::Matrix< T >::operatorOneNorm(), VNL::Matrix< T >::Put(), VNL::Matrix< T >::Resize(), VNL::Matrix< T >::ScaleColumn(), VNL::Matrix< T >::ScaleRow(), VNL::Matrix< T >::SetColumns(), VNL::Matrix< T >::SetIdentity(), VNL::Matrix< T >::SetRow(), VNL::Matrix< T >::Swap(), VNL::Matrix< T >::Transpose(), and VNL::Matrix< T >::Update().
template<class T = double> unsigned VNL::Matrix< T >::num_rows [protected, inherited]
Referenced by VNL::Matrix< T >::Clear(), VNL::Matrix< std::complex< double > >::end(), VNL::Matrix< T >::Fill(), VNL::Matrix< T >::FillDiagonal(), VNL::Matrix< T >::Get(), VNL::Matrix< std::complex< double > >::IsEmpty(), VNL::Matrix< T >::Matrix(), VNL::Matrix< std::complex< double > >::Matrix(), VNL::MatrixFixedRef< m, n, float >::MatrixFixedRef(), VNL::MatrixRef< T >::MatrixRef(), VNL::Matrix< T >::operator*=(), VNL::Matrix< T >::operator+=(), VNL::Matrix< T >::operator-=(), VNL::Matrix< T >::operator/=(), VNL::Matrix< T >::operator=(), VNL::Matrix< T >::operator_eq(), VNL::Matrix< T >::Put(), VNL::Matrix< T >::Resize(), VNL::Matrix< std::complex< double > >::Rows(), VNL::Matrix< T >::SetColumns(), VNL::Matrix< T >::Swap(), and VNL::Matrix< T >::Update().
The documentation for this class was generated from the following file:
matrixfixed.h