VW: vnl_finite_int_poly< N, M > Class Template Reference
vnl_finite_int_poly< N, M > Class Template Reference
finite modulo-N arithmetic with polynomials of degree < M.
#include <finite.h>
Public Member Functions
vnl_finite_int_poly (std::vector< Scalar > const &p)
Creates a general finite_int_poly.
vnl_finite_int_poly (Scalar const &n)
Creates a degree 0 finite_int_poly.
vnl_finite_int_poly ()
Default constructor. Creates a degree 0 finite_int_poly equal to 0.
vnl_finite_int_poly (Base const &x)
~vnl_finite_int_poly ()
unsigned int deg () const
Formal degree of this polynomial.
int degree () const
Effective degree of this polynomial; equals -1 when this polynomial is 0.
Scalar operator[] (unsigned int i) const
Access to individual coefficients.
Base & operator= (Base const &x)
Assignment.
Base & operator= (Scalar const &n)
bool operator== (Base const &x) const
Comparison of finite int polys.
bool operator!= (Base const &x) const
bool operator== (Scalar const &x) const
bool operator!= (Scalar const &x) const
Base operator- () const
Unary minus - returns the additive inverse.
Base operator+ () const
Unary plus - returns the current polynomial.
bool operator! () const
Unary not - returns true if finite int poly is equal to zero.
Base & operator+= (Base const &r)
Plus&assign: replace lhs by lhs + rhs.
Base & operator-= (Base const &r)
Minus&assign: replace lhs by lhs - rhs.
Base & operator*= (Scalar const &n)
Scalar multiple of this.
unsigned int additive_order () const
The additive order of x is the smallest positive r such that r*x == 0.
Base & operator*= (Base const &r)
Multiply&assign: replace lhs by lhs * rhs, modulo the "modulo" polynomial.
unsigned int multiplicative_order () const
Return the multiplicative order of this polynomial.
Static Public Member Functions
static unsigned int cardinality ()
The number of different finite_int polynomials of this type.
static std::vector< Scalar > & modulo_polynomial (std::vector< Scalar > p=std::vector< Scalar >())
get/set the (irreducible) modulo polynomial of degree M.
static bool is_field ()
Return true when this ring is a field.
static Base smallest_generator ()
Return the smallest multiplicative generator of the units in this ring.
Detailed Description
template<int N, int M>
class vnl_finite_int_poly< N, M >
finite modulo-N arithmetic with polynomials of degree < M.
This class implements arithmetic with polynomials of degree < M over vnl_finite_int<N>. Multiplication is defined modulo a polynomial of degree M.
For N prime, and when the "modulo" polynomial is irreducible, vnl_finite_int_poly<N,M> implements the finite field GF(N^M).
Addition, subtraction and scalar multiplication are already defined without the presence of a "modulo" polynomial. Restricted to these operations, vnl_finite_int_poly<N,M> forms an M-dimensional vector space over vnl_finite_int<N>. The current implementation does not yet implement anything more than that.
Constructor & Destructor Documentation
template<int N, int M> vnl_finite_int_poly< N, M >::vnl_finite_int_poly (std::vector< Scalar > const & p) [inline]
Creates a general finite_int_poly.
template<int N, int M> vnl_finite_int_poly< N, M >::vnl_finite_int_poly (Scalar const & n) [inline]
Creates a degree 0 finite_int_poly.
template<int N, int M> vnl_finite_int_poly< N, M >::vnl_finite_int_poly () [inline]
Default constructor. Creates a degree 0 finite_int_poly equal to 0.
template<int N, int M> vnl_finite_int_poly< N, M >::vnl_finite_int_poly (Base const & x) [inline]
template<int N, int M> vnl_finite_int_poly< N, M >::~vnl_finite_int_poly () [inline]
Member Function Documentation
template<int N, int M> unsigned int vnl_finite_int_poly< N, M >::additive_order () const [inline]
The additive order of x is the smallest positive r such that r*x == 0.
References vnl_finite_int_poly< N, M >::deg(), and vnl_finite_int< N >::gcd().
template<int N, int M> static unsigned int vnl_finite_int_poly< N, M >::cardinality () [inline, static]
The number of different finite_int polynomials of this type.
Referenced by vnl_finite_int_poly< N, M >::is_field().
template<int N, int M> unsigned int vnl_finite_int_poly< N, M >::deg () const [inline]
Formal degree of this polynomial.
Referenced by vnl_finite_int_poly< N, M >::additive_order(), vnl_finite_int_poly< N, M >::degree(), vnl_finite_int_poly< N, M >::operator!(), vnl_finite_int_poly< N, M >::operator*=(), vnl_finite_int_poly< N, M >::operator+=(), vnl_finite_int_poly< N, M >::operator-=(), vnl_finite_int_poly< N, M >::operator==(), and vnl_finite_int_poly< N, M >::operator[]().
template<int N, int M> int vnl_finite_int_poly< N, M >::degree () const [inline]
Effective degree of this polynomial; equals -1 when this polynomial is 0.
References vnl_finite_int_poly< N, M >::deg().
Referenced by vnl_finite_int_poly< N, M >::operator*=().
template<int N, int M> static bool vnl_finite_int_poly< N, M >::is_field () [inline, static]
Return true when this ring is a field.
Note that this requires that N is a prime, but that condition is not sufficient: also the "modulo" polynomial must be irreducible.
References vnl_finite_int_poly< N, M >::cardinality(), vnl_finite_int< N >::is_field(), and vnl_finite_int_poly< N, M >::modulo_polynomial().
Referenced by vnl_finite_int_poly< N, M >::smallest_generator().
template<int N, int M> static std::vector<Scalar>& vnl_finite_int_poly< N, M >::modulo_polynomial (std::vector< Scalar > p = std::vector<Scalar>()) [inline, static]
get/set the (irreducible) modulo polynomial of degree M.
Note that this polynomial has to be set only once, i.e., once set, it applies to all vnl_finite_int_polys with the same N and M.
Referenced by vnl_finite_int_poly< N, M >::is_field(), and vnl_finite_int_poly< N, M >::smallest_generator().
template<int N, int M> unsigned int vnl_finite_int_poly< N, M >::multiplicative_order () const [inline]
Return the multiplicative order of this polynomial.
template<int N, int M> bool vnl_finite_int_poly< N, M >::operator! () const [inline]
Unary not - returns true if finite int poly is equal to zero.
References vnl_finite_int_poly< N, M >::deg().
template<int N, int M> bool vnl_finite_int_poly< N, M >::operator!= (Scalar const & x) const [inline]
References vnl_finite_int_poly< N, M >::operator==().
template<int N, int M> bool vnl_finite_int_poly< N, M >::operator!= (Base const & x) const [inline]
References vnl_finite_int_poly< N, M >::operator==().
template<int N, int M> Base& vnl_finite_int_poly< N, M >::operator*= (Base const & r) [inline]
Multiply&assign: replace lhs by lhs * rhs, modulo the "modulo" polynomial.
References vnl_finite_int_poly< N, M >::deg(), and vnl_finite_int_poly< N, M >::degree().
template<int N, int M> Base& vnl_finite_int_poly< N, M >::operator*= (Scalar const & n) [inline]
Scalar multiple of this.
References vnl_finite_int_poly< N, M >::deg().
template<int N, int M> Base vnl_finite_int_poly< N, M >::operator+ () const [inline]
Unary plus - returns the current polynomial.
template<int N, int M> Base& vnl_finite_int_poly< N, M >::operator+= (Base const & r) [inline]
Plus&assign: replace lhs by lhs + rhs.
References vnl_finite_int_poly< N, M >::deg().
template<int N, int M> Base vnl_finite_int_poly< N, M >::operator- () const [inline]
Unary minus - returns the additive inverse.
template<int N, int M> Base& vnl_finite_int_poly< N, M >::operator-= (Base const & r) [inline]
Minus&assign: replace lhs by lhs - rhs.
References vnl_finite_int_poly< N, M >::deg().
template<int N, int M> Base& vnl_finite_int_poly< N, M >::operator= (Scalar const & n) [inline]
template<int N, int M> Base& vnl_finite_int_poly< N, M >::operator= (Base const & x) [inline]
Assignment.
template<int N, int M> bool vnl_finite_int_poly< N, M >::operator== (Scalar const & x) const [inline]
References vnl_finite_int_poly< N, M >::deg().
template<int N, int M> bool vnl_finite_int_poly< N, M >::operator== (Base const & x) const [inline]
Comparison of finite int polys.
References vnl_finite_int_poly< N, M >::deg().
Referenced by vnl_finite_int_poly< N, M >::operator!=().
template<int N, int M> Scalar vnl_finite_int_poly< N, M >::operator[] (unsigned int i) const [inline]
Access to individual coefficients.
References vnl_finite_int_poly< N, M >::deg().
template<int N, int M> static Base vnl_finite_int_poly< N, M >::smallest_generator () [inline, static]
Return the smallest multiplicative generator of the units in this ring.
This is only possible if the units form a cyclic group for multiplication. If not, smallest_generator() returns 1 to indicate this fact. Note that the multiplication group of a finite *field* is always cyclic.
References vnl_finite_int_poly< N, M >::is_field(), and vnl_finite_int_poly< N, M >::modulo_polynomial().
The documentation for this class was generated from the following file:
finite.h