VW: VW::FMPlanarComputeNonLinear Class Reference
VW::FMPlanarComputeNonLinear Class Reference
#include <fmplanarcomputenonlinear.h>
Public Member Functions
FMPlanarComputeNonLinear (double error_tolerance=DEFAULT_TOLERANCE, unsigned int max_iters=DEFAULT_MAXITERS)
bool Compute (VW::FMatrixPlanar &result, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1)
Compute a fundamental matrix from two lists of 2D point features.
bool Compute (VW::FMatrixPlanar &result, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const std::vector< unsigned int > &whichfeatures)
Constructor & Destructor Documentation
VW::FMPlanarComputeNonLinear::FMPlanarComputeNonLinear (double error_tolerance = DEFAULT_TOLERANCE, unsigned int max_iters = DEFAULT_MAXITERS) [inline]
Member Function Documentation
bool VW::FMPlanarComputeNonLinear::Compute (VW::FMatrixPlanar & result, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const std::vector< unsigned int > & whichfeatures)
References VW::FMPlanarCompute::GenerateParameterVectorHZ(), VW::FMPlanarCompute::GenerateParameterVectorHZJK(), VW::FMPlanarCompute::GenerateParameterVectorVLJK(), VNL::LeastSquaresFunction::GetNumberOfUnknowns(), VNL::LevenbergMarquardt::Minimize(), VW::FMPlanarCompute::ReconstructTransformHZ(), VW::FMPlanarCompute::ReconstructTransformHZJK(), VW::FMPlanarCompute::ReconstructTransformVLJK(), VNL::NonlinearMinimizer::SetFTolerance(), and VNL::NonlinearMinimizer::SetMaxFunctionEvals().
bool VW::FMPlanarComputeNonLinear::Compute (VW::FMatrixPlanar & result, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1)
Compute a fundamental matrix from two lists of 2D point features.
Minimisation is performed using Levenberg-Marquadt with Sampson distance as the error measure. Note that no normalisation is performed, so its best if you normalise the data before calling this.
Returns:
true for successful minimisation, false otherwise (homography is left untouched in this case).
The documentation for this class was generated from the following files:
fmplanarcomputenonlinear.h
fmplanarcomputenonlinear.cpp