VW: VNL::ComplexEigensystem Class Reference
VNL::ComplexEigensystem Class Reference
Calculates eigenvalues and eigenvectors of a square complex matrix.
#include <complexeigensystem.h>
Public Member Functions
ComplexEigensystem (VNL::Matrix< double > const &A_real, VNL::Matrix< double > const &A_imag, bool right=true, bool left=false)
ComplexEigensystem (VNL::Matrix< std::complex< double > > const &A, bool right=true, bool left=false)
std::complex< double > EigenValue (unsigned i) const
VNL::Vector< std::complex
< double > > LeftEigenVector (unsigned i) const
VNL::Vector< std::complex
< double > > RightEigenVector (unsigned i) const
Public Attributes
int const N
VNL::Matrix< std::complex
< double > > L
VNL::Matrix< std::complex
< double > > R
VNL::Vector< std::complex
< double > > W
Detailed Description
Calculates eigenvalues and eigenvectors of a square complex matrix.
Class to compute and hold the eigenvalues and (optionally) eigenvectors of a square complex matrix, using the LAPACK routine zgeev.
Default behaviour is to compute the eigenvalues and the right eigenvectors.
The input NxN matrix A is passed into the constructor. The flags right,left request the calculation of right and left eigenvectors respectively. The compute eigenvalues are stored in the member 'W'.
Computed right eigenvectors are stored in the **ROWS** of the member 'R' and computed left eigenvectors are stored in the **ROWS** of the member 'L'. When eigenvectors are not requested, the corre- sponding matrices L and R will be empty.
The ith right eigenvector v satisfies A*v = W[i]*v
The ith left eigenvector u satisfies u*A = W[i]*u (no conjugation)
Constructor & Destructor Documentation
VNL::ComplexEigensystem::ComplexEigensystem (VNL::Matrix< double > const & A_real, VNL::Matrix< double > const & A_imag, bool right = true, bool left = false)
References VNL::Matrix< T >::assert_size(), VNL::Matrix< T >::begin(), VNL::Complexify(), and VNL::Matrix< T >::size().
VNL::ComplexEigensystem::ComplexEigensystem (VNL::Matrix< std::complex< double > > const & A, bool right = true, bool left = false)
Member Function Documentation
std::complex<double> VNL::ComplexEigensystem::EigenValue (unsigned i) const [inline]
References W.
VNL::Vector<std::complex<double> > VNL::ComplexEigensystem::LeftEigenVector (unsigned i) const [inline]
References VNL::Matrix< T >::GetRow(), and L.
VNL::Vector<std::complex<double> > VNL::ComplexEigensystem::RightEigenVector (unsigned i) const [inline]
References VNL::Matrix< T >::GetRow(), and R.
Member Data Documentation
VNL::Matrix<std::complex<double> > VNL::ComplexEigensystem::L
Referenced by LeftEigenVector().
int const VNL::ComplexEigensystem::N
VNL::Matrix<std::complex<double> > VNL::ComplexEigensystem::R
Referenced by RightEigenVector().
VNL::Vector<std::complex<double> > VNL::ComplexEigensystem::W
Referenced by EigenValue().
The documentation for this class was generated from the following files:
complexeigensystem.h
complexeigensystem.cpp