VW: VW::IOObject Class Reference
VW::IOObject Class Reference
Abstract base class for objects that can be input/output in a standard (streaming) way.
#include <ioobject.h>
Public Member Functions
virtual ~IOObject ()
bool WriteASCIIFile (const std::string &filename) const
Open a file and output as plain ASCII (overwriting any existing contents).
bool WriteXMLFile (const std::string &filename, const std::string &name="") const
Open a file and output as XML-style ASCII (overwriting any existing contents).
bool WriteBinaryFile (const std::string &filename) const
Open a file and output as binary (overwriting any existing contents).
virtual bool WriteASCII (std::ostream &stream) const =0
Stream as plain ASCII.
virtual bool WriteXML (std::ostream &stream, const std::string &name="") const =0
Stream as XML style ASCII.
virtual bool WriteBinary (std::ostream &stream) const =0
Stream as binary.
virtual bool ReadASCIIFile (const std::string &filename)
Open a file and input as plain ASCII.
virtual bool ReadXMLFile (const std::string &filename, const std::string &name="")
Open a file and input as XML style ASCII.
virtual bool ReadBinaryFile (const std::string &filename)
Open a file and input as binary.
virtual bool ReadASCII (std::istream &stream)=0
Stream as plain ASCII.
virtual bool ReadXML (std::istream &stream, const std::string &name="")=0
Stream as XML style ASCII.
virtual bool ReadBinary (std::istream &stream)=0
Stream as binary.
Detailed Description
Abstract base class for objects that can be input/output in a standard (streaming) way.
Author:
BJ Tordoff
Date:
22/10/02 This abstract class forces inheriting sub-classes to implement a set of streaming functions, providing input and output in binary, ASCII and XML-style ASCII formats. In addition it provides basic file versions of these functions that do not need to be overloaded, and maps the standard streaming operation to the ASCII functions.
Constructor & Destructor Documentation
virtual VW::IOObject::~IOObject () [inline, virtual]
Member Function Documentation
virtual bool VW::IOObject::ReadASCII (std::istream & stream) [pure virtual]
Stream as plain ASCII.
Parameters:
stream the input stream to read from
Returns:
true if successfully read, false if there are problems
Implemented in VW::AngleAxis, VW::CalibrationMatrix, VW::CalibrationTable, VW::Point2D, VW::Point3D, VW::Quaternion, VW::ClassifierUV, VW::CornerFeature, VW::ImagePatch, VW::ImagePatchYUV, VW::PatchFeature, VW::PlesseyCorner, VW::PlesseyCornerYUV, VW::SIFTFeature, and VW::FirewireCamera.
Referenced by std::operator>>(), and ReadASCIIFile().
bool VW::IOObject::ReadASCIIFile (const std::string & filename) [virtual]
Open a file and input as plain ASCII.
Open a file and read as plain ASCII.
Once the file is open, the child class's ReadASCII function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References ReadASCII().
virtual bool VW::IOObject::ReadBinary (std::istream & stream) [pure virtual]
Stream as binary.
Parameters:
stream the input stream to read from
Returns:
true if successfully read, false if there are problems
Implemented in VW::AngleAxis, VW::CalibrationMatrix, VW::CalibrationTable, VW::Point2D, VW::Point3D, VW::Quaternion, VW::ClassifierUV, VW::CornerFeature, VW::ImagePatch, VW::ImagePatchYUV, VW::PatchFeature, VW::PlesseyCorner, VW::PlesseyCornerYUV, VW::SIFTFeature, and VW::FirewireCamera.
Referenced by ReadBinaryFile().
bool VW::IOObject::ReadBinaryFile (const std::string & filename) [virtual]
Open a file and input as binary.
Open a file and read as binary.
Once the file is open, the child class's ReadBinary function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References ReadBinary().
virtual bool VW::IOObject::ReadXML (std::istream & stream, const std::string & name = "") [pure virtual]
Stream as XML style ASCII.
Parameters:
stream the input stream to read from
name if specified, the found tag must have a NAME= parameter that matches
Returns:
true if successfully read, false if there are problems
Implemented in VW::AngleAxis, VW::CalibrationMatrix, VW::CalibrationTable, VW::Point2D, VW::Point3D, VW::Quaternion, VW::ClassifierUV, VW::CornerFeature, VW::ImagePatch, VW::ImagePatchYUV, VW::PatchFeature, VW::PlesseyCorner, VW::PlesseyCornerYUV, VW::SIFTFeature, and VW::FirewireCamera.
Referenced by ReadXMLFile().
bool VW::IOObject::ReadXMLFile (const std::string & filename, const std::string & name = "") [virtual]
Open a file and input as XML style ASCII.
Open a file and read as XML-style ASCII.
Once the file is open, the child class's ReadXML function is used to read the content.
Parameters:
filename the name of the file to open
name the optional name tag-attribute to match ie. data must start <MyClass name="name">
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References ReadXML().
Referenced by VW::ClassifierUV::ClassifierUV(), and VW::FirewireCameraGTK::LoadParameterFile().
virtual bool VW::IOObject::WriteASCII (std::ostream & stream) const [pure virtual]
Stream as plain ASCII.
Parameters:
stream the output stream to write to
Returns:
true if successfully written, false if there are problems
Implemented in VW::AngleAxis, VW::CalibrationMatrix, VW::CalibrationTable, VW::Point2D, VW::Point3D, VW::Quaternion, VW::ClassifierUV, VW::CornerFeature, VW::ImagePatch, VW::ImagePatchYUV, VW::PatchFeature, VW::PlesseyCorner, VW::PlesseyCornerYUV, VW::SIFTFeature, and VW::FirewireCamera.
Referenced by std::operator<<(), and WriteASCIIFile().
bool VW::IOObject::WriteASCIIFile (const std::string & filename) const
Open a file and output as plain ASCII (overwriting any existing contents).
Open a file and output as plain ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteASCII function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References WriteASCII().
virtual bool VW::IOObject::WriteBinary (std::ostream & stream) const [pure virtual]
Stream as binary.
Parameters:
stream the output stream to write to
Returns:
true if successfully written, false if there are problems
Implemented in VW::AngleAxis, VW::CalibrationMatrix, VW::CalibrationTable, VW::Point2D, VW::Point3D, VW::Quaternion, VW::ClassifierUV, VW::CornerFeature, VW::ImagePatch, VW::ImagePatchYUV, VW::PatchFeature, VW::PlesseyCorner, VW::PlesseyCornerYUV, VW::SIFTFeature, and VW::FirewireCamera.
Referenced by WriteBinaryFile().
bool VW::IOObject::WriteBinaryFile (const std::string & filename) const
Open a file and output as binary (overwriting any existing contents).
Once the file is open, the child class's WriteBinary function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References WriteBinary().
virtual bool VW::IOObject::WriteXML (std::ostream & stream, const std::string & name = "") const [pure virtual]
Stream as XML style ASCII.
Parameters:
stream the output stream to write to
name if specified, the class will be given a NAME= parameter
Returns:
true if successfully written, false if there are problems
Implemented in VW::AngleAxis, VW::CalibrationMatrix, VW::CalibrationTable, VW::Point2D, VW::Point3D, VW::Quaternion, VW::ClassifierUV, VW::CornerFeature, VW::ImagePatch, VW::ImagePatchYUV, VW::PatchFeature, VW::PlesseyCorner, VW::PlesseyCornerYUV, VW::SIFTFeature, and VW::FirewireCamera.
Referenced by WriteXMLFile().
bool VW::IOObject::WriteXMLFile (const std::string & filename, const std::string & name = "") const
Open a file and output as XML-style ASCII (overwriting any existing contents).
Open a file and output as XML-style ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteXML function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
name the tag parameter, if required
Returns:
true for success, false if file cannot be opened or the data can't be written.
References WriteXML().
Referenced by VW::FirewireCameraGTK::SaveParameterFile().
The documentation for this class was generated from the following files:
ioobject.h
ioobject.cpp