VW: VW::HistogramEqualisation Class Reference
VW::HistogramEqualisation Class Reference
[ImageProcessing]
Standard histogram equalisation of image intensities.
#include <histogramequalisation.h>
Public Member Functions
HistogramEqualisation ()
Construct without initialising.
HistogramEqualisation (VW::ImageMono< unsigned char > &image)
Calculate te histogram and apply immediately to this image.
HistogramEqualisation (VW::ImageYUV< unsigned char > &image)
Calculate te histogram and apply immediately to this image.
HistogramEqualisation (const VW::ImageMono< unsigned char > &inputimage, VW::ImageMono< unsigned char > &resultimage)
Calculate from inputimage and store equalised result in resultimge.
HistogramEqualisation (const VW::ImageYUV< unsigned char > &inputimage, VW::ImageYUV< unsigned char > &resultimage)
Calculate from inputimage and store equalised result in resultimge.
void ComputeFromImage (const VW::ImageMono< unsigned char > &inputimage)
Recompute the histogram from an image.
void ComputeFromImage (const VW::ImageYUV< unsigned char > &inputimage)
Recompute the histogram from an image.
void AddImage (const VW::ImageMono< unsigned char > &inputimage)
Add a new image to the histogram.
void AddImage (const VW::ImageYUV< unsigned char > &inputimage)
Add a new image to the histogram.
void ApplyToImage (VW::ImageMono< unsigned char > &resultimage)
Apply a previosuly computed histogram to a new image.
void ApplyToImage (VW::ImageYUV< unsigned char > &resultimage)
Apply a previosuly computed histogram to a new image.
void ApplyToImage (const VW::ImageMono< unsigned char > &inputimage, VW::ImageMono< unsigned char > &resultimage)
Apply a previosuly computed histogram to a new image.
void ApplyToImage (const VW::ImageYUV< unsigned char > &inputimage, VW::ImageYUV< unsigned char > &resultimage)
Apply a previosuly computed histogram to a new image.
Protected Member Functions
void ResetArrays ()
Protected Attributes
unsigned int _totalnum
std::vector< unsigned int > _bin_contents
std::vector< unsigned char > _hash
Detailed Description
Standard histogram equalisation of image intensities.
Author:
BJ Tordoff
Date:
05/04/2005
Constructor & Destructor Documentation
VW::HistogramEqualisation::HistogramEqualisation () [inline]
Construct without initialising.
VW::HistogramEqualisation::HistogramEqualisation (VW::ImageMono< unsigned char > & image) [inline]
Calculate te histogram and apply immediately to this image.
References ApplyToImage(), and ComputeFromImage().
VW::HistogramEqualisation::HistogramEqualisation (VW::ImageYUV< unsigned char > & image) [inline]
Calculate te histogram and apply immediately to this image.
References ApplyToImage(), and ComputeFromImage().
VW::HistogramEqualisation::HistogramEqualisation (const VW::ImageMono< unsigned char > & inputimage, VW::ImageMono< unsigned char > & resultimage) [inline]
Calculate from inputimage and store equalised result in resultimge.
References ApplyToImage(), and ComputeFromImage().
VW::HistogramEqualisation::HistogramEqualisation (const VW::ImageYUV< unsigned char > & inputimage, VW::ImageYUV< unsigned char > & resultimage) [inline]
Calculate from inputimage and store equalised result in resultimge.
References ApplyToImage(), and ComputeFromImage().
Member Function Documentation
void VW::HistogramEqualisation::AddImage (const VW::ImageYUV< unsigned char > & inputimage)
Add a new image to the histogram.
References _bin_contents, _hash, _totalnum, VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetRowStart(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), NUMBINS, and VW::PixelYUV< Type >::y.
void VW::HistogramEqualisation::AddImage (const VW::ImageMono< unsigned char > & inputimage)
Add a new image to the histogram.
References _bin_contents, _hash, _totalnum, VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetRowStart(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), NUMBINS, and VW::PixelMono< Type >::y.
Referenced by ComputeFromImage().
void VW::HistogramEqualisation::ApplyToImage (const VW::ImageYUV< unsigned char > & inputimage, VW::ImageYUV< unsigned char > & resultimage)
Apply a previosuly computed histogram to a new image.
References _hash, VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::AllocImageData(), VW::PixelYUV< Type >::alpha, VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::FreeImageData(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetRowStart(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::IsAlloced(), VW::PixelYUV< Type >::u, VW::PixelYUV< Type >::v, and VW::PixelYUV< Type >::y.
void VW::HistogramEqualisation::ApplyToImage (const VW::ImageMono< unsigned char > & inputimage, VW::ImageMono< unsigned char > & resultimage)
Apply a previosuly computed histogram to a new image.
References _hash, VW::ImageBase< PixelType, PixelPtr >::AllocImageData(), VW::ImageBase< PixelType, PixelPtr >::FreeImageData(), VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetRowStart(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), VW::ImageBase< PixelType, PixelPtr >::IsAlloced(), and VW::PixelMono< Type >::y.
void VW::HistogramEqualisation::ApplyToImage (VW::ImageYUV< unsigned char > & resultimage)
Apply a previosuly computed histogram to a new image.
References _hash, VW::PixelYUV< Type >::alpha, VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetRowStart(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), VW::PixelYUV< Type >::u, VW::PixelYUV< Type >::v, and VW::PixelYUV< Type >::y.
void VW::HistogramEqualisation::ApplyToImage (VW::ImageMono< unsigned char > & resultimage)
Apply a previosuly computed histogram to a new image.
References _hash, VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetRowStart(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), and VW::PixelMono< Type >::y.
Referenced by HistogramEqualisation().
void VW::HistogramEqualisation::ComputeFromImage (const VW::ImageYUV< unsigned char > & inputimage) [inline]
Recompute the histogram from an image.
References AddImage(), and ResetArrays().
void VW::HistogramEqualisation::ComputeFromImage (const VW::ImageMono< unsigned char > & inputimage) [inline]
Recompute the histogram from an image.
References AddImage(), and ResetArrays().
Referenced by HistogramEqualisation().
void VW::HistogramEqualisation::ResetArrays () [protected]
References _bin_contents, _hash, _totalnum, and NUMBINS.
Referenced by ComputeFromImage().
Member Data Documentation
std::vector<unsigned int> VW::HistogramEqualisation::_bin_contents [protected]
Referenced by AddImage(), and ResetArrays().
std::vector<unsigned char> VW::HistogramEqualisation::_hash [protected]
Referenced by AddImage(), ApplyToImage(), and ResetArrays().
unsigned int VW::HistogramEqualisation::_totalnum [protected]
Referenced by AddImage(), and ResetArrays().
The documentation for this class was generated from the following files:
histogramequalisation.h
histogramequalisation.cpp