VW: VW::PDF::Gaussian2DIso Class Reference
VW::PDF::Gaussian2DIso Class Reference
[MathsStuff]
a small class to hold the constants associated with a 2D Isotropic Gaussian PDF (note that this is much faster than the non-isotropic VW::PDF::Gaussian2D).
#include <pdfgaussian2diso.h>
Public Member Functions
Gaussian2DIso (const VNL::VectorFixed< 2, double > &mean, double covariance=1.0)
Gaussian2DIso (double mean_x, double mean_y, double covariance=1.0)
double EvaluateDensityForError (const VNL::VectorFixed< 2, double > &e) const
Calculate the probability density at distance e from the mean.
double EvaluateDensityForError2 (double e_squared) const
Calculate the probability density at squared-distance from the mean .
double ApproxDensityForError2 (double e_squared) const
calculate the approximate density using a Pade approximation to exp, which is faster, but only accurate to about e = 3*sigma
VNL::VectorFixed< 2, double > Sample () const
Sample from a random variable with this PDF.
Private Member Functions
virtual double EvaluateDensityForValue (const VNL::VectorFixed< 2, double > &x) const
Calculate the probability density at location x.
VNL::VectorFixed< 2, double > GetMean () const
VNL::MatrixFixed< 2, 2, double > GetCovariance () const
Private Attributes
double _sigma
VNL::VectorFixed< 2, double > _mu
VNL::MatrixFixed< 2, 2, double > _C
Detailed Description
a small class to hold the constants associated with a 2D Isotropic Gaussian PDF (note that this is much faster than the non-isotropic VW::PDF::Gaussian2D).
Author:
BJ Tordoff
Date:
30/06/2003 This PDF class allows evaluation of the probability density at any location, and sampling from a random variable with this PDF. Since some parts of the evaluation depend only on mean and covariance, storing as a class gives some computational benefits.
Constructor & Destructor Documentation
VW::PDF::Gaussian2DIso::Gaussian2DIso (const VNL::VectorFixed< 2, double > & mean, double covariance = 1.0) [inline]
VW::PDF::Gaussian2DIso::Gaussian2DIso (double mean_x, double mean_y, double covariance = 1.0) [inline]
Member Function Documentation
double VW::PDF::Gaussian2DIso::ApproxDensityForError2 (double e_squared) const [inline]
calculate the approximate density using a Pade approximation to exp, which is faster, but only accurate to about e = 3*sigma
References VW::PadeExp44().
double VW::PDF::Gaussian2DIso::EvaluateDensityForError (const VNL::VectorFixed< 2, double > & e) const [inline, virtual]
Calculate the probability density at distance e from the mean.
Implements VW::PDF::PDFBase2D.
References VNL::DotProduct(), and EvaluateDensityForError2().
double VW::PDF::Gaussian2DIso::EvaluateDensityForError2 (double e_squared) const [inline, virtual]
Calculate the probability density at squared-distance from the mean .
Implements VW::PDF::PDFBase2DIso.
Referenced by EvaluateDensityForError().
VNL::VectorFixed< 2, double > VW::PDF::Gaussian2DIso::Sample () const [virtual]
Sample from a random variable with this PDF.
Implements VW::PDF::PDFBase2D.
References VW::PDF::PDFBase2D::_mu, VW::PDF::PDFBase2DIso::_sigma, VW::Rand(), and std::sqrt().
The documentation for this class was generated from the following files:
pdfgaussian2diso.h
pdfgaussian2diso.cpp