VW: VW::FMatrixPlanar Class Reference
VW::FMatrixPlanar Class Reference
[GeometricObjects]
A class to represent the specialisation of the fundamental matrix due to camera motion in a plane.
#include <fmatrixplanar.h>
Public Types
typedef CVector< double >::abs_t abs_t
Type def for norms.
typedef double element_type
typedef double * iterator
Iterators.
typedef doubleconst * const_iterator
Const iterators.
Public Member Functions
FMatrixPlanar ()
FMatrixPlanar (const FMatrix &F)
FMatrixPlanar (const VNL::MatrixFixed< 3, 3, double > &M)
FMatrixPlanar & operator= (const FMatrix &F)
FMatrixPlanar & operator= (const VNL::MatrixFixed< 3, 3, double > m)
FMatrixPlanar & operator= (const VNL::Matrix< double > m)
void Constrain ()
FMatrixPlanar::Constrain () -- Constrain to rank 2 (singularity condition).
VW::Line2D Transfer (const VW::Point2D &point) const
VW::Line2D ReverseTransfer (const VW::Point2D &point) const
template<class ElementType >
void TransferPoint (const ElementType &point, VW::Line2D &eline) const
template<class ElementType >
void ReverseTransferPoint (const ElementType &point, VW::Line2D &eline) const
void GetEpipoles (VW::Point2D &e1, VW::Point2D &e2) const
VNL::MatrixFixed< 3, 3, double > AsMatrix () const
template<class F >
unsigned int GetMinFeatures (const F &f)
unsigned int GetNumViews ()
std::ostream & operator<< (std::ostream &stream) const
bool resize (unsigned int, unsigned int)
Resizing a vnl_matrix_ref fails.
unsigned Rows () const
Return number of rows.
unsigned Columns () const
Return number of columns.
unsigned Cols () const
Return number of columns.
unsigned Size () const
Return number of elements.
unsigned size () const
Return number of elements.
void Put (unsigned r, unsigned c, doubleconst &)
set element with boundary checks if error checking is on.
double Get (unsigned r, unsigned c) const
get element with boundary checks if error checking is on.
double * operator[] (unsigned r)
return pointer to given row.
doubleconst * operator[] (unsigned r) const
return pointer to given row.
double & operator() (unsigned r, unsigned c)
Access an element for reading or writing.
doubleconst & operator() (unsigned r, unsigned c) const
Access an element for reading.
void Fill (doubleconst &)
Set all elements of matrix to specified value.
void FillDiagonal (doubleconst &)
Set all diagonal elements of matrix to specified value.
void CopyIn (doubleconst *)
Fill (laminate) this matrix with the given data.
void Set (doubleconst *d)
Fill (laminate) this matrix with the given data.
void CopyOut (double *) const
Fill the given array with this matrix.
Matrix< double > & operator+= (doublevalue)
Add rhs to each element of lhs matrix in situ.
Matrix< double > & operator+= (Matrix< double > const &)
Add rhs to lhs matrix in situ.
Matrix< double > & operator-= (doublevalue)
Subtract rhs from each element of lhs matrix in situ.
Matrix< double > & operator-= (Matrix< double > const &)
Subtract rhs from lhs matrix in situ.
Matrix< double > & operator*= (doublevalue)
Scalar multiplication in situ of lhs matrix by rhs.
Matrix< double > & operator*= (Matrix< double > const &rhs)
Multiply lhs matrix in situ by rhs.
Matrix< double > & operator/= (doublevalue)
Scalar division of lhs matrix in situ by rhs.
Matrix< double > operator- () const
Negate all elements of matrix.
Matrix< double > operator- (doubleconst &v) const
Subtract rhs from each element of lhs matrix and return result in new matrix.
Matrix< double > operator- (Matrix< double > const &rhs) const
Matrix subtract rhs from lhs and return result in new matrix.
Matrix< double > operator+ (doubleconst &v) const
Add rhs to each element of lhs matrix and return result in new matrix.
Matrix< double > operator+ (Matrix< double > const &rhs) const
Matrix add rhs to lhs matrix and return result in new matrix.
Matrix< double > operator* (doubleconst &v) const
Scalar multiplication of lhs matrix by rhs and return result in new matrix.
Matrix< double > operator* (Matrix< double > const &rhs) const
Matrix multiply lhs by rhs matrix and return result in new matrix.
Matrix< double > operator/ (doubleconst &v) const
Scalar division of lhs matrix by rhs and return result in new matrix.
Matrix< double > Apply (double(*f)(double)) const
Make a new matrix by applying function to each element.
Matrix< double > Apply (double(*f)(doubleconst &)) const
Make a new matrix by applying function to each element.
Matrix< double > Transpose () const
Return transpose.
Matrix< double > ConjugateTranspose () const
Return conjugate transpose.
Matrix< double > & Update (Matrix< double > const &, unsigned top=0, unsigned left=0)
Set values of this matrix to those of M, starting at [top,left].
void SetColumn (unsigned i, doubleconst *v)
Set the elements of the i'th column to v[j] (No bounds checking).
void SetColumn (unsigned i, doublevalue)
Set the elements of the i'th column to value.
void SetColumn (unsigned j, Vector< double > const &v)
Set j-th colum to v.
void SetColumns (unsigned starting_column, Matrix< double > const &M)
Set columns to those in M, starting at starting_column.
void SetRow (unsigned i, doubleconst *v)
Set the elements of the i'th row to v[j] (No bounds checking).
void SetRow (unsigned i, doublevalue)
Set the elements of the i'th row to value.
void SetRow (unsigned i, Vector< double > const &)
Set the i-th row.
Matrix< double > Extract (unsigned rows, unsigned cols, unsigned top=0, unsigned left=0) const
Extract a sub-matrix of size rows x cols, starting at (top,left).
Vector< double > GetRow (unsigned row) const
Get a vector equal to the given row.
Vector< double > GetColumn (unsigned col) const
Get a vector equal to the given column.
Matrix< double > GetNRows (unsigned rowstart, unsigned n) const
Get n rows beginning at rowstart.
Matrix< double > GetNColumns (unsigned colstart, unsigned n) const
Get n columns beginning at colstart.
void SetIdentity (doubleval=double(1))
Set this matrix to an identity (or diagonal) matrix.
void InplaceTranspose ()
Transpose this matrix efficiently.
void FlipUD ()
Reverse order of rows.
void FlipLR ()
Reverse order of columns.
void NormalizeRows ()
Normalize each row so it is a unit vector.
void NormalizeColumns ()
Normalize each column so it is a unit vector.
void ScaleRow (unsigned row, doublevalue)
Scale elements in given row by a factor of T.
void ScaleColumn (unsigned col, doublevalue)
Scale elements in given column by a factor of T.
void Swap (Matrix< double > &that)
Swap this matrix with that matrix.
abs_t ArrayOneNorm () const
Return sum of absolute values of elements.
abs_t ArrayTwoNorm () const
Return square root of sum of squared absolute element values.
abs_t ArrayInfNorm () const
Return largest absolute element value.
abs_t AbsoluteValueSum () const
Return sum of absolute values of elements.
abs_t AbsoluteValueMax () const
Return largest absolute value.
abs_t operatorOneNorm () const
abs_t operatorInfNorm () const
abs_t FrobeniusNorm () const
Return frobenius norm of matrix (sqrt of sum of squares of its elements).
abs_t FroNorm () const
Return frobenius norm of matrix (sqrt of sum of squares of its elements).
abs_t RMS () const
Return RMS of all elements.
double MinValue () const
Return minimum value of elements.
double MaxValue () const
Return maximum value of elements.
double Mean () const
Return mean of all matrix elements.
bool IsEmpty () const
Return true iff the size is zero.
bool IsIdentity () const
Return true if all elements equal to identity.
bool IsIdentity (double tol) const
Return true if all elements equal to identity, within given tolerance.
bool IsZero () const
Return true if all elements equal to zero.
bool IsZero (double tol) const
Return true if all elements equal to zero, within given tolerance.
bool IsFinite () const
Return true if finite.
bool HasNaNs () const
Return true if matrix contains NaNs.
void assert_size (unsigned rows, unsigned cols) const
abort if size is not as expected.
void assert_finite () const
abort if matrix containins any INFs or NANs.
bool ReadASCII (std::istream &s)
doubleconst * DataBlock () const
Access the contiguous block storing the elements in the matrix row-wise. O(1).
double * DataBlock ()
Access the contiguous block storing the elements in the matrix row-wise. O(1).
doubleconst *const * DataArray () const
Access the 2D array, so that elements can be accessed with array[row][col] directly.
double ** DataArray ()
Access the 2D array, so that elements can be accessed with array[row][col] directly.
iterator begin ()
Iterator pointing to start of data.
const_iterator begin () const
Iterator pointing to start of data.
iterator end ()
Iterator pointing to element beyond end of data.
const_iterator end () const
Iterator pointing to element beyond end of data.
bool operator_eq (Matrix< double > const &rhs) const
Return true if *this == rhs.
bool operator== (Matrix< double > const &that) const
Equality operator.
bool operator!= (Matrix< double > const &that) const
Inequality operator.
void print (std::ostream &os) const
Print matrix to os in some hopefully sensible format.
void Clear ()
Make the matrix as if it had been default-constructed.
bool Resize (unsigned r, unsigned c)
Resize to r rows by c columns. Old data lost.
Static Public Member Functions
static Matrix< double > Read (std::istream &s)
Static Public Attributes
static const unsigned int MIN_POINTSET_SIZE = 7
static const unsigned int MIN_LINESET_SIZE = 0
static const unsigned int NUM_VIEWS = 2
static const char *const NAME = "FMatrix"
static const unsigned int MIN_SET_SIZE = 4
Protected Member Functions
void assert_size_internal (unsigned rows, unsigned cols) const
void assert_finite_internal () const
void destroy ()
Delete data.
Static Protected Member Functions
static void inline_function_tickler ()
Protected Attributes
unsigned num_rows
unsigned num_cols
double ** data
Detailed Description
A class to represent the specialisation of the fundamental matrix due to camera motion in a plane.
Author:
JGH Knight
Date:
02/08/02 When the camera only moves in a plane (translates in the plane and rotates about an axis perpendicular to it), as is typical for ground vehicles, the fundamental matrix has only 6 degrees of freedom. This is done by forcing the both F, and (F + F') (its symmetric part) to be rank 2.
Member Typedef Documentation
typedef CVector<double >::abs_t VNL::Matrix< double >::abs_t [inherited]
Type def for norms.
typedef double const* VNL::Matrix< double >::const_iterator [inherited]
Const iterators.
typedef double VNL::Matrix< double >::element_type [inherited]
typedef double * VNL::Matrix< double >::iterator [inherited]
Iterators.
Constructor & Destructor Documentation
VW::FMatrixPlanar::FMatrixPlanar () [inline]
References Constrain().
VW::FMatrixPlanar::FMatrixPlanar (const FMatrix & F) [inline]
References Constrain().
VW::FMatrixPlanar::FMatrixPlanar (const VNL::MatrixFixed< 3, 3, double > & M) [inline]
References Constrain().
Member Function Documentation
abs_t VNL::Matrix< double >::AbsoluteValueMax () const [inline, inherited]
Return largest absolute value.
abs_t VNL::Matrix< double >::AbsoluteValueSum () const [inline, inherited]
Return sum of absolute values of elements.
Matrix<double > VNL::Matrix< double >::Apply (double (*)(double const &) f) const [inherited]
Make a new matrix by applying function to each element.
Return the matrix made by applying "f" to each element.
Matrix<double > VNL::Matrix< double >::Apply (double (*)(double) f) const [inherited]
Make a new matrix by applying function to each element.
Return the matrix made by applying "f" to each element.
abs_t VNL::Matrix< double >::ArrayInfNorm () const [inline, inherited]
Return largest absolute element value.
abs_t VNL::Matrix< double >::ArrayOneNorm () const [inline, inherited]
Return sum of absolute values of elements.
abs_t VNL::Matrix< double >::ArrayTwoNorm () const [inline, inherited]
Return square root of sum of squared absolute element values.
VNL::MatrixFixed<3,3,double> VW::FMatrix::AsMatrix () const [inline, inherited]
Referenced by Constrain(), VW::FMatrixCompute::GenerateParameterVector(), VW::FMPlanarCompute::GenerateParameterVectorHZ(), VW::FMPlanarCompute::GenerateParameterVectorHZJK(), VW::FMPlanarCompute::GenerateParameterVectorVLJK(), VW::FMatrix::ReverseTransferPoint(), and VW::FMatrix::TransferPoint().
void VNL::Matrix< double >::assert_finite () const [inline, inherited]
abort if matrix containins any INFs or NANs.
This function does or tests nothing if NDEBUG is defined
void VNL::Matrix< double >::assert_finite_internal () const [protected, inherited]
Abort if any element of M is inf or nan.
void VNL::Matrix< double >::assert_size (unsigned rows, unsigned cols) const [inline, inherited]
abort if size is not as expected.
This function does or tests nothing if NDEBUG is defined
void VNL::Matrix< double >::assert_size_internal (unsigned rows, unsigned cols) const [protected, inherited]
Abort unless M has the given size.
const_iterator VNL::Matrix< double >::begin () const [inline, inherited]
Iterator pointing to start of data.
iterator VNL::Matrix< double >::begin () [inline, inherited]
Iterator pointing to start of data.
void VNL::Matrix< double >::Clear () [inherited]
Make the matrix as if it had been default-constructed.
unsigned VNL::Matrix< double >::Cols () const [inline, inherited]
Return number of columns.
A synonym for columns()
unsigned VNL::Matrix< double >::Columns () const [inline, inherited]
Return number of columns.
A synonym for cols()
Matrix<double > VNL::Matrix< double >::ConjugateTranspose () const [inherited]
Return conjugate transpose.
void VW::FMatrixPlanar::Constrain ()
FMatrixPlanar::Constrain () -- Constrain to rank 2 (singularity condition).
Enforces the singularity conditions on the fundamental matrix using the SVD.
Reimplemented from VW::FMatrix.
References VW::FMatrix::AsMatrix().
Referenced by FMatrixPlanar().
void VNL::Matrix< double >::CopyIn (double const *) [inherited]
Fill (laminate) this matrix with the given data.
Fill this matrix with the given data.
We assume that p points to a contiguous rows*cols array, stored rowwise.
void VNL::Matrix< double >::CopyOut (double *) const [inherited]
Fill the given array with this matrix.
We assume that p points to a contiguous rows*cols array, stored rowwise. No bounds checking on the array
We assume that p points to a contiguous rows*cols array, stored rowwise.
double * * VNL::Matrix< double >::DataArray () [inline, inherited]
Access the 2D array, so that elements can be accessed with array[row][col] directly.
2d array, [row][column].
double const* const* VNL::Matrix< double >::DataArray () const [inline, inherited]
Access the 2D array, so that elements can be accessed with array[row][col] directly.
2d array, [row][column].
double * VNL::Matrix< double >::DataBlock () [inline, inherited]
Access the contiguous block storing the elements in the matrix row-wise. O(1).
1d array, row-major order.
double const* VNL::Matrix< double >::DataBlock () const [inline, inherited]
Access the contiguous block storing the elements in the matrix row-wise. O(1).
1d array, row-major order.
Referenced by VW::Homography2DCovariance::operator=(), VW::FMatrixAffineCovariance::operator=(), and VW::FMatrixCovariance::operator=().
void VNL::Matrix< double >::destroy () [protected, inherited]
Delete data.
Frees up the dynamic storage used by matrix.
O(m*n).
const_iterator VNL::Matrix< double >::end () const [inline, inherited]
Iterator pointing to element beyond end of data.
iterator VNL::Matrix< double >::end () [inline, inherited]
Iterator pointing to element beyond end of data.
Matrix<double > VNL::Matrix< double >::Extract (unsigned rows, unsigned cols, unsigned top = 0, unsigned left = 0) const [inherited]
Extract a sub-matrix of size rows x cols, starting at (top,left).
Returns a copy of submatrix of THIS matrix, specified by the top-left corner and size in rows, cols. O(m*n).
Thus it contains elements [top,top+rows-1][left,left+cols-1]
Use update() to copy new values of this submatrix back into THIS matrix.
Referenced by VW::ProjectionMatrix::Decompose().
void VNL::Matrix< double >::Fill (double const &) [inherited]
Set all elements of matrix to specified value.
Sets all elements of matrix to specified value. O(m*n).
Complexity
void VNL::Matrix< double >::FillDiagonal (double const &) [inherited]
Set all diagonal elements of matrix to specified value.
Sets all diagonal elements of matrix to specified value. O(n).
Complexity
void VNL::Matrix< double >::FlipLR () [inherited]
Reverse order of columns.
void VNL::Matrix< double >::FlipUD () [inherited]
Reverse order of rows.
Reverse order of rows. Name is from Matlab, meaning "flip upside down".
abs_t VNL::Matrix< double >::FrobeniusNorm () const [inline, inherited]
Return frobenius norm of matrix (sqrt of sum of squares of its elements).
abs_t VNL::Matrix< double >::FroNorm () const [inline, inherited]
Return frobenius norm of matrix (sqrt of sum of squares of its elements).
double VNL::Matrix< double >::Get (unsigned r, unsigned c) const [inherited]
get element with boundary checks if error checking is on.
get -- Returns the value of the element at specified row and column. O(1).
Checks for valid range of indices.
Vector<double > VNL::Matrix< double >::GetColumn (unsigned col) const [inherited]
Get a vector equal to the given column.
Create a vector out of column[column_index].
Referenced by VW::ProjectionMatrix::Decompose().
void VW::FMatrix::GetEpipoles (VW::Point2D & e1, VW::Point2D & e2) const [inherited]
References VW::Point2D::Set(), VNL::SVD< T >::U(), and VNL::SVD< T >::V().
Referenced by VW::FMPlanarCompute::GenerateParameterVectorHZ(), and VW::FMPlanarCompute::GenerateParameterVectorVLJK().
template<class F > unsigned int VW::FMatrix::GetMinFeatures (const F & f) [inline, inherited]
Reimplemented from VW::Transform.
Matrix<double > VNL::Matrix< double >::GetNColumns (unsigned colstart, unsigned n) const [inherited]
Get n columns beginning at colstart.
Returns a copy of n columns, starting from "column".
Matrix<double > VNL::Matrix< double >::GetNRows (unsigned rowstart, unsigned n) const [inherited]
Get n rows beginning at rowstart.
Returns a copy of n rows, starting from "row".
unsigned int VW::FMatrix::GetNumViews () [inline, inherited]
Reimplemented from VW::Transform.
References VW::FMatrix::NUM_VIEWS.
Vector<double > VNL::Matrix< double >::GetRow (unsigned row) const [inherited]
Get a vector equal to the given row.
Create a vector out of row[row_index].
bool VNL::Matrix< double >::HasNaNs () const [inherited]
Return true if matrix contains NaNs.
Return true if any element of (*this) is nan.
static void VNL::Matrix< double >::inline_function_tickler () [static, protected, inherited]
void VNL::Matrix< double >::InplaceTranspose () [inherited]
Transpose this matrix efficiently.
Transpose matrix M in place.
Works for rectangular matrices using an enormously clever algorithm from ACM TOMS.
bool VNL::Matrix< double >::IsEmpty () const [inline, inherited]
Return true iff the size is zero.
bool VNL::Matrix< double >::IsFinite () const [inherited]
Return true if finite.
Return false if any element of (*this) is inf or nan.
bool VNL::Matrix< double >::IsIdentity (double tol) const [inherited]
Return true if all elements equal to identity, within given tolerance.
Return true if maximum absolute deviation of M from identity is <= tol.
bool VNL::Matrix< double >::IsIdentity () const [inherited]
Return true if all elements equal to identity.
bool VNL::Matrix< double >::IsZero (double tol) const [inherited]
Return true if all elements equal to zero, within given tolerance.
Return true if max(abs((*this))) <= tol.
bool VNL::Matrix< double >::IsZero () const [inherited]
Return true if all elements equal to zero.
double VNL::Matrix< double >::MaxValue () const [inline, inherited]
Return maximum value of elements.
double VNL::Matrix< double >::Mean () const [inline, inherited]
Return mean of all matrix elements.
double VNL::Matrix< double >::MinValue () const [inline, inherited]
Return minimum value of elements.
void VNL::Matrix< double >::NormalizeColumns () [inherited]
Normalize each column so it is a unit vector.
Make each column of the matrix have unit norm.
Zero columns are ignored
All-zero columns are ignored.
void VNL::Matrix< double >::NormalizeRows () [inherited]
Normalize each row so it is a unit vector.
Make each row of the matrix have unit norm.
Zero rows are ignored
All-zero rows are ignored.
bool VNL::Matrix< double >::operator!= (Matrix< double > const & that) const [inline, inherited]
Inequality operator.
double const& VNL::Matrix< double >::operator() (unsigned r, unsigned c) const [inline, inherited]
Access an element for reading.
There are assert style boundary checks - define NDEBUG to turn them off.
double & VNL::Matrix< double >::operator() (unsigned r, unsigned c) [inline, inherited]
Access an element for reading or writing.
There are assert style boundary checks - define NDEBUG to turn them off.
Matrix<double > VNL::Matrix< double >::operator* (Matrix< double > const & rhs) const [inline, inherited]
Matrix multiply lhs by rhs matrix and return result in new matrix.
Matrix<double > VNL::Matrix< double >::operator* (double const & v) const [inline, inherited]
Scalar multiplication of lhs matrix by rhs and return result in new matrix.
Matrix<double >& VNL::Matrix< double >::operator*= (Matrix< double > const & rhs) [inline, inherited]
Multiply lhs matrix in situ by rhs.
Matrix<double >& VNL::Matrix< double >::operator*= (double value) [inherited]
Scalar multiplication in situ of lhs matrix by rhs.
Matrix<double > VNL::Matrix< double >::operator+ (Matrix< double > const & rhs) const [inline, inherited]
Matrix add rhs to lhs matrix and return result in new matrix.
Matrix<double > VNL::Matrix< double >::operator+ (double const & v) const [inline, inherited]
Add rhs to each element of lhs matrix and return result in new matrix.
Matrix<double >& VNL::Matrix< double >::operator+= (Matrix< double > const &) [inherited]
Add rhs to lhs matrix in situ.
Adds lhs matrix with rhs matrix, and stores in place in lhs matrix.
O(m*n). The dimensions of the two matrices must be identical.
Matrix<double >& VNL::Matrix< double >::operator+= (double value) [inherited]
Add rhs to each element of lhs matrix in situ.
Matrix<double > VNL::Matrix< double >::operator- (Matrix< double > const & rhs) const [inline, inherited]
Matrix subtract rhs from lhs and return result in new matrix.
Matrix<double > VNL::Matrix< double >::operator- (double const & v) const [inline, inherited]
Subtract rhs from each element of lhs matrix and return result in new matrix.
Matrix<double > VNL::Matrix< double >::operator- () const [inherited]
Negate all elements of matrix.
Returns new matrix which is the negation of THIS matrix.
O(m*n).
Matrix<double >& VNL::Matrix< double >::operator-= (Matrix< double > const &) [inherited]
Subtract rhs from lhs matrix in situ.
Substract lhs matrix with rhs matrix and store in place in lhs matrix.
O(m*n). The dimensions of the two matrices must be identical.
Matrix<double >& VNL::Matrix< double >::operator-= (double value) [inherited]
Subtract rhs from each element of lhs matrix in situ.
Matrix<double > VNL::Matrix< double >::operator/ (double const & v) const [inline, inherited]
Scalar division of lhs matrix by rhs and return result in new matrix.
Matrix<double >& VNL::Matrix< double >::operator/= (double value) [inherited]
Scalar division of lhs matrix in situ by rhs.
std::ostream & VW::FMatrix::operator<< (std::ostream & stream) const [inherited]
VW::FMatrixPlanar & VW::FMatrixPlanar::operator= (const VNL::Matrix< double > m) [inline]
VW::FMatrixPlanar & VW::FMatrixPlanar::operator= (const VNL::MatrixFixed< 3, 3, double > m) [inline]
VW::FMatrixPlanar & VW::FMatrixPlanar::operator= (const FMatrix & F) [inline]
bool VNL::Matrix< double >::operator== (Matrix< double > const & that) const [inline, inherited]
Equality operator.
double const* VNL::Matrix< double >::operator[] (unsigned r) const [inline, inherited]
return pointer to given row.
No boundary checking here.
double * VNL::Matrix< double >::operator[] (unsigned r) [inline, inherited]
return pointer to given row.
No boundary checking here.
bool VNL::Matrix< double >::operator_eq (Matrix< double > const & rhs) const [inherited]
Return true if *this == rhs.
Two matrices are equal if and only if they have the same dimensions and the same values.
O(m*n). Elements are compared with operator== as default. Change this default with set_compare() at run time or by specializing Matrix_compare at compile time.
abs_t VNL::Matrix< double >::operatorInfNorm () const [inherited]
abs_t VNL::Matrix< double >::operatorOneNorm () const [inherited]
void VNL::Matrix< double >::print (std::ostream & os) const [inherited]
Print matrix to os in some hopefully sensible format.
void VNL::Matrix< double >::Put (unsigned r, unsigned c, double const &) [inherited]
set element with boundary checks if error checking is on.
put -- Puts value into element at specified row and column. O(1).
Checks for valid range of indices.
static Matrix<double > VNL::Matrix< double >::Read (std::istream & s) [static, inherited]
Read a Matrix from an ascii std::istream.
Automatically determines file size if the input matrix has zero size. This is a static method so you can type <verb> Matrix<float> M = Matrix<float>::read(cin); </verb> which many people prefer to the ">>" alternative.
bool VNL::Matrix< double >::ReadASCII (std::istream & s) [inherited]
Read a Matrix from an ascii std::istream.
Automatically determines file size if the input matrix has zero size.
bool VNL::Matrix< double >::Resize (unsigned r, unsigned c) [inherited]
Resize to r rows by c columns. Old data lost.
returns true if size changed.
bool VNL::MatrixFixedRef< m, n, double >::resize (unsigned int, unsigned int) [inline, inherited]
Resizing a vnl_matrix_ref fails.
VW::Line2D VW::FMatrix::ReverseTransfer (const VW::Point2D & point) const [inline, inherited]
References c, VNL::Matrix< double >::data, VW::Point2D::GetX(), and VW::Point2D::GetY().
Referenced by VW::FMPlanarCompute::LeastSquaresFunctionPoints::F(), and VW::FMatrixCompute::LeastSquaresFunctionPoints::F().
template<class ElementType > void VW::FMatrix::ReverseTransferPoint (const ElementType & point, VW::Line2D & eline) const [inline, inherited]
References VW::FMatrix::AsMatrix(), and VNL::Matrix< double >::Transpose().
abs_t VNL::Matrix< double >::RMS () const [inline, inherited]
Return RMS of all elements.
unsigned VNL::Matrix< double >::Rows () const [inline, inherited]
Return number of rows.
void VNL::Matrix< double >::ScaleColumn (unsigned col, double value) [inherited]
Scale elements in given column by a factor of T.
Multiply column[column_index] by value.
void VNL::Matrix< double >::ScaleRow (unsigned row, double value) [inherited]
Scale elements in given row by a factor of T.
Multiply row[row_index] by value.
void VNL::Matrix< double >::Set (double const * d) [inline, inherited]
Fill (laminate) this matrix with the given data.
A synonym for copy_in()
void VNL::Matrix< double >::SetColumn (unsigned j, Vector< double > const & v) [inherited]
Set j-th colum to v.
Set column[column_index] to given vector. No bounds check.
void VNL::Matrix< double >::SetColumn (unsigned i, double value) [inherited]
Set the elements of the i'th column to value.
Set column[column_index] to given value.
void VNL::Matrix< double >::SetColumn (unsigned i, double const * v) [inherited]
Set the elements of the i'th column to v[j] (No bounds checking).
Set column[column_index] to data at given address.
void VNL::Matrix< double >::SetColumns (unsigned starting_column, Matrix< double > const & M) [inherited]
Set columns to those in M, starting at starting_column.
Set columns starting at starting_column to given matrix.
Referenced by VW::ProjectionMatrix::Compose().
void VNL::Matrix< double >::SetIdentity (double val = T(1)) [inherited]
Set this matrix to an identity (or diagonal) matrix.
Fill this matrix with a row*row identity matrix.
Abort if the matrix is not square
Referenced by VW::Homography2D::Homography2D().
void VNL::Matrix< double >::SetRow (unsigned i, Vector< double > const &) [inherited]
Set the i-th row.
Set row[row_index] to given vector. No bounds check.
void VNL::Matrix< double >::SetRow (unsigned i, double value) [inherited]
Set the elements of the i'th row to value.
Set row[row_index] to given value.
void VNL::Matrix< double >::SetRow (unsigned i, double const * v) [inherited]
Set the elements of the i'th row to v[j] (No bounds checking).
Set row[row_index] to data at given address. No bounds check.
unsigned VNL::Matrix< double >::size () const [inline, inherited]
Return number of elements.
This equals rows() * cols()
unsigned VNL::Matrix< double >::Size () const [inline, inherited]
Return number of elements.
This equals rows() * cols()
void VNL::Matrix< double >::Swap (Matrix< double > & that) [inherited]
Swap this matrix with that matrix.
VW::Line2D VW::FMatrix::Transfer (const VW::Point2D & point) const [inline, inherited]
References c, VNL::Matrix< double >::data, VW::Point2D::GetX(), and VW::Point2D::GetY().
Referenced by VW::FMPlanarCompute::LeastSquaresFunctionPoints::F(), and VW::FMatrixCompute::LeastSquaresFunctionPoints::F().
template<class ElementType > void VW::FMatrix::TransferPoint (const ElementType & point, VW::Line2D & eline) const [inline, inherited]
References VW::FMatrix::AsMatrix().
Matrix<double > VNL::Matrix< double >::Transpose () const [inherited]
Return transpose.
Returns new matrix with rows and columns transposed.
O(m*n).
Reimplemented in VW::RotationMatrix.
Referenced by VW::FMatrix::ReverseTransferPoint(), and VW::Homography2D::TransferLine().
Matrix<double >& VNL::Matrix< double >::Update (Matrix< double > const & , unsigned top = 0, unsigned left = 0) [inherited]
Set values of this matrix to those of M, starting at [top,left].
Replaces the submatrix of THIS matrix, starting at top left corner, by the elements of matrix m. O(m*n).
This is the reverse of extract().
Member Data Documentation
double ** VNL::Matrix< double >::data [protected, inherited]
Referenced by VW::RotationMatrix::Angle(), VW::RotationMatrix::Axis(), VW::ProjectionMatrix::Compose(), VW::EssentialMatrix::Constrain(), VW::Homography2DCovariance::ForceSymmetry(), VW::FMatrixAffineCovariance::ForceSymmetry(), VW::FMatrixCovariance::ForceSymmetry(), VW::Homography2D::GetTransferError2(), VW::RotationMatrix::InverseRotate(), VW::ProjectionMatrix::operator=(), VW::Homography2DCovariance::operator=(), VW::Homography2D::operator=(), VW::FMatrixAffineCovariance::operator=(), VW::FMatrixCovariance::operator=(), VW::FMatrix::operator=(), VW::EssentialMatrix::operator=(), VW::ProjectionMatrix::Project(), VW::ProjectionMatrix::ProjectionMatrix(), VW::FMatrix::ReverseTransfer(), VW::EssentialMatrix::ReverseTransfer(), VW::RotationMatrix::Rotate(), VW::RotationMatrix::Set(), VW::RotationMatrix::SetFromXYZEuler(), VW::RotationMatrix::SetFromYXZEuler(), VW::RotationMatrix::SetFromZXYEuler(), VW::RotationMatrix::SetFromZXZEuler(), VW::RotationMatrix::SetFromZYXEuler(), VW::RotationMatrix::SetIdentity(), VW::FMatrix::Transfer(), VW::EssentialMatrix::Transfer(), VW::Homography2D::TransferPoint(), VW::Homography2DCovariance::TransferUncertainty(), VW::FMatrixAffineCovariance::TransferUncertainty(), VW::FMatrixCovariance::TransferUncertainty(), VW::RotationMatrix::Transpose(), and VW::RotationMatrix::WriteBinary().
const unsigned int VW::FMatrix::MIN_LINESET_SIZE = 0 [static, inherited]
const unsigned int VW::FMatrix::MIN_POINTSET_SIZE = 7 [static, inherited]
const unsigned int VW::Transform::MIN_SET_SIZE = 4 [static, inherited]
const char *const VW::FMatrix::NAME = "FMatrix" [static, inherited]
Reimplemented from VW::Transform.
unsigned VNL::Matrix< double >::num_cols [protected, inherited]
unsigned VNL::Matrix< double >::num_rows [protected, inherited]
const unsigned int VW::FMatrix::NUM_VIEWS = 2 [static, inherited]
Reimplemented from VW::Transform.
Referenced by VW::FMatrix::GetNumViews().
The documentation for this class was generated from the following files:
fmatrixplanar.h
fmatrixplanar.cpp