VW: VNL::RNPolySolveCmplx Class Reference
VNL::RNPolySolveCmplx Class Reference
This is a local implementation of a "complex number" class, for internal use only.
Public Member Functions
RNPolySolveCmplx (double a=0, double b=0)
double norm () const
RNPolySolveCmplx operator- () const
RNPolySolveCmplx operator+ (RNPolySolveCmplx const &Y) const
RNPolySolveCmplx operator- (RNPolySolveCmplx const &Y) const
RNPolySolveCmplx & operator+= (RNPolySolveCmplx const &Y)
RNPolySolveCmplx & operator-= (RNPolySolveCmplx const &Y)
RNPolySolveCmplx operator* (RNPolySolveCmplx const &Y) const
RNPolySolveCmplx operator/ (RNPolySolveCmplx const &Y) const
RNPolySolveCmplx operator* (double T) const
RNPolySolveCmplx & operator*= (double T)
RNPolySolveCmplx & operator*= (RNPolySolveCmplx const &Y)
RNPolySolveCmplx & operator/= (RNPolySolveCmplx const &Y)
Public Attributes
double R
double C
Detailed Description
This is a local implementation of a "complex number" class, for internal use only.
Constructor & Destructor Documentation
VNL::RNPolySolveCmplx::RNPolySolveCmplx (double a = 0, double b = 0) [inline]
Referenced by operator*(), operator+(), operator-(), and operator/().
Member Function Documentation
double VNL::RNPolySolveCmplx::norm () const [inline]
References C, and R.
Referenced by operator/().
RNPolySolveCmplx VNL::RNPolySolveCmplx::operator* (double T) const [inline]
References C, R, and RNPolySolveCmplx().
RNPolySolveCmplx VNL::RNPolySolveCmplx::operator* (RNPolySolveCmplx const & Y) const [inline]
References C, R, and RNPolySolveCmplx().
RNPolySolveCmplx& VNL::RNPolySolveCmplx::operator*= (RNPolySolveCmplx const & Y) [inline]
References C, and R.
RNPolySolveCmplx& VNL::RNPolySolveCmplx::operator*= (double T) [inline]
References C, and R.
RNPolySolveCmplx VNL::RNPolySolveCmplx::operator+ (RNPolySolveCmplx const & Y) const [inline]
References C, R, and RNPolySolveCmplx().
RNPolySolveCmplx& VNL::RNPolySolveCmplx::operator+= (RNPolySolveCmplx const & Y) [inline]
References C, and R.
RNPolySolveCmplx VNL::RNPolySolveCmplx::operator- (RNPolySolveCmplx const & Y) const [inline]
References C, R, and RNPolySolveCmplx().
RNPolySolveCmplx VNL::RNPolySolveCmplx::operator- () const [inline]
References C, R, and RNPolySolveCmplx().
RNPolySolveCmplx& VNL::RNPolySolveCmplx::operator-= (RNPolySolveCmplx const & Y) [inline]
References C, and R.
RNPolySolveCmplx VNL::RNPolySolveCmplx::operator/ (RNPolySolveCmplx const & Y) const [inline]
References C, norm(), R, and RNPolySolveCmplx().
Referenced by operator/=().
RNPolySolveCmplx& VNL::RNPolySolveCmplx::operator/= (RNPolySolveCmplx const & Y) [inline]
References operator/().
Member Data Documentation
double VNL::RNPolySolveCmplx::C
Referenced by norm(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), and operator/().
double VNL::RNPolySolveCmplx::R
Referenced by norm(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), and operator/().
The documentation for this class was generated from the following file:
rnpolysolve.cpp