VW: VW::Quaternion Class Reference
VW::Quaternion Class Reference
[GeometricObjects]
Representation of a 3D quaternion.
#include <quaternion.h>
Public Member Functions
Quaternion (double x=0, double y=0, double z=0, double r=1)
Construct elements individually.
Quaternion (const VW::Vector3D &axis, const double &angle)
Construct from an angle around an axis.
Quaternion (const VW::AngleAxis &angleaxis)
Construct using an angle-axis vector.
Quaternion (const VW::RotationMatrix &R)
Construct from a rotation matrix.
virtual ~Quaternion ()
void Set (double x, double y, double z, double r)
Set elements individually.
void Set (const VW::Vector3D &axis, const double &angle)
Set using a rotation axis and angle.
void Set (const VW::AngleAxis &angleaxis)
Set using an angle-axis vector.
void Set (const VW::RotationMatrix &R)
Set from a rotation matrix.
void SetFromXYZEuler (const double theta_x, const double theta_y, const double theta_z)
Create a quaternion from X,Y,Z rotations.
void SetFromZXYEuler (const double theta_z, const double theta_x, const double theta_y)
Create a quaternion from roll, pitch, yaw.
void SetFromYXZEuler (const double theta_y, const double theta_x, const double theta_z)
Create a quaternion from yaw, pitch, roll.
void SetFromZYXEuler (const double theta_z, const double theta_y, const double theta_x)
Create a quaternion from Z,Y,X rotations.
void SetFromZXZEuler (const double theta_z1, const double theta_x, const double theta_z2)
Create a quaternion from Z,X,Z rotations.
void SetRXYZ (const VNL::VectorFixed< 4, double > &vRXYZ)
Set a quaternion from the values of a VNL 4-vector.
double GetX () const
double GetY () const
double GetZ () const
double GetR () const
double & X ()
double & Y ()
double & Z ()
double & R ()
const double & X () const
const double & Y () const
const double & Z () const
const double & R () const
void Get (double &x, double &y, double &z, double &r) const
VW::Vector3D Axis () const
double Angle () const
VW::AngleAxis AngleAxis () const
VW::RotationMatrix RotationMatrix () const
VW::RotationMatrix RotationMatrixTranspose () const
VW::Quaternion Conjugate () const
VW::Quaternion Inverse () const
void GetXYZEuler (double &theta_x, double &theta_y, double &theta_z) const
void GetZXYEuler (double &theta_z, double &theta_x, double &theta_y) const
void GetYXZEuler (double &theta_y, double &theta_x, double &theta_z) const
void GetZYXEuler (double &theta_z, double &theta_y, double &theta_x) const
void GetZXZEuler (double &theta_z1, double &theta_x, double &theta_z2) const
VNL::VectorFixed< 4, double > GetRXYZ () const
Get the quaternion as a VNL 4-vector.
VW::Vector3D Rotate (const VW::Vector3D &v) const
Rotate a vector.
VW::Vector3D operator* (const VW::Vector3D &v) const
VW::LineSeg3D Rotate (const VW::LineSeg3D &l) const
Rotate a line segment.
VW::LineSeg3D operator* (const VW::LineSeg3D &l) const
Rotate a line segment.
VW::Quaternion operator* (const VW::Quaternion &q) const
Combine two rotations.
VW::Vector3D Imaginary () const
double Real () const
bool operator== (const VW::Quaternion &q) const
Is q1 identitical to this quaternion.
bool operator!= (const VW::Quaternion &q) const
Is q1 different from this quaternion.
void Normalise ()
Make sure this is a unit vector.
virtual bool WriteASCII (std::ostream &stream) const
Write space separated data (order is x,y,z,r).
virtual bool WriteXML (std::ostream &stream, const std::string &name="") const
Stream as XML style ASCII.
virtual bool WriteBinary (std::ostream &stream) const
Write binary data (order is x,y,z,r).
virtual bool ReadASCII (std::istream &stream)
Read from an ASCII input stream, from Roll, Pitch, Yaw (ZXY) Euler angles in degrees.
virtual bool ReadXML (std::istream &stream, const std::string &name="")
Stream as XML style ASCII.
virtual bool ReadBinary (std::istream &stream)
Read binary data (order is x,y,z,r).
bool WriteASCIIFile (const std::string &filename) const
Open a file and output as plain ASCII (overwriting any existing contents).
bool WriteXMLFile (const std::string &filename, const std::string &name="") const
Open a file and output as XML-style ASCII (overwriting any existing contents).
bool WriteBinaryFile (const std::string &filename) const
Open a file and output as binary (overwriting any existing contents).
virtual bool ReadASCIIFile (const std::string &filename)
Open a file and input as plain ASCII.
virtual bool ReadXMLFile (const std::string &filename, const std::string &name="")
Open a file and input as XML style ASCII.
virtual bool ReadBinaryFile (const std::string &filename)
Open a file and input as binary.
Protected Attributes
double _x
double _y
double _z
double _r
Detailed Description
Representation of a 3D quaternion.
Author:
BJ Tordoff
Date:
02/11/2002 This quaternion class represents a 3D rotation as a complex vector with three imaginary parts x,y,z and real part r: q = ix + jy + kz + r. Whilst designed for simlarity to the (partially incorrect) VNL quaternion class, it provides additional functions for rotating VW::Vector3D's and for initialisation from and recovery of Euler angles.
Note that unlike the VNL equivalent, it is guaranteed to be a unit vector.
As an IOObject descendant it can be streamed as binary, ASCII or XML-style.
Constructor & Destructor Documentation
VW::Quaternion::Quaternion (double x = 0, double y = 0, double z = 0, double r = 1) [inline]
Construct elements individually.
References Normalise().
Referenced by Conjugate().
VW::Quaternion::Quaternion (const VW::Vector3D & axis, const double & angle) [inline]
Construct from an angle around an axis.
Parameters:
axis the axis (doesn't need to be a unit vector) around which to rotate
angle the rotation angle in radians
References Set().
VW::Quaternion::Quaternion (const VW::AngleAxis & angleaxis) [inline]
Construct using an angle-axis vector.
References Set().
VW::Quaternion::Quaternion (const VW::RotationMatrix & R) [inline]
Construct from a rotation matrix.
References Set().
virtual VW::Quaternion::~Quaternion () [inline, virtual]
Member Function Documentation
double VW::Quaternion::Angle () const
Returns:
the angle of rotation in radians.
References _r, _x, _y, _z, and std::sqrt().
Referenced by VW::ThreeDToolGLCommon::ActuallyDrawDistortedTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawWarpedTexturedRectangle(), AngleAxis(), VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::DrawCameraGraphic(), VW::ThreeDToolGLCommon::DrawCylinder(), VW::ThreeDToolGLCommon::DrawRectangle(), and VW::ThreeDToolGLCommon::RotateDrawingPosition().
VW::AngleAxis VW::Quaternion::AngleAxis () const
Returns:
a vector whose magnitude gives the angle of rotation and direction gives the rotation axis
References _x, _y, _z, and Angle().
VW::Vector3D VW::Quaternion::Axis () const
Returns:
the axis of rotation.
References Imaginary(), VW::Point3D::Norm(), and VW::Point3D::Set().
Referenced by VW::ThreeDToolGLCommon::ActuallyDrawDistortedTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawWarpedTexturedRectangle(), VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::DrawCameraGraphic(), VW::ThreeDToolGLCommon::DrawCylinder(), VW::ThreeDToolGLCommon::DrawRectangle(), and VW::ThreeDToolGLCommon::RotateDrawingPosition().
VW::Quaternion VW::Quaternion::Conjugate () const [inline]
References _r, _x, _y, _z, and Quaternion().
Referenced by VW::ThreePointPose::ComputeQRotn().
void VW::Quaternion::Get (double & x, double & y, double & z, double & r) const [inline]
References _r, _x, _y, and _z.
double VW::Quaternion::GetR () const [inline]
References _r.
Referenced by VW::AngleAxis::Set().
VNL::VectorFixed< 4, double > VW::Quaternion::GetRXYZ () const [inline]
Get the quaternion as a VNL 4-vector.
The R part is first, as in many quaternion implementations.
References _r, _x, _y, and _z.
double VW::Quaternion::GetX (void) const [inline]
References _x.
Referenced by VW::AngleAxis::Set().
void VW::Quaternion::GetXYZEuler (double & theta_x, double & theta_y, double & theta_z) const [inline]
References _r, _x, _y, and _z.
double VW::Quaternion::GetY (void) const [inline]
References _y.
Referenced by VW::AngleAxis::Set().
void VW::Quaternion::GetYXZEuler (double & theta_y, double & theta_x, double & theta_z) const [inline]
References _r, _x, _y, and _z.
double VW::Quaternion::GetZ (void) const [inline]
References _z.
Referenced by VW::AngleAxis::Set().
void VW::Quaternion::GetZXYEuler (double & theta_z, double & theta_x, double & theta_y) const [inline]
References _r, _x, _y, and _z.
void VW::Quaternion::GetZXZEuler (double & theta_z1, double & theta_x, double & theta_z2) const [inline]
References _r, _x, _y, and _z.
void VW::Quaternion::GetZYXEuler (double & theta_z, double & theta_y, double & theta_x) const [inline]
References _r, _x, _y, and _z.
VW::Vector3D VW::Quaternion::Imaginary () const
Returns:
the imaginary part (sin(theta/2)*(x,y,z)) of the quaternion
References _x, _y, and _z.
Referenced by Axis(), operator*(), and Rotate().
VW::Quaternion VW::Quaternion::Inverse () const [inline]
References _r, _x, _y, and _z.
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), and VW::ThreeDToolGLCommon::Dragged().
void VW::Quaternion::Normalise () [inline]
Make sure this is a unit vector.
This is called automatically when constructing from four doubles.
References _r, _x, _y, _z, and std::sqrt().
Referenced by Quaternion(), and Set().
bool VW::Quaternion::operator!= (const VW::Quaternion & q) const [inline]
Is q1 different from this quaternion.
References _r, _x, _y, and _z.
VW::Quaternion VW::Quaternion::operator* (const VW::Quaternion & q) const
Combine two rotations.
Parameters:
q the inner rotation
Returns:
the resulting rotation (like this*q for matrices)
References _r, VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), Imaginary(), and VW::VectorProduct().
VW::LineSeg3D VW::Quaternion::operator* (const VW::LineSeg3D & l) const
Rotate a line segment.
Parameters:
l the line segment to be rotated
Returns:
the resulting rotated line segment
References Rotate().
VW::Vector3D VW::Quaternion::operator* (const VW::Vector3D & v) const
Parameters:
v the vector to be rotated
Returns:
the resulting rotated vector
References Rotate().
bool VW::Quaternion::operator== (const VW::Quaternion & q) const [inline]
Is q1 identitical to this quaternion.
References _r, _x, _y, and _z.
const double & VW::Quaternion::R () const [inline]
Returns:
a constant reference to the real part of the quaternion
References _r.
double & VW::Quaternion::R () [inline]
Returns:
a reference to the real part of the quaternion
References _r.
Referenced by RotationMatrix(), and RotationMatrixTranspose().
bool VW::Quaternion::ReadASCII (std::istream & stream) [inline, virtual]
Read from an ASCII input stream, from Roll, Pitch, Yaw (ZXY) Euler angles in degrees.
Implements VW::IOObject.
References _r, _x, _y, and _z.
bool VW::IOObject::ReadASCIIFile (const std::string & filename) [virtual, inherited]
Open a file and input as plain ASCII.
Open a file and read as plain ASCII.
Once the file is open, the child class's ReadASCII function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadASCII().
bool VW::Quaternion::ReadBinary (std::istream & stream) [inline, virtual]
Read binary data (order is x,y,z,r).
Implements VW::IOObject.
References _r, _x, _y, and _z.
bool VW::IOObject::ReadBinaryFile (const std::string & filename) [virtual, inherited]
Open a file and input as binary.
Open a file and read as binary.
Once the file is open, the child class's ReadBinary function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadBinary().
bool VW::Quaternion::ReadXML (std::istream & stream, const std::string & name = "") [inline, virtual]
Stream as XML style ASCII.
Parameters:
stream the input stream to read from
name if specified, the found tag must have a NAME= parameter that matches
Returns:
true if successfully read, false if there are problems
Implements VW::IOObject.
References _r, _x, _y, _z, VW::FindXMLBlock(), and VW::GetXMLBlock().
bool VW::IOObject::ReadXMLFile (const std::string & filename, const std::string & name = "") [virtual, inherited]
Open a file and input as XML style ASCII.
Open a file and read as XML-style ASCII.
Once the file is open, the child class's ReadXML function is used to read the content.
Parameters:
filename the name of the file to open
name the optional name tag-attribute to match ie. data must start <MyClass name="name">
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadXML().
Referenced by VW::ClassifierUV::ClassifierUV(), and VW::FirewireCameraGTK::LoadParameterFile().
double VW::Quaternion::Real () const [inline]
Returns:
the real part (cos(theta/2)) of the quaternion
References _r.
VW::LineSeg3D VW::Quaternion::Rotate (const VW::LineSeg3D & l) const
Rotate a line segment.
Parameters:
l the line segment to be rotated
Returns:
the resulting rotated line segment
References _r, VW::LineSeg3D::EndPoint(), Imaginary(), VW::LineSeg3D::StartPoint(), and VW::VectorProduct().
VW::Vector3D VW::Quaternion::Rotate (const VW::Vector3D & v) const
Rotate a vector.
Parameters:
v the vector to be rotated
Returns:
the resulting rotated vector
References _r, Imaginary(), and VW::VectorProduct().
Referenced by VW::ThreePointPose::ComputeQRotn(), operator*(), VW::AWFObject::Rotate(), and VW::AWFFace::Rotate().
VW::RotationMatrix VW::Quaternion::RotationMatrix () const
References _r, _x, _y, _z, and R().
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::Dragged(), VW::ThreeDToolGLCommon::DrawCinemaScreen(), VW::RotationCentre::Include(), VW::RotationMatrix::Set(), and VW::ThreeDToolGLCommon::TranslateDrawingPosition().
VW::RotationMatrix VW::Quaternion::RotationMatrixTranspose () const
Returns:
the rotation matrix corresponding to the inverse rotation by this quaternion.
References _r, _x, _y, _z, and R().
void VW::Quaternion::Set (const VW::RotationMatrix & R)
Set from a rotation matrix.
Parameters:
R the rotation matrix from which the quaternion will be extracted
References _r, _x, _y, _z, and std::sqrt().
void VW::Quaternion::Set (const VW::AngleAxis & angleaxis)
Set using an angle-axis vector.
The angle is recovered as \| angleaxis \| = angle and the axis as axis = angleaxis / angle.
Parameters:
angleaxis the 3D vector whose size gives the angle and direction gives the axis
References _r, _x, _y, _z, c, VW::AngleAxis::GetX(), VW::AngleAxis::GetY(), VW::AngleAxis::GetZ(), and std::sqrt().
void VW::Quaternion::Set (const VW::Vector3D & axis, const double & angle)
Set using a rotation axis and angle.
Parameters:
axis the axis (doesn't need to be a unit vector) around which to rotate
angle the rotation angle in radians
References _r, _x, _y, _z, c, VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), and VW::Point3D::Norm().
void VW::Quaternion::Set (double x, double y, double z, double r) [inline]
Set elements individually.
References _r, _x, _y, _z, and Normalise().
Referenced by VW::ThreePointPose::ComputeQRotn(), VW::ThreeDToolGLCommon::LookAt(), Quaternion(), and VW::DrawingPosition::Zero().
void VW::Quaternion::SetFromXYZEuler (const double theta_x, const double theta_y, const double theta_z) [inline]
Create a quaternion from X,Y,Z rotations.
Note that the rotations are applied in order to an object, so q_xyz * X = R_z * R_y * R_x * X.
References _r, _x, _y, and _z.
void VW::Quaternion::SetFromYXZEuler (const double theta_y, const double theta_x, const double theta_z) [inline]
Create a quaternion from yaw, pitch, roll.
Note that the rotations are applied in order to an object, so q_zxy * X = R_z * R_x * R_y * X.
References _r, _x, _y, and _z.
void VW::Quaternion::SetFromZXYEuler (const double theta_z, const double theta_x, const double theta_y) [inline]
Create a quaternion from roll, pitch, yaw.
Note that the rotations are applied in order to an object, so q_zxy * X = R_y * R_x * R_z * X.
References _r, _x, _y, and _z.
void VW::Quaternion::SetFromZXZEuler (const double theta_z1, const double theta_x, const double theta_z2) [inline]
Create a quaternion from Z,X,Z rotations.
Note that the rotations are applied in order to an object, so q_zxz * X = R_z2 * R_x * R_z1 * X. The ZXZ form is common in physics-based problems.
References _r, _x, _y, and _z.
void VW::Quaternion::SetFromZYXEuler (const double theta_z, const double theta_y, const double theta_x) [inline]
Create a quaternion from Z,Y,X rotations.
Note that the rotations are applied in order to an object, so q_zyx * X = R_x * R_y * R_z * X.
References _r, _x, _y, and _z.
void VW::Quaternion::SetRXYZ (const VNL::VectorFixed< 4, double > & vRXYZ) [inline]
Set a quaternion from the values of a VNL 4-vector.
The vector should have the R part first, as in many quaternion implementations.
References _r, _x, _y, and _z.
bool VW::Quaternion::WriteASCII (std::ostream & stream) const [inline, virtual]
Write space separated data (order is x,y,z,r).
Implements VW::IOObject.
References _r, _x, _y, and _z.
bool VW::IOObject::WriteASCIIFile (const std::string & filename) const [inherited]
Open a file and output as plain ASCII (overwriting any existing contents).
Open a file and output as plain ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteASCII function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteASCII().
bool VW::Quaternion::WriteBinary (std::ostream & stream) const [inline, virtual]
Write binary data (order is x,y,z,r).
Implements VW::IOObject.
References _r, _x, _y, and _z.
bool VW::IOObject::WriteBinaryFile (const std::string & filename) const [inherited]
Open a file and output as binary (overwriting any existing contents).
Once the file is open, the child class's WriteBinary function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteBinary().
bool VW::Quaternion::WriteXML (std::ostream & stream, const std::string & name = "") const [inline, virtual]
Stream as XML style ASCII.
Parameters:
stream the output stream to write to
name if specified, the class will be given a NAME= parameter
Returns:
true if successfully written, false if there are problems
Implements VW::IOObject.
References _r, _x, _y, and _z.
bool VW::IOObject::WriteXMLFile (const std::string & filename, const std::string & name = "") const [inherited]
Open a file and output as XML-style ASCII (overwriting any existing contents).
Open a file and output as XML-style ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteXML function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
name the tag parameter, if required
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteXML().
Referenced by VW::FirewireCameraGTK::SaveParameterFile().
const double & VW::Quaternion::X () const [inline]
Returns:
a constant reference to the first imaginary part of the quaternion
References _x.
double & VW::Quaternion::X () [inline]
Returns:
a reference to the first imaginary part of the quaternion
References _x.
const double & VW::Quaternion::Y () const [inline]
Returns:
a constant reference to the second imaginary part of the quaternion
References _y.
double & VW::Quaternion::Y () [inline]
Returns:
a reference to the second imaginary part of the quaternion
References _y.
const double & VW::Quaternion::Z () const [inline]
Returns:
a constant reference to the third imaginary part of the quaternion
References _z.
double & VW::Quaternion::Z () [inline]
Returns:
a reference to the third imaginary part of the quaternion
References _z.
Member Data Documentation
double VW::Quaternion::_r [protected]
Referenced by Angle(), Conjugate(), Get(), GetR(), GetRXYZ(), GetXYZEuler(), GetYXZEuler(), GetZXYEuler(), GetZXZEuler(), GetZYXEuler(), Inverse(), Normalise(), operator!=(), operator*(), operator==(), R(), ReadASCII(), ReadBinary(), ReadXML(), Real(), Rotate(), RotationMatrix(), RotationMatrixTranspose(), Set(), SetFromXYZEuler(), SetFromYXZEuler(), SetFromZXYEuler(), SetFromZXZEuler(), SetFromZYXEuler(), SetRXYZ(), WriteASCII(), WriteBinary(), and WriteXML().
double VW::Quaternion::_x [protected]
Referenced by Angle(), AngleAxis(), Conjugate(), Get(), GetRXYZ(), GetX(), GetXYZEuler(), GetYXZEuler(), GetZXYEuler(), GetZXZEuler(), GetZYXEuler(), Imaginary(), Inverse(), Normalise(), operator!=(), operator==(), ReadASCII(), ReadBinary(), ReadXML(), RotationMatrix(), RotationMatrixTranspose(), Set(), SetFromXYZEuler(), SetFromYXZEuler(), SetFromZXYEuler(), SetFromZXZEuler(), SetFromZYXEuler(), SetRXYZ(), WriteASCII(), WriteBinary(), WriteXML(), and X().
double VW::Quaternion::_y [protected]
Referenced by Angle(), AngleAxis(), Conjugate(), Get(), GetRXYZ(), GetXYZEuler(), GetY(), GetYXZEuler(), GetZXYEuler(), GetZXZEuler(), GetZYXEuler(), Imaginary(), Inverse(), Normalise(), operator!=(), operator==(), ReadASCII(), ReadBinary(), ReadXML(), RotationMatrix(), RotationMatrixTranspose(), Set(), SetFromXYZEuler(), SetFromYXZEuler(), SetFromZXYEuler(), SetFromZXZEuler(), SetFromZYXEuler(), SetRXYZ(), WriteASCII(), WriteBinary(), WriteXML(), and Y().
double VW::Quaternion::_z [protected]
Referenced by Angle(), AngleAxis(), Conjugate(), Get(), GetRXYZ(), GetXYZEuler(), GetYXZEuler(), GetZ(), GetZXYEuler(), GetZXZEuler(), GetZYXEuler(), Imaginary(), Inverse(), Normalise(), operator!=(), operator==(), ReadASCII(), ReadBinary(), ReadXML(), RotationMatrix(), RotationMatrixTranspose(), Set(), SetFromXYZEuler(), SetFromYXZEuler(), SetFromZXYEuler(), SetFromZXZEuler(), SetFromZYXEuler(), SetRXYZ(), WriteASCII(), WriteBinary(), WriteXML(), and Z().
The documentation for this class was generated from the following files:
quaternion.h
quaternion.cpp