VW: VW::ImagePatch Class Reference
VW::ImagePatch Class Reference
#include <imagepatch.h>
Public Member Functions
ImagePatch (const unsigned int size=5)
Data is created on construction, so height, width required.
ImagePatch (const unsigned int width, const unsigned int height)
Data is created on construction, so height, width required.
ImagePatch (const ImagePatch &p)
virtual ~ImagePatch ()
void Resize (const unsigned int width, const unsigned int height)
unsigned int GetWidth () const
Return patch width.
unsigned int GetHeight () const
Return patch height.
void SetData (const unsigned int x, const unsigned int y, const float value)
Set one element of data.
float GetData (const unsigned int x, const unsigned int y) const
Get one element of data.
std::vector< float >
::const_iterator GetRowStart (const unsigned int y) const
std::vector< float >::iterator GetRowStart (const unsigned int y)
float GetMean () const
Return the mean of the data.
float GetVariance () const
Return the variance of the data around the mean.
float GetZNCC (const VW::ImagePatch &p2) const
Return the variance of the data around the mean.
float GetNormalisedSumSquared () const
Return the normalised sum-squared.
float GetElementProduct (const VW::ImagePatch &p2) const
Get the element-by-element product of this patch with another.
virtual bool WriteASCII (std::ostream &stream) const
Stream as plain ASCII.
virtual bool WriteXML (std::ostream &stream, const std::string &name="") const
Stream as XML style ASCII.
virtual bool WriteBinary (std::ostream &stream) const
Stream as binary.
virtual bool ReadASCII (std::istream &stream)
Stream as plain ASCII.
virtual bool ReadXML (std::istream &stream, const std::string &name="")
Stream as XML style ASCII.
virtual bool ReadBinary (std::istream &stream)
Stream as binary.
bool WriteASCIIFile (const std::string &filename) const
Open a file and output as plain ASCII (overwriting any existing contents).
bool WriteXMLFile (const std::string &filename, const std::string &name="") const
Open a file and output as XML-style ASCII (overwriting any existing contents).
bool WriteBinaryFile (const std::string &filename) const
Open a file and output as binary (overwriting any existing contents).
virtual bool ReadASCIIFile (const std::string &filename)
Open a file and input as plain ASCII.
virtual bool ReadXMLFile (const std::string &filename, const std::string &name="")
Open a file and input as XML style ASCII.
virtual bool ReadBinaryFile (const std::string &filename)
Open a file and input as binary.
Detailed Description
Author:
BJ Tordoff
Date:
28/03/2002 @ Brief A storage class for simple (mono) image patches.
Functions are provided for creating patches from mono images using a supplied image position. If the position is supplied as floating point then bilinear interpolation is used to get the values. This doesn't cost much processing, and Smith:Sinclair:Cipolla:Wood:BMVC1998 indicate that it has some serious effect on the matching. However, I have some reservations about the fairness of their comparisons, so the choice is yours. Note that getting and setting of data is unchecked, so be careful of sizes.
Constructor & Destructor Documentation
VW::ImagePatch::ImagePatch (const unsigned int size = 5) [inline]
Data is created on construction, so height, width required.
VW::ImagePatch::ImagePatch (const unsigned int width, const unsigned int height) [inline]
Data is created on construction, so height, width required.
VW::ImagePatch::ImagePatch (const ImagePatch & p) [inline]
References GetData().
virtual VW::ImagePatch::~ImagePatch () [inline, virtual]
Member Function Documentation
float VW::ImagePatch::GetData (const unsigned int x, const unsigned int y) const [inline]
Get one element of data.
Referenced by ImagePatch().
float VW::ImagePatch::GetElementProduct (const VW::ImagePatch & p2) const [inline]
Get the element-by-element product of this patch with another.
References GetHeight(), and GetWidth().
Referenced by GetZNCC().
unsigned int VW::ImagePatch::GetHeight (void) const [inline]
Return patch height.
Referenced by VW::Correlate::Compute(), GetElementProduct(), VW::GetImagePatch(), and VW::GetInterpolatedImagePatch().
float VW::ImagePatch::GetMean () const [inline]
Return the mean of the data.
Referenced by VW::Correlate::Compute(), and GetZNCC().
float VW::ImagePatch::GetNormalisedSumSquared () const [inline]
Return the normalised sum-squared.
This is .
Referenced by VW::Correlate::Compute(), and GetZNCC().
std::vector< float >::iterator VW::ImagePatch::GetRowStart (const unsigned int y) [inline]
std::vector< float >::const_iterator VW::ImagePatch::GetRowStart (const unsigned int y) const [inline]
Referenced by VW::Correlate::Compute().
float VW::ImagePatch::GetVariance () const [inline]
Return the variance of the data around the mean.
unsigned int VW::ImagePatch::GetWidth (void) const [inline]
Return patch width.
Referenced by VW::Correlate::Compute(), GetElementProduct(), VW::GetImagePatch(), and VW::GetInterpolatedImagePatch().
float VW::ImagePatch::GetZNCC (const VW::ImagePatch & p2) const [inline]
Return the variance of the data around the mean.
References GetElementProduct(), GetMean(), GetNormalisedSumSquared(), and std::sqrt().
Referenced by VW::Correlate::Compute(), and VW::PlesseyCornerMatcher::GetMatchScore().
bool VW::ImagePatch::ReadASCII (std::istream & stream) [inline, virtual]
Stream as plain ASCII.
Implements VW::IOObject.
References Resize().
Referenced by VW::PlesseyCorner::ReadASCII().
bool VW::IOObject::ReadASCIIFile (const std::string & filename) [virtual, inherited]
Open a file and input as plain ASCII.
Open a file and read as plain ASCII.
Once the file is open, the child class's ReadASCII function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadASCII().
bool VW::ImagePatch::ReadBinary (std::istream & stream) [inline, virtual]
Stream as binary.
Implements VW::IOObject.
References VW::ReadBinary(), and Resize().
Referenced by VW::PlesseyCorner::ReadBinary().
bool VW::IOObject::ReadBinaryFile (const std::string & filename) [virtual, inherited]
Open a file and input as binary.
Open a file and read as binary.
Once the file is open, the child class's ReadBinary function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadBinary().
bool VW::ImagePatch::ReadXML (std::istream & stream, const std::string & name = "") [inline, virtual]
Stream as XML style ASCII.
Implements VW::IOObject.
References VW::FindXMLBlock(), VW::GetXMLBlock(), VW::GetXMLBlockAsNumber(), and Resize().
Referenced by VW::PlesseyCorner::ReadXML().
bool VW::IOObject::ReadXMLFile (const std::string & filename, const std::string & name = "") [virtual, inherited]
Open a file and input as XML style ASCII.
Open a file and read as XML-style ASCII.
Once the file is open, the child class's ReadXML function is used to read the content.
Parameters:
filename the name of the file to open
name the optional name tag-attribute to match ie. data must start <MyClass name="name">
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadXML().
Referenced by VW::ClassifierUV::ClassifierUV(), and VW::FirewireCameraGTK::LoadParameterFile().
void VW::ImagePatch::Resize (const unsigned int width, const unsigned int height) [inline]
Referenced by VW::Correlate::Compute(), ReadASCII(), ReadBinary(), ReadXML(), VW::PlesseyCorner::Set(), and VW::PlesseyCorner::SetPatchSize().
void VW::ImagePatch::SetData (const unsigned int x, const unsigned int y, const float value) [inline]
Set one element of data.
Referenced by VW::GetImagePatch(), and VW::GetInterpolatedImagePatch().
bool VW::ImagePatch::WriteASCII (std::ostream & stream) const [inline, virtual]
Stream as plain ASCII.
Implements VW::IOObject.
Referenced by VW::PlesseyCorner::WriteASCII().
bool VW::IOObject::WriteASCIIFile (const std::string & filename) const [inherited]
Open a file and output as plain ASCII (overwriting any existing contents).
Open a file and output as plain ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteASCII function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteASCII().
bool VW::ImagePatch::WriteBinary (std::ostream & stream) const [inline, virtual]
Stream as binary.
Implements VW::IOObject.
References VW::WriteBinary().
Referenced by VW::PlesseyCorner::WriteBinary().
bool VW::IOObject::WriteBinaryFile (const std::string & filename) const [inherited]
Open a file and output as binary (overwriting any existing contents).
Once the file is open, the child class's WriteBinary function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteBinary().
bool VW::ImagePatch::WriteXML (std::ostream & stream, const std::string & name = "") const [inline, virtual]
Stream as XML style ASCII.
Implements VW::IOObject.
Referenced by VW::PlesseyCorner::WriteXML().
bool VW::IOObject::WriteXMLFile (const std::string & filename, const std::string & name = "") const [inherited]
Open a file and output as XML-style ASCII (overwriting any existing contents).
Open a file and output as XML-style ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteXML function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
name the tag parameter, if required
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteXML().
Referenced by VW::FirewireCameraGTK::SaveParameterFile().
The documentation for this class was generated from the following file:
imagepatch.h