VW: VW::CalibrationTable Class Reference
VW::CalibrationTable Class Reference
[GeometricObjects]
A camera calibration look-up table.
#include <calibrationtable.h>
Public Member Functions
CalibrationTable ()
virtual ~CalibrationTable ()
void AddCalibrationData (double motor_position, const VW::CalibrationMatrix &K)
void AddDistortionData (double motor_position, const double kappa)
VW::CalibrationMatrix GetCalibrationMatrix (double motor_position) const
double GetDistortion (double motor_position) const
double GetMotorPosition (double focal_length) const
void GetMotorLimits (double &motor_min, double &motor_max) const
void SetVaryingAspect ()
void SetVaryingSkew ()
void SetVaryingPrincipalPoint ()
void SetFixedAspect ()
void SetFixedSkew ()
void SetFixedPrincipalPoint ()
void SetKnownAspect (double aspect=1.0)
void SetKnownSkew (double skew=0.0)
void SetKnownPrincipalPoint (double px=0.0, double py=0.0)
void Clear ()
virtual bool WriteASCII (std::ostream &stream) const
Stream as plain ASCII.
virtual bool WriteXML (std::ostream &stream, const std::string &name="") const
Stream as XML style ASCII.
virtual bool WriteBinary (std::ostream &stream) const
Stream as binary.
virtual bool ReadASCII (std::istream &stream)
Stream as plain ASCII.
virtual bool ReadXML (std::istream &stream, const std::string &name="")
Stream as XML style ASCII.
virtual bool ReadBinary (std::istream &stream)
Stream as binary.
void PrintPolyCoeffs ()
bool WriteASCIIFile (const std::string &filename) const
Open a file and output as plain ASCII (overwriting any existing contents).
bool WriteXMLFile (const std::string &filename, const std::string &name="") const
Open a file and output as XML-style ASCII (overwriting any existing contents).
bool WriteBinaryFile (const std::string &filename) const
Open a file and output as binary (overwriting any existing contents).
virtual bool ReadASCIIFile (const std::string &filename)
Open a file and input as plain ASCII.
virtual bool ReadXMLFile (const std::string &filename, const std::string &name="")
Open a file and input as XML style ASCII.
virtual bool ReadBinaryFile (const std::string &filename)
Open a file and input as binary.
Detailed Description
A camera calibration look-up table.
Author:
BJ Tordoff
Date:
02/11/2002 This class can hold a single calibration instance for a camera, or a set of calibrations sampled at various zoom-lens motor positions. In the latter case the calibration parameters are used to fit polynomials so that interpolated values can be retrieved.
CameraCalibration inherits from IOObject and is able to read calibration data from suitably formatted data files. The data is input/output in the following order:
Number of calibration data points
Number of distortion data points
Array of calibration data
motor position
focal-length
aspect
skew
principal-x
principal-y
Array of distortion data
motor position
kappa
Constructor & Destructor Documentation
VW::CalibrationTable::CalibrationTable ()
VW::CalibrationTable::~CalibrationTable () [virtual]
References VERBOSE.
Member Function Documentation
void VW::CalibrationTable::AddCalibrationData (double motor_position, const VW::CalibrationMatrix & K) [inline]
References VW::ChebyshevPolynomial::AddData(), VW::CalibrationMatrix::GetAspectRatio(), VW::CalibrationMatrix::GetFocalLength(), VW::CalibrationMatrix::GetPrincipalPointX(), VW::CalibrationMatrix::GetPrincipalPointY(), and VW::CalibrationMatrix::GetSkew().
void VW::CalibrationTable::AddDistortionData (double motor_position, const double kappa) [inline]
References VW::ChebyshevPolynomial::AddData().
void VW::CalibrationTable::Clear () [inline]
References VW::ChebyshevPolynomial::Clear().
Referenced by ReadBinary(), and ReadXML().
VW::CalibrationMatrix VW::CalibrationTable::GetCalibrationMatrix (double motor_position) const [inline]
References VW::ChebyshevPolynomial::GetYValue(), VW::CalibrationMatrix::SetAspectRatio(), VW::CalibrationMatrix::SetFocalLength(), VW::CalibrationMatrix::SetPrincipalPointX(), VW::CalibrationMatrix::SetPrincipalPointY(), VW::CalibrationMatrix::SetSkew(), and VERBOSE.
double VW::CalibrationTable::GetDistortion (double motor_position) const [inline]
References VW::ChebyshevPolynomial::GetYValue().
void VW::CalibrationTable::GetMotorLimits (double & motor_min, double & motor_max) const [inline]
double VW::CalibrationTable::GetMotorPosition (double focal_length) const [inline]
References VW::ChebyshevPolynomial::GetYValue().
void VW::CalibrationTable::PrintPolyCoeffs () [inline]
References VW::ChebyshevPolynomial::GetCoeffs().
bool VW::CalibrationTable::ReadASCII (std::istream & stream) [virtual]
Stream as plain ASCII.
Parameters:
stream the input stream to read from
Returns:
true if successfully read, false if there are problems
Implements VW::IOObject.
References VERBOSE.
bool VW::IOObject::ReadASCIIFile (const std::string & filename) [virtual, inherited]
Open a file and input as plain ASCII.
Open a file and read as plain ASCII.
Once the file is open, the child class's ReadASCII function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadASCII().
bool VW::CalibrationTable::ReadBinary (std::istream & stream) [virtual]
Stream as binary.
Parameters:
stream the input stream to read from
Returns:
true if successfully read, false if there are problems
Implements VW::IOObject.
References Clear(), and m.
bool VW::IOObject::ReadBinaryFile (const std::string & filename) [virtual, inherited]
Open a file and input as binary.
Open a file and read as binary.
Once the file is open, the child class's ReadBinary function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadBinary().
bool VW::CalibrationTable::ReadXML (std::istream & stream, const std::string & name = "") [virtual]
Stream as XML style ASCII.
Parameters:
stream the input stream to read from
name if specified, the found tag must have a NAME= parameter that matches
Returns:
true if successfully read, false if there are problems
Implements VW::IOObject.
References Clear(), VW::FindXMLBlock(), VW::GetXMLBlock(), VW::GetXMLBlockAsNumber(), m, and VERBOSE.
bool VW::IOObject::ReadXMLFile (const std::string & filename, const std::string & name = "") [virtual, inherited]
Open a file and input as XML style ASCII.
Open a file and read as XML-style ASCII.
Once the file is open, the child class's ReadXML function is used to read the content.
Parameters:
filename the name of the file to open
name the optional name tag-attribute to match ie. data must start <MyClass name="name">
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadXML().
Referenced by VW::ClassifierUV::ClassifierUV(), and VW::FirewireCameraGTK::LoadParameterFile().
void VW::CalibrationTable::SetFixedAspect () [inline]
References VW::ChebyshevPolynomial::SetPolynomialOrder().
void VW::CalibrationTable::SetFixedPrincipalPoint () [inline]
References VW::ChebyshevPolynomial::SetPolynomialOrder().
void VW::CalibrationTable::SetFixedSkew () [inline]
References VW::ChebyshevPolynomial::SetPolynomialOrder().
void VW::CalibrationTable::SetKnownAspect (double aspect = 1.0) [inline]
void VW::CalibrationTable::SetKnownPrincipalPoint (double px = 0.0, double py = 0.0) [inline]
void VW::CalibrationTable::SetKnownSkew (double skew = 0.0) [inline]
void VW::CalibrationTable::SetVaryingAspect () [inline]
References K_POLYFITORDER, and VW::ChebyshevPolynomial::SetPolynomialOrder().
void VW::CalibrationTable::SetVaryingPrincipalPoint () [inline]
References K_POLYFITORDER, and VW::ChebyshevPolynomial::SetPolynomialOrder().
void VW::CalibrationTable::SetVaryingSkew () [inline]
References K_POLYFITORDER, and VW::ChebyshevPolynomial::SetPolynomialOrder().
bool VW::CalibrationTable::WriteASCII (std::ostream & stream) const [virtual]
Stream as plain ASCII.
Parameters:
stream the output stream to write to
Returns:
true if successfully written, false if there are problems
Implements VW::IOObject.
References m, and VERBOSE.
bool VW::IOObject::WriteASCIIFile (const std::string & filename) const [inherited]
Open a file and output as plain ASCII (overwriting any existing contents).
Open a file and output as plain ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteASCII function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteASCII().
bool VW::CalibrationTable::WriteBinary (std::ostream & stream) const [virtual]
Stream as binary.
Parameters:
stream the output stream to write to
Returns:
true if successfully written, false if there are problems
Implements VW::IOObject.
References m.
bool VW::IOObject::WriteBinaryFile (const std::string & filename) const [inherited]
Open a file and output as binary (overwriting any existing contents).
Once the file is open, the child class's WriteBinary function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteBinary().
bool VW::CalibrationTable::WriteXML (std::ostream & stream, const std::string & name = "") const [virtual]
Stream as XML style ASCII.
Parameters:
stream the output stream to write to
name if specified, the class will be given a NAME= parameter
Returns:
true if successfully written, false if there are problems
Implements VW::IOObject.
References m.
bool VW::IOObject::WriteXMLFile (const std::string & filename, const std::string & name = "") const [inherited]
Open a file and output as XML-style ASCII (overwriting any existing contents).
Open a file and output as XML-style ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteXML function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
name the tag parameter, if required
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteXML().
Referenced by VW::FirewireCameraGTK::SaveParameterFile().
The documentation for this class was generated from the following files:
calibrationtable.h
calibrationtable.cpp