VW: VW::LineSeg2D Class Reference
VW::LineSeg2D Class Reference
[GeometricObjects]
Representation of a 2D line segment.
#include <lineseg2d.h>
Public Member Functions
LineSeg2D (void)
LineSeg2D (const double x0, const double y0, const double x1, const double y1)
LineSeg2D (const Point2D &p0, const Point2D &p1)
LineSeg2D (const Point2D *p0, const Point2D *p1)
virtual ~LineSeg2D ()
LineSeg2D & operator= (const LineSeg2D &ls)
bool operator== (const LineSeg2D &ls)
void GetEndPoints (double &x0, double &y0, double &x1, double &y1) const
void GetEndPoints (Point2D &p0, Point2D &p1) const
Point2D GetStartPoint (void) const
double GetStartX (void) const
double GetStartY (void) const
Point2D GetEndPoint (void) const
double GetEndX (void) const
double GetEndY (void) const
Point2D GetMidPoint (void) const
void SetEndPoints (const double x0, const double y0, const double x1, const double y1)
void SetEndPoints (const Point2D p0, const Point2D p1)
void SetStartPoint (const Point2D p)
void SetEndPoint (const Point2D p)
LineSeg2D Truncate (const double x0, const double y0, const double x1, const double y1) const
Truncate to lie within a rectangle (x0,y0)->(x1,y1) (eg for displaying).
Vector2D GetDirection () const
Get the direction.
double GetLength () const
Get the length of the segment.
double GetLength2 () const
Get the sqaured length of the segment.
double Norm () const
The norm (length) of the segment.
double Norm2 () const
The squared norm (length) of the segment.
double GetAngle () const
Return the angle between the +ve X-axis and the line, measured clockwise ().
double GetDistanceToOrigin () const
Return the perpendicular distance of line from origin.
double DistanceToLeft (const VW::Point2D &testpoint) const
The distance to the left of the line to reach the testpoint (negative if to right).
bool IsToLeft (const VW::Point2D &testpoint) const
Is a point to the left of the line.
double DistanceToRight (const VW::Point2D &testpoint) const
The distance to the right of the line to reach the testpoint (negative if to left).
bool IsToRight (const VW::Point2D &testpoint) const
Is a point to the right of the line.
Line2D GetLine () const
Return the infinite line that this segment is part of.
double GetDistanceToLine (const VW::Point2D &testpoint) const
distance to infinite line.
double GetDistanceToLineSeg (const VW::Point2D &testpoint) const
distance to line segment including endpoints
double GetCosAngle (const VW::LineSeg2D &lineseg) const
Get the cosine of the angle between two line-segments.
bool GetIntersection (const VW::LineSeg2D &lineseg, VW::Point2D &result) const
Find the point of intersection of this lineseg with another.
virtual bool WriteASCII (std::ostream &stream) const
virtual bool WriteXML (std::ostream &stream, const std::string &name="") const
virtual bool WriteBinary (std::ostream &stream) const
virtual bool ReadASCII (std::istream &stream)
virtual bool ReadXML (std::istream &stream, const std::string &name="")
virtual bool ReadBinary (std::istream &stream)
Public Attributes
Point2D sp
Point2D ep
Friends
double operator* (const LineSeg2D &ls1, const LineSeg2D &ls2)
std::ostream & operator<< (std::ostream &s, const LineSeg2D &ls)
std::istream & operator>> (std::istream &s, LineSeg2D &ls)
Detailed Description
Representation of a 2D line segment.
Author:
ID Reid
Date:
02/08/2002
Constructor & Destructor Documentation
LineSeg2D::LineSeg2D (void)
Referenced by Truncate().
LineSeg2D::LineSeg2D (const double x0, const double y0, const double x1, const double y1)
LineSeg2D::LineSeg2D (const Point2D & p0, const Point2D & p1)
LineSeg2D::LineSeg2D (const Point2D * p0, const Point2D * p1)
LineSeg2D::~LineSeg2D () [virtual]
Member Function Documentation
double VW::LineSeg2D::DistanceToLeft (const VW::Point2D & testpoint) const [inline]
The distance to the left of the line to reach the testpoint (negative if to right).
References ep, VW::Point2D::GetX(), VW::Point2D::GetY(), VW::Point2D::Normalise(), and sp.
Referenced by IsToLeft().
double VW::LineSeg2D::DistanceToRight (const VW::Point2D & testpoint) const [inline]
The distance to the right of the line to reach the testpoint (negative if to left).
References ep, VW::Point2D::GetX(), VW::Point2D::GetY(), VW::Point2D::Normalise(), and sp.
Referenced by IsToRight().
double LineSeg2D::GetAngle () const
Return the angle between the +ve X-axis and the line, measured clockwise ().
References ep, VW::Point2D::GetX(), VW::Point2D::GetY(), and sp.
Referenced by VW::LineSegFitted::CorrectEndpoints(), and VW::GetAngleBetween().
double VW::LineSeg2D::GetCosAngle (const VW::LineSeg2D & lineseg) const [inline]
Get the cosine of the angle between two line-segments.
References ep, VW::Point2D::Normalise(), VW::ScalarProduct(), and sp.
VW::Vector2D VW::LineSeg2D::GetDirection () const [inline]
Get the direction.
References ep, GetLength(), and sp.
Referenced by Truncate().
double LineSeg2D::GetDistanceToLine (const VW::Point2D & testpoint) const
distance to infinite line.
References VW::Point2D::_x, VW::Point2D::_y, ep, GetLength(), and sp.
Referenced by GetDistanceToOrigin(), and GetIntersection().
double LineSeg2D::GetDistanceToLineSeg (const VW::Point2D & testpoint) const
distance to line segment including endpoints
References VW::Point2D::_x, VW::Point2D::_y, ep, VW::Point2D::GetDistance(), GetLength(), and sp.
Referenced by VW::GetDistance().
double LineSeg2D::GetDistanceToOrigin () const
Return the perpendicular distance of line from origin.
References GetDistanceToLine().
VW::Point2D VW::LineSeg2D::GetEndPoint (void) const [inline]
References ep.
Referenced by VW::RadialDistortion::Distort(), VW::Normalisation::Normalise(), VW::Line2D::Truncate(), VW::RadialDistortion::Undistort(), VW::RadialDistortion::UndistortInPlace(), and VW::Normalisation::UnNormalise().
void VW::LineSeg2D::GetEndPoints (VW::Point2D & p0, VW::Point2D & p1) const [inline]
References ep, and sp.
void VW::LineSeg2D::GetEndPoints (double & x0, double & y0, double & x1, double & y1) const [inline]
References ep, VW::Point2D::Get(), and sp.
double VW::LineSeg2D::GetEndX (void) const [inline]
References ep, and VW::Point2D::GetX().
double VW::LineSeg2D::GetEndY (void) const [inline]
References ep, and VW::Point2D::GetY().
bool LineSeg2D::GetIntersection (const VW::LineSeg2D & lineseg, VW::Point2D & result) const
Find the point of intersection of this lineseg with another.
If there is no intersection, or it's beyond the end of the line(s) it returns false.
References ep, VW::Point2D::GetDistance(), GetDistanceToLine(), GetLength(), VW::Point2D::GetX(), VW::Point2D::GetY(), VW::Point2D::Normalise(), VW::Point2D::Set(), and sp.
double VW::LineSeg2D::GetLength () const [inline]
Get the length of the segment.
References VW::Point2D::_x, VW::Point2D::_y, ep, sp, and std::sqrt().
Referenced by GetDirection(), GetDistanceToLine(), GetDistanceToLineSeg(), GetIntersection(), and Norm().
double VW::LineSeg2D::GetLength2 () const [inline]
Get the sqaured length of the segment.
References VW::Point2D::_x, VW::Point2D::_y, ep, and sp.
Referenced by Norm2().
VW::Line2D VW::LineSeg2D::GetLine () const [inline]
Return the infinite line that this segment is part of.
References ep, VW::Point2D::GetX(), VW::Point2D::GetY(), VW::Line2D::Set(), sp, and std::sqrt().
Referenced by VW::LineThroughPoints().
VW::Point2D VW::LineSeg2D::GetMidPoint (void) const [inline]
References ep, and sp.
VW::Point2D VW::LineSeg2D::GetStartPoint (void) const [inline]
References sp.
Referenced by VW::RadialDistortion::Distort(), VW::Normalisation::Normalise(), VW::Line2D::Truncate(), VW::RadialDistortion::Undistort(), VW::RadialDistortion::UndistortInPlace(), and VW::Normalisation::UnNormalise().
double VW::LineSeg2D::GetStartX (void) const [inline]
References VW::Point2D::GetX(), and sp.
double VW::LineSeg2D::GetStartY (void) const [inline]
References VW::Point2D::GetY(), and sp.
bool VW::LineSeg2D::IsToLeft (const VW::Point2D & testpoint) const [inline]
Is a point to the left of the line.
References DistanceToLeft().
Referenced by VW::IsToLeft().
bool VW::LineSeg2D::IsToRight (const VW::Point2D & testpoint) const [inline]
Is a point to the right of the line.
References DistanceToRight().
Referenced by VW::IsToRight().
double VW::LineSeg2D::Norm () const [inline]
The norm (length) of the segment.
References GetLength().
double VW::LineSeg2D::Norm2 () const [inline]
The squared norm (length) of the segment.
References GetLength2().
LineSeg2D & LineSeg2D::operator= (const LineSeg2D & ls)
References ep, and sp.
bool LineSeg2D::operator== (const LineSeg2D & ls)
References ep, and sp.
bool VW::LineSeg2D::ReadASCII (std::istream & stream) [virtual]
References ep, and sp.
Referenced by VW::operator>>().
bool VW::LineSeg2D::ReadBinary (std::istream & stream) [virtual]
References ep, VW::Point2D::ReadBinary(), and sp.
bool VW::LineSeg2D::ReadXML (std::istream & stream, const std::string & name = "") [virtual]
References ep, VW::FindXMLBlock(), VW::Point2D::ReadXML(), and sp.
void VW::LineSeg2D::SetEndPoint (const Point2D p) [inline]
References ep.
void VW::LineSeg2D::SetEndPoints (const Point2D p0, const Point2D p1) [inline]
References ep, and sp.
void VW::LineSeg2D::SetEndPoints (const double x0, const double y0, const double x1, const double y1) [inline]
References ep, VW::Point2D::Set(), and sp.
Referenced by VW::LineSegFitted::CorrectEndpoints(), and VW::RadialDistortion::UndistortInPlace().
void VW::LineSeg2D::SetStartPoint (const Point2D p) [inline]
References sp.
LineSeg2D LineSeg2D::Truncate (const double x0, const double y0, const double x1, const double y1) const
Truncate to lie within a rectangle (x0,y0)->(x1,y1) (eg for displaying).
References ep, GetDirection(), VW::Point2D::GetX(), VW::Point2D::GetY(), LineSeg2D(), and sp.
bool VW::LineSeg2D::WriteASCII (std::ostream & stream) const [virtual]
References ep, and sp.
Referenced by VW::operator<<().
bool VW::LineSeg2D::WriteBinary (std::ostream & stream) const [virtual]
References ep, sp, and VW::Point2D::WriteBinary().
bool VW::LineSeg2D::WriteXML (std::ostream & stream, const std::string & name = "") const [virtual]
References ep, sp, and VW::Point2D::WriteXML().
Friends And Related Function Documentation
double operator* (const LineSeg2D & ls1, const LineSeg2D & ls2) [friend]
std::ostream& operator<< (std::ostream & s, const LineSeg2D & ls) [friend]
std::istream& operator>> (std::istream & s, LineSeg2D & ls) [friend]
Member Data Documentation
Point2D VW::LineSeg2D::ep
Referenced by DistanceToLeft(), DistanceToRight(), VW::DrawFunctions::Draw(), GetAngle(), GetCosAngle(), GetDirection(), GetDistanceToLine(), GetDistanceToLineSeg(), GetEndPoint(), GetEndPoints(), GetEndX(), GetEndY(), GetIntersection(), GetLength(), GetLength2(), GetLine(), GetMidPoint(), operator*(), operator=(), operator==(), ReadASCII(), ReadBinary(), ReadXML(), SetEndPoint(), SetEndPoints(), Truncate(), WriteASCII(), WriteBinary(), and WriteXML().
Point2D VW::LineSeg2D::sp
Referenced by DistanceToLeft(), DistanceToRight(), VW::DrawFunctions::Draw(), GetAngle(), GetCosAngle(), GetDirection(), GetDistanceToLine(), GetDistanceToLineSeg(), GetEndPoints(), GetIntersection(), GetLength(), GetLength2(), GetLine(), GetMidPoint(), GetStartPoint(), GetStartX(), GetStartY(), operator*(), operator=(), operator==(), ReadASCII(), ReadBinary(), ReadXML(), SetEndPoints(), SetStartPoint(), Truncate(), WriteASCII(), WriteBinary(), and WriteXML().
The documentation for this class was generated from the following files:
lineseg2d.h
lineseg2d.cpp