VW: VW::PMatrixCompute::LSFuncPoints Class Reference
VW::PMatrixCompute::LSFuncPoints Class Reference
A small class that knows how to be minimised.
Public Types
enum UseGradient { no_gradient, use_gradient }
Public Member Functions
LSFuncPoints (const std::vector< VW::Point2D > &x, const std::vector< VW::Point3D > &X, const std::vector< unsigned int > &whichfeatures, const bool estimate_kappa=true, const bool zero_skew=true, const bool unity_aspect=false)
void F (const VNL::Vector< double > &x, VNL::Vector< double > &fx)
The main function.
void ThrowFailure ()
void ClearFailure ()
virtual void GradF (Vector< double > const &x, Matrix< double > &jacobian)
Calculate the Jacobian, given the parameter vector x.
void FDGradF (Vector< double > const &x, Matrix< double > &jacobian, double stepsize)
Use this to compute a finite-difference gradient other than lmdif.
virtual void Trace (int iteration, Vector< double > const &x, Vector< double > const &fx)
Called after each LM iteration to print debugging etc.
double RMS (Vector< double > const &x)
Compute the rms error at x by calling f and returning the norm of the residual vector.
int GetNumberOfUnknowns () const
Return the number of unknowns.
int GetNumberOfResiduals () const
Return the number of residuals.
bool HasGradient () const
Return true if the derived class has indicated that gradf has been implemented.
Public Attributes
bool failure
Protected Member Functions
void _init (int number_of_unknowns, int number_of_residuals)
Protected Attributes
const std::vector< VW::Point2D > & _x
const std::vector< VW::Point3D > & _X
const std::vector< unsigned int > & _whichfeatures
const bool _estimate_kappa
const bool _zero_skew
const bool _unity_aspect
int p_
int n_
bool use_gradient_
std::string print_x_fmt_
std::string print_f_fmt_
Detailed Description
A small class that knows how to be minimised.
Member Enumeration Documentation
enum VNL::LeastSquaresFunction::UseGradient [inherited]
Enumerator:
no_gradient
use_gradient
Constructor & Destructor Documentation
VW::PMatrixCompute::LSFuncPoints::LSFuncPoints (const std::vector< VW::Point2D > & x, const std::vector< VW::Point3D > & X, const std::vector< unsigned int > & whichfeatures, const bool estimate_kappa = true, const bool zero_skew = true, const bool unity_aspect = false)
Member Function Documentation
void VNL::LeastSquaresFunction::_init (int number_of_unknowns, int number_of_residuals) [protected, inherited]
References VNL::LeastSquaresFunction::n_, and VNL::LeastSquaresFunction::p_.
void VNL::LeastSquaresFunction::ClearFailure () [inherited]
References VNL::LeastSquaresFunction::failure.
Referenced by VNL::LevenbergMarquardt::lmder_lsqfun(), and VNL::LevenbergMarquardt::lmdif_lsqfun().
void VW::PMatrixCompute::LSFuncPoints::F (const VNL::Vector< double > & x, VNL::Vector< double > & fx) [virtual]
The main function.
Given the parameter vector x, compute the vector of residuals fx. Fx has been sized appropriately before the call.
Implements VNL::LeastSquaresFunction.
References _estimate_kappa, _whichfeatures, _x, _X, _zero_skew, VNL::Vector< T >::begin(), VW::RadialDistortion::DistortPoint(), VW::Point2D::GetDistance(), VW::PMatrixCompute::ParamVecToTransform(), and VW::ProjectionMatrix::Project().
void VNL::LeastSquaresFunction::FDGradF (VNL::Vector< double > const & x, VNL::Matrix< double > & jacobian, double stepsize) [inherited]
Use this to compute a finite-difference gradient other than lmdif.
Compute fd gradient.
References VNL::Matrix< T >::Columns(), VNL::LeastSquaresFunction::F(), VNL::LeastSquaresFunction::GetNumberOfResiduals(), VNL::LeastSquaresFunction::GetNumberOfUnknowns(), VNL::Matrix< T >::Rows(), and VNL::Vector< T >::size().
int VNL::LeastSquaresFunction::GetNumberOfResiduals () const [inline, inherited]
Return the number of residuals.
References VNL::LeastSquaresFunction::n_.
Referenced by VNL::LevenbergMarquardt::_Init(), VNL::LevenbergMarquardt::DiagnoseOutcome(), VNL::LeastSquaresFunction::FDGradF(), VNL::LevenbergMarquardt::lmder_lsqfun(), VNL::LevenbergMarquardt::lmdif_lsqfun(), VNL::LevenbergMarquardt::MinimizeUsingGradient(), VNL::LevenbergMarquardt::MinimizeWithoutGradient(), vnl_discrete_diff_fwd(), vnl_discrete_diff_sym(), and vnl_discrete_diff_test_lsf().
int VNL::LeastSquaresFunction::GetNumberOfUnknowns () const [inline, inherited]
Return the number of unknowns.
References VNL::LeastSquaresFunction::p_.
Referenced by VNL::LevenbergMarquardt::_Init(), VW::FMPlanarComputeNonLinear::Compute(), VW::FMatrixComputeNonLinear::Compute(), VNL::LeastSquaresFunction::FDGradF(), VNL::LevenbergMarquardt::lmder_lsqfun(), VNL::LevenbergMarquardt::lmdif_lsqfun(), VNL::LevenbergMarquardt::MinimizeUsingGradient(), VNL::LevenbergMarquardt::MinimizeWithoutGradient(), VW::PMatrixCompute::NonLinearFromPoints(), vnl_discrete_diff_fwd(), vnl_discrete_diff_sym(), and vnl_discrete_diff_test_lsf().
void VNL::LeastSquaresFunction::GradF (VNL::Vector< double > const & x, VNL::Matrix< double > & jacobian) [virtual, inherited]
Calculate the Jacobian, given the parameter vector x.
Referenced by VNL::LeastSquaresCostFunction::GradF(), VNL::LevenbergMarquardt::lmder_lsqfun(), and vnl_discrete_diff_test_lsf().
bool VNL::LeastSquaresFunction::HasGradient () const [inline, inherited]
Return true if the derived class has indicated that gradf has been implemented.
References VNL::LeastSquaresFunction::use_gradient_.
Referenced by VNL::LeastSquaresCostFunction::GradF(), VNL::LevenbergMarquardt::Minimize(), VNL::LevenbergMarquardt::MinimizeUsingGradient(), and VNL::LevenbergMarquardt::MinimizeWithoutGradient().
double VNL::LeastSquaresFunction::RMS (VNL::Vector< double > const & x) [inherited]
Compute the rms error at x by calling f and returning the norm of the residual vector.
References VNL::LeastSquaresFunction::F(), VNL::LeastSquaresFunction::n_, and VNL::Vector< T >::RMS().
void VNL::LeastSquaresFunction::ThrowFailure () [inherited]
References VNL::LeastSquaresFunction::failure.
void VNL::LeastSquaresFunction::Trace (int iteration, VNL::Vector< double > const & x, VNL::Vector< double > const & fx) [virtual, inherited]
Called after each LM iteration to print debugging etc.
Referenced by VNL::LevenbergMarquardt::lmder_lsqfun(), and VNL::LevenbergMarquardt::lmdif_lsqfun().
Member Data Documentation
const bool VW::PMatrixCompute::LSFuncPoints::_estimate_kappa [protected]
Referenced by F().
const bool VW::PMatrixCompute::LSFuncPoints::_unity_aspect [protected]
const std::vector<unsigned int>& VW::PMatrixCompute::LSFuncPoints::_whichfeatures [protected]
Referenced by F().
const std::vector<VW::Point3D>& VW::PMatrixCompute::LSFuncPoints::_X [protected]
Referenced by F().
const std::vector<VW::Point2D>& VW::PMatrixCompute::LSFuncPoints::_x [protected]
Referenced by F().
const bool VW::PMatrixCompute::LSFuncPoints::_zero_skew [protected]
Referenced by F().
bool VNL::LeastSquaresFunction::failure [inherited]
Referenced by VNL::LeastSquaresFunction::ClearFailure(), VNL::LevenbergMarquardt::lmder_lsqfun(), VNL::LevenbergMarquardt::lmdif_lsqfun(), VNL::LeastSquaresFunction::ThrowFailure(), vnl_discrete_diff_fwd(), and vnl_discrete_diff_sym().
int VNL::LeastSquaresFunction::n_ [protected, inherited]
Referenced by VNL::LeastSquaresFunction::_init(), VNL::LeastSquaresFunction::GetNumberOfResiduals(), VNL::LeastSquaresFunction::LeastSquaresFunction(), and VNL::LeastSquaresFunction::RMS().
int VNL::LeastSquaresFunction::p_ [protected, inherited]
Referenced by VNL::LeastSquaresFunction::_init(), VNL::LeastSquaresFunction::GetNumberOfUnknowns(), and VNL::LeastSquaresFunction::LeastSquaresFunction().
std::string VNL::LeastSquaresFunction::print_f_fmt_ [protected, inherited]
std::string VNL::LeastSquaresFunction::print_x_fmt_ [protected, inherited]
bool VNL::LeastSquaresFunction::use_gradient_ [protected, inherited]
Referenced by VNL::LeastSquaresFunction::HasGradient(), and VNL::LeastSquaresFunction::LeastSquaresFunction().
The documentation for this class was generated from the following file:
pmatrixcomputenonlinear.cpp