VW: VW::Yorick Class Reference
VW::Yorick Class Reference
#include <yorickmain.h>
Public Types
enum YorickAxis { YORICK_PAN = YorickPMAC::PMAC_PAN, YORICK_TILT = YorickPMAC::PMAC_TILT, YORICK_VERGELEFT = YorickPMAC::PMAC_VERGELEFT, YORICK_VERGERIGHT = YorickPMAC::PMAC_VERGERIGHT }
Public Member Functions
Yorick (void)
virtual ~Yorick ()
bool SetActive (bool state)
void SetVergeLeftActive (bool state)
void SetVergeRightActive (bool state)
void SetTiltActive (bool state)
void SetPanActive (bool state)
bool GetActive (void)
bool GetVergeLeftActive (void)
bool GetVergeRightActive (void)
bool GetTiltActive (void)
bool GetPanActive (void)
virtual int Demand (float p, float t, float vl, float vr)
virtual int DemandPan (float p)
virtual int DemandTilt (float t)
virtual int DemandPanTilt (float p, float t)
virtual int DemandVergeLeft (float vl)
virtual int DemandVergeRight (float vr)
virtual int DemandVerge (float vl, float vr)
int SlowRecentre (void)
int SlowDemand (float p, float t, float vl, float vr)
int WaitForCompletion (int=MAX_COUNTS, float=ODOMETRY_ACCEPT)
int Homez (void)
int HomezOneAxis (YorickAxis axis)
int GetPosition (float *p, float *t, float *vl, float *vr)
int GetPositionAndStore (float *p, float *t, float *vl, float *vr)
int GetVelocity (float *vp, float *vt, float *vvl, float *vvr)
float GetInstantVergeLeft (void)
float GetInstantVergeRight (void)
float GetInstantTilt (void)
float GetInstantPan (void)
float GetVergeLeft (void)
float GetVergeRight (void)
float GetTilt (void)
float GetPan (void)
void GetVergeLeftLimits (float *minv, float *maxv)
void GetVergeRightLimits (float *minv, float *maxv)
void GetTiltLimits (float *mint, float *maxt)
void GetPanLimits (float *minp, float *maxp)
int GetHistoricPosition (struct timeval time, float &p, float &t, float &vl, float &vr)
int GetHistoricPositionAndUncertainty (struct timeval time, float &p, float &t, float &vl, float &vr, float &delta_p, float &delta_t, float &delta_vl, float &delta_vr)
void ShowOdometryHistory (void)
void GetOdometryHistory (std::vector< timeval > &time, std::vector< double > &pan_history, std::vector< double > &tilt_history, std::vector< double > &vergeleft_history, std::vector< double > &vergeright_history)
void FlushHistory (void)
int IsPMACOpen ()
int ReadState (void)
Static Public Attributes
static const float PAN_LIMIT = 90.0
static const float TILT_LIMIT = 60.0
static const float VLEFT_LIMIT = 45.0
static const float VRIGHT_LIMIT = 45.0
Protected Attributes
int seq_no
float pan
float tilt
float vleft
float vright
YorickPMAC pmac
Member Enumeration Documentation
enum VW::Yorick::YorickAxis
Enumerator:
YORICK_PAN
YORICK_TILT
YORICK_VERGELEFT
YORICK_VERGERIGHT
Constructor & Destructor Documentation
VW::Yorick::Yorick (void)
References pan, seq_no, tilt, vleft, vright, and YORICK_ODOMETRY_HISTORY_LENGTH.
VW::Yorick::~Yorick (void) [virtual]
References YorickPMAC::Close(), and pmac.
Member Function Documentation
int VW::Yorick::Demand (float p, float t, float vl, float vr) [virtual]
Reimplemented in VW::YorickGTK.
References YorickPMAC::Demand(), YorickPMAC::GetMode(), pan, PAN_LIMIT, pmac, YorickPMAC::PMAC_ALL, YorickPMAC::PMAC_DEMAND, YorickPMAC::PMAC_ON, seq_no, tilt, TILT_LIMIT, vleft, VLEFT_LIMIT, vright, and VRIGHT_LIMIT.
Referenced by SlowDemand().
int VW::Yorick::DemandPan (float p) [virtual]
Reimplemented in VW::YorickGTK.
References YorickPMAC::Demand(), YorickPMAC::GetMode(), pan, PAN_LIMIT, pmac, YorickPMAC::PMAC_ALL, YorickPMAC::PMAC_DEMAND, YorickPMAC::PMAC_ON, seq_no, tilt, vleft, and vright.
int VW::Yorick::DemandPanTilt (float p, float t) [virtual]
Reimplemented in VW::YorickGTK.
References YorickPMAC::Demand(), YorickPMAC::GetMode(), pan, PAN_LIMIT, pmac, YorickPMAC::PMAC_ALL, YorickPMAC::PMAC_DEMAND, YorickPMAC::PMAC_ON, seq_no, tilt, TILT_LIMIT, vleft, and vright.
int VW::Yorick::DemandTilt (float t) [virtual]
Reimplemented in VW::YorickGTK.
References YorickPMAC::Demand(), YorickPMAC::GetMode(), pan, pmac, YorickPMAC::PMAC_ALL, YorickPMAC::PMAC_DEMAND, YorickPMAC::PMAC_ON, seq_no, tilt, TILT_LIMIT, vleft, and vright.
int VW::Yorick::DemandVerge (float vl, float vr) [virtual]
Reimplemented in VW::YorickGTK.
References YorickPMAC::Demand(), YorickPMAC::GetMode(), pan, pmac, YorickPMAC::PMAC_ALL, YorickPMAC::PMAC_DEMAND, YorickPMAC::PMAC_ON, seq_no, tilt, vleft, VLEFT_LIMIT, vright, and VRIGHT_LIMIT.
int VW::Yorick::DemandVergeLeft (float vl) [virtual]
Reimplemented in VW::YorickGTK.
References YorickPMAC::Demand(), YorickPMAC::GetMode(), pan, pmac, YorickPMAC::PMAC_ALL, YorickPMAC::PMAC_DEMAND, YorickPMAC::PMAC_ON, seq_no, tilt, vleft, VLEFT_LIMIT, and vright.
int VW::Yorick::DemandVergeRight (float vr) [virtual]
Reimplemented in VW::YorickGTK.
References YorickPMAC::Demand(), YorickPMAC::GetMode(), pan, pmac, YorickPMAC::PMAC_ALL, YorickPMAC::PMAC_DEMAND, YorickPMAC::PMAC_ON, seq_no, tilt, vleft, vright, and VRIGHT_LIMIT.
void VW::Yorick::FlushHistory (void)
References YorickPMAC::GetMode(), YorickPMAC::GetOdometry(), pmac, YorickPMAC::PMAC_ON, and seq_no.
Referenced by SetActive().
bool VW::Yorick::GetActive (void) [inline]
Referenced by VW::YorickGTK::i_Activate().
int VW::Yorick::GetHistoricPosition (struct timeval time, float & p, float & t, float & vl, float & vr)
References GetHistoricPositionAndUncertainty().
int VW::Yorick::GetHistoricPositionAndUncertainty (struct timeval time, float & p, float & t, float & vl, float & vr, float & delta_p, float & delta_t, float & delta_vl, float & delta_vr)
References YorickPMAC::GetMode(), YorickPMAC::GetOdometry(), pmac, YorickPMAC::PMAC_ON, seq_no, and YORICK_ODOMETRY_HISTORY_LENGTH.
Referenced by GetHistoricPosition().
float VW::Yorick::GetInstantPan (void)
References GetPosition().
float VW::Yorick::GetInstantTilt (void)
References GetPosition().
float VW::Yorick::GetInstantVergeLeft (void)
References GetPosition().
float VW::Yorick::GetInstantVergeRight (void)
References GetPosition().
void VW::Yorick::GetOdometryHistory (std::vector< timeval > & time, std::vector< double > & pan_history, std::vector< double > & tilt_history, std::vector< double > & vergeleft_history, std::vector< double > & vergeright_history)
float VW::Yorick::GetPan (void) [inline]
References pan.
Referenced by VW::YorickDragPad::Redraw(), and VW::YorickGTK::UpdateForm().
bool VW::Yorick::GetPanActive (void) [inline]
void VW::Yorick::GetPanLimits (float * minp, float * maxp) [inline]
References PAN_LIMIT.
Referenced by VW::YorickDragPad::Redraw().
int VW::Yorick::GetPosition (float * p, float * t, float * vl, float * vr)
References YorickPMAC::GetMode(), YorickPMAC::GetOdometry(), pmac, YorickPMAC::PMAC_ON, and seq_no.
Referenced by GetInstantPan(), GetInstantTilt(), GetInstantVergeLeft(), GetInstantVergeRight(), and WaitForCompletion().
int VW::Yorick::GetPositionAndStore (float * p, float * t, float * vl, float * vr)
References YorickPMAC::GetMode(), YorickPMAC::GetOdometry(), pmac, YorickPMAC::PMAC_ON, and seq_no.
float VW::Yorick::GetTilt (void) [inline]
References tilt.
Referenced by VW::YorickDragPad::Redraw(), and VW::YorickGTK::UpdateForm().
bool VW::Yorick::GetTiltActive (void) [inline]
void VW::Yorick::GetTiltLimits (float * mint, float * maxt) [inline]
References TILT_LIMIT.
Referenced by VW::YorickDragPad::Redraw().
int VW::Yorick::GetVelocity (float * vp, float * vt, float * vvl, float * vvr)
References YorickPMAC::GetMode(), YorickPMAC::GetVelocity(), pmac, YorickPMAC::PMAC_ON, and seq_no.
Referenced by WaitForCompletion().
float VW::Yorick::GetVergeLeft (void) [inline]
References vleft.
Referenced by VW::YorickDragPad::Redraw(), and VW::YorickGTK::UpdateForm().
bool VW::Yorick::GetVergeLeftActive (void) [inline]
void VW::Yorick::GetVergeLeftLimits (float * minv, float * maxv) [inline]
References VLEFT_LIMIT.
Referenced by VW::YorickDragPad::Redraw().
float VW::Yorick::GetVergeRight (void) [inline]
References vright.
Referenced by VW::YorickDragPad::Redraw(), and VW::YorickGTK::UpdateForm().
bool VW::Yorick::GetVergeRightActive (void) [inline]
void VW::Yorick::GetVergeRightLimits (float * minv, float * maxv) [inline]
References VRIGHT_LIMIT.
Referenced by VW::YorickDragPad::Redraw().
int VW::Yorick::Homez (void)
References YorickPMAC::Demand(), YorickPMAC::GetMode(), pan, pmac, YorickPMAC::PMAC_ALL, YorickPMAC::PMAC_HOMEZ, YorickPMAC::PMAC_ON, seq_no, tilt, vleft, and vright.
Referenced by VW::YorickGTK::i_SetOrigin().
int VW::Yorick::HomezOneAxis (YorickAxis axis)
References YorickPMAC::Demand(), YorickPMAC::GetMode(), pan, pmac, YorickPMAC::PMAC_HOMEZ, YorickPMAC::PMAC_ON, seq_no, tilt, vleft, vright, YORICK_PAN, YORICK_TILT, YORICK_VERGELEFT, and YORICK_VERGERIGHT.
int VW::Yorick::IsPMACOpen ()
References YorickPMAC::GetMode(), pmac, and YorickPMAC::PMAC_ON.
int VW::Yorick::ReadState (void)
References YorickPMAC::GetState(), and pmac.
bool VW::Yorick::SetActive (bool state)
References YorickPMAC::Close(), FlushHistory(), YorickPMAC::GetMode(), YorickPMAC::Init(), pmac, YorickPMAC::PMAC_ON, and YorickPMAC::SetModePending().
Referenced by VW::YorickGTK::i_Activate().
void VW::Yorick::SetPanActive (bool state) [inline]
void VW::Yorick::SetTiltActive (bool state) [inline]
void VW::Yorick::SetVergeLeftActive (bool state) [inline]
void VW::Yorick::SetVergeRightActive (bool state) [inline]
void VW::Yorick::ShowOdometryHistory (void)
References YORICK_ODOMETRY_HISTORY_LENGTH.
int VW::Yorick::SlowDemand (float p, float t, float vl, float vr)
References Demand(), YorickPMAC::GetMode(), YorickPMAC::GetOdometry(), max, pan, pmac, YorickPMAC::PMAC_ON, seq_no, tilt, vleft, and vright.
Referenced by SlowRecentre().
int VW::Yorick::SlowRecentre (void)
References SlowDemand().
Referenced by VW::YorickGTK::i_Recentre().
int VW::Yorick::WaitForCompletion (int max_counts = MAX_COUNTS, float odometry_accept = ODOMETRY_ACCEPT)
References GetPosition(), GetVelocity(), pan, tilt, vleft, and vright.
Member Data Documentation
float VW::Yorick::pan [protected]
Referenced by Demand(), DemandPan(), DemandPanTilt(), DemandTilt(), DemandVerge(), DemandVergeLeft(), DemandVergeRight(), GetPan(), Homez(), HomezOneAxis(), SlowDemand(), WaitForCompletion(), and Yorick().
const float VW::Yorick::PAN_LIMIT = 90.0 [static]
Referenced by Demand(), DemandPan(), DemandPanTilt(), GetPanLimits(), and VW::YorickGTKWidget::InitForm().
YorickPMAC VW::Yorick::pmac [protected]
Referenced by Demand(), DemandPan(), DemandPanTilt(), DemandTilt(), DemandVerge(), DemandVergeLeft(), DemandVergeRight(), FlushHistory(), GetHistoricPositionAndUncertainty(), GetPosition(), GetPositionAndStore(), GetVelocity(), Homez(), HomezOneAxis(), IsPMACOpen(), ReadState(), SetActive(), SlowDemand(), and ~Yorick().
int VW::Yorick::seq_no [protected]
Referenced by Demand(), DemandPan(), DemandPanTilt(), DemandTilt(), DemandVerge(), DemandVergeLeft(), DemandVergeRight(), FlushHistory(), GetHistoricPositionAndUncertainty(), GetPosition(), GetPositionAndStore(), GetVelocity(), Homez(), HomezOneAxis(), SlowDemand(), and Yorick().
float VW::Yorick::tilt [protected]
Referenced by Demand(), DemandPan(), DemandPanTilt(), DemandTilt(), DemandVerge(), DemandVergeLeft(), DemandVergeRight(), GetTilt(), Homez(), HomezOneAxis(), SlowDemand(), WaitForCompletion(), and Yorick().
const float VW::Yorick::TILT_LIMIT = 60.0 [static]
Referenced by Demand(), DemandPanTilt(), DemandTilt(), GetTiltLimits(), and VW::YorickGTKWidget::InitForm().
float VW::Yorick::vleft [protected]
Referenced by Demand(), DemandPan(), DemandPanTilt(), DemandTilt(), DemandVerge(), DemandVergeLeft(), DemandVergeRight(), GetVergeLeft(), Homez(), HomezOneAxis(), SlowDemand(), WaitForCompletion(), and Yorick().
const float VW::Yorick::VLEFT_LIMIT = 45.0 [static]
Referenced by Demand(), DemandVerge(), DemandVergeLeft(), GetVergeLeftLimits(), and VW::YorickGTKWidget::InitForm().
float VW::Yorick::vright [protected]
Referenced by Demand(), DemandPan(), DemandPanTilt(), DemandTilt(), DemandVerge(), DemandVergeLeft(), DemandVergeRight(), GetVergeRight(), Homez(), HomezOneAxis(), SlowDemand(), WaitForCompletion(), and Yorick().
const float VW::Yorick::VRIGHT_LIMIT = 45.0 [static]
Referenced by Demand(), DemandVerge(), DemandVergeRight(), GetVergeRightLimits(), and VW::YorickGTKWidget::InitForm().
The documentation for this class was generated from the following files:
yorickmain.h
yorickmain.cpp