VW: VW::EssentialMatrixComputeLinear Class Reference
VW::EssentialMatrixComputeLinear Class Reference
[GeometricAlgorithms]
EssentialMatrixComputeLinear.
#include <essentialmatrixcomputelinear.h>
Public Member Functions
EssentialMatrixComputeLinear (const bool normalise=true)
Create a linear computation object.
bool Compute (VW::EssentialMatrix &result, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1)
Compute an fmatrix from two lists of 2D point features.
bool Compute (VW::EssentialMatrix &result, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const std::vector< unsigned int > &which_features)
Compute an essential matrix from two lists of 2D point features.
bool ComputeWeighted (VW::EssentialMatrix &result, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const std::vector< double > &weights)
Compute an essential matrix from two lists of 2D point features, weighting the contribution of the features.
Detailed Description
EssentialMatrixComputeLinear.
Author:
BJ Tordoff
Date:
19/04/2005 general linear algorithm for EssentialMatrices.
Constructor & Destructor Documentation
VW::EssentialMatrixComputeLinear::EssentialMatrixComputeLinear (const bool normalise = true) [inline]
Create a linear computation object.
Note that the calculation can involve a normalisation, so it is not necessary to pre-normalise the input points/lines (although it doesn't hurt).
Member Function Documentation
bool VW::EssentialMatrixComputeLinear::Compute (VW::EssentialMatrix & result, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const std::vector< unsigned int > & which_features)
Compute an essential matrix from two lists of 2D point features.
Note that x0, x1 are defined such that x_1' E x_0 = 0
Parameters:
which_features a list of the indices of feature-pairs to use
References VW::EssentialMatrixCompute::AddToDesignMatrix(), VW::Normalisation::Init(), VW::EssentialMatrixCompute::MakeSymmetric(), VW::Normalisation::Normalise(), and VW::EssentialMatrixCompute::RecoverE().
bool VW::EssentialMatrixComputeLinear::Compute (VW::EssentialMatrix & result, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1)
Compute an fmatrix from two lists of 2D point features.
Note that x0, x1 are defined such that x_1' E x_0 = 0
Parameters:
inlierlist a list of the indices of feature-pairs to use
References VW::EssentialMatrixCompute::AddToDesignMatrix(), VW::Normalisation::Init(), VW::EssentialMatrixCompute::MakeSymmetric(), VW::Normalisation::Normalise(), VW::EssentialMatrixCompute::RecoverE(), and VERBOSE.
bool VW::EssentialMatrixComputeLinear::ComputeWeighted (VW::EssentialMatrix & result, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const std::vector< double > & weights)
Compute an essential matrix from two lists of 2D point features, weighting the contribution of the features.
References VW::EssentialMatrixCompute::AddToDesignMatrix(), VW::Normalisation::Init(), VW::EssentialMatrixCompute::MakeSymmetric(), VW::Normalisation::Normalise(), VW::EssentialMatrixCompute::RecoverE(), and VERBOSE.
Referenced by VW::EssentialMatrixComputePreemptive::Compute().
The documentation for this class was generated from the following files:
essentialmatrixcomputelinear.h
essentialmatrixcomputelinear.cpp