VW: VW::FMatrixComputeMLESAC Class Reference
VW::FMatrixComputeMLESAC Class Reference
[GeometricAlgorithms]
outlier rejection for fundamental matrices.
#include <fmatrixcomputemlesac.h>
Public Member Functions
FMatrixComputeMLESAC (double image_noise, double search_area, double desired_confidence=99.0)
bool Compute (VW::FMatrix &H, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, std::vector< unsigned int > &inliers)
void SetDesiredConfidence (double desired_confidence)
Set the desired confidence (%).
void SetImageNoise (double image_noise)
Set the expected image noise standard deviation (in pixels).
void SetSearchArea (double search_area)
Set the are searched for each feature.
void SetMaxIterations (unsigned int max_iters)
Set an upper bound on the number of iterations.
Detailed Description
outlier rejection for fundamental matrices.
Author:
JGH Knight
Date:
02/11/02 As for Homography2Ds, this is a class derived from a version of ComputeMLESAC instantiated for FMatrix transforms. Also, the BaseFeature type is forced to be VW::Point2D, since fundamental matrices cannot be calculated from lines.
Derivation is used rather than just specialisation of the template so that additional features can be provided over and above that provided by ComputeMLESAC.
Constructor & Destructor Documentation
VW::FMatrixComputeMLESAC::FMatrixComputeMLESAC (double image_noise, double search_area, double desired_confidence = 99.0) [inline]
Member Function Documentation
bool VW::FMatrixComputeMLESAC::Compute (VW::FMatrix & H, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, std::vector< unsigned int > & inliers)
References VW::Normalisation::AsMatrix(), VW::Normalisation::GetScale(), VW::FMatrixCompute::MLESACCore(), VW::Normalisation::Normalise(), VNL::Matrix< T >::Transpose(), and VERBOSE.
void VW::FMatrixComputeMLESAC::SetDesiredConfidence (double desired_confidence) [inline]
Set the desired confidence (%).
Once this level of confidence is reached sampling will terminate. Note that if max_iters is also set, both will be used.
void VW::FMatrixComputeMLESAC::SetImageNoise (double image_noise) [inline]
Set the expected image noise standard deviation (in pixels).
This is used to determine the Gaussian model for the inlier process.
void VW::FMatrixComputeMLESAC::SetMaxIterations (unsigned int max_iters) [inline]
Set an upper bound on the number of iterations.
If not set (or set to zero), sampling will continue until the desired confidence level is reached.
void VW::FMatrixComputeMLESAC::SetSearchArea (double search_area) [inline]
Set the are searched for each feature.
This determines the uniform distribution used to model the outlier process.
The documentation for this class was generated from the following files:
fmatrixcomputemlesac.h
fmatrixcomputemlesac.cpp