VW: VW::SequencerFileChannelGTKWidget Class Reference
VW::SequencerFileChannelGTKWidget Class Reference
#include <sequencerfilegtk.h>
Public Member Functions
void InitForm (SequencerFileGTK *main_form)
std::string GetFileName ()
void SetFileName (const std::string s)
void SetLED (bool valid)
Protected Member Functions
void LoadStart ()
void LoadOK ()
void LoadCancel ()
Protected Attributes
Gtk::FileSelection * file_selector
SequencerFileGTK * _main_form
Gtk::Entry * file_name
Gtk::Button * browse_button
Gtk::Pixmap * status_led
Member Function Documentation
std::string VW::SequencerFileChannelGTKWidget::GetFileName () [inline]
References file_name.
void VW::SequencerFileChannelGTKWidget::InitForm (SequencerFileGTK * main_form)
References _main_form, add(), browse_button, led_off_xpm, load_icon_xpm, LoadStart(), status_led, and VW::SequencerFileGTK::UpdateFromForm().
void VW::SequencerFileChannelGTKWidget::LoadCancel () [protected]
References _main_form, file_selector, and VW::SequencerFileGTK::UpdateFromForm().
Referenced by LoadStart().
void VW::SequencerFileChannelGTKWidget::LoadOK () [protected]
References _main_form, file_selector, VW::SequencerFileGTK::UpdateFromForm(), and VERBOSE.
Referenced by LoadStart().
void VW::SequencerFileChannelGTKWidget::LoadStart () [protected]
References file_selector, LoadCancel(), and LoadOK().
Referenced by InitForm().
void VW::SequencerFileChannelGTKWidget::SetFileName (const std::string s) [inline]
References file_name.
void VW::SequencerFileChannelGTKWidget::SetLED (bool valid)
References led_green_xpm, led_red_xpm, and status_led.
Member Data Documentation
SequencerFileGTK* VW::SequencerFileChannelGTKWidget::_main_form [protected]
Referenced by InitForm(), LoadCancel(), and LoadOK().
Gtk::Button* VW::SequencerFileChannelGTKWidget::browse_button [protected]
Referenced by InitForm().
Gtk::Entry* VW::SequencerFileChannelGTKWidget::file_name [protected]
Referenced by GetFileName(), and SetFileName().
Gtk::FileSelection* VW::SequencerFileChannelGTKWidget::file_selector [protected]
Referenced by LoadCancel(), LoadOK(), and LoadStart().
Gtk::Pixmap* VW::SequencerFileChannelGTKWidget::status_led [protected]
Referenced by InitForm(), and SetLED().
The documentation for this class was generated from the following files:
sequencerfilegtk.h
sequencerfilegtk.cpp