VW: VNL::Transpose Class Reference
VNL::Transpose Class Reference
Efficient matrix transpose.
#include <transpose.h>
Public Member Functions
Transpose (const Matrix< double > &M)
Make a vnl_transpose object referring to matrix M.
operator Matrix< double > () const
Noisily convert a vnl_transpose to a matrix.
Matrix< double > AsMatrix () const
Quietly convert a vnl_transpose to a matrix.
Matrix< double > operator* (const Matrix< double > &O)
Return M' * O.
Vector< double > operator* (const Vector< double > &O)
Return M' * O.
Friends
Matrix< double > operator* (const Matrix< double > &A, const Transpose &B)
Return A * B'.
Detailed Description
Efficient matrix transpose.
vnl_transpose is an efficient way to write C = vnl_transpose(A) * B. The vnl_transpose class holds a reference to the original matrix and when involved in an operation for which it has been specialized, performs the operation without copying.
If the operation has not been specialized, the vnl_transpose performs a copying conversion to a matrix, printing a message to stdout. At that stage, the user may choose to implement the particular operation or use vnl_transpose::asMatrix() to clear the warning.
NOTE: This is a reference class, so should be shorter-lived than the matrix to which it refers.
Constructor & Destructor Documentation
VNL::Transpose::Transpose (const Matrix< double > & M) [inline]
Make a vnl_transpose object referring to matrix M.
Member Function Documentation
Matrix<double> VNL::Transpose::AsMatrix () const [inline]
Quietly convert a vnl_transpose to a matrix.
References VNL::Matrix< T >::Transpose().
VNL::Transpose::operator Matrix< double > () const [inline]
Noisily convert a vnl_transpose to a matrix.
References VNL::Matrix< T >::Transpose().
Vector<double> VNL::Transpose::operator* (const Vector< double > & O) [inline]
Return M' * O.
References vnl_fastops::AtB(), and VNL::Matrix< T >::Columns().
Matrix<double> VNL::Transpose::operator* (const Matrix< double > & O) [inline]
Return M' * O.
References vnl_fastops::AtB(), and VNL::Matrix< T >::Columns().
Friends And Related Function Documentation
Matrix<double> operator* (const Matrix< double > & A, const Transpose & B) [friend]
Return A * B'.
The documentation for this class was generated from the following file:
transpose.h