VW: VNL::RealNPolynomial Class Reference
VNL::RealNPolynomial Class Reference
real polynomial in N variables.
#include <realnpolynomial.h>
Public Member Functions
RealNPolynomial ()
RealNPolynomial (const VNL::Vector< double > &c, const VNL::Matrix< int > &p)
Constructor.
double Eval (const VNL::Vector< double > &x)
int Degree ()
RealNPolynomial operator- () const
RealNPolynomial operator+ (RealNPolynomial const &) const
RealNPolynomial operator- (RealNPolynomial const &) const
RealNPolynomial operator* (RealNPolynomial const &) const
RealNPolynomial operator+ (double) const
RealNPolynomial operator- (double P) const
RealNPolynomial operator* (double) const
RealNPolynomial & operator*= (double P)
RealNPolynomial operator/ (double P) const
RealNPolynomial & operator/= (double P)
int Degree () const
Return the degree (highest power of x) of the polynomial.
double & operator[] (int i)
Access to the polynomial coefficients.
double operator[] (int i) const
Access to the polynomial coefficients.
const VNL::Vector< double > & Coefficients () const
Return the vector of coefficients.
VNL::Vector< double > & Coefficients ()
Return the vector of coefficients.
void Set (const VNL::Vector< double > &c, const VNL::Matrix< int > &p)
Set vector of coefficients of each product.
const VNL::Matrix< int > & PolyN () const
Return the polynomial matrix.
VNL::Matrix< int > & PolyN ()
Return the vector of coefficients.
Friends
class RNPolySolve
std::ostream & operator<< (std::ostream &, RealNPolynomial const &)
Detailed Description
real polynomial in N variables.
vnl_real_npolynomial represents a polynomial in multiple variables. Used by vnl_rnpoly_solve which solves systems of polynomial equations. Representation: an N-omial (N terms) is represented by (1) a vector with the N coefficients (vnl_vector<double>), and (2) a matrix with N rows, the i-th row representing the exponents of term i, as follows: (VNL::Matrix<int>) column k contains the (integer) exponent of variable k. Example: the polynomial is represented by the coefficients vector [A B C D] and the exponents matrix
      [3 0]
      [1 1]
      [0 2]
      [1 2].
Constructor & Destructor Documentation
VNL::RealNPolynomial::RealNPolynomial () [inline]
Referenced by operator*(), operator+(), and operator-().
VNL::RealNPolynomial::RealNPolynomial (const VNL::Vector< double > & c, const VNL::Matrix< int > & p)
Constructor.
 coeffs = VNL::Vector<double>(nterms)
 polyn = VNL::Matrix<int>(nterms,nvar)
 Example: A*x^3 + B*x*y + C*y^2 + D*x*y^2
 nvar = 2;
 nterms = 4;
 coeffs = [A B C D]';
 polyn = [3 0]
         [1 1]
         [0 2]
         [1 2];
*
References VNL::Matrix< T >::Rows(), and VNL::Vector< T >::size().
Member Function Documentation
VNL::Vector<double>& VNL::RealNPolynomial::Coefficients () [inline]
Return the vector of coefficients.
const VNL::Vector<double>& VNL::RealNPolynomial::Coefficients () const [inline]
Return the vector of coefficients.
int VNL::RealNPolynomial::Degree () const [inline]
Return the degree (highest power of x) of the polynomial.
References VNL::Vector< T >::size().
int VNL::RealNPolynomial::Degree ()
double VNL::RealNPolynomial::Eval (const VNL::Vector< double > & x)
RealNPolynomial VNL::RealNPolynomial::operator* (double P) const
References RealNPolynomial().
RealNPolynomial VNL::RealNPolynomial::operator* (RealNPolynomial const & P) const
References RealNPolynomial().
Referenced by operator/().
RealNPolynomial& VNL::RealNPolynomial::operator*= (double P) [inline]
Referenced by operator/=().
RealNPolynomial VNL::RealNPolynomial::operator+ (double P) const
References RealNPolynomial().
RealNPolynomial VNL::RealNPolynomial::operator+ (RealNPolynomial const & P) const
References RealNPolynomial().
Referenced by operator-().
RealNPolynomial VNL::RealNPolynomial::operator- (double P) const [inline]
References operator+().
RealNPolynomial VNL::RealNPolynomial::operator- (RealNPolynomial const & P) const
References RealNPolynomial().
RealNPolynomial VNL::RealNPolynomial::operator- () const
References RealNPolynomial().
RealNPolynomial VNL::RealNPolynomial::operator/ (double P) const [inline]
References operator*().
RealNPolynomial& VNL::RealNPolynomial::operator/= (double P) [inline]
References operator*=().
double VNL::RealNPolynomial::operator[] (int i) const [inline]
Access to the polynomial coefficients.
double& VNL::RealNPolynomial::operator[] (int i) [inline]
Access to the polynomial coefficients.
VNL::Matrix<int>& VNL::RealNPolynomial::PolyN () [inline]
Return the vector of coefficients.
const VNL::Matrix<int>& VNL::RealNPolynomial::PolyN () const [inline]
Return the polynomial matrix.
(ie specifying the variables in each product)
void VNL::RealNPolynomial::Set (const VNL::Vector< double > & c, const VNL::Matrix< int > & p)
Set vector of coefficients of each product.
Set the coefficients and degree of variable.
References VNL::Matrix< T >::Cols(), VNL::Matrix< T >::MaxValue(), and VNL::Matrix< T >::Rows().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & , RealNPolynomial const &) [friend]
friend class RNPolySolve [friend]
The documentation for this class was generated from the following files:
realnpolynomial.h
realnpolynomial.cpp