VW: VW::Histogram Class Reference
VW::Histogram Class Reference
[MathsStuff]
A simple class for storing and retrieving 1D histogram values.
#include <histogram.h>
Public Member Functions
Histogram ()
Create uninitialised.
Histogram (const std::vector< double > &tickmarks)
Create with an array giving the axis values (tickmarks are the bin boundaries, so there is one less bin than tickmarks).
Histogram (const double min_val, const double max_val, const unsigned int num_bins)
Create with bins equally spread.
~Histogram ()
void SetTickMarks (const std::vector< double > &tickmarks)
Set the bin boundary locations (tickmarks are the bin boundaries, so there is one less bin than tickmarks).
void AddData (double xval, double amount=1.0)
Add a piece of data to the histogram (amount is added to the appropriate bin).
void AddData (const std::vector< double > &xvals, double amount=1.0)
Add a set of data to the histogram (amount is added to the appropriate bins).
void Clear ()
Reset all bins to zero.
unsigned int Size () const
Number of bins.
double Domain () const
Domain spanned by tick-marks (axis).
double DomainMin () const
Minimum axis value.
double DomainMax () const
Maximum axis value.
double Range () const
Range spanned by bin contents.
double RangeMin () const
Minimum bin height.
double RangeMax () const
Maximum bin height.
double Tick (unsigned int which) const
double GetBinFrequency (unsigned int bin_index) const
Number of datapoints in this bin.
double GetBinHeight (unsigned int bin_index) const
Height is frequency/size.
double GetInterpValue (double axis_val) const
Estimate the histogram value by bilinear interpolation.
double GetClosestValue (double axis_val) const
Get the histogram value of the closest bin.
bool FindPeaks (std::vector< HistogramLocation > &peaks, unsigned int max_num=0) const
If any peaks are found they are stored in peaks, strongest first, otherwise return value is false.
bool FindTroughs (std::vector< HistogramLocation > &troughs) const
If any troughs are found they are stored in peaks, otherwise return value is false.
operator bool () const
double operator[] (int i)
Get a raw data element (same as H.GetData(i)).
const double operator[] (int i) const
Get a raw data element (same as H.GetData(i)).
Friends
std::ostream & operator<< (std::ostream &, const VW::Histogram &)
Detailed Description
A simple class for storing and retrieving 1D histogram values.
Author:
BJ Tordoff
Date:
04/06/2004
Constructor & Destructor Documentation
VW::Histogram::Histogram ()
Create uninitialised.
VW::Histogram::Histogram (const std::vector< double > & tickmarks)
Create with an array giving the axis values (tickmarks are the bin boundaries, so there is one less bin than tickmarks).
VW::Histogram::Histogram (const double min_val, const double max_val, const unsigned int num_bins)
Create with bins equally spread.
VW::Histogram::~Histogram ()
Member Function Documentation
void VW::Histogram::AddData (const std::vector< double > & xvals, double amount = 1.0)
Add a set of data to the histogram (amount is added to the appropriate bins).
References AddData().
void VW::Histogram::AddData (double xval, double amount = 1.0)
Add a piece of data to the histogram (amount is added to the appropriate bin).
Referenced by AddData().
void VW::Histogram::Clear () [inline]
Reset all bins to zero.
double VW::Histogram::Domain () const [inline]
Domain spanned by tick-marks (axis).
double VW::Histogram::DomainMax () const [inline]
Maximum axis value.
double VW::Histogram::DomainMin () const [inline]
Minimum axis value.
bool VW::Histogram::FindPeaks (std::vector< HistogramLocation > & peaks, unsigned int max_num = 0) const
If any peaks are found they are stored in peaks, strongest first, otherwise return value is false.
If max_num is non zero then only the strongest max_num peaks are returned.
References VW::HistogramLocation::x.
bool VW::Histogram::FindTroughs (std::vector< HistogramLocation > & troughs) const
If any troughs are found they are stored in peaks, otherwise return value is false.
double VW::Histogram::GetBinFrequency (unsigned int bin_index) const [inline]
Number of datapoints in this bin.
double VW::Histogram::GetBinHeight (unsigned int bin_index) const [inline]
Height is frequency/size.
double VW::Histogram::GetClosestValue (double axis_val) const
Get the histogram value of the closest bin.
double VW::Histogram::GetInterpValue (double axis_val) const
Estimate the histogram value by bilinear interpolation.
VW::Histogram::operator bool () const [inline]
const double VW::Histogram::operator[] (int i) const [inline]
Get a raw data element (same as H.GetData(i)).
double VW::Histogram::operator[] (int i) [inline]
Get a raw data element (same as H.GetData(i)).
double VW::Histogram::Range () const [inline]
Range spanned by bin contents.
double VW::Histogram::RangeMax () const [inline]
Maximum bin height.
double VW::Histogram::RangeMin () const [inline]
Minimum bin height.
void VW::Histogram::SetTickMarks (const std::vector< double > & tickmarks)
Set the bin boundary locations (tickmarks are the bin boundaries, so there is one less bin than tickmarks).
All data will be lost.
unsigned int VW::Histogram::Size () const [inline]
Number of bins.
Referenced by VW::operator<<().
double VW::Histogram::Tick (unsigned int which) const [inline]
Referenced by VW::operator<<().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & , const VW::Histogram &) [friend]
The documentation for this class was generated from the following files:
histogram.h
histogram.cpp