VW: VNL::CostFunction Class Reference
VNL::CostFunction Class Reference
An object that represents a function from R^n -> R.
#include <costfunction.h>
Public Types
typedef NumericLimits< double > limits
Public Member Functions
CostFunction (int number_of_unknowns)
virtual ~CostFunction ()
virtual double F (Vector< double > const &x)
The main function. Given the parameter vector x, compute the value of f(x).
virtual void GradF (Vector< double > const &x, Vector< double > &gradient)
Calculate the gradient of f at parameter vector x.
virtual void Compute (Vector< double > const &x, double *f, Vector< double > *g)
Compute one or both of f and g.
int GetNumberOfUnknowns () const
Return the number of unknowns.
void FDGradF (Vector< double > const &x, Vector< double > &gradient, double stepsize=1e-5)
Compute finite-difference gradient.
virtual double ReportedError (double f_value)
Called when error is printed for user.
Vector< double > GradF (Vector< double > const &x)
Conveniences for printing grad, fdgrad.
Vector< double > FDGradF (Vector< double > const &x)
virtual double GetRangeMin () const
Return bounding cube of range (outputs).
virtual double GetRangeMax () const
virtual UnaryFunction< double,
Vector< double > > * Copy () const
Copy should allocate a copy of this on the heap and return it.
Public Attributes
int dim
Detailed Description
An object that represents a function from R^n -> R.
It is commonly used to express the interface of a minimizer.
Member Typedef Documentation
typedef NumericLimits<double > VNL::UnaryFunction< double , Vector< double > >::limits [inherited]
Constructor & Destructor Documentation
VNL::CostFunction::CostFunction (int number_of_unknowns) [inline]
virtual VNL::CostFunction::~CostFunction () [inline, virtual]
Member Function Documentation
void VNL::CostFunction::Compute (VNL::Vector< double > const & x, double * f, VNL::Vector< double > * g) [virtual]
Compute one or both of f and g.
Normally implemented in terms of the above two, but may be faster if specialized. f != 0 => compute f
References F(), and GradF().
Referenced by F(), GradF(), VNL::LBFGS::Minimize(), and VNL::ConjugateGradient::ValueAndGradientComputer_().
virtual UnaryFunction<double ,Vector< double > >* VNL::UnaryFunction< double , Vector< double > >::Copy () const [inline, virtual, inherited]
Copy should allocate a copy of this on the heap and return it.
If Subclasses do not implement this function, it will return null, but many applications will never call it, so this may not be a problem for you.
double VNL::CostFunction::F (VNL::Vector< double > const & x) [virtual]
The main function. Given the parameter vector x, compute the value of f(x).
Default implementation of f is compute.
..
Implements VNL::UnaryFunction< double, Vector< double > >.
Reimplemented in VNL::AmoebaLSCF, VNL::Powell1DFun, and VNL::LeastSquaresCostFunction.
References Compute().
Referenced by Compute(), VNL::Powell1DFun::F(), VNL::BrentData::F(), FDGradF(), VNL::Powell::Minimize(), and VNL::ConjugateGradient::ValueComputer_().
VNL::Vector< double > VNL::CostFunction::FDGradF (VNL::Vector< double > const & x)
References dim, and FDGradF().
void VNL::CostFunction::FDGradF (VNL::Vector< double > const & x, VNL::Vector< double > & gradient, double stepsize = 1e-5)
Compute finite-difference gradient.
Compute fd gradient.
References dim, and F().
Referenced by FDGradF(), and VNL::LBFGS::Minimize().
int VNL::CostFunction::GetNumberOfUnknowns () const [inline]
Return the number of unknowns.
References dim.
Referenced by VNL::Amoeba::Amoeba(), VNL::ConjugateGradient::GradientComputer_(), VNL::LBFGS::Minimize(), VNL::ConjugateGradient::Minimize(), VNL::ConjugateGradient::Preconditioner_(), VNL::ConjugateGradient::ValueAndGradientComputer_(), and VNL::ConjugateGradient::ValueComputer_().
virtual double VNL::UnaryFunction< double , Vector< double > >::GetRangeMax () const [inline, virtual, inherited]
virtual double VNL::UnaryFunction< double , Vector< double > >::GetRangeMin () const [inline, virtual, inherited]
Return bounding cube of range (outputs).
VNL::Vector< double > VNL::CostFunction::GradF (VNL::Vector< double > const & x)
Conveniences for printing grad, fdgrad.
References dim, and GradF().
void VNL::CostFunction::GradF (VNL::Vector< double > const & x, VNL::Vector< double > & g) [virtual]
Calculate the gradient of f at parameter vector x.
Default implementation of gradf is to call compute.
Reimplemented in VNL::LeastSquaresCostFunction.
References Compute().
Referenced by Compute(), GradF(), and VNL::ConjugateGradient::GradientComputer_().
virtual double VNL::CostFunction::ReportedError (double f_value) [inline, virtual]
Called when error is printed for user.
Referenced by VNL::ConjugateGradient::DiagnoseOutcome(), and VNL::LBFGS::Minimize().
Member Data Documentation
int VNL::CostFunction::dim
Referenced by FDGradF(), GetNumberOfUnknowns(), and GradF().
The documentation for this class was generated from the following files:
costfunction.h
costfunction.cpp