VW: VW::ShiTomasiDetector Class Reference
VW::ShiTomasiDetector Class Reference
[ImageProcessing]
Interest point detection using the method of Shi & Tomasi.
#include <shitomasidetector.h>
Public Member Functions
ShiTomasiDetector (const float strength_threshold=0.1, const unsigned int patchsize=5, const unsigned int max_number=0)
Construct blank for subsequent use of Compute(.
ShiTomasiDetector (const VW::ImageMono< unsigned char > &image, std::vector< CornerFeature > &features, const float strength_threshold=0.1, const unsigned int patchsize=5, const unsigned int max_number=0)
Construct and find features.
ShiTomasiDetector (const VW::Pyramid< float > &pyramid, std::vector< CornerFeature > &features, const float strength_threshold=0.1, const unsigned int patchsize=5, const unsigned int max_number=0)
ShiTomasiDetector (const VW::ImageMono< unsigned char > &image, CornerFeature &best_feature, const float strength_threshold=0.1, const unsigned int patchsize=5)
Construct and find the singe strongest feature.
ShiTomasiDetector (const VW::Pyramid< float > &pyramid, CornerFeature &best_feature, const float strength_threshold=0.1, const unsigned int patchsize=5)
Construct and find the singe strongest feature.
void SetMinStrengthThreshold (float new_threshold)
void SetPatchSize (unsigned int new_size)
void SetMaxNumFeatures (unsigned int new_maximum)
void Compute (const VW::Pyramid< float > &pyramid, std::vector< CornerFeature > &features)
Compute features at each level of a pyramid.
template<class T >
void Compute (const VW::ImageMono< T > &image, std::vector< CornerFeature > &features)
Compute features in a single image.
void Compute (const VW::Pyramid< float > &pyramid, CornerFeature &best_feature)
Compute the single strongest feature in a pyramid.
template<class T >
void Compute (const VW::ImageMono< T > &image, CornerFeature &best_feature)
Compute the single strongest feature in an image.
Detailed Description
Interest point detection using the method of Shi & Tomasi.
Author:
BJ Tordoff & AJ Davison
Date:
29/11/2004 This detector can be used to either find the single strongest feature in the region of interest (image.ROI()), or the set of all maxima.
Constructor & Destructor Documentation
VW::ShiTomasiDetector::ShiTomasiDetector (const float strength_threshold = 0.1, const unsigned int patchsize = 5, const unsigned int max_number = 0) [inline]
Construct blank for subsequent use of Compute(.
..)
Parameters:
strength_threshold is the minimum corner strength (in range 0 to 1)
patchsize is the size of the correlation patch (should be odd)
max_number is the maximum number of features that will be stored (0 indicates no limit)
VW::ShiTomasiDetector::ShiTomasiDetector (const VW::ImageMono< unsigned char > & image, std::vector< CornerFeature > & features, const float strength_threshold = 0.1, const unsigned int patchsize = 5, const unsigned int max_number = 0) [inline]
Construct and find features.
References Compute().
VW::ShiTomasiDetector::ShiTomasiDetector (const VW::Pyramid< float > & pyramid, std::vector< CornerFeature > & features, const float strength_threshold = 0.1, const unsigned int patchsize = 5, const unsigned int max_number = 0) [inline]
References Compute().
VW::ShiTomasiDetector::ShiTomasiDetector (const VW::ImageMono< unsigned char > & image, CornerFeature & best_feature, const float strength_threshold = 0.1, const unsigned int patchsize = 5) [inline]
Construct and find the singe strongest feature.
References Compute().
VW::ShiTomasiDetector::ShiTomasiDetector (const VW::Pyramid< float > & pyramid, CornerFeature & best_feature, const float strength_threshold = 0.1, const unsigned int patchsize = 5) [inline]
Construct and find the singe strongest feature.
References Compute().
Member Function Documentation
template<class T > void VW::ShiTomasiDetector::Compute (const VW::ImageMono< T > & image, CornerFeature & best_feature) [inline]
Compute the single strongest feature in an image.
References VW::ROI::Bottom(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), VW::ROI::Left(), VW::ROI::Right(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::ROI(), VW::CornerFeature::Set(), VW::ROI::Top(), VERBOSE, VW::ROI::Width(), and VW::PixelMono< Type >::y.
void VW::ShiTomasiDetector::Compute (const VW::Pyramid< float > & pyramid, CornerFeature & best_feature)
Compute the single strongest feature in a pyramid.
References Compute(), VW::CornerFeature::GetCornerStrength(), VW::Pyramid< StorageType >::GetScale(), VW::Point2D::GetX(), VW::Point2D::GetY(), VW::Pyramid< StorageType >::NumLevels(), and VW::CornerFeature::Set().
template<class T > void VW::ShiTomasiDetector::Compute (const VW::ImageMono< T > & image, std::vector< CornerFeature > & features) [inline]
Compute features in a single image.
void VW::ShiTomasiDetector::Compute (const VW::Pyramid< float > & pyramid, std::vector< CornerFeature > & features)
Compute features at each level of a pyramid.
References VW::Pyramid< StorageType >::GetScale(), and VW::Pyramid< StorageType >::NumLevels().
Referenced by Compute(), and ShiTomasiDetector().
void VW::ShiTomasiDetector::SetMaxNumFeatures (unsigned int new_maximum) [inline]
void VW::ShiTomasiDetector::SetMinStrengthThreshold (float new_threshold) [inline]
void VW::ShiTomasiDetector::SetPatchSize (unsigned int new_size) [inline]
The documentation for this class was generated from the following files:
shitomasidetector.h
shitomasidetector.cpp