VW: VW::Timer Class Reference
VW::Timer Class Reference
Simple timer class for measuring elapsed time, with precision down to microseconds.
#include <timer.h>
Public Member Functions
Timer ()
void Start ()
Start, or restart (if already going) the timer.
void Stop ()
Stop the timer, storing the time elapsed.
double GetAsSeconds () const
Return the time elapsed with units of seconds (precision is still microsecs).
double GetAsMilliseconds () const
Return the time elapsed with units of milli-seconds (precision is still microsecs).
double GetAsMicroseconds () const
Return the time elapsed with units of micro-seconds (precision is microsecs).
double GetAsNanoseconds () const
Return the time elapsed with units of micro-seconds (precision is still microsecs).
Protected Attributes
bool _is_running
long int _start_secs
long int _start_microsecs
long int _stop_secs
long int _stop_microsecs
Detailed Description
Simple timer class for measuring elapsed time, with precision down to microseconds.
Author:
BJ Tordoff
Date:
25/03/2004 There are several ways to use this class, but some general rules:
The timer starts when the class is created
Calling Start() will reset the timer to zero
Calling Stop() stores the end time
Calling GetAsXXX() with the timer running returns the elapsed time but leaves the timer running
Some example uses:
VW::Timer timer; t.Start(); SomeFunc(); t.Stop(); cout << "SomeFunc took " << timer << endl;
VW::Timer timer; SomeCode(); cout << "Time since start is " << timer << endl; SomeMoreCode(); cout << "Time since start is " << timer << endl;
VW::Timer timer; double secs1,secs2; timer.Start(); SomeCode(); secs1 = timer.GetAsSeconds(); timer.Start(); // Restart the timer SomeMoreCode(); secs2 = timer.GetAsSeconds();
cout << "Code took " << secs1 << " + " << secs2 << " seconds." << endl;
Constructor & Destructor Documentation
VW::Timer::Timer ()
References Start().
Member Function Documentation
double VW::Timer::GetAsMicroseconds () const [inline]
Return the time elapsed with units of micro-seconds (precision is microsecs).
References GetAsSeconds().
double VW::Timer::GetAsMilliseconds () const [inline]
Return the time elapsed with units of milli-seconds (precision is still microsecs).
References GetAsSeconds().
Referenced by VW::FMatrixAffineComputePreemptive::Compute(), VW::EssentialMatrixComputePreemptive::Compute(), GLUTMotionFunc(), and GLUTPassiveMotionFunc().
double VW::Timer::GetAsNanoseconds () const [inline]
Return the time elapsed with units of micro-seconds (precision is still microsecs).
References GetAsSeconds().
double VW::Timer::GetAsSeconds () const
Return the time elapsed with units of seconds (precision is still microsecs).
References _is_running, _start_microsecs, _start_secs, _stop_microsecs, and _stop_secs.
Referenced by GetAsMicroseconds(), GetAsMilliseconds(), GetAsNanoseconds(), and VW::operator<<().
void VW::Timer::Start ()
Start, or restart (if already going) the timer.
References _is_running, _start_microsecs, and _start_secs.
Referenced by VW::FMatrixAffineComputePreemptive::Compute(), VW::EssentialMatrixComputePreemptive::Compute(), GLUTMotionFunc(), GLUTPassiveMotionFunc(), and Timer().
void VW::Timer::Stop ()
Stop the timer, storing the time elapsed.
References _is_running, _stop_microsecs, and _stop_secs.
Member Data Documentation
bool VW::Timer::_is_running [protected]
Referenced by GetAsSeconds(), Start(), and Stop().
long int VW::Timer::_start_microsecs [protected]
Referenced by GetAsSeconds(), and Start().
long int VW::Timer::_start_secs [protected]
Referenced by GetAsSeconds(), and Start().
long int VW::Timer::_stop_microsecs [protected]
Referenced by GetAsSeconds(), and Stop().
long int VW::Timer::_stop_secs [protected]
Referenced by GetAsSeconds(), and Stop().
The documentation for this class was generated from the following files:
timer.h
timer.cpp