VW: VNL::SparseMatrixLinearSystem< T > Class Template Reference
VNL::SparseMatrixLinearSystem< T > Class Template Reference
SparseMatrix -> LinearSystem adaptor.
#include <sparsematrixlinearsystem.h>
Public Member Functions
SparseMatrixLinearSystem (VNL::SparseMatrix< T > const &A, VNL::Vector< T > const &b)
:Constructor from VNL::SparseMatrix<double> for system Ax = b.
void Multiply (VNL::Vector< double > const &x, VNL::Vector< double > &b) const
Implementations of the vnl_linear_system virtuals.
void TransposeMultiply (VNL::Vector< double > const &b, VNL::Vector< double > &x) const
Implementations of the vnl_linear_system virtuals.
void GetRHS (VNL::Vector< double > &b) const
Implementations of the vnl_linear_system virtuals.
void ApplyPreconditioner (VNL::Vector< double > const &x, VNL::Vector< double > &px) const
Implementations of the vnl_linear_system virtuals.
template<>
void GetRHS (VNL::Vector< double > &b) const
template<>
void TransposeMultiply (VNL::Vector< double > const &b, VNL::Vector< double > &x) const
Compute A_transpose * y, putting result in x.
template<>
void GetRHS (VNL::Vector< double > &b) const
template<>
void TransposeMultiply (VNL::Vector< double > const &b, VNL::Vector< double > &x) const
Compute A_transpose * y, putting result in x.
template<>
void Multiply (VNL::Vector< double > const &x, VNL::Vector< double > &b) const
Compute A*x, putting result in y.
template<>
void Multiply (VNL::Vector< double > const &x, VNL::Vector< double > &b) const
Compute A*x, putting result in y.
int GetNumberOfUnknowns () const
Return the number of unknowns.
int GetNumberOfResiduals () const
Return the number of residuals.
double GetRMSError (Vector< double > const &x) const
Compute rms error for parameter vector x.
double GetRelativeResidual (Vector< double > const &x) const
Compute relative residual (|Ax - b| / |b|)for parameter vector x.
Protected Attributes
VNL::SparseMatrix< T > const & A_
VNL::Vector< T > const & b_
VNL::Vector< double > jacobi_precond_
int p_
int n_
Detailed Description
template<class T>
class VNL::SparseMatrixLinearSystem< T >
SparseMatrix -> LinearSystem adaptor.
An adaptor that converts a SparseMatrix<T> to a LinearSystem
Constructor & Destructor Documentation
template<class T > VNL::SparseMatrixLinearSystem< T >::SparseMatrixLinearSystem (VNL::SparseMatrix< T > const & A, VNL::Vector< T > const & b) [inline]
:Constructor from VNL::SparseMatrix<double> for system Ax = b.
Keeps a reference to the original sparse matrix A and vector b so DO NOT DELETE THEM!!
Member Function Documentation
template<class T > void VNL::SparseMatrixLinearSystem< T >::ApplyPreconditioner (VNL::Vector< double > const & x, VNL::Vector< double > & px) const [inline, virtual]
Implementations of the vnl_linear_system virtuals.
Reimplemented from VNL::LinearSystem.
References VNL::SparseMatrixLinearSystem< T >::A_, VNL::DotProduct(), VNL::LinearSystem::GetNumberOfUnknowns(), VNL::SparseMatrixLinearSystem< T >::jacobi_precond_, and VNL::Vector< T >::size().
int VNL::LinearSystem::GetNumberOfResiduals () const [inline, inherited]
Return the number of residuals.
References VNL::LinearSystem::n_.
Referenced by VNL::LSqr::Minimize().
int VNL::LinearSystem::GetNumberOfUnknowns () const [inline, inherited]
Return the number of unknowns.
References VNL::LinearSystem::p_.
Referenced by VNL::SparseMatrixLinearSystem< T >::ApplyPreconditioner(), and VNL::LSqr::Minimize().
double VNL::LinearSystem::GetRelativeResidual (VNL::Vector< double > const & x) const [inherited]
Compute relative residual (|Ax - b| / |b|)for parameter vector x.
References VNL::LinearSystem::GetRHS(), VNL::LinearSystem::Multiply(), VNL::LinearSystem::n_, and VNL::Vector< T >::RMS().
template<> void VNL::SparseMatrixLinearSystem< float >::GetRHS (VNL::Vector< double > & b) const [inline, virtual]
Implements VNL::LinearSystem.
References VNL::SparseMatrixLinearSystem< T >::b_, and VNL::Copy().
template<> void VNL::SparseMatrixLinearSystem< double >::GetRHS (VNL::Vector< double > & b) const [inline, virtual]
Implements VNL::LinearSystem.
References VNL::SparseMatrixLinearSystem< T >::b_.
template<class T > void VNL::SparseMatrixLinearSystem< T >::GetRHS (VNL::Vector< double > & b) const [virtual]
Implementations of the vnl_linear_system virtuals.
Implements VNL::LinearSystem.
double VNL::LinearSystem::GetRMSError (VNL::Vector< double > const & x) const [inherited]
Compute rms error for parameter vector x.
References VNL::LinearSystem::GetRHS(), VNL::LinearSystem::Multiply(), VNL::LinearSystem::n_, and VNL::Vector< T >::RMS().
template<> void VNL::SparseMatrixLinearSystem< float >::Multiply (VNL::Vector< double > const & x, VNL::Vector< double > & y) const [inline, virtual]
Compute A*x, putting result in y.
Implements VNL::LinearSystem.
References VNL::SparseMatrixLinearSystem< T >::A_, VNL::Copy(), and VNL::Vector< T >::size().
template<> void VNL::SparseMatrixLinearSystem< double >::Multiply (VNL::Vector< double > const & x, VNL::Vector< double > & y) const [inline, virtual]
Compute A*x, putting result in y.
Implements VNL::LinearSystem.
References VNL::SparseMatrixLinearSystem< T >::A_.
template<class T > void VNL::SparseMatrixLinearSystem< T >::Multiply (VNL::Vector< double > const & x, VNL::Vector< double > & b) const [virtual]
Implementations of the vnl_linear_system virtuals.
Implements VNL::LinearSystem.
template<> void VNL::SparseMatrixLinearSystem< float >::TransposeMultiply (VNL::Vector< double > const & y, VNL::Vector< double > & x) const [inline, virtual]
Compute A_transpose * y, putting result in x.
Implements VNL::LinearSystem.
References VNL::SparseMatrixLinearSystem< T >::A_, VNL::Copy(), and VNL::Vector< T >::size().
template<> void VNL::SparseMatrixLinearSystem< double >::TransposeMultiply (VNL::Vector< double > const & y, VNL::Vector< double > & x) const [inline, virtual]
Compute A_transpose * y, putting result in x.
Implements VNL::LinearSystem.
References VNL::SparseMatrixLinearSystem< T >::A_.
template<class T > void VNL::SparseMatrixLinearSystem< T >::TransposeMultiply (VNL::Vector< double > const & b, VNL::Vector< double > & x) const [virtual]
Implementations of the vnl_linear_system virtuals.
Implements VNL::LinearSystem.
Member Data Documentation
template<class T > VNL::SparseMatrix<T> const& VNL::SparseMatrixLinearSystem< T >::A_ [protected]
Referenced by VNL::SparseMatrixLinearSystem< T >::ApplyPreconditioner(), VNL::SparseMatrixLinearSystem< T >::Multiply(), and VNL::SparseMatrixLinearSystem< T >::TransposeMultiply().
template<class T > VNL::Vector<T> const& VNL::SparseMatrixLinearSystem< T >::b_ [protected]
Referenced by VNL::SparseMatrixLinearSystem< T >::GetRHS().
template<class T > VNL::Vector<double> VNL::SparseMatrixLinearSystem< T >::jacobi_precond_ [protected]
Referenced by VNL::SparseMatrixLinearSystem< T >::ApplyPreconditioner().
int VNL::LinearSystem::n_ [protected, inherited]
Referenced by VNL::LinearSystem::GetNumberOfResiduals(), VNL::LinearSystem::GetRelativeResidual(), and VNL::LinearSystem::GetRMSError().
int VNL::LinearSystem::p_ [protected, inherited]
Referenced by VNL::LinearSystem::GetNumberOfUnknowns().
The documentation for this class was generated from the following files:
sparsematrixlinearsystem.h
sparsematrixlinearsystem.cpp