VW: VW::Thread Class Reference
VW::Thread Class Reference
[CoreSequencers]
Base class from which a multi-threaded app can derrive.
#include <thread.h>
Public Member Functions
Thread ()
Construct, with optional attributes.
virtual ~Thread ()
operator ThreadType * ()
virtual void * Main (void *)=0
int Detach ()
int Start (void *arg=0)
Static Protected Member Functions
static FuncRetType _CallMain (void *obj)
Protected Attributes
ThreadType _thread
void * _arg
Detailed Description
Base class from which a multi-threaded app can derrive.
Constructor & Destructor Documentation
VW::Thread::Thread ()
Construct, with optional attributes.
VW::Thread::~Thread () [virtual]
Member Function Documentation
FuncRetType VW::Thread::_CallMain (void * obj) [static, protected]
References _arg, Main(), and VERBOSE.
Referenced by Start().
int VW::Thread::Detach ()
References _thread.
Referenced by VW::SequencerBase::Stop().
virtual void* VW::Thread::Main (void *) [pure virtual]
Implemented in VW::SequencerBase.
Referenced by _CallMain().
VW::Thread::operator ThreadType * () [inline]
References _thread.
int VW::Thread::Start (void * arg = 0)
References _arg, _CallMain(), _thread, and VERBOSE.
Referenced by VW::SequencerBase::Continuous().
Member Data Documentation
void* VW::Thread::_arg [protected]
Referenced by _CallMain(), and Start().
ThreadType VW::Thread::_thread [protected]
Referenced by Detach(), operator ThreadType *(), and Start().
The documentation for this class was generated from the following files:
thread.h
thread.cpp