VW: VW::PDF::Gaussian1D Class Reference
VW::PDF::Gaussian1D Class Reference
[MathsStuff]
a small class to hold the constants associated with a 1D Gaussian PDF.
#include <pdfgaussian1d.h>
Public Member Functions
Gaussian1D (double mean=0, double variance=1)
double EvaluateDensityForValue (double e) const
Calculate the probability density at location x.
double EvaluateDensityForError (double e) const
Evaluate the density at a distance from the mean.
double EvaluateDensityForError2 (double e_squared) const
Evaluate the density at a distance-squared from the mean.
double ApproxDensityForError2 (double e_squared) const
calculate the approximate density using a Pade approximation to exp, which is faster, but only accurate to about e = 3*sigma
double Sample () const
Sample from a random variable with this PDF.
double GetMean () const
double GetStandardDeviation () const
double GetVariance () const
Protected Attributes
double _mu
double _sigma
double _sigma2
Detailed Description
a small class to hold the constants associated with a 1D Gaussian PDF.
Author:
BJ Tordoff
Date:
30/06/2003 This PDF class allows evaluation of the probability density at any location, and sampling from a random variable with this PDF. Since some parts of the evaluation depend only on and , storing as a class gives some computational benefits.
Constructor & Destructor Documentation
VW::PDF::Gaussian1D::Gaussian1D (double mean = 0, double variance = 1) [inline]
Member Function Documentation
double VW::PDF::Gaussian1D::ApproxDensityForError2 (double e_squared) const [inline]
calculate the approximate density using a Pade approximation to exp, which is faster, but only accurate to about e = 3*sigma
References VW::PadeExp44().
Referenced by VW::FMatrixAffineComputePreemptive::Compute(), and VW::EssentialMatrixComputePreemptive::Compute().
double VW::PDF::Gaussian1D::EvaluateDensityForError (double e) const [inline]
Evaluate the density at a distance from the mean.
References EvaluateDensityForError2().
Referenced by VW::Line2DCompute::CalcErrorProbabilityPoint().
double VW::PDF::Gaussian1D::EvaluateDensityForError2 (double e_squared) const [inline]
Evaluate the density at a distance-squared from the mean.
Referenced by EvaluateDensityForError(), and EvaluateDensityForValue().
double VW::PDF::Gaussian1D::EvaluateDensityForValue (double x) const [inline, virtual]
Calculate the probability density at location x.
Implements VW::PDF::PDFBase1D.
References VW::PDF::PDFBase1D::_mu, and EvaluateDensityForError2().
double VW::PDF::PDFBase1D::GetMean () const [inline, inherited]
References VW::PDF::PDFBase1D::_mu.
double VW::PDF::PDFBase1D::GetStandardDeviation () const [inline, inherited]
References VW::PDF::PDFBase1D::_sigma.
double VW::PDF::PDFBase1D::GetVariance () const [inline, inherited]
References VW::PDF::PDFBase1D::_sigma2.
double VW::PDF::Gaussian1D::Sample () const [virtual]
Sample from a random variable with this PDF.
Implements VW::PDF::PDFBase1D.
References VW::PDF::PDFBase1D::_mu, VW::PDF::PDFBase1D::_sigma, PI, VW::Rand(), and std::sqrt().
Member Data Documentation
double VW::PDF::PDFBase1D::_mu [protected, inherited]
Referenced by EvaluateDensityForValue(), VW::PDF::PDFBase1D::GetMean(), VW::PDF::Uniform1D::Sample(), and Sample().
double VW::PDF::PDFBase1D::_sigma [protected, inherited]
Referenced by VW::PDF::PDFBase1D::GetStandardDeviation(), and Sample().
double VW::PDF::PDFBase1D::_sigma2 [protected, inherited]
Referenced by VW::PDF::PDFBase1D::GetVariance().
The documentation for this class was generated from the following files:
pdfgaussian1d.h
pdfgaussian1d.cpp