VW: VW::GLUTWindow Class Reference
VW::GLUTWindow Class Reference
#include <glutwindow.h>
Public Member Functions
virtual ~GLUTWindow ()
bool IsMe (int i) const
void SetID (int id)
int GetID () const
virtual void Mouse (int button, int state, int x, int y)=0
virtual void Draw ()=0
virtual void Resize (int w, int h)=0
virtual void Motion (int x, int y)=0
virtual void PassiveMotion (int x, int y)=0
virtual void Keyboard (unsigned char key, int x, int y)=0
Protected Member Functions
int _CreateWindow (unsigned int width, unsigned int height, const std::string &title)
int _CreateSubwindow (int parent_window_id, unsigned int x, unsigned int y, unsigned int width, unsigned int height)
void _MakeCurrent () const
Constructor & Destructor Documentation
virtual VW::GLUTWindow::~GLUTWindow () [inline, virtual]
Member Function Documentation
int VW::GLUTWindow::_CreateSubwindow (int parent_window_id, unsigned int x, unsigned int y, unsigned int width, unsigned int height) [protected]
References GLUTAddWindow(), and GLUTRegisterCallbacks().
Referenced by VW::ThreeDToolGluteWidget::SetSize(), and VW::DisplayGluteWidget::SetSize().
int VW::GLUTWindow::_CreateWindow (unsigned int width, unsigned int height, const std::string & title) [protected]
References GLUTAddWindow(), GLUTRegisterCallbacks(), and VERBOSE.
Referenced by VW::DisplayGLUT::SetSize(), VW::ThreeDToolGLUT::ThreeDToolGLUT(), and Glute2::Window::Window().
void VW::GLUTWindow::_MakeCurrent () const [inline, protected]
Referenced by Glute2::Window::MakeCurrent(), VW::DisplayGluteWidget::MakeCurrent(), VW::DisplayGluteWidget::Resize(), VW::DisplayGluteWidget::SetSize(), and VW::DisplayGluteWidget::SwapBuffers().
virtual void VW::GLUTWindow::Draw () [pure virtual]
Implemented in VW::DisplayGLUT, VW::ThreeDToolGLUT, VW::DisplayGluteWidget, VW::ThreeDToolGluteWidget, and Glute2::Window.
int VW::GLUTWindow::GetID () const [inline]
Referenced by GLUTAddWindow(), VW::ThreeDToolGluteWidget::MakeCurrent(), VW::ThreeDToolGluteWidget::RequestDraw(), VW::ThreeDToolGluteWidget::Resize(), and VW::ThreeDToolGluteWidget::SwapBuffers().
bool VW::GLUTWindow::IsMe (int i) const [inline]
Reimplemented in VW::DisplayGLUT, VW::ThreeDToolGLUT, VW::DisplayGluteWidget, and VW::ThreeDToolGluteWidget.
virtual void VW::GLUTWindow::Keyboard (unsigned char key, int x, int y) [pure virtual]
Implemented in VW::DisplayGLUT, VW::ThreeDToolGLUT, VW::DisplayGluteWidget, VW::ThreeDToolGluteWidget, and Glute2::Window.
virtual void VW::GLUTWindow::Motion (int x, int y) [pure virtual]
Implemented in VW::DisplayGLUT, VW::ThreeDToolGLUT, VW::DisplayGluteWidget, VW::ThreeDToolGluteWidget, and Glute2::Window.
virtual void VW::GLUTWindow::Mouse (int button, int state, int x, int y) [pure virtual]
Implemented in VW::DisplayGLUT, VW::ThreeDToolGLUT, VW::DisplayGluteWidget, VW::ThreeDToolGluteWidget, and Glute2::Window.
virtual void VW::GLUTWindow::PassiveMotion (int x, int y) [pure virtual]
Implemented in VW::DisplayGLUT, VW::ThreeDToolGLUT, VW::DisplayGluteWidget, VW::ThreeDToolGluteWidget, and Glute2::Window.
virtual void VW::GLUTWindow::Resize (int w, int h) [pure virtual]
Implemented in VW::DisplayGLUT, VW::ThreeDToolGLUT, VW::DisplayGluteWidget, VW::ThreeDToolGluteWidget, and Glute2::Window.
void VW::GLUTWindow::SetID (int id) [inline]
The documentation for this class was generated from the following files:
glutwindow.h
glutwindow.cpp