VW: VNL::LinearSystem Class Reference
VNL::LinearSystem Class Reference
Abstraction for a linear system of equations.
#include <linearsystem.h>
Public Member Functions
LinearSystem (int number_of_unknowns, int number_of_residuals)
virtual ~LinearSystem ()
virtual void Multiply (Vector< double > const &x, Vector< double > &y) const =0
Compute A*x, putting result in y.
virtual void TransposeMultiply (Vector< double > const &y, Vector< double > &x) const =0
Compute A_transpose * y, putting result in x.
virtual void GetRHS (Vector< double > &b) const =0
virtual void ApplyPreconditioner (Vector< double > const &x, Vector< double > &px) const
int GetNumberOfUnknowns () const
Return the number of unknowns.
int GetNumberOfResiduals () const
Return the number of residuals.
double GetRMSError (Vector< double > const &x) const
Compute rms error for parameter vector x.
double GetRelativeResidual (Vector< double > const &x) const
Compute relative residual (|Ax - b| / |b|)for parameter vector x.
Protected Attributes
int p_
int n_
Detailed Description
Abstraction for a linear system of equations.
vnl_linear_system provides an abstraction for a linear system of equations, Ax = b, to be solved by one of the iterative linear solvers. Access to the systems is via the pure virtual methods multiply() and transpose_multiply(). This procedural access scheme makes it possible to solve very large, sparse systems which it would be inefficient to store in matrix form.
To solve the system, use an algorithm like vnl_lsqr.
Constructor & Destructor Documentation
VNL::LinearSystem::LinearSystem (int number_of_unknowns, int number_of_residuals) [inline]
VNL::LinearSystem::~LinearSystem () [virtual]
Member Function Documentation
void VNL::LinearSystem::ApplyPreconditioner (VNL::Vector< double > const & x, VNL::Vector< double > & px) const [virtual]
Reimplemented in VNL::SparseMatrixLinearSystem< T >.
References VNL::Vector< T >::size().
int VNL::LinearSystem::GetNumberOfResiduals () const [inline]
Return the number of residuals.
References n_.
Referenced by VNL::LSqr::Minimize().
int VNL::LinearSystem::GetNumberOfUnknowns () const [inline]
Return the number of unknowns.
References p_.
Referenced by VNL::SparseMatrixLinearSystem< T >::ApplyPreconditioner(), and VNL::LSqr::Minimize().
double VNL::LinearSystem::GetRelativeResidual (VNL::Vector< double > const & x) const
Compute relative residual (|Ax - b| / |b|)for parameter vector x.
References GetRHS(), Multiply(), n_, and VNL::Vector< T >::RMS().
virtual void VNL::LinearSystem::GetRHS (Vector< double > & b) const [pure virtual]
Implemented in VNL::SparseMatrixLinearSystem< T >, VNL::SparseMatrixLinearSystem< T >, and VNL::SparseMatrixLinearSystem< T >.
Referenced by GetRelativeResidual(), GetRMSError(), and VNL::LSqr::Minimize().
double VNL::LinearSystem::GetRMSError (VNL::Vector< double > const & x) const
Compute rms error for parameter vector x.
References GetRHS(), Multiply(), n_, and VNL::Vector< T >::RMS().
virtual void VNL::LinearSystem::Multiply (Vector< double > const & x, Vector< double > & y) const [pure virtual]
Compute A*x, putting result in y.
Implemented in VNL::SparseMatrixLinearSystem< T >, VNL::SparseMatrixLinearSystem< T >, and VNL::SparseMatrixLinearSystem< T >.
Referenced by VNL::LSqr::aprod_(), GetRelativeResidual(), and GetRMSError().
virtual void VNL::LinearSystem::TransposeMultiply (Vector< double > const & y, Vector< double > & x) const [pure virtual]
Compute A_transpose * y, putting result in x.
Implemented in VNL::SparseMatrixLinearSystem< T >, VNL::SparseMatrixLinearSystem< T >, and VNL::SparseMatrixLinearSystem< T >.
Referenced by VNL::LSqr::aprod_().
Member Data Documentation
int VNL::LinearSystem::n_ [protected]
Referenced by GetNumberOfResiduals(), GetRelativeResidual(), and GetRMSError().
int VNL::LinearSystem::p_ [protected]
Referenced by GetNumberOfUnknowns().
The documentation for this class was generated from the following files:
linearsystem.h
linearsystem.cpp