VW: VW::ScaleImage Class Reference
VW::ScaleImage Class Reference
[ImageProcessing]
Scaling of an image (isotropic or XY aligned).
#include <scaleimage.h>
Public Member Functions
ScaleImage (const float scale, const InterpolationMethod method=Bilinear)
Construct for isotropic scaling.
ScaleImage (const float x_scale, const float y_scale, const InterpolationMethod method=Bilinear)
Construct for XY aligned scaling.
template<class ImType >
ScaleImage (const ImType &im, const float scale, ImType &result, const InterpolationMethod method=Bilinear)
Construct and immediately scale isotropically.
template<class ImType >
ScaleImage (const ImType &im, const float x_scale, const float y_scale, ImType &result, const InterpolationMethod method=Bilinear)
Construct and immediately scale XY aligned.
template<class ImType >
void Compute (const ImType &im, ImType &result) const
Scale an image, storing the result in result.
Detailed Description
Scaling of an image (isotropic or XY aligned).
Author:
BJ Tordoff
Date:
14/06/2004
Constructor & Destructor Documentation
VW::ScaleImage::ScaleImage (const float scale, const InterpolationMethod method = Bilinear) [inline]
Construct for isotropic scaling.
VW::ScaleImage::ScaleImage (const float x_scale, const float y_scale, const InterpolationMethod method = Bilinear) [inline]
Construct for XY aligned scaling.
template<class ImType > VW::ScaleImage::ScaleImage (const ImType & im, const float scale, ImType & result, const InterpolationMethod method = Bilinear) [inline]
Construct and immediately scale isotropically.
References Compute().
template<class ImType > VW::ScaleImage::ScaleImage (const ImType & im, const float x_scale, const float y_scale, ImType & result, const InterpolationMethod method = Bilinear) [inline]
Construct and immediately scale XY aligned.
References Compute().
Member Function Documentation
template<class ImType > void VW::ScaleImage::Compute (const ImType & im, ImType & result) const [inline]
Scale an image, storing the result in result.
References VW::Bicubic, VW::Bilinear, VW::Biquadratic, and VW::NearestNeighbour.
Referenced by VW::PyramidYUV< StorageType >::Compute(), VW::Pyramid< StorageType >::Compute(), and ScaleImage().
The documentation for this class was generated from the following files:
scaleimage.h
scaleimage.cpp