VW: VW::EssentialMatrixComputePreemptive Class Reference
VW::EssentialMatrixComputePreemptive Class Reference
#include <essentialmatrixcomputepreemptive.h>
Public Member Functions
EssentialMatrixComputePreemptive (double image_noise, double search_area, unsigned int max_num_hypotheses)
bool Compute (VW::EssentialMatrix &E, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, std::vector< double > &posteriors)
Compute with random sampling.
bool Compute (VW::EssentialMatrix &E, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const std::vector< double > &priors, std::vector< double > &posteriors)
Compute with guided sampling according to "priors".
void SetImageNoise (double image_noise)
Set the expected image noise standard deviation (in pixels).
void SetSearchArea (double search_area)
Set the are searched for each feature.
void SetNumHypotheses (unsigned int num)
Set the number of hypotheses.
void SetMaxTime (double millisecs)
Set the maximum time in millisecs.
Constructor & Destructor Documentation
VW::EssentialMatrixComputePreemptive::EssentialMatrixComputePreemptive (double image_noise, double search_area, unsigned int max_num_hypotheses) [inline]
Member Function Documentation
bool VW::EssentialMatrixComputePreemptive::Compute (VW::EssentialMatrix & E, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const std::vector< double > & priors, std::vector< double > & posteriors)
Compute with guided sampling according to "priors".
References VW::AccumulateWeights(), VW::PDF::Gaussian1D::ApproxDensityForError2(), VW::EssentialMatrixCompute5Point::Compute(), VW::EssentialMatrixComputeLinear::ComputeWeighted(), VW::CreateRandomisedList(), VW::Timer::GetAsMilliseconds(), VW::Line2D::GetDistance2(), VW::Normalisation::GetScale(), VW::Normalisation::Normalise(), VNL::MatrixFixedRef< m, n, T >::resize(), VW::Timer::Start(), VW::EssentialMatrix::Transfer(), VW::EssentialMatrixCompute::Unnormalise(), and VW::WeightedSample().
bool VW::EssentialMatrixComputePreemptive::Compute (VW::EssentialMatrix & E, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, std::vector< double > & posteriors)
Compute with random sampling.
References VW::PDF::Gaussian1D::ApproxDensityForError2(), VW::EssentialMatrixCompute5Point::Compute(), VW::EssentialMatrixComputeLinear::ComputeWeighted(), VW::CreateRandomisedList(), VW::Timer::GetAsMilliseconds(), VW::Line2D::GetDistance2(), VW::Normalisation::GetScale(), VW::Normalisation::Normalise(), VW::RandomSample(), VNL::MatrixFixedRef< m, n, T >::resize(), VW::Timer::Start(), VW::EssentialMatrix::Transfer(), and VW::EssentialMatrixCompute::Unnormalise().
void VW::EssentialMatrixComputePreemptive::SetImageNoise (double image_noise) [inline]
Set the expected image noise standard deviation (in pixels).
This is used to determine the Gaussian model for the inlier process.
void VW::EssentialMatrixComputePreemptive::SetMaxTime (double millisecs) [inline]
Set the maximum time in millisecs.
If not set, not time limit is imposed.
void VW::EssentialMatrixComputePreemptive::SetNumHypotheses (unsigned int num) [inline]
Set the number of hypotheses.
void VW::EssentialMatrixComputePreemptive::SetSearchArea (double search_area) [inline]
Set the are searched for each feature.
This determines the uniform distribution used to model the outlier process.
The documentation for this class was generated from the following files:
essentialmatrixcomputepreemptive.h
essentialmatrixcomputepreemptive.cpp