VW: VW::SequencerFile Class Reference
VW::SequencerFile Class Reference
[Sequencers, CoreSequencers]
A sequencer for handling sequentailly ordered files.
#include <sequencerfile.h>
Public Member Functions
SequencerFile ()
Construct without initialising.
SequencerFile (const std::string &file_name)
Construct a single file-reader.
SequencerFile (const std::vector< std::string > &file_names)
Construct multiple file-readers.
virtual bool Init ()
All sequencers have an Init(), even if they don't need it, so call init() before using a sequencer (especially if from an interface).
virtual void AddChannel (const std::string &file_name)
Add an extra file-channel.
void AddChannels (const std::vector< std::string > &file_names)
Add a set of extra file-channels.
bool IsChannelOK (unsigned int which_channel=0) const
Was the last read operation on this channel successful?
void * GetBuffer (unsigned int which_channel=0)
Gain access to the sequencers buffer.
template<class ImType >
void CopyImage (ImType &image, unsigned int which_channel=0)
Take a copy of the grabbed image.
virtual void Rewind ()
Rewind the grabbing of all movies to the beginning.
virtual void Skip (int num_frames=1)
Skip the next frame(s).
virtual void SetLooping (SequencerLoopMode mode=LOOP)
What should the sequencer do when it runs out of files in the sequence?
std::string GetInitialFileName (unsigned int which_channel=0)
The name(s) of the files.
Sequence control functions
virtual void Continuous ()
Start continuous capture from the sequence.
virtual void Stop ()
Stop continuous capture from the sequence.
virtual void Next ()
Capture the next single frame.
Initialisation functions
virtual void SetDelay (int d)
Set the delay between frames (only usually used for non-hardware sequencers).
Information functions
bool GetContinuous () const
Is the sequencer running in continuous mode?
int GetDelay () const
What is the delay between frames.
unsigned int GetNumberOfChannels () const
Most sequencers are able to present mutliple images per frame.
unsigned int GetCurrentFrameNumber () const
Return the current frame number.
Public Attributes
VWEvents::Event1< void, int > NewFrameEvent
The "new frame has arrived" event.
Protected Member Functions
void _InitialiseFiles ()
bool _DetermineFilenamePatterns (unsigned int which_channel)
virtual bool _Step ()
void _WaitForThread ()
Wait for the thread to exit.
virtual void _FrameArrived ()
we have been signalled that a frame has arrived and we are now "inside" the signalling object, so invoke the appropriate callback
void * Main (void *)
void _CheckInitialised ()
Protected Attributes
std::vector< ImageRGB
< unsigned char > * > im
std::vector< std::string > first_file_name
std::vector< std::string > format_string
std::vector< int > frame_num
std::vector< int > initial_frame_num
std::vector< int > play_speed
std::vector< bool > file_ok
SequencerLoopMode _loop
int delay
unsigned int frame_number
bool cont
bool thread_running
bool _initialised
ThreadType parent
unsigned int number_of_channels
Mutex access_lock
bool user_finished
Detailed Description
A sequencer for handling sequentailly ordered files.
Author:
ID Reid, BJ Tordoff
Date:
02/08/02 The file sequencer can take several ordered lists of files and present each list as a channel within the sequencer paradigm. The sequence is initialised using just the first frame, from which the numbering scheme is deduced. The enumeration of the files must be using a zero-filled fixed-width field such as "some_name_00001.ppm". Channels can be added in one go by passing a vector of filenames, or singly by repeatedly adding a single filename. The netpbm package is used to allow loading of a wide sleection of image types, of which jpeg,png,gif,ppm,pgm,eps are just a few.
Constructor & Destructor Documentation
SequencerFile::SequencerFile ()
Construct without initialising.
References _InitialiseFiles(), VW::SequencerBase::frame_number, and VW::SequencerBase::number_of_channels.
VW::SequencerFile::SequencerFile (const std::string & file_name)
Construct a single file-reader.
VW::SequencerFile::SequencerFile (const std::vector< std::string > & file_names)
Construct multiple file-readers.
Member Function Documentation
void VW::SequencerBase::_CheckInitialised () [protected, inherited]
References VW::SequencerBase::_initialised.
Referenced by VW::SequencerBase::Continuous(), VW::SequencerBase::Next(), and VW::SequencerBase::Stop().
bool SequencerFile::_DetermineFilenamePatterns (unsigned int which_channel) [protected]
References first_file_name, format_string, frame_num, and initial_frame_num.
Referenced by VW::SequencerFileGTK::UpdateFromForm().
void SequencerBase::_FrameArrived () [protected, virtual, inherited]
we have been signalled that a frame has arrived and we are now "inside" the signalling object, so invoke the appropriate callback
Reimplemented in VW::SequencerFileGTK, VW::SequencerFirewireGTK, VW::SequencerFileWx, VW::SequencerFirewireWx, and VW::SequencerMeteor.
References VW::SequencerBase::NewFrameEvent, VW::SequencerBase::user_finished, and VERBOSE.
Referenced by VW::SequencerBase::Main(), and VW::SequencerBase::Next().
void SequencerFile::_InitialiseFiles () [protected]
References _loop, file_ok, format_string, frame_num, VW::SequencerBase::frame_number, im, initial_frame_num, VW::NO_LOOPING, VW::SequencerBase::number_of_channels, and play_speed.
Referenced by SequencerFile().
bool SequencerFile::_Step () [protected, virtual]
Implements VW::SequencerBase.
References _loop, VW::SequencerBase::access_lock, VW::BOUNCE, VW::SequencerBase::cont, file_ok, format_string, frame_num, VW::SequencerBase::frame_number, im, initial_frame_num, VW::Mutex::Lock(), VW::LOOP, VW::NO_LOOPING, VW::SequencerBase::number_of_channels, play_speed, VW::ReadImage(), VW::REPEATLAST, VW::SequencerBase::Stop(), and VW::Mutex::Unlock().
void SequencerBase::_WaitForThread () [inline, protected, inherited]
Wait for the thread to exit.
References VW::SequencerBase::access_lock, VW::Mutex::Lock(), msleep(), VW::SequencerBase::thread_running, VW::Mutex::Unlock(), and VERBOSE.
Referenced by VW::SequencerBase::Stop().
virtual void VW::SequencerFile::AddChannel (const std::string & file_name) [virtual]
Add an extra file-channel.
Channels can be added at any time and simply begin from thier first frame.
Reimplemented in VW::SequencerFileGTK, and VW::SequencerFileWx.
Referenced by AddChannels().
void VW::SequencerFile::AddChannels (const std::vector< std::string > & file_names) [inline]
Add a set of extra file-channels.
Channels can be added at any time and simply begin from thier first frame.
References AddChannel().
void SequencerBase::Continuous () [virtual, inherited]
Start continuous capture from the sequence.
Reimplemented in VW::SequencerFileGTK, VW::SequencerFirewireGTK, VW::SequencerMovieGTK, VW::SequencerFileWx, VW::SequencerFirewireWx, and VW::SequencerMeteor.
References VW::SequencerBase::_CheckInitialised(), VW::SequencerBase::access_lock, VW::SequencerBase::cont, VW::Mutex::Lock(), VW::Thread::Start(), and VW::Mutex::Unlock().
Referenced by VW::SequencerFirewireGlute::_ContClicked(), VW::SequencerFileGlute::_ContClicked(), VW::SequencerFirewireGlow::OnMessage(), and VW::SequencerFileGlow::OnMessage().
template<class ImType > void VW::SequencerFile::CopyImage (ImType & image, unsigned int which_channel = 0) [inline]
Take a copy of the grabbed image.
References im, VW::ImageCopy(), and VW::SequencerBase::number_of_channels.
void * VW::SequencerFile::GetBuffer (unsigned int which_channel = 0) [inline, virtual]
Gain access to the sequencers buffer.
Implements VW::SequencerBase.
References im.
bool VW::SequencerBase::GetContinuous () const [inline, inherited]
Is the sequencer running in continuous mode?
References VW::SequencerBase::cont.
unsigned int VW::SequencerBase::GetCurrentFrameNumber () const [inline, inherited]
Return the current frame number.
In the case of movies or files this is the frame number with respect to the start frame (ie, 1=start frame) and won't correspond to the sequence frame numbers if started part way through a sequence.
References VW::SequencerBase::frame_number.
int VW::SequencerBase::GetDelay () const [inline, inherited]
What is the delay between frames.
References VW::SequencerBase::delay.
std::string VW::SequencerFile::GetInitialFileName (unsigned int which_channel = 0) [inline]
The name(s) of the files.
References first_file_name.
Referenced by VW::SequencerFileGTKWidget::AddFile().
unsigned int VW::SequencerBase::GetNumberOfChannels () const [inline, inherited]
Most sequencers are able to present mutliple images per frame.
References VW::SequencerBase::number_of_channels.
Referenced by VW::SequencerMovieGTKWidget::InitForm(), and VW::SequencerFileGTKWidget::InitForm().
virtual bool VW::SequencerFile::Init () [inline, virtual]
All sequencers have an Init(), even if they don't need it, so call init() before using a sequencer (especially if from an interface).
Reimplemented from VW::SequencerBase.
Reimplemented in VW::SequencerFileGTK, and VW::SequencerFileWx.
bool VW::SequencerFile::IsChannelOK (unsigned int which_channel = 0) const [inline]
Was the last read operation on this channel successful?
References file_ok.
void * SequencerBase::Main (void *) [protected, virtual, inherited]
Implements VW::Thread.
References VW::SequencerBase::_FrameArrived(), VW::SequencerBase::_Step(), VW::SequencerBase::access_lock, VW::SequencerBase::cont, VW::SequencerBase::delay, VW::SequencerBase::frame_number, VW::Mutex::Lock(), msleep(), VW::SequencerBase::thread_running, VW::Mutex::Unlock(), and VERBOSE.
void SequencerBase::Next () [virtual, inherited]
Capture the next single frame.
Reimplemented in VW::SequencerFileGTK, VW::SequencerFirewireGTK, VW::SequencerMovieGTK, VW::SequencerFileWx, VW::SequencerFirewireWx, and VW::SequencerMeteor.
References VW::SequencerBase::_CheckInitialised(), VW::SequencerBase::_FrameArrived(), VW::SequencerBase::_Step(), VW::SequencerBase::access_lock, VW::SequencerBase::cont, VW::Mutex::Lock(), VW::SequencerBase::Stop(), and VW::Mutex::Unlock().
Referenced by VW::SequencerFirewireGlute::_NextClicked(), VW::SequencerFileGlute::_NextClicked(), VW::SequencerFirewireGlow::OnMessage(), and VW::SequencerFileGlow::OnMessage().
void SequencerFile::Rewind () [virtual]
Rewind the grabbing of all movies to the beginning.
Reimplemented in VW::SequencerFileGTK, and VW::SequencerFileWx.
References VW::SequencerBase::access_lock, file_ok, frame_num, VW::SequencerBase::frame_number, initial_frame_num, VW::Mutex::Lock(), VW::SequencerBase::number_of_channels, and VW::Mutex::Unlock().
void VW::SequencerBase::SetDelay (int d) [inline, virtual, inherited]
Set the delay between frames (only usually used for non-hardware sequencers).
This is the time (in milliseconds) for which the sequencer sleeps between frames: the total frame period will be this plus the time taken to acquire the new frame. By default the delay is set to 1ms (zero or less is not a valid setting).
References VW::SequencerBase::delay.
void VW::SequencerFile::SetLooping (SequencerLoopMode mode = LOOP) [inline, virtual]
What should the sequencer do when it runs out of files in the sequence?
Reimplemented in VW::SequencerFileGTK, and VW::SequencerFileWx.
References _loop.
void SequencerFile::Skip (int num_frames = 1) [virtual]
Skip the next frame(s).
References VW::SequencerBase::access_lock, file_ok, frame_num, VW::SequencerBase::frame_number, VW::Mutex::Lock(), VW::SequencerBase::number_of_channels, and VW::Mutex::Unlock().
void SequencerBase::Stop () [virtual, inherited]
Stop continuous capture from the sequence.
Reimplemented in VW::SequencerFileGTK, VW::SequencerFirewireGTK, VW::SequencerMovieGTK, VW::SequencerFileWx, VW::SequencerFirewireWx, VW::SequencerFirewire, and VW::SequencerMeteor.
References VW::SequencerBase::_CheckInitialised(), VW::SequencerBase::_WaitForThread(), VW::SequencerBase::access_lock, VW::SequencerBase::cont, VW::Thread::Detach(), VW::Mutex::Lock(), VW::Mutex::Unlock(), and VERBOSE.
Referenced by VW::SequencerMovie::_Step(), _Step(), VW::SequencerFileGlute::_StopClicked(), VW::SequencerBase::Next(), and VW::SequencerFileGlow::OnMessage().
Member Data Documentation
bool VW::SequencerBase::_initialised [protected, inherited]
Referenced by VW::SequencerBase::_CheckInitialised(), and VW::SequencerBase::Init().
SequencerLoopMode VW::SequencerFile::_loop [protected]
Referenced by _InitialiseFiles(), _Step(), VW::SequencerFileWx::SetLooping(), VW::SequencerFileGTK::SetLooping(), and SetLooping().
Mutex VW::SequencerBase::access_lock [protected, inherited]
Referenced by _Step(), VW::SequencerBase::_WaitForThread(), VW::SequencerBase::Continuous(), VW::SequencerBase::Main(), VW::SequencerBase::Next(), Rewind(), Skip(), and VW::SequencerBase::Stop().
bool VW::SequencerBase::cont [protected, inherited]
Referenced by VW::SequencerMovie::_Step(), VW::SequencerFirewire::_Step(), _Step(), VW::SequencerBase::Continuous(), VW::SequencerBase::GetContinuous(), VW::SequencerBase::Main(), VW::SequencerBase::Next(), VW::SequencerBase::Stop(), VW::SequencerMovieGTK::UpdateForm(), VW::SequencerFirewireWx::UpdateForm(), VW::SequencerFileWx::UpdateForm(), and VW::SequencerFileGTK::UpdateForm().
int VW::SequencerBase::delay [protected, inherited]
Referenced by VW::SequencerBase::GetDelay(), VW::SequencerBase::Main(), and VW::SequencerBase::SetDelay().
std::vector<bool> VW::SequencerFile::file_ok [protected]
Referenced by _InitialiseFiles(), _Step(), IsChannelOK(), Rewind(), Skip(), VW::SequencerFileWx::UpdateForm(), VW::SequencerFileGTK::UpdateForm(), and VW::SequencerFileGTK::UpdateFromForm().
std::vector<std::string> VW::SequencerFile::first_file_name [protected]
Referenced by _DetermineFilenamePatterns(), GetInitialFileName(), and VW::SequencerFileGTK::UpdateFromForm().
std::vector<std::string> VW::SequencerFile::format_string [protected]
Referenced by _DetermineFilenamePatterns(), _InitialiseFiles(), and _Step().
std::vector<int> VW::SequencerFile::frame_num [protected]
Referenced by _DetermineFilenamePatterns(), _InitialiseFiles(), _Step(), Rewind(), and Skip().
unsigned int VW::SequencerBase::frame_number [protected, inherited]
Referenced by _InitialiseFiles(), VW::SequencerMovie::_Step(), _Step(), VW::SequencerBase::GetCurrentFrameNumber(), VW::SequencerBase::Main(), VW::SequencerMovie::Rewind(), Rewind(), SequencerFile(), Skip(), VW::SequencerFileWx::UpdateForm(), and VW::SequencerFileGTK::UpdateForm().
std::vector<ImageRGB<unsigned char>* > VW::SequencerFile::im [protected]
Referenced by _InitialiseFiles(), _Step(), CopyImage(), and GetBuffer().
std::vector<int> VW::SequencerFile::initial_frame_num [protected]
Referenced by _DetermineFilenamePatterns(), _InitialiseFiles(), _Step(), and Rewind().
VWEvents::Event1<void,int> VW::SequencerBase::NewFrameEvent [inherited]
The "new frame has arrived" event.
Attach a function to this callback signal if you want to perform an operation each time a new image arrives. This is typically done using my_sequencer.NewFrameEvent.connect(&MyFunction); where 'MyFunction' must take an integer argument and return void.
Referenced by VW::SequencerMeteor::_FrameArrived(), VW::SequencerFirewireWx::_FrameArrived(), VW::SequencerFirewireGTK::_FrameArrived(), VW::SequencerFileWx::_FrameArrived(), VW::SequencerFileGTK::_FrameArrived(), and VW::SequencerBase::_FrameArrived().
unsigned int VW::SequencerBase::number_of_channels [protected, inherited]
Referenced by _InitialiseFiles(), VW::SequencerMovie::_Step(), VW::SequencerFirewire::_Step(), _Step(), CopyImage(), VW::SequencerFirewire::GetCamera(), VW::SequencerFirewire::GetNumberOfCameras(), VW::SequencerBase::GetNumberOfChannels(), VW::SequencerMeteor::Init(), VW::SequencerFirewire::ProbeForCameras(), VW::SequencerMovie::Rewind(), Rewind(), SequencerFile(), VW::SequencerFirewire::SequencerFirewire(), VW::SequencerMovie::SequencerMovie(), VW::SequencerFirewire::SetDefaultCameraSettings(), Skip(), VW::SequencerFirewire::StartDMA(), VW::SequencerFirewire::StartISO(), VW::SequencerFirewire::StopDMA(), VW::SequencerFirewire::StopISO(), VW::SequencerMovieGTK::UpdateForm(), VW::SequencerFileWx::UpdateForm(), VW::SequencerFileGTK::UpdateForm(), VW::SequencerMovieGTK::UpdateFromForm(), and VW::SequencerFileGTK::UpdateFromForm().
ThreadType VW::SequencerBase::parent [protected, inherited]
std::vector<int> VW::SequencerFile::play_speed [protected]
Referenced by _InitialiseFiles(), and _Step().
bool VW::SequencerBase::thread_running [protected, inherited]
Referenced by VW::SequencerFirewire::_Step(), VW::SequencerBase::_WaitForThread(), and VW::SequencerBase::Main().
bool VW::SequencerBase::user_finished [protected, inherited]
Referenced by VW::SequencerFirewireWx::_FrameArrived(), VW::SequencerFirewireGTK::_FrameArrived(), VW::SequencerFileWx::_FrameArrived(), VW::SequencerFileGTK::_FrameArrived(), and VW::SequencerBase::_FrameArrived().
The documentation for this class was generated from the following files:
sequencerfile.h
sequencerfile.cpp