VW: VW::PatchFeature Class Reference
VW::PatchFeature Class Reference
[ImageProcessing]
A class to store a feature location along with the zero-normalised patch of the surrounding image.
#include <patchfeature.h>
Public Member Functions
PatchFeature (unsigned int patch_size=0)
PatchFeature (const float x, const float y, const float strength, const float scale, const unsigned int patch_size, const double orientation)
PatchFeature (const CornerFeature &base_feature, unsigned int patch_size, const double orientation)
double GetOrientation () const
Orientation is anti-clockwise from right.
void SetOrientation (const double new_orientation)
double GetMatchScore (const VW::PatchFeature &p2) const
The match score is the zero-normalised cross correlation (ZNCC).
unsigned int GetPatchSize () const
VW::ZNPatch GetPatch ()
VW::ZNPatch & Patch ()
const VW::ZNPatch & Patch () const
void SetPatch (const VW::ZNPatch &new_patch)
Try to avoid this one, as it copies the whole patch.
virtual bool WriteASCII (std::ostream &stream) const
Stream as plain ASCII.
virtual bool WriteXML (std::ostream &stream, const std::string &name="") const
Stream as XML style ASCII.
virtual bool WriteBinary (std::ostream &stream) const
Stream as binary.
virtual bool ReadASCII (std::istream &stream)
Stream as plain ASCII.
virtual bool ReadXML (std::istream &stream, const std::string &name="")
Stream as XML style ASCII.
virtual bool ReadBinary (std::istream &stream)
Stream as binary.
void Set (const float x, const float y, const float strength=0.0f, const float scale=1.0f)
void Set (const double x_coord, const double y_coord)
Set both the X and Y positions.
int GetPixelRow () const
int GetPixelColumn () const
float GetCornerStrength () const
void SetCornerStrength (const float new_strength)
float GetFeatureScale () const
void SetFeatureScale (const float new_scale)
bool operator> (const CornerFeature &p) const
bool operator< (const CornerFeature &p) const
bool operator== (const CornerFeature &p) const
Point2D & operator+= (const Point2D &p)
Add a point to this point - the result is another point.
Point2D & operator-= (const Point2D &p)
Subtract a point from this point - the result is another point.
Point2D & operator*= (double scale)
Point2D & operator/= (double scale)
bool operator!= (const Point2D &p) const
void Get (double &x_coord, double &y_coord) const
double GetX (void) const
Get the X position.
double GetY (void) const
Get the Y position.
double operator[] (unsigned int index) const
treat as an array (no bound checking!)
void SetX (const double x_coord)
Set the X position.
void SetY (const double y_coord)
Set the Y position.
double Norm () const
The 2-norm - root sum squared of the elements.
double NormSquared () const
The 2-norm squared - sum squared of the elements.
void Normalise ()
double GetDistance (const Point2D &testpoint) const
bool WriteASCIIFile (const std::string &filename) const
Open a file and output as plain ASCII (overwriting any existing contents).
bool WriteXMLFile (const std::string &filename, const std::string &name="") const
Open a file and output as XML-style ASCII (overwriting any existing contents).
bool WriteBinaryFile (const std::string &filename) const
Open a file and output as binary (overwriting any existing contents).
virtual bool ReadASCIIFile (const std::string &filename)
Open a file and input as plain ASCII.
virtual bool ReadXMLFile (const std::string &filename, const std::string &name="")
Open a file and input as XML style ASCII.
virtual bool ReadBinaryFile (const std::string &filename)
Open a file and input as binary.
Public Attributes
double _orientation
unsigned int _patchsize
ZNPatch _patch
double _x
double _y
Protected Attributes
int c
int r
float _strength
float _scale
Friends
Point2D operator+ (const Point2D &p1, const Point2D &p2)
Point2D operator- (const Point2D &p)
Point2D operator- (const Point2D &p1, const Point2D &p2)
double operator* (const Point2D &p1, const Point2D &p2)
Point2D operator* (const Point2D &p1, const double a)
Point2D operator* (const double a, const Point2D &p1)
Point2D operator/ (const Point2D &p1, const double a)
double ScalarProduct (const Point2D &p1, const Point2D &p2)
Detailed Description
A class to store a feature location along with the zero-normalised patch of the surrounding image.
Author:
BJ Tordoff
Date:
24/11/2004 include <VW/Improc/patchfeature.h>
Constructor & Destructor Documentation
VW::PatchFeature::PatchFeature (unsigned int patch_size = 0)
VW::PatchFeature::PatchFeature (const float x, const float y, const float strength, const float scale, const unsigned int patch_size, const double orientation)
VW::PatchFeature::PatchFeature (const CornerFeature & base_feature, unsigned int patch_size, const double orientation)
Member Function Documentation
void Point2D::Get (double & x_coord, double & y_coord) const [inherited]
References VW::Point2D::_x, and VW::Point2D::_y.
Referenced by VW::LineSeg2D::GetEndPoints().
float VW::CornerFeature::GetCornerStrength () const [inline, inherited]
References VW::CornerFeature::_strength.
Referenced by VW::ShiTomasiDetector::Compute(), VW::PlesseyDetector::Compute(), CompareStrength::operator()(), VW::PlesseyCornerYUV::operator<(), VW::CornerFeature::operator<(), VW::PlesseyCornerYUV::operator==(), VW::CornerFeature::operator==(), VW::PlesseyCornerYUV::operator>(), and VW::CornerFeature::operator>().
double VW::Point2D::GetDistance (const Point2D & testpoint) const [inline, inherited]
References VW::Point2D::_x, VW::Point2D::_y, and std::sqrt().
Referenced by VW::PMatrixCompute::LSFuncPoints::F(), VW::Homography2DCompute::LeastSquaresFunctionPoints::F(), VW::LineSeg2D::GetDistanceToLineSeg(), and VW::LineSeg2D::GetIntersection().
float VW::CornerFeature::GetFeatureScale () const [inline, inherited]
References VW::CornerFeature::_scale.
Referenced by VW::GetSIFTDescriptor::Compute(), VW::GetPatchDescriptor::Compute(), and VW::DrawFunctions::Draw().
double VW::PatchFeature::GetMatchScore (const VW::PatchFeature & p2) const [inline]
The match score is the zero-normalised cross correlation (ZNCC).
References _patch, VW::ZNPatch::GetMatchScore(), and Patch().
Referenced by VW::PatchFeatureMatcher::GetMatchScore().
double VW::PatchFeature::GetOrientation () const [inline]
Orientation is anti-clockwise from right.
References _orientation.
Referenced by VW::DrawFunctions::Draw().
VW::ZNPatch VW::PatchFeature::GetPatch () [inline]
References _patch.
unsigned int VW::PatchFeature::GetPatchSize () const [inline]
References _patch, and VW::ZNPatch::GetSize().
Referenced by VW::DrawFunctions::Draw().
int VW::CornerFeature::GetPixelColumn () const [inline, inherited]
References VW::CornerFeature::c.
int VW::CornerFeature::GetPixelRow () const [inline, inherited]
References VW::CornerFeature::r.
double VW::Point2D::GetX (void) const [inline, inherited]
Get the X position.
Returns:
the x position as a double.
References VW::Point2D::_x.
Referenced by VW::AWFObject::_GenList(), VW::ConvexHull2D::_IsClockwise(), VW::ThreeDToolGLCommon::ActuallyDrawDistortedTexturedRectangle(), VW::FMatrixCompute::AddToDesignMatrix(), VW::FMatrixAffineCompute::AddToDesignMatrix(), VW::EssentialMatrixCompute::AddToDesignMatrix(), VW::ShiTomasiDetector::Compute(), VW::PlesseyDetector::Compute(), VW::GetSIFTDescriptor::Compute(), VW::GetPatchDescriptor::Compute(), VW::ThreePointPose::ComputeJacobian(), VW::ThreePointPose::ComputeJacobians(), VW::LineSeg2D::DistanceToLeft(), VW::LineSeg2D::DistanceToRight(), VW::RadialDistortion::Distort(), VW::RadialDistortion::DistortImage(), VW::RadialDistortion::DistortPoint(), VW::DrawFunctions::Draw(), VW::DrawFunctions::DrawCovariance(), VW::Homography2DCompute::LeastSquaresFunctionPoints::F(), VW::FMPlanarCompute::LeastSquaresFunctionPoints::F(), VW::FMatrixCompute::LeastSquaresFunctionPoints::F(), FillDesignMatrix(), VW::FMPlanarCompute::GenerateParameterVectorHZ(), VW::LineSeg2D::GetAngle(), VW::Line2D::GetDistance(), VW::Line2D::GetDistance2(), VW::GetDistanceVariance(), VW::LineSeg2D::GetEndX(), VW::LineSeg2D::GetIntersection(), VW::LineSeg2D::GetLine(), VW::LineSeg2D::GetStartX(), VW::Homography2D::GetTransferError2(), VW::Normalisation::Normalise(), CompareX::operator()(), operator*(), VW::CalibrationMatrix::operator*(), VW::FMatrixAffine::ReverseTransfer(), VW::FMatrix::ReverseTransfer(), VW::EssentialMatrix::ReverseTransfer(), VW::Round(), VW::Warp::SetDistortion(), VW::CalibrationMatrix::SetPrincipalPoint(), VW::ThreePointPose::ThreePointPose(), VW::FMatrixAffine::Transfer(), VW::FMatrix::Transfer(), VW::EssentialMatrix::Transfer(), VW::TransferPoint(), VW::Homography2DCovariance::TransferUncertainty(), VW::FMatrixAffineCovariance::TransferUncertainty(), VW::FMatrixCovariance::TransferUncertainty(), VW::PMatrixCompute::TransformToParamVec(), VW::LineSeg2D::Truncate(), VW::Line2D::Truncate(), VW::RadialDistortion::Undistort(), VW::RadialDistortion::UndistortImage(), VW::RadialDistortion::UndistortInPlace(), VW::RadialDistortion::UndistortPoint(), VW::RadialDistortion::UndistortPointInPlace(), VW::Normalisation::UnNormalise(), and VW::Delaunay2D::UpdateTessellation().
double VW::Point2D::GetY (void) const [inline, inherited]
Get the Y position.
Returns:
the y position as a double.
References VW::Point2D::_y.
Referenced by VW::AWFObject::_GenList(), VW::ConvexHull2D::_IsClockwise(), VW::ThreeDToolGLCommon::ActuallyDrawDistortedTexturedRectangle(), VW::FMatrixCompute::AddToDesignMatrix(), VW::FMatrixAffineCompute::AddToDesignMatrix(), VW::EssentialMatrixCompute::AddToDesignMatrix(), VW::ShiTomasiDetector::Compute(), VW::PlesseyDetector::Compute(), VW::GetSIFTDescriptor::Compute(), VW::GetPatchDescriptor::Compute(), VW::ThreePointPose::ComputeJacobian(), VW::ThreePointPose::ComputeJacobians(), VW::LineSeg2D::DistanceToLeft(), VW::LineSeg2D::DistanceToRight(), VW::RadialDistortion::Distort(), VW::RadialDistortion::DistortImage(), VW::RadialDistortion::DistortPoint(), VW::DrawFunctions::Draw(), VW::DrawFunctions::DrawCovariance(), VW::Homography2DCompute::LeastSquaresFunctionPoints::F(), VW::FMPlanarCompute::LeastSquaresFunctionPoints::F(), VW::FMatrixCompute::LeastSquaresFunctionPoints::F(), FillDesignMatrix(), VW::FMPlanarCompute::GenerateParameterVectorHZ(), VW::LineSeg2D::GetAngle(), VW::Line2D::GetDistance(), VW::Line2D::GetDistance2(), VW::GetDistanceVariance(), VW::LineSeg2D::GetEndY(), VW::LineSeg2D::GetIntersection(), VW::LineSeg2D::GetLine(), VW::LineSeg2D::GetStartY(), VW::Homography2D::GetTransferError2(), VW::Normalisation::Normalise(), CompareY::operator()(), operator*(), VW::CalibrationMatrix::operator*(), IndexedPoint::operator<(), VW::FMatrixAffine::ReverseTransfer(), VW::FMatrix::ReverseTransfer(), VW::EssentialMatrix::ReverseTransfer(), VW::Round(), VW::Warp::SetDistortion(), VW::CalibrationMatrix::SetPrincipalPoint(), VW::ThreePointPose::ThreePointPose(), VW::FMatrixAffine::Transfer(), VW::FMatrix::Transfer(), VW::EssentialMatrix::Transfer(), VW::TransferPoint(), VW::Homography2DCovariance::TransferUncertainty(), VW::FMatrixAffineCovariance::TransferUncertainty(), VW::FMatrixCovariance::TransferUncertainty(), VW::PMatrixCompute::TransformToParamVec(), VW::LineSeg2D::Truncate(), VW::Line2D::Truncate(), VW::RadialDistortion::Undistort(), VW::RadialDistortion::UndistortImage(), VW::RadialDistortion::UndistortInPlace(), VW::RadialDistortion::UndistortPoint(), VW::RadialDistortion::UndistortPointInPlace(), VW::Normalisation::UnNormalise(), and VW::Delaunay2D::UpdateTessellation().
double VW::Point2D::Norm (void) const [inline, inherited]
The 2-norm - root sum squared of the elements.
Returns:
the 2-norm as a double.
References VW::Point2D::_x, VW::Point2D::_y, and std::sqrt().
Referenced by VW::Point2D::Normalise().
void VW::Point2D::Normalise () [inline, inherited]
References VW::Point2D::_x, VW::Point2D::_y, and VW::Point2D::Norm().
Referenced by VW::LineSeg2D::DistanceToLeft(), VW::LineSeg2D::DistanceToRight(), VW::LineSeg2D::GetCosAngle(), and VW::LineSeg2D::GetIntersection().
double VW::Point2D::NormSquared (void) const [inline, inherited]
The 2-norm squared - sum squared of the elements.
Returns:
the square of the 2-norm as a double.
References VW::Point2D::_x, and VW::Point2D::_y.
bool Point2D::operator!= (const Point2D & p) const [inherited]
References VW::Point2D::_x, and VW::Point2D::_y.
VW::Point2D & VW::Point2D::operator*= (double scale) [inline, inherited]
References VW::Point2D::_x, and VW::Point2D::_y.
VW::Point2D & VW::Point2D::operator+= (const Point2D & p) [inline, inherited]
Add a point to this point - the result is another point.
Returns:
the point formed by vector addition
References VW::Point2D::_x, and VW::Point2D::_y.
VW::Point2D & VW::Point2D::operator-= (const Point2D & p) [inline, inherited]
Subtract a point from this point - the result is another point.
Returns:
the point formed by vector subtraction
References VW::Point2D::_x, and VW::Point2D::_y.
VW::Point2D & VW::Point2D::operator/= (double scale) [inline, inherited]
References VW::Point2D::_x, and VW::Point2D::_y.
bool VW::CornerFeature::operator< (const CornerFeature & p) const [inline, inherited]
Reimplemented in VW::PlesseyCorner, and VW::PlesseyCornerYUV.
References VW::CornerFeature::_strength, and VW::CornerFeature::GetCornerStrength().
bool VW::CornerFeature::operator== (const CornerFeature & p) const [inline, inherited]
Reimplemented from VW::Point2D.
Reimplemented in VW::PlesseyCorner, and VW::PlesseyCornerYUV.
References VW::CornerFeature::_strength, and VW::CornerFeature::GetCornerStrength().
bool VW::CornerFeature::operator> (const CornerFeature & p) const [inline, inherited]
Reimplemented in VW::PlesseyCorner, and VW::PlesseyCornerYUV.
References VW::CornerFeature::_strength, and VW::CornerFeature::GetCornerStrength().
double VW::Point2D::operator[] (unsigned int index) const [inline, inherited]
treat as an array (no bound checking!)
References VW::Point2D::_x.
const VW::ZNPatch & VW::PatchFeature::Patch () const [inline]
References _patch.
VW::ZNPatch & VW::PatchFeature::Patch () [inline]
References _patch.
Referenced by GetMatchScore().
bool VW::PatchFeature::ReadASCII (std::istream & stream) [virtual]
Stream as plain ASCII.
Parameters:
stream the input stream to read from
Returns:
true if successfully read, false if there are problems
Reimplemented from VW::CornerFeature.
bool VW::IOObject::ReadASCIIFile (const std::string & filename) [virtual, inherited]
Open a file and input as plain ASCII.
Open a file and read as plain ASCII.
Once the file is open, the child class's ReadASCII function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadASCII().
bool VW::PatchFeature::ReadBinary (std::istream & stream) [virtual]
Stream as binary.
Parameters:
stream the input stream to read from
Returns:
true if successfully read, false if there are problems
Reimplemented from VW::CornerFeature.
References _orientation, _patch, VW::CornerFeature::_scale, VW::CornerFeature::_strength, VW::Point2D::_x, VW::Point2D::_y, and VW::ZNPatch::ReadBinary().
bool VW::IOObject::ReadBinaryFile (const std::string & filename) [virtual, inherited]
Open a file and input as binary.
Open a file and read as binary.
Once the file is open, the child class's ReadBinary function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadBinary().
bool VW::PatchFeature::ReadXML (std::istream & stream, const std::string & name = "") [virtual]
Stream as XML style ASCII.
Parameters:
stream the input stream to read from
name if specified, the found tag must have a NAME= parameter that matches
Returns:
true if successfully read, false if there are problems
Reimplemented from VW::CornerFeature.
bool VW::IOObject::ReadXMLFile (const std::string & filename, const std::string & name = "") [virtual, inherited]
Open a file and input as XML style ASCII.
Open a file and read as XML-style ASCII.
Once the file is open, the child class's ReadXML function is used to read the content.
Parameters:
filename the name of the file to open
name the optional name tag-attribute to match ie. data must start <MyClass name="name">
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadXML().
Referenced by VW::ClassifierUV::ClassifierUV(), and VW::FirewireCameraGTK::LoadParameterFile().
void VW::Point2D::Set (const double x_coord, const double y_coord) [inline, inherited]
Set both the X and Y positions.
Parameters:
x_coord the new X position.
y_coord the new Y position.
References VW::Point2D::_x, and VW::Point2D::_y.
Referenced by VW::ThreeDToolGLCommon::ActuallyDrawDistortedTexturedRectangle(), VW::FMatrixAffine::GetEpipoleDirections(), VW::FMatrix::GetEpipoles(), VW::EssentialMatrix::GetEpipoles(), VW::LineSeg2D::GetIntersection(), VW::PMatrixCompute::ParamVecToTransform(), VW::LineSeg2D::SetEndPoints(), and VW::TransferPoint().
void VW::CornerFeature::Set (const float x, const float y, const float strength = 0.0f, const float scale = 1.0f) [inline, inherited]
References VW::CornerFeature::_scale, VW::CornerFeature::_strength, VW::Point2D::_x, VW::Point2D::_y, VW::CornerFeature::c, and VW::CornerFeature::r.
Referenced by VW::ShiTomasiDetector::Compute(), and VW::PlesseyDetector::Compute().
void VW::CornerFeature::SetCornerStrength (const float new_strength) [inline, inherited]
References VW::CornerFeature::_strength.
Referenced by VW::PlesseyDetector::Compute().
void VW::CornerFeature::SetFeatureScale (const float new_scale) [inline, inherited]
References VW::CornerFeature::_scale.
void VW::PatchFeature::SetOrientation (const double new_orientation) [inline]
References _orientation.
void VW::PatchFeature::SetPatch (const VW::ZNPatch & new_patch)
Try to avoid this one, as it copies the whole patch.
..
void VW::Point2D::SetX (const double x_coord) [inline, inherited]
Set the X position.
Parameters:
x_coord the new X position.
References VW::Point2D::_x.
Referenced by VW::Normalisation::Normalise(), VW::CalibrationMatrix::operator*(), VW::RadialDistortion::UndistortInPlace(), and VW::Normalisation::UnNormalise().
void VW::Point2D::SetY (const double y_coord) [inline, inherited]
Set the Y position.
Parameters:
y_coord the new Y position.
References VW::Point2D::_y.
Referenced by VW::CalibrationMatrix::operator*(), and VW::RadialDistortion::UndistortInPlace().
bool VW::PatchFeature::WriteASCII (std::ostream & stream) const [virtual]
Stream as plain ASCII.
Parameters:
stream the output stream to write to
Returns:
true if successfully written, false if there are problems
Reimplemented from VW::CornerFeature.
References _orientation, _patch, VW::CornerFeature::_scale, VW::CornerFeature::_strength, VW::Point2D::_x, and VW::Point2D::_y.
Referenced by VW::operator<<().
bool VW::IOObject::WriteASCIIFile (const std::string & filename) const [inherited]
Open a file and output as plain ASCII (overwriting any existing contents).
Open a file and output as plain ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteASCII function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteASCII().
bool VW::PatchFeature::WriteBinary (std::ostream & stream) const [virtual]
Stream as binary.
Parameters:
stream the output stream to write to
Returns:
true if successfully written, false if there are problems
Reimplemented from VW::CornerFeature.
References _orientation, _patch, VW::CornerFeature::_scale, VW::CornerFeature::_strength, VW::Point2D::_x, VW::Point2D::_y, and VW::ZNPatch::WriteBinary().
bool VW::IOObject::WriteBinaryFile (const std::string & filename) const [inherited]
Open a file and output as binary (overwriting any existing contents).
Once the file is open, the child class's WriteBinary function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteBinary().
bool VW::PatchFeature::WriteXML (std::ostream & stream, const std::string & name = "") const [virtual]
Stream as XML style ASCII.
Parameters:
stream the output stream to write to
name if specified, the class will be given a NAME= parameter
Returns:
true if successfully written, false if there are problems
Reimplemented from VW::CornerFeature.
bool VW::IOObject::WriteXMLFile (const std::string & filename, const std::string & name = "") const [inherited]
Open a file and output as XML-style ASCII (overwriting any existing contents).
Open a file and output as XML-style ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteXML function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
name the tag parameter, if required
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteXML().
Referenced by VW::FirewireCameraGTK::SaveParameterFile().
Friends And Related Function Documentation
Point2D operator* (const double a, const Point2D & p1) [friend, inherited]
Point2D operator* (const Point2D & p1, const double a) [friend, inherited]
double operator* (const Point2D & p1, const Point2D & p2) [friend, inherited]
Point2D operator+ (const Point2D & p1, const Point2D & p2) [friend, inherited]
Point2D operator- (const Point2D & p1, const Point2D & p2) [friend, inherited]
Point2D operator- (const Point2D & p) [friend, inherited]
Point2D operator/ (const Point2D & p1, const double a) [friend, inherited]
double ScalarProduct (const Point2D & p1, const Point2D & p2) [friend, inherited]
Member Data Documentation
double VW::PatchFeature::_orientation
Referenced by GetOrientation(), ReadBinary(), SetOrientation(), WriteASCII(), and WriteBinary().
ZNPatch VW::PatchFeature::_patch
Referenced by GetMatchScore(), GetPatch(), GetPatchSize(), Patch(), ReadBinary(), WriteASCII(), and WriteBinary().
unsigned int VW::PatchFeature::_patchsize
float VW::CornerFeature::_scale [protected, inherited]
Referenced by VW::CornerFeature::GetFeatureScale(), VW::SIFTFeature::operator=(), VW::PlesseyCornerYUV::ReadASCII(), VW::PlesseyCorner::ReadASCII(), VW::CornerFeature::ReadASCII(), VW::SIFTFeature::ReadBinary(), VW::PlesseyCornerYUV::ReadBinary(), VW::PlesseyCorner::ReadBinary(), ReadBinary(), VW::CornerFeature::ReadBinary(), VW::PlesseyCornerYUV::ReadXML(), VW::PlesseyCorner::ReadXML(), VW::CornerFeature::ReadXML(), VW::PlesseyCornerYUV::Set(), VW::PlesseyCorner::Set(), VW::CornerFeature::Set(), VW::CornerFeature::SetFeatureScale(), VW::SIFTFeature::WriteASCII(), VW::PlesseyCornerYUV::WriteASCII(), VW::PlesseyCorner::WriteASCII(), WriteASCII(), VW::CornerFeature::WriteASCII(), VW::SIFTFeature::WriteBinary(), VW::PlesseyCornerYUV::WriteBinary(), VW::PlesseyCorner::WriteBinary(), WriteBinary(), and VW::CornerFeature::WriteBinary().
float VW::CornerFeature::_strength [protected, inherited]
Referenced by VW::CornerFeature::GetCornerStrength(), VW::PlesseyCornerYUV::operator<(), VW::CornerFeature::operator<(), VW::SIFTFeature::operator=(), VW::PlesseyCornerYUV::operator==(), VW::CornerFeature::operator==(), VW::PlesseyCornerYUV::operator>(), VW::CornerFeature::operator>(), VW::PlesseyCornerYUV::ReadASCII(), VW::PlesseyCorner::ReadASCII(), VW::CornerFeature::ReadASCII(), VW::SIFTFeature::ReadBinary(), VW::PlesseyCornerYUV::ReadBinary(), VW::PlesseyCorner::ReadBinary(), ReadBinary(), VW::CornerFeature::ReadBinary(), VW::PlesseyCornerYUV::ReadXML(), VW::PlesseyCorner::ReadXML(), VW::CornerFeature::ReadXML(), VW::PlesseyCornerYUV::Set(), VW::PlesseyCorner::Set(), VW::CornerFeature::Set(), VW::CornerFeature::SetCornerStrength(), VW::SIFTFeature::WriteASCII(), VW::PlesseyCornerYUV::WriteASCII(), VW::PlesseyCorner::WriteASCII(), WriteASCII(), VW::CornerFeature::WriteASCII(), VW::SIFTFeature::WriteBinary(), VW::PlesseyCornerYUV::WriteBinary(), VW::PlesseyCorner::WriteBinary(), WriteBinary(), VW::CornerFeature::WriteBinary(), VW::PlesseyCornerYUV::WriteXML(), VW::PlesseyCorner::WriteXML(), and VW::CornerFeature::WriteXML().
double VW::Point2D::_x [inherited]
Referenced by VW::CornerFeature::CornerFeature(), VW::LineSegFitted::CorrectEndpoints(), VW::Point2D::Get(), VW::Point2D::GetDistance(), VW::LineSeg2D::GetDistanceToLine(), VW::LineSeg2D::GetDistanceToLineSeg(), VW::LineSeg2D::GetLength(), VW::LineSeg2D::GetLength2(), VW::Point2D::GetX(), VW::LineSegFitted::LineSegFitted(), VW::Point2D::Norm(), VW::Point2D::Normalise(), VW::Point2D::NormSquared(), VW::Point2D::operator!=(), VW::operator*(), VW::Point2D::operator*=(), VW::operator+(), VW::Point2D::operator+=(), VW::operator-(), VW::Point2D::operator-=(), VW::operator/(), VW::Point2D::operator/=(), VW::SIFTFeature::operator=(), VW::Point2D::operator=(), VW::Point2D::operator==(), VW::Point2D::operator[](), VW::Point2D::ReadASCII(), VW::PlesseyCornerYUV::ReadASCII(), VW::PlesseyCorner::ReadASCII(), VW::CornerFeature::ReadASCII(), VW::SIFTFeature::ReadBinary(), VW::Point2D::ReadBinary(), VW::PlesseyCornerYUV::ReadBinary(), VW::PlesseyCorner::ReadBinary(), ReadBinary(), VW::CornerFeature::ReadBinary(), VW::Point2D::ReadXML(), VW::PlesseyCornerYUV::ReadXML(), VW::PlesseyCorner::ReadXML(), VW::CornerFeature::ReadXML(), VW::ScalarProduct(), VW::Point2D::Set(), VW::PlesseyCornerYUV::Set(), VW::PlesseyCorner::Set(), VW::CornerFeature::Set(), VW::Point2D::SetX(), VW::SIFTFeature::WriteASCII(), VW::Point2D::WriteASCII(), VW::PlesseyCornerYUV::WriteASCII(), VW::PlesseyCorner::WriteASCII(), WriteASCII(), VW::CornerFeature::WriteASCII(), VW::SIFTFeature::WriteBinary(), VW::Point2D::WriteBinary(), VW::PlesseyCornerYUV::WriteBinary(), VW::PlesseyCorner::WriteBinary(), WriteBinary(), VW::CornerFeature::WriteBinary(), VW::Point2D::WriteXML(), VW::PlesseyCornerYUV::WriteXML(), VW::PlesseyCorner::WriteXML(), and VW::CornerFeature::WriteXML().
double VW::Point2D::_y [inherited]
Referenced by VW::CornerFeature::CornerFeature(), VW::LineSegFitted::CorrectEndpoints(), VW::Point2D::Get(), VW::Point2D::GetDistance(), VW::LineSeg2D::GetDistanceToLine(), VW::LineSeg2D::GetDistanceToLineSeg(), VW::LineSeg2D::GetLength(), VW::LineSeg2D::GetLength2(), VW::Point2D::GetY(), VW::LineSegFitted::LineSegFitted(), VW::Point2D::Norm(), VW::Point2D::Normalise(), VW::Point2D::NormSquared(), VW::Point2D::operator!=(), VW::operator*(), VW::Point2D::operator*=(), VW::operator+(), VW::Point2D::operator+=(), VW::operator-(), VW::Point2D::operator-=(), VW::operator/(), VW::Point2D::operator/=(), VW::SIFTFeature::operator=(), VW::Point2D::operator=(), VW::Point2D::operator==(), VW::Point2D::ReadASCII(), VW::PlesseyCornerYUV::ReadASCII(), VW::PlesseyCorner::ReadASCII(), VW::CornerFeature::ReadASCII(), VW::SIFTFeature::ReadBinary(), VW::Point2D::ReadBinary(), VW::PlesseyCornerYUV::ReadBinary(), VW::PlesseyCorner::ReadBinary(), ReadBinary(), VW::CornerFeature::ReadBinary(), VW::Point2D::ReadXML(), VW::PlesseyCornerYUV::ReadXML(), VW::PlesseyCorner::ReadXML(), VW::CornerFeature::ReadXML(), VW::ScalarProduct(), VW::Point2D::Set(), VW::PlesseyCornerYUV::Set(), VW::PlesseyCorner::Set(), VW::CornerFeature::Set(), VW::Point2D::SetY(), VW::SIFTFeature::WriteASCII(), VW::Point2D::WriteASCII(), VW::PlesseyCornerYUV::WriteASCII(), VW::PlesseyCorner::WriteASCII(), WriteASCII(), VW::CornerFeature::WriteASCII(), VW::SIFTFeature::WriteBinary(), VW::Point2D::WriteBinary(), VW::PlesseyCornerYUV::WriteBinary(), VW::PlesseyCorner::WriteBinary(), WriteBinary(), VW::CornerFeature::WriteBinary(), VW::Point2D::WriteXML(), VW::PlesseyCornerYUV::WriteXML(), VW::PlesseyCorner::WriteXML(), and VW::CornerFeature::WriteXML().
int VW::CornerFeature::c [protected, inherited]
Referenced by VW::CornerFeature::CornerFeature(), VW::CornerFeature::GetPixelColumn(), VW::SIFTFeature::operator=(), VW::PlesseyCornerYUV::Set(), VW::PlesseyCorner::Set(), and VW::CornerFeature::Set().
int VW::CornerFeature::r [protected, inherited]
Referenced by VW::CornerFeature::CornerFeature(), VW::CornerFeature::GetPixelRow(), VW::SIFTFeature::operator=(), VW::PlesseyCornerYUV::Set(), VW::PlesseyCorner::Set(), and VW::CornerFeature::Set().
The documentation for this class was generated from the following files:
patchfeature.h
patchfeature.cpp