VW: VW::GetSIFTDescriptor Class Reference
VW::GetSIFTDescriptor Class Reference
[ImageProcessing]
Interest point description using the method of Lowe.
#include <getsiftdescriptor.h>
Public Member Functions
GetSIFTDescriptor (const bool weighted=true, const bool oriented=true)
GetSIFTDescriptor (const std::vector< VW::CornerFeature > &locations, const VW::Pyramid< float > &image, std::vector< VW::SIFTFeature > &resulting_features, const bool weighted=true, const bool oriented=true)
bool Compute (const std::vector< VW::CornerFeature > &locations, const VW::Pyramid< float > &pyramid, std::vector< VW::SIFTFeature > &resulting_features)
Detailed Description
Interest point description using the method of Lowe.
Author:
BJ Tordoff after ND Molton
Date:
09/11/2004 include <VW/Improc/getsiftdescriptor.h>
Functions for adding a SIFT descriptor to a point set based on NDM's SIFT code.
Input is a list of location as output by VW::Plessey or VW::DOGDetector and the source image or image-pyramid. Output is a list of SIFTFeatures where each location generates one SIFTFeature per dominant orientation (typically either 1 or 2).
NB: Currently turning off orientation speeds things up a lot, but the weighting flag isn't used as yet.
Constructor & Destructor Documentation
VW::GetSIFTDescriptor::GetSIFTDescriptor (const bool weighted = true, const bool oriented = true) [inline]
VW::GetSIFTDescriptor::GetSIFTDescriptor (const std::vector< VW::CornerFeature > & locations, const VW::Pyramid< float > & image, std::vector< VW::SIFTFeature > & resulting_features, const bool weighted = true, const bool oriented = true) [inline]
References Compute().
Member Function Documentation
bool VW::GetSIFTDescriptor::Compute (const std::vector< VW::CornerFeature > & locations, const VW::Pyramid< float > & pyramid, std::vector< VW::SIFTFeature > & resulting_features)
References VW::Pyramid< StorageType >::ClosestLevel(), VW::CornerFeature::GetFeatureScale(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), VW::Pyramid< StorageType >::GetScale(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), VW::Point2D::GetX(), VW::Point2D::GetY(), and VERBOSE.
Referenced by GetSIFTDescriptor().
The documentation for this class was generated from the following files:
getsiftdescriptor.h
getsiftdescriptor.cpp