VW: VNL::LevenbergMarquardt Class Reference
VNL::LevenbergMarquardt Class Reference
Levenberg Marquardt nonlinear least squares.
#include <levenbergmarquardt.h>
Public Types
enum ReturnCodes {
ERROR_FAILURE = -1, ERROR_DODGY_INPUT = 0, CONVERGED_FTOL = 1, CONVERGED_XTOL = 2,
CONVERGED_XFTOL = 3, CONVERGED_GTOL = 4, FAILED_TOO_MANY_ITERATIONS = 5, FAILED_FTOL_TOO_SMALL = 6,
FAILED_XTOL_TOO_SMALL = 7, FAILED_GTOL_TOO_SMALL = 8
}
Some generic return codes that apply to all minimizers.
Public Member Functions
LevenbergMarquardt (LeastSquaresFunction &f)
Initialize with the function object that is to be minimized.
~LevenbergMarquardt ()
Initialize as above, and then run minimization.
bool MinimizeWithoutGradient (Vector< double > &x)
Minimize the function supplied in the constructor until convergence or failure.
bool MinimizeUsingGradient (Vector< double > &x)
Minimize the function supplied in the constructor until convergence or failure.
bool Minimize (Vector< double > &x)
Calls minimize_using_gradient() or minimize_without_gradient().
void DiagnoseOutcome () const
Provide an ASCII diagnosis of the last minimization on std::ostream.
void DiagnoseOutcome (std::ostream &) const
Matrix< double > const & GetJtJ ()
Return J'*J computed at last minimum.
void SetFTolerance (double v)
Set the convergence tolerance on F (sum of squared residuals).
double GetFTolerance () const
void SetXTolerance (double v)
Set the convergence tolerance on X.
double GetXTolerance () const
void SetGTolerance (double v)
Set the convergence tolerance on Grad(F)' * F.
double GetGTolerance () const
void SetMaxFunctionEvals (int v)
Set the termination maximum number of iterations.
int GetMaxFunctionEvals () const
void SetEpsilonFunction (double v)
Set the step length for FD Jacobian.
double GetEpsilonFunction () const
void SetTrace (bool on)
Turn on per-iteration printouts.
bool GetTrace () const
void SetVerbose (bool verb)
Set verbose flag.
bool GetVerbose () const
void SetCheckDerivatives (int cd)
Set check_derivatives flag. Negative values may mean fewer checks.
int SetCheckDerivatives () const
double GetStartError () const
Return the error of the function when it was evaluated at the start point of the last minimization.
double GetEndError () const
Return the best error that was achieved by the last minimization, corresponding to the returned x.
int GetNumEvaluations () const
Return the total number of times the function was evaluated by the last minimization.
int GetNumIterations () const
Return the number of {iterations} in the last minimization.
virtual Matrix< double > const & GetCovariance ()
Return the covariance of the estimate at the end.
virtual std::string IsA () const
Return the name of the class.
virtual bool IsClass (std::string const &s) const
Return true if the name of the class matches the argument.
ReturnCodes GetFailureCode () const
Return the failure code of the last minimization.
Protected Member Functions
void _Init (LeastSquaresFunction *f)
void _Reset ()
void _ReportEval (double f)
Called by derived classes after each function evaluation.
void _ReportIter ()
Called by derived classes after each iteration.
Static Protected Member Functions
static void lmdif_lsqfun (int *m, int *n, double *x, double *fx, int *iflag)
static void lmder_lsqfun (int *m, int *n, double *x, double *fx, double *fJ, int *, int *iflag)
Protected Attributes
LeastSquaresFunction * f_
Matrix< double > * fdjac_
Vector< int > * ipvt_
Matrix< double > * covariance_
bool set_covariance_
double xtol
int maxfev
double ftol
double gtol
double epsfcn
unsigned num_iterations_
int num_evaluations_
double start_error_
double end_error_
bool trace
bool verbose_
int check_derivatives_
ReturnCodes failure_code_
Friends
class LevenbergMarquardt_Activate
Detailed Description
Levenberg Marquardt nonlinear least squares.
vnl_levenberg_marquardt is an interface to the MINPACK routine lmdif, and implements Levenberg Marquardt nonlinear fitting. The function to be minimized is passed as a vnl_least_squares_function object, which may or may not wish to provide derivatives. If derivatives are not supplied, they are calculated by forward differencing, which costs one function evaluation per dimension, but is perfectly accurate. (See Hartley in ``Applications of Invariance in Computer Vision'' for example).
Member Enumeration Documentation
enum VNL::NonlinearMinimizer::ReturnCodes [inherited]
Some generic return codes that apply to all minimizers.
Enumerator:
ERROR_FAILURE
ERROR_DODGY_INPUT
CONVERGED_FTOL
CONVERGED_XTOL
CONVERGED_XFTOL
CONVERGED_GTOL
FAILED_TOO_MANY_ITERATIONS
FAILED_FTOL_TOO_SMALL
FAILED_XTOL_TOO_SMALL
FAILED_GTOL_TOO_SMALL
Constructor & Destructor Documentation
VNL::LevenbergMarquardt::LevenbergMarquardt (LeastSquaresFunction & f) [inline]
Initialize with the function object that is to be minimized.
References _Init().
VNL::LevenbergMarquardt::~LevenbergMarquardt ()
Initialize as above, and then run minimization.
obsolete, as virtuals in base class vnl_nonlinear_minimizer not valid... i.e. if minimize() calls base::get_covariance(), it will call the base version rather than any overridden here or in classes derived from this. This is an argument against computation in constructors. You should replace code like LevenbergMarquardt lm(f, x); with LevenbergMarquardt lm(f); lm.minimize(x); Or x = LevenbergMarquardt_minimize(f, x);
References covariance_, fdjac_, and ipvt_.
Member Function Documentation
void VNL::LevenbergMarquardt::_Init (VNL::LeastSquaresFunction * f) [protected]
References covariance_, VNL::NonlinearMinimizer::epsfcn, f_, fdjac_, VNL::NonlinearMinimizer::ftol, VNL::LeastSquaresFunction::GetNumberOfResiduals(), VNL::LeastSquaresFunction::GetNumberOfUnknowns(), VNL::NonlinearMinimizer::gtol, ipvt_, m, VNL::NonlinearMinimizer::maxfev, set_covariance_, and VNL::NonlinearMinimizer::xtol.
Referenced by LevenbergMarquardt().
void VNL::NonlinearMinimizer::_ReportEval (double f) [protected, inherited]
Called by derived classes after each function evaluation.
References VNL::NonlinearMinimizer::end_error_, VNL::NonlinearMinimizer::num_evaluations_, and VNL::NonlinearMinimizer::start_error_.
Referenced by VNL::Powell::_PubReportEval(), and VNL::Powell::Minimize().
void VNL::NonlinearMinimizer::_ReportIter () [protected, inherited]
Called by derived classes after each iteration.
References VNL::NonlinearMinimizer::end_error_, VNL::NonlinearMinimizer::num_evaluations_, VNL::NonlinearMinimizer::num_iterations_, and VNL::NonlinearMinimizer::verbose_.
Referenced by VNL::Powell::Minimize().
void VNL::NonlinearMinimizer::_Reset () [protected, inherited]
References VNL::NonlinearMinimizer::num_evaluations_, VNL::NonlinearMinimizer::num_iterations_, and VNL::NonlinearMinimizer::start_error_.
Referenced by VNL::NonlinearMinimizer::NonlinearMinimizer().
void VNL::LevenbergMarquardt::DiagnoseOutcome (std::ostream & s) const
References VNL::NonlinearMinimizer::CONVERGED_FTOL, VNL::NonlinearMinimizer::CONVERGED_GTOL, VNL::NonlinearMinimizer::CONVERGED_XFTOL, VNL::NonlinearMinimizer::CONVERGED_XTOL, VNL::NonlinearMinimizer::ERROR_DODGY_INPUT, VNL::NonlinearMinimizer::ERROR_FAILURE, f_, VNL::NonlinearMinimizer::FAILED_FTOL_TOO_SMALL, VNL::NonlinearMinimizer::FAILED_GTOL_TOO_SMALL, VNL::NonlinearMinimizer::FAILED_TOO_MANY_ITERATIONS, VNL::NonlinearMinimizer::FAILED_XTOL_TOO_SMALL, VNL::NonlinearMinimizer::failure_code_, VNL::NonlinearMinimizer::GetEndError(), VNL::LeastSquaresFunction::GetNumberOfResiduals(), VNL::NonlinearMinimizer::GetStartError(), m, VNL::NonlinearMinimizer::num_evaluations_, VNL::NonlinearMinimizer::num_iterations_, and whoami.
void VNL::LevenbergMarquardt::DiagnoseOutcome () const
Provide an ASCII diagnosis of the last minimization on std::ostream.
Referenced by MinimizeUsingGradient(), and MinimizeWithoutGradient().
VNL::Matrix< double > const & VNL::NonlinearMinimizer::GetCovariance () [virtual, inherited]
Return the covariance of the estimate at the end.
double VNL::NonlinearMinimizer::GetEndError () const [inline, inherited]
Return the best error that was achieved by the last minimization, corresponding to the returned x.
References VNL::NonlinearMinimizer::end_error_.
Referenced by DiagnoseOutcome().
double VNL::NonlinearMinimizer::GetEpsilonFunction () const [inline, inherited]
References VNL::NonlinearMinimizer::epsfcn.
ReturnCodes VNL::NonlinearMinimizer::GetFailureCode () const [inline, inherited]
Return the failure code of the last minimization.
References VNL::NonlinearMinimizer::failure_code_.
double VNL::NonlinearMinimizer::GetFTolerance () const [inline, inherited]
References VNL::NonlinearMinimizer::ftol.
double VNL::NonlinearMinimizer::GetGTolerance () const [inline, inherited]
References VNL::NonlinearMinimizer::gtol.
VNL::Matrix< double > const & VNL::LevenbergMarquardt::GetJtJ ()
Return J'*J computed at last minimum.
References covariance_, and set_covariance_.
int VNL::NonlinearMinimizer::GetMaxFunctionEvals () const [inline, inherited]
References VNL::NonlinearMinimizer::maxfev.
Referenced by VNL::LBFGS::Minimize().
int VNL::NonlinearMinimizer::GetNumEvaluations () const [inline, inherited]
Return the total number of times the function was evaluated by the last minimization.
References VNL::NonlinearMinimizer::num_evaluations_.
int VNL::NonlinearMinimizer::GetNumIterations () const [inline, inherited]
Return the number of {iterations} in the last minimization.
Each iteration may have comprised several function evaluations.
References VNL::NonlinearMinimizer::num_iterations_.
double VNL::NonlinearMinimizer::GetStartError () const [inline, inherited]
Return the error of the function when it was evaluated at the start point of the last minimization.
For minimizers driven by a vnl_least_squares_function (Levenberg-Marquardt) this is usually the RMS error. For those driven by a vnl_cost_function (CG, LBFGS, Amoeba) it is simply the value of the vnl_cost_function at the start (usually the sum of squared residuals).
References VNL::NonlinearMinimizer::start_error_.
Referenced by DiagnoseOutcome().
bool VNL::NonlinearMinimizer::GetTrace () const [inline, inherited]
References VNL::NonlinearMinimizer::trace.
bool VNL::NonlinearMinimizer::GetVerbose () const [inline, inherited]
References VNL::NonlinearMinimizer::verbose_.
double VNL::NonlinearMinimizer::GetXTolerance () const [inline, inherited]
References VNL::NonlinearMinimizer::xtol.
std::string VNL::NonlinearMinimizer::IsA () const [virtual, inherited]
Return the name of the class.
Used by polymorphic IO
Referenced by VNL::NonlinearMinimizer::IsClass().
bool VNL::NonlinearMinimizer::IsClass (std::string const & s) const [virtual, inherited]
Return true if the name of the class matches the argument.
Used by polymorphic IO
References VNL::NonlinearMinimizer::IsA().
void VNL::LevenbergMarquardt::lmder_lsqfun (int * m, int * n, double * x, double * fx, double * fJ, int * , int * iflag) [static, protected]
References VNL::LeastSquaresFunction::ClearFailure(), VNL::LeastSquaresFunction::F(), f_, VNL::LeastSquaresFunction::failure, VNL::LeastSquaresFunction::GetNumberOfResiduals(), VNL::LeastSquaresFunction::GetNumberOfUnknowns(), VNL::LeastSquaresFunction::GradF(), VNL::Matrix< T >::InplaceTranspose(), VNL::Vector< T >::Magnitude(), VNL::NonlinearMinimizer::num_iterations_, VNL::Vector< T >::RMS(), VNL::NonlinearMinimizer::start_error_, VNL::LeastSquaresFunction::Trace(), and VNL::NonlinearMinimizer::trace.
Referenced by MinimizeUsingGradient().
void VNL::LevenbergMarquardt::lmdif_lsqfun (int * m, int * n, double * x, double * fx, int * iflag) [static, protected]
References VNL::LeastSquaresFunction::ClearFailure(), VNL::LeastSquaresFunction::F(), f_, VNL::LeastSquaresFunction::failure, VNL::LeastSquaresFunction::GetNumberOfResiduals(), VNL::LeastSquaresFunction::GetNumberOfUnknowns(), VNL::Vector< T >::Magnitude(), VNL::NonlinearMinimizer::num_iterations_, VNL::Vector< T >::RMS(), VNL::NonlinearMinimizer::start_error_, VNL::LeastSquaresFunction::Trace(), and VNL::NonlinearMinimizer::trace.
Referenced by MinimizeWithoutGradient().
bool VNL::LevenbergMarquardt::Minimize (VNL::Vector< double > & x)
Calls minimize_using_gradient() or minimize_without_gradient().
, depending on whether the cost function provides a gradient.
References f_, VNL::LeastSquaresFunction::HasGradient(), MinimizeUsingGradient(), and MinimizeWithoutGradient().
Referenced by VW::Homography2DComputeNonLinear::Compute(), VW::FMPlanarComputeNonLinear::Compute(), VW::FMatrixComputeNonLinear::Compute(), VNL::LevenbergMarquardtMinimize(), VW::RadialDistortionCompute::NonLinearFromLines(), and VW::PMatrixCompute::NonLinearFromPoints().
bool VNL::LevenbergMarquardt::MinimizeUsingGradient (VNL::Vector< double > & x)
Minimize the function supplied in the constructor until convergence or failure.
On return, x is such that f(x) is the lowest value achieved. Returns true for convergence, false for failure. The cost function must provide a gradient.
References VNL::Matrix< T >::DataBlock(), VNL::Vector< T >::DataBlock(), DiagnoseOutcome(), VNL::NonlinearMinimizer::end_error_, VNL::NonlinearMinimizer::ERROR_DODGY_INPUT, VNL::NonlinearMinimizer::ERROR_FAILURE, f_, VNL::NonlinearMinimizer::failure_code_, fdjac_, VNL::NonlinearMinimizer::ftol, VNL::LeastSquaresFunction::GetNumberOfResiduals(), VNL::LeastSquaresFunction::GetNumberOfUnknowns(), VNL::LeastSquaresFunction::HasGradient(), ipvt_, lmder1_(), lmder_lsqfun(), m, VNL::NonlinearMinimizer::num_evaluations_, VNL::NonlinearMinimizer::num_iterations_, VNL::Vector< T >::RMS(), set_covariance_, VNL::Vector< T >::size(), and VNL::NonlinearMinimizer::start_error_.
Referenced by Minimize().
bool VNL::LevenbergMarquardt::MinimizeWithoutGradient (VNL::Vector< double > & x)
Minimize the function supplied in the constructor until convergence or failure.
On return, x is such that f(x) is the lowest value achieved. Returns true for convergence, false for failure. Does not use the gradient even if the cost function provides one.
References VNL::Matrix< T >::DataBlock(), VNL::Vector< T >::DataBlock(), DiagnoseOutcome(), VNL::NonlinearMinimizer::end_error_, VNL::NonlinearMinimizer::epsfcn, VNL::NonlinearMinimizer::ERROR_DODGY_INPUT, f_, VNL::NonlinearMinimizer::failure_code_, fdjac_, VNL::NonlinearMinimizer::ftol, VNL::LeastSquaresFunction::GetNumberOfResiduals(), VNL::LeastSquaresFunction::GetNumberOfUnknowns(), VNL::NonlinearMinimizer::gtol, VNL::LeastSquaresFunction::HasGradient(), ipvt_, lmdif_(), lmdif_lsqfun(), m, VNL::NonlinearMinimizer::maxfev, VNL::NonlinearMinimizer::num_evaluations_, VNL::NonlinearMinimizer::num_iterations_, VNL::Vector< T >::RMS(), set_covariance_, VNL::Vector< T >::size(), VNL::NonlinearMinimizer::start_error_, and VNL::NonlinearMinimizer::xtol.
Referenced by Minimize().
int VNL::NonlinearMinimizer::SetCheckDerivatives () const [inline, inherited]
References VNL::NonlinearMinimizer::check_derivatives_.
void VNL::NonlinearMinimizer::SetCheckDerivatives (int cd) [inline, inherited]
Set check_derivatives flag. Negative values may mean fewer checks.
References VNL::NonlinearMinimizer::check_derivatives_.
void VNL::NonlinearMinimizer::SetEpsilonFunction (double v) [inline, inherited]
Set the step length for FD Jacobian.
Be aware that SetXTolerance will reset this to xtol * 0.001. The default is 1e-11.
References VNL::NonlinearMinimizer::epsfcn.
void VNL::NonlinearMinimizer::SetFTolerance (double v) [inline, inherited]
Set the convergence tolerance on F (sum of squared residuals).
When the differences in successive RMS errors is less than this, the routine terminates. So this is effectively the desired precision of your minimization. Setting it too low wastes time, too high might cause early convergence. The default of 1e-9 is on the safe side, but if speed is an issue, you can try raising it.
References VNL::NonlinearMinimizer::ftol.
Referenced by VW::Homography2DComputeNonLinear::Compute(), VW::FMPlanarComputeNonLinear::Compute(), VW::FMatrixComputeNonLinear::Compute(), VW::RadialDistortionCompute::NonLinearFromLines(), and VW::PMatrixCompute::NonLinearFromPoints().
void VNL::NonlinearMinimizer::SetGTolerance (double v) [inline, inherited]
Set the convergence tolerance on Grad(F)' * F.
References VNL::NonlinearMinimizer::gtol.
void VNL::NonlinearMinimizer::SetMaxFunctionEvals (int v) [inline, inherited]
Set the termination maximum number of iterations.
References VNL::NonlinearMinimizer::maxfev.
Referenced by VW::Homography2DComputeNonLinear::Compute(), VW::FMPlanarComputeNonLinear::Compute(), VW::FMatrixComputeNonLinear::Compute(), VW::RadialDistortionCompute::NonLinearFromLines(), and VW::PMatrixCompute::NonLinearFromPoints().
void VNL::NonlinearMinimizer::SetTrace (bool on) [inline, inherited]
Turn on per-iteration printouts.
References VNL::NonlinearMinimizer::trace.
void VNL::NonlinearMinimizer::SetVerbose (bool verb) [inline, inherited]
Set verbose flag.
References VNL::NonlinearMinimizer::verbose_.
void VNL::NonlinearMinimizer::SetXTolerance (double v) [inline, inherited]
Set the convergence tolerance on X.
When the length of the steps taken in X are about this long, the routine terminates. The default is 1e-8, which should work for many problems, but if you can get away with 1e-4, say, minimizations will be much quicker.
References VNL::NonlinearMinimizer::epsfcn, and VNL::NonlinearMinimizer::xtol.
Friends And Related Function Documentation
friend class LevenbergMarquardt_Activate [friend]
Member Data Documentation
int VNL::NonlinearMinimizer::check_derivatives_ [protected, inherited]
Referenced by VNL::LBFGS::Minimize(), VNL::NonlinearMinimizer::NonlinearMinimizer(), and VNL::NonlinearMinimizer::SetCheckDerivatives().
Matrix<double>* VNL::LevenbergMarquardt::covariance_ [protected]
Referenced by _Init(), GetJtJ(), and ~LevenbergMarquardt().
double VNL::NonlinearMinimizer::end_error_ [protected, inherited]
Referenced by VNL::NonlinearMinimizer::_ReportEval(), VNL::NonlinearMinimizer::_ReportIter(), VNL::ConjugateGradient::DiagnoseOutcome(), VNL::NonlinearMinimizer::GetEndError(), VNL::ConjugateGradient::Init(), VNL::LBFGS::Minimize(), VNL::ConjugateGradient::Minimize(), MinimizeUsingGradient(), and MinimizeWithoutGradient().
double VNL::NonlinearMinimizer::epsfcn [protected, inherited]
Referenced by _Init(), VNL::NonlinearMinimizer::GetEpsilonFunction(), MinimizeWithoutGradient(), VNL::NonlinearMinimizer::NonlinearMinimizer(), VNL::NonlinearMinimizer::SetEpsilonFunction(), and VNL::NonlinearMinimizer::SetXTolerance().
LeastSquaresFunction* VNL::LevenbergMarquardt::f_ [protected]
Referenced by _Init(), DiagnoseOutcome(), lmder_lsqfun(), lmdif_lsqfun(), Minimize(), MinimizeUsingGradient(), and MinimizeWithoutGradient().
ReturnCodes VNL::NonlinearMinimizer::failure_code_ [protected, inherited]
Referenced by DiagnoseOutcome(), VNL::NonlinearMinimizer::GetFailureCode(), VNL::LBFGS::Minimize(), MinimizeUsingGradient(), and MinimizeWithoutGradient().
Matrix<double>* VNL::LevenbergMarquardt::fdjac_ [protected]
Referenced by _Init(), MinimizeUsingGradient(), MinimizeWithoutGradient(), and ~LevenbergMarquardt().
double VNL::NonlinearMinimizer::ftol [protected, inherited]
Referenced by _Init(), VNL::NonlinearMinimizer::GetFTolerance(), VNL::Powell::Minimize(), VNL::Brent::Minimize(), MinimizeUsingGradient(), MinimizeWithoutGradient(), VNL::NonlinearMinimizer::NonlinearMinimizer(), and VNL::NonlinearMinimizer::SetFTolerance().
double VNL::NonlinearMinimizer::gtol [protected, inherited]
Referenced by _Init(), VNL::NonlinearMinimizer::GetGTolerance(), VNL::LBFGS::Minimize(), VNL::ConjugateGradient::Minimize(), MinimizeWithoutGradient(), VNL::NonlinearMinimizer::NonlinearMinimizer(), and VNL::NonlinearMinimizer::SetGTolerance().
Vector<int>* VNL::LevenbergMarquardt::ipvt_ [protected]
Referenced by _Init(), MinimizeUsingGradient(), MinimizeWithoutGradient(), and ~LevenbergMarquardt().
int VNL::NonlinearMinimizer::maxfev [protected, inherited]
Referenced by _Init(), VNL::NonlinearMinimizer::GetMaxFunctionEvals(), VNL::Powell::Minimize(), VNL::ConjugateGradient::Minimize(), MinimizeWithoutGradient(), VNL::NonlinearMinimizer::NonlinearMinimizer(), and VNL::NonlinearMinimizer::SetMaxFunctionEvals().
int VNL::NonlinearMinimizer::num_evaluations_ [protected, inherited]
Referenced by VNL::NonlinearMinimizer::_ReportEval(), VNL::NonlinearMinimizer::_ReportIter(), VNL::NonlinearMinimizer::_Reset(), DiagnoseOutcome(), VNL::ConjugateGradient::DiagnoseOutcome(), VNL::NonlinearMinimizer::GetNumEvaluations(), VNL::ConjugateGradient::Init(), VNL::LBFGS::Minimize(), VNL::ConjugateGradient::Minimize(), MinimizeUsingGradient(), MinimizeWithoutGradient(), and VNL::ConjugateGradient::ValueComputer_().
unsigned VNL::NonlinearMinimizer::num_iterations_ [protected, inherited]
Referenced by VNL::NonlinearMinimizer::_ReportIter(), VNL::NonlinearMinimizer::_Reset(), DiagnoseOutcome(), VNL::ConjugateGradient::DiagnoseOutcome(), VNL::NonlinearMinimizer::GetNumIterations(), VNL::ConjugateGradient::Init(), lmder_lsqfun(), lmdif_lsqfun(), VNL::Powell::Minimize(), VNL::LBFGS::Minimize(), VNL::ConjugateGradient::Minimize(), MinimizeUsingGradient(), and MinimizeWithoutGradient().
bool VNL::LevenbergMarquardt::set_covariance_ [protected]
Referenced by _Init(), GetJtJ(), MinimizeUsingGradient(), and MinimizeWithoutGradient().
double VNL::NonlinearMinimizer::start_error_ [protected, inherited]
Referenced by VNL::NonlinearMinimizer::_ReportEval(), VNL::NonlinearMinimizer::_Reset(), VNL::ConjugateGradient::DiagnoseOutcome(), VNL::NonlinearMinimizer::GetStartError(), VNL::ConjugateGradient::Init(), lmder_lsqfun(), lmdif_lsqfun(), VNL::LBFGS::Minimize(), VNL::ConjugateGradient::Minimize(), MinimizeUsingGradient(), and MinimizeWithoutGradient().
bool VNL::NonlinearMinimizer::trace [protected, inherited]
Referenced by VNL::NonlinearMinimizer::GetTrace(), lmder_lsqfun(), lmdif_lsqfun(), VNL::LBFGS::Minimize(), VNL::NonlinearMinimizer::NonlinearMinimizer(), and VNL::NonlinearMinimizer::SetTrace().
bool VNL::NonlinearMinimizer::verbose_ [protected, inherited]
Referenced by VNL::NonlinearMinimizer::_ReportIter(), VNL::NonlinearMinimizer::GetVerbose(), VNL::LBFGS::Minimize(), VNL::Brent::MinimizeGivenBounds(), VNL::Brent::MinimizeGivenBoundsAnd1stF(), VNL::NonlinearMinimizer::NonlinearMinimizer(), and VNL::NonlinearMinimizer::SetVerbose().
double VNL::NonlinearMinimizer::xtol [protected, inherited]
Referenced by _Init(), VNL::NonlinearMinimizer::GetXTolerance(), MinimizeWithoutGradient(), VNL::NonlinearMinimizer::NonlinearMinimizer(), and VNL::NonlinearMinimizer::SetXTolerance().
The documentation for this class was generated from the following files:
levenbergmarquardt.h
levenbergmarquardt.cpp