VW: VNL::RPolyRoots Class Reference
VNL::RPolyRoots Class Reference
Find the roots of a real polynomial.
#include <rpolyroots.h>
Public Member Functions
RPolyRoots (const VNL::Vector< double > &a)
The constructor calculates the roots.
RPolyRoots (const RealPolynomial &poly)
Calculate roots of a vnl_real_polynomial. Same comments apply.
std::complex< double > operator[] (int i) const
Return i'th complex root.
VNL::Vector< std::complex
< double > > Roots () const
Complex vector of all roots.
const double & Real (int i) const
Real part of root I.
const double & Imag (int i) const
Imaginary part of root I.
VNL::Vector< double > & Real ()
Vector of real parts of roots.
VNL::Vector< double > & Imag ()
Vector of imaginary parts of roots.
VNL::Vector< double > RealRoots (double tol=1e-12) const
Return real roots only.
bool Compute ()
Compute roots using Jenkins-Traub algorithm.
bool ComputeQR ()
Compute roots using QR decomposition of companion matrix. [unimplemented].
bool ComputeLaguerre ()
Compute roots using Laguerre algorithm. [unimplemented].
Protected Attributes
VNL::Vector< double > coeffs_
VNL::Vector< double > r_
VNL::Vector< double > i_
int num_roots_found_
Detailed Description
Find the roots of a real polynomial.
Uses algorithm 493 from ACM Trans. Math. Software - the Jenkins-Traub algorithm, described by Numerical Recipes under "Other sure-fire techniques" as "practically a standard in black-box polynomial rootfinders". (See M.A. Jenkins, ACM TOMS 1 (1975) pp. 178-189.).
This class is not very const-correct as it is intended as a compute object rather than a data object.
Constructor & Destructor Documentation
VNL::RPolyRoots::RPolyRoots (const VNL::Vector< double > & a)
The constructor calculates the roots.
This is the most efficient interface as all the result variables are initialized to the correct size. The polynomial is .
Note that if the routine fails, not all roots will be found. In this case, the "realroots" and "roots" functions will return fewer than n roots.
References VNL::Vector< T >::assert_finite(), and Compute().
VNL::RPolyRoots::RPolyRoots (const RealPolynomial & poly)
Calculate roots of a vnl_real_polynomial. Same comments apply.
References VNL::Vector< T >::assert_finite(), VNL::RealPolynomial::Coefficients(), and Compute().
Member Function Documentation
bool VNL::RPolyRoots::Compute ()
Compute roots using Jenkins-Traub algorithm.
Calls rpoly and interprets failure codes.
References coeffs_, VNL::Vector< T >::DataBlock(), i_, num_roots_found_, r_, rpoly_(), and VNL::Vector< T >::size().
Referenced by RPolyRoots().
bool VNL::RPolyRoots::ComputeLaguerre ()
Compute roots using Laguerre algorithm. [unimplemented].
bool VNL::RPolyRoots::ComputeQR ()
Compute roots using QR decomposition of companion matrix. [unimplemented].
VNL::Vector<double>& VNL::RPolyRoots::Imag () [inline]
Vector of imaginary parts of roots.
References i_.
const double& VNL::RPolyRoots::Imag (int i) const [inline]
Imaginary part of root I.
References i_.
Referenced by VW::ThreePointPose::ComputeFischlerBolles().
std::complex<double> VNL::RPolyRoots::operator[] (int i) const [inline]
Return i'th complex root.
References i_, and r_.
VNL::Vector<double>& VNL::RPolyRoots::Real () [inline]
Vector of real parts of roots.
References r_.
const double& VNL::RPolyRoots::Real (int i) const [inline]
Real part of root I.
References r_.
Referenced by VW::ThreePointPose::ComputeFischlerBolles().
VNL::Vector< double > VNL::RPolyRoots::RealRoots (double tol = 1e-12) const
Return real roots only.
Roots are real if the absolute value of their imaginary part is less than the optional argument TOL. TOL defaults to 1e-12 [untested]
References c, i_, num_roots_found_, and r_.
Referenced by VW::ThreePointPose::ComputeFinsterwalder().
VNL::Vector< std::complex< double > > VNL::RPolyRoots::Roots () const
Complex vector of all roots.
References i_, num_roots_found_, and r_.
Member Data Documentation
VNL::Vector<double> VNL::RPolyRoots::coeffs_ [protected]
Referenced by Compute().
VNL::Vector<double> VNL::RPolyRoots::i_ [protected]
Referenced by Compute(), Imag(), operator[](), RealRoots(), and Roots().
int VNL::RPolyRoots::num_roots_found_ [protected]
Referenced by Compute(), RealRoots(), and Roots().
VNL::Vector<double> VNL::RPolyRoots::r_ [protected]
Referenced by Compute(), operator[](), Real(), RealRoots(), and Roots().
The documentation for this class was generated from the following files:
rpolyroots.h
rpolyroots.cpp