VW: VW::ThreeDToolGluteWidget Class Reference
VW::ThreeDToolGluteWidget Class Reference
[GLTools]
A version of the ThreeDTool which can be embedded in a glute GUI.
#include <threedtoolglutewidget.h>
Public Member Functions
ThreeDToolGluteWidget (const unsigned int camera_width, const unsigned int camera_height, const std::string title="")
unsigned int WindowWidth () const
unsigned int WindowHeight () const
void SwapBuffers ()
void MakeCurrent ()
void RequestDraw ()
bool IsMe (int display_id) const
Is the GL display id given mine?
void SetSize (const unsigned int newwidth, const unsigned int newheight)
bool Dragging ()
void SetID (int id)
int GetID () const
void SetPosition (unsigned int x, unsigned int y)
unsigned int GetMinimumWidth () const
unsigned int GetMinimumHeight () const
bool WantsToGrowX () const
bool WantsToGrowY () const
virtual void SetParentWindow (Glute2::Window *parent_window)
bool IsYInverted () const
Setting up the view
void SetCameraSize (unsigned int width, unsigned int size)
Set the size of the camera.
unsigned int CameraWidth ()
What is the width of the virtual camera? (Note this is not the same as the window width).
unsigned int CameraHeight ()
What is the height of the virtual camera? (Note this is not the same as the window height).
void SetCameraPositionOrientation (const Vector3D &new_position, const Quaternion &new_orientation)
Set camera position.
void GetCameraPositionOrientation (Vector3D &current_position, Quaternion &current_orientation)
void LookAt (const Point3D &some_point)
Make the camera look at a position.
void SetCameraParameters (const double fku, const double fkv, const double u0, const double v0)
Set the parameters of the perspective projection used by the display.
void SetCameraParameters (const VW::CalibrationMatrix &normK)
Set the parameters of the perspective projection used by the display.
void SetOrthographicCameraParameters (const double xWidth, const double yWidth, const double u0, const double v0)
Set the parameters of the orthographic projection used by the display.
void PushCameraSettings ()
Push the current camera position and calibration onto the stack.
void PopCameraSettings ()
Pop the previous camera position and calibration from the stack, added by a previous PushCameraSettings.
Shortcuts for some basic GL properties
void SetPenColour (const unsigned char red, const unsigned char green, const unsigned char blue, const unsigned char alpha)
Set pen colour (characters for R, G, B, alpha).
void GetPenColour (unsigned char &red, unsigned char &green, unsigned char &blue, unsigned char &alpha)
void SetBackgroundColour (const unsigned char red, const unsigned char green, const unsigned char blue, const unsigned char alpha)
Set background colour (characters for R, G, B, alpha).
void EnableLighting ()
Shortcut for enabling lighting effects.
void DisableLighting ()
Shortcut for disabling lighting effects.
void SetMaterial (const GLMaterialType material)
Shortcut for setting material properties and colours to match a pre-defined type.
void SetAntialiasing (bool on)
Moving around the world
void TranslateDrawingPosition (const Vector3D &r)
Translate the current drawing position (NB: can also use a vnl_vector).
void RotateDrawingPosition (const Quaternion &q)
Rotate the current drawing position (NB: can also use a vnl_quaternion).
void RotateDrawingPosition (const RotationMatrix &R)
Rotate the current drawing position.
void PushDrawingPosition ()
Push the current drawing position onto the stack.
void PopDrawingPosition ()
Pop the previous drawing position from the stack, added by a previous PushDrawingPosition.
void Set2DDrawingPosition (const double u, const double v)
Move to a drawing position so that GL calls can be made to draw 2D stuff in camera coordinates (mostly used internally).
Drawing functions
void DrawAxes (bool number_axes=true)
Draw XYZ coordinate axes.
void DrawPoint (const Vector3D &r0)
void DrawPoint (const Vector3D &r0, const int name)
void DrawLine (const Vector3D &r0, const Vector3D &r1)
void DrawLine (const Vector3D &r0, const Vector3D &r1, const int name)
void DrawTriangle (const Vector3D &p1, const Vector3D &p2, const Vector3D &p3) const
Draw a triangle.
void DrawTriangle (const Vector3D &p1, const Vector3D &p2, const Vector3D &p3, int name) const
Version of DrawTriangle() (see above) supporting object selection.
void DrawRectangle (const Vector3D &rW, const Quaternion &qWO, const double rectangle_width, const double rectangle_height)
Draw a rectangle.
void DrawRectangle (const Vector3D &rW, const Quaternion &qWO, const double rectangle_width, const double rectangle_height, const int name)
Version of DrawRectangle() (see above) supporting object selection.
void DrawTexturedRectangle (const Vector3D &rW, const Quaternion &qWO, const double rectangle_width, const double rectangle_height, const VW::ImageMono< unsigned char > &imageref)
void DrawTexturedRectangle (const Vector3D &rW, const Quaternion &qWO, const double rectangle_width, const double rectangle_height, const VW::ImageMono< unsigned char > &imageref, const int name)
void DrawWarpedTexturedRectangle (const Vector3D &rW, const Quaternion &qWO, double corner00[2], double corner01[2], double corner10[2], double corner11[2], const VW::ImageMono< unsigned char > &imageref, const int name)
void DrawCinemaScreen (const double zC, const VW::ImageMono< unsigned char > &imageref)
Draw a cinema screen image: texture at correct position, depth zC to fill the virtual camera image.
void DrawCinemaScreen (const double zC, const VW::ImageMono< unsigned char > &imageref, double kappa, const VW::Point2D &distortion_centre)
Draw a cinema screen image: texture at correct position, depth zC to fill the virtual camera image.
void DrawSphere (const double R)
void DrawSphere (const Vector3D &r0, const double R)
void DrawSphere (const Vector3D &r0, const double R, const int name)
void DrawCone (const double bottomradius, const double topradius, const double height)
Cone at current location.
void DrawDisc (const double innerradius, const double outerradius)
Disc (well, more a ring really) at current location.
void DrawCylinder (const double radius, const double height, const bool drawends=false)
Cylinder at current location.
void DrawCylinder (const Vector3D &base_centre, const Quaternion &orientation, const double radius, const double height, const bool drawends=false)
Cylinder.
void DrawCylinder (const Vector3D &base_centre, const Quaternion &orientation, const double radius, const double height, const int name, const bool drawends=false)
void DrawCovariance (const Vector3D &r0, const VNL::MatrixFixed< 3, 3, double > &P, double number_of_sigma)
void DrawCovariance (const Vector3D &r0, const VNL::MatrixFixed< 3, 3, double > &P, const double number_of_sigma, const int name)
void DrawCameraGraphic (const Vector3D &rW, const Quaternion &qWO, const double width)
void DrawCameraGraphic (const Vector3D &rW, const Quaternion &qWO, const double width, const int name)
void Draw2DBegin (double u=0.0, double v=0.0)
Set up the window for drawing in 2D using standard Gl commands.
void Draw2DEnd ()
Signal the end of a block started with Draw2DBegin().
void Draw2DLine (const VW::Vector2D &p1, const VW::Vector2D p2)
Draw a 2D line between two image co-ordinates.
void Draw2DLine (const double u1, const double v1, const double u2, const double v2)
Draw a 2D line between two image co-ordinates.
void Draw2DLine (const VW::Vector2D &p1, const VW::Vector2D p2, int name)
Draw a 2D line between two image co-ordinates, with a name for selection.
void Draw2DLine (const double u1, const double v1, const double u2, const double v2, const int name)
Draw a 2D line between two image co-ordinates, with a name for selection.
void Draw2DArrow (const double u1, const double v1, double size1, const double u2, const double v2, double size2, int name)
Draw a 2D line between two image co-ordinates with an arrow at each end, and a name for selection.
void Draw2DArrow (const double u1, const double v1, double size1, const double u2, const double v2, double size2)
Draw a 2D line between two image co-ordinates with an arrow at each end.
void Draw2DArrow (const VW::Vector2D &p1, double size1, const VW::Vector2D &p2, double size2)
Draw a 2D line between two image co-ordinates with an arrow at each end.
void Draw2DArrow (const VW::Vector2D &p1, double size1, const VW::Vector2D &p2, double size2, int name)
Draw a 2D line between two image co-ordinates with an arrow at each end, and a name for selection.
void Draw2DDashedLine (const double u1, const double v1, const double u2, const double v2, const double ndashes, const double dash_gap_size_ratio)
Draw a dashed line between the specified positions.
void Draw2DDashedLine (const double u1, const double v1, const double u2, const double v2, const double ndashes, const double dash_gap_size_ratio, const int name)
Draw a dashed line between the specified positions, selection version.
void Draw2DRectangle (const double u, const double v, const double width, const double height)
void Draw2DRectangle (const double u, const double v, const double width, const double height, const int name)
void Draw2DTexturedRectangle (const double u, const double v, const double width, const double height, const VW::ImageMono< unsigned char > &imageref)
void Draw2DTexturedRectangle (const double u, const double v, const double width, const double height, const VW::ImageMono< unsigned char > &imageref, const int name)
void Draw2DCircle (const double u, const double v, const double inner_radius, const double outer_radius)
Draw circle.
void Draw2DCircle (const double u, const double v, const double inner_radius, const double outer_radius, const int name)
Draw circle (selection version).
void Draw2DCovariance (const double u, const double v, const VNL::MatrixFixed< 2, 2, double > &P, const double number_of_sigma, const double ring_thickness)
Draw covariance.
void Draw2DCovariance (const double u, const double v, const VNL::MatrixFixed< 2, 2, double > &P, const double number_of_sigma, const double ring_thickness, const int name)
Draw covariance (selection version).
void Draw2DText (const double u, const double v, const std::string &string)
Print a string at a given image location.
void DrawRotationCentre ()
Plot rotation centre.
Other bits n bobs
void IncludeInRotationCentre (const Vector3D &r)
Include a point in the rotation centre calculation.
void DoDrawing ()
Cause a redraw event immediately.
void Clear ()
Clears screen (this is done automatically when Draw() is called).
void GetImage (VW::ImageMono< unsigned char > &image)
Capture the current view as an image.
void GetImage (VW::ImageRGB< unsigned char > &image)
Capture the current view as an image.
Public Attributes
VWEvents::Event1< void, bool > DrawEvent
The display needs redrawing.
VWEvents::Event3< void, int,
double, double > ProcessHitsEvent
Static Public Attributes
static const double DEFAULT_WIDTH_OVER_FKU = 0.75
This constant sets default projection zoom: normally choose your own with SetCameraParameters().
static const unsigned int DEFAULT_CAMERA_WIDTH = 640
Sets the camera width used in the default constructor.
static const unsigned int DEFAULT_CAMERA_HEIGHT = 480
Sets the camera height used in the default constructor.
Protected Member Functions
void Resize (int newwidth, int newheight)
void Motion (int newx, int newy)
void Mouse (int button, int state, int x, int y)
void Draw ()
void PassiveMotion (int newx, int newy)
void Keyboard (unsigned char key, int x, int y)
void Dragged (const int x0, const int y0, const int x1, const int y1, const int button)
Mouse drag.
void DragRelease ()
Mouse drag has finished.
void Clicked (const int x0, const int y0, const int button)
Mouse button has been clicked.
virtual void _CallDrawEvent (bool b)
Call the user draw callback.
virtual void _CallProcessHitsEvent (int item, double x, double y)
Call the user ProcessHits callback.
double ProjectOntoSphere (double px, double py)
Quaternion TrackBall (const double p1x, const double p1y, const double p2x, const double p2y)
void InitGL ()
void DrawNumberHere (double const number)
void ActuallyDrawTexturedRectangle (const Vector3D rW, const Quaternion qWO, const double rectangle_width, const double rectangle_height, const VW::ImageMono< unsigned char > &imageref)
void ActuallyDrawWarpedTexturedRectangle (const Vector3D rW, const Quaternion qWO, double corner00[2], double corner01[2], double corner10[2], double corner11[2], const VW::ImageMono< unsigned char > &imageref)
void ActuallyDrawDistortedTexturedRectangle (const Vector3D rW, const Quaternion qWO, const double rectangle_width, const double rectangle_height, const VW::ImageMono< unsigned char > &imageref, double kappa, const VW::Point2D &distortion_centre)
int _CreateWindow (unsigned int width, unsigned int height, const std::string &title)
int _CreateSubwindow (int parent_window_id, unsigned int x, unsigned int y, unsigned int width, unsigned int height)
void _MakeCurrent () const
virtual bool _IsIn (int x, int y)
Is this coordinate inside this widget's sensitive area.
void _SetFocus (bool state)
bool _NeedsRedraw () const
virtual void _MousePressed (int x, int y, int button)
virtual void _MouseReleased (int startx, int starty, int endx, int endy, int button)
virtual void _PassiveMotion (int x, int y)
virtual void _Drag (int startx, int starty, int endx, int endy, int button)
virtual void _KeyPress (int x, int y, unsigned char key)
Protected Attributes
bool _initialised
int last_x
int last_y
int current_button
bool dragging
bool orthographic_projection_flag
GLint texture_interpolation
unsigned int camera_width
unsigned int camera_height
bool currently_drawing_in_selection_mode_flag
int click_x0
int click_y0
bool gl_initialised
RotationCentre * rotation_centre
double fku
double fkv
double u0
double v0
double xL
double xR
double yB
double yT
double xW
double xM
double yH
double yM
GLUquadricObj * sphereptr
GLUquadricObj * cylinderptr
GLUquadricObj * circleptr
DrawingPosition current_drawing_position
std::vector< DrawingPosition > drawing_position_stack
Vector3D camera_position
Quaternion camera_orientation
GLuint texName
unsigned int texWidth
unsigned int texHeight
double _R_background
double _G_background
double _B_background
double _alpha_background
int _x
int _y
int _w
int _h
int _sx
int _sy
int _sw
int _sh
bool _focus
bool _needs_redraw
Glute2::Window * _parent_window
bool _wants_to_grow_x
bool _wants_to_grow_y
unsigned int _minsize_x
unsigned int _minsize_y
Static Protected Attributes
static const double zN = 0.01
static const double zF = 100000
static const double move_clipping_plane_factor = 0.999999
static const double TRACKBALLSIZE = 0.8
Detailed Description
A version of the ThreeDTool which can be embedded in a glute GUI.
Author:
BJ Tordoff
Date:
03/12/2003 ***Please insert long descrition here...
Constructor & Destructor Documentation
ThreeDToolGluteWidget::ThreeDToolGluteWidget (const unsigned int camera_width, const unsigned int camera_height, const std::string title = "")
References Glute2::Widget::_h, Glute2::Widget::_minsize_x, Glute2::Widget::_minsize_y, Glute2::Widget::_w, Glute2::Widget::_wants_to_grow_x, and Glute2::Widget::_wants_to_grow_y.
Member Function Documentation
void ThreeDToolGLCommon::_CallDrawEvent (bool b) [protected, virtual, inherited]
Call the user draw callback.
This is virtual so that child classes (such as ThreeDToolGTKGLWidget) can overload it to also call using SigC etc.
Reimplemented in VW::ThreeDToolGTKGLWidget, and VW::ThreeDToolWxGLWidget.
References VW::ThreeDToolGLCommon::DrawEvent.
Referenced by VW::ThreeDToolGLCommon::DoDrawing().
void ThreeDToolGLCommon::_CallProcessHitsEvent (int item, double x, double y) [protected, virtual, inherited]
Call the user ProcessHits callback.
This is virtual so that child classes (such as ThreeDToolGTKGLWidget) can overload it to also call using SigC etc.
Reimplemented in VW::ThreeDToolGTKGLWidget, and VW::ThreeDToolWxGLWidget.
References VW::ThreeDToolGLCommon::ProcessHitsEvent.
Referenced by VW::ThreeDToolGLCommon::Clicked().
int VW::GLUTWindow::_CreateSubwindow (int parent_window_id, unsigned int x, unsigned int y, unsigned int width, unsigned int height) [protected, inherited]
References GLUTAddWindow(), and GLUTRegisterCallbacks().
Referenced by SetSize(), and VW::DisplayGluteWidget::SetSize().
int VW::GLUTWindow::_CreateWindow (unsigned int width, unsigned int height, const std::string & title) [protected, inherited]
References GLUTAddWindow(), GLUTRegisterCallbacks(), and VERBOSE.
Referenced by VW::DisplayGLUT::SetSize(), VW::ThreeDToolGLUT::ThreeDToolGLUT(), and Glute2::Window::Window().
virtual void Glute2::Widget::_Drag (int startx, int starty, int endx, int endy, int button) [inline, protected, virtual, inherited]
Reimplemented in Glute2::Container, and Glute2::Slider.
Referenced by Glute2::Window::Motion().
bool Glute2::Widget::_IsIn (int x, int y) [protected, virtual, inherited]
Is this coordinate inside this widget's sensitive area.
References Glute2::Widget::_sh, Glute2::Widget::_sw, Glute2::Widget::_sx, Glute2::Widget::_sy, Glute2::Widget::_x, and Glute2::Widget::_y.
Referenced by Glute2::Container::_PassiveMotion(), and Glute2::Window::PassiveMotion().
virtual void Glute2::Widget::_KeyPress (int x, int y, unsigned char key) [inline, protected, virtual, inherited]
Reimplemented in Glute2::Container.
Referenced by Glute2::Window::Keyboard().
void VW::GLUTWindow::_MakeCurrent () const [inline, protected, inherited]
Referenced by Glute2::Window::MakeCurrent(), VW::DisplayGluteWidget::MakeCurrent(), VW::DisplayGluteWidget::Resize(), VW::DisplayGluteWidget::SetSize(), and VW::DisplayGluteWidget::SwapBuffers().
virtual void Glute2::Widget::_MousePressed (int x, int y, int button) [inline, protected, virtual, inherited]
Reimplemented in Glute2::Button, Glute2::CheckBox, Glute2::Container, and Glute2::Slider.
Referenced by Glute2::Window::Mouse().
virtual void Glute2::Widget::_MouseReleased (int startx, int starty, int endx, int endy, int button) [inline, protected, virtual, inherited]
Reimplemented in Glute2::Button, Glute2::CheckBox, Glute2::Container, and Glute2::Slider.
Referenced by Glute2::Window::Mouse().
bool Glute2::Widget::_NeedsRedraw () const [inline, protected, inherited]
References Glute2::Widget::_needs_redraw.
Referenced by Glute2::Window::Motion(), Glute2::Window::Mouse(), and Glute2::Window::PassiveMotion().
virtual void Glute2::Widget::_PassiveMotion (int x, int y) [inline, protected, virtual, inherited]
Reimplemented in Glute2::Container.
Referenced by Glute2::Window::PassiveMotion().
void Glute2::Widget::_SetFocus (bool state) [inline, protected, inherited]
References Glute2::Widget::_focus, and Glute2::Widget::_needs_redraw.
Referenced by Glute2::Window::PassiveMotion().
void ThreeDToolGLCommon::ActuallyDrawDistortedTexturedRectangle (const Vector3D rW, const Quaternion qWO, const double rectangle_width, const double rectangle_height, const VW::ImageMono< unsigned char > & imageref, double kappa, const VW::Point2D & distortion_centre) [protected, inherited]
References VW::Quaternion::Angle(), VW::Quaternion::Axis(), c, VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetRawBuffer(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), VW::Point2D::GetX(), VW::Point3D::GetX(), VW::Point2D::GetY(), VW::Point3D::GetY(), VW::Point3D::GetZ(), M_PI, VW::Point2D::Set(), VW::ThreeDToolGLCommon::texHeight, VW::ThreeDToolGLCommon::texName, VW::ThreeDToolGLCommon::texture_interpolation, VW::ThreeDToolGLCommon::texWidth, VW::RadialDistortion::UndistortPoint(), and VERBOSE.
Referenced by VW::ThreeDToolGLCommon::DrawCinemaScreen().
void ThreeDToolGLCommon::ActuallyDrawTexturedRectangle (const Vector3D rW, const Quaternion qWO, const double rectangle_width, const double rectangle_height, const VW::ImageMono< unsigned char > & imageref) [protected, inherited]
References VW::Quaternion::Angle(), VW::Quaternion::Axis(), VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetRawBuffer(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), M_PI, VW::ThreeDToolGLCommon::texHeight, VW::ThreeDToolGLCommon::texName, VW::ThreeDToolGLCommon::texture_interpolation, VW::ThreeDToolGLCommon::texWidth, and VERBOSE.
Referenced by VW::ThreeDToolGLCommon::DrawCinemaScreen(), and VW::ThreeDToolGLCommon::DrawTexturedRectangle().
void ThreeDToolGLCommon::ActuallyDrawWarpedTexturedRectangle (const Vector3D rW, const Quaternion qWO, double corner00[2], double corner01[2], double corner10[2], double corner11[2], const VW::ImageMono< unsigned char > & imageref) [protected, inherited]
References VW::Quaternion::Angle(), VW::Quaternion::Axis(), VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetRawBuffer(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), M_PI, VW::ThreeDToolGLCommon::texHeight, VW::ThreeDToolGLCommon::texName, VW::ThreeDToolGLCommon::texture_interpolation, VW::ThreeDToolGLCommon::texWidth, and VERBOSE.
Referenced by VW::ThreeDToolGLCommon::DrawWarpedTexturedRectangle().
unsigned int VW::ThreeDToolGLCommon::CameraHeight () [inline, inherited]
What is the height of the virtual camera? (Note this is not the same as the window height).
Referenced by VW::ThreeDToolQGLWidget::ThreeDToolQGLWidget().
unsigned int VW::ThreeDToolGLCommon::CameraWidth () [inline, inherited]
What is the width of the virtual camera? (Note this is not the same as the window width).
Referenced by VW::ThreeDToolQGLWidget::ThreeDToolQGLWidget().
void ThreeDToolGLCommon::Clear () [inherited]
Clears screen (this is done automatically when Draw() is called).
void ThreeDToolGLCommon::Clicked (const int x0, const int y0, const int button) [protected, inherited]
Mouse button has been clicked.
This should be called by specific GUI classes inherited from this one when a mouse click occurs.
References VW::ThreeDToolGLCommon::_CallProcessHitsEvent(), VW::Quaternion::Angle(), VW::Quaternion::Axis(), VW::ThreeDToolGLCommon::camera_height, VW::ThreeDToolGLCommon::camera_orientation, VW::ThreeDToolGLCommon::camera_position, VW::ThreeDToolGLCommon::camera_width, VW::ThreeDToolGLCommon::click_x0, VW::ThreeDToolGLCommon::click_y0, VW::ThreeDToolGLCommon::current_drawing_position, VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, VW::ThreeDToolGLCommon::DrawEvent, VW::ThreeDToolGLCommon::drawing_position_stack, VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), VW::Quaternion::Inverse(), M_PI, VW::ThreeDToolGLCommon::move_clipping_plane_factor, VW::ThreeDToolGLCommon::orthographic_projection_flag, VW::RotationCentre::Reset(), VW::ThreeDToolGLCommon::rotation_centre, VW::Quaternion::RotationMatrix(), VERBOSE, VW::ThreeDToolGLCommon::WindowHeight(), VW::ThreeDToolGLCommon::WindowWidth(), VW::ThreeDToolGLCommon::xL, VW::ThreeDToolGLCommon::xR, VW::ThreeDToolGLCommon::yB, VW::ThreeDToolGLCommon::yT, VW::DrawingPosition::Zero(), VW::ThreeDToolGLCommon::zF, and VW::ThreeDToolGLCommon::zN.
Referenced by VW::LocalGTKGLArea::button_release_event_impl(), Mouse(), VW::ThreeDToolGLUT::Mouse(), VW::ThreeDToolQGLWidget::mouseReleaseEvent(), VW::ThreeDToolWxGLWidget::OnMouseUp(), and VW::ThreeDToolGlowWidget::OnMouseUp().
void VW::ThreeDToolGLCommon::DisableLighting () [inline, inherited]
Shortcut for disabling lighting effects.
void ThreeDToolGLCommon::DoDrawing () [inherited]
Cause a redraw event immediately.
This is generally a bad idea, and one should use RequestDraw() instead, which causes a redraw event at the next good opportunity.
References VW::ThreeDToolGLCommon::_alpha_background, VW::ThreeDToolGLCommon::_B_background, VW::ThreeDToolGLCommon::_CallDrawEvent(), VW::ThreeDToolGLCommon::_G_background, VW::ThreeDToolGLCommon::_R_background, VW::Quaternion::Angle(), VW::Quaternion::Axis(), VW::ThreeDToolGLCommon::camera_height, VW::ThreeDToolGLCommon::camera_orientation, VW::ThreeDToolGLCommon::camera_position, VW::ThreeDToolGLCommon::camera_width, VW::ThreeDToolGLCommon::current_drawing_position, VW::ThreeDToolGLCommon::dragging, VW::ThreeDToolGLCommon::drawing_position_stack, VW::ThreeDToolGLCommon::DrawRotationCentre(), VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), VW::ThreeDToolGLCommon::gl_initialised, VW::ThreeDToolGLCommon::InitGL(), VW::Quaternion::Inverse(), M_PI, VW::ThreeDToolGLCommon::MakeCurrent(), VW::ThreeDToolGLCommon::move_clipping_plane_factor, VW::ThreeDToolGLCommon::orthographic_projection_flag, VW::RotationCentre::Reset(), VW::ThreeDToolGLCommon::rotation_centre, VW::Quaternion::RotationMatrix(), VW::ThreeDToolGLCommon::SetPenColour(), VW::ThreeDToolGLCommon::SwapBuffers(), VERBOSE, VW::ThreeDToolGLCommon::WindowHeight(), VW::ThreeDToolGLCommon::WindowWidth(), VW::ThreeDToolGLCommon::xL, VW::ThreeDToolGLCommon::xR, VW::ThreeDToolGLCommon::yB, VW::ThreeDToolGLCommon::yT, VW::DrawingPosition::Zero(), VW::ThreeDToolGLCommon::zF, and VW::ThreeDToolGLCommon::zN.
Referenced by Draw(), VW::ThreeDToolGLUT::Draw(), VW::LocalGTKGLArea::draw_impl(), VW::ThreeDToolGlowWidget::OnBeginPaint(), VW::ThreeDToolWxGLWidget::OnPaint(), and VW::ThreeDToolQGLWidget::paintGL().
void ThreeDToolGLCommon::Dragged (const int x0, const int y0, const int x1, const int y1, const int button) [protected, inherited]
Mouse drag.
This should be called by specific GUI classes inherited from this one when the mouse is dragged.
Parameters:
x0 The previous x position of the mouse
y0 The previous y position of the mouse
x1 The current x position of the mouse
y1 The current y position of the mouse
button The button held down (left=1, middle=2, right=3)
References VW::ThreeDToolGLCommon::camera_height, VW::ThreeDToolGLCommon::camera_orientation, VW::ThreeDToolGLCommon::camera_position, VW::ThreeDToolGLCommon::camera_width, VW::RotationCentre::Centre(), VW::ThreeDToolGLCommon::dragging, VW::ThreeDToolGLCommon::fku, VW::ThreeDToolGLCommon::fkv, VW::Point3D::GetZ(), VW::Quaternion::Inverse(), VW::ThreeDToolGLCommon::orthographic_projection_flag, VW::ThreeDToolGLCommon::RequestDraw(), VW::ThreeDToolGLCommon::rotation_centre, VW::Quaternion::RotationMatrix(), VW::ThreeDToolGLCommon::SetOrthographicCameraParameters(), VW::ThreeDToolGLCommon::TrackBall(), VW::ThreeDToolGLCommon::u0, VW::ThreeDToolGLCommon::v0, VERBOSE, VW::ThreeDToolGLCommon::WindowHeight(), VW::ThreeDToolGLCommon::WindowWidth(), VW::ThreeDToolGLCommon::xW, and VW::ThreeDToolGLCommon::yH.
Referenced by Motion(), VW::ThreeDToolGLUT::Motion(), VW::LocalGTKGLArea::motion_notify_event_impl(), VW::ThreeDToolQGLWidget::mouseMoveEvent(), VW::ThreeDToolGlowWidget::OnMouseDrag(), and VW::ThreeDToolWxGLWidget::OnMouseMove().
bool VW::ThreeDToolGLCommon::Dragging () [inline, inherited]
References VW::ThreeDToolGLCommon::dragging.
Referenced by VW::LocalGTKGLArea::button_release_event_impl(), Mouse(), VW::ThreeDToolGLUT::Mouse(), and VW::ThreeDToolQGLWidget::mouseReleaseEvent().
void ThreeDToolGLCommon::DragRelease () [protected, inherited]
Mouse drag has finished.
This should be called by specific GUI classes inherited from this one when the mouse drag is released.
References VW::ThreeDToolGLCommon::dragging, and VW::ThreeDToolGLCommon::RequestDraw().
Referenced by VW::LocalGTKGLArea::button_release_event_impl(), Mouse(), VW::ThreeDToolGLUT::Mouse(), VW::ThreeDToolQGLWidget::mouseReleaseEvent(), VW::ThreeDToolWxGLWidget::OnMouseUp(), and VW::ThreeDToolGlowWidget::OnMouseUp().
void VW::ThreeDToolGluteWidget::Draw () [inline, protected, virtual]
Implements VW::GLUTWindow.
References VW::ThreeDToolGLCommon::DoDrawing().
void VW::ThreeDToolGLCommon::Draw2DArrow (const VW::Vector2D & p1, double size1, const VW::Vector2D & p2, double size2, int name) [inline, inherited]
Draw a 2D line between two image co-ordinates with an arrow at each end, and a name for selection.
The sizees are the lengths of the two arrows, in pixels (10.0 is a good size; use 0.0 for no arrow). This version takes two vectors, an alternative version takes four doubles.
References VW::ThreeDToolGLCommon::Draw2DArrow().
void VW::ThreeDToolGLCommon::Draw2DArrow (const VW::Vector2D & p1, double size1, const VW::Vector2D & p2, double size2) [inline, inherited]
Draw a 2D line between two image co-ordinates with an arrow at each end.
The sizees are the lengths of the two arrows, in pixels (10.0 is a good size; use 0.0 for no arrow). This version takes two vectors, an alternative version takes four doubles.
References VW::ThreeDToolGLCommon::Draw2DArrow().
void ThreeDToolGLCommon::Draw2DArrow (const double u1, const double v1, double size1, const double u2, const double v2, double size2) [inherited]
Draw a 2D line between two image co-ordinates with an arrow at each end.
The sizees are the lengths of the two arrows, in pixels (10.0 is a good size; use 0.0 for no arrow). This version takes four doubles; an alternative version takes two Vector2Ds.
References VW::ThreeDToolGLCommon::Draw2DBegin(), VW::ThreeDToolGLCommon::Draw2DEnd(), and VNL::VectorFixedRef< n, T >::Normalize().
void ThreeDToolGLCommon::Draw2DArrow (const double u1, const double v1, double size1, const double u2, const double v2, double size2, int name) [inherited]
Draw a 2D line between two image co-ordinates with an arrow at each end, and a name for selection.
The sizees are the lengths of the two arrows, in pixels (10.0 is a good size; use 0.0 for no arrow). This version takes four doubles; an alternative version takes two Vector2Ds.
References VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag.
Referenced by VW::ThreeDToolGLCommon::Draw2DArrow().
void ThreeDToolGLCommon::Draw2DBegin (double u = 0.0, double v = 0.0) [inherited]
Set up the window for drawing in 2D using standard Gl commands.
This function disables lighting and shading, saves the matrices, and calls Set2DDrawingPosition() to set up the correct projection and clipping to draw in 2D in a 3D control. This function call should be followed by glBegin(), some GL commands, then glEnd() and finished with Draw2DEnd().
Parameters:
u The x-co-ordinate of the drawing origin (in image co-ordinates)
v The y-co-ordinate of the drawing origin (in image co-ordinates)
References VW::ThreeDToolGLCommon::Set2DDrawingPosition().
Referenced by VW::ThreeDToolGLCommon::Draw2DArrow(), VW::ThreeDToolGLCommon::Draw2DCircle(), VW::ThreeDToolGLCommon::Draw2DCovariance(), VW::ThreeDToolGLCommon::Draw2DDashedLine(), VW::ThreeDToolGLCommon::Draw2DLine(), and VW::ThreeDToolGLCommon::Draw2DRectangle().
void ThreeDToolGLCommon::Draw2DCircle (const double u, const double v, const double inner_radius, const double outer_radius, const int name) [inherited]
Draw circle (selection version).
This actually draws a ring; set inner_radius to 0 for filled disk.
References VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, and VW::ThreeDToolGLCommon::Draw2DCircle().
void ThreeDToolGLCommon::Draw2DCircle (const double u, const double v, const double inner_radius, const double outer_radius) [inherited]
Draw circle.
This actually draws a ring; set inner_radius to 0 for filled disk.
References VW::ThreeDToolGLCommon::circleptr, VW::ThreeDToolGLCommon::Draw2DBegin(), and VW::ThreeDToolGLCommon::Draw2DEnd().
Referenced by VW::ThreeDToolGLCommon::Draw2DCircle().
void ThreeDToolGLCommon::Draw2DCovariance (const double u, const double v, const VNL::MatrixFixed< 2, 2, double > & P, const double number_of_sigma, const double ring_thickness, const int name) [inherited]
Draw covariance (selection version).
This draws a 2D covariance ellipse; u, v centre P covariance matrix. All values in camera pixel coordinates ring_thickness is how thick to draw it (in pixels).
References VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, and VW::ThreeDToolGLCommon::Draw2DCovariance().
void ThreeDToolGLCommon::Draw2DCovariance (const double u, const double v, const VNL::MatrixFixed< 2, 2, double > & P, const double number_of_sigma, const double ring_thickness) [inherited]
Draw covariance.
This draws a 2D covariance ellipse; u, v centre P covariance matrix. All values in camera pixel coordinates ring_thickness is how thick to draw it (in pixels).
References VW::ThreeDToolGLCommon::circleptr, VW::ThreeDToolGLCommon::Draw2DBegin(), VW::ThreeDToolGLCommon::Draw2DEnd(), VNL::SymmetricEigensystem< T >::GetEigenvalue(), std::sqrt(), VNL::SymmetricEigensystem< T >::V, and VERBOSE.
Referenced by VW::ThreeDToolGLCommon::Draw2DCovariance().
void ThreeDToolGLCommon::Draw2DDashedLine (const double u1, const double v1, const double u2, const double v2, const double ndashes, const double dash_gap_size_ratio, const int name) [inherited]
Draw a dashed line between the specified positions, selection version.
References VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, and VW::ThreeDToolGLCommon::Draw2DDashedLine().
void ThreeDToolGLCommon::Draw2DDashedLine (const double u1, const double v1, const double u2, const double v2, const double ndashes, const double dash_gap_size_ratio) [inherited]
Draw a dashed line between the specified positions.
References VW::ThreeDToolGLCommon::Draw2DBegin(), VW::ThreeDToolGLCommon::Draw2DEnd(), and v.
Referenced by VW::ThreeDToolGLCommon::Draw2DDashedLine().
void ThreeDToolGLCommon::Draw2DEnd () [inherited]
Signal the end of a block started with Draw2DBegin().
Referenced by VW::ThreeDToolGLCommon::Draw2DArrow(), VW::ThreeDToolGLCommon::Draw2DCircle(), VW::ThreeDToolGLCommon::Draw2DCovariance(), VW::ThreeDToolGLCommon::Draw2DDashedLine(), VW::ThreeDToolGLCommon::Draw2DLine(), and VW::ThreeDToolGLCommon::Draw2DRectangle().
void ThreeDToolGLCommon::Draw2DLine (const double u1, const double v1, const double u2, const double v2, const int name) [inherited]
Draw a 2D line between two image co-ordinates, with a name for selection.
This version takes two vectors, an alternative version takes four doubles.
References VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, and VW::ThreeDToolGLCommon::Draw2DLine().
void VW::ThreeDToolGLCommon::Draw2DLine (const VW::Vector2D & p1, const VW::Vector2D p2, int name) [inline, inherited]
Draw a 2D line between two image co-ordinates, with a name for selection.
This version takes four doubles; an alternative version takes two Vector2Ds.
References VW::ThreeDToolGLCommon::Draw2DLine().
void ThreeDToolGLCommon::Draw2DLine (const double u1, const double v1, const double u2, const double v2) [inherited]
Draw a 2D line between two image co-ordinates.
This version takes four doubles; an alternative version takes two Vector2Ds.
References VW::ThreeDToolGLCommon::Draw2DBegin(), and VW::ThreeDToolGLCommon::Draw2DEnd().
void VW::ThreeDToolGLCommon::Draw2DLine (const VW::Vector2D & p1, const VW::Vector2D p2) [inline, inherited]
Draw a 2D line between two image co-ordinates.
This version takes two vectors, an alternative version takes four doubles.
Referenced by VW::ThreeDToolGLCommon::Draw2DLine().
void ThreeDToolGLCommon::Draw2DRectangle (const double u, const double v, const double width, const double height, const int name) [inherited]
References VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, and VW::ThreeDToolGLCommon::Draw2DRectangle().
void ThreeDToolGLCommon::Draw2DRectangle (const double u, const double v, const double width, const double height) [inherited]
References VW::ThreeDToolGLCommon::Draw2DBegin(), and VW::ThreeDToolGLCommon::Draw2DEnd().
Referenced by VW::ThreeDToolGLCommon::Draw2DRectangle().
void ThreeDToolGLCommon::Draw2DText (const double u, const double v, const std::string & string) [inherited]
Print a string at a given image location.
References VW::ThreeDToolGLCommon::Set2DDrawingPosition().
void ThreeDToolGLCommon::Draw2DTexturedRectangle (const double u, const double v, const double width, const double height, const VW::ImageMono< unsigned char > & imageref, const int name) [inherited]
References VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, and VW::ThreeDToolGLCommon::Draw2DTexturedRectangle().
void ThreeDToolGLCommon::Draw2DTexturedRectangle (const double u, const double v, const double width, const double height, const VW::ImageMono< unsigned char > & imageref) [inherited]
References VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ImageBase< PixelType, PixelPtr >::GetRawBuffer(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), VW::ThreeDToolGLCommon::Set2DDrawingPosition(), VW::ThreeDToolGLCommon::texName, VW::ThreeDToolGLCommon::texture_interpolation, and VERBOSE.
Referenced by VW::ThreeDToolGLCommon::Draw2DTexturedRectangle().
void ThreeDToolGLCommon::DrawAxes (bool number_axes = true) [inherited]
Draw XYZ coordinate axes.
Axes are drawn at the world origin with extent calculated from the the rotation centre span.
References VW::RotationCentre::Centre(), VW::ThreeDToolGLCommon::DrawLine(), VW::ThreeDToolGLCommon::DrawNumberHere(), VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), VW::ThreeDToolGLCommon::rotation_centre, VW::Point3D::Set(), VW::RotationCentre::XMax(), VW::RotationCentre::XMin(), VW::RotationCentre::YMax(), VW::RotationCentre::YMin(), VW::RotationCentre::ZMax(), and VW::RotationCentre::ZMin().
void ThreeDToolGLCommon::DrawCameraGraphic (const Vector3D & rW, const Quaternion & qWO, const double width, const int name) [inherited]
References VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, and VW::ThreeDToolGLCommon::DrawCameraGraphic().
void ThreeDToolGLCommon::DrawCameraGraphic (const Vector3D & rW, const Quaternion & qWO, const double width) [inherited]
References VW::Quaternion::Angle(), VW::Quaternion::Axis(), VW::ThreeDToolGLCommon::cylinderptr, VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), VW::RotationCentre::Include(), M_PI, and VW::ThreeDToolGLCommon::rotation_centre.
Referenced by VW::ThreeDToolGLCommon::DrawCameraGraphic().
void ThreeDToolGLCommon::DrawCinemaScreen (const double zC, const VW::ImageMono< unsigned char > & imageref, double kappa, const VW::Point2D & distortion_centre) [inherited]
Draw a cinema screen image: texture at correct position, depth zC to fill the virtual camera image.
The distortion parameter and distortion centre are used to undistort the image as it is texture mapped.
Parameters:
zC the depth at which to place the cinema screen
imageref the image to be drawn
kappa the coefficeint of distortion (pixels^{-2}).
distortion_centre the image location at which the radial distortion is centred.
References VW::ThreeDToolGLCommon::ActuallyDrawDistortedTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawTexturedRectangle(), VW::ThreeDToolGLCommon::camera_height, VW::ThreeDToolGLCommon::camera_orientation, VW::ThreeDToolGLCommon::camera_position, VW::ThreeDToolGLCommon::camera_width, VW::ThreeDToolGLCommon::fku, VW::ThreeDToolGLCommon::fkv, VW::Quaternion::RotationMatrix(), VW::ThreeDToolGLCommon::u0, VW::ThreeDToolGLCommon::v0, and VERBOSE.
void ThreeDToolGLCommon::DrawCinemaScreen (const double zC, const VW::ImageMono< unsigned char > & imageref) [inherited]
Draw a cinema screen image: texture at correct position, depth zC to fill the virtual camera image.
Parameters:
zC the depth at which to place the cinema screen
imageref the image to be drawn
References VW::ThreeDToolGLCommon::ActuallyDrawTexturedRectangle(), VW::ThreeDToolGLCommon::camera_height, VW::ThreeDToolGLCommon::camera_orientation, VW::ThreeDToolGLCommon::camera_position, VW::ThreeDToolGLCommon::camera_width, VW::ThreeDToolGLCommon::fku, VW::ThreeDToolGLCommon::fkv, VW::Quaternion::RotationMatrix(), VW::ThreeDToolGLCommon::u0, VW::ThreeDToolGLCommon::v0, and VERBOSE.
void ThreeDToolGLCommon::DrawCone (const double bottomradius, const double topradius, const double height) [inherited]
Cone at current location.
References VW::ThreeDToolGLCommon::cylinderptr, VW::RotationCentre::IncludeCurrent(), VW::ThreeDToolGLCommon::rotation_centre, and VERBOSE.
Referenced by DrawCamera(), and VW::DrawFireI().
void ThreeDToolGLCommon::DrawCovariance (const Vector3D & r0, const VNL::MatrixFixed< 3, 3, double > & P, const double number_of_sigma, const int name) [inherited]
References VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, and VW::ThreeDToolGLCommon::DrawCovariance().
void ThreeDToolGLCommon::DrawCovariance (const Vector3D & r0, const VNL::MatrixFixed< 3, 3, double > & P, double number_of_sigma) [inherited]
References VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), VW::RotationCentre::Include(), VW::ThreeDToolGLCommon::rotation_centre, VW::ThreeDToolGLCommon::sphereptr, std::sqrt(), and VERBOSE.
Referenced by VW::ThreeDToolGLCommon::DrawCovariance().
void ThreeDToolGLCommon::DrawCylinder (const Vector3D & base_centre, const Quaternion & orientation, const double radius, const double height, const int name, const bool drawends = false) [inherited]
References VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, and VW::ThreeDToolGLCommon::DrawCylinder().
void ThreeDToolGLCommon::DrawCylinder (const Vector3D & base_centre, const Quaternion & orientation, const double radius, const double height, const bool drawends = false) [inherited]
Cylinder.
References VW::Quaternion::Angle(), VW::Quaternion::Axis(), VW::ThreeDToolGLCommon::circleptr, VW::ThreeDToolGLCommon::cylinderptr, VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), VW::RotationCentre::Include(), M_PI, VW::ThreeDToolGLCommon::rotation_centre, and VERBOSE.
void ThreeDToolGLCommon::DrawCylinder (const double radius, const double height, const bool drawends = false) [inherited]
Cylinder at current location.
References VW::ThreeDToolGLCommon::circleptr, VW::ThreeDToolGLCommon::cylinderptr, VW::RotationCentre::IncludeCurrent(), VW::ThreeDToolGLCommon::rotation_centre, and VERBOSE.
Referenced by DrawCamera(), VW::ThreeDToolGLCommon::DrawCylinder(), VW::DrawFireI(), DrawGTIWheel(), DrawMotor(), DrawMotor1Frame(), VW::DrawVL500(), and VW::DrawYorick811().
void ThreeDToolGLCommon::DrawDisc (const double innerradius, const double outerradius) [inherited]
Disc (well, more a ring really) at current location.
References VW::ThreeDToolGLCommon::circleptr, VW::RotationCentre::IncludeCurrent(), VW::ThreeDToolGLCommon::rotation_centre, and VERBOSE.
Referenced by DrawCamera(), DrawGTIWheel(), VW::DrawVL500(), and VW::DrawYorick811().
void ThreeDToolGLCommon::DrawLine (const Vector3D & r0, const Vector3D & r1, const int name) [inherited]
References VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, and VW::ThreeDToolGLCommon::DrawLine().
void ThreeDToolGLCommon::DrawLine (const Vector3D & r0, const Vector3D & r1) [inherited]
References VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), VW::RotationCentre::Include(), and VW::ThreeDToolGLCommon::rotation_centre.
Referenced by VW::ThreeDToolGLCommon::DrawAxes(), and VW::ThreeDToolGLCommon::DrawLine().
void ThreeDToolGLCommon::DrawNumberHere (double const number) [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::DrawAxes().
void ThreeDToolGLCommon::DrawPoint (const Vector3D & r0, const int name) [inherited]
References VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, and VW::ThreeDToolGLCommon::DrawPoint().
void ThreeDToolGLCommon::DrawPoint (const Vector3D & r0) [inherited]
References VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), VW::RotationCentre::Include(), and VW::ThreeDToolGLCommon::rotation_centre.
Referenced by VW::ThreeDToolGLCommon::DrawPoint().
void ThreeDToolGLCommon::DrawRectangle (const Vector3D & rW, const Quaternion & qWO, const double rectangle_width, const double rectangle_height, const int name) [inherited]
Version of DrawRectangle() (see above) supporting object selection.
References VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, and VW::ThreeDToolGLCommon::DrawRectangle().
void ThreeDToolGLCommon::DrawRectangle (const Vector3D & rW, const Quaternion & qWO, const double rectangle_width, const double rectangle_height) [inherited]
Draw a rectangle.
Parameters:
rW The centre of the rectangle in the world frame
qWO The transformation between the world frame and the object frame in which the rectangle is aligned: In the object frame, the height of the rectangle is aligned with the y axis; the width with the x axis; and the rectangle is perpendicular to the z axis
rectangle_width The width of the rectangle (i.e. extent in the object x-axis direction)
rectangle_height The height of the rectangle (i.e. extent in the object y-axis direction)
References VW::Quaternion::Angle(), VW::Quaternion::Axis(), VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), VW::RotationCentre::Include(), M_PI, and VW::ThreeDToolGLCommon::rotation_centre.
Referenced by VW::ThreeDToolGLCommon::DrawRectangle().
void ThreeDToolGLCommon::DrawRotationCentre () [inherited]
Plot rotation centre.
Centre is plotted as a single white point.
References VW::RotationCentre::Centre(), VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), and VW::ThreeDToolGLCommon::rotation_centre.
Referenced by VW::ThreeDToolGLCommon::DoDrawing().
void ThreeDToolGLCommon::DrawSphere (const Vector3D & r0, const double R, const int name) [inherited]
References VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, and VW::ThreeDToolGLCommon::DrawSphere().
void ThreeDToolGLCommon::DrawSphere (const Vector3D & r0, const double R) [inherited]
References VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), VW::RotationCentre::Include(), VW::ThreeDToolGLCommon::rotation_centre, VW::ThreeDToolGLCommon::sphereptr, and VERBOSE.
void ThreeDToolGLCommon::DrawSphere (const double R) [inherited]
References VW::RotationCentre::IncludeCurrent(), VW::ThreeDToolGLCommon::rotation_centre, VW::ThreeDToolGLCommon::sphereptr, and VERBOSE.
Referenced by DrawMotor1Frame(), and VW::ThreeDToolGLCommon::DrawSphere().
void ThreeDToolGLCommon::DrawTexturedRectangle (const Vector3D & rW, const Quaternion & qWO, const double rectangle_width, const double rectangle_height, const VW::ImageMono< unsigned char > & imageref, const int name) [inherited]
References VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, and VW::ThreeDToolGLCommon::DrawTexturedRectangle().
void ThreeDToolGLCommon::DrawTexturedRectangle (const Vector3D & rW, const Quaternion & qWO, const double rectangle_width, const double rectangle_height, const VW::ImageMono< unsigned char > & imageref) [inherited]
References VW::ThreeDToolGLCommon::ActuallyDrawTexturedRectangle(), VW::RotationCentre::Include(), and VW::ThreeDToolGLCommon::rotation_centre.
Referenced by VW::ThreeDToolGLCommon::DrawTexturedRectangle().
void ThreeDToolGLCommon::DrawTriangle (const Vector3D & p1, const Vector3D & p2, const Vector3D & p3, int name) const [inherited]
Version of DrawTriangle() (see above) supporting object selection.
References VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, and VW::ThreeDToolGLCommon::DrawTriangle().
void ThreeDToolGLCommon::DrawTriangle (const Vector3D & p1, const Vector3D & p2, const Vector3D & p3) const [inherited]
Draw a triangle.
Parameters:
p1 A point on the triangle
p2 A point on the triangle
p3 A point on the triangle
References VW::RotationCentre::Include(), and VW::ThreeDToolGLCommon::rotation_centre.
Referenced by VW::ThreeDToolGLCommon::DrawTriangle().
void ThreeDToolGLCommon::DrawWarpedTexturedRectangle (const Vector3D & rW, const Quaternion & qWO, double corner00[2], double corner01[2], double corner10[2], double corner11[2], const VW::ImageMono< unsigned char > & imageref, const int name) [inherited]
References VW::ThreeDToolGLCommon::ActuallyDrawWarpedTexturedRectangle(), VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, VW::RotationCentre::Include(), and VW::ThreeDToolGLCommon::rotation_centre.
void VW::ThreeDToolGLCommon::EnableLighting () [inline, inherited]
Shortcut for enabling lighting effects.
void ThreeDToolGLCommon::GetCameraPositionOrientation (Vector3D & current_position, Quaternion & current_orientation) [inherited]
References VW::ThreeDToolGLCommon::camera_orientation, and VW::ThreeDToolGLCommon::camera_position.
int VW::GLUTWindow::GetID () const [inline, inherited]
Referenced by GLUTAddWindow(), MakeCurrent(), RequestDraw(), Resize(), and SwapBuffers().
void ThreeDToolGLCommon::GetImage (VW::ImageRGB< unsigned char > & image) [inherited]
Capture the current view as an image.
Retrieves a colour (RGB) image of the current view.
References VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::AllocImageData(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetHeight(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetRowStart(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetWidth(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::IsAlloced(), VW::ThreeDToolGLCommon::MakeCurrent(), VW::ThreeDToolGLCommon::WindowHeight(), and VW::ThreeDToolGLCommon::WindowWidth().
void ThreeDToolGLCommon::GetImage (VW::ImageMono< unsigned char > & image) [inherited]
Capture the current view as an image.
Retrieves a mono image of the current view.
References VW::ImageBase< PixelType, PixelPtr >::AllocImageData(), VW::ImageBase< PixelType, PixelPtr >::GetHeight(), VW::ImageBase< PixelRGB< Type >, PixelRGB< Type > * >::GetRowStart(), VW::ImageBase< PixelType, PixelPtr >::GetWidth(), VW::ImageCopy(), VW::ImageBase< PixelType, PixelPtr >::IsAlloced(), VW::ThreeDToolGLCommon::MakeCurrent(), VW::ThreeDToolGLCommon::WindowHeight(), and VW::ThreeDToolGLCommon::WindowWidth().
unsigned int Glute2::Widget::GetMinimumHeight () const [inline, inherited]
References Glute2::Widget::_minsize_y.
Referenced by Glute2::HBox::_RecalcSizes(), Glute2::Window::Add(), and Glute2::Window::Resize().
unsigned int Glute2::Widget::GetMinimumWidth () const [inline, inherited]
References Glute2::Widget::_minsize_x.
Referenced by Glute2::VBox::_RecalcSizes(), Glute2::Window::Add(), and Glute2::Window::Resize().
void ThreeDToolGLCommon::GetPenColour (unsigned char & red, unsigned char & green, unsigned char & blue, unsigned char & alpha) [inherited]
void VW::ThreeDToolGLCommon::IncludeInRotationCentre (const Vector3D & r) [inline, inherited]
Include a point in the rotation centre calculation.
References VW::RotationCentre::Include(), and VW::ThreeDToolGLCommon::rotation_centre.
Referenced by VW::AWFObject::Draw(), VW::DrawGTI(), VW::DrawThreeQuarterDesk(), VW::DrawWeRo(), and VW::DrawYorick811().
void ThreeDToolGLCommon::InitGL () [protected, inherited]
References VW::ThreeDToolGLCommon::_alpha_background, VW::ThreeDToolGLCommon::_B_background, VW::ThreeDToolGLCommon::_G_background, VW::ThreeDToolGLCommon::_R_background, VW::ThreeDToolGLCommon::circleptr, VW::ThreeDToolGLCommon::click_x0, VW::ThreeDToolGLCommon::click_y0, VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, VW::ThreeDToolGLCommon::cylinderptr, VW::ThreeDToolGLCommon::gl_initialised, VW::ThreeDToolGLCommon::MakeCurrent(), VW::ThreeDToolGLCommon::sphereptr, VW::ThreeDToolGLCommon::texHeight, VW::ThreeDToolGLCommon::texName, and VW::ThreeDToolGLCommon::texWidth.
Referenced by VW::ThreeDToolGLCommon::DoDrawing().
bool VW::ThreeDToolGluteWidget::IsMe (int display_id) const
Is the GL display id given mine?
Reimplemented from VW::GLUTWindow.
bool Glute2::Widget::IsYInverted () const [inherited]
void VW::ThreeDToolGluteWidget::Keyboard (unsigned char key, int x, int y) [inline, protected, virtual]
Implements VW::GLUTWindow.
void ThreeDToolGLCommon::LookAt (const Point3D & some_point) [inherited]
Make the camera look at a position.
The current position and vertical are maintained (if possible), so that only the orientation is affected.
References VW::ThreeDToolGLCommon::camera_orientation, VW::ThreeDToolGLCommon::camera_position, VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), VW::Point3D::Normalise(), R, VW::Quaternion::Set(), and VW::VectorProduct().
void ThreeDToolGluteWidget::MakeCurrent () [virtual]
Implements VW::ThreeDToolGLCommon.
References VW::GLUTWindow::GetID().
Referenced by SetSize().
void ThreeDToolGluteWidget::Motion (int newx, int newy) [protected, virtual]
Implements VW::GLUTWindow.
References current_button, VW::ThreeDToolGLCommon::Dragged(), last_x, and last_y.
void ThreeDToolGluteWidget::Mouse (int button, int state, int x, int y) [protected, virtual]
Implements VW::GLUTWindow.
References VW::ThreeDToolGLCommon::Clicked(), current_button, VW::ThreeDToolGLCommon::Dragging(), VW::ThreeDToolGLCommon::DragRelease(), last_x, and last_y.
void VW::ThreeDToolGluteWidget::PassiveMotion (int newx, int newy) [inline, protected, virtual]
Implements VW::GLUTWindow.
void VW::ThreeDToolGLCommon::PopCameraSettings () [inline, inherited]
Pop the previous camera position and calibration from the stack, added by a previous PushCameraSettings.
void ThreeDToolGLCommon::PopDrawingPosition () [inherited]
Pop the previous drawing position from the stack, added by a previous PushDrawingPosition.
References VW::ThreeDToolGLCommon::current_drawing_position, VW::ThreeDToolGLCommon::drawing_position_stack, and VERBOSE.
Referenced by DrawCamera(), VW::DrawFireI(), VW::DrawGTI(), DrawGTIBlock(), DrawGTIWheel(), VW::DrawGTIWithYorick(), DrawMotor(), DrawMotor1Frame(), DrawMotor2Frame(), DrawMotor3Frame(), VW::DrawThreeQuarterDesk(), VW::DrawVL500(), VW::DrawWeRo(), and VW::DrawYorick811().
double ThreeDToolGLCommon::ProjectOntoSphere (double px, double py) [protected, inherited]
References std::sqrt(), and VW::ThreeDToolGLCommon::TRACKBALLSIZE.
Referenced by VW::ThreeDToolGLCommon::TrackBall().
void VW::ThreeDToolGLCommon::PushCameraSettings () [inline, inherited]
Push the current camera position and calibration onto the stack.
Top member of the stack is the current position and calibration (see also PopCameraSettings).
void ThreeDToolGLCommon::PushDrawingPosition () [inherited]
Push the current drawing position onto the stack.
Top member of the stack is the current drawing position (see also PopDrawingPosition).
References VW::ThreeDToolGLCommon::current_drawing_position, VW::ThreeDToolGLCommon::drawing_position_stack, and VERBOSE.
Referenced by DrawCamera(), VW::DrawFireI(), VW::DrawGTI(), DrawGTIBlock(), DrawGTIWheel(), VW::DrawGTIWithYorick(), DrawMotor(), DrawMotor1Frame(), DrawMotor2Frame(), DrawMotor3Frame(), VW::DrawThreeQuarterDesk(), VW::DrawVL500(), VW::DrawWeRo(), and VW::DrawYorick811().
void ThreeDToolGluteWidget::RequestDraw () [virtual]
Implements VW::ThreeDToolGLCommon.
References Glute2::Widget::_parent_window, VW::GLUTWindow::GetID(), and Glute2::Window::GetWindowID().
Referenced by Resize().
void ThreeDToolGluteWidget::Resize (int newwidth, int newheight) [protected, virtual]
Implements VW::GLUTWindow.
References Glute2::Widget::_h, Glute2::Widget::_parent_window, Glute2::Widget::_w, Glute2::Widget::_x, Glute2::Widget::_y, Glute2::Window::GetHeight(), VW::GLUTWindow::GetID(), Glute2::Window::GetWindowID(), and RequestDraw().
Referenced by SetSize().
void ThreeDToolGLCommon::RotateDrawingPosition (const RotationMatrix & R) [inherited]
Rotate the current drawing position.
References VW::ThreeDToolGLCommon::RotateDrawingPosition().
void ThreeDToolGLCommon::RotateDrawingPosition (const Quaternion & q) [inherited]
Rotate the current drawing position (NB: can also use a vnl_quaternion).
References VW::Quaternion::Angle(), VW::Quaternion::Axis(), VW::ThreeDToolGLCommon::current_drawing_position, M_PI, and VW::DrawingPosition::qWO.
Referenced by VW::DrawFireI(), VW::DrawGTI(), DrawGTIBlock(), DrawGTIWheel(), VW::DrawGTIWithYorick(), VW::DrawThreeQuarterDesk(), VW::DrawVL500(), VW::DrawWeRo(), VW::DrawYorick811(), and VW::ThreeDToolGLCommon::RotateDrawingPosition().
void ThreeDToolGLCommon::Set2DDrawingPosition (const double u, const double v) [inherited]
Move to a drawing position so that GL calls can be made to draw 2D stuff in camera coordinates (mostly used internally).
References VW::ThreeDToolGLCommon::camera_height, VW::ThreeDToolGLCommon::camera_width, VW::ThreeDToolGLCommon::click_x0, VW::ThreeDToolGLCommon::click_y0, VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag, VW::ThreeDToolGLCommon::fku, VW::ThreeDToolGLCommon::fkv, VW::ThreeDToolGLCommon::move_clipping_plane_factor, VW::ThreeDToolGLCommon::orthographic_projection_flag, VW::ThreeDToolGLCommon::u0, VW::ThreeDToolGLCommon::v0, VW::ThreeDToolGLCommon::WindowHeight(), VW::ThreeDToolGLCommon::xL, VW::ThreeDToolGLCommon::xR, VW::ThreeDToolGLCommon::xW, VW::ThreeDToolGLCommon::yB, VW::ThreeDToolGLCommon::yH, VW::ThreeDToolGLCommon::yT, VW::ThreeDToolGLCommon::zF, and VW::ThreeDToolGLCommon::zN.
Referenced by VW::ThreeDToolGLCommon::Draw2DBegin(), VW::ThreeDToolGLCommon::Draw2DText(), and VW::ThreeDToolGLCommon::Draw2DTexturedRectangle().
void ThreeDToolGLCommon::SetAntialiasing (bool on) [inherited]
References VW::ThreeDToolGLCommon::texture_interpolation.
void VW::ThreeDToolGLCommon::SetBackgroundColour (const unsigned char red, const unsigned char green, const unsigned char blue, const unsigned char alpha) [inline, inherited]
Set background colour (characters for R, G, B, alpha).
References VW::ThreeDToolGLCommon::_alpha_background, VW::ThreeDToolGLCommon::_B_background, VW::ThreeDToolGLCommon::_G_background, and VW::ThreeDToolGLCommon::_R_background.
void ThreeDToolGLCommon::SetCameraParameters (const VW::CalibrationMatrix & normK) [inherited]
Set the parameters of the perspective projection used by the display.
Note that the calibration matrix should be normalised, so that the GL view will be correct even if the window size is different from the image for which the calibration was calculated.
Parameters:
normK the normalised calibration matrix (ie. for an image -1<x<1, -0.75<y<0.75)
References VW::ThreeDToolGLCommon::camera_height, VW::ThreeDToolGLCommon::camera_width, VW::CalibrationMatrix::GetAspectRatio(), VW::CalibrationMatrix::GetFocalLength(), VW::CalibrationMatrix::GetPrincipalPointX(), VW::CalibrationMatrix::GetPrincipalPointY(), and VW::ThreeDToolGLCommon::SetCameraParameters().
void ThreeDToolGLCommon::SetCameraParameters (const double fku, const double fkv, const double u0, const double v0) [inherited]
Set the parameters of the perspective projection used by the display.
References VW::ThreeDToolGLCommon::camera_height, VW::ThreeDToolGLCommon::camera_width, VW::ThreeDToolGLCommon::fku, VW::ThreeDToolGLCommon::fkv, VW::ThreeDToolGLCommon::orthographic_projection_flag, VW::ThreeDToolGLCommon::u0, VW::ThreeDToolGLCommon::v0, VERBOSE, VW::ThreeDToolGLCommon::xL, VW::ThreeDToolGLCommon::xM, VW::ThreeDToolGLCommon::xR, VW::ThreeDToolGLCommon::xW, VW::ThreeDToolGLCommon::yB, VW::ThreeDToolGLCommon::yH, VW::ThreeDToolGLCommon::yM, VW::ThreeDToolGLCommon::yT, and VW::ThreeDToolGLCommon::zN.
Referenced by VW::ThreeDToolGLCommon::SetCameraParameters(), and VW::ThreeDToolGLCommon::SetCameraSize().
void ThreeDToolGLCommon::SetCameraPositionOrientation (const Vector3D & new_position, const Quaternion & new_orientation) [inherited]
Set camera position.
Only used when the external application wants to set the view position itself (rather than the normal case of this being done using the class's internal mouse-drag system). Here new_position is cW (camera position vector in world frame) And new_orientation is qWC (quaternion associated with rotation RWC between world frame and camera frame)
References VW::ThreeDToolGLCommon::camera_orientation, and VW::ThreeDToolGLCommon::camera_position.
void ThreeDToolGLCommon::SetCameraSize (unsigned int width, unsigned int size) [inherited]
Set the size of the camera.
This function will also reset the camera parameters to the generic settings. The camera size is the dimensions of the virtual camera used for rendering, not the size of the tool's drawing area. The camera view will be scaled to the drawing area (maintaining its aspect ratio).
References VW::ThreeDToolGLCommon::camera_height, VW::ThreeDToolGLCommon::camera_width, VW::ThreeDToolGLCommon::DEFAULT_WIDTH_OVER_FKU, and VW::ThreeDToolGLCommon::SetCameraParameters().
Referenced by VW::ThreeDToolGLCommon::ThreeDToolGLCommon().
void VW::GLUTWindow::SetID (int id) [inline, inherited]
void ThreeDToolGLCommon::SetMaterial (const GLMaterialType material) [inherited]
Shortcut for setting material properties and colours to match a pre-defined type.
References VW::GLMATERIAL_BRASS, VW::GLMATERIAL_EMERALD, VW::GLMATERIAL_REDPLASTIC, and VW::GLMATERIAL_SLATE.
void ThreeDToolGLCommon::SetOrthographicCameraParameters (const double xWidth, const double yWidth, const double u0, const double v0) [inherited]
Set the parameters of the orthographic projection used by the display.
References VW::ThreeDToolGLCommon::camera_height, VW::ThreeDToolGLCommon::camera_width, VW::ThreeDToolGLCommon::orthographic_projection_flag, VW::ThreeDToolGLCommon::u0, VW::ThreeDToolGLCommon::v0, VERBOSE, VW::ThreeDToolGLCommon::xL, VW::ThreeDToolGLCommon::xM, VW::ThreeDToolGLCommon::xR, VW::ThreeDToolGLCommon::xW, VW::ThreeDToolGLCommon::yB, VW::ThreeDToolGLCommon::yH, VW::ThreeDToolGLCommon::yM, and VW::ThreeDToolGLCommon::yT.
Referenced by VW::ThreeDToolGLCommon::Dragged().
void Glute2::Widget::SetParentWindow (Glute2::Window * parent_window) [virtual, inherited]
Reimplemented in Glute2::Container.
References Glute2::Widget::_parent_window.
Referenced by Glute2::Container::_PushBack(), Glute2::Container::_PushFront(), and Glute2::Window::Add().
void ThreeDToolGLCommon::SetPenColour (const unsigned char red, const unsigned char green, const unsigned char blue, const unsigned char alpha) [inherited]
Set pen colour (characters for R, G, B, alpha).
Referenced by VW::ThreeDToolGLCommon::DoDrawing(), DrawCamera(), VW::DrawFireI(), VW::DrawGTI(), DrawGTIBlock(), DrawGTIWheel(), DrawMotor(), DrawMotor1Frame(), DrawMotor2Frame(), DrawMotor3Frame(), VW::DrawThreeQuarterDesk(), VW::DrawVL500(), and VW::DrawYorick811().
void Glute2::Widget::SetPosition (unsigned int x, unsigned int y) [inline, inherited]
References Glute2::Widget::_x, and Glute2::Widget::_y.
Referenced by Glute2::Window::Add().
void ThreeDToolGluteWidget::SetSize (const unsigned int newwidth, const unsigned int newheight) [virtual]
Implements Glute2::Widget.
References VW::GLUTWindow::_CreateSubwindow(), Glute2::Widget::_h, _initialised, Glute2::Widget::_minsize_x, Glute2::Widget::_minsize_y, Glute2::Widget::_parent_window, Glute2::Widget::_sh, Glute2::Widget::_sw, Glute2::Widget::_w, Glute2::Widget::_x, Glute2::Widget::_y, Glute2::Window::GetHeight(), Glute2::Window::GetWindowID(), MakeCurrent(), and Resize().
void ThreeDToolGluteWidget::SwapBuffers () [virtual]
Implements VW::ThreeDToolGLCommon.
References Glute2::Widget::_parent_window, VW::GLUTWindow::GetID(), and Glute2::Window::GetWindowID().
Quaternion ThreeDToolGLCommon::TrackBall (const double p1x, const double p1y, const double p2x, const double p2y) [protected, inherited]
References VW::Point3D::Norm(), VW::Point3D::Normalise(), VW::ThreeDToolGLCommon::ProjectOntoSphere(), VW::ThreeDToolGLCommon::TRACKBALLSIZE, VW::VectorProduct(), and VERBOSE.
Referenced by VW::ThreeDToolGLCommon::Dragged().
void ThreeDToolGLCommon::TranslateDrawingPosition (const Vector3D & r) [inherited]
Translate the current drawing position (NB: can also use a vnl_vector).
References VW::ThreeDToolGLCommon::current_drawing_position, VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), VW::DrawingPosition::qWO, VW::Quaternion::RotationMatrix(), and VW::DrawingPosition::rW.
Referenced by DrawCamera(), VW::DrawFireI(), VW::DrawGTI(), DrawGTIBlock(), DrawGTIWheel(), VW::DrawGTIWithYorick(), DrawMotor(), DrawMotor1Frame(), DrawMotor2Frame(), DrawMotor3Frame(), VW::DrawThreeQuarterDesk(), VW::DrawVL500(), VW::DrawWeRo(), and VW::DrawYorick811().
bool Glute2::Widget::WantsToGrowX () const [inline, inherited]
References Glute2::Widget::_wants_to_grow_x.
Referenced by Glute2::VBox::_RecalcSizes(), and Glute2::HBox::_RecalcSizes().
bool Glute2::Widget::WantsToGrowY () const [inline, inherited]
References Glute2::Widget::_wants_to_grow_y.
Referenced by Glute2::VBox::_RecalcSizes(), and Glute2::HBox::_RecalcSizes().
unsigned int ThreeDToolGluteWidget::WindowHeight () const [virtual]
Implements VW::ThreeDToolGLCommon.
References Glute2::Widget::_h.
unsigned int ThreeDToolGluteWidget::WindowWidth () const [virtual]
Implements VW::ThreeDToolGLCommon.
References Glute2::Widget::_w.
Member Data Documentation
double VW::ThreeDToolGLCommon::_alpha_background [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::InitGL(), and VW::ThreeDToolGLCommon::SetBackgroundColour().
double VW::ThreeDToolGLCommon::_B_background [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::InitGL(), and VW::ThreeDToolGLCommon::SetBackgroundColour().
bool Glute2::Widget::_focus [protected, inherited]
Referenced by Glute2::Widget::_SetFocus(), Glute2::Slider::Draw(), Glute2::CheckBox::Draw(), and Glute2::Button::Draw().
double VW::ThreeDToolGLCommon::_G_background [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::InitGL(), and VW::ThreeDToolGLCommon::SetBackgroundColour().
int Glute2::Widget::_h [protected, inherited]
Referenced by Glute2::VBox::_RecalcSizes(), Glute2::HBox::_RecalcSizes(), Glute2::Frame::_RecalcSizes(), Glute2::Widget::Draw(), Glute2::Slider::Draw(), Glute2::Label::Draw(), Glute2::Frame::Draw(), Glute2::CheckBox::Draw(), Glute2::Button::Draw(), VW::DisplayGluteWidget::GetHeight(), Resize(), VW::DisplayGluteWidget::Resize(), SetSize(), Glute2::Slider::SetSize(), Glute2::Label::SetSize(), VW::DisplayGluteWidget::SetSize(), Glute2::Container::SetSize(), Glute2::CheckBox::SetSize(), Glute2::Button::SetSize(), ThreeDToolGluteWidget(), and WindowHeight().
bool VW::ThreeDToolGluteWidget::_initialised [protected]
Referenced by SetSize().
unsigned int Glute2::Widget::_minsize_x [protected, inherited]
Referenced by Glute2::VBox::_RecalcSizes(), Glute2::HBox::_RecalcSizes(), Glute2::Frame::_RecalcSizes(), Glute2::Button::Button(), Glute2::CheckBox::CheckBox(), Glute2::Widget::GetMinimumWidth(), Glute2::Label::Label(), SetSize(), Glute2::Label::SetSize(), VW::DisplayGluteWidget::SetSize(), Glute2::Slider::Slider(), and ThreeDToolGluteWidget().
unsigned int Glute2::Widget::_minsize_y [protected, inherited]
Referenced by Glute2::VBox::_RecalcSizes(), Glute2::HBox::_RecalcSizes(), Glute2::Frame::_RecalcSizes(), Glute2::Button::Button(), Glute2::CheckBox::CheckBox(), Glute2::Widget::GetMinimumHeight(), Glute2::Label::Label(), SetSize(), Glute2::Label::SetSize(), VW::DisplayGluteWidget::SetSize(), Glute2::Slider::Slider(), and ThreeDToolGluteWidget().
bool Glute2::Widget::_needs_redraw [protected, inherited]
Referenced by Glute2::Slider::_Drag(), Glute2::Container::_Drag(), Glute2::Slider::_MousePressed(), Glute2::Container::_MousePressed(), Glute2::Button::_MousePressed(), Glute2::Container::_MouseReleased(), Glute2::CheckBox::_MouseReleased(), Glute2::Button::_MouseReleased(), Glute2::Widget::_NeedsRedraw(), Glute2::Container::_PassiveMotion(), Glute2::VBox::_RecalcSizes(), Glute2::HBox::_RecalcSizes(), Glute2::Frame::_RecalcSizes(), Glute2::Widget::_SetFocus(), Glute2::Slider::Draw(), Glute2::Label::Draw(), VW::DisplayGluteWidget::Draw(), Glute2::CheckBox::Draw(), Glute2::Button::Draw(), and VW::DisplayGluteWidget::RequestDraw().
Glute2::Window* Glute2::Widget::_parent_window [protected, inherited]
Referenced by Glute2::Container::_PushBack(), Glute2::Container::_PushFront(), RequestDraw(), Resize(), VW::DisplayGluteWidget::Resize(), Glute2::Widget::SetParentWindow(), Glute2::Container::SetParentWindow(), SetSize(), VW::DisplayGluteWidget::SetSize(), and SwapBuffers().
double VW::ThreeDToolGLCommon::_R_background [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::InitGL(), and VW::ThreeDToolGLCommon::SetBackgroundColour().
int Glute2::Widget::_sh [protected, inherited]
Referenced by Glute2::Widget::_IsIn(), Glute2::Button::Button(), Glute2::CheckBox::CheckBox(), Glute2::Slider::Draw(), Glute2::CheckBox::Draw(), Glute2::Button::Draw(), Glute2::Label::Label(), VW::DisplayGluteWidget::Resize(), SetSize(), Glute2::Slider::SetSize(), VW::DisplayGluteWidget::SetSize(), Glute2::Container::SetSize(), Glute2::CheckBox::SetSize(), Glute2::Button::SetSize(), and Glute2::Slider::Slider().
int Glute2::Widget::_sw [protected, inherited]
Referenced by Glute2::Slider::_Drag(), Glute2::Widget::_IsIn(), Glute2::Button::Button(), Glute2::CheckBox::CheckBox(), Glute2::Slider::Draw(), Glute2::CheckBox::Draw(), Glute2::Button::Draw(), Glute2::Label::Label(), VW::DisplayGluteWidget::Resize(), SetSize(), Glute2::Slider::SetSize(), VW::DisplayGluteWidget::SetSize(), Glute2::Container::SetSize(), Glute2::CheckBox::SetSize(), Glute2::Button::SetSize(), and Glute2::Slider::Slider().
int Glute2::Widget::_sx [protected, inherited]
Referenced by Glute2::Slider::_Drag(), Glute2::Widget::_IsIn(), Glute2::Slider::Draw(), Glute2::Label::Draw(), Glute2::CheckBox::Draw(), Glute2::Button::Draw(), Glute2::Label::SetSize(), Glute2::Container::SetSize(), Glute2::CheckBox::SetSize(), Glute2::Button::SetSize(), and Glute2::Slider::Slider().
int Glute2::Widget::_sy [protected, inherited]
Referenced by Glute2::Widget::_IsIn(), Glute2::Slider::Draw(), Glute2::Label::Draw(), Glute2::CheckBox::Draw(), Glute2::Button::Draw(), Glute2::Slider::SetSize(), Glute2::Label::SetSize(), Glute2::Container::SetSize(), Glute2::CheckBox::SetSize(), and Glute2::Button::SetSize().
int Glute2::Widget::_w [protected, inherited]
Referenced by Glute2::VBox::_RecalcSizes(), Glute2::HBox::_RecalcSizes(), Glute2::Frame::_RecalcSizes(), Glute2::Widget::Draw(), Glute2::Slider::Draw(), Glute2::Label::Draw(), Glute2::Frame::Draw(), Glute2::CheckBox::Draw(), Glute2::Button::Draw(), VW::DisplayGluteWidget::GetWidth(), Resize(), VW::DisplayGluteWidget::Resize(), SetSize(), Glute2::Slider::SetSize(), Glute2::Label::SetSize(), VW::DisplayGluteWidget::SetSize(), Glute2::Container::SetSize(), Glute2::CheckBox::SetSize(), Glute2::Button::SetSize(), ThreeDToolGluteWidget(), and WindowWidth().
bool Glute2::Widget::_wants_to_grow_x [protected, inherited]
Referenced by Glute2::VBox::_RecalcSizes(), Glute2::HBox::_RecalcSizes(), Glute2::Frame::_RecalcSizes(), Glute2::Button::Button(), Glute2::CheckBox::CheckBox(), Glute2::Label::Label(), Glute2::Slider::Slider(), ThreeDToolGluteWidget(), and Glute2::Widget::WantsToGrowX().
bool Glute2::Widget::_wants_to_grow_y [protected, inherited]
Referenced by Glute2::VBox::_RecalcSizes(), Glute2::HBox::_RecalcSizes(), Glute2::Frame::_RecalcSizes(), Glute2::Button::Button(), Glute2::CheckBox::CheckBox(), Glute2::Label::Label(), Glute2::Slider::Slider(), ThreeDToolGluteWidget(), and Glute2::Widget::WantsToGrowY().
int Glute2::Widget::_x [protected, inherited]
Referenced by Glute2::Slider::_Drag(), Glute2::Widget::_IsIn(), Glute2::VBox::_RecalcSizes(), Glute2::HBox::_RecalcSizes(), Glute2::Frame::_RecalcSizes(), Glute2::Widget::Draw(), Glute2::Slider::Draw(), Glute2::Label::Draw(), Glute2::Frame::Draw(), Glute2::CheckBox::Draw(), Glute2::Button::Draw(), Resize(), VW::DisplayGluteWidget::Resize(), Glute2::Widget::SetPosition(), SetSize(), Glute2::Label::SetSize(), VW::DisplayGluteWidget::SetSize(), and Glute2::Button::SetSize().
int Glute2::Widget::_y [protected, inherited]
Referenced by Glute2::Widget::_IsIn(), Glute2::VBox::_RecalcSizes(), Glute2::HBox::_RecalcSizes(), Glute2::Frame::_RecalcSizes(), Glute2::Widget::Draw(), Glute2::Slider::Draw(), Glute2::Label::Draw(), Glute2::Frame::Draw(), Glute2::CheckBox::Draw(), Glute2::Button::Draw(), Resize(), VW::DisplayGluteWidget::Resize(), Glute2::Widget::SetPosition(), SetSize(), Glute2::Label::SetSize(), VW::DisplayGluteWidget::SetSize(), and Glute2::Button::SetSize().
unsigned int VW::ThreeDToolGLCommon::camera_height [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::Dragged(), VW::ThreeDToolGLCommon::DrawCinemaScreen(), VW::ThreeDToolGLCommon::Set2DDrawingPosition(), VW::ThreeDToolGLCommon::SetCameraParameters(), VW::ThreeDToolGLCommon::SetCameraSize(), VW::ThreeDToolGLCommon::SetOrthographicCameraParameters(), and VW::ThreeDToolGLCommon::ThreeDToolGLCommon().
Quaternion VW::ThreeDToolGLCommon::camera_orientation [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::Dragged(), VW::ThreeDToolGLCommon::DrawCinemaScreen(), VW::ThreeDToolGLCommon::GetCameraPositionOrientation(), VW::ThreeDToolGLCommon::LookAt(), VW::ThreeDToolGLCommon::SetCameraPositionOrientation(), and VW::ThreeDToolGLCommon::ThreeDToolGLCommon().
Vector3D VW::ThreeDToolGLCommon::camera_position [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::Dragged(), VW::ThreeDToolGLCommon::DrawCinemaScreen(), VW::ThreeDToolGLCommon::GetCameraPositionOrientation(), VW::ThreeDToolGLCommon::LookAt(), VW::ThreeDToolGLCommon::SetCameraPositionOrientation(), and VW::ThreeDToolGLCommon::ThreeDToolGLCommon().
unsigned int VW::ThreeDToolGLCommon::camera_width [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::Dragged(), VW::ThreeDToolGLCommon::DrawCinemaScreen(), VW::ThreeDToolGLCommon::Set2DDrawingPosition(), VW::ThreeDToolGLCommon::SetCameraParameters(), VW::ThreeDToolGLCommon::SetCameraSize(), VW::ThreeDToolGLCommon::SetOrthographicCameraParameters(), and VW::ThreeDToolGLCommon::ThreeDToolGLCommon().
GLUquadricObj* VW::ThreeDToolGLCommon::circleptr [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Draw2DCircle(), VW::ThreeDToolGLCommon::Draw2DCovariance(), VW::ThreeDToolGLCommon::DrawCylinder(), VW::ThreeDToolGLCommon::DrawDisc(), VW::ThreeDToolGLCommon::InitGL(), and VW::ThreeDToolGLCommon::~ThreeDToolGLCommon().
int VW::ThreeDToolGLCommon::click_x0 [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::InitGL(), and VW::ThreeDToolGLCommon::Set2DDrawingPosition().
int VW::ThreeDToolGLCommon::click_y0 [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::InitGL(), and VW::ThreeDToolGLCommon::Set2DDrawingPosition().
int VW::ThreeDToolGluteWidget::current_button [protected]
Referenced by Motion(), and Mouse().
DrawingPosition VW::ThreeDToolGLCommon::current_drawing_position [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::PopDrawingPosition(), VW::ThreeDToolGLCommon::PushDrawingPosition(), VW::ThreeDToolGLCommon::RotateDrawingPosition(), VW::ThreeDToolGLCommon::ThreeDToolGLCommon(), and VW::ThreeDToolGLCommon::TranslateDrawingPosition().
bool VW::ThreeDToolGLCommon::currently_drawing_in_selection_mode_flag [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::Draw2DArrow(), VW::ThreeDToolGLCommon::Draw2DCircle(), VW::ThreeDToolGLCommon::Draw2DCovariance(), VW::ThreeDToolGLCommon::Draw2DDashedLine(), VW::ThreeDToolGLCommon::Draw2DLine(), VW::ThreeDToolGLCommon::Draw2DRectangle(), VW::ThreeDToolGLCommon::Draw2DTexturedRectangle(), VW::ThreeDToolGLCommon::DrawCameraGraphic(), VW::ThreeDToolGLCommon::DrawCovariance(), VW::ThreeDToolGLCommon::DrawCylinder(), VW::ThreeDToolGLCommon::DrawLine(), VW::ThreeDToolGLCommon::DrawPoint(), VW::ThreeDToolGLCommon::DrawRectangle(), VW::ThreeDToolGLCommon::DrawSphere(), VW::ThreeDToolGLCommon::DrawTexturedRectangle(), VW::ThreeDToolGLCommon::DrawTriangle(), VW::ThreeDToolGLCommon::DrawWarpedTexturedRectangle(), VW::ThreeDToolGLCommon::InitGL(), and VW::ThreeDToolGLCommon::Set2DDrawingPosition().
GLUquadricObj* VW::ThreeDToolGLCommon::cylinderptr [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::DrawCameraGraphic(), VW::ThreeDToolGLCommon::DrawCone(), VW::ThreeDToolGLCommon::DrawCylinder(), VW::ThreeDToolGLCommon::InitGL(), and VW::ThreeDToolGLCommon::~ThreeDToolGLCommon().
const unsigned int VW::ThreeDToolGLCommon::DEFAULT_CAMERA_HEIGHT = 480 [static, inherited]
Sets the camera height used in the default constructor.
Usually set your own using the other constructor, or calling SetCameraSize().
const unsigned int VW::ThreeDToolGLCommon::DEFAULT_CAMERA_WIDTH = 640 [static, inherited]
Sets the camera width used in the default constructor.
Usually set your own using the other constructor, or calling SetCameraSize().
const double VW::ThreeDToolGLCommon::DEFAULT_WIDTH_OVER_FKU = 0.75 [static, inherited]
This constant sets default projection zoom: normally choose your own with SetCameraParameters().
Referenced by VW::ThreeDToolGLCommon::SetCameraSize().
bool VW::ThreeDToolGLCommon::dragging [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::Dragged(), VW::ThreeDToolGLCommon::Dragging(), VW::ThreeDToolGLCommon::DragRelease(), VW::ThreeDToolWxGLWidget::OnMouseDown(), VW::ThreeDToolWxGLWidget::OnMouseMove(), and VW::ThreeDToolWxGLWidget::OnMouseUp().
VWEvents::Event1<void,bool> VW::ThreeDToolGLCommon::DrawEvent [inherited]
The display needs redrawing.
When this signal is emitted the display has already been cleared and the viewpoint set appropriately. The user just needs to draw the scene at the origin.
Referenced by VW::ThreeDToolWxGLWidget::_CallDrawEvent(), VW::ThreeDToolGTKGLWidget::_CallDrawEvent(), VW::ThreeDToolGLCommon::_CallDrawEvent(), and VW::ThreeDToolGLCommon::Clicked().
std::vector<DrawingPosition> VW::ThreeDToolGLCommon::drawing_position_stack [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::PopDrawingPosition(), and VW::ThreeDToolGLCommon::PushDrawingPosition().
double VW::ThreeDToolGLCommon::fku [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Dragged(), VW::ThreeDToolGLCommon::DrawCinemaScreen(), VW::ThreeDToolGLCommon::Set2DDrawingPosition(), and VW::ThreeDToolGLCommon::SetCameraParameters().
double VW::ThreeDToolGLCommon::fkv [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Dragged(), VW::ThreeDToolGLCommon::DrawCinemaScreen(), VW::ThreeDToolGLCommon::Set2DDrawingPosition(), and VW::ThreeDToolGLCommon::SetCameraParameters().
bool VW::ThreeDToolGLCommon::gl_initialised [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::InitGL(), and VW::ThreeDToolGLCommon::~ThreeDToolGLCommon().
int VW::ThreeDToolGluteWidget::last_x [protected]
Referenced by Motion(), and Mouse().
int VW::ThreeDToolGluteWidget::last_y [protected]
Referenced by Motion(), and Mouse().
const double VW::ThreeDToolGLCommon::move_clipping_plane_factor = 0.999999 [static, protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), and VW::ThreeDToolGLCommon::Set2DDrawingPosition().
bool VW::ThreeDToolGLCommon::orthographic_projection_flag [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::Dragged(), VW::ThreeDToolGLCommon::Set2DDrawingPosition(), VW::ThreeDToolGLCommon::SetCameraParameters(), and VW::ThreeDToolGLCommon::SetOrthographicCameraParameters().
VWEvents::Event3<void,int,double,double> VW::ThreeDToolGLCommon::ProcessHitsEvent [inherited]
Referenced by VW::ThreeDToolWxGLWidget::_CallProcessHitsEvent(), VW::ThreeDToolGTKGLWidget::_CallProcessHitsEvent(), and VW::ThreeDToolGLCommon::_CallProcessHitsEvent().
RotationCentre* VW::ThreeDToolGLCommon::rotation_centre [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::Dragged(), VW::ThreeDToolGLCommon::DrawAxes(), VW::ThreeDToolGLCommon::DrawCameraGraphic(), VW::ThreeDToolGLCommon::DrawCone(), VW::ThreeDToolGLCommon::DrawCovariance(), VW::ThreeDToolGLCommon::DrawCylinder(), VW::ThreeDToolGLCommon::DrawDisc(), VW::ThreeDToolGLCommon::DrawLine(), VW::ThreeDToolGLCommon::DrawPoint(), VW::ThreeDToolGLCommon::DrawRectangle(), VW::ThreeDToolGLCommon::DrawRotationCentre(), VW::ThreeDToolGLCommon::DrawSphere(), VW::ThreeDToolGLCommon::DrawTexturedRectangle(), VW::ThreeDToolGLCommon::DrawTriangle(), VW::ThreeDToolGLCommon::DrawWarpedTexturedRectangle(), VW::ThreeDToolGLCommon::IncludeInRotationCentre(), and VW::ThreeDToolGLCommon::ThreeDToolGLCommon().
GLUquadricObj* VW::ThreeDToolGLCommon::sphereptr [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::DrawCovariance(), VW::ThreeDToolGLCommon::DrawSphere(), VW::ThreeDToolGLCommon::InitGL(), and VW::ThreeDToolGLCommon::~ThreeDToolGLCommon().
unsigned int VW::ThreeDToolGLCommon::texHeight [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::ActuallyDrawDistortedTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawWarpedTexturedRectangle(), and VW::ThreeDToolGLCommon::InitGL().
GLuint VW::ThreeDToolGLCommon::texName [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::ActuallyDrawDistortedTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawWarpedTexturedRectangle(), VW::ThreeDToolGLCommon::Draw2DTexturedRectangle(), and VW::ThreeDToolGLCommon::InitGL().
GLint VW::ThreeDToolGLCommon::texture_interpolation [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::ActuallyDrawDistortedTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawWarpedTexturedRectangle(), VW::ThreeDToolGLCommon::Draw2DTexturedRectangle(), and VW::ThreeDToolGLCommon::SetAntialiasing().
unsigned int VW::ThreeDToolGLCommon::texWidth [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::ActuallyDrawDistortedTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawWarpedTexturedRectangle(), and VW::ThreeDToolGLCommon::InitGL().
const double VW::ThreeDToolGLCommon::TRACKBALLSIZE = 0.8 [static, protected, inherited]
Referenced by VW::ThreeDToolGLCommon::ProjectOntoSphere(), and VW::ThreeDToolGLCommon::TrackBall().
double VW::ThreeDToolGLCommon::u0 [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Dragged(), VW::ThreeDToolGLCommon::DrawCinemaScreen(), VW::ThreeDToolGLCommon::Set2DDrawingPosition(), VW::ThreeDToolGLCommon::SetCameraParameters(), and VW::ThreeDToolGLCommon::SetOrthographicCameraParameters().
double VW::ThreeDToolGLCommon::v0 [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Dragged(), VW::ThreeDToolGLCommon::DrawCinemaScreen(), VW::ThreeDToolGLCommon::Set2DDrawingPosition(), VW::ThreeDToolGLCommon::SetCameraParameters(), and VW::ThreeDToolGLCommon::SetOrthographicCameraParameters().
double VW::ThreeDToolGLCommon::xL [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::Set2DDrawingPosition(), VW::ThreeDToolGLCommon::SetCameraParameters(), and VW::ThreeDToolGLCommon::SetOrthographicCameraParameters().
double VW::ThreeDToolGLCommon::xM [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::SetCameraParameters(), and VW::ThreeDToolGLCommon::SetOrthographicCameraParameters().
double VW::ThreeDToolGLCommon::xR [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::Set2DDrawingPosition(), VW::ThreeDToolGLCommon::SetCameraParameters(), and VW::ThreeDToolGLCommon::SetOrthographicCameraParameters().
double VW::ThreeDToolGLCommon::xW [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Dragged(), VW::ThreeDToolGLCommon::Set2DDrawingPosition(), VW::ThreeDToolGLCommon::SetCameraParameters(), and VW::ThreeDToolGLCommon::SetOrthographicCameraParameters().
double VW::ThreeDToolGLCommon::yB [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::Set2DDrawingPosition(), VW::ThreeDToolGLCommon::SetCameraParameters(), and VW::ThreeDToolGLCommon::SetOrthographicCameraParameters().
double VW::ThreeDToolGLCommon::yH [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Dragged(), VW::ThreeDToolGLCommon::Set2DDrawingPosition(), VW::ThreeDToolGLCommon::SetCameraParameters(), and VW::ThreeDToolGLCommon::SetOrthographicCameraParameters().
double VW::ThreeDToolGLCommon::yM [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::SetCameraParameters(), and VW::ThreeDToolGLCommon::SetOrthographicCameraParameters().
double VW::ThreeDToolGLCommon::yT [protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::Set2DDrawingPosition(), VW::ThreeDToolGLCommon::SetCameraParameters(), and VW::ThreeDToolGLCommon::SetOrthographicCameraParameters().
const double VW::ThreeDToolGLCommon::zF = 100000 [static, protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), and VW::ThreeDToolGLCommon::Set2DDrawingPosition().
const double VW::ThreeDToolGLCommon::zN = 0.01 [static, protected, inherited]
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::Set2DDrawingPosition(), and VW::ThreeDToolGLCommon::SetCameraParameters().
The documentation for this class was generated from the following files:
threedtoolglutewidget.h
threedtoolglutewidget.cpp