VW: VW::DisplayWxGLWidget Class Reference
VW::DisplayWxGLWidget Class Reference
[Displays]
A display widget for WxWidgets guis.
#include <displaywxglwidget.h>
Public Member Functions
DisplayWxGLWidget ()
DisplayWxGLWidget (wxWindow *parent, int wx_id, const unsigned int width, const unsigned int height, const std::string title="")
~DisplayWxGLWidget (void)
void SetSize (const unsigned int new_width, const unsigned int new_height)
Set (or reset) the size.
unsigned int GetWidth ()
unsigned int GetHeight ()
void MakeCurrent ()
void RequestDraw ()
void Draw ()
For internal use only - call it at your own risk - you have been warned.
void Reset (unsigned char red=0, unsigned char green=0, unsigned char blue=127)
void SetPixel (const int x, const int y, const unsigned char red, const unsigned char green, const unsigned char blue, const unsigned char alpha=0)
Set the colour of a single pixel.
void SetPixel (const int x, const int y)
Set a single pixel to the current pen colour.
void SetPenColour (const unsigned char red, const unsigned char green, const unsigned char blue, const unsigned char alpha=0)
Set the colour used for drawing lines and points.
void GetPenColour (unsigned char &red, unsigned char &green, unsigned char &blue, unsigned char &alpha) const
Recover the colour used for drawing lines and points.
void DrawPoint (const float x, const float y)
Draw a point at .
void DrawLine (const float x0, const float y0, const float x1, const float y1)
Draw a line from to .
void GetGLCoords (float pixelx, float pixely, float &glx, float &gly) const
Convert pixel coords into GL coords for drawing.
void ConvertToGLCoords (float &x, float &y) const
Convert pixel coords into GL coords for drawing.
void GetPixelCoords (float pixelx, float pixely, float &glx, float &gly) const
Convert GL coords into pixel coords.
void ConvertToPixelCoords (float &x, float &y) const
Convert GL coords into pixel coords.
virtual unsigned int GetTextureName ()
virtual unsigned int GetTextureWidth () const
virtual unsigned int GetTextureHeight () const
virtual void GenerateTexture (unsigned int desired_width, unsigned int desired_height)
float GetImageDrawingDepth () const
float GetFeatureDrawingDepth () const
void Flush ()
Force display to the screen.
bool IsInitialised ()
std::string GetTitle () const
Return the name (displayed in title bar if visible) of the display.
void DrawRectangle (const float x0, const float y0, const float x1, const float y1)
Convenience function to draw a rectangle (just calls four lots of DrawLine).
void DrawCircle (const float x0, const float y0, const float radius)
Convenience function to draw a circle (made of line segments).
void DrawRightEllipse (const float x0, const float y0, const float rx, const float ry)
Convenience function to draw a right ellipse (ie major and minor axes aligned with x, y axes).
void DrawEllipse (const float x0, const float y0, const float rx, const float ry, const float skew)
Convenience function to draw a general ellipse.
Public Attributes
VWEvents::Event1< void, bool > DrawEvent
The display needs redrawing.
VWEvents::Event3< void, int,
int, int > ClickEvent
VWEvents::Event5< void, int,
int, int, int, int > DragEvent
VWEvents::Event5< void, int,
int, int, int, int > DragFinishedEvent
Protected Member Functions
void SwapBuffers ()
void Resize (int new_width, int new_height)
void DisplayCoordsToPixelCoords (float dispx, float dispy, float &pixx, float &pixy) const
void OnMouseDown (wxMouseEvent &event)
void OnMouseUp (wxMouseEvent &event)
void OnMouseMove (wxMouseEvent &event)
void OnPaint (wxPaintEvent &event)
void OnSize (wxSizeEvent &event)
DECLARE_DYNAMIC_CLASS (DisplayWxGLWidget)
DECLARE_EVENT_TABLE ()
void ResetCoords (double width, double height)
void InitGL ()
void SetGLView ()
Protected Attributes
int _wx_id
bool _dragging
bool _pressed
int _last_x
int _last_y
int _current_button
unsigned int _width
unsigned int _height
unsigned int texName
unsigned int texture_width
unsigned int texture_height
float _xscale
float _xoffset
float _yscale
float _yoffset
unsigned char _red
unsigned char _green
unsigned char _blue
unsigned char _alpha
int last_x
int last_y
bool dragging
bool _initialised
bool _visible
std::string _my_title
Detailed Description
A display widget for WxWidgets guis.
Author:
BJ Tordoff
Date:
02/08/2003
Constructor & Destructor Documentation
VW::DisplayWxGLWidget::DisplayWxGLWidget ()
VW::DisplayWxGLWidget::DisplayWxGLWidget (wxWindow * parent, int wx_id, const unsigned int width, const unsigned int height, const std::string title = "")
VW::DisplayWxGLWidget::~DisplayWxGLWidget (void) [inline]
Member Function Documentation
void VW::DisplayGLCommon::ConvertToGLCoords (float & x, float & y) const [inline, inherited]
Convert pixel coords into GL coords for drawing.
References VW::DisplayGLCommon::_xoffset, VW::DisplayGLCommon::_xscale, VW::DisplayGLCommon::_yoffset, and VW::DisplayGLCommon::_yscale.
void VW::DisplayGLCommon::ConvertToPixelCoords (float & x, float & y) const [inline, inherited]
Convert GL coords into pixel coords.
References VW::DisplayGLCommon::_xoffset, VW::DisplayGLCommon::_xscale, VW::DisplayGLCommon::_yoffset, and VW::DisplayGLCommon::_yscale.
Referenced by DisplayCoordsToPixelCoords().
VW::DisplayWxGLWidget::DECLARE_DYNAMIC_CLASS (DisplayWxGLWidget) [protected]
VW::DisplayWxGLWidget::DECLARE_EVENT_TABLE () [protected]
void VW::DisplayWxGLWidget::DisplayCoordsToPixelCoords (float dispx, float dispy, float & pixx, float & pixy) const [inline, protected]
References _height, _width, and VW::DisplayGLCommon::ConvertToPixelCoords().
Referenced by OnMouseDown(), OnMouseMove(), and OnMouseUp().
void VW::DisplayWxGLWidget::Draw ()
For internal use only - call it at your own risk - you have been warned.
References _wx_id, and VERBOSE.
Referenced by OnPaint().
void VW::DisplayBase::DrawCircle (const float x0, const float y0, const float radius) [inline, inherited]
Convenience function to draw a circle (made of line segments).
References VW::DisplayBase::DrawRightEllipse().
Referenced by VW::DrawFunctions::Draw().
void VW::DisplayBase::DrawEllipse (const float x0, const float y0, const float rx, const float ry, const float skew) [inherited]
Convenience function to draw a general ellipse.
The parameters are such that they are easily recovered from the matrix equation for an ellipse:
(x-x0 y-y0) C^-1 (x-x0) = sigma^2 (y-y0)
where sigma gives the "radius" (number of std devs) and C is
C = [ rx 0 ] [ rx skew ] [ skew ry ] [ 0 ry ]
Parameters:
x0 x coord of centre
y0 y coord of centre
rx radius in x-direction at y=0
ry radius in y-direction at x=0
skew effect of y on x, where skew=0 gives a right ellipse
References VW::DisplayBase::DrawLine(), and NUM_CIRC_POINTS.
Referenced by VW::DrawFunctions::Draw(), and VW::DrawFunctions::DrawCovariance().
void VW::DisplayGLCommon::DrawLine (const float x0, const float y0, const float x1, const float y1) [inline, virtual, inherited]
Draw a line from to .
Implements VW::DisplayBase.
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::GetFeatureDrawingDepth(), VW::DisplayGLCommon::GetGLCoords(), and VW::DisplayGLCommon::MakeCurrent().
Referenced by VW::DisplayGTKGL::DrawLine().
void VW::DisplayGLCommon::DrawPoint (const float x, const float y) [inline, virtual, inherited]
Draw a point at .
Implements VW::DisplayBase.
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::GetFeatureDrawingDepth(), VW::DisplayGLCommon::GetGLCoords(), and VW::DisplayGLCommon::MakeCurrent().
Referenced by VW::DisplayGTKGL::DrawPoint().
void VW::DisplayBase::DrawRectangle (const float x0, const float y0, const float x1, const float y1) [inline, inherited]
Convenience function to draw a rectangle (just calls four lots of DrawLine).
References VW::DisplayBase::DrawLine().
void VW::DisplayBase::DrawRightEllipse (const float x0, const float y0, const float rx, const float ry) [inherited]
Convenience function to draw a right ellipse (ie major and minor axes aligned with x, y axes).
Parameters:
x0 x coord of centre
y0 y coord of centre
rx max radius in x-direction
ry max radius in y direction
References VW::DisplayBase::DrawLine(), and NUM_CIRC_POINTS.
Referenced by VW::DisplayBase::DrawCircle().
void VW::DisplayGLCommon::Flush (void) [inline, virtual, inherited]
Force display to the screen.
Implements VW::DisplayBase.
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::MakeCurrent(), and VW::DisplayGLCommon::SwapBuffers().
Referenced by VW::DisplayGTKGL::Flush(), and VW::DisplayGTKGL::SwapBuffers().
void VW::DisplayGLCommon::GenerateTexture (unsigned int desired_width, unsigned int desired_height) [virtual, inherited]
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::ResetCoords(), VW::DisplayGLCommon::texName, VW::DisplayGLCommon::texture_height, VW::DisplayGLCommon::texture_width, and VERBOSE.
Referenced by VW::DrawFunctions::Draw(), and VW::DisplayGTKGL::GenerateTexture().
float VW::DisplayGLCommon::GetFeatureDrawingDepth () const [inline, inherited]
Referenced by VW::DisplayGLCommon::DrawLine(), VW::DisplayGLCommon::DrawPoint(), and VW::DisplayGLCommon::SetPixel().
void VW::DisplayGLCommon::GetGLCoords (float pixelx, float pixely, float & glx, float & gly) const [inline, inherited]
Convert pixel coords into GL coords for drawing.
References VW::DisplayGLCommon::_xoffset, VW::DisplayGLCommon::_xscale, VW::DisplayGLCommon::_yoffset, and VW::DisplayGLCommon::_yscale.
Referenced by VW::DisplayGLCommon::DrawLine(), VW::DisplayGLCommon::DrawPoint(), and VW::DisplayGLCommon::SetPixel().
unsigned int VW::DisplayWxGLWidget::GetHeight (void) [inline, virtual]
Implements VW::DisplayBase.
References _height.
float VW::DisplayGLCommon::GetImageDrawingDepth () const [inline, inherited]
Referenced by VW::DrawFunctions::Draw().
void VW::DisplayGLCommon::GetPenColour (unsigned char & red, unsigned char & green, unsigned char & blue, unsigned char & alpha) const [inline, virtual, inherited]
Recover the colour used for drawing lines and points.
Implements VW::DisplayBase.
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::_alpha, VW::DisplayGLCommon::_blue, VW::DisplayGLCommon::_green, and VW::DisplayGLCommon::_red.
Referenced by VW::DisplayGTKGL::GetPenColour().
void VW::DisplayGLCommon::GetPixelCoords (float pixelx, float pixely, float & glx, float & gly) const [inline, inherited]
Convert GL coords into pixel coords.
References VW::DisplayGLCommon::_xoffset, VW::DisplayGLCommon::_xscale, VW::DisplayGLCommon::_yoffset, and VW::DisplayGLCommon::_yscale.
unsigned int VW::DisplayGLCommon::GetTextureHeight () const [inline, virtual, inherited]
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::texture_height.
Referenced by VW::DrawFunctions::Draw(), and VW::DisplayGTKGL::GetTextureHeight().
unsigned int VW::DisplayGLCommon::GetTextureName () [inline, virtual, inherited]
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::texName.
Referenced by VW::DrawFunctions::Draw(), and VW::DisplayGTKGL::GetTextureName().
unsigned int VW::DisplayGLCommon::GetTextureWidth () const [inline, virtual, inherited]
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::texture_width.
Referenced by VW::DrawFunctions::Draw(), and VW::DisplayGTKGL::GetTextureWidth().
std::string VW::DisplayBase::GetTitle () const [inline, inherited]
Return the name (displayed in title bar if visible) of the display.
References VW::DisplayBase::_my_title.
Referenced by VW::DisplayGLUT::SetSize().
unsigned int VW::DisplayWxGLWidget::GetWidth (void) [inline, virtual]
Implements VW::DisplayBase.
References _width.
void VW::DisplayGLCommon::InitGL () [protected, inherited]
References VW::DisplayBase::_initialised, VW::DisplayBase::_visible, VW::DisplayGLCommon::SetGLView(), VW::DisplayGLCommon::texName, VW::DisplayGLCommon::texture_height, VW::DisplayGLCommon::texture_width, and VERBOSE.
Referenced by MakeCurrent(), VW::DisplayGTKGLWidget::MakeCurrent(), and VW::DisplayGLUT::MakeCurrent().
bool VW::DisplayBase::IsInitialised () [inline, inherited]
References VW::DisplayBase::_initialised.
Referenced by VW::DrawFunctions::Draw().
void VW::DisplayWxGLWidget::MakeCurrent () [virtual]
Implements VW::DisplayGLCommon.
References VW::DisplayBase::_initialised, VW::DisplayGLCommon::InitGL(), and VERBOSE.
void VW::DisplayWxGLWidget::OnMouseDown (wxMouseEvent & event) [protected]
References _current_button, _dragging, _last_x, _last_y, _pressed, and DisplayCoordsToPixelCoords().
void VW::DisplayWxGLWidget::OnMouseMove (wxMouseEvent & event) [protected]
References _current_button, _dragging, _last_x, _last_y, _pressed, _wx_id, DisplayCoordsToPixelCoords(), and VW::DisplayBase::DragEvent.
void VW::DisplayWxGLWidget::OnMouseUp (wxMouseEvent & event) [protected]
References _current_button, _dragging, _last_x, _last_y, _pressed, _wx_id, VW::DisplayBase::ClickEvent, DisplayCoordsToPixelCoords(), and VW::DisplayBase::DragFinishedEvent.
void VW::DisplayWxGLWidget::OnPaint (wxPaintEvent & event) [protected]
References Draw(), and VERBOSE.
void VW::DisplayWxGLWidget::OnSize (wxSizeEvent & event) [protected]
References _height, _width, RequestDraw(), and VERBOSE.
void VW::DisplayWxGLWidget::RequestDraw ()
References FALSE, and VERBOSE.
Referenced by OnSize().
void VW::DisplayGLCommon::Reset (unsigned char red = 0, unsigned char green = 0, unsigned char blue = 127) [inline, inherited]
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::MakeCurrent().
Referenced by VW::DrawFunctions::Draw(), and VW::DisplayGTKGL::Reset().
void VW::DisplayGLCommon::ResetCoords (double width, double height) [inline, protected, inherited]
References VW::DisplayGLCommon::_xoffset, VW::DisplayGLCommon::_xscale, VW::DisplayGLCommon::_yoffset, and VW::DisplayGLCommon::_yscale.
Referenced by VW::DisplayGLCommon::DisplayGLCommon(), VW::DisplayGLCommon::GenerateTexture(), VW::DisplayGluteWidget::SetSize(), and VW::DisplayGLUT::SetSize().
void VW::DisplayWxGLWidget::Resize (int new_width, int new_height) [protected]
References _height, _width, SetSize(), and VERBOSE.
void VW::DisplayGLCommon::SetGLView () [protected, inherited]
References VERBOSE.
Referenced by VW::DisplayGLCommon::InitGL(), VW::DisplayGluteWidget::Resize(), VW::DisplayGLUT::Resize(), VW::DisplayGluteWidget::SetSize(), and VW::DisplayGLUT::SetSize().
void VW::DisplayGLCommon::SetPenColour (const unsigned char red, const unsigned char green, const unsigned char blue, const unsigned char alpha = 0) [inline, virtual, inherited]
Set the colour used for drawing lines and points.
Implements VW::DisplayBase.
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::_alpha, VW::DisplayGLCommon::_blue, VW::DisplayGLCommon::_green, VW::DisplayGLCommon::_red, and VW::DisplayGLCommon::MakeCurrent().
Referenced by VW::DisplayGTKGL::SetPenColour().
void VW::DisplayGLCommon::SetPixel (const int x, const int y) [inline, virtual, inherited]
Set a single pixel to the current pen colour.
Implements VW::DisplayBase.
References VW::DisplayGLCommon::GetFeatureDrawingDepth(), VW::DisplayGLCommon::GetGLCoords(), and VW::DisplayGLCommon::MakeCurrent().
void VW::DisplayGLCommon::SetPixel (const int x, const int y, const unsigned char red, const unsigned char green, const unsigned char blue, const unsigned char alpha = 0) [inline, virtual, inherited]
Set the colour of a single pixel.
Implements VW::DisplayBase.
Reimplemented in VW::DisplayGTKGL.
References VW::DisplayGLCommon::_alpha, VW::DisplayGLCommon::_blue, VW::DisplayGLCommon::_green, VW::DisplayGLCommon::_red, VW::DisplayGLCommon::GetFeatureDrawingDepth(), VW::DisplayGLCommon::GetGLCoords(), and VW::DisplayGLCommon::MakeCurrent().
Referenced by VW::DisplayGTKGL::SetPixel().
void VW::DisplayWxGLWidget::SetSize (const unsigned int new_width, const unsigned int new_height) [virtual]
Set (or reset) the size.
If the display is not currently onscreen, it is shown. Otherwise it is resized (which often involves first hiding it from view, so don't expect it to be fast!).
Implements VW::DisplayBase.
References _height, _width, and VERBOSE.
Referenced by Resize().
void VW::DisplayWxGLWidget::SwapBuffers () [protected, virtual]
Implements VW::DisplayGLCommon.
References VERBOSE.
Member Data Documentation
unsigned char VW::DisplayGLCommon::_alpha [protected, inherited]
Referenced by VW::DisplayGLCommon::GetPenColour(), VW::DisplayGLCommon::SetPenColour(), and VW::DisplayGLCommon::SetPixel().
unsigned char VW::DisplayGLCommon::_blue [protected, inherited]
Referenced by VW::DisplayGLCommon::GetPenColour(), VW::DisplayGLCommon::SetPenColour(), and VW::DisplayGLCommon::SetPixel().
int VW::DisplayWxGLWidget::_current_button [protected]
Referenced by OnMouseDown(), OnMouseMove(), and OnMouseUp().
bool VW::DisplayWxGLWidget::_dragging [protected]
Referenced by OnMouseDown(), OnMouseMove(), and OnMouseUp().
unsigned char VW::DisplayGLCommon::_green [protected, inherited]
Referenced by VW::DisplayGLCommon::GetPenColour(), VW::DisplayGLCommon::SetPenColour(), and VW::DisplayGLCommon::SetPixel().
unsigned int VW::DisplayWxGLWidget::_height [protected]
Referenced by DisplayCoordsToPixelCoords(), GetHeight(), OnSize(), Resize(), and SetSize().
bool VW::DisplayBase::_initialised [protected, inherited]
Referenced by VW::PSCanvas::Close(), VW::PSCanvas::DrawLine(), VW::PSCanvas::Flush(), VW::DisplayGTKGL::GetHeight(), VW::DisplayGTK::GetHeight(), VW::DisplayGTKGL::GetWidth(), VW::DisplayGTK::GetWidth(), VW::DisplayGLCommon::InitGL(), VW::DisplayBase::IsInitialised(), MakeCurrent(), VW::DisplayGTKGLWidget::MakeCurrent(), VW::DisplayGLUT::MakeCurrent(), VW::PSCanvas::Open(), VW::PSCanvas::SetSize(), VW::DisplayXForms::SetSize(), VW::DisplayX::SetSize(), VW::DisplayGTKGL::SetSize(), VW::DisplayGTK::SetSize(), VW::DisplayGluteWidget::SetSize(), and VW::PSCanvas::~PSCanvas().
int VW::DisplayWxGLWidget::_last_x [protected]
Referenced by OnMouseDown(), OnMouseMove(), and OnMouseUp().
int VW::DisplayWxGLWidget::_last_y [protected]
Referenced by OnMouseDown(), OnMouseMove(), and OnMouseUp().
std::string VW::DisplayBase::_my_title [protected, inherited]
Referenced by VW::DisplayBase::GetTitle(), VW::DisplayXForms::SetSize(), VW::DisplayX::SetSize(), VW::DisplayGTKGL::SetSize(), and VW::DisplayGTK::SetSize().
bool VW::DisplayWxGLWidget::_pressed [protected]
Referenced by OnMouseDown(), OnMouseMove(), and OnMouseUp().
unsigned char VW::DisplayGLCommon::_red [protected, inherited]
Referenced by VW::DisplayGLCommon::GetPenColour(), VW::DisplayGLCommon::SetPenColour(), and VW::DisplayGLCommon::SetPixel().
bool VW::DisplayBase::_visible [protected, inherited]
Referenced by VW::DisplayGLCommon::InitGL(), VW::DisplayXForms::SetSize(), VW::DisplayX::SetSize(), VW::DisplayGTKGLWidget::SetSize(), VW::DisplayGTKGL::SetSize(), and VW::DisplayGTK::SetSize().
unsigned int VW::DisplayWxGLWidget::_width [protected]
Referenced by DisplayCoordsToPixelCoords(), GetWidth(), OnSize(), Resize(), and SetSize().
int VW::DisplayWxGLWidget::_wx_id [protected]
Referenced by Draw(), OnMouseMove(), and OnMouseUp().
float VW::DisplayGLCommon::_xoffset [protected, inherited]
Referenced by VW::DisplayGLCommon::ConvertToGLCoords(), VW::DisplayGLCommon::ConvertToPixelCoords(), VW::DisplayGLCommon::GetGLCoords(), VW::DisplayGLCommon::GetPixelCoords(), VW::DisplayGLCommon::ResetCoords(), and VW::DisplayGTKGL::SetSize().
float VW::DisplayGLCommon::_xscale [protected, inherited]
Referenced by VW::DisplayGLCommon::ConvertToGLCoords(), VW::DisplayGLCommon::ConvertToPixelCoords(), VW::DisplayGLCommon::GetGLCoords(), VW::DisplayGLCommon::GetPixelCoords(), VW::DisplayGLCommon::ResetCoords(), and VW::DisplayGTKGL::SetSize().
float VW::DisplayGLCommon::_yoffset [protected, inherited]
Referenced by VW::DisplayGLCommon::ConvertToGLCoords(), VW::DisplayGLCommon::ConvertToPixelCoords(), VW::DisplayGLCommon::GetGLCoords(), VW::DisplayGLCommon::GetPixelCoords(), VW::DisplayGLCommon::ResetCoords(), and VW::DisplayGTKGL::SetSize().
float VW::DisplayGLCommon::_yscale [protected, inherited]
Referenced by VW::DisplayGLCommon::ConvertToGLCoords(), VW::DisplayGLCommon::ConvertToPixelCoords(), VW::DisplayGLCommon::GetGLCoords(), VW::DisplayGLCommon::GetPixelCoords(), VW::DisplayGLCommon::ResetCoords(), and VW::DisplayGTKGL::SetSize().
VWEvents::Event3<void,int,int,int> VW::DisplayBase::ClickEvent [inherited]
Referenced by VW::DisplayGTKGL::_HandleClick(), VW::DisplayGTK::_HandleClick(), VW::DisplayGTKWidget::button_release_event_impl(), VW::DisplayGTKGLWidget::button_release_event_impl(), DisplayXFormsCanvasHandler(), VW::DisplayGluteWidget::Mouse(), VW::DisplayGLUT::Mouse(), and OnMouseUp().
VWEvents::Event5<void,int,int,int,int,int> VW::DisplayBase::DragEvent [inherited]
Referenced by VW::DisplayGTKGL::_HandleDrag(), VW::DisplayGTK::_HandleDrag(), DisplayXFormsCanvasHandler(), VW::DisplayGluteWidget::Motion(), VW::DisplayGLUT::Motion(), VW::DisplayGTKWidget::motion_notify_event_impl(), VW::DisplayGTKGLWidget::motion_notify_event_impl(), and OnMouseMove().
VWEvents::Event5<void,int,int,int,int,int> VW::DisplayBase::DragFinishedEvent [inherited]
Referenced by VW::DisplayGTKGL::_HandleDragFinished(), VW::DisplayGTK::_HandleDragFinished(), VW::DisplayGTKWidget::button_release_event_impl(), VW::DisplayGTKGLWidget::button_release_event_impl(), DisplayXFormsCanvasHandler(), VW::DisplayGluteWidget::Mouse(), VW::DisplayGLUT::Mouse(), and OnMouseUp().
bool VW::DisplayGLCommon::dragging [protected, inherited]
Referenced by VW::DisplayGTKGLWidget::button_press_event_impl(), VW::DisplayGTKGLWidget::button_release_event_impl(), and VW::DisplayGTKGLWidget::motion_notify_event_impl().
VWEvents::Event1<void,bool> VW::DisplayWxGLWidget::DrawEvent
The display needs redrawing.
When this signal is emitted the display has already been cleared and the viewpoint set appropriately. The user just needs to draw the scene at the origin.
int VW::DisplayGLCommon::last_x [protected, inherited]
Referenced by VW::DisplayGTKGLWidget::button_press_event_impl(), VW::DisplayGTKGLWidget::button_release_event_impl(), and VW::DisplayGTKGLWidget::motion_notify_event_impl().
int VW::DisplayGLCommon::last_y [protected, inherited]
Referenced by VW::DisplayGTKGLWidget::button_press_event_impl(), VW::DisplayGTKGLWidget::button_release_event_impl(), and VW::DisplayGTKGLWidget::motion_notify_event_impl().
unsigned int VW::DisplayGLCommon::texName [protected, inherited]
Referenced by VW::DisplayGLCommon::GenerateTexture(), VW::DisplayGLCommon::GetTextureName(), and VW::DisplayGLCommon::InitGL().
unsigned int VW::DisplayGLCommon::texture_height [protected, inherited]
Referenced by VW::DisplayGLCommon::GenerateTexture(), VW::DisplayGLCommon::GetTextureHeight(), and VW::DisplayGLCommon::InitGL().
unsigned int VW::DisplayGLCommon::texture_width [protected, inherited]
Referenced by VW::DisplayGLCommon::GenerateTexture(), VW::DisplayGLCommon::GetTextureWidth(), and VW::DisplayGLCommon::InitGL().
The documentation for this class was generated from the following files:
displaywxglwidget.h
displaywxglwidget.cpp