VW: VW::Homography2DComputeGUNSAC Class Reference
VW::Homography2DComputeGUNSAC Class Reference
Compute a homography from two lists of 2D point features using BJT's guided uncertain sampling and consensus method.
#include <homography2dcomputegunsac.h>
Public Member Functions
Homography2DComputeGUNSAC (double image_noise, double search_area, double desired_confidence=99.0)
bool Compute (VW::Homography2D &H, const std::vector< VW::Point2D > &x0, const std::vector< VW::Point2D > &x1, const std::vector< double > &prior, std::vector< double > &posterior)
void SetDesiredConfidence (double desired_confidence)
Set the desired confidence (%).
void SetImageNoise (double image_noise)
Set the expected image noise standard deviation (in pixels).
void SetSearchArea (double search_area)
Set the are searched for each feature.
void SetMaxIterations (unsigned int max_iters)
Set an upper bound on the number of iterations.
Detailed Description
Compute a homography from two lists of 2D point features using BJT's guided uncertain sampling and consensus method.
Constructor & Destructor Documentation
VW::Homography2DComputeGUNSAC::Homography2DComputeGUNSAC (double image_noise, double search_area, double desired_confidence = 99.0) [inline]
Member Function Documentation
bool VW::Homography2DComputeGUNSAC::Compute (VW::Homography2D & H, const std::vector< VW::Point2D > & x0, const std::vector< VW::Point2D > & x1, const std::vector< double > & prior, std::vector< double > & posterior)
References VW::Normalisation::AsMatrix(), VW::Normalisation::GetScale(), VW::FMatrixCompute::GUNSACCore(), VW::Normalisation::InverseMatrix(), VW::Normalisation::Normalise(), and VERBOSE.
void VW::Homography2DComputeGUNSAC::SetDesiredConfidence (double desired_confidence) [inline]
Set the desired confidence (%).
Once this level of confidence is reached sampling will terminate. Note that if max_iters is also set, both will be used.
void VW::Homography2DComputeGUNSAC::SetImageNoise (double image_noise) [inline]
Set the expected image noise standard deviation (in pixels).
This is used to determine the Gaussian model for the inlier process.
void VW::Homography2DComputeGUNSAC::SetMaxIterations (unsigned int max_iters) [inline]
Set an upper bound on the number of iterations.
If not set (or set to zero), sampling will continue until the desired confidence level is reached.
void VW::Homography2DComputeGUNSAC::SetSearchArea (double search_area) [inline]
Set the are searched for each feature.
This determines the uniform distribution used to model the outlier process.
The documentation for this class was generated from the following files:
homography2dcomputegunsac.h
homography2dcomputegunsac.cpp