VW: VW::ImageBase< PixelType, PixelPtr > Class Template Reference
VW::ImageBase< PixelType, PixelPtr > Class Template Reference
[Image]
The base class from which all images are made.
#include <imagebase.h>
Public Member Functions
ImageBase (const unsigned int w, const unsigned int h)
Construct and allocate data storage.
ImageBase (PixelType *data, const unsigned int w, const unsigned int h)
Construct using pre-specified data storage (eg for wrapping another image class's data).
ImageBase ()
Construct without allocating storage.
virtual ~ImageBase ()
void AllocImageData (const unsigned int w, const unsigned int h)
Allocate the image data array.
void SetImageData (PixelType *data, const unsigned int w, const unsigned int h)
Allocate the image data array using some existing data.
void FreeImageData ()
De-allocate the image data array.
bool IsAlloced () const
Is the image data array allocated?
void GetSize (unsigned int &w, unsigned int &h) const
Get width and height in a single command.
unsigned int GetWidth (void) const
Determine the width of the image in pixels.
unsigned int GetHeight (void) const
Determine the height of the image in pixels.
void SetROI (const VW::ROI &new_roi)
Set the region of interest (ROI) of the image.
VW::ROI & ROI ()
Copy of the region of interest (ROI) of the image.
const VW::ROI & ROI () const
Constant reference to the region of interest (ROI) of the image.
void ResetROI ()
Set the ROI to be the whole image.
PixelType * GetImageBuffer (void) const
Get a pointer to the first pixel in the data array.
void * GetRawBuffer (void) const
Get a pointer to the first memory location used in the data array.
PixelType GetPixel (const int c, const int r) const
Recover (copy) the pixel at column c, row r.
void SetPixel (const int c, const int r, const PixelType &new_value)
Set the pixel at column c, row r.
PixelPtr GetRowStart (int r) const
PixelPtr * GetRowPointer (int r) const
PixelPtr operator[] (int r) const
PixelPtr GetROIRowStart (int r) const
void Clear (const PixelType &new_value=PixelType())
Set the whole image to a particular value.
bool ReadImage (const std::string &filename)
Read a standard image format from disk.
bool WriteImage (const std::string &filename) const
Write a standard image format to disk.
void FlipHorizontal ()
Flip the image horizontally (size preserved).
void FlipVertical ()
Flip the image vertically (size preserved).
void ExchangeData (ImageBase< PixelType, PixelPtr > &other)
Swap this image's data for other image data - size, ROI etc are also exchanged.
bool ReadBinary (std::istream &stream)
Read the image from a stream in the internal VW format.
bool WriteBinary (std::ostream &stream) const
Write the image to a stream in the internal VW format.
PixelType operator() (int r) const
Get the pixel at the start of row r.
PixelType operator() (int r, int c)
Recover a pixel (note y,x NOT x,y).
void SetPenColour (const PixelType &colour)
For drawing, the image has a pen colour much like a display.
PixelType GetPenColour () const
Return the current pen colour.
void DrawLine (const double x0, const double y0, const double x1, const double y1)
Public Attributes
PixelPtr * pixel
Pointers to the start of each row.
Protected Member Functions
virtual void GetFormatStrings (std::string &format, std::string &type) const =0
Return strings describing the format of image data.
ImageBase & operator= (const ImageBase &im)
Operator= is dangerous and has been disabled.
ImageBase (const ImageBase &)
The copy constructor is dangerous and has been disabled.
void _CreateRowPointers ()
Protected Attributes
unsigned int _width
unsigned int _height
VW::ROI _roi
PixelType * _data
bool _dataalloced
bool _rowsalloced
PixelType _pen_colour
Detailed Description
template<class PixelType, class PixelPtr>
class VW::ImageBase< PixelType, PixelPtr >
The base class from which all images are made.
Author:
ID Reid, BJ Tordoff
Date:
02/08/02 The base image class provides much of the functionality for the specific image classes, but more importantly as an abstract class enforces consistency between them. All images contain a RIO (region of interest) which specifies which region of the image is valid (many convolutions and similar leave a border of unprocessed pixels), and when designing algorithms one should work only inside the specified ROI.
Note that the '=' operator is deliberately disabled for all image classes to prevent nasty accidents. If you really need to copy an image, use one of the ImageCopy functions provided.
IO can be performed on a range of standard image formats using the ReadImage() and WriteImage() functions, or, in order to preserve all attributes with the Read/WriteBinary() functions. The latter pair use an internal format which is similar to the PPM raw format, ie type and size are specified in plain text and pixel data as binary. Note that when reading a raw VW image the format (RGB, YUV etc), type (Char, UChar, Double etc) and size must match exactly - no conversion will be performed.
Constructor & Destructor Documentation
template<class PixelType , class PixelPtr > VW::ImageBase< PixelType, PixelPtr >::ImageBase (const unsigned int w, const unsigned int h) [inline]
Construct and allocate data storage.
Parameters:
w desired width (in pixels) of the image
h desired height (in pixels) of the image
template<class PixelType, class PixelPtr > VW::ImageBase< PixelType, PixelPtr >::ImageBase (PixelType * data, const unsigned int w, const unsigned int h) [inline]
Construct using pre-specified data storage (eg for wrapping another image class's data).
Note that the format of the data must match the target pixel format but no checks are made.
Parameters:
addr the start of the memory array containing the image data
w width (in pixels) of the data array
h height (in pixels) of the data array
template<class PixelType, class PixelPtr > VW::ImageBase< PixelType, PixelPtr >::ImageBase () [inline]
Construct without allocating storage.
Storage space will be allocated automatically when an image is read from a file or stream, or must otherwise by created using the AllocImageData() function.
template<class PixelType , class PixelPtr > VW::ImageBase< PixelType, PixelPtr >::~ImageBase () [inline, virtual]
template<class PixelType, class PixelPtr > VW::ImageBase< PixelType, PixelPtr >::ImageBase (const ImageBase< PixelType, PixelPtr > &) [inline, protected]
The copy constructor is dangerous and has been disabled.
(See the ImageConversions functions if you really need to copy an image)
Member Function Documentation
template<class PixelType , class PixelPtr > void VW::ImageBase< PixelType, PixelPtr >::_CreateRowPointers () [inline, protected]
References VW::ImageBase< PixelType, PixelPtr >::_data, VW::ImageBase< PixelType, PixelPtr >::_height, VW::ImageBase< PixelType, PixelPtr >::_rowsalloced, VW::ImageBase< PixelType, PixelPtr >::_width, and VW::ImageBase< PixelType, PixelPtr >::pixel.
Referenced by VW::ImageBase< PixelType, PixelPtr >::ExchangeData().
template<class PixelType , class PixelPtr > void VW::ImageBase< PixelType, PixelPtr >::AllocImageData (const unsigned int w, const unsigned int h) [inline]
Allocate the image data array.
Parameters:
w the width of array (number of columns) to allocate
h the height of array (number of rows) to allocate
Referenced by VW::HistogramEqualisation::ApplyToImage(), VW::ClassifierUV::Classify(), VW::RadialDistortion::DistortImage(), VW::ThreeDToolGLCommon::GetImage(), VW::ClassifierUV::GetProbImage(), VW::ReadJPEGImage(), and VW::RadialDistortion::UndistortImage().
template<class PixelType, class PixelPtr > void VW::ImageBase< PixelType, PixelPtr >::Clear (const PixelType & new_value = PixelType()) [inline]
Set the whole image to a particular value.
Fill the entire image with a pixel value.
template<class PixelType , class PixelPtr > void VW::ImageBase< PixelType, PixelPtr >::DrawLine (const double x0, const double y0, const double x1, const double y1) [inline]
References VW::ImageBase< PixelType, PixelPtr >::_pen_colour, VW::ImageBase< PixelType, PixelPtr >::pixel, and std::sqrt().
template<class PixelType, class PixelPtr> void VW::ImageBase< PixelType, PixelPtr >::ExchangeData (ImageBase< PixelType, PixelPtr > & other) [inline]
Swap this image's data for other image data - size, ROI etc are also exchanged.
This is handy to avoid an image copy when doing things like:
void MyFunc(ImageXXX& im) { VW::ImageXXX result; DoSomeProcessing(im,result); im.ExchangeData(result); }
which would otherwise require a copy of the result data back to the original.
References VW::ImageBase< PixelType, PixelPtr >::_CreateRowPointers(), VW::ImageBase< PixelType, PixelPtr >::_data, VW::ImageBase< PixelType, PixelPtr >::_dataalloced, VW::ImageBase< PixelType, PixelPtr >::_height, VW::ImageBase< PixelType, PixelPtr >::_roi, and VW::ImageBase< PixelType, PixelPtr >::_width.
template<class PixelType , class PixelPtr > void VW::ImageBase< PixelType, PixelPtr >::FlipHorizontal () [inline]
Flip the image horizontally (size preserved).
References VW::ImageBase< PixelType, PixelPtr >::_data, VW::ImageBase< PixelType, PixelPtr >::_height, VW::ImageBase< PixelType, PixelPtr >::_width, VW::ImageBase< PixelType, PixelPtr >::IsAlloced(), and VW::ImageBase< PixelType, PixelPtr >::pixel.
template<class PixelType , class PixelPtr > void VW::ImageBase< PixelType, PixelPtr >::FlipVertical () [inline]
Flip the image vertically (size preserved).
References VW::ImageBase< PixelType, PixelPtr >::_data, VW::ImageBase< PixelType, PixelPtr >::_height, VW::ImageBase< PixelType, PixelPtr >::_width, VW::ImageBase< PixelType, PixelPtr >::IsAlloced(), and VW::ImageBase< PixelType, PixelPtr >::pixel.
template<class PixelType , class PixelPtr > void VW::ImageBase< PixelType, PixelPtr >::FreeImageData () [inline]
De-allocate the image data array.
Once freed, storage space will be reallocated automatically when an image is read from a file or stream, or must otherwise by created using the AllocImageData() function.
Referenced by VW::HistogramEqualisation::ApplyToImage().
template<class PixelType, class PixelPtr> virtual void VW::ImageBase< PixelType, PixelPtr >::GetFormatStrings (std::string & format, std::string & type) const [protected, pure virtual]
Return strings describing the format of image data.
This must be overloaded on a per-type basis.
Implemented in VW::ImageHSV< Type >, VW::ImageMono< Type >, VW::ImageRGB< Type >, VW::ImageYUV< Type >, VW::ImageMono< unsigned char >, VW::ImageMono< TMP_TYPE >, VW::ImageHSV< Type >, VW::ImageHSV< Type >, VW::ImageMono< Type >, VW::ImageMono< Type >, VW::ImageMono< Type >, VW::ImageMono< Type >, VW::ImageRGB< Type >, VW::ImageRGB< Type >, VW::ImageRGB< Type >, VW::ImageYUV< Type >, VW::ImageYUV< Type >, VW::ImageYUV< Type >, VW::ImageYUV< Type >, and VW::ImageYUV< Type >.
template<class PixelType , class PixelPtr > unsigned int VW::ImageBase< PixelType, PixelPtr >::GetHeight (void) const [inline]
Determine the height of the image in pixels.
Returns:
the height (number of rows) of the image
Referenced by VW::ThreeDToolGLCommon::ActuallyDrawDistortedTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawWarpedTexturedRectangle(), VW::HistogramEqualisation::AddImage(), VW::HistogramEqualisation::ApplyToImage(), VW::ClassifierUV::Classify(), VW::PlesseyOld::Compute(), VW::PlesseyDetector::Compute(), VW::DOGDetector::Compute(), VW::ChamferDistance::Compute(), VW::Canny::Compute(), VW::RadialDistortion::DistortImage(), VW::DrawFunctions::Draw(), VW::ThreeDToolGLCommon::Draw2DTexturedRectangle(), VW::ThreeDToolGLCommon::GetImage(), VW::ClassifierUV::GetProbImage(), VW::ReadJPEGImage(), VW::RadialDistortion::UndistortImage(), VW::ImageConversions::VWImage_to_RGBABuffer(), VW::ImageConversions::VWImage_to_RGBBuffer(), and VW::WriteJPEGImage().
template<class PixelType , class PixelPtr > PixelType * VW::ImageBase< PixelType, PixelPtr >::GetImageBuffer (void) const [inline]
Get a pointer to the first pixel in the data array.
The array is stored in row-major form, and can be traversed using pointer arithmatic, eg: const unsigned int num_pix = im.GetWidth() * im.GetHeight(); PixelType* p = im.GetImageBuffer(); for (unsigned int i=0; i<num_pix; i++,p++) { p->ScaleIntensity(0.5); }
template<class PixelType , class PixelPtr > PixelType VW::ImageBase< PixelType, PixelPtr >::GetPenColour () const [inline]
Return the current pen colour.
References VW::ImageBase< PixelType, PixelPtr >::_pen_colour.
template<class PixelType , class PixelPtr > PixelType VW::ImageBase< PixelType, PixelPtr >::GetPixel (const int c, const int r) const [inline]
Recover (copy) the pixel at column c, row r.
If VW is compiled in debug mode, this function is range-checked.
Parameters:
c the column index (0<c<width)
r the row index (0<r<height)
Returns:
a copy of the pixel (so changes to this pixel will not affect the underlying image)
References c.
Referenced by VW::RadialDistortion::DistortImage(), VW::DrawFunctions::Draw(), VW::GetImagePatch(), VW::GetInterpolatedImagePatch(), and VW::RadialDistortion::UndistortImage().
template<class PixelType , class PixelPtr > void * VW::ImageBase< PixelType, PixelPtr >::GetRawBuffer (void) const [inline]
Get a pointer to the first memory location used in the data array.
As this returns a void*, you can cast it to any type you like, with the usual pitfalls that this entails if the pointer type doesn't match the type of the data stored.
Referenced by VW::ThreeDToolGLCommon::ActuallyDrawDistortedTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawWarpedTexturedRectangle(), VW::ImageConversions::BGRABuffer_to_VWImage(), VW::ClassifierUV::Classify(), VW::DrawFunctions::Draw(), VW::ThreeDToolGLCommon::Draw2DTexturedRectangle(), VW::ClassifierUV::GetProbImage(), VW::ImageConversions::Interlaced4Buffer_to_VWImage(), VW::ImageConversions::MonoBuffer_to_VWImage(), VW::ImageConversions::RGBBuffer_to_VWImage(), VW::ImageConversions::VWImage_to_RGBABuffer(), VW::ImageConversions::VWImage_to_RGBBuffer(), VW::ImageConversions::YUV422Buffer_to_VWImage(), and VW::ImageConversions::YUV444Buffer_to_VWImage().
template<class PixelType , class PixelPtr > PixelPtr VW::ImageBase< PixelType, PixelPtr >::GetROIRowStart (int r) const [inline]
template<class PixelType , class PixelPtr > PixelPtr * VW::ImageBase< PixelType, PixelPtr >::GetRowPointer (int r) const [inline]
template<class PixelType , class PixelPtr > PixelPtr VW::ImageBase< PixelType, PixelPtr >::GetRowStart (int r) const [inline]
Referenced by VW::HistogramEqualisation::AddImage(), VW::HistogramEqualisation::ApplyToImage(), VW::ChamferDistance::Compute(), VW::Canny::Compute(), VW::RadialDistortion::DistortImage(), VW::DrawFunctions::Draw(), VW::ReadJPEGImage(), VW::RadialDistortion::UndistortImage(), and VW::WriteJPEGImage().
template<class PixelType , class PixelPtr > void VW::ImageBase< PixelType, PixelPtr >::GetSize (unsigned int & w, unsigned int & h) const [inline]
Get width and height in a single command.
Parameters:
w will be set to the width (number of columns)
h will be set to the height (number of rows)
template<class PixelType , class PixelPtr > unsigned int VW::ImageBase< PixelType, PixelPtr >::GetWidth (void) const [inline]
Determine the width of the image in pixels.
Returns:
the width (number of columns) of the image
Referenced by VW::ThreeDToolGLCommon::ActuallyDrawDistortedTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawWarpedTexturedRectangle(), VW::HistogramEqualisation::AddImage(), VW::HistogramEqualisation::ApplyToImage(), VW::ClassifierUV::Classify(), VW::PlesseyOld::Compute(), VW::PlesseyDetector::Compute(), VW::DOGDetector::Compute(), VW::ChamferDistance::Compute(), VW::Canny::Compute(), VW::RadialDistortion::DistortImage(), VW::DrawFunctions::Draw(), VW::ThreeDToolGLCommon::Draw2DTexturedRectangle(), VW::ThreeDToolGLCommon::GetImage(), VW::ClassifierUV::GetProbImage(), VW::ReadJPEGImage(), VW::RadialDistortion::UndistortImage(), VW::ImageConversions::VWImage_to_RGBABuffer(), VW::ImageConversions::VWImage_to_RGBBuffer(), and VW::WriteJPEGImage().
template<class PixelType , class PixelPtr > bool VW::ImageBase< PixelType, PixelPtr >::IsAlloced () const [inline]
Is the image data array allocated?
Returns:
true if data array exists
Referenced by VW::HistogramEqualisation::ApplyToImage(), VW::ClassifierUV::Classify(), VW::PlesseyDetector::Compute(), VW::RadialDistortion::DistortImage(), VW::DrawFunctions::Draw(), VW::ImageBase< PixelType, PixelPtr >::FlipHorizontal(), VW::ImageBase< PixelType, PixelPtr >::FlipVertical(), VW::ThreeDToolGLCommon::GetImage(), VW::ClassifierUV::GetProbImage(), VW::ReadJPEGImage(), and VW::RadialDistortion::UndistortImage().
template<class PixelType , class PixelPtr > PixelType VW::ImageBase< PixelType, PixelPtr >::operator() (int r, int c) [inline]
Recover a pixel (note y,x NOT x,y).
This function is not range-checked.
Parameters:
r the row number (y coord) of the pixel
c the column number (x coord) of the pixel
Returns:
the pixel value at this position
References VW::ImageBase< PixelType, PixelPtr >::pixel.
template<class PixelType , class PixelPtr > PixelType VW::ImageBase< PixelType, PixelPtr >::operator() (int r) const [inline]
Get the pixel at the start of row r.
This function is not range checked.
Parameters:
r the row number (y coord) of the pixel
Returns:
the pixel value at the start of this row
References VW::ImageBase< PixelType, PixelPtr >::pixel.
template<class PixelType , class PixelPtr > VW::ImageBase< PixelType, PixelPtr > & VW::ImageBase< PixelType, PixelPtr >::operator= (const ImageBase< PixelType, PixelPtr > & im) [inline, protected]
Operator= is dangerous and has been disabled.
(See the ImageConversions functions if you really need to copy an image)
template<class PixelType , class PixelPtr > PixelPtr VW::ImageBase< PixelType, PixelPtr >::operator[] (int r) const [inline]
template<class PixelType , class PixelPtr > bool VW::ImageBase< PixelType, PixelPtr >::ReadBinary (std::istream & stream) [inline]
Read the image from a stream in the internal VW format.
This format is strongly related to the raw PPM format, but keeps the byte ordering and alpha values of the image class used. The image format and data type are written in plain text before the data, stored as binary.
Parameters:
stream the input stream into which the image data will be written
References c.
template<class PixelType , class PixelPtr > bool VW::ImageBase< PixelType, PixelPtr >::ReadImage (const std::string & filename) [inline]
Read a standard image format from disk.
The type of file is determined by the name extension (how very Windows...)
Parameters:
filename the name of the image file to load (can be relative or absolute)
Returns:
true if the image was loaded successfully
Reimplemented in VW::ImageHSV< Type >, VW::ImageInterleave< Type, Skip >, VW::ImageMono< Type >, VW::ImageRGB< Type >, VW::ImageYUV< Type >, VW::ImageMono< unsigned char >, and VW::ImageMono< TMP_TYPE >.
template<class PixelType , class PixelPtr > void VW::ImageBase< PixelType, PixelPtr >::ResetROI () [inline]
Set the ROI to be the whole image.
Reset the region of interest to be the whole image.
References VW::ImageBase< PixelType, PixelPtr >::_height, VW::ImageBase< PixelType, PixelPtr >::_roi, VW::ImageBase< PixelType, PixelPtr >::_width, and VW::ROI::Set().
template<class PixelType , class PixelPtr > const VW::ROI & VW::ImageBase< PixelType, PixelPtr >::ROI () const [inline]
Constant reference to the region of interest (ROI) of the image.
Returns:
the current region of interest in the image.
template<class PixelType , class PixelPtr > VW::ROI & VW::ImageBase< PixelType, PixelPtr >::ROI () [inline]
Copy of the region of interest (ROI) of the image.
Returns:
the current region of interest in the image. Reference to the region of interest (ROI) of the image.
the current region of interest in the image.
Referenced by VW::GetPlesseyCorner::GetPlesseyCorner().
template<class PixelType, class PixelPtr > void VW::ImageBase< PixelType, PixelPtr >::SetImageData (PixelType * data, const unsigned int w, const unsigned int h) [inline]
Allocate the image data array using some existing data.
Parameters:
data the memory location of the existing data array
w the width of array (number of columns) to allocate
h the height of array (number of rows) to allocate
template<class PixelType, class PixelPtr > void VW::ImageBase< PixelType, PixelPtr >::SetPenColour (const PixelType & colour) [inline]
For drawing, the image has a pen colour much like a display.
References VW::ImageBase< PixelType, PixelPtr >::_pen_colour.
template<class PixelType, class PixelPtr > void VW::ImageBase< PixelType, PixelPtr >::SetPixel (const int c, const int r, const PixelType & new_value) [inline]
Set the pixel at column c, row r.
If VW is compiled in debug mode, this function is range-checked.
Parameters:
c the column index (0<c<width)
r the row index (0<r<height)
new_value the new data for this pixel
References c.
template<class PixelType , class PixelPtr > void VW::ImageBase< PixelType, PixelPtr >::SetROI (const VW::ROI & new_roi) [inline]
Set the region of interest (ROI) of the image.
Parameters:
new_roi the new region of interest to use.
template<class PixelType , class PixelPtr > bool VW::ImageBase< PixelType, PixelPtr >::WriteBinary (std::ostream & stream) const [inline]
Write the image to a stream in the internal VW format.
This format is strongly related to the raw PPM format, but keeps the byte ordering and alpha values of the image class used. The image format and data type are written in plain text before the data, stored as binary.
template<class PixelType , class PixelPtr > bool VW::ImageBase< PixelType, PixelPtr >::WriteImage (const std::string & filename) const [inline]
Write a standard image format to disk.
The type of file is determined by the name extension (how very Windows...)
Parameters:
filename the name of the image file to save (can be relative or absolute)
Returns:
true if the image was saved successfully
Reimplemented in VW::ImageHSV< Type >, VW::ImageInterleave< Type, Skip >, VW::ImageMono< Type >, VW::ImageRGB< Type >, VW::ImageYUV< Type >, VW::ImageMono< unsigned char >, and VW::ImageMono< TMP_TYPE >.
Member Data Documentation
template<class PixelType, class PixelPtr> PixelType* VW::ImageBase< PixelType, PixelPtr >::_data [protected]
Referenced by VW::ImageBase< PixelType, PixelPtr >::_CreateRowPointers(), VW::ImageBase< PixelType, PixelPtr >::ExchangeData(), VW::ImageBase< PixelType, PixelPtr >::FlipHorizontal(), and VW::ImageBase< PixelType, PixelPtr >::FlipVertical().
template<class PixelType, class PixelPtr> bool VW::ImageBase< PixelType, PixelPtr >::_dataalloced [protected]
Referenced by VW::ImageBase< PixelType, PixelPtr >::ExchangeData().
template<class PixelType, class PixelPtr> unsigned int VW::ImageBase< PixelType, PixelPtr >::_height [protected]
Referenced by VW::ImageBase< PixelType, PixelPtr >::_CreateRowPointers(), VW::ImageBase< PixelType, PixelPtr >::ExchangeData(), VW::ImageBase< PixelType, PixelPtr >::FlipHorizontal(), VW::ImageBase< PixelType, PixelPtr >::FlipVertical(), and VW::ImageBase< PixelType, PixelPtr >::ResetROI().
template<class PixelType, class PixelPtr> PixelType VW::ImageBase< PixelType, PixelPtr >::_pen_colour [protected]
Referenced by VW::ImageBase< PixelType, PixelPtr >::DrawLine(), VW::ImageBase< PixelType, PixelPtr >::GetPenColour(), and VW::ImageBase< PixelType, PixelPtr >::SetPenColour().
template<class PixelType, class PixelPtr> VW::ROI VW::ImageBase< PixelType, PixelPtr >::_roi [protected]
Referenced by VW::ImageBase< PixelType, PixelPtr >::ExchangeData(), and VW::ImageBase< PixelType, PixelPtr >::ResetROI().
template<class PixelType, class PixelPtr> bool VW::ImageBase< PixelType, PixelPtr >::_rowsalloced [protected]
Referenced by VW::ImageBase< PixelType, PixelPtr >::_CreateRowPointers().
template<class PixelType, class PixelPtr> unsigned int VW::ImageBase< PixelType, PixelPtr >::_width [protected]
Referenced by VW::ImageBase< PixelType, PixelPtr >::_CreateRowPointers(), VW::ImageBase< PixelType, PixelPtr >::ExchangeData(), VW::ImageBase< PixelType, PixelPtr >::FlipHorizontal(), VW::ImageBase< PixelType, PixelPtr >::FlipVertical(), and VW::ImageBase< PixelType, PixelPtr >::ResetROI().
template<class PixelType, class PixelPtr> PixelPtr* VW::ImageBase< PixelType, PixelPtr >::pixel
Pointers to the start of each row.
A pointer to the start of the row r is given by image.pixel[r], and a pixel at row r, column c, by image.pixel[r][c]. This is functionally identical to saying image[r][c], but in some circumstances may be faster.
Referenced by VW::ImageBase< PixelType, PixelPtr >::_CreateRowPointers(), VW::ImageBase< PixelType, PixelPtr >::DrawLine(), VW::ImageBase< PixelType, PixelPtr >::FlipHorizontal(), VW::ImageBase< PixelType, PixelPtr >::FlipVertical(), and VW::ImageBase< PixelType, PixelPtr >::operator()().
The documentation for this class was generated from the following file:
imagebase.h