VW: VNL::SymMatrix< T > Class Template Reference
VNL::SymMatrix< T > Class Template Reference
stores a symmetric matrix as just the diagonal and lower triangular part.
#include <symmatrix.h>
Public Types
typedef T * iterator
typedef const T * const_iterator
Public Member Functions
SymMatrix ()
Construct an empty symmetic matrix.
SymMatrix (unsigned nn)
Construct an symmetic matrix of size nn by nn.
SymMatrix (T const *data, unsigned nn)
Construct a symmetric matrix with elements equal to data.
SymMatrix (unsigned nn, const T &value)
Construct a symmetric matrix with all elements equal to value.
SymMatrix (VNL::Matrix< T > const &that)
Construct a symmetric matrix from a full matrix.
~SymMatrix ()
SymMatrix< T > & operator= (SymMatrix< T > const &that)
SymMatrix< T > & operator*= (T v)
In-place arithmetic operations.
SymMatrix< T > & operator/= (T v)
In-place arithmetic operations.
T operator() (unsigned i, unsigned j) const
T & operator() (unsigned i, unsigned j)
const T * operator[] (unsigned i) const
Access a half-row of data.
T Fast (unsigned i, unsigned j) const
fast access, however i >= j.
T & Fast (unsigned i, unsigned j)
fast access, however i >= j.
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
unsigned long size () const
unsigned long Size () const
unsigned Rows () const
unsigned Cols () const
unsigned Columns () const
Matrix< T > AsMatrix () const
Convert a SymMatrix to a Matrix.
void Resize (int n)
Resize matrix to n by n.
T * DataBlock ()
Return pointer to the lower triangular elements as a contiguous 1D C array;.
T const * DataBlock () const
Return pointer to the lower triangular elements as a contiguous 1D C array;.
void SetHalfRow (const VNL::Vector< T > &half_row, unsigned i)
Set the first i values of row i.
SymMatrix< T > & Update (SymMatrix< T > const &m, unsigned diag_start=0)
Replaces the symmetric submatrix of THIS matrix with the elements of matrix m.
void Swap (SymMatrix &m)
Swap contents of m with THIS.
Protected Member Functions
void _SetupIndex ()
Set up the index array.
Protected Attributes
T * data_
T ** index_
unsigned nn_
Detailed Description
template<class T>
class VNL::SymMatrix< T >
stores a symmetric matrix as just the diagonal and lower triangular part.
vnl_sym_matrix stores a symmetric matrix for time and space efficiency. Specifically, only the diagonal and lower triangular elements are stored.
Member Typedef Documentation
template<class T> typedef const T* VNL::SymMatrix< T >::const_iterator
template<class T> typedef T* VNL::SymMatrix< T >::iterator
Constructor & Destructor Documentation
template<class T> VNL::SymMatrix< T >::SymMatrix () [inline]
Construct an empty symmetic matrix.
template<class T> VNL::SymMatrix< T >::SymMatrix (unsigned nn) [inline, explicit]
Construct an symmetic matrix of size nn by nn.
References VNL::SymMatrix< T >::_SetupIndex().
template<class T > VNL::SymMatrix< T >::SymMatrix (T const * data, unsigned nn) [inline]
Construct a symmetric matrix with elements equal to data.
value should be stored row-wise, and contrain the n*(n+1)/2 diagonal and lower triangular elements
References VNL::SymMatrix< T >::_SetupIndex(), VNL::SymMatrix< T >::Fast(), and VNL::SymMatrix< T >::nn_.
template<class T > VNL::SymMatrix< T >::SymMatrix (unsigned nn, const T & value) [inline]
Construct a symmetric matrix with all elements equal to value.
References VNL::SymMatrix< T >::_SetupIndex(), VNL::SymMatrix< T >::data_, and VNL::SymMatrix< T >::size().
template<class T > VNL::SymMatrix< T >::SymMatrix (VNL::Matrix< T > const & that) [inline, explicit]
Construct a symmetric matrix from a full matrix.
If NDEBUG is set, the symmetry of the matrix will be asserted.
References VNL::SymMatrix< T >::_SetupIndex(), VNL::Matrix< T >::Cols(), VNL::SymMatrix< T >::Fast(), and VNL::SymMatrix< T >::nn_.
template<class T> VNL::SymMatrix< T >::~SymMatrix () [inline]
References VNL::SymMatrix< T >::data_, VNL::SymMatrix< T >::index_, VNL::SymMatrix< T >::nn_, and VNL::SymMatrix< T >::size().
Member Function Documentation
template<class T> void VNL::SymMatrix< T >::_SetupIndex () [inline, protected]
Set up the index array.
References VNL::SymMatrix< T >::data_, VNL::SymMatrix< T >::index_, and VNL::SymMatrix< T >::nn_.
Referenced by VNL::SymMatrix< T >::Resize(), and VNL::SymMatrix< T >::SymMatrix().
template<class T > VNL::Matrix< T > VNL::SymMatrix< T >::AsMatrix () const [inline]
Convert a SymMatrix to a Matrix.
References VNL::SymMatrix< T >::Fast(), and VNL::SymMatrix< T >::nn_.
template<class T> const_iterator VNL::SymMatrix< T >::begin () const [inline]
References VNL::SymMatrix< T >::data_.
template<class T> iterator VNL::SymMatrix< T >::begin () [inline]
References VNL::SymMatrix< T >::data_.
template<class T> unsigned VNL::SymMatrix< T >::Cols () const [inline]
References VNL::SymMatrix< T >::nn_.
Referenced by operator==().
template<class T> unsigned VNL::SymMatrix< T >::Columns () const [inline]
References VNL::SymMatrix< T >::nn_.
template<class T> T const* VNL::SymMatrix< T >::DataBlock () const [inline]
Return pointer to the lower triangular elements as a contiguous 1D C array;.
References VNL::SymMatrix< T >::data_.
template<class T> T* VNL::SymMatrix< T >::DataBlock () [inline]
Return pointer to the lower triangular elements as a contiguous 1D C array;.
References VNL::SymMatrix< T >::data_.
Referenced by operator==().
template<class T> const_iterator VNL::SymMatrix< T >::end () const [inline]
References VNL::SymMatrix< T >::data_, and VNL::SymMatrix< T >::size().
template<class T> iterator VNL::SymMatrix< T >::end () [inline]
References VNL::SymMatrix< T >::data_, and VNL::SymMatrix< T >::size().
Referenced by VNL::SymMatrix< T >::Update().
template<class T> T& VNL::SymMatrix< T >::Fast (unsigned i, unsigned j) [inline]
fast access, however i >= j.
References VNL::SymMatrix< T >::index_.
template<class T> T VNL::SymMatrix< T >::Fast (unsigned i, unsigned j) const [inline]
fast access, however i >= j.
References VNL::SymMatrix< T >::index_.
Referenced by VNL::SymMatrix< T >::AsMatrix(), operator==(), VNL::SymMatrix< T >::SymMatrix(), and VNL::SymMatrix< T >::Update().
template<class T> T& VNL::SymMatrix< T >::operator() (unsigned i, unsigned j) [inline]
References VNL::SymMatrix< T >::index_.
template<class T> T VNL::SymMatrix< T >::operator() (unsigned i, unsigned j) const [inline]
References VNL::SymMatrix< T >::index_.
template<class T> SymMatrix<T>& VNL::SymMatrix< T >::operator*= (T v) [inline]
In-place arithmetic operations.
References VNL::SymMatrix< T >::data_, and VNL::SymMatrix< T >::size().
template<class T> SymMatrix<T>& VNL::SymMatrix< T >::operator/= (T v) [inline]
In-place arithmetic operations.
References VNL::SymMatrix< T >::data_, and VNL::SymMatrix< T >::size().
template<class T > VNL::SymMatrix< T > & VNL::SymMatrix< T >::operator= (VNL::SymMatrix< T > const & that) [inline]
References VNL::SymMatrix< T >::Resize(), VNL::SymMatrix< T >::Rows(), and VNL::SymMatrix< T >::Update().
template<class T> const T* VNL::SymMatrix< T >::operator[] (unsigned i) const [inline]
Access a half-row of data.
Only the first i+1 values from this pointer are valid.
References VNL::SymMatrix< T >::index_, and VNL::SymMatrix< T >::nn_.
template<class T > void VNL::SymMatrix< T >::Resize (int n) [inline]
Resize matrix to n by n.
References VNL::SymMatrix< T >::_SetupIndex(), VNL::SymMatrix< T >::data_, VNL::SymMatrix< T >::index_, VNL::SymMatrix< T >::nn_, and VNL::SymMatrix< T >::size().
Referenced by VNL::SymMatrix< T >::operator=().
template<class T> unsigned VNL::SymMatrix< T >::Rows () const [inline]
References VNL::SymMatrix< T >::nn_.
Referenced by VNL::SymMatrix< T >::operator=(), operator==(), and VNL::SymMatrix< T >::SetHalfRow().
template<class T > void VNL::SymMatrix< T >::SetHalfRow (const VNL::Vector< T > & half_row, unsigned i) [inline]
Set the first i values of row i.
or the top i values of column i
References VNL::Vector< T >::CopyOut(), VNL::ErrorVectorDimension(), VNL::SymMatrix< T >::index_, VNL::SymMatrix< T >::nn_, VNL::SymMatrix< T >::Rows(), and VNL::Vector< T >::size().
template<class T> unsigned long VNL::SymMatrix< T >::Size () const [inline]
References VNL::SymMatrix< T >::nn_.
template<class T> unsigned long VNL::SymMatrix< T >::size () const [inline]
References VNL::SymMatrix< T >::nn_.
Referenced by VNL::SymMatrix< T >::end(), VNL::SymMatrix< T >::operator*=(), VNL::SymMatrix< T >::operator/=(), operator==(), VNL::SymMatrix< T >::Resize(), VNL::SymMatrix< T >::SymMatrix(), and VNL::SymMatrix< T >::~SymMatrix().
template<class T > void VNL::SymMatrix< T >::Swap (SymMatrix< T > & m) [inline]
Swap contents of m with THIS.
References VNL::SymMatrix< T >::data_, VNL::SymMatrix< T >::index_, and VNL::SymMatrix< T >::nn_.
Referenced by Swap().
template<class T > VNL::SymMatrix< T > & VNL::SymMatrix< T >::Update (VNL::SymMatrix< T > const & m, unsigned diagonal_start = 0) [inline]
Replaces the symmetric submatrix of THIS matrix with the elements of matrix m.
Replaces the symetric submatrix of THIS matrix, starting at top left corner, by the elements of matrix m.
Starting at top left corner. Complexity is .
O(m*m).
References VNL::SymMatrix< T >::end(), VNL::ErrorMatrixDimension(), VNL::SymMatrix< T >::Fast(), and VNL::SymMatrix< T >::nn_.
Referenced by VNL::SymMatrix< T >::operator=().
Member Data Documentation
template<class T> T* VNL::SymMatrix< T >::data_ [protected]
Referenced by VNL::SymMatrix< T >::_SetupIndex(), VNL::SymMatrix< T >::begin(), VNL::SymMatrix< T >::DataBlock(), VNL::SymMatrix< T >::end(), VNL::SymMatrix< T >::operator*=(), VNL::SymMatrix< T >::operator/=(), VNL::SymMatrix< T >::Resize(), VNL::SymMatrix< T >::Swap(), VNL::SymMatrix< T >::SymMatrix(), and VNL::SymMatrix< T >::~SymMatrix().
template<class T> T** VNL::SymMatrix< T >::index_ [protected]
Referenced by VNL::SymMatrix< T >::_SetupIndex(), VNL::SymMatrix< T >::Fast(), VNL::SymMatrix< T >::operator()(), VNL::SymMatrix< T >::operator[](), VNL::SymMatrix< T >::Resize(), VNL::SymMatrix< T >::SetHalfRow(), VNL::SymMatrix< T >::Swap(), and VNL::SymMatrix< T >::~SymMatrix().
template<class T> unsigned VNL::SymMatrix< T >::nn_ [protected]
Referenced by VNL::SymMatrix< T >::_SetupIndex(), VNL::SymMatrix< T >::AsMatrix(), VNL::SymMatrix< T >::Cols(), VNL::SymMatrix< T >::Columns(), VNL::SymMatrix< T >::operator[](), VNL::SymMatrix< T >::Resize(), VNL::SymMatrix< T >::Rows(), VNL::SymMatrix< T >::SetHalfRow(), VNL::SymMatrix< T >::Size(), VNL::SymMatrix< T >::size(), VNL::SymMatrix< T >::Swap(), VNL::SymMatrix< T >::SymMatrix(), VNL::SymMatrix< T >::Update(), and VNL::SymMatrix< T >::~SymMatrix().
The documentation for this class was generated from the following files:
symmatrix.h
symmatrix.tpp