VW: VW::MatchData Class Reference
VW::MatchData Class Reference
[ImageProcessing]
A storage class for match data.
#include <matchdata.h>
Public Member Functions
MatchData ()
MatchData (const unsigned int old_i, const unsigned int new_i, const float match_score=0, const bool is_valid=true)
unsigned int GetNewIndex () const
unsigned int GetOldIndex () const
float GetScore () const
void SetScore (float new_score)
bool operator> (const MatchData &m) const
bool operator< (const MatchData &m) const
bool operator== (const MatchData &m) const
Public Attributes
unsigned int new_index
unsigned int old_index
float score
bool valid
Friends
std::ostream & VW::operator<< (std::ostream &s, const MatchData &m)
std::istream & VW::operator>> (std::istream &s, MatchData &m)
Detailed Description
A storage class for match data.
Author:
BJ Tordoff
Date:
14/01/2000 The match-data class stores one potential match, including the list-index of the two points and the correlation score.
Constructor & Destructor Documentation
VW::MatchData::MatchData () [inline]
VW::MatchData::MatchData (const unsigned int old_i, const unsigned int new_i, const float match_score = 0, const bool is_valid = true) [inline]
Member Function Documentation
unsigned int VW::MatchData::GetNewIndex () const [inline]
References new_index.
Referenced by VW::MatchesToPointLists().
unsigned int VW::MatchData::GetOldIndex () const [inline]
References old_index.
Referenced by VW::MatchesToPointLists().
float VW::MatchData::GetScore () const [inline]
References score.
Referenced by VW::MatchesToPointLists(), CompareHigher::operator()(), CompareLower::operator()(), operator<(), operator==(), and operator>().
bool VW::MatchData::operator< (const MatchData & m) const [inline]
References GetScore(), and score.
bool VW::MatchData::operator== (const MatchData & m) const [inline]
References GetScore(), and score.
bool VW::MatchData::operator> (const MatchData & m) const [inline]
References GetScore(), and score.
void VW::MatchData::SetScore (float new_score) [inline]
References score.
Friends And Related Function Documentation
std::ostream& VW::operator<< (std::ostream & s, const MatchData & m) [friend]
std::istream& VW::operator>> (std::istream & s, MatchData & m) [friend]
Member Data Documentation
unsigned int VW::MatchData::new_index
Referenced by GetNewIndex(), VW::operator<<(), and VW::operator>>().
unsigned int VW::MatchData::old_index
Referenced by GetOldIndex(), VW::operator<<(), and VW::operator>>().
float VW::MatchData::score
Referenced by GetScore(), operator<(), operator==(), operator>(), and SetScore().
bool VW::MatchData::valid
The documentation for this class was generated from the following file:
matchdata.h