VW: VW::Normalisation Class Reference
VW::Normalisation Class Reference
[GeometricObjects]
A 2D normalisation object.
#include <normalisation.h>
Public Member Functions
Normalisation ()
Construct and set to identity.
Normalisation (double width)
Construct using an image width (assumes 4:3 width:height ratio).
Normalisation (double width, double height)
Construct using an image width and height.
Normalisation (double scale, double centre_x, double centre_y)
Construct and set to isotropic scaling around given location.
Normalisation (const VNL::MatrixFixed< 3, 3, double > &C)
Construct from an existing 3x3 matrix.
Normalisation (const VNL::MatrixFixed< 3, 3, float > &C)
Construct from an existing floating point matrix.
template<class PointFeature >
Normalisation (const std::vector< PointFeature > &feature_list, VW::Point2D point=VW::Point2D())
Construct based on mean and standard deviation of point feature list.
template<class PointFeature >
Normalisation (const std::vector< PointFeature > &feature_list, const std::vector< unsigned int > &which_features, VW::Point2D point=VW::Point2D())
Construct based on mean and standard deviation of selected elements from a point feature list.
template<class LineFeature >
Normalisation (const std::vector< LineFeature > &feature_list, VW::Line2D line)
Construct based on mean and standard deviation of line feature list.
Normalisation (const Normalisation &C)
Construct (copy) from an existing normalisation.
void Init ()
void Init (double width, double height=0)
void Init (double scale, double centre_x, double centre_y)
void Init (const VNL::MatrixFixed< 3, 3, double > &C)
void Init (const VNL::MatrixFixed< 3, 3, float > &C)
template<class PointFeature >
void Init (const std::vector< PointFeature > &feature_list, VW::Point2D point=VW::Point2D())
Initialise based on mean and standard deviation of selected elements from a point feature list.
template<class PointFeature >
void Init (const std::vector< PointFeature > &feature_list, const std::vector< unsigned int > &which_features, VW::Point2D point=VW::Point2D())
Initialise based on mean and standard deviation of selected elements from a point feature list.
template<class LineFeature >
void Init (const std::vector< LineFeature > &feature_list, VW::Line2D line)
double NormaliseX (double x) const
double NormaliseY (double y) const
double UnNormaliseX (double x) const
double UnNormaliseY (double y) const
VW::Point2D Normalise (const VW::Point2D &point) const
VW::Line2D Normalise (const VW::Line2D &line) const
VW::LineSeg2D Normalise (const VW::LineSeg2D &lineseg) const
VW::CalibrationMatrix Normalise (const VW::CalibrationMatrix &K) const
VW::Point2D UnNormalise (const VW::Point2D &point) const
VW::Line2D UnNormalise (const VW::Line2D &line) const
VW::LineSeg2D UnNormalise (const VW::LineSeg2D &lineseg) const
VW::CalibrationMatrix UnNormalise (const VW::CalibrationMatrix &K) const
template<class PointFeature >
void Normalise (std::vector< PointFeature > &feature_list, VW::Point2D point=VW::Point2D()) const
template<class PointFeature >
PointFeature Normalise (const PointFeature &feature, VW::Point2D point=VW::Point2D()) const
template<class LineFeature >
void Normalise (std::vector< LineFeature > &feature_list, VW::Line2D line) const
template<class LineFeature >
LineFeature Normalise (const LineFeature &feature, VW::Line2D line) const
VNL::MatrixFixed< 3, 3, double > Normalise (const VNL::MatrixFixed< 3, 3, double > &M) const
Normalise a 3x3 double precision matrix.
VNL::MatrixFixed< 3, 3, float > Normalise (const VNL::MatrixFixed< 3, 3, float > &M) const
Normalise a 3x3 floating point matrix.
template<class PointFeature >
void UnNormalise (std::vector< PointFeature > &feature_list, VW::Point2D point=VW::Point2D()) const
template<class PointFeature >
PointFeature UnNormalise (const PointFeature &feature, VW::Point2D point=VW::Point2D()) const
template<class LineFeature >
void UnNormalise (std::vector< LineFeature > &feature_list, VW::Line2D line) const
template<class LineFeature >
LineFeature UnNormalise (const LineFeature &feature, VW::Line2D line) const
VNL::MatrixFixed< 3, 3, double > UnNormalise (const VNL::MatrixFixed< 3, 3, double > &M) const
VNL::MatrixFixed< 3, 3, float > UnNormalise (const VNL::MatrixFixed< 3, 3, float > &M) const
Normalisation Inverse () const
The inverse of a normalisation matrix is also a normalisation matrix.
VNL::MatrixFixed< 3, 3, double > operator() () const
VNL::MatrixFixed< 3, 3, double > AsMatrix () const
VNL::MatrixFixed< 3, 3, double > InverseMatrix () const
double GetScale () const
double GetCentreX () const
double GetCentreY () const
void GetCentre (double &x, double &y) const
bool IsIdentity () const
Static Public Attributes
static const float DEFAULT_WIDTH_HEIGHT_RATIO = 0.75
Protected Attributes
double _scale
double _centre_x
double _centre_y
Detailed Description
A 2D normalisation object.
Author:
JGH Knight
Date:
02/11/2002 This class is designed for normalising points and lines on the 2D plane, such as must be done before calculating the various image transforms. A variety of normalisations are possible, but the most common and simplest is to simply provide the image width (assuming a 4x3 ratio image), giving a normalisation to coords (-1<x<1, -0.75<y<0.75).
X and Y are scaled equally. Doing otherwise complicates things and is rarely needed.
Constructor & Destructor Documentation
VW::Normalisation::Normalisation () [inline]
Construct and set to identity.
Referenced by Inverse().
VW::Normalisation::Normalisation (double width) [inline]
Construct using an image width (assumes 4:3 width:height ratio).
The scaling is then isotropic around the image centre.
VW::Normalisation::Normalisation (double width, double height) [inline]
Construct using an image width and height.
The scaling is then isotropic around the image centre.
VW::Normalisation::Normalisation (double scale, double centre_x, double centre_y) [inline]
Construct and set to isotropic scaling around given location.
VW::Normalisation::Normalisation (const VNL::MatrixFixed< 3, 3, double > & C) [inline]
Construct from an existing 3x3 matrix.
VW::Normalisation::Normalisation (const VNL::MatrixFixed< 3, 3, float > & C) [inline]
Construct from an existing floating point matrix.
template<class PointFeature > VW::Normalisation::Normalisation (const std::vector< PointFeature > & feature_list, VW::Point2D point = VW::Point2D()) [inline]
Construct based on mean and standard deviation of point feature list.
References Init().
template<class PointFeature > VW::Normalisation::Normalisation (const std::vector< PointFeature > & feature_list, const std::vector< unsigned int > & which_features, VW::Point2D point = VW::Point2D()) [inline]
Construct based on mean and standard deviation of selected elements from a point feature list.
References Init().
template<class LineFeature > VW::Normalisation::Normalisation (const std::vector< LineFeature > & feature_list, VW::Line2D line) [inline]
Construct based on mean and standard deviation of line feature list.
VW::Normalisation::Normalisation (const Normalisation & C) [inline]
Construct (copy) from an existing normalisation.
Member Function Documentation
VNL::MatrixFixed< 3, 3, double > VW::Normalisation::AsMatrix () const
References _centre_x, _centre_y, and _scale.
Referenced by VW::Homography2DComputeMLESAC::Compute(), VW::Homography2DComputeGUNSAC::Compute(), VW::Homography2DComputeGUISAC::Compute(), VW::FMatrixComputeMLESAC::Compute(), VW::FMatrixComputeGUNSAC::Compute(), VW::EssentialMatrixComputeMLESAC::Compute(), VW::PMatrixCompute::LinearFromPoints(), VW::PMatrixCompute::NonLinearFromPoints(), Normalise(), and operator()().
void VW::Normalisation::GetCentre (double & x, double & y) const [inline]
References _centre_x, and _centre_y.
double VW::Normalisation::GetCentreX () const [inline]
References _centre_x.
Referenced by VW::FMatrixCompute::Unnormalise(), VW::FMatrixAffineCompute::Unnormalise(), VW::EssentialMatrixCompute::Unnormalise(), and VW::FMatrixAffineCompute::UnnormaliseFVec().
double VW::Normalisation::GetCentreY () const [inline]
References _centre_y.
Referenced by VW::FMatrixCompute::Unnormalise(), VW::FMatrixAffineCompute::Unnormalise(), VW::EssentialMatrixCompute::Unnormalise(), and VW::FMatrixAffineCompute::UnnormaliseFVec().
double VW::Normalisation::GetScale () const [inline]
References _scale.
Referenced by VW::Homography2DComputeMLESAC::Compute(), VW::Homography2DComputeLinear::Compute(), VW::Homography2DComputeGUNSAC::Compute(), VW::Homography2DComputeGUISAC::Compute(), VW::FMatrixComputeMLESAC::Compute(), VW::FMatrixComputeLinear::Compute(), VW::FMatrixComputeGUNSAC::Compute(), VW::FMatrixAffineComputePreemptive::Compute(), VW::FMatrixAffineComputeMLESAC::Compute(), VW::FMatrixAffineComputeLinear::Compute(), VW::FMatrixAffineComputeGUISAC::Compute(), VW::EssentialMatrixComputePreemptive::Compute(), VW::EssentialMatrixComputeMLESAC::Compute(), VW::Line2DCompute::GUISACFromPoints(), VW::Line2DCompute::MLESACFromPoints(), VW::PMatrixCompute::NonLinearFromPoints(), VW::FMatrixCompute::Unnormalise(), VW::FMatrixAffineCompute::Unnormalise(), VW::EssentialMatrixCompute::Unnormalise(), and VW::FMatrixAffineCompute::UnnormaliseFVec().
template<class LineFeature > void VW::Normalisation::Init (const std::vector< LineFeature > & feature_list, VW::Line2D line) [inline]
template<class PointFeature > void VW::Normalisation::Init (const std::vector< PointFeature > & feature_list, const std::vector< unsigned int > & which_features, VW::Point2D point = VW::Point2D()) [inline]
Initialise based on mean and standard deviation of selected elements from a point feature list.
References _centre_x, _centre_y, _scale, and VW::GetPointDistribution().
template<class PointFeature > void VW::Normalisation::Init (const std::vector< PointFeature > & feature_list, VW::Point2D point = VW::Point2D()) [inline]
Initialise based on mean and standard deviation of selected elements from a point feature list.
References _centre_x, _centre_y, _scale, and VW::GetPointDistribution().
void VW::Normalisation::Init (const VNL::MatrixFixed< 3, 3, float > & C) [inline]
References _centre_x, _centre_y, and _scale.
void VW::Normalisation::Init (const VNL::MatrixFixed< 3, 3, double > & C) [inline]
References _centre_x, _centre_y, and _scale.
void VW::Normalisation::Init (double scale, double centre_x, double centre_y) [inline]
References _centre_x, _centre_y, and _scale.
void VW::Normalisation::Init (double width, double height = 0) [inline]
References _centre_x, _centre_y, _scale, and DEFAULT_WIDTH_HEIGHT_RATIO.
void VW::Normalisation::Init () [inline]
References _centre_x, _centre_y, and _scale.
Referenced by VW::Homography2DComputeLinear::Compute(), VW::FMatrixComputeLinear::Compute(), VW::FMatrixAffineComputeLinear::Compute(), VW::EssentialMatrixComputeLinear::Compute(), VW::EssentialMatrixCompute5Point::Compute(), VW::Homography2DComputeLinear::ComputeWeighted(), VW::FMatrixComputeLinear::ComputeWeighted(), VW::FMatrixAffineComputeLinear::ComputeWeighted(), VW::EssentialMatrixComputeLinear::ComputeWeighted(), VW::FMatrixCompute::Linear7Point(), VW::PMatrixCompute::LinearFromPoints(), and Normalisation().
VW::Normalisation VW::Normalisation::Inverse () const [inline]
The inverse of a normalisation matrix is also a normalisation matrix.
References _centre_x, _centre_y, _scale, and Normalisation().
VNL::MatrixFixed< 3, 3, double > VW::Normalisation::InverseMatrix () const
References _centre_x, _centre_y, and _scale.
Referenced by VW::Homography2DComputeMLESAC::Compute(), VW::Homography2DComputeGUNSAC::Compute(), VW::Homography2DComputeGUISAC::Compute(), VW::FMatrixComputeGUNSAC::Compute(), VW::PMatrixCompute::NonLinearFromPoints(), and UnNormalise().
bool VW::Normalisation::IsIdentity () const [inline]
References _centre_x, _centre_y, and _scale.
Referenced by Normalise(), and UnNormalise().
VNL::MatrixFixed< 3, 3, float > VW::Normalisation::Normalise (const VNL::MatrixFixed< 3, 3, float > & M) const
Normalise a 3x3 floating point matrix.
References AsMatrix(), and VNL::Copy().
VNL::MatrixFixed< 3, 3, double > VW::Normalisation::Normalise (const VNL::MatrixFixed< 3, 3, double > & M) const [inline]
Normalise a 3x3 double precision matrix.
References AsMatrix().
template<class LineFeature > LineFeature VW::Normalisation::Normalise (const LineFeature & feature, VW::Line2D line) const [inline]
References _centre_x, _centre_y, and _scale.
template<class LineFeature > void VW::Normalisation::Normalise (std::vector< LineFeature > & feature_list, VW::Line2D line) const [inline]
References IsIdentity(), and Normalise().
template<class PointFeature > PointFeature VW::Normalisation::Normalise (const PointFeature & feature, VW::Point2D point = VW::Point2D()) const [inline]
References _centre_x, _centre_y, _scale, and VW::Point2D::SetX().
template<class PointFeature > void VW::Normalisation::Normalise (std::vector< PointFeature > & feature_list, VW::Point2D point = VW::Point2D()) const [inline]
References IsIdentity(), and Normalise().
VW::CalibrationMatrix VW::Normalisation::Normalise (const VW::CalibrationMatrix & K) const
References _centre_x, _centre_y, _scale, VW::CalibrationMatrix::GetAspectRatio(), VW::CalibrationMatrix::GetFocalLength(), VW::CalibrationMatrix::GetPrincipalPointX(), VW::CalibrationMatrix::GetPrincipalPointY(), and VW::CalibrationMatrix::GetSkew().
VW::LineSeg2D VW::Normalisation::Normalise (const VW::LineSeg2D & lineseg) const
References VW::LineSeg2D::GetEndPoint(), VW::LineSeg2D::GetStartPoint(), and Normalise().
VW::Line2D VW::Normalisation::Normalise (const VW::Line2D & line) const
References _centre_x, _centre_y, and _scale.
VW::Point2D VW::Normalisation::Normalise (const VW::Point2D & point) const
References _centre_x, _centre_y, _scale, VW::Point2D::GetX(), and VW::Point2D::GetY().
Referenced by VW::PlesseyOld::Compute(), VW::PlesseyDetector::Compute(), VW::Homography2DComputeMLESAC::Compute(), VW::Homography2DComputeLinear::Compute(), VW::Homography2DComputeGUNSAC::Compute(), VW::Homography2DComputeGUISAC::Compute(), VW::FMatrixComputeMLESAC::Compute(), VW::FMatrixComputeLinear::Compute(), VW::FMatrixComputeGUNSAC::Compute(), VW::FMatrixAffineComputePreemptive::Compute(), VW::FMatrixAffineComputeMLESAC::Compute(), VW::FMatrixAffineComputeLinear::Compute(), VW::FMatrixAffineComputeGUISAC::Compute(), VW::EssentialMatrixComputePreemptive::Compute(), VW::EssentialMatrixComputeMLESAC::Compute(), VW::EssentialMatrixComputeLinear::Compute(), VW::EssentialMatrixCompute5Point::Compute(), VW::Homography2DComputeLinear::ComputeWeighted(), VW::FMatrixComputeLinear::ComputeWeighted(), VW::FMatrixAffineComputeLinear::ComputeWeighted(), VW::EssentialMatrixComputeLinear::ComputeWeighted(), VW::Line2DCompute::GUISACFromPoints(), VW::FMatrixCompute::Linear7Point(), VW::PMatrixCompute::LinearFromPoints(), VW::Line2DCompute::MLESACFromPoints(), VW::PMatrixCompute::NonLinearFromPoints(), and Normalise().
double VW::Normalisation::NormaliseX (double x) const
References _centre_x, and _scale.
double VW::Normalisation::NormaliseY (double y) const
References _centre_y, and _scale.
VNL::MatrixFixed<3,3,double> VW::Normalisation::operator() () const [inline]
References AsMatrix().
VNL::MatrixFixed< 3, 3, float > VW::Normalisation::UnNormalise (const VNL::MatrixFixed< 3, 3, float > & M) const
References VNL::Copy(), and InverseMatrix().
VNL::MatrixFixed< 3, 3, double > VW::Normalisation::UnNormalise (const VNL::MatrixFixed< 3, 3, double > & M) const [inline]
Parameters:
M the matrix to be unnormalised (will not be changed)
Returns:
a new matrix which is un-normalised
References InverseMatrix().
template<class LineFeature > LineFeature VW::Normalisation::UnNormalise (const LineFeature & feature, VW::Line2D line) const [inline]
References _centre_x, _centre_y, and _scale.
template<class LineFeature > void VW::Normalisation::UnNormalise (std::vector< LineFeature > & feature_list, VW::Line2D line) const [inline]
References IsIdentity(), and UnNormalise().
template<class PointFeature > PointFeature VW::Normalisation::UnNormalise (const PointFeature & feature, VW::Point2D point = VW::Point2D()) const [inline]
References _centre_x, _centre_y, _scale, and VW::Point2D::SetX().
template<class PointFeature > void VW::Normalisation::UnNormalise (std::vector< PointFeature > & feature_list, VW::Point2D point = VW::Point2D()) const [inline]
References IsIdentity(), and UnNormalise().
VW::CalibrationMatrix VW::Normalisation::UnNormalise (const VW::CalibrationMatrix & K) const
References _centre_x, _centre_y, _scale, VW::CalibrationMatrix::GetAspectRatio(), VW::CalibrationMatrix::GetFocalLength(), VW::CalibrationMatrix::GetPrincipalPointX(), VW::CalibrationMatrix::GetPrincipalPointY(), and VW::CalibrationMatrix::GetSkew().
VW::LineSeg2D VW::Normalisation::UnNormalise (const VW::LineSeg2D & lineseg) const
References VW::LineSeg2D::GetEndPoint(), VW::LineSeg2D::GetStartPoint(), and UnNormalise().
VW::Line2D VW::Normalisation::UnNormalise (const VW::Line2D & line) const
References _centre_x, _centre_y, and _scale.
VW::Point2D VW::Normalisation::UnNormalise (const VW::Point2D & point) const
References _centre_x, _centre_y, _scale, VW::Point2D::GetX(), and VW::Point2D::GetY().
Referenced by VW::DrawFunctions::Draw(), VW::Line2DCompute::GUISACFromPoints(), VW::Line2DCompute::MLESACFromPoints(), VW::PMatrixCompute::NonLinearFromPoints(), and UnNormalise().
double VW::Normalisation::UnNormaliseX (double x) const
References _centre_x, and _scale.
double VW::Normalisation::UnNormaliseY (double y) const
References _centre_y, and _scale.
Member Data Documentation
double VW::Normalisation::_centre_x [protected]
Referenced by AsMatrix(), GetCentre(), GetCentreX(), Init(), Inverse(), InverseMatrix(), IsIdentity(), Normalise(), NormaliseX(), UnNormalise(), and UnNormaliseX().
double VW::Normalisation::_centre_y [protected]
Referenced by AsMatrix(), GetCentre(), GetCentreY(), Init(), Inverse(), InverseMatrix(), IsIdentity(), Normalise(), NormaliseY(), UnNormalise(), and UnNormaliseY().
double VW::Normalisation::_scale [protected]
Referenced by AsMatrix(), GetScale(), Init(), Inverse(), InverseMatrix(), IsIdentity(), Normalise(), NormaliseX(), NormaliseY(), UnNormalise(), UnNormaliseX(), and UnNormaliseY().
const float VW::Normalisation::DEFAULT_WIDTH_HEIGHT_RATIO = 0.75 [static]
Referenced by Init().
The documentation for this class was generated from the following files:
normalisation.h
normalisation.cpp