VW: VW::ParametricFlowNonLin Class Reference
VW::ParametricFlowNonLin Class Reference
#include <parametricflow.h>
Public Member Functions
ParametricFlowNonLin ()
template<class Type >
ParametricFlowNonLin (const ImageMono< Type > &imold, const ImageMono< Type > &imnew, VW::Homography2D &H, const ImageMono< Type > *mask=NULL)
template<class Type >
void Compute (const ImageMono< Type > &imold, const ImageMono< Type > &imnew, VW::Homography2D &H, const ImageMono< Type > *mask=NULL)
Constructor & Destructor Documentation
VW::ParametricFlowNonLin::ParametricFlowNonLin () [inline]
template<class Type > VW::ParametricFlowNonLin::ParametricFlowNonLin (const ImageMono< Type > & imold, const ImageMono< Type > & imnew, VW::Homography2D & H, const ImageMono< Type > * mask = NULL) [inline]
References Compute().
Member Function Documentation
template<class Type > void ParametricFlowNonLin::Compute (const ImageMono< Type > & imold, const ImageMono< Type > & imnew, VW::Homography2D & H, const ImageMono< Type > * mask = NULL) [inline]
References VNL::Matrix< T >::DataBlock(), VW::ROI::Height(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::ROI(), and VW::ROI::Width().
Referenced by ParametricFlowNonLin().
The documentation for this class was generated from the following files:
parametricflow.h
parametricflow.cpp