VW: VW::DrawingPosition Class Reference
VW::DrawingPosition Class Reference
A class to store a translation, rotation drawing position.
#include <threedtoolglcommon.h>
Public Member Functions
DrawingPosition ()
void Zero ()
Public Attributes
Vector3D rW
Quaternion qWO
Detailed Description
A class to store a translation, rotation drawing position.
Constructor & Destructor Documentation
DrawingPosition::DrawingPosition ()
References Zero().
Member Function Documentation
void DrawingPosition::Zero ()
References qWO, rW, VW::Quaternion::Set(), and VW::Point3D::Set().
Referenced by VW::ThreeDToolGLCommon::Clicked(), VW::ThreeDToolGLCommon::DoDrawing(), and DrawingPosition().
Member Data Documentation
Quaternion VW::DrawingPosition::qWO
Referenced by VW::RotationCentre::Include(), VW::ThreeDToolGLCommon::RotateDrawingPosition(), VW::ThreeDToolGLCommon::TranslateDrawingPosition(), and Zero().
Vector3D VW::DrawingPosition::rW
Referenced by VW::RotationCentre::Include(), VW::ThreeDToolGLCommon::TranslateDrawingPosition(), and Zero().
The documentation for this class was generated from the following files:
threedtoolglcommon.h
threedtoolglcommon.cpp