VW: VW::ImageMono< Type > Class Template Reference
VW::ImageMono< Type > Class Template Reference
[Image]
A class for storing monochrome images.
#include <imagemono.h>
Public Types
typedef Type DataType
typedef PixelMono< Type > PixelType
typedef PixelType * PixelPtr
Public Member Functions
ImageMono (const std::string &filename)
Construct and read a file.
ImageMono (const int w, const int h)
Construct and allocate the image data array.
ImageMono ()
Construct without allocating the data array.
ImageMono (PixelMono< Type > *buf, const int w, const int h)
Construct from a data block.
~ImageMono ()
Destroy all data.
PixelMono< double > GetInterpolatedPixel (double x, double y) const
Get a linearly interpolated pixel value.
PixelMono< float > GetInterpolatedPixel (float x, float y) const
Get a linearly interpolated pixel value.
bool ReadImage (FILE *fp)
Read the image from an open stream.
bool WriteImage (FILE *fp) const
Write the image to an open stream.
bool ReadImage (const std::string &filename)
Read the image from a file on disk.
bool WriteImage (const std::string &filename) const
Write the image as a file.
template<>
void GetFormatStrings (std::string &format, std::string &type) const
Return strings describing the format of image data.
template<>
void GetFormatStrings (std::string &format, std::string &type) const
Return strings describing the format of image data.
template<>
void GetFormatStrings (std::string &format, std::string &type) const
Return strings describing the format of image data.
template<>
void GetFormatStrings (std::string &format, std::string &type) const
Return strings describing the format of image data.
void AllocImageData (const unsigned int w, const unsigned int h)
void SetImageData (PixelMono< Type > *data, const unsigned int w, const unsigned int h)
void FreeImageData ()
bool IsAlloced () const
void GetSize (unsigned int &w, unsigned int &h) const
unsigned int GetWidth (void) const
unsigned int GetHeight (void) const
void SetROI (const VW::ROI &new_roi)
VW::ROI & ROI ()
const VW::ROI & ROI () const
void ResetROI ()
Set the ROI to be the whole image.
PixelMono< Type > * GetImageBuffer (void) const
void * GetRawBuffer (void) const
PixelMono< Type > GetPixel (const int c, const int r) const
void SetPixel (const int c, const int r, const PixelMono< Type > &new_value)
PixelMono< Type > * GetRowStart (int r) const
PixelMono< Type > ** GetRowPointer (int r) const
PixelMono< Type > * operator[] (int r) const
PixelMono< Type > * GetROIRowStart (int r) const
void Clear (const PixelMono< Type > &new_value=PixelMono< Type >())
Set the whole image to a particular value.
void FlipHorizontal ()
void FlipVertical ()
void ExchangeData (ImageBase< PixelMono< Type >, PixelMono< Type > * > &other)
Swap this image's data for other image data - size, ROI etc are also exchanged.
bool ReadBinary (std::istream &stream)
bool WriteBinary (std::ostream &stream) const
PixelMono< Type > operator() (int r) const
PixelMono< Type > operator() (int r, int c)
void SetPenColour (const PixelMono< Type > &colour)
For drawing, the image has a pen colour much like a display.
PixelMono< Type > GetPenColour () const
Return the current pen colour.
void DrawLine (const double x0, const double y0, const double x1, const double y1)
Public Attributes
PixelMono< Type > ** pixel
Pointers to the start of each row.
Protected Member Functions
void GetFormatStrings (std::string &format, std::string &type) const
Return strings describing the format of image data.
void _CreateRowPointers ()
Protected Attributes
unsigned int _width
unsigned int _height
VW::ROI _roi
PixelMono< Type > * _data
bool _dataalloced
bool _rowsalloced
PixelMono< Type > _pen_colour
Detailed Description
template<class Type>
class VW::ImageMono< Type >
A class for storing monochrome images.
Author:
ID Reid, BJ Tordoff
Date:
02/08/02 This image class stores the image in a row-major packed format (ie. like a standard C/C++ array), with pixels as single values of type Type.
Member Typedef Documentation
template<class Type> typedef Type VW::ImageMono< Type >::DataType
template<class Type> typedef PixelType* VW::ImageMono< Type >::PixelPtr
template<class Type> typedef PixelMono<Type> VW::ImageMono< Type >::PixelType
Constructor & Destructor Documentation
template<class Type > VW::ImageMono< Type >::ImageMono (const std::string & filename) [inline]
Construct and read a file.
References VW::ImageMono< Type >::ReadImage().
template<class Type > VW::ImageMono< Type >::ImageMono (const int w, const int h) [inline]
Construct and allocate the image data array.
template<class T > VW::ImageMono< T >::ImageMono () [inline]
Construct without allocating the data array.
Before use, AllocImageData should be used to specify the image size.
template<class Type> VW::ImageMono< Type >::ImageMono (PixelMono< Type > * buf, const int w, const int h) [inline]
Construct from a data block.
template<class T > VW::ImageMono< T >::~ImageMono () [inline]
Destroy all data.
Member Function Documentation
void VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::_CreateRowPointers () [protected, inherited]
void VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::AllocImageData (const unsigned int w, const unsigned int h) [inherited]
Allocate the image data array.
Parameters:
w the width of array (number of columns) to allocate
h the height of array (number of rows) to allocate
Referenced by VW::Pyramid< StorageType >::AverageAndSubsampleBy2(), VW::Threshold< Type >::Compute(), VW::Correlate::Compute(), VW::ChamferDistance::Compute(), VW::ClassifierUV::GetProbImage(), and VW::ReadJPEGImage().
void VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::Clear (const PixelMono< Type > & new_value = PixelType()) [inherited]
Set the whole image to a particular value.
Fill the entire image with a pixel value.
void VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::DrawLine (const double x0, const double y0, const double x1, const double y1) [inherited]
void VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::ExchangeData (ImageBase< PixelMono< Type > , PixelMono< Type > * > & other) [inherited]
Swap this image's data for other image data - size, ROI etc are also exchanged.
This is handy to avoid an image copy when doing things like:
void MyFunc(ImageXXX& im) { VW::ImageXXX result; DoSomeProcessing(im,result); im.ExchangeData(result); }
which would otherwise require a copy of the result data back to the original.
void VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::FlipHorizontal () [inherited]
Flip the image horizontally (size preserved).
void VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::FlipVertical () [inherited]
Flip the image vertically (size preserved).
void VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::FreeImageData () [inherited]
De-allocate the image data array.
Once freed, storage space will be reallocated automatically when an image is read from a file or stream, or must otherwise by created using the AllocImageData() function.
Referenced by VW::Correlate::Compute().
template<> void VW::ImageMono< bool >::GetFormatStrings (std::string & format, std::string & type) const [inline, virtual]
Return strings describing the format of image data.
This must be overloaded on a per-type basis.
Implements VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >.
template<> void VW::ImageMono< float >::GetFormatStrings (std::string & format, std::string & type) const [inline, virtual]
Return strings describing the format of image data.
This must be overloaded on a per-type basis.
Implements VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >.
template<> void VW::ImageMono< unsigned int >::GetFormatStrings (std::string & format, std::string & type) const [inline, virtual]
Return strings describing the format of image data.
This must be overloaded on a per-type basis.
Implements VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >.
template<> void VW::ImageMono< unsigned char >::GetFormatStrings (std::string & format, std::string & type) const [inline, virtual]
Return strings describing the format of image data.
This must be overloaded on a per-type basis.
Implements VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >.
template<class T > void VW::ImageMono< T >::GetFormatStrings (std::string & format, std::string & type) const [inline, protected, virtual]
Return strings describing the format of image data.
This must be overloaded on a per-type basis.
Implements VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >.
unsigned int VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::GetHeight (void) const [inherited]
Determine the height of the image in pixels.
Returns:
the height (number of rows) of the image
Referenced by VW::Pyramid< StorageType >::AllocMemory(), VW::Pyramid< StorageType >::AverageAndSubsampleBy2(), VW::Threshold< Type >::Compute(), VW::Pyramid< StorageType >::Compute(), VW::PlesseyDetector::Compute(), VW::ParametricFlow::Compute(), VW::IntegralImageSquared< DataType >::Compute(), VW::IntegralImage< DataType >::Compute(), VW::GetSIFTDescriptor::Compute(), VW::Correlate::Compute(), VW::Convolve< maskType >::Compute(), VW::ChamferDistance::Compute(), GenerallySmooth(), VW::ClassifierUV::GetProbImage(), VW::Moments::Moments(), VW::ParametricFlowFunc< Type >::ParametricFlowFunc(), VW::ReadJPEGImage(), and VW::WriteJPEGImage().
PixelMono< Type > * VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::GetImageBuffer (void) const [inherited]
Get a pointer to the first pixel in the data array.
The array is stored in row-major form, and can be traversed using pointer arithmatic, eg: const unsigned int num_pix = im.GetWidth() * im.GetHeight(); PixelType* p = im.GetImageBuffer(); for (unsigned int i=0; i<num_pix; i++,p++) { p->ScaleIntensity(0.5); }
template<class T > VW::PixelMono< float > VW::ImageMono< T >::GetInterpolatedPixel (float x, float y) const [inline]
Get a linearly interpolated pixel value.
References mp, VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::pixel, and VW::PixelMono< Type >::y.
template<class T > VW::PixelMono< double > VW::ImageMono< T >::GetInterpolatedPixel (double x, double y) const [inline]
Get a linearly interpolated pixel value.
References mp, VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::pixel, and VW::PixelMono< Type >::y.
PixelMono< Type > VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::GetPenColour () const [inherited]
Return the current pen colour.
PixelMono< Type > VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::GetPixel (const int c, const int r) const [inherited]
Recover (copy) the pixel at column c, row r.
If VW is compiled in debug mode, this function is range-checked.
Parameters:
c the column index (0<c<width)
r the row index (0<r<height)
Returns:
a copy of the pixel (so changes to this pixel will not affect the underlying image)
Referenced by VW::GetImagePatch(), and VW::GetInterpolatedImagePatch().
void* VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::GetRawBuffer (void) const [inherited]
Get a pointer to the first memory location used in the data array.
As this returns a void*, you can cast it to any type you like, with the usual pitfalls that this entails if the pointer type doesn't match the type of the data stored.
Referenced by VW::ClassifierUV::GetProbImage().
PixelMono< Type > * VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::GetROIRowStart (int r) const [inherited]
Referenced by VW::Pyramid< StorageType >::AverageAndSubsampleBy2(), VW::Threshold< Type >::Compute(), VW::IntegralImageSquared< DataType >::Compute(), VW::IntegralImage< DataType >::Compute(), and VW::Correlate::Compute().
PixelMono< Type > * * VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::GetRowPointer (int r) const [inherited]
Referenced by VW::Convolve< maskType >::Compute().
PixelMono< Type > * VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::GetRowStart (int r) const [inherited]
Referenced by VW::Correlate::Compute(), VW::Convolve< maskType >::Compute(), VW::ChamferDistance::Compute(), VW::ReadJPEGImage(), and VW::WriteJPEGImage().
void VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::GetSize (unsigned int & w, unsigned int & h) const [inherited]
Get width and height in a single command.
Parameters:
w will be set to the width (number of columns)
h will be set to the height (number of rows)
Referenced by VW::PyramidCorrelate::PyramidCorrelate().
unsigned int VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::GetWidth (void) const [inherited]
Determine the width of the image in pixels.
Returns:
the width (number of columns) of the image
Referenced by VW::Pyramid< StorageType >::AllocMemory(), VW::Pyramid< StorageType >::AverageAndSubsampleBy2(), VW::Threshold< Type >::Compute(), VW::ShiTomasiDetector::Compute(), VW::Pyramid< StorageType >::Compute(), VW::PlesseyDetector::Compute(), VW::ParametricFlow::Compute(), VW::IntegralImageSquared< DataType >::Compute(), VW::IntegralImage< DataType >::Compute(), VW::GetSIFTDescriptor::Compute(), VW::Correlate::Compute(), VW::Convolve< maskType >::Compute(), VW::ChamferDistance::Compute(), GenerallySmooth(), VW::ClassifierUV::GetProbImage(), VW::Moments::Moments(), VW::ParametricFlowFunc< Type >::ParametricFlowFunc(), VW::ReadJPEGImage(), and VW::WriteJPEGImage().
bool VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::IsAlloced (void) const [inherited]
Is the image data array allocated?
Returns:
true if data array exists
Referenced by VW::Pyramid< StorageType >::AverageAndSubsampleBy2(), VW::Threshold< Type >::Compute(), VW::Correlate::Compute(), VW::ChamferDistance::Compute(), VW::ClassifierUV::GetProbImage(), VW::PyramidCorrelate::PyramidCorrelate(), and VW::ReadJPEGImage().
PixelMono< Type > VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::operator() (int r, int c) [inherited]
Recover a pixel (note y,x NOT x,y).
This function is not range-checked.
Parameters:
r the row number (y coord) of the pixel
c the column number (x coord) of the pixel
Returns:
the pixel value at this position
PixelMono< Type > VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::operator() (int r) const [inherited]
Get the pixel at the start of row r.
This function is not range checked.
Parameters:
r the row number (y coord) of the pixel
Returns:
the pixel value at the start of this row
PixelMono< Type > * VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::operator[] (int r) const [inherited]
bool VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::ReadBinary (std::istream & stream) [inherited]
Read the image from a stream in the internal VW format.
This format is strongly related to the raw PPM format, but keeps the byte ordering and alpha values of the image class used. The image format and data type are written in plain text before the data, stored as binary.
Parameters:
stream the input stream into which the image data will be written
template<class Type> bool VW::ImageMono< Type >::ReadImage (const std::string & filename)
Read the image from a file on disk.
The filename suffix is used to determine the desired image format (eg gif, jpeg, png) a la Windows. If the image size has already been specified, the stored image must have the same size as the target, otherwise the size will be determined from the file image.
Returns:
true for successful loading, false if there was an error.
Reimplemented from VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >.
template<class Type > bool ImageMono::ReadImage (FILE * fp) [inline]
Read the image from an open stream.
Referenced by VW::ImageMono< Type >::ImageMono().
void VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::ResetROI () [inherited]
Set the ROI to be the whole image.
Reset the region of interest to be the whole image.
const VW::ROI& VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::ROI () const [inherited]
Constant reference to the region of interest (ROI) of the image.
Returns:
the current region of interest in the image.
VW::ROI& VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::ROI () [inherited]
Copy of the region of interest (ROI) of the image.
Returns:
the current region of interest in the image. Reference to the region of interest (ROI) of the image.
the current region of interest in the image.
Referenced by VW::Pyramid< StorageType >::AverageAndSubsampleBy2(), VW::Threshold< Type >::Compute(), VW::ShiTomasiDetector::Compute(), VW::ParametricFlowNonLin::Compute(), VW::ParametricFlowWide::Compute(), VW::IntegralImageSquared< DataType >::Compute(), VW::IntegralImage< DataType >::Compute(), VW::GetPatchDescriptor::Compute(), VW::Correlate::Compute(), and VW::Convolve< maskType >::Compute().
void VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::SetImageData (PixelMono< Type > * data, const unsigned int w, const unsigned int h) [inherited]
Allocate the image data array using some existing data.
Parameters:
data the memory location of the existing data array
w the width of array (number of columns) to allocate
h the height of array (number of rows) to allocate
void VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::SetPenColour (const PixelMono< Type > & colour) [inherited]
For drawing, the image has a pen colour much like a display.
void VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::SetPixel (const int c, const int r, const PixelMono< Type > & new_value) [inherited]
Set the pixel at column c, row r.
If VW is compiled in debug mode, this function is range-checked.
Parameters:
c the column index (0<c<width)
r the row index (0<r<height)
new_value the new data for this pixel
void VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::SetROI (const VW::ROI & new_roi) [inherited]
Set the region of interest (ROI) of the image.
Parameters:
new_roi the new region of interest to use.
Referenced by VW::Correlate::Compute().
bool VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::WriteBinary (std::ostream & stream) const [inherited]
Write the image to a stream in the internal VW format.
This format is strongly related to the raw PPM format, but keeps the byte ordering and alpha values of the image class used. The image format and data type are written in plain text before the data, stored as binary.
template<class Type> bool VW::ImageMono< Type >::WriteImage (const std::string & filename) const
Write the image as a file.
The filename suffix is used to determine the desired image format (eg gif, jpeg, png) a la Windows. If the file already exists, it will be overwritten.
Returns:
true for successful loading, false if there was an error.
Reimplemented from VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >.
template<class Type > bool ImageMono::WriteImage (FILE * fp) const [inline]
Write the image to an open stream.
Referenced by VW::ParametricFlowWide::Compute().
Member Data Documentation
PixelMono< Type > * VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::_data [protected, inherited]
bool VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::_dataalloced [protected, inherited]
unsigned int VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::_height [protected, inherited]
PixelMono< Type > VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::_pen_colour [protected, inherited]
VW::ROI VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::_roi [protected, inherited]
bool VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::_rowsalloced [protected, inherited]
unsigned int VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::_width [protected, inherited]
PixelMono< Type > * * VW::ImageBase< PixelMono< Type > , PixelMono< Type > * >::pixel [inherited]
Pointers to the start of each row.
A pointer to the start of the row r is given by image.pixel[r], and a pixel at row r, column c, by image.pixel[r][c]. This is functionally identical to saying image[r][c], but in some circumstances may be faster.
Referenced by GenerallySmooth(), and VW::ImageMono< Type >::GetInterpolatedPixel().
The documentation for this class was generated from the following files:
imagemono.h
imagemono.cpp