VW: VW::AWFEdge Class Reference
VW::AWFEdge Class Reference
#include <awfedge.h>
Public Member Functions
AWFEdge (unsigned int startindex, unsigned int endindex)
void AddFace (unsigned int index)
VW::LineSeg3D GetAsLine (const std::vector< VW::Point3D > &vertices) const
VW::Vector3D GetNormal1 (const std::vector< AWFFace > &faces) const
VW::Vector3D GetNormal2 (const std::vector< AWFFace > &faces) const
void Draw (const std::vector< VW::Point3D > &vertices) const
bool IsMe (unsigned int index1, unsigned int index2) const
bool HasFaces () const
Constructor & Destructor Documentation
VW::AWFEdge::AWFEdge (unsigned int startindex, unsigned int endindex) [inline]
Member Function Documentation
void VW::AWFEdge::AddFace (unsigned int index)
Referenced by VW::AWFObject::_GenerateEdges().
void VW::AWFEdge::Draw (const std::vector< VW::Point3D > & vertices) const
References VW::Point3D::GetX(), VW::Point3D::GetY(), and VW::Point3D::GetZ().
VW::LineSeg3D VW::AWFEdge::GetAsLine (const std::vector< VW::Point3D > & vertices) const
VW::Vector3D VW::AWFEdge::GetNormal1 (const std::vector< AWFFace > & faces) const
VW::Vector3D VW::AWFEdge::GetNormal2 (const std::vector< AWFFace > & faces) const
bool VW::AWFEdge::HasFaces () const [inline]
bool VW::AWFEdge::IsMe (unsigned int index1, unsigned int index2) const [inline]
The documentation for this class was generated from the following files:
awfedge.h
awfedge.cpp