VW: VW::Convolve< maskType > Class Template Reference
VW::Convolve< maskType > Class Template Reference
#include <convolve.h>
Public Member Functions
Convolve (ConvolutionMask1D< maskType > &c, ConvolutionMask1D< maskType > &r)
template<class inType , class outType >
Convolve (const ImageMono< inType > &im, ConvolutionMask1D< maskType > &c, ConvolutionMask1D< maskType > &r, ImageMono< outType > &result, const unsigned int subsampling=1)
template<class inType , class outType >
Convolve (const ImageYUV< inType > &im, ConvolutionMask1D< maskType > &c, ConvolutionMask1D< maskType > &r, ImageYUV< outType > &result, const unsigned int subsampling=1)
template<class inType , class outType >
void Compute (const ImageMono< inType > &im, ImageMono< outType > &result, const unsigned int subsampling=1)
template<class inType , class outType >
void Compute (const ImageYUV< inType > &im, ImageYUV< outType > &result, const unsigned int subsampling=1)
Protected Attributes
ConvolutionMask1D< maskType > cmask
ConvolutionMask1D< maskType > rmask
Detailed Description
template<class maskType>
class VW::Convolve< maskType >
Author:
ID Reid, DW Murray
Date:
02/08/2002 @ Brief A class for performing convolutions on images.
If all you want to do is smooth an image, using VW::SmoothGaussian or VW::SmoothUniform may be easier (and faster).
Constructor & Destructor Documentation
template<class maskType> VW::Convolve< maskType >::Convolve (ConvolutionMask1D< maskType > & c, ConvolutionMask1D< maskType > & r) [inline]
template<class maskType> template<class inType , class outType > VW::Convolve< maskType >::Convolve (const ImageMono< inType > & im, ConvolutionMask1D< maskType > & c, ConvolutionMask1D< maskType > & r, ImageMono< outType > & result, const unsigned int subsampling = 1) [inline]
References VW::Convolve< maskType >::Compute().
template<class maskType> template<class inType , class outType > VW::Convolve< maskType >::Convolve (const ImageYUV< inType > & im, ConvolutionMask1D< maskType > & c, ConvolutionMask1D< maskType > & r, ImageYUV< outType > & result, const unsigned int subsampling = 1) [inline]
References VW::Convolve< maskType >::Compute().
Member Function Documentation
template<class maskType > template<class inType , class outType > void VW::Convolve< maskType >::Compute (const ImageYUV< inType > & im, ImageYUV< outType > & result, const unsigned int subsampling = 1) [inline]
References alpha, VW::PixelYUV< Type >::alpha, c, VW::Convolve< maskType >::cmask, EVEN_SYMMETRY, VW::ROI::Get(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetRowPointer(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetRowStart(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), ODD_SYMMETRY, VW::Convolve< maskType >::rmask, VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::ROI(), VW::ROI::Set(), VW::PixelYUV< Type >::u, v, VW::PixelYUV< Type >::v, VERBOSE, and VW::PixelYUV< Type >::y.
template<class maskType > template<class inType , class outType > void VW::Convolve< maskType >::Compute (const ImageMono< inType > & im, ImageMono< outType > & result, const unsigned int subsampling = 1) [inline]
References c, VW::Convolve< maskType >::cmask, EVEN_SYMMETRY, VW::ROI::Get(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetRowPointer(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetRowStart(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), ODD_SYMMETRY, VW::Convolve< maskType >::rmask, VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::ROI(), VW::ROI::Set(), VERBOSE, and VW::PixelMono< Type >::y.
Referenced by VW::Convolve< maskType >::Convolve().
Member Data Documentation
template<class maskType> ConvolutionMask1D<maskType> VW::Convolve< maskType >::cmask [protected]
Referenced by VW::Convolve< maskType >::Compute().
template<class maskType> ConvolutionMask1D<maskType> VW::Convolve< maskType >::rmask [protected]
Referenced by VW::Convolve< maskType >::Compute().
The documentation for this class was generated from the following files:
VW/Improc/convolve.h
convolve.cpp