VW: VW::Point3D Class Reference
VW::Point3D Class Reference
[GeometricObjects]
Representation of a 3D position or vector.
#include <point3d.h>
Public Member Functions
Point3D (void)
Point3D (const double x_coord, const double y_coord, const double z_coord)
Point3D (const VNL::VectorFixed< 3, double > &v)
virtual ~Point3D ()
Point3D & operator= (const Point3D &p)
Point3D & operator+= (const Point3D &p)
Point3D & operator-= (const Point3D &p)
Point3D & operator*= (double scale)
Point3D & operator/= (double scale)
bool operator== (const Point3D &p) const
bool operator!= (const Point3D &p) const
void Get (double &x_coord, double &y_coord, double &z_coord) const
double GetX (void) const
double GetY (void) const
double GetZ (void) const
VNL::VectorFixed< 3, double > GetVNL3 () const
double operator[] (unsigned int index) const
treat as an array (no bound checking!)
void Set (const double x_coord, const double y_coord, const double z_coord)
void SetX (const double x_coord)
void SetY (const double y_coord)
void SetZ (const double z_coord)
void SetVNL3 (const VNL::VectorFixed< 3, double > &vnl3)
double Norm () const
double NormSquared () const
void Normalise ()
double GetDistance (const Point3D &testpoint) const
virtual bool WriteASCII (std::ostream &stream) const
Stream as plain ASCII.
virtual bool WriteXML (std::ostream &stream, const std::string &name="") const
Stream as XML style ASCII.
virtual bool WriteBinary (std::ostream &stream) const
Stream as binary.
virtual bool ReadASCII (std::istream &stream)
Stream as plain ASCII.
virtual bool ReadXML (std::istream &stream, const std::string &name="")
Stream as XML style ASCII.
virtual bool ReadBinary (std::istream &stream)
Stream as binary.
bool WriteASCIIFile (const std::string &filename) const
Open a file and output as plain ASCII (overwriting any existing contents).
bool WriteXMLFile (const std::string &filename, const std::string &name="") const
Open a file and output as XML-style ASCII (overwriting any existing contents).
bool WriteBinaryFile (const std::string &filename) const
Open a file and output as binary (overwriting any existing contents).
virtual bool ReadASCIIFile (const std::string &filename)
Open a file and input as plain ASCII.
virtual bool ReadXMLFile (const std::string &filename, const std::string &name="")
Open a file and input as XML style ASCII.
virtual bool ReadBinaryFile (const std::string &filename)
Open a file and input as binary.
Public Attributes
double _x
double _y
double _z
Friends
Point3D operator- (const Point3D &p)
Point3D operator+ (const Point3D &p1, const Point3D &p2)
Point3D operator- (const Point3D &p1, const Point3D &p2)
double operator* (const Point3D &p1, const Point3D &p2)
Point3D operator* (const Point3D &p1, const double a)
Point3D operator* (const double a, const Point3D &p1)
Point3D operator* (const VNL::MatrixFixed< 3, 3, double > &M, const Point3D &p1)
Point3D operator/ (const Point3D &p1, const double a)
double ScalarProduct (const Point3D &p1, const Point3D &p2)
Point3D VectorProduct (const Point3D &p1, const Point3D &p2)
double ScalarTripleProduct (const Point3D &p1, const Point3D &p2, const Point3D &p3)
p1 .
Detailed Description
Representation of a 3D position or vector.
Author:
BJ Tordoff
Date:
02/08/2002 Point2D represents a position in 3D Euclidean space, and provides the expected operations of addition, subtraction, multiplication by scalars etc. In addition it inherits from the IOObject and provides the standard streaming capabilities.
Constructor & Destructor Documentation
Point3D::Point3D (void)
Point3D::Point3D (const double x_coord, const double y_coord, const double z_coord)
VW::Point3D::Point3D (const VNL::VectorFixed< 3, double > & v) [inline]
Point3D::~Point3D () [virtual]
Member Function Documentation
void Point3D::Get (double & x_coord, double & y_coord, double & z_coord) const
References _x, _y, and _z.
Referenced by VW::LineSeg3D::GetEndPoints().
double VW::Point3D::GetDistance (const Point3D & testpoint) const [inline]
References _x, _y, _z, and std::sqrt().
VNL::VectorFixed< 3, double > VW::Point3D::GetVNL3 () const [inline]
References _x, _y, and _z.
double VW::Point3D::GetX (void) const [inline]
References _x.
Referenced by VW::AWFObject::_GenList(), VW::ThreeDToolGLCommon::ActuallyDrawDistortedTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawWarpedTexturedRectangle(), VW::ThreeDToolGLCommon::Clicked(), VW::ProjectionMatrix::Compose(), VW::ThreePointPose::ComputeJacobian(), VW::ThreePointPose::ComputeQRotn(), VW::ThreeDToolGLCommon::DoDrawing(), VW::DrawFunctions::Draw(), VW::AWFEdge::Draw(), VW::ThreeDToolGLCommon::DrawAxes(), VW::ThreeDToolGLCommon::DrawCameraGraphic(), VW::ThreeDToolGLCommon::DrawCovariance(), VW::ThreeDToolGLCommon::DrawCylinder(), VW::ThreeDToolGLCommon::DrawLine(), VW::ThreeDToolGLCommon::DrawPoint(), VW::ThreeDToolGLCommon::DrawRectangle(), VW::ThreeDToolGLCommon::DrawRotationCentre(), VW::ThreeDToolGLCommon::DrawSphere(), VW::GetDerivativeRotationMatrix(), VW::RotationCentre::Include(), VW::Normalisation3D::Init(), VW::RotationMatrix::InverseRotate(), VW::ThreeDToolGLCommon::LookAt(), VW::Quaternion::operator*(), VW::operator*(), VW::CalibrationMatrix::operator*(), VW::ProjectionMatrix::Project(), VW::Project(), VW::RotationMatrix::Rotate(), VW::Round(), VW::RotationMatrix::Set(), VW::Quaternion::Set(), VW::AngleAxis::Set(), VW::PMatrixCompute::TransformToParamVec(), VW::AWFObject::Translate(), and VW::ThreeDToolGLCommon::TranslateDrawingPosition().
double VW::Point3D::GetY (void) const [inline]
References _y.
Referenced by VW::AWFObject::_GenList(), VW::ThreeDToolGLCommon::ActuallyDrawDistortedTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawWarpedTexturedRectangle(), VW::ThreeDToolGLCommon::Clicked(), VW::ProjectionMatrix::Compose(), VW::ThreePointPose::ComputeJacobian(), VW::ThreePointPose::ComputeQRotn(), VW::ThreeDToolGLCommon::DoDrawing(), VW::DrawFunctions::Draw(), VW::AWFEdge::Draw(), VW::ThreeDToolGLCommon::DrawAxes(), VW::ThreeDToolGLCommon::DrawCameraGraphic(), VW::ThreeDToolGLCommon::DrawCovariance(), VW::ThreeDToolGLCommon::DrawCylinder(), VW::ThreeDToolGLCommon::DrawLine(), VW::ThreeDToolGLCommon::DrawPoint(), VW::ThreeDToolGLCommon::DrawRectangle(), VW::ThreeDToolGLCommon::DrawRotationCentre(), VW::ThreeDToolGLCommon::DrawSphere(), VW::GetDerivativeRotationMatrix(), VW::RotationCentre::Include(), VW::Normalisation3D::Init(), VW::RotationMatrix::InverseRotate(), VW::ThreeDToolGLCommon::LookAt(), VW::Quaternion::operator*(), VW::operator*(), VW::CalibrationMatrix::operator*(), VW::ProjectionMatrix::Project(), VW::Project(), VW::RotationMatrix::Rotate(), VW::Round(), VW::RotationMatrix::Set(), VW::Quaternion::Set(), VW::AngleAxis::Set(), VW::PMatrixCompute::TransformToParamVec(), VW::AWFObject::Translate(), and VW::ThreeDToolGLCommon::TranslateDrawingPosition().
double VW::Point3D::GetZ (void) const [inline]
References _z.
Referenced by VW::AWFObject::_GenList(), VW::ThreeDToolGLCommon::ActuallyDrawDistortedTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawTexturedRectangle(), VW::ThreeDToolGLCommon::ActuallyDrawWarpedTexturedRectangle(), VW::ThreeDToolGLCommon::Clicked(), VW::ProjectionMatrix::Compose(), VW::ThreePointPose::ComputeJacobian(), VW::ThreePointPose::ComputeQRotn(), VW::ThreeDToolGLCommon::DoDrawing(), VW::ThreeDToolGLCommon::Dragged(), VW::DrawFunctions::Draw(), VW::AWFEdge::Draw(), VW::ThreeDToolGLCommon::DrawAxes(), VW::ThreeDToolGLCommon::DrawCameraGraphic(), VW::ThreeDToolGLCommon::DrawCovariance(), VW::ThreeDToolGLCommon::DrawCylinder(), VW::ThreeDToolGLCommon::DrawLine(), VW::ThreeDToolGLCommon::DrawPoint(), VW::ThreeDToolGLCommon::DrawRectangle(), VW::ThreeDToolGLCommon::DrawRotationCentre(), VW::ThreeDToolGLCommon::DrawSphere(), VW::GetDerivativeRotationMatrix(), VW::RotationCentre::Include(), VW::Normalisation3D::Init(), VW::RotationMatrix::InverseRotate(), VW::ThreeDToolGLCommon::LookAt(), VW::Quaternion::operator*(), VW::operator*(), VW::CalibrationMatrix::operator*(), VW::ProjectionMatrix::Project(), VW::Project(), VW::RotationMatrix::Rotate(), VW::Round(), VW::RotationMatrix::Set(), VW::Quaternion::Set(), VW::AngleAxis::Set(), VW::PMatrixCompute::TransformToParamVec(), VW::AWFObject::Translate(), and VW::ThreeDToolGLCommon::TranslateDrawingPosition().
double VW::Point3D::Norm (void) const [inline]
References _x, _y, _z, and std::sqrt().
Referenced by VW::Quaternion::Axis(), VW::GetDerivativeRotationMatrix(), Normalise(), VW::RotationMatrix::Set(), VW::Quaternion::Set(), and VW::ThreeDToolGLCommon::TrackBall().
void VW::Point3D::Normalise () [inline]
References _x, _y, _z, and Norm().
Referenced by VW::RotationMatrix::Axis(), VW::ThreePointPose::ComputeJacobian(), VW::ThreePointPose::ComputeJacobians(), VW::ThreeDToolGLCommon::LookAt(), VW::ThreePointPose::ThreePointPose(), and VW::ThreeDToolGLCommon::TrackBall().
double VW::Point3D::NormSquared (void) const [inline]
References _x, _y, and _z.
bool Point3D::operator!= (const Point3D & p) const
References _x, _y, and _z.
VW::Point3D & VW::Point3D::operator*= (double scale) [inline]
References _x, _y, and _z.
VW::Point3D & VW::Point3D::operator+= (const Point3D & p) [inline]
References _x, _y, and _z.
VW::Point3D & VW::Point3D::operator-= (const Point3D & p) [inline]
References _x, _y, and _z.
VW::Point3D & VW::Point3D::operator/= (double scale) [inline]
References _x, _y, and _z.
Point3D & Point3D::operator= (const Point3D & p)
References _x, _y, and _z.
bool Point3D::operator== (const Point3D & p) const
References _x, _y, and _z.
double VW::Point3D::operator[] (unsigned int index) const [inline]
treat as an array (no bound checking!)
References _x.
bool VW::Point3D::ReadASCII (std::istream & stream) [inline, virtual]
Stream as plain ASCII.
Parameters:
stream the input stream to read from
Returns:
true if successfully read, false if there are problems
Implements VW::IOObject.
References _x, _y, and _z.
bool VW::IOObject::ReadASCIIFile (const std::string & filename) [virtual, inherited]
Open a file and input as plain ASCII.
Open a file and read as plain ASCII.
Once the file is open, the child class's ReadASCII function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadASCII().
bool VW::Point3D::ReadBinary (std::istream & stream) [inline, virtual]
Stream as binary.
Parameters:
stream the input stream to read from
Returns:
true if successfully read, false if there are problems
Implements VW::IOObject.
References _x, _y, and _z.
bool VW::IOObject::ReadBinaryFile (const std::string & filename) [virtual, inherited]
Open a file and input as binary.
Open a file and read as binary.
Once the file is open, the child class's ReadBinary function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadBinary().
bool VW::Point3D::ReadXML (std::istream & stream, const std::string & name = "") [inline, virtual]
Stream as XML style ASCII.
Parameters:
stream the input stream to read from
name if specified, the found tag must have a NAME= parameter that matches
Returns:
true if successfully read, false if there are problems
Implements VW::IOObject.
References _x, _y, _z, VW::FindXMLBlock(), and VW::GetXMLBlockAsNumber().
bool VW::IOObject::ReadXMLFile (const std::string & filename, const std::string & name = "") [virtual, inherited]
Open a file and input as XML style ASCII.
Open a file and read as XML-style ASCII.
Once the file is open, the child class's ReadXML function is used to read the content.
Parameters:
filename the name of the file to open
name the optional name tag-attribute to match ie. data must start <MyClass name="name">
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadXML().
Referenced by VW::ClassifierUV::ClassifierUV(), and VW::FirewireCameraGTK::LoadParameterFile().
void VW::Point3D::Set (const double x_coord, const double y_coord, const double z_coord) [inline]
References _x, _y, and _z.
Referenced by VW::Quaternion::Axis(), VW::ProjectionMatrix::Decompose(), VW::EssentialMatrix::Decompose(), VW::ThreeDToolGLCommon::DrawAxes(), VW::RotationCentre::Reset(), VW::LineSeg3D::SetEndPoints(), and VW::DrawingPosition::Zero().
void VW::Point3D::SetVNL3 (const VNL::VectorFixed< 3, double > & vnl3) [inline]
References _x, _y, and _z.
void VW::Point3D::SetX (const double x_coord) [inline]
References _x.
Referenced by VW::RotationMatrix::Axis(), VW::RotationCentre::Include(), and VW::CalibrationMatrix::operator*().
void VW::Point3D::SetY (const double y_coord) [inline]
References _y.
Referenced by VW::RotationMatrix::Axis(), VW::RotationCentre::Include(), and VW::CalibrationMatrix::operator*().
void VW::Point3D::SetZ (const double z_coord) [inline]
References _z.
Referenced by VW::RotationMatrix::Axis(), VW::RotationCentre::Include(), and VW::CalibrationMatrix::operator*().
bool VW::Point3D::WriteASCII (std::ostream & stream) const [inline, virtual]
Stream as plain ASCII.
Parameters:
stream the output stream to write to
Returns:
true if successfully written, false if there are problems
Implements VW::IOObject.
References _x, _y, and _z.
bool VW::IOObject::WriteASCIIFile (const std::string & filename) const [inherited]
Open a file and output as plain ASCII (overwriting any existing contents).
Open a file and output as plain ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteASCII function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteASCII().
bool VW::Point3D::WriteBinary (std::ostream & stream) const [inline, virtual]
Stream as binary.
Parameters:
stream the output stream to write to
Returns:
true if successfully written, false if there are problems
Implements VW::IOObject.
References _x, _y, and _z.
bool VW::IOObject::WriteBinaryFile (const std::string & filename) const [inherited]
Open a file and output as binary (overwriting any existing contents).
Once the file is open, the child class's WriteBinary function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteBinary().
bool VW::Point3D::WriteXML (std::ostream & stream, const std::string & name = "") const [inline, virtual]
Stream as XML style ASCII.
Parameters:
stream the output stream to write to
name if specified, the class will be given a NAME= parameter
Returns:
true if successfully written, false if there are problems
Implements VW::IOObject.
References _x, _y, and _z.
bool VW::IOObject::WriteXMLFile (const std::string & filename, const std::string & name = "") const [inherited]
Open a file and output as XML-style ASCII (overwriting any existing contents).
Open a file and output as XML-style ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteXML function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
name the tag parameter, if required
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteXML().
Referenced by VW::FirewireCameraGTK::SaveParameterFile().
Friends And Related Function Documentation
Point3D operator* (const VNL::MatrixFixed< 3, 3, double > & M, const Point3D & p1) [friend]
Point3D operator* (const double a, const Point3D & p1) [friend]
Point3D operator* (const Point3D & p1, const double a) [friend]
double operator* (const Point3D & p1, const Point3D & p2) [friend]
Point3D operator+ (const Point3D & p1, const Point3D & p2) [friend]
Point3D operator- (const Point3D & p1, const Point3D & p2) [friend]
Point3D operator- (const Point3D & p) [friend]
Point3D operator/ (const Point3D & p1, const double a) [friend]
double ScalarProduct (const Point3D & p1, const Point3D & p2) [friend]
double ScalarTripleProduct (const Point3D & p1, const Point3D & p2, const Point3D & p3) [friend]
p1 .
(p2 x p3)
Point3D VectorProduct (const Point3D & p1, const Point3D & p2) [friend]
Member Data Documentation
double VW::Point3D::_x
Referenced by VW::AWFObject::_GenList(), Get(), GetDistance(), VW::LineSeg3D::GetLength2(), GetVNL3(), GetX(), Norm(), VW::Norm(), VW::Norm2(), Normalise(), NormSquared(), operator!=(), VW::operator*(), operator*=(), VW::operator+(), operator+=(), VW::operator-(), operator-=(), VW::operator/(), operator/=(), operator=(), operator==(), operator[](), ReadASCII(), ReadBinary(), ReadXML(), VW::ScalarProduct(), VW::ScalarTripleProduct(), Set(), SetVNL3(), SetX(), VW::VectorProduct(), WriteASCII(), WriteBinary(), and WriteXML().
double VW::Point3D::_y
Referenced by VW::AWFObject::_GenList(), Get(), GetDistance(), VW::LineSeg3D::GetLength2(), GetVNL3(), GetY(), Norm(), VW::Norm(), VW::Norm2(), Normalise(), NormSquared(), operator!=(), VW::operator*(), operator*=(), VW::operator+(), operator+=(), VW::operator-(), operator-=(), VW::operator/(), operator/=(), operator=(), operator==(), ReadASCII(), ReadBinary(), ReadXML(), VW::ScalarProduct(), VW::ScalarTripleProduct(), Set(), SetVNL3(), SetY(), VW::VectorProduct(), WriteASCII(), WriteBinary(), and WriteXML().
double VW::Point3D::_z
Referenced by VW::AWFObject::_GenList(), Get(), GetDistance(), VW::LineSeg3D::GetLength2(), GetVNL3(), GetZ(), Norm(), VW::Norm(), VW::Norm2(), Normalise(), NormSquared(), operator!=(), VW::operator*(), operator*=(), VW::operator+(), operator+=(), VW::operator-(), operator-=(), VW::operator/(), operator/=(), operator=(), operator==(), ReadASCII(), ReadBinary(), ReadXML(), VW::ScalarProduct(), VW::ScalarTripleProduct(), Set(), SetVNL3(), SetZ(), VW::VectorProduct(), WriteASCII(), WriteBinary(), and WriteXML().
The documentation for this class was generated from the following files:
point3d.h
point3d.cpp