VW: VW::ParametricFlowWide Class Reference
VW::ParametricFlowWide Class Reference
#include <parametricflow.h>
Public Member Functions
ParametricFlowWide (int p=8)
template<class Type >
ParametricFlowWide (const ImageMono< Type > &imold, const ImageMono< Type > &imnew, const int p, VW::Homography2D &H)
template<class Type >
void Compute (const ImageMono< Type > &imold, const ImageMono< Type > &imnew, VW::Homography2D &H)
operator bool ()
void SetParamSpace (const int p)
int GetParamSpace ()
Constructor & Destructor Documentation
VW::ParametricFlowWide::ParametricFlowWide (int p = 8) [inline]
template<class Type > VW::ParametricFlowWide::ParametricFlowWide (const ImageMono< Type > & imold, const ImageMono< Type > & imnew, const int p, VW::Homography2D & H) [inline]
References Compute().
Member Function Documentation
template<class Type > void ParametricFlowWide::Compute (const ImageMono< Type > & imold, const ImageMono< Type > & imnew, VW::Homography2D & H) [inline]
References VW::Pyramid< StorageType >::Level(), VNL::MatrixIdentity, VW::Pyramid< StorageType >::NumLevels(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::ROI(), VW::ROI::Set(), and VW::ImageMono< Type >::WriteImage().
Referenced by ParametricFlowWide().
int VW::ParametricFlowWide::GetParamSpace () [inline]
VW::ParametricFlowWide::operator bool () [inline]
void VW::ParametricFlowWide::SetParamSpace (const int p) [inline]
The documentation for this class was generated from the following files:
parametricflow.h
parametricflow.cpp