VW: VW::SequencerMovieGTK Class Reference
VW::SequencerMovieGTK Class Reference
#include <sequencermoviegtk.h>
Public Member Functions
SequencerMovieGTK (const std::string &moviename, VW::InterfaceType t=VW::INTERFACE_AS_BUTTONWINDOW)
SequencerMovieGTK (const std::vector< std::string > &movienames, VW::InterfaceType t=VW::INTERFACE_AS_BUTTONWINDOW)
~SequencerMovieGTK ()
virtual bool Init ()
All sequencers have an Init(), even if they don't need it, so call init() before using a sequencer (especially if from an interface).
virtual void Continuous ()
Start continuous capture from the sequence.
virtual void Stop ()
Stop continuous capture from the sequence.
virtual void Next ()
Capture the next single frame.
virtual void Rewind ()
Re-open this file and start from the beginning.
void CreateForm ()
void UpdateForm ()
void UpdateFromForm ()
void LoadParameterFile (std::string paramfile=".param")
void SaveParameterFile (std::string paramfile=".param")
void Show (void)
void Hide (void)
void Quit (void)
VW::InterfaceType GetType (void)
void AddChannel (const std::string &file_name)
void * GetBuffer (unsigned int which_channel=0)
Gain access to the sequencers buffer.
template<class ImType >
void CopyImage (ImType &image, unsigned int which_channel=0)
Take a copy of the grabbed image.
std::string GetMovieName (unsigned int which_channel=0)
The name(s) of the movies.
int GetY4MPID (unsigned int which_channel=0)
The pid(s) of the y4mtoppm processes.
void _cleanup (int which_channel)
remove temporary files created for mplayer and y4mtoppm
Initialisation functions
virtual void SetDelay (int d)
Set the delay between frames (only usually used for non-hardware sequencers).
Information functions
bool GetContinuous () const
Is the sequencer running in continuous mode?
int GetDelay () const
What is the delay between frames.
unsigned int GetNumberOfChannels () const
Most sequencers are able to present mutliple images per frame.
unsigned int GetCurrentFrameNumber () const
Return the current frame number.
Public Attributes
VWEvents::Event1< void, int > NewFrameEvent
The "new frame has arrived" event.
Protected Member Functions
void LoadStart ()
void LoadOK ()
void SaveStart ()
void SaveOK ()
void FileCancel ()
virtual void InitButtonWindow ()
virtual void InitButtonWindow (unsigned int width, unsigned int height)
virtual void InitWidget ()
void _InitialiseMovies ()
void _OpenFile (unsigned int which_channel)
virtual bool _Step ()
void _WaitForThread ()
Wait for the thread to exit.
virtual void _FrameArrived ()
we have been signalled that a frame has arrived and we are now "inside" the signalling object, so invoke the appropriate callback
void * Main (void *)
void _CheckInitialised ()
Protected Attributes
SigC::Signal1< void, std::string > LoadEvent
SigC::Signal1< void, std::string > SaveEvent
SequencerMovieGTKWidget * my_widget
Gtk::Window * my_window
VW::InterfaceType my_type
std::string my_name
Gtk::FileSelection * file_selector
std::vector< ImageRGB
< unsigned char > * > im
std::vector< FILE * > fp
std::vector< std::string > movienames
std::vector< bool > file_ok
std::vector< int > y4m_pid
std::vector< int > mplayer_pid
std::vector< char * > streamname
int delay
unsigned int frame_number
bool cont
bool thread_running
bool _initialised
ThreadType parent
unsigned int number_of_channels
Mutex access_lock
bool user_finished
Constructor & Destructor Documentation
VW::SequencerMovieGTK::SequencerMovieGTK (const std::string & moviename, VW::InterfaceType t = VW::INTERFACE_AS_BUTTONWINDOW)
VW::SequencerMovieGTK::SequencerMovieGTK (const std::vector< std::string > & movienames, VW::InterfaceType t = VW::INTERFACE_AS_BUTTONWINDOW)
VW::SequencerMovieGTK::~SequencerMovieGTK ()
References Stop().
Member Function Documentation
void VW::SequencerBase::_CheckInitialised () [protected, inherited]
References VW::SequencerBase::_initialised.
Referenced by VW::SequencerBase::Continuous(), VW::SequencerBase::Next(), and VW::SequencerBase::Stop().
void SequencerMovie::_cleanup (int which_channel) [inherited]
remove temporary files created for mplayer and y4mtoppm
References VW::SequencerMovie::streamname.
Referenced by VW::SequencerMovie::_OpenFile().
void SequencerBase::_FrameArrived () [protected, virtual, inherited]
we have been signalled that a frame has arrived and we are now "inside" the signalling object, so invoke the appropriate callback
Reimplemented in VW::SequencerFileGTK, VW::SequencerFirewireGTK, VW::SequencerFileWx, VW::SequencerFirewireWx, and VW::SequencerMeteor.
References VW::SequencerBase::NewFrameEvent, VW::SequencerBase::user_finished, and VERBOSE.
Referenced by VW::SequencerBase::Main(), and VW::SequencerBase::Next().
void VW::SequencerMovie::_InitialiseMovies () [protected, inherited]
void SequencerMovie::_OpenFile (unsigned int which_channel) [protected, inherited]
References VW::SequencerMovie::_cleanup(), VW::SequencerMovie::file_ok, VW::SequencerMovie::fp, VW::SequencerMovie::movienames, VW::SequencerMovie::mplayer_pid, VW::SequencerMovie::streamname, and VW::SequencerMovie::y4m_pid.
Referenced by VW::SequencerMovie::Rewind(), and UpdateFromForm().
bool SequencerMovie::_Step () [protected, virtual, inherited]
Implements VW::SequencerBase.
References VW::SequencerBase::cont, VW::SequencerMovie::file_ok, VW::SequencerMovie::fp, VW::SequencerBase::frame_number, VW::SequencerMovie::im, VW::SequencerMovie::movienames, VW::SequencerBase::number_of_channels, VW::ReadImage(), and VW::SequencerBase::Stop().
void SequencerBase::_WaitForThread () [inline, protected, inherited]
Wait for the thread to exit.
References VW::SequencerBase::access_lock, VW::Mutex::Lock(), msleep(), VW::SequencerBase::thread_running, VW::Mutex::Unlock(), and VERBOSE.
Referenced by VW::SequencerBase::Stop().
void VW::SequencerMovie::AddChannel (const std::string & file_name) [inherited]
void VW::SequencerMovieGTK::Continuous () [virtual]
Start continuous capture from the sequence.
Reimplemented from VW::SequencerBase.
References UpdateForm().
Referenced by VW::SequencerMovieGTKWidget::InitForm().
template<class ImType > void VW::SequencerMovie::CopyImage (ImType & image, unsigned int which_channel = 0) [inline, inherited]
Take a copy of the grabbed image.
References VW::SequencerMovie::im, and VW::ImageCopy().
void VW::SequencerMovieGTK::CreateForm ()
void VW::InterfaceGTK< SequencerMovieGTKWidget >::FileCancel () [inline, protected, inherited]
void * VW::SequencerMovie::GetBuffer (unsigned int which_channel = 0) [inline, virtual, inherited]
Gain access to the sequencers buffer.
Implements VW::SequencerBase.
References VW::SequencerMovie::im.
bool VW::SequencerBase::GetContinuous () const [inline, inherited]
Is the sequencer running in continuous mode?
References VW::SequencerBase::cont.
unsigned int VW::SequencerBase::GetCurrentFrameNumber () const [inline, inherited]
Return the current frame number.
In the case of movies or files this is the frame number with respect to the start frame (ie, 1=start frame) and won't correspond to the sequence frame numbers if started part way through a sequence.
References VW::SequencerBase::frame_number.
int VW::SequencerBase::GetDelay () const [inline, inherited]
What is the delay between frames.
References VW::SequencerBase::delay.
std::string VW::SequencerMovie::GetMovieName (unsigned int which_channel = 0) [inline, inherited]
The name(s) of the movies.
References VW::SequencerMovie::movienames.
Referenced by VW::SequencerMovieGTKWidget::InitForm().
unsigned int VW::SequencerBase::GetNumberOfChannels () const [inline, inherited]
Most sequencers are able to present mutliple images per frame.
References VW::SequencerBase::number_of_channels.
Referenced by VW::SequencerMovieGTKWidget::InitForm(), and VW::SequencerFileGTKWidget::InitForm().
VW::InterfaceType VW::InterfaceGTK< SequencerMovieGTKWidget >::GetType (void) [inline, inherited]
int VW::SequencerMovie::GetY4MPID (unsigned int which_channel = 0) [inline, inherited]
The pid(s) of the y4mtoppm processes.
References VW::SequencerMovie::y4m_pid.
void VW::InterfaceGTK< SequencerMovieGTKWidget >::Hide (void) [inline, inherited]
bool VW::SequencerMovieGTK::Init () [virtual]
All sequencers have an Init(), even if they don't need it, so call init() before using a sequencer (especially if from an interface).
Reimplemented from VW::SequencerBase.
References UpdateForm().
virtual void VW::InterfaceGTK< SequencerMovieGTKWidget >::InitButtonWindow (unsigned int width, unsigned int height) [protected, virtual, inherited]
virtual void VW::InterfaceGTK< SequencerMovieGTKWidget >::InitButtonWindow () [protected, virtual, inherited]
virtual void VW::InterfaceGTK< SequencerMovieGTKWidget >::InitWidget () [protected, virtual, inherited]
void VW::InterfaceGTK< SequencerMovieGTKWidget >::LoadOK () [inline, protected, inherited]
void VW::SequencerMovieGTK::LoadParameterFile (std::string paramfile = ".param") [inline]
void VW::InterfaceGTK< SequencerMovieGTKWidget >::LoadStart () [inline, protected, inherited]
void * SequencerBase::Main (void *) [protected, virtual, inherited]
Implements VW::Thread.
References VW::SequencerBase::_FrameArrived(), VW::SequencerBase::_Step(), VW::SequencerBase::access_lock, VW::SequencerBase::cont, VW::SequencerBase::delay, VW::SequencerBase::frame_number, VW::Mutex::Lock(), msleep(), VW::SequencerBase::thread_running, VW::Mutex::Unlock(), and VERBOSE.
void VW::SequencerMovieGTK::Next () [virtual]
Capture the next single frame.
Reimplemented from VW::SequencerBase.
References UpdateForm().
Referenced by VW::SequencerMovieGTKWidget::InitForm().
void VW::InterfaceGTK< SequencerMovieGTKWidget >::Quit (void) [inline, inherited]
void VW::SequencerMovieGTK::Rewind () [virtual]
Re-open this file and start from the beginning.
Reimplemented from VW::SequencerMovie.
References UpdateForm().
Referenced by VW::SequencerMovieGTKWidget::InitForm().
void VW::InterfaceGTK< SequencerMovieGTKWidget >::SaveOK () [inline, protected, inherited]
void VW::SequencerMovieGTK::SaveParameterFile (std::string paramfile = ".param") [inline]
void VW::InterfaceGTK< SequencerMovieGTKWidget >::SaveStart () [inline, protected, inherited]
void VW::SequencerBase::SetDelay (int d) [inline, virtual, inherited]
Set the delay between frames (only usually used for non-hardware sequencers).
This is the time (in milliseconds) for which the sequencer sleeps between frames: the total frame period will be this plus the time taken to acquire the new frame. By default the delay is set to 1ms (zero or less is not a valid setting).
References VW::SequencerBase::delay.
void VW::InterfaceGTK< SequencerMovieGTKWidget >::Show (void) [inline, inherited]
void VW::SequencerMovieGTK::Stop () [virtual]
Stop continuous capture from the sequence.
Reimplemented from VW::SequencerBase.
References UpdateForm().
Referenced by VW::SequencerMovieGTKWidget::InitForm(), and ~SequencerMovieGTK().
void VW::SequencerMovieGTK::UpdateForm (void) [virtual]
Implements VW::InterfaceGTK< SequencerMovieGTKWidget >.
References VW::SequencerBase::cont, VW::SequencerMovie::file_ok, VW::SequencerMovieGTKWidget::go_button, VW::InterfaceGTK< SequencerMovieGTKWidget >::my_widget, VW::SequencerMovieGTKWidget::next_button, VW::SequencerBase::number_of_channels, VW::SequencerMovieGTKWidget::rewind_button, VW::SequencerMovieGTKWidget::SetLED(), and VW::SequencerMovieGTKWidget::stop_button.
Referenced by Continuous(), Init(), Next(), Rewind(), Stop(), and UpdateFromForm().
void VW::SequencerMovieGTK::UpdateFromForm ()
References VW::SequencerMovie::_OpenFile(), VW::SequencerMovieGTKWidget::GetMovieName(), VW::InterfaceGTK< SequencerMovieGTKWidget >::my_widget, VW::SequencerBase::number_of_channels, and UpdateForm().
Referenced by VW::SequencerMovieChannelGTKWidget::InitForm(), VW::SequencerMovieChannelGTKWidget::LoadCancel(), and VW::SequencerMovieChannelGTKWidget::LoadOK().
Member Data Documentation
bool VW::SequencerBase::_initialised [protected, inherited]
Referenced by VW::SequencerBase::_CheckInitialised(), and VW::SequencerBase::Init().
Mutex VW::SequencerBase::access_lock [protected, inherited]
Referenced by VW::SequencerFile::_Step(), VW::SequencerBase::_WaitForThread(), VW::SequencerBase::Continuous(), VW::SequencerBase::Main(), VW::SequencerBase::Next(), VW::SequencerFile::Rewind(), VW::SequencerFile::Skip(), and VW::SequencerBase::Stop().
bool VW::SequencerBase::cont [protected, inherited]
Referenced by VW::SequencerMovie::_Step(), VW::SequencerFirewire::_Step(), VW::SequencerFile::_Step(), VW::SequencerBase::Continuous(), VW::SequencerBase::GetContinuous(), VW::SequencerBase::Main(), VW::SequencerBase::Next(), VW::SequencerBase::Stop(), UpdateForm(), VW::SequencerFirewireWx::UpdateForm(), VW::SequencerFileWx::UpdateForm(), and VW::SequencerFileGTK::UpdateForm().
int VW::SequencerBase::delay [protected, inherited]
Referenced by VW::SequencerBase::GetDelay(), VW::SequencerBase::Main(), and VW::SequencerBase::SetDelay().
std::vector<bool> VW::SequencerMovie::file_ok [protected, inherited]
Referenced by VW::SequencerMovie::_OpenFile(), VW::SequencerMovie::_Step(), VW::SequencerMovie::Rewind(), and UpdateForm().
Gtk::FileSelection* VW::InterfaceGTK< SequencerMovieGTKWidget >::file_selector [protected, inherited]
std::vector<FILE*> VW::SequencerMovie::fp [protected, inherited]
Referenced by VW::SequencerMovie::_OpenFile(), and VW::SequencerMovie::_Step().
unsigned int VW::SequencerBase::frame_number [protected, inherited]
Referenced by VW::SequencerFile::_InitialiseFiles(), VW::SequencerMovie::_Step(), VW::SequencerFile::_Step(), VW::SequencerBase::GetCurrentFrameNumber(), VW::SequencerBase::Main(), VW::SequencerMovie::Rewind(), VW::SequencerFile::Rewind(), VW::SequencerFile::SequencerFile(), VW::SequencerFile::Skip(), VW::SequencerFileWx::UpdateForm(), and VW::SequencerFileGTK::UpdateForm().
std::vector<ImageRGB<unsigned char>* > VW::SequencerMovie::im [protected, inherited]
Referenced by VW::SequencerMovie::_Step(), VW::SequencerMovie::CopyImage(), and VW::SequencerMovie::GetBuffer().
SigC::Signal1<void,std::string> VW::InterfaceGTK< SequencerMovieGTKWidget >::LoadEvent [protected, inherited]
std::vector<std::string> VW::SequencerMovie::movienames [protected, inherited]
Referenced by VW::SequencerMovie::_OpenFile(), VW::SequencerMovie::_Step(), and VW::SequencerMovie::GetMovieName().
std::vector<int> VW::SequencerMovie::mplayer_pid [protected, inherited]
Referenced by VW::SequencerMovie::_OpenFile().
std::string VW::InterfaceGTK< SequencerMovieGTKWidget >::my_name [protected, inherited]
VW::InterfaceType VW::InterfaceGTK< SequencerMovieGTKWidget >::my_type [protected, inherited]
SequencerMovieGTKWidget * VW::InterfaceGTK< SequencerMovieGTKWidget >::my_widget [protected, inherited]
Referenced by UpdateForm(), and UpdateFromForm().
Gtk::Window* VW::InterfaceGTK< SequencerMovieGTKWidget >::my_window [protected, inherited]
VWEvents::Event1<void,int> VW::SequencerBase::NewFrameEvent [inherited]
The "new frame has arrived" event.
Attach a function to this callback signal if you want to perform an operation each time a new image arrives. This is typically done using my_sequencer.NewFrameEvent.connect(&MyFunction); where 'MyFunction' must take an integer argument and return void.
Referenced by VW::SequencerMeteor::_FrameArrived(), VW::SequencerFirewireWx::_FrameArrived(), VW::SequencerFirewireGTK::_FrameArrived(), VW::SequencerFileWx::_FrameArrived(), VW::SequencerFileGTK::_FrameArrived(), and VW::SequencerBase::_FrameArrived().
unsigned int VW::SequencerBase::number_of_channels [protected, inherited]
Referenced by VW::SequencerFile::_InitialiseFiles(), VW::SequencerMovie::_Step(), VW::SequencerFirewire::_Step(), VW::SequencerFile::_Step(), VW::SequencerFile::CopyImage(), VW::SequencerFirewire::GetCamera(), VW::SequencerFirewire::GetNumberOfCameras(), VW::SequencerBase::GetNumberOfChannels(), VW::SequencerMeteor::Init(), VW::SequencerFirewire::ProbeForCameras(), VW::SequencerMovie::Rewind(), VW::SequencerFile::Rewind(), VW::SequencerFile::SequencerFile(), VW::SequencerFirewire::SequencerFirewire(), VW::SequencerMovie::SequencerMovie(), VW::SequencerFirewire::SetDefaultCameraSettings(), VW::SequencerFile::Skip(), VW::SequencerFirewire::StartDMA(), VW::SequencerFirewire::StartISO(), VW::SequencerFirewire::StopDMA(), VW::SequencerFirewire::StopISO(), UpdateForm(), VW::SequencerFileWx::UpdateForm(), VW::SequencerFileGTK::UpdateForm(), UpdateFromForm(), and VW::SequencerFileGTK::UpdateFromForm().
ThreadType VW::SequencerBase::parent [protected, inherited]
SigC::Signal1<void,std::string> VW::InterfaceGTK< SequencerMovieGTKWidget >::SaveEvent [protected, inherited]
std::vector<char *> VW::SequencerMovie::streamname [protected, inherited]
Referenced by VW::SequencerMovie::_cleanup(), and VW::SequencerMovie::_OpenFile().
bool VW::SequencerBase::thread_running [protected, inherited]
Referenced by VW::SequencerFirewire::_Step(), VW::SequencerBase::_WaitForThread(), and VW::SequencerBase::Main().
bool VW::SequencerBase::user_finished [protected, inherited]
Referenced by VW::SequencerFirewireWx::_FrameArrived(), VW::SequencerFirewireGTK::_FrameArrived(), VW::SequencerFileWx::_FrameArrived(), VW::SequencerFileGTK::_FrameArrived(), and VW::SequencerBase::_FrameArrived().
std::vector<int> VW::SequencerMovie::y4m_pid [protected, inherited]
Referenced by VW::SequencerMovie::_OpenFile(), and VW::SequencerMovie::GetY4MPID().
The documentation for this class was generated from the following files:
sequencermoviegtk.h
sequencermoviegtk.cpp