VW: VW::Pyramid< StorageType > Class Template Reference
VW::Pyramid< StorageType > Class Template Reference
[ImageProcessing]
Construct an image pyramid from an image.
#include <pyramid.h>
Public Member Functions
Pyramid ()
Default constructor.
Pyramid (unsigned int base_width, unsigned int base_height, unsigned int minsize=32, unsigned int num_levels_per_octave=1)
Construct and reserve memory for manual manipulation.
template<class ImageType >
Pyramid (const ImageType &im, unsigned int minsize=32, unsigned int num_levels_per_octave=1, bool quick_and_dirty=false)
Construct and compute (note that the pyramid is monochrome regardless of the input image type).
~Pyramid ()
template<class ImageType >
void Compute (const ImageType &im, unsigned int minsize=32, unsigned int num_levels_per_octave=1, bool quick_and_dirty=false)
Compute the pyramid based on the supplied image (note that the pyramid is monochrome regardless of the input image type).
void location (int c, int r, int nsrc, int ndest, int &cres, int &rres)
BJT: Anyone know what this is for? Why it is lower case etc?
unsigned int GetNumLevels () const
The number of levels (images) contained in this pyramid.
unsigned int NumLevels () const
unsigned int GetNumLevelsPerOctave () const
The number of levels (images) in each scale octave of this pyramid.
unsigned int GetNumOctaves () const
The number of (complete) scale octaves in this pyramid.
unsigned int GetMinSize () const
The smallest dimension of the levels.
unsigned int GetWidth (unsigned int which_level=0) const
The width of the specified level (or the largest width if not specified).
unsigned int GetHeight (unsigned int which_level=0) const
The height of the specified level (or the largest height if not specified).
const std::vector< ImageMono
< StorageType > * > & Level () const
Get access to the array of images.
const ImageMono< StorageType > & operator[] (int i) const
Access a particular level (read only).
ImageMono< StorageType > & operator[] (int i)
Access a particular level (read/write).
float ScalingFactor () const
The scale factor between successive levels (0.5 for sumbsample by 2).
float GetScale (unsigned int which_level) const
Get the scale factor associated with a level of the pyramid (this is the ratio of the image size compared to the base image size, and is always less than 1).
int ClosestLevel (float scale) const
Determine the level that is closest to this scale.
Protected Member Functions
void AllocMemory (unsigned int base_width, unsigned int base_height, unsigned int minsize)
void AverageAndSubsampleBy2 (const VW::ImageMono< StorageType > &source_image, VW::ImageMono< StorageType > &dest_image)
A function to combine smoothing and subsampling in a quick and dirty fashion.
Protected Attributes
unsigned int _num_levels
unsigned int _num_levels_per_octave
float scaling_factor
std::vector< ImageMono
< StorageType > * > level
Detailed Description
template<class StorageType>
class VW::Pyramid< StorageType >
Construct an image pyramid from an image.
Author:
ID Reid, JGH Knight
Date:
02/08/2002 The image pyramid consists of subsampled octaves of the base image, but whereas the input image can be in any format (providing it can be converted to the storage type), the pyramid is always monochrome (perhaps should PyramidMono?). Subsampling can be performed either using the correct method of Gaussian smoothing at the nyquist frequency followed by decimation, or using the faster method of averaging 2x2 blocks of pixels before decimation.
Constructor & Destructor Documentation
template<class StorageType > VW::Pyramid< StorageType >::Pyramid () [inline]
Default constructor.
If you do not supply an image at object creation, you will have to subsequently call one of the compute methods below.
template<class StorageType > VW::Pyramid< StorageType >::Pyramid (unsigned int base_width, unsigned int base_height, unsigned int minsize = 32, unsigned int num_levels_per_octave = 1) [inline]
Construct and reserve memory for manual manipulation.
Only use this if you want to fill the pyramid yourself later.
References VW::Pyramid< StorageType >::AllocMemory().
template<class StorageType > template<class ImageType > VW::Pyramid< StorageType >::Pyramid (const ImageType & im, unsigned int minsize = 32, unsigned int num_levels_per_octave = 1, bool quick_and_dirty = false) [inline, explicit]
Construct and compute (note that the pyramid is monochrome regardless of the input image type).
This constructs the object and calls the compute function with (optional) parameters for size, number of levels etc.
References VW::Pyramid< StorageType >::Compute().
template<class StorageType > VW::Pyramid< StorageType >::~Pyramid () [inline]
References VW::Pyramid< StorageType >::_num_levels, and VW::Pyramid< StorageType >::level.
Member Function Documentation
template<class StorageType > void VW::Pyramid< StorageType >::AllocMemory (unsigned int base_width, unsigned int base_height, unsigned int minsize) [inline, protected]
References VW::Pyramid< StorageType >::_num_levels, VW::Pyramid< StorageType >::_num_levels_per_octave, VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), VW::Pyramid< StorageType >::level, and VW::Pyramid< StorageType >::scaling_factor.
Referenced by VW::Pyramid< StorageType >::Pyramid().
template<class StorageType> void Pyramid::AverageAndSubsampleBy2 (const VW::ImageMono< StorageType > & source_image, VW::ImageMono< StorageType > & dest_image) [inline, protected]
A function to combine smoothing and subsampling in a quick and dirty fashion.
References VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::AllocImageData(), c, VW::ROI::Get(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetROIRowStart(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::IsAlloced(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::ROI(), VW::ROI::Set(), and VW::PixelMono< Type >::y.
Referenced by VW::Pyramid< StorageType >::Compute().
template<class StorageType > int VW::Pyramid< StorageType >::ClosestLevel (float scale) const [inline]
Determine the level that is closest to this scale.
References VW::Pyramid< StorageType >::scaling_factor.
Referenced by VW::GetSIFTDescriptor::Compute(), and VW::GetPatchDescriptor::Compute().
template<class StorageType > template<class ImageType > void Pyramid::Compute (const ImageType & im, unsigned int minsize = 32, unsigned int num_levels_per_octave = 1, bool quick_and_dirty = false) [inline]
Compute the pyramid based on the supplied image (note that the pyramid is monochrome regardless of the input image type).
Only call the compute function if you didn't construct the object with an image. If quick and dirty is false (default) then Ian's method is used, where convolution is with an approximately Gaussian kernel. The alternative method just averages 2x2 blocks of pixels, which may give some marginal speed improvements.
References VW::Pyramid< StorageType >::_num_levels, VW::Pyramid< StorageType >::_num_levels_per_octave, VW::Pyramid< StorageType >::AverageAndSubsampleBy2(), VW::Bilinear, VW::ScaleImage::Compute(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), VW::ImageCopy(), VW::Pyramid< StorageType >::level, VW::ConvolutionMask1D< maskType >::MakeGaussian(), and VW::Pyramid< StorageType >::scaling_factor.
Referenced by VW::Pyramid< StorageType >::Pyramid().
template<class StorageType > unsigned int VW::Pyramid< StorageType >::GetHeight (unsigned int which_level = 0) const [inline]
The height of the specified level (or the largest height if not specified).
References VW::Pyramid< StorageType >::level.
Referenced by VW::DOGDetector::Compute().
template<class StorageType > unsigned int VW::Pyramid< StorageType >::GetMinSize () const [inline]
The smallest dimension of the levels.
References VW::Pyramid< StorageType >::_num_levels, and VW::Pyramid< StorageType >::level.
Referenced by VW::DOGDetector::Compute().
template<class StorageType > unsigned int VW::Pyramid< StorageType >::GetNumLevels () const [inline]
The number of levels (images) contained in this pyramid.
References VW::Pyramid< StorageType >::_num_levels.
template<class StorageType > unsigned int VW::Pyramid< StorageType >::GetNumLevelsPerOctave () const [inline]
The number of levels (images) in each scale octave of this pyramid.
References VW::Pyramid< StorageType >::_num_levels_per_octave.
Referenced by VW::DOGDetector::Compute().
template<class StorageType > unsigned int VW::Pyramid< StorageType >::GetNumOctaves () const [inline]
The number of (complete) scale octaves in this pyramid.
References VW::Pyramid< StorageType >::_num_levels, and VW::Pyramid< StorageType >::_num_levels_per_octave.
template<class StorageType > float VW::Pyramid< StorageType >::GetScale (unsigned int which_level) const [inline]
Get the scale factor associated with a level of the pyramid (this is the ratio of the image size compared to the base image size, and is always less than 1).
References VW::Pyramid< StorageType >::scaling_factor.
Referenced by VW::ShiTomasiDetector::Compute(), VW::PlesseyDetector::Compute(), VW::GetSIFTDescriptor::Compute(), and VW::GetPatchDescriptor::Compute().
template<class StorageType > unsigned int VW::Pyramid< StorageType >::GetWidth (unsigned int which_level = 0) const [inline]
The width of the specified level (or the largest width if not specified).
References VW::Pyramid< StorageType >::level.
Referenced by VW::DOGDetector::Compute().
template<class StorageType > const std::vector< VW::ImageMono< StorageType > * > & VW::Pyramid< StorageType >::Level () const [inline]
Get access to the array of images.
References VW::Pyramid< StorageType >::level.
Referenced by VW::ParametricFlowWide::Compute().
template<class StorageType > void Pyramid::location (int c, int r, int nsrc, int ndest, int & cres, int & rres) [inline]
BJT: Anyone know what this is for? Why it is lower case etc?
References VW::Pyramid< StorageType >::level.
template<class StorageType > unsigned int VW::Pyramid< StorageType >::NumLevels () const [inline]
References VW::Pyramid< StorageType >::_num_levels.
Referenced by VW::ShiTomasiDetector::Compute(), VW::PyramidCorrelate::Compute(), VW::PlesseyDetector::Compute(), VW::ParametricFlowWide::Compute(), and VW::PyramidCorrelate::PyramidCorrelate().
template<class StorageType > VW::ImageMono< StorageType > & VW::Pyramid< StorageType >::operator[] (int i) [inline]
Access a particular level (read/write).
References VW::Pyramid< StorageType >::level.
template<class StorageType > const VW::ImageMono< StorageType > & VW::Pyramid< StorageType >::operator[] (int i) const [inline]
Access a particular level (read only).
References VW::Pyramid< StorageType >::level.
template<class StorageType > float VW::Pyramid< StorageType >::ScalingFactor () const [inline]
The scale factor between successive levels (0.5 for sumbsample by 2).
References VW::Pyramid< StorageType >::scaling_factor.
Member Data Documentation
template<class StorageType> unsigned int VW::Pyramid< StorageType >::_num_levels [protected]
Referenced by VW::Pyramid< StorageType >::AllocMemory(), VW::Pyramid< StorageType >::Compute(), VW::Pyramid< StorageType >::GetMinSize(), VW::Pyramid< StorageType >::GetNumLevels(), VW::Pyramid< StorageType >::GetNumOctaves(), VW::Pyramid< StorageType >::NumLevels(), and VW::Pyramid< StorageType >::~Pyramid().
template<class StorageType> unsigned int VW::Pyramid< StorageType >::_num_levels_per_octave [protected]
Referenced by VW::Pyramid< StorageType >::AllocMemory(), VW::Pyramid< StorageType >::Compute(), VW::Pyramid< StorageType >::GetNumLevelsPerOctave(), and VW::Pyramid< StorageType >::GetNumOctaves().
template<class StorageType> std::vector<ImageMono<StorageType> *> VW::Pyramid< StorageType >::level [protected]
Referenced by VW::Pyramid< StorageType >::AllocMemory(), VW::Pyramid< StorageType >::Compute(), VW::Pyramid< StorageType >::GetHeight(), VW::Pyramid< StorageType >::GetMinSize(), VW::Pyramid< StorageType >::GetWidth(), VW::Pyramid< StorageType >::Level(), VW::Pyramid< StorageType >::location(), VW::Pyramid< StorageType >::operator[](), and VW::Pyramid< StorageType >::~Pyramid().
template<class StorageType> float VW::Pyramid< StorageType >::scaling_factor [protected]
Referenced by VW::Pyramid< StorageType >::AllocMemory(), VW::Pyramid< StorageType >::ClosestLevel(), VW::Pyramid< StorageType >::Compute(), VW::Pyramid< StorageType >::GetScale(), and VW::Pyramid< StorageType >::ScalingFactor().
The documentation for this class was generated from the following files:
pyramid.h
pyramid.cpp