VW: VW::GetPatchDescriptor Class Reference
VW::GetPatchDescriptor Class Reference
[ImageProcessing]
Describe image features by the surrounding patch (with normalisation).
#include <getpatchdescriptor.h>
Public Member Functions
GetPatchDescriptor (const unsigned int patch_size=7, const bool weighted=false, const bool oriented=false)
Construct and set params.
GetPatchDescriptor (const std::vector< VW::CornerFeature > &locations, const VW::Pyramid< float > &pyramid, std::vector< VW::PatchFeature > &resulting_features, const unsigned int patch_size=7, const bool weighted=false, const bool oriented=false)
Calculate a set of PatchFeatures from a set of locations.
bool Compute (const std::vector< VW::CornerFeature > &locations, const VW::Pyramid< float > &pyramid, std::vector< VW::PatchFeature > &resulting_features) const
Detailed Description
Describe image features by the surrounding patch (with normalisation).
Author:
BJ Tordoff
Date:
25/11/2004 include <VW/Improc/getpatchdescriptor.h>
The normalisation can optionally be weighted, giving a distribution which is still zero mean and unit variance, but where the central values are given more prominence (at the cost of some initialisation time).
Constructor & Destructor Documentation
VW::GetPatchDescriptor::GetPatchDescriptor (const unsigned int patch_size = 7, const bool weighted = false, const bool oriented = false) [inline]
Construct and set params.
Note that weighting and orienting the patches improves matching but makes the aquistion step take longer.
Parameters:
patch_size the size of the (square) patch - must be odd
weighted should the patch be centrally weighted?
weighted should the patch be align to the dominent orientation?
VW::GetPatchDescriptor::GetPatchDescriptor (const std::vector< VW::CornerFeature > & locations, const VW::Pyramid< float > & pyramid, std::vector< VW::PatchFeature > & resulting_features, const unsigned int patch_size = 7, const bool weighted = false, const bool oriented = false) [inline]
Calculate a set of PatchFeatures from a set of locations.
Each location can give rise to more than one feature since it may have ambiguous dominant direction.
Parameters:
patch_size the size of the (square) patch - must be odd
References Compute().
Member Function Documentation
bool VW::GetPatchDescriptor::Compute (const std::vector< VW::CornerFeature > & locations, const VW::Pyramid< float > & pyramid, std::vector< VW::PatchFeature > & resulting_features) const
References VW::ROI::Bottom(), VW::Pyramid< StorageType >::ClosestLevel(), VW::CornerFeature::GetFeatureScale(), VW::Pyramid< StorageType >::GetScale(), VW::Point2D::GetX(), VW::Point2D::GetY(), VW::ROI::Left(), VW::ROI::Right(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::ROI(), std::sqrt(), VW::ROI::Top(), and VERBOSE.
Referenced by GetPatchDescriptor().
The documentation for this class was generated from the following files:
getpatchdescriptor.h
getpatchdescriptor.cpp