VW: vnl_finite_int< N > Class Template Reference
vnl_finite_int< N > Class Template Reference
finite modulo-N arithmetic.
#include <finite.h>
Public Member Functions
vnl_finite_int (int x=0)
Creates a finite int element.
vnl_finite_int (Base const &x)
~vnl_finite_int ()
operator int () const
operator int ()
operator long () const
operator long ()
operator short () const
operator short ()
Base & operator= (Base const &x)
Assignment.
Base & operator= (int x)
bool operator== (Base const &x) const
Comparison of finite int numbers.
bool operator!= (Base const &x) const
bool operator== (int x) const
bool operator!= (int x) const
Base operator- () const
Unary minus - returns the additive inverse.
Base operator+ () const
Unary plus - returns the current number.
bool operator! () const
Unary not - returns true if finite int number is equal to zero.
Base & operator+= (Base const &r)
Plus&assign: replace lhs by lhs + rhs.
Base & operator+= (int r)
Base & operator-= (Base const &r)
Minus&assign: replace lhs by lhs - rhs.
Base & operator-= (int r)
Base & operator*= (int r)
Multiply&assign: replace lhs by lhs * rhs.
Base & operator*= (Base const &r)
Multiply&assign: replace lhs by lhs * rhs.
Base reciproc () const
Multiplicative inverse.
Base & operator/= (Base const &r)
Divide&assign. Uses r.reciproc() for efficient computation.
Base & operator++ ()
Pre-increment (++r).
Base & operator-- ()
Pre-decrement (--r).
Base operator++ (int)
Post-increment (r++).
Base operator-- (int)
Post-decrement (r--).
bool is_unit () const
Return true only when x is a unit in this ring.
bool is_zero_divisor () const
Return true only when x is a zero divisor, i.e., is not a unit.
unsigned int additive_order () const
The additive order of x is the smallest nonnegative r such that r*x == 0.
unsigned int multiplicative_order () const
The multiplicative order of x is the smallest r (>0) such that x^r == 1.
Base pow (int r)
Return the r-th power of this number.
unsigned int log () const
Return the smallest nonnegative exponent r for which x=g^r, where g is the smallest generator.
Static Public Member Functions
static unsigned int cardinality ()
The number of different finite_int numbers of this type.
static unsigned int totient ()
Return the Euler totient function, i.e., the number of units of this ring.
static std::vector< unsigned int > decompose ()
Write N as the unique product of prime factors.
static bool is_field ()
Return true when N is a prime number, i.e., when this ring is a field.
static Base smallest_generator ()
Return the smallest multiplicative generator of the units in this ring.
static Base exp (int r)
Return the inverse of log(), i.e., return g^r where g is the smallest generator.
static unsigned int gcd (unsigned int l, unsigned int n=N)
Calculate the greatest common divisor of l and N.
Detailed Description
template<int N>
class vnl_finite_int< N >
finite modulo-N arithmetic.
The templated vnl_finite_int<N> provides arithmetic "modulo N", i.e., arithmetic in the finite (Galois) field GF(N) in case N is a prime or just in the finite ring (or semi-field) of integers modulo N otherwise. In that case division makes no sense (unless no zero divisor is involved), but all other operations remain valid.
Constructor & Destructor Documentation
template<int N> vnl_finite_int< N >::vnl_finite_int (int x = 0) [inline]
Creates a finite int element.
Default constructor gives 0. Also serves as automatic cast from int to vnl_finite_int.
template<int N> vnl_finite_int< N >::vnl_finite_int (Base const & x) [inline]
template<int N> vnl_finite_int< N >::~vnl_finite_int () [inline]
Member Function Documentation
template<int N> unsigned int vnl_finite_int< N >::additive_order () const [inline]
The additive order of x is the smallest nonnegative r such that r*x == 0.
References vnl_finite_int< N >::gcd().
template<int N> static unsigned int vnl_finite_int< N >::cardinality () [inline, static]
The number of different finite_int numbers of this type.
template<int N> static std::vector<unsigned int> vnl_finite_int< N >::decompose () [inline, static]
Write N as the unique product of prime factors.
Referenced by vnl_finite_int< N >::is_field(), and vnl_finite_int< N >::totient().
template<int N> static Base vnl_finite_int< N >::exp (int r) [inline, static]
Return the inverse of log(), i.e., return g^r where g is the smallest generator.
References vnl_finite_int< N >::pow(), and vnl_finite_int< N >::smallest_generator().
Referenced by vnl_finite_int< N >::reciproc().
template<int N> static unsigned int vnl_finite_int< N >::gcd (unsigned int l, unsigned int n = N) [inline, static]
Calculate the greatest common divisor of l and N.
Referenced by vnl_finite_int_poly< N, M >::additive_order(), vnl_finite_int< N >::additive_order(), vnl_finite_int< N >::is_unit(), vnl_finite_int< N >::is_zero_divisor(), and vnl_finite_int< N >::multiplicative_order().
template<int N> static bool vnl_finite_int< N >::is_field () [inline, static]
Return true when N is a prime number, i.e., when this ring is a field.
References vnl_finite_int< N >::decompose().
Referenced by vnl_finite_int_poly< N, M >::is_field(), and vnl_finite_int< N >::smallest_generator().
template<int N> bool vnl_finite_int< N >::is_unit () const [inline]
Return true only when x is a unit in this ring.
In a field, all numbers except 0 are units. The total number of units is given by the Euler totient function.
References vnl_finite_int< N >::gcd().
Referenced by operator/(), vnl_finite_int< N >::operator/=(), and vnl_finite_int< N >::reciproc().
template<int N> bool vnl_finite_int< N >::is_zero_divisor () const [inline]
Return true only when x is a zero divisor, i.e., is not a unit.
References vnl_finite_int< N >::gcd().
Referenced by vnl_finite_int< N >::log().
template<int N> unsigned int vnl_finite_int< N >::log () const [inline]
Return the smallest nonnegative exponent r for which x=g^r, where g is the smallest generator.
References vnl_finite_int< N >::is_zero_divisor(), and vnl_finite_int< N >::smallest_generator().
Referenced by vnl_finite_int< N >::reciproc().
template<int N> unsigned int vnl_finite_int< N >::multiplicative_order () const [inline]
The multiplicative order of x is the smallest r (>0) such that x^r == 1.
References vnl_finite_int< N >::gcd().
Referenced by vnl_finite_int< N >::smallest_generator().
template<int N> vnl_finite_int< N >::operator int () [inline]
template<int N> vnl_finite_int< N >::operator int () const [inline]
template<int N> vnl_finite_int< N >::operator long () [inline]
template<int N> vnl_finite_int< N >::operator long () const [inline]
template<int N> vnl_finite_int< N >::operator short () [inline]
template<int N> vnl_finite_int< N >::operator short () const [inline]
template<int N> bool vnl_finite_int< N >::operator! () const [inline]
Unary not - returns true if finite int number is equal to zero.
template<int N> bool vnl_finite_int< N >::operator!= (int x) const [inline]
References vnl_finite_int< N >::operator==().
template<int N> bool vnl_finite_int< N >::operator!= (Base const & x) const [inline]
template<int N> Base& vnl_finite_int< N >::operator*= (Base const & r) [inline]
Multiply&assign: replace lhs by lhs * rhs.
References vnl_finite_int< N >::operator*=(), vnl_finite_int< N >::operator+=(), and v.
template<int N> Base& vnl_finite_int< N >::operator*= (int r) [inline]
Multiply&assign: replace lhs by lhs * rhs.
References vnl_finite_int< N >::operator+=(), and v.
Referenced by vnl_finite_int< N >::operator*=(), and vnl_finite_int< N >::operator/=().
template<int N> Base vnl_finite_int< N >::operator+ () const [inline]
Unary plus - returns the current number.
template<int N> Base vnl_finite_int< N >::operator++ (int) [inline]
Post-increment (r++).
template<int N> Base& vnl_finite_int< N >::operator++ () [inline]
Pre-increment (++r).
template<int N> Base& vnl_finite_int< N >::operator+= (int r) [inline]
References vnl_finite_int< N >::operator=().
template<int N> Base& vnl_finite_int< N >::operator+= (Base const & r) [inline]
Plus&assign: replace lhs by lhs + rhs.
Referenced by vnl_finite_int< N >::operator*=().
template<int N> Base vnl_finite_int< N >::operator- () const [inline]
Unary minus - returns the additive inverse.
template<int N> Base vnl_finite_int< N >::operator-- (int) [inline]
Post-decrement (r--).
template<int N> Base& vnl_finite_int< N >::operator-- () [inline]
Pre-decrement (--r).
template<int N> Base& vnl_finite_int< N >::operator-= (int r) [inline]
References vnl_finite_int< N >::operator=().
template<int N> Base& vnl_finite_int< N >::operator-= (Base const & r) [inline]
Minus&assign: replace lhs by lhs - rhs.
template<int N> Base& vnl_finite_int< N >::operator/= (Base const & r) [inline]
Divide&assign. Uses r.reciproc() for efficient computation.
References vnl_finite_int< N >::is_unit(), vnl_finite_int< N >::operator*=(), vnl_finite_int< N >::operator=(), and vnl_finite_int< N >::reciproc().
template<int N> Base& vnl_finite_int< N >::operator= (int x) [inline]
template<int N> Base& vnl_finite_int< N >::operator= (Base const & x) [inline]
Assignment.
Referenced by vnl_finite_int< N >::operator+=(), vnl_finite_int< N >::operator-=(), and vnl_finite_int< N >::operator/=().
template<int N> bool vnl_finite_int< N >::operator== (int x) const [inline]
References vnl_finite_int< N >::operator==().
Referenced by vnl_finite_int< N >::operator==().
template<int N> bool vnl_finite_int< N >::operator== (Base const & x) const [inline]
Comparison of finite int numbers.
Note that finite ints have no order, so < and > make no sense.
Referenced by vnl_finite_int< N >::operator!=().
template<int N> Base vnl_finite_int< N >::pow (int r) [inline]
Return the r-th power of this number.
References vnl_finite_int< N >::totient().
Referenced by vnl_finite_int< N >::exp().
template<int N> Base vnl_finite_int< N >::reciproc () const [inline]
Multiplicative inverse.
Uses exp() and log() for efficient computation, unless log() is not defined.
References vnl_finite_int< N >::exp(), vnl_finite_int< N >::is_unit(), vnl_finite_int< N >::log(), vnl_finite_int< N >::smallest_generator(), and vnl_finite_int< N >::totient().
Referenced by operator/(), and vnl_finite_int< N >::operator/=().
template<int N> static Base vnl_finite_int< N >::smallest_generator () [inline, static]
Return the smallest multiplicative generator of the units in this ring.
This is only possible if the units form a cyclic group for multiplication. If not, smallest_generator() returns 1 to indicate this fact. Note that the multiplication group of a finite *field* is always cyclic.
References vnl_finite_int< N >::is_field(), vnl_finite_int< N >::multiplicative_order(), and vnl_finite_int< N >::totient().
Referenced by vnl_finite_int< N >::exp(), vnl_finite_int< N >::log(), and vnl_finite_int< N >::reciproc().
template<int N> static unsigned int vnl_finite_int< N >::totient () [inline, static]
Return the Euler totient function, i.e., the number of units of this ring.
This number also equals the periodicity of the exponent: every unit, when raised to this power, yields 1.
References vnl_finite_int< N >::decompose().
Referenced by vnl_finite_int< N >::pow(), vnl_finite_int< N >::reciproc(), and vnl_finite_int< N >::smallest_generator().
The documentation for this class was generated from the following file:
finite.h