VW: VNL::DiagMatrix< T > Class Template Reference
VNL::DiagMatrix< T > Class Template Reference
stores a diagonal matrix as a single vector.
#include <diagmatrix.h>
Public Types
typedef Vector< T >::iterator iterator
typedef Vector< T >::const_iterator const_iterator
Public Member Functions
DiagMatrix ()
DiagMatrix (unsigned nn)
Construct an empty diagonal matrix.
DiagMatrix (unsigned nn, T const &value)
Construct a diagonal matrix with diagonal elements equal to value.
DiagMatrix (Vector< T > const &that)
Construct a diagonal matrix from a vnl_vector.
~DiagMatrix ()
DiagMatrix & operator= (DiagMatrix< T > const &that)
DiagMatrix< T > & operator*= (T v)
In-place arithmetic operations.
DiagMatrix< T > & operator/= (T v)
In-place arithmetic operations.
void InvertInPlace ()
Invert a DiagMatrix in-situ.
T Determinant () const
Return determinant as product of diagonal values.
Vector< T > Solve (Vector< T > const &b)
Return inv(D) * b.
void Solve (Vector< T > const &b, Vector< T > *out)
Return inv(D) * b.
T operator() (unsigned i, unsigned j) const
T & operator() (unsigned i, unsigned j)
T & operator() (unsigned i)
T const & operator() (unsigned i) const
T & operator[] (unsigned i)
T const & operator[] (unsigned i) const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
unsigned size () const
unsigned Size () const
unsigned Rows () const
unsigned Cols () const
unsigned Columns () const
Matrix< T > AsMatrix () const
Convert a DiagMatrix to a Matrix.
void Resize (int n)
void Clear ()
void Fill (T const &x)
T * DataBlock ()
Return pointer to the diagonal elements as a contiguous 1D C array;.
T const * DataBlock () const
Vector< T > const & Diagonal () const
Return diagonal elements as a vector.
void Set (Vector< T > const &v)
Set diagonal elements using vector.
Protected Attributes
Vector< T > diagonal_
Detailed Description
template<class T>
class VNL::DiagMatrix< T >
stores a diagonal matrix as a single vector.
DiagMatrix stores a diagonal matrix for time and space efficiency. Specifically, only the diagonal elements are stored, and some matrix operations (currently *, + and -) are overloaded to use more efficient algorithms.
Member Typedef Documentation
template<class T> typedef Vector<T>::const_iterator VNL::DiagMatrix< T >::const_iterator
template<class T> typedef Vector<T>::iterator VNL::DiagMatrix< T >::iterator
Constructor & Destructor Documentation
template<class T> VNL::DiagMatrix< T >::DiagMatrix () [inline]
template<class T> VNL::DiagMatrix< T >::DiagMatrix (unsigned nn) [inline]
Construct an empty diagonal matrix.
template<class T> VNL::DiagMatrix< T >::DiagMatrix (unsigned nn, T const & value) [inline]
Construct a diagonal matrix with diagonal elements equal to value.
template<class T> VNL::DiagMatrix< T >::DiagMatrix (Vector< T > const & that) [inline]
Construct a diagonal matrix from a vnl_vector.
The vector elements become the diagonal elements.
template<class T> VNL::DiagMatrix< T >::~DiagMatrix () [inline]
Member Function Documentation
template<class T > VNL::Matrix< T > VNL::DiagMatrix< T >::AsMatrix () const [inline]
Convert a DiagMatrix to a Matrix.
References VNL::DiagMatrix< T >::diagonal_.
template<class T> const_iterator VNL::DiagMatrix< T >::begin () const [inline]
template<class T> iterator VNL::DiagMatrix< T >::begin () [inline]
Referenced by VNL::MatlabPrint().
template<class T> void VNL::DiagMatrix< T >::Clear () [inline]
Referenced by VNL::BinaryLoad().
template<class T> unsigned VNL::DiagMatrix< T >::Cols () const [inline]
template<class T> unsigned VNL::DiagMatrix< T >::Columns () const [inline]
Referenced by VNL::SVD< T >::DeterminantMagnitude(), VNL::SVD< T >::PseudoInverse(), VNL::SVD< T >::Recompose(), and VNL::SVD< T >::TransposeInverse().
template<class T> T const* VNL::DiagMatrix< T >::DataBlock () const [inline]
template<class T> T* VNL::DiagMatrix< T >::DataBlock () [inline]
Return pointer to the diagonal elements as a contiguous 1D C array;.
Referenced by VNL::BinaryLoad(), VNL::BinarySave(), VNL::DiagMatrix< T >::Determinant(), VNL::GeneralizedEigensystem::GeneralizedEigensystem(), VNL::DiagMatrix< T >::InvertInPlace(), VNL::operator*(), VNL::operator+(), and VNL::operator-().
template<class T > T VNL::DiagMatrix< T >::Determinant () const [inline]
Return determinant as product of diagonal values.
References VNL::DiagMatrix< T >::DataBlock(), and VNL::DiagMatrix< T >::diagonal_.
template<class T> Vector<T> const& VNL::DiagMatrix< T >::Diagonal () const [inline]
Return diagonal elements as a vector.
Referenced by VNL::operator*().
template<class T> const_iterator VNL::DiagMatrix< T >::end () const [inline]
template<class T> iterator VNL::DiagMatrix< T >::end () [inline]
template<class T> void VNL::DiagMatrix< T >::Fill (T const & x) [inline]
Referenced by VNL::SVD< T >::PseudoInverse(), VNL::SVD< T >::Recompose(), and VNL::SVD< T >::TransposeInverse().
template<class T > void VNL::DiagMatrix< T >::InvertInPlace () [inline]
Invert a DiagMatrix in-situ.
Just replaces each element with its reciprocal.
References VNL::DiagMatrix< T >::DataBlock(), and VNL::DiagMatrix< T >::diagonal_.
template<class T> T const& VNL::DiagMatrix< T >::operator() (unsigned i) const [inline]
template<class T> T& VNL::DiagMatrix< T >::operator() (unsigned i) [inline]
template<class T> T& VNL::DiagMatrix< T >::operator() (unsigned i, unsigned j) [inline]
template<class T> T VNL::DiagMatrix< T >::operator() (unsigned i, unsigned j) const [inline]
template<class T> DiagMatrix<T>& VNL::DiagMatrix< T >::operator*= (T v) [inline]
In-place arithmetic operations.
template<class T> DiagMatrix<T>& VNL::DiagMatrix< T >::operator/= (T v) [inline]
In-place arithmetic operations.
template<class T> DiagMatrix& VNL::DiagMatrix< T >::operator= (DiagMatrix< T > const & that) [inline]
template<class T> T const& VNL::DiagMatrix< T >::operator[] (unsigned i) const [inline]
template<class T> T& VNL::DiagMatrix< T >::operator[] (unsigned i) [inline]
template<class T> void VNL::DiagMatrix< T >::Resize (int n) [inline]
Referenced by VNL::BinaryLoad().
template<class T> unsigned VNL::DiagMatrix< T >::Rows () const [inline]
Referenced by VNL::SVD< T >::PseudoInverse(), VNL::SVD< T >::Recompose(), VNL::SVD< T >::Singularities(), VNL::SVD< T >::TransposeInverse(), and VNL::SVD< T >::ZeroOutAbsolute().
template<class T> void VNL::DiagMatrix< T >::Set (Vector< T > const & v) [inline]
Set diagonal elements using vector.
template<class T> unsigned VNL::DiagMatrix< T >::Size () const [inline]
template<class T> unsigned VNL::DiagMatrix< T >::size () const [inline]
Referenced by VNL::BinaryLoad(), VNL::BinarySave(), VNL::MatlabPrint(), VNL::operator+(), and VNL::operator-().
template<class T> void VNL::DiagMatrix< T >::Solve (VNL::Vector< T > const & b, VNL::Vector< T > * out) [inline]
Return inv(D) * b.
References VNL::DiagMatrix< T >::diagonal_.
template<class T> VNL::Vector< T > VNL::DiagMatrix< T >::Solve (VNL::Vector< T > const & b) [inline]
Return inv(D) * b.
References VNL::DiagMatrix< T >::diagonal_.
Member Data Documentation
template<class T> Vector<T> VNL::DiagMatrix< T >::diagonal_ [protected]
Referenced by VNL::DiagMatrix< T >::AsMatrix(), VNL::DiagMatrix< std::complex< double > >::begin(), VNL::DiagMatrix< std::complex< double > >::Clear(), VNL::DiagMatrix< std::complex< double > >::Cols(), VNL::DiagMatrix< std::complex< double > >::Columns(), VNL::DiagMatrix< std::complex< double > >::DataBlock(), VNL::DiagMatrix< T >::Determinant(), VNL::DiagMatrix< std::complex< double > >::Diagonal(), VNL::DiagMatrix< std::complex< double > >::end(), VNL::DiagMatrix< std::complex< double > >::Fill(), VNL::DiagMatrix< T >::InvertInPlace(), VNL::DiagMatrix< std::complex< double > >::operator()(), VNL::DiagMatrix< std::complex< double > >::operator*=(), VNL::DiagMatrix< std::complex< double > >::operator/=(), VNL::DiagMatrix< std::complex< double > >::operator=(), VNL::DiagMatrix< std::complex< double > >::operator[](), VNL::DiagMatrix< std::complex< double > >::Resize(), VNL::DiagMatrix< std::complex< double > >::Rows(), VNL::DiagMatrix< std::complex< double > >::Set(), VNL::DiagMatrix< std::complex< double > >::Size(), VNL::DiagMatrix< std::complex< double > >::size(), and VNL::DiagMatrix< T >::Solve().
The documentation for this class was generated from the following files:
diagmatrix.h
diagmatrix.tpp