VW: VW::ImageYUV< Type > Class Template Reference
VW::ImageYUV< Type > Class Template Reference
[Image]
A class for storing YUV (YCrCb?) images.
#include <imageyuv.h>
Public Types
typedef Type DataType
typedef PixelYUV< Type > PixelType
typedef PixelType * PixelPtr
Public Member Functions
ImageYUV (const std::string &filename)
Construct and read a file.
ImageYUV (const int w, const int h)
ImageYUV ()
~ImageYUV ()
PixelYUV< double > GetInterpolatedPixel (double x, double y) const
Get a linearly interpolated pixel value.
bool ReadImage (const std::string &filename)
bool WriteImage (const std::string &filename) const
template<>
void GetFormatStrings (std::string &format, std::string &type) const
Return strings describing the format of image data.
template<>
void GetFormatStrings (std::string &format, std::string &type) const
Return strings describing the format of image data.
template<>
void GetFormatStrings (std::string &format, std::string &type) const
Return strings describing the format of image data.
template<>
void GetFormatStrings (std::string &format, std::string &type) const
Return strings describing the format of image data.
template<>
void GetFormatStrings (std::string &format, std::string &type) const
Return strings describing the format of image data.
void AllocImageData (const unsigned int w, const unsigned int h)
void SetImageData (PixelYUV< Type > *data, const unsigned int w, const unsigned int h)
void FreeImageData ()
bool IsAlloced () const
void GetSize (unsigned int &w, unsigned int &h) const
unsigned int GetWidth (void) const
unsigned int GetHeight (void) const
void SetROI (const VW::ROI &new_roi)
VW::ROI & ROI ()
const VW::ROI & ROI () const
void ResetROI ()
Set the ROI to be the whole image.
PixelYUV< Type > * GetImageBuffer (void) const
void * GetRawBuffer (void) const
PixelYUV< Type > GetPixel (const int c, const int r) const
void SetPixel (const int c, const int r, const PixelYUV< Type > &new_value)
PixelYUV< Type > * GetRowStart (int r) const
PixelYUV< Type > ** GetRowPointer (int r) const
PixelYUV< Type > * operator[] (int r) const
PixelYUV< Type > * GetROIRowStart (int r) const
void Clear (const PixelYUV< Type > &new_value=PixelYUV< Type >())
Set the whole image to a particular value.
void FlipHorizontal ()
void FlipVertical ()
void ExchangeData (ImageBase< PixelYUV< Type >, PixelYUV< Type > * > &other)
Swap this image's data for other image data - size, ROI etc are also exchanged.
bool ReadBinary (std::istream &stream)
bool WriteBinary (std::ostream &stream) const
PixelYUV< Type > operator() (int r) const
PixelYUV< Type > operator() (int r, int c)
void SetPenColour (const PixelYUV< Type > &colour)
For drawing, the image has a pen colour much like a display.
PixelYUV< Type > GetPenColour () const
Return the current pen colour.
void DrawLine (const double x0, const double y0, const double x1, const double y1)
Public Attributes
PixelYUV< Type > ** pixel
Pointers to the start of each row.
Protected Member Functions
void GetFormatStrings (std::string &format, std::string &type) const
Return strings describing the format of image data.
void _CreateRowPointers ()
Protected Attributes
unsigned int _width
unsigned int _height
VW::ROI _roi
PixelYUV< Type > * _data
bool _dataalloced
bool _rowsalloced
PixelYUV< Type > _pen_colour
Detailed Description
template<class Type>
class VW::ImageYUV< Type >
A class for storing YUV (YCrCb?) images.
Author:
ID Reid, BJ Tordoff
Date:
02/08/02 This image class stores the image in a row-major format (ie. like a standard C/C++ array), with pixels as YUVA where A is a spare (alpha?) channel. This way pixels stored using 8-bit integers (ie. unsigned chars, as are produced by many cameras, and used on most displays) are aligned on 4-byte memory locations, adding a tad to performance. Strictly speaking this (and the related conversions) are really Y Cr Cb rather than YUV, but looking around the 'net the terminology seems to be interchangeable.
Member Typedef Documentation
template<class Type> typedef Type VW::ImageYUV< Type >::DataType
template<class Type> typedef PixelType* VW::ImageYUV< Type >::PixelPtr
template<class Type> typedef PixelYUV<Type> VW::ImageYUV< Type >::PixelType
Constructor & Destructor Documentation
template<class Type > VW::ImageYUV< Type >::ImageYUV (const std::string & filename) [inline]
Construct and read a file.
References VW::ImageYUV< Type >::ReadImage().
template<class Type > VW::ImageYUV< Type >::ImageYUV (const int w, const int h) [inline]
template<class Type> VW::ImageYUV< Type >::ImageYUV () [inline]
template<class Type> VW::ImageYUV< Type >::~ImageYUV () [inline]
Member Function Documentation
void VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::_CreateRowPointers () [protected, inherited]
void VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::AllocImageData (const unsigned int w, const unsigned int h) [inherited]
Allocate the image data array.
Parameters:
w the width of array (number of columns) to allocate
h the height of array (number of rows) to allocate
Referenced by VW::PyramidYUV< StorageType >::_AverageAndSubsampleBy2(), VW::HistogramEqualisation::ApplyToImage(), VW::RadialDistortion::DistortImage(), and VW::ReadJPEGImage().
void VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::Clear (const PixelYUV< Type > & new_value = PixelType()) [inherited]
Set the whole image to a particular value.
Fill the entire image with a pixel value.
void VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::DrawLine (const double x0, const double y0, const double x1, const double y1) [inherited]
void VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::ExchangeData (ImageBase< PixelYUV< Type > , PixelYUV< Type > * > & other) [inherited]
Swap this image's data for other image data - size, ROI etc are also exchanged.
This is handy to avoid an image copy when doing things like:
void MyFunc(ImageXXX& im) { VW::ImageXXX result; DoSomeProcessing(im,result); im.ExchangeData(result); }
which would otherwise require a copy of the result data back to the original.
void VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::FlipHorizontal () [inherited]
Flip the image horizontally (size preserved).
void VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::FlipVertical () [inherited]
Flip the image vertically (size preserved).
void VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::FreeImageData () [inherited]
De-allocate the image data array.
Once freed, storage space will be reallocated automatically when an image is read from a file or stream, or must otherwise by created using the AllocImageData() function.
Referenced by VW::HistogramEqualisation::ApplyToImage().
template<> void VW::ImageYUV< double >::GetFormatStrings (std::string & format, std::string & type) const [inline, virtual]
Return strings describing the format of image data.
This must be overloaded on a per-type basis.
Implements VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >.
template<> void VW::ImageYUV< float >::GetFormatStrings (std::string & format, std::string & type) const [inline, virtual]
Return strings describing the format of image data.
This must be overloaded on a per-type basis.
Implements VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >.
template<> void VW::ImageYUV< int >::GetFormatStrings (std::string & format, std::string & type) const [inline, virtual]
Return strings describing the format of image data.
This must be overloaded on a per-type basis.
Implements VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >.
template<> void VW::ImageYUV< char >::GetFormatStrings (std::string & format, std::string & type) const [inline, virtual]
Return strings describing the format of image data.
This must be overloaded on a per-type basis.
Implements VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >.
template<> void VW::ImageYUV< unsigned char >::GetFormatStrings (std::string & format, std::string & type) const [inline, virtual]
Return strings describing the format of image data.
This must be overloaded on a per-type basis.
Implements VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >.
template<class Type> void VW::ImageYUV< Type >::GetFormatStrings (std::string & format, std::string & type) const [protected, virtual]
Return strings describing the format of image data.
This must be overloaded on a per-type basis.
Implements VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >.
unsigned int VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::GetHeight (void) const [inherited]
Determine the height of the image in pixels.
Returns:
the height (number of rows) of the image
Referenced by VW::PyramidYUV< StorageType >::_AverageAndSubsampleBy2(), VW::HistogramEqualisation::AddImage(), VW::HistogramEqualisation::ApplyToImage(), VW::ClassifierUV::Classify(), VW::ClassifierUV::ClassifyAndColour(), VW::PyramidYUV< StorageType >::Compute(), VW::PlesseyOld::Compute(), VW::IntegralImageSquared< DataType >::Compute(), VW::IntegralImage< DataType >::Compute(), VW::Convolve< maskType >::Compute(), VW::Canny::Compute(), VW::RadialDistortion::DistortImage(), VW::DrawFunctions::Draw(), VW::ClassifierUV::GetProbImage(), VW::ReadJPEGImage(), VW::ImageConversions::VWImage_to_RGBABuffer(), VW::ImageConversions::VWImage_to_RGBBuffer(), VW::WriteJPEGImage(), VW::ImageConversions::YUV411Buffer_to_VWImage(), and VW::ImageConversions::YUV422Buffer_to_VWImage().
PixelYUV< Type > * VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::GetImageBuffer (void) const [inherited]
Get a pointer to the first pixel in the data array.
The array is stored in row-major form, and can be traversed using pointer arithmatic, eg: const unsigned int num_pix = im.GetWidth() * im.GetHeight(); PixelType* p = im.GetImageBuffer(); for (unsigned int i=0; i<num_pix; i++,p++) { p->ScaleIntensity(0.5); }
template<class T > VW::PixelYUV< double > VW::ImageYUV< T >::GetInterpolatedPixel (double x, double y) const [inline]
Get a linearly interpolated pixel value.
References mp, VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::pixel, VW::PixelYUV< Type >::u, VW::PixelYUV< Type >::v, and VW::PixelYUV< Type >::y.
PixelYUV< Type > VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::GetPenColour () const [inherited]
Return the current pen colour.
PixelYUV< Type > VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::GetPixel (const int c, const int r) const [inherited]
Recover (copy) the pixel at column c, row r.
If VW is compiled in debug mode, this function is range-checked.
Parameters:
c the column index (0<c<width)
r the row index (0<r<height)
Returns:
a copy of the pixel (so changes to this pixel will not affect the underlying image)
Referenced by VW::RadialDistortion::DistortImage(), VW::GetImagePatch(), and VW::GetInterpolatedImagePatch().
void* VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::GetRawBuffer (void) const [inherited]
Get a pointer to the first memory location used in the data array.
As this returns a void*, you can cast it to any type you like, with the usual pitfalls that this entails if the pointer type doesn't match the type of the data stored.
Referenced by VW::ImageConversions::BGRABuffer_to_VWImage(), VW::ClassifierUV::Classify(), VW::ClassifierUV::ClassifyAndColour(), VW::ClassifierUV::GetProbImage(), VW::ImageConversions::MonoBuffer_to_VWImage(), VW::ImageConversions::RGBBuffer_to_VWImage(), VW::ImageConversions::VWImage_to_RGBABuffer(), VW::ImageConversions::VWImage_to_RGBBuffer(), VW::ImageConversions::YUV411Buffer_to_VWImage(), VW::ImageConversions::YUV422Buffer_to_VWImage(), and VW::ImageConversions::YUV444Buffer_to_VWImage().
PixelYUV< Type > * VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::GetROIRowStart (int r) const [inherited]
Referenced by VW::PyramidYUV< StorageType >::_AverageAndSubsampleBy2().
PixelYUV< Type > * * VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::GetRowPointer (int r) const [inherited]
Referenced by VW::Convolve< maskType >::Compute().
PixelYUV< Type > * VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::GetRowStart (int r) const [inherited]
Referenced by VW::HistogramEqualisation::AddImage(), VW::HistogramEqualisation::ApplyToImage(), VW::IntegralImageSquared< DataType >::Compute(), VW::IntegralImage< DataType >::Compute(), VW::Correlate::Compute(), VW::Convolve< maskType >::Compute(), VW::Canny::Compute(), VW::RadialDistortion::DistortImage(), VW::DrawFunctions::Draw(), VW::ReadJPEGImage(), and VW::WriteJPEGImage().
void VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::GetSize (unsigned int & w, unsigned int & h) const [inherited]
Get width and height in a single command.
Parameters:
w will be set to the width (number of columns)
h will be set to the height (number of rows)
unsigned int VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::GetWidth (void) const [inherited]
Determine the width of the image in pixels.
Returns:
the width (number of columns) of the image
Referenced by VW::PyramidYUV< StorageType >::_AverageAndSubsampleBy2(), VW::HistogramEqualisation::AddImage(), VW::HistogramEqualisation::ApplyToImage(), VW::ClassifierUV::Classify(), VW::ClassifierUV::ClassifyAndColour(), VW::PyramidYUV< StorageType >::Compute(), VW::PlesseyOld::Compute(), VW::IntegralImageSquared< DataType >::Compute(), VW::IntegralImage< DataType >::Compute(), VW::Correlate::Compute(), VW::Convolve< maskType >::Compute(), VW::Canny::Compute(), VW::RadialDistortion::DistortImage(), VW::DrawFunctions::Draw(), VW::ClassifierUV::GetProbImage(), VW::ReadJPEGImage(), VW::ImageConversions::VWImage_to_RGBABuffer(), VW::ImageConversions::VWImage_to_RGBBuffer(), VW::WriteJPEGImage(), VW::ImageConversions::YUV411Buffer_to_VWImage(), and VW::ImageConversions::YUV422Buffer_to_VWImage().
bool VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::IsAlloced (void) const [inherited]
Is the image data array allocated?
Returns:
true if data array exists
Referenced by VW::PyramidYUV< StorageType >::_AverageAndSubsampleBy2(), VW::HistogramEqualisation::ApplyToImage(), VW::RadialDistortion::DistortImage(), and VW::ReadJPEGImage().
PixelYUV< Type > VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::operator() (int r, int c) [inherited]
Recover a pixel (note y,x NOT x,y).
This function is not range-checked.
Parameters:
r the row number (y coord) of the pixel
c the column number (x coord) of the pixel
Returns:
the pixel value at this position
PixelYUV< Type > VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::operator() (int r) const [inherited]
Get the pixel at the start of row r.
This function is not range checked.
Parameters:
r the row number (y coord) of the pixel
Returns:
the pixel value at the start of this row
PixelYUV< Type > * VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::operator[] (int r) const [inherited]
bool VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::ReadBinary (std::istream & stream) [inherited]
Read the image from a stream in the internal VW format.
This format is strongly related to the raw PPM format, but keeps the byte ordering and alpha values of the image class used. The image format and data type are written in plain text before the data, stored as binary.
Parameters:
stream the input stream into which the image data will be written
template<class Type> bool VW::ImageYUV< Type >::ReadImage (const std::string & filename)
Reimplemented from VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >.
Referenced by VW::ImageYUV< Type >::ImageYUV().
void VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::ResetROI () [inherited]
Set the ROI to be the whole image.
Reset the region of interest to be the whole image.
const VW::ROI& VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::ROI () const [inherited]
Constant reference to the region of interest (ROI) of the image.
Returns:
the current region of interest in the image.
VW::ROI& VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::ROI () [inherited]
Copy of the region of interest (ROI) of the image.
Returns:
the current region of interest in the image. Reference to the region of interest (ROI) of the image.
the current region of interest in the image.
Referenced by VW::PyramidYUV< StorageType >::_AverageAndSubsampleBy2(), VW::IntegralImageSquared< DataType >::Compute(), VW::IntegralImage< DataType >::Compute(), VW::Correlate::Compute(), VW::Convolve< maskType >::Compute(), VW::GetPlesseyCorner::GetPlesseyCorner(), and VW::GetPlesseyCornerYUV::GetPlesseyCornerYUV().
void VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::SetImageData (PixelYUV< Type > * data, const unsigned int w, const unsigned int h) [inherited]
Allocate the image data array using some existing data.
Parameters:
data the memory location of the existing data array
w the width of array (number of columns) to allocate
h the height of array (number of rows) to allocate
void VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::SetPenColour (const PixelYUV< Type > & colour) [inherited]
For drawing, the image has a pen colour much like a display.
void VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::SetPixel (const int c, const int r, const PixelYUV< Type > & new_value) [inherited]
Set the pixel at column c, row r.
If VW is compiled in debug mode, this function is range-checked.
Parameters:
c the column index (0<c<width)
r the row index (0<r<height)
new_value the new data for this pixel
void VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::SetROI (const VW::ROI & new_roi) [inherited]
Set the region of interest (ROI) of the image.
Parameters:
new_roi the new region of interest to use.
bool VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::WriteBinary (std::ostream & stream) const [inherited]
Write the image to a stream in the internal VW format.
This format is strongly related to the raw PPM format, but keeps the byte ordering and alpha values of the image class used. The image format and data type are written in plain text before the data, stored as binary.
template<class Type> bool VW::ImageYUV< Type >::WriteImage (const std::string & filename) const
Reimplemented from VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >.
Member Data Documentation
PixelYUV< Type > * VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::_data [protected, inherited]
bool VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::_dataalloced [protected, inherited]
unsigned int VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::_height [protected, inherited]
PixelYUV< Type > VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::_pen_colour [protected, inherited]
VW::ROI VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::_roi [protected, inherited]
bool VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::_rowsalloced [protected, inherited]
unsigned int VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::_width [protected, inherited]
PixelYUV< Type > * * VW::ImageBase< PixelYUV< Type > , PixelYUV< Type > * >::pixel [inherited]
Pointers to the start of each row.
A pointer to the start of the row r is given by image.pixel[r], and a pixel at row r, column c, by image.pixel[r][c]. This is functionally identical to saying image[r][c], but in some circumstances may be faster.
Referenced by VW::ImageYUV< Type >::GetInterpolatedPixel().
The documentation for this class was generated from the following files:
imageyuv.h
imageyuv.cpp