VW: VW::SequencerFirewire Class Reference
VW::SequencerFirewire Class Reference
[Sequencers]
Retrieve a sequence of image from one or more firewire cameras.
#include <sequencerfirewire.h>
Public Member Functions
SequencerFirewire (unsigned int x_reduction=1, unsigned int y_reduction=1)
virtual ~SequencerFirewire ()
virtual bool Init ()
Initialise the grabber.
virtual void Stop ()
Stop continuous capture from the sequence (overloaded from base).
int GetNumberOfCameras (void) const
The total number of cameras attached to the Firewire BUS.
virtual VW::FirewireCamera * GetCamera (unsigned int which_camera)
Returns a pointer to one camera.
void * GetBuffer (unsigned int which_channel=0)
Get a pointer to the raw buffer.
template<class ImType >
void CopyImage (ImType &image, unsigned int which_channel=0)
Recover the image for one camera.
Sequence control functions
virtual void Continuous ()
Start continuous capture from the sequence.
virtual void Next ()
Capture the next single frame.
Initialisation functions
virtual void SetDelay (int d)
Set the delay between frames (only usually used for non-hardware sequencers).
Information functions
bool GetContinuous () const
Is the sequencer running in continuous mode?
int GetDelay () const
What is the delay between frames.
unsigned int GetNumberOfChannels () const
Most sequencers are able to present mutliple images per frame.
unsigned int GetCurrentFrameNumber () const
Return the current frame number.
Public Attributes
VWEvents::Event1< void, int > NewFrameEvent
The "new frame has arrived" event.
Protected Member Functions
virtual bool _Step ()
virtual void AddNewCamera (std::vector< VW::FirewireCamera * > &c_list, unsigned int which_element)
void SetDefaultCameraSettings (void)
void ProbeForCameras ()
bool StartDMA ()
Setup the DMA transfer in each camera.
bool StopDMA ()
Stop the cameras running - ie.
bool StartISO ()
Start isochronous image transfer.
bool StopISO ()
Stop isochronous image transfer.
void _WaitForThread ()
Wait for the thread to exit.
virtual void _FrameArrived ()
we have been signalled that a frame has arrived and we are now "inside" the signalling object, so invoke the appropriate callback
void * Main (void *)
void _CheckInitialised ()
Protected Attributes
bool cameras_running
bool dma_running
int frame_num
unsigned int x_subsamp
unsigned int y_subsamp
pthread_mutex_t buffer_access_lock
int delay
unsigned int frame_number
bool cont
bool thread_running
bool _initialised
ThreadType parent
unsigned int number_of_channels
Mutex access_lock
bool user_finished
Static Protected Attributes
static raw1394handle_t raw_device_handle
static std::vector
< VW::FirewireCamera * > camera_list
static dc1394_cameracapture * camera_capture_stuff
Detailed Description
Retrieve a sequence of image from one or more firewire cameras.
A sequencer for handling firewire digital cameras (not DV!).
This class implements the sequencer API for firewire cameras, providing easy access to continuous or single-stepped image sequences. The camera DMA is started when either 'Continuous' or 'Next' is first called and is only stopped on object destruction (largely due to the fact it seg-faults when the DMA is stopped). Conversely the grabbing thread is stopped when 'Stop' is called, so there should be no CPU overhead to leaving DMA running.
Author:
ID Reid, BJ Tordoff
Date:
02/08/2002 The firewire sequencer uses the FirewireCamera class to provide a sequencer-style interface to any digital cameras connected. Each connected camera is given a channel, and at present it is assumed that you want to use them all (ie. there is no facility for starting and stopping particular cameras).
Constructor & Destructor Documentation
VW::SequencerFirewire::SequencerFirewire (unsigned int x_reduction = 1, unsigned int y_reduction = 1)
References VW::SequencerBase::number_of_channels.
SequencerFirewire::~SequencerFirewire () [virtual]
References Stop(), StopDMA(), and StopISO().
Member Function Documentation
void VW::SequencerBase::_CheckInitialised () [protected, inherited]
References VW::SequencerBase::_initialised.
Referenced by VW::SequencerBase::Continuous(), VW::SequencerBase::Next(), and VW::SequencerBase::Stop().
void SequencerBase::_FrameArrived () [protected, virtual, inherited]
we have been signalled that a frame has arrived and we are now "inside" the signalling object, so invoke the appropriate callback
Reimplemented in VW::SequencerFileGTK, VW::SequencerFirewireGTK, VW::SequencerFileWx, VW::SequencerFirewireWx, and VW::SequencerMeteor.
References VW::SequencerBase::NewFrameEvent, VW::SequencerBase::user_finished, and VERBOSE.
Referenced by VW::SequencerBase::Main(), and VW::SequencerBase::Next().
bool SequencerFirewire::_Step () [protected, virtual]
Implements VW::SequencerBase.
References buffer_access_lock, camera_capture_stuff, cameras_running, VW::SequencerBase::cont, frame_num, VW::SequencerBase::number_of_channels, StartISO(), StopISO(), VW::SequencerBase::thread_running, and VERBOSE.
void SequencerBase::_WaitForThread () [inline, protected, inherited]
Wait for the thread to exit.
References VW::SequencerBase::access_lock, VW::Mutex::Lock(), msleep(), VW::SequencerBase::thread_running, VW::Mutex::Unlock(), and VERBOSE.
Referenced by VW::SequencerBase::Stop().
void VW::SequencerFirewire::AddNewCamera (std::vector< VW::FirewireCamera * > & c_list, unsigned int which_element) [protected, virtual]
Reimplemented in VW::SequencerFirewireGTK, and VW::SequencerFirewireWx.
References VERBOSE.
Referenced by ProbeForCameras().
void SequencerBase::Continuous () [virtual, inherited]
Start continuous capture from the sequence.
Reimplemented in VW::SequencerFileGTK, VW::SequencerFirewireGTK, VW::SequencerMovieGTK, VW::SequencerFileWx, VW::SequencerFirewireWx, and VW::SequencerMeteor.
References VW::SequencerBase::_CheckInitialised(), VW::SequencerBase::access_lock, VW::SequencerBase::cont, VW::Mutex::Lock(), VW::Thread::Start(), and VW::Mutex::Unlock().
Referenced by VW::SequencerFirewireGlute::_ContClicked(), VW::SequencerFileGlute::_ContClicked(), VW::SequencerFirewireGlow::OnMessage(), and VW::SequencerFileGlow::OnMessage().
template<class ImType > void VW::SequencerFirewire::CopyImage (ImType & image, unsigned int which_channel = 0) [inline]
Recover the image for one camera.
The image is copied from the raw image buffer into the VW image, employing some conversion on the way. This is not a fast thing to do. For absolute speed use the raw buffer.
References buffer_access_lock, camera_capture_stuff, camera_list, VW::FirewireParams::M_1024x768_MONO, VW::FirewireParams::M_1024x768_RGB, VW::FirewireParams::M_1024x768_YUV422, VW::FirewireParams::M_1280x960_MONO, VW::FirewireParams::M_1280x960_RGB, VW::FirewireParams::M_1280x960_YUV422, VW::FirewireParams::M_1600x1200_MONO, VW::FirewireParams::M_1600x1200_RGB, VW::FirewireParams::M_1600x1200_YUV422, VW::FirewireParams::M_160x120_YUV444, VW::FirewireParams::M_320x240_YUV422, VW::FirewireParams::M_640x480_MONO, VW::FirewireParams::M_640x480_RGB, VW::FirewireParams::M_640x480_YUV411, VW::FirewireParams::M_640x480_YUV422, VW::FirewireParams::M_800x600_MONO, VW::FirewireParams::M_800x600_RGB, VW::FirewireParams::M_800x600_YUV422, VW::ImageConversions::MonoBuffer_to_VWImage(), VW::ImageConversions::RGBBuffer_to_VWImage(), VERBOSE, x_subsamp, y_subsamp, VW::ImageConversions::YUV411Buffer_to_VWImage(), VW::ImageConversions::YUV422Buffer_to_VWImage(), and VW::ImageConversions::YUV444Buffer_to_VWImage().
void * VW::SequencerFirewire::GetBuffer (unsigned int which_channel = 0) [inline, virtual]
Get a pointer to the raw buffer.
A raw pointer is returned, so it is up to the user to deal with it before the firewire DMA chooses to overwrite it. Wrapping an image around the bizarre format YUV images that the firewire cameras use will almost certainly be tricky. Note that the data is usually unsigned char
Implements VW::SequencerBase.
References camera_capture_stuff.
VW::FirewireCamera * VW::SequencerFirewire::GetCamera (unsigned int which_camera) [inline, virtual]
Returns a pointer to one camera.
References camera_list, and VW::SequencerBase::number_of_channels.
bool VW::SequencerBase::GetContinuous () const [inline, inherited]
Is the sequencer running in continuous mode?
References VW::SequencerBase::cont.
unsigned int VW::SequencerBase::GetCurrentFrameNumber () const [inline, inherited]
Return the current frame number.
In the case of movies or files this is the frame number with respect to the start frame (ie, 1=start frame) and won't correspond to the sequence frame numbers if started part way through a sequence.
References VW::SequencerBase::frame_number.
int VW::SequencerBase::GetDelay () const [inline, inherited]
What is the delay between frames.
References VW::SequencerBase::delay.
int VW::SequencerFirewire::GetNumberOfCameras (void) const [inline]
The total number of cameras attached to the Firewire BUS.
References VW::SequencerBase::number_of_channels.
unsigned int VW::SequencerBase::GetNumberOfChannels () const [inline, inherited]
Most sequencers are able to present mutliple images per frame.
References VW::SequencerBase::number_of_channels.
Referenced by VW::SequencerMovieGTKWidget::InitForm(), and VW::SequencerFileGTKWidget::InitForm().
bool VW::SequencerFirewire::Init () [virtual]
Initialise the grabber.
This tells the grabber to scan for cameras and initialise them. It must be called before trying to use the sequencer.
Reimplemented from VW::SequencerBase.
Reimplemented in VW::SequencerFirewireGTK, and VW::SequencerFirewireWx.
References ProbeForCameras(), SetDefaultCameraSettings(), and VERBOSE.
void * SequencerBase::Main (void *) [protected, virtual, inherited]
Implements VW::Thread.
References VW::SequencerBase::_FrameArrived(), VW::SequencerBase::_Step(), VW::SequencerBase::access_lock, VW::SequencerBase::cont, VW::SequencerBase::delay, VW::SequencerBase::frame_number, VW::Mutex::Lock(), msleep(), VW::SequencerBase::thread_running, VW::Mutex::Unlock(), and VERBOSE.
void SequencerBase::Next () [virtual, inherited]
Capture the next single frame.
Reimplemented in VW::SequencerFileGTK, VW::SequencerFirewireGTK, VW::SequencerMovieGTK, VW::SequencerFileWx, VW::SequencerFirewireWx, and VW::SequencerMeteor.
References VW::SequencerBase::_CheckInitialised(), VW::SequencerBase::_FrameArrived(), VW::SequencerBase::_Step(), VW::SequencerBase::access_lock, VW::SequencerBase::cont, VW::Mutex::Lock(), VW::SequencerBase::Stop(), and VW::Mutex::Unlock().
Referenced by VW::SequencerFirewireGlute::_NextClicked(), VW::SequencerFileGlute::_NextClicked(), VW::SequencerFirewireGlow::OnMessage(), and VW::SequencerFileGlow::OnMessage().
void VW::SequencerFirewire::ProbeForCameras () [protected]
References AddNewCamera(), camera_capture_stuff, camera_list, VW::SequencerBase::number_of_channels, raw_device_handle, and VERBOSE.
Referenced by VW::SequencerFirewireGTK::Init(), and Init().
void VW::SequencerFirewire::SetDefaultCameraSettings (void) [protected]
References camera_list, VW::FirewireParams::FPS_15, VW::FirewireParams::M_320x240_YUV422, and VW::SequencerBase::number_of_channels.
Referenced by VW::SequencerFirewireGTK::Init(), and Init().
void VW::SequencerBase::SetDelay (int d) [inline, virtual, inherited]
Set the delay between frames (only usually used for non-hardware sequencers).
This is the time (in milliseconds) for which the sequencer sleeps between frames: the total frame period will be this plus the time taken to acquire the new frame. By default the delay is set to 1ms (zero or less is not a valid setting).
References VW::SequencerBase::delay.
bool VW::SequencerFirewire::StartDMA (void) [protected]
Setup the DMA transfer in each camera.
Note that this doesn't start transferring images, just creates the channel.
References buffer_access_lock, camera_capture_stuff, camera_list, dma_running, VW::SequencerBase::number_of_channels, and VERBOSE.
Referenced by StartISO().
bool VW::SequencerFirewire::StartISO (void) [protected]
Start isochronous image transfer.
This begins the actual transfer of images from camera to memory.
References camera_list, cameras_running, dma_running, VW::SequencerBase::number_of_channels, and StartDMA().
Referenced by _Step().
virtual void VW::SequencerFirewire::Stop () [inline, virtual]
Stop continuous capture from the sequence (overloaded from base).
Reimplemented from VW::SequencerBase.
Reimplemented in VW::SequencerFirewireGTK, and VW::SequencerFirewireWx.
References StopISO().
Referenced by VW::SequencerFirewireGlute::_StopClicked(), VW::SequencerFirewireGlow::OnMessage(), and ~SequencerFirewire().
bool VW::SequencerFirewire::StopDMA (void) [protected]
Stop the cameras running - ie.
stop DMA. At the moment this seems to be a fatal thing to do (ie. don't expect to be able to restart tham having called this function). However, to stop the cameras carrying on after your program has finished, call it.
References camera_capture_stuff, camera_list, dma_running, VW::SequencerBase::number_of_channels, and VERBOSE.
Referenced by StopISO(), ~SequencerFirewire(), VW::SequencerFirewireGTK::~SequencerFirewireGTK(), and VW::SequencerFirewireWx::~SequencerFirewireWx().
bool VW::SequencerFirewire::StopISO (void) [protected]
Stop isochronous image transfer.
This halts image transfer, and appears a safe thing to do.
References camera_list, cameras_running, VW::SequencerBase::number_of_channels, StopDMA(), and VERBOSE.
Referenced by _Step(), Stop(), ~SequencerFirewire(), VW::SequencerFirewireGTK::~SequencerFirewireGTK(), and VW::SequencerFirewireWx::~SequencerFirewireWx().
Member Data Documentation
bool VW::SequencerBase::_initialised [protected, inherited]
Referenced by VW::SequencerBase::_CheckInitialised(), and VW::SequencerBase::Init().
Mutex VW::SequencerBase::access_lock [protected, inherited]
Referenced by VW::SequencerFile::_Step(), VW::SequencerBase::_WaitForThread(), VW::SequencerBase::Continuous(), VW::SequencerBase::Main(), VW::SequencerBase::Next(), VW::SequencerFile::Rewind(), VW::SequencerFile::Skip(), and VW::SequencerBase::Stop().
pthread_mutex_t VW::SequencerFirewire::buffer_access_lock [protected]
Referenced by _Step(), CopyImage(), and StartDMA().
dc1394_cameracapture * VW::SequencerFirewire::camera_capture_stuff [static, protected]
Referenced by _Step(), CopyImage(), GetBuffer(), ProbeForCameras(), StartDMA(), and StopDMA().
vector< VW::FirewireCamera * > VW::SequencerFirewire::camera_list [static, protected]
Referenced by CopyImage(), GetCamera(), VW::SequencerFirewireGTK::Init(), ProbeForCameras(), SetDefaultCameraSettings(), StartDMA(), StartISO(), StopDMA(), and StopISO().
bool VW::SequencerFirewire::cameras_running [protected]
Referenced by _Step(), StartISO(), and StopISO().
bool VW::SequencerBase::cont [protected, inherited]
Referenced by VW::SequencerMovie::_Step(), _Step(), VW::SequencerFile::_Step(), VW::SequencerBase::Continuous(), VW::SequencerBase::GetContinuous(), VW::SequencerBase::Main(), VW::SequencerBase::Next(), VW::SequencerBase::Stop(), VW::SequencerMovieGTK::UpdateForm(), VW::SequencerFirewireWx::UpdateForm(), VW::SequencerFileWx::UpdateForm(), and VW::SequencerFileGTK::UpdateForm().
int VW::SequencerBase::delay [protected, inherited]
Referenced by VW::SequencerBase::GetDelay(), VW::SequencerBase::Main(), and VW::SequencerBase::SetDelay().
bool VW::SequencerFirewire::dma_running [protected]
Referenced by StartDMA(), StartISO(), and StopDMA().
int VW::SequencerFirewire::frame_num [protected]
Referenced by _Step().
unsigned int VW::SequencerBase::frame_number [protected, inherited]
Referenced by VW::SequencerFile::_InitialiseFiles(), VW::SequencerMovie::_Step(), VW::SequencerFile::_Step(), VW::SequencerBase::GetCurrentFrameNumber(), VW::SequencerBase::Main(), VW::SequencerMovie::Rewind(), VW::SequencerFile::Rewind(), VW::SequencerFile::SequencerFile(), VW::SequencerFile::Skip(), VW::SequencerFileWx::UpdateForm(), and VW::SequencerFileGTK::UpdateForm().
VWEvents::Event1<void,int> VW::SequencerBase::NewFrameEvent [inherited]
The "new frame has arrived" event.
Attach a function to this callback signal if you want to perform an operation each time a new image arrives. This is typically done using my_sequencer.NewFrameEvent.connect(&MyFunction); where 'MyFunction' must take an integer argument and return void.
Referenced by VW::SequencerMeteor::_FrameArrived(), VW::SequencerFirewireWx::_FrameArrived(), VW::SequencerFirewireGTK::_FrameArrived(), VW::SequencerFileWx::_FrameArrived(), VW::SequencerFileGTK::_FrameArrived(), and VW::SequencerBase::_FrameArrived().
unsigned int VW::SequencerBase::number_of_channels [protected, inherited]
Referenced by VW::SequencerFile::_InitialiseFiles(), VW::SequencerMovie::_Step(), _Step(), VW::SequencerFile::_Step(), VW::SequencerFile::CopyImage(), GetCamera(), GetNumberOfCameras(), VW::SequencerBase::GetNumberOfChannels(), VW::SequencerMeteor::Init(), ProbeForCameras(), VW::SequencerMovie::Rewind(), VW::SequencerFile::Rewind(), VW::SequencerFile::SequencerFile(), SequencerFirewire(), VW::SequencerMovie::SequencerMovie(), SetDefaultCameraSettings(), VW::SequencerFile::Skip(), StartDMA(), StartISO(), StopDMA(), StopISO(), VW::SequencerMovieGTK::UpdateForm(), VW::SequencerFileWx::UpdateForm(), VW::SequencerFileGTK::UpdateForm(), VW::SequencerMovieGTK::UpdateFromForm(), and VW::SequencerFileGTK::UpdateFromForm().
ThreadType VW::SequencerBase::parent [protected, inherited]
raw1394handle_t VW::SequencerFirewire::raw_device_handle [static, protected]
Referenced by ProbeForCameras().
bool VW::SequencerBase::thread_running [protected, inherited]
Referenced by _Step(), VW::SequencerBase::_WaitForThread(), and VW::SequencerBase::Main().
bool VW::SequencerBase::user_finished [protected, inherited]
Referenced by VW::SequencerFirewireWx::_FrameArrived(), VW::SequencerFirewireGTK::_FrameArrived(), VW::SequencerFileWx::_FrameArrived(), VW::SequencerFileGTK::_FrameArrived(), and VW::SequencerBase::_FrameArrived().
unsigned int VW::SequencerFirewire::x_subsamp [protected]
Referenced by CopyImage().
unsigned int VW::SequencerFirewire::y_subsamp [protected]
Referenced by CopyImage().
The documentation for this class was generated from the following files:
sequencerfirewire.h
sequencerfirewire.cpp