VW: VW::YorickDragPad Class Reference
VW::YorickDragPad Class Reference
The Yorick drag-pad.
#include <yorickgtk.h>
Public Member Functions
void Erase ()
void Redraw ()
YorickDragPad (VW::Yorick *yorick_pointer)
~YorickDragPad ()
Protected Attributes
float _pan
float _tilt
float _vergel
float _verger
Detailed Description
The Yorick drag-pad.
This class provides a drawingarea on which mouse-drags send commands to Yorick. Drags with button1 control pan and tilt, and button2 controls vergence. The current axis positions are represented visually by a cross-hair.
Constructor & Destructor Documentation
VW::YorickDragPad::YorickDragPad (VW::Yorick * yorick_pointer)
VW::YorickDragPad::~YorickDragPad ()
Member Function Documentation
void VW::YorickDragPad::Erase ()
void VW::YorickDragPad::Redraw ()
References VW::Yorick::GetPan(), VW::Yorick::GetPanLimits(), VW::Yorick::GetTilt(), VW::Yorick::GetTiltLimits(), VW::Yorick::GetVergeLeft(), VW::Yorick::GetVergeLeftLimits(), VW::Yorick::GetVergeRight(), and VW::Yorick::GetVergeRightLimits().
Referenced by VW::YorickGTK::DemandPan(), VW::YorickGTK::DemandPanTilt(), VW::YorickGTK::DemandTilt(), VW::YorickGTK::DemandVerge(), VW::YorickGTK::DemandVergeRight(), VW::YorickGTK::i_Elevate(), VW::YorickGTK::i_Pan(), VW::YorickGTK::i_VergeLeft(), VW::YorickGTK::i_VergeRight(), and VW::YorickGTK::UpdateForm().
Member Data Documentation
float VW::YorickDragPad::_pan [protected]
float VW::YorickDragPad::_tilt [protected]
float VW::YorickDragPad::_vergel [protected]
float VW::YorickDragPad::_verger [protected]
The documentation for this class was generated from the following files:
yorickgtk.h
yorickgtk.cpp