VW: VNL::MatlabFilewrite Class Reference
VNL::MatlabFilewrite Class Reference
Code to perform MATLAB binary file operations.
#include <matlabfilewrite.h>
Public Member Functions
MatlabFilewrite (char const *file_name, char const *basename=0)
void Write (double v, char const *variable_name=0)
Add scalar/vector/matrix variable to the MAT file using specified variable name.
void Write (Vector< double > const &v, char const *variable_name=0)
vector.
void Write (Vector< std::complex< double > > const &v, char const *variable_name=0)
void Write (Matrix< float > const &M, char const *variable_name=0)
matrix.
void Write (Matrix< double > const &M, char const *variable_name=0)
void Write (Matrix< std::complex< float > > const &M, char const *variable_name=0)
void Write (Matrix< std::complex< double > > const &M, char const *variable_name=0)
void Write (double const *const *M, int rows, int cols, char const *variable_name=0)
Protected Member Functions
std::string _MakeVarName (char const *variable_name)
Protected Attributes
std::string basename_
int variable_int_
std::fstream out_
Detailed Description
Code to perform MATLAB binary file operations.
vnl_matlab_filewrite is a collection of I/O functions for reading/writing matrices in the compact MATLAB binary format (.mat)
Constructor & Destructor Documentation
VNL::MatlabFilewrite::MatlabFilewrite (char const * file_name, char const * basename = 0)
References out_.
Member Function Documentation
std::string VNL::MatlabFilewrite::_MakeVarName (char const * variable_name) [protected]
References basename_, and variable_int_.
Referenced by Write().
void VNL::MatlabFilewrite::Write (double const *const * M, int rows, int cols, char const * variable_name = 0)
References _MakeVarName(), VNL::MatlabWrite(), and out_.
void VNL::MatlabFilewrite::Write (Matrix< std::complex< double > > const & M, char const * variable_name = 0)
References _MakeVarName(), VNL::MatlabWrite(), and out_.
void VNL::MatlabFilewrite::Write (Matrix< std::complex< float > > const & M, char const * variable_name = 0)
References _MakeVarName(), VNL::MatlabWrite(), and out_.
void VNL::MatlabFilewrite::Write (VNL::Matrix< double > const & M, char const * variable_name = 0)
References _MakeVarName(), VNL::Matrix< T >::Cols(), VNL::Matrix< T >::DataArray(), VNL::MatlabWrite(), out_, and VNL::Matrix< T >::Rows().
void VNL::MatlabFilewrite::Write (VNL::Matrix< float > const & M, char const * variable_name = 0)
matrix.
References _MakeVarName(), VNL::Matrix< T >::Cols(), VNL::Matrix< T >::DataArray(), VNL::MatlabWrite(), out_, and VNL::Matrix< T >::Rows().
void VNL::MatlabFilewrite::Write (Vector< std::complex< double > > const & v, char const * variable_name = 0)
References _MakeVarName(), VNL::MatlabWrite(), out_, and v.
void VNL::MatlabFilewrite::Write (VNL::Vector< double > const & v, char const * variable_name = 0)
vector.
References _MakeVarName(), VNL::Vector< T >::DataBlock(), VNL::MatlabWrite(), out_, and VNL::Vector< T >::size().
void VNL::MatlabFilewrite::Write (double v, char const * variable_name = 0)
Add scalar/vector/matrix variable to the MAT file using specified variable name.
scalar.
If no name is given, variables will be generated by appending 0,1,2 etc to the given basename.
References _MakeVarName(), VNL::MatlabWrite(), and out_.
Member Data Documentation
std::string VNL::MatlabFilewrite::basename_ [protected]
Referenced by _MakeVarName().
std::fstream VNL::MatlabFilewrite::out_ [protected]
Referenced by MatlabFilewrite(), and Write().
int VNL::MatlabFilewrite::variable_int_ [protected]
Referenced by _MakeVarName().
The documentation for this class was generated from the following files:
matlabfilewrite.h
matlabfilewrite.cpp