VW: VW::Urand Class Reference
VW::Urand Class Reference
#include <random.h>
Public Member Functions
Urand (int nn)
int operator() ()
void Seed (long s)
int Abs (int x)
int Draw ()
double FDraw ()
Static Public Member Functions
static double RandMax ()
Constructor & Destructor Documentation
VW::Urand::Urand (int nn) [inline]
Member Function Documentation
int VW::Randint::Abs (int x) [inline, inherited]
Referenced by VW::Randint::FDraw(), and VW::Randint::operator()().
int VW::Randint::Draw () [inline, inherited]
Referenced by VW::Randint::FDraw(), and VW::Randint::operator()().
double VW::Randint::FDraw () [inline, inherited]
References VW::Randint::Abs(), VW::Randint::Draw(), and VW::Randint::RandMax().
Referenced by operator()().
int VW::Urand::operator() () [inline]
Reimplemented from VW::Randint.
References VW::Randint::FDraw().
double VW::Randint::RandMax () [inline, static, inherited]
Referenced by VW::Randint::FDraw().
void VW::Randint::Seed (long s) [inline, inherited]
The documentation for this class was generated from the following file:
random.h