VW: VNL::SVD< T > Class Template Reference
VNL::SVD< T > Class Template Reference
Holds the singular value decomposition of a VNL::Matrix.
#include <svd.h>
Public Types
typedef VNL::NumericTraits< T >
::abs_t singval_t
The singular values of a matrix of complex<T> are of type T, not complex<T>.
Public Member Functions
SVD (Matrix< T > const &M, double zero_out_tol=0.0)
Construct an vnl_svd<T> object from matrix .
~SVD ()
void ZeroOutAbsolute (double tol=1e-8)
find weights below threshold tol, zero them out, and update W_ and Winverse_.
void ZeroOutRelative (double tol=1e-8)
find weights below tol*max(w) and zero them out.
int Singularities () const
int Rank () const
singval_t WellCondition () const
singval_t DeterminantMagnitude () const
Calculate determinant as product of diagonals in W.
singval_t Norm () const
Matrix< T > & U ()
Return the matrix U.
Matrix< T > const & U () const
Return the matrix U.
T U (int i, int j)
Return the matrix U's (i,j)th entry (to avoid svd.U()(i,j);).
DiagMatrix< singval_t > & W ()
Get at DiagMatrix (q.v.
DiagMatrix< singval_t > const & W () const
Get at DiagMatrix (q.v.
DiagMatrix< singval_t > & WInverse ()
VNL::DiagMatrix< singval_t >
const & Winverse () const
singval_t & W (int i, int j)
singval_t & W (int i)
singval_t SigmaMax () const
singval_t SigmaMin () const
Matrix< T > & V ()
Return the matrix V.
Matrix< T > const & V () const
Return the matrix V.
T V (int i, int j)
Return the matrix V's (i,j)th entry (to avoid svd.V()(i,j);).
Matrix< T > Inverse () const
Matrix< T > PseudoInverse () const
pseudo-inverse (for non-square matrix).
Matrix< T > PseudoInverse (int rank) const
pseudo-inverse (for non-square matrix) of desired rank.
Matrix< T > TransposeInverse () const
Calculate inverse of transpose.
Matrix< T > Recompose () const
Recompose SVD to U*W*V'.
Matrix< T > Solve (Matrix< T > const &B) const
Solve the matrix equation M X = B, returning X.
Vector< T > Solve (Vector< T > const &y) const
Solve the matrix-vector system M x = y, returning x.
void Solve (T const *rhs, T *lhs) const
void SolvePreinverted (Vector< T > const &rhs, Vector< T > *out) const
Solve the matrix-vector system M x = y.
VNL::Matrix< T > Nullspace () const
Return N such that M * N = 0.
VNL::Matrix< T > LeftNullspace () const
Return N such that M' * N = 0.
VNL::Matrix< T > Nullspace (int required_nullspace_dimension) const
Return N such that M * N = 0.
VNL::Matrix< T > LeftNullspace (int required_nullspace_dimension) const
Implementation to be done yet; currently returns left_nullspace(). - PVR.
VNL::Vector< T > Nullvector () const
Return the rightmost column of V.
VNL::Vector< T > LeftNullvector () const
Return the rightmost column of U.
bool Valid () const
template<>
SVD (VNL::Matrix< long double > const &M, double)
Detailed Description
template<class T>
class VNL::SVD< T >
Holds the singular value decomposition of a VNL::Matrix.
The class holds three matrices U, W, V such that the original matrix . The DiagMatrix W stores the singular values in decreasing order. The columns of U which correspond to the nonzero singular values form a basis for range of M, while the columns of V corresponding to the zero singular values are the nullspace.
The SVD is computed at construction time, and enquiries may then be made of the SVD. In particular, this allows easy access to multiple right-hand-side solves without the bother of putting all the RHS's into a Matrix.
This class is supplied even though there is an existing VNL::Matrix method for several reasons:
It is more convenient to use as it manages all the storage for the U,S,V matrices, allowing repeated queries of the same SVD results.
It avoids namespace clutter in the Matrix class. While svd() is a perfectly reasonable method for a Matrix, there are many other decompositions that might be of interest, and adding them all would make for a very large Matrix class.
It demonstrates the holder model of compute class, implementing an algorithm on an object without adding a member that may not be of general interest. A similar pattern can be used for other decompositions which are not defined as members of the library Matrix class.
It extends readily to n-ary operations, such as generalized eigensystems, which cannot be members of just one matrix.
Member Typedef Documentation
template<class T> typedef VNL::NumericTraits<T>::abs_t VNL::SVD< T >::singval_t
The singular values of a matrix of complex<T> are of type T, not complex<T>.
Constructor & Destructor Documentation
template<class T> VNL::SVD< T >::SVD (VNL::Matrix< T > const & M, double zero_out_tol = 0.0) [inline]
Construct an vnl_svd<T> object from matrix .
The vnl_svd<T> object contains matrices , , such that .
Uses linpack routine DSVDC to calculate an ``economy-size'' SVD where the returned is the same size as , while and are both . This is efficient for large rectangular solves where , typical in least squares.
The optional argument zero_out_tol is used to mark the zero singular values: If nonnegative, any s.v. smaller than zero_out_tol in absolute value is set to zero. If zero_out_tol is negative, the zeroing is relative to |zero_out_tol| * sigma_max();
References abs, VNL::Matrix< T >::assert_finite(), VNL::Matrix< T >::Columns(), VNL::Vector< T >::DataBlock(), VNL::Math::eps, VNL::Matrix< T >::FrobeniusNorm(), VNL::matlab_print_format_long, VNL::MatlabPrint(), min, VNL::SVD< T >::Recompose(), VNL::Matrix< T >::Rows(), VNL::SVD< T >::ZeroOutAbsolute(), and VNL::SVD< T >::ZeroOutRelative().
template<class T> VNL::SVD< T >::~SVD () [inline]
template<> VNL::SVD< long double >::SVD (VNL::Matrix< long double > const & M, double) [inline]
References VNL::Copy(), VNL::SVD< T >::U(), VNL::SVD< T >::V(), and VNL::SVD< T >::W().
Member Function Documentation
template<class T > VNL::SVD< T >::singval_t VNL::SVD< T >::DeterminantMagnitude () const [inline]
Calculate determinant as product of diagonals in W.
References VNL::DiagMatrix< T >::Columns().
template<class T > VNL::Matrix< T > VNL::SVD< T >::Inverse () const [inline]
References VNL::SVD< T >::PseudoInverse().
Referenced by VW::Homography2D::Inverse(), and VNL::MatrixInverse< T >::operator VNL::Matrix< T >().
template<class T > VNL::Matrix< T > VNL::SVD< T >::LeftNullspace (int required_nullspace_dimension) const [inline]
Implementation to be done yet; currently returns left_nullspace(). - PVR.
References VNL::SVD< T >::LeftNullspace().
template<class T > VNL::Matrix< T > VNL::SVD< T >::LeftNullspace () const [inline]
Return N such that M' * N = 0.
Return N s.t. M' * N = 0.
References VNL::SVD< T >::Rank().
Referenced by VNL::SVD< T >::LeftNullspace().
template<class T > VNL::Vector< T > VNL::SVD< T >::LeftNullvector () const [inline]
Return the rightmost column of U.
Does not check to see whether or not the matrix actually was rank-deficient.
References min.
template<class T > VNL::SVD< T >::singval_t VNL::SVD< T >::Norm () const [inline]
References abs, and VNL::SVD< T >::SigmaMax().
template<class T > VNL::Matrix< T > VNL::SVD< T >::Nullspace (int required_nullspace_dimension) const [inline]
Return N such that M * N = 0.
Return N s.t. M * N = 0.
template<class T > VNL::Matrix< T > VNL::SVD< T >::Nullspace () const [inline]
Return N such that M * N = 0.
Return N s.t. M * N = 0.
References VNL::SVD< T >::Rank().
template<class T > VNL::Vector< T > VNL::SVD< T >::Nullvector () const [inline]
Return the rightmost column of V.
Does not check to see whether or not the matrix actually was rank-deficient - the caller is assumed to have examined W and decided that to his or her satisfaction.
Referenced by VW::FMPlanarCompute::GenerateParameterVectorHZJK(), VW::FMPlanarCompute::GenerateParameterVectorVLJK(), and VW::PMatrixCompute::LinearFromPoints().
template<class T > VNL::Matrix< T > VNL::SVD< T >::PseudoInverse (int rank) const [inline]
pseudo-inverse (for non-square matrix) of desired rank.
Calculate pseudo-inverse.
References VNL::DiagMatrix< T >::Columns(), VNL::DiagMatrix< T >::Fill(), VNL::DiagMatrix< T >::Rows(), and VNL::SVD< T >::Winverse().
template<class T > VNL::Matrix< T > VNL::SVD< T >::PseudoInverse () const [inline]
pseudo-inverse (for non-square matrix).
Calculate pseudo-inverse.
References VNL::DiagMatrix< T >::Columns(), VNL::DiagMatrix< T >::Fill(), VNL::DiagMatrix< T >::Rows(), and VNL::SVD< T >::Winverse().
Referenced by VNL::SVD< T >::Inverse().
template<class T> int VNL::SVD< T >::Rank () const [inline]
Referenced by VNL::SVD< T >::LeftNullspace(), VNL::SVD< T >::Nullspace(), and VNL::SVD< T >::Singularities().
template<class T > VNL::Matrix< T > VNL::SVD< T >::Recompose () const [inline]
Recompose SVD to U*W*V'.
References VNL::DiagMatrix< T >::Columns(), VNL::DiagMatrix< T >::Fill(), VNL::DiagMatrix< T >::Rows(), and VNL::SVD< T >::W().
Referenced by VW::FMatrix::Constrain(), and VNL::SVD< T >::SVD().
template<class T> singval_t VNL::SVD< T >::SigmaMax () const [inline]
Referenced by VNL::SVD< T >::Norm(), VNL::SVD< T >::WellCondition(), and VNL::SVD< T >::ZeroOutRelative().
template<class T> singval_t VNL::SVD< T >::SigmaMin () const [inline]
Referenced by VNL::SVD< T >::WellCondition().
template<class T> int VNL::SVD< T >::Singularities () const [inline]
References VNL::SVD< T >::Rank(), and VNL::DiagMatrix< T >::Rows().
template<class T> void VNL::SVD< T >::Solve (T const * rhs, T * lhs) const [inline]
References VNL::SVD< T >::Solve().
template<class T> VNL::Vector< T > VNL::SVD< T >::Solve (VNL::Vector< T > const & y) const [inline]
Solve the matrix-vector system M x = y, returning x.
References VNL::Vector< T >::size(), and VNL::Vector< T >::Update().
template<class T> VNL::Matrix< T > VNL::SVD< T >::Solve (VNL::Matrix< T > const & B) const [inline]
Solve the matrix equation M X = B, returning X.
References VNL::Matrix< T >::Columns(), and VNL::Matrix< T >::Rows().
Referenced by operator*(), and VNL::SVD< T >::Solve().
template<class T> void VNL::SVD< T >::SolvePreinverted (VNL::Vector< T > const & y, VNL::Vector< T > * x_out) const [inline]
Solve the matrix-vector system M x = y.
Assuming that the singular values W have been preinverted by the caller.
Assume that the singular values W have been preinverted by the caller.
References VNL::Vector< T >::size().
template<class T > VNL::Matrix< T > VNL::SVD< T >::TransposeInverse () const [inline]
Calculate inverse of transpose.
References VNL::DiagMatrix< T >::Columns(), VNL::DiagMatrix< T >::Fill(), VNL::DiagMatrix< T >::Rows(), and VNL::SVD< T >::Winverse().
template<class T> T VNL::SVD< T >::U (int i, int j) [inline]
Return the matrix U's (i,j)th entry (to avoid svd.U()(i,j);).
template<class T> Matrix<T> const& VNL::SVD< T >::U () const [inline]
Return the matrix U.
template<class T> Matrix<T>& VNL::SVD< T >::U () [inline]
Return the matrix U.
Referenced by VW::EssentialMatrix::Constrain(), VW::EssentialMatrix::Decompose(), VW::FMatrix::GetEpipoles(), VW::EssentialMatrix::GetEpipoles(), VW::RotationMatrix::Normalise(), VW::RotationMatrix::Set(), and VNL::SVD< T >::SVD().
template<class T> T VNL::SVD< T >::V (int i, int j) [inline]
Return the matrix V's (i,j)th entry (to avoid svd.V()(i,j);).
template<class T> Matrix<T> const& VNL::SVD< T >::V () const [inline]
Return the matrix V.
template<class T> Matrix<T>& VNL::SVD< T >::V () [inline]
Return the matrix V.
Referenced by VW::EssentialMatrix::Constrain(), VW::EssentialMatrix::Decompose(), VW::FMatrix::GetEpipoles(), VW::EssentialMatrix::GetEpipoles(), VW::RotationMatrix::Normalise(), VW::RotationMatrix::Set(), and VNL::SVD< T >::SVD().
template<class T> bool VNL::SVD< T >::Valid () const [inline]
Referenced by VW::RotationMatrix::Normalise().
template<class T> singval_t& VNL::SVD< T >::W (int i) [inline]
template<class T> singval_t& VNL::SVD< T >::W (int i, int j) [inline]
template<class T> DiagMatrix<singval_t> const& VNL::SVD< T >::W () const [inline]
Get at DiagMatrix (q.v.
) of singular values, sorted from largest to smallest.
template<class T> DiagMatrix<singval_t>& VNL::SVD< T >::W () [inline]
Get at DiagMatrix (q.v.
) of singular values, sorted from largest to smallest.
Referenced by VW::FMatrix::Constrain(), VW::EssentialMatrix::Decompose(), VNL::SVD< T >::Recompose(), and VNL::SVD< T >::SVD().
template<class T> singval_t VNL::SVD< T >::WellCondition () const [inline]
References VNL::SVD< T >::SigmaMax(), and VNL::SVD< T >::SigmaMin().
template<class T> VNL::DiagMatrix<singval_t> const& VNL::SVD< T >::Winverse () const [inline]
Referenced by VNL::SVD< T >::PseudoInverse(), and VNL::SVD< T >::TransposeInverse().
template<class T> DiagMatrix<singval_t>& VNL::SVD< T >::WInverse () [inline]
template<class T > void VNL::SVD< T >::ZeroOutAbsolute (double tol = 1e-8) [inline]
find weights below threshold tol, zero them out, and update W_ and Winverse_.
References std::abs(), and VNL::DiagMatrix< T >::Rows().
Referenced by VNL::SVD< T >::SVD(), and VNL::SVD< T >::ZeroOutRelative().
template<class T > void VNL::SVD< T >::ZeroOutRelative (double tol = 1e-8) [inline]
find weights below tol*max(w) and zero them out.
References std::abs(), VNL::SVD< T >::SigmaMax(), and VNL::SVD< T >::ZeroOutAbsolute().
Referenced by VNL::SVD< T >::SVD().
The documentation for this class was generated from the following files:
svd.h
svd.tpp