VW: VW::Mutex Class Reference
VW::Mutex Class Reference
Simple class to represent a mutex (mutual exclusion).
#include <thread.h>
Public Member Functions
Mutex ()
~Mutex ()
bool Lock ()
Attempt to lock the mutex.
bool Unlock ()
Detailed Description
Simple class to represent a mutex (mutual exclusion).
Constructor & Destructor Documentation
VW::Mutex::Mutex ()
References FALSE, and VERBOSE.
VW::Mutex::~Mutex ()
References VERBOSE.
Member Function Documentation
bool VW::Mutex::Lock ()
Attempt to lock the mutex.
References VERBOSE.
Referenced by VW::SequencerFile::_Step(), VW::SequencerBase::_WaitForThread(), VW::SequencerBase::Continuous(), VW::SequencerBase::Main(), VW::SequencerBase::Next(), VW::SequencerFile::Rewind(), VW::SequencerFile::Skip(), and VW::SequencerBase::Stop().
bool VW::Mutex::Unlock ()
References TRUE, and VERBOSE.
Referenced by VW::SequencerFile::_Step(), VW::SequencerBase::_WaitForThread(), VW::SequencerBase::Continuous(), VW::SequencerBase::Main(), VW::SequencerBase::Next(), VW::SequencerFile::Rewind(), VW::SequencerFile::Skip(), and VW::SequencerBase::Stop().
The documentation for this class was generated from the following files:
thread.h
thread.cpp