VW: VW::SequencerFileGTK Class Reference
VW::SequencerFileGTK Class Reference
[Sequencers]
A GTK1-based interface to the file sequencer.
#include <sequencerfilegtk.h>
Public Member Functions
SequencerFileGTK (VW::InterfaceType t=VW::INTERFACE_AS_BUTTONWINDOW)
SequencerFileGTK (const std::string &first_file_name, VW::InterfaceType t=VW::INTERFACE_AS_BUTTONWINDOW)
SequencerFileGTK (const std::vector< std::string > &first_file_names, VW::InterfaceType t=VW::INTERFACE_AS_BUTTONWINDOW)
~SequencerFileGTK ()
virtual bool Init ()
All sequencers have an Init(), even if they don't need it, so call init() before using a sequencer (especially if from an interface).
void AddChannel (const std::string &file_name)
Add an extra file-channel.
virtual void Continuous ()
Start continuous capture from the sequence.
virtual void Stop ()
Stop continuous capture from the sequence.
virtual void Next ()
Capture the next single frame.
virtual void Rewind ()
Re-open this file and start from the beginning.
virtual void SetLooping (SequencerLoopMode mode=LOOP)
What should the sequencer do when it runs out of files in the sequence?
void CreateForm ()
void UpdateForm ()
void UpdateFromForm ()
void LoadParameterFile (std::string paramfile=".param")
void SaveParameterFile (std::string paramfile=".param")
void OnLoopChanged (int which)
void Show (void)
void Hide (void)
void Quit (void)
VW::InterfaceType GetType (void)
void AddChannels (const std::vector< std::string > &file_names)
Add a set of extra file-channels.
bool IsChannelOK (unsigned int which_channel=0) const
Was the last read operation on this channel successful?
void * GetBuffer (unsigned int which_channel=0)
Gain access to the sequencers buffer.
template<class ImType >
void CopyImage (ImType &image, unsigned int which_channel=0)
Take a copy of the grabbed image.
virtual void Skip (int num_frames=1)
Skip the next frame(s).
std::string GetInitialFileName (unsigned int which_channel=0)
The name(s) of the files.
Initialisation functions
virtual void SetDelay (int d)
Set the delay between frames (only usually used for non-hardware sequencers).
Information functions
bool GetContinuous () const
Is the sequencer running in continuous mode?
int GetDelay () const
What is the delay between frames.
unsigned int GetNumberOfChannels () const
Most sequencers are able to present mutliple images per frame.
unsigned int GetCurrentFrameNumber () const
Return the current frame number.
Public Attributes
SigC::Signal1< void, int > NewFrameSignal
VWEvents::Event1< void, int > NewFrameEvent
The "new frame has arrived" event.
Protected Member Functions
virtual void _FrameArrived ()
we have been signalled that a frame has arrived and we are now "inside" the signalling object, so invoke the appropriate callback
void LoadStart ()
void LoadOK ()
void SaveStart ()
void SaveOK ()
void FileCancel ()
virtual void InitButtonWindow ()
virtual void InitButtonWindow (unsigned int width, unsigned int height)
virtual void InitWidget ()
void _InitialiseFiles ()
bool _DetermineFilenamePatterns (unsigned int which_channel)
virtual bool _Step ()
void _WaitForThread ()
Wait for the thread to exit.
void * Main (void *)
void _CheckInitialised ()
Protected Attributes
SigC::Signal1< void, std::string > LoadEvent
SigC::Signal1< void, std::string > SaveEvent
SequencerFileGTKWidget * my_widget
Gtk::Window * my_window
VW::InterfaceType my_type
std::string my_name
Gtk::FileSelection * file_selector
std::vector< ImageRGB
< unsigned char > * > im
std::vector< std::string > first_file_name
std::vector< std::string > format_string
std::vector< int > frame_num
std::vector< int > initial_frame_num
std::vector< int > play_speed
std::vector< bool > file_ok
SequencerLoopMode _loop
int delay
unsigned int frame_number
bool cont
bool thread_running
bool _initialised
ThreadType parent
unsigned int number_of_channels
Mutex access_lock
bool user_finished
Detailed Description
A GTK1-based interface to the file sequencer.
Author:
ID Reid, BJ Tordoff
Date:
02/08/02 This sequencer is a version of SequencerFile which also provides a GTK interface. The sequencer functionality is identical to the parent class, but with added functions to control the interface. As it is just a GTK1 widget it can be embedded in any GTK1 form, either as a button and pop-up window or as a full widget.
Constructor & Destructor Documentation
VW::SequencerFileGTK::SequencerFileGTK (VW::InterfaceType t = VW::INTERFACE_AS_BUTTONWINDOW)
References VW::InterfaceGTK< SequencerFileGTKWidget >::InitButtonWindow(), VW::SequencerFileGTKWidget::InitForm(), VW::InterfaceGTK< SequencerFileGTKWidget >::InitWidget(), VW::INTERFACE_AS_BUTTONWINDOW, VW::InterfaceGTK< SequencerFileGTKWidget >::my_name, VW::InterfaceGTK< SequencerFileGTKWidget >::my_type, VW::InterfaceGTK< SequencerFileGTKWidget >::my_widget, and UpdateForm().
VW::SequencerFileGTK::SequencerFileGTK (const std::string & first_file_name, VW::InterfaceType t = VW::INTERFACE_AS_BUTTONWINDOW)
VW::SequencerFileGTK::SequencerFileGTK (const std::vector< std::string > & first_file_names, VW::InterfaceType t = VW::INTERFACE_AS_BUTTONWINDOW)
VW::SequencerFileGTK::~SequencerFileGTK ()
References Stop().
Member Function Documentation
void VW::SequencerBase::_CheckInitialised () [protected, inherited]
References VW::SequencerBase::_initialised.
Referenced by VW::SequencerBase::Continuous(), VW::SequencerBase::Next(), and VW::SequencerBase::Stop().
bool SequencerFile::_DetermineFilenamePatterns (unsigned int which_channel) [protected, inherited]
References VW::SequencerFile::first_file_name, VW::SequencerFile::format_string, VW::SequencerFile::frame_num, and VW::SequencerFile::initial_frame_num.
Referenced by UpdateFromForm().
virtual void VW::SequencerFileGTK::_FrameArrived () [inline, protected, virtual]
we have been signalled that a frame has arrived and we are now "inside" the signalling object, so invoke the appropriate callback
Reimplemented from VW::SequencerBase.
References VW::SequencerBase::NewFrameEvent, NewFrameSignal, and VW::SequencerBase::user_finished.
void SequencerFile::_InitialiseFiles () [protected, inherited]
References VW::SequencerFile::_loop, VW::SequencerFile::file_ok, VW::SequencerFile::format_string, VW::SequencerFile::frame_num, VW::SequencerBase::frame_number, VW::SequencerFile::im, VW::SequencerFile::initial_frame_num, VW::NO_LOOPING, VW::SequencerBase::number_of_channels, and VW::SequencerFile::play_speed.
Referenced by VW::SequencerFile::SequencerFile().
bool SequencerFile::_Step () [protected, virtual, inherited]
Implements VW::SequencerBase.
References VW::SequencerFile::_loop, VW::SequencerBase::access_lock, VW::BOUNCE, VW::SequencerBase::cont, VW::SequencerFile::file_ok, VW::SequencerFile::format_string, VW::SequencerFile::frame_num, VW::SequencerBase::frame_number, VW::SequencerFile::im, VW::SequencerFile::initial_frame_num, VW::Mutex::Lock(), VW::LOOP, VW::NO_LOOPING, VW::SequencerBase::number_of_channels, VW::SequencerFile::play_speed, VW::ReadImage(), VW::REPEATLAST, VW::SequencerBase::Stop(), and VW::Mutex::Unlock().
void SequencerBase::_WaitForThread () [inline, protected, inherited]
Wait for the thread to exit.
References VW::SequencerBase::access_lock, VW::Mutex::Lock(), msleep(), VW::SequencerBase::thread_running, VW::Mutex::Unlock(), and VERBOSE.
Referenced by VW::SequencerBase::Stop().
void VW::SequencerFileGTK::AddChannel (const std::string & file_name) [virtual]
Add an extra file-channel.
Channels can be added at any time and simply begin from thier first frame.
Reimplemented from VW::SequencerFile.
void VW::SequencerFile::AddChannels (const std::vector< std::string > & file_names) [inline, inherited]
Add a set of extra file-channels.
Channels can be added at any time and simply begin from thier first frame.
References VW::SequencerFile::AddChannel().
void VW::SequencerFileGTK::Continuous () [virtual]
Start continuous capture from the sequence.
Reimplemented from VW::SequencerBase.
References UpdateForm(), and VERBOSE.
Referenced by VW::SequencerFileGTKWidget::InitForm().
template<class ImType > void VW::SequencerFile::CopyImage (ImType & image, unsigned int which_channel = 0) [inline, inherited]
Take a copy of the grabbed image.
References VW::SequencerFile::im, VW::ImageCopy(), and VW::SequencerBase::number_of_channels.
void VW::SequencerFileGTK::CreateForm ()
void VW::InterfaceGTK< SequencerFileGTKWidget >::FileCancel () [inline, protected, inherited]
void * VW::SequencerFile::GetBuffer (unsigned int which_channel = 0) [inline, virtual, inherited]
Gain access to the sequencers buffer.
Implements VW::SequencerBase.
References VW::SequencerFile::im.
bool VW::SequencerBase::GetContinuous () const [inline, inherited]
Is the sequencer running in continuous mode?
References VW::SequencerBase::cont.
unsigned int VW::SequencerBase::GetCurrentFrameNumber () const [inline, inherited]
Return the current frame number.
In the case of movies or files this is the frame number with respect to the start frame (ie, 1=start frame) and won't correspond to the sequence frame numbers if started part way through a sequence.
References VW::SequencerBase::frame_number.
int VW::SequencerBase::GetDelay () const [inline, inherited]
What is the delay between frames.
References VW::SequencerBase::delay.
std::string VW::SequencerFile::GetInitialFileName (unsigned int which_channel = 0) [inline, inherited]
The name(s) of the files.
References VW::SequencerFile::first_file_name.
Referenced by VW::SequencerFileGTKWidget::AddFile().
unsigned int VW::SequencerBase::GetNumberOfChannels () const [inline, inherited]
Most sequencers are able to present mutliple images per frame.
References VW::SequencerBase::number_of_channels.
Referenced by VW::SequencerMovieGTKWidget::InitForm(), and VW::SequencerFileGTKWidget::InitForm().
VW::InterfaceType VW::InterfaceGTK< SequencerFileGTKWidget >::GetType (void) [inline, inherited]
void VW::InterfaceGTK< SequencerFileGTKWidget >::Hide (void) [inline, inherited]
bool VW::SequencerFileGTK::Init () [virtual]
All sequencers have an Init(), even if they don't need it, so call init() before using a sequencer (especially if from an interface).
Reimplemented from VW::SequencerFile.
References UpdateForm(), and VERBOSE.
virtual void VW::InterfaceGTK< SequencerFileGTKWidget >::InitButtonWindow (unsigned int width, unsigned int height) [protected, virtual, inherited]
virtual void VW::InterfaceGTK< SequencerFileGTKWidget >::InitButtonWindow () [protected, virtual, inherited]
Referenced by SequencerFileGTK().
virtual void VW::InterfaceGTK< SequencerFileGTKWidget >::InitWidget () [protected, virtual, inherited]
Referenced by SequencerFileGTK().
bool VW::SequencerFile::IsChannelOK (unsigned int which_channel = 0) const [inline, inherited]
Was the last read operation on this channel successful?
References VW::SequencerFile::file_ok.
void VW::InterfaceGTK< SequencerFileGTKWidget >::LoadOK () [inline, protected, inherited]
void VW::SequencerFileGTK::LoadParameterFile (std::string paramfile = ".param") [inline]
void VW::InterfaceGTK< SequencerFileGTKWidget >::LoadStart () [inline, protected, inherited]
void * SequencerBase::Main (void *) [protected, virtual, inherited]
Implements VW::Thread.
References VW::SequencerBase::_FrameArrived(), VW::SequencerBase::_Step(), VW::SequencerBase::access_lock, VW::SequencerBase::cont, VW::SequencerBase::delay, VW::SequencerBase::frame_number, VW::Mutex::Lock(), msleep(), VW::SequencerBase::thread_running, VW::Mutex::Unlock(), and VERBOSE.
void VW::SequencerFileGTK::Next () [virtual]
Capture the next single frame.
Reimplemented from VW::SequencerBase.
References UpdateForm(), and VERBOSE.
Referenced by VW::SequencerFileGTKWidget::InitForm().
void VW::SequencerFileGTK::OnLoopChanged (int which)
References VW::BOUNCE, VW::LOOP, VW::NO_LOOPING, and SetLooping().
Referenced by VW::SequencerFileGTKWidget::InitForm().
void VW::InterfaceGTK< SequencerFileGTKWidget >::Quit (void) [inline, inherited]
void VW::SequencerFileGTK::Rewind () [virtual]
Re-open this file and start from the beginning.
Reimplemented from VW::SequencerFile.
References UpdateForm(), and VERBOSE.
Referenced by VW::SequencerFileGTKWidget::InitForm().
void VW::InterfaceGTK< SequencerFileGTKWidget >::SaveOK () [inline, protected, inherited]
void VW::SequencerFileGTK::SaveParameterFile (std::string paramfile = ".param") [inline]
void VW::InterfaceGTK< SequencerFileGTKWidget >::SaveStart () [inline, protected, inherited]
void VW::SequencerBase::SetDelay (int d) [inline, virtual, inherited]
Set the delay between frames (only usually used for non-hardware sequencers).
This is the time (in milliseconds) for which the sequencer sleeps between frames: the total frame period will be this plus the time taken to acquire the new frame. By default the delay is set to 1ms (zero or less is not a valid setting).
References VW::SequencerBase::delay.
void VW::SequencerFileGTK::SetLooping (SequencerLoopMode mode = LOOP) [virtual]
What should the sequencer do when it runs out of files in the sequence?
Reimplemented from VW::SequencerFile.
References VW::SequencerFile::_loop, VW::SequencerFileGTKWidget::loop_menu, and VW::InterfaceGTK< SequencerFileGTKWidget >::my_widget.
Referenced by OnLoopChanged().
void VW::InterfaceGTK< SequencerFileGTKWidget >::Show (void) [inline, inherited]
void SequencerFile::Skip (int num_frames = 1) [virtual, inherited]
Skip the next frame(s).
References VW::SequencerBase::access_lock, VW::SequencerFile::file_ok, VW::SequencerFile::frame_num, VW::SequencerBase::frame_number, VW::Mutex::Lock(), VW::SequencerBase::number_of_channels, and VW::Mutex::Unlock().
void VW::SequencerFileGTK::Stop () [virtual]
Stop continuous capture from the sequence.
Reimplemented from VW::SequencerBase.
References UpdateForm(), and VERBOSE.
Referenced by VW::SequencerFileGTKWidget::InitForm(), and ~SequencerFileGTK().
void VW::SequencerFileGTK::UpdateForm (void) [virtual]
Implements VW::InterfaceGTK< SequencerFileGTKWidget >.
References VW::SequencerBase::cont, VW::SequencerFile::file_ok, VW::SequencerFileGTKWidget::frame_no_label, VW::SequencerBase::frame_number, VW::SequencerFileGTKWidget::go_button, VW::InterfaceGTK< SequencerFileGTKWidget >::my_widget, VW::SequencerFileGTKWidget::next_button, VW::SequencerBase::number_of_channels, VW::SequencerFileGTKWidget::rewind_button, VW::SequencerFileGTKWidget::SetLED(), VW::SequencerFileGTKWidget::stop_button, and VERBOSE.
Referenced by Continuous(), Init(), Next(), Rewind(), SequencerFileGTK(), Stop(), and UpdateFromForm().
void VW::SequencerFileGTK::UpdateFromForm ()
References VW::SequencerFile::_DetermineFilenamePatterns(), VW::SequencerFile::file_ok, VW::SequencerFile::first_file_name, VW::SequencerFileGTKWidget::GetFileName(), VW::InterfaceGTK< SequencerFileGTKWidget >::my_widget, VW::SequencerBase::number_of_channels, UpdateForm(), and VERBOSE.
Referenced by VW::SequencerFileChannelGTKWidget::InitForm(), VW::SequencerFileChannelGTKWidget::LoadCancel(), and VW::SequencerFileChannelGTKWidget::LoadOK().
Member Data Documentation
bool VW::SequencerBase::_initialised [protected, inherited]
Referenced by VW::SequencerBase::_CheckInitialised(), and VW::SequencerBase::Init().
SequencerLoopMode VW::SequencerFile::_loop [protected, inherited]
Referenced by VW::SequencerFile::_InitialiseFiles(), VW::SequencerFile::_Step(), VW::SequencerFileWx::SetLooping(), SetLooping(), and VW::SequencerFile::SetLooping().
Mutex VW::SequencerBase::access_lock [protected, inherited]
Referenced by VW::SequencerFile::_Step(), VW::SequencerBase::_WaitForThread(), VW::SequencerBase::Continuous(), VW::SequencerBase::Main(), VW::SequencerBase::Next(), VW::SequencerFile::Rewind(), VW::SequencerFile::Skip(), and VW::SequencerBase::Stop().
bool VW::SequencerBase::cont [protected, inherited]
Referenced by VW::SequencerMovie::_Step(), VW::SequencerFirewire::_Step(), VW::SequencerFile::_Step(), VW::SequencerBase::Continuous(), VW::SequencerBase::GetContinuous(), VW::SequencerBase::Main(), VW::SequencerBase::Next(), VW::SequencerBase::Stop(), VW::SequencerMovieGTK::UpdateForm(), VW::SequencerFirewireWx::UpdateForm(), VW::SequencerFileWx::UpdateForm(), and UpdateForm().
int VW::SequencerBase::delay [protected, inherited]
Referenced by VW::SequencerBase::GetDelay(), VW::SequencerBase::Main(), and VW::SequencerBase::SetDelay().
std::vector<bool> VW::SequencerFile::file_ok [protected, inherited]
Referenced by VW::SequencerFile::_InitialiseFiles(), VW::SequencerFile::_Step(), VW::SequencerFile::IsChannelOK(), VW::SequencerFile::Rewind(), VW::SequencerFile::Skip(), VW::SequencerFileWx::UpdateForm(), UpdateForm(), and UpdateFromForm().
Gtk::FileSelection* VW::InterfaceGTK< SequencerFileGTKWidget >::file_selector [protected, inherited]
std::vector<std::string> VW::SequencerFile::first_file_name [protected, inherited]
Referenced by VW::SequencerFile::_DetermineFilenamePatterns(), VW::SequencerFile::GetInitialFileName(), and UpdateFromForm().
std::vector<std::string> VW::SequencerFile::format_string [protected, inherited]
Referenced by VW::SequencerFile::_DetermineFilenamePatterns(), VW::SequencerFile::_InitialiseFiles(), and VW::SequencerFile::_Step().
std::vector<int> VW::SequencerFile::frame_num [protected, inherited]
Referenced by VW::SequencerFile::_DetermineFilenamePatterns(), VW::SequencerFile::_InitialiseFiles(), VW::SequencerFile::_Step(), VW::SequencerFile::Rewind(), and VW::SequencerFile::Skip().
unsigned int VW::SequencerBase::frame_number [protected, inherited]
Referenced by VW::SequencerFile::_InitialiseFiles(), VW::SequencerMovie::_Step(), VW::SequencerFile::_Step(), VW::SequencerBase::GetCurrentFrameNumber(), VW::SequencerBase::Main(), VW::SequencerMovie::Rewind(), VW::SequencerFile::Rewind(), VW::SequencerFile::SequencerFile(), VW::SequencerFile::Skip(), VW::SequencerFileWx::UpdateForm(), and UpdateForm().
std::vector<ImageRGB<unsigned char>* > VW::SequencerFile::im [protected, inherited]
Referenced by VW::SequencerFile::_InitialiseFiles(), VW::SequencerFile::_Step(), VW::SequencerFile::CopyImage(), and VW::SequencerFile::GetBuffer().
std::vector<int> VW::SequencerFile::initial_frame_num [protected, inherited]
Referenced by VW::SequencerFile::_DetermineFilenamePatterns(), VW::SequencerFile::_InitialiseFiles(), VW::SequencerFile::_Step(), and VW::SequencerFile::Rewind().
SigC::Signal1<void,std::string> VW::InterfaceGTK< SequencerFileGTKWidget >::LoadEvent [protected, inherited]
std::string VW::InterfaceGTK< SequencerFileGTKWidget >::my_name [protected, inherited]
Referenced by SequencerFileGTK().
VW::InterfaceType VW::InterfaceGTK< SequencerFileGTKWidget >::my_type [protected, inherited]
Referenced by SequencerFileGTK().
SequencerFileGTKWidget * VW::InterfaceGTK< SequencerFileGTKWidget >::my_widget [protected, inherited]
Referenced by SequencerFileGTK(), SetLooping(), UpdateForm(), and UpdateFromForm().
Gtk::Window* VW::InterfaceGTK< SequencerFileGTKWidget >::my_window [protected, inherited]
VWEvents::Event1<void,int> VW::SequencerBase::NewFrameEvent [inherited]
The "new frame has arrived" event.
Attach a function to this callback signal if you want to perform an operation each time a new image arrives. This is typically done using my_sequencer.NewFrameEvent.connect(&MyFunction); where 'MyFunction' must take an integer argument and return void.
Referenced by VW::SequencerMeteor::_FrameArrived(), VW::SequencerFirewireWx::_FrameArrived(), VW::SequencerFirewireGTK::_FrameArrived(), VW::SequencerFileWx::_FrameArrived(), _FrameArrived(), and VW::SequencerBase::_FrameArrived().
SigC::Signal1<void,int> VW::SequencerFileGTK::NewFrameSignal
Referenced by _FrameArrived().
unsigned int VW::SequencerBase::number_of_channels [protected, inherited]
Referenced by VW::SequencerFile::_InitialiseFiles(), VW::SequencerMovie::_Step(), VW::SequencerFirewire::_Step(), VW::SequencerFile::_Step(), VW::SequencerFile::CopyImage(), VW::SequencerFirewire::GetCamera(), VW::SequencerFirewire::GetNumberOfCameras(), VW::SequencerBase::GetNumberOfChannels(), VW::SequencerMeteor::Init(), VW::SequencerFirewire::ProbeForCameras(), VW::SequencerMovie::Rewind(), VW::SequencerFile::Rewind(), VW::SequencerFile::SequencerFile(), VW::SequencerFirewire::SequencerFirewire(), VW::SequencerMovie::SequencerMovie(), VW::SequencerFirewire::SetDefaultCameraSettings(), VW::SequencerFile::Skip(), VW::SequencerFirewire::StartDMA(), VW::SequencerFirewire::StartISO(), VW::SequencerFirewire::StopDMA(), VW::SequencerFirewire::StopISO(), VW::SequencerMovieGTK::UpdateForm(), VW::SequencerFileWx::UpdateForm(), UpdateForm(), VW::SequencerMovieGTK::UpdateFromForm(), and UpdateFromForm().
ThreadType VW::SequencerBase::parent [protected, inherited]
std::vector<int> VW::SequencerFile::play_speed [protected, inherited]
Referenced by VW::SequencerFile::_InitialiseFiles(), and VW::SequencerFile::_Step().
SigC::Signal1<void,std::string> VW::InterfaceGTK< SequencerFileGTKWidget >::SaveEvent [protected, inherited]
bool VW::SequencerBase::thread_running [protected, inherited]
Referenced by VW::SequencerFirewire::_Step(), VW::SequencerBase::_WaitForThread(), and VW::SequencerBase::Main().
bool VW::SequencerBase::user_finished [protected, inherited]
Referenced by VW::SequencerFirewireWx::_FrameArrived(), VW::SequencerFirewireGTK::_FrameArrived(), VW::SequencerFileWx::_FrameArrived(), _FrameArrived(), and VW::SequencerBase::_FrameArrived().
The documentation for this class was generated from the following files:
sequencerfilegtk.h
sequencerfilegtk.cpp