VW: VW::ImageRGBPlanes< Type > Class Template Reference
VW::ImageRGBPlanes< Type > Class Template Reference
[Image]
A class for storing an RGB image as seperate R, G and B images.
#include <imagergbplanes.h>
Public Member Functions
ImageRGBPlanes (const int w, const int h)
ImageRGBPlanes (Type *red, Type *green, Type *blue, const int w, const int h)
ImageRGBPlanes ()
~ImageRGBPlanes ()
void AllocImageData (int w, int h)
bool IsAlloced () const
unsigned int GetWidth () const
unsigned int GetHeight () const
bool ReadImage (FILE *file)
bool WriteImage (FILE *file) const
bool ReadImage (const std::string &filename)
bool WriteImage (const std::string &filename) const
Public Attributes
ImageMono< Type > r
ImageMono< Type > g
ImageMono< Type > b
Protected Attributes
bool _alloced
Detailed Description
template<class Type>
class VW::ImageRGBPlanes< Type >
A class for storing an RGB image as seperate R, G and B images.
Author:
ID Reid
Date:
02/08/02
Constructor & Destructor Documentation
template<class Type > ImageRGBPlanes::ImageRGBPlanes (const int w, const int h) [inline]
References VW::ImageRGBPlanes< Type >::AllocImageData().
template<class Type > ImageRGBPlanes::ImageRGBPlanes (Type * red, Type * green, Type * blue, const int w, const int h) [inline]
References VW::ImageRGBPlanes< Type >::b, VW::ImageRGBPlanes< Type >::g, and VW::ImageRGBPlanes< Type >::r.
template<class Type> VW::ImageRGBPlanes< Type >::ImageRGBPlanes () [inline]
template<class Type> VW::ImageRGBPlanes< Type >::~ImageRGBPlanes () [inline]
Member Function Documentation
template<class Type > void ImageRGBPlanes::AllocImageData (int w, int h) [inline]
References VW::ImageRGBPlanes< Type >::_alloced, VW::ImageRGBPlanes< Type >::b, VW::ImageRGBPlanes< Type >::g, and VW::ImageRGBPlanes< Type >::r.
Referenced by VW::ImageRGBPlanes< Type >::ImageRGBPlanes().
template<class Type > unsigned int VW::ImageRGBPlanes< Type >::GetHeight (void) const [inline]
References VW::ImageRGBPlanes< Type >::r.
template<class Type > unsigned int VW::ImageRGBPlanes< Type >::GetWidth (void) const [inline]
References VW::ImageRGBPlanes< Type >::r.
template<class Type > bool VW::ImageRGBPlanes< Type >::IsAlloced (void) const [inline]
References VW::ImageRGBPlanes< Type >::_alloced.
template<class Type > bool ImageRGBPlanes::ReadImage (const std::string & filename) [inline]
References VW::ImageRGBPlanes< Type >::ReadImage().
template<class Type > bool ImageRGBPlanes::ReadImage (FILE * file) [inline]
Referenced by VW::ImageRGBPlanes< Type >::ReadImage().
template<class Type > bool ImageRGBPlanes::WriteImage (const std::string & filename) const [inline]
References VW::ImageRGBPlanes< Type >::WriteImage().
template<class Type > bool ImageRGBPlanes::WriteImage (FILE * file) const [inline]
Referenced by VW::ImageRGBPlanes< Type >::WriteImage().
Member Data Documentation
template<class Type> bool VW::ImageRGBPlanes< Type >::_alloced [protected]
Referenced by VW::ImageRGBPlanes< Type >::AllocImageData(), and VW::ImageRGBPlanes< Type >::IsAlloced().
template<class Type> ImageMono<Type> VW::ImageRGBPlanes< Type >::b
Referenced by VW::ImageRGBPlanes< Type >::AllocImageData(), and VW::ImageRGBPlanes< Type >::ImageRGBPlanes().
template<class Type> ImageMono<Type> VW::ImageRGBPlanes< Type >::g
Referenced by VW::ImageRGBPlanes< Type >::AllocImageData(), and VW::ImageRGBPlanes< Type >::ImageRGBPlanes().
template<class Type> ImageMono<Type> VW::ImageRGBPlanes< Type >::r
Referenced by VW::ImageRGBPlanes< Type >::AllocImageData(), VW::ImageRGBPlanes< Type >::GetHeight(), VW::ImageRGBPlanes< Type >::GetWidth(), and VW::ImageRGBPlanes< Type >::ImageRGBPlanes().
The documentation for this class was generated from the following files:
imagergbplanes.h
imagergbplanes.cpp