VW: VW::AngleAxis Class Reference
VW::AngleAxis Class Reference
[GeometricObjects]
Representation of a 3D rotation as an angle-axis or axial vector.
#include <angleaxis.h>
Public Member Functions
AngleAxis ()
Construct elements individually.
AngleAxis (double x, double y, double z)
Construct elements individually.
AngleAxis (const VW::Vector3D &axis, const double &angle)
Construct from an angle around an axis.
AngleAxis (const VW::Vector3D &angleaxis)
Construct using an angle-axis vector.
AngleAxis (const VW::RotationMatrix &R)
Construct from a rotation matrix.
AngleAxis (const VW::Quaternion &R)
Construct from a rotation matrix.
virtual ~AngleAxis ()
void Set (double x, double y, double z)
Set elements individually.
void Set (const VW::Vector3D &axis, const double &angle)
Set using a rotation axis and angle.
void Set (const VW::Vector3D &angleaxis)
Set using an angle-axis vector.
void Set (const VW::RotationMatrix &R)
Set from a rotation matrix.
void Set (const VW::Quaternion &q)
Set from a quaternion.
double GetX () const
double GetY () const
double GetZ () const
double & X ()
double & Y ()
double & Z ()
const double & X () const
const double & Y () const
const double & Z () const
void Get (double &x, double &y, double &z) const
VW::Vector3D Axis () const
double Angle () const
VW::Quaternion Quaternion () const
VW::RotationMatrix RotationMatrix () const
VW::RotationMatrix RotationMatrixTranspose () const
VW::AngleAxis Inverse () const
VW::Vector3D Rotate (const VW::Vector3D &v) const
Rotate a vector.
VW::LineSeg3D Rotate (const VW::LineSeg3D &l) const
Rotate a line segment.
VW::AngleAxis operator* (const VW::AngleAxis &aa) const
Combine two rotations (this is VERY costly).
VW::AngleAxis operator* (const double scale) const
VW::AngleAxis operator/ (const double scale) const
VW::AngleAxis & operator*= (const double scale)
VW::AngleAxis & operator/= (const double scale)
bool operator== (const VW::AngleAxis &aa) const
Is q1 identitical to this quaternion.
bool operator!= (const VW::AngleAxis &aa) const
Is q1 different from this quaternion.
virtual bool WriteASCII (std::ostream &stream) const
Write space separated data (order is x,y,z,r).
virtual bool WriteXML (std::ostream &stream, const std::string &name="") const
Stream as XML style ASCII.
virtual bool WriteBinary (std::ostream &stream) const
Write binary data (order is x,y,z,r).
virtual bool ReadASCII (std::istream &stream)
Read from an ASCII input stream, from Roll, Pitch, Yaw (ZXY) Euler angles in degrees.
virtual bool ReadXML (std::istream &stream, const std::string &name="")
Stream as XML style ASCII.
virtual bool ReadBinary (std::istream &stream)
Read binary data (order is x,y,z,r).
bool WriteASCIIFile (const std::string &filename) const
Open a file and output as plain ASCII (overwriting any existing contents).
bool WriteXMLFile (const std::string &filename, const std::string &name="") const
Open a file and output as XML-style ASCII (overwriting any existing contents).
bool WriteBinaryFile (const std::string &filename) const
Open a file and output as binary (overwriting any existing contents).
virtual bool ReadASCIIFile (const std::string &filename)
Open a file and input as plain ASCII.
virtual bool ReadXMLFile (const std::string &filename, const std::string &name="")
Open a file and input as XML style ASCII.
virtual bool ReadBinaryFile (const std::string &filename)
Open a file and input as binary.
Protected Attributes
double _x
double _y
double _z
Detailed Description
Representation of a 3D rotation as an angle-axis or axial vector.
Author:
BJ Tordoff
Date:
02/11/2002 Although useful for somethings, angleaxis vectors are the poor mans alternative to using genuine quaternions mainly because the mathematics of products is much less simple (and more computationally costly).
Constructor & Destructor Documentation
VW::AngleAxis::AngleAxis () [inline]
Construct elements individually.
Referenced by operator*().
VW::AngleAxis::AngleAxis (double x, double y, double z) [inline]
Construct elements individually.
VW::AngleAxis::AngleAxis (const VW::Vector3D & axis, const double & angle) [inline]
Construct from an angle around an axis.
References Set().
VW::AngleAxis::AngleAxis (const VW::Vector3D & angleaxis) [inline]
Construct using an angle-axis vector.
References Set().
VW::AngleAxis::AngleAxis (const VW::RotationMatrix & R) [inline]
Construct from a rotation matrix.
References Set().
VW::AngleAxis::AngleAxis (const VW::Quaternion & R) [inline]
Construct from a rotation matrix.
References Set().
virtual VW::AngleAxis::~AngleAxis () [inline, virtual]
Member Function Documentation
double VW::AngleAxis::Angle () const
Returns:
the angle of rotation in radians.
References _x, _y, _z, and std::sqrt().
VW::Vector3D VW::AngleAxis::Axis () const
Returns:
the axis of rotation.
References _x, _y, _z, and std::sqrt().
void VW::AngleAxis::Get (double & x, double & y, double & z) const [inline]
References _x, _y, and _z.
double VW::AngleAxis::GetX () const [inline]
References _x.
Referenced by VW::Quaternion::Set(), and VW::PMatrixCompute::TransformToParamVec().
double VW::AngleAxis::GetY () const [inline]
References _y.
Referenced by VW::Quaternion::Set(), and VW::PMatrixCompute::TransformToParamVec().
double VW::AngleAxis::GetZ () const [inline]
References _z.
Referenced by VW::Quaternion::Set(), and VW::PMatrixCompute::TransformToParamVec().
VW::AngleAxis VW::AngleAxis::Inverse () const [inline]
References _x, _y, and _z.
bool VW::AngleAxis::operator!= (const VW::AngleAxis & aa) const [inline]
Is q1 different from this quaternion.
References _x, _y, and _z.
VW::AngleAxis VW::AngleAxis::operator* (const double scale) const [inline]
VW::AngleAxis VW::AngleAxis::operator* (const VW::AngleAxis & aa) const
Combine two rotations (this is VERY costly).
Parameters:
aa the inner rotation
Returns:
the resulting rotation (like this*q for matrices)
References AngleAxis().
VW::AngleAxis & VW::AngleAxis::operator*= (const double scale) [inline]
References _x, _y, and _z.
VW::AngleAxis VW::AngleAxis::operator/ (const double scale) const [inline]
VW::AngleAxis & VW::AngleAxis::operator/= (const double scale) [inline]
References _x, _y, and _z.
bool VW::AngleAxis::operator== (const VW::AngleAxis & aa) const [inline]
Is q1 identitical to this quaternion.
References _x, _y, and _z.
VW::Quaternion VW::AngleAxis::Quaternion () const
References _x, _y, _z, c, and std::sqrt().
bool VW::AngleAxis::ReadASCII (std::istream & stream) [inline, virtual]
Read from an ASCII input stream, from Roll, Pitch, Yaw (ZXY) Euler angles in degrees.
Implements VW::IOObject.
References _x, _y, and _z.
bool VW::IOObject::ReadASCIIFile (const std::string & filename) [virtual, inherited]
Open a file and input as plain ASCII.
Open a file and read as plain ASCII.
Once the file is open, the child class's ReadASCII function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadASCII().
bool VW::AngleAxis::ReadBinary (std::istream & stream) [inline, virtual]
Read binary data (order is x,y,z,r).
Implements VW::IOObject.
References _x, _y, and _z.
bool VW::IOObject::ReadBinaryFile (const std::string & filename) [virtual, inherited]
Open a file and input as binary.
Open a file and read as binary.
Once the file is open, the child class's ReadBinary function is used to read the content.
Parameters:
filename the name of the file to open
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadBinary().
bool VW::AngleAxis::ReadXML (std::istream & stream, const std::string & name = "") [inline, virtual]
Stream as XML style ASCII.
Parameters:
stream the input stream to read from
name if specified, the found tag must have a NAME= parameter that matches
Returns:
true if successfully read, false if there are problems
Implements VW::IOObject.
References _x, _y, _z, VW::FindXMLBlock(), and VW::GetXMLBlock().
bool VW::IOObject::ReadXMLFile (const std::string & filename, const std::string & name = "") [virtual, inherited]
Open a file and input as XML style ASCII.
Open a file and read as XML-style ASCII.
Once the file is open, the child class's ReadXML function is used to read the content.
Parameters:
filename the name of the file to open
name the optional name tag-attribute to match ie. data must start <MyClass name="name">
Returns:
true for success, false if file cannot be opened or the data isn't read successfully.
References VW::IOObject::ReadXML().
Referenced by VW::ClassifierUV::ClassifierUV(), and VW::FirewireCameraGTK::LoadParameterFile().
VW::LineSeg3D VW::AngleAxis::Rotate (const VW::LineSeg3D & l) const
Rotate a line segment.
Parameters:
l the line segment to be rotated
Returns:
the resulting rotated line segment
References _x, _y, _z, VW::LineSeg3D::EndPoint(), std::sqrt(), VW::LineSeg3D::StartPoint(), and VW::VectorProduct().
VW::Vector3D VW::AngleAxis::Rotate (const VW::Vector3D & v) const
Rotate a vector.
Parameters:
v the vector to be rotated
Returns:
the resulting rotated vector
References _x, _y, _z, std::sqrt(), and VW::VectorProduct().
VW::RotationMatrix VW::AngleAxis::RotationMatrix () const
References _x, _y, _z, c, R, and std::sqrt().
VW::RotationMatrix VW::AngleAxis::RotationMatrixTranspose () const
Returns:
the rotation matrix corresponding to the inverse rotation by this quaternion.
References _x, _y, _z, c, R, and std::sqrt().
void VW::AngleAxis::Set (const VW::Quaternion & q)
Set from a quaternion.
References _x, _y, _z, VW::Quaternion::GetR(), VW::Quaternion::GetX(), VW::Quaternion::GetY(), VW::Quaternion::GetZ(), and std::sqrt().
void VW::AngleAxis::Set (const VW::RotationMatrix & R)
Set from a rotation matrix.
Parameters:
R the rotation matrix from which the quaternion will be extracted
References _x, _y, _z, and std::sqrt().
void VW::AngleAxis::Set (const VW::Vector3D & angleaxis)
Set using an angle-axis vector.
The angle is recovered as \| angleaxis \| = angle and the axis as axis = angleaxis / angle.
Parameters:
angleaxis the 3D vector whose size gives the angle and direction gives the axis
References _x, _y, _z, VW::Point3D::GetX(), VW::Point3D::GetY(), and VW::Point3D::GetZ().
void VW::AngleAxis::Set (const VW::Vector3D & axis, const double & angle)
Set using a rotation axis and angle.
Parameters:
axis the axis (doesn't need to be a unit vector) around which to rotate
angle the rotation angle in radians
References _x, _y, _z, VW::Point3D::GetX(), VW::Point3D::GetY(), and VW::Point3D::GetZ().
void VW::AngleAxis::Set (double x, double y, double z) [inline]
Set elements individually.
References _x, _y, and _z.
Referenced by AngleAxis().
bool VW::AngleAxis::WriteASCII (std::ostream & stream) const [inline, virtual]
Write space separated data (order is x,y,z,r).
Implements VW::IOObject.
References _x, _y, and _z.
bool VW::IOObject::WriteASCIIFile (const std::string & filename) const [inherited]
Open a file and output as plain ASCII (overwriting any existing contents).
Open a file and output as plain ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteASCII function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteASCII().
bool VW::AngleAxis::WriteBinary (std::ostream & stream) const [inline, virtual]
Write binary data (order is x,y,z,r).
Implements VW::IOObject.
References _x, _y, and _z.
bool VW::IOObject::WriteBinaryFile (const std::string & filename) const [inherited]
Open a file and output as binary (overwriting any existing contents).
Once the file is open, the child class's WriteBinary function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteBinary().
bool VW::AngleAxis::WriteXML (std::ostream & stream, const std::string & name = "") const [inline, virtual]
Stream as XML style ASCII.
Parameters:
stream the output stream to write to
name if specified, the class will be given a NAME= parameter
Returns:
true if successfully written, false if there are problems
Implements VW::IOObject.
References _x, _y, and _z.
bool VW::IOObject::WriteXMLFile (const std::string & filename, const std::string & name = "") const [inherited]
Open a file and output as XML-style ASCII (overwriting any existing contents).
Open a file and output as XML-style ASCII (overwriting any existing contents) .
Once the file is open, the child class's WriteXML function is used to create the content.
Parameters:
filename the name of the file to create (or overwrite if it exists)
name the tag parameter, if required
Returns:
true for success, false if file cannot be opened or the data can't be written.
References VW::IOObject::WriteXML().
Referenced by VW::FirewireCameraGTK::SaveParameterFile().
const double & VW::AngleAxis::X () const [inline]
Returns:
a constant reference to the first imaginary part of the quaternion
References _x.
double & VW::AngleAxis::X () [inline]
Returns:
a reference to the first imaginary part of the quaternion
References _x.
const double & VW::AngleAxis::Y () const [inline]
Returns:
a constant reference to the second imaginary part of the quaternion
References _y.
double & VW::AngleAxis::Y () [inline]
Returns:
a reference to the second imaginary part of the quaternion
References _y.
const double & VW::AngleAxis::Z () const [inline]
Returns:
a constant reference to the third imaginary part of the quaternion
References _z.
double & VW::AngleAxis::Z () [inline]
Returns:
a reference to the third imaginary part of the quaternion
References _z.
Member Data Documentation
double VW::AngleAxis::_x [protected]
Referenced by Angle(), Axis(), Get(), GetX(), Inverse(), operator!=(), operator*=(), operator/=(), operator==(), Quaternion(), ReadASCII(), ReadBinary(), ReadXML(), Rotate(), RotationMatrix(), RotationMatrixTranspose(), Set(), WriteASCII(), WriteBinary(), WriteXML(), and X().
double VW::AngleAxis::_y [protected]
Referenced by Angle(), Axis(), Get(), GetY(), Inverse(), operator!=(), operator*=(), operator/=(), operator==(), Quaternion(), ReadASCII(), ReadBinary(), ReadXML(), Rotate(), RotationMatrix(), RotationMatrixTranspose(), Set(), WriteASCII(), WriteBinary(), WriteXML(), and Y().
double VW::AngleAxis::_z [protected]
Referenced by Angle(), Axis(), Get(), GetZ(), Inverse(), operator!=(), operator*=(), operator/=(), operator==(), Quaternion(), ReadASCII(), ReadBinary(), ReadXML(), Rotate(), RotationMatrix(), RotationMatrixTranspose(), Set(), WriteASCII(), WriteBinary(), WriteXML(), and Z().
The documentation for this class was generated from the following files:
angleaxis.h
angleaxis.cpp