VW: VW::ThreePointPose Class Reference
VW::ThreePointPose Class Reference
Compute 3D pose of 3 points given their image projections.
#include <threepointpose.h>
Public Member Functions
ThreePointPose (const Point2D _x1, const Point2D _x2, const Point2D _x3, const Point3D _p1, const Point3D _p2, const Point3D _p3, const CalibrationMatrix K=CalibrationMatrix(1.0, 1.0, 0.0, 0.0, 0.0))
void ComputeFischlerBolles (Point3D j1, Point3D j2, Point3D j3, double a2, double b2, double c2)
void ComputeQRotn ()
void ComputeQRotn (const int i, Quaternion &q, Vector3D &t)
void ComputeFinsterwalder (Point3D j1, Point3D j2, Point3D j3, Point3D p1, Point3D p2, Point3D p3)
void ComputeJacobian (const int soln)
bool ComputeJacobians ()
unsigned int NumSolns () const
void GetAllDepths (std::vector< double > &_s1, std::vector< double > &_s2, std::vector< double > &_s3) const
void GetDepths (int i, double &_s1, double &_s2, double &_s3) const
void GetAllPoints (std::vector< Point3D > &_P1, std::vector< Point3D > &_P2, std::vector< Point3D > &_P3) const
void GetPoints (int i, Point3D &_P1, Point3D &_P2, Point3D &_P3) const
void GetAllPoses (std::vector< Quaternion > &_q, std::vector< Vector3D > &_t) const
void GetPose (int i, Quaternion &_q, Vector3D &_t) const
VNL::MatrixFixed< 6, 7, double > & GetJacobian (const int i)
VNL::MatrixFixed< 7, 7, double > GetCovariance (const int i, VNL::MatrixFixed< 6, 6, double > P)
operator bool ()
Detailed Description
Compute 3D pose of 3 points given their image projections.
Author:
ID Reid
Date:
30/11/04 Determine the depths, locations and pose of three points given their image projections. Uses the 3-point method of Fischler and Bolles (which involves solving a degree-4 polynomial) to obtain possible depths of points. These depths lead directly to point locations, and can be used to determine the pose of the three points relative to an alternative coordinate frane using the method of Faugeras to solve for a quaternion rotation
Author:
ID Reid
Date:
30/11/04 Determine the depths, locations and pose of three points given their image projections. Uses the 3-point method of Fischler and Bolles (which involves solving a degree-4 polynomial) to obtain possible depths of points. These depths lead directly to point locations, and can be used to determine the pose of the three points relative to an alternative coordinate frame using the method of Faugeras to solve for a quaternion rotation
Optional computation of Jacobian. Done numerically via pertubations.
Constructor & Destructor Documentation
ThreePointPose::ThreePointPose (const Point2D _x1, const Point2D _x2, const Point2D _x3, const Point3D _p1, const Point3D _p2, const Point3D _p3, const CalibrationMatrix K = CalibrationMatrix(1.0,1.0, 0.0, 0.0, 0.0))
References ComputeFischlerBolles(), ComputeQRotn(), VW::Point2D::GetX(), VW::Point2D::GetY(), VW::CalibrationMatrix::Inverse(), VW::Point3D::Normalise(), and NumSolns().
Member Function Documentation
void ThreePointPose::ComputeFinsterwalder (Point3D j1, Point3D j2, Point3D j3, Point3D p1, Point3D p2, Point3D p3)
References VNL::RPolyRoots::RealRoots(), std::sqrt(), and v.
void ThreePointPose::ComputeFischlerBolles (Point3D j1, Point3D j2, Point3D j3, double a2, double b2, double c2)
References DEBUG, VNL::RPolyRoots::Imag(), VNL::RPolyRoots::Real(), REAL_THRESH, std::sqrt(), and v.
Referenced by ComputeJacobian(), ComputeJacobians(), and ThreePointPose().
void ThreePointPose::ComputeJacobian (const int soln)
References ComputeFischlerBolles(), ComputeQRotn(), DEBUG, VW::Point3D::GetX(), VW::Point2D::GetX(), VW::Point3D::GetY(), VW::Point2D::GetY(), VW::Point3D::GetZ(), VW::CalibrationMatrix::Inverse(), VW::Point3D::Normalise(), and NumSolns().
Referenced by GetCovariance(), and GetJacobian().
bool ThreePointPose::ComputeJacobians ()
References ComputeFischlerBolles(), ComputeQRotn(), VW::Point2D::GetX(), VW::Point2D::GetY(), VW::CalibrationMatrix::Inverse(), VW::Point3D::Normalise(), and NumSolns().
void ThreePointPose::ComputeQRotn (const int i, Quaternion & q, Vector3D & t)
References VW::Quaternion::Conjugate(), DEBUG, VNL::SymmetricEigensystem< T >::GetEigenvalue(), VNL::SymmetricEigensystem< T >::GetEigenvector(), VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), m, VW::Quaternion::Rotate(), VW::Quaternion::Set(), and v.
void ThreePointPose::ComputeQRotn ()
References DEBUG, VNL::SymmetricEigensystem< T >::GetEigenvalue(), VNL::SymmetricEigensystem< T >::GetEigenvector(), VW::Point3D::GetX(), VW::Point3D::GetY(), VW::Point3D::GetZ(), m, and v.
Referenced by ComputeJacobian(), ComputeJacobians(), and ThreePointPose().
void VW::ThreePointPose::GetAllDepths (std::vector< double > & _s1, std::vector< double > & _s2, std::vector< double > & _s3) const [inline]
void VW::ThreePointPose::GetAllPoints (std::vector< Point3D > & _P1, std::vector< Point3D > & _P2, std::vector< Point3D > & _P3) const [inline]
void VW::ThreePointPose::GetAllPoses (std::vector< Quaternion > & _q, std::vector< Vector3D > & _t) const [inline]
VNL::MatrixFixed<7,7,double> VW::ThreePointPose::GetCovariance (const int i, VNL::MatrixFixed< 6, 6, double > P) [inline]
References ComputeJacobian().
void VW::ThreePointPose::GetDepths (int i, double & _s1, double & _s2, double & _s3) const [inline]
VNL::MatrixFixed<6,7,double>& VW::ThreePointPose::GetJacobian (const int i) [inline]
References ComputeJacobian().
void VW::ThreePointPose::GetPoints (int i, Point3D & _P1, Point3D & _P2, Point3D & _P3) const [inline]
void VW::ThreePointPose::GetPose (int i, Quaternion & _q, Vector3D & _t) const [inline]
unsigned int VW::ThreePointPose::NumSolns () const [inline]
Referenced by ComputeJacobian(), ComputeJacobians(), and ThreePointPose().
VW::ThreePointPose::operator bool () [inline]
The documentation for this class was generated from the following files:
threepointpose.h
threepointpose.cpp