VW: VW::IntegralImage< DataType > Class Template Reference
VW::IntegralImage< DataType > Class Template Reference
[ImageProcessing]
Implementation of integral image as described in Viola's CVPR2001 paper on face detection via boosting.
#include <integralimage.h>
Public Member Functions
IntegralImage ()
~IntegralImage ()
template<class InType >
IntegralImage (const ImageMono< InType > &im)
Construct and compute from source image im.
template<class InType >
IntegralImage (const ImageYUV< InType > &im)
Construct and compute from the Y channel of source image im.
template<class InType >
IntegralImage (const ImageYUV< InType > &im, const ROI &roi)
Construct and compute from the Y channel of source image im in the region specified by ROI.
template<class InType >
void Compute (const ImageMono< InType > &im)
Compute the integral image from source image im.
template<class InType >
void Compute (const ImageYUV< InType > &im)
Compute the integral image from the Y channel of source image im.
template<class InType >
void Compute (const ImageYUV< InType > &im, const ROI &roi)
Compute the integral image from the Y channel of source image im in the region specified by ROI.
DataType GetRegionSum (int x0, int y0, int x1, int y1) const
Compute the sum over a region (x0,y0)-(x1,y1) inclusive.
unsigned int GetWidth () const
unsigned int GetHeight () const
DataType * operator[] (int row)
Get a pointer to the start of a row.
operator bool () const
Detailed Description
template<class DataType>
class VW::IntegralImage< DataType >
Implementation of integral image as described in Viola's CVPR2001 paper on face detection via boosting.
Author:
ID Reid
Date:
06/08/2002 The class is templated on the internal storage type, which should be at least as big as the data-type of the image being integrated. Usually you should maintain signed-ness, such as: Image Type Integral Image Type "unsigned char" -> "unsigned int" or "long unsigned int" "char" -> "int" or "long int" "unsigned int" -> "long unsigned int" "int" -> "long int" "float" -> "float" or "double" "double" -> "double" or "long double"
Constructor & Destructor Documentation
template<class DataType> VW::IntegralImage< DataType >::IntegralImage () [inline]
template<class DataType > VW::IntegralImage< DataType >::~IntegralImage () [inline]
template<class DataType > template<class InType > VW::IntegralImage< DataType >::IntegralImage (const ImageMono< InType > & im) [inline]
Construct and compute from source image im.
References VW::IntegralImage< DataType >::Compute().
template<class DataType> template<class InType > VW::IntegralImage< DataType >::IntegralImage (const ImageYUV< InType > & im) [inline]
Construct and compute from the Y channel of source image im.
template<class DataType > template<class InType > VW::IntegralImage< DataType >::IntegralImage (const ImageYUV< InType > & im, const ROI & roi) [inline]
Construct and compute from the Y channel of source image im in the region specified by ROI.
References VW::IntegralImage< DataType >::Compute().
Member Function Documentation
template<class DataType > template<class InType > void IntegralImage::Compute (const ImageYUV< InType > & im, const ROI & roi) [inline]
Compute the integral image from the Y channel of source image im in the region specified by ROI.
References VW::ROI::Get(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetHeight(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetRowStart(), VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::GetWidth(), and VW::PixelYUV< Type >::y.
template<class DataType > template<class InType > void VW::IntegralImage< DataType >::Compute (const ImageYUV< InType > & im) [inline]
Compute the integral image from the Y channel of source image im.
References VW::IntegralImage< DataType >::Compute(), and VW::ImageBase< PixelYUV< Type >, PixelYUV< Type > * >::ROI().
template<class DataType > template<class InType > void IntegralImage::Compute (const ImageMono< InType > & im) [inline]
Compute the integral image from source image im.
References VW::ROI::Get(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetHeight(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetROIRowStart(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::GetWidth(), VW::ImageBase< PixelMono< Type >, PixelMono< Type > * >::ROI(), and VW::PixelMono< Type >::y.
Referenced by VW::IntegralImage< DataType >::Compute(), and VW::IntegralImage< DataType >::IntegralImage().
template<class DataType > unsigned int VW::IntegralImage< DataType >::GetHeight (void) const [inline]
template<class DataType > DataType VW::IntegralImage< DataType >::GetRegionSum (int x0, int y0, int x1, int y1) const [inline]
Compute the sum over a region (x0,y0)-(x1,y1) inclusive.
Referenced by VW::Correlate::Compute().
template<class DataType > unsigned int VW::IntegralImage< DataType >::GetWidth (void) const [inline]
template<class DataType > VW::IntegralImage< DataType >::operator bool () const [inline]
template<class DataType > DataType * VW::IntegralImage< DataType >::operator[] (int row) [inline]
Get a pointer to the start of a row.
Note that the -1th row and column are zeros to make the region-summing faster, so to skip a row, add GetWidth()+1.
The documentation for this class was generated from the following files:
integralimage.h
integralimage.cpp