VW: VNL::GeneralizedEigensystem Class Reference
VNL::GeneralizedEigensystem Class Reference
Solves the generalized eigenproblem Ax=Bx.
#include <generalizedeigensystem.h>
Public Member Functions
GeneralizedEigensystem (const VNL::Matrix< double > &A, const VNL::Matrix< double > &B)
Solves the generalized eigenproblem Ax=Bx.
Public Attributes
int n
VNL::Matrix< double > V
Public eigenvectors.
VNL::DiagMatrix< double > D
Public eigenvalues.
Detailed Description
Solves the generalized eigenproblem Ax=Bx.
Solves the generalized eigenproblem of , with symmetric and positive definite.
See Golub and van Loan, Section 8.7.
Constructor & Destructor Documentation
VNL::GeneralizedEigensystem::GeneralizedEigensystem (const VNL::Matrix< double > & A, const VNL::Matrix< double > & B)
Solves the generalized eigenproblem Ax=Bx.
Solve real generalized eigensystem for and , where symmetric, positive definite. Initializes storage for the matrix and the VNL::DiagMatrix . The eigenvalues are sorted into increasing order (of value, not absolute value).
Uses vnl_cholesky decomposition , to convert to and then uses the symmetric eigensystem code. It will print a verbose warning if is not positive definite.
References VNL::Vector< T >::begin(), c, VNL::SymmetricEigensystem< T >::D, D, VNL::DiagMatrix< T >::DataBlock(), VNL::Matrix< T >::GetNColumns(), VNL::MatlabPrint(), n, rsg_(), VNL::Matrix< T >::Transpose(), VNL::Matrix< T >::Update(), V, and VNL::SymmetricEigensystem< T >::V.
Member Data Documentation
VNL::DiagMatrix<double> VNL::GeneralizedEigensystem::D
Public eigenvalues.
After construction, this contains the diagonal matrix of eigenvalues, stored as a vector.
Referenced by GeneralizedEigensystem().
int VNL::GeneralizedEigensystem::n
Referenced by GeneralizedEigensystem().
VNL::Matrix<double> VNL::GeneralizedEigensystem::V
Public eigenvectors.
After construction, this contains the matrix of eigenvectors.
Referenced by GeneralizedEigensystem().
The documentation for this class was generated from the following files:
generalizedeigensystem.h
generalizedeigensystem.cpp