VW: complexops.tpp File Reference
complexops.tpp File Reference
#include "complexify.h"
#include "real.h"
#include "imag.h"
#include <assert.h>
#include <cmath>
Defines
#define VNL_COMPLEX_OPS_INSTANTIATE(T)
Functions
template<class T >
void vnl_complexify (T const *src, std::complex< T > *dst, unsigned n)
template<class T >
void vnl_complexify (T const *re, T const *im, std::complex< T > *dst, unsigned n)
template<class T >
VNL::Vector< std::complex< T > > vnl_complexify (VNL::Vector< T > const &v)
template<class T >
VNL::Vector< std::complex< T > > vnl_complexify (VNL::Vector< T > const &re, VNL::Vector< T > const &im)
template<class T >
VNL::Matrix< std::complex< T > > vnl_complexify (VNL::Matrix< T > const &M)
template<class T >
VNL::Matrix< std::complex< T > > vnl_complexify (VNL::Matrix< T > const &re, VNL::Matrix< T > const &im)
template<class T >
void vnl_real (std::complex< T > const *C, T *R, unsigned int n)
Return array of real parts of complex array.
template<class T >
VNL::Vector< T > vnl_real (VNL::Vector< std::complex< T > > const &C)
Vector of real parts of VNL::Vector<std::complex<T> >.
template<class T >
VNL::Matrix< T > vnl_real (VNL::Matrix< std::complex< T > > const &C)
Matrix of real parts of VNL::Matrix<std::complex<T> >.
template<class T >
void vnl_imag (std::complex< T > const *C, T *I, unsigned int n)
Return array of imaginary parts of complex array.
template<class T >
VNL::Vector< T > vnl_imag (VNL::Vector< std::complex< T > > const &C)
Vector of imaginary parts of VNL::Vector<std::complex<T> >.
template<class T >
VNL::Matrix< T > vnl_imag (VNL::Matrix< std::complex< T > > const &C)
Matrix of imaginary parts of VNL::Matrix<std::complex<T> >.
Detailed Description
Author:
fsm@robots.ox.ac.uk This is the implementation file for the following three header files: vnl_complexify.h vnl_real.h vnl_complex.h
Define Documentation
#define VNL_COMPLEX_OPS_INSTANTIATE (T)
Value:
template void vnl_complexify(T const *, std::complex<T > *, unsigned); \
template void vnl_complexify(T const *, T const *, std::complex<T > *, unsigned); \
\
template VNL::Vector<std::complex<T > > vnl_complexify(VNL::Vector<T > const &); \
template VNL::Vector<std::complex<T > > vnl_complexify(VNL::Vector<T > const &, VNL::Vector<T > const &); \
template VNL::Matrix<std::complex<T > > vnl_complexify(VNL::Matrix<T > const &); \
template VNL::Matrix<std::complex<T > > vnl_complexify(VNL::Matrix<T > const &, VNL::Matrix<T > const &); \
\
template void vnl_real(std::complex<T > const*, T*, unsigned int); \
template void vnl_imag(std::complex<T > const*, T*, unsigned int); \
\
template VNL::Vector<T > vnl_real(VNL::Vector<std::complex<T > > const&); \
template VNL::Vector<T > vnl_imag(VNL::Vector<std::complex<T > > const&); \
\
template VNL::Matrix<T > vnl_real(VNL::Matrix<std::complex<T > > const&); \
template VNL::Matrix<T > vnl_imag(VNL::Matrix<std::complex<T > > const&)
Function Documentation
template<class T > VNL::Matrix<std::complex<T> > vnl_complexify (VNL::Matrix< T > const & re, VNL::Matrix< T > const & im) [inline]
References VNL::Matrix< T >::begin(), VNL::Matrix< T >::Columns(), VNL::Matrix< T >::Rows(), VNL::Matrix< T >::size(), and vnl_complexify().
template<class T > VNL::Matrix<std::complex<T> > vnl_complexify (VNL::Matrix< T > const & M) [inline]
References VNL::Matrix< T >::begin(), VNL::Matrix< T >::Columns(), VNL::Matrix< T >::Rows(), VNL::Matrix< T >::size(), and vnl_complexify().
template<class T > VNL::Vector<std::complex<T> > vnl_complexify (VNL::Vector< T > const & re, VNL::Vector< T > const & im) [inline]
References VNL::Vector< T >::begin(), VNL::Vector< T >::size(), and vnl_complexify().
template<class T > VNL::Vector<std::complex<T> > vnl_complexify (VNL::Vector< T > const & v) [inline]
References VNL::Vector< T >::begin(), VNL::Vector< T >::size(), and vnl_complexify().
template<class T > void vnl_complexify (T const * re, T const * im, std::complex< T > * dst, unsigned n) [inline]
template<class T > void vnl_complexify (T const * src, std::complex< T > * dst, unsigned n) [inline]
Referenced by vnl_complexify().
template<class T > VNL::Matrix<T> vnl_imag (VNL::Matrix< std::complex< T > > const & C) [inline]
Matrix of imaginary parts of VNL::Matrix<std::complex<T> >.
Matrix of imaginary parts of vnl_matrix<std::complex<T> >.
template<class T > VNL::Vector<T> vnl_imag (VNL::Vector< std::complex< T > > const & C) [inline]
Vector of imaginary parts of VNL::Vector<std::complex<T> >.
Vector of imaginary parts of vnl_vector<std::complex<T> >.
template<class T > void vnl_imag (std::complex< T > const * C, T * I, unsigned int n) [inline]
Return array of imaginary parts of complex array.
Return array I of imaginary parts of complex array C.
template<class T > VNL::Matrix<T> vnl_real (VNL::Matrix< std::complex< T > > const & C) [inline]
Matrix of real parts of VNL::Matrix<std::complex<T> >.
Matrix of real parts of vnl_matrix<std::complex<T> >.
template<class T > VNL::Vector<T> vnl_real (VNL::Vector< std::complex< T > > const & C) [inline]
Vector of real parts of VNL::Vector<std::complex<T> >.
Vector of real parts of vnl_vector<std::complex<T> >.
template<class T > void vnl_real (std::complex< T > const * C, T * R, unsigned int n) [inline]
Return array of real parts of complex array.
Return array R of real parts of complex array C.