VW: cvector.tpp File Reference
cvector.tpp File Reference
#include "cvector.h"
#include <cmath>
#include <VNL/vnlmath.h>
#include <VNL/complextraits.h>
#include <VNL/numerictraits.h>
#include "config.h"
#include <new>
Defines
#define impl_elmt_wise_commutative(op)
#define impl_elmt_wise_non_commutative(op)
#define impl_elmt_wise_commutative_a(op)
#define impl_elmt_wise_non_commutative_a(op)
#define VNL_C_VECTOR_USE_VNL_ALLOC 0
#define VNL_C_VECTOR_INSTANTIATE_norm(T, S)
#define VNL_C_VECTOR_INSTANTIATE_ordered(T)
#define VNL_C_VECTOR_INSTANTIATE_unordered(T)
#define VNL_C_VECTOR_INSTANTIATE(T) extern "no such macro"
Functions
void * vnl_c_vector_alloc (int n, int size)
void vnl_c_vector_dealloc (void *v, int n, int size)
template<class T >
void vnl_c_vector_construct (T *p, int n)
void vnl_c_vector_construct (float *, int)
void vnl_c_vector_construct (double *, int)
void vnl_c_vector_construct (long double *, int)
void vnl_c_vector_construct (std::complex< float > *, int)
void vnl_c_vector_construct (std::complex< double > *, int)
void vnl_c_vector_construct (std::complex< long double > *, int)
template<class T >
void vnl_c_vector_destruct (T *p, int n)
void vnl_c_vector_destruct (float *, int)
void vnl_c_vector_destruct (double *, int)
void vnl_c_vector_destruct (long double *, int)
void vnl_c_vector_destruct (std::complex< float > *, int)
void vnl_c_vector_destruct (std::complex< double > *, int)
void vnl_c_vector_destruct (std::complex< long double > *, int)
Detailed Description
Author:
Andrew W. Fitzgibbon, Oxford RRG
Date:
12 Feb 98
Define Documentation
#define impl_elmt_wise_commutative (op)
Value:
if (z == x) \
    for (unsigned i=0; i<n; ++i) \
      z[i] op##= y[i]; \
\
  else if (z == y) \
    for (unsigned i=0; i<n; ++i) \
      z[i] op##= x[i]; \
\
  else \
    for (unsigned i=0; i<n; ++i) \
      z[i] = x[i] op y[i];
Referenced by VNL::CVector< T >::Add(), and VNL::CVector< T >::Multiply().
#define impl_elmt_wise_commutative_a (op)
Value:
if (z == x) \
    for (unsigned i=0; i<n; ++i) \
      z[i] op##= y; \
\
  else \
    for (unsigned i=0; i<n; ++i) \
      z[i] = x[i] op y;
Referenced by VNL::CVector< T >::Add(), VNL::CVector< T >::Divide(), VNL::CVector< T >::Multiply(), and VNL::CVector< T >::Subtract().
#define impl_elmt_wise_non_commutative (op)
Value:
if (z == x) \
    for (unsigned i=0; i<n; ++i) \
      z[i] op##= y[i]; \
\
  else \
    for (unsigned i=0; i<n; ++i) \
      z[i] = x[i] op y[i];
Referenced by VNL::CVector< T >::Divide(), and VNL::CVector< T >::Subtract().
#define impl_elmt_wise_non_commutative_a (op)
Value:
if (z == x) \
    for (unsigned i=0; i<n; ++i) \
      z[i] op##= y; \
\
  else \
    for (unsigned i=0; i<n; ++i) \
      z[i] = x[i] op y;
#define VNL_C_VECTOR_INSTANTIATE (T) extern "no such macro"
#define VNL_C_VECTOR_INSTANTIATE_norm (T, S)
Value:
namespace VNL {\
template void CVectorTwoNormSquared(T const *, unsigned, S *); \
template void CVectorRMSNorm(T const *, unsigned, S *); \
template void CVectorOneNorm(T const *, unsigned, S *); \
template void CVectorTwoNorm(T const *, unsigned, S *); \
template void CVectorInfNorm(T const *, unsigned, S *); \
}
#define VNL_C_VECTOR_INSTANTIATE_ordered (T)
Value:
VNL_C_VECTOR_INSTANTIATE_norm(T, VNL::CVector<T >::abs_t); \
namespace VNL {template class CVector<T >;};
#define VNL_C_VECTOR_INSTANTIATE_unordered (T)
Value:
namespace VNL {\
template <> T CVector<T >::MaxValue(T const *, unsigned) {return T(0);}; \
template <> T CVector<T >::MinValue(T const *, unsigned) {return T(0);}; \
};\
VNL_C_VECTOR_INSTANTIATE_norm(T, VNL::CVector<T >::abs_t); \
namespace VNL {template class CVector<T >;};
#define VNL_C_VECTOR_USE_VNL_ALLOC 0
Function Documentation
void* vnl_c_vector_alloc (int n, int size) [inline]
References vnl_alloc::allocate().
Referenced by VNL::CVector< T >::AllocateT(), and VNL::CVector< T >::AllocateTptr().
void vnl_c_vector_construct (std::complex< long double > * , int) [inline]
void vnl_c_vector_construct (std::complex< double > * , int) [inline]
void vnl_c_vector_construct (std::complex< float > * , int) [inline]
void vnl_c_vector_construct (long double * , int) [inline]
void vnl_c_vector_construct (double * , int) [inline]
void vnl_c_vector_construct (float * , int) [inline]
template<class T > void vnl_c_vector_construct (T * p, int n) [inline]
Referenced by VNL::CVector< T >::AllocateT().
void vnl_c_vector_dealloc (void * v, int n, int size) [inline]
References vnl_alloc::deallocate().
Referenced by VNL::CVector< T >::Deallocate().
void vnl_c_vector_destruct (std::complex< long double > * , int) [inline]
void vnl_c_vector_destruct (std::complex< double > * , int) [inline]
void vnl_c_vector_destruct (std::complex< float > * , int) [inline]
void vnl_c_vector_destruct (long double * , int) [inline]
void vnl_c_vector_destruct (double * , int) [inline]
void vnl_c_vector_destruct (float * , int) [inline]
template<class T > void vnl_c_vector_destruct (T * p, int n) [inline]
Referenced by VNL::CVector< T >::Deallocate().