VW: discretediff.cpp File Reference
discretediff.cpp File Reference
#include "discretediff.h"
#include <VNL/leastsquaresfunction.h>
#include <assert.h>
#include <iostream>
Functions
bool vnl_discrete_diff_fwd (VNL::LeastSquaresFunction *lsf, double h_, VNL::Vector< double > const &x, VNL::Matrix< double > &J)
forward differences.
bool vnl_discrete_diff_fwd (VNL::LeastSquaresFunction *lsf, VNL::Vector< double > const &h, VNL::Vector< double > const &x, VNL::Matrix< double > &J)
forward differences.
bool vnl_discrete_diff_fwd (VNL::LeastSquaresFunction *lsf, VNL::Vector< double > const &h, VNL::Vector< double > const &x, VNL::Vector< double > const &y, VNL::Matrix< double > &J)
forward differences.
bool vnl_discrete_diff_sym (VNL::LeastSquaresFunction *lsf, double h_, VNL::Vector< double > const &x, VNL::Matrix< double > &J)
symmetric differences.
bool vnl_discrete_diff_sym (VNL::LeastSquaresFunction *lsf, VNL::Vector< double > const &h, VNL::Vector< double > const &x, VNL::Matrix< double > &J)
symmetric differences.
void vnl_discrete_diff_test_lsf (VNL::LeastSquaresFunction *lsf, VNL::Vector< double > const &x)
Function Documentation
bool vnl_discrete_diff_fwd (VNL::LeastSquaresFunction * lsf, VNL::Vector< double > const & h, VNL::Vector< double > const & x, VNL::Vector< double > const & y, VNL::Matrix< double > & J)
forward differences.
References VNL::Matrix< T >::Columns(), VNL::LeastSquaresFunction::F(), VNL::LeastSquaresFunction::failure, VNL::LeastSquaresFunction::GetNumberOfResiduals(), VNL::LeastSquaresFunction::GetNumberOfUnknowns(), m, VNL::Matrix< T >::Rows(), and VNL::Vector< T >::size().
bool vnl_discrete_diff_fwd (VNL::LeastSquaresFunction * lsf, VNL::Vector< double > const & h, VNL::Vector< double > const & x, VNL::Matrix< double > & J)
forward differences.
References VNL::LeastSquaresFunction::F(), VNL::LeastSquaresFunction::failure, VNL::LeastSquaresFunction::GetNumberOfResiduals(), and vnl_discrete_diff_fwd().
bool vnl_discrete_diff_fwd (VNL::LeastSquaresFunction * lsf, double h_, VNL::Vector< double > const & x, VNL::Matrix< double > & J)
forward differences.
References VNL::LeastSquaresFunction::F(), VNL::LeastSquaresFunction::failure, VNL::LeastSquaresFunction::GetNumberOfResiduals(), VNL::LeastSquaresFunction::GetNumberOfUnknowns(), and vnl_discrete_diff_fwd().
Referenced by vnl_discrete_diff_fwd().
bool vnl_discrete_diff_sym (VNL::LeastSquaresFunction * lsf, VNL::Vector< double > const & h, VNL::Vector< double > const & x, VNL::Matrix< double > & J)
symmetric differences.
References VNL::Matrix< T >::Columns(), VNL::LeastSquaresFunction::F(), VNL::LeastSquaresFunction::failure, VNL::LeastSquaresFunction::GetNumberOfResiduals(), VNL::LeastSquaresFunction::GetNumberOfUnknowns(), m, VNL::Matrix< T >::Rows(), and VNL::Vector< T >::size().
bool vnl_discrete_diff_sym (VNL::LeastSquaresFunction * lsf, double h_, VNL::Vector< double > const & x, VNL::Matrix< double > & J)
symmetric differences.
References VNL::LeastSquaresFunction::GetNumberOfUnknowns(), and vnl_discrete_diff_sym().
Referenced by vnl_discrete_diff_sym(), and vnl_discrete_diff_test_lsf().
void vnl_discrete_diff_test_lsf (VNL::LeastSquaresFunction * lsf, VNL::Vector< double > const & x)
References VNL::CosAngle(), VNL::LeastSquaresFunction::GetNumberOfResiduals(), VNL::LeastSquaresFunction::GetNumberOfUnknowns(), VNL::LeastSquaresFunction::GradF(), m, VNL::Vector< T >::size(), and vnl_discrete_diff_sym().