VW: discretediff.h File Reference
discretediff.h File Reference
Functions to compute jacobians of vnl_least_squares_functions.
#include <VNL/vector.h>
#include <VNL/matrix.h>
Namespaces
namespace VNL
call this to initialize the format stack.
Functions
bool vnl_discrete_diff_fwd (VNL::LeastSquaresFunction *lsf, double h, VNL::Vector< double > const &x, VNL::Matrix< double > &J)
forward differences.
bool vnl_discrete_diff_fwd (VNL::LeastSquaresFunction *lsf, VNL::Vector< double > const &h, VNL::Vector< double > const &x, VNL::Matrix< double > &J)
forward differences.
bool vnl_discrete_diff_fwd (VNL::LeastSquaresFunction *lsf, VNL::Vector< double > const &h, VNL::Vector< double > const &x, VNL::Vector< double > const &y, VNL::Matrix< double > &J)
forward differences.
bool vnl_discrete_diff_sym (VNL::LeastSquaresFunction *lsf, double h, VNL::Vector< double > const &x, VNL::Matrix< double > &J)
symmetric differences.
bool vnl_discrete_diff_sym (VNL::LeastSquaresFunction *lsf, VNL::Vector< double > const &h, VNL::Vector< double > const &x, VNL::Matrix< double > &J)
symmetric differences.
void vnl_discrete_diff_test_lsf (VNL::LeastSquaresFunction *lsf, VNL::Vector< double > const &x)
Detailed Description
Functions to compute jacobians of vnl_least_squares_functions.
Functions to compute jacobians of vnl_least_squares_functions by discrete differences. They return false on failure and true on success.
   name size    description
   lsf  ---     the function.
   h    1 or n  step size (scalar or a vector).
   x    n       point at which to evaluate the derivative of the function.
   y    m       value of the function at x.
   J    mxn     jacobian of the function at x.
Author:
fsm@robots.ox.ac.uk
   Modifications
    dac (Manchester) 28/03/2001: tidied up documentation
    Peter Vanroose   27/05/2001: Corrected documentation
Function Documentation
bool vnl_discrete_diff_fwd (VNL::LeastSquaresFunction * lsf, VNL::Vector< double > const & h, VNL::Vector< double > const & x, VNL::Vector< double > const & y, VNL::Matrix< double > & J)
forward differences.
References VNL::Matrix< T >::Columns(), VNL::LeastSquaresFunction::F(), VNL::LeastSquaresFunction::failure, VNL::LeastSquaresFunction::GetNumberOfResiduals(), VNL::LeastSquaresFunction::GetNumberOfUnknowns(), m, VNL::Matrix< T >::Rows(), and VNL::Vector< T >::size().
bool vnl_discrete_diff_fwd (VNL::LeastSquaresFunction * lsf, VNL::Vector< double > const & h, VNL::Vector< double > const & x, VNL::Matrix< double > & J)
forward differences.
References VNL::LeastSquaresFunction::F(), VNL::LeastSquaresFunction::failure, VNL::LeastSquaresFunction::GetNumberOfResiduals(), and vnl_discrete_diff_fwd().
bool vnl_discrete_diff_fwd (VNL::LeastSquaresFunction * lsf, double h, VNL::Vector< double > const & x, VNL::Matrix< double > & J)
forward differences.
References VNL::LeastSquaresFunction::F(), VNL::LeastSquaresFunction::failure, VNL::LeastSquaresFunction::GetNumberOfResiduals(), VNL::LeastSquaresFunction::GetNumberOfUnknowns(), and vnl_discrete_diff_fwd().
Referenced by vnl_discrete_diff_fwd().
bool vnl_discrete_diff_sym (VNL::LeastSquaresFunction * lsf, VNL::Vector< double > const & h, VNL::Vector< double > const & x, VNL::Matrix< double > & J)
symmetric differences.
References VNL::Matrix< T >::Columns(), VNL::LeastSquaresFunction::F(), VNL::LeastSquaresFunction::failure, VNL::LeastSquaresFunction::GetNumberOfResiduals(), VNL::LeastSquaresFunction::GetNumberOfUnknowns(), m, VNL::Matrix< T >::Rows(), and VNL::Vector< T >::size().
bool vnl_discrete_diff_sym (VNL::LeastSquaresFunction * lsf, double h, VNL::Vector< double > const & x, VNL::Matrix< double > & J)
symmetric differences.
References VNL::LeastSquaresFunction::GetNumberOfUnknowns(), and vnl_discrete_diff_sym().
Referenced by vnl_discrete_diff_sym(), and vnl_discrete_diff_test_lsf().
void vnl_discrete_diff_test_lsf (VNL::LeastSquaresFunction * lsf, VNL::Vector< double > const & x)
References VNL::CosAngle(), VNL::LeastSquaresFunction::GetNumberOfResiduals(), VNL::LeastSquaresFunction::GetNumberOfUnknowns(), VNL::LeastSquaresFunction::GradF(), m, VNL::Vector< T >::size(), and vnl_discrete_diff_sym().