VW: fmatrixcompute7point.cpp File Reference
fmatrixcompute7point.cpp File Reference
#include <VNL/Algo/rpolyroots.h>
#include <VNL/Algo/determinant.h>
#include <VNL/Algo/adjugate.h>
#include <VNL/Algo/svd.h>
#include <VW/GeomObjects/point2d.h>
#include <VW/GeomObjects/fmatrix.h>
#include <VW/GeomObjects/normalisation.h>
#include "fmatrixcompute7point.h"
Defines
#define VERBOSE false
Typedefs
typedef VNL::MatrixFixed
< 7, 9, double > Matrix7x9
Functions
void FillDesignMatrix (const VW::Point2D &x0, const VW::Point2D &x1, const unsigned int index, Matrix7x9 &D)
Detailed Description
Author:
JGH Knight
Date:
02/08/2002
(c) Copyright University of Oxford
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
Define Documentation
#define VERBOSE false
Typedef Documentation
typedef VNL::MatrixFixed<7,9,double> Matrix7x9
Function Documentation
void FillDesignMatrix (const VW::Point2D & x0, const VW::Point2D & x1, const unsigned int index, Matrix7x9 & D)
References VW::Point2D::GetX(), and VW::Point2D::GetY().
Referenced by VW::FMatrixCompute::Linear7Point().