VW: GLTools
GLTools
Tools for creating and manipulating 3D displays and some draw functions for some physical objects.
Classes
class VW::ThreeDToolGLCommon
A base class for doing 3D drawing in VW.
class VW::ThreeDToolGLUT
A version of the ThreeDToolGLWidget which uses GLUT to open a window and handle events.
class VW::ThreeDToolGluteWidget
A version of the ThreeDTool which can be embedded in a glute GUI.
class VW::ThreeDToolGTKGLWidget
A version of the ThreeDToolGLWidget which is also a GTK widget, and can be embedded in a GTK interface.
class VW::ThreeDToolWxGLWidget
A version of the ThreeDToolGLWidget for embedding in WxWidgets apps.
Functions
void VW::DrawFireI (VW::ThreeDToolGLCommon &display, const VW::Vector3D &position, const VW::Quaternion &orientation)
Draw a model of the Unibrain Fire-I camera.
void VW::DrawGTI (VW::ThreeDToolGLCommon &display, const VW::Vector3D &position, const VW::Quaternion &orientation)
Draw a model of the GTI mobile robot.
void VW::DrawGTIWithYorick (VW::ThreeDToolGLCommon &display, const VW::Vector3D &position, const VW::Quaternion &orientation, const double yorickpan=0, const double yoricktilt=0, const double yorickvergeleft=0, const double yorickvergeright=0, const std::string &yorickcameratype="VL500")
Draw a model of the GTI mobile robot.
void VW::DrawThreeQuarterDesk (VW::ThreeDToolGLCommon &display, const VW::Vector3D &position, const VW::Quaternion &orientation, bool origin_on_desk=true)
Draw a model of a three-quarter corner desk.
void VW::DrawVL500 (VW::ThreeDToolGLCommon &display, const VW::Vector3D &position, const VW::Quaternion &orientation, bool origin_is_optic_centre=true)
Draw a model of the Sony VL500 camera.
void VW::DrawWeRo (VW::ThreeDToolGLCommon &display, const VW::Vector3D &position, const VW::Quaternion &orientation, const double tilt=0, const double pan=0, const double cyclo=0, const bool origin_at_camera_centre=false)
Draw a model of the WeRo active head.
void VW::DrawYorick811 (VW::ThreeDToolGLCommon &display, const VW::Vector3D &position, const VW::Quaternion &orientation, const double pan=0, const double tilt=0, const double vergeleft=0, const double vergeright=0, const std::string &cameratype="VL500")
Draw a model of the Yorick811 active head.
Detailed Description
Tools for creating and manipulating 3D displays and some draw functions for some physical objects.
Function Documentation
void VW::DrawFireI (VW::ThreeDToolGLCommon & display, const VW::Vector3D & position, const VW::Quaternion & orientation)
Draw a model of the Unibrain Fire-I camera.
Author:
BJ Tordoff
Date:
02/02/2003 Draws a model of the camera with origin at approximately the optic centre of the camera. Assumes that one GL unit is one metre.
Parameters:
display the 3D display on which the object will be drawn.
position the position (relative to the current origin) at which the object will be drawn.
orientation the orientation of the object (default is that the ground lives in the X-Z plane).
References VW::ThreeDToolGLCommon::DrawCone(), VW::ThreeDToolGLCommon::DrawCylinder(), DrawFireICurve(), DrawFireICurveLid(), VW::ThreeDToolGLCommon::PopDrawingPosition(), VW::ThreeDToolGLCommon::PushDrawingPosition(), VW::ThreeDToolGLCommon::RotateDrawingPosition(), VW::ThreeDToolGLCommon::SetPenColour(), and VW::ThreeDToolGLCommon::TranslateDrawingPosition().
void VW::DrawGTI (VW::ThreeDToolGLCommon & display, const VW::Vector3D & position, const VW::Quaternion & orientation)
Draw a model of the GTI mobile robot.
Author:
BJ Tordoff
Date:
02/02/2003 Draws a model of the GTI "mobile" (well, in theory it is) robot. The origin is the position on the floor below the point of attachment of the Yorick8-11 head.
Parameters:
display the 3D display on which the object will be drawn.
position the position (relative to the current origin) at which the object will be drawn.
orientation the orientation of the object (default is that the ground lives in the X-Z plane).
References block_depth, block_width, DrawGTIBlock(), DrawGTIWheel(), VW::ThreeDToolGLCommon::IncludeInRotationCentre(), VW::ThreeDToolGLCommon::PopDrawingPosition(), VW::ThreeDToolGLCommon::PushDrawingPosition(), VW::ThreeDToolGLCommon::RotateDrawingPosition(), VW::ThreeDToolGLCommon::SetPenColour(), VW::ThreeDToolGLCommon::TranslateDrawingPosition(), and wheel_height.
Referenced by VW::DrawGTIWithYorick().
void VW::DrawGTIWithYorick (VW::ThreeDToolGLCommon & display, const VW::Vector3D & position, const VW::Quaternion & orientation, const double yorickpan = 0, const double yoricktilt = 0, const double yorickvergeleft = 0, const double yorickvergeright = 0, const std::string & yorickcameratype = "VL500")
Draw a model of the GTI mobile robot.
Author:
BJ Tordoff
Date:
02/08/02 Draws a model of the GTI "mobile" (well, in theory it is) robot. The origin is the position on the floor below the point of attachment of the Yorick8-11 head.
Parameters:
display the 3D display on which the object will be drawn.
position the position (relative to the current origin) at which the object will be drawn.
orientation the orientation of the object (default is that the ground lives in the X-Z plane).
pan Yorick pan angle (in degrees) -90<pan<90
tilt Yorick tilt angle (in degrees) -60<tilt<60
vergeleft Yorick left vergence angle (in degrees) -90<vergeleft<90
pan Yorick right vergence angle (in degrees) -90<vergeright<90
cameratype the name of the camera to draw on the Yorick platforms, possible values are
VL500
References block_height, VW::DrawGTI(), VW::DrawYorick811(), VW::ThreeDToolGLCommon::PopDrawingPosition(), VW::ThreeDToolGLCommon::PushDrawingPosition(), VW::ThreeDToolGLCommon::RotateDrawingPosition(), VW::ThreeDToolGLCommon::TranslateDrawingPosition(), and wheel_height.
void VW::DrawThreeQuarterDesk (VW::ThreeDToolGLCommon & display, const VW::Vector3D & position, const VW::Quaternion & orientation, bool origin_on_desk = true)
Draw a model of a three-quarter corner desk.
Author:
BJ Tordoff
Date:
06/02/2003 Draws a model of the three-quarter desks we have in the lab. By default the origin is on the desktop, positioned at the (extrapolated) internal corner of the 'L' shape. This can be changed to the corner leg if desired.
Parameters:
display the 3D display on which the object will be drawn.
position the position (relative to the current origin) at which the object will be drawn.
orientation the orientation of the object (default is that the ground lives in the X-Z plane).
origin_on_desk whether to position the desk relative to the centre of the desktop (true) or the corner leg (false).
References DrawThreeQuarterDeskBorder(), DrawThreeQuarterDeskLeg(), DrawThreeQuarterDeskTop(), VW::ThreeDToolGLCommon::IncludeInRotationCentre(), VW::ThreeDToolGLCommon::PopDrawingPosition(), VW::ThreeDToolGLCommon::PushDrawingPosition(), VW::ThreeDToolGLCommon::RotateDrawingPosition(), VW::ThreeDToolGLCommon::SetPenColour(), and VW::ThreeDToolGLCommon::TranslateDrawingPosition().
void VW::DrawVL500 (VW::ThreeDToolGLCommon & display, const VW::Vector3D & position, const VW::Quaternion & orientation, bool origin_is_optic_centre = true)
Draw a model of the Sony VL500 camera.
Author:
BJ Tordoff
Date:
06/02/2003 Draws a model of the camera with origin at approximately the optic centre of the camera. Assumes that one GL unit is one metre.
Parameters:
display the 3D display on which the object will be drawn.
position the position (relative to the current origin) at which the object will be drawn.
orientation the orientation of the object (default is that the ground lives in the X-Z plane).
origin_is_optic_centre if true (the default) then the origin is assumed to lie at the optic centre. If not then the object origin is placed at the screw-mount position.
References VW::ThreeDToolGLCommon::DrawCylinder(), VW::ThreeDToolGLCommon::DrawDisc(), DrawVL500Curve(), DrawVL500Face(), DrawVL500FrontQuadrant(), VW::ThreeDToolGLCommon::PopDrawingPosition(), VW::ThreeDToolGLCommon::PushDrawingPosition(), VW::ThreeDToolGLCommon::RotateDrawingPosition(), VW::ThreeDToolGLCommon::SetPenColour(), and VW::ThreeDToolGLCommon::TranslateDrawingPosition().
Referenced by VW::DrawYorick811().
void VW::DrawWeRo (VW::ThreeDToolGLCommon & display, const VW::Vector3D & position, const VW::Quaternion & orientation, const double tilt = 0, const double pan = 0, const double cyclo = 0, const bool origin_at_camera_centre = false)
Draw a model of the WeRo active head.
Author:
BJ Tordoff
Date:
06/02/2003 Draws a model of WW Mayol's Wearable Robot (WeRo). The robot can be drawn starting from either the ball joint that connects it to the wearer or from the camera (eg. when a vision algorithm estimates the camera pose). All angles in degrees.
Parameters:
display the ThreeDToolGLCommon (or derivative) on which to draw
position 3D position at which to begin drawing
orientation the direction in which Yorick is facing when zeroed
tilt tilt angle (in degrees) -60<tilt<60
pan pan angle (in degrees) -90<pan<90
cyclo cyclo-rotation angle (in degrees) -90<cyclo<90
origin_at_camera_centre if true the robot is drawn start with the camera at the origin, then following the kinematic chain backwards, but otherwise it is drawn from the ball-joint upwards.
References camerabasethick, camerathick, DrawCamera(), DrawMotor(), DrawMotor1Frame(), DrawMotor2Frame(), DrawMotor3Frame(), frame1ballcyllen, frame1ballpos, frame1ballrad, frame1border, frame1depth, frame1width, framethickness, VW::ThreeDToolGLCommon::IncludeInRotationCentre(), motor2Xoffset, motor2Zoffset, motor3Xoffset, motor3Zoffset, motorfaciaradius, motorlength, motorlength1, motorlipthick, motoroffset, motorthick, motorwidth, PCBthick, VW::ThreeDToolGLCommon::PopDrawingPosition(), VW::ThreeDToolGLCommon::PushDrawingPosition(), VW::ThreeDToolGLCommon::RotateDrawingPosition(), and VW::ThreeDToolGLCommon::TranslateDrawingPosition().
void VW::DrawYorick811 (VW::ThreeDToolGLCommon & display, const VW::Vector3D & position, const VW::Quaternion & orientation, const double pan = 0, const double tilt = 0, const double vergeleft = 0, const double vergeright = 0, const std::string & cameratype = "VL500")
Draw a model of the Yorick811 active head.
Author:
BJ Tordoff
Date:
06/02/2003 Draws a model of medium Yorick, adding two Sony VL500's to the platforms. Note that angles are in DEGREES.
Parameters:
display the ThreeDToolGLWidget (or derivative) on which to draw
position 3D position at which to begin drawing
orientation the direction in which Yorick is facing when zeroed
pan pan angle (in degrees) -90<pan<90
tilt tilt angle (in degrees) -60<tilt<60
vergeleft left vergence angle (in degrees) -90<vergeleft<90
pan right vergence angle (in degrees) -90<vergeright<90
cameratype the name of the camera to draw on the platforms, possible * values are
VL500
References VW::ThreeDToolGLCommon::DrawCylinder(), VW::ThreeDToolGLCommon::DrawDisc(), VW::DrawVL500(), VW::ThreeDToolGLCommon::IncludeInRotationCentre(), nameplateheight, nameplaterelief, nameplatewidth, pan_axis_height1, pan_axis_height2, pan_axis_radius1, pan_axis_radius2, pan_motor_height, pan_motor_radius, platform_halfdepth, platform_halfwidth, platform_thickness, VW::ThreeDToolGLCommon::PopDrawingPosition(), VW::ThreeDToolGLCommon::PushDrawingPosition(), VW::ThreeDToolGLCommon::RotateDrawingPosition(), VW::ThreeDToolGLCommon::SetPenColour(), tilt_axis_length1, tilt_axis_length2, tilt_axis_length3, tilt_axis_radius1, tilt_axis_radius2, tilt_axis_radius3, tiltspotposx, tiltspotradius, tiltspotrelief, VW::ThreeDToolGLCommon::TranslateDrawingPosition(), verge_length, verge_motor_length, verge_motor_radius, verge_offset, verge_radius, and vergestem_radius.
Referenced by VW::DrawGTIWithYorick().