VW: imageconversions.cpp File Reference
imageconversions.cpp File Reference
#include <iostream>
#include <cstring>
#include <cstdlib>
#include "imageconversions.h"
Defines
#define VERBOSE false
Functions
template<class T >
void ResizeVWImage (T *image, const int unsigned new_width, const unsigned int new_height)
Define Documentation
#define VERBOSE false
Function Documentation
template<class T > void ResizeVWImage (T * image, const int unsigned new_width, const unsigned int new_height) [inline]
Referenced by VW::ImageConversions::BGRABuffer_to_VWImage(), VW::ImageConversions::Interlaced4Buffer_to_VWImage(), VW::ImageConversions::MonoBuffer_to_VWImage(), VW::ImageConversions::RGBBuffer_to_VWImage(), VW::ImageConversions::YUV411Buffer_to_VWImage(), VW::ImageConversions::YUV422Buffer_to_VWImage(), and VW::ImageConversions::YUV444Buffer_to_VWImage().