VW: Glute2 Namespace Reference
Glute2 Namespace Reference
Classes
class Button
class CheckBox
class Colour
class Container
class Frame
class HBox
class Label
class Slider
class VBox
class Widget
class Window
Functions
void SetPen (const Colour &colour)
Function Documentation
void Glute2::SetPen (const Colour & colour) [inline]
References Glute2::Colour::MakeCurrent().
Referenced by Glute2::Slider::Draw(), Glute2::Label::Draw(), Glute2::Frame::Draw(), Glute2::CheckBox::Draw(), and Glute2::Button::Draw().