VW: VW::FMatrixAffineCompute Namespace Reference
VW::FMatrixAffineCompute Namespace Reference
[GeometricAlgorithms]
Assorted helper functions for computing affine Fundamental Matrices.
Functions
VW::FMatrixAffine Unnormalise (const VW::FMatrixAffine &F, const Normalisation &n0, const Normalisation &n1)
Unnormalise an FMatrixAffine ie.
D5Vector UnnormaliseFVec (const D5Vector &f, const Normalisation &n0, const Normalisation &n1)
Unnormalise a 5-vector which represents the non-zero elements of an affine fmatrix ie.
VW::FMatrixAffineCovariance Unnormalise (const VW::FMatrixAffineCovariance &C, const Normalisation &n0, const Normalisation &n1)
Unnormalise a covariance.
void AddToDesignMatrix (VNL::MatrixFixed< 5, 5, double > &D, const VW::Point2D &x0, const VW::Point2D &x1)
Add a correspondence to a design matrix (as three outer products).
void AddToDesignMatrix (VNL::MatrixFixed< 5, 5, double > &D, const VW::Point2D &x0, const VW::Point2D &x1, const double weight)
Add a weighted correspondence to a design matrix (as three outer products).
void RecoverF (const VNL::SymmetricEigensystem< double > &eig, const Normalisation &n0, const Normalisation &n1, FMatrixAffine &result)
Retrieve from null vector when there is normalisation.
void RecoverF (const VNL::SymmetricEigensystem< double > &eig, FMatrixAffine &result)
Retrieve from null vector assuming no normalisation.
void MakeSymmetric (VNL::MatrixFixed< 5, 5, double > &D)
Copy the upper triangle of a matrix into the lower.
void GUISACCore (VW::FMatrixAffine &result, const std::vector< VW::Point2D > &norm_x0, const std::vector< VW::Point2D > &norm_x1, const std::vector< double > &prior, std::vector< double > &posterior, double desired_confidence, unsigned int max_iters, double image_noise, double search_area)
void MLESACCore (VW::FMatrixAffine &result, const std::vector< VW::Point2D > &norm_x0, const std::vector< VW::Point2D > &norm_x1, std::vector< unsigned int > &inliers, double desired_confidence, unsigned int max_iters, double image_noise, double search_area)
Detailed Description
Assorted helper functions for computing affine Fundamental Matrices.
Author:
BJ Tordoff
Date:
17/04/2005
Function Documentation
void VW::FMatrixAffineCompute::AddToDesignMatrix (VNL::MatrixFixed< 5, 5, double > & D, const VW::Point2D & x0, const VW::Point2D & x1, const double weight) [inline]
Add a weighted correspondence to a design matrix (as three outer products).
Note that only the upper triangle of the symmetric matrix is filled in.
References VW::Point2D::GetX(), and VW::Point2D::GetY().
void VW::FMatrixAffineCompute::AddToDesignMatrix (VNL::MatrixFixed< 5, 5, double > & D, const VW::Point2D & x0, const VW::Point2D & x1) [inline]
Add a correspondence to a design matrix (as three outer products).
Note that only the upper triangle of the symmetric matrix is filled in.
References VW::Point2D::GetX(), and VW::Point2D::GetY().
void VW::FMatrixAffineCompute::GUISACCore (VW::FMatrixAffine & result, const std::vector< VW::Point2D > & norm_x0, const std::vector< VW::Point2D > & norm_x1, const std::vector< double > & prior, std::vector< double > & posterior, double desired_confidence, unsigned int max_iters, double image_noise, double search_area)
References VW::AccumulateWeights(), VW::FMatrixAffineComputeLinear::Compute(), VW::FMatrixAffineComputeLinear::ComputeWeighted(), VW::SeedRand(), VERBOSE, and VW::WeightedSample().
Referenced by VW::Homography2DComputeGUISAC::Compute(), and VW::FMatrixAffineComputeGUISAC::Compute().
void VW::FMatrixAffineCompute::MakeSymmetric (VNL::MatrixFixed< 5, 5, double > & D) [inline]
Copy the upper triangle of a matrix into the lower.
void VW::FMatrixAffineCompute::MLESACCore (VW::FMatrixAffine & result, const std::vector< VW::Point2D > & norm_x0, const std::vector< VW::Point2D > & norm_x1, std::vector< unsigned int > & inliers, double desired_confidence, unsigned int max_iters, double image_noise, double search_area)
References VW::FMatrixAffineComputeLinear::Compute(), VW::RandomSample(), VW::SeedRand(), and VERBOSE.
Referenced by VW::FMatrixAffineComputeMLESAC::Compute().
void VW::FMatrixAffineCompute::RecoverF (const VNL::SymmetricEigensystem< double > & eig, VW::FMatrixAffine & result) [inline]
Retrieve from null vector assuming no normalisation.
References VNL::SymmetricEigensystem< T >::Nullvector(), VW::FMatrixAffine::Set(), and VNL::SymmetricEigensystem< T >::V.
void VW::FMatrixAffineCompute::RecoverF (const VNL::SymmetricEigensystem< double > & eig, const Normalisation & n0, const Normalisation & n1, VW::FMatrixAffine & result) [inline]
Retrieve from null vector when there is normalisation.
References VNL::SymmetricEigensystem< T >::Nullvector(), VW::FMatrixAffine::Set(), Unnormalise(), and VNL::SymmetricEigensystem< T >::V.
Referenced by VW::FMatrixComputeLinear::Compute(), VW::FMatrixAffineComputeLinear::Compute(), VW::FMatrixComputeLinear::ComputeWeighted(), and VW::FMatrixAffineComputeLinear::ComputeWeighted().
VW::FMatrixAffineCovariance VW::FMatrixAffineCompute::Unnormalise (const VW::FMatrixAffineCovariance & C, const Normalisation & n0, const Normalisation & n1) [inline]
Unnormalise a covariance.
References VW::Normalisation::GetCentreX(), VW::Normalisation::GetCentreY(), VW::Normalisation::GetScale(), and VNL::Matrix< T >::Transpose().
VW::FMatrixAffine VW::FMatrixAffineCompute::Unnormalise (const VW::FMatrixAffine & F, const Normalisation & n0, const Normalisation & n1) [inline]
Unnormalise an FMatrixAffine ie.
F = n1'*Fn*n0 (hand optimised to 12 flops - matrix mult would be 90)
References c, VW::FMatrixAffine::GetA(), VW::FMatrixAffine::GetB(), VW::FMatrixAffine::GetC(), VW::Normalisation::GetCentreX(), VW::Normalisation::GetCentreY(), VW::FMatrixAffine::GetD(), VW::FMatrixAffine::GetE(), and VW::Normalisation::GetScale().
Referenced by RecoverF().
D5Vector VW::FMatrixAffineCompute::UnnormaliseFVec (const D5Vector & f, const Normalisation & n0, const Normalisation & n1) [inline]
Unnormalise a 5-vector which represents the non-zero elements of an affine fmatrix ie.
F = n1'*Fn*n0
References VW::Normalisation::GetCentreX(), VW::Normalisation::GetCentreY(), and VW::Normalisation::GetScale().