VW: VW::EssentialMatrixCompute Namespace Reference
VW::EssentialMatrixCompute Namespace Reference
[GeometricAlgorithms]
Assorted helper functions for computing Essential Matrices.
Functions
VW::EssentialMatrix Unnormalise (const VW::EssentialMatrix &E, const Normalisation &n0, const Normalisation &n1)
Unnormalise an EssentialMatrix ie.
D9Vector UnnormaliseEVec (const D9Vector &f, const Normalisation &n0, const Normalisation &n1)
Unnormalise a 9-vector as though it were a 3x3 matrix ie.
void AddToDesignMatrix (VNL::MatrixFixed< 9, 9, double > &D, const VW::Point2D &x0, const VW::Point2D &x1)
Add a correspondence to a design matrix (as three outer products).
void AddToDesignMatrix (VNL::MatrixFixed< 9, 9, double > &D, const VW::Point2D &x0, const VW::Point2D &x1, const double weight)
Add a weighted correspondence to a design matrix (as three outer products).
void RecoverE (const VNL::SymmetricEigensystem< double > &eig, const Normalisation &n0, const Normalisation &n1, EssentialMatrix &result)
Retrieve from null vector when there is normalisation.
void RecoverE (const VNL::SymmetricEigensystem< double > &eig, EssentialMatrix &result)
Retrieve from null vector assuming no normalisation.
void MakeSymmetric (VNL::MatrixFixed< 9, 9, double > &D)
Copy the upper triangle of a matrix into the lower.
Detailed Description
Assorted helper functions for computing Essential Matrices.
Author:
BJ Tordoff
Date:
19/04/2005
Function Documentation
void VW::EssentialMatrixCompute::AddToDesignMatrix (VNL::MatrixFixed< 9, 9, double > & D, const VW::Point2D & x0, const VW::Point2D & x1, const double weight) [inline]
Add a weighted correspondence to a design matrix (as three outer products).
Note that only the upper triangle of the symmetric matrix is filled in.
References VW::Point2D::GetX(), and VW::Point2D::GetY().
void VW::EssentialMatrixCompute::AddToDesignMatrix (VNL::MatrixFixed< 9, 9, double > & D, const VW::Point2D & x0, const VW::Point2D & x1) [inline]
Add a correspondence to a design matrix (as three outer products).
Note that only the upper triangle of the symmetric matrix is filled in.
References VW::Point2D::GetX(), and VW::Point2D::GetY().
Referenced by VW::FMatrixComputeLinear::Compute(), VW::FMatrixAffineComputeLinear::Compute(), VW::EssentialMatrixComputeLinear::Compute(), VW::EssentialMatrixCompute5Point::Compute(), VW::FMatrixComputeLinear::ComputeWeighted(), VW::FMatrixAffineComputeLinear::ComputeWeighted(), and VW::EssentialMatrixComputeLinear::ComputeWeighted().
void VW::EssentialMatrixCompute::MakeSymmetric (VNL::MatrixFixed< 9, 9, double > & D) [inline]
Copy the upper triangle of a matrix into the lower.
Referenced by VW::Homography2DComputeLinear::Compute(), VW::FMatrixComputeLinear::Compute(), VW::FMatrixAffineComputeLinear::Compute(), VW::EssentialMatrixComputeLinear::Compute(), VW::Homography2DComputeLinear::ComputeWeighted(), VW::FMatrixComputeLinear::ComputeWeighted(), VW::FMatrixAffineComputeLinear::ComputeWeighted(), and VW::EssentialMatrixComputeLinear::ComputeWeighted().
void VW::EssentialMatrixCompute::RecoverE (const VNL::SymmetricEigensystem< double > & eig, VW::EssentialMatrix & result) [inline]
Retrieve from null vector assuming no normalisation.
References VW::EssentialMatrix::Constrain(), VNL::SymmetricEigensystem< T >::Nullvector(), and VNL::SymmetricEigensystem< T >::V.
void VW::EssentialMatrixCompute::RecoverE (const VNL::SymmetricEigensystem< double > & eig, const Normalisation & n0, const Normalisation & n1, VW::EssentialMatrix & result) [inline]
Retrieve from null vector when there is normalisation.
References VW::EssentialMatrix::Constrain(), VNL::SymmetricEigensystem< T >::Nullvector(), Unnormalise(), and VNL::SymmetricEigensystem< T >::V.
Referenced by VW::EssentialMatrixComputeLinear::Compute(), and VW::EssentialMatrixComputeLinear::ComputeWeighted().
VW::EssentialMatrix VW::EssentialMatrixCompute::Unnormalise (const VW::EssentialMatrix & E, const Normalisation & n0, const Normalisation & n1) [inline]
Unnormalise an EssentialMatrix ie.
E = n1'*En*n0 (hand optimised to 35 flops - matrix mult would be 90)
References VW::Normalisation::GetCentreX(), VW::Normalisation::GetCentreY(), and VW::Normalisation::GetScale().
Referenced by VW::Homography2DComputeLinear::Compute(), VW::FMatrixComputeLinear::Compute(), VW::FMatrixAffineComputePreemptive::Compute(), VW::FMatrixAffineComputeLinear::Compute(), VW::EssentialMatrixComputePreemptive::Compute(), and RecoverE().
D9Vector VW::EssentialMatrixCompute::UnnormaliseEVec (const D9Vector & f, const Normalisation & n0, const Normalisation & n1)
Unnormalise a 9-vector as though it were a 3x3 matrix ie.
E = n1'*En*n0 (hand optimised to 35 flops - matrix mult would be 90)