VW: VW::ComputeFuncs Namespace Reference
VW::ComputeFuncs Namespace Reference
Functions that are common to the computation routines.
Functions
template<class T >
void ConvertTransformToParamVector (const T &transform, VNL::Vector< double > &x)
Convert a transform class into a parameter vector.
template<class T >
void ConvertParamVectorToTransform (const VNL::Vector< double > &x, T &transform)
Convert a parameter vector into a transform class.
Detailed Description
Functions that are common to the computation routines.
Function Documentation
template<class T > void VW::ComputeFuncs::ConvertParamVectorToTransform (const VNL::Vector< double > & x, T & transform) [inline]
Convert a parameter vector into a transform class.
References VNL::Matrix< T >::CopyIn(), VNL::Vector< T >::CopyOut(), VNL::Matrix< T >::FrobeniusNorm(), VNL::Matrix< T >::size(), and VNL::Vector< T >::size().
Referenced by VW::Homography2DComputeNonLinear::Compute(), and VW::Homography2DCompute::LeastSquaresFunctionPoints::F().
template<class T > void VW::ComputeFuncs::ConvertTransformToParamVector (const T & transform, VNL::Vector< double > & x) [inline]
Convert a transform class into a parameter vector.
References VNL::Vector< T >::CopyIn(), VNL::Matrix< T >::CopyOut(), VNL::Matrix< T >::FrobeniusNorm(), and VNL::Matrix< T >::size().
Referenced by VW::Homography2DComputeNonLinear::Compute().