VW: channel.h File Reference
TransputerCode/channel.h File Reference
Typedefs
typedef int Chan
Functions
int ChanInInt (Chan chan)
void ChanOutInt (Chan chan, int i)
char ChanInChar (Chan chan)
void ChanOutChar (Chan chan, char c)
void ChanIn (Chan chan, char *buf, int count)
void ChanOut (Chan chan, char *buf, int count)
int ChanInMsg (Chan chan, char *buf)
void ChanOutMsg (Chan chan, char *buf, int len)
Typedef Documentation
typedef int Chan
Function Documentation
void ChanIn (Chan chan, char * buf, int count)
char ChanInChar (Chan chan)
Referenced by VW::GTI::Drive(), and VW::GTI::Rotate().
int ChanInInt (Chan chan)
int ChanInMsg (Chan chan, char * buf)
Referenced by VW::GTI::GetDriveOdometry(), VW::GTI::SetSteeringAngle(), and VW::GTI::SetVelocity().
void ChanOut (Chan chan, char * buf, int count)
Referenced by VW::GTI::Drive(), VW::GTI::Rotate(), VW::GTI::SetSteeringAngle(), and VW::GTI::SetVelocity().
void ChanOutChar (Chan chan, char c)
Referenced by VW::GTI::Drive(), VW::GTI::GetDriveOdometry(), VW::GTI::Rotate(), VW::GTI::SetSteeringAngle(), and VW::GTI::SetVelocity().
void ChanOutInt (Chan chan, int i)
void ChanOutMsg (Chan chan, char * buf, int len)